### ISSUE TITLE
Some yarn packages were not imported

### ISSUE THREAD

**Issue by HolyWalley** [rails/webpacker#1001]
I created a question on the stackoverflow but can't received an answer in 2 weeks. so i need a help

https://stackoverflow.com/questions/46917082/datetimepicker-is-not-a-function-rails-webpacker

**Comment by gauravtiwari** [comment]
Please make sure you are importing packages correctly, 

```js
import * as jQuery from 'jquery'
// or
import 'jquery'
import 'some-date-picker'
// etc
```
docs: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import
