### ISSUE TITLE
gzip assets not being decoded in the browser

### ISSUE THREAD

**Issue by steverob** [rails/webpacker#1005]
After pre-compiling for production, webpack has generated regular and gzipped assets for me.
But then the browser does not seem to be inflating the gzipped assets and it's trying to evaluate it as it is leading to JavaScript sytax errors.

![2017-11-09_15-43-55_scrot](https://user-images.githubusercontent.com/1220480/32600189-ce688c2e-c564-11e7-8796-17aeae4906ab.png)

This is what I see in the network console when I open the asset.

Response headers: 

```
Accept-Ranges:bytes
Connection:close
Content-Encoding:gzip
Content-Type:text/javascript
Date:Thu, 09 Nov 2017 10:13:43 GMT
ETag:"80681f-18880-55d89c1dde200"
Last-Modified:Thu, 09 Nov 2017 09:52:08 GMT
Server:Apache/2.2.22 (Ubuntu)
Transfer-Encoding:chunked
Vary:Accept-Encoding,User-Agent
```

If I go and delete the gzipped files, then apache serves the regular `.js` files and it all works well. Do I need to do anything more to get gzipped assets working?

I'm using Chrome btw. With the default webpacker settings (react_on_rails)

**Comment by gauravtiwari** [comment]
@steverob Guess you would need to enable gzip for apache or could be configuration issue in apache config http://httpd.apache.org/docs/current/mod/mod_deflate.html
