### ISSUE TITLE
webpack://

### ISSUE THREAD

**Issue by Seaborg** [rails/webpacker#1007]
Hi,

It's more of a question than an issue, why do I see in the browser's inspector (production environment) `webpack://` including `/node_modules` even though it looks like files appear empty...?

Here is my webpacker.yml:

```
# Note: You must restart bin/webpack-dev-server for changes to take effect
default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_output_path: packs
  cache_path: tmp/cache/webpacker

  # Additional paths webpack should lookup modules
  # ['app/assets', 'engine/foo/app/assets']
  resolved_paths: ['app/assets']

  # Reload manifest.json on all requests so we reload latest compiled packs
  cache_manifest: false

  extensions:
    - .coffee
    - .erb
    - .js
    - .jsx
    - .ts
    - .vue
    - .sass
    - .scss
    - .css
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg


production:
  <<: *default

  # Production depends on precompilation of packs prior to booting for performance.
  compile: false

  # Cache manifest.json for performance
  cache_manifest: true

```

**Comment by gauravtiwari** [comment]
Not sure I understand. Could you post a screenshot please?

**Comment by Seaborg** [comment]
![issue](https://user-images.githubusercontent.com/509290/32659001-79db4024-c614-11e7-9044-d06d05715657.png)

**Comment by gauravtiwari** [comment]
We use `nosources-source-map`: https://webpack.js.org/configuration/devtool/#production so it doesn't leak your original code.

> It still exposes filenames and structure for decompiling, but it doesn't expose the original code.
