### ISSUE TITLE
React is not defined console error

### ISSUE THREAD

**Issue by interpegasus** [rails/webpacker#1008]
Hello, 
I have installed 'webpacker' (react version), into an existing rails 5 app that was working with React before.

However the React functionality stopped working. JSX components are not found.

1. I would like to know how to solved the following error in the js console: _Uncaught ReferenceError: React is not defined_

2. And also I would like to know how to configure webpacker with the path to find React components: /app/assets/javascript/components/

Thank you in advance : )

**application.js**
```
//= require rails-ujs
//= require turbolinks
//= require axios
//= require react
//= require react_ujs
//= require components
//= require_tree .
//= require foundation
//= require datetimepicker
//= require libphonenumber/utils
//= require intlTelInput
$(document).foundation();
```
**Gemfile**
```
gem 'rails', '~> 5.1.4'
...
...
gem "react-rails"
gem 'webpacker', git: 'https://github.com/rails/webpacker.git'
```

**Comment by gauravtiwari** [comment]
Webpack works differently that asset pipeline. Please see this example repo: https://github.com/gauravtiwari/webpacker-react-frontend or https://github.com/gauravtiwari/webpacker-example-app

react-rails have documentation here: https://github.com/reactjs/react-rails#get-started-with-webpacker
