### ISSUE TITLE
Error while running `rails webpacker:install`

### ISSUE THREAD

**Issue by thbar** [rails/webpacker#1009]
I'm starting to migrate an existing app (Rails 5.1, ruby 2.3.4, using RVM) to webpacker.

When running the install, I got the following error:

```
$ bundle exec rails webpacker:install
https://github.com/modeset/teaspoon (at master@c9b4f46) is not yet checked out. Run `bundle install` first.
```

This happens despite the fact that `bundle install` was already run previously.

I debugged what is happening, and ended up [here](https://github.com/rails/webpacker/blob/master/lib/tasks/webpacker/install.rake#L7).

I printed the exec line on screen, and got:

```
/Users/thbar/.rvm/rubies/ruby-2.3.4/bin/ruby ./bin/rails app:template LOCATION=/Users/thbar/.rvm/gems/ruby-2.3.4@REDACTED/gems/webpacker-3.0.2/lib/install/template.rb
```

Then I executed that exact line myself directly, and it worked out fine.

I'm not sure if there's an issue with my `./bin/rails`, or an interaction with bundler or RVM, at this point.

**Comment by thbar** [comment]
FWIW, this specific app seems to have old `bin/*`, so it could be linked to that. Unsure at this point.

**Comment by gauravtiwari** [comment]
Please try running: 

```bash
bundle pack
bundle install --path vendor/cache
```
