### ISSUE TITLE
How to generate CSS without hash in filenames

### ISSUE THREAD

**Issue by yizeng** [rails/webpacker#1010]
Just need some help with this. Much appreciated.

After [webpacker PR #653][2], all assets have hashes in the filenames now., but I'd like to find out how to generate JS and CSS without hash in the filename in the test environment.

For JS, I managed to get it working by:

    // config/webpack/test.js
    const merge = require('webpack-merge')
    const environment = require('./environment')
    
    const customConfig = {
        output: {
            filename: '[name].bundle.js'
        }
    };
    
    module.exports = merge(environment.toWebpackConfig(), customConfig)

For CSS, if it's webpack, I think it can be done by (I might be wrong here):

    // webpack.config.js
    var ExtractTextPlugin = require("extract-text-webpack-plugin");
    module.exports = {
        // The standard entry point and output config
        entry: {
            posts: "./posts",
            post: "./post",
            about: "./about"
        },
        output: {
            filename: "[name].bundle.js"
        },
        module: {
            loaders: [
                {
                    test: /\.css$/,
                    loader: ExtractTextPlugin.extract("style-loader", "css-loader")
                }
            ]
        },
        plugins: [
            new ExtractTextPlugin("[name].bundle.css")
        ]
    }

However, I'm not sure how to achieve it with webpacker gem. Couldn't quite understand the [doc here][3].

  [1]: https://github.com/rails/webpacker
  [2]: https://github.com/rails/webpacker/pull/653
  [3]: https://github.com/rails/webpacker/blob/master/docs/webpack.md

**Comment by gauravtiwari** [comment]
This should do the trick: 

```js
// test.js
const extractText = environment.plugins.get('ExtractText')
extractText.filename = '[name].js'
```
