### ISSUE TITLE
Compiling extremally slow and freezing OS

### ISSUE THREAD

**Issue by esl-douglas** [rails/webpacker#1018]
When I run rake webpacker:clobber and open any page, webpacker starts to compile. And keeps compiling for 10, 20, 30 minutes until it freezes my OS and I have to restart the PC. I'm using coffeescript and erb.

Shouldn't webpacker work like Sprockets and only compile files for production? Why compile in development environment?

**Comment by gauravtiwari** [comment]
@esl-douglas Why you are running? ` rake:webpacker:clobber`. Could you please post more information - step by step?

**Comment by esl-douglas** [comment]
I'm running clobber just to test the entire compilation from zero. But even when I don't run it, and just change something on one file, the compilation process is taking all my RAM and freezing the OS.

**Comment by gauravtiwari** [comment]
@esl-douglas Probably seems like a misconfiguration, I can't seem to reproduce it. It's hard to find out the cause without more details.
