### ISSUE TITLE
conflict over `bin/yarn` when generating a new Rails app with webpacker

### ISSUE THREAD

**Issue by claudiob** [rails/webpacker#102]
If I try to generate a brand new Rails app with the current master (8de6807) and the command:

```sh
~/code/rails$ railties/exe/rails new myapp --webpack=react --edge
```

then I get the following conflict on the file `bin/yarn`:

```sh
      create  
      create  README.md
      [...]
      create  bin/webpack
    conflict  bin/yarn
Overwrite /Users/claudiob/code/rails/myapp/bin/yarn? (enter "h" for help) [Ynaqdh]
```

The diff in the conflict is as follows:

```diff
-VENDOR_PATH = File.expand_path('..', __dir__)
-Dir.chdir(VENDOR_PATH) do
+YARN_ROOT = File.expand_path('../', __dir__)
+Dir.chdir(YARN_ROOT) do
```

The conflict arises becuase, when generating a new Rails app:

- rails tries to add bin/yarn [from this code](https://github.com/rails/rails/blob/master/railties/lib/rails/generators/rails/app/templates/bin/yarn)
- webpacker tries to add bin/yarn [from this code](https://github.com/rails/webpacker/blob/master/lib/install/bin/yarn.tt)

and the two files are different.

**Comment by claudiob** [comment]
I think this is the result of https://github.com/rails/webpacker/pull/84 @dleavitt which then resulted in https://github.com/rails/rails/pull/28093 by @dhh

**Comment by dhh** [comment]
We should make the one in webpacker match the one in Rails.
