### ISSUE TITLE
Heroku Build is passing even if Webpack compilation failed.

### ISSUE THREAD

**Issue by gandhi-jay** [rails/webpacker#1029]
Hey, 

I'm deploying Rails 5.0 app with Webpacker 3.0. When i do git push for build, 

> remote:        Webpacker is installed 🎉 🍰
remote:        Using /tmp/build_1deb11e370c08943030e13686a654476/config/webpacker.yml file for setting up webpack paths
remote:        Compiling…
remote:        Compilation failed:
remote:        yarn run v0.28.4
remote:        $ "/tmp/build_1deb11e370c08943030e13686a654476/node_modules/.bin/webpack" "--config" "/tmp/build_1deb11e370c08943030e13686a654476/config/webpack/production.js"
remote:        Warning: postcss-cssnext found a duplicate plugin ('autoprefixer') in your postcss plugins. This might be inefficient. You should remove 'autoprefixer' from your postcss plugin list since it's already included by postcss-cssnext.
remote:        Note: If, for a really specific reason, postcss-cssnext warnings are irrelevant for your use case, and you really know what you are doing, you can disable this warnings by setting  'warnForDuplicates' option of postcss-cssnext to 'false'.
remote:        <--- Last few GCs --->
remote:        843653 ms: Mark-sweep 1095.7 (1434.8) -> 1089.6 (1434.8) MB, 1044.1 / 0.0 ms [allocation failure] [GC in old space requested].
remote:        844673 ms: Mark-sweep 1089.6 (1434.8) -> 1089.4 (1434.8) MB, 1019.5 / 0.0 ms [allocation failure] [GC in old space requested].
remote:        845741 ms: Mark-sweep 1089.4 (1434.8) -> 1107.3 (1404.8) MB, 1068.5 / 0.0 ms [last resort gc].
remote:        846838 ms: Mark-sweep 1107.3 (1404.8) -> 1125.5 (1404.8) MB, 1096.6 / 0.0 ms [last resort gc].
remote:        <--- JS stacktrace --->
remote:        ==== JS stack trace =========================================
remote:        Security context: 0x81067e3fa99 <JS Object>
remote:        2: add(aka MappingList_add) [/tmp/build_1deb11e370c08943030e13686a654476/node_modules/source-map/lib/mapping-list.js:55] [pc=0x7772ce55d6d] (this=0x215b92a28051 <a MappingList with map 0x10e9d726ba31>,aMapping=0x2732b42dca59 <an Object with map 0xf3e988eb781>)
remote:        3: addMapping(aka SourceMapGenerator_addMapping) [/tmp/build_1deb11e370c08943030e13686a654476/node_modules/source-map/lib/source-...
remote:        info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
remote:        warning package.json: No license field
remote:        FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
remote:        1: node::Abort() [node]
remote:        2: 0x109cafc [node]
remote:        3: v8::Utils::ReportApiFailure(char const*, char const*) [node]
remote:        4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
remote:        5: v8::internal::Factory::NewUninitializedFixedArray(int) [node]
remote:        6: 0xc4bc93 [node]
remote:        7: 0x9eb29d [node]
remote:        8: v8::internal::Runtime_ArrayPush(int, v8::internal::Object**, v8::internal::Isolate*) [node]
remote:        9: 0x777241062bf
remote:        Aborted
remote:        error Command failed with exit code 134.
remote:        Asset precompilation completed (1127.81s)
remote:        Cleaning assets
remote:        Running: rake assets:clean

I've fixed memory issue, but asset precompilation is getting successful even if webpack is failing.

Some more info,
Rails - 5.0
React - 15.6
Webpack - 2.6

We're not using @rails/webpacker.

**Comment by TigerWolf** [comment]
Im having the same issue on Red hat, if memory runs out webpacker fails but capistrano deploy still continues without error. We have fixed the memory issue so I will have to manufacture a test case to replicate if that will help.
