### ISSUE TITLE
issue with 404 fallback while trying open web page - reactJS

### ISSUE THREAD

**Issue by mrpatel15** [rails/webpacker#1031]
> webpack-dev-server --inline --content-base ./ --env.dev

Project is running at http://localhost:8080/
webpack output is served from /build/
Content not from webpack is served from
404s will fallback to /index.html
Hash: d3f68b6fdfee6c8b0dd4
Version: webpack 3.8.1
Time: 3889ms

**Comment by gauravtiwari** [comment]
Could you please share more information? Are you running the dev server using binstub? `./bin/webpack-dev-server`

**Comment by gauravtiwari** [comment]
Great 👍

**Comment by arslansarfraz** [comment]
Hello @mrpatel15 could you please tell me how can I fix this
