### ISSUE TITLE
webpacker installation issue

### ISSUE THREAD

**Issue by prasanthrubyist** [rails/webpacker#1041]
rails webpacker:install

Ubuntu 14.04
webpacker (3.0.2)
Rails 5.1.4
Ruby 2.3.1p112

I'm getting below errors:

> Webpacker requires Node.js >= 6.0.0 and you are using 0.10.25
> Please upgrade Node.js https://nodejs.org/en/download/

 Webpack needs nodejs ?

I also tried to installed Nodejs, After getting Yarn comparability  issues,

Please provide appropriate  steps to install webpack
I'm trying to use rails webpacker:install:vue

**Comment by prasanthrubyist** [comment]
Sorry, After properly installed Nodejs and Yarn, it's  installed correctly

**Comment by gauravtiwari** [comment]
Great 👍 

Yes, the error basically means to install a node version > 6.0.0

**Comment by mathieujobin** [comment]
in case someone run here with a similar error in the future
I am on ubuntu 19.04 with node 10.15 and nothing works...
```
 (master) $ rails webpacker:install 
rails aborted!
ArgumentError: Malformed version number string 0.32+git
bin/rails:4:in `<main>'
Tasks: TOP => webpacker:install => webpacker:check_yarn
(See full trace by running task with --trace)
```
