### ISSUE TITLE
Stylesheet Pack Tag (scss support)

### ISSUE THREAD

**Issue by klapouchy** [rails/webpacker#1043]
Does webpacker support `.scss` (not `.sass`) styles outside of `.js`?

What I would like to do is to create `.scss` pack that can be loaded using  `<%= stylesheet_pack_tag 'styles' %>`

**Comment by renchap** [comment]
You need to import your SCSS file in a JS pack. For example, if you add `import from "styles/application.scss"` to your `packs/applications.js` then an `application.css` file will be generated from `app/client/styles/application.scss`

**Comment by gauravtiwari** [comment]
@klapouchy If you don't want to import it via a js file then place your `.scss` or `.sass` file inside `packs` directory and it can be loaded like so: `<%= stylesheet_pack_tag 'styles' %>`

Although, we don't recommend it.

**Comment by klapouchy** [comment]
@renchap I wasn't able to get `import from (styles/application.scss)` to work. Instead only `require('./application.scss')` allowed for the bundle to be compiled successfully.
