### ISSUE TITLE
window.autoInit in Rails using material-components-web and webpacker

### ISSUE THREAD

**Issue by whatsthebeef** [rails/webpacker#1044]
I'm using Rails 5.1.4 with the code below. I have confirmed that the material.js file is being processed and the material-components-web module is downloaded and discovered.

Why is mdc undefined when calling `window.mdc.autoInit()`?

    // app/javascript/packs/material.js
    import 'material-components-web'

    // app/views/layouts/application.html.eeb
    <html>
      <head>
        <%= javascript_pack_tag 'material' %>
      </head>
      <body>
        <script>window.mdc.autoInit();</script>
      </body>
    </html>

I have tried

- importing @material/auto-init separately.
- Putting the `autoInit` call inside an onload
- Adding a `console.dir(window)`/`console.dir(this)` inside pack file. this is not window inside the the pack file and the exports aren't being attached to this

**Comment by gauravtiwari** [comment]
ES6 imports works differently, try: 

```
// material.js
import mdc from 'material-components-web'
// for accessing is as a window object
window.mdc = mdc

// Or do this inside component
document.addEventListener('DOMContentLoader', () => mdc.autoInit())
```

**Comment by whatsthebeef** [comment]
@gauravtiwari Thanks, you nailed it.

In the unlikely event someone gets stuck at the same point as me, to make 'material-components-web' work with Rails I did

    // material.js
    import * as mdc from 'material-components-web'
    // for accessing is as a window object
    window.mdc = mdc

And then I made sure `window.mdc.autoInit()` was called at the end of the body

**Comment by gauravtiwari** [comment]
Great 👍 

Ideally, you would like to contain all logic inside the component, unless you need to anything outside of it. 

```js
// .... rest of the component code
// this should initialise mdc after DOM is loaded
document.addEventListener('DOMContentLoaded', () => mdc.autoInit())
```

and then all you need is: 

```html
<head>
  <%= javascript_pack_tag 'material' %>
</head>
```
