### ISSUE TITLE
can't install webpacker : ruby-2.4.1/bin/ruby: No such file or directory

### ISSUE THREAD

**Issue by regiomag** [rails/webpacker#1050]
Hi, 
I am trying to install webpacker on my 4.2.8 rails app (ruby 2.4.1, installed with RVM).

When I do run: bundle exec rake webpacker:install 

I am getting the following error 
/.rvm/rubies/ruby-2.4.1/bin/ruby: No such file or directory -- ./bin/rake (LoadError)

Any clue on what could be wrong ? 

Thank you for your support

**Comment by gauravtiwari** [comment]
Could you please run `bundle install --binstubs` or `bundle binstubs rake` and then try same command?

**Comment by gauravtiwari** [comment]
Looks like rake binstub isn't there.

**Comment by regiomag** [comment]
Hello, I did run : bundle install --binstubs 
and could install the webpacker.

Thank you very much. I have been stucked on this for a while and could not find any help on google. 

Have a nice day

**Comment by gauravtiwari** [comment]
Awesome 👍

**Comment by chasestory** [comment]
same to the above... Any response?
