### ISSUE TITLE
Adding webpacker to existing project breaks the application

### ISSUE THREAD

**Issue by 3buson** [rails/webpacker#1054]
Hi, I'm trying to add webpacker to an existing rails 5.1 application.
I don't have anything non-standard at the moment.
I'm running ruby 2.4 and rails 5.1 and am using turbolinks.
The application has a few `.js` files in `app/assets/javascripts`, a few `.scss` files in `app/assets/stylesheets` and some images organized in subfolders in `app/assets/images`.

I'm including the javascript with `javascript_include_tag` (`application.js` just requires all the files in the directory), stylesheets with `stylesheet_link_tag` (`application.scss` just requires all the files in the directory) and all the images in html.erb templates with `image_tag`.

I added webpacker gem to Gemfile, ran `bundle install` and `rails webpacker:install`. Once I do this the app returns 500 upon every request. The issue is that the images that are loaded with `image_tag` are no longer found. I get the error pasted below. I tried commenting out the images but then the problem is with the `javascript_include_tag` with the same error.

```
ActionView::Template::Error (File to import not found or unreadable: outside. 
Load paths:
...
```

What did I do wrong? Shouldn't the existing images from `app/assets/images` loaded with `image_tag` still be working? And same for `javascript_include_tag`...

**Comment by gauravtiwari** [comment]
@3buson Strange! What are you using `javascript_include_tag` tag for - loading sprockets css and js? Are you trying to load webpacker assets with `javascript_include_tag`?

**Comment by 3buson** [comment]
@gauravtiwari yes, the `javascript_include_tag` is for loading regular js. And then `stylesheet_link_tag` for including the whole css.
I'm not even including the webpacker related stuff anywhere. The things start failing the moment I run `rails webpacker:install` (without any manual changes in the code).

**Comment by gauravtiwari** [comment]
Right I see. What happens if you remove webpacker gem from your Gemfile?

**Comment by gauravtiwari** [comment]
Also, are you importing css from node_modules to sprockets (application.css) or something?

**Comment by 3buson** [comment]
So if I add webpacker gem to working application, run `bundle install` and `rails webpacker:install` the app breaks. It is unable to find images with the error I pasted in the initial post.
If I remove webpacker gem and rerun `bundle install` nothing changes. The error is still the same.

I'm not sure I understand what you mean by 'importing css from node_modules to sprockets'.

**Comment by gauravtiwari** [comment]
> If I remove webpacker gem and rerun bundle install nothing changes. The error is still the same.

That's what I wanted to know. So, it seems that the problem is something else since the application breaks even when webpacker isn't installed. The installer doesn't add anything except a bunch of JS config files, which shouldn't break sprockets. 

```
ActionView::Template::Error (File to import not found or unreadable: outside. 
Load paths:
```

The error basically means you are trying to import something in your `application.css` that is unreachable (file not found). Could you please your application.css and see if there is anything that's causing this problem?

**Comment by 3buson** [comment]
Ok, I understand. But this error is not happening when including css. It happens on the first appearance of `image_tag`. It looks that somehow, after installing webpacker gem and running `rails webpacker:install`, something regarding the assets changes. And that is causing the error to occur on the first occurrence of including any of the assets.
Do you have any ideas what I could try to overcome this?

**Comment by gauravtiwari** [comment]
@3buson I am not sure really. I would try to revert some of the changes to a working state and then reapply them step by step to see where exactly this error crops up. With git you can checkout to a new branch and then try to fix this in another branch.

**Comment by 3buson** [comment]
@gauravtiwari it looks like removing or just renaming the `node_modules` folder does the trick. Any ideas what would be the cause of that? If not it might be the best to figure out which part of `node_modules` folder is causing the issues right?

**Comment by gauravtiwari** [comment]
So it seems like probably sprockets is trying to find something in node_modules folder. Does commenting out application.css helps (just give it a try)?

**Comment by 3buson** [comment]
I tried removing the `stylesheet_link_tag` and also clearing out the contents of `application.scss` but the error is still the same - fails on first occurrence of `image_tag`.

**Comment by 3buson** [comment]
Hm, so I found this line in `config/initializers/assets.rb` - `Rails.application.config.assets.paths << Rails.root.join('node_modules')`.
Removing this solves the issue. But this is a standard rails 5 app assets initializer, I did not add this. Does anybody have the explanation? We can close this one since it is solved.

**Comment by gauravtiwari** [comment]
cc // @guilleiguaran

**Comment by guilleiguaran** [comment]
can this be reproduced in a new 5.1 app?

I've updated an existing 5.1 app to use webpacker as described in the initial post and I didn't had any problem related to `image_tag`

**Comment by 3buson** [comment]
@guilleiguaran will try to get to the bottom of this over the weekend.

**Comment by simoniong** [comment]
I have the same issue right now, but don't know how to reproduce it, I am using Sprockets 3, but all javascript & stylesheets is using stylesheet_pack_include & javascript_pack_include, only Sprocket part, is using `image_tag` to reference images under `app/assets/images`

the errors point to the location of image_tag, and got this:

```
ActionView::Template::Error (SyntaxError: [stdin]:18:40: unexpected identifier):
            .box-content.text-center
              =image_tag "themes/#{theme_name}.png", class: 'img-responsive'
```
