### ISSUE TITLE
Requiring test.js in plugin config throws an error

### ISSUE THREAD

**Issue by nickhall** [rails/webpacker#1055]
I'm using webpacker 3.0.2 and trying desperately to get karma-webpack to work. Docs [here](https://github.com/rails/webpacker/blob/master/docs/testing.md) suggest requiring test.js in your karma-webpack configuration, advice which I followed. However, when including it and running karma, this error appears:

```
 TypeError: Cannot read property 'dev_server' of undefined
  at Object.<anonymous> (/path/to/node_modules/@rails/webpacker/package/config.js:19:12)
```

My dev dependencies are quaint and humble:

```
  "devDependencies": {
// eslint stuff
// ...
    "istanbul-instrumenter-loader": "^3.0.0",
    "jasmine": "^2.8.0",
    "karma": "^1.7.1",
    "karma-chrome-launcher": "^2.2.0",
    "karma-coverage": "^1.1.1",
    "karma-coverage-istanbul-reporter": "^1.3.0",
    "karma-jasmine": "^1.1.0",
    "karma-spec-reporter": "^0.0.31",
    "karma-webpack": "^2.0.6",
    "webpack-dev-server": "^2.9.2"
  }
```

I sniffed out the offending code here:

```
if (config.dev_server) {
  Object.keys(config.dev_server).forEach((key) => {
    config.dev_server[key] = devServer(key)
  })
}
```

It's loading the config from webpack.yml, and wouldn't you know that the dev settings have a dev_server entry, but test doesn't.

~~I tried adding `dev_server: false` to my test environment and it (sort of) works. It won't load my vue components, but that's an issue for another day.~~

Scratch that, I had disabled requiring of the script. Adding the option doesn't do anything.

I leave it up to you fine folk to decide if this is truly a bug, but it snarled me, so here I share.

**Comment by gauravtiwari** [comment]
cc// @codef0rmer

**Comment by nickhall** [comment]
I found the true solution: I had to manually set `NODE_ENV=test` when running karma. Not sure if this is purely my goof or an indication of how something could be improved somewhere, but please take it for what it is.

**Comment by gauravtiwari** [comment]
That's what I suspected as well from the error (basically saying I can't find any config). Great 👍

**Comment by gauravtiwari** [comment]
It's there in the docs though: https://github.com/rails/webpacker/blob/master/docs/testing.md#karma-setup-for-typescript (see scripts section)
