### ISSUE TITLE
asset_pack_path and aliases

### ISSUE THREAD

**Issue by timonbandit** [rails/webpacker#1061]
Hey guys!
I have a problem.
We trying to migrate from sprockets to webpacker and it's a bit tricky in our case.
We have a big application and 3 different themes.
Our folder structure looks like
```
app/themes/theme1
    /assets
        /images/theme1
        /javascript/theme1
        /stylesheets/theme1        
app/themes/theme2
    /assets
        /images/theme2
        /javascript/theme2
        /stylesheets/theme2        
app/themes/theme3
    /assets
        /images/theme3
        /javascript/theme3
        /stylesheets/theme3        

```
Sometimes I need to get my images in views. in sprockets, it was like
 `<%= asset_path('theme1/myimage.png') %>`
But now I have to write:
`<%=asset_pack_path("_/themes/theme1/assets/images/theme1/myimage.png") %>`
It looks terrible :(

I added 
`resolved_paths: ['app/assets/', 'app/themes/theme1/assets/', 'app/themes/theme2/assets/', 'app/themes/theme3/assets/']` to webpacker.yml 
and i can import images more/less comfortable `import 'images/theme1/myimage.png';` in my js files.

Is it possible to use aliases in asset_pack_path helper?

**Comment by gauravtiwari** [comment]
@timonbandit `asset_pack_path` is pretty limited and only works if a pack i.e. an image is under packs or imported in one of the packs. Perhaps, consider using a hybrid approach - sprockets for image linking and webpacker for rest of the stuff.

Obviously, you can alias on webpacker side for easy import - https://github.com/rails/webpacker/blob/master/docs/assets.md#using-babel-module-resolver. 

Would that work?

**Comment by timonbandit** [comment]
Thank you @gauravtiwari !
But there is another one problem:
```asset_path``` not working now ;(
```SyntaxError: Unexpected token: name ($)``` 
in my .erb
```background: #000 url(<%=asset_path('theme1/logo.png') %>) no-repeat;```

**Comment by gauravtiwari** [comment]
@timonbandit Is this under webpacker assets? or Rails views?

```yml
app/assets: 
  images: 
    # shared images here ie. used in views

app/javascript: 
   images: 
      # webpacker specific images here
```

**Comment by timonbandit** [comment]
@gauravtiwari I have no separate webpack assets. Because i'm migrating existing project and don't want to change directory structure.
Cause I have to use images from directories I pointed above

**Comment by gauravtiwari** [comment]
Right, when are you getting this error? During webpack build or when loading rails views?

**Comment by timonbandit** [comment]
when loading the page
```
ExecJS::RuntimeError in Home#index
Showing /var/www/app/app/themes/theme1/views/banners/cyber-monday/_sticky.html.erb where line #5 raised:

SyntaxError: Unexpected token: name ($)
```

**Comment by gauravtiwari** [comment]
Are you using server side rendering?

> cyber-monday/_sticky.html.erb

Is there a javascript_pack_tag on line 5 here?

**Comment by timonbandit** [comment]
yes it's server side rendering.
On line 5 -   ```background: #000 url(<%=asset_path('theme1/logo.png') %>) no-repeat;```

**Comment by gauravtiwari** [comment]
Could you paste full code please - hard to debug this way? But I guess the issue here is something is being passed on to JS that is not recognised by the interpreter.

**Comment by timonbandit** [comment]
_sticky.html.erb right now contains only this
```
<style>
  /*CyberMonday Skrrra*/
  a.sticky-bar {
    z-index: 998;
   background: #000 url(<%=asset_path('theme1/logo.png') %>) no-repeat;
    background-size: cover;
    width: 100%;
    height: 80px;
    bottom: 0;
    left: 0;
    position: fixed;
    color: #fff;
    display: none;
  }
</style>
```
When i change asset_path to asset_pack_path - it's working.

**Comment by timonbandit** [comment]
@gauravtiwari I found the problem.
Conflict with my ```js_compressor```
disabling ```Rails.application.config.assets.js_compressor = :uglifier``` solve this problem.
And I found a lot of similar closed issues, maybe need to add this information to Readme.md?

**Comment by gauravtiwari** [comment]
Ahh `uglifier` again, great you figured it out 👍 

Please make a PR 👍
