### ISSUE TITLE
Webpack watch command

### ISSUE THREAD

**Issue by andrewjaanuu** [rails/webpacker#1062]
is the webpack watch command supposed to be `./bin/webpack --watch --progress` rather than `./bin/webpack --colors --progress`? Also after I run `./bin/webpack --watch --progress`, it seem to still slow and shows Compilling... on the rails log output as if `./bin/webpack --watch --progress` weren't running.
I am using v3.0.2 with Rails 4.2.10.

**Comment by gauravtiwari** [comment]
Yes, that looks correct: 


```bash
# watch
./bin/webpack --watch --progress --color
```

```bash
# one of build
./bin/webpack --color --progress
```

![screen shot 2017-12-05 at 09 02 50](https://user-images.githubusercontent.com/771039/33598546-1ef5bc30-d99b-11e7-8ff5-e3d5bebfbde1.png)

**Comment by andrewjaanuu** [comment]
But the documentation is wrong, and webpacker don't seem to detect if `./bin/webpack --watch --progress --color` is running and rails server still seem to compile even with that running.

**Comment by gauravtiwari** [comment]
Please turn of compile, from webpacker.yml: `compile: false`
