### ISSUE TITLE
How to configure devServer.historyApiFallback in webpacker?

### ISSUE THREAD

**Issue by yizeng** [rails/webpacker#1065]
Just a quick question regarding how to enable [devServer.historyApiFallback](https://webpack.js.org/configuration/dev-server/#devserver-historyapifallback).

I'm aware of that there are many options we can set in `config/webpacker.yml`, like

    # config/webpacker.yml
    development:
        dev_server:
            host: localhost
            port: 3035

But how do I enable `historyApiFallback` there and how to configure it?

For example,
```
historyApiFallback: {
  rewrites: [
    { from: /^\/$/, to: '/views/landing.html' },
    { from: /^\/subpage/, to: '/views/subpage.html' },
    { from: /./, to: '/views/404.html' }
  ]
}
```

I can see in `package/environments/development.js` [here](https://github.com/rails/webpacker/blob/master/package/environments/development.js), we have `disableDotRule` enabled, but not configurable otherwise.

**Comment by gauravtiwari** [comment]
@yizeng If you are using master, you could reference dev server object and update config: 

```js
// development.js
environment.config.merge({
  devServer: {
    historyApiFallback: {
      rewrites: [
        { from: /^\/$/, to: '/views/landing.html' },
        { from: /^\/subpage/, to: '/views/subpage.html' },
        { from: /./, to: '/views/404.html' }
      ]
    }
  }
})
```

or if you are using 3.0.2,

```js
const merge = require('webpack-merge')
const config = environment.toWebpackConfig()

merge(environment.config, {
  devServer: {
    historyApiFallback: {
      rewrites: [
        { from: /^\/$/, to: '/views/landing.html' },
        { from: /^\/subpage/, to: '/views/subpage.html' },
        { from: /./, to: '/views/404.html' }
      ]
    }
  }
})

modules.exports =  config
```
