### ISSUE TITLE
Support customizing of resolveLoader

### ISSUE THREAD

**Issue by webark** [rails/webpacker#1069]
Would people be open to a PR enabling the adding of additional routes to the resolveLoader array? This would enable creating local custom loaders, rather than needing them to be packages.

https://github.com/rails/webpacker/blob/7738e6b2a25b5e35874cf5290a6e680ec10794b0/package/environment.js#L79-L81

**Comment by gauravtiwari** [comment]
We have some new API's coming in soon that will make it easy to customise.

**Comment by webark** [comment]
cool! thanks @gauravtiwari have any rough timeline for that?
