### ISSUE TITLE
mathjs has security issue

### ISSUE THREAD

**Issue by nikolalsvk** [rails/webpacker#1070]
Here's the security issue https://nodesecurity.io/advisories/552

mathjs is used by `postcss-sass` which is a dependency of `postcss-smart-import`.

**Comment by DanielSwensson** [comment]
I've opened a [PR ](https://github.com/sebastian-software/postcss-smart-import/pull/51) for `postcss-smart-import` to update `postcss-sass`. However `postcss-smart-import` is no longer maintained so moving to `postcss-import` as suggested would be a good direction to go.

**Comment by gauravtiwari** [comment]
Yes @DanielSwensson that's the plan. Will switch to `postcss-import`.

**Comment by DanielSwensson** [comment]
`postcss-smart-import` has been updated and no longer depends on `mathjs`. Think we can close this issue now.

**Comment by gauravtiwari** [comment]
Cool, thanks 👍  💯
