### ISSUE TITLE
Redirect from a rails view to react view returns blank page

### ISSUE THREAD

**Issue by iamcaleberic** [rails/webpacker#1073]
I have been having an issue where if I redirect or have a link from a rails view to a react view I just get a blank page is there a known limitation that touches on this particular issue.

After a refresh the react view is loaded correctly.

**Comment by gauravtiwari** [comment]
If you are using turbolinks you would need to make sure to use proper turbolinks event for mounting the react app. Here is a thread, it's mainly for vue app but principles are same for react: https://github.com/rails/webpacker/issues/161

**Comment by iamcaleberic** [comment]
@gauravtiwari thanks for pointing me to the thread...sorry for the duplicate issue was not sure what was happening...
