### ISSUE TITLE
Webpacker is installed 🎉 🍰  / invalid byte sequence

### ISSUE THREAD

**Issue by benbonnet** [rails/webpacker#1075]
Trying to deploy via mina, when precompiling, webpacker invariably outputs emoticons.

Got stuck for a while with the following : ```ArgumentError: invalid byte sequence in US-ASCII```

It might not happen on a osx workstation or so, but some CI (here bitbucket) might not provide clear ways handle such characters.

Eventually found out using the following `bundle exec rails webpacker:compile >> /dev/null`; is there a way to quiet the webpacker:install command ?

**Comment by gauravtiwari** [comment]
Ahh! May be you can precompile locally and then push it CI. Anyway, if this is a problem lets get rid of emojis :(

**Comment by benbonnet** [comment]
well not discussing this part, /dev/null is not that bad. But as there's a `--silent` for yarn or `--quiet` for bundle, there could be such some kind of `--stfu` option here maybe (;

**Comment by gauravtiwari** [comment]
Nope, not at the moment but happy to accept a PR 👍
