### ISSUE TITLE
`bin/rails webpacker:install` fails with `Errno::ENOENT: No such file or directory @ rb_sysopen`

### ISSUE THREAD

**Issue by mihaibb** [rails/webpacker#1077]
I've also put an issue on bundler since I'm not sure why this is happening.

https://github.com/bundler/bundler/issues/6208

**Comment by gauravtiwari** [comment]
Could you please run `bundle install --binstubs` or `bundle binstubs rails` and then run `bundle exec rails webpacker:install`?

**Comment by mihaibb** [comment]
```

**Comment by mihaibb** [comment]
I think I've found the problem, my `bundler` gem had a different of `bundle` gem.
I had to update both.

It works if I run the  `bundle exec rails webpacker:install` on existing app.
When I create a new rails app with `rails new myapp --webpack=react ` I get the error above and I have to run `bundle exec rails webpacker:install` manually.

**Comment by gauravtiwari** [comment]
@mihaibb Tested out with latest rails and this command works fine: `rails new myapp --webpack=react`

![screen shot 2017-12-11 at 11 04 34](https://user-images.githubusercontent.com/771039/33828203-1a683d88-de63-11e7-9e2e-33a1d2cbd6f0.png)

**Comment by mihaibb** [comment]
It works now. I think it was because of not having the latest rubygems or something. 
My bundler and bundle had different versions. 
Strange. 
Thanks for you help.
