### ISSUE TITLE
Production js build fails: Unexpected token: punc ([)

### ISSUE THREAD

**Issue by martyphee** [rails/webpacker#1086]
```
ERROR in application-0d41bce0b00e78f1221a.js from UglifyJs
Unexpected token: punc ([) [./node_modules/...Title/index.js:50,0][application-0d41bce0b00e78f1221a.js:415,4]
```

The line it's failing on is
```[styles[`level-${level}`]]: level,```

The `.bablerc` isn't changed.  I haven't done much to the application yet except trying to get in one of our libraries.

I've tried a few things, but haven't been able to get it to compile.

**Comment by martyphee** [comment]
nvm, fixed!

`production.js`
```
const merge = require('webpack-merge');
const environment = require('./environment');
const customConfig = require('./custom');

const UglifyJSPlugin = require("uglifyjs-webpack-plugin");
environment.plugins.delete("UglifyJs");
environment.plugins.set("UglifyJs", new UglifyJSPlugin());

config = merge(environment.toWebpackConfig(), customConfig);

module.exports = config;
```

`package.json`
`"uglifyjs-webpack-plugin": "^1.1.0"`

**Comment by guilleiguaran** [comment]
@martyphee to confirm, you fixed this updating to last version of plugin?

**Comment by gauravtiwari** [comment]
Yes, this is going to be default in webpack 4.0 but for now if you need es6 in your production build then you would need add that plugin manually.
