### ISSUE TITLE
Syntax error when trying to import vue.esm in Jest test

### ISSUE THREAD

**Issue by sdellis** [rails/webpacker#1087]
When I use `import Vue from 'vue'` instead of `import Vue from 'vue/dist/vue.esm'` in my `store.js`, it works, but then my dev app doesn't work. I'm using the latest version of vue-loader (13.5.0).

```
> NODE_ENV=test jest valhalla/app/javascript/test/unit/specs --coverage --no-cache

 FAIL  valhalla/app/javascript/test/unit/specs/store/mutations.spec.js
  ● Test suite failed to run

    /Users/Sellis/Development/figgy/node_modules/vue/dist/vue.esm.js:10671
    export default Vue$3;
    ^^^^^^
    
    SyntaxError: Unexpected token export
```
I have tried updating both my .babelrc file (as described as the solution to #416 ) and my `config/webpack/environment.js` to add the ["transform-es2015-modules-commonjs"] plugin in my test env. These did not fix the error.

**Comment by gauravtiwari** [comment]
@sdellis Were you able to figure this out? This isn't related to webpacker but setting up Jest with webpack. Perhaps you wanna post on Stackoverflow?

What happens if you do this? 

```json
"transformIgnorePatterns": ["<rootDir>/node_modules/(?!vue)" ]
```

**Comment by sdellis** [comment]
@gauravtiwari thank you for looking at this. I have not been able to figure it out and adding `"transformIgnorePatterns": ["<rootDir>/node_modules/(?!vue)" ]` had no effect. In order to target elements in my existing html/erb templates with Webpacker, I need to import `vue.esm.js`. Perhaps the default test environment does not work out of the box for my scenario? That made me think that this could be a problem with the default Webpacker test env configuration, but I'm happy to move this over to StackOverflow. In case a simple example clarifies things:
 
The following is my store: 
```
// store.js
import Vue from 'vue/dist/vue.esm' // changing this to import from 'vue' works
import Vuex from 'vuex'
Vue.use(Vuex)

const state = {
  count: 0
}

// export `mutations` as a named export
export const mutations = {
  increment: state => state.count++
}

export default new Vuex.Store({
  state,
  mutations
})
```
And here is my test:
```
import { mutations } from './store'

// destructure assign `mutations`
const { increment } = mutations

describe('mutations', () => {
  it('INCREMENT', () => {
    // mock state
    const state = { count: 0 }
    // apply mutation
    increment(state)
    // assert result
    expect(state.count).toBe(1)
  })
})
```

**Comment by gauravtiwari** [comment]
Have you tried this? https://github.com/eddyerburgh/vue-jest and also have you setup babel-jest?

**Comment by sdellis** [comment]
Yes, all my other jest-based tests work. It also works when I import 'vue' rather than 'vue.esm.js'. Here's [my StackOverflow post](https://stackoverflow.com/questions/47837971/cannot-import-vue-esm-js-in-vuex-mutations-test-in-webpacker).

**Comment by aronwolf90** [comment]
use vue/dist/vue.common, i also dont found a way to get running the vue/dist/vue.esm. Also i switch to mocho (much much much faster in docker container)

**Comment by vizcay** [comment]
Same problem here, ending up migrating all my (very simple) template strings to render functions to be able to use the runtime-only version of Vue which works fine.
