### ISSUE TITLE
Add a babel-plugin and set options for it

### ISSUE THREAD

**Issue by hundsim** [rails/webpacker#1088]
I'm trying to add the babel-plugin [`babel-plugin-styled-components`](https://github.com/styled-components/babel-plugin-styled-components) (that adds debugging support for [`styled-components`](https://github.com/styled-components/styled-components)), and add the [following options](https://www.styled-components.com/docs/tooling#better-debugging) for it:

    {
      "plugins": [
        ["babel-plugin-styled-components", {
          "displayName": false
        }]
      ]
    }

I suppose that [this is the Webpacker doc section](https://github.com/rails/webpacker/blob/master/docs/webpack.md#plugins) laying out how to add a plugin. But I still don't understand how to add a plugin and set the options for it.

  >TypeError: environment.plugins.prepend is not a function

The above is the error I get when trying the below in `environment.js`:

    const { environment } = require('@rails/webpacker')
    const webpack = require('webpack')

    environment.plugins.prepend(
      'Provide',
      new webpack.ProvidePlugin({
        BabelPluginStyledComponents: 'babel-plugin-styled-components'
      })
    )

    module.exports = environment

**Comment by gauravtiwari** [comment]
Please upgrade to version 3.1.1
