### ISSUE TITLE
Webpack 3+  Compiling warnings about use custom data attributes on my scss file

### ISSUE THREAD

**Issue by HectorLS** [rails/webpacker#1094]
Hello, i'm getting this warning when i compile

`WARNING in ./node_modules/css-loader?{"minimize":false,"sourceMap":true,"importLoaders":2}!./node_modules/postcss-loader/lib?{"sourceMap":true,"config":{"path":"/Users/USERNAME/PROJECTNAME/.postcssrc.yml"}}!./node_modules/resolve-url-loader?{"attempts":1,"absolute":false,"sourceMap":true,"fail":false,"silent":false,"keepQuery":false,"debug":false,"root":null,"includeRoot":false}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true}!./app/frontend/packs/application.scss
`

`
(Emitted value instead of an instance of Error) postcss-custom-selectors: /Users/USERNAME/PROJECTNAME/app/javascript/scss/sassfile.scss:219:10: The selector 'html[data-device='mobile'] .logo is undefined`

The important part is this i think
**The selector** 'html[data-device='mobile'] .logo **is undefined**`

Whaaat ? warning because i'm using a custom data-attribute (which one gonna be added obviously with javascript at some point)

But CSS should just add my rules, doesn't need to worry about my selector  :confused:

How can remove it, because i have like 10 selector like that one, and my terminal is full of warning

**Comment by gauravtiwari** [comment]
@HectorLS Can't reproduce this locally. Is this still an issue for you?

**Comment by HectorLS** [comment]
Yes, cannot see how to solved it. So weird that complain about my selector

**Comment by gauravtiwari** [comment]
Could you post a couple of lines from? `sassfile.scss:219:10`? (mainly here)

**Comment by HectorLS** [comment]
```
webpacker.1 |     WARNING in ./node_modules/css-loader?{"minimize":false,"sourceMap":true,"importLoaders":2}!./node_modules/postcss-loader/lib?{"sourceMap":true,"config":{"path":"/Username/ProjectName/.postcssrc.yml"}}!./node_modules/resolve-url-loader?{"attempts":1,"absolute":false,"sourceMap":true,"fail":false,"silent":false,"keepQuery":false,"debug":false,"root":null,"includeRoot":false}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true}!./app/javascript/packs/application.scss
webpacker.1 |     (Emitted value instead of an instance of Error) postcss-custom-selectors: /Username/ProjectName/app/javascript/scss/sections/_sassFilename.scss:219:10: The selector 'html[data-device='mobile'] .gallery .gallery-item video::--webkit-media-controls-play-button,
webpacker.1 |     html[data-device='mobile'] .gallery .gallery-item video::-webkit-media-controls-start-playback-button,
webpacker.1 |     html[data-device='tablet'] .gallery .gallery-item video::--webkit-media-controls-play-button,
webpacker.1 |     html[data-device='tablet'] .gallery .gallery-item video::-webkit-media-controls-start-playback-button' is undefined
webpacker.1 |     NonErrorEmittedError: (Emitted value instead of an instance of Error) postcss-custom-selectors: /Username/ProjectName/app/javascript/scss/sections/_sassFilename.scss:219:10: The selector 'html[data-device='mobile'] .gallery .gallery-item video::--webkit-media-controls-play-button,
webpacker.1 |     html[data-device='mobile'] .gallery .gallery-item video::-webkit-media-controls-start-playback-button,
webpacker.1 |     html[data-device='tablet'] .gallery .gallery-item video::--webkit-media-controls-play-button,
webpacker.1 |     html[data-device='tablet'] .gallery .gallery-item video::-webkit-media-controls-start-playback-button' is undefined
webpacker.1 |         at Object.emitWarning (/Username/ProjectName/node_modules/webpack/lib/NormalModule.js:117:16)
webpacker.1 |         at result.warnings.forEach (/Username/ProjectName/node_modules/postcss-loader/lib/index.js:149:49)
webpacker.1 |         at Array.forEach (<anonymous>)
webpacker.1 |         at postcss.process.then (/Username/ProjectName/node_modules/postcss-loader/lib/index.js:149:27)
webpacker.1 |         at <anonymous>
webpacker.1 |         at process._tickDomainCallback (internal/process/next_tick.js:228:7)
webpacker.1 | Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--0-oneOf-6-2!node_modules/postcss-loader/lib/index.js??ref--0-oneOf-6-3!node_modules/resolve-url-loader/index.js??ref--0-oneOf-6-4!node_modules/sass-loader/lib/loader.js??ref--0-oneOf-6-5!app/javascript/packs/admin.scss:
webpacker.1 |
```

**Comment by gauravtiwari** [comment]
Thanks, I meant the scss file, don't need to paste all scss code. Just the selector compiler is complaining about: `html[data-device='mobile'] .gallery .gallery-item video::--webkit-media-controls-play-button`. I want to see the scss is written.

**Comment by HectorLS** [comment]
```
html[data-device='mobile'],
html[data-device='tablet'] {
  .gallery {
    .gallery-item {
      video {
        &::--webkit-media-controls-play-button,            //  Old shadow dom iOS  video element
        &::-webkit-media-controls-start-playback-button {  //  New shadow dom iOS video element
          display: none !important;
        }
      }
    }
  }
}
            
```

Yes i was on it, sorry by the delay

**Comment by gauravtiwari** [comment]
Ahh yes, you should probably put styles like this in a `.css` file and import it in your component, instead of using in scss files, since css modules doesn't support everything.

**Comment by HectorLS** [comment]
ok, so then its about the pseudo-selectors, not about my data attributes.
thank you so much 👍

**Comment by gauravtiwari** [comment]
Nope, great 👍
