### ISSUE TITLE
Move to postcss-import, postcss-smart-import is unmaintaned

### ISSUE THREAD

**Issue by jondavidjohn** [rails/webpacker#1095]
`postcss-smart-import` is unmaintained and now has a downstream dependency that has a security vulnerability.

https://nodesecurity.io/advisories/552

This likely is not an actual problem since this package is focused on delivering front-end javascript, but it still seems like a good idea to move to a supported module.

**Comment by guilleiguaran** [comment]
Thanks for opening this issue!!

This was already done: https://github.com/rails/webpacker/commit/6fdabc78c6142059c8204cdd092cea265d3ff554#diff-b9cfc7f2cdf78a7f4b91a753d10865a2 and it's pending for release in the next days.
