### ISSUE TITLE
Using jQuery $ in rails js response while using webpack

### ISSUE THREAD

**Issue by simoniong** [rails/webpacker#1096]
Hi, all, I don't know if it's appropriate to ask this question here, please correct me if i am wrong, or guide me to ask somewhere else.

As I know we have 2 system to compile js assets now, one compile from Asset Pipeline, and the other is compile from Webpack. What happen if i only include jquery in webpack, but not in asset pipeline?

Let say, I have jQuery compiled in Webpack, but totally do not use any asset pipeline things ( jquery gem removed as well ), and I try to make a js call using something like:

```
   link_to some_path, remote: true
```

and render js response in rails using some template like `update.js.erb`.
the content in `update.js.erb` would be something like:

``` update.js.erb
$('.category').html("<%= j render "category_field" %>");
```

Would this work? as in my understanding, `update.js.erb` is compile from asset pipeline, so at least, it would compile to some js code, send back to browser, so in this case, asset pipeline should not need to know about js content, it just need to know how to compile erb content into js file, and then send back to browser.

 In browser, as we already loaded the page, the asset compiled from webpack is already loaded, so jquery should be ready, It should be able to compile js code returned from server, right?

I have weird issue here, that js response can not be executed because of `Uncaught ReferenceError: $ is not defined`. but when I turn on developer console, and type in $, it's there.

**Comment by guilleiguaran** [comment]
Is `update.js.erb` under `app/views`? If this is the case then it isn't processed by Sprockets.

By default `$` isn't available globally when compiling entries with webpack, you need to use something `ProvidePlugin` to make it available globally in the browser: https://webpack.js.org/plugins/provide-plugin/#usage-jquery

**Comment by guilleiguaran** [comment]
Closing since this isn't really a webpacker issue.

**Comment by simoniong** [comment]
@guilleiguaran Thanks for your quick response, I already using `ProvidePlugin` in webpack config, but I still got this errors. I could use $ in chrome's development console, but not the js response back from server side.

I though it was asset pipeline issue, but seems it wan't after you clarify it. Anyway, I will see if i could take some time tomorrow to reproduce it with a fresh new install. Thanks man!

**Comment by simoniong** [comment]
turns out, I need `expose-loader` to expose my `$` & `jQuery` so that Chrome development console can refer to it correctly, and js response from rails can run properly, and it work in my system test as well using selenium.

This is for conclusion: `ProvidePlugin` is for build time, and `expose-loader` is for run time.

but I am still having another issues with jquery plugin, like select2, while I use this in javascript response generated from Rails, I keep having a errors like:

``` 
$(..).select2 is not a function
```
I think It's not webpacker's issue, I will ask somewhere like SO. Thanks guys!
