### ISSUE TITLE
webpacker compile in production is super sluggish

### ISSUE THREAD

**Issue by iamcaleberic** [rails/webpacker#1100]
I have been trying to deploy rails/webpacker application to production and during webpacker compile everything just comes to a grinding halt  the server has 2 cores and 4 GB ram which is usually sufficient for this process but this is not the case. The compilation process for webpacker starts and just hogs the resources and then just dies or leaves some zombie processes running. It takes about 15 minutes.

Trying to compile the assets locally as suggested by someone who was facing a similar issue[https://github.com/rails/webpacker/issues/1003]  just resulted in the below error. So being out of resources does not seem to be the issue because locally I have more than enough resources. Is this an issue related to the project or what seems to be the issue because the gem i was using earlier is able to handle all this without a fuss...?

``` 
<--- Last few GCs --->

[12826:0x55c0e2d41380]   717417 ms: Mark-sweep 1324.3 (1463.7) -> 1324.2 (1463.7) MB, 923.8 / 0.0 ms  allocation failure GC in old space requested
[12826:0x55c0e2d41380]   718631 ms: Mark-sweep 1324.2 (1463.7) -> 1324.2 (1429.7) MB, 1213.4 / 0.1 ms  last resort GC in old space requested
[12826:0x55c0e2d41380]   719690 ms: Mark-sweep 1324.2 (1429.7) -> 1324.2 (1425.7) MB, 1058.7 / 0.0 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0xf4701da5749 <JSObject>
    1: add [0xfeab18022d1 <undefined>:~9498] [pc=0x2caf2ef85569](this=0x303a06e84819 <Object map = 0x1e7b13f71cd1>,source=0x9b825d86c59 <String[35]: api/request-9f3f7dd6fe0e2daee077.js>,gen_line=1,gen_col=942333,orig_line=62884,orig_col=26570,name=0xfeab18022d1 <undefined>)
    2: /* anonymous */ [0xfeab18022d1 <undefined>:~4262] [pc=0x2caf2ef860e8](this=0x303a06e853f9 <Object map = 0x15ef766aa79...


FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [node]
 2: 0x55c0e128d13f [node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
 5: v8::internal::Factory::NewUninitializedFixedArray(int) [node]
 6: 0x55c0e0e6e1b0 [node]
 7: v8::internal::Runtime_GrowArrayElements(int, v8::internal::Object**, v8::internal::Isolate*) [node]
 8: 0x2caf2d9842fd
```

**Comment by iamcaleberic** [comment]
#1003

**Comment by gauravtiwari** [comment]
@iamcaleberic Think this is related to your app code, probably a circular dependency that's causing VM to crash. Were you able to figure it out?

**Comment by iamcaleberic** [comment]
@gauravtiwari I was not able to figure it out...switched to an alternative I use and worked great. The VM is not actually crashing the config commands runs and just dies out and zombies out...Will try and use this at a future time.Thanks for the comment though.
