### ISSUE TITLE
problem with images 

### ISSUE THREAD

**Issue by net1957** [rails/webpacker#1101]
I have troubles to uses images with webpacker.

I'm on windows...
I added a image as javascript/images/logo.png and
````
 <img src="<%= asset_pack_path('images/logo.png')%>">
````
 in the layout.

in packs/application.js I added:
```` JS
require.context('../images/', true, /\.(gif|jpg|png|svg)$/i)
````
With  **webpacker 3.0.2** I get the following manifest file:
````
{
  "application.css": "/packs/application-cf63677c5f4021f40c64b2013d17428c.css",
  "application.js": "/packs/application-6a8f00751a437a9bfb81.js",
  "images\\logo.png": "/packs/images/logo-b463011bf65683cac7917a30ba072bf8.png"
}
````
Bad path separator! and asset_pack_path('images/logo.png') don't find the file.
if I manualy correct the manifest it's working. Surely a windows thing...

But,

If I upgrade to **webpack 3.1.1**  I get no reference to images in the manifest and it fail .

Any idea about the problem ?

I used https://github.com/zarqman/look_ma_no_sprockets as example. All credits to the author.

Regards

**Comment by gauravtiwari** [comment]
Seems to build just fine,

```json
{
  "application.js": "/packs/application-8cbbb693a6f356cd6f37.js",
  "application.js.map": "/packs/application-8cbbb693a6f356cd6f37.js.map",
  "hello_coffee.js": "/packs/hello_coffee-a69b59487d6e2da7157e.js",
  "hello_coffee.js.map": "/packs/hello_coffee-a69b59487d6e2da7157e.js.map",
  "hello_react.js": "/packs/hello_react-f7d90ef63bedfb0e838a.js",
  "hello_react.js.map": "/packs/hello_react-f7d90ef63bedfb0e838a.js.map",
  "images/building-ecosystem.png": "/packs/images/building-ecosystem-8db23de7c2de4ff3e665092d637e13cd.png"
}
```

```js
require.context('../images/', true, /\.(gif|jpg|png|svg)$/i)
```

![screen shot 2017-12-14 at 08 22 30](https://user-images.githubusercontent.com/771039/33982621-0e64a664-e0a9-11e7-8183-151a2c8fdf3e.png)

**Comment by aganov** [comment]
Same issue here, `url-loader` is processing small files and they are excluded from `manifest.json`

Temporary solution is to set `{ limit: 1 }` to `url-loader` but this is not the right way... @gauravtiwari Any ideas?

**Comment by net1957** [comment]
I can confirm @aganov temporary solution.
On windows i get the same result in webpack 3.1.1 as in 3.02 with 2 \\\\  (should be /)

````
{
  "application.css": "/packs/application-3fd31c847214dce7c7a66830d3041511.css",
  "application.css.map": "/packs/application-3fd31c847214dce7c7a66830d3041511.css.map",
  "application.js": "/packs/application-814bc0d5a16e20a1fcc8.js",
  "application.js.map": "/packs/application-814bc0d5a16e20a1fcc8.js.map",
  "images\\logo.png": "/packs/images/logo-b463011bf65683cac7917a30ba072bf8.png"
}
````

any idea where to look for this path separator issue ?

**Comment by aganov** [comment]
@net1957 FYI: `url-loader` is now removed from the "core" loaders (in master branch). Removing it manually will be no longer necessary.

**Comment by gauravtiwari** [comment]
@net1957 Perhaps, consider posting `\\` issue on file-loader repo.
