### ISSUE TITLE
Different webpack configs for different packs

### ISSUE THREAD

**Issue by TheRusskiy** [rails/webpacker#1115]
Wondering if it's possible?

My use case is that I use `OfflinePlugin` ( https://github.com/NekR/offline-plugin ) to cache assets using service the worker.
If all packs are using the same webpack config then client ends up downloading all packs (e.g. admin, customer, etc)

**Comment by gauravtiwari** [comment]
I think you can apply an origin from where the service workers should register assets from and then you can filters assets you don't want to cache: https://github.com/goldhand/sw-precache-webpack-plugin
