### ISSUE TITLE
Can not use `asset_pack_path` in js.erb file

### ISSUE THREAD

**Issue by lanzhiheng** [rails/webpacker#1117]
Hi, I want to get webpacker's resource by asset_pack_path

It works very well if I locale my code in ```*.html.erb``` file with inline script tag like this

```
<script>
   if ($('#your-story-section').length) $.getScript("<%= asset_pack_path 'story_page.js' %>")
</script>
```

But, if I move my code to a javascipt file ```*.js.erb```

``` application.js.erb
if ($('#your-story-section').length) $.getScript("<%= asset_pack_path 'story_page.js' %>")
```

and then use sprockets to require it 

```
//= require custom/application.js.erb
```

I will get this error

![image](https://user-images.githubusercontent.com/8858472/34094757-8be5a9ae-e409-11e7-98b6-b3b6a91a6103.png)

Can you help me to abort this error, I don't want to contain any inline javasciprt in code base.

**Comment by gauravtiwari** [comment]
What if you put `application.js.erb` inside `app/javascript/packs` and then require it in your view using? `javascript_pack_tag`? 

```js
// packs/something.js.erb
if ($('#your-story-section').length) $.getScript("<%= asset_pack_path 'story_page.js' %>")
```

```rb
# views/something/
<%= javascript_pack_tag 'something' %>
```

**Comment by lanzhiheng** [comment]
@gauravtiwari  Thanks for your answer, But I alaway get this error if I locate my file to `app/javascript/packs` directory.

**Comment by lanzhiheng** [comment]
Is it cause by [here](https://github.com/rails/webpacker/blob/v1.1.0/lib/webpacker/railtie.rb#L5)? Are we just register the webpack helper to ActionController, but not in the sprockets?

**Comment by lanzhiheng** [comment]
@gauravtiwari I think I will extend the class by this way, to solve this problem. In my `assets/javascripts/a.js.erb` file I just add this code

```
  <% # append some helper method from webpack %>
  <% instance_singleton_class = self.singleton_class %>
  <% instance_singleton_class.include Webpacker::Helper %>

  if ($('#story').length) $.getScript("<%= asset_pack_path 'story.js' %>")
  if ($('#product').length) $.getScript("<%= asset_pack_path 'product.js' %>")
``` to extend the current instance

**Comment by gauravtiwari** [comment]
@lanzhiheng Does this work? 

```erb
<%# app/javascript/my_pack/example.js.erb %>

<% helpers = ActionController::Base.helpers %>
const railsImagePath = "<%= helpers. asset_pack_path('rails.png') %>"
```

**Comment by DataCourier** [comment]
@gauravtiwari thanks, works for me!
