### ISSUE TITLE
Unable to run webpacker:install in a rails engine.

### ISSUE THREAD

**Issue by etewiah** [rails/webpacker#1124]
When I install the webpacker gem in a rails engine the "webpacker:install" command is not available.  There is however a "app:webpacker:install" command available.

When I run it:

`bundle exec rails app:webpacker:install`

I get the following error:

```
rails aborted!
Don't know how to build task 'app:template' (see --tasks)
./bin/rails:13:in `require'
./bin/rails:13:in `<main>'
(See full trace by running task with --trace)
```

The only way to get the command to run is to cd into "spec/dummy" and run "webpacker:install".  That installs webpacker into the "spec/dummy" directory though which is not ideal.

Just so I can learn more about webpacker I went ahead and installed it in the dummy app in my project here and it actually works but does not seem like the correct way to do things:

https://github.com/RealEstateWebTools/property_web_scraper

**Comment by gauravtiwari** [comment]
@etewiah Thanks for filling the issue. Webpacker doesn't support engines yet, please see this thread for more details: https://github.com/rails/webpacker/issues/348

**Comment by gauravtiwari** [comment]
Lets track this in #1694

**Comment by zedtux** [comment]
I'm facing this exact error, @etewiah how did you fixed it?
