### ISSUE TITLE
after migrating from 3.0.2 to 3.2.0 image files are not found by css-loader

### ISSUE THREAD

**Issue by leikind** [rails/webpacker#1125]
I have files in `app/assets/images` and SASS styles like  `.world-icon { background-image: url('world.png'); }`. With webpacker 3.0.2 they were found and processed. With 3.2.0 I get the following errors:

```    ERROR in ./node_modules/css-loader?{"minimize":false,"sourceMap":true,"importLoaders":2}!./node_modules/postcss-loader/lib?{"sourceMap":true,"config":{"path":"/Users/leikind/projects/fb/backend/.postcssrc.yml"}}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true}!./app/webpack/stylesheets/application.scss
    Module not found: Error: Can't resolve './world.png' in '/Users/leikind/projects/fb/backend/app/webpack/stylesheets'
     @ ./node_modules/css-loader?{"minimize":false,"sourceMap":true,"importLoaders":2}!./node_modules/postcss-loader/lib?{"sourceMap":true,"config":{"path":"/Users/leikind/projects/fb/backend/.postcssrc.yml"}}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true}!./app/webpack/stylesheets/application.scss 6:84042-84064 
```

Adding `app/assets/images` to `resolved_paths` in `webpacker.yml` has no effect.

I have a pretty standard configuration, only one additional loader `expose-loader`.

What am I missing? How can this be fixed?

**Comment by gauravtiwari** [comment]
@leikind Is this image relative to css file? `'world.png'`

We have removed `resolve-url-loader` which has some clever lookups but also impacted the build times and some folks had security concerns as well. There are two solutions: 

1. Use full relative path: `../../app/assets/images/foo.png`
2. reinstall resolve-url-loader in your app: https://github.com/rails/webpacker/blob/master/docs/css.md#resolve-url-loader

**Comment by leikind** [comment]
The solution with `resolve-url-loader` has not worked, but I am more than OK with providing relative paths to images explicitly
