### ISSUE TITLE
Asset compilation

### ISSUE THREAD

**Issue by stefatkins** [rails/webpacker#1128]
Hi, I am currently encountering an issue with webpacker and the way its watches asset changes. 
We have two different entry points (files that are in javascript/packs) : 

- application.js
- administration.js

each entry point imports a css file :

```
//application.js 
import "../css/application.css" 
```

```
//administration.js 
import "../css/administration.css" 
```

As you can see, css files aren't in packs folder.

Everytime a change is made in administration.js, webpacker compiles administration.css even if no changes were made in css, and above all it also compiles application.css, that is not called at all in administration.js. And vice-versa with application.js.

This is making font-end development in the javascript folder very long.

Is there a way to solve this ?

**Comment by gauravtiwari** [comment]
@stefan694 What are you using webpack-dev-server or watcher?

**Comment by stefan694** [comment]
Hi @gauravtiwari, I am using webpack-dev-server

**Comment by gauravtiwari** [comment]
@stefan694 Could you try watcher please? Seems like since webpack dev server builds from memory it emits all the assets but it doesn't rebuild them. 

```
./bin/webpack --watch --progress --color
```

**Comment by stefan694** [comment]
I have an error:

`Unknown switches '--watch, --progress, --color'`
 
This is the configuration of my freshly new rails project : 
- rails 5.1.4
- webpacker version : 3.2.0

**Comment by gauravtiwari** [comment]
```
bundle binstubs webpacker --force
./bin/webpack --watch --progress --color
```

**Comment by stefan694** [comment]
Still does not work with ```./bin/webpack --watch --progress --color```

**Comment by gauravtiwari** [comment]
Please try the latest RC, otherwise feel free to open a new issue with more details.
