### ISSUE TITLE
Webpack.yml `resolved_paths` do not seem to work in the default test environment

### ISSUE THREAD

**Issue by sdellis** [rails/webpacker#1129]
The Webpack.yml `resolved_paths` do not seem to work in the default test environment. I have `  resolved_paths: ['app/assets/images']` set and importing image assets (i.e., `import default_image from 'default.png'`) works great in dev and production. However, when using Jest to run a test on a module that references an image in that path, I get the following error:

```
  ● Test suite failed to run

    Cannot find module 'default.png' from 'my-module.js'
```
Is this a bug or am I missing something?

**Comment by gauravtiwari** [comment]
@sdellis Jest is different tool and requires a different setup. I think you would need to add paths to: https://facebook.github.io/jest/docs/en/configuration.html#modulepaths-array-string similar to webpack.

**Comment by Shoroh** [comment]
Hi @sdellis, have you solved the issue?
