### ISSUE TITLE
file-loader using an 'exclude' pattern is too aggressive

### ISSUE THREAD

**Issue by n0nick** [rails/webpacker#1132]
The [change in package/rule/file.js](https://github.com/rails/webpacker/pull/1058/files#diff-5738d5d73471ec5cb82aa72024b3d794) as part of #1058 made `file-loader` catch all files not matching some `exclude` pattern instead of testing against a `test` pattern.

This means that any file extension not included in the hard-coded `exclude` pattern is treated by Webpack as a file and tries to generate a dynamic export.

In particular, I was using [pug-loader](https://github.com/pugjs/pug-loader) with the following loader config:
```javascript
{
  test: /\.(pug|jade)?$/,
  use: [
    {
      loader: 'pug-loader'
    }
  ]
};
```
But since the `.jade` and `.pug` file extensions are not part of the hard-coded `exclude` pattern, Webpack would generate a dynamic export which my app (`import template from "file.jade"` made `template` a path string instead of a template function).

**Comment by gauravtiwari** [comment]
Duplicate #1127
