### ISSUE TITLE
Module parse failed - .vue files

### ISSUE THREAD

**Issue by aphilippartd** [rails/webpacker#1134]
Hi,
I am currently facing a very strange issue. I am currently trying to import a .vue file in one of my .js packs. For some reason, whenever i try to import the said .vue file, the following error message is displayed:
![image](https://user-images.githubusercontent.com/24428618/34201548-1f569588-e575-11e7-8702-9c2c869fc64e.png)

I really do not understand where this error may be coming from as I was using .vue components without any issues in a previous project with a similar configuration. The only configuration change I made was to add the following in my environment.js:

`module.exports = {
  resolve: {
    alias: {
      components: '/components',
      utilities: '/utilities'
    }
  }
}`

I would highly appreciate if someone could help me on this one.
Thanks!!!

More info:
Failing line:
![image](https://user-images.githubusercontent.com/24428618/34201775-e34fcdec-e575-11e7-86e2-5b29bfd5e336.png)

Component i am trying to load:
![image](https://user-images.githubusercontent.com/24428618/34201803-034403e8-e576-11e7-9e91-c2ac8907283a.png)

**Comment by gauravtiwari** [comment]
Are you using the latest version of webpacker?

**Comment by gauravtiwari** [comment]
If yes, you would need to copy vue loader or run vue install to add the loader to environment.js: https://github.com/rails/webpacker/blob/master/CHANGELOG.md#breaking-changes

**Comment by aphilippartd** [comment]
No, i am using version 3.0 with rails 5.1.1 which was the same setup in my previous working project. Would updating my webpacker version do the trick?

**Comment by gauravtiwari** [comment]
Don't think it's using `3.0.2` atleast for node module. If you want to use 3.0.2, could you please install like so: 

```
yarn add @rails/webpacker@3.0.2
```

**Comment by gauravtiwari** [comment]
> Would updating my webpacker version do the trick?

The latest version has extracted vue loader into user space so you would need to add it either though installer or manually as explained in the Changelog.

**Comment by aphilippartd** [comment]
Great thanks!!! Updating the webpacker to 3.2 and running the following commands did the trick (and seriously reduced the size of generated .js packs):
`bundle update webpacker
yarn upgrade @rails/webpacker
bundle exec rails webpacker:install:vue`

Thanks a lot for your help!!!

**Comment by gauravtiwari** [comment]
Awesome 👍

**Comment by woto** [comment]
Too bad because it's bug in a fresh Rails 5.1.4 release :(

**Comment by aphilippartd** [comment]
Would there have been any other way to solve the issue?

**Comment by gauravtiwari** [comment]
What's the issue? thought it was resolved earlier

**Comment by aphilippartd** [comment]
No worries it's indeed solved, just asking the question to woto out of curiosity  :)
