### ISSUE TITLE
CSS code injection with vue-loader

### ISSUE THREAD

**Issue by tyvdh** [rails/webpacker#1136]
Is there a way to have the vue-loader not refresh my page when I make a CSS change? With a standard webpack implementation this "just works", however here while using the webpacker to generate and place links to the generated files it forces a refresh for every change. For JS this is fine and expected, for CSS this is a nightmare.

**Comment by gauravtiwari** [comment]
@tyvdh Have you turned on `hmr: true` in webpacker.yml?

**Comment by tyvdh** [comment]
Yep. Found that a bit after posting this. Works like a charm. Thanks!
