### ISSUE TITLE
Merging duplicate imports

### ISSUE THREAD

**Issue by tyvdh** [rails/webpacker#1137]
How are folks handling duplicate imports across packs?

I'm currently planning on having a pack tag set up on a per-page basis. With all the code and styles associated with that page boiled down to a single pack. The major issue with this of course is that currently if I use say lodash for multiple packs it will be compiled and included in each and every one of those packs. How are folks avoiding loading duplicate code?

Am I thinking about this all backwards? How are people managing large multi page projects within their rails apps without duplicating either library and util imports as well as components and more global but app specific utils?

Rails keeps me from having and SPA but Webpacker doesn't seem to be aware of the other packs it's creating and will just boil down the code for each pack into a single file regardless of other packs it has created.

NOTE: I'm wary of creating a singular pack of JS and CSS as our app is fairly monolith and I do not need or want to load all the scripts and styles for all the app immediately. Is there some sort of code splitting + webpacker trick that anyone knows about.

Thanks.

**Comment by doits** [comment]
This is done by common chunks in webpack: https://webpack.js.org/plugins/commons-chunk-plugin/ - it creates one or more "common chunks" where shared code lives. This chunks are included globally / on every page (for example lodash) and it will be used by all other page specific packs.

But don't ask me for instructions how to make webpacker use this :-) If you find it it, this would be a good thing for the webpacker doc folder if you ask me.

**Comment by gauravtiwari** [comment]
thanks @doits 

@tyvdh Yes, please consider using common chunk plugin and create multiple variations as fit for your app. 

```js
// https://webpack.js.org/plugins/commons-chunk-plugin/#combining-implicit-common-vendor-chunks-and-manifest-file
environment.plugins.append('CommonChunkManifest',
    new webpack.optimize.CommonsChunkPlugin({
      name: 'manifest' // Runtime code
    })
)

// Merge chunks 
// https://github.com/webpack/webpack/tree/master/examples/extra-async-chunk
environment.plugins.append(
  'CommonsChunkAsync',
    new webpack.optimize.CommonsChunkPlugin({
      async: true,
      children: true,
      minChunks: 3
    })
)

```
