### ISSUE TITLE
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' https:".

### ISSUE THREAD

**Issue by mayordwells** [rails/webpacker#1138]
Don't know if this is a Rails or Webpacker error, but a quick fix will be appreciated. Following a setup that used to work for me on multiple projects. On a Rails + Angular + Webpacker setup
Using Rails 5.2.0.beta2 and Ruby 2.4.2

Here's the screenshot of the error log in console. What's the possible cause of this? and what can I do to fix it?
<img width="1195" alt="screen shot 2017-12-21 at 12 56 57 pm" src="https://user-images.githubusercontent.com/1370340/34250750-d6751fd0-e64e-11e7-87c8-e1858bda26e4.png">

**Comment by gauravtiwari** [comment]
@mayordwells Here is an example rails 5.2 app with csp: https://github.com/gauravtiwari/webpacker-5.2-csp

please see content_security_policy.rb. We have also added documentation here: https://github.com/rails/webpacker#angular-with-typescript(at the bottom)
