### ISSUE TITLE
please add feature that config the location of `.babelrc` and `package.json`

### ISSUE THREAD

**Issue by geminiyellow** [rails/webpacker#1139]
webpack compile the script not the ruby code. i really dont want to see that ruby config file and js config file side by side. when run the `webpacker:installer`, now the folders is 

```
config
  webpack
    *.js
```

i just want to change the root to my folder, like

```
client(my folder)
  old folders
```
and,  if you can, please let me config the location of `.babelrc` and `package.json`. 
yes, i really happy to see it can move to my folder.

`babelrc`  and `package.json` is not part of ror.

**Comment by gauravtiwari** [comment]
@geminiyellow Please see this PR: https://github.com/rails/rails/pull/28093 and https://github.com/rails/webpacker/pull/84
