### ISSUE TITLE
File naming within packs

### ISSUE THREAD

**Issue by elkhan** [rails/webpacker#1142]
Just came across a bug/feature - if you name your .js and .css files within a pack with the same name (minus extension) .js file won't get rendered.
A way to reproduce, two files app/javascript/packs/app.js and app/javascript/packs/app.css.
Within application.html.erb include only stylesheet_pack_tag 'app' and say, index.html.erb has one javascript_pack_tag 'app' - app/javascript/packs/app.js won't get rendered.

**Comment by renchap** [comment]
`app/javascript/packs` needs to contain only your Webpack entry points (called pack files by Webpacker).
Also, your stylesheets needs to be included by a pack file to be compiled. For example, in `app/javascript/packs/app.js`:

```es6
import '../app/index' // will import app/javascript/app/index.js
import '../app/styles' // will import app/javascript/app/styles.css
```

**Comment by gauravtiwari** [comment]
Thanks @renchap 

Yes, please don't name two files same since it's all treated as one thing i.e. entries and not like one is JS and other is CSS. As @renchap suggested you can include CSS within the JS pack and it will generate a stylesheet with exact name as pack.
