### ISSUE TITLE
webpacker not rendering assets in production

### ISSUE THREAD

**Issue by melhotiby** [rails/webpacker#1143]
I have a [test Project](https://github.com/melhotiby/testWebpacker) that I am using webpacker and react with ES6. The project compiles the assets in development and renders as expected, by running the following
```ruby
# Starting the webpack dev server
./bin/webpack-dev-server

# Starting the rails server
rails s
```
Locally it compiles successfully `webpack: Compiled successfully` and renders as expected 
<img width="598" alt="screen shot 2017-12-22 at 10 13 29 am" src="https://user-images.githubusercontent.com/850602/34302994-77852890-e701-11e7-83ae-36b188bb0566.png">
Looking at the source I get both the asset files declared from the `javascript_pack_tag 'application'` and `stylesheet_pack_tag 'application'` I have defined in my [layout file](https://github.com/melhotiby/testWebpacker/blob/master/app/views/layouts/application.html.erb#L7-L8)
```html
<script src="/packs/application-5680934a591ae8f2b1a0.js"></script>
<link rel="stylesheet" media="screen" href="/packs/application-bb8bae90a02ba1aa29ca2a65ffc7a103.css" />
```
This seems to be working as expected, though I have no idea how the `application.css` is being generated with CSS since there is no `application.scss` file in the `app/javascript/packs` directory as their is a `application.js`file. Does anyone know how this is generated? Does it look at the `application.js` and look to see if there are css files imported and adds them to application.css?

When I try to start the application in production though I get no assets rendered at all. I used the following commands locally to test
```bash
NODE_ENV=production RAILS_ENV=production ./bin/rails webpacker:compile
Webpacker is installed 🎉 🍰
Using /Users/matt/Sites/testWebpacker/config/webpacker.yml file for setting up webpack paths
```
and starting the rails server in production using
```ruby
 RAILS_ENV=production rails s
```
Viewing the site both the assets are not loaded, thoughts? 
<img width="601" alt="screen shot 2017-12-22 at 10 34 57 am" src="https://user-images.githubusercontent.com/850602/34303534-d3cd1962-e703-11e7-8b2f-a7b4e4b5c283.png">

**Comment by gauravtiwari** [comment]
You would need to serve static files through Rails: 

```
RAILS_ENV=production RAILS_SERVE_STATIC_FILES=enabled bundle exec rails s
```

**Comment by gauravtiwari** [comment]
Also, please keep anything that's not an entry point outside of `packs` folder. I noticed you have components folder inside `packs` - that can live outside :)

**Comment by melhotiby** [comment]
So your thinking of keeping the components out of the packs folder and right in the app/javascript?

**Comment by melhotiby** [comment]
Also do you know how the application.css is getting created without a application.scss in the packs folder?

**Comment by gauravtiwari** [comment]
> So your thinking of keeping the components out of the packs folder and right in the app/javascript?

Yep unless it's an entry file

**Comment by gauravtiwari** [comment]
> Also do you know how the application.css is getting created without a application.scss in the packs folder?

Because you are importing `blank` module inside Parent https://github.com/gauravtiwari/testWebpacker-1/blob/master/app/javascript/packs/application.js#L1

which has styles etc. 

We use https://github.com/webpack-contrib/extract-text-webpack-plugin to extract any styles in a file with same name as pack (if any)

**Comment by melhotiby** [comment]
@gauravtiwari - Two more questions?
 
1. Is the `RAILS_SERVE_STATIC_FILES` ENV something that we would want to in production in general, since rails defaults to false?

2. Notice my project does not have a app/assets folder and if I want this webpack to compile on capistrano deploy, based on you [documentation](https://github.com/rails/webpacker#deployment). Any suggestions for that? Here is my setup I have
```ruby
# File config/deploy/production.rb
namespace :deploy do
  after  :finishing,    :compile_assets
  after  :finishing,    :cleanup
  after  :finishing,    :restart
end

# File Capfile
...
require ‘capistrano/yarn’
require “capistrano/bundler”
require “capistrano/rails/assets”
...
``` 
Deploy fails to compile
```bash
Tasks: TOP => deploy:assets:precompile
(See full trace by running task with --trace)
The deploy has failed with an error: Exception while executing as deploy@34.229.159.108: rake exit status: 1
rake stdout: Nothing written
rake stderr: rake aborted!
Don’t know how to build task ‘assets:precompile’ (see --tasks)
```
Is this related to not having an assets folder? Is there a good way of compiling webpack during a capistrano deploy?

**Comment by gauravtiwari** [comment]
> Is the RAILS_SERVE_STATIC_FILES ENV something that we would want to in production in general, since rails defaults to false?

Yes, unless you are using something like nginx to server static files from public folder

> 2.

Should work fine, could run it with `--trace` option please (See full trace by running task with --trace)

**Comment by gauravtiwari** [comment]
More documentation on 1. here: http://guides.rubyonrails.org/configuring.html

**Comment by melhotiby** [comment]
I ended up adding `require 'sprockets/railtie'` to `config/application.rb` and it fixed it.

As for serving static files with nginx in production to render the assets for webpack would I need something like 
```bash
location / {
  root /var/app/blank/current/public;
}
```
Any ideas of a good resource for finding out more?
