### ISSUE TITLE
webpacker.yml api config error on heroku

### ISSUE THREAD

**Issue by ansachs** [rails/webpacker#1146]
compiles fine on local, in production node_env, but maybe not on heroku due to dependency versions?
had to write paths as :

 paths:
    src_path: app/javascript
    config_path: config/webpack
    node_modules_path: node_modules
    dist_dir: packs
    dist_path: public/packs

**Comment by gauravtiwari** [comment]
Are you getting any errors on heroku? Just deployed one yesterday on heroku without any problem.

**Comment by ansachs** [comment]
I was getting a webpack API schema error when I tried to compile with the
default package webpacker.yml file. I'm using the default paths in my app

**Comment by gauravtiwari** [comment]
Could you please post your deploy log from heroku?

**Comment by ansachs** [comment]
It looks like there were possibly a bunch of issues, one being that error with translating to the webpack schema that only showed up when i did webpacker:compile and not assets:precompile, the other was possibly with heroku detecting a manifest.json in my test-pack folder.
