### ISSUE TITLE
Question about putting everything under /packs

### ISSUE THREAD

**Issue by bufordtaylor** [rails/webpacker#1147]
From the docs:
```The configuration for what webpack is supposed to compile by default rests on the convention that every file in app/javascript/packs/*(default) or whatever path you set for source_entry_path in the webpacker.yml configuration is turned into their own output files (or entry points, as webpack calls it). Therefore you don't want to put anything inside packs directory that you do not want to be an entry file. As a rule of thumb, put all files you want to link in your views inside "packs" directory and keep everything else under app/javascript.```

I understand *what* to do, but I'm not entirely sure *why* to do it. Can anyone help me out here?

**Comment by akabiru** [comment]
> put all files you want to link in your views inside "packs" directory and keep everything else under app/javascript.

@bufordtaylor I think this is so `javascript_pack_tag` in the erb view can work; so you can have your entry point in packs but keep the rest of the "app" somewhere else. E.g. My setup is usually as follows:
```
frontend/
├── app
│   ├── actions
│   ├── components
│   ├── containers
│   ├── reducers
│   ├── store
│   ├── styles
│   └── utils
└── packs
```

**Comment by eckdanny-osi** [comment]
My project has adopted a "SPA forrest" approach:

```
app/javascript
├── shared
│   ├── components
│   ├── services
│   ├── utils
│   ├── ...
│   └── types
├── foo
│   ├── ...
│   └── index.js
├── bar
│   ├── ...
│   └── index.js
└── packs
    ├── foo.js
    └── bar.js
```

Each file (_entrypoint_) in `packs` is just a one-liner import for side-effect only (the react app boostrap is in the associated _functional-area_'s index.js module) It has helped reduce confusion between our React and Rails devs at the boundary layer)

**Comment by gauravtiwari** [comment]
Thanks @akabiru and @eckdanny-osi 💯  🍰 

Hope the above answers your question @bufordtaylor
