### ISSUE TITLE
Integrations still appear in webpacker.yml

### ISSUE THREAD

**Issue by iainbeeston** [rails/webpacker#1148]
In #1103 integrations were moved out of the default webpacker install, and now have to be added manually. However, the default webpacker.yml still includes extensions for `.jsx`, `.coffee`, `.vue` and `.erb`. Should these be removed from the default webpacker.yml file, and be added by the appropriate installer rake task?

**Comment by iainbeeston** [comment]
Just to be clear, the webpacker.yml file I'm looking at is https://github.com/rails/webpacker/blob/7738e6b2a25b5e35874cf5290a6e680ec10794b0/lib/install/config/webpacker.yml

**Comment by gauravtiwari** [comment]
Good spot 👍 Yes they should be moved to installer.
