### ISSUE TITLE
Breaking `bundle exec`

### ISSUE THREAD

**Issue by stefanvermaas** [rails/webpacker#1150]
After upgrading to version `3.2.0` the deployment of our application broke. After some digging I found that this commit (d9ad255af4287c981980d5f62f024c6685fa46a7) actually broke things as [this line](https://github.com/rails/webpacker/commit/d9ad255af4287c981980d5f62f024c6685fa46a7#diff-d372bcc3fac8ad71a96a2cc49d03bfacL56) was changes. 

When deploying (with Capistrano) the error that occurred said "that it was missing the bundle command" and thus it could not start compiling. After changing the way that Webpack was called, back to the original way of calling Webpack, everything deployed just fine.

```shell
# The error output while compiling
01:22 deploy:assets:precompile
  /usr/local/rvm/bin/rvm 2.4.2 do bundle exec rake assets:precompile
  yarn install v1.3.2
  [1/4] Resolving packages...
  [2/4] Fetching packages...
  [3/4] Linking dependencies...
  [4/4] Building fresh packages...
  Done in 17.86s.
  Webpacker is installed 🎉 🍰
  Using /srv/**/**/releases/20171228142049/config/webpacker.yml file for setting up webpack paths
  Compiling…
  Compilation failed:

  /usr/local/rvm/gems/ruby-2.4.2@global/gems/bundler-1.12.5/lib/bundler/rubygems_integration.rb:373:in `block in replace_bin_path': can't find executable bundle (Gem::Exception)
  	from /usr/local/rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/rubygems.rb:299:in `activate_bin_path'
  	from /usr/local/rvm/gems/ruby-2.4.2@global/bin/bundle:23:in `<main>'
  	from /usr/local/rvm/gems/ruby-2.4.2@global/bin/ruby_executable_hooks:15:in `eval'
  	from /usr/local/rvm/gems/ruby-2.4.2@global/bin/ruby_executable_hooks:15:in `<main>'

  Done in 23.37s
```

```ruby
# Current way of executing Webpack (broken)
sterr, stdout, status = Open3.capture3(webpack_env, "bundle exec webpack")

# Old way of executing Webpack (works)
sterr, stdout, status = Open3.capture3(webpack_env, "#{RbConfig.ruby} ./bin/webpack")
```

We're currently using bundler version `1.12.5` on the servers, could this be the reason that the new version of the gem fails? 

For now I'll just use [our version](https://github.com/stefanvermaas/webpacker) of `webpacker` in which I reverted the change.

**Comment by jpickwell** [comment]
There might be an issue with how Capistrano is calling Ruby on the remote server. I personally am using RVM on the remote server, and Capistrano uses RVM to invoke the correct version of Ruby.

However, I'm using Bundler 1.16.0, Webpacker 3.2.0, and Capistrano 3.10.1.

**Comment by javan** [comment]
@stefanvermaas, it looks like this was fixed in bundler 1.14.0: https://github.com/bundler/bundler/pull/4992

@jpickwell, can you please confirm the Bundler and Ruby versions you're using on the *server*.

**Comment by stefanvermaas** [comment]
@javan Thanks for this link! Seems promising, I'll try to see if we can upgrade bundler on our servers. 

I'll keep you posted about the progress for this.

**Comment by stefanvermaas** [comment]
Just a heads up: updating to the newest version of Bundler did indeed solve the problem. Thanks @javan for pointing this out.

**Comment by jpickwell** [comment]
@javan, sorry for the late reply. The server uses the same version of Bundler and Ruby that I develop with: Ruby 2.4.1, Bundler 1.16.0. (This was the versions at that time, I've since updated to Ruby 2.5.0 and Bundler 1.16.1)
