### ISSUE TITLE
Webpacker modifies the Rails.logger instance

### ISSUE THREAD

**Issue by sveinn** [rails/webpacker#1155]
[This change](https://github.com/rails/webpacker/pull/716/files#diff-50b8c9dee133212dfe72007434531c0dR30) to Webpacker inadvertently modifies `Rails.logger` and `Rails.logger.formatter`; methods are added to their singleton classes. (This happens because of [this line](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/tagged_logging.rb#L64-L65) in `ActiveSupport::TaggedLogging`).

In particular, a [call method](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/tagged_logging.rb#L22) is added, which results in it being executed ahead of the Rails.logger.formatter's call method. The added call method makes the assumption that `msg` is a string ([by interpolating it passes a string to super](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/tagged_logging.rb#L23)), which `msg` need not be. 

This is a problem because it's possible that `Rails.logger.formatter` expects to receive an exception class and not a strings for `msg`, which happened in my case, which is why I am filing this issue.

**Comment by sveinn** [comment]
Here is a test case that reproduces this issue, and should pass once the issue is resolved.

```
def test_rails_logger_should_not_be_modified
    # Set up a rails logger
    rails_logger = Logger.new(StringIO.new)
    rails_logger.formatter = rails_logger.instance_variable_get(:@default_formatter)
    assert_false rails_logger.formatter.respond_to?(:tagged)

    # Do what the 'webpacker.logger' initializer does
    webpacker_logger = ActiveSupport::TaggedLogging.new(rails_logger)
    
    # Webpacker logger is a tagged logger
    assert webpacker_logger.respond_to?(:tagged)
    assert webpacker_logger.formatter.respond_to?(:tagged)

    # Assert that the Rails logger is not modified by webpacker's initializer
    test_object = Object.new
    def test_object.to_s
      raise "to_s called on msg. this means 'call' method has been added by ActiveSupport::TaggedLogging"
    end
    assert_nothing_raised { rails_logger.formatter.call('',Date.new,'',test_object) }

    assert_false rails_logger.respond_to?(:tagged)
    assert_false rails_logger.formatter.respond_to?(:tagged)
  end
```

**Comment by sveinn** [comment]
Here is one idea for a fix:
```ruby
    ...
    # Proposed fix to the 'webpacker.logger' initializer
    temp_logger = rails_logger.dup
    temp_logger.formatter = rails_logger.formatter.dup
    webpacker_logger = ActiveSupport::TaggedLogging.new(temp_logger)
    ...
```
@curvo, @javan and @gauravtiwari I see that you guys were involved in the [original change](https://github.com/rails/webpacker/pull/716) to the initializer. Would love to get your thoughts if you have the time. Thanks!

**Comment by jonleighton** [comment]
I've had trouble with this too. We have a custom logger where `msg` is a hash (it outputs JSON log messages). Due to Webpacker wrapping it in `ActiveSupport::TaggedLogging`, our hashes end up getting turned into strings.

IMO, Webpacker shouldn't require `Rails.logger` to be a `ActiveSupport::TaggedLogging`. If the logger doesn't respond to `tagged` then Webpacker should just not call `tagged` on it.

**Comment by andrewpage** [comment]
Having the same issue as @jonleighton. My structured logging isn't working! Would love to see a fix for this.

**Comment by andrewpage** [comment]
Looks like a fix for this has been included in the [Rails 6 version of ActiveSupport](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/tagged_logging.rb#L63). The `ActiveSupport::TaggedLogger` initializer duplicates the logger that is passed in before extending it, therefore removing this undesired behavior.

Here is a snippet of Ruby code that you can use to import this into your application without needing to fully upgrade. Include this *after* ActiveSupport has been loaded, and *before* Webpacker has. Probably makes sense to stick this between `require 'rails/all'` and `Bundler.require(*Rails.groups)`.

```ruby
# Monkeypatch in Rails 6 ActiveSupport::TaggedLogging initializer.
# Solves problem in which the TaggedLogging initializer modifies an existing logger
# by injecting its own functionality in.
if Rails::VERSION::MAJOR < 6
  module ActiveSupport
    module TaggedLogging
      def self.new(logger)
        logger = logger.dup

        if logger.formatter
          logger.formatter = logger.formatter.dup
        else
          # Ensure we set a default formatter so we aren't extending nil!
          logger.formatter = ActiveSupport::Logger::SimpleFormatter.new
        end

        logger.formatter.extend Formatter
        logger.extend(self)
      end
    end
  end
else
  ActiveSupport::Deprecation.warn('No longer need to monkeypatch ActiveSupport::TaggedLogging!')
end
```

This has solved the problem on my end. Hope this helps.

**Comment by guillaumebriday** [comment]
Is this issue still relevant ?

Or can it be closed ?
