### ISSUE TITLE
Undefined methods for Map property being presented in the docs

### ISSUE THREAD

**Issue by chiefGui** [rails/webpacker#1156]
Hello there! Wish you all a happy new year and many thanks for your efforts on creating and maintaining this great solution that brings esnext to the Rails' world!

Not sure if I'm missing something but in [Webpacker's Webpack docs](https://github.com/rails/webpacker/blob/master/docs/webpack.md#loaders) we have the following code fragment:

```js
// config/webpack/environment.js
const { environment } = require('@rails/webpacker')

environment.loaders.append('json', {
  test: /\.json$/,
  use: 'json-loader'
})

// Insert json loader at the top of list
environment.loaders.prepend('json', jsonLoader)

// Insert json loader after/before a given loader
environment.loaders.insert('json', jsonLoader, { after: 'style'} )
environment.loaders.insert('json', jsonLoader, { before: 'babel'} )

module.exports = environment
```

According to some tests I've made here, `environment.loaders` is, naturally, an ordinary [`Map`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) object:

```js
console.log(environment.loaders instanceof Map) // true
```

Still according to your documentation, `environment.loaders.insert` is possible:

```js
// Insert json loader after/before a given loader
environment.loaders.insert('json', jsonLoader, { after: 'style'} )
```

**BUT!** as we previously saw in the `Map`'s API, it **does not** implement the method `insert`, meaning that it'll leads us to an unexpected result because it's `undefined`:

```js
console.log(typeof environment.loaders.insert) // undefined
```

My question is: am I really missing something or your docs are quite... inaccurate? The "workaround" I found to have greater customisability around my loaders is just using `.set` and `.get`, natively provided by the `Map` object. Of course, it works and it works well, but it contradicts your documentation and has less semantics.

Could you address me where I'm wrong?

Some technical specs to help you help me:

```bash
$ node -v
v9.2.0
$ ./bin/webpack -v
3.10.0
$ ruby -v
ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin16]
```

```ruby
gem 'webpacker', github: 'rails/webpacker', ref: '50f52fcc2516f6206801acba51854bdfafe38ffe'
```

![image](https://user-images.githubusercontent.com/1330257/34544535-0262ddb0-f0ce-11e7-8459-6660702145f2.png)

**Comment by a-axton** [comment]
Thanks, thought I was going crazy. Ran into the same problem with the plugins example in the docs

**Comment by chiefGui** [comment]
@a-axton Haha, I know right? Same here.

**Comment by renchap** [comment]
What is your Webpacker version? `environment.loaders` switched from a Map to a [ConfigList](https://github.com/rails/webpacker/blob/master/package/config_types/config_list.js) in 3.1.0

**Comment by a-axton** [comment]
I am currently on 3.0.2. I should have known to check that! Thanks for clearing that up!

**Comment by javan** [comment]
That environment API [was added in 3.1.0](https://github.com/rails/webpacker/blob/master/CHANGELOG.md#310---2017-12-11). Feel free to reopen if you're using that version or higher. Note: I'm referring to your `package.json`'s `@rails/webpacker` version.
