### ISSUE TITLE
Adding a loader in a correct order (adding eslint-loader)

### ISSUE THREAD

**Issue by leikind** [rails/webpacker#1157]
The problem I am facing is likely me missing something and not a bug, but since the way you configure loaders with Webpacker is somewhat different from the way you do it with pure Webpack I've decided to ask here. Please point me to another place if this is not a bug or not a place for questions.

I have `eslint` installed and integrated with my editor and working well from command line. Now I want to integrate linting in webpack.

I've added `eslint-loader`, and here's how I configure it in `environment.js`:

```js
environment.loaders.prepend('eslint', {
  test: /\.js$/,
  use: [{loader: 'eslint-loader'}]
})
```

When I run `./bin/webpack` I get a big number of linting errors which are actually not present in the source file, for example:

```
/my/project/app/webpack/packs/app.js
  1:22  error  Extra semicolon  semi
  2:19  error  Extra semicolon  semi
  4:33  error  Extra semicolon  semi
```

And in reality this file does not have semicolons:

```
$ cat /my/project/app/webpack/packs/app.js
import '../js/common'
import '../js/app'

import '../stylesheets/app.scss'
```

and linting it from command line shows no errors:

```
$ ./node_modules/.bin/eslint webpack/packs/app.js

```

That can mean only one this: eslint is linting not the original files but already modified files.

Here's the output of `console.log(environment.loaders)`:

```js
ConfigList [
  { key: 'eslint', value: { test: /\.js$/, use: [Object] } },
  { key: 'babel',
    value:
     { test: /\.(js|jsx)?(\.erb)?$/,
       exclude: /node_modules/,
       use: [Object] } },
  { key: 'css', value: { test: /\.(css)$/i, use: [Object] } },
  { key: 'sass',
    value: { test: /\.(scss|sass)$/i, use: [Object] } },
  { key: 'file',
    value:
     { exclude: /\.(js|jsx|coffee|ts|tsx|vue|elm|scss|sass|css|html|json)?(\.erb)?$/,
       use: [Object] } } ]
```       

`eslint` comes first, so I really don't understand what modifies JS files. What am I missing? How do I debug it?

webpacker version: 3.2.0
eslint-loader version: 1.9.0
eslint version: 4.10.0
node version 6.12.3
Rails: 2.4.3

**Comment by renchap** [comment]
You need to add `enforce: "pre",` to your `eslint` loader to ensure it is ran before all other loaders.
This is documented in `eslint-loader` README: https://github.com/MoOx/eslint-loader#usage

You can also append your loader, not prepend it, as loaders are processed from bottom to top.

**Comment by leikind** [comment]
Thank you. 
Changing to append solved it.
