### ISSUE TITLE
Url loader docs example not working

### ISSUE THREAD

**Issue by navied** [rails/webpacker#1158]
The url loader example in the docs here:

https://github.com/rails/webpacker/blob/master/docs/webpack.md#url-loader

Is not working anymore due to the removal of assetHost from #1107 

What would be the proper replacement with the new webpacker version?

**Comment by gauravtiwari** [comment]
Yeah the documentation needs updating. You don't need to specify `publicPath`. 

```js
// config/webpack/loaders/url.js

module.exports = {
  test: [/\.bmp$/, /\.gif$/, /\.jpe?g$/, /\.png$/],
  use: [{
    loader: 'url-loader',
    options: {
      limit: 10000,
      name: '[name]-[hash].[ext]'
    }
  }]
}

// config/webpack/environment.js

const { environment } = require('@rails/webpacker')

environment.loaders.prepend('url', url)
```
