### ISSUE TITLE
bundle exec webpack is so slow

### ISSUE THREAD

**Issue by khiav223577** [rails/webpacker#1160]
Everytime I checkout to another branch, my rails server will get stuck for 30 seconds with the last message: `[Webpacker] Compiling…`.
It seems like it is waiting for `bundle exec webpack` 
https://github.com/rails/webpacker/blob/a192f00e310c9a4901d51a71d4d958e7db05661c/lib/webpacker/compiler.rb#L53-L65

How could I reduce the compiling time?

P.S. I just upgrade `webpacker` from `1.2` to `3.2`, only get a 4 seconds improvement.

**Comment by jarydkrish** [comment]
@khiav223577 reducing compile time with webpack can be project-specific.

Without knowing what packages are part of your project (like your `package.json`), I'm not sure what would cause long compile times.

You could always look into using something like the [hard-source-webpack-plugin](https://github.com/mzgoddard/hard-source-webpack-plugin), as that caches `node_modules` to make webpack builds faster. But that will only make the next compile time faster.

Then you could do something like this (if you only wanted that plugin in development):
```js
// config/webpack/development.js
const HardSourceWebpackPlugin = require('hard-source-webpack-plugin');
const environment = require('./environment');

environment.plugins.prepend(
  'HardSourceWebpackPlugin',
  new HardSourceWebpackPlugin(),
);

const devEnvironment = environment.toWebpackConfig();

devEnvironment.devtool = 'eval-source-map';

module.exports = devEnvironment;
```

**Comment by gauravtiwari** [comment]
@khiav223577 You could use webpack dev server or watcher in development together with rails server for faster compilation.

```
./bin/webpack-dev-server
```

or

```
./bin/webpack --watch --color
```
