### ISSUE TITLE
Yarn integrity check should be silent when it passes

### ISSUE THREAD

**Issue by dhh** [rails/webpacker#1169]
```
$ r c
=> Booting Rails
yarn check v1.3.2
success Folder in sync.
✨  Done in 0.09s.
Loading development environment (Rails 5.2.0.beta2)
irb(main):001:0> 
```

Three lines for the Yarn integrity check every time it runs in development mode is too noisy. It should be silent unless it fails.

**Comment by gauravtiwari** [comment]
Will take a look 👍

**Comment by guilleiguaran** [comment]
Isn't this done in https://github.com/rails/webpacker/pull/1131? if that is the case I think we just need to cut a new release of the gem!!

**Comment by dhh** [comment]
Ha. Yes it is.

**Comment by gauravtiwari** [comment]
Ahh yes, totally forgot. Will make a new release over the weekend.
