### ISSUE TITLE
asset_pack_path + HMR

### ISSUE THREAD

**Issue by timonbandit** [rails/webpacker#1171]
Hi!
i can't use ```asset_pack_path``` with HMR on my dev machine due of 
```
Webpacker can't find theme1.css in /var/www/app/public/packs/manifest.json.
```
it's works for js, but not for css, which i'm using for this:
```
<script>
  loadCSS("<%= asset_pack_path('theme1.css') %>");
</script>
```
i think problem is in helper.rb
```ruby
  def asset_pack_path(name, **options)
    asset_path(Webpacker.manifest.lookup!(name), **options)
  end
```

stylesheet_pack_tag helper is checking if it on dev server or HMR:
```ruby
def stylesheet_pack_tag(*names, **options)
    unless Webpacker.dev_server.running? && Webpacker.dev_server.hot_module_replacing?
      stylesheet_link_tag(*sources_from_pack_manifest(names, type: :stylesheet), **options)
    end
  end
```
Is it ok to send a PR?

**Comment by gauravtiwari** [comment]
Please do 👍

**Comment by timonbandit** [comment]
@gauravtiwari done :+1:

**Comment by maykefreitas** [comment]
Hey guys, I know that it's merged, but, how I'll use `asset_pack_path` for images in development environment? After upgrading to the version 3.2.1, I can't see my images in development env with dev server and hmr enabled.

**Comment by gauravtiwari** [comment]
Yeah this introduced a bug for other asset types. Will fix during the weekend.
