### ISSUE TITLE
Asset helpers should not call Webpacker.dev_server.running? in production

### ISSUE THREAD

**Issue by javan** [rails/webpacker#1173]
`Webpacker.dev_server.running?` opens a socket connection: https://github.com/rails/webpacker/blob/c46d751b12cc7e24661bc76ad5ebebd0e08c7dda/lib/webpacker/dev_server.rb#L12-L17

That's fine for development mode, but no good for production.
https://github.com/rails/webpacker/blob/c46d751b12cc7e24661bc76ad5ebebd0e08c7dda/lib/webpacker/helper.rb#L13-L14
https://github.com/rails/webpacker/blob/c46d751b12cc7e24661bc76ad5ebebd0e08c7dda/lib/webpacker/helper.rb#L30-L31
https://github.com/rails/webpacker/blob/c46d751b12cc7e24661bc76ad5ebebd0e08c7dda/lib/webpacker/helper.rb#L64-L65

Introduced in https://github.com/rails/webpacker/pull/641 and https://github.com/rails/webpacker/pull/1172.

/cc @dhh @gauravtiwari

**Comment by gauravtiwari** [comment]
Good spot 👍  think we need to bypass this check altogether in production or make this block development specific only?

```rb
unless Webpacker.env.development? &&  Webpacker.dev_server.running? && Webpacker.dev_server.hot_module_replacing?
```

**Comment by javan** [comment]
That would work, I suppose. Probably time for a new helper to encapsulate that condition. Another option is to have `Webpacker::DevServer#running?` return false unless `env.development?`.

**Comment by dhh** [comment]
Agree we shouldn’t keep piling on that expression. I vaguely remember something about the dev server being used in test env though? But having this short circuit in #running? seems right.
