### ISSUE TITLE
Commands to generate a component/module/service/route in Angular?

### ISSUE THREAD

**Issue by codef0rmer** [rails/webpacker#1177]
This `rails g controller hello_angular index` generates a rails controller along with associated component/module. What if I want to generate a new Angular Component without a rails route/controller?

**Comment by gauravtiwari** [comment]
@codef0rmer We don't ship any generators with webpacker. You meant to automatically create a angular module and service if `rails g controller hello_angular index` is run?

**Comment by codef0rmer** [comment]
No. When I ran `rails g controller hello_angular index` for the first time, it created all angular specific files such as Controller, Module, etc. But running the same command with a different name does not generate new controller/module.

Do you mean I've to manually create module, controller, services?

**Comment by gauravtiwari** [comment]
Ahh yes, it's generated by angular installer: `bundle exec rails webpacker:install:angular`, which generates a `hello_angular` app as an example. 

Yes please 👍  we don't ship any generators so you can use any tool you like to scaffold your angular app under `app/javascript` and then link necessary packs for the view to render.

**Comment by codef0rmer** [comment]
Thanks!
