### ISSUE TITLE
[Q] Server side rendering

### ISSUE THREAD

**Issue by woniesong92** [rails/webpacker#119]
This is a question, not an issue with the project -- feel free to close it if it shouldn't be here.

In one of my recent projects, I gave up using Rails views completely and used React components instead. The Rails router takes care of the API endpoints and the react router takes care of the views. The controllers would serve the resources in JSON to the react views. One problem I couldn't solve with this setup was server-side rendering.

I think a lot of people will try what I did when webpacker becomes more mature. Do you have an idea  about how to solve server-side-rendering problem when people use Rails as an API backend and use JS to render the views?

**Comment by ytbryan** [comment]
Does this article answer your question ?https://medium.com/technically-speaking/isomorphic-reactjs-app-with-ruby-on-rails-part-1-server-side-rendering-8438bbb1ea1c#.cjlmxjknf

**Comment by woniesong92** [comment]
@ytbryan Unfortunately no 😢 . I tried `react-rails` but it's too tightly coupled with Rails' asset pipeline and isn't intended to work well with other react libraries/tools (e.g. Redux, HMR).

**Comment by renchap** [comment]
We are working on https://github.com/renchap/webpacker-react to provide Webpacker+React integration. Server-side rendering is not done yet, but should be soon.

**Comment by woniesong92** [comment]
@renchap would that be a part of this gem as well?

**Comment by renchap** [comment]
Yes. I outlined how it would work here : https://github.com/renchap/webpacker-react/issues/3

**Comment by woniesong92** [comment]
@renchap oh! So webpacker-react will be merged to rails/webpacker, and rails/webpacker will be merged to rails?

**Comment by woniesong92** [comment]
Great work by the way :smile:

**Comment by renchap** [comment]
I meant that server-rendering would be a part of webpacker-react, which will stay as a separate gem form Webpacker.
I dont think Webpacker will be merged into the main rails repository (for example Sprockets/sprockets-rails are still separate repos), but it will be supported out of the box by Rails 5.1.

**Comment by justin808** [comment]
@woniesong92 @ytbryan Take a look at 

https://github.com/shakacode/react_on_rails

I'm going to take a look today at having it support webpacker. We've got many live projects using server rendering with React and Wepback.

Let me know if you want a Slack invite a [justin@shakacode.com](mailto:justin@shakacode.com). I'm happy to help. We've got a vibrant community working on this topic and over 2700 stars, and, according to nmpjs.com, [over 112K downloads in the last month](https://www.npmjs.com/package/react-on-rails).

**Comment by gauravtiwari** [comment]
@woniesong92 Does it work out? Please consider closing this issue. Thank you everyone for your answers.

**Comment by woniesong92** [comment]
@gauravtiwari thanks for the answers!

**Comment by woniesong92** [comment]
@renchap Hey, thanks for the help before.
Do you know the best practice for server side rendering now that Rails 5.1 is shipped with webpacker? I think using `react-rails` for server side rendering might be a good solution, but wanted to know if there was a better way.

**Comment by justin808** [comment]
@woniesong92 Please take a look a [React on Rails](https://github.com/shakacode/react_on_rails). Many companies use it, including server-side rendering. [Projects](https://github.com/shakacode/react_on_rails/blob/master/PROJECTS.md) and [Kudos](https://github.com/shakacode/react_on_rails/blob/master/KUDOS.md).

**Comment by snuggs** [comment]
I can concur with @justin808. Awesome project. Looking forward to his presentation at NYC.rb ;-) <3

**Comment by deesx** [comment]
react-rails now works with webpacker, so it could bring the best of both worlds (rails + npm, serverside)

With a minimal overhead on configuration - react_on_rails is at the moment the best solution, but the amount procfiles in the getting started's repo have always been very dreadful to me

react-rails let you render a component from a controller, so you ultimately it is even possible to skip the whole 'app/views' folder. You could end up with a minimal integration setup, with most benefits from react and ssr

Currently experiencing, anyone already managed this approach successfully ?

**Comment by justin808** [comment]
@deesx I don't understand your comment in regards to procfiles. You don't need any procfiles. Procfiles are simply a way to easily start up multiple processes.

**Comment by benbonnet** [comment]
@justin808 meant by that; react_on_rails look like another framework rather than a project that would merge into rails with a minimal interface (which I think would be a great improvement). It is sometimes confusing to see it systematically promoted when the 'server side rendering' topic pops up

**Comment by inkhrt** [comment]
am also having issue with my web packer

**Comment by justin808** [comment]
For the record [React on Rails](https://github.com/shakacode/react_on_rails) thoroughly supports React Serve-Side Rendering, along with react-rails, which is, AFAIK, the only other library that supports this. Both of these libraries leverage rails/webpacker for the view helpers and can use the default Webpack configuration **IF** you want the same configuration for both server and client side. However, that would be **unusual** as it's common to use techniques like code-splitting on the client, which makes no sense for server rendering.

**Comment by justin808** [comment]
I just wrote an article on using the pre-release of v4 with React on Rails, including server-side-rendering and concurrent use of the webpack-dev-server.

[Easy React Server Rendering with rails/webpacker v4 and React on Rails
 ](https://blog.shakacode.com/easy-react-server-rendering-with-rails-webpacker-v4-and-react-on-rails-71602276cf4c)

I included a few github repo examples.

**Comment by dachinat** [comment]
Hi, can I use `Rails 5.2.1` with `webpack:react` and server-side rendering today?
Thanks.

**Comment by justin808** [comment]
@dachinat you need to use either https://github.com/shakacode/react_on_rails or https://github.com/reactjs/react-rails/. Both can get the job done. Besides the docs, check out the CHANGELOGs to get a sense of activity in the projects.

* https://github.com/shakacode/react_on_rails/blob/master/CHANGELOG.md
* https://github.com/reactjs/react-rails/blob/master/CHANGELOG.md

**Comment by dachinat** [comment]
@justin808 very nice, thank you
