### ISSUE TITLE
"webpack binstubs not found" when compiling assets on Windows

### ISSUE THREAD

**Issue by Jaroost** [rails/webpacker#1191]
When compiling assets on Windows10 x64
`rails assets:precompile`

I'm getting this error: 
```
C:\Dev\PTMManager\PTMManager>rails assets:precompile
yarn check v1.3.2
warning package.json: No license field
warning No license field
success Folder in sync.
Done in 0.16s.
webpack binstubs not found.
Have you run rails webpacker:install ?
Make sure the bin directory or binstubs are not included in .gitignore
Exiting!
```

I managed to find where it's not working:
In `check_binstubs.rake` there is a call to `Bundler.which("webpack")` this method find the binstub but on Windows this is not an executable so the call to `Bundler.which("webpack")` returns nil.

I temporarly solved this with : (in check_binstubs.rake task)
```
unless Bundler.which("webpack") || Bundler.which("webpack.bat")
```

**Comment by Jaroost** [comment]
OK, good to know, I will use the master branch for now 👍

**Comment by stoivo** [comment]
When I run `webpacker:install` binstub are not created. 

Is this related?

**Comment by gauravtiwari** [comment]
Just pushed a new release.

**Comment by Jaroost** [comment]
Cool will try it tomorrow 👍

**Comment by stoivo** [comment]
@gauravtiwari, is this related to that binstubs are not created on `webpacker:install`

**Comment by gauravtiwari** [comment]
@stoivo They should be created unless you have modified the binstubs path. Locally it works for me with a fresh rails app with webpacker.
