### ISSUE TITLE
Dev server proxy error serving images

### ISSUE THREAD

**Issue by bcm** [rails/webpacker#1192]
I'm importing an image into a React component:

```js
import LogoImage from "./brand-logo.png";
```

When I load a page that renders that component, I get an error on the image request from the dev server proxy:

```
Jan 20, 2018 09:24 AM: Rack app error handling request { GET /packs/components/layout/globalnav/brand-logo-2bf2d6263ba27fded9a0dc15bb283d42.png }
#<TypeError: no implicit conversion of Regexp into Integer>
/Users/bcm/.rvm/gems/ruby-2.4.3@destro/gems/rack-2.0.3/lib/rack/deflater.rb:111:in `[]'
/Users/bcm/.rvm/gems/ruby-2.4.3@destro/gems/rack-2.0.3/lib/rack/deflater.rb:111:in `should_deflate?'
/Users/bcm/.rvm/gems/ruby-2.4.3@destro/gems/rack-2.0.3/lib/rack/deflater.rb:37:in `call'
/Users/bcm/.rvm/gems/ruby-2.4.3@destro/gems/puma-3.10.0/lib/puma/configuration.rb:225:in `call'
/Users/bcm/.rvm/gems/ruby-2.4.3@destro/gems/puma-3.10.0/lib/puma/server.rb:605:in `handle_request'
/Users/bcm/.rvm/gems/ruby-2.4.3@destro/gems/puma-3.10.0/lib/puma/server.rb:437:in `process_client'
/Users/bcm/.rvm/gems/ruby-2.4.3@destro/gems/puma-3.10.0/lib/puma/server.rb:301:in `block in run'
/Users/bcm/.rvm/gems/ruby-2.4.3@destro/gems/puma-3.10.0/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

All JS and CSS assets load successfully through the proxy.

If I turn off the dev server, or if I request the asset directly from the dev server instead of through the proxy, the image request is successful. It only fails going through the proxy.

The issue began when I upgraded from Webpacker 2.0 to 3.0. It remained through each subsequent upgrade to 3.1 and 3.2. It does not occur if I revert back to 2.0. I'm on Rails 5.1.4.

What other information can I provide to help track down the issue? Thanks!

**Comment by gauravtiwari** [comment]
@bcm Have you followed the upgrade instructions (https://github.com/rails/webpacker/blob/master/CHANGELOG.md#breaking-changes-1)? A lot has changed from 2 and 3.

```
bundle update webpacker
yarn add webpacker
```

```
bundle exec rails webpacker:install
```

**Comment by gauravtiwari** [comment]
Also is this happening locally or in production?

**Comment by bcm** [comment]
Yes, I did follow all of those instructions. Everything's working great except for this one thing.

It's only happening locally, through the webpack dev server proxy. Production's just fine.

**Comment by bcm** [comment]
```$ bundle exec rails middleware
use Webpacker::DevServerProxy
use Rack::UTF8Sanitizer
use InvalidPercentEncoding
use ActionDispatch::SSL
use Rack::Sendfile
use FontAssets::Middleware
use ActionDispatch::Static
use ActionDispatch::Executor
use ActiveSupport::Cache::Strategy::LocalCache::Middleware
use Rack::Runtime
use Rack::MethodOverride
use ActionDispatch::RequestId
use RequestStore::Middleware
use ActionDispatch::RemoteIp
use Sprockets::Rails::QuietAssets
use Rails::Rack::Logger
use ActionDispatch::ShowExceptions
use WebConsole::Middleware
use ActionDispatch::DebugExceptions
use BetterErrors::Middleware
use Airbrake::Rack::Middleware
use ActionDispatch::Reloader
use ActionDispatch::Callbacks
use ActiveRecord::Migration::CheckPending
use ActionDispatch::Cookies
use ActionDispatch::Session::CookieStore
use ActionDispatch::Flash
use Rack::Head
use Rack::ConditionalGet
use Rack::ETag
use AlphaRedirect
use AtomRedirect
use OmniAuth::Builder
use Flipper::Middleware::SetupEnv
use Flipper::Middleware::Memoizer
use Gone
use V1Redirect
run Destro::Application.routes```

**Comment by bcm** [comment]
Awesome, thank you. I'm certain that I did something dumb in the upgrade; I just can't figure out what :)

Happy to give you access to the repo if that would be useful.

**Comment by gauravtiwari** [comment]
@bcm Tried reproducing this with a fresh rails app but seems to be working fine - both locally and production - https://github.com/gauravtiwari/webpacker-example-3.2.1

Is it possible you have added some middleware that's conflicting with dev proxy? I have added some of them in example app but not all.

**Comment by bcm** [comment]
It's certainly possible. I do have a few custom middlewares. I'll check.

That said, it seems very strange that only image requests are affected, not JS or CSS...

**Comment by gauravtiwari** [comment]
@bcm Yeah it's possible that the middleware is only applied to static assets like images.

**Comment by MrHubble** [comment]
The problem for me was the `font_assets` gem which was listed in the `bundle exec rails middleware`  results as `use FontAssets::Middleware`. 

`font_assets` is no longer needed with Rails 5 and we can use `rack-cors` instead: https://devcenter.heroku.com/articles/using-amazon-cloudfront-cdn#cors

**Comment by bcm** [comment]
Interesting. Even after removing font_assets and all of my custom middlewares, though, I still get the issue. Gonna have to figure out how to get in there with a debugger.
