### ISSUE TITLE
Should yarn-error.log be added to .gitignore file?

### ISSUE THREAD

**Issue by wiredin** [rails/webpacker#1193]
Should yarn-error.log be added to rails .gitignore automatically during webpacker setup?

**Comment by inkhrt** [comment]
No

**Comment by guilleiguaran** [comment]
yarn-error.log is added automatically in new Rails apps except if yarn is skipped, doing it in webpacker will add repeated entries to the .gitignore file.

See: https://github.com/rails/rails/blob/master/railties/lib/rails/generators/rails/app/templates/gitignore.tt#L31

/cc @gauravtiwari

**Comment by gauravtiwari** [comment]
@guilleiguaran Ahh thanks :). Fixed: https://github.com/rails/webpacker/pull/1197

**Comment by wiredin** [comment]
Thanks everyone! That makes sense, my app was originally rails version 5.0 so it did not already have yarn-error.log in the gitignore.
