### ISSUE TITLE
Space in dir path prevents webpack-dev-server from running

### ISSUE THREAD

**Issue by kobaltz** [rails/webpacker#120]
To replicate this issue, 
- ensure `yarn` is installed (`brew install yarn`)
- create a new Rails 5.1.0.beta1 app with `rails new testapp  --webpack` in a directory hierarchy which has a space in one of the folder names. (`/Users/kobaltz/Test Folder/testapp`)

![image](https://cloud.githubusercontent.com/assets/635114/23336560/916bbbe4-fba1-11e6-96d8-3568a61c20b3.png)

Running `./bin/webpack-dev-server` within the Rails root dir generates the following error

    sh: Folder/testapp/node_modules: No such file or directory

If the space in the parent directory's name is removed, `webpack-dev-server` works.

![image](https://cloud.githubusercontent.com/assets/635114/23336597/4154edfa-fba2-11e6-8488-0e171dc731d9.png)

**Comment by ytbryan** [comment]
So the fix is to escape the path at APP_PATH. 

However, interestingly because Dir.chdir and File.foreach cannot take in a path that is escaped. (is this a bug/flaw on ruby side?) 

Therefore, I simply create a second APP_PATH called APP_PATH2 with the path escaped. Use it on the other paths that depends on it. Try it and let me know if this fix. It's working on my end. 

And thank you for http://driftingruby.com/ :) 

> #!/usr/bin/env ruby
> 
> ENV['RAILS_ENV'] ||= 'development'
> RAILS_ENV   = ENV['RAILS_ENV']
> 
> ENV['NODE_ENV'] ||= RAILS_ENV
> NODE_ENV    = ENV['NODE_ENV']
> 
> APP_PATH = File.expand_path('../', __dir__)
> APP_PATH2 = File.expand_path('../', __dir__).gsub(/ /, "\\ ")
> 
> SET_NODE_PATH  = "NODE_PATH=#{APP_PATH2}/node_modules"
> WEBPACKER_BIN  = "./node_modules/.bin/webpack-dev-server"
> WEBPACK_CONFIG = "#{APP_PATH2}/config/webpack/#{NODE_ENV}.js"
> 
> # Warn the user if the configuration is not set
> RAILS_ENV_CONFIG = File.join("config", "environments", "#{RAILS_ENV}.rb")
> 
> # Look into the environment file for a non-commented variable declaration
> unless File.foreach(File.join(APP_PATH, RAILS_ENV_CONFIG)).detect { |line| line.match(/^\s*[^#]*config\.x\.webpacker\[\:dev_server_host\].*=/) }
>   puts "Warning: if you want to use webpack-dev-server, you need to tell Webpacker to serve asset packs from it. Please set config.x.webpacker[:dev_server_host] in #{RAILS_ENV_CONFIG}.\n\n"
> end
> 
> Dir.chdir(APP_PATH) do
>   exec "#{SET_NODE_PATH} #{WEBPACKER_BIN} --config #{WEBPACK_CONFIG} --content-base #{APP_PATH2}/public/packs #{ARGV.join(" ")}"
> end

**Comment by gauravtiwari** [comment]
Or just use shellwords. Perhaps, needs a PR to fix this 👍 

```ruby
#!/usr/bin/env ruby
require 'shellwords'

ENV['RAILS_ENV'] ||= 'development'
RAILS_ENV   = ENV['RAILS_ENV']

ENV['NODE_ENV'] ||= RAILS_ENV
NODE_ENV    = ENV['NODE_ENV']

APP_PATH = File.expand_path('../', __dir__)
ESCAPED_APP_PATH = APP_PATH.shellescape

SET_NODE_PATH  = "NODE_PATH=#{ESCAPED_APP_PATH}/node_modules"
WEBPACKER_BIN  = "./node_modules/.bin/webpack-dev-server"
WEBPACK_CONFIG = "#{ESCAPED_APP_PATH}/config/webpack/#{NODE_ENV}.js"

# Warn the user if the configuration is not set
RAILS_ENV_CONFIG = File.join("config", "environments", "#{RAILS_ENV}.rb")

# Look into the environment file for a non-commented variable declaration
unless File.foreach(File.join(APP_PATH, RAILS_ENV_CONFIG)).detect { |line| line.match(/^\s*[^#]*config\.x\.webpacker\[\:dev_server_host\].*=/) }
  puts "Warning: if you want to use webpack-dev-server, you need to tell Webpacker to serve asset packs from it. Please set config.x.webpacker[:dev_server_host] in #{RAILS_ENV_CONFIG}.\n\n"
end

Dir.chdir(APP_PATH) do
  exec "#{SET_NODE_PATH} #{WEBPACKER_BIN} --config #{WEBPACK_CONFIG} --content-base #{ESCAPED_APP_PATH}/public/packs #{ARGV.join(" ")}"
end
```

```ruby
#!/usr/bin/env ruby
require 'shellwords'

ENV['RAILS_ENV'] ||= 'development'
RAILS_ENV   = ENV['RAILS_ENV']

ENV['NODE_ENV'] ||= RAILS_ENV
NODE_ENV    = ENV['NODE_ENV']

APP_PATH = File.expand_path('../', __dir__)
ESCAPED_APP_PATH = APP_PATH.shellescape

SET_NODE_PATH  = "NODE_PATH=#{ESCAPED_APP_PATH}/node_modules"
WEBPACK_BIN    = "./node_modules/webpack/bin/webpack.js"
WEBPACK_CONFIG = "#{ESCAPED_APP_PATH}/config/webpack/#{NODE_ENV}.js"

Dir.chdir(APP_PATH) do
  exec "#{SET_NODE_PATH} #{WEBPACK_BIN} --config #{WEBPACK_CONFIG} #{ARGV.join(" ")}"
end
```
