### ISSUE TITLE
Production build breaks browsers which doesn't support `PropertyShorthend`

### ISSUE THREAD

**Issue by pudek357** [rails/webpacker#1211]
Hi everyone 👋 

This [PR](https://github.com/rails/webpacker/pull/1194/files) introduced problem with production build, when we use in code [PropertyShorthend](http://es6-features.org/#PropertyShorthand).

I was trying to investigate this problem and I figured out that the problem is with this [line](https://github.com/rails/webpacker/pull/1194/files#diff-7c25d136c924ad7b0b9e0cfe72f6a1c0R18).
If `ecma` is set to `>= 6` then `UglifyJS` produces for example code:
```
const someVar = 'abc';
const testObj = {
  someVar,
};
```
that production build:
```
const testObj = {  someVar };
```
but should instead:
```
const testObj = {  someVar: someVar  };
```

**Comment by gauravtiwari** [comment]
@pudek357 You could tweak your babelrc with appropriate browser query: http://browserl.ist/?q=%3E%3D+1%25 (this is what we ship with atm)

You could set specific browsers you need to support in your query: https://github.com/ai/browserslist#queries

**Comment by pudek357** [comment]
it's mine `.babelrc`:
```
{
  "presets": [
    [
      "env",
      {
        "modules": false,
        "targets": {
          "browsers": [
            "last 2 versions",
            "> 1%",
            "ie > 10"
          ],
          "uglify": true
        },
        "useBuiltIns": true
      }
    ],
    "react"
  ],
  "plugins": [
    "syntax-dynamic-import",
    "transform-object-rest-spread",
    [
      "transform-class-properties",
      {
        "spec": true
      }
    ]
  ]
}
```

It's work with `"@rails/webpacker": "3.2.0"` when i change version to `3.2.1` then it doesn't uglify properly `PropertyShorthend`

**Comment by gauravtiwari** [comment]
Please try the latest RC, otherwise feel free to open a new issue with more details.
