### ISSUE TITLE
File are not always recompiled

### ISSUE THREAD

**Issue by roine** [rails/webpacker#1213]
I'm using webpacker with elm and when I save my files they first get recompiled but then all the save within the next few minutes won't be recompiled and after that period saving successfully recompiles the files. 

I'm guessing it's that way on purpose, how do I deactivate this?

**Comment by gauravtiwari** [comment]
@roine Are you using watcher or dev server? I am not sure if I understand the issue correctly, could you please share more info?

**Comment by roine** [comment]
dev-server and only happens with elm

**Comment by guillaumebriday** [comment]
Is this issue still relevant ?

Can it be closed if not ?
