### ISSUE TITLE
Asset compile hangs on [Webpacker] Compiling assets 

### ISSUE THREAD

**Issue by Praneeta** [rails/webpacker#1217]
Trying to run NODE_ENV=production RAILS_ENV=development bundle exec rake assets:precompile --trace locally
It basically hangs at [Webpacker] Compiling assets 🎉
I cannot really tell what it's doing then.
I checked my output path packs. The files are generated but are completely empty.
Any suggestions?

I had trouble running webpacker, needed to increase the allocated memory - more about that in #1189 .

**Comment by catskull** [comment]
Compiling assets could take a very long time. How long have you let it run?

**Comment by gauravtiwari** [comment]
@Praneeta Ahh I see, could you run this locally and see what happens: 

```
NODE_ENV=production ./bin/webpack --progress --config config/webpack/production.js
```

**Comment by gauravtiwari** [comment]
Also, how big is the app? Is it using angular? And how are the entry points structured i.e. what do you have in the `packs` folder?

**Comment by Praneeta** [comment]
@gauravtiwari Thanks for the tip on running it directly. Seems like uglifying the files is slowing (@catskull  - it did not finish under 30 mins, then I stopped it.) the process.
If I comment the uglify plugin from production, it compiles in 4 mins.
My app is rather large but I could pull some of it out in chunks. I am trying to make it so that each page in the app (not a single page app) has it's own js file and there is only 1 script tag per page. But seems like this is causing the asset compile process to take forever.

**Comment by Praneeta** [comment]
`webpack.optimize.CommonsChunkPlugin` was a huge help. Cut down the compile time under 5 mins. With the right config, can it get it as low as a minute.

**Comment by gauravtiwari** [comment]
Great 👍 Yeah you can try DLL plugin for further optimisation: https://webpack.js.org/plugins/dll-plugin/

Example: https://github.com/rails/webpacker/issues/702

**Comment by hiveer** [comment]
In my case, I have to set `check_yarn_integrity: false` for 'development' in config/webpacker.yml.
Otherwise you're stuck because of an integrity error.
