### ISSUE TITLE
Blank page when using react + capybara webkit

### ISSUE THREAD

**Issue by mbajur** [rails/webpacker#1219]
Hello!

I've been setting up a new project with react-webpacker frontend. The application is a bare rails application generated with `--webpack=react` option and some additional gems but i doubt they are the reason.

Anyway - for some misterious reason, when i'm trying to run the simplest feature spec, capybara can't seem to render my react component and sees the app as a blank white page instead. capybara-screenshot shows me that pack javascript file is included in rendered page head but i can't see the request for it in test logs. Also, it seems there are no any javascript errors present in the webkit console. I have tested the same setup in selenium/firefox and it was working fine. I'm not fully sure if that's even a webpack issue but i decided to start here.

I've created a sample repository to reproduce my issue, you can get it here:
https://github.com/mbajur/webkit-webpacker-demo

```
$ bundle
$ yarn install
$ rake db:setup
$ spinach # or rspec, i've included both spinach and rspec feature specs and they act the same
```

Thank you in advance for any clues or help!

**Comment by renchap** [comment]
`capybara-webkit` is based on QTWebkit, itself based on an old Webkit version. This version does not support modern JS features (ES2015/ES6).
Your JS code is most probably not transpiled to run on those old browsers, so the JS code cant be executed.

You need to change the supported browsers in your `.babelrc` file to include a Safari version as old as the Webkit version used in `capybara-webkit`.
Another source of errors is missing polyfills, you should ensure you have `import "babel-polyfill"` in the first JS file loaded on your page (and `babel-preset-env` will then ensure the needed core polyfills are loaded).

A better way to fix this would be to switch away from capybara-webpack. Rails 5.1+ includes [system tests](http://guides.rubyonrails.org/testing.html#system-testing) to integrate with Capybara, and now that Chrome supports a true headless mode `capybara-webpack` is far less useful. With Rails 5.1, I use this in my `application_system_test_case.rb` file (you need Chrome installed locally):

```ruby
Capybara.register_driver(:headless_chrome) do |app|
  capabilities = Selenium::WebDriver::Remote::Capabilities.chrome(
    chromeOptions: { args: %w[headless window-size=1600x1080] },
  )

  Capybara::Selenium::Driver.new(
    app,
    browser: :chrome,
    desired_capabilities: capabilities,
  )
end

class ApplicationSystemTestCase < ActionDispatch::SystemTestCase
  #driven_by :selenium, using: :chrome, screen_size: [1600, 1200]
  driven_by :headless_chrome
end
```

With Rails 5.2, you can simply use `driven_by :selenium, using: :headless_chrome` as support is built-in.

**Comment by mbajur** [comment]
Yes, that was it @renchap, thank you so much for such comprehensive reply. Registering a new driver with headless chrome fixed that just like that.
