### ISSUE TITLE
Cannot test with Internet explorer with webpack-dev-server

### ISSUE THREAD

**Issue by cshupp1** [rails/webpacker#1221]
Environment:
```
    Windows 10
    webpacker (3.2.1)
    rails (5.1.4)
    JRuby 9.1.15.0
```

While developing in development mode with webpack-dev-server if you attempt to test your UI with IE11 this is your error:

```
/***/ }),
/* 65 */
/*!*************************************************************!*\
  !*** (webpack)-dev-server/node_modules/strip-ansi/index.js ***!
  \*************************************************************/
/*! dynamic exports provided */
/*! all exports used */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

const ansiRegex = __webpack_require__(/*! ansi-regex */ 66);

module.exports = input => typeof input === 'string' ? input.replace(ansiRegex(), '') : input;
```

The last line being what IE dislikes (it won't eat the arrow).

Attempts to add *transform-es2015-arrow-functions* to .bablerc are of no use.  This sent me to to the babeljs slack channel where @loganfsmyth helped me to analyze the situation.  The good news is spinning a war and running in production fixes the problem.  Logan helped to discover that the naughty library is only used with *webpack-dev-server*.

Apparently strip-ansi 4.0 uses the arrow while 3.0.1 does not.

Yarn list shows:
```
├─ webpack-dev-server@2.11.0
│  *bunch of deleted stuff*
│  ├─ strip-ansi@^4.0.0
│  ├─ strip-ansi@4.0.0
│  │  └─ ansi-regex@^3.0.0
 *bunch of deleted stuff*
```

Could we please support developing with IE11?

Thanks,

Cris

**Comment by cshupp1** [comment]
I have been advised on the bablejs slack channel to let you know that upgrading web-pack-dev-server to:
2.11.1 will resolve this issue.

**Comment by arunshan** [comment]
@cshupp1 Were you able to resolve that issue on IE11? I am currently facing that issue.

**Comment by cshupp1** [comment]
@arunshan, not in development mode.  Compile your assets via rake assets:precompile and it will work in IE.

**Comment by cshupp1** [comment]
@arunshan, I just tried running 'webpack' in rails root, not webpack-dev-server.  That also worked worked with IE.

**Comment by gauravtiwari** [comment]
You could run watcher if webpack-dev-server is causing issues: 

`
./bin/webpack --watch --progress --color 
```

or upgrade to 2.11.1 as advised

**Comment by cshupp1** [comment]
For those that thought (as I did) that this gem mandates your version of webpack-dev-server, it doesn't.

I ran:
```
yarn upgrade webpack-dev-server
```
This upgraded me to 2.11.1 which does work with IE.

**Comment by cshupp1** [comment]
@arunshan Above is your fix!
