### ISSUE TITLE
Webpack v4

### ISSUE THREAD

**Issue by mikecx** [rails/webpacker#1224]
Didn't see another issue in the search for it but with [Webpack v4](https://medium.com/webpack/webpack-4-beta-try-it-today-6b1d27d7d7e2) on the horizon and potentially being a stable release in about a month, is there work being done to update webpacker? The promise of less configuration, better build speeds, and smaller builds already has me excited.

**Comment by gauravtiwari** [comment]
@mikecx Thanks - yep once stable version is released.

**Comment by renchap** [comment]
Webpack v4 is now released: https://github.com/webpack/webpack/releases/tag/v4.0.0

Do you already have a defined plan to switch to it? It brings a whole lot of goodness.

**Comment by guilleiguaran** [comment]
@renchap there is any upgrade guide for Webpack 3 -> 4?

**Comment by renchap** [comment]
The migration guide is not yet published (https://github.com/webpack/webpack.js.org/issues/1706).

The one for the alpha version is mostly up-to-date and should be fine: https://github.com/webpack/webpack/issues/6357 (at the end of the top post)

Other useful links:
- Announcement: https://medium.com/webpack/webpack-4-released-today-6cdb994702d4
- Release notes: https://github.com/webpack/webpack/releases/tag/v4.0.0
- Migration guide for plugin and loaders authors: https://medium.com/webpack/webpack-4-migration-guide-for-plugins-loaders-20a79b927202

**Comment by rhazegh** [comment]
Looking forward to using webpack 4.0. 

Hopefully it will help with lengthy build times on heroku.

**Comment by dbalatero** [comment]
@gauravtiwari do you need assistance with getting webpack v4 working? I'd be glad to help if so.

**Comment by gauravtiwari** [comment]
Thanks @dbalatero 🍫 

I was thinking to do some groundwork (#1304 ) first before making an upgrade to v4. Also, noticed one of the plugins we use i.e. manifest plugin is still in RC. Would be great if you could help with some reviewing later :)

**Comment by renchap** [comment]
I can also help if needed (testing or implementing). But we need to coordinate to not do the work twice :)

**Comment by gauravtiwari** [comment]
Just published a pre-version with initial Webpack 4.0 support: 

To try out: 

```
gem 'webpacker', '>= 4.0.x'
```

```
yarn add @rails/webpacker
```

**Comment by faceyspacey** [comment]
@gauravtiwari awesome!! Gonna try it out now.

**Comment by adaam2** [comment]
Even after upgrading `@rails/webpacker`, I was still running into this problem. However there is another solution to fix this issue, which is by using `resolutions` to ensure that the `webpacker` version of `extract-text-webpack-plugin` is the new webpack v4 one:

```
"resolutions": {
    "@rails/webpacker/extract-text-webpack-plugin": "^4.0.0-beta.0"
  }
```

**Comment by gauravtiwari** [comment]
@adaam2 Webpacker is using mini-css-extract-plugin now - https://github.com/rails/webpacker/blob/master/package.json#L28

Have you upgraded both npm package and ruby gem including deps?

**Comment by adaam2** [comment]
I'll take a look at this tonight. I believe my Webpacker dep definition in my package.json is `^4.0.0-pre.2` and my Gemfile version is `^4.0.0-pre.2`

**Comment by JakeLaCombe** [comment]
Is there by chance a timeline available for when it will be officially released?

**Comment by zedtux** [comment]
@adaam2's solution works fine for me, thank you !!
