### ISSUE TITLE
Import matches wrong file

### ISSUE THREAD

**Issue by IgorDmitriev** [rails/webpacker#1225]
I was upgrading project to most recent webpacker version `3.2.1` (from `3.0.2`) and got hit by this new behavior:
```
|- Hello.css
|- Hello.jsx
|- index.js
```

When we have stylesheets file name the same as a javascript file name and using import without specifying an extension, for some reason now it would import CSS file.

Expected behavior: if we are not specifying extension, lookup for files string with javasctipt files `js`->`jsx`-> styles -> other files.

Here is a sample code for these files, to reproduce.

```
// index.js
import React from 'react';
import ReactDOM from 'react-dom';
import Hello from './Hello';

document.addEventListener('DOMContentLoaded', () => {
  ReactDOM.render(
    <Hello name="React" />,
    document.body.appendChild(document.createElement('div')),
  );
});
```

```
// Hello.jsx
import React from 'react';
import './Hello.css';

const Hello = ({ name }) => <h1>Hello, {name}!</h1>;

export default Hello;
```

```
/* Hello.css */
body {
  background-color: #222;
  color: #fff;
}
```

I was able to reproduce it with clean repo after `rails new myapp --webpack=react`.

**Comment by gauravtiwari** [comment]
Can you please share how extensions are configured in webpacker.yml?

```yml
  extensions:
    - .js
    - .jsx
    - .sass
    - .css
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg
```

**Comment by IgorDmitriev** [comment]
We have these extensions mentioned there, I think it's a default. I see the same list in a new rails app.
```yml
  extensions:
    - .jsx
    - .js
    - .sass
    - .scss
    - .css
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg
```

I already tried to remove `scss`, `css`, `sass` from this list didn't help. Same with rearrangement. 

Also, I noticed, when I intentionally trying to import some file that doesn't exist, I'm getting this stack trace with the same ordering no matter how we set it in `webpacker.yml` file.

```
[webpacker-test/app/javascript/hello/HelloS]
[webpacker-test/app/javascript/hello/HelloS.js]
[webpacker-test/app/javascript/hello/HelloS.sass]
[webpacker-test/app/javascript/hello/HelloS.scss]
[webpacker-test/app/javascript/hello/HelloS.css]
[webpacker-test/app/javascript/hello/HelloS.png]
[webpacker-test/app/javascript/hello/HelloS.svg]
[webpacker-test/app/javascript/hello/HelloS.gif]
[webpacker-test/app/javascript/hello/HelloS.jpeg]
[webpacker-test/app/javascript/hello/HelloS.jpg]
[webpacker-test/app/javascript/hello/HelloS.jsx]
[webpacker-test/app/javascript/hello/HelloS]
```

When I'm removing extensions from `webpacker.yml` list, they would still be attempted to load here. Only removing `jsx` extension affect this list, and seems like no matter where it listed in the config file, it will be at the end of file search.

**Comment by IgorDmitriev** [comment]
I think it's in a `@rails/webpacker` part, where we are merging `defaultConfig` with `appConfig`.
https://github.com/rails/webpacker/blob/master/package/config.js

Removing `extensions` key from `defaultConfig` if it presented in `appConfig` helped:
```
const defaultConfig = safeLoad(readFileSync(defaultFilePath), 'utf8')[environment]
const appConfig = safeLoad(readFileSync(filePath), 'utf8')[environment]

if (appConfig.extensions !== undefined) delete defaultConfig.extensions

const config = deepMerge(defaultConfig, appConfig)
```

**Comment by IgorDmitriev** [comment]
https://github.com/rails/webpacker/pull/1253 fixed it.
