### ISSUE TITLE
Webpack binstubs were generating incorrect paths for a heroku deploy

### ISSUE THREAD

**Issue by corinnekunze** [rails/webpacker#1226]
I'm currently running webpacker `3.1` and react_on_rails `10.0.2`

Everything was working peachy until I attempted to get things up on production via heroku and was getting this:

```
remote: -----> Preparing app for Rails asset pipeline
remote:        Running: rake assets:precompile
remote:        ReactOnRails: Set generated_assets_dir to default: public/webpack/production
remote:        cd /tmp/build_fa0e794cfc67cd6cc34ea7412d22026f && RAILS_ENV=production bin/webpack
remote:        bin/webpack:14:in `load': cannot load such file -- /tmp/build_fa0e794cfc67cd6cc34ea7412d22026f/vendor/ruby/2.4.0/gems/webpacker-3.2.0/exe/webpack (LoadError)
remote:        from bin/webpack:14:in `<main>'
remote:        rake aborted!
remote:        Command failed with status (1): [cd /tmp/build_fa0e794cfc67cd6cc34ea7412d22...]
remote:        /tmp/build_fa0e794cfc67cd6cc34ea7412d22026f/vendor/bundle/ruby/2.3.0/gems/react_on_rails-10.0.2/lib/tasks/assets.rake:64:in `block (3 levels) in <top (required)>'
remote:        /tmp/build_fa0e794cfc67cd6cc34ea7412d22026f/vendor/bundle/ruby/2.3.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
remote:        Tasks: TOP => assets:precompile => react_on_rails:assets:compile_environment => react_on_rails:assets:webpack
remote:        (See full trace by running task with --trace)
remote:  !
remote:  !     Precompiling assets failed.
remote:  !
remote:  !     Push rejected, failed to compile Ruby app.
remote: 
remote:  !     Push failed
```

Basically what was happening was the bin files that were generated looked like this:
```
# bin/webpack
require "pathname"
path = Pathname.new(__FILE__)
$:.unshift File.expand_path "../../vendor", path.realpath

require "bundler/setup"
load File.expand_path "../../vendor/ruby/2.4.0/gems/webpacker-3.2.0/exe/webpack", path.realpath
```

I took a look at this repo (https://github.com/shakacode/react-webpack-rails-tutorial/tree/master/bin) and grabbed the binstubs from there for both `webpack` and `webpack-dev-server` that look more like this:

```
#bin/webpack
require "pathname"
ENV["BUNDLE_GEMFILE"] ||= File.expand_path("../../Gemfile",
  Pathname.new(__FILE__).realpath)

require "rubygems"
require "bundler/setup"

load Gem.bin_path("webpacker", "webpack")
```

Then I was able to deploy successfully. 

I'm not 100% - is there a way that these need to get generated differently or is this some weirdness with react_on_rails?

**Comment by gauravtiwari** [comment]
@corinnekunze Are you using same bundler and ruby version - both on heroku and locally? Perhaps consider upgrading bundler.

**Comment by corinnekunze** [comment]
Hi @gauravtiwari - looks like even when both versions are the same I run into the same issue.

I believe that these binfiles are being changed from the webpacker default binfiles when `react_on_rails` installs. 

So in this case I'm thinking I'll need to open an issue there since it looks like the default webpacker binfiles included with webpacker should work correctly with heroku.
