### ISSUE TITLE
can't run the production serveur (Ubuntu): how to set webpacker.yml value of compile to true for your env

### ISSUE THREAD

**Issue by regiomag** [rails/webpacker#1227]
Hello, 
I saw many similar issue, tried many fixes but i am still stucked. I hope someone can help we. 

I am pushing my rails 4.2.8 react-redux app to production. The app runs fine on local serveur but can't make it run on production. My production serveur is running on Ubuntu 16.04.3 

**When  loading a page, I do get the error :** 

ActionView::Template::Error (Webpacker can't find application.js in /var/www/lb_4.2/releases/20180127140601/public/packs/manifest.json. Possible causes:
1. You want to set webpacker.yml value of compile to true for your environment
   unless you are using the `webpack -w` or the webpack-dev-server.
2. webpack has not yet re-run to reflect updates.
3. You have misconfigured Webpacker's config/webpacker.yml file.
4. Your webpack configuration is not creating a manifest.
Your manifest contains:
{
}

**I did install on my production serveur:**
yarn 1.3.2
I did install : 
bundle exec rake webpacker:install  
bundle exec rake webpacker:install:react

**Here is the content of my webpacker.yml**

> #

 Note: You must restart bin/webpack-dev-server for changes to take effect

default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_output_path: packs
  cache_path: tmp/cache/webpacker

  # Additional paths webpack should lookup modules
  # ['app/assets', 'engine/foo/app/assets']
  resolved_paths: []

  # Reload manifest.json on all requests so we reload latest compiled packs
  cache_manifest: false

  extensions:
    - .jsx
    - .js
    - .sass
    - .scss
    - .css
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg

development:
  <<: *default
  compile: true

  # Reference: https://webpack.js.org/configuration/dev-server/
  dev_server:
    https: false
    host: localhost
    port: 3035
    public: localhost:3035
    hmr: false
    # Inline should be set to true if using HMR
    inline: true
    overlay: true
    compress: true
    disable_host_check: true
    use_local_ip: false
    quiet: false
    headers:
      'Access-Control-Allow-Origin': '*'
    watch_options:
      ignored: /node_modules/

test:
  <<: *default
  compile: true

  # Compile test packs to a separate directory
  public_output_path: packs-test

production:
  <<: *default

  # Production depends on precompilation of packs prior to booting for performance.
  compile: false

  # Cache manifest.json for performance
  cache_manifest: true

> 

In my config/environment.rb, It seems I am on production env
# Load the rails application
require File.expand_path('../application', __FILE__)

# Initialize the rails application
WebLbb::Application.initialize!

ENV['RAILS_ENV'] ||= 'production'

> 
**In my local, I do have public/packs/manifest.json**
{
  "application.js": "/packs/application-93fc893609a00214bb86.js",
  "application.js.map": "/packs/application-93fc893609a00214bb86.js.map",
  "hello_react.js": "/packs/hello_react-8f27acc82abd43b36575.js",
  "hello_react.js.map": "/packs/hello_react-8f27acc82abd43b36575.js.map"
}

I did not push that one to production

- How to set webpacker.yml value of compile to true for your environment ? 
- What am I missing

Thank you for your help

Best regards

**Comment by gauravtiwari** [comment]
@regiomag You don't need to reinstall webpacker on production but make sure assets are precompiled. Are you compiling or compiled sprockets assets locally?

```
bundle exec rails assets:precompile
```

Is this being run as part of deployment?

**Comment by regiomag** [comment]
Hello, Thank you for your answer. 

Do you mean I shall precompile in local before deploying or shall I precomile on production only ?

How do I know if I am compiling or compiled sprockets assets locally ?

assets/stylesheets/application.scss:
@import "bootstrap-sprockets";
@import "font-awesome-sprockets";

assets/javascripts/application.js:
@import "bootstrap-sprockets";
@import "font-awesome-sprockets";

/bin/sprockets:
require "bundler/setup"
load Gem.bin_path("sprockets", "sprockets")

config/application.rb:
require 'sprockets/railtie'

**Comment by gauravtiwari** [comment]
@regiomag How are your deploying your application - capistrano?

**Comment by regiomag** [comment]
Yes, I am deploying it with capistrano

**Comment by gauravtiwari** [comment]
Right and is this being run as part of deployment? `assets:precompile`

**Comment by regiomag** [comment]
This is my cap file: 
# Load DSL and set up stages
require "capistrano/setup"

# Include default deployment tasks
require "capistrano/deploy"

# Load the SCM plugin appropriate to your project:
#
# require "capistrano/scm/hg"
# install_plugin Capistrano::SCM::Hg
# or
# require "capistrano/scm/svn"
# install_plugin Capistrano::SCM::Svn
# or
require "capistrano/scm/git"

# Thinking Sphinx deploying via Capistrano
require 'thinking_sphinx/capistrano'

install_plugin Capistrano::SCM::Git

# Include tasks from other gems included in your Gemfile
#
# For documentation on these, see for example:
#
#   https://github.com/capistrano/rvm
#   https://github.com/capistrano/rbenv
#   https://github.com/capistrano/chruby
#   https://github.com/capistrano/bundler
#   https://github.com/capistrano/rails
#   https://github.com/capistrano/passenger
#
require "capistrano/rvm"
# require "capistrano/rbenv"
# require "capistrano/chruby"
require "capistrano/bundler"
# require "capistrano/rails/assets"
# require "capistrano/rails/migrations"
require "capistrano/passenger"

# Load custom tasks from `lib/capistrano/tasks` if you have any defined
Dir.glob("lib/capistrano/tasks/*.rake").each { |r| import r }


In my application.rb, I do have: 

require 'sprockets/railtie'
Bundler.require(:default, Rails.env)
module WebLbb
  class Application < Rails::Application
    config.assets.enabled = true
    config.assets.compile = true
    config.assets.version = '1.0'
  end
end

**Comment by regiomag** [comment]
@gauravtiwari thank you, I did run 
bundle exec rake assets:precompile
from my production serveur and I am now able to see the built.

Thank you for your support and best regards

**Comment by gauravtiwari** [comment]
Is 'deploy/assets' included in your Capfile?

**Comment by inkhrt** [comment]
I need a server virus.
