### ISSUE TITLE
asset_pack_path doesn't work for css files when HMR running

### ISSUE THREAD

**Issue by djforth** [rails/webpacker#1233]
So I'm using css-hot-reloader as opposed to writing a bunch of additional JS to inject css inline.

Now you had by default forced that the =stylesheet_pack_tag will return nothing if HMR is on.  I managed to work round this by using the following:

```
  <link rel="stylesheet" href="<%=asset_pack_path(("application.css") %>" media="all">
```
However in webpacker 3.2.1, you seem to have changed it so that it returns undefined.

Can we allow some way to disable this functionality?

for example in the config:

    hmr: true
    # Inline should be set to true if using HMR
    inline: false # <-This doesn't do anything be useful if it did

**Comment by djforth** [comment]
I'm going to bump this issue and am happy to fix this if it is approved.

So in the webpacker.yml you have the following:

```
  dev_server:
    ...
    hmr: false
    # Inline should be set to true if using HMR
    inline: true # <= This doesn't do anything.
```

But in the helper it does not look if inline is true, just if the dev server is running and hmr is set.

```
def asset_pack_path(name, **options)
    unless stylesheet?(name) && Webpacker.dev_server.running? && Webpacker.dev_server.hot_module_replacing?
      asset_path(Webpacker.manifest.lookup!(name), **options)
    end
  end
```

Meaning if like me you are using css-hot-reloader (Which works fine if you disable your browser cache) .  Can I please put a fix in that says if inline is false it renders the path? As I am simply making the functionality work this should effect anyone set up that are loading via js.

**Comment by gauravtiwari** [comment]
@djforth Apologies for delay. May be we can have a new helper method that doesn't check for hmr and just returns what's in manifest?

**Comment by djforth** [comment]
No problem, as I say monkey patched the method for now. That would work too, whatever way would cause the least issues imo.  What would we call the method asset_pack_force_path or something?

I can write up some documentation if you like on how to set up css-hot-loader too if that would be helpful?

**Comment by coorasse** [comment]
Yes. That would be helpful since it doesn't work also for me at the moment and I didn't really get how to monkey patch it for now

**Comment by djforth** [comment]
Sorry I've been heads deep on a react-native project so haven't had a chance to look at it.  The monkey patch is fairly easy, just add the following into your application_helper:

```
def asset_pack_path(name, **options)
    path = super(name)
    return path if path
    asset_path(Webpacker.manifest.lookup!(name), **options)
  end

```

Then in your layout:

> <link rel="stylesheet" href="<%=asset_pack_path("application.css") %>" media="all">

I'll try to add a fix & pull request this weekend.

**Comment by guillaumebriday** [comment]
Is this issue still relevant? Feel free to reopen if needed
