### ISSUE TITLE
Using ERB

### ISSUE THREAD

**Issue by jonhue** [rails/webpacker#1242]
I want to access settings specified with the config gem from within my assets.

Using sprockets, I am able to add `.erb` to the filename and then just use:

```js
var key = '<%= Settings.key %>';
```

How am I able to do the same thing using webpack(er)?

**Comment by sergiolombrico** [comment]
You can, but need to use the 'rails-erb-loader' in your webpack config...

**Comment by jonhue** [comment]
@sergiolombrico 

After adding the ERB loader and adding the file extension to my `application` pack, I am getting the following error:

```
ERROR in ./app/webpack/packs/application.js.erb
Module build failed: Error: spawn bin/rails ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
 @ multi (webpack)-dev-server/client?http://localhost:3035 ./app/webpack/packs/application.js.erb
```

**Comment by ytbryan** [comment]
please provide more info ie application.js.erb and your loader file
