### ISSUE TITLE
Files under bin folder are not created

### ISSUE THREAD

**Issue by gogainda** [rails/webpacker#1247]
Files under bin folder are not created if gemfile has dependencies like:
```
gem 'sorcery', git: 'https://github.com/NoamB/sorcery.git'
```
When you run ```bundle exec rake webpacker:install``` it will say that sorcery should be installed using bundle install, after that it will move to the next installation section and bin folder will stay unchanged.

I am using rail 4.2

**Comment by gauravtiwari** [comment]
Have you tried running `bundle` and then `bundle exec rake webpacker:install` after?
