### ISSUE TITLE
App cannot serve pack files in production

### ISSUE THREAD

**Issue by sergiolombrico** [rails/webpacker#1249]
I am fairly new to the rails 5.x environment with webpack. I cannot explain why my production environment does not serve my files from webpack.

Environment info:

> Rails version             5.1.4
> Ruby version              2.4.1-p111 (x86_64-darwin14)
> RubyGems version          2.6.11
> Rack version              2.0.4

Created a new project without sprockets and coffee but with webpacker.

> rails new az --skip-sprockets --skip-coffee --webpack

Modified the layout file to only reference my **application.scss** located in **az/app/javascript/packs**

```
<!DOCTYPE html>
<html>
  <head>
    <title>Az</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_pack_tag    'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>
```
I have no Javascript file in my packs directory.

When working in my development environment I do not perceive of any problems, i.e. no errors are reported in the console as a result of a 404. The application stylesheet is made available as follows:

`<link rel="stylesheet" media="screen" href="/packs/application-73c6fedf3688dd93c7c203db5e155723.css">`

The problem occurs in production mode in my own environment. I do this as follows:

`rake webpacker:compile`

and next

`rails s -e production`

The server starts but it prompts with the following message:

> GET http://localhost:3000/packs/application-73c6fedf3688dd93c7c203db5e155723.css net::ERR_ABORTED

even though the file is present in public/packs which contains the following:

> application-73c6fedf3688dd93c7c203db5e155723.css
> application-73c6fedf3688dd93c7c203db5e155723.css.map
> application-b527cfda47d2fc1b2b2a.js
> application-b527cfda47d2fc1b2b2a.js.map
> manifest.json

which the manifest contains the following:

```
{
  "application.css": "/packs/application-73c6fedf3688dd93c7c203db5e155723.css",
  "application.css.map": "/packs/application-73c6fedf3688dd93c7c203db5e155723.css.map",
  "application.js": "/packs/application-b527cfda47d2fc1b2b2a.js",
  "application.js.map": "/packs/application-b527cfda47d2fc1b2b2a.js.map"
}
```

**Comment by gauravtiwari** [comment]
@sergiolombrico Great, Yep that's correct unless you are serving it through CDN or nginx.

**Comment by devmtnaing** [comment]
if you don't want to enable `public_file_server`, you can still define the `public_output_path` in webpacker.yml file as `public_output_path: assets/packs` which will generate to `public/assets/packs` instead of `public/packs`

**Comment by zoran** [comment]
Please do not set `config.public_file_server.enabled = true` but
```
config.public_file_server.enabled = ENV['RAILS_SERVE_STATIC_FILES'].present?
```

and run `RAILS_SERVE_STATIC_FILES=true bin/rails s -e production`

**Comment by vidukapoor** [comment]
> @sergiolombrico did you ever get it working on production? I'm deploying via capistrano. When I ssh into the server, I can see the webpacker files in the public directory. I did what @devmtnaing said, and set the`public_output_path: assets/packs`. With that, in my public directory I have `public/assets/packs` which I think is how it should be. The problem I'm having now is that when I try and load the production app via browser, i get
> 
> `GET http://mydomain.com.com/assets/packs/application-a92f8824a2be8ce119c9a85ad9428f2a.css net::ERR_ABORTED 404 (Not Found)`
> 
> `GET http://mydomain.com/assets/packs/application-62f0629fe4e28ed155f9.js 404 (Not Found)`
> 
> Local dev I don't have any issues.
> 
> Any thoughts?


Hi @Lasvad any hits on your issue? 
In my case **docker** configuration is on top of **webpacker, rails, capistrano.**
I am getting this error, 
> GET https://mydomain.com/packs/application-c61326f76533681a238f.js net::ERR_ABORTED 404 (Not Found)

> /app/javascript/packs/application.js
console log on the given path is also not coming, working all in case of local setup

**Comment by Apokly** [comment]
Hi @vidukapoor , did you find a solution ?

**Comment by vidukapoor** [comment]
@Apokly sorry to say, any of the given solutions are not working out, so i opted out from webpacker, due to less limeline to start the project, will try again in upcoming project.
Here i noticed the problem is with docker based production setup only.

**Comment by Apokly** [comment]
@vidukapoor If it can help you, found a workaround using :
```ruby
config.serve_static_files = true
```

My application is running on rails 4 (currently migrating to rails 5).

**Comment by vidukapoor** [comment]
@Apokly I don't have `config.serve_static_files = true` config in my `/config/environments/production.rb`, in place of this I have `config.public_file_server.enabled = ENV['RAILS_SERVE_STATIC_FILES'].present?` , sure will try with https://github.com/rails/webpacker/issues/1249#issuecomment-456047305 also.

Adding to this, I am already on `rails 5`.

**Comment by frbl** [comment]
@vidukapoor any luck?

**Comment by vidukapoor** [comment]
sorry, @frbl due to less time, i had moved to stand alone application of `REACT`

**Comment by frbl** [comment]
Ok, no problem! We managed to solve our problem using this dockerfile

```docker

FROM ruby:2.6.1

ARG precompileassets

# Needed for Yarn
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev curl software-properties-common && \
  curl -sL https://deb.nodesource.com/setup_10.x |  bash - && \
  curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
  echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
  apt-get update && \
  apt-get install -y nodejs yarn && \
  apt-get remove -y --purge curl software-properties-common &&\
  rm -rf /var/lib/apt/lists/*

RUN mkdir /app
WORKDIR /app

## THIS CAUSED US A LOT OF TROUBLE WITH PRECOMPILING!
# VOLUME /app


RUN gem install bundler


COPY package.json /app/package.json
COPY yarn.lock /app/yarn.lock
RUN yarn install

COPY Gemfile /app/Gemfile
COPY Gemfile.lock /app/Gemfile.lock
RUN bundle config --global frozen 1 \
  && bundle install \
  && rm -rf /usr/local/bundle/bundler/gems/*/.git \
    /usr/local/bundle/cache/

COPY . /app
RUN bin/potential_asset_precompile.sh $precompileassets

EXPOSE 3000

ENTRYPOINT ["/app/lib/docker-entrypoint.sh"]
CMD ["rails","server","-b","0.0.0.0","-p","3000"]
```

Where `potential_precompile_assets` was taken from a blog post which I cannot find anymore (sorry to the original author!). The contents are:

```shell
#!/bin/bash
echo 'Running potential asset precompile'
if [ $# -eq 0 ] ; then
  echo 'no argument supplied, precompiling'
  bundle exec rake assets:precompile
  bundle exec rake webpacker:compile
else
  if [ $1 == "not" ] ; then
    echo "precompile = not, so not running precompile"
  else
    echo 'argument supplied but different from not, precompiling'
    bundle exec rake assets:precompile
    bundle exec rake webpacker:compile
  fi
fi
```
