### ISSUE TITLE
Way to generate array-like webpack configuration to fix tree-shaking with multiple entries

### ISSUE THREAD

**Issue by codef0rmer** [rails/webpacker#1251]
With respect this (https://github.com/FormidableLabs/webpack-tree-shaking-multiple-entry-points#webpack--tree-shaking--multiple-entry-points), I'm trying to fix the configuration file so that tree-shaking would work as expected.

This is what I tried:

```
const environment = require('./environment')
const webpackConfig = environment.toWebpackConfig()

const entries = Object.keys(webpackConfig.entry)
const webpackConfigArray = entries.map(function (entryName) {
  let webpackConfigIndie = Object.assign({}, webpackConfig)
  let entry = {}
  entry[entryName] = webpackConfig.entry[entryName]
  webpackConfigIndie.entry = entry;
  return webpackConfigIndie
})

module.exports = webpackConfigArray
```

This messes up the builds and keeps the last build only on FileSystem removing the rest?

**Comment by codef0rmer** [comment]
One thing I noticed is that `manifest.json` only includes the last bundle which means it is getting overwritten.

**Comment by codef0rmer** [comment]
I've managed to crack it 😊 

*In `environment.js`:*
```
environment.generateMultiWebpackConfig = function(webpackConfig) {
   // Memoize the combined pack entries to be used in manifest.json
  let manifest = {}
  environment.plugins.get('Manifest').opts.reduce = function(i, file) {
    let seed = {}
    seed[file.name] = file.path
    manifest = Object.assign(manifest, seed)
    return manifest
  }
  const entries = Object.keys(webpackConfig.entry)
  const webpackConfigArray = entries.map(function (entryName, i) {
    let webpackConfigIndie = Object.assign({}, webpackConfig)
    let entry = {}
    entry[entryName] = webpackConfig.entry[entryName]
    // Removes the combined entries with just one in each config looped over
    webpackConfigIndie.entry = entry;
    return webpackConfigIndie
  })
  return webpackConfigArray
}
module.exports = environment
```

*In `development.js`, import it:*
```
webpackConfig.devtool = 'sourcemap'
module.exports = environment.generateMultiWebpackConfig(webpackConfig)
```

@gauravtiwari I'm not sure if it's a hack or what. Can you validate so that I can raise a PR for the tree-shaking docs?

P.S. Although one can not run `environment.toWebpackConfig()` on the generated multi-configs since it somehow does not comply with the JSON schema supported.

**Comment by codef0rmer** [comment]
@gauravtiwari does `assets:precompile` command use threadings? The command never fails locally but on CI with above invalid `manifest.json` file? 🤔 

```
environment.generateMultiWebpackConfig = function(env) {
  let webpackConfig = env.toWebpackConfig()
  let entries = Object.keys(webpackConfig.entry)
  return entries.map(function (entryName, i) {
    return Object.assign(
      {},
      webpackConfig,
      { entry: { [entryName] : webpackConfig.entry[entryName] } }
    )
  })
}
```

**Comment by Superpencil** [comment]
@codef0rmer did you get it to work in the end?
Trying to implement this: https://github.com/webpack/webpack/tree/master/examples/i18n
Since we're dealing with 10MB of translations :)

**Comment by codef0rmer** [comment]
@Superpencil do you get the same broken manifest.json?

**Comment by codef0rmer** [comment]
@Superpencil If you are facing the same problem of broken manifest then you have to manually fix the JSON. I wrote an article on it: https://medium.com/simpl-under-the-hood/enable-tree-shaking-in-rails-webpacker-a33ef1ba2bc3

**Comment by codef0rmer** [comment]
@gauravtiwari is it possible to link this article somewhere in docs?

**Comment by jakeNiemiec** [comment]
I would wait for webpack to fix that specific bug: https://github.com/webpack/webpack/issues/4453#issuecomment-485422565. The method described in that article is clever, but it's not a well-rounded solution to the problem at hand.

My understanding is that tree-shaking will still work for `node_modules` libraries (the main target for TS).

**Comment by codef0rmer** [comment]
@jakeNiemiec I fixed the issue by generating different Manifest files for each pack and then combine them into a single `manifest.json` file at the end. Works like a charm on Prod :)

https://amitgharat.wordpress.com/2019/06/03/enable-tree-shaking-in-rails-webpacker-a-sequel/

**Comment by jakeNiemiec** [comment]
Looks like webpack finally fixed this: https://github.com/webpack/webpack/issues/4453#issuecomment-671092318

**Comment by guillaumebriday** [comment]
Is this issue still relevant? Feel free to reopen if needed
