### ISSUE TITLE
Imports from /node_modules are not transpiled

### ISSUE THREAD

**Issue by mgibas** [rails/webpacker#1260]
Just created new app using this commands:
``` 
rails new myapp --webpack
bundle
bundle exec rails webpacker:install
```
everything seems to be fine if it comes to `/app/javascript/packs/application.js` (code inside is transpiled the way I configure in `.babelrc`) but nothing happens to dependencies imported from `/node_modules` folder, ie.:

`require('../../../node_modules/@mylib/mylib/file.js');`

this will only output content of the file into a pack, but code is not picked up by babel :(

**Comment by mgibas** [comment]
Seems like same thing as in #1239 
Is this is by design and I can run into some weird issues ?

**Comment by renchap** [comment]
`babel-loader` ignores `node_modules/` in the default config: https://github.com/rails/webpacker/blob/89e4d602c29ca5cf89d7e634a7e901225d2e7a4f/package/rules/babel.js#L4-L10

You can all an `include` option to make webpack process a specific module with Babel.

Ideally the `exclude` option should not be here, but some NPM packages are distributed with a `.babelrc` file, and running `babel-loader` on them will cause errors as Babel will try to use their specific `.babelrc` file, but you may not have the correct Babel plugins in your project. See https://github.com/babel/babel/issues/6766 for some details on this.

**Comment by gauravtiwari** [comment]
Thanks @renchap 

Okay to close @mgibas ?

**Comment by mgibas** [comment]
Yes, thanks @renchap and @gauravtiwari!
