### ISSUE TITLE
Externals libraries autoincluded by cdn instead of bundling them

### ISSUE THREAD

**Issue by HectorLS** [rails/webpacker#1273]
Hello, we have the external option in Webpack, [link here](https://webpack.js.org/configuration/externals/)

There is a way to achieve the same for my external libraries using Webpacker ?

**Comment by gauravtiwari** [comment]
@HectorLS Yep just set externals option using `environment.config` and then follow instructions in the doc you posted. 

```js
environment.config.merge({
  externals: {
    jquery: 'jQuery'
  }
}) 
```
