### ISSUE TITLE
How to handle multiple require and asset_pack_url

### ISSUE THREAD

**Issue by yannski** [rails/webpacker#1275]
Assuming I require some images twice in my JS bundle with something like (first require is to have an original image, second require is for thumbnail generation):
```js
importAll(require.context('images/blog/', true, /\.(png|jpe?g|svg)$/))
importAll(require.context('!file-loader?name=[path][name]-thumbnail-[hash].[ext]&context=app/javascript!image-webpack-loader!image-process-loader?resize[]=600&resize[]=360!images/blog/', true, /banner\.jpg$/))
```
The value generated in the manifest is not deterministic. For some images the value will be the result of the first require and for some other images it will be the second require. Therefore, when I use the asset_pack_url I get one of the assets.

How am I supposed to handle this kind of case with webpacker/Rails?

**Comment by yannski** [comment]
I ended up using https://github.com/webdeveric/webpack-assets-manifest and completely replace the include webpack-manifest-plugin. Maybe it should be the default one.

**Comment by gauravtiwari** [comment]
@yannski Thanks. Latest Webpacker (pre-version) is using `webpack-assets-manifest ` since it has support for webpack  and other things we need.
