### ISSUE TITLE
Angular esm5

### ISSUE THREAD

**Issue by manoj3243** [rails/webpacker#1280]
Failed to compile.

./node_modules/@angular/animations/esm5/animations.js
Module build failed: Error: ENOENT: no such file or directory, open 'c:\angular\demo\node_modules\@angular\animations\esm5\animations.js'
 @ ./node_modules/@angular/platform-browser/esm5/animations.js 9:0-83
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

**Comment by ytbryan** [comment]
Can you provide more information? 

For example: steps to reproduce? What are you expecting? What actually happened?

**Comment by manoj3243** [comment]
Hi actually i want to build a webpage using prebuild themes from angular material the components is working but the theme css and classes is not applying

- 

- [ ] 1. 
![screenshot 25](https://user-images.githubusercontent.com/30524439/36376593-ac601374-1599-11e8-9a4a-bf84e90e0644.png)

**Comment by gauravtiwari** [comment]
You will probably need to include css using `<%= stylesheet_pack_tag 'whatever_css_file_name_as_pack.css' %>`

**Comment by manoj3243** [comment]
Hi ,
i include in my css file

**Comment by manoj3243** [comment]
Hi ,
i include in my css file
![screenshot 27](https://user-images.githubusercontent.com/30524439/36377620-d0f16b1c-159d-11e8-85c4-940b28ffedf5.png)

**Comment by manoj3243** [comment]
Is there any body to solve the issue

**Comment by ytbryan** [comment]
Are you using Rails and webpacker? The project structure looks different. 

cc @gauravtiwari I think this is close-able.
