### ISSUE TITLE
Conflict with Passenger and Apache

### ISSUE THREAD

**Issue by jlhumerez** [rails/webpacker#1288]
I have this problem:
![image](https://user-images.githubusercontent.com/25935784/36603690-fa3c8e10-1891-11e8-8b51-d085a6b906ec.png)

works correctly when it is in development; in production is when it no longer works.

**Comment by gauravtiwari** [comment]
@jlhumerez Perhaps you wanna look into logs and see what exactly is going wrong on production.

**Comment by jlhumerez** [comment]
Excuse me, I forgot the log messages:

[ E 2018-02-23 11:38:45.0661 32094/T13 age/Cor/App/Implementation.cpp:304 ]: Could not spawn process for application /home/x0/public_html/x0: An error occurred while starting up the preloader.
[ E 2018-02-23 11:38:45.0992 32094/Tj age/Cor/Con/CheckoutSession.cpp:285 ]: [Cl
ient 7-1] Cannot checkout session because a spawning error occurred. The identif
ier of the error is f71ff339. Please see earlier logs for details about the erro
r.

**Comment by guilleiguaran** [comment]
@jlhumerez in production your assets should be compiled to `/public/packs` folder and served directly by your web server: https://www.phusionpassenger.com/library/dev/ruby/rails_integration.html#asset-pipeline

Webpacker shouldn't be used in production environment.
