### ISSUE TITLE
Documentation for adding loaders is out of date. environment.loaders.append does not exist

### ISSUE THREAD

**Issue by DamianPereira** [rails/webpacker#1289]
I was trying to add a webp loader to the config, and was following the documentation here:

https://github.com/rails/webpacker/blob/master/docs/webpack.md#loaders

environment.loaders.append does not work, because environment.loaders is an ES6 Map instead of an array. This works correctly:

```
environment.loaders.set('webp', {
  test: /\.webp$/,
  loader: ['file-loader', 'webp-loader']
})
```

Some other stuff:
- I did not add the ".webp" under extensions on webpacker.yml , and it still works.
- I don't understand how the order is defined, or if it changes anything in webpack.

Anyway, the documentation should probably be updated.

**Comment by gauravtiwari** [comment]
@DamianPereira Are you using the latest version of npm package and gem?

**Comment by DamianPereira** [comment]
My npm package was outdated. I upgraded with `yarn upgrade @rails/webpacker --latest
`and not it works as documented. Sorry, thought I had everything updated, closing this. Thanks!
