### ISSUE TITLE
Webpack Loader Options Plugin Still Needed?

### ISSUE THREAD

**Issue by justin808** [rails/webpacker#129]
It was added here: https://github.com/rails/webpacker/commit/1bc83f06734c9369a96d609f77aa71be0487faff

> The LoaderOptionsPlugin is unlike other plugins. It exists to help people move from webpack 1 to webpack 2. With webpack 2 the schema for a webpack.config.js became stricter; no longer open for extension by other loaders / plugins. With webpack 2 the intention is that you pass options directly to loaders / plugins. i.e. options are not global / shared.

And is here: https://github.com/rails/webpacker/blob/master/lib/install/config/development.js#L20

What are the specific loaders that still require this?

I'd be in favor of having some comments in the webpack JS files for when things like this are added for backward compatibility so that we know when to remove them.

**Comment by dhh** [comment]
We shouldn't have anything that's for backwards compatibility in the generated files right now. So a PR to clean that up would be good 👍

**Comment by justin808** [comment]
I could do this. Do we have any way to assign tasks, to avoid duplication of efforts?

**Comment by gauravtiwari** [comment]
@justin808 I can clean this up in the coming up PR for #109 since it involves same files.

**Comment by gauravtiwari** [comment]
@justin808 this is fixed now. We can close this one :)
