### ISSUE TITLE
Security issues for 2 libraries that are included in @rails/webpacker

### ISSUE THREAD

**Issue by nikolalsvk** [rails/webpacker#1298]
I've received security alerts from Gemnasium for:

- hoek https://nodesecurity.io/advisories/566
- ssri https://nodesecurity.io/advisories/565

Can you please upgrade the packages that include these packages with security issues.

hoek is used from "@rails/webpacker#node-sass#node-gyp#request#hawk".
ssri is used from "@rails/webpacker#compression-webpack-plugin#cacache".

**Comment by gauravtiwari** [comment]
Updated compression webpack to latest version, please use 3.3.0
