### ISSUE TITLE
Question: Using glob for entry points in webpack

### ISSUE THREAD

**Issue by randyv12** [rails/webpacker#1299]
Hello there, I ran into some issues recently with build performance issues.  The issue arises when the codebase increases (lots of files). And when node compiles these files, drastic performance issues happens, (Java heap out of memory, slow build time etc.)  I noticed in:
```
https://github.com/rails/webpacker/blob/master/package/environment.js#L36
```
We are using glob with sync to find entry points.  This can cause a lot of issues for developers that do not understand Webpack really well.  Using a glob there will match a lot of files, (in my case, typescript files), that are imported in a main index.ts file, for entry points.

Perhaps we could use a better template that shows what could an entry point possibly be?  These entry points can be mistaken that by design, it supposed to match all the files matching an extension, but really, all it needs to do is either map single or multiple entry points (which can have imports).  Developers might not intend to have non-entry point files compiled.

For me, I've used an index.(ext) file naming convention so that other files, say (react components) that are not exposed from an entry point would not be part of the manifest.json.

This will really help out other developers down the road when they start tinkering with webpack optimization plugins such as common chunks plugin, and uglifyjs plugin.  

Thanks!

**Comment by gauravtiwari** [comment]
@randyv12 How is your app structured?

It only matches extensions that are declared in webpacker.yml. Also, please ensure only webpack entry points aka packs are added in packs folder (app source can live app/javascript). Please see: https://github.com/rails/webpacker#usage

**Comment by woniesong92** [comment]
We are also experiencing a very degraded performance in a not-so-large codebase. Might be related to https://github.com/rails/webpacker/issues/1319?

**Comment by randyv12** [comment]
@gauravtiwari , Hey there, thanks for the reply!

It seems that my app structure affects the performance by quite a lot.  The fact that the glob matches more than it needs to had compiled more than just a entry points.  I'm leaning towards more, implementing a naming convention of.. (*.entry{.ts, .tsx}) for entry points. Just a few days ago, I've speeded up the Webpack compilation from 400 seconds to 60 seconds, with a smaller set of entry points, and added some loader caching from (typescript-awesome-loader).

@woniesong92 ,  I recommend this guide for speeding up Webpack
https://slack.engineering/keep-webpack-fast-a-field-guide-for-better-build-performance-f56a5995e8f1

A few things that can help, and these are the things I ran into:

1. Turn off source maps for prod builds
2. Make sure your ManifestPlugin has writeToFileEmit: false (if you're precompiling, you do not need it)
3. You can target specific file paths for commons chunking, chunking across a huge code base can be slow.
```
        minChunks: function(module, count) {
            return module.resource && (/file_path/).test(module.resource) && count === 1;
        }
```
4. Setting up a package.json npm script with additional memory (just incase you run into java heap errors)
```
# in package json
"scripts": {
  "compile_script": "NODE_ENV=test NODE_PATH=./node_modules ./node_modules/.bin/webpack --config ./config/webpack/config.js"
}
```
```
node --max-old-space-size=4096 `which npm` run compile_script
```
5.  If you are using React and if you have server side rendering, you can use a single entry point for SSR, ensuring there are no window references, and external api calls on component life cycles.  You can also use stateless components.
6.  Since we are in Rails, we can also monkey patch the gzip library with pigz which can compress files in parallel.  This speeds up asset precompilation on Sprockets (fork the repo and version)

Good luck out there.  Optimizing is tough, but really rewarding!

**Comment by rossta** [comment]
@randyv12 Do you have a lot of files in `app/javascript/packs`? (or whereever you have configured your entry points)?

**Comment by randyv12** [comment]
yes @rossta , we've made a mistake of having too many assets in the packs directory, it will be good to use a naming convention to filter by or filter with a glob **.entry.ts(x)?*

**Comment by gauravtiwari** [comment]
@randyv12 Webpacker only looks for entries inside packs folder, outside of it you can structure your app anyway you like. Here is a basic setup we suggested in README: https://github.com/rails/webpacker#usage

```yml
packs:
  - # only entry files here imported from source, usually one per view....
src: # or app or whatever you wanna call 
  - components
  - images
  - helpers
  - etc....
```
