### ISSUE TITLE
Question: Assets generated with hash in development mode - upgrading from webpacker 2.x to 3.2

### ISSUE THREAD

**Issue by ratneshraval** [rails/webpacker#1300]
Trying to upgrade to webpacker 3.2. I see that I have 2 ways of doing this. Either by using `yarn upgrade --latest` which keeps the current set of configs in place.
I decided to go on a more difficult journey by trying to use the new config structure and recreating my customizations. 

`rails assets:precompile` 
2.x Used to generate assets in development mode (no hash in generated file names)
3.2.2 generates them with hash. Curious if I'm doing something wrong is this default behavior 

Setup:
Rails: 5.1.2
Webpacker: 3.2.2
Webpack: 3.10.0

**Comment by ratneshraval** [comment]
Even brand new app generates asset names with hash. So looks like 2 is default behavior.
Any way to turn it off when RAILS_ENV or NODE_ENV = development?

**Comment by gauravtiwari** [comment]
@ratneshraval Nope, that's default behavior now, same as sprockets. Is it causing any problem?

**Comment by gauravtiwari** [comment]
There is some info here too: https://github.com/rails/webpacker/issues/1310

**Comment by ratneshraval** [comment]
@gauravtiwari  no issues, just a question. This can be closed now.
