### ISSUE TITLE
custom environments (e.g. staging) `TypeError: Cannot convert undefined or null to object` in `webpacker/packer/config.js`

### ISSUE THREAD

**Issue by btakita** [rails/webpacker#1306]
`webpacker/lib/install/config/webpacker.yml` only has `development`, `production`, `test`; It is not overridable in `webpacker/packer/config.js`. This causes an error on `NODE_ENV=staging rake webpacker:compile`

See https://github.com/rails/webpacker/commit/8c6476e4cb907d0dd2bad16e2ab03271a53200f8

and https://www.ctolib.com/article/comments/25042

**Comment by btakita** [comment]
https://github.com/socialchorus/bossanova/pull/3530

**Comment by gauravtiwari** [comment]
Made a new release 3.3.0

**Comment by wpolicarpo** [comment]
Seems like this is still happening in `3.3.0`.

**Comment by gauravtiwari** [comment]
@wpolicarpo Working on a PR to fix this

**Comment by gauravtiwari** [comment]
Just released 3.4.0 and there is some documentation added in README. Please try it out and report your feedback.
