### ISSUE TITLE
Determining where the pre-processor occurs compared to the asset pipeline

### ISSUE THREAD

**Issue by psychoslave** [rails/webpacker#1309]
Hello,

This is not an issue about the code, at most about the documentation, so I'm not sure this is the right place to posting this, at which case please point me to where I should submit my question.

So, I successfully installed and configured rails-erb-loader so `.vue.erb` interpretation are working fine. I did so mainly in order to be able to use a gettext gem, namely [https://github.com/grosser/fast_gettext](fast_gettext), so we can use the same source of locale for both traditional erb views and Vue.js components. 

But now I've been asked at which moment this interpretation happen in the overall pipeline. In particular, does translation by loaders happens early and is cached, so that in my case each locale will generate javascript file that won't be modified until locales themselves are changing, or will it be fully reprocessed each time the layout calling the webpacker application is hit?

I red some documentation, including
- https://webpack.js.org/concepts/
- https://webpack.js.org/concepts/loaders/
- https://webpack.js.org/guides/build-performance/

Still I'm a bit uncertain about how the above question should be responded. 

A straight forward answer would be nice, but I'm also open to hint of further reading, and even alternative suggestions to resolve the initial targeted problem of pooling internationalization facilities into a gettext-like solution.

**Comment by chall8908** [comment]
As I understand it - and this depends on your setup - I would expect you would get a single set of JS files translated into your default locale.

As far as I know, ERB in webpacked files is evaluated once at compile time.

In order to do what you want, you'll either have to try some pack trickery - like having one per locale - or you'll have to use a JS-based I18n solution which seems to be the consensus in #597.

**Comment by psychoslave** [comment]
Hello @chall8908 I reached the same conclusions as the one your are proposing. Thank you for you feedback which comfort me in this position,  and for the link to the relevant issue.

**Comment by gauravtiwari** [comment]
Thanks @chall8908 

@psychoslave Would make sense to post this on StackOverflow for suggestions.
