### ISSUE TITLE
Webpack.logger uses wrong logger

### ISSUE THREAD

**Issue by flippakitten** [rails/webpacker#1312]
I'm not sure why this was designed like this but when initializing the Webpacker.logger, if Rails logger is using `TaggedLogging`, it sets `Webpacker.logger` to use the Rails logger, otherwise it uses Tagged logging. 

The issue is if you have a custom formatter, calling `ActiveSupport::TaggedLogging.new` will set `@formatter` to use `SimpleFormatter`

```ruby
  initializer "webpacker.logger" do
    config.after_initialize do
      if ::Rails.logger.respond_to?(:tagged)
        Webpacker.logger = ::Rails.logger
      else
        Webpacker.logger = ActiveSupport::TaggedLogging.new(::Rails.logger)
      end
    end
  end
```

I've opened a PR https://github.com/rails/webpacker/pull/1311

**Comment by calleo** [comment]
Ran into this myself. It doesn't play well at all with other logging libraries like [ougai](https://github.com/tilfin/ougai) since the tagged logger stringifies the message (which is a hash).

**Comment by flippakitten** [comment]
If anyone comes across this I ended up using [SemanticLogger](https://github.com/rocketjob/rails_semantic_logger).
