### ISSUE TITLE
Webpack Externals

### ISSUE THREAD

**Issue by iChip** [rails/webpacker#1315]
I've looked a bit through the Webpacker node API but didn't see any an option for specifying external libraries.

This is a very important build option as it lets me decide which libraries are retrieved from the global scope at runtime so that they can be excluded from the build to prevent redundancy.

Reference: https://webpack.js.org/configuration/externals/

**Comment by gauravtiwari** [comment]
@iChip Here is documentation for setting any config property: https://github.com/rails/webpacker/blob/master/docs/webpack.md#configuration

```js
// global
// environment.js
const { environment } = require('@rails/webpacker')
environment.config.externals = []

// or within specific env
// development.js
const { environment } = require('@rails/webpacker')
environment.config.externals = []
```

**Comment by iChip** [comment]
Derp - thanks 🙏
