### ISSUE TITLE
Support non-default modules folder location for yarn integrity check

### ISSUE THREAD

**Issue by joonty** [rails/webpacker#1320]
We install our yarn modules into a different directory from the default `.node_modules/` in the project directory. This works, but the webpacker yarn integrity check fails, because [the command that's executed assumes the default location](https://github.com/rails/webpacker/blob/master/lib/webpacker/railtie.rb#L28). A different directory can be specified with `yarn check --integrity --modules-folder <path>`.

Incidentally, the reason as to why we do this is because we use Docker, and have a shared cache for bundled gems and node modules, but there may be other reasons as to why people would do this.

I propose either an environment config, or even just an environment variable, to be able to specify the modules folder used for the integrity check command. 

I'd be more than happy to issue a pull request if you agree and let me know if you have a preference of a config option or environment variable.

Thanks!

**Comment by guillaumebriday** [comment]
Yarn integrity check has been remove in https://github.com/rails/webpacker/pull/2518
