### ISSUE TITLE
Heroku: can't find executable webpack for gem webpacker (Gem::Exception)

### ISSUE THREAD

**Issue by jonhue** [rails/webpacker#1321]
After upgrading to the master branch of this repository, I get the following error when compiling on Heroku:

```
       Compiling…
       Compilation failed:
       /tmp/build_d4da645e5840bc32169cdef3aecaed44/jonhue-jonhue-97c0597/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/rubygems_integration.rb:432:in `block in replace_bin_path': can't find executable webpack for gem webpacker (Gem::Exception)
       from /tmp/build_d4da645e5840bc32169cdef3aecaed44/jonhue-jonhue-97c0597/vendor/bundle/ruby/2.3.0/gems/bundler-1.15.2/lib/bundler/rubygems_integration.rb:463:in `block in replace_bin_path'
       from ./bin/webpack:29:in `<main>'
 !
 !     Precompiling assets failed.
```

**Comment by Jehops** [comment]
We are also seeing this without Heroku:
```
rails assets:precompile
...
/usr/local/lib/ruby/gems/2.4/gems/bundler-1.16.1/lib/bundler/rubygems_integration.rb:458:in `block in replace_bin_path': can't find executable webpack for gem webpacker (Gem::Exception)
        from /usr/local/lib/ruby/gems/2.4/gems/bundler-1.16.1/lib/bundler/rubygems_integration.rb:489:in `block in replace_bin_path'
        from ./bin/webpack:17:in `<main>'
```
I notice the FreeBSD package, `rubygem-webpacker-rails5` starting with version 3.3.0 no longer installs `bin/webpacker` and `bin/bin/webpack-dev-server` under `$PREFIX`.

**Comment by gauravtiwari** [comment]
Please run `bundle exec rails webpacker:binstubs` and commit binstubs to heroku.

**Comment by vishthemenon** [comment]
I had the same issue as well when upgrading to webpacker 3.3.0. You need regenerate the binstubs for webpacker (and webpack-dev-server if you are using hot reloading in development).

**Comment by Jehops** [comment]
Thanks.  Could you elaborate on what command need to be run to fix our `rubygem-webpacker-rails5` package on FreeBSD (no Heroku)?  I assume we need to run something to generate those two executable scripts that are now missing.

**Comment by jonhue** [comment]
@gauravtiwari I did re-generate the binstubs using the `:install` generator. Your solution worked though. Any chance, they're not generating the same files?

**Comment by Jehops** [comment]
Sorry, I somehow missed `bundle exec rails webpacker:binstubs`.  I will try that.

**Comment by vishthemenon** [comment]
@jonhue `:install` may overwrite any custom config you might have previously added to your webpack config files but the binstubs generated are the same as far as I know.

**Comment by jonhue** [comment]
Of course, I did not override the config files 😉

**Comment by Jehops** [comment]
Is it possible to generate the scripts without bundler?  [Bundler is not listed as a production dependency](https://rubygems.org/gems/webpacker/versions/3.3.0).

**Comment by vishthemenon** [comment]
You could generate it in development and commit it to your repo before deploying.

**Comment by Jehops** [comment]
This is for an OS package.  Running bundler during the package build causes problems. Assuming the old behaviour of installing these scripts under `$PREFIX/bin` cannot be restored, is there a solution without bundler?  What about simply creating links from `${PREFIX}/lib/ruby/gems/2.4/gems/webpacker-3.3.0/lib/install/bin/webpack` to `${PREFIX}/bin` ?

**Comment by Jehops** [comment]
When I say creating links, I mean we would do this when building our package.  Do you foresee any problems doing this?

**Comment by Jehops** [comment]
Sorry for the noise.  Basically what was suggested above works.  We just have to run `rails webpacker:binstubs` in all packages that require webpacker.  Thanks. :)

**Comment by AlexandrePerdomo** [comment]
Actually running this issue in my project. Got one app working in production but i'm unable to push another app with the same code and configuration (staging app, in heroic pipelines).
I tried running bundle exec rails webpacker:binstubs. Files webpack and webpack-dev-server are identicals. 
Any idea/ suggestions ?

**Comment by gauravtiwari** [comment]
@AlexandrePerdomo Are you sure you are installing latest version of webpacker and npm package?

```
bundle update webpacker
yarn add @rails/webpacker
```

Are you able to compile locally?

**Comment by AlexandrePerdomo** [comment]
Actually not understanding how i pushed my app 2 months ago with this configuration and not able to push my staging app today... Thx a lot for your help. Everything is working now.

**Comment by eileennoonan83** [comment]
Just wanted to add a comment saying that I got this error installing with `rails new myapp --webpack` (also with `... webpack=react`). That was version `3.4.3`.

None of the above fixes worked for me. I switched the webpacker version to `3.2.1` in my gemfile and that did it for me.

**Comment by vishthemenon** [comment]
@eileennoonan83 Could you please share the error message you got? I tried to recreate but had no errors? Which command did you run to get the error?

**Comment by eileennoonan83** [comment]
@vishthemenon I got the same error message as is in the title of this issue, and I got it running both ‘rails new ...’ and when trying to install into an existing app

**Comment by vishthemenon** [comment]
Which version of rails, webpacker are u running? Have you tried regenerating your binstubs? That is often a common cause of this error especially when upgrading from 3.2+ to 3.3+

**Comment by jtibrewala** [comment]
Rails 4.2.10
webpacker (4.0.0.pre.pre.2 1fce3a3)
Yes I have done `bundle exec rake webpacker:install`

Any other thoughts/suggestions on what I could be doing wrong?

**Comment by vishthemenon** [comment]
Hmm, I tried recreating the error with the said versions but it seems to be working fine. Also do check if your node packages are updated as well. 

Lastly, I did remember seeing a related issue linked to bundler version and the errors in binstubs generated by an older bundler version. Perhaps, upgrade your bundler and regenerate the binstubs. It should look something like this 

```ruby
#!/usr/bin/env ruby

ENV['RAILS_ENV'] ||= ENV['RACK_ENV'] || 'development'
ENV['NODE_ENV'] ||= ENV['RAILS_ENV']

require 'pathname'
ENV['BUNDLE_GEMFILE'] ||= File.expand_path('../../Gemfile',
                                           Pathname.new(__FILE__).realpath)

require 'rubygems'
require 'bundler/setup'

require 'webpacker'
require 'webpacker/webpack_runner'
Webpacker::WebpackRunner.run(ARGV)
```

**Comment by krainboltgreene** [comment]
Why was a breaking change introduced in a minor version?
