### ISSUE TITLE
Move vendor libs to separate bundle

### ISSUE THREAD

**Issue by codemotion** [rails/webpacker#1322]
Making app with Vue and take notice that size of all packs become larger and larger.

<img width="1028" alt="screen shot 2018-03-05 at 21 05 07" src="https://user-images.githubusercontent.com/626493/36991732-a6d7f98c-20b9-11e8-817b-89ad7268bb3e.png">

Using BundleAnalyzerPlugin found out that vendor libraries like Vue are copied into each pack bundle.
<img width="2257" alt="screen shot 2018-03-05 at 21 08 56" src="https://user-images.githubusercontent.com/626493/36991733-a6fc0ac0-20b9-11e8-9820-12a84ebc90a8.png">

Please, make option in config of webpack to move all cross-packs vendor libraries to the separate bundle.

**Comment by IgorDmitriev** [comment]
You can add `CommonsChunkPlugin` plugin in your config in `environment.js`:
```javascript
environment.config.merge({
  entry: {
    vendor: ['react', 'react-dom', 'semantic-ui-react']
  }
});

environment.plugins.append(
  'CommonChunkPlugin',
  new webpack.optimize.CommonsChunkPlugin({
    name: 'vendor',
    minChunks: Infinity
  })
);
```

There are more options in webpack docs: https://github.com/webpack/docs/wiki/list-of-plugins#commonschunkplugin

**Comment by rossta** [comment]
@codemotion It looks like you're producing a bundle for many (every?) module in your project. Are you sure that's what you want? If not, make sure only the entry file(s) are placed inside of `app/javascript/packs`. The rest of your source code can live outside of this directory so the separate modules can more sensibly be bundled together.

**Comment by gauravtiwari** [comment]
thanks @rossta @IgorDmitriev
