### ISSUE TITLE
Webpack v4 support

### ISSUE THREAD

**Issue by btakita** [rails/webpacker#1323]
It looks like there are some compatibility issues with webpack v4. I ran into this issue with `@rails/webpacker`:

https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/701#issuecomment-370519851

I'm sure there are more issues...

**Comment by humphreybc** [comment]
See https://github.com/rails/webpacker/issues/1224

**Comment by rossta** [comment]
There is a PR already in progress, no need to report another issue for this #1316

**Comment by gauravtiwari** [comment]
Duplicate #1224
