### ISSUE TITLE
Trying to import js file to webpack application js

### ISSUE THREAD

**Issue by suhomlineugene** [rails/webpacker#1326]
I have ruby project where I add typescript and webpacker

I have wrote typescript and make rake assets:tsc. So it compiles ts code to js.

Now I have welcome.js at folder `app/assets/javascripts/generated/welcome.js

Here is code of welcome.js

`var HelloWorld = /** @class */ (function () {
    function HelloWorld(name) {
        this.name = name;
    }
    HelloWorld.prototype.print = function () {
        alert("Hello World, " + this.name + "!");
    };
    return HelloWorld;
}());
new HelloWorld('John Doe').print();
//# sourceMappingURL=welcome.js.map`

I tried to wrote in welcome.js

`export default HelloWorld;`

And in application.js wrote `import HelloWorld from 'generated'`

And gets this error

> Uncaught Error: Cannot find module "generated" at Object. (application.js:1) at webpack_require (bootstrap 24a076357adc3b41e79b:19) at Object.defineProperty.value (bootstrap 24a076357adc3b41e79b:62) at bootstrap 24a076357adc3b41e79b:62

How I can solve it?

**Comment by rossta** [comment]
@suhomlineugene This sort of question may be better asked/answered on StackOverflow where it will be easier to search for and find answers later.

**Comment by suhomlineugene** [comment]
@rossta I posted it to SO. Here is link https://stackoverflow.com/questions/49138589/import-js-file-to-webpack-application-js/49140415#49140415.

**Comment by gauravtiwari** [comment]
@suhomlineugene Should be `import HelloWorld from 'generated/welcome'` no? If you have an index.js inside generate than you can do `import HelloWorld from 'generated'`
