### ISSUE TITLE
webpacker:compile combines CSS differently than webpack-dev-server

### ISSUE THREAD

**Issue by kieraneglin** [rails/webpacker#1329]
I have a Rails/Webpacker/Vue app where I want to have different styles on each page.  That may look like this:

```html
// page-a.vue
<style lang="scss">
  @import './stylesheets/a';
</style>
```

```html
// page-b.vue
<style lang="scss">
  @import './stylesheets/b';
</style>
```
These stylesheets have completely separate rules that should not mix.

In development with `webpack-dev-server`, the stylesheets remain separate as expected.  However, when `webpacker:compile` is run, the stylesheets merge and all the CSS is used by both files.
___

Because of this, deploying to production will cause your applications to look vastly different than in development.  

If there is a way to separate out the CSS when using `webpacker:compile`, I'm also very interested in fixing this.

**Comment by rossta** [comment]
@kieraneglin It would help to provide more context so others can reproduce the issue. Sharing more information about your configuration and your dependencies or steps to reproduce on a fresh install would be a good start.

**Comment by doits** [comment]
Just a wild gues: Scoping the styles with `scoped` might help, so they are only applied to the current page.

```vue
<style lang="scss" scoped>
  @import './stylesheets/a';
</style>
```
