### ISSUE TITLE
How to disable/remove webpacker from a project?

### ISSUE THREAD

**Issue by gingerhot** [rails/webpacker#1333]
I tried `webpacker` in a project, and now I want to disable or remove the webpacker from it decently, but I failed to find how to in Docs and searching,  and also there isn't a Rake task defined for this.

So some help will be appreciated.

**Comment by ytbryan** [comment]
To disable webpacker, 

1. Comment out from Gemfile. 

2. Comment out the single line on production and development.rb on the integrity check. 

3. Comment out any javascript_pack_tag or stylesheet_pack_tag 

*I’m typing this on a phone and no access to laptop till night time. Will provide code snippet when I’m back

**Comment by gingerhot** [comment]
@ytbryan Thanks for your rapid helping~

I commented out these lines, and the webpacker did not run compiling again. But I found Rails still run `yarn install` when I run `rails assets:precompile`, I'm not clear that if it's a feature of Rails 5 or because that webpacker hooks up a new `webpacker:compile` task to `assets:precompile` as document [here](https://github.com/rails/webpacker#deployment). If it was because of the later, how do I unhook it?

Thanks again ~

**Comment by ytbryan** [comment]
🤔 to give you an accurate answer, I need to trace the source code when I get back. 

But from the back of my mind, I think you can:

1. Run ‘bundle exec gem uninstall webpacker’
2. And/or comment out the ‘.bin/yarn’ binstub

**Comment by gingerhot** [comment]
@ytbryan yes, it works. Thanks again~

**Comment by ekzema** [comment]
https://github.com/rails/webpacker/issues/1333#issuecomment-372076800
In rails 6, this information is partially not relevant, namely:
in app / config / development.rb, app / config / production.rb no need to comment.
