### ISSUE TITLE
webpacker:compile doesnt seem to be loading babelrc

### ISSUE THREAD

**Issue by roine** [rails/webpacker#1336]
Im trying to get my js to compile to valid JS for IE10. Also the debug mode doesnt seem to run in prod compile mode, everything is fine in webpack-dev-server. Here's my config:

```{
  "presets": [
    ["env", {
      "modules": false,
      "targets": {
        "browsers": ["IE 10",
          "> 1%",
          "last 2 versions"
        ],
      },
      "useBuiltIns": true,
      "debug": true,
    }]
  ],

  "plugins": [
    "syntax-dynamic-import",
    "transform-object-rest-spread",
    ["transform-class-properties", { "spec": true }]
  ]
}
```

Here is where it breaks `r=n[i]={i,`, IE10 doesnt support this syntax.

Following screenshots are from the same page

**Dev mode**
<img width="784" alt="screen shot 2018-03-11 at 1 56 48 pm" src="https://user-images.githubusercontent.com/955500/37254416-7334f8e8-2535-11e8-8690-b4d1ca66f921.png">

**After compile, running in Prod mode**
<img width="787" alt="screen shot 2018-03-11 at 2 03 43 pm" src="https://user-images.githubusercontent.com/955500/37254421-875855ae-2535-11e8-83f4-89abaf0dca3f.png">

How do I get my prod build to work for IE10?

**Comment by roine** [comment]
Solved with:

```
const UglifyJSPlugin = require('uglifyjs-webpack-plugin');
environment.plugins.delete('UglifyJs');
environment.plugins.set('UglifyJs', new UglifyJSPlugin({
  uglifyOptions:{
    ecma:5
  }
}));
```

**Comment by dipakchandranp** [comment]
@roine Where did you add this code?
