### ISSUE TITLE
Css not loading correctly

### ISSUE THREAD

**Issue by suhomlineugene** [rails/webpacker#1341]
I want to use css in webpacker

So i have css file under app/javascript/components

Here is code of file

`  /*
*= require jquery/jquery.ui.resizable
*= require jquery/jquery.fancybox.min
*= require jquery/jquery.resizeandcrop
*= require jquery/tooltipster.bundle.min
*= require jquery/datepicker.min
*= require_tree ./base
*= require_tree ./flygcity_responsive
*/`

And also I have folder `flygcity_responsive` with scss and css files

I importing it in packs/stylesheet.ts

like this

`import  "../components/stylesheets/flygcity_responsive"`
After this I run webpacker-dev-server and it compile all great.

But when I run rails s it not upload styles

So i thin references not working.

Where is my problem may be?

**Comment by danielpowell4** [comment]
Where do you have this code?

```
/*
*= require jquery/jquery.ui.resizable
*= require jquery/jquery.fancybox.min
*= require jquery/jquery.resizeandcrop
*= require jquery/tooltipster.bundle.min
*= require jquery/datepicker.min
*= require_tree ./base
*= require_tree 
./flygcity_responsive
*/
```

The `*=`'s make it look like it's still hanging out over in `app/assets/stylesheets/application.css`

That is fine for the traditional sprockets pipeline that produces a `<%= stylesheet_link_tag 'application' %>` you likely include in the head of your `/app/views/layouts/application.html.erb` file

If you are fine with the traditional asset pipeline, you can also just add styles to the application/style sheets where they will be handled in the automagic rails way via "require_tree". The two can coexist as you migrate to the webpack way of doing things if you chose to migrate.

To use the stylesheet pack tags webpacker provides, you **don't** touch anything inside of application.css for app/assets for that matter.

Instead, you include them directly in your component. 

```css
// app/javascript/components/flygcity/styles/MainComponent.scss

.main-component {
  color: red;
}
```

```js
// app/javascript/components/flygcity/MainComponent.js
import React from "react";
import "./styles/MainComponent.scss"   // <----- include the component specific styles

const MainComponent = _ => <h1 className="main-component">Hello World</h1>;

export default MainComponent;
```
```js
// app/javascript/packs/flygcity.js
import React from "react";
import ReactDOM from "react-dom";
import MainComponent from "../components/flygcity/MainComponent";
import "react-virtualized/styles.css"; // <--- ANOTHER OPTION IMPORTING STYLES

document.addEventListener("DOMContentLoaded", function() {
  const rootElement = document.getElementById("someElement");
  if (rootElement !== null) {
    ReactDOM.render(
        <MainComponent />,
      rootElement
    );
  }
});

```

Then back in a Rails view be sure to include the javascript and stylesheet pack tags served up from public.
```erb
<%= javascript_pack_tag 'flygcity' %>
<%= stylesheet_pack_tag 'flygcity' %>
```

**Comment by gauravtiwari** [comment]
Please try the latest RC, otherwise feel free to open a new issue with more details.
