### ISSUE TITLE
Local webpacker.yml version

### ISSUE THREAD

**Issue by anikolaev** [rails/webpacker#1343]
Is there any opportunity to have local custom `webpacker.yml` file with individual settings? Changing the file itself marks it as changed in Git. Looking at the source code I couldn't find any `*.local.*` versions support. Also I couldn't find any config options for that. What do you think about modifying `configuration.js` replacing
```
const { readFileSync } = require('fs')

const configPath = resolve('config', 'webpacker.yml')
```
with
```
const { readFileSync, existsSync } = require('fs')

const configPathDefault = resolve('config', 'webpacker.yml')
const configPathLocal = resolve('config', 'webpacker.local.yml')
const configPath = existsSync(configPathLocal) ? configPathLocal : configPathDefault
```
or something similar to it? It would allow adding custom `webpacker.local.yml` file overloading the original one.

**Comment by Systho** [comment]
Usual way of doing what you ask is using environement variables

You can then either read those variables in your .js config file (not in your .yml file though as this one is not processed currently)

**Comment by anikolaev** [comment]
After upgrading from version 2 I faced with the issues similar to https://github.com/rails/webpacker/issues/863 so I moved all settings to `webpacker.yml`.
