### ISSUE TITLE
Add support for multiple context 

### ISSUE THREAD

**Issue by cdimonacoext** [rails/webpacker#1344]
As the documentation of Webpack says, https://webpack.js.org/configuration/configuration-types/, it's possibile to have multiple webpack configuation using an array.

Seems impossibile to do on webpacker, even with webpack merge.

**Comment by gauravtiwari** [comment]
@cdimonacoext You can export array from any of the `{environment}`.js files: 

```js
# development.js
process.env.NODE_ENV = process.env.NODE_ENV || 'development'

const environment = require('./environment')

module.exports = [
	environment.toWebpackConfig(),
	environment.toWebpackConfig()
]
```
