### ISSUE TITLE
Uglifier breaks code for IE11

### ISSUE THREAD

**Issue by eamon-hguk** [rails/webpacker#1354]
Hello,

I cannot get my Vuejs packs to run in IE in production, as I get an error when the js in the pack is run.
The error is SCRIPT1003: Expected ':'
It is this piece of the code which breaks:
var r=t[i]={i,1:!1,exports:{}}

This translates to the following part of the below code (marked with PROBLEM CODE BELOW), which is at the very top of the pack js file:

/******/ (function(modules) { // webpackBootstrap
/******/ 	// The module cache
/******/ 	var installedModules = {};
/******/
/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {
/******/
/******/ 		// Check if module is in cache
/******/ 		if(installedModules[moduleId]) {
/******/ 			return installedModules[moduleId].exports;
/******/ 		}
/******/ 		// Create a new module (and put it into the cache)
/******/            PROBLEM CODE HERE
/******/ 		var module = installedModules[moduleId] = {
/******/ 			i: moduleId,
/******/ 			l: false,
/******/ 			exports: {}
/******/ 		};
/******/
/******/ 		// Execute the module function
/******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
/******/
/******/ 		// Flag the module as loaded
/******/ 		module.l = true;
/******/
/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}
/******/
/******/
/******/ 	// expose the modules object (__webpack_modules__)
/******/ 	__webpack_require__.m = modules;
/******/
/******/ 	// expose the module cache
/******/ 	__webpack_require__.c = installedModules;
/******/
/******/ 	// define getter function for harmony exports
/******/ 	__webpack_require__.d = function(exports, name, getter) {
/******/ 		if(!__webpack_require__.o(exports, name)) {
/******/ 			Object.defineProperty(exports, name, {
/******/ 				configurable: false,
/******/ 				enumerable: true,
/******/ 				get: getter
/******/ 			});
/******/ 		}
/******/ 	};
/******/
/******/ 	// getDefaultExport function for compatibility with non-harmony modules
/******/ 	__webpack_require__.n = function(module) {
/******/ 		var getter = module && module.__esModule ?
/******/ 			function getDefault() { return module['default']; } :
/******/ 			function getModuleExports() { return module; };
/******/ 		__webpack_require__.d(getter, 'a', getter);
/******/ 		return getter;
/******/ 	};
/******/
/******/ 	// Object.prototype.hasOwnProperty.call
/******/ 	__webpack_require__.o = function(object, property) { return Object.prototype.hasOwnProperty.call(object, property); };
/******/
/******/ 	// __webpack_public_path__
/******/ 	__webpack_require__.p = "/packs/";
/******/
/******/ 	// Load entry module and return exports
/******/ 	return __webpack_require__(__webpack_require__.s = 896);
/******/ })
/************************************************************************/
/******/ ([
/* 0 */

I am using all the defaults that come with webpacker and webpacker-vue

It works in the non-uglified code, and in other browsers.

Thank You

Eamon

**Comment by iChip** [comment]
Having the same issue.

**Comment by robertfall** [comment]
It comes down to this line: https://github.com/rails/webpacker/blob/master/package/environments/production.js#L20

Our fix was just to override it to a lower ES level. I'd like to submit a PR if changing this will be acceptable? We settled on ES 7.

**Comment by clarketus** [comment]
This issue is already logged here, along with a solution: https://github.com/rails/webpacker/issues/1235

That being said, I have no idea why webpacker is trying to set an uglifier config that is not just the uglifier defaults.

**Comment by gauravtiwari** [comment]
Please try the latest RC, otherwise feel free to open a new issue with more details.
