### ISSUE TITLE
Pre-compilation should use `yarn install --frozen-lockfile` by default

### ISSUE THREAD

**Issue by danielpowell4** [rails/webpacker#1358]
As I can tell, the current behavior is to enhance assets precompile with a plain `yarn install`. I believe this automatically regenerates the yarn.lock file.

[enhance_assets_precompile](https://github.com/rails/webpacker/blob/d5fe0fe8e492d1511c6f31648f8fe861504c111e/lib/tasks/webpacker/compile.rake#L11)
[webpacker:yarn_install](https://github.com/rails/webpacker/blob/97e09e3f72e2596a76efa600d7fd93889a458e50/lib/tasks/webpacker/yarn_install.rake)

We can flag `check_yarn_integrity: true` in the environment specific files to stop rails from initializing, but to me it seems that just double checks that `yarn install` has been run recently.

This seems problematic as it essentially ignores the `lock` file that is checked into version control so it is possible for the node_modules tree that is deployed to diverge from the one that is installed locally or staging if `yarn install` behaves differently.

Yarn allows for yarn install to more closely follow the yarn.lock file through two flags, one that fails if an update is needed (`--frozen-lockfile`) and one that doesn't (`--pure-lockfile`)

From the [yarn docs](https://yarnpkg.com/lang/en/docs/cli/install/#toc-yarn-install-pure-lockfile):

`yarn install --pure-lockfile`
Don’t generate a yarn.lock lockfile.

`yarn install --frozen-lockfile`
Don’t generate a yarn.lock lockfile and fail if an update is needed.

I think that the `--frozen-lockfile` flag should be the default.

Let me know if I missed something along the way OR if you are interested in a PR!

**Comment by gauravtiwari** [comment]
@danielpowell4 Thanks, fixed in #1345
