### ISSUE TITLE
"packs" or "bundles"

### ISSUE THREAD

**Issue by justin808** [rails/webpacker#136]
It seems that the term "pack" is synonymous with the webpack documentation for bundles.

Eventually, we'll want to configure larger Rails apps to support [Code Splitting](https://webpack.js.org/guides/code-splitting/).

The advantage of using the term "bundles" in the directories and docs is that it will be immediately obvious to the experienced webpack users what these are.

However, maybe we want to use the terms "pack" and "packs" to specifically mean webpack bundles configured via the Rails default configuration of entry points. So maybe "packs" is better?
(but per discussion below, we cannot restrict finding the "pack" files).

Another issue we need to consider is [splitting the vendor bundle](https://webpack.js.org/guides/code-splitting-libraries/).

Luckily, [Webpack now supports an implicit vendor bundle](https://webpack.js.org/guides/code-splitting-libraries/#implicit-common-vendor-chunk).

This means that we'll have a "pack" (or bundle) that does not map to a file in the `/app/javascripts/packs` directory. So long as we're depending on the manifest file that @gauravtiwari is using, and not so much on what's in the "packs" directory, then we should be covered.

Plus, there's another import piece to the puzzle of using a "vendor bundle", which is the [manifest file](https://webpack.js.org/guides/code-splitting-libraries/#manifest-file).

**Comment by lookitsatravis** [comment]
One thing to consider is using "bundle" for webpack could get quite confusing when referring to "bundle" for the `bundler` gem.

**Comment by dhh** [comment]
Yeah, I went over this from a lot of different angles when deciding on "packs". We have a lot of overloading of the word "bundle" in the Rails world, so packs provided a uncontested word we can use. We are balancing multiple domains and ecosystems here, so there's some give and take. Optimizing solely for what an experienced webpack user would expect isn't going to give that.
