### ISSUE TITLE
ERB does not work with rails 5.2

### ISSUE THREAD

**Issue by damienlethiec** [rails/webpacker#1360]
Hello,

I use Rails 5.2.0.rc1

I tried to use integrate ERB with webpacker following the instructions in the README but I have the following error when I restract webpack dev server:

```
assets | set is deprecated! Use append instead
assets | /Users/damienlethiec/code/damienlethiec/ProjetsPros/Goose/grease/config/webpack/environment.js:14
assets | environment.loaders.append('erb', erb)
assets |                                   ^
assets |
assets | ReferenceError: erb is not defined
assets |     at Object.<anonymous> (/Users/damienlethiec/code/damienlethiec/ProjetsPros/Goose/grease/config/webpack/environment.js:14:35)
assets |     at Module._compile (module.js:649:30)
assets |     at Object.Module._extensions..js (module.js:660:10)
assets |     at Module.load (module.js:561:32)
assets |     at tryModuleLoad (module.js:501:12)
assets |     at Function.Module._load (module.js:493:3)
assets |     at Module.require (module.js:593:17)
assets |     at require (internal/module.js:11:18)
assets |     at Object.<anonymous> (/Users/damienlethiec/code/damienlethiec/ProjetsPros/Goose/grease/config/webpack/development.js:1:83)
assets |     at Module._compile (module.js:649:30)
11:12:21 - INFO - Bundle already up-to-date
guard  | 11:12:21 - INFO - Guard is now watching at '/Users/damienlethiec/code/damienlethiec/ProjetsPros/Goose/grease'
```

Any ideas to solve this?
Thanks a lot

**Comment by ytbryan** [comment]
Have you looked at https://github.com/rails/webpacker/issues/1256 and https://github.com/rails/webpacker/issues/1297?

**Comment by damienlethiec** [comment]
I did not find them before now. I will have a look soon. However, it seems they concern vue which I do not use (but maybe the solution will be the same).

Thanks

**Comment by ytbryan** [comment]
Ok, try to add the loader as shown 

https://github.com/rails/webpacker/issues/1256#issuecomment-367573638

**Comment by gauravtiwari** [comment]
Thanks @ytbryan 

Can't reproduce this locally with fresh rails 5.2 app. Are you sure the install has completed successfully when adding erb?

`bundle exec rails webpacker:install:erb`

**Comment by alekseyl** [comment]
problem is not in rails version (I've got same problem on rails 5.1.5 ), it's in

`bundle exec rails webpacker:install:erb`

Because of a missing variable `erb`, don't you see this? All reference to vue problem also missing the point.  

You actually missing something like this in a environment header: 

`const erb = require('./loaders/erb');`

**Comment by damienlethiec** [comment]
Oh, of course, you are probably right! Thank you!
