### ISSUE TITLE
multiple css output files

### ISSUE THREAD

**Issue by benbonnet** [rails/webpacker#1363]
Knowing that the use case might not make that much sense, rather interested into understanding how things work and how it could be setup; would it be possible by configuration to have multiple css output files ? So to be able to have different stylesheet_pack_tag

**Comment by rossta** [comment]
There are a few ways to do it, by a simple way would be as follows: start with two files in `app/javascript/packs` which would both, some where in their dependency graphs, import css. You would then add `stylesheet_pack_tag` helpers when needed referring to a css "pack" matching the names of your pack files.

```shell
app/
  javascript/
    css/
      application.scss
      welcome.scss
    packs/
      application.js
      welcome.js
```
```javascript
// app/javascript/packs/application.js
import 'css/application.scss'
```
```javascript
// app/javascript/packs/welcome.js
import 'css/welcome.scss'
```
```html
<!-- app/views/layouts/application.html.erb -->
<%= stylesheet_pack_tag 'application', 'welcome' %>
```

**Comment by gauravtiwari** [comment]
thanks @rossta 🍰 

Does this answers your question @benbonnet?

**Comment by benbonnet** [comment]
@gauravtiwari yep thx alot!

**Comment by cecilian** [comment]
Just to report a real-world use case, I just used the setup suggested by @rossta to manage dual scss for left-to-right and right-to-left layout in a multilingual application. And, it works perfectly. Thank you!
