### ISSUE TITLE
Windows 10, can't find executable webpack for gem webpacker

### ISSUE THREAD

**Issue by yorodm** [rails/webpacker#1366]
I'm using webpacker 3.3.1, Rails 5.1.5 and Ruby 2.4 on Windows 10, when I try to execute
``bundle exec webpack``
I get:
``
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/rubygems_integration.rb:458:in `block in replace_bin_path': can't find executable webpack for gem webpacker (Gem::Exception)
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/rubygems_integration.rb:478:in `block in replace_bin_path'
        from C:/Ruby24-x64/bin/webpack:23:in `<main>'
``

**Comment by gauravtiwari** [comment]
Please run `bundle exec rails webpacker:binstubs`

**Comment by yorodm** [comment]
Same result, also I get these warnings while installing webpacker
``
warning "@rails/webpacker > postcss-cssnext@3.1.0" has unmet peer dependency "caniuse-lite@^1.0.30000697".
``
``
warning " > webpack-dev-server@2.11.2" has unmet peer dependency "webpack@^2.2.0 || ^3.0.0".
``
``
warning "webpack-dev-server > webpack-dev-middleware@1.12.2" has unmet peer dependency "webpack@^1.0.0 || ^2.0.0 || ^3.0.0".
``

**Comment by rossta** [comment]
@yorodm What are the contents of your `./bin/webpack` file? Does executing the binstub directly work, i.e. `./bin/webpack` instead of `bundle exec webpack`?

**Comment by gauravtiwari** [comment]
@yorodm Were you able to figure this out? Also, perhaps you wanna give the latest version a shot and see if that fixes the issue for you.

**Comment by yorodm** [comment]
Sorry for the delay, some other project got stuck and had to shift my focus from Rails to Django. I will try the new version but nonetheless the problem seems to be related to the webpack version (yarn keeps installing ^4.0.0)

**Comment by yorodm** [comment]
@rossta  Yep, running `./bin/webpack` works as expected in version 3.4.3, still no luck using bundler tho.
These are the contents of `./bin/webpack`
```
#!/usr/bin/env ruby

ENV["RAILS_ENV"] ||= ENV["RACK_ENV"] || "development"
ENV["NODE_ENV"]  ||= ENV["NODE_ENV"] || "development"

require "pathname"
ENV["BUNDLE_GEMFILE"] ||= File.expand_path("../../Gemfile",
  Pathname.new(__FILE__).realpath)

require "rubygems"
require "bundler/setup"

require "webpacker"
require "webpacker/webpack_runner"
Webpacker::WebpackRunner.run(ARGV)
```

**Comment by gauravtiwari** [comment]
Please try the latest RC, otherwise feel free to open a new issue with more details.
