### ISSUE TITLE
Page not allowed to display insecure content from  webpack:///_datepicker.css

### ISSUE THREAD

**Issue by paneq** [rails/webpacker#1372]
I encountered the following and similar warnings on production

```
[blocked] The page at https://example.org/ was not allowed to display insecure content from webpack:///_datepicker.css.
```

I was able to reproduce it when a browser tried to load a map file.

![webpack_map](https://user-images.githubusercontent.com/65587/37817514-55138bfe-2e77-11e8-995e-93564990a1ce.png)

Versions:

```
$ bundle show webpacker
/Users/rupert/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/webpacker-3.2.1

$ bundle show rails
/Users/rupert/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/rails-4.2.10

$ yarn list --pattern webpack
yarn list v1.5.1
warning package.json: No license field
warning No license field
├─ @rails/webpacker@3.2.1
├─ case-sensitive-paths-webpack-plugin@2.1.1
├─ compression-webpack-plugin@1.1.6
├─ eslint-import-resolver-webpack@0.8.4
├─ extract-text-webpack-plugin@3.0.2
├─ uglifyjs-webpack-plugin@1.1.8
├─ webpack-dev-middleware@1.12.2
├─ webpack-dev-server@2.11.1
├─ webpack-manifest-plugin@1.3.2
├─ webpack-sources@1.1.0
└─ webpack@3.10.0
   └─ uglifyjs-webpack-plugin@0.4.6
```

I am not sure if this is a webpacker issue, webpack issue or webpack configuration issue. Let me know if you have any ideas.

**Comment by cseelus** [comment]
@paneq Did you find the reason for this behavior?

**Comment by paneq** [comment]
@cseelus Nope, never 😿

**Comment by cseelus** [comment]
We had this only with Safari 12.0, luckily its gone with 12.1. Weird tho …

**Comment by guillaumebriday** [comment]
It seems to be a browser related issue.

Check your headers or your browser extensions maybe.

Can this issue be closed ?
