### ISSUE TITLE
Question: env variable inside webpacker.yml

### ISSUE THREAD

**Issue by ratneshraval** [rails/webpacker#1373]
How do I use environment variables inside webpacker.yml?

Tried this syntax and it takes it as a literal string 

`<%= ENV['x'] %>`

**Comment by gauravtiwari** [comment]
@ratneshraval Webpacker.yml doesn't support erb since we use the same file on both JS and Ruby side. What's your use case?

**Comment by ratneshraval** [comment]
I want to set webpacker `public_output_path` based on  rails `RAILS_RELATIVE_URL_ROOT`

**Comment by gauravtiwari** [comment]
Ahh right, this is in todo but for now I guess you can append `RAILS_RELATIVE_URL_ROOT` in environment.js.

```js
const { environment } = require('@rails/webpacker')

environment.config.set(
  'output.publicPath', 
  `${process.env.RAILS_RELATIVE_URL_ROOT}${environment.config.output.publicPath}`
)

module.exports = environment
```

**Comment by ratneshraval** [comment]
I tried that with command 
`RAILS_RELATIVE_URL_ROOT=/xyz bundle exec rails assets:precompile`
but it didn't work! The packs were still placed directly in `public/packs` instead of `public/xyz/packs`

**Comment by gauravtiwari** [comment]
@ratneshraval Updated example ^^

**Comment by gauravtiwari** [comment]
Will get this in next release 👍

**Comment by gauravtiwari** [comment]
Lets track this issue in #1357
