### ISSUE TITLE
Webpacker HMR looking for json with content-type text/html with a 404 cause page reload

### ISSUE THREAD

**Issue by AirWick219** [rails/webpacker#1375]
I have got hmr set up where the webpack-dev-server if returning the correct hot-update.json back and it swapped the module without page reload. but there is an extra hot-update.json with a content-type of text/html that's is not there and throw a 404 which causes the page to reload. I was wondering if you guys have an idea of what that might be ?? 

webpacker 3.3.1, 
webpack-dev-server: 2.11.2

<img width="1029" alt="screen shot 2018-03-23 at 5 16 47 pm" src="https://user-images.githubusercontent.com/5618294/37855752-dcd3756c-2ebe-11e8-94fa-ca34bdd93241.png">
<img width="605" alt="screen shot 2018-03-23 at 5 16 56 pm" src="https://user-images.githubusercontent.com/5618294/37855757-e3a41b30-2ebe-11e8-9c97-74832a9cb8dd.png">

**Comment by gauravtiwari** [comment]
@ What version of Rails are you using?

**Comment by AirWick219** [comment]
I am on rails 5.1. Let me try to recreate this in my other repo. 

I faught with this a little bit last night and it seems that the ```6137e4 ...``` hash it is the same hash as the over all webpack compile hash from the console. Seems like something is going on with the webpack-dev-server.

I am not sure why its trying to look for that json in the generated boobstrap file for the other hash.

 

In this case, It's the ```86d36....``` hash

<img width="1497" alt="screen shot 2018-03-26 at 9 33 20 am" src="https://user-images.githubusercontent.com/5618294/37912743-c71a3276-30d8-11e8-8088-4eb9d67aef76.png">

![screen shot 2018-03-26 at 9 30 44 am](https://user-images.githubusercontent.com/5618294/37912704-ac833502-30d8-11e8-9fb0-135f6d87f1aa.png)

![screen shot 2018-03-26 at 9 30 54 am](https://user-images.githubusercontent.com/5618294/37912705-ac92faf0-30d8-11e8-81de-f8004bae236c.png)

**Comment by AirWick219** [comment]
Weird ... You can close this ... While preparing a example repo .. It magically works and the extra json is not there anymore which does not cause the 404.  

But in order to prevent the page refresh. I have to add the following code in my root level component to remount the latest module since I am using react-rails. 

```
components/Base.jsx

if (module.hot) {
  module.hot.accept('./Management', () => {
    ReactRailsUJS.mountComponents();
  });
}
```

Otherwise, I would get an error in the dev-server

```
Aborted because ./app/javascript/components/Management.jsx is not accepted
```

Since webpacker has a issue going on to restrict using ```webpack-dev-server``` 3+ 
https://github.com/rails/webpacker/issues/1303 . so not sure if that's something that would go away with  ```webpack-dev-server``` 3+

**Comment by gauravtiwari** [comment]
Great 👍 going to close this one for now.

**Comment by ahmadasaad89** [comment]
I have this exact problem, HMR is looking for a different hash than the one generated on recompile, any ideas why is this happening?
