### ISSUE TITLE
Integration with Ember

### ISSUE THREAD

**Issue by IlyaOsotov** [rails/webpacker#1392]
What about integration with EmberJS?
I mean something like this `rails new myapp --webpack=ember` or `bundle exec rails webpacker:install:ember`

**Comment by gauravtiwari** [comment]
Feel free to make a PR 👍

**Comment by michaelrkn** [comment]
Ember doesn't use webpack, so I'm not sure exactly how this would work. You might check out https://github.com/thoughtbot/ember-cli-rails.

**Comment by ytbryan** [comment]
Yeah, I also tried to do an ember default pack but failed. This probably can be closed until ember supports webpack

**Comment by LemonAndroid** [comment]
@ytbryan Is this planned for ember?
