### ISSUE TITLE
Change default location of javascript source directory

### ISSUE THREAD

**Issue by crispinheneise** [rails/webpacker#1397]
I'm not sure if this is the appropriate venue for this comment/question; if not could you point me to the right direction? 

It seems odd to me to have images and style sheet sources living together with javascripts under the app/javascripts directory. 

That is why, in every new project, the first thing I do is rename app/javascripts to app/frontend. It seems more natural to me to have the following directory structure: 

```
app/frontend/src          # javascripts
app/frontend/images       # images
app/frontend/stylesheets  # stylesheets
```

My impression is that Rails 6 will unify the asset pipeline and Webpacker into a single asset director, which would be ideal. But for now, I feel like it hurts my brain less to do make this change in new projects, and I was wondering if anyone else felt this pain.

**Comment by gauravtiwari** [comment]
No problem. 

Please see: https://github.com/rails/webpacker/pull/2 and https://github.com/rails/webpacker/pull/692
