### ISSUE TITLE
SyntaxError: Left hand side of operator '=' must be a reference.

### ISSUE THREAD

**Issue by ytbryan** [rails/webpacker#140]
**To reproduce:** 

1. Use the latest version of rails/webpacker gem `gem 'webpacker', github: "rails/webpacker"`
2. Install either the vue or react default-pack. 
3. Error `SyntaxError: Left hand side of operator '=' must be a reference` printed in browser js console. 

I am not sure what is causing this yet.

**Comment by gauravtiwari** [comment]
@ytbryan Can't reproduce. Did you add any additional code? Anything else you get in the console.

**Comment by ytbryan** [comment]
Oops, I did not. I tried again this morning and it works. Sorry for the misreporting! 😅
