### ISSUE TITLE
Commit 4.0.0-pre.2 breaks webpacker 3.4

### ISSUE THREAD

**Issue by sannyok81** [rails/webpacker#1401]
I'm using webpacker version 3.4. But after last commit 4.0.0-pre.2 my project became broken. Reason is, I define version of webpacker 3.4 in Gemfile, but after "bundle exec rails webpacker:install", generated package.json file contains webcker version 4.0.0-pre.2. It causes errors in runnning webpack.

**Comment by gauravtiwari** [comment]
@sannyok81 Thanks for reporting. Just published 3.4.3.
