### ISSUE TITLE
Webpacker can't find map.js...

### ISSUE THREAD

**Issue by Tioneb12** [rails/webpacker#1404]
Rails 5.1.5
Ruby 2.4.3
webpack 4.4.1

My app work fine before I want install geocoder. Since I have this message error :

Webpacker can't find map.js in /Users/ben/code/Tioneb12/ project/public/packs/manifest.json. Possible causes:
1. You want to set webpacker.yml value of compile to true for your environment
   unless you are using the `webpack -w` or the webpack-dev-server.
2. webpack has not yet re-run to reflect updates.
3. You have misconfigured Webpacker's config/webpacker.yml file.
4. Your webpack configuration is not creating a manifest.
Your manifest contains:
{
  "application.js": "/packs/application-8d71e5035f8940a9e3d3.js",
  "application.js.map": "/packs/application-8d71e5035f8940a9e3d3.js.map"
}

Webpack have not create the manifest.json.

What can I do ?

**Comment by gauravtiwari** [comment]
Are you including map.js through javascript_pack_tag? Looks like there is no entry file in packs/ called map.js and hence there is no file in manifest.json

**Comment by rossta** [comment]
Do you intend `map.js` to be bundled separately from `application.js`. If so, it should be its own file in `app/javascript/packs`. If not, then you would simply import it in `application.js` from another directory.

**Comment by Tioneb12** [comment]
Thks ;)

I have put : 
- map.js in app/javascript/packs/maps.js
- add in views/layouts/application.erb.html : 
    <%= javascript_pack_tag 'application' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js" %>
    <%= javascript_pack_tag "map" %>

**Comment by gauravtiwari** [comment]
@Tioneb12 Should be maps:

```
<%= javascript_pack_tag "maps" %>
```

**Comment by Tioneb12** [comment]
No sorry, it's a mistake... it's : app/javascript/packs/map.js

**Comment by gauravtiwari** [comment]
Cool, is all working now?

**Comment by Tioneb12** [comment]
No, it's always the same :(

**Comment by rossta** [comment]
Just as a sanity check, you restarted your Rails server after adding the `map.js` file to the project, correct?

**Comment by Tioneb12** [comment]
Yes I did it

**Comment by gauravtiwari** [comment]
If you can make an example on github for us, we can take a look for you.

**Comment by Tioneb12** [comment]
My repo : https://github.com/Tioneb12/rando
ᐧ

2018-04-03 18:19 GMT+02:00 Gaurav Tiwari <notifications@github.com>:

**Comment by gauravtiwari** [comment]
You have included webpack 4, which probably might be silently causing compilation to fail since 3.x doesn't support webpack 4. 

If you wish to use Webpack 4 then try pre version. 

```
yarn add @rails/webpacker@4.0.0-pre.2
```

```Gemfile
gem 'webpacker', '>= 4.x'
```

**Comment by Tioneb12** [comment]
Thks a lot for your help .... you are a love <3
