### ISSUE TITLE
[Angular] Import component specific/scoped styles?

### ISSUE THREAD

**Issue by hbomb79** [rails/webpacker#1407]
I've only really started rails and I really liked the look of angular, so I've been trying to get webpacker to work and I'm really struggling.

I noticed that importing HTML from a template file (for a component `templateUrl`) is documented, but I can't find anything that seems to work properly for component's `styleUrls`. I was hoping someone could help, although I know this isn't strictly an issue.

Here are the files I think are relevant, if you need any more, you know what to do.

###### app/javascript/dashboard/banner/banner.component.ts
```ts
import { Component, OnInit } from '@angular/core'
import templateString from './template.html'
import './banner.component.sass'

@Component({
    selector: 'app-banner',
    template: templateString
})
export class BannerComponent implements OnInit {
    constructor() {}

    ngOnInit() {}
}
```

###### app/javascript/dashboard/banner/banner.component.sass
```sass
p
    color: blue
```

###### app/javascript/dashboard/banner/template.html
```html
<p>I'm a banner</p>
```

###### config/webpack/environment.js
```js
const webpack = require('webpack')
const { resolve } = require('path')
const { environment, config } = require('@rails/webpacker')
const typescript =  require('./loaders/typescript')

environment.loaders.append('typescript', typescript)
environment.loaders.append('html', {
  test: /\.html$/,
  use: [{
    loader: 'html-loader',
    options: {
      minimize: true,
      removeAttributeQuotes: false,
      caseSensitive: true,
      customAttrSurround: [ [/#/, /(?:)/], [/\*/, /(?:)/], [/\[?\(?/, /(?:)/] ],
      customAttrAssign: [ /\)?\]?=/ ]
    }
  }]
})

environment.plugins.append('ContextReplacement',
  new webpack.ContextReplacementPlugin(
    /angular(\\|\/)core(\\|\/)(@angular|esm5)/,
    resolve(config.source_path)
  )
)

module.exports = environment
```

The above works, although it works a little _too well_. Instead of the p tag inside the banner component being colored blue, all p tags on the site are colored blue. It was my understanding that Angular supported component styles which were only available to that component. Am I misunderstanding, if not, how can I scope my css/sass to just the component.

I've looked at [css-modules](https://github.com/css-modules/css-modules), and don't really understand it; if that's the answer, could you please explain in slightly more detail than usual. I've also tried to follow the [example project](), however, I ran into issues with `require` that I can delve into if need be. It's my understanding that css-modules help for module specific styles; I don't really need that as I can just use the asset pipeline, I'm after component specific styles.

I've also tried the first 'workaround' in #963, however, it failed just as it did for people further on in that comment chain; hence I tried to follow the instructions given to others in that issue and have come up blank.

Any help is greatly appreciated, I'm at the breaking point here.

**Comment by jakehockey10** [comment]
Bummer no response.  Did you figure this out ever?

**Comment by hbomb79** [comment]
Unfortunately not, @jakehockey10. In the end, I ended up using one global stylesheet and just using the element names (like `app-banner`) to target them instead of packaging element-specific CSS.

It's an ugly solution, but it's all I could get working.

**Comment by guillaumebriday** [comment]
Is this issue still relevant? Feel free to reopen if needed

**Comment by jakehockey10** [comment]
It is relevant in the sense that I'd like for this to work.  But I would understand if this library didn't consider those desires relevant to them.  I think the problem is that people who like Angular and the Angular CLI and also love Ruby on Rails were hoping that the Angular integration would give them a little bit more of the functionality that the Angular CLI provides in terms of scaffolding out the Angular portion of the application.

But with Hotwire being released, I'm seeing less and less reason for anyone to care about Angular not being treated like a first-class citizen in the Rails ecosystem.
