### ISSUE TITLE
require statement for angular example broken

### ISSUE THREAD

**Issue by taboularasa** [rails/webpacker#141]
@gauravtiwari Hi there, I noticed that the path for requiring the angular example pack changed recently. I just tested on a new app and found this change breaks the pack. 

using: `require("hello_angular")` the example app works

using: `require("./hello_angular")` the example app does not work and there are no errors 

https://github.com/rails/webpacker/commit/77b6ea0909968424e69043c361f83e070527b86d#diff-cfabf609842d53ffbfb34e4508592450

**Comment by guilleiguaran** [comment]
Fixed

**Comment by gauravtiwari** [comment]
Can confirm ^
