### ISSUE TITLE
Add equivalent task to "rake assets:clean"

### ISSUE THREAD

**Issue by swrobel** [rails/webpacker#1410]
I don't see any straightforward way to remove all of the outdated packs from `public/packs[-test]` ... am I missing something?

**Comment by swrobel** [comment]
Thanks, I'm aware of that one, but that's like `assets:clobber`, not `assets:clean`.

**Comment by swrobel** [comment]
For context, Heroku's ruby buildpack depends on assets:clean to make sure slug sizes don't get too big. https://github.com/heroku/heroku-buildpack-ruby/blob/v177/lib/language_pack/rails4.rb#L92

cc @schneems

**Comment by investment-radar** [comment]
And for me another thing I want just like assets:clean, by default it will keep 3 versions of the assets files.

**Comment by swrobel** [comment]
possible solution: https://github.com/heroku/heroku-buildpack-ruby/pull/803#issuecomment-428772751

**Comment by ericboehs** [comment]
I've started on a solution here: https://github.com/rails/webpacker/compare/master...ericboehs:eb-4-clean-task

**Comment by ytbryan** [comment]
looking good! Send a PR!

**Comment by ericboehs** [comment]
I don't think it's ready. I believe it needs to keep recent versions of the assets or active user sessions will break after a deploy.

**Comment by ericboehs** [comment]
[It's ready](
https://github.com/rails/webpacker/pull/1744). Or as close to ready as I'm going to get it without some input. cc: @ytbryan @swrobel

**Comment by NielsKSchjoedt** [comment]
+1

**Comment by henrypoydar** [comment]
+1

**Comment by NielsKSchjoedt** [comment]
Looks like there as a cleanup plugin introduced for Webpacker itself, I added this, and it works great! It's a more integrated way of cleaning up those assets instead of relying on rails doing it. https://github.com/johnagan/clean-webpack-plugin
