### ISSUE TITLE
Specifying Custom localIdentName for css Modules as part of config.

### ISSUE THREAD

**Issue by bytheway875** [rails/webpacker#1411]
I noticed there was a recent change to the webpack config to add scssModule and cssModule support. However, it currently uses the default localIdentName, which is [hash:base64], and I still have to do this in order to get my more-descriptive localIndentName applied:

```
const cssModulesOptions = {
  // This must match the value of generateScopedName
  // in the .babelrc settings of react-css-modules.
  localIdentName: "[path]--[name]--[local]--[hash:base64:5]"
}

const CSSLoader = environment.loaders.get('moduleSass').use.find(el => el.loader === 'css-loader')

CSSLoader.options = merge(CSSLoader.options, cssModulesOptions)
```

I'm not sure how css-modules and react-css-modules work, but with the lighter-weight babel-plugin-react-css-modules, I need to make sure that my localIdentName in the css-loader config matches the generated class names. Since there is a huge performance advantage to using the babel-plugin vs the main package, and the default value of localIndentName is the not-so-descriptive [hash:base64] seems like this will be something people will need to do fairly often.

Is there any precendent for adding a config variable to webpacker.yml or elsewhere that we can then use in the getStyleRule file to feed it the localIdentName? 

If this seems like something that is feasible and useful, I can work on it.

**Comment by gauravtiwari** [comment]
@bytheway875 Thanks for filling the issue. I have been thinking about this too. Would make sense to provide a default minimal `localIdentName` that remains unique. We could have an options object on environment instance that can be responsible for providing some of these settings. 

Please feel free to make a PR to add this option.

**Comment by bytheway875** [comment]
Cool. I've forked the project, but I'm not sure how to get it running locally against a sample applications. Is it enough to link the gem locally?

**Comment by gauravtiwari** [comment]
@bytheway875 Thank you :)

In your gemfile: 

```
gem "foo", path: "/path/to/local_webpacker_path"
```

then to link webpacker npm package, run this inside webpacker directory: 

```
yarn link
```

this will create a local copy of the package, and to use in your sample application. Run below command inside sample application folder: 

```
yarn link @rails/webpacker
```

Note: Run above whenever you run `yarn install` inside sample application since that will override the local link.

**Comment by gauravtiwari** [comment]
Please try the latest RC, otherwise feel free to open a new issue with more details.
