### ISSUE TITLE
Sourcemap generation problem

### ISSUE THREAD

**Issue by MehmetKaplan** [rails/webpacker#1413]
I have been trying to generate the sourcemaps with an ultimate goal of debugging my React code within vscode.

Below are the crucial files. Even though ```webpack-dev-server``` seems as if it is generating ```.js.map``` files, I can not find them anywhere in the disk and VSCODE debug gives following error:

```Breakpoint ignored because generated code not found (source map problem?).```

My question is how can I generate *.js.map files, find them on disk?

The related files' contents are as follows:

    //config/webpack/development.js
    const environment = require('./environment')
    const config = environment.toWebpackConfig();    
    config.devtool = 'sourcemap';  
    module.exports = config;

And 

    #config/webpacker.yml

    # Note: You must restart bin/webpack-dev-server for changes to take effect
    
    default: &default
      source_path: app/javascript
      source_entry_path: packs
      public_output_path: packs
      cache_path: tmp/cache/webpacker
    
      # Additional paths webpack should lookup modules
      # ['app/assets', 'engine/foo/app/assets']
      resolved_paths: []
    
      # Reload manifest.json on all requests so we reload latest compiled packs
      cache_manifest: true #false kaplan
    
      extensions:
        - .coffee
        - .erb
        - .js
        - .jsx
        - .ts
        - .vue
        - .sass
        - .scss
        - .css
        - .png
        - .svg
        - .gif
        - .jpeg
        - .jpg
    
    development:
      <<: *default
      compile: true
    
      # Reference: https://webpack.js.org/configuration/dev-server/
      dev_server:
        https: true
        host: localhost
        port: 3035
        public: localhost:3035
        hmr: false
        # Inline should be set to true if using HMR
        inline: true
        overlay: true
        disable_host_check: true
        use_local_ip: false
    
    test:
      <<: *default
      compile: true
    
      # Compile test packs to a separate directory
      public_output_path: packs-test
    
    production:
      <<: *default
    
      # Production depends on precompilation of packs prior to booting for performance.
      compile: false
    
      # Cache manifest.json for performance
      cache_manifest: true

Output of the ```webpack-dev-server -d``` command is as follows. File names are deleted only application.js kept, but the idea is same:

    Project is running at https://localhost:3035/
    webpack output is served from /packs/
    Content not from webpack is served from /media/sf_SharedFolder/MOCMON/GlobalArea/Users/UsersServer/public/packs
    404s will fallback to /index.html
    Hash: *************                                                              
    Version: webpack 3.8.1
    Time: 44870ms
                                                           Asset     Size  Chunks                    Chunk Names
                         application-48d3865b78e43b7457f3.js.map  3.01 MB       0  [emitted]         application
                             application-48d3865b78e43b7457f3.js  2.66 MB       0  [emitted]  [big]  application
                                                   manifest.json   4.4 kB          [emitted]         
     [415] multi (webpack)-dev-server/client?https://localhost:3035 ./app/javascript/packs/application.js 40 bytes {0} [built]
        + 427 hidden modules
    webpack: Compiled successfully.

PS: Please be informed, I opened the same issue in stackoverflow but I suspect issue may be related with webpacker or my lack of knowledge about webpacker.

**Comment by MehmetKaplan** [comment]
Please ignore

**Comment by mackmm145** [comment]
@MehmetKaplan did you resolve this? could you share how?

**Comment by BobbyAdamson** [comment]
@MehmetKaplan I am having the same problem. I suspect I am doing something wrong. What was your solution?

**Comment by jakeNiemiec** [comment]
This may help https://github.com/rails/webpacker/issues/2003#issuecomment-511474134
