### ISSUE TITLE
Arrow functions are not being transpiled in production

### ISSUE THREAD

**Issue by gregblass** [rails/webpacker#1418]
I just launched my first production Rails app with webpacker. I wrote many of my JS functions using arrow notation, but then started getting errors being reported for users using IE11.

I assumed webpacker would handle this for me because it said 'ES6 with babel' under features on the readme.

I dove in a little bit to some of the issues on here, and one suggestion was to add import 'babel-polyfill' to app/javascript/packs/application.js - but that didn't seem to make any difference (unless I am doing something wrong).

In the meantime, I went back and converted all my arrow functions back to regular javascript functions since the code is in production, but I'd like to be able to use arrow functions in the future.

Is ES6 babel transpiling intended to work out of the box, or is there something I'm missing here that I need to do to get that to work? Furthermore, is there a gap in the documentation, or did I miss some key part?

**Comment by gauravtiwari** [comment]
@gregblass Could you paste the content of your .babelrc file, please?

Another way is to compile in ES5 mode by default, which was default behavior before but not anymore, now the compiler targets latest ECMA version 8, to change this:

```js
// environment.js
const environment = require('./environment')

environment.plugins.get("UglifyJs").options.uglifyOptions.ecma = 5

module.exports = environment.toWebpackConfig()
```

**Comment by gregblass** [comment]
```
{
  "presets": [
    [
      "env",
      {
        "modules": false,
        "targets": {
          "browsers": "> 1%",
          "uglify": true
        },
        "useBuiltIns": true
      }
    ],
    "react"
  ],
  "plugins": [
    "syntax-dynamic-import",
    "transform-object-rest-spread",
    [
      "transform-class-properties",
      {
        "spec": true
      }
    ]
  ]
}

```

**Comment by gregblass** [comment]
@gauravtiwari Anything look wrong there?

**Comment by gauravtiwari** [comment]
@gregblass Sorry for the late response. Looks good to me - http://browserl.ist/?q=%3E+1%25

Do you have any special setup in environment.js? What version of webpacker is this?

**Comment by gregblass** [comment]
Oh I know, IE11 is barely used - except the use case for this software -its for car dealerships. Probably no other industry would have IE11 usage like this except maybe hospitals or something. The first day we launched, it was a dumpster fire of issues.

I haven't touched environment.js - looks like the default file there.

Here's my package.json file:

`{
  "name": "vinup",
  "private": true,
  "dependencies": {
    "@rails/webpacker": "^3.2.0",
    "babel-preset-react": "^6.24.1",
    "coffeescript": "1.12.7",
    "dialog-polyfill": "^0.4.9",
    "prop-types": "^15.6.0",
    "react": "^16.2.0",
    "react-dom": "^16.2.0"
  },
  "devDependencies": {
    "webpack-dev-server": "^2.9.7"
  }
}
`

**Comment by gauravtiwari** [comment]
Thanks. Are you using coffeescript or ES6 mainly?

**Comment by gregblass** [comment]
No coffeescript. Just ES6.

Sure, I'll give this a try. Thanks for your help!

**Comment by gregblass** [comment]
Alright, I added it - but in development mode, in chrome, it's not transpiling it.

1) Does it only happen in production?
2) Does it only happen if the browser does not support it?

**Comment by gregblass** [comment]
I should probably read this, yeah? https://github.com/babel/babel/tree/master/packages/babel-preset-env

**Comment by gregblass** [comment]
So I just tried in development on IE11 using browser stack - no transpiling done. I'm guessing it will only happen in production? I'll test it out there.

**Comment by gregblass** [comment]
OK so can confirm, not transpiling the arrows still in production for IE11.

**Comment by gauravtiwari** [comment]
Right, I see - I will take a look at this tonight or tomorrow. Is it possible for you to make an example repo on github for me to check?

**Comment by gregblass** [comment]
No worries, I appreciate all your help thus far. I'm clearly missing something. I'll do more research and if I still can't get it going, I'll put together an example repo. I feel like you could just create a new rails app with webpacker enabled, and it just won't transpile by default?

**Comment by gauravtiwari** [comment]
Yep, that's what I am going to test.

**Comment by SerzN1** [comment]
Hi . Looks like had the same situation . Try to use special preset "react-app" in `.babelrc`
```
{
  "presets": [
    "react-app",
    "stage-0"
  ],
  "plugins": []
}
```

**Comment by gauravtiwari** [comment]
Please try the latest RC, otherwise feel free to open a new issue with more details.

**Comment by gregblass** [comment]
Hey there! I just finally tried again as I figured 6 months would be enough time for this to work out of the box. I'm now using a fresh install of webpacker (4.0.2) - but my arrow functions are still not being transcribed in production.

What am I missing here?

**Comment by gregblass** [comment]
Let me take a step back actually. Is there any way to tell in production if my transpiling is working whatsoever? Also - if I am testing on MS Edge and selecting emulation -> IE9 (on VirtualBox). Would this trigger the transpiling?

Thank you in advance to anyone who can explain a little bit here. I'm obviously a complete newby :(

**Comment by jakeNiemiec** [comment]
We are fighting this dragon over here: https://github.com/rails/webpacker/issues/2109#issuecomment-497462893. 

Can you post your environment.js, package.json, package-lock.json, babel.config.js and application.js to a https://gist.github.com in that issue?

**Comment by dimaShin** [comment]
Hi. Any chance this could be opened again as I don't see any solution here. or should I report new issue?
My babel.config if
`{
    presets: [['@babel/preset-env', {
      targets: {
        browsers: '> 1%, last 2 versions',
        chrome: '41',
        firefox: '41',
        safari: '9',
        ios: '7',
        android: '4.1',
        ie: '11',
      },
    }], '@babel/preset-react', '@babel/preset-flow'],
    env: {
      development: {
        plugins: ['react-hot-loader/babel'],
      },
      production: {
        plugins: [
          '@babel/plugin-transform-react-constant-elements',
          '@babel/plugin-transform-react-inline-elements',
        ],
      },
      test: {
        plugins: ['istanbul'],
      },
    },
    plugins: [
      '@babel/plugin-transform-runtime',
      '@babel/plugin-syntax-dynamic-import',
      ['dynamic-import-node', { noInterop: true }],
      '@babel/plugin-syntax-import-meta',
      '@babel/plugin-proposal-class-properties',
      '@babel/plugin-proposal-json-strings',
      '@babel/plugin-proposal-function-sent',
      '@babel/plugin-proposal-export-namespace-from',
      '@babel/plugin-proposal-numeric-separator',
      '@babel/plugin-proposal-throw-expressions',
    ],
    sourceMaps: true,
  }`
babel version is @7.4.5

**Comment by jakeNiemiec** [comment]
@dimaShin, please see https://github.com/rails/webpacker/issues/1418#issuecomment-498286779, make sure to additionally post the error you are encountering.

**Comment by dimaShin** [comment]
Hi @jakeNiemiec. Thank you for your response. Unfortunately I don't see how  #2109 is related to my issue.
I'm facing the problem that arrow functions are left in the bundle even though I've put ie11 in the targets. So there is no any errors in the stdout, but application doesn't work in IE

**Comment by jakeNiemiec** [comment]
> Unfortunately I don't see how #2109 is related to my issue. I'm facing the problem that arrow functions

The arrow functions just indicate that there is a wider problem that is preventing your babel from running. The other issue can [help troubleshoot your issue](https://github.com/rails/webpacker/issues/2109#issuecomment-498336919), but I was really pointing to this part of the comment:

> **Can you post your environment.js, package.json, package-lock.json, babel.config.js and application.js** to a https://gist.github.com in that issue?
