### ISSUE TITLE
webpacker:vue vuex state computed error

### ISSUE THREAD

**Issue by BoleLee** [rails/webpacker#1423]
when  the state value of vuex change, the computed data from the vuex state didn't change.
当vuex状态树的state值改变后，这些state值的相对应的computed计算属性的值没有跟着变化，一直维持初始值。
**problem reappear demo:**  [problem reappear demo](https://github.com/BoleLee/rails-webpacker-vue)

**Comment by ytbryan** [comment]
You are using Vue-router which is not supported by default. There is also Rails router at play. 

You can see how I use vuex here. https://github.com/ytbryan/vuex-example

**Comment by BoleLee** [comment]
@ytbryan I have seen your vuex-example project, and change my demo project according to yours, but still didn't solve my problem. 
Can you spend some time to see [my updated project demo](https://github.com/BoleLee/rails-webpacker-vue) and help find what I was wrong?

and I have another question: why you can use ```<%= vue_component "" %>``` tag, I have tried to use it but it report error.

**Comment by ytbryan** [comment]
@BoleLee 

At `app/javascript/packs/test.js`, use this
```
// import Vue from 'vue/dist/vue.esm'
import Vue from 'vue'
```

`vue_component` is simply `javascript_pack_tag` + `stylesheet_pack_tag`. To  disable stylesheet with `<%= vue_component "", stylesheet: false %>` It is part of the [vuejs gem](http://github.com/ytbryan/vuejs)

**Comment by BoleLee** [comment]
@ytbryan Thank you very much! It has helped solve my problem.

**Comment by ytbryan** [comment]
No problem. Please close this issue. 

Also, for future webpacker questions, please use stackoverflow.
