### ISSUE TITLE
Webpacker::Manifest::MissingEntryError

### ISSUE THREAD

**Issue by xero88** [rails/webpacker#1424]
I get Webpacker::Manifest::MissingEntryError

**Comment by gauravtiwari** [comment]
Could you please share more info on this?

**Comment by xero88** [comment]
Sorry, it was not related to webpacker itself but with Rails

**Comment by igbanam** [comment]
@xero88 how did you resolve the error? Or could you point us to somewhere where it's being resolved

**Comment by xero88** [comment]
@igbanam I resolved with : 

bundle exec rails webpacker:install:react
