### ISSUE TITLE
Intermittant MIME type error

### ISSUE THREAD

**Issue by kingpalethe** [rails/webpacker#1427]
I am finding with webpacker/rails5.2/react andI have this error intermittently. 

The Chrome error:
```
Refused to execute script from 'https://xxxx.c9users.io/packs/app-db2321ee442b54d8590a.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

````
The Firefox error
```
Loading failed for the <script> with source “https:/xxxx.c9users.io/packs/app-0d57c79a1493e661aa6a.js”.

```
The issue comes up randomly. It seems usually I can solve it with these steps.

1. CNTRL-C to quit rails and webpacker in the console.
2. `yarn install` in console (If I don't do this, I get the dreaded ` No such file or directory - /home/ubuntu/workspace/factbar/node_modules/.bin/webpack-dev-server (Errno::ENOENT)`
3. Start the server again.
4. Reload the browser twice

**Comment by kingpalethe** [comment]
And I've found an easier hack to solve it: Just open up any `.js` file, anything that will trigger a new Webpack compilation, save it, see that Webpack has recompiled, then load the page again. So somehow my compilations are "going bad", but can be refreshed like this.

**Comment by ukazap** [comment]
Can repro.

**Comment by archonic** [comment]
I started getting this error after updating from webpacker 3.4.3 from 3.3.0. Downgrading didn't help so I'm not sure that's related. I was getting this error for both application.css and application.js. Making a change to application.css worked but no editing to application.js is making that error go away.

The contents of application.js is just `Cannot GET /packs/application-8eaa34a62b42ec360920.js` despite compiling without errors.

**Comment by seanfcarroll** [comment]
I'm getting the same problem, and all was working perfectly yesterday. (confused)

**Comment by shenst1** [comment]
I had this error when I had two rails applications running a service at port `8080`. Are you running multiple node servers? I shut the one I wasn't using down and the error went away.

**Comment by rriikkuu** [comment]
I came across this issue again. I'm on webpack 3.5.3 and 2.11.1 webpack-dev-server. One thing i noticed is this happens only when my rails server log also outputs compilation message:

```
Started GET "/" for 127.0.0.1 at 2018-05-26 00:51:08 -0400
Processing by WelcomeController#index as HTML
  Rendering welcome/index.html.erb within layouts/application
[Webpacker] Compiling…
[Webpacker] Compiled all packs in C:/Users/Danny/Desktop/paperVue/public/packs
  Rendered welcome/index.html.erb within layouts/application (6765.6ms)
Completed 200 OK in 6859ms (Views: 6841.4ms | ActiveRecord: 0.0ms)
```

Specifically this message

```
[Webpacker] Compiling…
[Webpacker] Compiled all packs in C:/Users/Danny/Desktop/paperVue/public/packs
```

**Comment by gauravtiwari** [comment]
@rriikkuu The on-demand compiler shouldn't run if you are using webpack dev server. Are you sure webpack dev server is running?

**Comment by rriikkuu** [comment]
@gauravtiwari I believe so. Hot reload works for the most part, then randomly it will attempt a hot reload when I save a change in my code and it will fail to load the bundle. Every time i encounter this issue, I see that webpacker compiling message. 

I then make another change, save (which prompts webpack-dev-server to recompile), and reload the page manually. When i do this, the bundle is loaded properly.

**Comment by DataCourier** [comment]
Been getting this issue as well but for me it doesn't go away no matter how many restarts, yarn reinstalls asset cleaning, or file poking I do. I can't recall how I got it working last time and I am getting messages like this one when I visit the files:

```
Cannot GET /packs/help-88e5d007f846a1331049.js
```

**Comment by cw2908** [comment]
I had this issue but also solved by `kill`ing the processes running here: `ps -x | grep webpack`
