### ISSUE TITLE
Hot Module Reloading Not Working on a fresh install

### ISSUE THREAD

**Issue by coorasse** [rails/webpacker#1437]
**Fresh installation:**
ruby: 2.5.0
rails: 5.2.0
node: 8.9.4
webpacker: 3.4.3

**Steps**
Edit `webpacker.yml` and set `hmr: true`

Run `bin/webpack-dev-server`

**Expected result**

Hot module reloading is running and working

**Actual result**
HMR seems to work: I even have a confirmation message in developers console but it does not. Check video: http://recordit.co/N8WazSywMB

Also notice that if I enable HMR, stylesheets are not served at all and not inlined as described also in #1233

**Comment by coorasse** [comment]
You are right. I just missed that step and thought it would just work out of the box. Seems like we need to adapt some code in order to have it working. I also managed to have scss hot reload working by reading the docs a bit more in detail. Thanks

**Comment by gastonmorixe** [comment]
This is how I got HMR working with React without reloading the full page.

```javascript
import React from "react"
import ReactDOM from "react-dom"

import RootComp from "./root/"

let root = null
const el = document.createElement("div")

document.addEventListener("DOMContentLoaded", () => {
  root = document.body.appendChild(el)
  ReactDOM.render(<RootComp />, el)
})

if (module.hot) {
  module.hot.accept("./root/", () => {
    console.log("HMR Update!")
    ReactDOM.render(<RootComp />, el)
  })
}
```

**Comment by domi91c** [comment]
Can someone tell me how to get HMR working with Vue?
