### ISSUE TITLE
Do not include the same imports into numerous packages.

### ISSUE THREAD

**Issue by codemotion** [rails/webpacker#1443]
I've a project with a lot of packages (every controller has it's own — basically to render Vue).

But, for example, every shared components (Posts component can be rendered at Main, Search, Blog page, User page and so on) INCLUDE the same script.

Look at the image:

![screen shot 2018-04-22 at 19 37 31](https://user-images.githubusercontent.com/626493/39097443-0ee1809a-4665-11e8-8fbe-48c0664f6ade.png)

I've already use `webpack.optimize.CommonsChunkPlugin` to move Vue, Axios and others to separate bundle. But every locally imported component still is included all-over others.

**Comment by rossta** [comment]
What you probably want is another common chunk for those shared components. You need to configure this yourself in version 3, otherwise, Webpack doesn't know you want them to be shared. As @renchap said, it's possible v4 defaults may be better in this regard.

**Comment by codemotion** [comment]
Thanks, guys.

Have you try webpack 4 with this gem? Can't get it work.

**Comment by Jeremy-Walton** [comment]
Has a solution that uses webpack 4 been found yet? I am running into this exact same issue and I can't get the new SplitChunksPlugin https://webpack.js.org/plugins/split-chunks-plugin/ to work.

**Comment by Jeremy-Walton** [comment]
> Has a solution that uses webpack 4 been found yet? I am running into this exact same issue and I can't get the new SplitChunksPlugin https://webpack.js.org/plugins/split-chunks-plugin/ to work.

I was able to figure out how to get this working by adding this into my config/webpack/environment.js

```
environment.config.set('optimization', {
  splitChunks: {
    chunks: "all",
    name: 'vendor',
    cacheGroups: {
      vendors: {
        reuseExistingChunk: true
      }
    }
  }
});
```

In my application.html, I added this into the head so it gets included on every page.
`= javascript_pack_tag 'vendor'`

The result is the total file size from all my packs dropped from 65mb to 5mb.

**Comment by gauravtiwari** [comment]
Please try the latest RC, otherwise feel free to open a new issue with more details.
