### ISSUE TITLE
bundle exec rails webpacker:install does not create src or images directory /app/ as the Readme suggests

### ISSUE THREAD

**Issue by cabanalabs** [rails/webpacker#1444]
How to reproduce:
- Install Rails 5.2.0 and then run:
`rails new my_test_app --webpack"`
`cd my_test_app`
`rails webpacker:install`

The readme suggests that this will create three app/javascript/packs app/src and app/images
but this only seems to create app/javascript/packs and the src and images directories are missing.

**Comment by ytbryan** [comment]
Which part of the readme?

**Comment by ytbryan** [comment]
I see. `rails webpacker:install` does not create  `src` or `images` directories. But those directories could be created manually to store css and images respectively. 

Why don't you send in a PR to improve that part of readme?

**Comment by cabanalabs** [comment]
Ah thanks for clarifying. Sure, I'd be happy to send a PR with a suggested improvement.
