### ISSUE TITLE
ActionController::RoutingError (No route matches [GET] "/_next/webpack-hmr") every 20secs

### ISSUE THREAD

**Issue by felipero** [rails/webpacker#1447]
Hi, I just created a fresh install of Rails 5.2 with webpacker and vue js. Everything work fine so far, with a few tweaks on the vue generated code. The only issue is that I'm getting several RoutingErrors. Every 20secs or so. Like that:

```21:36:41 rails.1   | Started GET "/_next/webpack-hmr" for ::1 at 2018-04-24 21:36:41 -0300
21:36:41 rails.1   |
21:36:41 rails.1   | ActionController::RoutingError (No route matches [GET] "/_next/webpack-hmr"):
21:36:41 rails.1   |
21:36:41 rails.1   | actionpack (5.2.0) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
```

Looks like something is trying to check the hmr, but is actually hitting the wrong url. Maybe this request should be in the port 3035 instead?

**Comment by ytbryan** [comment]
can you share your repo?

**Comment by felipero** [comment]
@ytbryan Here it goes: https://github.com/felipero/webpacker-hmr-issue

**Comment by felipero** [comment]
By the way, I'm running ruby 2.5.1 with Rails 5.2.0. Webpacker 3.4.3 and @rails/webpacker 3.4.

I also tried with webpacker 4.0.0.pre

**Comment by ytbryan** [comment]
Nope, I don't have that. Restart your computer? Restart terminal? 


```
=> Booting Puma
=> Rails 5.2.0 application starting in development 
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.11.4 (ruby 2.5.1-p57), codename: Love Song
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://0.0.0.0:3000
Use Ctrl-C to stop
Started GET "/" for 127.0.0.1 at 2018-04-25 10:38:45 +0800
Processing by PagesController#home as HTML
  Rendering pages/home.html.erb within layouts/application
  Rendered pages/home.html.erb within layouts/application (3.7ms)
Completed 200 OK in 1947ms (Views: 1943.2ms | ActiveRecord: 0.0ms)
```

**Comment by felipero** [comment]
OMG... It was an old chrome tab from another next.js project I left open. It kept trying to reach `_next/webpack-hmr` for the whole weekend. 
![image](https://user-images.githubusercontent.com/21774/39225992-05d0d420-4826-11e8-8dce-120a3d024663.png)

@ytbryan I'm so sorry to waste your time with this. I wasted 2 hours myself with this. Your answer triggered me to figure it out. Rubber duck debugging.

**Comment by ytbryan** [comment]
no problem :) we learn something new every day :)

**Comment by jmelkor** [comment]
@felipero, thanks for this thread! It help me too to find the solution in 2 minutes.

**Comment by Montaguti** [comment]
I just installed the Next.js and was thinking it could be a problem in the installation procces affecting the rails gems folder (???).
I'm glad for this thread.

**Comment by jonathandean** [comment]
haha same!

**Comment by cassiano** [comment]
To solve it (temporarily), create an empty file in the public folder: `touch public/_next/webpack-hmr`

Any final solutions, please?

**Comment by innocentamadi** [comment]
@cassiano Closing the next.js application that is also on the same port as rails should fix it. If you need to run next.js, just run it on a different port from rails.

**Comment by FernandoNaon** [comment]
Same here, This thread is highly valuable!

**Comment by holdmypotion** [comment]
I can't believe we all are facing such an issue. Thanks for the thread. Helped a lot https://github.com/rails/webpacker/issues/1447#issuecomment-384155924
