### ISSUE TITLE
Allow to override @node_modules_path

### ISSUE THREAD

**Issue by tmaier** [rails/webpacker#1449]
`@node_modules_path` is hardcoded to `@node_modules_path = File.join(@app_path, "node_modules")`

Yarn actually allows to override this setting with `--modules-folder /usr/local/node_modules` (e.g. in the `.yarnrc` file)

## Use case

This can be useful when docker is being used for development.
One may mount the working directory as volume, which would allow to edit the files in the host system and execute the dev environment at the same time in docker.

The host system may compile packages, like node-sass differently on OS X or Ubuntu than on the Alpine (musl)-based docker system.
As the node-modules folder is assumed to be in the working directory, the packages may have been compiled for the wrong Operating System (host vs docker)

## Required changes

- Allow to override `@node_modules_path`, e.g. with `ENV['NODE_PATH']`
- Get the right modules folder directly from yarn
  e.g. `$ yarn config list` outputs `{ '--modules-folder': '/usr/local/node_modules' }`

**Comment by tmaier** [comment]
This is how one may run `$ yarn install` within his `Dockerfile`

```dockerfile
FROM ruby:2.4-alpine3.7

# ...

ENV NODE_PATH=/usr/local/node_modules
RUN true \
  && echo "--modules-folder /usr/local/node_modules" >> ~/.yarnrc \
  && yarn install --frozen-lockfile \
  && yarn cache clean \
  && mv ~/.yarnrc /home/myuser/.yarnrc \
  && chown myuser:myuser /home/myuser/.yarnrc
```

**Comment by gauravtiwari** [comment]
@tmaier Happy to accept a PR allowing to change PATH using an ENV variable.

**Comment by tmaier** [comment]
I actually found a better command `$ yarn bin` (<https://yarnpkg.com/en/docs/cli/bin>)

`NODE_PATH` is also not used by webpack and actually discouraged to use at all. (<https://github.com/webpack/webpack/issues/4479#issuecomment-286701441>)

My assumption going forward for a Pull Request:
- `NODE_PATH` is not necessary anymore and can be removed
- The only left use-case for `@node_modules_path` is fin find the binaries `webpack` and `webpack-dev-server`
- Yarn tells us exactly where he installs this binaries with `$ yarn bin`. I would run it with `%x[yarn bin]`

**Comment by tmaier** [comment]
@gauravtiwari, please check out the pull request #1450.

Going forward, the `Dockerfile` would look like this:

```dockerfile
FROM ruby:2.4-alpine3.7

# ...

RUN \
  && echo "--modules-folder /usr/local/node_modules" >> ~/.yarnrc \
  && yarn install --frozen-lockfile \
  && yarn cache clean \
  && mv ~/.yarnrc /home/myuser/.yarnrc \
  && chown myuser:myuser /home/myuser/.yarnrc
```
