### ISSUE TITLE
Tag 1.0

### ISSUE THREAD

**Issue by swrobel** [rails/webpacker#145]
The 1.0 gem was released but there's no corresponding tag to indicate which commit was released.

**Comment by gauravtiwari** [comment]
@swrobel 
(bumped to 0.2) 

[Commit] https://github.com/rails/webpacker/commit/abe02c161bcbb8b79c889540946818a213a728c2 

[Page Jan 17]
https://github.com/rails/webpacker/commits/master?after=Y3Vyc29yOrKqMlvb4oa8U%2Bpuegs1bdUkMsaJKzEwNA%3D%3D 

(TO)

(Bumped to 1.0)
[Page Feb 23]
https://github.com/rails/webpacker/commits/master?after=Y3Vyc29yOrKqMlvb4oa8U%2Bpuegs1bdUkMsaJKzM0

[Commit]  
https://github.com/rails/webpacker/commit/47e935c3679348bf5c26ea0400e8d90330ff1209

**Comment by rafaelfranca** [comment]
Done. I think @dhh forgot to push the tag

**Comment by dhh** [comment]
Did. My bad! Thanks for the cleanup.
