### ISSUE TITLE
Loading HTML: loaded, but reference using #asset_pack_path fails

### ISSUE THREAD

**Issue by qd3v** [rails/webpacker#1469]
Hi! I'm not sure this problem is related to webpacker gem, so sorry if I'm wrong.
I'm working on web component, and I have this simple configuration:

`/config/webpack/loaders/html-loader.js`:

```
module.exports = {
  test: /\.html$/,
  use: [{
    loader: 'html-loader' // also tried `wc-loader`, `polymer-webpack-loader`
  }]
}
```

`/config/webpack/loaders/environment.js`:

```
//...
environment.loaders.append('html-loader', require('./loaders/html-loader'))
//...
```
Webpack loads html file as it should (html contents imported to pack file) but as soon as I add this line in view (slim):

```
link rel="import" href="#{asset_pack_path 'custom_wc/picture_frame.html'}"
```

I get this error:

`Webpacker can't find custom_wc/picture_frame.html in ... /packs/manifest.json`

Also target html file not generated in `public/assets/packs` directory if I run `RAILS_ENV=production rake webpacker:compile`, and manifest entry also missing.
It was a long time ago last time I used webpack, and I really tried to find the solution by myself, asked in Ruby on Rails Link's #frontend Slack channel, but no luck...
What am I doing wrong?
Thanks!
P.S. importing and referencing images works as it should

**Comment by vanburg** [comment]
Got another problem: in dev mode with livereloading, manifest.js doesn't get updated, and always points to compiled at startup (first) .html file version...
Frontend tools is so hard to use... :)
