### ISSUE TITLE
Support for webpack --output-public-path into webpacker.yml production:

### ISSUE THREAD

**Issue by jwhentsch** [rails/webpacker#1470]
I have a smal rails test app which is rails +vue + vuetify +some fonts. The main goal is to provide the fonts from the app itself, not via google fontservice ore somthing similar.

I have those packages (package.json) for the fonts

- roboto-fontface-woff

- material-design-icons-iconfont

- font-awesome

The fonts get bound in like described in the fonts packages.

In development mode, everything works fine.

For Production, calling "**bundle exec rails assets:precompile**" generates the packs under public/packs and the fonts under public/packs/_/_/node_modules/font-awesome and the like.
The problem is, my Apps root path is "/csm/modules/jwhTest" and the references webpack generates into my code for .js and .css - files are correct and finally result in letting the browser get the files from "https://myhost/csm/modules/jwhTest/packs/fonts-3bb196446076dc31757f1fceda129288.css". But the browser tries to load the fonts from " https://myhost/packs/_/_/node_modules/font-awesome/fonts/fontawesome-webfont-af7ae505a9eed503f8b8e6982036873e.woff2" which is wrong, the app root is missing.

When i call "bin/webpack **--output-public-path=/csm/modules/jwhTest/packs/**" afterwards, everything gets generated correct - everything works perfect.

I've tried to achieve the same thing with setting "public_output_path" in the production: section of webpacker.yml - but that's not working it even generates wrong paths to the .js and .css files.

So please, could you sort of implement a real support for the webpack --output-public-path - option in webpacker.yml. I guess, this would solve a lot of similar problems with font support I've seen people writing/complainig about.

In the mean time I just write my own entry in Rakefile which does simply a "bin/webpack **--output-public-path=/csm/modules/jwhTest/packs/**" at the very end of the building process.

Thanks in advance,

jwh

**Comment by ericenns** [comment]
Wouldn't this make more sense to tie into RAILS_RELATIVE_URL_ROOT env variable.

Needs to be changed on this line https://github.com/rails/webpacker/blob/b7e69e91aec051d5913ee3be05a0789800834e1d/lib/webpacker/compiler.rb#L56
