### ISSUE TITLE
blank page with commented body vue.js webpacker on production, works fine on dev.

### ISSUE THREAD

**Issue by ozkar99** [rails/webpacker#1471]
First of all, thanks for taking the time to read this, and making webpacker a reality in rails, its great.

Now about the issue:

From what ive seen it has to do something with the runtime/compiler version of vue.js, my guess is that webpacker is not loading correct import for production only for dev(which i have no clue how to diagnose correctly, its a guess at this point) i've tried both setting the webpacker alias from vue to  `vue/dist/vue.esm.js` and also importing directly from that (as seen on `javascripts/packs/application.json` example) . 

Repo for this is hosted at:
https://github.com/ozkar99/tools/tree/webpacker-prod 

Prod Screenshots:

If you go to sources page renders html
![image](https://user-images.githubusercontent.com/4227887/39533490-cef23e6a-4df4-11e8-95de-cd2aba5ba069.png)

If you go to elements, its just a comment:
![image](https://user-images.githubusercontent.com/4227887/39533617-23b3a164-4df5-11e8-9e7d-13ad2ba4f370.png)

Ive been searching high and low, and everything should work, its based off:

https://gorails.com/episodes/vuejs-components-in-rails-views?autoplay=1

Let me know if you have any suggestions or pointers on how to correctly diagnose this problem.

**Comment by ytbryan** [comment]
Did you try to precompile assets for production? `rails assets:precompile`

**Comment by ozkar99** [comment]
Yes, they are being precompiled and loaded:

![image](https://user-images.githubusercontent.com/4227887/39534434-319654f0-4df7-11e8-9328-0116774d9418.png)

I even searched for `data-behaviour=vue` and its there, meaning webpack is grabbing `packs/application.js` and compiling it.

One thing to note (might be related to the issue or not) the source map files are blank.

**Comment by rossta** [comment]
Try changing your import to `import Vue from 'vue';` (that's what I do on my Webpacker + Vue Rails project). You probably don't want to import the ES module version because, by default, Webpacker won't apply babel-loader to your node_modules imports. More info from this wenkanglin's comment in the Vue forums: https://forum.vuejs.org/t/whats-the-difference-between-vue-esm-js-and-other-vue-dist-files/7259/10

**Comment by ozkar99** [comment]
@rossta, you mean while also removing the alias correct?

Wouldn't this mean i have to also change how i mount the root vue.js element? because i wouldnt have the compiler available?

PS: i forgot to specify the branch for this current code, its updated on the main comment now.

**Comment by ozkar99** [comment]
Additional Notes:

If i delete the `public/packs` and set `webpacker.yml` to `cache manifest: false` on production then i get this:

![image](https://user-images.githubusercontent.com/4227887/39538252-cff6c4c2-4e01-11e8-9364-2abdfb4fc05f.png)

And now the sourcemaps do work.

Seems like `assets:precompile` its not building correctly? and was not displaying anyhting to the console?

Will add unsafe eval to production, and do further testing.

**Comment by ozkar99** [comment]
@rossta 
i think there was misunderstanding, i dont have any vue-compiler set up explicitily, i meant that i am using the template compiler enabled vue.js instead of the runtime only vue.js.

**Comment by ozkar99** [comment]
Closing this issue as it has nothing to do with webpacker and more about cs_policies, thank you everyone for your guidance.

**Comment by phortx** [comment]
@ozkar did you find a solution? I have the same problem here and adding `unsave_eval` for production is my current workaround but one shouldn't do that I think.

**Comment by Ozkar** [comment]
@phortx you probably meant to mention @ozkar99

**Comment by phortx** [comment]
@Ozkar Oh yes! Sorry for bothering you 😅

**Comment by ozkar99** [comment]
Sorry @phortx, no. also using unsafe eval on prod.

**Comment by phortx** [comment]
Oh ok, that's bad. Shouldn't we reopen this issue? I'm not an expert, but it feels like a webpacker issue, isn't it?

**Comment by mrsweaters** [comment]
Ah, this solved the problem: https://stackoverflow.com/a/48651338
