### ISSUE TITLE
Idea: switch to webpack-command

### ISSUE THREAD

**Issue by renchap** [rails/webpacker#1472]
[`webpack-command`](https://github.com/webpack-contrib/webpack-command) has recently been announced: https://medium.com/webpack/webpacks-new-cli-hotness-d6a2063168a8.
It is a rewrite of `webpack-cli` focused on modularity, with the end goal being replacing it with a lighter and better-architectured alternative.

I think it would be a good idea to evaluate if we can use it in Webpacker, as currently `webpack-cli` is mostly abstracted from the user, and installing less dependencies (the new `webpack-command` is 92% smaller when accounting dependencies, according to the blog post) is a nice win.

**Comment by renchap** [comment]
webpack-cli will be deprecated soon: https://medium.com/webpack/unladen-swallows-and-the-deprecation-of-webpack-cli-39814f6694d3

**Comment by gauravtiwari** [comment]
https://github.com/webpack-contrib/webpack-command is deprecated
