### ISSUE TITLE
Example Stimulus application.js matches any single char before js extension, not "."

### ISSUE THREAD

**Issue by bayprogrammer** [rails/webpacker#1477]
I believe in the regular expression contained here:

https://github.com/rails/webpacker/blob/89e4d602c29ca5cf89d7e634a7e901225d2e7a4f/lib/install/examples/stimulus/application.js#L5

we *mean* to match filenames ending in ".js" (as in, the literal "." character), rather than "js" preceded by any character.

Simple REPL example of the problem:

```javascript
> context = /.js$/
> context.test("hello_controller.js")  //=> true, as expected
> context.test("hello_controllerjs")  //=> also true, though not what new user likely expects

> context2 = /\.js$/
> context2.test("hello_controller.js")  //=> true
> context2.test("hello_controllerjs")  // => false
```

The latter form may lead to fewer unexpected issues for users.

**Comment by ytbryan** [comment]
@bayprogrammer Thank you, please send in a PR!
