### ISSUE TITLE
Vue use plugin with Typescript doesn't work

### ISSUE THREAD

**Issue by tchukuchuk** [rails/webpacker#1479]
Hi,

I have an issue with Vue.use for plugins with Typescript.

In my [sample project](https://github.com/tchukuchuk/webpacker-typescript-vue-plugin-issue) , I use the [vue-mq plugin](https://github.com/AlexandreBonaventure/vue-mq) which normally adds $mq on this.
So I declare $mq in the [plugins.d.ts](https://github.com/tchukuchuk/webpacker-typescript-vue-plugin-issue/blob/master/app/javascript/plugins.d.ts).

If I add Vue.use in the [application.ts](https://github.com/tchukuchuk/webpacker-typescript-vue-plugin-issue/blob/master/app/javascript/packs/application.ts), it doesn't seem to modify the Vue global instance. You can see this in the [Sample component](https://github.com/tchukuchuk/webpacker-typescript-vue-plugin-issue/blob/master/app/javascript/components/Sample.vue).
If I add Vue.use in the [Sample component](https://github.com/tchukuchuk/webpacker-typescript-vue-plugin-issue/blob/master/app/javascript/components/Sample.vue#L14), it works.

Do I miss something ?

Thanks.

**Comment by tchukuchuk** [comment]
Somebody can help me ?

**Comment by tchukuchuk** [comment]
I tried without webpacker, but only with webpack and it works !

https://github.com/tchukuchuk/webpack-typescript-vue-plugin

**Comment by ytbryan** [comment]
If you can write the installation and configuration instruction of your plugin, it will be great. 

Bryan

**Comment by tchukuchuk** [comment]
Actually, it's not a plugin. It's a sample application which demonstrates the use of " Vue.use " for plugins with Typescript.

You need to install packages with Yarn for example :

`yarn install`

Then you can run webpack with :

`node_modules/.bin/webpack-dev-server`

After, you can see in you console that `this.$mq` has a value whereas it doesn't have one with the [webpacker sample application](https://github.com/tchukuchuk/webpacker-typescript-vue-plugin-issue).
