### ISSUE TITLE
How to add custom alias.

### ISSUE THREAD

**Issue by hateonion** [rails/webpacker#1482]
Hi, I want to add some custom alias as I used did in webpack. 

I checked with this https://github.com/rails/webpacker/blob/master/docs/webpack.md#configuration, 
but seems when I call `environment.config.merge()`, it's actually not a function.

So except I did something like this.

```javascript
// config/webpack/development.js(test.js/prod.js as well)

const custom = require('./custom');
const env = require('./environment');
const _ = require('lodash')

const mergedConfig = _.merge(env.toWebpackConfig(), custom);
module.export= mergedConfig;

```
Is there any formal way I can merge my custom alias?
Thanks

**Comment by BoleLee** [comment]
@hateonion did you want to add some alias like:
`'@': 'app/javascript/src' `

Have you find how to config this ?

**Comment by BoleLee** [comment]
[#986](https://github.com/rails/webpacker/issues/986#issuecomment-408062235)

**Comment by stoplion** [comment]
#986 shows an export map of routes? How does that fix it?
And what does the file ./custom suppose to contain?
