### ISSUE TITLE
Duplicates sass style prop at the output.

### ISSUE THREAD

**Issue by Volosojui** [rails/webpacker#1485]
Hi. When I apply sass function to the value of any prop, then my output style file has duplicated code with some diff.

![image](https://user-images.githubusercontent.com/1647303/39713864-effb02be-5230-11e8-9a39-3b0a4994b912.png)

output:

![image](https://user-images.githubusercontent.com/1647303/39713906-0bc71370-5231-11e8-9931-9aed6ca470d0.png)

Maybe someone knows how to fix this?

Thanks!

**Comment by benpickles** [comment]
I imagine that's autoprefixer providing a fallback for browsers that do not support rem.

**Comment by paulgeisler** [comment]
Check the options of the first postcss-plugin.
The default option for postcss-pxtorem is `replace: true,` that's becuase it does not replicate the code line but replaces it.

**Comment by gauravtiwari** [comment]
Please use the latest RC, and feel free to open a new issue with more details if this is still an issue.
