### ISSUE TITLE
Passing Environment Variables

### ISSUE THREAD

**Issue by Rheisen** [rails/webpacker#1486]
I'm using Heroku for a rails webpacker react app and I'm trying to set environment variables on Heroku and pass them through into the react app. Currently I don't see a way to do this, but it is useful for specific settings for production vs. staging.

EDIT:

I should have read the documentation more thoroughly, but here is how to do this.
[webpacker rails env documentation](https://github.com/rails/webpacker/blob/master/docs/env.md)

Essentially by using foreman everything in a .env file located in the same directory as your Procfile will automatically load and be provided to the processes being run by foreman. With webpacker they can be accessed with `process.env.ENV_VAR_NAME`.

**Comment by BassamAziz** [comment]
Hello, awesome, running through the same thing. but still unsure where to put the .env locally, and how to configure this on heroku. help is a lot appreciated. thanks

**Comment by gauravtiwari** [comment]
Please see env docs and consider using the latest RC.

**Comment by chrissyast** [comment]
@Rheisen I have a similar but related issue. I followed the instructions in the link, and if I do `console.log(process.env.MY_ENV)` within environment.js then the variables are there, but they are not available to me within my React components.

**Comment by jakeNiemiec** [comment]
@chrissyast The browser does not have access to the server's ENV variables (gotta protect those secret keys 🙃).

You can achieve your goal by using the [webpack define plugin](https://webpack.js.org/plugins/define-plugin/). I hope this is enough to point you in the right direction.

**Comment by chrissyast** [comment]
@jakeNiemiec  I used [dotenv-webpack](https://github.com/mrsteele/dotenv-webpack#description) which includes webpack define. But still they are not available to me in the component :(

**Comment by chrissyast** [comment]
In the end I didn't need either of those, I just needed 
```js
const dotenv = require('dotenv')
dotenv.config()
```

in my config/webpack/development.js🤦🏻‍♂️
