### ISSUE TITLE
[Webpacker] Compiling 3-4x times per request

### ISSUE THREAD

**Issue by george-norris-salesforce** [rails/webpacker#1490]
Hello,
Having an issue where every request in Rails, Webpacker is compiling three to four times, which is making development very slow.
Getting messages like so:
```
[Webpacker] Compiling…
[8baa7db9-ee64-4266-9951-6bb5a10d7170] [Webpacker] Compiled all packs in /path/to/file
[8baa7db9-ee64-4266-9951-6bb5a10d7170] [Webpacker] Compiling…
[8baa7db9-ee64-4266-9951-6bb5a10d7170] [Webpacker] Compiled all packs in /path/to/file
[8baa7db9-ee64-4266-9951-6bb5a10d7170] [Webpacker] Compiling…
```

**Comment by rossta** [comment]
@george-norris-salesforce For others to debug this issue, it would be helpful to post more info, e.g. your versions of the Webpacker gem, `@rails/webpacker`, Rails, etc., any configuration changes, what's in your packs directory. Help others reproduce.

**Comment by nice00xt** [comment]
Same here, I have webpacker 3.4 with rails 5 and docker, I'm having the same issue, the more complex is my app more time take to compile the assets, up to 5 mins!, I tried to run the webpack-dev-server but I get Cannot GET / message

**Comment by george-norris-salesforce** [comment]
webpacker (3.1.1)
We've renamed the folder. Other than that, no config changes

**Comment by nice00xt** [comment]
@george-norris-salesforce sorry what is the folder?

**Comment by mikeappell** [comment]
@george-norris-salesforce is it possible you're including either `mini-css-extract-plugin` or `extract-text-webpack-plugin` more than once? I believe for me, extract-text being ran several times was what was causing multiple compilation steps for me.

However, once I migrated to Webpacker 4.x and started using `mini-css-extract-plugin` instead I went back to only one compilation step.

**Comment by AndrewRayCode** [comment]
I'm seeing webpacker compile on every request, even refreshing the same page.

**Comment by gauravtiwari** [comment]
Please use the latest RC, and feel free to open a new issue with more details if this is still an issue.

**Comment by IgorKhlebnikov** [comment]
Each `image_pack_tag` doing new compilation (development). Can someone to explain why? Or how to fix
