### ISSUE TITLE
Discussion: Add an option to load (and cache) public_output_path content from a remote source without redeployment

### ISSUE THREAD

**Issue by joeyparis** [rails/webpacker#1491]
I would like to propose the idea of adding the ability to have the contents of `public_output_path` updated and subsequently cached from a remote source (e.g. an S3 bucket). 

The purpose being you could update your compiled webpack output in production without having to redeploy the entire Rails application. This would also allow a different method for users to opt-out of compiling code during deployment and instead compiling locally then uploading to the remote host (of course precompiling before deployment is always an option).

I would imagine it could leverage similar methods to how `dev_server` currently works, although without live reloading, file watching, and compiling.

**General Development Flow**
1. Make changes to local `source_path`
2. Compile using `webpacker:compile` (maybe with an option indicating this is being created with the explicity purpose of being uploaded to the remote production source)
3. Place compiled data in the target `remote_path` (Manually, unless you want to add the ability for support of services like S3)

**General Load Flow**
1. Check if data exists in `public_output_path`
    * If yes, render that data but continue next steps in different thread
2. Check if newer data exists in `remote_path` (maybe using manifest.json?)
    * If yes, download the new data and put it in the `public_output_path`

Perhaps the `public_output_path` file has two subfolders one for the originally compiled packs from deployment, and then a separate folder from the `remote_path` as a fallback of sorts.

**Potential Issues**
* This setup does run the risk of production code becoming out of sync with what is expected based on actual version history making tasks like rollbacks more difficult to perform reliably.
* Required packages could change but would not be reflected in the new output resulting in missing packages.
* Probably a few that I didn't even consider

What are everyone's thoughts on an implementation like this? I know it would make my life easier in a few scenarios, especially with how long my deployment times are on Elastic Beanstalk. Do other's see the value in this option or is the use case to limited to be worth the development time?

**Comment by justin808** [comment]
This is beyond the scope of rails/webpacker. FWIW, bundle caching is a feature of [React on Rails Pro](https://www.shakacode.com/react-on-rails-pro/).
