### ISSUE TITLE
Babel 7 support

### ISSUE THREAD

**Issue by kennym** [rails/webpacker#1495]
Are there any plans for babel 7 support in the planning?

**Comment by renchap** [comment]
I guess what it is out of beta :)

I have been using Babel 7 for about 6 months with Webpacker. You just need to add the proper packages to your `package.json` and it should work.

For example, in mine:

```
{
  "dependencies": {
    "@babel/cli": "7.0.0-beta.46",
    "@babel/core": "7.0.0-beta.46",
    "@babel/plugin-proposal-class-properties": "7.0.0-beta.46",
    "@babel/plugin-proposal-object-rest-spread": "7.0.0-beta.46",
    "@babel/plugin-syntax-dynamic-import": "7.0.0-beta.46",
    "@babel/polyfill": "7.0.0-beta.46",
    "@babel/preset-env": "7.0.0-beta.46",
    "@babel/preset-react": "7.0.0-beta.46",
    "babel-loader": "^8.0.0-beta.0",
    ...
  }
}
```

You might also need to convert your `.babelrc` to the new `.babelrc.js`, but it is quite straightforward

**Comment by bjankord** [comment]
@gauravtiwari Cool! By final release do you mean webpacker v4.0.0 stable release?

**Comment by gauravtiwari** [comment]
@bjankord Yep!

**Comment by gauravtiwari** [comment]
Made a pre-release (with babel 7 support):

```
yarn add @rails/webpacker@next
bundle update webpacker
```
