### ISSUE TITLE
webpack binstubs not found Deploy capistrano Rails 5.1.4

### ISSUE THREAD

**Issue by gilcierweb** [rails/webpacker#1497]
yarn install v1.6.0
[1/4] Resolving packages...
⠁ 

success Already up-to-date.
Done in 1.64s.
      01 webpack binstubs not found.
      01 Have you run rails webpacker:install ?
      01 Make sure the bin directory or binstubs are not included in .gitignore
      01 Exiting!
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as deployer@xxxxxxxx: rake exit status: 1
yarn install v1.6.0
[1/4] Resolving packages...
success Already up-to-date.
Done in 1.64s.
webpack binstubs not found.
Have you run rails webpacker:install ?
Make sure the bin directory or binstubs are not included in .gitignore
Exiting!
rake stderr: Nothing written

**Comment by ytbryan** [comment]
so, have you make sure that the webpack binstubs are present in the production environment?

**Comment by yongwoon** [comment]
maybe, in config/deploy.rb bin folder included in  set :linked_dirs.
exclude bin folder in linked_dirs list
