### ISSUE TITLE
How to disable fingerprinting?

### ISSUE THREAD

**Issue by dipeshba** [rails/webpacker#1504]
webpacker is appending hashes to all the assets by default. Is there a way to disable this?

**Comment by rossta** [comment]
@dipeshba You'd have to edit the defaults for the output config and for the CSS extract plugin, though, I wouldn't recommend doing that... don't you want to improve the caching behavior of your assets?

Current hashing configuration:
https://github.com/rails/webpacker/blob/e0c32fa9af8b7f36f2034f7907d6077f423b750f/package/environments/base.js#L80
https://github.com/rails/webpacker/blob/e0c32fa9af8b7f36f2034f7907d6077f423b750f/package/environments/base.js#L34

Docs for customizing configuration: https://github.com/rails/webpacker/blob/master/docs/webpack.md

**Comment by gauravtiwari** [comment]
Duplicate #1310
