### ISSUE TITLE
several questions on yarn integrity check

### ISSUE THREAD

**Issue by dreyks** [rails/webpacker#1506]
1. it seems that yarn integrity check only runs for rails app and not when i run `bin/webpack` or `bin/webpack-dev-server`. Dou you think that would be beneficial?

2. In most cases my lockfile is ok but the actual package is missing i.e. i pulled new commits and didn't run `yarn install`. `yarn check --integrity` won't catch it though. On the other hand running a full `yarn check` on each rails command might be a performance hit. what do you think?

**Comment by rossta** [comment]
The yarn integrity check has been removed from Webpacker. See the PR for more details https://github.com/rails/webpacker/pull/2518
