### ISSUE TITLE
Readme error

### ISSUE THREAD

**Issue by agnewtj** [rails/webpacker#1509]
The React integration doc contains the following error:
`
(or run bundle exec rails webpacker:install:react in a existing Rails app already setup with Webpacker).`

The correct command is
`
bundle exec rails webpacker:install:react`

**Comment by gauravtiwari** [comment]
@agnewtj Both are same :)

**Comment by agnewtj** [comment]
Meant to write ‘rake’ !

**Comment by gauravtiwari** [comment]
Ahh yes, that's for `rails < 5.0`
