### ISSUE TITLE
`Webpacker::Digests.lookup` issue

### ISSUE THREAD

**Issue by towry** [rails/webpacker#151]
The content of `digests.json` file that my project generated in production environment is:

```json
{"conversation":["conversation-4ab9768dd0430c0910c6.js","conversation-4ab9768dd0430c0910c6.js.map"],"hello_react":"hello_react-4ab9768dd0430c0910c6.js","packs-bundle":"packs-bundle-4ab9768dd0430c0910c6.js"}
```
So the [lookup](https://github.com/rails/webpacker/blob/master/lib/webpacker/digests.rb#L29) method will return an array string instead of the correct digested filename if I want to use `conversation` script.

**Comment by yiliangt5** [comment]
I will take this

**Comment by gauravtiwari** [comment]
@towry You are passing sourcemap option in production right? 

```js
devtool: 'sourcemap',
new webpack.optimize.UglifyJsPlugin({
      sourceMap: true,
 }),
```

After #153 this should be find as it flattens the manifest.

**Comment by gauravtiwari** [comment]
@towry We can close this one. #153 is merged
