### ISSUE TITLE
How to use image_pack_tag with uncompiled images?

### ISSUE THREAD

**Issue by vill** [rails/webpacker#1521]
Hi there.

For previewing images I would like to use this code:
```slim
= image_pack_tag (f.object.image_url.blank? ? 'images/placeholder.jpg' : f.object.image_url)
```

But for saved images, an error occurs:

```
Webpacker can't find /uploads/cache/cf7275cc2133e682a42f57d953516295.png
```

I think it's necessary to add a condition to [image_pack_tag](https://github.com/rails/webpacker/blob/cd6770d4c5afe8b756363937de689e348331a545/lib/webpacker/helper.rb#L43) when it needs to look for paths in the manifest file and when not to do it (if the path starts with a slash `/`).

For example, how the `image_tag` method builds paths:

```ruby
image_tag("icon.png")
# => <img alt="Icon" src="/assets/icon.png" />

image_tag("/icons/icon.gif")
# => <img alt="Icon" src="/icons/icon.gif" />
```

**Comment by tenshiAMD** [comment]
@vill, Try these codes below to add uncompiled assets in webpack:

```
const CopyWebpackPlugin = require('copy-webpack-plugin');
environment.plugins.prepend(
    'Copy',
    new CopyWebpackPlugin([
        { from: 'images/placeholder.jpg', to: 'images'}
    ])
);
```

**Comment by tenshiAMD** [comment]
@vill, Try these codes below to add uncompiled assets in webpack:

#### config/webpack/environment.js

```
const CopyWebpackPlugin = require('copy-webpack-plugin');
environment.plugins.prepend(
    'Copy',
    new CopyWebpackPlugin([
        { from: 'images/placeholder.jpg', to: 'images'}
    ])
);
```

**Comment by guillaumebriday** [comment]
I think you should wrap your condition around your tags like so:

```ruby
- if f.object.image_url.blank?
  = image_pack_tag('images/placeholder.jpg')
- else
  = image_tag(f.object.image_url)
```

Hope this help 👍 

Feel free to close this issue if it's ok for you @vill
