### ISSUE TITLE
Webpacker::Manifest::MissingEntryError in Orders#new

### ISSUE THREAD

**Issue by indahwii** [rails/webpacker#1523]
Webpacker can't find pay_type.js in /home/studio/indah/depot/public/packs/manifest.json. Possible causes:
1. You want to set webpacker.yml value of compile to true for your environment
   unless you are using the `webpack -w` or the webpack-dev-server.
2. webpack has not yet re-run to reflect updates.
3. You have misconfigured Webpacker's config/webpacker.yml file.
4. Your webpack configuration is not creating a manifest.
Your manifest contains:
{
  "application.js": "/packs/application-daf00e23d1e09f8b59b4.js",
  "application.js.map": "/packs/application-daf00e23d1e09f8b59b4.js.map",
  "hello_react.js": "/packs/hello_react-915178db5f552571d1a3.js",
  "hello_react.js.map": "/packs/hello_react-915178db5f552571d1a3.js.map"
}

**Comment by boatrite** [comment]
I got this error after adding webpacker to Rails 5.2 project and running `rails webpacker:install` and `rails webpacker:install:vue`. None of the commands generated a package.json file (and subsequently did not download packages, so I had no node_modules directory).

I ended up running `rails new myapp --webpack=vue` in /tmp, so I could copy out package.json (which was generated).

After copying out the package.json, I ran `bin/yarn install` to download the packages and then everything worked.

Just in case someone runs into something similar.

**Comment by indahwii** [comment]
oke thanks!

**Comment by feliperaul** [comment]
I followed the readme exactly, as did @boatrite, and I also didn't have package.json generated, which caused the `Webpacker::Manifest::MissingEntryError`. Took me a while to figure this one out since the error message is `Webpacker can't find application.js in /Users/user/dev/project/public/packs/manifest.json`, which is misleading, since the file application.js exists in the correct folder (it was generated after webpacker:install).

**Comment by rahymov** [comment]
bin/yarn install worked for me

**Comment by valentidiamond** [comment]
rails webpacker:install:vue woked for me. Thanks

**Comment by birthdaycorp** [comment]
rails webpacker:install worked for me!

**Comment by macyjeanma** [comment]
yarn install worked for me as well

**Comment by gogaz** [comment]
`bundle exec rails webpacker:install:react` fixed the issue in my case

**Comment by Ahmad-Buglen** [comment]
fix misprint
