### ISSUE TITLE
Chrome Dev Console sockjs-node/info (failed)

### ISSUE THREAD

**Issue by resistorsoftware** [rails/webpacker#1527]
Project is Rails 5.2 + Webpack=React. Gem version 3.5.3. Web App compiles and loads packs inline with no problems in console (albeit it is very slow for a teeny App).
I try Foreman with a Procfile.dev containing the line:

    webpacker: ./bin/webpack-dev-server

So now things compile, Rails logs are clean, but the Chrome Dev console fills with XHR errors. 

    sockjs.js:1601 GET https://tllttllt.dev:3035/sockjs-node/info?t=1527345346654 0 ()

Is this a problem? What is the secret sauce to getting a clean console on these XHR calls? My webpacker.yml file is pretty much stock although I changed localhost to 0.0.0.0. I also set https to true.

    dev_server:
      https: true
      host: 0.0.0.0
      port: 3035
      public: 0.0.0.0:3035
      hmr: true
      # Inline should be set to true if using HMR
      inline: true
      overlay: true
      compress: true
      disable_host_check: true
      use_local_ip: false
      quiet: false
      headers:
        'Access-Control-Allow-Origin': '*'
      watch_options:
        ignored: /node_modules/

**Comment by gauravtiwari** [comment]
Please try the latest RC, otherwise feel free to open a new issue with more details.
