### ISSUE TITLE
Webpacker 4 hangs using Travis CI

### ISSUE THREAD

**Issue by jlpereira** [rails/webpacker#1532]
Hi guys!

We are experiencing a problem with the compilation of the assets in our project when we use Travis CI.
Our project: https://github.com/SpeciesFileGroup/taxonworks

Gem 'webpacker', '>= 4.0.x'
"@rails/webpacker": "4.0.0-pre.2",

Locally it works without any problems, but we can not find the reason why it hangs
This is what we are reaching:

```
Webpacker is installed 🎉 🍰
Using /home/travis/build/SpeciesFileGroup/taxonworks/config/webpacker.yml file for setting up webpack paths
Compiling ...

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

We have already tried to eliminate all entries applications from application.js to check if it was a problem of delay in the compilation, but it is still hanging

Any idea?

Thanks!

**Comment by jlpereira** [comment]
Solved, the problem was the plugin increase-memory-limit. I remove it and now works perfect.

Thanks anyway!

**Comment by gauravtiwari** [comment]
Great 👍
