### ISSUE TITLE
Compiling never completes Rails 5.2, ERB and compile: true

### ISSUE THREAD

**Issue by raldred** [rails/webpacker#1534]
webpacker: 3.5.3
rails: 5.2
ruby: 2.5.0

This is on an out the box 5.2 rails install. Added webpacker, webpacker:react & webpacker:erb
All fine apart from ERB, it hangs during requests and just sits on `[Webpacker] Compiling…`

**Comment by jakeNiemiec** [comment]
[Do you use Font Awesome?](https://fontawesome.com/how-to-use/with-the-api/other/tree-shaking#issues)

**Comment by raldred** [comment]
Just to be clear I'm seeing this in development with webpack dev server, production is fine.

**Comment by guillaumebriday** [comment]
Is this issue still relevant ?

Feel free to close it if not 👍

**Comment by raldred** [comment]
@guillaumebriday the issue was that erb errors were not bubbled up so the compile process just hung.
Does anyone know if this has been resolved upstream of 3.5.3?
It's not something I've come across recently.

**Comment by MichaelArriaga** [comment]
Any solution to this that's not related to erb-loader? I'm experiencing the compiling.... issue but do not use erb-loader. I am using Docker on Windows.
