### ISSUE TITLE
Support for rails 4.1?

### ISSUE THREAD

**Issue by sandeepravi** [rails/webpacker#1536]
I see that the prerequisite for webpacker is Rails 4.2? But I was just curious whether I can get it working with 4.1 as well? 

Are there any specific 4.2 related dependencies?

**Comment by wittawasw** [comment]
All the tests passed on Rails 4.1 and I'm able to run it on Rails 4.1.x projects.

**Comment by sandeepravi** [comment]
yeah it did work, just had to fix the dependencies.
