### ISSUE TITLE
Should Webpacker "support" hot module reloading?

### ISSUE THREAD

**Issue by justin808** [rails/webpacker#154]
For a long discussion on this topic, see: [Hot Module Reloading #332](https://github.com/shakacode/react_on_rails/issues/332).

Maybe this HMR will be stable eventually.

We support this feature for [React on Rails](https://github.com/shakacode/react_on_rails) via examples, but not as a core part of the gem. By this, I mean that we do not add the extra complexity of HMR. In retrospect, this was a great decision.

**Comment by gauravtiwari** [comment]
@justin808 I don't think webpacker provides this out-of-the-box? It does provide webpack-dev-server support, but not with `--hot` option. Perhaps, something to clear out in the readme.

**Comment by ytbryan** [comment]
Am I missing something here? 

Because this should be already supported because of webpack-dev-server? 

Must it be explicitly supported for React? For Vue, it comes out of the box whenever i switch on webpack-dev-server.

**Comment by justin808** [comment]
We can close this. Webpack dev server is hot reloading.
