### ISSUE TITLE
I have a issue with the process of compiling packages in docker

### ISSUE THREAD

**Issue by nice00xt** [rails/webpacker#1540]
I decided to start the my app with docker but i have an issue 
always that I'm adding changes on my files the app start compiling all the packages and this take a lot of time, 
 I tried to start my app with `./bin/webpack-dev-server`, and docker in another tab,  but I get a `Cannot GET /` message in the view from `http://localhost:3035`

I'm using webpacker 3.4
this is my webpacker config

```
# Note: You must restart bin/webpack-dev-server for changes to take effect

default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_output_path: packs
  cache_path: tmp/cache/webpacker

  # Additional paths webpack should lookup modules
  # ['app/assets', 'engine/foo/app/assets']
  resolved_paths: []

  # Reload manifest.json on all requests so we reload latest compiled packs
  cache_manifest: false

  extensions:
    - .jsx
    - .js
    - .sass
    - .scss
    - .css
    - .module.sass
    - .module.scss
    - .module.css
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg

development:
  <<: *default
  compile: true

  # Reference: https://webpack.js.org/configuration/dev-server/
  dev_server:
    https: false
    host: localhost
    port: 3035
    public: 0.0.0.0:3035
    hmr: false
    # Inline should be set to true if using HMR
    inline: true
    overlay: true
    compress: true
    disable_host_check: true
    use_local_ip: false
    quiet: false
    headers:
      'Access-Control-Allow-Origin': '*'
    watch_options:
      ignored: /node_modules/


test:
  <<: *default
  compile: true

  # Compile test packs to a separate directory
  public_output_path: packs-test

production:
  <<: *default

  # Production depends on precompilation of packs prior to booting for performance.
  compile: false

  # Cache manifest.json for performance
  cache_manifest: true

```

**Comment by madwire** [comment]
@nice00xt if your running it from inside a container you might need to bind to 0.0.0.0 for the port forwarding to work, so try running ```WEBPACKER_DEV_SERVER_HOST=0.0.0.0 ./bin/webpack-dev-server```

_I'm assuming your using docker-compose and your mapping to port 3035_

**Comment by nice00xt** [comment]
@matthewd I did I'm running `WEBPACKER_DEV_SERVER_HOST=0.0.0.0 ./bin/webpack-dev-server` in a separate tab from and still have the same result i got
```
10% building modules 1/1 modules 0 active
Project is running at http://0.0.0.0:3035/
webpack output is served from /packs/
Content not from webpack is served from /Users/juanmejia/projects/linc/public/packs
404s will fallback to /index.html
Hash: 5513c4644945c22b69ca
Version: webpack 3.11.0
Time: 6400ms
```
and is still compiling for the docker server side after any change inside of `/javascritpt/src` source 
I guess i have to configure the dockerfile for this

**Comment by gauravtiwari** [comment]
@nice00xt You don't need to worry about the output from `http://0.0.0.0:3035/` see if the packs are loaded fine through Rails server i.e. `localhost:3000` or whatever the rails server address is.

**Comment by nice00xt** [comment]
@gauravtiwari Is doing well the problem is when I finish a change the logs show a `webpacker compiling`message and took at least 20 to 40 seconds while is compiling all the assets, now I did the [docker configuracion](https://github.com/rails/webpacker/blob/master/docs/docker.md) and now runing webpacker inside the container and is the same issue

**Comment by gauravtiwari** [comment]
You could turn off on-demand compilation from webpacker.yml in development environment. `compile: false`

**Comment by nice00xt** [comment]
@gauravtiwari I runing docker with webpacker and with the option `compile: false` I get this 

`ActionController::RoutingError (No route matches [GET] "/packs/application-6bea9f300ce703be1832.js")`

but with the config `compile: true` after a small change then the app start compiling, but I can't see changes until reload the browser and then docker start compiling after, that part take a long time
<img width="597" alt="screen shot 2018-06-18 at 5 57 13 pm" src="https://user-images.githubusercontent.com/2046454/41566588-cc355cd2-7321-11e8-9f44-325c9c82482b.png">

**Comment by gauravtiwari** [comment]
@nice00xt Ahh I thought you are already running the dev server. Thanks @madwire 

Please take a look at the template
