### ISSUE TITLE
Generate JS and CSS files without hash in test environment

### ISSUE THREAD

**Issue by yizeng** [rails/webpacker#1541]
Asked this before and here is the solution with webpacker 3.0.2

```
// test.js
process.env.NODE_ENV = process.env.NODE_ENV || 'development'

const environment = require('./environment')
environment.config.set('output.filename', '[name].js')

const extractText = environment.plugins.get('ExtractText');
extractText.filename = '[name].css';

module.exports = environment.toWebpackConfig()
```

However, I recently upgraded to webpacker 3.5.3. Hashes get generated again in test environment.

Any ideas? Could this be related to `Settings in config/webpack/test.js stopped working after of upgrade from 3.2 to 3.5` #1502? Would webpacker 4 be different again?

**Comment by guillaumebriday** [comment]
Is this issue still relevant? Feel free to reopen if needed
