### ISSUE TITLE
Adding new entry file in packs?

### ISSUE THREAD

**Issue by amanjaggaPracto** [rails/webpacker#1550]
I want to add another entry(view) file for a new controller that I have created.
I added a file and linked with a rails view using javascript_pack_tag but I am getting this error

1. You want to set webpacker.yml value of compile to true for your environment
   unless you are using the `webpack -w` or the webpack-dev-server.
2. webpack has not yet re-run to reflect updates.
3. You have misconfigured Webpacker's config/webpacker.yml file.
4. Your webpack configuration is not creating a manifest.
Your manifest contains:
`{
  "application.css": "/packs/application-b037e7ed7f36b52ce70819b2beba7e60.css",
  "application.css.map": "/packs/application-b037e7ed7f36b52ce70819b2beba7e60.css.map",
  "application.js": "/packs/application-7ca5d620194ef078f715.js",
  "application.js.map": "/packs/application-7ca5d620194ef078f715.js.map",
  "CamphorPro-Heavy.ttf": "/packs/CamphorPro-Heavy-4cb7266df7f991ead5958c89e973033f.ttf",
  "CamphorPro-Regular.ttf": "/packs/CamphorPro-Regular-5bcaa4d6a378e36e4881697aca203921.ttf",
  "trrr.ttf": "/packs/trrr-8d70d86e2936f9fcdb00602f6742d4fc.ttf",
  "_/assets/images/ic_search_system.svg": "/packs/_/assets/images/ic_search_system-8049a4a9a422b8968430f5ed754af214.svg",
  "_/assets/images/service_dashboard/ico_search.svg": "/packs/_/assets/images/service_dashboard/ico_search-8049a4a9a422b8968430f5ed754af214.svg",
  "_/assets/images/service_dashboard/ico_arrow.svg": "/packs/_/assets/images/service_dashboard/ico_arrow-46786c5a32a9f1c1a50c72e12385aa44.svg",
  "_/assets/images/service_dashboard/ico_user.svg": "/packs/_/assets/images/service_dashboard/ico_user-e1154afa5a542cde71c3b7ab8d2d4db0.svg",
  "_/assets/images/service_dashboard/ico_dropdown.svg": "/packs/_/assets/images/service_dashboard/ico_dropdown-4fba3f2d3babb573c8c610f8abe6cbb5.svg",
  "_/assets/images/service_dashboard/ico_pipe.svg": "/packs/_/assets/images/service_dashboard/ico_pipe-7917abd6b195432d5550196d56ab1b21.svg"
}
`

How do I add this entry to manifest file?

**Comment by gauravtiwari** [comment]
Have you restarted the webpack watcher/server?

**Comment by amanjaggaPracto** [comment]
Had restarted the server but forgot to restart the watcher. Thanks for the quick resolution
