### ISSUE TITLE
Cache watched_files_digest

### ISSUE THREAD

**Issue by swrobel** [rails/webpacker#1552]
It seems an optimization could be made by caching the output of [watched_files_digest](https://github.com/rails/webpacker/blob/v4.0.0.pre.pre.2/lib/webpacker/compiler.rb#L45) because it seems to run a number of times on the same set of files during a test run, which seems unnecessary. However, I know that a `Webpacker.instance` exists globally for a running Rails app, so I'm not exactly sure how to approach this so that it's only cached for the duration of a single test run/request.

**Comment by guillaumebriday** [comment]
Is this issue still relevant? Feel free to reopen if needed
