### ISSUE TITLE
question: something like the react-rails 'react_component' method?

### ISSUE THREAD

**Issue by lauherkcambria** [rails/webpacker#156]
Hey there, it's my first time asking a question so I apologize if this isn't the best place to ask! Is there a way to incorporate the react-rails 'react_component' or something similar with the webpacker gem? I was thinking it would be useful to be able to pass values from controller to my react component with something like this in my view:

`<%#= javascript_pack_tag 'MyComponent',  @passed_controller_json_value%>`

similar to how  Id' do it with the react-rails gem:

`<%= react_component('MyComponent',   @passed_controller_json_value) %>`

More importantly, however, if asking this question demonstrates that I am instead missing a fundamental concept of this implementation, please let me know as I'm very excited to try (at least!) to understand how webpacker, react, and rails work together. 

Any guidance would be much appreciated! Thanks!

**Comment by renchap** [comment]
React integration is not in the scoep of the Webpacker project, but some external gems exists, like this one: https://github.com/renchap/webpacker-react
It provides the method you are looking for, as well as other React-related features.

**Comment by User420420420420** [comment]
Thanks for the help @renchap! I'm mainly looking to understand how this all works, taking a look at your project will  definitely help. :)

**Comment by gauravtiwari** [comment]
@lauherkcambria feel free to close the issue if you are satisfied :) Providing something like - react_component helper is out of scope. Like @renchap suggested you can either use his gem or create a helper yourself that provides this feature. There are also some more gems that provides this helper, but not sure if they are compatible with webpacker at this point. 

To understand how webpacker works, perhaps checkout this post - https://medium.com/statuscode/introducing-webpacker-7136d66cddfb#.pshdjvxh0

**Comment by lauherkcambria** [comment]
thanks @gauravtiwari btw i read your medium blog post very nice :) 👍
