### ISSUE TITLE
Run file-loader before erb-loader

### ISSUE THREAD

**Issue by luislezcair** [rails/webpacker#1560]
Hello.

I'm facing an error with erb-loader. When making a call to `asset_pack_path` inside a .js.erb file it produces an error if it cannot find the asset (i.e. it wasn't compiled yet by file-loader). I followed the [docs](https://github.com/rails/webpacker/blob/master/docs/webpack.md) to make erb-loader run _after_ file-loader but it seems it's not working.

I uploaded a [repo](https://github.com/luislezcair/erb-loader-test) to demonstrate the issue. [This](https://github.com/luislezcair/erb-loader-test/blob/master/config/webpack/environment.js) is where I change the order of loaders. I even put `enforce: true` in the file-loader to make it run before anything else, but it seems it is not producing the output files in time.

If I run `./bin/webpack` a _second_ time, the assets are already in the `public/packs` directory and erb-loader runs fine (a  call to `asset_pack_path` produces the desired output).

I made a longer explanation in an issue [here](https://github.com/usabilityhub/rails-erb-loader/issues/63#issuecomment-395276526)

I'm using Webpack 4.10.2 with Webpacker 4.0.0.pre.pre.2 and Rails 5.2.

**Comment by renatodeleao** [comment]
@luislezcair i'm facing the same issue. Realised that the repo doesn't exist anymore. Did you manage to solve this?

Thanks in advance.

**Comment by luislezcair** [comment]
Nope, I just ended using more specific loaders and ditched away erb. I think it was not intended to be used this way.

**Comment by guillaumebriday** [comment]
Is this issue still relevant? Feel free to reopen if needed
