### ISSUE TITLE
Disable optimization / uglify

### ISSUE THREAD

**Issue by itay-grudev** [rails/webpacker#1566]
I want to disable optimization / uglify to be able to debug a problem. Anything using the webpack configuration didn't work. Any advice?

**Comment by itay-grudev** [comment]
That's what I was looking for. Thanks.

**Comment by kangkyu** [comment]
I needed ``` config.optimization.minimize = false ``` too

**Comment by efatsi** [comment]
I am unable to skip minification, and unfortunately the above solutions don't seem applicable anymore.

I get the following error when trying to delete the minimizer config:
```
delete(config.optimization.minimizer)
              ^

TypeError: Cannot convert undefined or null to object
```

On inspection, it doesn't appear `optimization` is an available key on the config. So I attempted to add the config to the base environment.js file like so:
```js
const { environment } = require('@rails/webpacker')

environment.optimization = {
  minimize: false
}

module.exports = environment
```
But nothing has stopped minification from happening. Any further ideas?

**Comment by hopewise** [comment]
in which file to apply those configuration? isn't it `babel.config.js` ?
can you please help me here:

https://stackoverflow.com/questions/70878283/how-to-configure-performance-settings

**Comment by hopewise** [comment]
It did not work for me, what could be wrong? here is how my `config/webpack/production.js` looks like:

```
process.env.NODE_ENV = process.env.NODE_ENV || 'production'
const environment = require('./environment')
const config = environment.toWebpackConfig();
delete(config.optimization.minimizer);
config.optimization.minimize = false;
module.exports = config;
```
