### ISSUE TITLE
Should webpacker delay ERB compilation to request-time?

### ISSUE THREAD

**Issue by lbrito1** [rails/webpacker#1569]
**Edit:** I've rephrased the title and a few paragraphs here to better reflect my understanding of this problem

I'm experimenting with webpacker and Vue single-file components on a large legacy Rails app.

I'm faced many times with this situation: a Vue instance's template depends on controller instance variables. For example:

**foo_controller.rb**
```ruby
def index
  @foobar = 'Foo bar'
end
```

**foo.html.erb**
```html
<div id="vue-root">
  <%= @foobar %>
</div>
```

**foo.js**
```js
$(window).load(function() {
  new Vue({el: vueRoot})
});
```

Moving forward to Vue SFCs, I'm not sure what the correct way to deal with that `@foobar` in the template is, as at compilation time it won't exist, of course. Sure, we can use [props](https://github.com/rails/webpacker/blob/master/docs/props.md) when the objective is just displaying `@foobar`.

But what about when we have something more complex, like: `<%= @foobar.my_method %>`? That seems like a common enough scenario in many Rails projects. 

I can also think of several helpers/gems that depend on an actual object (as opposed to a serialized representation of it) - think pagination gems, Paperclip, ActiveSupport helpers, etc. All of them need ERB compiled in request-time so they can use the objects defined in the controller action. 

I'm relatively new to the frontend world, so don't mind if I ask: are we expected to choose between that ecosystem (of helpers and such) and equivalent js packages?

**Comment by luislezcair** [comment]
I think you have a misunderstanding. In your example code `@foobar` is resolved in the _server_ and when the javascript gets executed in the _client_ `@foobar` will be already resolved and loaded in the page. There shouldn't be any problem there.

**Comment by lbrito1** [comment]
@luislezcair I think you've missed the point of the issue. Yes, `@foobar` is resolved in the server. But because Webpacker compiles eagerly (in development, after saving the js file; in production, prior to deploy), the erb file containing `@foobar` will have been compiled already _before the request_.

This is fine for stuff that is known at compilation time: constants, some helpers etc. But not for stuff that depends on what the client sends in the request.

This might be a little subtle to notice at first, so I've created a demo: https://github.com/lbrito1/rails-test-erb . Take a look at https://github.com/lbrito1/rails-test-erb/blob/master/app/javascript/erb_test.vue.erb :

```erb
<template>
  <div>
    <h1>ERB compiled by Webpacker</h1>
    <p><%= @from_request %></p>
    <p><%= ErbTest.not_from_request %></p>
  </div>
</template>
```

`not_from_request` is available during compilation (it just returns the string: `"Got this from the server, but *not* from the request."`), but `@from_request` is not (it returns a string with something in the request params). If you search in the js that webpacker compiles for that file, it'll be this:

```js
var staticRenderFns = [
  function() {
    var _vm = this
    var _h = _vm.$createElement
    var _c = _vm._self._c || _h
    return _c("div", [
      _c("h1", [_vm._v("ERB compiled by Webpacker")]),
      _vm._v(" "),
      _c("p"),
      _vm._v(" "),
      _c("p", [_vm._v("Got this from the server, but *not* from the request.")])
    ])
  }
]```

Notice that the first `p` element, which should have `@from_request`, is being rendered empty.
