### ISSUE TITLE
Adding a file to app/javascript/packs doesn't get picked up by webpack-dev-server

### ISSUE THREAD

**Issue by superplussed** [rails/webpacker#1574]
I've been searching around and I don't see any mention of this problem, but if I edit or delete file in the packs folder the manifest updates, but not if I add one.  I'm running the webserver with this command:

    ./bin/webpack-dev-server --watch

**Comment by renchap** [comment]
This is a Webpack limitation, it reads the config at startup, and the packfiles list is build when the configuration is generated.

**Comment by superplussed** [comment]
Hmm, I'm trying to port a project that I have from a gem called gulp_assets which runs gulp on the site and then has some tie-in to the asset pipeline in a way that I don't understand.  But when I start up my project, the yarn start command compiles 1600 .js file to get my development build going.  It's hard to imagine doing this each time I add a file, but maybe a front-end like this is too big to be in a rails repo at all.

**Comment by renchap** [comment]
I think you are not using the packfiles correctly. A packfile is an entrypoint from which you can import other files. Webpack will generate 1 output file per entrypoint, intelligently bundling all the imported files recursively (and optionally creating other files to group imports that appear in multiple entrypoints.

You definitely should not have 1600 files in your `packs` directory.

**Comment by superplussed** [comment]
Ahh, ok, I hadn't tested adding files outside the packs folder.  It works fine to add them there.  Ty :)
