### ISSUE TITLE
Questions about stylesheet_pack_tag

### ISSUE THREAD

**Issue by ryanscottaudio** [rails/webpacker#1575]
The documentation reads:

> You can then link the JavaScript pack in Rails views using the javascript_pack_tag helper. If you have styles imported in your pack file, you can link them by using stylesheet_pack_tag:
> 
> `<%= javascript_pack_tag 'application' %>`
> `<%= stylesheet_pack_tag 'application' %>`
> If you want to link a static asset for <link rel="prefetch"> or <img /> tag, you can use the asset_pack_path helper:
> 
> `<link rel="prefetch" href="<%= asset_pack_path 'application.css' %>" />`
> `<img src="<%= asset_pack_path 'images/logo.svg' %>" />`

I've also seen it stated in other issues on this repo that it using `stylesheet_pack_tag` to point at a CSS file is discouraged, as "packs" should only be JS files.

Am I to understand that
1. if I reference a stylesheet in a JS pack `application.js` but DON'T include `<%= stylesheet_pack_tag 'application' %>` in my .html.erb file, then those styles will not be applied?
2. because webpacker won't know to bundle things outside of the single specified directory, and won't know to bundle CSS referenced in `.html.erb` files using `asset_pack_path`, if I want to bundle CSS using webpacker, i HAVE to include the CSS using references in JS files?
3. if I want to bundle/serve a CSS file without including a JS file on the page at all, I instead HAVE to create a JS file with a reference to that CSS file just so that webpacker will know to bundle/serve the CSS?

I feel like I MUST be missing something here. I'm migrating a very old codebase to webpacker right now and these issues seem extremely problematic.

Thanks!

**Comment by gauravtiwari** [comment]
Hey Ryan, 

> stylesheet_pack_tag to point at a CSS file is discouraged, as "packs" should only be JS files

Yep, but if you include a css file in your JS pack inside packs folder i.e. using an import statement then a separate CSS bundle will be created anyway (please see manifest.json), same as pack name unless you are using webpack dev server, in which case the CSS will be inlined with JS. 

> if I reference a stylesheet in a JS pack application.js but DON'T include <%= stylesheet_pack_tag 'application' %> in my .html.erb file, then those styles will not be applied?

Correct, unless you are using webpack dev server,  in which case the CSS will be inlined with JS. 

> CSS using webpacker, i HAVE to include the CSS using references in JS files?

Yes, you have to include any assets in the pipeline to be bundled. As mentioned in the README, packs folder is a special folder that's reserved for entry files.

> if I want to bundle/serve a CSS file without including a JS file on the page at all, I instead HAVE to create a JS file with a reference to that CSS file just so that webpacker will know to bundle/serve the CSS?

Yes or you can have a css/sass file inside packs folder as long as you don't create a circular dependency i.e. have the css/sass in the packs folder and also import it in one of your JS files (which is what we have discouraged).

**Comment by ryanscottaudio** [comment]
What do you mean by "please see manifest.json"?

So if I put stylesheets into my packs folder and require them using `stylesheet_pack_tag` then I'll be fine as long as I don't create circular dependencies? Will these stylesheets be part of `hmr`?

**Comment by gauravtiwari** [comment]
> What do you mean by "please see manifest.json"?

Just to see what's inside manifest (css, fonts) and anything inside manifest can be included in the view using relevant helpers. 

> So if I put stylesheets into my packs folder and require them using stylesheet_pack_tag then I'll be fine as long as I don't create circular dependencies? Will these stylesheets be part of hmr?

Exactly! And yes HMR should work fine.

**Comment by ryanscottaudio** [comment]
Thanks.
