### ISSUE TITLE
Make stylesheet_pack_tag load in development

### ISSUE THREAD

**Issue by ryanscottaudio** [rails/webpacker#1577]
Is there a way to force `stylesheet_pack_tag` to load content in development? Right now I have stylesheets working in my packs folder (wanted to keep CSS and JS files separate), but I'm having to reference them using `javascript_pack_tag` and it just feels kind of weird.

**Comment by renchap** [comment]
Do you have HMR enabled? When HMR is enabled, you need to load the stylesheets using JS so they can be hot-reloaded, so Webpacker does not output anything for the related `stylesheet_pack_tag` as the CSS is contained inside the JS file.
