### ISSUE TITLE
public/packs fills up with old files

### ISSUE THREAD

**Issue by dyeje** [rails/webpacker#1579]
I've noticed that the `public/packs` folder just keeps filling up with files as you develop and new compilations are made.  Is this intended behavior?  Gets annoying cleaning it out every so often.

**Comment by rossta** [comment]
@dyeje I use the `webpack-dev-server` in development, which serves files from memory and shouldn't fill up `public/packs` with anything. Do you something differently in development?

On the other hand, I do use the `compile: true` option in test and my `public/packs-test` directory does fill up over time. I occasionally use `RAILS_ENV=test bin/rake webpacker:clobber` to clear it out. Do you happen to mean `public/packs-test` as well?

**Comment by dyeje** [comment]
Hm, I do not use `webpack-dev-server`.  I just run rails normally and see the `Webpack compiling...` message in the logs when I update JS.  I have `compile: true` for dev in `webpacker.yml`. I never noticed it before, but yes `public/packs-test` fills up as well. 

Good to know about the rake task and `webpack-dev-server`, just always thought this was weird behavior and figured I'd bring it up.

**Comment by rossta** [comment]
Ok, yes, `compile: true` means Rails will shell out to the Webpack executable and your `public/packs` directory will fill up. That may add some overhead so you may be able to speed things up in development by using the dev server instead (with the tradeoffs of running a separate process alongside Rails). 

Using `compile: true` for Webpack is analogous to running `rake assets:precompile` for Sprockets for every change. I don't believe the asset pipeline would automatically clean up your `public/assets` directory if you used this strategy for Sprockets, so I'm not sure that something similar would be done for Webpacker but I suppose you could try a PR.

**Comment by dyeje** [comment]
Gotcha, that all makes sense to me.  Thanks!

**Comment by suryakantcaax** [comment]
> compile:
Hi Dyeje

how you resolved this issue? i facing same issue and its takint too much time to test even small changes in js file
