### ISSUE TITLE
Why does the deep_assign utility guard against falsy values?

### ISSUE THREAD

**Issue by gj** [rails/webpacker#1580]
I'd like to set the `node` property to `false` to take advantage of [this kill switch for unnecessary Node libs](https://github.com/webpack/webpack/blob/8e6a012dbbb1526db1da753b61c43e8c61b3379f/lib/node/NodeSourcePlugin.js#L16-L19), but this guard clause prevents it:

https://github.com/rails/webpacker/blob/fb9118ec6291a99605d30c3c887e48df1b3491a1/package/utils/deep_assign.js#L5

Happy to contribute a PR to address this case, but I'd like to better understand the reasoning behind the guard clause first. 🙂

**Comment by gj** [comment]
@gauravtiwari — friendly ping on this one / #1585 

Sorry to bother; you just seem to be the most active one around here 🙂

**Comment by gauravtiwari** [comment]
@gj Thanks and no worries. Could you please explain your usage? The kill switch example isn't very clear.

**Comment by gj** [comment]
Passing a boolean `false` is one of the possible values expected by the `node` property in Webpack's configuration. Here's the PR that added it into Webpack: https://github.com/webpack/webpack/pull/4995

And here's a test case for it: https://github.com/webpack/webpack/blob/7719cc6dd76f5ca1f5cc2bda3cc80b8529e628dd/test/configCases/parsing/node-source-plugin-off/webpack.config.js#L3

**Comment by gauravtiwari** [comment]
thanks merged 👍
