### ISSUE TITLE
Cannot GET / - Fresh install rails g newapp --webpack=react

### ISSUE THREAD

**Issue by robSturcke** [rails/webpacker#1584]
Can't get the react components of `application.js` or `hello_react.jsx` to load when placing the `pack_tag`: `<%= javascript_pack_tag 'hello_react' %>` in my `application.html.erb` or `index.html.erb`

Running both `./bin/webpack-dev-server` and `rails s`

Tried adding a `index.html` file in my `public > packs` directory but it loads as plain text. (Advice from issue #1325 ).  

What am I missing?  Not looking for hot reloading, just trying to get this to load a react component. 

I also tried `react-rails` but even with importing `<%= react_component("HelloWorld", { greeting: "Hello" }) %>` from a generated component I'm getting the same issue on `localhost:3035`.  I tried changing it to `localhost:3000` in the webpack config but same result.

**Comment by bengalamx** [comment]
Hi Rob, did you resolve this?
