### ISSUE TITLE
Integrate testcafe

### ISSUE THREAD

**Issue by phortx** [rails/webpacker#1586]
I'm trying to setup testcafe for my Webpacker based Vue SPA app currently. Does any one have experience with the integration? There are some questions, that bother me:

- I think I have to launch the server in TEST env manually for the tests?
- How to integrate with the webpack config of rails?

I'm thankful for any advice. Thanks!

**Comment by gauravtiwari** [comment]
@phortx testcafe is an end-to-end solution so you don't need to integrate it with Webpacker (unless I am mistaken).

-----

> I think I have to launch the server in TEST env manually for the tests?

Yes, because your end to end solution will visit the views in your Rails app so both you rails server and webpack dev server should be running (unless you have pre-compiled your packs using `webpacker:compile` or using on-demand compiler) 

> How to integrate with the webpack config of rails?

Don't think you need this step. 

Just setup an e2e folder in the rails app and create a pages folder will a list of tests. 

```js
// imports removed

const url = 'http://localhost:3000/404'

fixture `404`

test('user sees a valid 404 page', async t => {
  await t
    .navigateTo(url)
    .expect(notFound.selectors.title.innerText).contains('Page not found')
    .expect(notFound.selectors.link.innerText).contains('Go to home page')
})
```

**Comment by phortx** [comment]
@gauravtiwari Wow that was fast. Thank you for your answer :)

I've wrote a small bash script to prepare the test env and launch a rails server before running testcafe. This works like a charm :)

My `bin/e2e`:

```bash
#!/usr/bin/env bash

set -e

# Kill the rails server when this script ends
function finish {
  if [[ -n $SERVER_PID ]]; then
    echo "Stopping the rails server ..."
    kill $SERVER_PID
  fi
}

trap finish EXIT


# Make sure all commands run with test env
RAILS_ENV=test

echo "Setting up the database ..."
bundle exec rails db:environment:set db:reset > /dev/null

echo "Compiling the assets ..."
bin/webpack > /dev/null

echo "Spawning a rails server ..."
bundle exec rails s -p 5050 > /dev/null &

# Remember the PID of the rails server
SERVER_PID=$!

# Make a first request to make sure the server is warm and testcafe doesn't get a timeout on the first request
echo "Warming up the server ..."
sleep 10
wget -O- http://localhost:5050/ > /dev/null


echo "Running the tests ..."
testcafe chrome frontend/spec/e2e/test.js
```
