### ISSUE TITLE
How to set webpacker allow to use window object?

### ISSUE THREAD

**Issue by zverexe** [rails/webpacker#1588]
I need to use window object in my rails + react app but during server rendering, there isn't such an object. I know that in a webpack you can set target: 'node', and there won't be any error. Can I do the same in webpacker? If yes, how can I do this?

**Comment by ryanscottaudio** [comment]
https://webpack.js.org/configuration/externals/ or  may be helpful

**Comment by zverexe** [comment]
module.exports = {
   target: 'node'
};
???

**Comment by gauravtiwari** [comment]
Yep, that's correct 👍 thanks @ryanscottaudio 

Any valid Webpack configuration can be merged into existing config.

**Comment by gauravtiwari** [comment]
Here are docs: https://github.com/rails/webpacker/blob/master/docs/webpack.md#configuration

**Comment by vedmant** [comment]
Hm, for some reason environment.config is not defined in my environment.js: 

    const { environment } = require('@rails/webpacker')
    const { resolve } = require('path')
    const babelLoader = require('@rails/webpacker/package/loaders/babel')

    babelLoader.exclude = []
    babelLoader.include = [resolve('app/javascript'), resolve('node_modules/vue-multiselect')]
    environment.loaders.set('babel', babelLoader)

    environment.config.merge({
      externals: {
        jquery: 'jQuery',
      },
    })

    module.exports = environment

I have TypeError: Cannot read property 'merge' of undefined

webpacker (3.0.2)
rails (5.0.6)

**Comment by zverexe** [comment]
@ryanscottaudio sorry but your solution doesn't work. I received errors in the console, I still cannot use window object

**Comment by gauravtiwari** [comment]
@zverexe Perhaps you are using an old version of webpacker that didn't support this API?

**Comment by zverexe** [comment]
@gauravtiwari I use webpacker 3.5

**Comment by gauravtiwari** [comment]
Sorry that comment was for @vedmant 

@zverexe Could you please explain what are you trying to do? 
> I still cannot use window object.

**Comment by zverexe** [comment]
@gauravtiwari I want to check window with using window.innerwidth but since I'm using server rendering I get errors from server in the console that window is undefined because window object doesn't accessible on the server

**Comment by gauravtiwari** [comment]
@zverexe Thanks, I see. `window` object isn't available on the server. You probably have to change your code to be isomorphic so it works in both server and client side environment. You can use provideplugin to supply window object but this is going to break client-side window object.  

```js
environment.plugins.prepend(
  'Provide',
  new webpack.ProvidePlugin({
    'window': {}
  })
)
```

Usually, on the server you would have a `global` object. Here is a small helper function that you can use in your code: 

```js
export const canUseDOM: boolean = !!(
  typeof window !== 'undefined' &&
  window.document &&
  window.document.createElement
)

const MOBILE = 480
const TABLET = 800
const DESKTOP = 1440

const deviceSize = () => {
  if (canUseDOM) return window.innerWidth
  else if (device.isDesktop) return DESKTOP
  else if (device.isTablet) return TABLET
  else if (device.isMobile) return MOBILE
}
```

**Comment by gauravtiwari** [comment]
That's not hardcoded actually, on the server you can use user agent header to check device. Perhaps consider moving code involving `window` to client-side instead of server i.e. inside `componentDidMount`?

**Comment by zverexe** [comment]
I need window width before component render so I will use it in the render method. I cannot set it in componentDidMount

**Comment by zverexe** [comment]
I cannot put it to default as I do not know users screen width, it can be variuos. I thought I can hide window through webpacker during ssr compilation and use it just on frontend

**Comment by vedmant** [comment]
@gauravtiwari Indeed, I upgraded webpacker and can use config object, thanks!
