### ISSUE TITLE
What's the scope of helpers inside a javaScript file?

### ISSUE THREAD

**Issue by urielhdz** [rails/webpacker#159]
I'm playing with a React app with Rails, I've tried to use some view helpers inside a javaScript file without success.

It seems like we can't render partials or use blocks, since the first one can't find templates, and the second one can't parse blocks.

Now, I'm wondering if both these use cases are meant to be supported by the framework or if they're outside of the scope of it?

This is the error when using a block:

```ruby
/usr/local/rvm/gems/ruby-2.4.0/gems/erubis-2.7.0/lib/erubis/evaluator.rb:65:in `eval': (erubis:9: syntax error, unexpected ')' (SyntaxError)
 :user, url: "/users") do |f|) ).to_s; _buf << '
```

And this is my component:

```javascript
<% h = ActionController::Base.helpers %>

import React from 'react';

export class Login extends React.Component {

  render(){
    return (
      <%= h.form_for(User.new, as: :user, url: "/users") do |f| %>
      <%= h.text_field_tag :name %>
      <%end%>
    );
  }

}
```

Thank you.

**Comment by gauravtiwari** [comment]
@urielhdz No these helpers aren't supported, only some assets helpers. Please checkout the readme. I guess if you are building a react app you probably need to do things react way and not the other way around, kinda kills the purpose :) There are some react form libraries that you can use here, like Formsy

**Comment by gauravtiwari** [comment]
Feel free to close the issue if the above answers your question :)

**Comment by urielhdz** [comment]
I just wanted to confirm that both of those helpers were not supported, thank you very much for your answer and recommendation.
