### ISSUE TITLE
problem on webm|mp4

### ISSUE THREAD

**Issue by bidva** [rails/webpacker#1591]
I have problem on loading videos
 
```
./app/javascript/packs/WebSitePages/assets/videos/Map2-transcode.mp4
Module parse failed: Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
```
anybody knows how can I add loader to handle these kind of files ?

**Comment by gj** [comment]
Looks like you'll have to modify the `test` regex of the `file-loader` loader provided to you by Webpacker:

https://github.com/rails/webpacker/blob/392376871cf7d35dc4efd991a1dc279f20b2b26b/package/rules/file.js#L5

The default regex isn't going to match on `.webm` or `.mp4` files.

There's an example of how to modify the options of pre-configured loaders in the [Webpacker documentation](https://github.com/rails/webpacker/blob/9dbe833ac3981b2cbda2e70be143d621c055336f/docs/webpack.md#loaders).

Hope that helps!

**Comment by bidva** [comment]
@gj sorry maybe this is very basic but documentation didn't say how to modify a loader , it describe how to appending new loader.
there is 2 method comes to my mind. remove file loader and append new one. or modify it directly.
 May I ask you to give me an example how to modify one of them ?

**Comment by gj** [comment]
Here's from the documentation:

>You can also modify the loaders that Webpacker pre-configures for you. We'll update
the `babel` loader as an example:

>```js
>// config/webpack/environment.js
>const { environment } = require('@rails/webpacker')
>
>const babelLoader = environment.loaders.get('babel')
>babelLoader.options.cacheDirectory = false
>
>module.exports = environment
>```

**Comment by dachinat** [comment]
How did you resolve this?

**Comment by dachinat** [comment]
I did `environment.loaders.get('file').test = /\.(jpg|jpeg|png|gif|tiff|ico|svg|eot|otf|ttf|woff|woff2|mp4)$/i
`, and you?

**Comment by lextoc** [comment]
This works for me:

```
const { environment } = require('@rails/webpacker'

const fileLoader = environment.loaders.get('file')
fileLoader.test = /\.(jpg|jpeg|png|gif|tiff|ico|svg|eot|otf|ttf|woff|woff2|webm|mp4)$/i

module.exports = environment
```

**Comment by thisismydesign** [comment]
Posting some things learned when investigating this. I don't know much of this was specific for our app but it could be useful.

Extending `file-loader` options in `config/webpack/environment.js` will add the files as a "top-level reference" to the manifest, e.g.

`config/webpack/loaders/video.js`
```js
module.exports = {
  test: [/\.webm$/, /\.mp4$/, /\.ogv?g$/],
  use: [{
    loader: 'file-loader'
  }]
}
```

`config/webpack/environment.js`
```js
// ...
environment.loaders.prepend('video', videoLoader)
```

`public/packs/manifest.json`
```json
{
  "video.mp4": "/packs/js/video-1ee54f2c89b094e7e306.mp4"
}
```

And then: `asset_pack_path('video.mp4')`

This couldn't handle `ovg` format.

Alternatively:

`config/webpacker.yml`
```yml
  static_assets_extensions:
    - ....
    - .webm
    - .mp4
    - .ogv
```

`app/javascript/packs/application.js`
```ruby
# Require the files somehow
require.context("../images", true, /\.(gif|jpg|png|svg|mp4|webm|ogv)$/i);
```

Will add files as e.g.
`public/packs/manifest.json`
```json
{
  "media/images/video.mp4": "/packs/media/images/video-f00ac7a10a886bdd9ee02a799acc4e4d.mp4"
}
```

And then: `asset_pack_path('media/images/video.mp4')`
