### ISSUE TITLE
rake webpacker:check_node does handle extended Node.JS versions

### ISSUE THREAD

**Issue by jbotelho2-bb** [rails/webpacker#1598]
It looks like the `webpacker:check_node` uses the `Gem::Version` parser to parse Node.JS versions:

https://github.com/rails/webpacker/blob/4f5e1aca68dabacd790ee771727d3121ae0fd3d4/lib/tasks/webpacker/check_node.rake#L12

Unfortunately, this is only able to parse a subset of possible Node.JS versions. We have started tagging our Node.JS builds with extended version numbers (e.g. 8.11.2+some-tag), which is valid according to the [semver convention](https://semver.org/) that Node.JS follows, but results in webpacker blowing up:
 
```
rake aborted!
       ArgumentError: Malformed version number string 8.11.3+0-b20180704T02124290
       /opt/lib64/ruby/2.4.0/rubygems/version.rb:208:in `initialize'
       /opt/lib64/ruby/2.4.0/rubygems/version.rb:199:in `new'
       /opt/lib64/ruby/2.4.0/rubygems/version.rb:199:in `new'
       /tmp/build/vendor/bundle/ruby/2.4.0/gems/webpacker-3.5.3/lib/tasks/webpacker/check_node.rake:12:in `block (2 levels) in <top (required)>'
```

**Comment by gauravtiwari** [comment]
Feel free to make a PR please :)
