### ISSUE TITLE
Discussion: Consider removing on-demand compilation as a default as it quickly becomes slow

### ISSUE THREAD

**Issue by johnmcdowall** [rails/webpacker#1599]
On-demand compilation quickly becomes un-usably slow with even the most trivial amounts of code or npm dependencies. 

See: https://twitter.com/searls/status/1015035330750103554 

Summary: It doesn't take much in terms of dependencies to make the on-demand compilation slow to the point of unbearableness. It gives a false impression that Webpack itself is slow, when in fact the on-demand compilation is rebuilding the entire universe from scratch on each request. 

This does not serve new user well, creates a misdirection, and could be better implemented by either being turned off, or starting up the external Webpack process automatically on a first request.

**Comment by guillaumebriday** [comment]
On the other hand, it helps new developers to started without worried about how to run webpack (and what it is in the first place) in the back I guess. 👍
