### ISSUE TITLE
"undefined method `inquiry'" error

### ISSUE THREAD

**Issue by ekremkaraca** [rails/webpacker#1601]
Hey guys,

I have got error below when I run command `rails  webpacker:install:react` automatically run with `rails new app --webpack=react`:

```shell
rails aborted!
NoMethodError: undefined method `inquiry' for "development":ActiveSupport::StringInquirer
bin/rails:4:in `<main>'
Tasks: TOP => webpacker:install:react => webpacker:verify_install
(See full trace by running task with --trace)
```

I have Ruby version 2.5.1 installed.

**Comment by gauravtiwari** [comment]
Sorry, @ekremkaraca. Fixed in another release. Could you please try again?

**Comment by ekremkaraca** [comment]
@gauravtiwari Yes, it works as webpacker version 3.5.5. It was 3.5.4 when I had the error above. Thanks so much:)

**Comment by gauravtiwari** [comment]
Great 👍 no problem :)
