### ISSUE TITLE
Question: Why did yarn was chosen instead of npm?

### ISSUE THREAD

**Issue by MidnightWonderer** [rails/webpacker#1603]
Just wanted to know the rationale behind the decision.  
npm is the default for javascript project just curious why webpacker insist on using yarn and depends it as the default.

**Comment by renchap** [comment]
This is not a Webpacker decision, but a Rails one. Yarn is the JS package manager integrated with Rails so Webpacker uses it.
I was not involved in this, but iirc when the decision was made, npm was really lacking behind yarn, both in term of perf and feature (lockfile for example)

**Comment by prusswan** [comment]
Yarn is directly supported since [Rails 5.1](http://guides.rubyonrails.org/5_1_release_notes.html), but more importantly, dhh likes it so..

More info: http://g3ortega.com/rails/2017/05/30/rails-5-1-and-forward-yarn-on-rails.html

**Comment by MidnightWonderer** [comment]
Thanks for the info.  
Rails is starting to move slow IMO.  
A lot of stuffs with legacy reasons and steep update path.  
  
Guess I'm going to ditch the webpacker all together for future projects.  
 
Just pure npm & webpack itself have fewer hassle these day. Rails integration is a breeze just some thin Ruby code will do the job.  
  
Thanks a lot everyone who made the webpacker possible. It was a good ride.

**Comment by seanhealy** [comment]
It's pretty straight forwards to make webpacker play nice with npm.

There is a nice guide here:
https://itnext.io/how-to-use-webpacker-with-npm-instead-of-yarn-a8a764e3a8ab

However I do agree that out of the box support for npm or, just moving to npm now that it has caught itself up would be much preferable.

**Comment by fabriziobertoglio1987** [comment]
but [will yarn ever replace npm](https://github.com/yarnpkg/website/issues/913)?

**Comment by aesyondu** [comment]
Hi all, based on this [comment](https://medium.com/@TomPrats/i-think-some-changes-to-webpacker-broke-this-e1ffefc2b768) in this [article](https://itnext.io/how-to-use-webpacker-with-npm-instead-of-yarn-a8a764e3a8ab) as well as this [comment in a separate issue](https://github.com/rails/webpacker/issues/1746#issuecomment-439577648), it is no longer trivially possible to move to npm.

**Comment by jakeNiemiec** [comment]
Additionally, see: https://github.com/rails/webpacker/issues/2467#issuecomment-591652421
