### ISSUE TITLE
after installation webpacker to rails app in the application began to load for a very long time

### ISSUE THREAD

**Issue by vadus1** [rails/webpacker#1614]
I'm installing webpacker to my rails app, and after installation, I noticed that the pages in the application began to load for a very long time, what could happen?
I originally followed the installation instructions. 
After the start, I have to wait a long time for response.

I use ruby 2.5.0, rails 5.2.0, webpacker 3.5.5, node 10.6.0, yarn 1.7.0

from logs:

```
Started GET "/home/index" for 127.0.0.1 at 2018-07-13 02:55:45 +0300
Processing by HomeController#index as HTML
  Rendering home/index.html.erb within layouts/application
  Rendered home/index.html.erb within layouts/application (0.5ms)
Completed 200 OK in 30035ms (Views: 30032.9ms | ActiveRecord: 0.0ms)
```

sure, i'm run `./bin/webpack-dev-server` and `rails s`

<img width="1680" alt="2018-07-13 2 54 14" src="https://user-images.githubusercontent.com/3416746/42665473-7c737c94-8648-11e8-962f-4bbac2a21cfe.png">

**Comment by vadus1** [comment]
#1527 this is issue help me. 
I just too change `host: localhost` to `host: 0.0.0.0`

**Comment by vadus1** [comment]
@rahulakurati ran, did not help. 
When I changed `host` only then everything fell into place.

**Comment by rahulakurati** [comment]
Where does your rails app run? localhost or 0.0.0.0 ?

**Comment by vadus1** [comment]
hm good question. by default `localhost.`

**Comment by guillaumebriday** [comment]
Could this issue be closed?
