### ISSUE TITLE
Allow environment settings in webpacker.yml with ERB

### ISSUE THREAD

**Issue by tamouse** [rails/webpacker#1615]
Follow the conventions of Rails `config_for` that processes ERB settings before running the YAML loader.

**Comment by ckahle33** [comment]
Any update on this?

**Comment by jasonkarns** [comment]
Related to https://github.com/rails/webpacker/issues/956

I also expected ERB parsing in webpacker.yml to work. We need to get the dev server port from `ENV`

**Comment by SophiaAP** [comment]
Similar problem here. Some of our team does not want the javascript compiling in development but since we can't use environment variables in the YAML this is not an option. 

If anyone has advice on a workaround for this, we'd really appreciate it! 

Thanks for all your hard work on this gem.

**Comment by 23tux** [comment]
Same issue here: We are running parallel specs and need to suffix the public path with a test env number to avoid clashes between parallel specs on the file system. Any updates on this?

**Comment by latortuga** [comment]
@gauravtiwari since you closed #1801, are you opposed to supporting ERB in the config completely? Is there some other way to support this?

My use-case for ERB in the config is dynamic setting of the dev server port. I run multiple apps in development on my machine and I have to do the dev server dance by shutting down all of them except current each time I want to switch work between apps. It's my impression that this file is intended to be checked into source control so, if so, it should allow configuring from the environment in some way.

**Comment by schuylr** [comment]
My use-case to have ERB is to be able to control the `dev_server: public` endpoint so I can duplicate my Rails app across multiple development domains to behave differently.

**Comment by gingerlime** [comment]
@schuylr same here :( did you find a solution/workaround?

**Comment by latortuga** [comment]
I gave up on this feature and ended up just changing my webpacker-dev-server port in each app I work on. It works fine. I still think this feature might be nice.

**Comment by gingerlime** [comment]
In case it helps anyone, or now [this workaround](https://github.com/rails/webpacker/issues/956#issuecomment-416265099) helped us ... (and there's another [potential workaround](https://github.com/rails/webpacker/issues/956#issuecomment-341484600) but I haven't tried it).

Our use case was to override `dev_server: public` by running webpack dev server with `WEBPACKER_DEV_SERVER_PUBLIC=$SOME_ENV bin/webpack-dev-server`... So for a couple of overrides, I guess that's ok, but feels a bit dirty.

**Comment by rpbaptist** [comment]
It took me some iterations to realize ERB was not supported by this one Rails `.yml` config file. Unexpected indeed.

Another use case is when moving to Docker and want to be able to run a server locally or in a container.

Using things like `  check_yarn_integrity: <%= !!ENV["YARN_INTEGRITY_CHECK"] %>
` are a convinience I'd like to see possible.

I've ended up monkey patching webpacker instead.

**Comment by justin808** [comment]
Can't do since the yaml file is used by JS code.
