### ISSUE TITLE
bundle exec webpacker:compile fails

### ISSUE THREAD

**Issue by larquin** [rails/webpacker#162]
I'm getting this error when trying to run `webpacker:compile`:

```
sh: ./node_modules/webpack/bin/webpack.js: No such file or directory
rails aborted!
JSON::ParserError: A JSON text must at least contain two octets!
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => webpacker:compile
(See full trace by running task with --trace)
```

Obviously it seems like the rake task can't find the `webpack` command, but for some reason I was under the impression (probably falsely) that you didn't have to manage node dependencies for webpacker in the same way as say, a node project. 

I'm sure I'm missing something really obvious here, and if the answer is in documentation, I'm happy to re-read

**Comment by ytbryan** [comment]
Assuming you are using Rails 5.1.x, these are the steps to get started:

1. add `gem 'webpacker', github: "rails/webpacker"` 
2. `bundle` 
3. run `rails webpacker:install`

I think you might have missed step 3? Let me know if this fixes it

**Comment by gauravtiwari** [comment]
Hey @larquin,  As @ytbryan suggested, it's very likely you haven't run step 3. Webpacker is just a thin wrapper that bridges modern JS development experience gap by providing some out-of-box tools and helpers with Rails. Everything under the hood works exact the same way as it would work on any node project. Probably, when you run step 3 you will see what I mean. 

Feel free to close the issue if it works :)

**Comment by larquin** [comment]
@ytbryan @gauravtiwari yup, that was it. Thanks so much!

**Comment by atcoco** [comment]
1.  add gem 'webpacker', github: "rails/webpacker"
   2. bundle
   3. run rails webpacker:install
I have tried like this, but I have an error by third step.
Let me know what I can do.

**Comment by ytbryan** [comment]
> I have tried like this, but I have an error by third step.

And what kind of error?

**Comment by obelich** [comment]
i get this error

Adding configurations
      append  .gitignore
Installing all JavaScript dependencies
         run  yarn add @rails/webpacker coffeescript@1.12.7 from "."
ERROR: [Errno 2] No such file or directory: 'add'
Installing dev server for live reloading
         run  yarn add --dev webpack-dev-server from "."
Usage: yarn [options]

yarn: error: no such option: --dev
