### ISSUE TITLE
Typescript loader parses spec folder

### ISSUE THREAD

**Issue by hemju** [rails/webpacker#1620]
I added typescript + vue to our projects (based on this description https://github.com/rails/webpacker/blob/master/docs/typescript.md) Now I am getting a compilation error from typescript because we have a file in our spec/fixtures that has the file extension .ts. This fixture file is not a typescript file, so it produces a compilation error.

1. How can I exclude the spec folder from webpacker ts loader? I tried

```
module.exports = {
  test: /\.(ts|tsx)?(\.erb)?$/,
  use: [{
    loader: 'ts-loader',
    options: {
      appendTsSuffixTo: [/\.vue$/]
    }
  }],
  exclude: [
    "spec/**/*.test.ts",
    "node_modules"
  ]
}
```
Didn't help

2. Shouldn't the ts loader per default only look into the app/javascript folder?

**Comment by gauravtiwari** [comment]
You could exclude using `tsconfig.js`: https://www.typescriptlang.org/docs/handbook/tsconfig-json.html

**Comment by hemju** [comment]
Works, thanks.
