### ISSUE TITLE
There must be a way to specify multiple pack entry directories

### ISSUE THREAD

**Issue by ryanscottaudio** [rails/webpacker#1627]
I'm migrating an old codebase to use webpacker. We have the option to run JS tests when running locally, which means that we need to bundle the test files into separate entry points along with everything else. We DON'T want to bundle those files for staging/production, however. I would think that the solution to this would just be to specify two separate pack entry directories in development/test and one in staging/production, but it seems like that's totally impossible in this structure, unless I'm missing something. If I'm not missing anything, and it IS impossible, then it seems weird to me that webpacker would restrict a functionality that webpack offers.

The only solution I can think of for this would be using symlinks to link my packs folders into a parent folder and marking THAT as the `source_entry_path`, but this would also involve prepending all my `javascript_pack_tag` calls with this new directory, which seems nuts to me.

**Comment by ryanscottaudio** [comment]
I see in https://github.com/rails/webpacker/issues/585#issuecomment-321497152 that you addressed this a bit, saying that "ideally for developer experience it would be nice to have all entries at one place, which is how you would like to have in the longer term". I disagree that this is true in all cases, and I think it would be extremely useful to have multiple entry points as an option so that the decision to have one entry point or many could be delegated to each engineer/team in each unique situation, rather than enforced in the name of "best practices". Configuration over convention and all that.

**Comment by tgsoverly** [comment]
I have a use case with multiple engines that the idea of having the code in the respective engine would be much better from a developer perspective than navigating up to the highest level and then back down.

**Comment by maryammouse** [comment]
I completely agree, and am running into this issue right now. We have a monolith rails app that uses engines for different parts of the app, and I would really like not to have move files up from the engine into the main app...

**Comment by gauravtiwari** [comment]
Going to review this PR: https://github.com/rails/webpacker/pull/1694 and merge hopefully for engines support.

**Comment by tgsoverly** [comment]
It also feels like this is related too https://github.com/rails/webpacker/issues/348

**Comment by maryammouse** [comment]
Great to hear this is being worked on! :)

**Comment by guillaumebriday** [comment]
Is this issue still relevant? Feel free to reopen if needed
