### ISSUE TITLE
Files within directories within symlinked directories within the source_entry_path directory are not being bundled

### ISSUE THREAD

**Issue by ryanscottaudio** [rails/webpacker#1628]
If I have this directory structure:
```
packs/
  symlinked_directory/ <-- symlink to some other directory
    shallow_file.js
    deep_directory/ <-- not a symlink, just a regular directory within a symlinked directory
      deep_file.js
```
and set `source_entry_path: packs`, webpacker will only bundle/add to manifest.json `shallow_file.js` and not `deep_file.js`.

**Comment by guillaumebriday** [comment]
Consider packs as entrypoints, you should only import other files that are in `app/javascripts` for instance, see: https://github.com/rails/webpacker#usage
