### ISSUE TITLE
Unable to use devise helpers

### ISSUE THREAD

**Issue by draconiandev** [rails/webpacker#163]
Even though it is not a sprockets' helper, I am trying to access devise helpers in the *.jsx.erb files through the documented method of `<% h = ActionController::Base.helpers %>`. But whenever I use, something like `h.user_signed_in?` or `h.current_user`, console throws no method error `'user_signed_in?': undefined method 'user_signed_in?' for nil:NilClass (NoMethodError)`. Other helpers like `pluralize` or `link_to` work fine. However, if I try `h.respond_to?(:user_signed_in?)`, it returns true.

Is there anyway to access these or will there be support for all helper methods in the future?

I am using Rails 5.1.0.beta1, webpacker from master along with webpacker-react

**Comment by gauravtiwari** [comment]
Hey @draconiandev No, helpers apart from `ActionController::Base` aren't supported out of the box. You can probably patch it up, but I don't think this is going to be in the core. Can you not pass these things as props? https://github.com/renchap/webpacker-react#rendering-from-a-view

**Comment by gauravtiwari** [comment]
```erb
<%= react_component('Hello', user_signed_in: user_signed_in?) %>
```
