### ISSUE TITLE
'Compile: true' in test env and flaky specs

### ISSUE THREAD

**Issue by Shoroh** [rails/webpacker#1636]
I'm not sure if this is a bug.

We use Jenkins as a CI, with debian OS. Recently we added to our Rails 4.2 App Webpacker with Vuejs. And since that, we started to get flaky acceptance specs on CI (3-4 random specs of 300). Btw, we use Capybara and Rspec.

**If we precompile webpack assets locally and commit them to repo (the test-pack folder), and turned 'compile' to false in test env (in webpacker.yml), the flaky specs disappears, everything is green.**

But it's not a good idea to keep test-pack in repos.

What's going on there when compile set to true? What we did wrong? Can it be a bug of webpacker or incompatibilities with Rspec and Capybara?

I can provide more info about our stack if needed.

**Comment by maschwenk** [comment]
Do the failures start on the first instance of a feature spec running? If so then Capybara may be timing out as it waits for the compilation to finish. It's a good practice for CI runs to precompile your assets beforehand. No need to commit them to the repo, just have a step in the pre-test build process

**Comment by Shoroh** [comment]
Thanks, @maschwenk 

Yep, this is what exactly happened — our JS grew up and compiling time became longer.
As you advised, we added this precompilation step to CI, and everything went well.
