### ISSUE TITLE
Environment variables set with Webpacker::Compiler aren't available via process.env

### ISSUE THREAD

**Issue by bbugh** [rails/webpacker#1641]
#691 and [the docs](https://github.com/rails/webpacker/blob/cd36cd5/docs/env.md) suggest that `Webpacker::Compiler` would be able to pass environment variables over to the compiler, but I'm not finding this to be the case (at least based on the documentation example).

```ruby
# config/initializers/webpacker.rb
Webpacker::Compiler.env['FRONTEND_API_KEY'] = 'your_secret_key'
```

```javascript
// anywhere in environment.js (tried multiple places)
console.log(process.env['FRONTEND_API_KEY'])
=> undefined

console.log(process.env.FRONTEND_API_KEY)
=> undefined

console.log(process.env)
=> lots of environment variables
```

```bash
» FRONTEND_API_KEY='your_secret_key' ./bin/webpack-dev-server
your_secret_key
```

**Use case**

In our case, we have an existing Rails app that we're adding SPA to. We have a lot of legacy environment variable `if` checks and environment checks using Figaro. It would be quite complex to try to reproduce this in dotenv. By far the simplest solution for sharing app keys and variables with the SPA is simply passing them over from Rails at compile-time. 

Thank you for reading and for the really useful gem.

**Comment by Sparragus** [comment]
@bbugh Are you using Foreman or Heroku? If so, for Foreman you need to create a `.env` file. For Heroku, then add the env vars in their dashboard.

When you do this, you make them available on `process.env` inside `environment.js`. You also need to do the following inside `environment.js`.

```
environment.plugins.prepend(
  "Environment",
  new webpack.EnvironmentPlugin(
    JSON.parse(
      JSON.stringify({
        FRONTEND_API_KEY: process.env. FRONTEND_API_KEY.
        // add as many env vars as you need
      })
    )
  )
);
```

I know this does not explain why `Webpacker::Compiler.env['FRONTEND_API_KEY'] = 'your_secret_key'
` does not work (I wonder the same), but it may help temporarily.

Cheers.

**Comment by bbugh** [comment]
@Sparragus Thank you for the suggestion. As I mentioned in my initial report, our legacy environment variable structure is quite (annoyingly) complicated, and trying to reproduce it in a second location via dotenv would be very brittle and complicated. We'd honestly just stop using webpacker before we went down that road (which would be a shame because it's great). 

I think we're the ideal use case for the original intent of #691. The trouble we're having would be very easily and elegantly solved easily if this issue was resolved.

**Comment by ravelinx22** [comment]
I was able to load environment variables from Figaro application.yml by loading the files content. My ./bin/webpack and ./bin/webpack-dev-server looks like follows

```
#!/usr/bin/env ruby

ENV["RAILS_ENV"] ||= ENV["RACK_ENV"] || "development"
ENV["NODE_ENV"]  ||= "development"

# THIS WAS THE PART I ADDED
require 'yaml'
config = YAML.safe_load(
  File.read(
    File.expand_path('../config/application.yml', __dir__)
  )
)
variables = config.fetch(ENV['RAILS_ENV'], {})
variables.each do |key, value|
  ENV[key] = value.to_s
end

require "pathname"
ENV["BUNDLE_GEMFILE"] ||= File.expand_path("../../Gemfile",
  Pathname.new(__FILE__).realpath)

require "bundler/setup"

require "webpacker"
require "webpacker/webpack_runner"

APP_ROOT = File.expand_path("..", __dir__)
Dir.chdir(APP_ROOT) do
  Webpacker::WebpackRunner.run(ARGV)
end
```

And finally modified the environment.js as it was suggested by @Sparragus with the following:

```
environment.plugins.insert(
  "Environment",
  new webpack.EnvironmentPlugin(process.env)
)
```

**Comment by sirwolfgang** [comment]
Has there been thought for supporting something like this to pull in `Rails.application.credentials`?

**Comment by schmijos** [comment]
> environment.plugins.insert(
>   "Environment",
>   new webpack.EnvironmentPlugin(process.env)
> )

Don't you risk exposing everything like that?
