### ISSUE TITLE
Install generator appends content to .gitignore without newline at beginning

### ISSUE THREAD

**Issue by Owumaro** [rails/webpacker#1645]
https://github.com/rails/webpacker/blob/8ca372dc500d16a2343aaade7646647aac6925b3/lib/install/template.rb#L41

If you have a .gitignore file not ending with a `\n`, the `webpacker:install` command will write right after your last line.

Ex:
```
.DS_Store
```
Will become :
```
.DS_Store/public/packs
/public/packs-test
/node_modules
yarn-debug.log*
.yarn-integrity
```

**Comment by sharang-d** [comment]
This seems to be fixed by https://github.com/rails/webpacker/pull/1961/files.
Can it be closed? @gauravtiwari @Owumaro
