### ISSUE TITLE
Single entry point and slow transpiling performance

### ISSUE THREAD

**Issue by pinkynrg** [rails/webpacker#1649]
Is it possible to set a single file as entry point in webpacker?

in my other webpack configs i have something like the following:

```
entry: {
  app: './src/js/index.jsx',
},
output: {
  filename: '[name].js',
  path: path.resolve('assets/js')
},  
```

I don't get how I can my webpacker configuration to behave like the above:

```
source_path: app/javascript
source_entry_path: packs
public_output_path: packs 
cache_path: tmp/cache/webpacker
```

I tried to just type in the name of the file for my source_entry_path but that doesn't seem to be sufficient.

**Comment by renchap** [comment]
Each file in your `packs/` directory will become an entrypoint. If you only want one, just put only one file in `packs/` (and import your other files located outside of this directory)

**Comment by pinkynrg** [comment]
I was trying to do that cause it seems like the compiling process is kind of slow using webpacker and i don't know what part of the configuration is doing this.

Right now i'm only transpiling a div block with a "Hello" content and it takes almost 4 seconds.

```
Completed 200 OK in 3703ms (Views: 3700.6ms | ActiveRecord: 0.0ms)
```

**Comment by renchap** [comment]
Can you share the content of your `packs/` directory?

**Comment by pinkynrg** [comment]
Currently I only have this sample file:

```
// Run this example by adding <%= javascript_pack_tag 'hello_react' %> to the head of your layout file,
// like app/views/layouts/application.html.erb. All it does is render <div>Hello React</div> at the bottom
// of the page.

import React from 'react'
import ReactDOM from 'react-dom'
import PropTypes from 'prop-types'

const Hello = props => (
  <div>Hello srasdad. {props.name}!</div>
)

Hello.defaultProps = {
  name: 'David'
}

Hello.propTypes = {
  name: PropTypes.string
}

document.addEventListener('DOMContentLoaded', () => {
  ReactDOM.render(
    <Hello name="React" />,
    document.body.appendChild(document.createElement('div')),
  )
})
```

Maybe it appears "slower" because the JSX is getting transpiled only when I refresh the page? I normally watch the files? How can I watch the files so they continuously get transpiled?

**Comment by pinkynrg** [comment]
solved by using ./bin/webpack-dev-server which seems to be much faster than the lazy transpiling solution.
