### ISSUE TITLE
Should the webpack dependencies move to devDependencies?

### ISSUE THREAD

**Issue by soapsign** [rails/webpacker#165]
Currently, the generated package.json of the MV* templates, webpack dependencies are include in 
dependencies section but not devDependencies. It is more suitable to move those to devDependencies ?

**Comment by dleavitt** [comment]
negative, see: https://github.com/rails/webpacker/issues/117

**Comment by gauravtiwari** [comment]
@soapsign and this one  -  https://github.com/rails/webpacker/issues/160

**Comment by gauravtiwari** [comment]
Feel free to close the issue if that answers your question :)

**Comment by soapsign** [comment]
`Background: right now we're putting build deps under devDependencies even though they're required in production.`
If I need to deploy to server without node, can I bundle using webpack beforehand?

**Comment by p0wl** [comment]
yes, you can. run `rake webpacker:compile` and ensure that the files in `public/packs` are deployed to your server.

**Comment by soapsign** [comment]
OK.
