### ISSUE TITLE
Vue CLI 3 for webpacker 4

### ISSUE THREAD

**Issue by bbugh** [rails/webpacker#1650]
Vue CLI 3 was fully released recently, and it's a *huge* upgrade in quality for developer experience. Way less webpack, better command line tools, and plugins that don't require ejecting, so it's very simple to add things to the setup. It's the most "convention over configuration" system I've seen in javascript land.

Having the webpacker install a Vue CLI 3 setup instead of the old style would be an awesome pairing. I imagine it's going to be relatively simple change with huge benefits for everybody. It uses webpack 4 behind the scenes so I think it would require webpacker 4.

Thanks for taking so much of the nightmare out of webpack via webpacker. ❤️

**Comment by etewiah** [comment]
@bbugh Do you happen to know if it is possible to upgrade an existing vue webpacker install to take advantage of Vue CLI 3?
Thanks

**Comment by bbugh** [comment]
I don't, but someone recently posted an article about how to [integrate vue cli with webpacker](https://medium.com/@hunterae/rails-webpacker-and-vue-cli-can-actually-play-nicely-10215fe833e1). I haven't tried it yet, but it looks solid.

I also have [an example repository](https://github.com/bbugh/rails-5-vue-cli3-sample) about how to integrate Vue CLI3 + Rails without webpacker. 

You can also [read the article author's thoughts](https://old.reddit.com/r/vuejs/comments/dcrn4i/rails_webpacker_and_vue_cli_can_actually_play/f2h1m3i/) on the advantages of his approach integrating webpacker vs my example repository's manual approach.

**Comment by guillaumebriday** [comment]
I think it's out of the scope of this gem.

The approach is correct though.
Myself I used this in this repo : https://github.com/guillaumebriday/rails-vue-cli with explanations in the readme

I think we can close this issue 👍
