### ISSUE TITLE
Possible to use Stimulus and Erb simultaniously?

### ISSUE THREAD

**Issue by richjdsmith** [rails/webpacker#1655]
As implied in the title, if I have a project that already has Stimulus and Webpacker installed, is it possible to add Erb support in the Stimulus JS templates,by running ` bundle exec rails webpacker:install:erb `?

**Comment by grk** [comment]
This should work, `webpacker:install:erb` makes changes to the global webpack environment config. You'll just have to remove the example `hello_erb.js.erb` file.

**Comment by guillaumebriday** [comment]
Is this issue can be closed ?
