### ISSUE TITLE
Having trouble getting Webpacker running in TravisCI

### ISSUE THREAD

**Issue by mattgrande** [rails/webpacker#1661]
I'd like to get my app "running" in Travis so I can run E2E tests on in, but webpacker is refusing to run.

My travis file is pretty simple:

```
language: ruby
rvm:
  - 2.4.2
  - 2.5.1

before_script:
  - bin/yarn
  - bin/rails db:migrate RAILS_ENV=test

script:
  - bin/rails test
  - bin/yarn test
  - bin/webpack-dev-server --host 127.0.0.1
```

but I'm getting this error:

```
[0K$ bin/webpack-dev-server --host 127.0.0.1
webpack dev_server configuration not found in /home/travis/build/[omitted]/[omitted]/config/webpacker.yml[test].
Please run bundle exec rails webpacker:install to install Webpacker
```

Here's my concerns:

1. I shouldn't need to reinstall webpacker on the CI; Everything's in git
2. I have a `config/webpacker.yml` in the repo as well, so there should be access to it
3. I tried adding a `config/webpacker.yml[test]` file, but that didn't help either (same results)

What am I doing wrong?

**Comment by codingiam** [comment]
I've also run into this error message:

```bash
$ RAILS_ENV=dev ./bin/webpack-dev-server 
$ webpack dev_server configuration not found in .../config/webpacker.yml[dev].
Please run bundle exec rails webpacker:install to install Webpacker
```

So, I tried:
```bash
$ RAILS_ENV=development ./bin/webpack-dev-server
```

and it worked.

It looks like this happens when your RAILS_ENV has a value that's different from `development` and you're trying to start the dev server. This happens even when `config/webpacker.yml` has `dev` defined.

**Comment by gauravtiwari** [comment]
@codingiam If you need to use dev server in test, just copy the configuration from development to test as well, the above checks if dev server configuration is present before starting it.

**Comment by gauravtiwari** [comment]
Is this still an issue?

**Comment by mattgrande** [comment]
No; I don't quite understand it, but if I set `RAILS_ENV=development`, everything works fine... Even if my test env matching my dev env exactly.

This leads me to believe it's something, somewhere, in my configuration, and it's just a matter of figuring out what.

Thanks for the help, @codingiam!

**Comment by mwagz** [comment]
@mattgrande My `travis.yml` file is a little more intense, but I was able to get Travis to run everything by using the standard binstub.

```yml
# ...
script:
  - ./bin/webpack
# ...

**Comment by mattgrande** [comment]
I'm also using the binstub for Travis, so that's not the issue.

**Comment by mattgrande** [comment]
It's been working well with `RAILS_ENV=development` for awhile now, so I'm going to leave well enough alone. Thanks to all for their help.
