### ISSUE TITLE
Service Workers

### ISSUE THREAD

**Issue by jclif** [rails/webpacker#1662]
I've seen a few closed issues for service worker support, with some comments on the difficulty or serving them at root. Has any work been done to more deeply integrate support for service workers?

**Comment by bragovo** [comment]
I add plugin https://github.com/goldhand/sw-precache-webpack-plugin
Main problem here https://github.com/GoogleChromeLabs/sw-precache/blob/master/lib/sw-precache.js#L54 — pw-pecache can't find compiled file in filesystem and I dont know how to fix this for dev env. All other thing works fine.

**Comment by djforth** [comment]
sw-precache is pretty old and google now recommend using this - https://developers.google.com/web/tools/workbox/modules/workbox-webpack-plugin

It's pretty easy to implement into your webpack config, but I don't know about adding it by default, there are so many different ways of setting it up I would think adding it by default might be bit painful without a lot config.

**Comment by bragovo** [comment]
Is it possible to add generated index.html (by root_path) to manifest for cache by sw?

**Comment by guillaumebriday** [comment]
Is this issue can be closed ?
