### ISSUE TITLE
Invalid Host 

### ISSUE THREAD

**Issue by friendz708** [rails/webpacker#1666]
I am having problem in my php script. problem is as while visiting websites:

Warning: mysql_connect(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /home/hyipsdoor/public_html/inc_hyipguyz/config.inc.php on line 318

Warning: mysql_connect(): Connection timed out in /home/hyipsdoor/public_html/inc_hyipguyz/config.inc.php on line 318
Connection timed out

AND WHAT I FOUND IN LINE 318 IS AS:

  function db_open ()
  {
    global $settings;
    if (!($dbconn = mysql_connect ($settings['hostname'], $settings['db_login'], $settings['db_pass'])))
    {
      exit (mysql_error ());
      
    }

    if (!(mysql_select_db ($settings['database'])))
    {
      exit (mysql_error ());
      
    }

    return $dbconn;
  }

Please help in this regard.

**Comment by corymcdonald** [comment]
This is a ruby library not a php library, chances are StackOverflow would be much more suited to help you out

**Comment by gauravtiwari** [comment]
thanks @corymcdonald
