### ISSUE TITLE
Rails 3 Support

### ISSUE THREAD

**Issue by elpic** [rails/webpacker#1675]
Is it possible to add support to Rails 3?

**Comment by danielrose7** [comment]
If you're up for a challenge, you could file a PR. However as Rails 3 is officially unsupported,  I think it's safe to say that webpacker won't be delivered to or maintained for Rails 3 apps.

If it's ES6 that you're after, here is a sample of what I was using on a project I work on go onto Rails 4 about a year ago using Browserify:

https://gist.github.com/danielrose7/39b94a16d763090ad69d57f32b8a9070

**Comment by gauravtiwari** [comment]
Thanks @danielpowell4 ❤️
