### ISSUE TITLE
All node_modules assets are dumped into public/assets

### ISSUE THREAD

**Issue by jemminger** [rails/webpacker#1681]
I have only 10 runtime dependencies in my package.json.  When I deploy, my public/assets folder balloons to 88+MB because every asset in the whole node_modules tree is copied there.  Is this expected behavior?  It's inflating the size of the heroku slug, and it's taking more than 15 minutes to deploy now no doubt related to having to compile assets from almost 1000 node_module folders.

**Comment by renchap** [comment]
This is definitely not normal. I think it might be Sprockets copying them, but I am not sure why.

**Comment by jemminger** [comment]
Yeah, just checked and I've got another app with supposedly the same setup and it's not happening there.  Guess I'll have a diff party
