### ISSUE TITLE
rails assets:precompile deletes some @types package ...why?

### ISSUE THREAD

**Issue by github0013** [rails/webpacker#1683]
```bash
$ RAILS_ENV=production rails assets:clobber
$ yarn
```
At this point, all @types packages are installed like this.
![7590a39d1828f187774974db72598fd5](https://user-images.githubusercontent.com/809378/45006101-2f1bbb00-b032-11e8-8f55-c51f4acb60c7.png)

Then when I run this command, at `Building fresh packages...`, some @types packages get deleted.

```bash
$ RAILS_ENV=production rails assets:precompile
...
...
warning "webpack-dev-server > webpack-dev-middleware@1.12.2" has unmet peer dependency "webpack@^1.0.0 || ^2.0.0 || ^3.0.0".
[4/4] 📃  Building fresh packages...
```

![7dfde543a12bcef7546c4216c1fb9a85](https://user-images.githubusercontent.com/809378/45006103-3216ab80-b032-11e8-969e-88c1aa7654d5.png)

```json
// package.json
{
  ...
  ...

  "devDependencies": {
    "@types/numeral": "^0.0.25",
    "@types/react": "^16.4.11",
    "@types/react-dom": "^16.0.7",
    "@types/react-router": "^4.0.30",
    "@types/react-router-dom": "^4.3.0",
    "@types/uuid": "^3.4.4",
    "node-sass": "^4.9.3",
    "postcss-modules": "^1.3.2",
    "webpack-dev-server": "2.11.2"
  }
}
```

Has anybody notice this behavior?

**Comment by gauravtiwari** [comment]
Because `RAILS_ENV=production rails assets:precompile` re-installs npm packages and removes packages listed under dev. 

https://yarnpkg.com/en/docs/cli/install#toc-yarn-install-production-true-false

**Comment by benoist** [comment]
@gauravtiwari is there a way to keep the dev packages when precompiling? 
Every time I run the precompile before deployment, I have to reinstall the dev package before I can continue with development.

**Comment by gauravtiwari** [comment]
Hey @benoist Hmm, don't think so, unless you run the `RAILS_ENV=production rails webpacker:compile` directly but that won't precompile sprockets assets :( 

The other way is to customise `assets:precompile` task and remove enhancements that way you can run two tasks separately.
