### ISSUE TITLE
Gaining access to the rails variables inside js file

### ISSUE THREAD

**Issue by ytbryan** [rails/webpacker#1684]
Hi folks, 

does anyone know how do I access the rails variables via erb inside a .js file. I am not looking for an alternate solution like using the `gon` rubygem. 

From https://github.com/rails/webpacker/issues/1256, I know I can access the ActionController' helpers using: 

```
<% helper = ActionController::Base.helpers %>
<% helpers.asset_pack_path('rails.png') %>
```
How do I print the rails variable (@something) of my index action of Actioncontroller, inside the js.erb? 

For instance, 
```ruby
#inside PagesController.rb
def index
@something = "something" 
end
```

```js
//packs/something.js.erb
console.log("<%= @something %>")
```

What am I missing here? Appreciate any pointers. Thank you!

**Comment by haffla** [comment]
In a standard (non-Webpacker) `.js` or `.js.erb` file you cannot access controller instance variables either as far as I know.

If you cannot use gon, I guess you have to do it manually and set the variables in the view and access them then in your Javascript.

**Comment by ytbryan** [comment]
Yup, I am not looking at non-webpacker setup. Mainly looking at `packs/*js.erb` 

I was hoping that Rails' ujs has something available for direct usage.

**Comment by gauravtiwari** [comment]
Not sure if that's easily doable unless you extend the `ActionController::Base.helpers` with your own set of helpers, which is a bit repetitive and probably not intuitive if you want to share instance variables - https://github.com/rails/webpacker/blob/master/lib/webpacker/railtie.rb#L64. 

Is it not possible to use `data-attrs` i.e. declaring `data-attrs` in the view and reading it back in JS? 

```html
<div data-attrs="{something: "foo"}" id="foo">
</div>
``` 

```js
const foo = JSON.parse(document.getElementById('foo').dataset.attrs);
foo.something
```

**Comment by sharang-d** [comment]
@ytbryan Did that work for you? Can we close this?

**Comment by anon987654321** [comment]
If I may ask, what's really the point of Erb in JS if we can't access Rails variables?
