### ISSUE TITLE
Staging config is not used

### ISSUE THREAD

**Issue by nozpheratu** [rails/webpacker#1696]
Using **v3.5.5**, I defined a new staging environment, in `config/webpacker.yml` I have:

```
staging:
  <<: *default
  compile: false
  cache_manifest: true
```

I also have the following in `config/webpack/staging.js`:

```
const environment = require('./environment');
const webpack = require('webpack');

environment.plugins.append(
  'DefineGlobals',
  new webpack.DefinePlugin({
    API_HOST: JSON.stringify('https://example.com'),
  }),
);

module.exports = environment.toWebpackConfig();

```

This `staging.js` config does not seem to get incorporated into my pack at all when I built using `RAILS_ENV=staging NODE_ENV=staging bundle exec rails assets:precompile`, one of my packs utilizes this environment-specific variable.

Regardless of whether `NODE_ENV` is set to production or staging, in any case it seems to be using the settings in `config/webpack/production.js` rather than `config/webpack/staging.js`.

**Comment by rossta** [comment]
[Here's the line](https://github.com/rails/webpacker/blob/88a253ed42966eb2d5c997435e9396881513bce1/lib/webpacker/runner.rb#L14) that would determine which `config/webpack/<env>.js` file to use. It might be worth checking to be sure this code gets executed with the right env value when you run the webpack executable. 

One possibility that occurred to me is, if you've upgraded from earlier versions: be sure you regenerate the binstub and uninstall previous versions of the gem, as discussed [here](https://github.com/rails/webpacker/issues/1165).

**Comment by ndesorden** [comment]
Same issue here. Thanks to @rossta , i've debugged NODE_ENV in runner.rb and has **production** as value!!!! Now trying to find who/where is changing NODE_ENV

**Comment by ndesorden** [comment]
Ooops, the compile rake task has hardcoded "production". Amazing ;-)

```
namespace :webpacker do
  desc "Compile JavaScript packs using webpack for production with digests"
  task compile: ["webpacker:verify_install", :environment] do
    Webpacker.with_node_env("production") do
      ensure_log_goes_to_stdout do
        if Webpacker.compile
          # Successful compilation!
        else
          # Failed compilation
          exit!
        end
      end
    end
  end
end
```

**Comment by dreyks** [comment]
i think hardcoding was the way to decouple NODE_ENV and RAILS_ENV and still retain the rails-magic in making it just work for assets:precompile in production

**Comment by phlegx** [comment]
We have the same problem! So, why it does not use RAILS_ENV?

```
module Webpacker
  class Runner
    ...
    def initialize(argv)
      ...
      #@webpack_config    = File.join(@app_path, "config/webpack/#{ENV["NODE_ENV"]}.js")
      @webpack_config    = File.join(@app_path, "config/webpack/#{ENV["RAILS_ENV"]}.js")
      ...
    end
  end
end
```

**Comment by jakeNiemiec** [comment]
> @phlegx why it does not use RAILS_ENV?

Short Answer: `NODE_ENV` controls different things than `RAILS_ENV`.

Take the `webpacker` gem for example, there is a difference between  developing **on** the gem and developing **with** the gem _(as a tool)_.  You want the JS/browser/packs side of things to think & act as if it was in production _(as a tool)_. When `RAILS_ENV` is `staging` or `test`, you would want `NODE_ENV` to be set to `production` (for speed & reliability). More discussion: https://github.com/rails/webpacker/issues/1212#issuecomment-442228316

**Comment by guillaumebriday** [comment]
Could we close this issue?
