### ISSUE TITLE
CSS position: sticky 

### ISSUE THREAD

**Issue by fowkswe** [rails/webpacker#1701]
Hi, 

I'm not even sure if this is the right place for this, but I thought I'd start here before diving into the webpack fundamentals.

It seems like something with the webpack config is breaking position: sticky.  My uniformed guess is that it relates to something getting injected into the DOM for hot reloading, but I can't find any such thing in web inspector.

I've created an example here:

https://github.com/fowkswe/teststicky

The element created in HAML, outside the Vue object will honor the `position: sticky` declaration, but the markup generated with the `hello_vue.vue` component does not. 

Any pointers would be greatly appreciated.

TIA, 
Billy

**Comment by danielpowell4** [comment]
Per the demo you linked, position sticky seems to be working fine for me (at least in firefox)

1. git clone...
2. bundle
3. yarn
4. bundle exec foreman start

![demo in firefox](https://user-images.githubusercontent.com/15863213/45715242-fc54e500-bb50-11e8-926e-b5818794f727.gif)

Wonder if you are running into a browser compatibility issue:
https://caniuse.com/#search=position%3A%20sticky

Depending on your use case, I'd recommend you check out things like [tether](http://tether.io/)/[popper](https://popper.js.org/) or one of the seeming dozens of vue-based solutions like [vue-affix](https://github.com/eddiemf/vue-affix) or [vue-fixed-header](https://github.com/potato4d/vue-fixed-header) or [vue-sticky](https://www.npmjs.com/package/vue-sticky)

Slapping this as a "webpacker" issue without much cause to reason that it's a webpacker-specific issue, isn't ideal. Stackoverflow and the wide world of the vue community member channels would likely have been a more proper place to start until you could definitely say that something in asset pre-compilation was going awry

**Comment by fowkswe** [comment]
@danielpowell4  Thanks for the response and for looking into it!  

I definitely weighed if this was the right place for it - but truly believe its a webpack(er) issue.   I should probably address it in the webpack project, but I'm less familiar with setting up a pure JS project to demonstrate.  

In the image you posted the stuck text is in the HAML markup.  You'll see the part rendered by Vue (thus webpacke'd) is still scrolling out of screen even though it's got `position: sticky; top: 0;` applied to it.

**Comment by danielpowell4** [comment]
@fowkswe Sorry for my misunderstanding the example. Dug a bit deeper... is most certainly not a webpacker issue.

What is happening is that unlike many CSS properties, position is not inherited by default (it doesn't cascade ever downward)

 This means that the elements inside of your nav in the example (ul, li, p etc) have a default of `position: static` which comes from the browser. [More info](https://www.w3schools.com/cssref/pr_class_position.asp)

To overcome this and get the behavior you expect, you'll need to override this and set it to `position: inherit` as shown here

```
<template lang='pug'>
  #app
    p(v-for="item in ['before', 'sticky', 'enabled']" :key="item") {{ item }}
    nav(style="position: sticky; top: 20px; z-index: 101;") little nav
      ul(style="position: inherit")
        li
          a(href='#') This
        li
          a(href='#') Nav, created in the hello_vue component
        li
          a(href='#') WILL
        li
          a(href='#') Stick
    p(v-for="item in 100" :key="item") {{ item }}
</template>
```

![vue](https://user-images.githubusercontent.com/15863213/45723072-c1f94100-bb6c-11e8-969a-5580fc35446c.gif)

This is (potentially) easier to read here:

```
<template>
  <div id="app">
    <p v-for="item in ['pre', 'sticky', 'text']" :key="item">{{item}}</p>
    <nav>This is Vue sticky</nav> // <-- Notice no nesting for simplicity
    <p v-for="item in 100" :key="item"> {{ item }}</p>
  </div>
</template>
```



If you find a better way to fix the issue, I'd be curious!

**Comment by fowkswe** [comment]
Hey @danielpowell4 thanks so much for suffering my silly question with the great answer!  :)

I'm still having problems with the `position: inherit` - would you mind sending me a pull request of your changes so i can try to replicate?

**Comment by danielpowell4** [comment]
I posted the file in an issue https://github.com/fowkswe/teststicky/issues/1

Good luck

**Comment by gauravtiwari** [comment]
Please use the latest RC, and feel free to open a new issue with more details if this is still an issue.
