### ISSUE TITLE
Log webpack compile result when running rake webpacker:compile

### ISSUE THREAD

**Issue by dbalatero** [rails/webpacker#1702]
Hey all!

When I run `rake webpacker:compile` I would love to see the output of Webpack written to stdout. This would assist in debugging hard-source-webpack-plugin caching on CircleCI, among other things.

What do you think about a config option for this? I see that stdout is already captured, so optionally printing it given a config variable would be pretty easy to add:

https://github.com/rails/webpacker/blob/7b5fdad7dbce59b928a62a8b320279c276556e50/lib/webpacker/compiler.rb#L69-L75

I'm happy to open a PR for this if you're open to it.

**Comment by dbalatero** [comment]
```ruby
if status.success? 
  logger.info "Compiled all packs in #{config.public_output_path}"
  logger.info stdout if config.show_webpack_output?
end
```

or something

**Comment by gauravtiwari** [comment]
@dbalatero Thanks, yes please feel free 👍
