### ISSUE TITLE
Vulnerable Module: Mem

### ISSUE THREAD

**Issue by liamdefty** [rails/webpacker#1706]
It appears that in the latest stable version there is a vulnerable module installed. The `mem` package needs to be updated to version 4> but is currently on 1.*. 

![image](https://user-images.githubusercontent.com/15612152/45890684-7be5ec80-bdbb-11e8-9d62-2a18b9e4cf5a.png)

**Comment by gauravtiwari** [comment]
Please use the latest RC, and feel free to open a new issue with more details if this is still an issue.
