### ISSUE TITLE
Typescript loader `test` regex marks `.ts` extension as optional

### ISSUE THREAD

**Issue by kjleitz** [rails/webpacker#1708]
See the following:

```js
// webpacker/lib/install/loaders/typescript.js (in the webpacker source)

module.exports = {
  test: /\.(ts|tsx)?(\.erb)?$/,
  use: [{
    loader: 'ts-loader'
  }]
}
```

```js
// config/webpack/loaders/typescript.js (in your project after installation)
// the extra Vue-specific option is added by me, but I'm including it for context in case it's relevant

module.exports = {
  test: /\.(ts|tsx)?(\.erb)?$/,
  use: [{
    loader: 'ts-loader',
    options: {
      appendTsSuffixTo: [/\.vue$/]
    }
  }]
};
```

The file `test` regex (`/\.(ts|tsx)?(\.erb)?$/`) marks the TypeScript file extension as optional (`...s|tsx)?(\.e...`). Is there a reason it's that way, and not `...s|tsx)(\.e...`? None of the other loader templates mark their respective extensions as optional in their test regexes, and removing the `?` doesn't seem to affect compilation in my own project.

Is this a typo, or is it intentional?

**Comment by kjleitz** [comment]
bump!

**Comment by connorshea** [comment]
I think this was probably supposed to be `tsx?`, to make the `x` optional.
