### ISSUE TITLE
Babel not transpiling

### ISSUE THREAD

**Issue by madroneropaulo** [rails/webpacker#1709]
My question was marked as duplicated on stackoverflow, and pointed to babel. But I think this is a webpacker config issue. 
https://stackoverflow.com/questions/52452172/rails-5-2-1-webpacker-babel-not-transpiling-react

**Comment by danielpowell4** [comment]
https://stackoverflow.com/questions/33460420/babel-loader-jsx-syntaxerror-unexpected-token

Are you sure you have run `bundle` and `yarn` recently?
Are you also sure there isn't a linter issue? I run my code through prettier with a [pre-commit hook](https://prettier.io/docs/en/precommit.html)

Typically speaking `jsx` is an unnecessary file extension. `js` works fine. Per [the prophet](https://twitter.com/dan_abramov/status/763712190272667648?lang=en)

FWIW here is my babelrc file. It is bit different than the default webpacker in that `uglify` is replaced with [forceAllTransforms](https://babeljs.io/docs/en/babel-preset-env#forcealltransforms). It also removes prop-types from dependencies--as they aren't checked in the production build of react

```
{
  "presets": [
    [
      "env",
      {
        "useBuiltIns": "usage",
        "forceAllTransforms": true,
        "shippedProposals": true
      }
    ],
    "react"
  ],
  "env": {
    "production": {
      "plugins": [
        [
          "transform-react-remove-prop-types",
          {
            "mode": "remove",
            "ignoreFilenames": ["node_modules"],
            "removeImport": true
          }
        ]
      ]
    }
  },
  "plugins": [
    "syntax-dynamic-import",
    "transform-object-rest-spread",
    "transform-class-properties"
  ]
}
```

and (what I think is relevant) package.json

```
{
  //...
  "devDependencies": {
    "prop-types": "^15.6.2",
    "webpack-cli": "^2.0.13",
    "webpack-dev-server": "^3.1.1"
  },
  "engines": {
    "node": "^8.11"
  },
  "dependencies": {
    "@rails/webpacker": "^4.0.0-pre.2",
    "babel-core": "^6.26.0",
    "babel-eslint": "^8.2.2",
    "babel-plugin-syntax-dynamic-import": "^6.18.0",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-plugin-transform-react-remove-prop-types": "^0.4.14",
    "babel-polyfill": "^6.26.0",
    "babel-preset-env": "^1.6.0",
    "babel-preset-react": "^6.24.1",
    "babelify": "^8.0.0",
    "caniuse-lite": "^1.0.30000815",
    "react": "^16.4.2",
    "react-dom": "^16.4.2",
    "style-loader": "^0.20.3"
  }
//...
}
```

Good luck!

**Comment by madroneropaulo** [comment]
Thank you... the problem was the dependencies. babel-preset-react  turns out should be on "dependencies" and not "devDependencies". I thought the dependencies are meant for runtime and thought that webpack builds everything beforehand... I have to read how webpacker works. Thank you again!
