### ISSUE TITLE
Documentation for contributing

### ISSUE THREAD

**Issue by sharang-d** [rails/webpacker#1710]
I could not find any documentation for contributing to the project.

Can we add some information to README.md to communicate this or create a new file like [CONTRIBUTING.md](https://github.com/rails/rails/blob/master/CONTRIBUTING.md)?
At least the basics like running yarn lint/test, etc.

**Comment by gauravtiwari** [comment]
Thanks @sharang-d 

Could you please open a PR and we can work on this?

**Comment by sharang-d** [comment]
Sure!
