### ISSUE TITLE
Babel 7 Support Release

### ISSUE THREAD

**Issue by jfangrad** [rails/webpacker#1714]
Hey, I noticed that master has been updated to use Babel 7. Is there a timeline on releasing a new version with the Babel 7 included? I need babel 7 support to pull in a new module to one of my projects and can't do so until webpacker is updated.

If not would it be possible to do a pre-release version?

**Comment by swrobel** [comment]
Duplicate of #1713

**Comment by gauravtiwari** [comment]
Just made another pre-release:

```
yarn add @rails/webpacker@next
bundle update webpacker
```

**Comment by Welziewagers2015** [comment]
Just saw the release on the yarn add nice work you all.
