### ISSUE TITLE
upgrade webpacker to version 4, why install @rails/webpacker@3.5.5

### ISSUE THREAD

**Issue by wukong1995** [rails/webpacker#1717]
i upgrade webpacker to version 4, and run `bundle exec rails webpacker:install`, why install @rails/webpacker@3.5.5 not @rails/webpacker@4.0.0-pre.2

prev version:
```
gem 'webpacker', '~> 3.0'

"@rails/webpacker": "^3.0.1",
```

**Comment by gauravtiwari** [comment]
Thanks @ytbryan 

Try pre-release/next tag:

```
yarn add @rails/webpacker@next
bundle update webpacker
```
