### ISSUE TITLE
@rails/webpacker: 4.0.0-pre.2 not updated to the latest master

### ISSUE THREAD

**Issue by anestik** [rails/webpacker#1718]
Although master has been updated with latest node modules, package has not been updated to npm registry. As a consequence, a conflict is caused with webpack 4 and webpack-cli 2. 

This has been referenced in the following issue too.
[https://github.com/webpack/webpack-cli/issues/607](url)

**Comment by gauravtiwari** [comment]
Just published - `pre.3` or you can install using the `next`tag. `yarn add @rails/webpacker@next`
