### ISSUE TITLE
Switch to terser-webpack-plugin for JS minification

### ISSUE THREAD

**Issue by renchap** [rails/webpacker#1719]
UglifyJS2 (also known as `uglify-es`, which supports ES6) is [no longer maintained](https://github.com/mishoo/UglifyJS2/issues/3156#issuecomment-392943058). It has been forked into [Terser](https://github.com/terser-js/terser) and `webpack` replaced `uglifyjs-webpack-plugin` with it for Webpack 5: https://github.com/webpack/webpack/pull/8036

I suggest that Webpacker switches to Terser as well as the currently user Uglify version has many unfixed bugs (especially when using ES6 output).

**Comment by gauravtiwari** [comment]
Please feel free to make a PR :)

**Comment by bjankord** [comment]
This is resolved with this PR: https://github.com/rails/webpacker/pull/1816
The PR has been merged to master.
