### ISSUE TITLE
Getting undefined method `javascript_pack_tag' for ...

### ISSUE THREAD

**Issue by schovi** [rails/webpacker#172]
Having Rails 5 application and followed this tutorial https://medium.com/statuscode/introducing-webpacker-7136d66cddfb#.4xpiogt9l how to install and run webpacker.

Having webpacker in Gemfile
```
gem 'webpacker', github: 'rails/webpacker'
```

And used installation commands 
```
rails webpacker:install
rails webpacker:install:react
```

And when open page with `<%= javascript_pack_tag 'app' %>` I am getting `undefined method 'javascript_pack_tag' for #<#<Class:0x007f8d5a158378>:0x007f8d5a0015b0>`

./bin/webpack-dev-server runs fine (but having some babel errors, but I guess that can't have impact on previous error).

**Comment by ytbryan** [comment]
It works on my side. I'm using rails `5.1.0.beta1`, latest webpacker from github. 

Did you `bundle install`?

**Comment by schovi** [comment]
@ytbryan Sure I run `bundle install`

```
Using webpacker 1.0 from git://github.com/rails/webpacker.git (at master@a85a3ab)
```

Tutorial said it is for Rails 4.2+ and unfortunately due to dependency hell in my project I can't update to 5.1 yet :(

**Comment by schovi** [comment]
I tried to `require 'webpacker'` in `application.rb` and it returned `true`, but still same error.

**Comment by schovi** [comment]
I trace the source code `webpacker/lib/webpacker/railitie.rb`
```
class Webpacker::Engine < ::Rails::Engine
  initializer :webpacker do |app|
    p "Initializing webpacker"
    ActiveSupport.on_load :action_controller do
      p "Using Webpacker::Helper"
      ActionController::Base.helper Webpacker::Helper
    end
```
and it printed my debug.

Then I tried to use Helper manually and everything is fine.
```
class ApplicationController < ActionController::Base
  helper Webpacker::Helper
end
```

**Comment by ytbryan** [comment]
May I know which rails version is this project on?

**Comment by schovi** [comment]
@ytbryan `Rails 5.0.1`

**Comment by ytbryan** [comment]
Just tested it with `5.0.1` and it still works fine on my end.

**Comment by schovi** [comment]
Maybe some conflict gem?

**Comment by ytbryan** [comment]
I don't have enough info to confirm that. 

Can you close this if the manual helped fixes it? Feel free to open it again if you find the root of the problem.

**Comment by schovi** [comment]
Thanks

**Comment by gauravtiwari** [comment]
@schovi Were you using .js.erb extension for app pack?

**Comment by gauravtiwari** [comment]
If yes to above, do you got javascript comments in that file? Please remove that since it's erb. I have made a demo for you here - https://tranquil-inlet-61365.herokuapp.com/ and code is here - https://github.com/gauravtiwari/webpacker-demo-app

**Comment by schovi** [comment]
@gauravtiwari I have bare structure generated by `rails webpacker:install` and `rails webpacker:install:react` nothing more. 
And I think problem is strictly related to Rails and its Helpers, because of manaully using

```
class ApplicationController < ActionController::Base
  helper Webpacker::Helper
end
```

works fine.

**Comment by gauravtiwari** [comment]
Ah right, but it's bit strange too, given you are using Rails 5.0.1. It works without including helper for me - https://github.com/gauravtiwari/webpacker-demo-app. Perhaps, `application.rb` is setup differently - I mean includes on the top that adds gems from Rails?

**Comment by schovi** [comment]
@guilleiguaran 

```
require_relative 'boot'

require 'active_record/railtie'
require 'action_controller/railtie'
require 'action_view/railtie'
# require 'action_mailer/railtie'
# require 'action_cable/engine'
# require 'rails/test_unit/railtie'
require 'sprockets/railtie'
require 'sidekiq/api'

# Require the gems listed in Gemfile, including any gems
# you've limited to :test, :development, or :production.
Bundler.require(*Rails.groups)

module MyApp
...
```

**Comment by schovi** [comment]
@gauravtiwari 

When adding `require 'webpacker/railitie'` it end up on missing constant Webpacker
```
/Users/schovi/.rvm/gems/ruby-2.4.0@lotof/bundler/gems/webpacker-a85a3ab0eac6/lib/webpacker/source.rb:5:in `<top (required)>': uninitialized constant Webpacker (NameError)
	from /Users/schovi/.rvm/gems/ruby-2.4.0@lotof/bundler/gems/webpacker-a85a3ab0eac6/lib/webpacker/helper.rb:1:in `require'
	from /Users/schovi/.rvm/gems/ruby-2.4.0@lotof/bundler/gems/webpacker-a85a3ab0eac6/lib/webpacker/helper.rb:1:in `<top (required)>'
	from /Users/schovi/.rvm/gems/ruby-2.4.0@lotof/bundler/gems/webpacker-a85a3ab0eac6/lib/webpacker/railtie.rb:3:in `require'
	from /Users/schovi/.rvm/gems/ruby-2.4.0@lotof/bundler/gems/webpacker-a85a3ab0eac6/lib/webpacker/railtie.rb:3:in `<top (required)>'
	from /Users/schovi/work/lotof/config/application.rb:14:in `require'
```

This fixes it:
```ruby
module Webpacker
end
require 'webpacker/railtie'
```

but still `undefined method `javascript_pack_tag'`. Even when `require 'rails/al'` as default.

When I will have time, i will try to remove 3rd party gems one by one to find if there is conflict.

**Comment by gauravtiwari** [comment]
@schovi I see. It's `require 'rails/all'` actually. Perhaps, just a typo in comment.

**Comment by schovi** [comment]
@gauravtiwari just typo, sorry.

**Comment by lbrito1** [comment]
@schovi I am having the same issue, even after adding your snippet:

```
require_relative 'boot'

require 'yaml'
require 'rails/all'
module Webpacker
end
require 'webpacker/railtie'

Bundler.require(*Rails.groups)
```

Did you find a solution to this?

**Comment by schovi** [comment]
@lbrito1 it was not solution. It was just experimenting with custom requiring. Snippet from before was workaround https://github.com/rails/webpacker/issues/172#issuecomment-287304427

**Comment by modusss** [comment]
I have the same error here with rails 5.0.1 and what solved to you didn't change here...

**Comment by archonic** [comment]
I'm not sure why, but I found this problem was introduced when I included `gem 'jquery-rails'` and bundled.

**Comment by archonic** [comment]
A generated Rails 5.1.rc1 with `--webpacker` is working fine. I've updated a Rails 5.0 app and installed the webpacker gem. At one point it was working and I'm not sure what change broke the `javascript_pack_tag` method. I've compared the generated app to my own and found a few inconsistencies. Fixing those inconsistencies hasn't fixed it though.

Here's the repo: https://github.com/archonic/limestone. My eternal gratitude if you can find what the issue is.

**Comment by tylerhunt** [comment]
I ran into this issue, too, and in my app traced it to a `config.before_action` definition in the Active Admin initializer. I dug into it, and my best understanding of the issue is that this was causing `ActionController::Base` to be loaded prematurely, and this was somehow preventing the Webpacker helpers from being loaded properly (they were available under `ActionController::Base.helpers` but not in the views).

**Comment by schovi** [comment]
@tylerhunt I have ActiveAdmin ofcourse.

**Comment by kernow** [comment]
I've also run into this issue on rails 5.1.0.rc2 the project is using active admin but it doesn't use any `before_action` configuration. I've not had a change to look into what is causing this as yet and the work around fixes the issue for now. If I get a chance to look into this more deeply I'll report back here.

**Comment by gauravtiwari** [comment]
Please could you all try latest master - `bundle update webpacker`. This issue is now fixed 🎉  🍰

**Comment by archonic** [comment]
Fixed, thanks!

**Comment by sitrakary** [comment]
Don't forget to restart your server :trollface:

**Comment by F3PiX** [comment]
For prosperity: 
I got a message in the console that I had to update yarn (`yarn install`) and that fixed the error.
(Rails 5.2.2, webpacker 3.5.5)

**Comment by tyler-boyd** [comment]
I ran into a similar issue when adding webpacker `erb` support.

For me (and hopefully anyone reading this), the issue was caused by the js-style comment (as suggested earlier by another comment):
```js
// To reference this file, add <%= javascript_pack_tag 'application' %> to the appropriate
// layout file, like app/views/layouts/application.html.erb
```

The solution is to make sure there is no `<% ...` tags anywhere in the code, including JS comments.

**Comment by chrisdetmering** [comment]
I had this same problem. I just restarted my server and it worked.

**Comment by fakefarm** [comment]
I had to stop the server, then run `bin/spring stop` then `rails s`
Then, the `javascript_pack_tag` worked.
(Restarting the server wasn't sufficient.)

But what has me curious is that I didn't need to start `bin/webpack-dev-server` 
(I thought that was my problem originally) I am curious when, and where, that is needed.
