### ISSUE TITLE
How to handle Angular Routing inside Ruby On Rails using webpacker

### ISSUE THREAD

**Issue by dtanoira** [rails/webpacker#1725]
I need to setup rails rounting (routes.rb)  and angular routes in my application at the same time.
I create several angular modules, each one make different jobs that I need to execute via URLs I setup in a Menu. But when clicked, rails intercept them and fires an error ->  No route matches [GET] "/custorder/show/"or  No route matches [GET] "/custorder/new".
I need help, configuring rails and angular to work together managing routes. thanks

**Comment by ytbryan** [comment]
You should look into the two solutions suggested here https://github.com/rails/webpacker/issues/1361

Webpacker assumes you use Rails' view which requires Rails router. In a way, Angular is embedded as a component onto Rails' view. 

To use Angular router inside Rails router is a wrong direction. Hope I helped.

**Comment by guillaumebriday** [comment]
You can check this repo: https://github.com/guillaumebriday/rails-vue-cli#how-it-works

It's with Vue but the concept is the same with angular
