### ISSUE TITLE
Precompile fails with js.erb files on Heroku

### ISSUE THREAD

**Issue by renatodex** [rails/webpacker#173]
Hi guys,

I having some difficult trying to compile .js.erb files on Heroku

## Steps to reproduce

- git clone https://github.com/renatodex/webpacker-erb-heroku
- bundle install
- yarn install
- heroku buildpacks:set heroku/nodejs --index 1
- heroku buildpacks:set heroku/ruby --index 2
- git push heroku master

Anyone else have experience this issue?

][`s

**Comment by gauravtiwari** [comment]
@renatodex Do you got javascript `//` comment in that file? Please remove that since it's erb. I have made a demo for you here - https://tranquil-inlet-61365.herokuapp.com/ and code is here - https://github.com/gauravtiwari/webpacker-demo-app/blob/master/app/javascript/packs/hello_erb.js.erb

**Comment by gauravtiwari** [comment]
Feel free to close the issue if that is the problem 😄

**Comment by renatodex** [comment]
Hi @gauravtiwari 

I noticed that your repository has a few modifications compared to a virgin Rails App like in my example.
When installed Webpacker, i could verify that the Shared Webpack configuration file already provided erb support through babel-loader and rails-erb-loader.

I succeed to clone your repository and deploy to Heroku, but i still dont understand why my repository failed to precompile.

As you can see in Github, none of my erb files has comments, and i am using the default Webpack configuration with Rails 5.0.2.

Could you help me understand what is wrong?

][`s

**Comment by ytbryan** [comment]
Are you able to compile at localhost first? I compiled successfully after I did `./bin/yarn upgrade` followed by `rails webpacker:compile`

Because it seems to complain about webpack.js in node_modules

**Comment by gauravtiwari** [comment]
@renatodex I see. Found the problem and made a PR for you here - https://github.com/renatodex/webpacker-erb-heroku/pull/1

**Comment by gauravtiwari** [comment]
Feel free to close the issue @renatodex if the issue is fixed for you 👍

**Comment by renatodex** [comment]
@gauravtiwari 
Thanks for the PR man, i really forgot about the application thing.

@ytbryan
Hi Bryan, i manage to compile everything on Local using NODE_ENV and RAILS_ENV set to production, the problem was happening on Heroku Deploy.

I think whats really bad is that when Heroku deploys, there is no trace information on precompile.
On my real application, i had a compilation error on Ruby erb, so even with erb loader in place, the Precompile Task was failing without tracing the Ruby error.

I had to fork the Heroku Buildpack and disable the precompile, so i could log on bash and execute the Precompile manually to discover the error.

Also, had a problem with bashrc, because i forgot to declare my presets on that file.

The Rails Webpacker often evolves extra knowledges about how Babel, Webpacker Configuration and Node Environment works (and in my case, Heroku Deploy too).

After all, i could finally solve all Webpacker problems on my apps! Thanks!
Maybe we could build a FAQ with the more feasible problems and the solutions to each one.

][`s
