### ISSUE TITLE
'assets:precompile' does not install devDependencies 

### ISSUE THREAD

**Issue by paulgeisler** [rails/webpacker#1751]
What's the reason behind installing node modules only from 'dependencies' through the '--production' flag?
https://github.com/rails/webpacker/blob/227661b546701e107213aa9b6f83451bc89cf7d5/lib/tasks/webpacker/yarn_install.rake#L4

I do have some dependencies which are needed to build the app and are declared as 'devDependencies' (for example 'sass-resources-loader'). Another mate had to put all the testing clobber into 'dependencies' because the modules were missing in the test environment (after 'assets:precompile' ) which is semantically wrong.

It was really confusing and hard to find out because i've never experienced this routine for installing/building JS apps. There are always the 'yarn / npm install' commands in the instructions.

Usually there are a lot of transpilers in 'devDependencies' (babel, coffeescript, pug ...) so how does it work without them or should those be moved to 'dependencies'  🤔❓

It's not even analogue to Rails 5.1 `yarn:install`.
https://github.com/rails/rails/blob/v5.1.2/railties/lib/rails/tasks/yarn.rake#L4
`system("./bin/yarn install --no-progress")`

I would appreciate some clarification (and maybe a little lesson about dependencies declaration). 🙂

**Comment by gauravtiwari** [comment]
@paulgeisler Please see this issue: https://github.com/rails/webpacker/issues/160 and https://github.com/rails/webpacker/issues/117

Also see, https://yarnpkg.com/lang/en/docs/cli/install/#toc-yarn-install-production-true-false

We should probably remove the production flag but either way if `NODE_ENV` is set to production only the modules listed in dependencies section would be installed. So, please consider moving build modules to dependencies section.

**Comment by paulgeisler** [comment]
I see... Thanks! :)
