### ISSUE TITLE
Is there a way to reference a pack without appended GUID?

### ISSUE THREAD

**Issue by rally25rs** [rails/webpacker#1756]
With sprockets, if you had a file `assets/javascripts/application.js` then at runtime you could git it with a URL with or without the appended ID string:

```
http://localhost/assets/application.js
http://localhost/assets/application-03459dbb52d0ad491f9e.js
```

(either would work)

with Webpacker it seems that the pack can only be loaded with the appended ID
```
http://localhost/packs/application-03459dbb52d0ad491f9e.js
```

I need to be able to have a static url that doesn't change between builds (because external apps can link to it). Is there a way to make the URL
```
http://localhost/packs/application.js
```
work?

**Comment by guillaumebriday** [comment]
Related to this: https://github.com/rails/webpacker/issues/2048#issuecomment-679982364

Feel free to close the issue
