### ISSUE TITLE
Own SSL certificate breaks proxy

### ISSUE THREAD

**Issue by edwinv** [rails/webpacker#1758]
I'd like to use our own .dev SSL certificate for running the `webpack-dev-server`. The `devServer` configuration in webpack.yml mimics the [`devServer`](https://webpack.js.org/configuration/dev-server/) closely, therefore I assumed I can [add my own SSL certificates](https://webpack.js.org/configuration/dev-server/#devserver-https) in the YAML:

```
development:
  devServer:
    https:
      cert: |
        -----BEGIN CERTIFICATE-----
        ...
      key: |
        -----BEGIN PRIVATE KEY-----
        ...
```

`webpack-dev-server` will start with the correct SSL certificates. The only thing failing is the proxy middleware:

```
#<EOFError: end of file reached>
~/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/protocol.rb:189:in `rbuf_fill'
~/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/protocol.rb:157:in `readuntil'
~/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/protocol.rb:167:in `readline'
~/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/http/response.rb:40:in `read_status_line'
~/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/http/response.rb:29:in `read_new'
~/.rvm/gems/ruby-2.5.1/gems/rack-proxy-0.6.5/lib/net_http_hacked.rb:53:in `begin_request_hacked'
~/.rvm/gems/ruby-2.5.1/gems/rack-proxy-0.6.5/lib/rack/http_streaming_response.rb:60:in `response'
~/.rvm/gems/ruby-2.5.1/gems/rack-proxy-0.6.5/lib/rack/http_streaming_response.rb:29:in `headers'
~/.rvm/gems/ruby-2.5.1/gems/rack-proxy-0.6.5/lib/rack/proxy.rb:120:in `perform_request'
~/.rvm/gems/ruby-2.5.1/gems/webpacker-3.5.5/lib/webpacker/dev_server_proxy.rb:20:in `perform_request'
```

It seems like the proxy server is not detecting https anymore. Changing [dev_server.rb:42](https://github.com/rails/webpacker/blob/master/lib/webpacker/dev_server.rb#L42) to also be true when a Hash is given solves this issue.

I'm unsure if using our own SSL certificates is a feature Webpacker wants to support or if I have found a loophole. I found [another solution in another comment](https://github.com/rails/webpacker/issues/612#issuecomment-319930567), but I like the webpacker.yml approach more. What is the best approach to move forward?

**Comment by jakeNiemiec** [comment]
More discussion: https://github.com/rails/webpacker/issues/1752 & https://github.com/rails/webpacker/issues/822

**Comment by marisveide** [comment]
When this issue #2000 will get merged, this issue will also get solved.

**Comment by jipiboily** [comment]
FYI, @marisveide's solution actually works perfectly fine!

**Comment by guillaumebriday** [comment]
Can this issue be closed ?

**Comment by jipiboily** [comment]
If anyone like me was wondering if this was "fixed", there you go: https://github.com/rails/webpacker/pull/2595

It is currently only in master.

I am assuming it will get released soon-ish, but I might be wrong (I am not up to speed as to what is master...is it 6.0, or 5.2.x? -- the version file says it is [5.1.1](https://github.com/rails/webpacker/blob/master/lib/webpacker/version.rb) but it is unlikely to be that...?).
