### ISSUE TITLE
Api for reset loaders and entry

### ISSUE THREAD

**Issue by lanzhiheng** [rails/webpacker#1766]
I have check the source code about `enviroment.loaders` and `environment.entry`, we don't have the relevent api to reset them. 

By default webpacker will auto generate too much entry if I have some js files in `packs` directory

![image](https://user-images.githubusercontent.com/8858472/47334950-66fec080-d6bb-11e8-8d54-69c38705fcd1.png)

But in fact I just want to let `app.js`  as the entry file. So I need to remove all the entry before configing my `environment.js` file.

``` js
const { environment } = require('@rails/webpacker')
Object.keys(environment.entry.toObject()).forEach((key) => {
  environment.entry.delete(key)
})
``` 

 In addition, If I want to reset the loaders(because the default configuration are not very useful for me). I need to run below code 

``` js
environment.loaders.keys().forEach((key) => {
  environment.loaders.delete(key)
})
```

Can we provide the api to reset the `loaders` and `entry` object?  like that

``` js
environment.loaders.reset()
environment.entry.reset()
```

**Comment by guillaumebriday** [comment]
Is this issue still relevant? Feel free to reopen if needed
