### ISSUE TITLE
ERROR: directory is already being watched!

### ISSUE THREAD

**Issue by lauri865** [rails/webpacker#1780]
On the latest build (4.0.0-pre.3), I get the following error on OS X 10.14 (Mojave):

`** ERROR: directory is already being watched! **

        Directory: /Users/user/dev/userapp/node_modules/@rails/webpacker/node_modules/.bin/mini-css-extract-plugin

        is already being watched through: /Users/name/dev/app/node_modules/mini-css-extract-plugin

        MORE INFO: https://github.com/guard/listen/wiki/Duplicate-directory-errors
        ** ERROR: directory is already being watched! **

        Directory: /Users/name/dev/userapp/node_modules/@rails/webpacker/node_modules/.bin/file-loader

        is already being watched through: /Users/user/dev/userapp/node_modules/file-loader`

Can't seem to figure out the root cause of it – any ideas? Thanks!

**Comment by zernie** [comment]
@lauri865 that sounds like a rails bug

**Comment by yoshiakit** [comment]
I've had a similar situation and modifying the config.file_watcher (see below) works for me:

``` 
# /config/environments/development.rb
 config.file_watcher = ActiveSupport::FileUpdateChecker
```
