### ISSUE TITLE
Is there any advantage to use webpack-watcher over webpack-dev-server? 

### ISSUE THREAD

**Issue by ytbryan** [rails/webpacker#179]
Is there any advantage to use webpack-watcher over webpack-dev-server? 

Because it seems like webpack-dev-server uses webpack's watch mode by default? https://webpack.github.io/docs/tutorials/getting-started/#watch-mode

**Comment by gauravtiwari** [comment]
@ytbryan Both are different - https://github.com/rails/webpacker/blob/master/lib/install/bin/webpack-dev-server.tt
https://github.com/rails/webpacker/blob/master/lib/install/bin/webpack-watcher.tt

`webpack-dev-server` uses https://webpack.js.org/configuration/dev-server/ whereas the watch mode is essentially webpack binary running in watch mode so, it's watching for changes and then compiling on demand. 

You can read more about use cases of `webpack-dev-server` in that link. It serves from memory so, usually faster than any other build modes webpack provides.
