### ISSUE TITLE
I want reuse my styles in vue component with sprite compass features

### ISSUE THREAD

**Issue by sunnmas** [rails/webpacker#1791]
The first component of the vue, screwed to an existing rails application. Faced many problems, here is another of them. You must write component styles in the Sass style language, using variables and mixins from the style files used in the application that are not related to webpacker. And it seems that the import of such a file does not cause any problems, except for the use of sprites. Compass rails I use gem "compass-rails, '3.1.0'. This gives me the right to write understandable for SProckets import: @import 'compass/reset' and others available in this gem. But webpacker does not understand this construction:
Module build error:
@import 'compass / reset'
^
File to import not found or not readable: compass / reset

**Comment by danielpowell4** [comment]
is there a related npm package you can install via your package.json file?

Seems like you are trying to import code from a gem instead, which is not supported.

Otherwise, there should be a way to provide a more specific import to the precise file you are wanting to bring in

**Comment by guillaumebriday** [comment]
Is this issue still relevant ?

Feel free to close it if not
