### ISSUE TITLE
Only load parts of the packs/multiple pages

### ISSUE THREAD

**Issue by HansWurst90** [rails/webpacker#1794]
Hi,

I am currently moving a project from using the conventional asset-pipeline with babel to webpacker.
I already moved all components that used to be in our `/app/verstehe/app/assets/javascripts/es6` folder to `/app/verstehe/app/javascript/packs`.

With the old pipeline we had different application.js files for different layouts or use cases (e.g. application.mobile.js or application.embed.js). when included in the right layouts they would take care of loading the right es6 components.

After a lot of searching I am still not sure how I would implement a way of "selective" loading of component in webpacker to make it work in a similar way.

I want to differentiate between multiple ways of only loading a part of the packs instead all of them always.

I am sorry if this is not the rigth place to ask. Please let me know where I can ask instead.

Thanks in advance!

**Comment by renchap** [comment]
`assets/javascript/packs` should only contain your entrypoints.
For each file in this directory Webpack will create a file that you can import in your view using `javascript_pack_tag`.

So you can achieve what you want by creating multiple entrypoints in your `packs` directory and including only the ones you need on a page. The best practice here is to use 1 pack per page (or type of page), and then leverage Webpack's code splitting to split the common code into separate files.

**Comment by HansWurst90** [comment]
thanks @renchap for the quick response.

I started to suspect that the components did not belong in there.
Would I just create a new directory in `/app/verstehe/app/javascript` for my components and import them in the `application.js`?

Do you have an example for this and the code splitting?

I keep finding examples for webpack but it seems to work a little different in webpacker.

**Comment by renchap** [comment]
Yes, you could for example use `/app/verstehe/assets/javascripts/components/my_component.jsx`

In `packs/application.js` you can then do something like:
```es6
import Component from "components/my_component.jsx"
```

For webpacker 3 (based on Webpack 3) you have a basic config here: https://github.com/rails/webpacker/blob/master/docs/webpack.md#add-common-chunks
You can adapt it using the Webpack 3 docs.

For Webpacker 4 (currently in beta, based on Webpack 4), you can add something like this in your `environment.js`:
```
environment.config.optimization.splitChunks = { chunks: 'all' }
```
You will find a more detailed explanation here: https://webpack.js.org/guides/code-splitting/ & https://medium.com/webpack/webpack-4-code-splitting-chunk-graph-and-the-splitchunks-optimization-be739a861366

This will allow webpack to extract the code common between multiple packs into a separate file, so it can be cached on the client and used by both entrypoints.

**Comment by guillaumebriday** [comment]
I think this issue is not relevant anymore I guess

Can this issue be closed ?
