### ISSUE TITLE
Webpacker fails to compile in dev

### ISSUE THREAD

**Issue by alik78** [rails/webpacker#1799]
I've seen a number of related issues when deploying application to prod but mine happens in dev. I am just getting started with a react project on ruby on rails and here I am :( 

I am missing `.bin/webpack` under `node_modules`
Not sure how and when this file is generated...

This is from `development.log` :
>[Webpacker] Compiling…
[Webpacker] Compilation failed:
/home/alik/.rvm/gems/ruby-2.5.1@sandbox/gems/webpacker-3.5.5/lib/webpacker/webpack_runner.rb:11:in `exec': No such file or directory - /home/alik/RubyProjects/sandbox/node_modules/.bin/webpack (Errno::ENOENT)
        from /home/alik/.rvm/gems/ruby-2.5.1@sandbox/gems/webpacker-3.5.5/lib/webpacker/webpack_runner.rb:11:in `block in run'
        from /home/alik/.rvm/gems/ruby-2.5.1@sandbox/gems/webpacker-3.5.5/lib/webpacker/webpack_runner.rb:10:in `chdir'
        from /home/alik/.rvm/gems/ruby-2.5.1@sandbox/gems/webpacker-3.5.5/lib/webpacker/webpack_runner.rb:10:in `run'
        from /home/alik/.rvm/gems/ruby-2.5.1@sandbox/gems/webpacker-3.5.5/lib/webpacker/runner.rb:6:in `run'
        from ./bin/webpack:15:in `<main>'

Completed 500 Internal Server Error in 813ms (ActiveRecord: 17.7ms)

>Webpacker::Manifest::MissingEntryError - Webpacker can't find application.js in /home/alik/RubyProjects/sandbox/public/packs/manifest.json. Possible causes:
>1. You want to set webpacker.yml value of compile to true for your environment
   unless you are using the `webpack -w` or the webpack-dev-server.
>2. webpack has not yet re-run to reflect updates.
>3. You have misconfigured Webpacker's config/webpacker.yml file.
>4. Your webpack configuration is not creating a manifest.
>Your manifest contains:
>{
>}

Additional info
- I have **node_modules** folder but it has just .yarn-integrity file in it
- I've ran `yarn install`
- I've ran `rails webpack:install`

`sandbox$ rails -v`
`Rails 5.2.1`

`sandbox$ yarn --verison`
`yarn install v1.12.3`
`[1/4] Resolving packages...`
`success Already up-to-date.`
`Done in 0.07s.`

`sandbox$ gem list | grep webpacker`
`webpacker (3.5.5)`

Any help is greatly appreciated!!!!! Thanks!!!

**Comment by jchiefelk** [comment]
+1

**Comment by sandergroen** [comment]
@alik78 did you do rails webpack:install OR rails webpacker:install. The later is the correct one. I think it should install all node dependencies.

**Comment by MrHubble** [comment]
@alik78 did you solve this problem? If yes, could you please share how you solved it?

**Comment by alik78** [comment]
> @alik78 did you solve this problem? If yes, could you please share how you solved it?

Since I was more or less starting from scratch I've ended up following this tutorial for setting up the environment: https://cognitiveclass.ai/blog/react-on-rails-tutorial-integrating-react-and-ruby-on-rails/
What problem are you having and how does your setup look like?

**Comment by MrHubble** [comment]
@alik78 thanks for taking the time to response. 

I was just trying to install `webpacker` on a Rails 5.2 app that had been upgraded from earlier Rails versions. I couldn't get `webpack-dev-server` running because the packages weren't being installed in the `node_modules` folder. 

After deleting a number of files (including `yarn.lock` that was being created in a directory above the intended directory ie `/Users/me/`), and running `rails app:update:bin` I was finally able to fix my problem. I'm unsure of the exact cause and exact fix but I no longer experience the problem.

Should we close this issue seeing as we both don't have the problem any more?

**Comment by alik78** [comment]
Yes, this can be closed. Looks like a dependency issue. I wish the error message was more meaningful but this is not a bug

**Comment by Siva-Ganesh-VR** [comment]
This may help anyone in the future

https://stackoverflow.com/questions/58506351/webpacker-throws-application-css-not-found-in-manifest-json-in-rails-6-applica

**Comment by robbiesoho** [comment]
Hello, Noob here, but I had this same issue and this worked for me...

in the terminal run

yarn add @rails/webpacker
bundle update webpacker

from:
https://github.com/rails/webpacker/issues/1494
