### ISSUE TITLE
Foreman Webpacker environment variables not working

### ISSUE THREAD

**Issue by biznickman** [rails/webpacker#1800]
I went through all of the steps outlined in the [Environment Variables document](https://github.com/rails/webpacker/blob/master/docs/env.md) but none of the steps worked for me. Every time I load the app it doesn't show the environment variables in `process.env`. However if I type `rails console` or run console via Foreman and `puts ENV` the environment variables from the `.env` file show up.

I tried all the strategies outlined in that doc and none of them worked.

I'm using:
* foreman - 0.85.0
* rails - 5.2.1

**Comment by biznickman** [comment]
FYI for anybody who lands on this page...

I identified the issue was that I wasn't using puma in my procfile. Once I switched that over everything worked properly.

**Comment by stoplion** [comment]
Puma is required to make this work? 🤔
