### ISSUE TITLE
Support for node-sass version that is compatible with node v11

### ISSUE THREAD

**Issue by mayordwells** [rails/webpacker#1807]
We upgraded our node version to 11 and our rails + webpacker project stopped compiling afterward. 
So we had to downgrade back to node 10 because the version of node-sass that is currently supported in webpacker is not compatitle node 11. 

Can we please upgrade to the version of node-sass that supports node 11? - https://www.npmjs.com/package/node-sass (v4.10.0)

Here's the version of node-sass that supports node 11 - https://github.com/sass/node-sass/issues/2521

Here's the version of node-sass in our project 

```
// copied from yarn.lock file
node-sass@^4.9.3:
  version "4.9.4"
  resolved 
```

Our project is running on - `"@rails/webpacker": "^4.0.0-pre.3",`

**Comment by jawad-aziz-farhad** [comment]
having the same issue.

**Comment by mayordwells** [comment]
@jawad-aziz-farhad add this ` "node-sass": "4.9.3",` to your package.json file to override the upgraded version. Then you might need to downgrade back to node 10.

I didn't test the latest version of node-sass and node using this approach.

**Comment by gauravtiwari** [comment]
@mayordwells Please use the latest RC.
