### ISSUE TITLE
How to setup Hot Module Reloading for Vue?

### ISSUE THREAD

**Issue by domi91c** [rails/webpacker#1811]
I've been unsuccessful in getting HMR to work with the default Webpacker + Vue setup, and haven't been able to find any instructions. Is there any extra code that I need to use to get this to work?

**Comment by ytbryan** [comment]
did you run webpack-dev-server at a separate terminal? 

Open a separate terminal and run `./bin/webpack-dev-server`

**Comment by domi91c** [comment]
Yes I did, and tried many different options. I should have mentioned, I get full page reloads instead of the regular HMR functionality.

**Comment by seuros** [comment]
Then HMR is working. If your coding don't support hot reloading, webpack will restart the whole page.

**Comment by domi91c** [comment]
Sorry for the delay. The code is literally the default Vue install from Webpacker.

**Comment by gauravtiwari** [comment]
Closing, since this isn't an issue with Webpacker. Please try asking on SO :)
