### ISSUE TITLE
Backports to v3 welcome?

### ISSUE THREAD

**Issue by jaredbeck** [rails/webpacker#1812]
Just a quick question, are backports to v3 welcome? If so, I would like to backport:

- https://github.com/rails/webpacker/pull/1644 - Fixes Browserslist 2 warning
- https://github.com/rails/webpacker/pull/1528 - Fixes "postcss-cssnext has been deprecated" warning

If backports are *not* welcome, what is the ETA on v4? 

Thanks for all your work bringing react to rails.

**Comment by gauravtiwari** [comment]
Please feel free, but v4 is coming up soon (this weekend)
