### ISSUE TITLE
Asset file contents

### ISSUE THREAD

**Issue by denissellu** [rails/webpacker#1813]
Hello

I'm not 100% if this is an issue for this repo.

When using asset pipe line with sprockets you can call this command
`Rails.application.assets.find_asset(filename).source` 
 to return the contents of the file. If for example this was an SVG you would get 
`<svg xmlns=\"http://www.w3.org/2000/svg\" version=\"1.1\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" preserveAspectRatio=\"none\".....`

Is there a method avaliable within webpacker to do this? Or is this even something Webpacker should do?

cheers

**Comment by jakeNiemiec** [comment]
This may be what you are looking for: https://github.com/rails/webpacker/blob/5476dbbf0df65d7de7a2a412b887cbcd5f298efb/docs/assets.md#link-in-your-rails-views

There is also a newer lookup method in case that's what you needed: https://github.com/rails/webpacker/blob/25768b0525f61c044c51216be45801d08685f650/CHANGELOG.md#added-5

**Comment by denissellu** [comment]
Thanks for that, 

That lookup method is great at verifing that the asset exists within Webpack, but what i'm looking for is the `#source` method that is avaliable in [sprockets](https://github.com/rails/sprockets/blob/0cb3314368f9f9e84343ebedcc09c7137e920bc4/lib/sprockets/asset.rb#L92) and it is mostly calling `File.binread`

**Comment by renatodeleao** [comment]
@jakeNiemiec that is really helpful, thanks! 

Was having an issue for while migrating an old code base with  [`controller/action` based scripts](https://stackoverflow.com/questions/23654254/loading-javascript-per-controller-in-rails) that are now packs and might not exist.

Need to add webpacker folder (`frontend`) to rails asset lookup, and then `Rails.application.assets.find_asset(filename).nil?`. 

I didn't know about those `Webpacker.manifest.lookup` or `Webpacker.manifest.lookup_pack_with_chunks` methods. I can't seem to find them in the `docs`. Any reason why?

Thanks for your time!
