### ISSUE TITLE
css module, how to import

### ISSUE THREAD

**Issue by xero88** [rails/webpacker#1814]
This is a nightmare.

How to add css from lib (like bootstrap)

This : 

> import "react-datepicker/dist/react-datepicker-cssmodules.css";

is not working ! Nothing in the documentation to help

I just want to do this : https://webpack.js.org/loaders/css-loader/#css-modules

**Comment by charlesvallieres** [comment]
I don't think this is an issue with webpacker. Have you tried with a ~ in front like mentioned in the documentation page you linked https://webpack.js.org/loaders/css-loader/#import

> To import styles from a node_modules path (include resolve.modules) and for alias, prefix it with a ~

```
import "~react-datepicker/dist/react-datepicker-cssmodules.css";
```

**Comment by guillaumebriday** [comment]
Can this issue be closed ?

**Comment by ndnenkov** [comment]
I had an issue where it worked in dev, but not in other environments. I had to add
```
@import 'react-datepicker/dist/react-datepicker';
```

To `application.scss` rather the inline import.
