### ISSUE TITLE
Cannot load fonts from npm package

### ISSUE THREAD

**Issue by openscript** [rails/webpacker#1817]
Dear community

I'm struggling with this for quite a while. I want to load the font Roboto from [`roboto-fontface`](https://www.npmjs.com/package/roboto-fontface). I have `fonts.scss` file in my packs folder, where I try to load this font with `@import '~roboto-fontface/css/roboto/sass/roboto-fontface-medium';`. This scss file I load from my TypeScript app (which works like a charm) with 
`import './fonts.scss';`. Unfortunately it doesn't look up the correct path.

I'm on `webpacker (3.5.5)` and `rails (5.2.1.1)`.

```
ERROR in ./node_modules/css-loader??ref--2-1!./node_modules/postcss-loader/lib??ref--2-2!./node_modules/resolve-url-loader!./node_modules/sass-loader/lib/loader.js??ref--2-4!./app/javascript/packs/fonts.scss
Module not found: Error: Can't resolve '../../../fonts/roboto/Roboto-Medium.woff2' in '/home/user/workspace/project/app/javascript/packs'
resolve '../../../fonts/roboto/Roboto-Medium.woff2' in '/home/user/workspace/project/app/javascript/packs'
  using description file: /home/user/workspace/project/package.json (relative path: ./app/javascript/packs)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /home/user/workspace/project/package.json (relative path: ./app/javascript/packs)
    using description file: /home/user/workspace/project/package.json (relative path: ./fonts/roboto/Roboto-Medium.woff2)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /home/user/workspace/project/fonts/roboto/Roboto-Medium.woff2 doesn't exist
      .tsx
        Field 'browser' doesn't contain a valid alias configuration
        /home/user/workspace/project/fonts/roboto/Roboto-Medium.woff2.tsx doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        /home/user/workspace/project/fonts/roboto/Roboto-Medium.woff2.ts doesn't exist
      .jsx
        Field 'browser' doesn't contain a valid alias configuration
        /home/user/workspace/project/fonts/roboto/Roboto-Medium.woff2.jsx doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /home/user/workspace/project/fonts/roboto/Roboto-Medium.woff2.js doesn't exist
      .sass
        Field 'browser' doesn't contain a valid alias configuration
        /home/user/workspace/project/fonts/roboto/Roboto-Medium.woff2.sass doesn't exist
      .scss
        Field 'browser' doesn't contain a valid alias configuration
        /home/user/workspace/project/fonts/roboto/Roboto-Medium.woff2.scss doesn't exist
```

I'm using the `resolve-url-loader` like this in my `environment.js`:

```
environment.loaders.get('sass').use.splice(-1, 0, {
    loader: 'resolve-url-loader'
});
```

I want to be able to embed the fonts or load them from the public folder. How can I do that?

Loading the fonts from Google directly is not possible for this project.

Any help is appreciated.

**Comment by jakeNiemiec** [comment]
This is highly dependant on how your `stuff` is organized. Could you post the sass where you import the font?

You probably need [`url-loader`](https://github.com/webpack-contrib/url-loader) or [`file-loader`](https://github.com/webpack-contrib/file-loader)

[`resolve-url-loader`](https://www.npmjs.com/package/resolve-url-loader#how-it-works) seems to have a very specific use.

**Comment by openscript** [comment]
The fonts are loaded through a mixin, which doesn't seem to work with `resolve-url-loader` as expected:

> Where url() statements are created in a mixin the source file may then be the mixin file, and not the file calling the mixin. Obviously this is not the desired behaviour.

see [resolve-url-loader README.md](https://www.npmjs.com/package/resolve-url-loader#limitations--known-issues)

I still looking for a way to get it to work in production. I would love to embed the fonts with base64 blobs in my js file, as I'm creating an offline app the service worker will be able to download everything at once.

**Comment by jakeNiemiec** [comment]
>The error is, that webpacker or webpack isn't searching within the roboto-fontface package for the fonts.

Watch out for a`loader`/`rule`/`plugin` with: `exclude: [/node_modules/],`. This is generally good to do, but for your specific case, it could break the way that `roboto-fontface`[ is loading the package](https://github.com/choffmeister/roboto-fontface-bower/blob/master/css/mixins.scss#L9).

If you use [`file-loader`](https://github.com/webpack-contrib/file-loader#getting-started), it would yank the file from anywhere its referenced and **make it available in your public directory along with the rest of your webpack output**. This works for everything from css background images to font svgs:
![image](https://user-images.githubusercontent.com/16782063/49301001-37e12900-f489-11e8-84f6-f25c5075d312.png)

> I would love to embed the fonts with base64 blobs in my js file, as I'm creating an offline app the service worker will be able to download everything at once.

If you use the above approach, **this will allow the browser to cache the fonts for offline use**. If you do go the base64 route, you may consider reading this ongoing [`resolve-url-loader`](https://github.com/bholloway/resolve-url-loader/issues/107#issuecomment-432785763) issue.

**Comment by openscript** [comment]
> Watch out for aloader/rule/plugin with: exclude: [/node_modules/],. This is generally good to do, but for your specific case, it could break the way that roboto-fontface is loading the package.

I've checked that. The `node_modules` is not excluded. 

I've

**Comment by openscript** [comment]
I think I finally nailed it!

I've removed the `extract-text-webpack-plugin` from the `sass` loader configuration with `environment.loaders.get('sass').use.shift();` in my `environment.js`. It seems like this plugin removes all `@font-face` declarations.

**Comment by jakeNiemiec** [comment]
The following may work better (assuming that you have a loader that can convert this):
```SCSS
@font-face {
  font-family: 'Roboto-Medium';
  src: url('~roboto-fontface/fonts/roboto/Roboto-Medium.woff2') format('woff2'), url('~roboto-fontface/fonts/roboto/Roboto-Medium.woff') format('woff');
}
```

...but, I personally would recommend stashing your fonts in your public directory:
```SCSS
@font-face {
  font-family: 'Roboto-Medium';
  src: url('/fonts/roboto/Roboto-Medium.woff2') format('woff2'), url('/fonts/roboto/Roboto-Medium.woff') format('woff');
}
```
(we do it this way so our fonts remain static, free from the webpack cache-busting/fingerprinting the files)

**Comment by openscript** [comment]
@jakeNiemiec You are right, this is cleaner, but I like the convenience of a NPM package.

**Comment by openscript** [comment]
I've just migrated to `webpacker 4.0.0.rc.1`. With this version it works out of the box!
