### ISSUE TITLE
Compiling in production fails silently and isn't verbose enough

### ISSUE THREAD

**Issue by ameft** [rails/webpacker#1824]
I have a Rails 5.2 app with Webpacker 4.0.0.pre.3 with runs smoothly in development and instead couldn't compile in production: `[Webpacker] Compiling…` just hanged there for hours (locally and on Heroku, where @schneems helped me a lot), in a similar way as described in #1534, #1217 and #1003.
After many hours of testing and research I found out that the problem was that two dependencies in `package.json` (@fortawesome/fontawesome-free and expose-loader) were in `devDependencies` instead of `dependencies`, that made compiling failing silently.
Running this command put me on the right path to find the solution, giving me some hits of errors `NODE_ENV=production ./bin/webpack --progress --config config/webpack/production.js`.
Problem is that instad running `RAILS_ENV=production NODE_ENV=production bundle exec rails assets:compile` didn't give me any indication of errors, and I don't know why but shouldn't be the case.
What do you think?

**Comment by jakeNiemiec** [comment]
[FontAwesome did a writeup on this known issue](https://fontawesome.com/how-to-use/with-the-api/other/tree-shaking#issues). Issue https://github.com/terser-js/terser/issues/50

There is also a webpacker PR to fix this https://github.com/rails/webpacker/issues/1719

**Comment by jakeNiemiec** [comment]
It's not that Webpacker is erroring out, uglify is incorrectly trying to minify all of the FA glyphs & exports. In other words, it's trying to do an impossible amount of work (memory & cpu wise). This is an issue that is just as hard to diagnose with vanilla webpack.

**Comment by ameft** [comment]
@jakeNiemiec are you sure that that is what it's happening? Why moving the libraries from `devDependencies` to `dependencies` should fix that? Compiling with `./bin/webpack` was giving me errors, but Webpacker didn't.

**Comment by jakeNiemiec** [comment]
@ameft Sorry, my mistake, I conflated some of the issues you pointed to with what you were saying. Now my understanding is: FA was in `devDeps` when it needed to be in `deps` and webpacker did not alert you to this error.

It looks like webpacker is configured correctly to display errors:
https://webpack.js.org/configuration/stats/#stats
https://github.com/rails/webpacker/blob/8d496a0b871085648d6ee21c0e1e469d11cfe593/package/environments/production.js#L34
https://github.com/rails/webpacker/blob/227661b546701e107213aa9b6f83451bc89cf7d5/package/environments/development.js#L43

You should also be able to pass custom settings to ensure errors are being displayed. Here is what I am currently using:
```js
  stats: {
    errors: true,
    errorDetails: true,
    colors: true,
    optimizationBailout: true
  }
```

**Comment by ameft** [comment]
I'll try the stats config and to revert the fix to see if the errors are displayed, thank you @jakeNiemiec!

**Comment by gauravtiwari** [comment]
@jakeNiemiec I think the issue here is `Open3` is hanging for some reason when there is error returned from the shell command. I am looking into alternatives but if someone has ideas feel free to make a PR.

**Comment by schneems** [comment]
A thing I've had to recommend fairly frequently is to manually run `./bin/webpack --progress`.

Can we make this the default output mode of webpacker? Any other documentation or tips on debugging hung or really slow compiles is appreciated.

**Comment by jakeNiemiec** [comment]
@schneems If you also add `--profile`, [this will give you some insight into where the bottlenecks are](https://webpack.js.org/api/cli/#profiling):
![image](https://user-images.githubusercontent.com/16782063/49403330-18106600-f712-11e8-9ac6-57870481ade5.png)

We use a progress plugin that does this on every build, here is one that a lot of `(react/vue/angular)-cli` libraries use:  https://www.npmjs.com/package/simple-progress-webpack-plugin#minimal
![image](https://raw.githubusercontent.com/dominique-mueller/simple-progress-webpack-plugin/HEAD/docs/compact-logger-preview.gif?raw=true)

**Comment by acrewdson** [comment]
+1 to what @schneems said above with respect to making `--progress` the webpacker default

**Comment by masato-hi** [comment]
I do not know about that no error output will occur, but this is maybe related #2143

**Comment by rossta** [comment]
@ameft Can this issue be closed and , if so, could you close it? Thank you!

**Comment by ameft** [comment]
@rossta I can of course close the issues, but it's not entirely clear to me if now webpacker behaves differently if it encounter certain errors during compiling. I didn't had any more issue on my part but I don't know if the original issue is actually addressed or maybe it's not a real issue to begin with...

**Comment by rossta** [comment]
@ameft Ah, thanks for pointing that out. 

It's my understanding that Webpacker suppressed the compilation output in the version associated with this issue (Webpacker 4.0.0.pre.3 from the description). 

Since 4.1.0 with this PR https://github.com/rails/webpacker/pull/2224, Webpacker will now print the compilation output to STDOUT by default though this behavior can be disabled in webpacker.yml https://github.com/rails/webpacker/blob/ac93e129ee10c89b0d56705203c026b1f58cd38d/lib/install/config/webpacker.yml#L9.

**Comment by ameft** [comment]
@rossta amazing thanks! Issue closed :)
