### ISSUE TITLE
Hello World for Typescript does not work

### ISSUE THREAD

**Issue by zdrummond** [rails/webpacker#1828]
Note: I am very new to Webpacker AND Typescript. So this is likely a problem with user.. however there is so little steps I am not sure what I messed up. 

I got Webpacker running with React. Easy peasy. 

Then I moved to following the [easy steps](https://github.com/rails/webpacker/blob/master/docs/typescript.md#typescript-with-react) written up to add Typescript. 

```
bundle exec rails webpacker:install:typescript
yarn add @types/react @types/react-dom
```

However, the `hello_typescript.ts` that is generated from the above is does not use typescript and is also uninteresting as it's just a console out. 

So then I went to the quick start at [MS's site](https://github.com/Microsoft/TypeScript-React-Starter#typescript-react-starter). That had a much more interesting example, so I copied that in. 

```
import * as React from 'react';

export interface Props {
  name: string;
  enthusiasmLevel?: number;
}

function Hello({ name, enthusiasmLevel = 1 }: Props) {
  if (enthusiasmLevel <= 0) {
    throw new Error('You could be a little more enthusiastic. :D');
  }

  return (
    <div className="hello">
      <div className="greeting">
        Hello {name + getExclamationMarks(enthusiasmLevel)}
      </div>
    </div>
  );
}

export default Hello;

// helpers

function getExclamationMarks(numChars: number) {
  return Array(numChars + 1).join('!');
}
```

However, when I copy that in, and try to render the pack, I get a bunch of errors around parsing the JSX like

```
ERROR in ./app/javascript/packs/hello_typescript.ts
[tsl] ERROR in /app/javascript/packs/hello_typescript.ts(17,10)
      TS1005: '>' expected.

ERROR in ./app/javascript/packs/hello_typescript.ts
[tsl] ERROR in /app/javascript/packs/hello_typescript.ts(17,19)
      TS1005: ')' expected.
```

which ends up with;

```
ERROR in ./app/javascript/packs/hello_typescript.ts
Module parse failed: Unterminated regular expression (15:5)
You may need an appropriate loader to handle this file type.
|         name + getExclamationMarks(enthusiasmLevel);
|     }
|     /div>
|         < /div>;
|     ;
```

So, it seems like I have TS, but not the ability to Render React in Typescript? Any ideas?

**Comment by HardieBoeve** [comment]
Did you tried renaming the file to .tsx?

**Comment by zdrummond** [comment]
💥 That was it. 

I didn't expect that, since the rest of my React code, even with JSX, ends with `.js`
