### ISSUE TITLE
Turn off live code reloading

### ISSUE THREAD

**Issue by gnapse** [rails/webpacker#1829]
From the README

> If you want to use live code reloading, or you have enough JavaScript that on-demand compilation is too slow, you'll need to run ./bin/webpack-dev-server or ruby ./bin/webpack-dev-server.

What if I want this option for the second reason stated above (I have enough JavaScript that on-demand compilation is too slow) but I do not want live code reloading? Is there a way to turn it off? I tried to find about it in the documentation but did not find it.

**Comment by jakeNiemiec** [comment]
I think the option to do this while running the dev server was removed: https://github.com/rails/webpacker/issues/724

[But, it looks like you could just use this instead of spinning up the dev server](https://github.com/rails/webpacker#development): 
```bash
# watcher
./bin/webpack --watch --colors --progress

# standalone build
./bin/webpack
```

**Comment by gnapse** [comment]
But isn't it the server the only option that will stop on-demand compilation? I recall that with the command above on-demand compilation still occurred. Will try again to confirm or deny.

**Comment by jakeNiemiec** [comment]
Did you try `compile: false` in your `webpacker.yml`?

https://github.com/rails/webpacker/blob/aefdf302cf178927147e74425d517688d3fe1434/README.md#L225

**Comment by gauravtiwari** [comment]
Thanks @jakeNiemiec 

As suggested, please use watcher if you don't want dev server:

```
# watcher
./bin/webpack --watch --colors --progress

```

**Comment by gnapse** [comment]
Thanks! The `compile: false` was all I needed, since I was still using the watcher command, but the rails server was also compiling on its own.
