### ISSUE TITLE
[4.0.0-rc.1] Javascript_asset_tag is broken

### ISSUE THREAD

**Issue by Zyphrax** [rails/webpacker#1835]
I've upgraded from `4.0.0-pre.3` to `4.0.0-rc.1` and now I get a really strange error in my application.slim:

> Sprockets::Rails::Helper::AssetNotFound at /
> The asset "{\"src\"=>\"/packs/vendor-4699109b154b54e1ef4e.js\", 
> \"integrity\"=>\"sha256-hkCqb1IPUS4z7o4PyMRG7t3+J0U2MgbmVUty9/hviU0= sha384-
> En5fK1fCL66RKx2Ovx8/n6AEwom4R6OgFxxNvKdrL6nQYow56QN66K0CE0N1c2z/ sha512-
> nTC02x/4ytkiw9of3MH55Xm4KkZaaGnbEkqBJ+OeToZmQH+fYrasEosB95s+bvNKQ6tjtcEIe
> zHJE8aHCyDqSw==\"}.js" is not present in the asset pipeline.

This errors seems to be caused by this call in my project:

_app/views/layout/application.slim_
```slim
= javascript_pack_tag 'vendor'
```

It seems that `javascript_pack_tag` generates a hash and is incorrectly converted to a Rails include tag. It seems to think that the hash is the `src`.

----
**Edit: It might have something to do with my splitChunks configuration**
This was working fine in `4.0.0-pre.3`, but now something goes wrong in [manifest.rb - lookup](https://github.com/rails/webpacker/blob/3aa4a5dc517106935b3d6f45aa82f4707a5de217/lib/webpacker/manifest.rb#L21).

```javascript
environment.config.merge({
  optimization: {
    splitChunks: {
      cacheGroups: {
        commons: {
          test: /\/node_modules\//,
          name: 'vendor',
          chunks: 'all'
        }
      }
    }
  }
});
```

Configurations with `cacheGroups` no longer work?

**Comment by gauravtiwari** [comment]
Made a new release, please give it a try 🙏

**Comment by gauravtiwari** [comment]
great, thanks @seuros

**Comment by Zyphrax** [comment]
Thanks @gauravtiwari !

Unfortunately there is something not right yet.

I use the following packs:
- `platform.ts`:  for things like Rollbar that I want to be loaded early on in my page
- `vendor.ts`:  for the third party libraries, basically anything from node_modules
- `tenant.ts`:  for the actual app logic

I include `platform.ts` near the top and a bit further down `tenant.ts` in my slim file:
```slim
= javascript_pack_tag 'platform'
...    
= javascript_pack_tag 'tenant', defer: true
```
In version `4.0.0-pre.3` I had to include `vendor` manually with a `javascript_pack_tag`, but version `4.0.0-rc.*` seems to takes care of this automatically.

The problem is that in the final HTML the `vendor` script file is included multiple times:

```html
<script src="/packs/vendor-c74fedd1b41bbb546647.chunk.js"></script>
<script src="/packs/platform-75df7bfe6d1333d19e71.js"></script>
...
<script src="/packs/vendor-c74fedd1b41bbb546647.chunk.js" defer="defer"></script>
<script src="/packs/tenant-218fa49335d9af3f1b19.js" defer="defer"></script>
```

It probably detects the dependency of both `platform` and `tenant` on the `vendor` pack.

**Comment by gauravtiwari** [comment]
@Zyphrax Thanks, I noticed the problem. I didn't realize this might have implications on `cacheGroups` but it seems it's being bundled together with the entry points, which sort of makes sense since it's a dependency like you said. 

The idea with this was to include in runtime chunks so you don't have to especially include them or add an option, which one might easily forget. Perhaps, we only check for runtime chunks and include them and leave the rest out so you can include them manually?

**Comment by renchap** [comment]
Could a simple solution here be to store the list of non-entry point javascript files that have been loaded, and skip adding the `<script>` if it is already done?

If the case above, this would add the `vendor` pack once (before platform), and skip it when including `tenant`.

**Comment by gauravtiwari** [comment]
@renchap Yep, it's possible but I think it's best to exclude anything that's not related to a pack and one can include that manually, for ex: vendor can be included anywhere, under the `<head />`or `<body>`. 

Wrote a fix, will make a PR in a bit.

**Comment by gauravtiwari** [comment]
I am going to take a look at this properly tomorrow if anyone has ideas feel free to make a PR.

**Comment by renchap** [comment]
I am not sure why you do not want to do it automatically, this could make it much easier for people. Or maybe with a setting to disable this behaviour?

**Comment by gauravtiwari** [comment]
Mainly, just to make things easier if it's a runtime chunk. It's quite easy to forget one if people are using `splitChunks` and forget to include runtime chunk above the main chunk. That's why felt it might be better to include it but didn't realize this might have implications.

**Comment by renchap** [comment]
I agree that it is a good idea to automatically include dependent packs, and my proposal is to only add something so a dependent pack only get included once per page. With an optional setting to disable this automatic behaviour if people want to do it manually for whatever reason.

**Comment by somebody32** [comment]
I would +1 on what @Zyphrax said, automatic dependency inclusion could avoid a lot of headaches, knowing that webpack changes extracted chunks name often (if not overridden) and have different settings for `splitChunks` for development and production. The later caused for us broken pages sometimes because of missing files in prod while being totally present in dev. (4.0.0-pre + splitChunks activated)

**Comment by jakeNiemiec** [comment]
RE: https://github.com/rails/webpacker/issues/1835#issuecomment-447615232, @Zyphrax You might try renaming `commons` to `vendors` and removing the `name` prop. I'm not sure if that would cause a problem, [but `name` seems to be in the wrong spot](https://webpack.js.org/plugins/split-chunks-plugin/#splitchunks-name).

@gauravtiwari Ideally, with the way `webpack-assets-manifest` generates the `entrypoints: { myChunkName: { js: [...], css: [...] }}` arrays, **_should_** webpacker map **all** the ordered filenames to `<script>`s & styles? If so, that would align well with how vanilla webpack is used -- plus [there are some nifty features that `splitChunks` brings to the table.](https://webpack.js.org/plugins/split-chunks-plugin/#optimization-splitchunks)

**Comment by Zyphrax** [comment]
@jakeNiemiec My configuration is the same as [the second example](https://webpack.js.org/plugins/split-chunks-plugin/#split-chunks-example-2) on Webpack’s splitChunks page. It gobbles up all vendor libraries into one big pack, which is fine for my project.

@gauravtiwari Thank you for all the great work!

**Comment by Zyphrax** [comment]
Temporary workaround for people that have duplicate includes:
```slim
/ Doesn't include dependencies, will only write platform script tag
= javascript_include_tag asset_pack_path('platform.js')

/ Automatically includes dependencies, writes multiple script tags
= javascript_pack_tag 'tenant'
```

**Comment by gauravtiwari** [comment]
Please give new RC a try.

**Comment by jakeNiemiec** [comment]
@Zyphrax duplicate includes shouldn't be a problem right? The browser has the content cached already?

 Do you think that chunks with side-effects (`import 'sideEffect.js`) will be affected by only outputting unique `<script>` tags? I worry about older libraries or frameworks that need to be loaded in exactly the right way. (like Angular ngZone)

**Comment by Zyphrax** [comment]
@gauravtiwari Works great, thank you! 🎉
