### ISSUE TITLE
webpacker 4.0.0.rc2: images are not accessible from rails views

### ISSUE THREAD

**Issue by deepj** [rails/webpacker#1839]
Hello,
I've made a fresh webpacker 4.0.0.rc2 installation and I'm trying to load an image from assets in a rails view

```erb
<%= image_pack_tag 'test.jpg' %>
```

The image is located in multiple paths (`app/assets/images/test.jpg`, `app/javascript/images/test.jpg`))

I don't see the file would be in the manifest

```
{
  "application.js": "/packs/application-8cac6ff83dcd20565aa4.js",
  "application.js.map": "/packs/application-8cac6ff83dcd20565aa4.js.map",
  "entrypoints": {
    "application": {
      "js": [
        "/packs/application-8cac6ff83dcd20565aa4.js"
      ],
      "js.map": [
        "/packs/application-8cac6ff83dcd20565aa4.js.map"
      ]
    },
    "hello_vue": {
      "js": [
        "/packs/hello_vue-e8868d6621d6bbe8029c.js"
      ],
      "js.map": [
        "/packs/hello_vue-e8868d6621d6bbe8029c.js.map"
      ]
    }
  },
  "hello_vue.js": "/packs/hello_vue-e8868d6621d6bbe8029c.js",
  "hello_vue.js.map": "/packs/hello_vue-e8868d6621d6bbe8029c.js.map"
}
```

I though, webpacker 4.0.0rc2 has out-of-box solution for this simple use case. I won't really import the image in `application.js`. I'd like to use it in the same way as using sprocket.

**Comment by gauravtiwari** [comment]
@deepj What happens if you put your images under packs folder?

**Comment by deepj** [comment]
@gauravtiwari Unfortunately, without luck.

But the manifesto looks now

```
{
  "application.js": "/packs/application-8cac6ff83dcd20565aa4.js",
  "application.js.map": "/packs/application-8cac6ff83dcd20565aa4.js.map",
  "entrypoints": {
    "application": {
      "js": [
        "/packs/application-8cac6ff83dcd20565aa4.js"
      ],
      "js.map": [
        "/packs/application-8cac6ff83dcd20565aa4.js.map"
      ]
    },
    "hello_vue": {
      "js": [
        "/packs/hello_vue-e8868d6621d6bbe8029c.js"
      ],
      "js.map": [
        "/packs/hello_vue-e8868d6621d6bbe8029c.js.map"
      ]
    },
    "images/test": {
      "js": [
        "/packs/images/test-386cb1dac0338a7cd384.js"
      ],
      "js.map": [
        "/packs/images/test-386cb1dac0338a7cd384.js.map"
      ]
    }
  },
  "hello_vue.js": "/packs/hello_vue-e8868d6621d6bbe8029c.js",
  "hello_vue.js.map": "/packs/hello_vue-e8868d6621d6bbe8029c.js.map",
  "images/test.js": "/packs/images/test-386cb1dac0338a7cd384.js",
  "images/test.js.map": "/packs/images/test-386cb1dac0338a7cd384.js.map",
  "packs/images/test.jpg": "/packs/packs/images/test-7a25cb51be37d1334cf2274ba9194279.jpg"
}
```

**Comment by gauravtiwari** [comment]
What happens if you do this? Is this an image? `test.js`? should be `test.jpg` right?

> try this
`<img src="<%= image_pack_tag 'packs/images/test.jpg' %>" />`

**Comment by deepj** [comment]
@gauravtiwari Hm, it works. It generates the following paths

```html
<img src="/packs/packs/images/test-7a25cb51be37d1334cf2274ba9194279.jpg" />
```

There is no `test.js` in my files, but it comes from webpacker and it's meant `test.jgp` I guess

**Comment by grk** [comment]
Can confirm, `asset_pack_path` needs the path to be `packs/images/example.jpg` to load from `app/javascript/packs/images/example.jpg` on 4.0.0.rc.2

**Comment by gauravtiwari** [comment]
What happens if you do this in `application.js`? 

```js
// top of packs/application.js
const importAll = (r) => r.keys().map(r)
importAll(require.context('./images', false, /\.(png|jpe?g|svg)$/));
```

This will load all images from images folder and then it should be available in manifest for you to pick up using `asset_pack_path`

**Comment by gauravtiwari** [comment]
The images folder should be outside `packs` folder.

**Comment by gauravtiwari** [comment]
Great, thanks @grk 

Like mentioned in the README, everything must go through packs (entrypoint) for it to be available in the end. If you want a bunch of images to be available in the view, best to use `importAll` and then include it in the main pack and it should be available for you using `asset_pack_path`. Otherwise, you must require an image or another asset in the pack for it to be available in the view using helper tags.

We don't recommend putting anything other than `js` a.k.a packs inside packs folder, in other words, a JS package you are going to include in your view.

**Comment by jasl** [comment]
I believe that's relates to #1887 

@gauravtiwari has made a fix, but document has a tiny bug need to be fixed.

For my experience, `< rc.3` (above I didn't test) you can move your images into `app/packs/images`, then you can use your `importAll("images")` (actually I do the same thing like you), and in your view, you can ref them like this: `<%= image_pack_tag("images/avatar.png") %>` or you can check manifest json to prove it correction.

**Comment by deepj** [comment]
@jasl thanks, but you don't fully understand my issues. No, I don't use sprocket at all. I recommend you re-read this issue. If some changes have been made since this issue was reported, then it's good.

**Comment by guillaumebriday** [comment]
hey @deepj, 

Does it work for you if your images are in a subfolder like so :

```app/javascript/images/blog/thumbnail.jpg``` ?

Because it does not for me, even with the @gauravtiwari's `importAll` hack :/

It only works for images at the root of `images` folder

My importAll method :

```js
const importAll = (r) => r.keys().map(r)
importAll(require.context('../images', true, /\.(png|jpe?g|svg)$/))
```

**Comment by VitorHP** [comment]
+1

**Comment by vidurpunj** [comment]
require.context('../images/', false);

**Comment by digaoddc** [comment]
For me, the solution was to add this line `require.context('../images', true)` in the file `app/javascript/packs/application.js`.
After that, I was able to use the `image_pack_tag` in the views

**Comment by guillaumebriday** [comment]
Yes,
It’s in the docs now : https://github.com/rails/webpacker/blob/master/docs/assets.md

We can close this issue.
