### ISSUE TITLE
React Hooks error

### ISSUE THREAD

**Issue by stoplion** [rails/webpacker#1840]
Testing out [React Hooks](https://reactjs.org/docs/hooks-intro.html) with Rails/Webpacker and noticed there is a `Error: Hooks can only be called inside the body of a function component` error. 

Using Webpacker `4.0.0-rc.2`
React Dom `^16.7.0-alpha.2`
React `16.7.0-alpha.2`

**Comment by gauravtiwari** [comment]
Hey @stoplion That's related to react hooks API, not webpacker. You should always use hooks inside react functional component body and it should be the first thing (AFAIK).

**Comment by nunez-giovanni** [comment]
@stoplion  - Did you get Hooks to work, seeing as this is not a webpacker issue? 

I was playing with Hooks on  Node + React and it worked fine, but I get your issue when I try Rails + React via React_On_Rails using the same component.

**Comment by bhgames** [comment]
Yep also had this issue.

**Comment by amauryfischer** [comment]
got same issue there ><

**Comment by kurtnovack** [comment]
I had the same issue and found a fix that worked for me, hopefully it'll help out others:

Both my rails app and a module I was importing had react as a dependency.
Ended up fixing it by importing react and react-dom from the module itself. (not the prettiest thing but it worked):

```
import React from 'the_added_module/node_modules/react'
import ReactDOM from 'the_added_module/node_modules/react-dom'
```

**Comment by amauryfischer** [comment]
I tried as u said with react on rails :
```
import React from 'react-on-rails/node_modules/react';
import ReactDOM from 'react-on-rails/node_modules/react-dom'
const Test = function() {
    const [state, setState] = useState(0)
    return (
        <div onClick={setState("coucou")}>state : {state}</div>
    )
}

export default Test;
```

This is not working for myself but i guess its normal...
I'm running react on rails, and react on rails in node modules does not have react, in fact my node_modules/react-on-rails/node-modules  only contains a .bin.

I suppose that's because my main package.json already contains react.

Moreover react-on-rails package.json as 
```
    "react": "^15.6.1",
    "react-dom": "^15.6.1",
```

I would like to know in your case @kurtnovack what is your react version in your main package/json and in your the_added_module ?
thanks a lot

**Comment by kurtnovack** [comment]
@amauryfischer they're all "^16.8.4". Sorry to hear that didn't work, I wasn't using react_on_rails and just importing react from npm.

**Comment by amauryfischer** [comment]
Ok, i wonder how ur hack made this work^^

**Comment by amauryfischer** [comment]
For those having the problem with react_on_rails i finally found out the solution, multiple React was loaded due to multiple react_component in views or javascript_pack_tag.
More details : https://github.com/shakacode/react_on_rails/issues/1198
