### ISSUE TITLE
Webpacker is not loading when running multiple webpacker instances with rails engines

### ISSUE THREAD

**Issue by ghaydarov** [rails/webpacker#1841]
First would like to start by saying thank you for this PR: https://github.com/rails/webpacker/pull/1836

I have a rails app with multiple engines that I am trying to use webpacker (master branch) with. I followed the setup as described in the [engine docs](https://github.com/rails/webpacker/blob/master/docs/engines.md) 

The issue I am encountering is that when I run `./bin/webpack-dev-server` on each engine and main app with different ports, only one of them loads the webpacker and rest is not picking up the pack file content (for the engine), meaning, not loading the contents of it.

I checked and I see that all instances of the main app and engines are present by:
```
Engine.webpacker.config.dev_server.present?
Main.webpacker.config.dev_server.present?
```

Any help is appreciated.

**Comment by ghaydarov** [comment]
As per documentation below, I tried without dev server as it should be lazyloading the pack files on demand, however, the same thing is happening and it is only loading the main app's packs, or shoud I say webpack and not for the engines.

> In development, Webpacker compiles on demand rather than upfront by default. This happens when you refer to any of the pack assets using the Webpacker helper methods. This means that you don't have to run any separate processes. Compilation errors are logged to the standard Rails log.

> If you want to use live code reloading, or you have enough JavaScript that on-demand compilation is too slow, you'll need to run ./bin/webpack-dev-server or ruby ./bin/webpack-dev-server.

I run ./bin/webpack on both engine and main app and it does compile with the right paths, but webpack is not loaded for engines.

Right, compiling all packs using one dev server instance would be great and would make more sense.

**Comment by ghaydarov** [comment]
So, I had to add my engine pack paths with Rack::Static middleware to load on development.  I thought it was necessary in production as it was mentioned in the docs. (I will update that part in another PR) Rails is not serving/loading folders/files from engine's public folder, and it seems like it is expected.

This fixes it and now webpack compiles even if you don't have webpack server instances are not running and it works when you have multiple instances of webpack dev servers running on different ports as well.

`       initializer "webpacker.static" do |app|`
`       app.config.middleware.use(`
`          Rack::Static,`
`          urls: ["/engine/packs"], root: ROOT_PATH.join("public"))`
`      end `

We also need a way to load and serve files in engine's public folder by default when webpacker is used. Otherwise we need to load that middleware in every engine, and that might not be very good idea. Any suggestions?

Also, currently, when you change your js code, when webpack dev server is not run, webpacker compiles main app's packs , but not in engine's.

**Comment by ghaydarov** [comment]
@palkan this is nice. I like the idea of making public directory configurable. thanks for the patch. However, I wasn't able to get it working without middleware, it just won't load the webpack as it wouldn't without middleware. Not sure what I am missing here.

**Comment by palkan** [comment]
> However, I wasn't able to get it working without middleware

Do you mean Rack::Static middleware?

I’ll try to build a simple app with engines to reproduce my configuration.

**Comment by ghaydarov** [comment]
> Do you mean Rack::Static middleware?
Yes.

**Comment by ghaydarov** [comment]
> Another approach could be to set your public_output_path for engine's webpacker to the main app public/ folder. Thus you won't need a separate middleware.

If we do this, this will put all engines' pack files in main app's public directory, and would not give us the isolation we want with the original PR you have, right? We don't want to load everything under main I think, load only engine pack when engine is accessed and main's pack when main accessed.

**Comment by ghaydarov** [comment]
This works nicely. Thanks man! I will close this as this is solved. Happy holidays!
