### ISSUE TITLE
[4.0.0.rc.1 / 4.0.0.rc.2] stylesheet_pack_tag is broken

### ISSUE THREAD

**Issue by VR4J** [rails/webpacker#1846]
I've upgraded from `4.0.0-pre.3` to `4.0.0-rc.2` and I noticed my stylesheets weren't included into the rails view. 

This misbehaviour seems to be caused by this call in my project:
_/app/views/layouts/application.html.haml_
```ruby
= stylesheet_pack_tag 'css/app.css'
```

It didn't cause any error's as it just seems to not generate the style tag in the html. 

When downgrading to `4.0.0-pre.3` it worked again.

**Comment by gauravtiwari** [comment]
Have you added `extract_css` option? #1625

**Comment by Vreijsen** [comment]
@gauravtiwari Yep, that fixed it thanks!

**Comment by guillaumebriday** [comment]
Feel free to close this issue if it's ok for you @VR4J
