### ISSUE TITLE
[Feature request] ActionView helper for CSS modules

### ISSUE THREAD

**Issue by DanielHeath** [rails/webpacker#1849]
I'd like to use CSS modules from my rails views (and from looking over the issue tracker, I'm far from the only one).

I propose a new helper method for rails views: 
```
css_module('css-module') do |styles|
  <div class="<%= styles[:exported-name] %>" />
end
```

This helper should:

 * Work transparently in dev and production
 * Correctly handle HMR where possible (or at least warn, if a full reload is required)
 * In development, error (or warn) if the styles have not already been included on the page (unless the module is a standalone pack)
 * Support CSS modules as standalone packs or in `src`
 * Generate a `<link rel=stylesheet` by default if the module is a standalone pack (or if `link: true` is specified)

Thoughts? Have I missed anything important? Would a PR be accepted?

**Comment by Ployee15** [comment]
Yes you can see your messages

ส่งจาก iPhone ของฉัน

เมื่อ 21 ธ.ค. 2561 เวลา 08:02 เขียนโดย Daniel Heath <notifications@github.com<mailto:notifications@github.com>>:


I'd like to use CSS modules from my rails views (and from looking over the issue tracker, I'm far from the only one).

I propose a new helper method for rails views:

css_module('css-module') do |styles|
  <div class="<%= styles[:exported-name] %>" />
end


This helper should:

  *   Work transparently in dev and production
  *   Correctly handle HMR where possible (or at least warn, if a full reload is required)
  *   In development, error (or warn) if the styles have not been included on the page
  *   Support CSS modules as standalone packs or in src
  *   Generate a <link rel=stylesheet by default if the module is a standalone pack

Thoughts? Have I missed anything important? Would a PR be accepted?

**Comment by derrickmar** [comment]
I love this idea

**Comment by guillaumebriday** [comment]
Hey! Thanks for the suggestion. 🙏 

But I'm not sure it's a common use case to use CSS modules in Rails views directly. Most of the time, it's directly in React/JSX or Vue SFC.
