### ISSUE TITLE
Rails 5.1.0.rc1 ships with a webpacker version which doesn't include vue task

### ISSUE THREAD

**Issue by mdesantis** [rails/webpacker#186]
Related to this Rails issue: https://github.com/rails/rails/issues/28573

Webpacker 1.0 gem ships without the `webpack:install:vue` rake task, so on Rails 5.1.0.rc1 `rails new rails_vue --webpack=vue` fails.

Replacing `gem 'webpacker'` with `gem 'webpacker', github: 'rails/webpacker'` makes the rake task `webpacker:install:vue` available, fixing this issue.

**Comment by dhh** [comment]
Going to cut a 1.1 release.

**Comment by rafaelfranca** [comment]
Released
