### ISSUE TITLE
Release 3.6 or 3.5.6 on 3-x-stable?

### ISSUE THREAD

**Issue by jdashton** [rails/webpacker#1861]
The 3-x-stable branch has a few commits, especially support for Elm 0.19. What would it take to get a new 3.6 or 3.5.6 release that included those commits?

**Comment by gauravtiwari** [comment]
Will do soon, thanks :)

**Comment by guillaumebriday** [comment]
Can this issue be closed ?

**Comment by jdashton** [comment]
Closing it.

**Comment by guillaumebriday** [comment]
Thanks @jdashton
