### ISSUE TITLE
Unexpected output from object-rest-spread

### ISSUE THREAD

**Issue by aruprakshit** [rails/webpacker#1862]
Here is a small snippet that doesn't work with current [proposal-object-rest-spread](https://github.com/rails/webpacker/blob/v3.5.5/package.json#L19) version webpacker 3.5.5 has. This looks like fixed in [this issue](https://github.com/babel/babel/issues/8785).

```js
var o = {1: {foo: 1, id: 2, bar: 3}}
var a = 1;
var { [a]: delA, ...rest} = o;

console.log(rest); // gives the value as o has. But it should be {}.
```

The [original bug](https://www.reddit.com/r/reactjs/comments/abxaup/unexpected_output_from_reducer_function_when/) I found in my project in the reducer function. Is there anyway to upgrade the `proposal-object-rest-spread` lib when with webpacker 3.5.5?

**Comment by guillaumebriday** [comment]
I think it's been fixed with newer versions and upgraded dependencies 

If so, feel free to close this issue @aruprakshit
