### ISSUE TITLE
CKEditor 5 build

### ISSUE THREAD

**Issue by meneerprins** [rails/webpacker#1865]
Before the latest webpacker update I could just use ```import BalloonEditor from '@ckeditor/ckeditor5-build-balloon';``` but after the latest update I get an error: 

```"export 'default' (imported as 'BalloonEditor') was not found in '@ckeditor/ckeditor5-build-balloon'```

Does anyone know how I can make the premade CKEditor 5 build work? The custom build seems too complicated.

Package: https://github.com/ckeditor/ckeditor5-build-balloon

**Comment by ansonhoyt** [comment]
@meneerprins are you still having this problem?

I'm troubleshooting the same thing with `@ckeditor/ckeditor5-build-classic`. I think it was working for us around `4.0.0.pre.pre.2` and I think it broke sometime before the `rc` builds.

I've tried fixing by re-installing `4.0.0-rc.5` with fresh configs (a lot have moved around) but no luck so far.

**Comment by ansonhoyt** [comment]
It broke in e95dd72. That is a big commit, so I'm not sure which part 😕

I can do a clean install of `4.0.0-rc.5`, use all the latest configs, downgrade to 99c0dd9:

```diff
Gemfile
-gem 'webpacker', '~> 4.0.0-rc.5'
+gem 'webpacker', git: 'https://github.com/rails/webpacker.git', ref: '99c0dd9'

package.json
-    "@rails/webpacker": "4.0.0-rc.5",
+    "@rails/webpacker": "https://github.com/rails/webpacker.git#99c0dd9",
```
...and CKEditor works again

**Comment by ansonhoyt** [comment]
Thanks to https://github.com/rails/webpacker/issues/1903#issuecomment-457314744, this can be fixed by following the [upgrade guide](https://github.com/rails/webpacker/blob/master/docs/v4-upgrade.md#excluding-node_modules-from-being-transpiled-by-babel-loader)

I just had to update `config/webpack/environment.js` with:
```diff
const { environment } = require('@rails/webpacker')

+ environment.loaders.delete('nodeModules')

module.exports = environment
```

**Comment by meneerprins** [comment]
Yes, I fixed it now with:

```
const nodeModulesLoader = environment.loaders.get('nodeModules');

if (!Array.isArray(nodeModulesLoader.exclude)) {
  nodeModulesLoader.exclude =
    nodeModulesLoader.exclude == null ? [] : [nodeModulesLoader.exclude];
}
nodeModulesLoader.exclude.push(/@ckeditor\/ckeditor5-build-balloon/);
```
