### ISSUE TITLE
Problems trying to get react-rails working with webpacker

### ISSUE THREAD

**Issue by JenniferVanderputten** [rails/webpacker#1877]
I was able to get it working with the Sprockets method, however, it is very difficult to add packages and do imports via that method, so I'm trying to get webpacker to work.

The first thing that happened is that the installation did not work properly.  I was getting the following error  when I installed as per instructions:

webpack-dev-server: line 1: XSym: not found
webpack-dev-server: line 2: 0047: not found
webpack-dev-server: line 3: baebe48db4509e117ed95eca45abdd2e: not found
webpack-dev-server: line 4: …/webpack-dev-server/bin/webpack-dev-server.js: not found

Turns out that the webpack-dev-server script simply contained the lines:
XSym
0047
baebe48db4509e117ed95eca45abdd2e
…/webpack-dev-server/bin/webpack-dev-server.js

So I copied the proper versions of webpack-dev-server and webpack into the bin directory to manually correct this.  By doing so, the webpack service comes up without any errors.

However, when I try to load my rails app, it just hangs.  No warnings or errors, nothing in the logs.  It appears to be waiting on something, and since the only difference between this and a working version is the inclusion of webpack, then it must be the webpack that is causing the hang.

Any ideas what the problem could be?

Thanks for your time!

**Comment by guillaumebriday** [comment]
Is this issue still relevant ?

Can it be closed ? @JenniferVanderputten
