### ISSUE TITLE
Watch rails views and reload page on changes

### ISSUE THREAD

**Issue by mbajur** [rails/webpacker#1879]
I'm currently using webpacker with page reloading on css/js changes and it all works just great. Thanks for this amazing piece of software. I was wondering - would that be possible to do the same for rails views? It would be great if updating erb or slim view could trigger a webpack page refresh (ideally without rebuilding entire js/css bundle).

I'm fully aware that's not the point of using webpack(er) and know there are solutions like guard and livereload for that but i would love to avoid using yet another deamon running in the background.

Thanks in advance for any clues!

**Comment by scottatron** [comment]
Not quite as nice as using webpack itself, but I've got this working by using [watchexec](https://github.com/watchexec/watchexec).

I run up webpack-dev-server, then run:
```
watchexec -w app/views touch app/javascript/packs/application.js
```

**Comment by mtomov** [comment]
There's an even easier way, just set the `devServer` `contentBase` property like this in `config/webpack/development.js`

```js
environment.config.devServer.watchContentBase = true
environment.config.devServer.contentBase = [
  path.join(__dirname, '../../app/views')
]
```

**Comment by swrobel** [comment]
Here's an example that won't cause webpack to do a full recompile. This will simply trigger a browser reload. Your specific watches may vary, but they're pretty easy to configure using an array of glob syntax w/ chokidar (which is already included by webpack) - just note that it doesn't accept regexes:

development.js:
```js
const chokidar = require('chokidar')
environment.config.devServer.before = (app, server) => {
  chokidar.watch([
    'config/locales/*.yml',
    'app/views/**/*.slim'
  ]).on('change', () => server.sockWrite(server.sockets, 'content-changed'))
}
```

**Comment by jesster2k10** [comment]
> Here's an example that won't cause webpack to do a full recompile. This will simply trigger a browser reload. Your specific watches may vary, but they're pretty easy to configure using an array of glob syntax w/ chokidar (which is already included by webpack) - just note that it doesn't accept regexes:
> 
> development.js:
> 
> ```js
> const chokidar = require('chokidar')
> environment.config.devServer.before = (app, server) => {
>   chokidar.watch([
>     'config/locales/*.yml',
>     'app/views/**/*.slim'
>   ]).on('change', () => server.sockWrite(server.sockets, 'content-changed'))
> }
> ```

Hey, I can't seem to get this working. The "chokidar" isn't watching any changes in *.html.erb files

**Comment by swrobel** [comment]
> > Here's an example that won't cause webpack to do a full recompile. This will simply trigger a browser reload. Your specific watches may vary, but they're pretty easy to configure using an array of glob syntax w/ chokidar (which is already included by webpack) - just note that it doesn't accept regexes:
> > development.js:
> > ```js
> > const chokidar = require('chokidar')
> > environment.config.devServer.before = (app, server) => {
> >   chokidar.watch([
> >     'config/locales/*.yml',
> >     'app/views/**/*.erb'
> >   ]).on('change', () => server.sockWrite(server.sockets, 'content-changed'))
> > }
> > ```
> 
> Hey, I can't seem to get this working. The "chokidar" isn't watching any changes in *.html.erb files

Yes, my glob was for slim templates, which are what I use. I've modified the code above to look for erb files (though anyone can & should modify these globs for their needs)

**Comment by jesster2k10** [comment]
> > > Here's an example that won't cause webpack to do a full recompile. This will simply trigger a browser reload. Your specific watches may vary, but they're pretty easy to configure using an array of glob syntax w/ chokidar (which is already included by webpack) - just note that it doesn't accept regexes:
> > > development.js:
> > > ```js
> > > const chokidar = require('chokidar')
> > > environment.config.devServer.before = (app, server) => {
> > >   chokidar.watch([
> > >     'config/locales/*.yml',
> > >     'app/views/**/*.erb'
> > >   ]).on('change', () => server.sockWrite(server.sockets, 'content-changed'))
> > > }
> > > ```
> > 
> > 
> > Hey, I can't seem to get this working. The "chokidar" isn't watching any changes in *.html.erb files
> 
> Yes, my glob was for slim templates, which are what I use. I've modified the code above to look for erb files (though anyone can & should modify these globs for their needs)

Thank you for that. I'm not sure what the issue was but after closing my terminal and restarting my server, it worked like a charm!

**Comment by cabgfx** [comment]
thanks, @swrobel that worked great!

Can confirm this works on Rails 6.0.3.1, webpacker 4.2.2 :+1:

My `config/webpack/development.js`:

```js
process.env.NODE_ENV = process.env.NODE_ENV || 'development'

const environment = require('./environment')
const chokidar = require('chokidar')

environment.config.devServer.before = (app, server) => {
  chokidar.watch([
    'config/locales/*.yml',
    'app/views/**/*.erb'
  ]).on('change', () => server.sockWrite(server.sockets, 'content-changed'))
}

module.exports = environment.toWebpackConfig()
```

**Comment by guillaumebriday** [comment]
Thanks @cabgfx

**Comment by henrypoydar** [comment]
Using `merge` for this in @rails/webpacker 6.0.0.beta-5 `config/webpack/development.js`:

````
process.env.NODE_ENV = process.env.NODE_ENV || "development";

const webpackConfig = require("./base");
const { merge } = require("@rails/webpacker");
const chokidar = require("chokidar");

// Hot reload views via webpack dev server. https://github.com/rails/webpacker/issues/1879.
// However, CI system tests may choke on this since NODE_ENV is  'development' in tests. 
// So check for RAILS_ENV and skip hot reload in testing.
module.exports = process.env.RAILS_ENV == "development" ? merge(webpackConfig, {
  devServer: {
    before: (app, server) => {
      chokidar
      .watch([
        "config/locales/*.yml",
        "app/views/**/*.md",
        "app/views/**/*.html.erb",
        "app/views/**/*.html.haml",
      ])
      .on("change", () => server.sockWrite(server.sockets, "content-changed"));
    }
  },
}) : webpackConfig;


````

**Comment by travisp** [comment]
For what it's worth, I had to add the option "awaitWriteFinish" or else the reload did not always successfully show the changed file (and I had to either manually refresh, or hit save a second time). The relevant section looks like this on webpacker 6:

```    
before: (app, server) => {
      chokidar
        .watch([
          "config/locales/*.yml",
          "app/views/**/*.html.erb",
          "app/views/**/*.html.haml",
        ], {
          awaitWriteFinish: true
        })
        .on("change", () => server.sockWrite(server.sockets, "content-changed"));
    }
  }
```

**Comment by mabras** [comment]
> For what it's worth, I had to add the option "awaitWriteFinish" or else the reload did not always successfully show the changed file (and I had to either manually refresh, or hit save a second time). The relevant section looks like this on webpacker 6:

Make sure of `hmr` and `inline` value set to `true`.
```
// config/webpacker.yml
  dev_server:
    ...
    hmr: true
    inline: true
    ...
```

**Comment by swrobel** [comment]
> Make sure of `hmr` and `inline` value set to `true`.

`inline` does need to be set to `true`, but `hmr` is not required. I have it turned off as mine isn't a SPA.

**Comment by chmich** [comment]
THANKS all! much smoother work with that settings.

Question:
If a page is broken there appears the rails-error-page.
In my example with better_errors: https://github.com/BetterErrors/better_errors
After repairing the html i have to click reload once and then the machine runs again and is reloading after all changes.
The cherry on the cake would be that the browser would then also refresh the page, when the error is fixed.

Does anyone know if that could be possible?

**Comment by joshsaintjacque** [comment]
> THANKS all! much smoother work with that settings.
> 
> Question:
> If a page is broken there appears the rails-error-page.
> In my example with better_errors: https://github.com/BetterErrors/better_errors
> After repairing the html i have to click reload once and then the machine runs again and is reloading after all changes.
> The cherry on the cake would be that the browser would then also refresh the page, when the error is fixed.
> 
> Does anyone know if that could be possible?

Adding `awaitWriteFinish: true` to my development.js change listener solved this issue for me.

**Comment by kylebolton** [comment]
For anyone having CI issues/packs-tests issues, I had to wrap the above code in a condition so RSpec didn't complain.
 
`process.env.NODE_ENV = process.env.NODE_ENV || 'development'

const environment = require('./environment')
const chokidar = require('chokidar')

if (process.env.RAILS_ENV === 'development') {
    environment.config.devServer.before = (app, server) => {
        chokidar.watch([
            'config/locales/*.yml',
            'app/views/**/*.erb'
        ],
        ).on('change', () => server.sockWrite(server.sockets, 'content-changed'))
    }
}

module.exports = environment.toWebpackConfig()

`
