### ISSUE TITLE
Sourcemaps are showing compiled babel output

### ISSUE THREAD

**Issue by chrisnicola** [rails/webpacker#1883]
I'm using Webpacker 4 and seem to be seeing compiled babel output when viewing sourcemaps under Chrome and Firefox. Wanted to check if it is just me before trying to put together an example as I'm currently seeing this under a relatively complex project.

I did narrow it down to this by removing the `babel` and `nodeModules` loaders and adding a much simpler loader config:

```
      {
        test: /\.(js|mjs)$/,
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader',
        },
      },
```

Is what I have now, which is *mostly* working. I say mostly because there is a separate issue now with Vue source maps but I'm pretty sure that doesn't have anything to do with Webpacker now. At least the plan JS files are showing the original code now.

**Comment by gauravtiwari** [comment]
@chrisnicola Hmm, that's strange can you put together an example app, please?

**Comment by gauravtiwari** [comment]
Seeing this with: `devtool: 'source-map'` (production) and `devtool: 'cheap-module-source-map'` (development), which looks correct, right?:

<img width="1155" alt="screenshot 2019-01-25 at 10 48 11" src="https://user-images.githubusercontent.com/771039/51741435-d4d9d000-208e-11e9-89c3-edd3a459f43f.png">

**Comment by chrisnicola** [comment]
@gauravtiwari sorry for not getting back to this earlier. So there are definitely some issues still with sourcemaps but they are mostly between webpack and the various browsers.

For one you need to use Firefox Developer Edition to work with Webpack source maps in dev mode. So that was my main problem.
