### ISSUE TITLE
`yarn check --verify-tree` doesn't work with a custom `--modules-folder`

### ISSUE THREAD

**Issue by jonleighton** [rails/webpacker#1884]
This PR added the `yarn check --verify-tree` command to the Yarn integrity check: https://github.com/rails/webpacker/pull/1774

Unfortunately, [that command doesn't work with a custom modules folder](https://github.com/yarnpkg/yarn/issues/2784).

Therefore, the integrity check is broken for users who are installing to a different directory than `RAILS_ROOT/node_modules/`.

I'm not sure what Webpacker should do about this. Perhaps it could detect whether the `NODE_PATH` is set to a non-standard location and not run `yarn check --verify-tree` in that situation.

**Comment by guillaumebriday** [comment]
Can this issue be closed ?
