### ISSUE TITLE
Support to pass data from view to component ?

### ISSUE THREAD

**Issue by ashwintastic** [rails/webpacker#1885]
I know this has been answered in [this](https://github.com/rails/webpacker/issues/575) but the answer points to a link which doesn't exist

**Comment by ashwintastic** [comment]
React components

**Comment by n0nick** [comment]
Seems to point to this documentation from back in v2.0:
https://github.com/rails/webpacker/tree/v2.0.0#pass-data-from-view

**Comment by guillaumebriday** [comment]
You should use [props](https://reactjs.org/docs/components-and-props.html) 

Can this issue be closed ?
