### ISSUE TITLE
Access Rails settings (development.yml , test.yml etc.) 

### ISSUE THREAD

**Issue by rahulakurati** [rails/webpacker#1895]
How to access rails settings variable (from development.yml etc.) inside JavaScript?

**Comment by jakeNiemiec** [comment]
You can put something like this (and more) in your `<head>`. (or anywhere, it just needs to be before any `javascript_pack_tag`s)

```erb
<script>
  window.mySettingsVariable = <%== @my_settings_variable.to_json %>;
</script>
```

A more complecated, but just as valid way of doing this would be to use the `DefinePlugin` in your `config/environment.js`. Here is one example I found: https://github.com/rails/webpacker/pull/1304#issuecomment-373294560

Note: Anyone who visits your site can access variables set on the `window` object. Be careful not to set any sensitive info.

**Comment by rahulakurati** [comment]
Ya thats right. I'm afraid binding to a window object might have security consequences.

**Comment by jakeNiemiec** [comment]
JavaScript is completely client-side, anything you expose to is will be available to your users (even if not assigned to `window`). JS should never come into contact with data that has _security consequences_.

**Comment by guillaumebriday** [comment]
Can this issue be closed ?
