### ISSUE TITLE
Reference resolved path in SCSS

### ISSUE THREAD

**Issue by IanLunn** [rails/webpacker#1896]
I have fonts saved in `app/assets/stylesheets/fonts` and would like to reference them in SCSS within the React app. I've added the font location to `webpacker.yml` like so:

```
resolved_paths: [
   'app/assets/stylesheets/fonts'
]
```

The [documentation states that this works for importing files in React](https://github.com/rails/webpacker#resolved) but can it be used in SCSS that a React app imports? Example SCSS:

```
@font-face {
  font-display: swap;
  font-family: "Font1";
  src: url(*resolved font path needed here*) format("woff2"),
    url(*resolved font path needed here*) format("woff");
  font-weight: normal;
  font-style: normal;
}
```

**Comment by gauravtiwari** [comment]
More info here, but it says it only works with imports: https://github.com/sass/node-sass/blob/master/README.md#includepaths (give it a try)
