### ISSUE TITLE
Documentation: Uglifier config

### ISSUE THREAD

**Issue by seanWLawrence** [rails/webpacker#1897]
The [Troubleshooting page](https://github.com/rails/webpacker/blob/master/docs/troubleshooting.md#rake-assetsprecompile-fails-execjsruntimeerror) recommends to comment out the uglifier config from Rails' asset pipeline if you run into issues with compilation happening twice. 

I was able to solve this in my app by using this config instead:

`Rails.application.config.assets.js_compressor = Uglifier.new(harmony: true)`

As recommended for ES6 syntax in Uglifier's [README](https://github.com/lautis/uglifier#es6--es2015--harmony-mode). 

In your opinion, is it still better to comment out the uglifier config as you recommended, and if so, would this mean that all JavaScript in the rails pipeline would not be minified?

**Comment by gauravtiwari** [comment]
Please make a pr to update README.

**Comment by gauravtiwari** [comment]
Updated
