### ISSUE TITLE
webpack-dev-server causes ruby to run 100% processor capacity constantly

### ISSUE THREAD

**Issue by kazmin** [rails/webpacker#1907]
My setup:
Windows 10
WSL with Ubuntu 18.04
webpacker 4.rc2 (I tried rc5, but it didn't compile)

When I run Puma as app server and webpack-dev-server it works fine for the first request. Then at the moment that I change and save a js file, the ruby process goes to 100% capacity and it does not go down until the webpack-dev-server is stopped. 

I tried stopping hot reload, but it didn't help. 
Running webpack --watch yields the same result - ruby at 100%.
Running just the app server works fine, the only problem is that the compile time is around 40 sec.

My coworker with Archlinux has everything working properly.

**Comment by gauravtiwari** [comment]
@kazmin Please, ensure you don't have a circular dependency within packs folder. Please see: https://github.com/rails/webpacker/blob/master/docs/folder-structure.md

**Comment by kazmin** [comment]
I don't believe I have any, I just have 2 simple files in the pack directory(I can share them if necessary). I also tried the circular-dependency-plugin just in case, but it didn't find anything.

**Comment by gauravtiwari** [comment]
@kazmin Please do and folder structure as well (make a test app on github, if possible)

**Comment by kazmin** [comment]
I have two files in my packs directory: 
application.js
```
  import "@babel/polyfill";
  var componentRequireContext = require.context("components", true)
  var ReactRailsUJS = require("react_ujs")
  ReactRailsUJS.useContext(componentRequireContext)
```

shared.js
```
import "@babel/polyfill";
import I18n from '@i18n-js/i18n-js';
import PathHelper from '@services/path_helper';
import moment from 'moment';
import _ from 'underscore';
import constants from '@services/constants';
import Analytics from '@services/analytics';
import OrderPriceStore from '@services/order_price_store';
import jQuery from 'jquery';

window.I18n = I18n;
window.PathHelper = PathHelper;
window.moment = moment;
window._ = _;

_.each(constants, function(value, key) {
    window[key] = value;
});

window.Analytics = Analytics;
window.OrderPriceStore = OrderPriceStore;
window.jQuery = jQuery;
window.$ = jQuery;
```

Overview of the javascript folder. The components folder holds my React components.
![image](https://user-images.githubusercontent.com/895568/51834612-82edb000-2303-11e9-8be8-a61348f30b7e.png)

Let me know if you'd need any more info.

**Comment by gauravtiwari** [comment]
Are you requiring any of these services in components?

```
import constants from '@services/constants';
import Analytics from '@services/analytics';
import OrderPriceStore from '@services/order_price_store';
```

Just a suggestion, you can put the code from shared to application.js and use `splitChunks` to separate out common chunks. `environment.splitChunks()` 

https://github.com/rails/webpacker/blob/master/docs/webpack.md#add-splitchunks-webpack-v4

Docs here: https://webpack.js.org/plugins/split-chunks-plugin/

**Comment by gauravtiwari** [comment]
I have a hunch that this might be related to windows OS/ruby. 

```
NODE_ENV=development yarn run webpack --config config/webpack/development.js --watch --progress --color
```


or 

```
NODE_ENV=development yarn run webpack-dev-server --config config/webpack/development.js
```

**Comment by jakeNiemiec** [comment]
`moment` is a known resource hog: https://github.com/jmblog/how-to-optimize-momentjs-with-webpack

I also would remove the `import "@babel/polyfill";` in the `shared.js` file: https://babeljs.io/docs/en/babel-polyfill#usage-in-node-browserify-webpack

**Comment by kazmin** [comment]
@gauravtiwari 
I'm not requiring any of the import anywhere else.
I ran the 
```NODE_ENV=development yarn run webpack-dev-server --config config/webpack/development.js```
and it again put my ruby process on 100% when I updated a js file.

@jakeNiemiec I'm using the IgnorePluging method for moment js.

**Comment by guillaumebriday** [comment]
Is this issue still relevant? Feel free to reopen if needed

**Comment by w-A-L-L-e** [comment]
Having same issue rails 5.2.8.1 and web packer for a react js frontend occasionally does this. Hard to track it, luckily doesn't happen in production, but happens when switching git branches or changing js files.
