### ISSUE TITLE
CDN host for staging environments

### ISSUE THREAD

**Issue by kpelelis** [rails/webpacker#1922]
**Webpacker version**: 4.0.0.rc7
**Rails Version**: 5.1.6

Greetings! We have integrated webpacker into our asset pipeline and now we are in the process of updating it to v4 in order to be in sync with the latest updates. Both testing and development environments are working just fine but we are facing some issues our staging environment which,is almost a mirror of the production setup.

Our assets are built using [our build server](https://github.com/skroutz/mistry/) with `RAILS_ENV=production` and are then moved into the application servers. A key concept in this build server is that it only generates production builds, as we want to keep staging and production environments as similar as possible and also leverage incremental building.

One of the few differences that the staging environment has, is that we do not use CDNs to distribute our assets. With the introduction of #1084 the URLs generated by the Manifest Plugin are prefixed with the production asset server URL (which in our case is a CDN). Currently there is no way to opt out of this feature without generating staging specific builds. Is there a chance to make this feature opt-in? I can get onto the task if it a valid change.

For the shake of completeness, the manifest file now looks something like:

```json
{
  "bundle1": "//my.cdn.com/assets/webpack/bundle1-abcdef0123456789.js"
}
```

Whereas before the update it looked like:

```json
{
  "bundle1": "/assets/webpack/bundle1-abcdef0123456789.js"
}
```

**Comment by iggant** [comment]
this is duplicate https://github.com/rails/webpacker/issues/1845

**Comment by guilleiguaran** [comment]
Closing in favor of #1845
