### ISSUE TITLE
4.0.0-rc7 asset_pack_path issue

### ISSUE THREAD

**Issue by ArthurianX** [rails/webpacker#1924]
Hey guys, 

I've been forced to update all the packages this evening and I got up to `rc7` where this strange bug happens:

I had a `png` file in `components/landing/static/logo.png` and I called its ref with `<%= image_tag asset_pack_path('components/landing/static/logo.png') %>` -- which **worked**

Now after the update I kept getting an error about the file not being found and I used a solution described in another issue here in this repo, to move all images inside the `packs/images` folder

I did that and if I wouldn't have looked in the generated manifest I'd have wasted some more time, 
**the only way I can access the image is through `media/logo.png`** not through `images/logo.png`

<img width="1264" alt="screenshot 2019-01-31 00 41 46" src="https://user-images.githubusercontent.com/2720451/52018120-0d940200-24f2-11e9-8073-fc96c7a72b8b.png">

This is really confusing, when did this convention appear or is this a bug ? 

P.S. - Loading the same file from its original location works as css background

**Comment by somebody32** [comment]
@ArthurianX I think that your case is described in the changelog: https://github.com/rails/webpacker/blob/2b0d5075f1ea85499ff7f1bd412e2c840e1c9c59/CHANGELOG.md#400rc6---2019-01-25

**Comment by ArthurianX** [comment]
Ooops, you're right. Closing this.

Thanks @somebody32 !
