### ISSUE TITLE
webpacker with nuxt.js

### ISSUE THREAD

**Issue by twnaing** [rails/webpacker#1928]
Has anyone try integrating [Nuxt.js](https://nuxtjs.org/) framework with webpacker gem?

As it is mentioned as "The Vue.js Framework", can it be done with some changes in (Vue) configuration?

I have considered the following approaches

- converting webpacker installed Vue to Nuxt.js ([suggested against by a contributor and to start from scratch](https://github.com/nuxt/nuxt.js/issues/2596#issuecomment-357994423))
- using Nuxtjs as separate project (I prefer to keep API and Nuxtjs in one project according to [this post](https://medium.com/rubyinside/a-modern-web-application-with-rails-da3deb48014c)

Both lead to webpacker gem with config for Nuxtjs. However I do not have experience or expertise to make webpacker gem to work correctly with Nuxtjs. 

If someone has the experience or could point the right way, I will be grateful.

**Comment by codebryo** [comment]
Hey there :)

Nuxt is more of a standalone Vue.js framework. It's not meant to be run inside a rails application.
It comes preconfigured with webpack and everything it needs to run. 
You can use it for static site generation, ssr, or more. 

If you want to use rails to serve an API, and build a standalone Vue app with nuxt that will consume it, that works. But you will not need the webpacker gem in this regards as Nuxt will handle everything on it's own.

**Comment by jpickwell** [comment]
@codebryo is correct, Nuxt.js is meant to be used as a standalone Vue.js framework. Nuxt.js is more like Rails, but for Node.js instead of Ruby.

**Comment by twnaing** [comment]
Thank you for the information. Very much appreciated.
