### ISSUE TITLE
Sprockets::FileNotFound: couldn't find file 'turbolinks'

### ISSUE THREAD

**Issue by pepibumur** [rails/webpacker#1931]
I'm not sure if this is the right place to publish this issue, if not, please let me know and I'll move it to the right repository.

After I migrated a project to Webpacker from Sprockets, I got rid of some dependencies that we were not using. One of them was Rails' turbolinks.

I can run the project locally, however, when I deploy the app and the `assets:compile` task gets executed, the following error is raised:

```
Sprockets::FileNotFound: couldn't find file 'turbolinks' with type 'application/javascript'
```

Some observations that I've made from that error are:
- Why are Sprockets error being raised? Shouldn't it be disabled from the project after configuring Webpacker? Is there anything else that I need to do to disable it?
- The line printed right before that one has no references to Turbolink.

**Comment by jpickwell** [comment]
Sprockets is not disabled by Webpacker. Webpacker and Sprockets can be used together. Check your `app/assets/javascripts` directory, you're most likely including `turbolinks` in a script here. Anything in the `app/assets` directory is handled by Sprockets.

**Comment by jakeNiemiec** [comment]
This is what I use to unfriend Sprokets:

```ruby
# config/application.rb

config.assets.enabled = false
config.assets.compile = false
config.assets.js_compressor = false

# prevent the cli generator from creating assets when generating a scaffold
config.generators do |g|
  g.assets false
end
```
