### ISSUE TITLE
WEBPACKER_PRECOMPILE=false still runs yarn:install

### ISSUE THREAD

**Issue by schuylr** [rails/webpacker#1932]
When I run `assets:precompile` with the `WEBPACKER_PRECOMPILE` flag set to false, it should skip installing Yarn dependencies:

```
circleci@3386211f0f38:~/project$ WEBPACKER_PRECOMPILE=false bundle exec rake assets:precompile
yarn install v1.9.4
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.59s.
```

I'm splitting my Sprockets and Webpacker compiles into separate tasks and don't want this running unnecessarily.

**Comment by jpickwell** [comment]
Without setting `WEBPACKER_PRECOMPILE`, `yarn:install` will be called twice:
* https://github.com/rails/rails/blob/94b5cd3a20edadd6f6b8cf0bdf1a4d4919df86cb/railties/lib/rails/tasks/yarn.rake#L17-L19
* https://github.com/rails/webpacker/blob/0d2b6ec5135773d7ca7dbd69174f629ee772811e/lib/tasks/webpacker/compile.rake#L35-L41

Setting `WEBPACKER_PRECOMPILE` only disables the Webpacker enhancement.

**Comment by jpickwell** [comment]
`WEBPACKER_PRECOMPILE=false` isn't meant to skip installing Yarn dependencies, but only to skip compiling webpack assets.

**Comment by kooogle** [comment]
可以直接到 gems 里修改源码，因为已经强制为预编译资产，我的结局方法
/gems/webpacker-4.0.7/lib/tasks/webpacker/compile.rake
```ruby
def enhance_assets_precompile
  # yarn:install was added in Rails 5.1
 # deps = yarn_install_available? ? [] : ["webpacker:yarn_install"]
 # Rake::Task["assets:precompile"].enhance(deps) do
 #   Rake::Task["webpacker:compile"].invoke
 # end
end
```ruby

**Comment by mfittko** [comment]
> `WEBPACKER_PRECOMPILE=false` isn't meant to skip installing Yarn dependencies, but only to skip compiling webpack assets when calling `bin/rails assets:precompile`.

Let us decide ourselves if we need to install yarn dependencies. This makes both, our deployment and our CI builds slower. We want to handle this, or at least be able to handle this ourselves.

**Comment by jpickwell** [comment]
@mfittko, then you also need to go complain to Rails because it also adds `yarn:install` to `assets:precompile`.

I think because Rails adds `yarn:install` to `assets:precompile`, first an env-var or something would need to be added there first, then Webpacker could use that env-var or whatever to handle the pre-Rails 5.1 situation.

**Comment by jpickwell** [comment]
I have the following `yarn.rake` file in my `lib/tasks` directory.

```ruby
# frozen_string_literal: true

# Remove yarn install tasks as dependencies.
if Rake::Task.task_defined?('assets:precompile')
  task = Rake::Task['assets:precompile']
  task.prerequisites.delete('webpacker:yarn_install')
  task.prerequisites.delete('yarn:install')
end
```

**Comment by mfittko** [comment]
I'll try that out, thanks @jpickwell ! Already did something similar already :)

**Comment by mfittko** [comment]
Okay, just to share this, I'm using following in my CI config now:
```bash
echo "Rake::Task['assets:precompile'].prerequisites.delete('webpacker:yarn_install')" > lib/tasks/yarn.rake
find vendor/bundle -name "yarn.rake" -delete -print | xargs touch
```
Unfortunately, `yarn:install` isn't a prerequisite and I saw no other way than clearing out the file from the rails install in my bundle.

**Comment by guillaumebriday** [comment]
Is this issue still relevant? Feel free to reopen if needed
