### ISSUE TITLE
Disabling ALL images copying to media folder

### ISSUE THREAD

**Issue by hishammalik** [rails/webpacker#1936]
Currently all images or other static assets are now written to the media folder (app/assets/images).

This results in images being copied over to assets/images as well as packs/media. I have lots of images my application and compile webpack locally when deploying and do rsync. Due to this media file containing all unused images file, the deployment time is increased.

So this new feature of copying everything to media is a bug for my use case, and I don't see how I can make it so that only explicitly referenced images in javascript is only copied over to media.

I should be able to use sprockets and webpacker indepedently and having them co-exist without copying over each others unused assets.

**Comment by guillaumebriday** [comment]
Not all images are copied, only the ones that are required in your JS. See https://github.com/rails/webpacker/blob/5-x-stable/docs/assets.md#link-in-your-rails-views

**Comment by hishammalik** [comment]
@guillaumebriday at the time of opening this ticket, that wasn't the case. This is indeed sorted in newer versions
