### ISSUE TITLE
cannot run `./bin/webpack` use bundler v2

### ISSUE THREAD

**Issue by jerrywdlee** [rails/webpacker#1939]
As [here said](https://bundler.io/v2.0/guides/bundler_2_upgrade.html) Bundler updated to v2 on January 2019.
When I installed bundler v2, I cannot run `./bin/webpack` directly, and returns error like

```sh
$ ./bin/webpack
You must use Bundler 2 or greater with this lockfile.
```

BTW, `bundle exec ./bin/webpack`  still works.

**Comment by consti** [comment]
I was able to use `bundler v2` by adding `require 'bundler'` right before the `require 'bundler/setup'` line in both, `bin/webpack` and `bin/webpack-dev-server`

**Comment by jpickwell** [comment]
That's not an issue with Webpacker. That's Bundler telling you that your `Gemfile.lock` file was created by Bundler v2, however you're using an older version of Bundler.

https://github.com/bundler/bundler/blob/v2.0.1/lib/bundler/lockfile_parser.rb#L108

**Comment by connorshea** [comment]
I ran into this issue with webpacker as well, full issue here: https://github.com/bundler/bundler/issues/6937

The solution is to add `require 'bundler'` as @consti mentions, or (once it's released) to upgrade to Ruby 2.6.2.

**Comment by jpickwell** [comment]
Ruby 2.5.3
Bundler 2.0.1
Webpacker 4.0.0-rc.7

No issues.

**Comment by consti** [comment]
@jpickwell the issue only occurs if you have more than one version of bundler installed (under the same version of ruby). E.g. in your setup you can probably replicate the issue by doing a `gem install bundler --version '< 2.0'`.

**Comment by connorshea** [comment]
@jpickwell if you have Bundler as a default gem I’m pretty sure you’re on 2.6, not 2.5

**Comment by jpickwell** [comment]
@connorshea, I don't have 2.6 installed. I did upgrade gem: `gem update --system`

**Comment by hayesr** [comment]
A lot of projects are having this problem, this advice from Jekyll worked for me: https://github.com/jekyll/jekyll/issues/7463#issuecomment-451686361

**Comment by jpickwell** [comment]
So the solution presented in that comment is `gem update --system`.
