### ISSUE TITLE
When upgrading a project to use Webpacker gem, the yarn binstub is not installed

### ISSUE THREAD

**Issue by corporealfunk** [rails/webpacker#1945]
We had a rails 5.2.2 project that we recently started to use with Webpacker.

The documentation for the Webpacker gem list instructions for installing webpacker into existing projects. Webpacker 3.5.5 relies on the fact that Rails supplies a yarn:install rake task:

https://github.com/rails/webpacker/blob/9e671a3ebe368cfdc624309a9b4a55e998f87186/lib/tasks/webpacker/compile.rake#L13

That task, provided by Railties 5.2.2, relies on the fact that there is a ./bin/yarn binstub installed:

https://github.com/rails/rails/blob/6183483fa13bb1cac7e32f64df568fc2f9fb9a6b/railties/lib/rails/tasks/yarn.rake#L11

It calls the binstub with a "system" call, but never checks the return value. If it fails, it dies silently.

When Webpacker is added to an existing project, the ./bin/yarn binstub is never generated.

However, when we install/init a new rails project like this, the binstub is generated by Railties 5.2.2:

`
rails new myapp --webpack
`

Given that this binstub is a requirement for asset precompilation to occur correctly, it seems like the Webpacker gem documentation and installation instructions should indicate somewhere that this binstub is required, and it should indicate how to generate it.

**Comment by wbotelhos** [comment]
Hi @corporealfunk ,

When I try to update the bins the`bin/yarn` is created but than removed. Is this like your problem?

```
$ rails app:update:bin
       exist  bin
   identical  bin/rails
   identical  bin/rake
   identical  bin/setup
      create  bin/yarn
      remove  bin/yarn
```

**Comment by guillaumebriday** [comment]
Is this still an issue @corporealfunk?
