### ISSUE TITLE
postcss config cascading isn't working

### ISSUE THREAD

**Issue by timonbandit** [rails/webpacker#1947]
Hey!
I'm trying to use several postcss.config.js for different folders (different templates) but postcss-loaders loads only one config from the root of a project.
I'm sure this is the problem on this line  get_style_rule.js:31
` config: { path: resolve() },`
I think this is a not correct way of using `path` in postcss-loader because post-css-loader documentation tells us - `Config lookup starts from path.dirname(file) and walks the file tree upwards until a config file is found.`

when I removed this line it helped me.

**Comment by timonbandit** [comment]
small workaround for this issue is changing the rule with postcss-loader
```
environment.loaders.get('sass').use.splice(2, 1, {
  loader: 'resolve-url-loader',
  options: {}
});
```

in `config/webpack.environment.js`

**Comment by guillaumebriday** [comment]
Can this issue be closed ?
