### ISSUE TITLE
Not there looking for content `url()` for `css` files from packages that are in `node_modules`

### ISSUE THREAD

**Issue by denisoster** [rails/webpacker#1956]
Webpack not looking in `node_modules`.
Not there looking for content `url()` for `css` files from packages that are in `node_modules`
How to make a webpack look for the necessary files for packages in `node_modules`?
[Log and application.scss](https://gist.github.com/denisoster/faa8f9df6c7ce5cb5e53658ca5b3e642)

**Comment by jakeNiemiec** [comment]
- Where is `mCSB_buttons.png` getting imported? 

- I see that some of the `import`s are missing a `~` (this generally indicates a reference to something in `node_modules`)

- Remove this line to fix that warning, it may also fix the other problem too https://gist.github.com/denisoster/faa8f9df6c7ce5cb5e53658ca5b3e642#file-environment-js-L8

**Comment by jakeNiemiec** [comment]
`app/javascript/packs/mCSB_buttons.png` If the .png is directly in your packs folder, consider moving it somewhere else so that webpacker doesn't try to compile it.

**Comment by denisoster** [comment]
@jakeNiemiec `~` no need to specify when importing css. 
The  [third and fourth](https://gist.github.com/denisoster/faa8f9df6c7ce5cb5e53658ca5b3e642#file-application-scss-L3-L4) line in my example works fine.
An error occurs when in the CCS there is `url()` this file is in the `node_modules`

**Comment by denisoster** [comment]
> `app/javascript/packs/mCSB_buttons.png` If the .png is directly in your packs folder, consider moving it somewhere else so that webpacker doesn't try to compile it.

It is a bad idea.
In the future, there will be many such packages.
And move every file that is not located. Not safe and long.
Much better to teach webpack search files in `node_modules/name_package`

**Comment by denisoster** [comment]
cast @gauravtiwari

**Comment by jakeNiemiec** [comment]
https://github.com/rails/webpacker#usage
![image](https://user-images.githubusercontent.com/16782063/53127497-35421d00-3528-11e9-94e1-6133865b88f2.png)

>It is a bad idea.

It's kinda just the way things are right now. I don't condone this workflow, but I don't think there are plans to change it. Sorry I couldn't be more helpful.

**Comment by denisoster** [comment]
This is a bug in [Issue resolve-url-loader](https://github.com/bholloway/resolve-url-loader/issues/107)
