### ISSUE TITLE
How to disable gzip generation in "config/webpack/development.js"?

### ISSUE THREAD

**Issue by pedrofurtado** [rails/webpacker#1957]

**Comment by jakeNiemiec** [comment]
It should be only happening in prod:

https://github.com/rails/webpacker/blob/9e671a3ebe368cfdc624309a9b4a55e998f87186/package/environments/production.js#L13

**Comment by pedrofurtado** [comment]
> It should be only happening in prod:
> 
> [webpacker/package/environments/production.js](https://github.com/rails/webpacker/blob/9e671a3ebe368cfdc624309a9b4a55e998f87186/package/environments/production.js#L13)
> 
> Line 13 in [9e671a3](/rails/webpacker/commit/9e671a3ebe368cfdc624309a9b4a55e998f87186)
> 
>  new CompressionPlugin({ 
> It could be your devserver settings:
> [webpacker/package/environments/development.js](https://github.com/rails/webpacker/blob/9e671a3ebe368cfdc624309a9b4a55e998f87186/package/environments/development.js#L24)
> 
> Line 24 in [9e671a3](/rails/webpacker/commit/9e671a3ebe368cfdc624309a9b4a55e998f87186)
> 
>  compress: devServer.compress,

@jakeNiemiec Thanks for feedback! I will check this in my dev environment here, it can be related with the second code snippet that you shared (devServer.compress). Thanks a lot! 👍
