### ISSUE TITLE
Replacing Asset Pipeline, are multiple entries supported?

### ISSUE THREAD

**Issue by dynjo** [rails/webpacker#196]
Experimentally going all in on Webpacker and ideally I want to be able to have my assets split between images, stylesheets and javascripts.

In Webpack this is possible like so:

`entry: {
  application: ["./javascripts/application.js", "./stylesheets/application.css"]
},`

Can I achieve the same thing in `paths.yml` somehow?

**Comment by renchap** [comment]
You can change `config/webpack/shared.js` to provide your own entrypoints.
But you can also directly import your CSS in `application.js`, like this:
```es6
import stylesheet from '~/stylesheets/application';
```

and it will get compiled by Webpack (see `config/webpack/loaders/sass.js` for relevant Webpack config).

**Comment by gauravtiwari** [comment]
@dynjo Is this still an issue for you?

**Comment by dynjo** [comment]
@gauravtiwari not right now, closing.
