### ISSUE TITLE
Cannot remove file extensions from static_assets_extensions

### ISSUE THREAD

**Issue by schpet** [rails/webpacker#1960]
i wanted to use a different loader for svgs, so i added [svgr/@webpack](https://www.npmjs.com/package/@svgr/webpack), removed `- .svg` from static_assets_extensions in my app's webpacker.yml, and added the following to my environment.js:

```
environment.loaders.append("svg", {
  test: /\.svg$/,
  use: ["@svgr/webpack"]
})
```

however this doesn't work because svgs continue to be run through webpacker's `file` loader in addition to the svgr loader.

turns out removing .svg, or any extension, from static_assets_extensions does nothing because the webpacker config and app config get deepMerge'd together, which appends the default static_assets_extensions with the app config ones. 

any reason to deep merge those config files together instead of a shallow Object.assign?
https://github.com/rails/webpacker/blob/c8928d539801d454bcf62069c46bce158b15c63a/package/config.js#L21

**Comment by guilleiguaran** [comment]
I think this is fixed with https://github.com/rails/webpacker/pull/1941, can you confirm?

**Comment by guilleiguaran** [comment]
Let me know if this still happening to re-open this.
