### ISSUE TITLE
JSON parse error

### ISSUE THREAD

**Issue by teamco** [rails/webpacker#1971]
Regarding the following error in `bundle exec foreman start -f Procfile.dev`
`12:22:39 web.1       | 	from ...ruby-2.6.0/lib/ruby/2.6.0/json/common.rb:156:in 'parse': 767: unexpected token at '' (JSON::ParserError)`
`12:22:39 web.1       | 	from ...ruby-2.6.0/lib/ruby/2.6.0/json/common.rb:156:in 'parse'`
`12:22:39 web.1       | 	from ...ruby-2.6.0/gems/webpacker-4.0.0.rc.7/lib/webpacker/manifest.rb:84`

Fix: 
`begin`
`JSON.parse config.public_manifest_path.read`
`rescue`
`{}`
`end`

**Comment by fobiasmog** [comment]
Did you try `rails webpacker:compile`?

**Comment by varalakshmi15** [comment]
> Did you try `rails webpacker:compile`?

Yeah thank you. That's worked for me.

**Comment by eadz** [comment]
I think there is a race condition with `rails test:system`.

When running tests in parallel, I wonder if webpack will read and write the manifest in different threads and that is causing an issue?
