### ISSUE TITLE
Is it possible to pre compile on local, and disable compile on heroku?

### ISSUE THREAD

**Issue by xyingsoft** [rails/webpacker#1982]
I am getting memory exceed error on heroku when I deploy and it took long time.
It would be great if I could pre-compile on my local and disable heroku's webpacker compilation.

Is it possible? then how?

Thanks.

**Comment by gauravtiwari** [comment]
Yes, just compile locally and then `assets:precompile` task will not run on heroku.

**Comment by xyingsoft** [comment]
Okay, thanks, Let me test

**Comment by hopewise** [comment]
Hi @xyingsoft , I got the same issue, servers exploded when I pre-compile react project!
I tried to run locally: `bundle exec rails webpacker:compile` but I got this error:

`Error: Command 'webpacker:compile' not recognized`

Can you please tell me how did you compile locally?
Also, did you set `compile: false` at `production` for `config/webpacker.yml` ?

**Comment by xyingsoft** [comment]
It worked for me. "bundle exec rails webpacker:compile"

**Comment by hopewise** [comment]
ok, I will check, did you leave `compile: true` at production for config/webpacker.yml ?

**Comment by xyingsoft** [comment]
in my case, it is compile: false
