### ISSUE TITLE
Deployment using capistrano generates "incorrect" javascript

### ISSUE THREAD

**Issue by ognevsky** [rails/webpacker#1984]
Hello, 

I've added `webpacker` to already existing application, it worked perfectly in development, but when we deployed it to staging, the page looked different than in development. But when I'm running `./bin/webpack` after the deploy on the staging, everything works perfectly then. 

So, after the deploy some javascript files are created in `public/packs/js` and when I visit the actual page, those files are loaded there (and page looks bad). 
After `./bin/webpack` other files are generated, and new files loaded on the actual page, and the page looks good. 

What I found is `./bin/webpack` generates those files in `development` env, and deploy generates `production` files (gzipped, minified). 
So, when we run `NODE_ENV=development RAILS_ENV=development ./bin/webpack` (which is default), then javascript is regenerated, but with `NODE_ENV=production RAILS_ENV=staging ./bin/webpack` it generates production minified javascript, which is (probably) broken. 

We run the deploy like this: `NODE_ENV=production cap staging deploy`. We run it locally. 

Maybe someone else had something similar? 
Thanks!

**Comment by gauravtiwari** [comment]
@ognevsky Could you please share more details on what is broken? Maybe a screenshot of development and staging app

**Comment by wojtha** [comment]
Hi @gauravtiwari. Thank you for quick response! I am college of @ognevsky. It turns out it was the `extract_css` option and missing `stylesheet_pack_tag` after upgrade to webpacker 4. Please feel free to close this issue.

**Comment by gauravtiwari** [comment]
That's what I suspected too. Glad you figured it out 👍
