### ISSUE TITLE
Webpacker reporting successful compile, but not found in manifest.json

### ISSUE THREAD

**Issue by brentdodell** [rails/webpacker#1985]
Hello, I'm upgrading webpacker from 3.5.3 to the latest release. Here's my current setup that I'm trying to get working:

- Rails v5.1.6
- Webpacker v4.0.2
- @rails/webpacker@^4.0.2
- webpack@^4.29.6
- webpack-dev-server@^3.2.1
- webpack-cli@^3.2.3
- webpacker-react@^0.3.0

My config files: https://gist.github.com/brentdodell/11e23c3696327e6317121f1b07c89f09

My packs appear to be compiling:
<img width="837" alt="screen shot 2019-03-07 at 6 53 51 am" src="https://user-images.githubusercontent.com/9657923/53958092-cf1bd500-40a5-11e9-9a46-89271dc9f130.png">

But when I try to load the page, it says it can't find the files in manifest.json, though they're in manifest.json:
<img width="990" alt="screen shot 2019-03-07 at 6 55 47 am" src="https://user-images.githubusercontent.com/9657923/53958273-30dc3f00-40a6-11e9-8733-25c41099d227.png">
<img width="614" alt="screen shot 2019-03-07 at 6 56 05 am" src="https://user-images.githubusercontent.com/9657923/53958279-35a0f300-40a6-11e9-9292-e88a5becd3b4.png">
<img width="651" alt="screen shot 2019-03-07 at 6 58 12 am" src="https://user-images.githubusercontent.com/9657923/53958517-e27b7000-40a6-11e9-8c41-4cc5c500a795.png">
<img width="660" alt="screen shot 2019-03-07 at 6 58 33 am" src="https://user-images.githubusercontent.com/9657923/53958518-e27b7000-40a6-11e9-8c13-802061b046a5.png">
<img width="697" alt="screen shot 2019-03-07 at 6 59 26 am" src="https://user-images.githubusercontent.com/9657923/53958519-e3140680-40a6-11e9-85ba-aaa740f65c93.png">
<img width="882" alt="screen shot 2019-03-07 at 6 59 55 am" src="https://user-images.githubusercontent.com/9657923/53958521-e3140680-40a6-11e9-84f6-51998441046a.png">
<img width="672" alt="screen shot 2019-03-07 at 7 00 28 am" src="https://user-images.githubusercontent.com/9657923/53958522-e3140680-40a6-11e9-8b5b-9a6fdcf14667.png">
<img width="684" alt="screen shot 2019-03-07 at 7 01 19 am" src="https://user-images.githubusercontent.com/9657923/53958524-e3140680-40a6-11e9-8df2-6aa24de44241.png">

**Comment by sharang-d** [comment]
Can you post the view code which is requiring the wepacker-processed
file/s. More specifically the helper that is being used.

**Comment by brentdodell** [comment]
```ERB
# application.html.erb

<%= javascript_packs_with_chunks_tag [
        'polyfills',
        'FlashMessages',
        'ProductBucket',
        'MembershipPlanCards',
        'WorshipTogetherKids/MembershipPlanCards',
        'igniter/SearchWidget',
        'igniter/analytics',
    ] %>
```

**Comment by gauravtiwari** [comment]
You don't need to declare in the form of array `[ ]`, just a list of packs. See the helper code: https://github.com/rails/webpacker/blob/0b86cadb5ed921e2c1538382e72a236ec30a5d97/lib/webpacker/helper.rb#L72

```erb
<%= javascript_packs_with_chunks_tag 
        'polyfills',
        'FlashMessages',
        'ProductBucket',
        'MembershipPlanCards',
        'WorshipTogetherKids/MembershipPlanCards',
        'igniter/SearchWidget',
        'igniter/analytics'
     %>
```

**Comment by brentdodell** [comment]
Thanks @gauravtiwari! I was was building up the array from different places (layout, view, etc) and forgot to unsplat it `*[]`. That did the trick!
