### ISSUE TITLE
Compile again after adding `extract_css: true` doesn't create css files

### ISSUE THREAD

**Issue by antoinematyja** [rails/webpacker#1986]
Hello, here is my issue :

- I had no `extract_css` in my `config/webpacker.yml` (=> false)
- I ran `bundle exec rails webpacker:compile` which created `public/packs/...` with js files + manifest.json
- I added `extract_css: true` to my `config/webpacker.yml`
- I ran `bundle exec rails webpacker:compile` again

And nothing happened. I had to rm my `public/packs` and compile again.
I guess the second webpacker:compile uses the cache and doesn't see that css files must be built.

**Comment by guillaumebriday** [comment]
Hum I never encountered this issue. Is it still relevant?

Or ran this issue be closed ?
