### ISSUE TITLE
Display an error message when there's a webpacker and @rails/webpacker version mismatch

### ISSUE THREAD

**Issue by connorshea** [rails/webpacker#1991]
I've seen a few people have problems when they unintentionally upgrade the Webpacker gem to 4.x but leave the `@rails/webpacker` npm package on 3.x. I'm not sure if there'd be a good way to check for this, but would it be possible to have an error specific to this situation? Right now it just fails with no obvious explanation, so it could be frustrating/confusing for users.

Do actioncable or activestorage have logic like this anywhere? I know they both have companion packages.

**Comment by guillaumebriday** [comment]
I think for Webpacker and other Rails JS packages/Ruby Gems, it's up to you to upgrade dependencies for JS and Gem to match the same version.

Can this issue be closed ?
