### ISSUE TITLE
How to generate unique CSS classes by css modules and use these classes in rails erb templates?

### ISSUE THREAD

**Issue by sigmaray** [rails/webpacker#1993]
There is an article how to implement rails helpers for CSS modules: https://www.visuality.pl/posts/css-modules-in-rails

I followed this aritcle and added rails helpers to a project.

The only problem with this approach is that CSS class being generated are not unique.

```
// Here we have resourcePath
const generateScopedName = (localName, resourcePath) => {
  const componentName = resourcePath.split('/').pop().replace('.scss', '');

  return Buffer.from(componentName).toString('base64').replace(/\W/, '') + '__' + localName;
};

const myCssLoaderOptions = {
  modules: true,
  sourceMap: true,
  getLocalIdent: (context, localIdentName, localName, options) => {
    return generateScopedName(localName, context.resourcePath );
  },
};
```
```
module CssModulesHelper
  # In rails helpers we don't have access to full path and can't generate unique hashes
  def css_module_class(name, selector)
    "#{encode_selector_name(selector)}__#{name}"
  end

  def encode_selector_name(name)
    Base64.encode64(name).gsub(/\W/, "")
  end
end
```

In `environment.js` it's possible to generate unique hash based on CSS file path. In rails helper we don't have file path, we can only generate a hash based on module name. It can cause collisions: if two css modules with same name would be placed into different directories, they will have same hash. I would prefer to use full path for hashing instead if file name.

Is there a way to inject into CSS class generation process, store class names in some JSON file and parse this file in rails helper?

**Comment by sigmaray** [comment]
It seems it's possible to export class names in postcss modules:
```
postcss([
  require('postcss-modules')({
    getJSON: function(cssFileName, json, outputFileName) {
      var path          = require('path');
      var cssName       = path.basename(cssFileName, '.css');
      var jsonFileName  = path.resolve('./build/' + cssName + '.json');
      fs.writeFileSync(jsonFileName, JSON.stringify(json));
    }
  })
]);
```
(https://github.com/css-modules/postcss-modules#saving-exported-classes)

But if I understood it correctly, webpacker uses modules from css-loader, not from postcss-loaded:
```
const getStyleRule = (test, modules = false, preprocessors = []) => {
  const use = [
    {
      loader: 'css-loader',
      options: {
        sourceMap: true,
        importLoaders: 2,
        localIdentName: '[name]__[local]___[hash:base64:5]',
        modules
      }
    },
    {
      loader: 'postcss-loader',
      options: {
        config: { path: resolve() },
        sourceMap: true
      }
    },
    ...preprocessors
  ]
```
(https://github.com/rails/webpacker/blob/16761e0f627591cbcb0c180912d52d669ca5c7ae/package/utils/get_style_rule.js)

**Comment by guillaumebriday** [comment]
Is this issue still relevant? Feel free to reopen if needed
