### ISSUE TITLE
NODE_ENV set to `development` on test.js config file

### ISSUE THREAD

**Issue by pdfrod** [rails/webpacker#1996]
The file [webpacker/lib/install/config/webpack/test.js](https://github.com/rails/webpacker/blob/651f812886241fc6112c189d99bd01ee92fbb46b/lib/install/config/webpack/test.js) is setting the environment to `development`. Shouldn't it be `test`?

**Comment by leonid-shevtsov** [comment]
I am concerned about this as. well. Trying to get `process.env.NODE_ENV` to be `test` in my Capybara tests and the straightforward methods aren't working.

**Comment by Superpencil** [comment]
Same issue here, had to set it to test to get capybara to pass (cors stuff)

**Comment by swrobel** [comment]
I was looking for the same, and it seems that node handles environments differently than Rails. There's [discussion here](https://github.com/rails/webpacker/issues/1429#issuecomment-381888148), but the key quote is:

> Webpack and node libraries only understands development and production environments.

**Comment by guillaumebriday** [comment]
Can this issue be closed ?

**Comment by Kukunin** [comment]
`process.env.RAILS_ENV` is available in my webpacker assets so I use it in my capybara tests.

Rails 6.1.3.2
webpacker 6.0.0.beta.7
