### ISSUE TITLE
TypeScript + CSS Modules

### ISSUE THREAD

**Issue by radar** [rails/webpacker#1999]
The [documentation for CSS modules](https://github.com/rails/webpacker/find/master) shows a way to import CSS modules with `.js` files. However, I am using TypeScript and it is failing to find the CSS module file when I run `bin/webpack-dev-server`:

```
ERROR in /Users/ryanbigg/code/playground/sunday/app/javascript/packs/hello_react.tsx
./app/javascript/packs/hello_react.tsx
[tsl] ERROR in /Users/ryanbigg/code/playground/sunday/app/javascript/packs/hello_react.tsx(6,20)
      TS2307: Cannot find module '../hello_react/styles/hello-react'.
ℹ ｢wdm｣: Failed to compile.
```

I am not sure what the cause of this problem is. If I rename the file to `hello_react.js`, it _can_ find the file just fine.

Here is an app which reproduces this issue: https://github.com/radar/webpacker-typescript-css-modules

**Comment by gauravtiwari** [comment]
Please see: https://github.com/radar/webpacker-typescript-css-modules/pull/1

**Comment by gauravtiwari** [comment]
perhaps some documentation for this would help?
