### ISSUE TITLE
Bigger default pack, bigger Rails tent. Are the non-react libraries welcome?

### ISSUE THREAD

**Issue by ytbryan** [rails/webpacker#20]
Hi Rails core team, thank you all for webpacker 👍🏻. 

Are the non-react libraries welcome in the default pack? For example, [vuejs](https://vuejs.org)? 

`rails webpacker:install:vuejs`

If yes, I will send in a PR for vuejs code example and rake task. Thank you!

**Comment by dhh** [comment]
Bring it on! We may well want to move to a more formalized plugin system but for now let's just build things out and see where they go.

**Comment by rlafranchi** [comment]
@ytbryan Let me know if there is anything I can do to help.  I started looking at a customizing a webpack template that uses vue-cli, but this sounds pretty awesome 👍

**Comment by dhh** [comment]
I've just added plumbing that we can now trigger these framework-specific hello worlds via the command line. Right now just react is hooked up, but it works like so: `rails new myapp --webpack=react`. We can do the same for vuejs.

Please open a PR when this is ready.
