### ISSUE TITLE
Default installation failing to build.

### ISSUE THREAD

**Issue by sergiotapia** [rails/webpacker#200]
I just added it to an existing app just to try out webpacker.

When I run the `./bin/webpack-watcher` command, I get this error:

```
ERROR in ./app/javascript/packs/application.js
Module build failed: Error: Cannot find module './full-chrome-versions' (While processing preset: "/Users/sergiotapia/Work/example-app/node_modules/babel-preset-env/lib/index.js")
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
```

**Comment by Kilian** [comment]
If you try again, electron-to-chromium is at 1.3.1 now and resolves that issue.

**Comment by sergiotapia** [comment]
@Kilian I'm still getting the error, I guess the babel-preset-env is still grabbing the old version of electron to chromium? How can I force update? I'm using Yarn.

**Comment by Kilian** [comment]
I don't use yarn so I'm not sure, but I would hope `yarn add electron-to-chromium@1.3.1` is enough.

**Comment by sergiotapia** [comment]
The babel-preset-env lib is probably referencing the stale broken version of electron-to-chromium. I'm not sure how to fix this.

**Comment by sergiotapia** [comment]
I just reverted the branch to before adding webpacker and started over.
