### ISSUE TITLE
Seperate to compile different assets on different servers

### ISSUE THREAD

**Issue by wildjcrt** [rails/webpacker#2006]
hi team.

Our repo combines multiple subdomains on different servers.
We need a feature that different server can only compile its own assets.
Is there any way to do this?

**Comment by guillaumebriday** [comment]
Could you give an example of why you want to achieve?

**Comment by wildjcrt** [comment]
for ex, we have front-end servers, back-end servers and api servers.

* api servers: no need to compile assets.
* front-end servers: only need to compile assets for front-end servers
* back-end servers: need to compile assets for front-end and back-end servers

In this case, obviously it's waste time to compile assets for back-end servers in front-end servers.

**Comment by rossta** [comment]
I think this could be relatively straightforward with your own config customization.

Let's say you have two packs, `frontend.js` and `backend.js`:

```sh
app/
  javascript/
    src/ # the rest of your JS source code
    packs/
      frontend.js
      backend.js
```

The default for Webpacker is to compile all the entry points in the packs directory. You could, instead, override the default in your configuration and use an ENV var to dynamically set the entry(s) in the webpack config.

Webpack v6
```js
const { webpackConfig } = require('@rails/webpacker')

const sliceObject = (object, keys) =>
  Object.fromEntries(Object.entries(object).filter(([k, _v]) => keys.includes(k)))

const packs = (process.env.WEBPACKER_PACKS || '').split(',')

module.exports = {
  ...webpackConfig,
  entry: sliceObject(webpackConfig.entry, packs),
}
```

* api servers: either don't run the asset compilation at all, or set `WEBPACKER_PACKS=''`
* front-end servers: set `WEBPACKER_PACKS=frontend`
* back-end servers: set `WEBPACKER_PACKS=frontend,backend`

I don't think there would be enough demand to make this part of the official package, but I could be wrong.

**Comment by wildjcrt** [comment]
cool, it looks good!

**Comment by guillaumebriday** [comment]
Great! thanks @rossta
