### ISSUE TITLE
Avoid using yarn check

### ISSUE THREAD

**Issue by iusztin** [rails/webpacker#2007]
I think it would be better to avoid using `yarn check` in the future. (E.g. the yarn integrity check feature depends on this.)

Why?
- The feature will be removed from `yarn` in the future: https://github.com/yarnpkg/rfcs/pull/106
- It's already considered buggy and its use is officially discouraged: https://github.com/yarnpkg/yarn/issues/6427#issuecomment-434499073

Though I'm not sure about the alternatives currently.
What do you guys think about this?

**Comment by gondalez** [comment]
Would (optionally) running `yarn install` on boot be an alternative?

I imagine it replacing the current `yarn check` mechanism: https://github.com/rails/webpacker/blob/90df6f551eb93c18d104d5ba20ecd898e3cc58cf/lib/webpacker/railtie.rb#L31

Forgive me if this is a silly question 😅

**Comment by connorshea** [comment]
It'll be removed in yarn 2.0, which should be coming sometime in the next few months(?), so we should replace this soon.

**Comment by daneguempel** [comment]
> It'll be removed in yarn 2.0, which should be coming sometime in the next few months(?), so we should replace this soon.

https://github.com/yarnpkg/rfcs/pull/106/files

**Comment by rossta** [comment]
Fixed by https://github.com/rails/webpacker/pull/2518
