### ISSUE TITLE
Avoid compiling at production server

### ISSUE THREAD

**Issue by hopewise** [rails/webpacker#2014]
The only way I could stop compilation at production is to override the compile method!
```
Webpacker::Compiler.class_eval do
  def compile
    if Rails.env == "production"
      logger.info "Skipped Compiling…"
      true
    else
      if stale?
        record_compilation_digest
        run_webpack.tap do |success|
          remove_compilation_digest if !success
        end
      else
        true
      end
    end
  end
end
```

I tried all the possible ways, like settings compile: false at `config/webpacker.yml` I tried also ENV var`WEBPACKER_PRECOMPILE` nothing worked with me..

**Comment by gauravtiwari** [comment]
What version of rails are you using? And what value of `WEBPACKER_PRECOMPILE` did you set?

**Comment by hopewise** [comment]
I set `WEBPACKER_PRECOMPILE ` to `no` and rails version is `4.2.6`

**Comment by gauravtiwari** [comment]
Ahh, that makes sense because that guard clause is only applied in 5+. Would you mind making a PR so it considers this case for both - 4.x and 5.x

This line I mean should enclose both cases: https://github.com/rails/webpacker/blob/master/lib/tasks/webpacker/compile.rake#L44

**Comment by hopewise** [comment]
guard clause ? I am not sure I understand, can you please show me the line that is not supported in rails 4?

the line above is empty

**Comment by gauravtiwari** [comment]
have fixed this on master, will make a release later.

**Comment by gauravtiwari** [comment]
See this commit c506521
