### ISSUE TITLE
Configuring node_modules and package.json to be in a subdirectory

### ISSUE THREAD

**Issue by justin808** [rails/webpacker#2017]
Is it possible to configure the main package.json and node_modules to be within a subdirectory?

Most React on Rails apps use a `/client` directory for all node/JS/front-end related files.

CC: @gauravtiwari

**Comment by robbymarston** [comment]
@justin808 I've got a .yarnrc file in the project root with the following contents:

```
--cwd "client"
```

and `bin/webpack` works as expected (Yarn v1.13.0). That said, in v1.15.2 the [configPath](https://github.com/rails/webpacker/blob/90df6f551eb93c18d104d5ba20ecd898e3cc58cf/package/env.js#L7) isn't resolving correctly, instead it looks for webpacker.yml in `client/config/`. Creating a redundant file or symlink resolves it but is a less-than-desirable workaround.

**Comment by jakeNiemiec** [comment]
@justin808 Related webpacker issue: https://github.com/rails/webpacker/issues/1606
Also: https://github.com/yarnpkg/yarn/issues/6404

@robbymarston I think `modules-folder` may work better than `cwd`... or perhaps a combination of the two? It's my experience that weird things start to happen when you deviate from the general `node_modules` flow. But, I was using npm, so YMMV. Best of luck!

**Comment by justin808** [comment]
I've come around to feeling that it's OK to generally use a top-level node_modules directory for simplicity.
