### ISSUE TITLE
4.0.x: new plugin breaks CSS/SCSS

### ISSUE THREAD

**Issue by jamesarosen** [rails/webpacker#2021]
We're trying to upgrade from `@rails/webpacker@4.0.0-pre.2` to `@rails/webpacker@4.0.2` (JS) and `webpacker@3.5.5` to `webpacker@4.0.2` (Ruby). When we do, we get the following error for _each_ CSS file:

```
Invalid CSS after "": expected 1 selector or at-rule, was "var content = requi"
in /Users/me/code/my_app/app/assets/packs/typefaces.scss (line 1, column 1)
```

When I log the computed Webpack configuration, I notice something new:

```
ConfigObject {
  resolve:
     { extensions:
        [ '.js',
          '.jsx',
          '.cjsx',
          '.coffee',
          '.coffee.cjsx',
          '.scss',
          '.css' ],

       plugins: [ [Object] ],  //  <= This is new:
```

It looks to me like Webpacker is trying to compile some CSS that had been converted into JavaScript, though I don't have any more information than the `var content = requi` in the error message.

**Comment by ngan** [comment]
Can you share the code you’re using to register the plugins? (environment.js)

**Comment by jamesarosen** [comment]
We are continuing to work through the upgrade guide. I will close this for now and reopen if we have any more useful findings.

**Comment by akoskm** [comment]
environment.js:

```
const { environment } = require('@rails/webpacker');
const webpack = require('webpack');
const erb = require('./loaders/erb');
const sass = require('./loaders/sass');
const typescript = require('./loaders/typescript');
const customConfig = require('./custom');

environment.plugins.append(
  'Provide',
  new webpack.ProvidePlugin({
    Popper: ['popper.js', 'default'],
  }),
);

environment.loaders.prepend('erb', erb);
environment.loaders.prepend('sass', sass);
environment.config.merge(customConfig);

environment.loaders.prepend('typescript', typescript);
module.exports = environment;
```

`./loaders/sass`:
```
module.exports = {
  test: /\.(scss)$/,
  use: [
    {
      loader: 'style-loader', // inject CSS to page
    },
    {
      loader: 'css-loader', // translates CSS into CommonJS modules,
      options: {
        importLoaders: 1,
        sourceMap: true,
        modules: true,
      },
    },
    {
      loader: 'postcss-loader', // Run post css actions
      options: {
        plugins: function () {
          // post css plugins, can be exported to postcss.config.js
          return [require('precss'), require('autoprefixer')];
        },
      },
    },
    {
      loader: 'sass-loader', // compiles Sass to CSS
    },
  ],
};
```

things I tried:
 - https://github.com/rails/webpacker/blob/749675d9c035dbc8777f718582e3e4804147e9e5/docs/webpack.md#overriding-loader-options-in-webpack-3-for-css-modules-etc (installed webpack-merge), added `<%= stylesheet_pack_tag 'YOUR_PACK_NAME_HERE' %>`
 - code sample from changelog: https://github.com/rails/webpacker/blob/40a171021f6a89117aed1317957199cf2ca72b98/CHANGELOG.md#added-npm-module-1

and here's the output I'm getting:

```
.table-actions {
^
      Invalid CSS after "": expected 1 selector or at-rule, was "var content = requi"
```

**Comment by Meekohi** [comment]
Hey @akoskm did you find any resolution to this? Looks a lot like our issue... been trying to upgrade to webpacker 4 for over a year and we still can't get anything to work. :'(

**Comment by akoskm** [comment]
@Meekohi I recently removed all this loader configuration from my `environment.js` and I don't have a `./loaders/sass` anymore. While I was trying to add support for css-modules I realized that these loaders are already set up to handle these files https://github.com/rails/webpacker/blob/bdb8673f8ae42af8b2d5c388c9938c3f3826a14f/package/rules/sass.js that calls into `getStyleRule` that sets up the loader chain: https://github.com/rails/webpacker/blob/13756f1ea6b3393117878bb339b9dd507b801eb2/package/utils/get_style_rule.js#L9-L29 for scss 🤷 

I have 0 loader configuration for scss.

**Comment by Meekohi** [comment]
Interesting so everything in `webpacker/package/rules/sass.js` is already included then? It's so hard for me to understand the "Invalid CSS" error it seems like the sass rule isn't triggered in time and it tries to parse it as raw css instead. Wish there was some way for it to output it's full state when hitting that error...

**Comment by akoskm** [comment]
> It's so hard for me to understand the "Invalid CSS" error it seems like the sass rule isn't triggered in time and it tries to parse it as raw css instead. 

Not exactly, if you look at the rest of the error message it tries to parse a javascript:

```
Invalid CSS after "": expected 1 selector or at-rule, was "var content = requi"
```
note the part:
```
"var content = requi"
```

I've seen this in other projects (see https://github.com/vuejs-templates/webpack-simple/issues/107) and can be caused because multiple loaders running through the same file.
