### ISSUE TITLE
Missing reference to stylesheet_packs_with_chunks_tag method in the docs

### ISSUE THREAD

**Issue by erickm93** [rails/webpacker#2025]
I'm using the SplitChunksPlugin on my project and needed to look through the source code to find this helper method.
Since this is a pretty new functionality, from this [PR](https://github.com/rails/webpacker/pull/1901), would be nice to add it to [V4 Upgrade Docs](https://github.com/rails/webpacker/blob/master/docs/v4-upgrade.md) or [CSS Docs](https://github.com/rails/webpacker/blob/master/docs/css.md)

**Comment by guillaumebriday** [comment]
It's been added since this issue has been opened.

I think this issue can be closed
