### ISSUE TITLE
In Production running node with flag --max_old_space_size

### ISSUE THREAD

**Issue by skylertom** [rails/webpacker#2033]
I want to limit the memory usage of node on production - ideally using `--max_old_space_size`.

I've [read that](https://blog.heroku.com/node-habits-2016#7-avoid-garbage) in heroku node(v8) has a limit of 1.5 GB before it starts garbage collection. The current setup only has the server with 2.5 GB, and around 1.5 of that is already taken up by non-webpacker Rails.

I've looked at this issue: #1189 which tries to only set the development webpacker instance.
Can I just adapt [this script](https://github.com/rails/webpacker/issues/1189#issuecomment-359176082) for production like this?
package.json
```
{
  "scripts": {
    "webpacker": "node --max_old_space_size=460 node_modules/.bin/webpack --config config/webpack/production.js"
  }
}
```

**Comment by BassamAziz** [comment]
@stom01 thanks, i've been looking for this. though, it still didn't fix it for me on Heroku. any ideas?

**Comment by seuros** [comment]
Set an environment variable with the value you want
```
NODE_OPTIONS=--max-old-space-size=4096
```

Then run webpack normally. Node will pickup the options from there.

**Comment by wildjcrt** [comment]
I've found an easier way.

Open `bin/webpack` and edit the bottom code like this.
```
APP_ROOT = File.expand_path("..", __dir__)
Dir.chdir(APP_ROOT) do
  ARGV << '--max-old-space-size=500'
  Webpacker::WebpackRunner.run(ARGV)
end
```

Here is the content of `bin/webpack` .
https://github.com/rails/webpacker/blob/master/lib/install/bin/webpack

**Comment by masato-hi** [comment]
Probably related https://github.com/rails/webpacker/issues/2143

**Comment by skylertom** [comment]
Running with @seuros suggestion worked for me

> Set an environment variable with the value you want
> 
> ```
> NODE_OPTIONS=--max-old-space-size=4096
> ```
> 
> Then run webpack normally. Node will pickup the options from there.
