### ISSUE TITLE
typescript install fails if environment.js file uses double quotes instead of single

### ISSUE THREAD

**Issue by jonknapp** [rails/webpacker#2034]
If the file `config/webpacker/environment.js` already exists, there is a possibility for the TypeScript installer to not complete all steps and leave the file in a broken state. The issue appears to be based on the type of quotes (double instead of single) being different than the original file generated by the template.

---------

If starting with nothing, the file `config/webpack/environment.js` gets created after running `bin/rails webpacker:install`:

```node
const { environment } = require('@rails/webpacker')

module.exports = environment
```

If you then run `bin/rails webpacker:install:typescript` you get the correct:

```node
const { environment } = require('@rails/webpacker')
const typescript =  require('./loaders/typescript')

environment.loaders.prepend('typescript', typescript)
module.exports = environment
```

However, if before running the typescript installer you changed the single quotes to double quotes (because of company linter policies/etc) you would get the following instead after running `bin/rails webpacker:install:typescript`:

```node
const { environment } = require("@rails/webpacker")

environment.loaders.prepend('typescript', typescript)
module.exports = environment
```

Since the require statement is not added, future webpack runs fail.

--------

Looking at the source for the installer, it appears to check for an existing string in the file to find where it should insert the line `const typescript =  require('./loaders/typescript')` at.

I haven't verified, but guessing this would effect the Vue, Elm, Coffee, and ERB installers as well based on the usage of `insert_into_file` with an `after:` that uses single quote characters.

**Comment by guillaumebriday** [comment]
Is this still an issue?
