### ISSUE TITLE
NODE_ENV environment variable under webpacker:compile is fixed at "production"

### ISSUE THREAD

**Issue by finfin** [rails/webpacker#2038]
# Scenario
Our system has three stages: development, staging 
Thus we need three separate webpack config 

# What Happened
RAILS_ENV controls what configuration webpacker will use using webpacker.yml
NODE_ENV controls what webpacker will use to customize webpack config

It works as expected when deploying in production
But when NODE_ENV is set to staging, webpack config seems to always loads production.js

After some digging, I found that node_env is forced to "production" when deploying https://github.com/rails/webpacker/blob/c5065217284e4540c07fefc35fe27d33fc531082/lib/tasks/webpacker/compile.rake#L29 

But under our scenario we need node_env other then production (even when deploying)

# Possible solution

A customizable property in webpacker.yml that can assign what node_env we're using (or what webpack config custom file to use)

**Comment by jakeNiemiec** [comment]
‘staging’ is not a valid ‘NODE_ENV’. If you are deploying to a staging server I would recommend setting it to ‘production’. 

There are several other issues discussing this at length, it would probably be better to actively talk about this on one of those.

**Comment by finfin** [comment]
Duplicate of #1395
