### ISSUE TITLE
Include images from webpacker in views

### ISSUE THREAD

**Issue by 0sk4r** [rails/webpacker#2043]
I have a problem with including images in my views. When i try to insert image in my view using html img tag and asset_pack_path i got an error. My images is located in app/javascript/images/logo.png. According to webpacker docs i should append /media/ to file but it does not help. I try diffrent path but it's still not working. I think webpacker doesn't compile my image.

```
Webpacker::Manifest::MissingEntryError in Home#index
Showing app/views/layouts/application.html.haml where line #14 raised:

Webpacker can't find media/logo.png in public/packs/manifest.json. Possible causes:
1. You want to set webpacker.yml value of compile to true for your environment
   unless you are using the `webpack -w` or the webpack-dev-server.
2. webpack has not yet re-run to reflect updates.
3. You have misconfigured Webpacker's config/webpacker.yml file.
4. Your webpack configuration is not creating a manifest.
Your manifest contains:
{
  "application.js": "/packs/js/application-321d1c3bcc175b7f61a6.js",
  "application.js.map": "/packs/js/application-321d1c3bcc175b7f61a6.js.map",
  "entrypoints": {
    "application": {
      "js": [
        "/packs/js/application-321d1c3bcc175b7f61a6.js"
      ],
      "js.map": [
        "/packs/js/application-321d1c3bcc175b7f61a6.js.map"
      ]
    },
    "hello_react": {
      "js": [
        "/packs/js/hello_react-c48c89eaf873362b846b.js"
      ],
      "js.map": [
        "/packs/js/hello_react-c48c89eaf873362b846b.js.map"
      ]
    }
  },
  "hello_react.js": "/packs/js/hello_react-c48c89eaf873362b846b.js",
  "hello_react.js.map": "/packs/js/hello_react-c48c89eaf873362b846b.js.map"
}
```
In my view `application.html.haml`

```
!!! 5
%html
  %head
   = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag    'application'
  %body
    %nav.navbar.navbar-expand-lg.navbar-light.bg-primary
      %a.navbar-brand(href="/")
        %img(src="#{asset_pack_path 'media/logo.png'}")
```

`app/javascript/packs/application.js`
```
require.context('../images', true)

import 'bootstrap'
import './src/application.scss' 

```

`Procfile.dev`
```
web: bundle exec rails s
webpacker: ./bin/webpack-dev-server
```
`webpacker.yml`
```
# Note: You must restart bin/webpack-dev-server for changes to take effect

default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_root_path: public
  public_output_path: packs
  cache_path: tmp/cache/webpacker
  check_yarn_integrity: false
  webpack_compile_output: false

  # Additional paths webpack should lookup modules
  # ['app/assets', 'engine/foo/app/assets']
  resolved_paths: []

  # Reload manifest.json on all requests so we reload latest compiled packs
  cache_manifest: false

  # Extract and emit a css file
  extract_css: false

  static_assets_extensions:
    - .jpg
    - .jpeg
    - .png
    - .gif
    - .tiff
    - .ico
    - .svg
    - .eot
    - .otf
    - .ttf
    - .woff
    - .woff2

  extensions:
    - .jsx
    - .mjs
    - .js
    - .sass
    - .scss
    - .css
    - .module.sass
    - .module.scss
    - .module.css
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg

development:
  <<: *default
  compile: true

  # Verifies that versions and hashed value of the package contents in the project's package.json
  check_yarn_integrity: true

  # Reference: https://webpack.js.org/configuration/dev-server/
  dev_server:
    https: false
    host: localhost
    port: 3035
    public: localhost:3035
    hmr: false
    # Inline should be set to true if using HMR
    inline: true
    overlay: true
    compress: true
    disable_host_check: true
    use_local_ip: false
    quiet: false
    headers:
      'Access-Control-Allow-Origin': '*'
    watch_options:
      ignored: '**/node_modules/**'


test:
  <<: *default
  compile: true

  # Compile test packs to a separate directory
  public_output_path: packs-test

production:
  <<: *default

  # Production depends on precompilation of packs prior to booting for performance.
  compile: false

  # Extract and emit a css file
  extract_css: true

  # Cache manifest.json for performance
  cache_manifest: true
```

**Comment by justinbkay** [comment]
I had this working with Webpacker 3.  The images would import fine with this in my application.js file:
`
require.context('../images', true, /\.(gif|jpg|png|svg)$/i)
`

I upgraded to Webpacker 4 and now that require doesn't work anymore.  My manifest.json file only includes images that are used in my css in url() calls.  

If I move the images directory from `app/javascript/images` to `app/javascript/packs/images` it will then see them and add them to the manifest.json file, but I don't think you should need to do that.  The path names get really long in the manifest file as well. You have to use 'media/packs/images/image.png' in your asset_pack_path method.

**Comment by meatherly** [comment]
@justinbkay getting the same problem

**Comment by AhmedKamal20** [comment]
`asset_pack_path('media/images/logo.png')` is working for me

**Comment by svilenkov** [comment]
> I had this working with Webpacker 3. The images would import fine with this in my application.js file:
> `require.context('../images', true, /\.(gif|jpg|png|svg)$/i)`
> 
> I upgraded to Webpacker 4 and now that require doesn't work anymore. My manifest.json file only includes images that are used in my css in url() calls.
> 
> If I move the images directory from `app/javascript/images` to `app/javascript/packs/images` it will then see them and add them to the manifest.json file, but I don't think you should need to do that. The path names get really long in the manifest file as well. You have to use 'media/packs/images/image.png' in your asset_pack_path method.

I had a similar issue (webpacker 4.2) and the problem was with file base names in the `packs/` dir. I had `application.scss` and `application.js` and the latter becomes empty so the `require.context...` never gets taken into account.
source: https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/118

Hopefully this can help someone

**Comment by marcelolx** [comment]
@0sk4r For me this is working `image_pack_tag "media/images/myimage.png"`. Remember, your images are in `javascripts/images/**` so you need append `media/images/`.

I think this issue could be closed, no?

webpacker version: 5.1.1.

**Comment by vidurpunj** [comment]
def resolve_path_to_image(name)
      path = name.starts_with?("media/images/") ? name : "media/images/#{name}"
      asset_path(current_webpacker_instance.manifest.lookup!(path))
    rescue
      asset_path(current_webpacker_instance.manifest.lookup!(name))
    end

**Comment by stoplion** [comment]
Having same issue. What exactly it "media"? I don't have a media dir in my app.

**Comment by kstratis** [comment]
> `asset_pack_path('media/images/logo.png')` is working for me

Works for me too... the question is .. why?

**Comment by guillaumebriday** [comment]
Can this issue be closed ?
