### ISSUE TITLE
Webpacker does not exit! when running into this error: Compiling… Compilation failed: 

### ISSUE THREAD

**Issue by etagwerker** [rails/webpacker#2045]
Hi there, 

I realize that this issue is very similar to #1028 but I just ran into it. 

Environment: 

- webpacker (4.0.2)
- webpack (4.29.6)

Every now and then the build will fail silently. Everything seems to work but the test log shows something like this: 

```
bin/rake assets:precompile
Compiling…
Compilation failed:
[BABEL] Note: The code generator has deoptimised the styling of /home/app/src/node_modules/nitro-storybook/fonts/regular.js as it exceeds the max of 500KB.

Hash: ed0dc586517a41a70d9f
Version: webpack 4.29.6
Time: 577752ms
Built at: 2019-04-09 10:31:09
                                                                                                                                            Asset       Size  Chunks                    Chunk Names
                                                                                                             js/apm-35b50727cdaacd8cb046.chunk.js   9.08 KiB      32  [emitted]         apm
```

It doesn't seem to call `exit!` as one would expect. (source: https://github.com/rails/webpacker/blob/c5065217284e4540c07fefc35fe27d33fc531082/lib/tasks/webpacker/compile.rake#L35) 

I believe that this commit will solve the problem: https://github.com/rails/webpacker/commit/e43151b8c96f2d750b718a6c4b7921de05846be4

**Comment by etagwerker** [comment]
I'm happy to report that https://github.com/rails/webpacker/pull/1989 fixes this issue. 

@gauravtiwari Would it be possible to get a new version cut for `webpacker` soonish? My project could really use it. Thank you!

**Comment by ch-tactica** [comment]
Did not fix it for me.
