### ISSUE TITLE
strategy for asset compilation on fixed url , not hashed

### ISSUE THREAD

**Issue by michelson** [rails/webpacker#2048]
Hi , just a question .

How can I manage the asset compilation without hash, example `domain/packs/file.js`

I want the name not change in compilation

**Comment by guillaumebriday** [comment]
It's a pretty bad practice because you wouldn't be able to use the browser cache.

Anyway if you really want to you need to override this plugin: https://github.com/rails/webpacker/blob/master/package/rules/file.js

Feel free to close this issue 👍
