### ISSUE TITLE
Change to Using swc with webpack (It's 16x faster than babel.)

### ISSUE THREAD

**Issue by thiensubs** [rails/webpacker#2051]
I read about SWC at https://swc-project.github.io/

It support webpack with https://swc-project.github.io/docs/usage-swc-loader

I thinks webpack should replace babel with swc.

**Comment by jakeNiemiec** [comment]
> This will download prebuilt binary instead of building swc if possible. To use swc in other environments, you should install nightly version of rust first. It can be done with `curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain=nightly`

Not sure too many people would be happy about depending on yet another language. It could work.

**Comment by brodock** [comment]
Sprockets used to rely on a factory pattern that allowed to switch between different javascript runtimes via execjs. I believe here is a perfect situation where we could do the same thing.
