### ISSUE TITLE
style-resources-loader doesn't work

### ISSUE THREAD

**Issue by irbis999** [rails/webpacker#2056]
I added stylus loader, it works
```
const getStyleRule = require('@rails/webpacker/package/utils/get_style_rule')
module.exports = getStyleRule(/\.(styl|stylus)$/i, false, [
  {
    loader: 'stylus-loader?resolve url',
  },
])
```

I also use vue in my project. I want to automaticaly inject file with variables in every <style lang='stylus'> section 

I tried to use style-resources-loader. But in doesn't work.
```
environment.loaders.get('stylus').use.splice(-1, 0, {
  loader: 'style-resources-loader',
  options: {
    patterns: [pathToFileWithVariables],
  },
})
```

Can anybody help me with this?

**Comment by guillaumebriday** [comment]
Is this issue still relevant ?

Or can we closed it ?
