### ISSUE TITLE
Webpacker default react config

### ISSUE THREAD

**Issue by JohnClema** [rails/webpacker#2058]
I currently am configuring a `babel.config.js` for a long lasting rails/webpacker/react project. 

Why does the provided install config use a preset/plugin format of `require('package').default` instead of `'package'`. 

For example [here](https://github.com/rails/webpacker/blob/404751f36f883db19221eeab257a5dbcdbc21540/lib/install/examples/react/babel.config.js) under line 21 `require('@babel/preset-env').default` is used as a preset, why not use `@babel/preset-env`?

**Comment by jakeNiemiec** [comment]
Agree, we should stick closely with what the babel docs say to do. 

If you created a PR, it would probably be accepted.

**Comment by JohnClema** [comment]
Thanks for the quick response 🙏 will do

**Comment by JohnClema** [comment]
Just opened it here: #2060

**Comment by guillaumebriday** [comment]
Can this issue be closed ?
