### ISSUE TITLE
Exclude some specific css from default rules

### ISSUE THREAD

**Issue by robypez** [rails/webpacker#2065]
Hello, I have this issue wirth CKEditor

[https://github.com/ckeditor/ckeditor5-vue/issues/24](https://github.com/ckeditor/ckeditor5-vue/issues/24)

According to the link the solution is excluding CKEditor CSS from default rules defined. 

I have this rule

```
rules: [
            {
                test: /ckeditor5-[^/]+\/theme\/icons\/[^/]+\.svg$/,
                use: [ 'raw-loader' ]
            },
            {
                test: /ckeditor5-[^/]+\/theme\/[\w-/]+\.css$/,
                use: [
                    {
                        loader: 'style-loader',
                        options: {
                            singleton: true
                        }
                    },
                    {
                        loader: 'postcss-loader',
                        options: styles.getPostCssConfig( {
                            themeImporter: {
                                themePath: require.resolve( '@ckeditor/ckeditor5-theme-lark' )
                            },
                            minify: true
                        } )
                    },
                ]
            }
        ]

```

For CSS and SVG of CKEditor I have two specific loaders.

How can I exclude css and svg files from default rules defined in Rails' Webpack config?

In the guide I find: "_By default, the Vue CLI uses [`file-loader`](https://webpack.js.org/loaders/file-loader/) for all SVG files. The `file-loader` copies the file to the output directory and resolves imports into URLs. The CKEditor's UI components use SVG {@link module:ui/icon/iconview~IconView#content source directly} so the theme icons must be loaded using [`raw-loader`](https://webpack.js.org/loaders/raw-loader). If your project uses different approach then CKEditor's UI library you must create different webpack loader rules for your project SVG files and CKEditor's ones._"

More info here: 

[Webpacker Vue Guide](https://github.com/ckeditor/ckeditor5/blob/master/docs/builds/guides/frameworks/vuejs.md)

**Comment by guillaumebriday** [comment]
Is this issue still relevant? Feel free to reopen if needed
