### ISSUE TITLE
How to add separate script tag with webpacker?

### ISSUE THREAD

**Issue by rusikf** [rails/webpacker#2068]
Hi, webpack hackers!

Lets we have application.js => `= javascript_pack_tag 'application'` in view - it is OK
Let's we also have 'datables' library, which I don't want to include in application.js

I want to add it separately like this:
`= javascript_pack_tag 'datables'`

Does it exist a simple way to do it ? :thinking:

**Comment by jakeNiemiec** [comment]
I would just import it in `application.js`. You could also make a `datables.js` pack file with a single import: `import 'datables';`.

**Comment by rusikf** [comment]
Ok thanks, but it also involves creating new file in packs dir:)

чт, 25 апр. 2019, 17:50 Jake Niemiec <notifications@github.com>:

**Comment by jakeNiemiec** [comment]
Well, it _is_ called javascript_**pack**_tag. More info: https://github.com/rails/webpacker#paths

**Comment by guillaumebriday** [comment]
Can this issue be closed ?
