### ISSUE TITLE
datatables issue

### ISSUE THREAD

**Issue by ssnake** [rails/webpacker#2069]
Hey,
I bumped into troubles with webpacker. I'm using Rails 6.beta3 and trying to add Datatables to my app. My steps:

```
 yarn add datatables.net-dt
```
then in `app/javascript/packs/application.js`:

```
require("@rails/ujs").start()
require("turbolinks").start()
require("@rails/activestorage").start()
require("channels")
import 'bootstrap/dist/js/bootstrap';
import 'popper.js/dist/popper.js';

require( 'datatables.net-dt' )();
```
`config/webpack/environment.js`:
```
const { environment } = require('@rails/webpacker')
const webpack = require('webpack')
module.exports = environment
environment.plugins.append('Provide', new webpack.ProvidePlugin({
  $: 'jquery',
  jQuery: 'jquery',
  Popper: ['popper.js', 'default']
}))
```

After this if load a page I get an error in js console:

```
Uncaught TypeError: Cannot set property '$' of undefined
    at DataTable (jquery.dataTables.js:129)
```
`jquery.dataTables.js`:
```
 var DataTable = function DataTable(options) {
    this.$ = function (sSelector, oOpts) { // <---------error is here. Turns out this is not defined variable
      return this.api(true).$(sSelector, oOpts); 
    };
```

Any ideas? Thanks in advance

**Comment by ssnake** [comment]
Opps. Its my bad. I found the issue. At the end of `app/javascript/packs/application.js` there was an error. I thought it didn't make impact on overall performance, but after eliminating of this things started working properly.

**Comment by philsmy** [comment]
Yes, I get the same. I cannot put anything that uses jQuery in the application.js without getting this error.

**Comment by jakeNiemiec** [comment]
@dwood-somniainc @philsmy Did you import jQuery before that line? Can you post the error?

**Comment by dwood-somniainc** [comment]
`
window.jQuery = $;
window.$ = $;
import {} from 'jquery-ujs'
import "./semantic.min"
..
...
require('datatables.net-se')();
require('datatables.net-autofill-se')();
....
require("@rails/activestorage").start();
require("channels");
require("jquery");
`

JS Console Error
```
Uncaught TypeError: Cannot set property '$' of undefined 
at DataTable (jquery.dataTables.js:129)
at Module.<anonymous>
at Module../app/javascript/packs/application.js
at __webpack_require__ (bootstrap:19)
at bootstrap:83
at bootstrap: 83



```
I'm using semantic-ui not bootstrap, btw.

**Comment by jakeNiemiec** [comment]
Looks like you are trying to set jQuery before it is imported. Try:
```js
window.$ = window.$ || require('jquery');
```

**Comment by dwood-somniainc** [comment]
That doesn't seem to be the problem. The error remains.

**Comment by jakeNiemiec** [comment]
@dwood-somniainc Looks like you missed a line in the setup, that should make `$` available. https://github.com/DataTables/Dist-DataTables-SemanticUI#npm

**Comment by dwood-somniainc** [comment]
Nothing seems to work. I tried your approach as well. I'll look at it again in a little while.
