### ISSUE TITLE
Using Webpacker with jQuery without code duplication

### ISSUE THREAD

**Issue by JohnMerlino2** [rails/webpacker#2073]
I want to create a Rails 5 project without using a framework like React. But I want to use jQuery and I also want to use Yarn with jQuery to manage my dependencies.

The Webpacker documentation illustrates usage with a framework like React:

```
rails new myapp --webpack=react

app/javascript:
  ├── packs:
  │ 
  │   └── application.js
  └── src:
  │   └── application.css
  └── images:
      └── logo.svg 

<%= javascript_pack_tag 'application' %>

./bin/webpack and ./bin/webpack-dev-server
```

I found a documentation illustrating how to use it with jQuery and rails-ujs. But it uses both Webpacker and the Assets Pipeline, which makes no sense to me:

```
yarn add jquery
rails yarn:install
gem 'jquery-rails'
//= require jquery
//= require jquery_ujs
//= require turbolinks
//= require_tree .
rails webpacker:install
```

'yarn add' will add jQuery to the Yarn global cache:

$ yarn cache list | grep jquery
jquery  3.4.0 npm https://registry.yarnpkg.com/jquery/-/jquery-3.4.0.tgz#8de513fa0fa4b2c7d2e48a530e26f0596936efdf

So why do we need to install jQuery again via Rails Gemfile? It is extreme code duplication here. The point of using Yarn was to avoid managing the gems through Ruby directly.

Originally asked here:
https://stackoverflow.com/questions/55895666/using-webpacker-with-jquery-without-code-duplication

**Comment by jakeNiemiec** [comment]
I gave an answer, hope it helps: https://stackoverflow.com/a/55906991/6091685

**Comment by jakeNiemiec** [comment]
I gave an answer, hope it helps: https://stackoverflow.com/a/55906991/6091685

**Comment by JohnMerlino2** [comment]
Yes, it worked. However, I added this to javascript/packs/application.js:

import 'jquery';
import 'jquery-ujs';
var Turbolinks = require("turbolinks");
Turbolinks.start();

Yet when I open app in browser, it loads jquery-ujs before jquery and so complains about undefined jquery object in jquery-ujs. I look at public/packs/js/application-60582f53493d022d6972.js and can confirm that jquery-ujs is present in the file before jquery. While I marked the answer correct on SO, I still have this one particular issue.

**Comment by jakeNiemiec** [comment]
This is the rule I use to solve that problem, but I'm not sure how to add a rule like this with vanilla webpackER.
```js
      {
        test: [
          require.resolve('jquery-ujs')
        ],
        use: [
          {
            loader: 'imports-loader',
            options: 'jQuery=jquery,$=jquery'
          }
        ]
      }
```

**Comment by JohnMerlino2** [comment]
Yes, the code snippet you cite resembles what you would place in a Webpack configuration file, like webpack.config.js at the root of a specific node project. However, Webpacker appears to have a different structure. I did find this:

https://github.com/rails/webpacker/blob/master/docs/webpack.md

**Comment by rossta** [comment]
Hope you find these examples helpful:

For Webpack v4 or v5

```js
const { environment } = require('@rails/webpacker')

environment.loaders.append('jquery', {
  {
    test: [
      require.resolve('jquery-ujs')
    ],
    use: [
      {
        loader: 'imports-loader',
        options: 'jQuery=jquery,$=jquery'
      }
    ]
  }
})
```

For Webpack v6:

```js
const { webpackConfig, merge } = require('@rails/webpacker')

const loaders = [
  {
    test: [
      require.resolve('jquery-ujs')
    ],
    use: [
      {
        loader: 'imports-loader',
        options: 'jQuery=jquery,$=jquery'
      }
    ]
  }
]

merge(webpackConfig, {
  module: {
    rules: loaders
  }
})
```
