### ISSUE TITLE
ssr vue.js

### ISSUE THREAD

**Issue by irbis999** [rails/webpacker#2074]
Hello! Did anybody try to make server side rendering with webpacker and vue? 
I want to achieve result similar to official ssr approach https://ssr.vuejs.org/ 
It would be nice to have vue-rendered markup in html at first page load

**Comment by jpickwell** [comment]
To use SSR in Rails, you'll need to use Vue.js components in your Rails views. Part of me thinks that SSR is out of scope for Webpacker, but I could be wrong.

**Comment by ytbryan** [comment]
SSR is possible with hypernova See https://github.com/ytbryan/vue_on_rails_ssr

**Comment by guillaumebriday** [comment]
Can this issue be closed ?
