### ISSUE TITLE
Module not found: Error

### ISSUE THREAD

**Issue by chenkovsky** [rails/webpacker#2076]
ERROR in ./app/javascript/packs/application.js
Module not found: Error: Can't resolve '@rails/ujs' in 'path_to_project/app/javascript/packs'
 @ ./app/javascript/packs/application.js 5:0-21

ERROR in ./app/javascript/packs/application.js
Module not found: Error: Can't resolve '@rails/activestorage' in 'path_to_project/app/javascript/packs'
 @ ./app/javascript/packs/application.js 9:0-31

@rails/activestorage and @rails/ujs exist in node_modules

**Comment by chenkovsky** [comment]
remove 'assets' from .yarnclean solves this problem.

**Comment by mvastola** [comment]
@chenkovsky, I spent *hours* trying to track down this problem. Thank you!
