### ISSUE TITLE
Converting to Webpack

### ISSUE THREAD

**Issue by IanLunn** [rails/webpacker#2079]
Hi, we've been using Webpacker for some time in our Rails project to support a React app. We're now looking at separating the React app from Rails and as much as we like Webpacker, moving to Webpack.

Are there any pointers for making the conversion from Webpacker to Webpack please? I'm assuming there are certain files we can expose then copy/paste with some syntax tweaks and changes to entry/output files.

**Comment by jakeNiemiec** [comment]
There is currently a PR for an eject feature: https://github.com/rails/webpacker/pull/1916#issue-247883688

There is also https://github.com/nikushi/webpack_manifest based on [this article](https://translate.google.com/translate?hl=en&sl=auto&tl=en&u=https%3A%2F%2Finside.pixiv.blog%2Fsubal%2F4615).

**Comment by guillaumebriday** [comment]
thanks @jakeNiemiec
