### ISSUE TITLE
Share asset_host from rails with webpack

### ISSUE THREAD

**Issue by schovi** [rails/webpacker#208]
Today I reach issue, where some of my assets was loaded from same domain as app and not from CDN as i have configured in `environment/production.rb`

(my solution)
```ruby
if ENV['ASSETS_HOST'].present?
  config.action_controller.asset_host = ENV['ASSETS_HOST']
end
```

webpack scripts and styles was handled fine, because url is generated in rails, but all assets loaded inside `.jsx?` or `.css` did not have this domain obviously. It took me some time to find where is root cause of this and then solution was easy.

`config/webpack/configuration.js`

from
```javascript
const publicPath = env.NODE_ENV !== 'production' && devServer.enabled ?
  `http://${devServer.host}:${devServer.port}/` : `/${paths.entry}/`
```

to

```javascript
let publicPath
if (env.NODE_ENV !== 'production' && devServer.enabled) {
  publicPath = `http://${devServer.host}:${devServer.port}/`
} else {
  publicPath = `${env.ASSETS_HOST}/${paths.entry}/`
}
```

My opinion is, it should be shared across whole environment by default, because it can cause lot of confusion, but on other hand I can't find solution, which can be done without changing something directly in rails gem.

**Comment by gauravtiwari** [comment]
Fixed by #224
