### ISSUE TITLE
@babel/polyfill deprecated since babel v7.4.0

### ISSUE THREAD

**Issue by 0xdevalias** [rails/webpacker#2081]
https://babeljs.io/docs/en/next/babel-polyfill
> As of Babel 7.4.0, this package has been deprecated in favor of directly including core-js/stable (to polyfill ECMAScript features) and regenerator-runtime/runtime (needed to use transpiled generator functions)

In our project we have already moved to this new recommended method, but webpacker is causing us to pull down `@babel/polyfill` still.

It would be cool to somehow remove the direct dependency on `@babel/polyfill` so we can use our own.

It's included here: https://github.com/rails/webpacker/blob/master/package.json#L22

**Comment by jakeNiemiec** [comment]
Also see: https://github.com/rails/webpacker/pull/2031

**Comment by aried3r** [comment]
Can this be closed? Ping @gauravtiwari
