### ISSUE TITLE
Bundler could not find compatible versions for gem "railties" and "activesupport"

### ISSUE THREAD

**Issue by reckerswartz** [rails/webpacker#2084]
This issue is on Rails master branch.
ticket reference https://github.com/rails/rails/issues/36112
Bundler could not find compatible versions for gem "activesupport":
In Gemfile:
    rails was resolved to 6.1.0.alpha, which depends on
      activesupport (= 6.1.0.alpha)

    webpacker was resolved to 4.0.2, which depends on
      activesupport (>= 4.2)

Bundler could not find compatible versions for gem "railties":
  In Gemfile:
    rails was resolved to 6.1.0.alpha, which depends on
      railties (= 6.1.0.alpha)

    sass-rails (~> 5) was resolved to 5.0.4, which depends on
      railties (>= 4.0.0, < 5.0)

    web-console was resolved to 4.0.0, which depends on
      railties (>= 6.0.0.a)

    webpacker was resolved to 4.0.2, which depends on
      railties (>= 4.2)

**Comment by guillaumebriday** [comment]
It doesn't seem you install your gems properly

But I think it's not relevant anymore
