### ISSUE TITLE
Multiple packs same name different extension

### ISSUE THREAD

**Issue by ionutzp** [rails/webpacker#2088]
If one adds multiple packs with the same name but a different extension for example `application.scss` and `application.js` only the last one will make it to the webpack entry path configuration. This is done [here](https://github.com/rails/webpacker/blob/master/package/environments/base.js#L65)

Expected behaviour would be that both paths are kept in the webpack entry paths

**Comment by antonlabs** [comment]
You literally saved me hours of struggle :+1: :tada:

**Comment by Siva-Ganesh-VR** [comment]
Take a look

https://stackoverflow.com/questions/58506351/webpacker-throws-application-css-not-found-in-manifest-json-in-rails-6-applica

**Comment by rossta** [comment]
I'm not sure this is a Webpacker bug. I get that the behavior is not what's expected—it is most certainly different that Sprockets. I believe the underlying dissonance is that Webpack entry points (which we're calling "packs" in Webpacker) are typically configured as JS object key => value pairs, i.e., the property `application` can only be used once in an object. https://webpack.js.org/concepts/entry-points/

It might be weird to key the entry points including the extension—this would yield output names like `application.js.js`, `application.css.css`. Perhaps another fix could be for Webpacker to detect duplicate names and exit with a helpful error message.

For those finding this issue and wondering what to do, I'd recommend the "Webpack way" here would be to use a single entry point, your `application.js` pack, and `import '../application.css'` from there.

**Comment by rossta** [comment]
Fixed by https://github.com/rails/webpacker/pull/2476
