### ISSUE TITLE
ts-loader is compiling node_modules

### ISSUE THREAD

**Issue by corymcdonald** [rails/webpacker#2091]
Not sure if anyone sees similar behavior, but I'm seeing some errors where when I import something from node_modules that uses typescript I'm getting the following.

```
ERROR in ./node_modules/brave-ui/theme/palette.ts
Module build failed (from ./node_modules/ts-loader/index.js):
Error: TypeScript emitted no output for /Users/cory/repos/publishers/node_modules/brave-ui/theme/palette.ts. By default, ts-loader will not compile .ts files in node_modules.
You should not need to recompile .ts files there, but if you really want to, use the allowTsInNodeModules option.
See: https://github.com/Microsoft/TypeScript/issues/12358
    at makeSourceMapAndFinish (/Users/cory/repos/publishers/node_modules/ts-loader/dist/index.js:78:15)
    at successLoader (/Users/cory/repos/publishers/node_modules/ts-loader/dist/index.js:68:9)
    at Object.loader (/Users/cory/repos/publishers/node_modules/ts-loader/dist/index.js:22:12)
```

I tracked this down and think it's related to this 
https://github.com/TypeStrong/ts-loader/issues/803

I looked at my webpack config and it looks like Webpacker is including those modules 

```javascript
{ extensions:
   [ '.ts',
     '.jsx',
     '.tsx',
     '.mjs',
     '.js',
     '.sass',
     '.scss',
     '.css',
     '.module.sass',
     '.module.scss',
     '.module.css',
     '.png',
     '.svg',
     '.gif',
     '.jpeg',
     '.jpg' ],
  plugins:
   [ { apply: [Function: nothing],
       makePlugin: [Function],
       moduleLoader: [Function],
       topLevelLoader: [Object],
       bind: [Function],
       tsLoaderOptions: [Function] } ],
  modules:
   [ '/Users/cory/repos/publishers/app/javascript',
     'node_modules' ] }
```

I looked at the source and wasn't able to find any way of overriding these values to get rid of it https://github.com/rails/webpacker/blob/b041a1d3e53c55ad801654892c99f5ec4ff099f2/package/environments/base.js#L73

**Comment by corymcdonald** [comment]
This occurred while I was upgrading from 4.0.0.RC2, so i'm not quite sure if I just downloaded a new version of a library that wasn't happy with stuff, or what. But right now I reverted back to my `yarn.lock` and I was able to compile again ✔️

**Comment by jakeNiemiec** [comment]
Webpacker compiles `node_modules` by default: https://github.com/rails/webpacker/blob/2387331b33c635ec7638af3fad5856cd5b1ea8c2/docs/v4-upgrade.md#excluding-node_modules-from-being-transpiled-by-babel-loader

**Comment by corymcdonald** [comment]
Since you can exclude them this is probably not an issue. Closing 😄
