### ISSUE TITLE
Yarn 2.0 (Yarn Plug’n’Play)

### ISSUE THREAD

**Issue by jakeNiemiec** [rails/webpacker#2112]
Summary from whitepaper:
Pros: 
- smaller install
- faster install
- better matches how gems behave
- better install & cache for CIs
- better peer dependencies 
- users working on multiple projects across a system won’t pay in-creasing install costs
- no `node_modules` folder

Cons: 
- no `node_modules` folder (some webpacker stuff currently relies on this). You also can't edit anything in `node_modules`
- packages must be accessed via yarn cache
- packages cannot rely on cross package boundaries (e.g.: webpacker users can't rely on the sub-dependencies of `@rails/webpacker` as if they were direct dependencies)

Resources:
- [overview](https://yarnpkg.com/en/docs/pnp)
- [getting-started](https://yarnpkg.com/en/docs/pnp/getting-started)
- [troubleshooting](https://yarnpkg.com/en/docs/pnp/troubleshooting)
- [whitepaper](https://github.com/yarnpkg/rfcs/files/2378943/Plugnplay.pdf)
- [webpack plugin](https://github.com/arcanis/pnp-webpack-plugin)

Newer links:
- https://dev.to/arcanis/introducing-yarn-2-4eh1
- https://next.yarnpkg.com/getting-started
- https://next.yarnpkg.com/advanced/migration

**Comment by omnilord** [comment]
Will pnp put all the modules in a singular global source of truth location on the local system, or will this still require downloading at least one new copy of them from the internet at every install, even if another project already uses the same version?

**Comment by jakeNiemiec** [comment]
From [the whitepaper](https://github.com/yarnpkg/rfcs/files/2378943/Plugnplay.pdf) (very short read):
>In its current state, running yarn install does the following under the hood -assuming a cold setup:
>1. Dependency ranges are resolved into pinned versions
>2. Packages for each version are fetched from their sources and stored in the offline mirror
>3. The offline mirror is unpacked into the cache
>4. The cache is copied into thenode_modulesfolders
>
>**Our solution aims to trim the fourth step from the equation**. Instead of copying each and every file from the cache to the node_modules folder (which can take a lot of time, amplified by the sheer number of files), we will instead generate a single file that will contain static resolutions tables that list:
>- What packages are available in the dependency tree
>- How they are linked together
>- Where they are located on the disk

So, instead of 100M of modules in a `node_modules` folder, that 100M is cached and you get a file that acts as a map to the modules that you need. No more filesystem traversal.

**Comment by paracycle** [comment]
PnP was exactly what I thought about when I read the thread at https://github.com/rails/rails/pull/36282, great to see there is a will to tackle this.

I would be interested in taking a look at implementing this but I am _super_ new to webpacker. Let me see how fast I can get familiar with it to make a contribution.

**Comment by jakeNiemiec** [comment]
I have tried it out and can confirm that webpacker needs to implement something like peerDependencies in order to make this work. Error with the default setup: `You cannot require a package ("@babel/preset-env") that is not declared in your dependencies`:
<details>

Add this to `package.json` to enable.
```json
"installConfig": {
    "pnp": true
  }
```

The errors

```error
Uncaught Error: Module build failed (from /Users/user/Library/Caches/Yarn/v4/npm-babel-loader-8.0.6-e33bdb6f362b03f4bb141a0c21ab87c501b70dfb/node_modules/babel-loader/lib/index.js):
Error: You cannot require a package ("@babel/preset-env") that is not declared in your dependencies (via "/Users/user/webpacker_tests/hello/babel.config.js")
    at makeError (Users/user/webpacker_tests/hello/.pnp.js:55)
    at Object.resolveToUnqualified (Users/user/webpacker_tests/hello/.pnp.js:11126)
    at Object.resolveRequest (Users/user/webpacker_tests/hello/.pnp.js:11204)
    at Function.Module._resolveFilename (Users/user/webpacker_tests/hello/.pnp.js:11386)
    at Function.Module._load (Users/user/webpacker_tests/hello/.pnp.js:11302)
    at Module.require (internal/modules/cjs/loader.js:637)
    ...
```

![image](https://user-images.githubusercontent.com/16782063/58907903-d1a5bf00-86d4-11e9-90ee-925fbed35dad.png)

</details>

If you meticulously install all of the deps you need with PnP, the starter files will actually compile successfully:
<details>

![image](https://user-images.githubusercontent.com/16782063/58908602-9ad0a880-86d6-11e9-9bf5-72ef82f5f420.png)

</details>

@gauravtiwari, This is only possible since you already did some work last year to enable PnP 🎉: https://github.com/rails/webpacker/pull/1823/files#diff-1701de23f718ce36149c9b23e2db08caR95

First glance action items:

- [ ] Fix `check_yarn_integrity` to do something like [this PR](https://github.com/facebook/create-react-app/pull/5269/files)
- [ ] Find a way to `hoist` deps to the users "top" `package.json`. Here is an [example that of another CLA tool doing this](https://github.com/facebook/create-react-app/pull/3876/files#diff-f8cdc1c146e13a6df22d7bda9c8d17c7R75)
  - [ ] Figure out which deps need to get hoisted from [`package.json`](https://github.com/rails/webpacker/blob/master/package.json#L14). This would include everything `require()'d` in [package/environments/base.js](https://github.com/rails/webpacker/blob/master/package/environments/base.js)
- [ ] Should PnP be the default?
- [ ] `require("channels")` needs to be changed to `require("../channels")`. Otherwise it throws an error because it looks for a package called `channels`.

**Comment by gauravtiwari** [comment]
Thanks @jakeNiemiec Sorry about the delay. I will take a look tomorrow and get back to you.

**Comment by somebody32** [comment]
just my 2 cents on `Should PnP be the default?`: https://twitter.com/sebmck/status/1137059802838757377?s=20. Obviously, Facebook's scale is a different story, but anyway

**Comment by jakeNiemiec** [comment]
[Yarn 2.0 summary post](https://dev.to/arcanis/introducing-yarn-2-4eh1)

With `yarn@2` released, I assume that other users will attempt to upgrade and use with webpacker. This will not work since [yarn now enforces package boundaries](https://dev.to/arcanis/introducing-yarn-2-4eh1#strict-package-boundaries).

**Comment by swrobel** [comment]
FWIW I attempted to use Yarn 2 about 4 months ago to see what would happen w/ Webpacker, and this is the discussion it led to on the Yarn 2 (aka berry) repo: https://github.com/yarnpkg/berry/issues/494

**Comment by jakeNiemiec** [comment]
> not asking for help

Sorry, both me and @arcanis have tried to assist you with the same problem for nearly 2 years ([2018](https://github.com/yarnpkg/yarn/issues/5749#issuecomment-393140599), [Oct 2019](https://github.com/rails/webpacker/issues/1537#issuecomment-539133786), [Nov 2019](https://github.com/yarnpkg/berry/issues/494#issuecomment-553654092)). That help was for @arcanis to understand this _bundler business_ we find ourselves in.

**Comment by jakeNiemiec** [comment]
I wanted to add this resource for anyone looking to try this out: https://next.yarnpkg.com/getting-started

It now occurs to me that migrating to Yarn 2.0 will require 2 major efforts:
- Migrating the Webpacker repo to Yarn 2
- Migrating user's Webpacker setups to Yarn 2

Both of these involve cutting reliance on `node_modules`. See more in the migration guide: https://next.yarnpkg.com/advanced/migration

**Comment by doits** [comment]
Shouldn't it work with `nodeLinker: node-modules` in `.yarnrc.yml` (https://yarnpkg.com/configuration/yarnrc#nodeLinker)? It doesn't use pnp then and the good old `node_modules` folder is still present.

**Comment by arcanis** [comment]
Yes, that would be the ideal migration for Webpacker / Rails. That's what we typically recommend in our [migration guide](https://yarnpkg.com/getting-started/migration#step-by-step):

> Don't worry if your project isn't quite ready for Plug'n'Play just yet! This guide will let you migrate **without losing your node_modules folder**, and only in a later optional section we will cover how to enable PnP support (which is recommended, but not mandatory). Baby steps! 😉

**Comment by doits** [comment]
I just tested it and it seems to work with two additional steps. I did this to upgrade and it is working in my development setup:

```shell
$ yarn set version berry
$ echo nodeLinker: node-modules >> .yarnrc.yml
$ yarn
$ yarn add webpack@^4.0 webpack-cli@^4.0 # otherwise it will complain about not finding the binary `webpack`
```

Compiling in development mode!

**Comment by doits** [comment]
I created #2799 with the changes needed to experimentally support Yarn 2, e.g. not to break when Yarn 2 is used.

**Comment by n-rodriguez** [comment]
> I created #2799 with the changes needed to experimentally support Yarn 2, e.g. not to break when Yarn 2 is used.

Thank you! It works here :)

**Comment by jrochkind** [comment]
Is there any word of plans/intentions from webpacker/rails maintainers?

**Comment by justin808** [comment]
Hi @shamrt, can you tell us a bit more about your requirements for rails/webpacker with react_on_rails?

@guillaumebriday, maybe I can add a test case for react_on_rails using yarn v2? I could update https://github.com/shakacode/react_on_rails_tutorial_with_ssr_and_hmr_fast_refresh with yarn v2?

@guillaumebriday it seems odd that rails/webpacker has to worry about very specific flags for yarn. Seems out of scope for the project and a good example of how keeping things leaner is better.

**Comment by justin808** [comment]
Feel free to reopen this issue here: 
https://github.com/shakacode/shakapacker/issues

**Comment by jrochkind** [comment]
Thanks @justin808 , can you provide a link explaining the origin of `shakapacker`. It says "Official, actively maintained fork of rails/webpacker" -- but I don't understand what that means, official according to whom, is there something not "official" or "actively maintained" about this repo that I hadn't heard, is there some coordination/hand-off from rails to that team, is there news I missed somewhere?

**Comment by justin808** [comment]
@dhh suggested the name for the fork 😄  and it's listed on the README.md for https://github.com/rails/webpacker.
