### ISSUE TITLE
With ts-loader, files aren't correctly cached if there is a compilation error. This leads to too many or too few calls to compile.

### ISSUE THREAD

**Issue by Taytay** [rails/webpacker#2113]
Webpacker 4.0.2 with ts-loader 6.0.1.

Summary: The cache file: `tmp/cache/webpacker/last-compilation-digest-development` is only updated if webpack compilation succeeds. However, even though ts-loader fails the webpack build if there is a Typescript error, webpack still emits an updated manifest.json and an output .js file. So, if you introduce an error in your source Typescript file and the webpack compiler runs, the cache file will still indicate that the output is based on the contents of the file BEFORE the error was introduced. So, if you then undo your change to the source file and reload the page, webpack is NOT invoked as it should be.

Furthermore, this means that as long as there is an error in any Typescript file, webpack will ignore the cache and will ALWAYS invoke compilation, causing repeated compilations of the exact same files with the exact same source.

Details:

Not using webpack dev server, but compiling on demand, meaning that it should only compile if there is a change.

I have a file in app/javascript/packs/authentications.ts that compiles correctly.
I load my login page and see that Webpack is compiling, as I expect:
```
web_1       | 18:07:28 web.1               | [Webpacker] Compiling…
web_1       | 18:07:39 web.1               | [Webpacker] Compiled all packs in /app/ynab_api/public/assets/packs
web_1       | 18:07:39 web.1               |   Rendered authentications/new.html.erb within layouts/application (10567.7ms)
web_1       | 18:07:39 web.1               |   Rendered shared/_favicon.erb (20.3ms)
web_1       | 18:07:39 web.1               | Completed 200 OK in 10919ms (Views: 10904.9ms | ActiveRecord: 0.0ms)
````
I look at my cache file and see:
```
$ cat tmp/cache/webpacker/last-compilation-digest-development
66a64d57cdc91eabf692e2bc6318c555fa6e10b2%
```

So far, so good. Now, introduce a compile error and reload the page.
Again, it compiles, but this time it displays a compilation error. So far, so good:
```
web_1       | 18:09:25 web.1               | [Webpacker] Compiling…
web_1       | 18:09:35 web.1               | [Webpacker] Compilation failed:
web_1       | 18:09:35 web.1               |
web_1       | 18:09:35 web.1               | Hash: 63e8d239697434693810
web_1       | 18:09:35 web.1               | Version: webpack 4.29.6
web_1       | 18:09:35 web.1               | Time: 8590ms
web_1       | 18:09:35 web.1               | Built at: 2019-05-31 18:09:35
web_1       | 18:09:35 web.1               |                                      Asset       Size           Chunks             Chunk Names
web_1       | 18:09:35 web.1               | js/authentications-f513c39af604d8951a62.js    377 KiB  authentications  [emitted]  authentications
web_1       | 18:09:35 web.1               |            js/otps-822bdb1661898df52846.js   5.48 KiB             otps  [emitted]  otps
web_1       | 18:09:35 web.1               |                              manifest.json  391 bytes                   [emitted]
web_1       | 18:09:35 web.1               | Entrypoint authentications = js/authentications-f513c39af604d8951a62.js
web_1       | 18:09:35 web.1               | Entrypoint otps = js/otps-822bdb1661898df52846.js
web_1       | 18:09:35 web.1               | [./app/javascript/packs/authentications.ts] 39 KiB {authentications} [built] [1 error]
web_1       | 18:09:35 web.1               | [./app/javascript/packs/otps.coffee] 1.65 KiB {otps} [built]
web_1       | 18:09:35 web.1               | [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 878 bytes {authentications} [built]
web_1       | 18:09:35 web.1               |     + 5 hidden modules
web_1       | 18:09:35 web.1               |
web_1       | 18:09:35 web.1               | ERROR in /app/ynab_api/app/javascript/packs/authentications.ts
web_1       | 18:09:35 web.1               | ./app/javascript/packs/authentications.ts
web_1       | 18:09:35 web.1               | [tsl] ERROR in /app/ynab_api/app/javascript/packs/authentications.ts(6,1)
web_1       | 18:09:35 web.1               |       TS2304: Cannot find name 'asdfsfsd'.
```

But now the output `.js` file and `manifest.json` HAS been updated, but the cache file has NOT been updated!
```
$ cat tmp/cache/webpacker/last-compilation-digest-development
66a64d57cdc91eabf692e2bc6318c555fa6e10b2%
```

So now, if I undo my change to the source file, restoring the source authentications.ts file to the state it was in before the error and reload the page, I do NOT see Webpack compile my file. 

And of course, the manifest.json and output .js files remain the same, meaning that the compiled file loaded is the one compiled based on the error-containing source file.

**Comment by jakeNiemiec** [comment]
Could it be related to that error message? 
```error
[tsl] ERROR in /app/ynab_api/app/javascript/packs/authentications.ts(6,1) 
  TS2304: Cannot find name 'asdfsfsd'.
```

**Comment by Taytay** [comment]
Hey @jakeNiemiec : Thanks for the response. That was an intentionally introduced error in my Typescript. My point is that _any_ error in the Typescript will cause the cache file and the output to get out of sync, meaning that compilations don't happen when they should, or that compilations happen repeatedly, as long as there is an error. It is common in development to have compilation errors, and then to fix them, but with this bug, fixing the error might mean that the source doesn't get recompiled when it should. It might silently skip compilation, leading to a very-difficult-to-track-down bug. :)

**Comment by jakeNiemiec** [comment]
After some more sleuthing, I think this is the cause of the problem: https://github.com/rails/webpacker/pull/1764

```ruby
# lib/webpacker/compiler.rb:18
  def compile
    if stale?
      run_webpack.tap do |success|
        record_compilation_digest if success
      end
    else
      true
    end
  end

  # Returns true if all the compiled packs are up to date with the underlying asset files.
  def fresh?
    watched_files_digest == last_compilation_digest
  end

  # Returns true if the compiled packs are out of date with the underlying asset files.
  def stale?
    !fresh?
  end
```
I think I have a good idea of what you mean, record_compilation_digest might need to run regardless of `success`, but I can't tell if #1764 would regress if we did that. Could you create a PR that works with your situation?

**Comment by Taytay** [comment]
Thanks! In looking briefly at #1764, it looks like that did two things. One of them is to make sure that the cache file isn't written to until AFTER webpack is finished. Unfortunately, it also only wrote to the cache file if webpack succeeded. I'll try _always_ writing to the cache file, regardless of whether or not webpack succeeded, but only after it's done, and let you know how it works. Does that sound right to you?

**Comment by jakeNiemiec** [comment]
Yes, if you make a PR that works with your TS, I can test the fork against #1764.

**Comment by jakeNiemiec** [comment]
I guess the WDS overlay never worked even though it was enabled by default in the webpacker.yml file. 

This is probobly the reason that webpack still spits out a build when there is an error. Ideally, you should get something like this in your browser:
![image](https://user-images.githubusercontent.com/16782063/58735074-ecb7bc80-83be-11e9-807f-ea92f910ae74.png)

I am fairly certain that removing `if success` will fix your problem and unblock this feature.

**Comment by Taytay** [comment]
@jakeNiemiec  - actually, when I used the WDS, I did see the overlay! If I don't use the WDS though, it compiles on demand, and that's when I see this issue.

**Comment by Taytay** [comment]
@jakeNiemiec : I made this change in my own local Gem and confirmed it worked. (The digest was always updated, whether i had an error or not. Furthermore, I didn't get continuous recompilations in the case of a Typescript error, and after I undid the changes that led to the error, I correctly got a recompilation as expected). I was not able to test against #1764, as I am not sure what those exact circumstances were. Based on the description, I would think that tapping Webpack and writing the digest in that block would indeed only happen AFTER Webpack runs.

**Comment by jakeNiemiec** [comment]
I'll wait a few days for the other dev to respond. In the meantime, I'll kick the tires to see that everything still works.

Thanks for your contribution.

**Comment by IlkhamGaysin** [comment]
Guys, I had memory allocation error during deployment as the digest was set the redeploy didin't compiled assets. I think it's a bug as I expect the digest to be the same as there wasn't any change of assets! Do you need config files from me of my rails app?

![image](https://user-images.githubusercontent.com/17009998/76625534-80223e80-6548-11ea-9a96-e617980b6983.png)
