### ISSUE TITLE
Can't run a bundle without the Webpacker gem in the host app?

### ISSUE THREAD

**Issue by zedtux** [rails/webpacker#2119]
I'm developing a Rails engine including a React app, so I'm using the webpacker gem.

I don't want to force people using my gem to have the webpacker gem  in their app, so I'm including the `public/*-pack/` folder (generated by the `rails build` command which runs webpack) in my gem, but I do not include the React source files, nor the `config/webpacker.yml` file, nor the `config/webpacker` folder.
See [the gemspec file](https://gitlab.com/pharmony/active_record_migration_ui/blob/master/active_record_migration_ui.gemspec#L27).

I have written [a little piece of Js to replace the `javascript_pack_tag` and `stylesheet_pack_tag` helpers](https://gitlab.com/pharmony/active_record_migration_ui/blob/master/app/views/layouts/active_record_migration_ui/application.html.erb#L15).

After having installed manually the gem file in my env, referenced it in my host app's `Gemfile`, and restarted my server, the Css loads fine, and the Js has loaded, but the React app doesn't run. I tried to copy/past the Js code in the Chrome's console, and it return `true`.

My understanding of webpack is that it builds a bundle with all my Js and Css files so that I can use them in any HTML files without having webpack nor webpacker installed.

Is my understanding wrong?

How can I see what's going wrong and fix it?

**Comment by jakeNiemiec** [comment]
Webpacker cannot pull JS from gems like sprockets. You would need to require your app via `package.json` in order for webpacker to have access to it. You can avoid this, but I would recommend the same sibling gem<=>package link setup that webpacker and rollbar uses.

If you tell me a bit more about the requirements of your app, I could walk you through it. Why does the react app need to be inside an engine? What does the react app do?

**Comment by zedtux** [comment]
I gave links to my gem so that you can have a look.

So the engine is providing a small app to run the rails migration scripts from the web browser (see the [README.md](https://gitlab.com/pharmony/active_record_migration_ui) file).

Can't just webpack export a bundle that can be imported as any other Js libraries?

**Comment by jakeNiemiec** [comment]
WebpackER is not set up to generate a bundle that can be re-bundled in a downstream app. **For an easy solution, I would mirror what the ahoy gem does here**: https://github.com/ankane/ahoy#javascript

Another great example is how active storage uses rollup to downstream JS https://github.com/rails/rails/blob/master/activestorage/rollup.config.js. Even they need to mirror their package on the JS registry: https://www.npmjs.com/package/@rails/activestorage

<hr>

How to author a library with vanilla webpack: https://webpack.js.org/guides/author-libraries

Misc concerns:
- Publish JS in a consumable format
- Downstream users will _probably_ need `react` as a dev dependency in their `package.json`. This is the same reason that `rails/webpacker` users need `webpack-dev-server` in their `package.json`.
- If a compiled js file (containing react) is loaded on a page that also has react, react will complain and refuse to render.
- Make sure you use a dynamic import with your app so users don't load your app code on every page load e.g.: 
`window.display_migration_warning = (props) => import('active_record_migration_ui', ()=> some_callback(props));`

You are one of many pioneers in this specific problem space. I doubt these pain-points will remain the same for long. There are many potential optimizations that I am just unfamiliar with.

**Comment by zedtux** [comment]
Okay thank you very much @jakeNiemiec for your nice comment, I'll review all that info and back to you soon.

The first thing I can tell is that I saw the react source code in the compiled javascript in the gem files.
Also my engine is intercepting requests and redirect them to my app until all the migration scripts have run (see the engine and middleware).

**Comment by zedtux** [comment]
Okay so I'm not sure I'm explaining well what I'm achieving, or I misunderstand you comment.

So basically my gem is _just_ a tool to be used in dev which doesn't integrates within an existing javascript app, so it couldn't be that the bundled react in my gem is conflicting with the host project.

It's really a little app, leaving aside of the host project, catching requests as soon as pending migration have been found. It doesn't integrates in existing page, it shows as a single app.

So :

> Downstream users will probably need react as a dev dependency in their package.json. This is the same reason that rails/webpacker users need webpack-dev-server in their package.json.

And 

> If a compiled js file (containing react) is loaded on a page that also has react, react will complain and refuse to render.

No they won't as my app will not run at the same time as their react app.

> Make sure you use a dynamic import with your app so users don't load your app code on every page load

This also can't happen as my app is [loaded from a layout file which leaves in the gem](https://gitlab.com/pharmony/active_record_migration_ui/blob/master/app/views/layouts/active_record_migration_ui/application.html.erb) context, not from the rails host app.

I have disabled code magnification and started to debug the bundle, and I actually see my React app source code loading (all my components, actions, reducers and so on, but also external libraries like redux and so on).

It's just like at the end, when the embedded webpack code has loaded all the stuff, it is stoping and not actually running the loaded app, like if it is waiting for something.

**Comment by jakeNiemiec** [comment]
> It's just like at the end, when the embedded webpack code has loaded all the stuff, it is stoping and not actually running the loaded app, like if it is waiting for something.

Here is a non-minified pack via `RAILS_ENV='development' NODE_ENV='development' ./bin/webpack`

![image](https://user-images.githubusercontent.com/16782063/59052320-71d62200-8854-11e9-8380-09851488ba03.png)

This is why you should not have multiple independently packed files. They each have a static, isolated list of tree-shaken libs.

**I cannot stress enough, this problem is endemic to JS libraries** and has been around since 2014. This blog post dives into this topic: https://medium.com/@dan_abramov/two-weird-tricks-that-fix-react-7cf9bbdef375

> like if it is waiting for something

Fetch is async, the event has [probably passed before the listener starts listening](https://gitlab.com/pharmony/active_record_migration_ui/blob/master/app/javascript/packs/application.js#L28). See here for a better solution: https://stackoverflow.com/questions/26566317/invariant-violation-registercomponent-target-container-is-not-a-dom-elem/26566330#26566330

**Comment by zedtux** [comment]
> You also must remember that I am a JS/webpack dev turned rails dev.

Well I didn't know that, I was thinking the way around, but good to know 👍.
I am actually the complete opposite of your: a Rails dev turning Js/Webpack dev :)

Okay so to reduce the double react problem, I have a create [a new Rails application with all the Javascript options disabled](https://gitlab.com/pharmony/rails-nojs-ar-migration-ui) (no webpack, no sprockets (Rails assets), etc ...) so that the only Js that exists in this little app is the one in my engine.

Let's say my ar-migration-ui gem works in this little app, if there is an issue with the double React, I can check that later in [another Rails app with webpack and React](https://gitlab.com/zedtux/rails-react-devise-bootstrap).

> Fetch is async, the event has probably passed before the listener starts listening. See here for a better solution: [...]

I thought about it, and wanted to test it but :

![Screenshot 2019-06-09 at 07 38 29](https://user-images.githubusercontent.com/478564/59155458-4e94b800-8a8a-11e9-993b-cf1f86da1fec.png)

As you can see, I moved the `<script>` tag to the body, but it doesn't solve the issue (it could helps, but didn't solve it).

> Perhaps I misunderstand, does this file load both the host application.js and the ar-migration-ui-packs application.js`?

As you can see in the above screenshot, I have added 2 comments in the `<script>` tag which says _Equivalent to ..._.

So the `fetch` code it loading the CSS and the JS files from the Webpack bundle like would do respectively `stylesheet_pack_tag` and `javascript_pack_tag`.

---

I checked my Js code based on your previous comment about the webpack loading code.

In the bundle, I understood that the different parts of the bundle has some kind of IDs (from `1` to `156` in my case), and then webpack loads the different parts from their IDs.

My app has the ID `150` (where I can see my code) and webpack `bootstrap` file is referencing it correctly :

![Screenshot 2019-06-09 at 07 51 56](https://user-images.githubusercontent.com/478564/59155526-86e8c600-8a8b-11e9-991d-1e68885710aa.png)

What I will try to do is to adds some `console.log` in my Javascript code, especially from the `packs/application.js` file and debug that trying to figure out what's going wrong.

**Comment by zedtux** [comment]
Okay so I found a way to make my gem working ! 🎉 

So basically the issue is that, for a reason I don't know yet, the `document.addEventListener` is never fired.

```javascript
console.log('document.addEventListener ...')
document.addEventListener('DOMContentLoaded', () => {
  console.log('document.addEventListener -> DOMContentLoaded !')
  bootApp()
})
```

I can see the "document.addEventListener" appear in the console, but not the "document.addEventListener -> DOMContentLoaded !".

I then tried with `window` instead of `document`, but same result.

Then I checked for the `document.readyState` and actually it returns `complete`.

So I'm doing :

```javascript
if (document.readyState != 'loading') bootApp()
```

And now it works.

I don't know yet what's the impact of this change, I need to check further, but I at least have a working way.

**Comment by zedtux** [comment]
I tried the gem in the rails project which uses Webpack/React, and all seem to work fine.

Here is the code I did to manage the app boot:

```javascript
import React from 'react'
import { render } from 'react-dom'
import { Provider } from 'react-redux'

import '../stylesheets/application.scss'

import App from '../src/app/App'
import ActionCableHandler from '../src/app/ActionCableHandler'
import store from '../src/config/stores'

let bootedApp = false

const bootApp = _ => {
  if (bootedApp) {
    console.warn('[ActiveRecord Migration UI] Tried to load app more than once')
    return
  }

  bootedApp = true

  render(
    <Provider store={store}>
      <App />
      <ActionCableHandler store={store} />
    </Provider>,
    document.getElementById('app')
  )
}

document.addEventListener('DOMContentLoaded', bootApp)

if (document.readyState != 'loading') bootApp()
```

And I'm checking if the warning appears, which isn't the case for now.

I'm publishing the first version of the gem now.

**Comment by zedtux** [comment]
The gem has been released 🎉 🎉 -> https://rubygems.org/gems/active_record_migration_ui

**Comment by jakeNiemiec** [comment]
🎉 Glad to hear it!
