### ISSUE TITLE
Web-dev-server not found 

### ISSUE THREAD

**Issue by SergiuT** [rails/webpacker#2122]
I'm trying to deploy a project on heroku but on deployment I get this error:
` sh: 1: webpack-dev-server: not found`

My package.json with the dependencies looks like this:

`"devDependencies": {
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.4",
    "babel-preset-env": "^1.6.1",
    "html-webpack-plugin": "^3.0.7",
    "webpack": "^4.33.0",
    "webpack-dev-server": "^3.5.1"
  },
  "dependencies": {
    "axios": "^0.18.1",
    "babel": "^6.23.0",
    "babel-polyfill": "^6.26.0",
    "fractional": "^1.0.0",
    "uniqid": "^4.1.1",
    "webpack-cli": "^2.0.12"
  },
  "engines": {
    "node": "11.12.0"
  }`

**Comment by jakeNiemiec** [comment]
In order to help debug, could you please post as much as you can of:
- `environment.js`
- `package.json`
- `babel.config.js` 
- `application.js` 
- the full error message (even the parts you wouldn’t think is relevant)

—to a https://gist.github.com. Please tag me via `@jakeNiemiec` in a comment and I’ll be able to point out any problems directly in the gist.

**Comment by SergiuT** [comment]
This mind sound like a stupid question, but where do I find babel.config.js and application.js, I mean i didnt use any of them in my app ?

**Comment by jakeNiemiec** [comment]
@SergiuT no problem at all, I updated the files with paths relative to your root project folder.

**Comment by SergiuT** [comment]
I can't see it just yet, it still looks like ./package.json for me.

**Comment by jakeNiemiec** [comment]
What version of webpacker do you have in your gemfile?

**Comment by SergiuT** [comment]
6.9.0

**Comment by jakeNiemiec** [comment]
Nither rails nor webpacker have released versions matching that. The highest is `4.0.7`

Without any of [those context files](https://github.com/rails/webpacker/issues/2122#issuecomment-500484830), I can't be of much help to you.
