### ISSUE TITLE
Webpack magic comments in require context

### ISSUE THREAD

**Issue by guillaumebriday** [rails/webpacker#2127]
This code works as expected

```js
const files = require.context('./', true, /\.vue$/i)
files.keys().map(key => {
  const component = key.split('/').pop().split('.')[0]

  Vue.component(component, () => import(`${key}`))
})
```

This one too, but the webpack magic comment is completely ignored :
```js
const files = require.context('./', true, /\.vue$/i)
files.keys().map(key => {
  const component = key.split('/').pop().split('.')[0]

  Vue.component(component, () => import(/* webpackPreload: true */ `${key}`))
})
```

Is it related to babel ? Or Webpacker specific configuration ?

Thank in advance

**Comment by jakeNiemiec** [comment]
`import` returns a promise. I think you are missing either an `await` or a `.then()`. You should also see the chunk being loaded in your Network panel, try looking at the contents.

(Also I am not too experienced with Vue)

**Comment by guillaumebriday** [comment]
Hum it does not work neither `await` nor `.then()`

It's weird because this works as expected:

```js
Vue.component('SearchbarToggle', () => import(/* webpackPrefetch: true */ /* webpackChunkName: "SearchbarToggle" */ '@components/SearchbarToggle'))
```

with both `prefetch` and the chunk name

**Comment by jakeNiemiec** [comment]
Webpack needs to statically analyze the code. If that function happens at runtime, webpack might not be able to add the preloading behavior.

**Comment by guillaumebriday** [comment]
That makes sense. Thank you !

**Comment by guillaumebriday** [comment]
Ok I found the solution, `require.context` accepts a mode as fourth parameter

```js
const files = require.context('./', true, /\.vue$/i, 'weak')
```
`weak` is what I wanted !
