### ISSUE TITLE
Can't access/modify options of a loader as instructed in docs/webpack.md

### ISSUE THREAD

**Issue by ranjan-purbey** [rails/webpacker#2129]
When I try to run the following snippet from [docs/webpack.md](https://github.com/rails/webpacker/blob/v4.0.7/docs/webpack.md#loaders):
```
const { environment } = require('@rails/webpacker')

const babelLoader = environment.loaders.get('babel')
babelLoader.options.cacheDirectory = false
```
I get the error `Cannot set property 'cacheDirectory' of undefined`
How can I modify the options of a pre-configured loaders?

**Comment by jakeNiemiec** [comment]
[Here is the structure you are modifying,](https://github.com/rails/webpacker/blob/master/package/rules/babel.js#L11) try the following:

```diff 
-babelLoader.options.cacheDirectory = false
+babelLoader.use[0].options.cacheDirectory = false
```

**Comment by ranjan-purbey** [comment]
Shouldn't that be updated in the docs then?

**Comment by jakeNiemiec** [comment]
It would be a nice addition, but I don't think disabling caching is a common use-case. You will find other examples in the docs if you do a `ctrl + f` for `babelLoader.use` or `use.find`.

**Comment by guillaumebriday** [comment]
Can this issue be closed ?

**Comment by ranjan-purbey** [comment]
Yes, closing now
