### ISSUE TITLE
image_pack_tag is returning malformed URI

### ISSUE THREAD

**Issue by bo-oz** [rails/webpacker#2138]
I moved all my static images into the `app/webpack/images` folder. My webpack-dev-server indicates that all images are succesfully processed. When trying to display an image I use the default image_pack_tag helper:

`image_pack_tag 'media/images/test.png'`

Somehow this produces some weird output:

`<img src="/assets/%2Fpacks%2Fmedia%2Fimages%2Ftest-xxxx.png">`

When I open `http://localhost:3000/packs/media/images/test-xxxx.png` I do see the correct image, so it seems the helper is outputting a malformed URI.

I don't understand why the actual URI is being encoded and where the /assets/ piece is coming from. Do I need to change something to Rails config to work nicely with Webpacker? Or could this potentially be an issue?

I'm using webpacker 4.0.7. in combination with Rails 5.2.1 on Ruby 2.4.4

**Comment by bo-oz** [comment]
Any updates on this? Is it indeed a bug?

**Comment by guillaumebriday** [comment]
I think this issue is out of date now. Here is the documention to work with assets : https://github.com/rails/webpacker/blob/master/docs/assets.md#link-in-your-rails-views

Can it be closed ? @bo-oz
