### ISSUE TITLE
Enable AOT compilation by default when you webpacker:install:angular

### ISSUE THREAD

**Issue by TylerRick** [rails/webpacker#2142]
See #2141.

Aside from being safer and being compatible with restrictive Content Security Policy, using AOT also results in 30-60% less code being served to users due to the JIT Compiler module not needing to be included in the bundle (see https://slides.com/wassimchegham/demystifying-ahead-of-time-compilation-in-angular-2-aot-jit#/32), which results in faster load times. Wins all around!

Would there be any objection to making the default configs use the `AngularCompilerPlugin` so that AOT (and CSP) works out of the box for Angular?

Potential problems that I can think of...

1. ~~Not sure yet if it works if you have _multiple_ Angular modules/entrypoints that you want to use. Maybe you'd have to add multiple `AngularCompilerPlugin` instances??~~

2. Ugly and annoying to have to add `NgFactory` and `.ngfactory` to things. This makes it appear to be imported from a non-existent file (at least not the one where your source code is), which is weird:
    ```
    import { AppModuleNgFactory } from './app/app.module.ngfactory';
    ```

3. The configuration is a bit more complex. The generator can at least help with that by starting you off with a working configuration, though it can't really help with any maintenance challenges that a more complex config could cause.

4. `@angular/compiler-cli` requires specific versions of `typescript` (`"~3.4.x"`) to avoid getting this error:

    ```
    ERROR in The Angular Compiler requires TypeScript >=3.4.0 and <3.5.0 but 3.5.2 was found instead.
    ```
    Doesn't seem like a big problem since the generator could insert the correct version constraint, 
    but would have to be updated occasionally when you update other dependencies ... Thankfully, the 
    error message makes it pretty obvious what you need to change.
  
4. Probably others that I'm not aware of

Makes me envy those who can just use `ng serve --prod` (and whatever they run the build production assets) from the Angular CLI. Maybe #400 will help with that?

**Comment by TylerRick** [comment]
I think I found the answer to this one:
> 1. Not sure yet if it works if you have multiple Angular modules/entrypoints that you want to use.
Looks like you can pass an array to `entryModules`:

https://github.com/angular/angular-cli/issues/7954#issuecomment-346770563
> If you're constructing AngularCompilerPlugin and passing an entryModule option, you need to pass all modules there, as an array. This option has a precedence over entryModules specified in tsconfig.

and https://gist.github.com/sqwk/ac04e8d0ca834347656b11206e36f7e8#file-webbpack-config-js-L75:
```
            new ngToolsWebpack.AngularCompilerPlugin({
                tsConfigPath: helpers.root('tsconfig.json'),
                entryModule: [
                    'src/app1/app/app.module#AppModule',
                    'src/app2/app/app.module#AppModule'
                ]
            }),
```

**Comment by guillaumebriday** [comment]
Can this issue be closed? Or do you still have the problem?
