### ISSUE TITLE
Get an error if HMR and hot together

### ISSUE THREAD

**Issue by a-dev** [rails/webpacker#2146]
I had an trouble in a project that hotModuleReplacement didn't work, got an error 'Maximum call stack size exceeded'.
It's [an old issue](https://github.com/webpack/webpack-dev-server/issues/87) that flag --hot and hotModuleReplacement can't be together.

I removed HotModuleReplacementPlugin() form config:
```
if (devServer.hmr) {
  this.plugins.append('HotModuleReplacement', new webpack.HotModuleReplacementPlugin()) // remove this line and HMR will work
  this.config.output.filename = '[name]-[hash].js'
}
```
I use last versions:
"webpack": "^4.35.0",
"webpack-dev-server": "^3.7.2",

**Comment by jakeNiemiec** [comment]
Does it work if you omit ‘—hot’?

**Comment by babel92** [comment]
Ran into similar issue after upgrading from 4.0.2 to 4.0.3. webpack-dev-server actually checks for this plugin but somehow it failed (https://github.com/webpack/webpack-dev-server/blob/802aa30cc0a549803e64b74a7085a2c549c71f41/lib/utils/updateCompiler.js#L18)

**Comment by a-dev** [comment]
> Does it work if you omit ‘—hot’? It should work if you just set `devServer.hot: true`.

@jakeNiemiec If you set hmr: true you already have a ‘--hot’, cause `hot: devServer.hmr`,
see here https://github.com/rails/webpacker/blob/master/package/environments/development.js

**Comment by jakeNiemiec** [comment]
What issue are you having? We can only fix problems with rails/webpacker here.

**Comment by a-dev** [comment]
I just sad that you have the flag `hot: true` and append `HotModuleReplacement` if `hmr: true` in yml config. But it can make error, cause it isn’t necessary to append HotModuleReplacement if —hot option omitted.

**Comment by jakeNiemiec** [comment]
> it can make error, cause it isn’t necessary to append HotModuleReplacement if —hot option omitted

I would think that the solution is: just don't append the HotModuleReplacement plugin. I also would not use both the `--hot` flag with `webpacker`.

Does removing the HotModuleReplacementPlugin() from your config fix things?

**Comment by a-dev** [comment]
@jakeNiemiec I don’t have HotModuleReplacementPlugin() in my config, it’s in the config of Webpacker. And I showed in this issue (first post) if you remove appending of HotModuleReplacementPlugin() you fix this error.
In Webpacker config it’s here — https://github.com/rails/webpacker/blob/master/package/environments/development.js#L11

**Comment by jakeNiemiec** [comment]
Apologies, the link from @babel92 completely threw me off. How are you invoking webpack with `--hot`? (I assume something like `./bin/webpack-dev-server --hot`)

**Comment by babel92** [comment]
Actually I think @a-dev and I are having the same issue - if you set hmr: true in webpacker.yml, webpacker inserts HotModuleReplacementPlugin and uses hot: true to launch webpack-dev-server (which should be equivalent to --hot option). And webpack-dev-server would try to check for this plugin before inserting it again but it failed to identify it somehow in our cases. My suggestion was just don't append this plugin in @rails/webpacker as a-dev already proposed, given webpack-dev-server will do that anyway.

**Comment by justin808** [comment]
I submitted a PR to fix this: https://github.com/rails/webpacker/pull/2439.

**Comment by laga912** [comment]
> I submitted a PR to fix this: #2439.

**Comment by laga912** [comment]
![284D2F19-09E8-4CAF-9A65-25C18C974226](https://user-images.githubusercontent.com/62596828/77419096-3f26f700-6d9e-11ea-8c60-f4d3a7ae5476.jpeg)
> Actually I think @a-dev and I are having the same issue - if you set hmr: true in webpacker.yml, webpacker inserts HotModuleReplacementPlugin and uses hot: true to launch webpack-dev-server (which should be equivalent to --hot option). And webpack-dev-server would try to check for this plugin before inserting it again but it failed to identify it somehow in our cases. My suggestion was just don't append this plugin in @rails/webpacker as a-dev already proposed, given webpack-dev-server will do that anyway.

**Comment by justin808** [comment]
@gauravtiwari can you reopen: https://github.com/rails/webpacker/pull/2439

I think given the docs clearly state that this is correct, we should consider #2439.

**Comment by justin808** [comment]
@guillaumebriday Let's close and let somebody reopen if an issue with v6.
