### ISSUE TITLE
Dynamic page loading failed Error: Loading chunk 1 failed.

### ISSUE THREAD

**Issue by reedlaw** [rails/webpacker#215]
This related to #213. Sorry if it's a bit tangential. I've got `react-boilerplate` nearly [integrated](https://bitbucket.org/rlaw3/rails-react-boilerplate/src) with Rails 5.1 after disabling HMR and relying on Webpacker for code chunking. But then I hit a snag that the chunks are being requested on localhost:5000 instead of localhost:8080. The `1.js` chunk exists but for some reason the entry point is requesting it on the wrong port. I'm not sure how to troubleshoot and any help would be greatly appreciated.

**Comment by gauravtiwari** [comment]
@reedlaw I haven't looked into `react-boilerplate`, but it seems it comes with a lot of it's own configuration and `out-of-the-box` webpacker doesn't support that convention. It seems that this error is something internally related to how `react-boilerplate` is configuration. 

Perhaps, a good approach is to add it piece-by-piece or may be make your own using webpacker + webpacker:react. Please see an example here - https://github.com/gauravtiwari/webpacker-react-frontend

**Comment by gauravtiwari** [comment]
I am closing this one as this isn't related to webpacker. Feel free to open a new one if you find anything that's related to webpacker.
