### ISSUE TITLE
Access compiled JS from ruby

### ISSUE THREAD

**Issue by yowzadave** [rails/webpacker#2153]
I'd like to use webpacker to compile a pack that would be used by my rails backend (via ExecJS/mini_racer). What would be the correct way to read this asset in a way that would work either in development (when I'm using `webpack-dev-server`) or in production, when I'd be pre-compiling? Ideally I'd be able to take advantage of the hot-reloading that `webpack-dev-server` offers.

**Comment by yowzadave** [comment]
FYI, I ended up doing something like this:

```
pack = Pathname(Webpacker.manifest.lookup("backend.js")).each_filename.to_a

source = if ENV["RAILS_ENV"] == "production"
  File.read(File.join Rails.root, "public", *pack)
else
  open("http://localhost:3035/" + pack.join("/")).read
end

ExecJS.compile(source)
```

I also needed to turn off HMR to get `webpack-dev-server` to work. Would still appreciate any additional insights if people have them!

**Comment by guillaumebriday** [comment]
Is this issue can be closed ?
