### ISSUE TITLE
So many BrowserListsErrors.

### ISSUE THREAD

**Issue by angarc** [rails/webpacker#2157]
Compilation keeps on failing, and because it keeps failing, it's not allowing me to deploy. This is the error I keep getting.

```
[Webpacker] BrowserslistError: Unknown browser query `android all`
BrowserslistError: Unknown browser query `android all`
BrowserslistError: Unknown browser query `android all`
BrowserslistError: Unknown browser query `android all`
BrowserslistError: Unknown browser query `android all`
BrowserslistError: Unknown browser query `android all`
BrowserslistError: Unknown browser query `android all`
BrowserslistError: Unknown browser query `android all`
BrowserslistError: Unknown browser query `android all`
BrowserslistError: Unknown browser query `android all`
BrowserslistError: Unknown browser query `android all`
BrowserslistError: Unknown browser query `android all`
BrowserslistError: Unknown browser query `android all`
BrowserslistError: Unknown browser query `android all`
BrowserslistError: Unknown browser query `android all`
BrowserslistError: Unknown browser query `android all`
BrowserslistError: Unknown browser query `android all`
BrowserslistError: Unknown browser query `android all`
BrowserslistError: Unknown browser query `android all`
BrowserslistError: Unknown browser query `android all`
BrowserslistError: Unknown browser query `android all`
BrowserslistError: Unknown browser query `android all`
BrowserslistError: Unknown browser query `android all`
BrowserslistError: Unknown browser query `android all`
BrowserslistError: Unknown browser query `android all`
BrowserslistError: Unknown browser query `android all`
BrowserslistError: Unknown browser query `android all`
BrowserslistError: Unknown browser query `android all`
BrowserslistError: Unknown browser query `android all`
BrowserslistError: Unknown browser query `android all`
BrowserslistError: Unknown browser query `android all`
```

Please note, I have many more lines of these errors, I only cut them because it seemed unnecessary to put them here.

I've have not written anything about `android` in my code.

This is the only thing I can think of. This is in my package-lock.json:
```
"autoprefixer": {
      "version": "9.6.0",
      "resolved": "https://registry.npmjs.org/autoprefixer/-/autoprefixer-9.6.0.tgz",
      "integrity": "blahblahblah",
      "requires": {
        "browserslist": "^4.6.1",
        "caniuse-lite": "^1.0.30000971",
        "chalk": "^2.4.2",
        "normalize-range": "^0.1.2",
        "num2fraction": "^1.2.2",
        "postcss": "^7.0.16",
        "postcss-value-parser": "^3.3.1"
      }
    },
```

Any ideas?

**Comment by renchap** [comment]
Do you have a `.browserslistrc` file in your project directory, or a `browserslist` entry in your `package.json`?
One of those contains a `android all` version selector, which is not valid. See https://github.com/browserslist/browserslist for browserslist syntax.

**Comment by imskytoo** [comment]
Hi dear webpacker
Please  confirm  me what must I do with this email and so many email you
and your organization  send to me.

Best regarding
Kasbkar

در تاریخ دوشنبه ۱ ژوئیهٔ ۲۰۱۹،‏ ۰:۵۹ Renaud Chaput <notifications@github.com>
نوشت:

**Comment by renchap** [comment]
@imskytoo  You are probably receiving those notifications because you are watching this repository.
You can change this at the top of the page:
![image](https://user-images.githubusercontent.com/42070/60422193-c7031a80-9beb-11e9-8bf5-6b814aaeed3d.png)

**Comment by angarc** [comment]
@renchap I do have a browserslist.rc file. I just has one line and it is: `default` You think this might be causing the problem?

**Comment by renchap** [comment]
According to the documentation, it should be `defaults`. 
Can you try to run `yarn run browserslist` in your project directory?

**Comment by angarc** [comment]
All I did was delete my `yarn.lock`, and ran `yarn` and I stopped getting the errors.
