### ISSUE TITLE
Webpacker::Manifest::MissingEntryError: While deploying on heroku

### ISSUE THREAD

**Issue by gsum** [rails/webpacker#2158]
--server log 
`remote:        yarn install v1.16.0
remote:        [1/4] Resolving packages...
remote:        [2/4] Fetching packages...
remote:        info fsevents@1.2.9: The platform "linux" is incompatible with this module.
remote:        info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
remote:        [3/4] Linking dependencies...
remote:        warning " > webpack-dev-server@3.7.2" has unmet peer dependency "webpack@^4.0.0".
remote:        warning "webpack-dev-server > webpack-dev-middleware@3.7.0" has unmet peer dependency "webpack@^4.0.0".
remote:        [4/4] Building fresh packages...
remote:        Done in 23.25s.
remote:        Compiling…
remote:        Compilation failed:
remote:        
remote:        WARNING: We noticed you're using the `useBuiltIns` option without declaring a core-js version. Currently, we assume version 2.x when no version is passed. Since this default version will likely change in future versions of Babel, we recommend explicitly setting the core-js version you are using via the `corejs` option.
remote:        
remote:        You should also be sure that the version you pass to the `corejs` option matches the version specified in your `package.json`'s `dependencies` section. If it doesn't, you need to run one of the following commands:
remote:        
remote:          npm install --save core-js@2    npm install --save core-js@3
remote:          yarn add core-js@2              yarn add core-js@3
remote:        
remote:        Unhandled rejection Error: original.line and original.column are not numbers -- you probably meant to omit the original mapping entirely and only map the generated position. If so, pass null for the original mapping instead of an object with empty or null values.
remote:            at SourceMapGenerator_validateMapping [as _validateMapping] (/tmp/build_e85ea979e95a5c2e7312218a40c90a21/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:276:15)
remote:            at SourceMapGenerator_addMapping [as addMapping] (/tmp/build_e85ea979e95a5c2e7312218a40c90a21/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:110:12)
remote:            at /tmp/build_e85ea979e95a5c2e7312218a40c90a21/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:72:17
remote:            at Array.forEach (<anonymous>)
remote:            at BasicSourceMapConsumer.SourceMapConsumer_eachMapping [as eachMapping] (/tmp/build_e85ea979e95a5c2e7312218a40c90a21/node_modules/webpack-sources/node_modules/source-map/lib/source-map-consumer.js:157:14)
remote:            at Function.SourceMapGenerator_fromSourceMap [as fromSourceMap] (/tmp/build_e85ea979e95a5c2e7312218a40c90a21/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:48:24)
remote:            at SourceMapSource.node (/tmp/build_e85ea979e95a5c2e7312218a40c90a21/node_modules/webpack-sources/lib/SourceMapSource.js:32:35)
remote:            at SourceMapSource.proto.sourceAndMap (/tmp/build_e85ea979e95a5c2e7312218a40c90a21/node_modules/webpack-sources/lib/SourceAndMapMixin.js:30:18)
remote:            at getTaskForFile (/tmp/build_e85ea979e95a5c2e7312218a40c90a21/node_modules/webpack/lib/SourceMapDevToolPlugin.js:37:30)
remote:            at files.forEach (/tmp/build_e85ea979e95a5c2e7312218a40c90a21/node_modules/webpack/lib/SourceMapDevToolPlugin.js:136:20)
remote:            at Array.forEach (<anonymous>)
remote:            at compilation.hooks.afterOptimizeChunkAssets.tap (/tmp/build_e85ea979e95a5c2e7312218a40c90a21/node_modules/webpack/lib/SourceMapDevToolPlugin.js:130:12)
remote:            at SyncHook.eval [as call] (eval at create (/tmp/build_e85ea979e95a5c2e7312218a40c90a21/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
remote:            at SyncHook.lazyCompileHook (/tmp/build_e85ea979e95a5c2e7312218a40c90a21/node_modules/tapable/lib/Hook.js:154:20)
remote:            at hooks.optimizeChunkAssets.callAsync.err (/tmp/build_e85ea979e95a5c2e7312218a40c90a21/node_modules/webpack/lib/Compilation.js:1315:42)
remote:            at _err1 (eval at create (/tmp/build_e85ea979e95a5c2e7312218a40c90a21/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:12:1)
remote:            at taskRunner.run (/tmp/build_e85ea979e95a5c2e7312218a40c90a21/node_modules/terser-webpack-plugin/dist/index.js:319:9)
remote:            at step (/tmp/build_e85ea979e95a5c2e7312218a40c90a21/node_modules/terser-webpack-plugin/dist/TaskRunner.js:87:9)
remote:            at done (/tmp/build_e85ea979e95a5c2e7312218a40c90a21/node_modules/terser-webpack-plugin/dist/TaskRunner.js:98:30)
remote:            at tryCatcher (/tmp/build_e85ea979e95a5c2e7312218a40c90a21/node_modules/bluebird/js/release/util.js:16:23)
remote:            at Promise._settlePromiseFromHandler (/tmp/build_e85ea979e95a5c2e7312218a40c90a21/node_modules/bluebird/js/release/promise.js:517:31)
remote:            at Promise._settlePromise (/tmp/build_e85ea979e95a5c2e7312218a40c90a21/node_modules/bluebird/js/release/promise.js:574:18)
remote:            at Promise._settlePromise0 (/tmp/build_e85ea979e95a5c2e7312218a40c90a21/node_modules/bluebird/js/release/promise.js:619:10)
remote:            at Promise._settlePromises (/tmp/build_e85ea979e95a5c2e7312218a40c90a21/node_modules/bluebird/js/release/promise.js:699:18)
remote:            at Promise._fulfill (/tmp/build_e85ea979e95a5c2e7312218a40c90a21/node_modules/bluebird/js/release/promise.js:643:18)
remote:            at Promise._resolveCallback (/tmp/build_e85ea979e95a5c2e7312218a40c90a21/node_modules/bluebird/js/release/promise.js:437:57)
remote:            at Promise._settlePromiseFromHandler (/tmp/build_e85ea979e95a5c2e7312218a40c90a21/node_modules/bluebird/js/release/promise.js:529:17)
remote:            at Promise._settlePromise (/tmp/build_e85ea979e95a5c2e7312218a40c90a21/node_modules/bluebird/js/release/promise.js:574:18)
remote:            at Promise._settlePromise0 (/tmp/build_e85ea979e95a5c2e7312218a40c90a21/node_modules/bluebird/js/release/promise.js:619:10)
remote:            at Promise._settlePromises (/tmp/build_e85ea979e95a5c2e7312218a40c90a21/node_modules/bluebird/js/release/promise.js:699:18)
remote:            at Promise._fulfill (/tmp/build_e85ea979e95a5c2e7312218a40c90a21/node_modules/bluebird/js/release/promise.js:643:18)
remote:            at Promise._resolveCallback (/tmp/build_e85ea979e95a5c2e7312218a40c90a21/node_modules/bluebird/js/release/promise.js:437:57)
remote:            at Promise._settlePromiseFromHandler (/tmp/build_e85ea979e95a5c2e7312218a40c90a21/node_modules/bluebird/js/release/promise.js:529:17)
remote:            at Promise._settlePromise (/tmp/build_e85ea979e95a5c2e7312218a40c90a21/node_modules/bluebird/js/release/promise.js:574:18)
remote:            at Promise._settlePromise0 (/tmp/build_e85ea979e95a5c2e7312218a40c90a21/node_modules/bluebird/js/release/promise.js:619:10)
remote:            at Promise._settlePromises (/tmp/build_e85ea979e95a5c2e7312218a40c90a21/node_modules/bluebird/js/release/promise.js:699:18)
remote:        
remote:        
remote:        Asset precompilation completed (33.17s)
remote:        Cleaning assets
remote:        Running: rake assets:clean
remote: -----> Detecting rails configuration`

--rollbar log

> 
> Full Raw
> Webpacker::Manifest::MissingEntryError:
> Webpacker can't find application in /app/public/packs/manifest.json. Possible causes:
> 1. You want to set webpacker.yml value of compile to true for your environment
>    unless you are using the `webpack -w` or the webpack-dev-server.
> 2. webpack has not yet re-run to reflect updates.
> 3. You have misconfigured Webpacker's config/webpacker.yml file.
> 4. Your webpack configuration is not creating a manifest.
> Your manifest contains:
> {
> }
> (Most recent call first)

--webpacker.yml
```
# Note: You must restart bin/webpack-dev-server for changes to take effect

default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_root_path: public
  public_output_path: packs
  cache_path: tmp/cache/webpacker
  check_yarn_integrity: false
  webpack_compile_output: false

  # Additional paths webpack should lookup modules
  # ['app/assets', 'engine/foo/app/assets']
  resolved_paths: []

  # Reload manifest.json on all requests so we reload latest compiled packs
  cache_manifest: false

  # Extract and emit a css file
  extract_css: false

  static_assets_extensions:
    - .jpg
    - .jpeg
    - .png
    - .gif
    - .tiff
    - .ico
    - .svg
    - .eot
    - .otf
    - .ttf
    - .woff
    - .woff2

  extensions:
    - .mjs
    - .js
    - .sass
    - .scss
    - .css
    - .module.sass
    - .module.scss
    - .module.css
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg

development:
  <<: *default
  compile: true

  # Verifies that versions and hashed value of the package contents in the project's package.json
  check_yarn_integrity: true

  # Reference: https://webpack.js.org/configuration/dev-server/
  dev_server:
    https: false
    host: localhost
    port: 3035
    public: localhost:3035
    hmr: false
    # Inline should be set to true if using HMR
    inline: true
    overlay: true
    compress: true
    disable_host_check: true
    use_local_ip: false
    quiet: false
    headers:
      'Access-Control-Allow-Origin': '*'
    watch_options:
      ignored: '**/node_modules/**'


test:
  <<: *default
  compile: true

  # Compile test packs to a separate directory
  public_output_path: packs-test

production:
  <<: *default

  # Production depends on precompilation of packs prior to booting for performance.
  compile: true

  # Extract and emit a css file
  extract_css: true

  # Cache manifest.json for performance
  cache_manifest: true

```

I spend hours and dont know what is causing this error.

**Comment by jakeNiemiec** [comment]
`yarn upgrade` should fix you up. Ref: https://github.com/rails/webpacker/issues/2156#issuecomment-507074269

**Comment by gsum** [comment]
No `yarn upgrade` did not fix that issue. I install webpacker 3.5 and that works for now.

**Comment by guillaumebriday** [comment]
Can this issue be closed ?
