### ISSUE TITLE
Webpacker + Vue compiled failed

### ISSUE THREAD

**Issue by Jaroost** [rails/webpacker#2162]
I tried to create a new Rails app using Webpacker and Vue. 

Info:
- Rails 5.2.3
- Ruby 2.5.5p157 x64
- OS: Windows Server 2016

Here what I have done:

`rails new myapp --webpack=vue -d mysql`

While installing package with yarn I have peer dependency warnings:
```
warning " > vue-loader@15.7.0" has unmet peer dependency "css-loader@*".
warning " > vue-loader@15.7.0" has unmet peer dependency "webpack@^4.1.0 || ^5.0.0-0".
```

After that my `package.json` file looks like this:
```
{
  "name": "myapp",
  "private": true,
  "dependencies": {
    "@rails/webpacker": "^4.0.7",
    "vue": "^2.6.10",
    "vue-loader": "^15.7.0",
    "vue-template-compiler": "^2.6.10"
  }
}
```

When I use command `rails webpacker:compile` it works perfectly and compile :
```
Compiling…
Compiled all packs in D:/myapp/public/packs
```
So far so good but when I try to add peer dependency in package.json things go wrong:
`yarn add webpack@^4.35.2`
`yarn add css-loader`

Here, peer dependencies warnings are gone.

Now package.json looks like this:

```
{
  "name": "myapp",
  "private": true,
  "dependencies": {
    "@rails/webpacker": "^4.0.7",
    "css-loader": "^3.0.0",
    "vue": "^2.6.10",
    "vue-loader": "^15.7.0",
    "vue-template-compiler": "^2.6.10",
    "webpack": "4.35.2"
  }
}
```

And when I try to run the `rails webpacker:compile`  it leave me with this (blank) error :

```
Compiling…
Compilation failed:


```

if I use the command `ruby .\bin\webpack-dev-server` I got the following error (It's normal I don't have webpack-dev-server in dev dependency of package.json. Is it normal that this package is not added by default?)

```
yarn run v1.16.0
error Command "webpack-dev-server" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

So I add webpack-dev-server to package.json:
`yarn add webpack-dev-server --dev`

So now I can run the `ruby .\bin\webpack-dev-server` and I got this following error:

```
ERROR in ./app/javascript/app.vue?vue&type=style&index=0&id=6fb8108a&scoped=true&lang=css& (./node_modules/css-loader/dist/cjs.js??ref--3-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--3-2!./node_modules/vue-loader/lib??vue-loader-options!./app/javascript/app.vue?vue&type=style&index=0&id=6fb8108a&scoped=true&lang=css&)
Module build failed (from ./node_modules/css-loader/dist/cjs.js):
ValidationError: CSS Loader Invalid Options

options should NOT have additional properties

    at validateOptions (D:\myapp\node_modules\schema-utils\src\validateOptions.js:32:11)
    at Object.loader (D:\myapp\node_modules\css-loader\dist\index.js:34:28)
i ｢wdm｣: Failed to compile.
```

Is it bad to add peer dependencies to my project?

**Comment by jakeNiemiec** [comment]
Are your files still stock? If not: in order to help debug, could you please post as much as you can of:
- `./package.json`
- `./babel.config.js` 
- `./config/webpack/environment.js`
- `./config/webpacker.yml`
- `./app/javascript/packs/application.js` 
- the full error message (even the parts you wouldn’t think is relevant)

—to a single https://gist.github.com. Please tag me via `@jakeNiemiec` in a comment and I’ll try to troubleshoot any problems directly in the gist.

**Comment by Jaroost** [comment]
@jakeNiemiec All files are stock except package.json. Here the [gist](https://gist.github.com/Jaroost/345678da2530a1463c98dd3fa756054d) with all files and error messages

**Comment by ytbryan** [comment]
Is it normal that this package is not added by default? nope, not normal.

What's your output for `rails webpacker:info`?

**Comment by Jaroost** [comment]
@ytbryan  

```
D:\myapp>rails webpacker:info
Ruby: ruby 2.5.5p157 (2019-03-15 revision 67260) [x64-mingw32]
Rails: 5.2.3
Webpacker: 4.0.7
Node: v12.5.0
Yarn: 1.16.0

@rails/webpacker:
myapp@ D:\myapp
`-- @rails/webpacker@4.0.7

Is bin/webpack present?: true
Is bin/webpack-dev-server present?: true
Is bin/yarn present?: true

D:\myapp>
```

**Comment by zedtux** [comment]
I'm facing the same issue as @Jaroost since I tried to solve the dependencies warning from yarn.

**Comment by zedtux** [comment]
As mentioned in [this comment](https://github.com/webpack-contrib/css-loader/issues/863#issuecomment-502963451), the `localIdentName` option was removed in favor `modules.localIdentName` option, and looking in this repo I found that [the old way is being still used](https://github.com/rails/webpacker/blob/41d79c96187154b5485289e8c3c42428dd819bfc/package/utils/get_style_rule.js#L24).

**Comment by jakeNiemiec** [comment]
> `options should NOT have additional properties`

@zedtux, I have seen this popping up as a problem. Any idea what causes this?

> @Jaroost Node: v12.5.0

![image](https://user-images.githubusercontent.com/16782063/60734204-c385d100-9f14-11e9-9793-63a3a35eccb7.png)

I would not use the "prerelease" version of node (current), I would instead use the "active version". I have seen problems with `node@12` & `node-sass`.

**Comment by zedtux** [comment]
> I have seen this popping up as a problem. Any idea what causes this?

@jakeNiemiec [the v3 of css-loader has some breaking changes](https://github.com/webpack-contrib/css-loader/blob/master/CHANGELOG.md#breaking-changes) including the move of the `localIdentName` option, so that the `node_modules/css-loader/dist/options.json` files doesn't validate the passing options to css-loader.

**Comment by Jaroost** [comment]
@jakeNiemiec I have node 10.16.0

the @zedtux solution works I updated the [gist](https://gist.github.com/Jaroost/345678da2530a1463c98dd3fa756054d) with the new environment.js (environment-fix.js)

**Comment by zedtux** [comment]
I had to revert all my packages updates as bootstrap wasn't loading like before (I had only the reset css style, and some classes from bootswatch, but all the buttons, list and so on styling wasn't loading).

**Comment by jakeNiemiec** [comment]
>  I have node 12.5.0, I tried node 10.16.0 with the same issue

`12` will give you issues unrelated webpacker. It all depends on if the tools you use are updated for `12.x.x`, examples:
- https://github.com/webpack/webpack/issues/9064#issuecomment-486722132
- https://github.com/vuejs/vue-cli/pull/4109
- https://github.com/vuejs/vue-cli/issues/3883
- https://github.com/webpack/webpack/issues/9070

<hr>

Here is how we are consuming webpack 4:
```scss
//scss
@import '~bootstrap/scss/bootstrap';
```
```js
//js
import Popper from 'popper.js/dist/esm/popper';

//MAKE SURE window.$ exists before this point, import jQuery how you normally would

window.Popper = Popper;
require('bootstrap');
```
Apart from that, I cannot be of much help with the vue stuff.

**Comment by Jaroost** [comment]
Ok I finally get this running by updating `environment.js` according to the [documentation](https://vue-loader.vuejs.org/guide/#manual-setup) like so:
```

const { environment } = require('@rails/webpacker')
const { VueLoaderPlugin } = require('vue-loader')
const vue = require('./loaders/vue')

environment.plugins.prepend('VueLoaderPlugin', new VueLoaderPlugin())
environment.loaders.prepend('vue', vue)

/*
** CSS loader fixing issue, See https://github.com/rails/webpacker/issues/2162
*/
const cssLoader = environment.loaders.get('css')
cssLoader.use=[{'loader':'vue-style-loader'}, {'loader': 'css-loader'}];

module.exports = environment
```

**Comment by guillaumebriday** [comment]
Can this issue be closed ?
