### ISSUE TITLE
Import with resolve.alias failure on repeated production builds

### ISSUE THREAD

**Issue by colepeters** [rails/webpacker#2164]
Hi all, please forgive me if this isn't an issue with Webpacker but rather with Webpack directly. Happy to close and reopen elsewhere if need be!

This is the weirdest bug I've encountered recently so please bear with me.

My webpack custom config is as follows:
```js
const path = require('path');

const resolvePath = p => path.resolve(__dirname, '../..', p);

const environment = {
  resolve: {
    alias: {
      '@': resolvePath('app/react'),
      '@common': resolvePath('app/react/common'),
      spec: resolvePath('app/react/spec'),
    },
  },
};

module.exports = environment;
```

In my directory `app/react/common/components/`, I have (in part) these files and directories:

```
index.js  --> exports all modules in this directory and sub directories for easy access
primitives/
  Box.js       --> React function component
Transition.js  --> React function component
```

In `Transition.js`, I import my Box component:
```js
import { animated } from 'react-spring'
import { Box } from '@common/components'

const AnimatedBox = animated(Box)
AnimatedBox.displayName = 'AnimatedBox'
…
```

In development builds, this is not an issue. **But**, if I build in production mode, while the initial build has no issues, _any subsequent rebuilds without any changes_ (e.g. running `NODE_ENV='production' node_modules/.bin/webpack` once after changes, then again without changes), I end up with a [minified React 130 error](https://reactjs.org/docs/error-decoder.html/?invariant=130&args[]=undefined&args[]=), AKA an invariant violation where React was expecting a string or a class/function, but got `undefined`.

After pulling my hair out trying to figure this out, I finally realized this `Box` import was causing the problem. Changing it up to this:

```js
// Transition.js
import { animated } from 'react-spring'
import { Box } from './primitives/Box'   // <---------- THIS

const AnimatedBox = animated(Box)
AnimatedBox.displayName = 'AnimatedBox'
…
```

solved the issue. Initial and all subsequent production rebuilds work fine, as do development builds.

I'm very confused — I have other components using imports similar to this that don't experience this issue at all. Any insights would be hugely appreciated, as I'd like to prevent any errors like this in the future! :)

_NB: The reason I discovered this error was happening only on a production re-build without changes is that this error occurred on our staging server, and running the prod build twice (the second time without changes) was the only way I could reproduce this issue locally. I have no idea why it happens like this, but here we are._ 😅

**Comment by jakeNiemiec** [comment]
It might be related to use `@` as an alias. `@` is reserved for [scoped packages](https://stackoverflow.com/questions/36667258/what-is-the-meaning-of-the-at-prefix-on-npm-packages).

**Comment by colepeters** [comment]
@jakeNiemiec Interesting, we have other aliases using `@` which don't exhibit this problem. (I didn't set this aspect of the project up, however you make a good point — I should look at fixing this.)

**Comment by bstchow** [comment]
@colepeters I am running into a similar issue on a project where we are seeing different behavior between initial build and subsequent builds in our staging ENV (which defaults to the same ENV as production).

**Comment by stoplion** [comment]
Seems like this would work. But it does not. 
```
environment.loaders.prepend('typescript', typescript);

environment.resolve = {
  extensions: ['.ts', '.js'],
  alias: {
    state: path.resolve(__dirname, '../../app/client/javascript/state'),
    components: path.resolve(
      __dirname,
      '../../app/client/javascript/components'
    ),
    utils: path.resolve(__dirname, '../../app/client/javascript/utils'),
    config: path.resolve(__dirname, '../../app/client/javascript/config'),
    services: path.resolve(__dirname, '../../app/client/javascript/services'),
    controllers: path.resolve(
      __dirname,
      '../../app/client/javascript/controllers'
    ),
  },
};

module.exports = environment;

```

**Comment by guillaumebriday** [comment]
In my `config/webpack/environment.js`, I have that:

```js
environment.config.merge({
  resolve: {
    alias: {
      vue: 'vue/dist/vue.esm',
      lodash: 'lodash-es',
      '@controllers': 'controllers',
      '@utils': 'utils'
    }
  }
})
```
