### ISSUE TITLE
Cannot find module 'webpack'

### ISSUE THREAD

**Issue by theredorm** [rails/webpacker#217]
I try to understand with webpack and such error after such launch starts ./bin/webpack-dev-server
In another terminal. PLS help me. 

`module.js:327
    throw err;
    ^

Error: Cannot find module 'webpack'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/andrew/railsapp/wpacktest/node_modules/webpack-dev-server/lib/Server.js:15:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
`

**Comment by gauravtiwari** [comment]
Have you run `./bin/rails webpacker:install`?

**Comment by theredorm** [comment]
yep

**Comment by theredorm** [comment]
@itkrt2y, I got this error. `Can not find application.js in /home/andrew/railsapp/wpacktest/public/packs/manifest.json. Is webpack still compiling?` And after I looked in Troubleshooting and executed the command ./bin/webpack-dev-server

**Comment by gauravtiwari** [comment]
You get that error because webpack isn't installed. Could you run this `./bin/rails webpacker:install` again please and follow the options?

**Comment by gauravtiwari** [comment]
Btw, what version of webpacker you using? It's  1.1

**Comment by gambala** [comment]
Get same error. Decide this way:

- Update nodejs to 6.x (I have 5.x).
- Run `./bin/rails webpacker:install` and `./bin/yarn install` again.
- Run `bin/webpack-dev-server`
- If there will be errors about missing webpack or babel-loader - add them to `package.json`:

```
{
  "devDependencies": {
    "webpack-dev-server": "^2.4.2"
  },
  "dependencies": {
    // another dependencies
    "babel-core": "^6.24.0",
    "babel-loader": "^6.4.1",
    "webpack": "^2.3.2",
  }
}
```

- Run `./bin/yarn install` and  `bin/webpack-dev-server` again.

**Comment by ytbryan** [comment]
Check the prerequisites of webpacker 1.1 https://github.com/rails/webpacker#prerequisites

**Comment by dhh** [comment]
Would be nice if we could programmatically check these prerequisites and give the right error message on what to do.

**Comment by theredorm** [comment]
@gambala, thx bro. 
@gauravtiwari , sorr, i had node js ~4.v and after I upgraded to 6 all earned.
