### ISSUE TITLE
webpacker with rails 6 compiles assets in development but doesn't work in production

### ISSUE THREAD

**Issue by 34code** [rails/webpacker#2174]
I'm using the built in generator on a fresh rails 6.0.0.rc1 project and webpack-dev-server works well in development. However, assets fail to work in production resulting in 404s and 422s.

I've tried `rake webpacker:compile` to no avail :(

**Comment by 34code** [comment]
my bad, needed to enable `config.public_file_server.enabled = true` in `config/production.rb`

**Comment by mathsurf** [comment]
Many thanks!!! yesterday I spent tons of hours about this issue. It's crazy, any tutorial warns to do this change.

**Comment by nodox** [comment]
I don't know why but can confirm this still works!
