### ISSUE TITLE
onError not working in staging

### ISSUE THREAD

**Issue by purple-seungyeon** [rails/webpacker#2175]
I use Ruby On Rails and webpacker for vue-loader.

And I using v-on:error in vue template for fallback image.

But it works in development and not working our staging server.

How can I fix it?

**Comment by jakeNiemiec** [comment]
Please ensure that no libraries are mistakenly installed to `devDependencies`: https://github.com/rails/webpacker/blob/master/docs/yarn.md#add-an-npm-module-to-devdependencies

If the problem persists, can you post any errors that happen in the terminal or console?

**Comment by purple-seungyeon** [comment]
I try yarn add --dev browser-sync.
But same issue and my webpack-dev-server is not say error.
my dev environment still good and my staging server is not working

**Comment by purple-seungyeon** [comment]
I solved v-img-fallback library.
cuz onError is deprecated in html5.
thank you for your comment.
