### ISSUE TITLE
Stylesheets are not minimized on production

### ISSUE THREAD

**Issue by aganov** [rails/webpacker#218]
Seems like stylesheet minimization is not enabled by default on production env. It was previously achieved by `new webpack.LoaderOptionsPlugin({minimize: true})` in `production.js` but this was removed here https://github.com/rails/webpacker/commit/a858f8e2cd2c736d09f936902a59d33b32ba73fb#diff-f83786ad580b744c4ee876b6fe21c138

I think we have 3 options to get back minimization:

* Get back `webpack.LoaderOptionsPlugin({minimize: true})` to `production.js`
* Modify `loaders/sass.js` to something like `use: [ { loader: 'css-loader', options: { minimize: env.NODE_ENV === 'production' } }, 'postcss-loader', 'sass-loader']` which seems ugly solution
* Add `--optimize-minimize` or `-p` options to `webpack` in `webpacker:compile` task

@gauravtiwari What do you think?

**Comment by dhh** [comment]
Fixed by #225.
