### ISSUE TITLE
rake assets:precompile doesn't check yarn install error status

### ISSUE THREAD

**Issue by timomeh** [rails/webpacker#2185]
## Summary

When running `rake assets:precompile`, webpacker ignores a non-zero exit code of `yarn install` and continues to compile a project with possibly missing dependencies.

## Impact

Yesterday some npm servers were down, which caused `yarn install` to fail randomly with "503 Service Unavailable". In this case, `yarn install` exits with a non-zero exit code. But webpacker ignores this exit code and continues to compile. We use Heroku, so if compiling was successful, the app gets deployed. In our case important dependencies were missing due to the 503-errors, so the broken app was deployed.

```
Detecting rake tasks
Preparing app for Rails asset pipeline
Running: rake assets:precompile
yarn install v1.17.3
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/xxxxx.tgz: Request failed \"503 Service Unavailable\"".
info If you think this is a bug, please open a bug report with the information provided in "/tmp/build_112a0c1d8dba717a8a5b68a386f6e805/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Compiling…
Compiled all packs in /tmp/build_112a0c1d8dba717a8a5b68a386f6e805/public/packs
Asset precompilation completed (169.76s)
Cleaning assets
Running: rake assets:clean
```

## Reproducing

This can be reproduced by turning off the internet connection and executing `rake assets:precompile`. If the verify conditions are true (`check_node`, `check_yarn`, `check_binstubs`), yarn will wait for a network connection and then fail, but webpacker continues to compile:

```console
$ rake assets:precompile
yarn install v1.16.0
info There appears to be trouble with your network connection. Retrying...
[1/5] 🔍  Validating package.json...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
Compiling…
```

Looking at the webpacker code, I noticed that the compile-task runs `yarn_install` with `Rake::Task#enhance`, instead of a rake task pre-condition. But I don't know if that's the culprit.

https://github.com/rails/webpacker/blob/2c2b9ffc055d13242b0ae60807609cc382bb0337/lib/tasks/webpacker/compile.rake#L18-L24

**Comment by juliantrueflynn** [comment]
I'm trying to solve this now and will hopefully shoot PR later today

**Comment by juliantrueflynn** [comment]
@timomeh if you or anyone reading wants a quick fix if my PR gets stuck in review or doesn't pass then:

    namespace :webpacker do
      desc "Custom. Support for older Rails versions. Install all JavaScript dependencies as specified via Yarn"
      task :yarn_install do
        Rake::Task["wepacker:yarn_install"].enhance do
          exit(1) unless $?.success?
        end
      end
    end

With Rake redeclaring the task will just append it on and not overwrite. The usage with `enhance` is to make sure that it's dispatching after the yarn install is complete.

**Comment by jaredbeck** [comment]
Fixed by https://github.com/rails/rails/pull/41824
