### ISSUE TITLE
Webpack compilation issue with react-s3-uploader library

### ISSUE THREAD

**Issue by sushilprj** [rails/webpacker#2186]
I am using webpacker gem with react in rails 4.2 and react application has a dependency with react-s3-upload library. When I compile my react application, it's compiled successfully without any issue but a portion of the code doesn't reflect in the compiled file. Here is the file path -
https://github.com/odysseyscience/react-s3-uploader/blob/master/ReactS3Uploader.js and missing code portion. 

`propTypes: {
        signingUrl: PropTypes.string,
        getSignedUrl: PropTypes.func,
        preprocess: PropTypes.func,
        onSignedUrl: PropTypes.func,
        onProgress: PropTypes.func,
        onFinish: PropTypes.func,
        onError: PropTypes.func,
        signingUrlMethod: PropTypes.string,
        signingUrlHeaders: PropTypes.oneOfType([
          PropTypes.object,
          PropTypes.func
        ]),
        signingUrlQueryParams: PropTypes.oneOfType([
          PropTypes.object,
          PropTypes.func
        ]),
        signingUrlWithCredentials: PropTypes.bool,
        uploadRequestHeaders: PropTypes.object,
        contentDisposition: PropTypes.string,
        server: PropTypes.string,
        scrubFilename: PropTypes.func,
        s3path: PropTypes.string,
        inputRef: PropTypes.func,
        autoUpload: PropTypes.bool
    }`

I have tried the same with webpack.js and it works without having any issue.

**Comment by jakeNiemiec** [comment]
I have never seen proptypes declared like that, do you get any errors? I think you may need to ask the webpack or react folks, webpack probably thinks that portion is "dead code".

**Comment by sushilprj** [comment]
@jakeNiemiec but it works with standalone webpack.js but it doesn't work with the webpacker gem.

**Comment by jakeNiemiec** [comment]
Standalone webpack does not include babel, terser minification, and others.

**Comment by sushilprj** [comment]
@jakeNiemiec, I tried with babel and react dependencies but haven't included the terser minification library.

**Comment by sushilprj** [comment]
@jakeNiemiec, I have verified and found that it creates a problem after compression and minification of JS files. Do you have any suggestion to fix this issue?

**Comment by jakeNiemiec** [comment]
Use ES6 instead of ES5 in your react scripts. I am also pretty sure that proptypes are really only for development, but I may be wrong.

**Comment by guillaumebriday** [comment]
Is this still an issue? Feel free to reopen if it is 👍
