### ISSUE TITLE
variables.scss variables not found

### ISSUE THREAD

**Issue by LukeeeeBennett** [rails/webpacker#2198]
I have a variables.scss of various sass variables, I want to use this globally in my app.

I have

```
// app/javascript/packs/my_pack.js

import '../../assets/stylesheets/variables'
import '../../assets/stylesheets/my_component'
```

And my `$my_color` is not found when used in `my_component`.

What did I do wrong? Sorry if this is not a place for questions, couldn't grep alternative in readme.

**Comment by jakeNiemiec** [comment]
I think you just need to import both`variables` in "scss-space".

```scss
// my_component.scss
@import '../../assets/stylesheets/variables';
```

**Comment by Vic-L** [comment]
I use webpacker in Rails 6, and my assets lie in the javascript pack folder.
I can verify that importing the variable in both files are required.

```
// app/javascript/packs/my_page.js

require("../scss/_variables.scss")
require("../scss/custom/my_page.sass")

// app/javascript/scss/my_page.scss
@import "../_variables.sass"
```

Note the import route should be relative in the stylesheet component.

**Comment by guillaumebriday** [comment]
Your variables file should be only imported in your scss file and import this scss file in your js pack.

Can this issue be closed ?

**Comment by lbennett-simplestream** [comment]
Yes, thank you!

**Comment by LukeeeeBennett** [comment]
Yes, thank you!
