### ISSUE TITLE
Module not found: Error: Can't resolve '@rails/ujs'

### ISSUE THREAD

**Issue by lrjbrual** [rails/webpacker#2199]
Hi, 

anyone knows how to solve the problem of `Module not found: Error: Can't resolve '@rails/ujs'` in Rails6. 

![image](https://user-images.githubusercontent.com/9385561/62037934-0cb80080-b1f5-11e9-8471-f2d0ea26405b.png)

I also tried to install in npm the :  npm i @rails/ujs but still the same error that can't find ujs. 

If you need more info, let me know. 

Thanks in advance.

**Comment by jakeNiemiec** [comment]
In order to help debug, could you please post as much as you can of:
- `./package.json`
- `./config/webpack/environment.js`
- `./config/webpacker.yml`
- `./app/javascript/packs/application.js` 
- the full error message (even the parts you wouldn’t think is relevant)

—to a single https://gist.github.com. Please tag me via `@jakeNiemiec` in a comment and I’ll try to troubleshoot any problems directly in the gist.

**Comment by lrjbrual** [comment]
Hi @jakeNiemiec I already resolved the problem. via adding :     `Rails: ['@rails/ujs']` in environment.js 

Thanks 
Cheers!

**Comment by afuno** [comment]
@lrjbrual Can you please write a more detailed solution to the problem?

**Comment by arusa** [comment]
yarn add @rails/ujs

**Comment by hiveer** [comment]
@lrjbrual  I have the same issue and this is working
```js
environment.plugins.prepend('Provide',
  new webpack.ProvidePlugin({
    $: 'jquery',
    jQuery: 'jquery'
    jQuery: 'jquery',
    Rails: '@rails/ujs'
  })
)
```
But I wonder why this way below is not working:
```js
import Rails from "@rails/ujs"
Rails.start()
```

**Comment by jakeNiemiec** [comment]
> why this way below is not working

In what way does it not work? If you use it globally (like in a <script>), you might need to graft it onto the `window`:
```js
import Rails from "@rails/ujs"
window.Rails = Rails
Rails.start()
```
I can't tell if this is [done for you here](https://github.com/rails/rails/blob/master/actionview/app/assets/javascripts/rails-ujs/start.coffee#L74). (I don't ☕️)

**Comment by benoittgt** [comment]
Check that you don't have .autoclean file generated by `yarn autoclean --init`. Remove it and rerun yarn.
