### ISSUE TITLE
js-yaml security vulnerability in 3.x version

### ISSUE THREAD

**Issue by GabrielFn** [rails/webpacker#2204]
![Captura de tela de 2019-08-01 15-22-19](https://user-images.githubusercontent.com/5855069/62317481-2e70ec00-b470-11e9-893d-7f0a1bcf370f.png)

Is there any intention to upgrade the js-yaml package to version 3.13.1 in branch 3.x?

PR
https://github.com/rails/webpacker/pull/2205

**Comment by guillaumebriday** [comment]
I think it's resolved now 👍 

Can this issue be closed ?
