### ISSUE TITLE
multiple websockets being opened when using HMR

### ISSUE THREAD

**Issue by JoeMattie** [rails/webpacker#2209]
Including multiple packs in a page like:
```= javascript_packs_with_chunks_tag 'app', 'project', 'other'```

results in three websockets being opened, and the updated chunk being downloaded three times any time an edit is made.  Additionally, console show multiple copies of `[HMR] Waiting for update signal from WDS...` with no *connected* message. However, HMR is working

What am I doing wrong?

**Comment by jakeNiemiec** [comment]
Each `pack` comes with separate embedded webpack runtimes. Please follow the code splitting docs in order to split your `packs` into `chunks`.

I give a good example of this in this comment: https://github.com/rails/webpacker/issues/1835#issuecomment-456569708
