### ISSUE TITLE
Webpacker Manifest is empty on deploy after adding react-on-rails

### ISSUE THREAD

**Issue by AlexKund** [rails/webpacker#2211]
Hi,
We moved to react and react-on-rails. Everything was ok before that but now we have problems on deploy with below log error:

ActionView::Template::Error: Webpacker can't find application.js in /public/packs-test/manifest.json. Possible causes:
        1. You want to set webpacker.yml value of compile to true for your environment
           unless you are using the `webpack -w` or the webpack-dev-server.
        2. webpack has not yet re-run to reflect updates.
        3. You have misconfigured Webpacker's config/webpacker.yml file.
        4. Your webpack configuration is not creating a manifest.
        Your manifest contains:
        {
        }
This is the result on deploy to the server with Jenkins. If we remove react-on-rails gem from Gemfile, deploy and assets are ok again. Am I doing something wrong or the problem is in the gem?

**Comment by jakeNiemiec** [comment]
In order to help debug, could you please post as much as you can of:
- `./package.json`
- `./config/webpack/environment.js`
- `./config/webpacker.yml`
- `./app/javascript/packs/application.js` 
- the full error message (even the parts you wouldn’t think is relevant)

—to a single https://gist.github.com. Please tag me via `@jakeNiemiec` in a comment and I’ll try to troubleshoot any problems directly in the gist.

**Comment by kundurdzhieva** [comment]
It seems that capistrano doesn't run webpacker:compile if react_on_rails have been added and public/packs folder doesn't exist.
We have made workaround compiling assets not locally but on server:
1. we added in file lib/capistrano/tasks/deploy.rake

+  desc 'Runs webpacker compile on the app servers'
+  task :webpacker_compile do
+    on roles(:app) do
+      within current_path do
+        with rails_env: fetch(:rails_env) do
+          execute :bundle, "exec rake webpacker:compile "
+        end
+      end
+    end
+  end

2. and inconfig/deploy.rb:
+after 'deploy:symlink:release', 'deploy:webpacker_compile'.
You could close that ticket

**Comment by jakeNiemiec** [comment]
Thanks for posting back the solution, glad it worked out.
