### ISSUE TITLE
Can't install svelte

### ISSUE THREAD

**Issue by markfrst** [rails/webpacker#2212]
When I try to install svelte `bundle exec rails webpacker:install:svelte` then I catch follow error:

```
rails aborted!
Don't know how to build task 'webpacker:install:svelte' (See the list of available tasks with `rails --tasks`)
Did you mean?  webpacker:install:elm
               webpacker:install:vue
               webpacker:install:react
               webpacker:install:erb
               webpacker:install:coffee
               webpacker:install:stimulus
               webpacker:install:angular

```

**Comment by magiknono** [comment]
i tested with rails 5.2 and rails 6.0.0.rc2 with webpacker 4.0.7 but it did not work and i had the same error.
Here is my repo to make it works manually  [sveltewithwebpack](https://github.com/magiknono/sveltewithwebpack)

I only followed steps of the PR #2134 by @victorhazbun

**Comment by markfrst** [comment]
@magiknono it's because of the new version not released yet. I installed the gem from git master and it works for me

**Comment by smondal** [comment]
As rails 6 were release and rails are using webpacker by default, So I think we should also release webapacker. So all the latest changes will reflect in the new version.

**Comment by victorhazbun** [comment]
Here is a sample app, Svelte and Rails 5 https://github.com/victorhazbun/fish-hub

**Comment by markfrst** [comment]
I close this issue because I think that it's will be fixed when published the next version
