### ISSUE TITLE
Webpacker uses a vulnerable version of set-value via dependencies

### ISSUE THREAD

**Issue by michdsouza** [rails/webpacker#2215]
webpacker uses a vulnerable version of set-value via dependencies, see https://www.npmjs.com/advisories/1012 for more details on the security issue.
set-value >=3.0.1 is patched.

| high          | Prototype Pollution                                                       |   
|---------------|---------------------------------------------------------------------------|
| Package       | set-value                                                                 |
| Patched in    | >=2.0.1 <3.0.0 || >=3.0.1                                                 |    
| Dependency of | @rails/webpacker                                                          |
| Path          | @rails/webpacker > webpack > micromatch > braces > snapdragon > base      |
│               │ > cache-base > set-value
| More info     | https://www.npmjs.com/advisories/1012                                     |

**Comment by guillaumebriday** [comment]
`set-value` is a webpack dependency. I think it's resolved now

Can this issue be closed ?

**Comment by michdsouza** [comment]
Yes. I think so.

**Comment by guillaumebriday** [comment]
@michdsouza close it then :)

**Comment by michdsouza** [comment]
Done :)
