### ISSUE TITLE
Ineffective mark-compacts near heap limit Allocation failed 

### ISSUE THREAD

**Issue by medicharlachiranjeevi** [rails/webpacker#2217]
Hi when i was deploying my rails 6 app using capistrano .I got error while precompile assets 
Error is:
```
`Compiling…
Compilation failed:
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x8f9d10 node::Abort() [node]
 2: 0x8f9d5c  [node]
 3: 0xaffd0e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xafff44 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xef4152  [node]
 6: 0xef4258 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [node]
 7: 0xf00332 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]
 8: 0xf00c64 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 9: 0xf0209f v8::internal::Heap::HandleGCRequest() [node]
10: 0xea141a v8::internal::StackGuard::HandleInterrupts() [node]
11: 0x1111fbf v8::internal::NativeRegExpMacroAssembler::CheckStackGuardState(v8::internal::Isolate*, int, bool, unsigned long*, v8::internal::Code*, v8::internal::String**, unsigned char const**, unsigned char const**) [node]
12: 0x12e5e32 v8::internal::RegExpMacroAssemblerX64::CheckStackGuardState(unsigned long*, v8::internal::Code*, unsigned long) [node]
13: 0x19b8b0e8fb88 


<--- Last few GCs --->

[2683:0x2bf7ab0]   582780 ms: Scavenge 1362.1 (1408.5) -> 1361.4 (1408.5) MB, 4.9 / 0.0 ms  (average mu = 0.345, current mu = 0.336) allocation failure 
[2683:0x2bf7ab0]   582794 ms: Scavenge 1362.2 (1408.5) -> 1361.6 (1408.5) MB, 3.4 / 0.0 ms  (average mu = 0.345, current mu = 0.336) allocation failure 
[2683:0x2bf7ab0]   582818 ms: Scavenge 1362.4 (1408.5) -> 1361.8 (1409.0) MB, 3.5 / 0.0 ms  (average mu = 0.345, current mu = 0.336) allocation failure 
`
```

**Comment by jakeNiemiec** [comment]
You seem to have run out of memory. I have seen this happen when users put all of their files in the `/packs` folder (try to avoid that). Can you tell me a bit more about:

- what is your setup like?
- what files are in the `/packs` folder?

See https://github.com/rails/webpacker/issues/1189#issuecomment-499234438 for more on this topic.

**Comment by medicharlachiranjeevi** [comment]
Hi thanks for reply.
we are using 4GB ram ec2 instance and our packs consists of our own java scripts

**Comment by jakeNiemiec** [comment]
> our packs consists of our own java scripts

How many? You should only have a few.

**Comment by medicharlachiranjeevi** [comment]
Thanks i have removed unused one worked fine

**Comment by medicharlachiranjeevi** [comment]
Hi i was getting same issue again now we are using 8GB Ram to.Our packs has 2MB js files.

**Comment by jakeNiemiec** [comment]
Please answer the questions asked above. I need more info to give you a reasonable response.

**Comment by ajitk-cuelogic** [comment]
![Screen Shot 2019-08-29 at 1 46 08 PM](https://user-images.githubusercontent.com/27008948/64430934-fac05c00-d0d6-11e9-9534-7e8bc92543e6.png)

Facing same issue on `bundle exec rake assets:precompile` while deploying to server(using docker) but it compiled successfully in the development.

Have only six entry files with heavily imported other files inside them.Some entry files are 10MB in size after compiled in the development.

**Comment by jakeNiemiec** [comment]
Please post in https://github.com/rails/webpacker/issues/1189 for further discussion on memory issues.
