### ISSUE TITLE
api_only=false can occur a csp error

### ISSUE THREAD

**Issue by JMDC-SUN** [rails/webpacker#2220]
I use webpacker+Vue in my web application. It  work very well.

But when api_only in config/application.rb is set to false, a csp error occured in using webpack-dev-server. when I set api_only to true, it has no any problem.

![image](https://user-images.githubusercontent.com/49149068/62679688-3db3e480-b9f0-11e9-810e-f78a35323c5b.png)

**Comment by guillaumebriday** [comment]
Is this issue still relevant?
