### ISSUE TITLE
Node js version upgrade from 6 to above

### ISSUE THREAD

**Issue by smondal** [rails/webpacker#2225]
As per Nodejs document they are no longer support  nodejs 6. Currently they are supporting nodejs 8 and above. Also end life of nodejs 8 is 2019-12-31. So I think we should upgrade our version from 6 to something else.

https://nodejs.org/en/about/releases/

Please suggest

**Comment by gauravtiwari** [comment]
Lets do that 👍

**Comment by smondalwsgc** [comment]
Thank @gauravtiwari, This ticket has resolved. Please closed this ticket
https://github.com/rails/webpacker/pull/2228

**Comment by gauravtiwari** [comment]
Closed by #2228
