### ISSUE TITLE
Image cannot be loaded in scss file when relative_url_root is set

### ISSUE THREAD

**Issue by Dankoda** [rails/webpacker#2226]
Let's say that `relative_url_root` is set to `/sub`.

When I try to set background image in scss file like this:

`background-image: url('~/src/images/image-top.png');` or `background-image: url('../../../../src/images/image-top.png');`

The image is not loaded, and when I inspect in developer console, I get this:
[![Image from Gyazo](https://i.gyazo.com/6b324ec12b64bbee62132f658accb771.png)](https://gyazo.com/6b324ec12b64bbee62132f658accb771)

In console, if I modify its path to `url(/sub/packs/src/images/image-top-a267153... .png)` (adding /sub before), it will show the image.

webpacker version is 3.6
How can I use image in scss file?

**Comment by jakeNiemiec** [comment]
Try: `background-image: '~/src/images/image-top.png';`

**Comment by guillaumebriday** [comment]
thanks @jakeNiemiec
