### ISSUE TITLE
Failed to compile - Capistrano Rails app deployment

### ISSUE THREAD

**Issue by ghost** [rails/webpacker#2236]
While I deploying my Rails-React app with Capistrano: I get this error:
![Capture](https://user-images.githubusercontent.com/30777032/63211126-6599fb00-c108-11e9-90ee-fa8ecbe2c3d6.PNG)

How should I fix it. I have some large JS files.

**Comment by jakeNiemiec** [comment]
Can you review this comment: https://github.com/rails/webpacker/issues/2109#issuecomment-498336919

If that does not help, could you please post as much as you can of:
- `./package.json`
- `./babel.config.js` 
- `./config/webpack/environment.js`
- `./app/javascript/packs/application.js` 
- the full **text** of error message (even the parts you wouldn’t think is relevant)

**Comment by guillaumebriday** [comment]
It seems to be an issue with corejs.

Try to follow this steps: https://github.com/rails/webpacker/blob/master/docs/es6.md#babel

Does this help? Can this issue be closed ?
