### ISSUE TITLE
run webpack BEFORE precompilation?

### ISSUE THREAD

**Issue by catmando** [rails/webpacker#2237]
Is there any reason to run webpack *after* precompilation?

Its obscure but the reason why we want to run webpack first is as follows:

In order to integrate server side prerendering with react you need to supply different versions of some of the react libraries, but then you also want to precompile the assets but with one of the two different pack files included.  

But this does not work unless webpack compile is run first.

I have monkey patched this, and it works (at least for some limited cases) 

Was wondering if I did a PR to swap them around, would it be accepted or is there some technical reason why the order is this way?

**Comment by jakeNiemiec** [comment]
See following docs, this can be configured:
- https://github.com/rails/webpacker#custom-rails-environments
- https://github.com/rails/webpacker/blob/master/docs/deployment.md#deployment

I saw you need multiple versions of react. The only way I know of to do this [is with engines](https://github.com/rails/webpacker/blob/master/docs/engines.md).

**Comment by catmando** [comment]
@jakeNiemiec thanks for the response. 

Unless I am missing something, "custom rails environment" etc, just lets you have different builds depending on whether you are on staging/production/test etc.

The problem here is a bit different.  React prerendering requires two DIFFERENT sets of assets depending on whether the code will run on the server (prerendering) or on the client.

The problem is easily solved by having two different packs:  One for the client (i.e. client_only.js) and one for the common elements that run on client and server (client_and_server.js)

This is all fine but the problem is that when the assets are precompiled, these packs must already exist.

However webpacker first runs precompile, THEN runs webpack.   The order simply needs to be swapped.

For now the work around is to add this to the application Rake file:

```ruby
puts "Warning: Hyperstack is running yarn install and webpacker:compile BEFORE assets:precompile"
# determine if we should use built in yarn:install or use webpacker:yarn_install
yarn_installer = (Rails::VERSION::MAJOR == 5 && Rails::VERSION::MINOR == 0) ? 'webpacker:yarn_install' : 'yarn:install'
# install yarn and compile packs BEFORE assets:precompile
Rake::Task["assets:precompile"].enhance([yarn_installer, 'webpacker:compile'])
```

This works fine, but its a bit cludgy.  

The question is would a PR be accepted that reverses the order?

**Comment by jakeNiemiec** [comment]
> Unless I am missing something, "custom rails environment" etc, just lets you have different builds depending on whether you are on staging/production/test etc.... However webpacker first runs precompile, THEN runs webpack.

I intended to show you that we have a flag to disable the precompiling behavior:

![image](https://user-images.githubusercontent.com/16782063/63371076-00811800-c349-11e9-99c4-4049823e5e37.png)

You can find this reflected in the code:
https://github.com/rails/webpacker/blob/c5065217284e4540c07fefc35fe27d33fc531082/lib/tasks/webpacker/compile.rake#L42-L51

Any PRs that enhance or better define this functionality **are very welcome**. You would just need to make sure not to break any functionality for the different libraries that webpacker supports and to update any documentation that references the old flow.

**Comment by catmando** [comment]
okay so I propose to do it like this:

make the `compile:` option accept true/false and :after

change the meaning of WEBPACKER_PRECOMPILE so that "no/false/n/f" works the same as today, but WEBPACKER_PRECOMPILE=after means run precompilation AFTER running webpacker.  Otherwise behavior is like it is today.

I also wonder if while I am at it, if it would be appropriate to add an option to the .yml file, that would work like the environment variable.  That way you can keep all the config in one place:

```yml
...
  
  # control when pre-compilation of packs occurs:
  precompile: after # after is default (i.e. current behavior), alias is true
  precompile: manual # don't hook into assets:precompile, alias is false
  precompile: before # hook into assets:precompile BEFORE assets:precompile
```

if the WEBPACKER_PRECOMPILE env variable is set it takes precedence over the yaml file.

**Comment by catmando** [comment]
any progress on this?

**Comment by justin808** [comment]
@catmando you can modify the `assets:precompile` rake task on your own, so this might be more of a doc issue.

If you want to add a PR for your proposed enhancement, I'll take a look.
