### ISSUE TITLE
Using json-loader is not a good example

### ISSUE THREAD

**Issue by awendt** [rails/webpacker#2241]
I followed the instructions in [Webpack: Loaders](https://github.com/rails/webpacker/blob/master/docs/webpack.md#loaders) and found the following steps are not working with `json-loader` anymore:

1. `yarn add json-loader`
2. call `environment.loaders.append` 

because Webpack supports JSON out-of-the-box since v3 (see https://github.com/webpack/webpack/issues/3363 and [release notes](https://webpack.js.org/migrate/3/#json-loader-is-not-required-anymore)). In fact, following all the steps results in breaking things.

Nevertheless, I learned something about Webpack, and I think that just removing those steps will confuse others who will try to add different loaders.

I think the docs should be changed to use another loader but I don't feel confident enough to do that myself.

**Comment by smondal** [comment]
We can use any other loader  from the loader list in webpack except json-loader. Removed json-loader related entries from documents.
We can use coffee-loader to replacement with json-loader.

Here is the full loader list from webpack
https://webpack.js.org/loaders
