### ISSUE TITLE
Can't resolve @rails/ujs

### ISSUE THREAD

**Issue by afuno** [rails/webpacker#2244]
**package.json:**

```json
"@rails/ujs": "^6.0.0-alpha",
```

**app/javascript/packs/application.js:**

```js
require("@rails/ujs").start()
```

I get an error:

> Module not found: Error: Can't resolve '@rails/ujs' in '/app/javascript/packs'

The `@rails/ujs` directory is present in `node_modules`.

For example — other libraries are imported normally:

```js
// app/javascript/packs/application.js

import Lodash from 'lodash'
```

Why is this happening?

**Comment by jakeNiemiec** [comment]
In order to help debug, could you please post as much as you can of:
- `./package.json`
- `./config/webpack/environment.js`
- `./app/javascript/packs/application.js` 
- the full error message (even the parts you wouldn’t think of as relevant)

**Comment by afuno** [comment]
@jakeNiemiec 

**package.json:**

```json
{
  "name": "blog",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@fortawesome/fontawesome-free": "^5.9.0",
    "@rails/actioncable": "^6.0.0",
    "@rails/activestorage": "^6.0.0",
    "@rails/ujs": "^6.0.0",
    "@rails/webpacker": "^4.0.7",
    "@sentry/browser": "^5.4.0",
    "@sentry/integrations": "^5.4.1",
    "cssom": "^0.4.1",
    "lodash": "^4.17.11",
    "rails-erb-loader": "^5.5.2",
    "tailwindcss": "^1.1.1",
    "tailwindcss-transforms": "^2.2.0",
    "v-click-outside": "^2.1.3",
    "v-runtime-template": "^1.10.0",
    "vee-validate": "^2.2.14",
    "vue": "^2.6.10",
    "vue-clipboard2": "^0.3.0",
    "vue-content-loader": "^0.2.2",
    "vue-i18n": "^8.12.0",
    "vue-loader": "^15.7.1",
    "vue-resource": "^1.5.1",
    "vue-scrollto": "^2.15.0",
    "vue-template-compiler": "^2.6.10",
    "vue-wait": "^1.4.6",
    "vuex": "^3.1.1",
    "vuex-cache": "^3.1.0",
    "vuex-map-fields": "^1.3.4"
  },
  "devDependencies": {
    "webpack-dev-server": "^3.8.0"
  }
}
```

**config/webpack/environment.js:**

```js
const { environment } = require('@rails/webpacker')
const { VueLoaderPlugin } = require('vue-loader')

const erb =  require('./loaders/erb')
const vue = require('./loaders/vue')

const customConfig = require('./custom')

environment.plugins.prepend('VueLoaderPlugin', new VueLoaderPlugin())
environment.loaders.prepend('vue', vue)

environment.config.merge(customConfig)

environment.loaders.prepend('erb', erb)

module.exports = environment
```

**app/javascript/packs/application.js:**

```js
require("@rails/ujs").start()
// require("@rails/activestorage").start()

require("channels")

import Vue from 'vue/dist/vue.esm'

const debug = process.env.NODE_ENV !== 'production'
Vue.config.productionTip = debug

document.addEventListener('DOMContentLoaded', (event) => {
  if (document.getElementById('app')) {

    new Vue({
      el: '#app'
    })
  }
})
```

**The text of the error:**

```
Failed to compile.

./app/javascript/packs/application.js
Module not found: Error: Can't resolve '@rails/ujs' in '/Users/afuno/apps/blog/app/javascript/packs'
```

**Comment by afuno** [comment]
I found a problem. The problem was the existing resolve alias:

```js
'@rails': path.resolve(__dirname, '..', '..', 'app'),
'@rails_js': path.resolve(__dirname, '..', '..', 'app/assets/javascripts'),
```

This was relevant to me in Rails < 6.0.0. In Rails 6.0.0 I deleted these lines.

**Comment by iangullo** [comment]
I have this exact same problem.

- ./package.json
`{
  "name": "bClub",
  "private": true,
  "dependencies": {
    "@hotwired/turbo": "^7.0.0-rc.3",
    "@hotwired/turbo-rails": "^7.0.0-rc.3",
    "@rails/actioncable": "^6.0.0",
    "@rails/actiontext": "6.1.4-1",
    "@rails/activestorage": "^6.0.0",
    "@rails/ujs": "^6.0.0",
    "@rails/webpacker": "5.4.2",
    "stimulus": "^2.0.0",
    "trix": "1.2.0",
    "webpack": "4.46.0",
    "webpack-cli": "3.3.12"
  },
  "version": "0.1.0",
  "devDependencies": {
    "webpack-dev-server": "^4.1.1"
  }
`
- ./config/webpack/environment.js
`const { environment } = require('@rails/webpacker')

module.exports = environment
`
- ./app/javascript/packs/application.js
`import Rails from "@rails/ujs"
import Turbo from "@hotwired/turbo"
import * as ActiveStorage from "@rails/activestorage"
import "channels"

Rails.start()
ActiveStorage.start()

import "controllers"

require("trix")
require("@rails/actiontext")
`
- Full Error Message:
`Compiling...                                                                                                       Compilation failed:                                                                                                ModuleNotFoundError: Module not found: Error: Can't resolve '@rails/ujs' in 'C:\Users\SESA219410\Source\rails\bclub\app\javascript\packs'                                                                                                 at C:\Users\SESA219410\Source\rails\bclub\node_modules\webpack\lib\Compilation.js:925:10                           at C:\Users\SESA219410\Source\rails\bclub\node_modules\webpack\lib\NormalModuleFactory.js:401:22                   at C:\Users\SESA219410\Source\rails\bclub\node_modules\webpack\lib\NormalModuleFactory.js:130:21                   at C:\Users\SESA219410\Source\rails\bclub\node_modules\webpack\lib\NormalModuleFactory.js:224:22                   at C:\Users\SESA219410\Source\rails\bclub\node_modules\neo-async\async.js:2830:7                                   at C:\Users\SESA219410\Source\rails\bclub\node_modules\neo-async\async.js:6877:13                                  at C:\Users\SESA219410\Source\rails\bclub\node_modules\webpack\lib\NormalModuleFactory.js:214:25                   at C:\Users\SESA219410\Source\rails\bclub\node_modules\enhanced-resolve\lib\Resolver.js:213:14                     at C:\Users\SESA219410\Source\rails\bclub\node_modules\enhanced-resolve\lib\Resolver.js:285:5                      at eval (eval at create (C:\Users\SESA219410\Source\rails\bclub\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)                                                                                                 at C:\Users\SESA219410\Source\rails\bclub\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:44:7              at C:\Users\SESA219410\Source\rails\bclub\node_modules\enhanced-resolve\lib\Resolver.js:285:5                      at eval (eval at create (C:\Users\SESA219410\Source\rails\bclub\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)                                                                                                 at C:\Users\SESA219410\Source\rails\bclub\node_modules\enhanced-resolve\lib\Resolver.js:285:5                      at eval (eval at create (C:\Users\SESA219410\Source\rails\bclub\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:27:1)                                                                                                 at C:\Users\SESA219410\Source\rails\bclub\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:67:43         at C:\Users\SESA219410\Source\rails\bclub\node_modules\enhanced-resolve\lib\Resolver.js:285:5                      at eval (eval at create (C:\Users\SESA219410\Source\rails\bclub\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:43:1)                                                                                                 at C:\Users\SESA219410\Source\rails\bclub\node_modules\enhanced-resolve\lib\ModuleKindPlugin.js:30:40              at C:\Users\SESA219410\Source\rails\bclub\node_modules\enhanced-resolve\lib\Resolver.js:285:5                      at eval (eval at create (C:\Users\SESA219410\Source\rails\bclub\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)                                                                                                 at C:\Users\SESA219410\Source\rails\bclub\node_modules\enhanced-resolve\lib\Resolver.js:285:5                      at eval (eval at create (C:\Users\SESA219410\Source\rails\bclub\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:16:1)                                                                                                 at C:\Users\SESA219410\Source\rails\bclub\node_modules\enhanced-resolve\lib\forEachBail.js:30:14                   at C:\Users\SESA219410\Source\rails\bclub\node_modules\enhanced-resolve\lib\Resolver.js:285:5                      at eval (eval at create (C:\Users\SESA219410\Source\rails\bclub\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)                                                                                                 at C:\Users\SESA219410\Source\rails\bclub\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:44:7              at C:\Users\SESA219410\Source\rails\bclub\node_modules\enhanced-resolve\lib\Resolver.js:285:5                      at eval (eval at create (C:\Users\SESA219410\Source\rails\bclub\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)                                                                                                 at C:\Users\SESA219410\Source\rails\bclub\node_modules\enhanced-resolve\lib\Resolver.js:285:5                      at eval (eval at create (C:\Users\SESA219410\Source\rails\bclub\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:27:1)                                                                                                 at C:\Users\SESA219410\Source\rails\bclub\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:67:43         at C:\Users\SESA219410\Source\rails\bclub\node_modules\enhanced-resolve\lib\Resolver.js:285:5                      at eval (eval at create (C:\Users\SESA219410\Source\rails\bclub\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:16:1)                                                                                                 at C:\Users\SESA219410\Source\rails\bclub\node_modules\enhanced-resolve\lib\RootPlugin.js:37:38                    at _next42 (eval at create (C:\Users\SESA219410\Source\rails\bclub\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:8:1)                                                                                           resolve '@rails/ujs' in 'C:\Users\SESA219410\Source\rails\bclub\app\javascript\packs'                                Parsed request is a module                                                                                         using description file: C:\Users\SESA219410\Source\rails\bclub\package.json (relative path: ./app/javascript/packs)                                                                                                                     Field 'browser' doesn't contain a valid alias configuration                                                        resolve as module                                                                                                    looking for modules in C:\Users\SESA219410\Source\rails\bclub\app\javascript                                         using description file: C:\Users\SESA219410\Source\rails\bclub\package.json (relative path: ./app/javascript)                                                                                                                           Field 'browser' doesn't contain a valid alias configuration                                                        using description file: C:\Users\SESA219410\Source\rails\bclub\package.json (relative path: ./app/javascript/@rails/ujs)                                                                                                                no extension                                                                                                         Field 'browser' doesn't contain a valid alias configuration                                                        C:\Users\SESA219410\Source\rails\bclub\app\javascript\@rails\ujs doesn't exist                                   .mjs                                                                                                                 Field 'browser' doesn't contain a valid alias configuration                                                        C:\Users\SESA219410\Source\rails\bclub\app\javascript\@rails\ujs.mjs doesn't exist                               .js                                                                                                                  Field 'browser' doesn't contain a valid alias configuration                                                        C:\Users\SESA219410\Source\rails\bclub\app\javascript\@rails\ujs.js doesn't exist                                .sass                                                                                                                Field 'browser' doesn't contain a valid alias configuration                                                        C:\Users\SESA219410\Source\rails\bclub\app\javascript\@rails\ujs.sass doesn't exist                              .scss                                                                                                                Field 'browser' doesn't contain a valid alias configuration                                                        C:\Users\SESA219410\Source\rails\bclub\app\javascript\@rails\ujs.scss doesn't exist                              .css                                                                                                                 Field 'browser' doesn't contain a valid alias configuration                                                        C:\Users\SESA219410\Source\rails\bclub\app\javascript\@rails\ujs.css doesn't exist                               .module.sass                                                                                                         Field 'browser' doesn't contain a valid alias configuration                                                        C:\Users\SESA219410\Source\rails\bclub\app\javascript\@rails\ujs.module.sass doesn't exist                       .module.scss                                                                                                         Field 'browser' doesn't contain a valid alias configuration                                                        C:\Users\SESA219410\Source\rails\bclub\app\javascript\@rails\ujs.module.scss doesn't exist                       .module.css                                                                                                          Field 'browser' doesn't contain a valid alias configuration                                                        C:\Users\SESA219410\Source\rails\bclub\app\javascript\@rails\ujs.module.css doesn't exist                        .png                                                                                                                 Field 'browser' doesn't contain a valid alias configuration                                                        C:\Users\SESA219410\Source\rails\bclub\app\javascript\@rails\ujs.png doesn't exist                               .svg                                                                                                                 Field 'browser' doesn't contain a valid alias configuration                                                        C:\Users\SESA219410\Source\rails\bclub\app\javascript\@rails\ujs.svg doesn't exist                               .gif                                                                                                                 Field 'browser' doesn't contain a valid alias configuration                                                        C:\Users\SESA219410\Source\rails\bclub\app\javascript\@rails\ujs.gif doesn't exist                               .jpeg                                                                                                                Field 'browser' doesn't contain a valid alias configuration                                                        C:\Users\SESA219410\Source\rails\bclub\app\javascript\@rails\ujs.jpeg doesn't exist                              .jpg                                                                                                                 Field 'browser' doesn't contain a valid alias configuration                                                        C:\Users\SESA219410\Source\rails\bclub\app\javascript\@rails\ujs.jpg doesn't exist                               as directory                                                                                                         C:\Users\SESA219410\Source\rails\bclub\app\javascript\@rails\ujs doesn't exist                             C:\Users\SESA219410\Source\rails\bclub\app\javascript\packs\node_modules doesn't exist or is not a directory       C:\Users\SESA219410\Source\rails\bclub\app\javascript\node_modules doesn't exist or is not a directory             C:\Users\SESA219410\Source\rails\bclub\app\node_modules doesn't exist or is not a directory                        C:\Users\SESA219410\Source\rails\node_modules doesn't exist or is not a directory                                  C:\Users\SESA219410\Source\node_modules doesn't exist or is not a directory                                        C:\Users\node_modules doesn't exist or is not a directory                                                          C:\node_modules doesn't exist or is not a directory                                                                looking for modules in C:\Users\SESA219410\Source\rails\bclub\node_modules                                           using description file: C:\Users\SESA219410\Source\rails\bclub\package.json (relative path: ./node_modules)          Field 'browser' doesn't contain a valid alias configuration                                                        using description file: C:\Users\SESA219410\Source\rails\bclub\node_modules\@rails\ujs\package.json (relative path: .)                                                                                                                  no extension                                                                                                         Field 'browser' doesn't contain a valid alias configuration                                                looking for modules in C:\Users\SESA219410\node_modules                                                              No description file found                                                                                          Field 'browser' doesn't contain a valid alias configuration                                                              C:\Users\SESA219410\Source\rails\bclub\node_modules\@rails\ujs is not a file                                     .mjs                                                                                                                 Field 'browser' doesn't contain a valid alias configuration                                                        C:\Users\SESA219410\Source\rails\bclub\node_modules\@rails\ujs.mjs doesn't exist                                 .js                                                                                                                  Field 'browser' doesn't contain a valid alias configuration                                                        C:\Users\SESA219410\Source\rails\bclub\node_modules\@rails\ujs.js doesn't exist                                  .sass                                                                                                                Field 'browser' doesn't contain a valid alias configuration                                                  No description file found                                                                                          no extension                                                                                                         Field 'browser' doesn't contain a valid alias configuration                                                            C:\Users\SESA219410\Source\rails\bclub\node_modules\@rails\ujs.sass doesn't exist                                .scss                                                                                                                Field 'browser' doesn't contain a valid alias configuration                                                    C:\Users\SESA219410\node_modules\@rails\ujs doesn't exist                                                        .mjs                                                                                                                 Field 'browser' doesn't contain a valid alias configuration                                                            C:\Users\SESA219410\Source\rails\bclub\node_modules\@rails\ujs.scss doesn't exist                                .css                                                                                                                 Field 'browser' doesn't contain a valid alias configuration                                                    C:\Users\SESA219410\node_modules\@rails\ujs.mjs doesn't exist                                                    .js                                                                                                                  Field 'browser' doesn't contain a valid alias configuration                                                            C:\Users\SESA219410\Source\rails\bclub\node_modules\@rails\ujs.css doesn't exist                                 .module.sass                                                                                                         Field 'browser' doesn't contain a valid alias configuration                                                    C:\Users\SESA219410\node_modules\@rails\ujs.js doesn't exist                                                     .sass                                                                                                                Field 'browser' doesn't contain a valid alias configuration                                                            C:\Users\SESA219410\Source\rails\bclub\node_modules\@rails\ujs.module.sass doesn't exist                         .module.scss                                                                                                         Field 'browser' doesn't contain a valid alias configuration                                                    C:\Users\SESA219410\node_modules\@rails\ujs.sass doesn't exist                                                   .scss                                                                                                                Field 'browser' doesn't contain a valid alias configuration                                                            C:\Users\SESA219410\Source\rails\bclub\node_modules\@rails\ujs.module.scss doesn't exist                         .module.css                                                                                                          Field 'browser' doesn't contain a valid alias configuration                                                    C:\Users\SESA219410\node_modules\@rails\ujs.scss doesn't exist                                                   .css                                                                                                                 Field 'browser' doesn't contain a valid alias configuration                                                            C:\Users\SESA219410\Source\rails\bclub\node_modules\@rails\ujs.module.css doesn't exist                          .png                                                                                                                 Field 'browser' doesn't contain a valid alias configuration                                                    C:\Users\SESA219410\node_modules\@rails\ujs.css doesn't exist                                                    .module.sass                                                                                                         Field 'browser' doesn't contain a valid alias configuration                                                            C:\Users\SESA219410\Source\rails\bclub\node_modules\@rails\ujs.png doesn't exist                                 .svg                                                                                                                 Field 'browser' doesn't contain a valid alias configuration                                                    C:\Users\SESA219410\node_modules\@rails\ujs.module.sass doesn't exist                                            .module.scss                                                                                                         Field 'browser' doesn't contain a valid alias configuration                                                            C:\Users\SESA219410\Source\rails\bclub\node_modules\@rails\ujs.svg doesn't exist                                 .gif                                                                                                                 Field 'browser' doesn't contain a valid alias configuration                                                    C:\Users\SESA219410\node_modules\@rails\ujs.module.scss doesn't exist                                            .module.css                                                                                                          Field 'browser' doesn't contain a valid alias configuration                                                            C:\Users\SESA219410\Source\rails\bclub\node_modules\@rails\ujs.gif doesn't exist                                 .jpeg                                                                                                                Field 'browser' doesn't contain a valid alias configuration                                                    C:\Users\SESA219410\node_modules\@rails\ujs.module.css doesn't exist                                             .png                                                                                                                 Field 'browser' doesn't contain a valid alias configuration                                                            C:\Users\SESA219410\Source\rails\bclub\node_modules\@rails\ujs.jpeg doesn't exist                                .jpg                                                                                                                 Field 'browser' doesn't contain a valid alias configuration                                                    C:\Users\SESA219410\node_modules\@rails\ujs.png doesn't exist                                                    .svg                                                                                                                 Field 'browser' doesn't contain a valid alias configuration                                                            C:\Users\SESA219410\Source\rails\bclub\node_modules\@rails\ujs.jpg doesn't exist                               C:\Users\SESA219410\node_modules\@rails\ujs.svg doesn't exist                                                    .gif                                                                                                                 Field 'browser' doesn't contain a valid alias configuration                                                          as directory                                                                                                         existing directory                                                                                                   use ./lib/assets/compiled/rails-ujs.js from main in package.json                                                     using description file: C:\Users\SESA219410\Source\rails\bclub\node_modules\@rails\ujs\package.json (relative path: .)                                                                                                                  Field 'browser' doesn't contain a valid alias configuration                                              C:\Users\SESA219410\node_modules\@rails\ujs.gif doesn't exist                                                    .jpeg                                                                                                                Field 'browser' doesn't contain a valid alias configuration                                                        C:\Users\SESA219410\node_modules\@rails\ujs.jpeg doesn't exist                                                   .jpg                                                                                                                 Field 'browser' doesn't contain a valid alias configuration                                                                  using description file: C:\Users\SESA219410\Source\rails\bclub\node_modules\@rails\ujs\package.json (relative path: ./lib/assets/compiled/rails-ujs.js)                                                                                 no extension                                                                                                         Field 'browser' doesn't contain a valid alias configuration                                          C:\Users\SESA219410\node_modules\@rails\ujs.jpg doesn't exist                                                    as directory                                                                                                         C:\Users\SESA219410\node_modules\@rails\ujs doesn't exist                                                                        C:\Users\SESA219410\Source\rails\bclub\node_modules\@rails\ujs\lib\assets\compiled\rails-ujs.js doesn't exist                                                                                                                       .mjs                                                                                                                 Field 'browser' doesn't contain a valid alias configuration                                                        C:\Users\SESA219410\Source\rails\bclub\node_modules\@rails\ujs\lib\assets\compiled\rails-ujs.js.mjs doesn't exist                                                                                                                   .js                                                                                                                  Field 'browser' doesn't contain a valid alias configuration                                                        C:\Users\SESA219410\Source\rails\bclub\node_modules\@rails\ujs\lib\assets\compiled\rails-ujs.js.js doesn't exist                                                                                                                    .sass                                                                                                                Field 'browser' doesn't contain a valid alias configuration                                                        C:\Users\SESA219410\Source\rails\bclub\node_modules\@rails\ujs\lib\assets\compiled\rails-ujs.js.sass doesn't exist                                                                                                                  .scss                                                                                                                Field 'browser' doesn't contain a valid alias configuration                                                        C:\Users\SESA219410\Source\rails\bclub\node_modules\@rails\ujs\lib\assets\compiled\rails-ujs.js.scss doesn't exist                                                                                                                  .css                                                                                                                 Field 'browser' doesn't contain a valid alias configuration                                                        C:\Users\SESA219410\Source\rails\bclub\node_modules\@rails\ujs\lib\assets\compiled\rails-ujs.js.css doesn't exist                                                                                                                   .module.sass                                                                                                         Field 'browser' doesn't contain a valid alias configuration                                                        C:\Users\SESA219410\Source\rails\bclub\node_modules\@rails\ujs\lib\assets\compiled\rails-ujs.js.module.sass doesn't exist                                                                                                           .module.scss                                                                                                         Field 'browser' doesn't contain a valid alias configuration                                                        C:\Users\SESA219410\Source\rails\bclub\node_modules\@rails\ujs\lib\assets\compiled\rails-ujs.js.module.scss doesn't exist                                                                                                           .module.css                                                                                                          Field 'browser' doesn't contain a valid alias configuration                                                        C:\Users\SESA219410\Source\rails\bclub\node_modules\@rails\ujs\lib\assets\compiled\rails-ujs.js.module.css doesn't exist                                                                                                            .png                                                                                                                 Field 'browser' doesn't contain a valid alias configuration                                                        C:\Users\SESA219410\Source\rails\bclub\node_modules\@rails\ujs\lib\assets\compiled\rails-ujs.js.png doesn't exist                                                                                                                   .svg                                                                                                                 Field 'browser' doesn't contain a valid alias configuration                                                        C:\Users\SESA219410\Source\rails\bclub\node_modules\@rails\ujs\lib\assets\compiled\rails-ujs.js.svg doesn't exist                                                                                                                   .gif                                                                                                                 Field 'browser' doesn't contain a valid alias configuration                                                        C:\Users\SESA219410\Source\rails\bclub\node_modules\@rails\ujs\lib\assets\compiled\rails-ujs.js.gif doesn't exist                                                                                                                   .jpeg                                                                                                                Field 'browser' doesn't contain a valid alias configuration                                                        C:\Users\SESA219410\Source\rails\bclub\node_modules\@rails\ujs\lib\assets\compiled\rails-ujs.js.jpeg doesn't exist                                                                                                                  .jpg                                                                                                                 Field 'browser' doesn't contain a valid alias configuration                                                        C:\Users\SESA219410\Source\rails\bclub\node_modules\@rails\ujs\lib\assets\compiled\rails-ujs.js.jpg doesn't exist                                                                                                                   as directory                                                                                                         C:\Users\SESA219410\Source\rails\bclub\node_modules\@rails\ujs\lib\assets\compiled\rails-ujs.js doesn't exist                                                                                                                 using path: C:\Users\SESA219410\Source\rails\bclub\node_modules\@rails\ujs\index                                     using description file: C:\Users\SESA219410\Source\rails\bclub\node_modules\@rails\ujs\package.json (relative path: ./index)                                                                                                            no extension                                                                                                         Field 'browser' doesn't contain a valid alias configuration                                                        C:\Users\SESA219410\Source\rails\bclub\node_modules\@rails\ujs\index doesn't exist                               .mjs                                                                                                                 Field 'browser' doesn't contain a valid alias configuration                                                        C:\Users\SESA219410\Source\rails\bclub\node_modules\@rails\ujs\index.mjs doesn't exist                           .js                                                                                                                  Field 'browser' doesn't contain a valid alias configuration                                                        C:\Users\SESA219410\Source\rails\bclub\node_modules\@rails\ujs\index.js doesn't exist                            .sass                                                                                                                Field 'browser' doesn't contain a valid alias configuration                                                        C:\Users\SESA219410\Source\rails\bclub\node_modules\@rails\ujs\index.sass doesn't exist                          .scss                                                                                                                Field 'browser' doesn't contain a valid alias configuration                                                        C:\Users\SESA219410\Source\rails\bclub\node_modules\@rails\ujs\index.scss doesn't exist                          .css                                                                                                                 Field 'browser' doesn't contain a valid alias configuration                                                        C:\Users\SESA219410\Source\rails\bclub\node_modules\@rails\ujs\index.css doesn't exist                           .module.sass                                                                                                         Field 'browser' doesn't contain a valid alias configuration                                                        C:\Users\SESA219410\Source\rails\bclub\node_modules\@rails\ujs\index.module.sass doesn't exist                                                                                                                                      .module.scss                                                                                                         Field 'browser' doesn't contain a valid alias configuration                                                        C:\Users\SESA219410\Source\rails\bclub\node_modules\@rails\ujs\index.module.scss doesn't exist                                                                                                                                      .module.css                                                                                                          Field 'browser' doesn't contain a valid alias configuration                                                        C:\Users\SESA219410\Source\rails\bclub\node_modules\@rails\ujs\index.module.css doesn't exist                    .png                                                                                                                 Field 'browser' doesn't contain a valid alias configuration                                                        C:\Users\SESA219410\Source\rails\bclub\node_modules\@rails\ujs\index.png doesn't exist                           .svg                                                                                                                 Field 'browser' doesn't contain a valid alias configuration                                                        C:\Users\SESA219410\Source\rails\bclub\node_modules\@rails\ujs\index.svg doesn't exist                           .gif                                                                                                                 Field 'browser' doesn't contain a valid alias configuration                                                        C:\Users\SESA219410\Source\rails\bclub\node_modules\@rails\ujs\index.gif doesn't exist                           .jpeg                                                                                                                Field 'browser' doesn't contain a valid alias configuration                                                        C:\Users\SESA219410\Source\rails\bclub\node_modules\@rails\ujs\index.jpeg doesn't exist                          .jpg                                                                                                                 Field 'browser' doesn't contain a valid alias configuration                                                        C:\Users\SESA219410\Source\rails\bclub\node_modules\@rails\ujs\index.jpg doesn't exist        `

**Comment by iangullo** [comment]
Previous message using Rails 6.1.4
