### ISSUE TITLE
Document speeding up TypeScript compilation

### ISSUE THREAD

**Issue by connorshea** [rails/webpacker#2249]
I added TypeScript to my Rails apps a few weeks ago and booting the webpack dev server was taking 60 or more seconds (I'm not sure if this is because of typescript or a combination of typescript and vue). It eventually got annoying enough that I searched around for a solution, and found this fork-ts-checker-webpack-plugin package: https://github.com/TypeStrong/fork-ts-checker-webpack-plugin

My initial compile time was 60-80 seconds, and now it's about 12-20 seconds.

This is based on my experience doing this in my own project here: https://github.com/connorshea/VideoGameList/pull/624

------

- Add the package to your `package.json` with `yarn add fork-ts-checker-webpack-plugin`.
- Add this to `config/webpack/environment.js` (you can remove the `vue: true` part if you're not using Vue):
```javascript
const ForkTsCheckerWebpackPlugin = require('fork-ts-checker-webpack-plugin');

environment.plugins.append(
  'ForkTsCheckerWebpackPlugin',
  new ForkTsCheckerWebpackPlugin({
    vue: true,

    // makes webpack wait for type checking to finish before "emitting"; allows
    // type errors to remain present in the build output from webpack and in
    // webpack-dev-server's darkened overlay
    async: false
  })
);
```

- Add `transpileOnly: true` to the `options` in `config/webpack/loaders/typescript.js`:
```javascript
const PnpWebpackPlugin = require('pnp-webpack-plugin');

module.exports = {
  test: /\.(ts|tsx)?(\.erb)?$/,
  use: [
    {
      loader: 'ts-loader',
      options: PnpWebpackPlugin.tsLoaderOptions({
        appendTsSuffixTo: [/\.vue$/],
        transpileOnly: true
      })
    }
  ]
};
```

If you don't use Vue, the `typescript.js` file might look a bit different.

-----

Should I contribute this to the typescript documentation?

**Comment by jakeNiemiec** [comment]
> Should I contribute this to the typescript documentation?

It would be very welcome. Personally, I stopped using typescript due to the crushing compile times, I'm glad to see modern solutions for this popping up.

**Comment by guillaumebriday** [comment]
Is this issue still relevant? Feel free to reopen if needed
