### ISSUE TITLE
3.6.0 release is not mentioned in the CHANGELOG

### ISSUE THREAD

**Issue by nfedyashev** [rails/webpacker#2253]
This is not a huge issue obviously, just making it a bit uneasy to upgrade.

https://github.com/rails/webpacker/blob/master/CHANGELOG.md

https://rubygems.org/gems/webpacker/versions

**Comment by ShootPassSlam** [comment]
I can update this. It looks like the CHANGELOG is missing v3.4.3 to v3.6.0 so I can add them all.

**Comment by ShootPassSlam** [comment]
Pull request here: [https://github.com/rails/webpacker/pull/2262](url)

**Comment by ShootPassSlam** [comment]
The CHANGELOG has been updated on master. This issue should be closed.

Thanks!
