### ISSUE TITLE
Misleading error message for "Can't find {bundle_name} in {manifest}" without node_modules

### ISSUE THREAD

**Issue by dbackeus** [rails/webpacker#2261]
On a fresh rails 6 app with some scaffolded resources for tests, simply not having `node_modules` installed and running`bin/rails test` will result in:

```
ActionView::Template::Error: Webpacker can't find application in /path-to-rails-app/public/packs-test/manifest.json. Possible causes:
1. You want to set webpacker.yml value of compile to true for your environment
   unless you are using the `webpack -w` or the webpack-dev-server.
2. webpack has not yet re-run to reflect updates.
3. You have misconfigured Webpacker's config/webpacker.yml file.
4. Your webpack configuration is not creating a manifest.
Your manifest contains:
{
}
```

This feels like quite a red herring when what we actually need to do is run `yarn install`.

**Comment by AxelTheGerman** [comment]
I was getting the same error when running `rails test` however my issue was that I'm using an NPM package that requires an auth token and the environment variable wasn't set. 

Would have saved me some time to see that original error. Unfortunately I know nothing about webpack (and would prefer not to use it if I had an alternative) so I don't know how to contribute to a fix

**Comment by guillaumebriday** [comment]
You need to compile your assets before running tests or add the option in your `webpacker.yml`
