### ISSUE TITLE
Using webpacker with favicons-webpack-plugin

### ISSUE THREAD

**Issue by anitagraham** [rails/webpacker#2265]
I am generating favicons using the favicons-webpack-plugin.  There seem to be two problems

- the file created by the plugin is in the wrong directory
- the file created by the plugin is not in `manifest.json`

This is my favicon-webpack-plugin config in `environment.js`

```
const favIconsConfig = {
  logo: path.join(SourceBranch('images'), '/Logo.png'),
  favicons: {
    icons: {
      android: false,
      appleIcon: false,
      appleStartup: false,
      coast: false,
      favicons: true,
      firefox: false,
      windows: false,
      yandex: false
    }
  }
}
```
and
```
environment.plugins.append('FaviconsWebpackPlugin', new FaviconsWebpackPlugin(favIconsConfig))
```

this produces `public/packs/packs/assets/favicon.png`, which is not mentioned in `public/packs/manifest.json`.

The output includes

```
Version: webpack 4.36.1                                                                                                                         
Time: 11413ms
Built at: 09/02/2019 5:31:00 PM
                                   Asset      Size     Chunks             Chunk Names
               /packs/assets/favicon.png    47 KiB             [emitted]  
                 css/events-8786ad0b.css   351 KiB     events  [emitted]  events
             css/events-8786ad0b.css.map   590 KiB     events  [emitted]  events

```
Changing the favicons options to use various combinations of 
```
publicPath: '/public',
outputPath: '/public/icons',
```
makes no difference.

Am I able to use `favicons-webpack-plugin` with webpacker?
How does it indicate to webpacker that a file has been emitted and should be catalogued in the manifest?

I think the fact that it is always in `packs/packs`  is a `favicons-webpack-plugin` issue but I would like to know how it should work with webpacker before moving on to that.

Thanks

**Comment by jakeNiemiec** [comment]
[`html-webpack-plugin`](https://github.com/jantimon/html-webpack-plugin) is probably incompatable with Rails since `html-webpack-plugin` uses `nodeJS` to generate `html` instead of `ruby/erb`.

**Comment by anitagraham** [comment]
Thanks for the quick reply. Although, thinking about it, I'm not using `html-webpack-plugin` at all, just getting `favicon-webpack-plugin` to generate the favicons.

Nonetheless thanks, and I will try a different approach.

**Comment by Szymon-dziewonski** [comment]
@anitagraham were you able to make it running? I have the same problem

**Comment by anitagraham** [comment]
I do seem to have it working (had to go back and check). After removing all the guff here is what I have configured. The favicon ends up in `public/packs/assets`.

The `favicons-webpack-plugin` has had quite a bit of work done on it recently. All kudos to [jantimon](https://github.com/jantimon) and other contributors.

```
// config/webpack/environment.js
const FaviconsWebpackPlugin = require('favicons-webpack-plugin')

// Favicons configuration options
// note, I also have all the icon-types apart from favicons, set to false
const favIconsConfig = {
  logo: path.join(SourceBranch('images'), 'client_icon.png'),
  publicPath: '..',
  favicons: {
    favicons: true,             // Create regular favicons. `boolean` or `{ offset, background, mask,  }
  }
environment.plugins.append( 'FaviconsWebpackPlugin', new FaviconsWebpackPlugin(favIconsConfig) )
```
and in `package.json`

```json
 "favicons": "^5.4.1",
 "favicons-webpack-plugin": "^3.0.1",
```
