### ISSUE TITLE
Ability to set publicPath "On The Fly"

### ISSUE THREAD

**Issue by summera** [rails/webpacker#2269]
As discussed in the [webpacker docs](https://webpack.js.org/guides/public-path/#on-the-fly) it is possible to set the `publicPath` on the fly using `__webpack_public_path__`. This has been discussed in a few older tickets (https://github.com/rails/webpacker/issues/1186, https://github.com/rails/webpacker/issues/1084, https://github.com/rails/webpacker/issues/1080). However, it is unclear from these whether this will actually work with webpacker and if there are any issues preventing it from working. It would seem, based on the [webpack source code](https://github.com/webpack-contrib/file-loader/blob/master/src/index.js#L40), that this **won't** work with webpacker because webpacker forces the `output.publicPath`. When `output.publicPath` is set, webpack does **not** use `__webpack_public_path__` as you can see in the [webpack source code](https://github.com/webpack-contrib/file-loader/blob/master/src/index.js#L40). Is this correct? If so, is it possible to add support for "On the Fly" public paths or are there other issues making this difficult? Thanks in advance!

**Comment by summera** [comment]
@gauravtiwari any thoughts on this?

**Comment by summera** [comment]
Right now, I am setting `WEBPACKER_ASSET_HOST` at compile time. Since the host to our CDN varies based on environment (staging, production, etc.), that means that assets have to be precompiled differently for each environment. It would make things easier and more flexible to precompile assets the same way across the board and be able to configure the host (via `publicPath` at runtime). 

As an example, if your application is dockerized and you are precompiling your assets in your Dockerfile, you want to be able to build a single image that will work in all your environments. However, if you have to precompile them differently for each environment, you would have to build your image differently for each environment using build args as well. This use case was also mentioned in https://github.com/rails/webpacker/issues/1080.

**Comment by summera** [comment]
@jakeNiemiec thanks for the suggestion! I got this working after messing around with it for a bit. The configuration/setup looks like the following:

```js
// config/webpack/environment.js

// This needs to be set to empty string. null won't work
environment.config.output.publicPath = "";
```

```erb
<%# app/views/layouts/application.html.erb %>

<% webpack_public_output_path = Webpacker.config.public_output_path.basename %>

<script>
  window.__webpack_public_path__ = "<%= Rails.configuration.action_controller.asset_host %>/<%= webpack_public_output_path %>/";
</script>

```

```js
// app/javascript/packs/application.js

// insert this at the top of your file before all your imports in your pack file
__webpack_public_path__ = window.__webpack_public_path__;
```

I'm wondering if there is a better way but after doing this I came across https://github.com/webpack/webpack/issues/443 which suggests the same thing for the most part. This configuration allows you to use a dynamic public path based on the rails configuration for asset host. So, if asset host changes based on environment the public path will reflect that and you can compile your assets the same across the board. 

I was trying to see if this could be worked into the `webpacker` gem somehow but the only way I see is to provide a helper to include in your layout that sets `window.__webpack_public_path__` like the above. However, you'd still have to insert `__webpack_public_path__ = window.__webpack_public_path__` at the top of your pack files. Is there a way that could be done with `webpacker` at compile time? I'd be happy to open a PR if there's a way to make it happen.

**Comment by jakeNiemiec** [comment]
> I was trying to see if this could be worked into the webpacker gem

I can't think of a one-size-fits-all solution. I think webpacker just needs a document that acts like https://github.com/k88hudson/git-flight-rules

**Comment by tsareg** [comment]
Have you seen https://github.com/agoldis/webpack-require-from ?

**Comment by haines** [comment]
We ran into trouble with @summera's [approach](https://github.com/rails/webpacker/issues/2269#issuecomment-548816104) because it broke URLs in CSS files.

Before changing the webpack config we got

```css
background-image: url(/packs/media/foo/bar.png)
```

but with `environment.config.output.publicPath = ''` that gets written as 

```css
background-image: url(media/foo/bar.png)
```

We ended up using this workaround, which prepends `/packs/` at compile time and then additionally prepends the asset host at runtime:

```javascript
// config/webpack/environment.js

const { output } = environment.config;
const { publicPath } = output;
const fileLoader = environment.loaders.get('file');

output.publicPath = '';

Object.assign(fileLoader.use[0].options, {
  publicPath,
  postTransformPublicPath: (p) => `__webpack_public_path__ + ${p}`
});
```

```erb
<%# app/views/layouts/application.html.erb %>

<script>
  window.__webpack_public_path__ = '<%= j Rails.configuration.action_controller.asset_host %>';
</script>
```

```javascript
// app/javascript/packs/application.js

__webpack_public_path__ = window.__webpack_public_path__;
```

The result is that the CSS bundle has the correct relative URLs (relative is fine here, because the images are served from the same CDN as the CSS), while the JS bundle dynamically generates absolute URLs.

**Comment by tomprats** [comment]
In case someone is still trying to do this and upgrading to version 6, the solution is pretty much the same but you also have to update the WebpackAssetsManifest plugin. My production.js now looks like this:

```
process.env.NODE_ENV = process.env.NODE_ENV || "production";

const webpackConfig = require("./base");

webpackConfig.output.publicPath = ""; // https://github.com/rails/webpacker/issues/2269
webpackConfig.plugins[1].options.publicPath = "/packs/";

module.exports = webpackConfig
```

There's probably a way to use your config instead of specifying `packs` directly, but I didn't have time to look into that yet
