### ISSUE TITLE
External js with webpacker

### ISSUE THREAD

**Issue by 127** [rails/webpacker#2272]
Help needed. Can somebody tell how the hell can I use usual normal external javascript from CDN? For example I need a jQuery without building it in production with lot's of different unknown tools  and dependencies I do not need.
The docs are still old even on the edge side.

**Comment by HarrisonB** [comment]
Do you just want to include a separate `<script>` tag? Webpacker is for bundling assets you have locally (generally).

**Comment by 127** [comment]
I need just part of my assets to be built up locally. A jquery-like is good enough drom CDN. I have a lot of scope conflicts like not available $ or partialetc. So is it ok

**Comment by HarrisonB** [comment]
I would say this is more of a Webpack problem than a Webpacker problem, so I wouldn’t worry about finding a Rails-specific solution.

If you’re trying to access a global property defined on the `window` (like how jQuery is often managed) then I’d suggest reading [the Webpack docs on shimming globals](https://webpack.js.org/guides/shimming/).

**Comment by jakeNiemiec** [comment]
@127 In your packs, if jquery is external, you can do something like:

```js
export function getJq() {
  return window.$ || require('jquery');
}
```

Each webpacked script will have a single reference to jQuery:
```js
import { getJq } from '../myCoreJsFile';
const $ = getJq();
import 'mySuperJqueryPlugin'; // lib that modifies `window.$.fn.mySuperPlugin` 
$('asdf').mySuperPlugin();
```
This helps when you have plugins that modify jQuery, but there are many exceptions to this. It really depends on what you need. Hope this helps.

**Comment by 127** [comment]
Thank you. It doesn't look a Rails Way but should work, I guess.
