### ISSUE TITLE
Image broken in production with asset host on webpacker 3.5.5

### ISSUE THREAD

**Issue by ajsharp** [rails/webpacker#2275]
I have a component like this:

```jsx
import React from 'react'
import verifiedIcon from 'img/verified-icon@2x.png'

const VerifiedIcon = () => (
  <img src={verifiedIcon}  />
)

export default VerifiedIcon
```

This works in development, broken in production. I'm successfully serving my js/css assets from an asset host, but in prod, the asset host isn't used for images. So js/css are served from `CDN.domain.com/packs/...` but image assets are just `domain.com/packs/...`.

I'm using out of the box webpacker 3.5.5 configuration. Is there some additional configuration I need to add?

**Comment by SkyMack** [comment]
I have the same issue using webpack 4.0.7 with Rails 5.0. Javascript and CSS are coming from the CDN, but images (like icon SVGs for example) are all linked with a relative URL.

There is a thread about a similar problem with older webpack versions and a potential work around here:
https://github.com/rails/webpacker/issues/1186#issuecomment-358110765

It looks like the bug either still exists in 4.0.7, or has come back.

**Comment by rubendinho** [comment]
We're having a similar issue here (4.0.7).  

We are using the compiled script on another server as an embedded script, and the relatively-linked URLs of images are causing "Failed to load resource: net::ERR_FILE_NOT_FOUND" errors.

**Comment by guillaumebriday** [comment]
Is this issue still relevant? Feel free to reopen if needed

**Comment by tanaylakhani** [comment]
For anyone interested. It looks like this happens when you run `bin/webpack` instead of `rails assets:precompile` to compile react assets. When you run `bin/webpack` it appears asset_host value is not considered. You can fix it by adding environment variable `WEBPACKER_ASSET_HOST` explicitly to your configuration.
