### ISSUE TITLE
bundle exec rails webpacker:install:typescript creates an invalid entry in config/webpack/environment.js

### ISSUE THREAD

**Issue by akoskm** [rails/webpacker#2277]
webpacker version: 4.0.7

It appends the line which should register the loader and also creates the loader, but it's not `require`d:
<img width="1291" alt="image" src="https://user-images.githubusercontent.com/3111627/64561472-264b7c80-d34b-11e9-976c-a26d2a6e4761.png">

**Comment by jakeNiemiec** [comment]
I think this is the missing line:

https://github.com/rails/webpacker/blob/a42f69ca016d45aaeac8824ee87997085e75b371/lib/install/typescript.rb#L23

**Comment by ShootPassSlam** [comment]
Can this ticket be closed? 

I attempted to reproduce this and it looks like "webpacker/lib/install/typescript.rb" properly added the require typescript line to "config/webpack/environment.js"
