### ISSUE TITLE
@babel/polyfill

### ISSUE THREAD

**Issue by nPaul** [rails/webpacker#2285]
I have problems with es5.map

im use  vuelayers node component

iam do
yarn add @babel-polyfill

and configure babel.config.js
useBuiltins: 'usage'

but babel not automatic include es6.map polyfills!
maybe need upgrade all dependecies in webpacker babel to 7.6.0?? last versions, just it 7.4.0

**Comment by RiccardoMargiotta** [comment]
Webpacker 4 is now using `core-js` for polyfilling.

In my Babel config, I have `useBuiltIns: usage` and `corejs: 3` set for automatic polyfilling based on `.browserslistrc`.

**Comment by guillaumebriday** [comment]
Can this issue be closed ?

**Comment by nPaul** [comment]
ye, this issue can be closed
i forgot how to i fix this problem
but just i have another problem with Intl polyfills

**Comment by guillaumebriday** [comment]
Feel free to close the issue then 👍
