### ISSUE TITLE
Webpacker::Manifest::MissingEntryError for Host assets when using an Engine

### ISSUE THREAD

**Issue by tangentus** [rails/webpacker#2289]
**The short and sweet of it**
The documented Webpacker Engine configuration works amazing, but does not allow any assets to be requested that are outside of the Engine when rendering an Engine route. Below is a potential/suggested fix that is working for me but more than anything I wanted to document the issue itself.

**Context**
So I recently have been working on an Engine that will utilize Webpacker for asset  compilation, since the majority of consuming Host applications will be using Webpacker as well. I followed the [Docs located here](https://github.com/rails/webpacker/blob/master/docs/engines.md) and they were fantastic! So first off, thank you! 

The unfortunate part was that when I mounted the Engine inside of a Rails app, my Host app could no longer render assets. Instead, the Engine's instance of Webpacker [that we override here](https://github.com/rails/webpacker/blob/master/docs/engines.md#step-5-configure-helper) would try (and fail) to find the asset. Any route that the Engine controlled meant that Engines Webpacker was used for _all_ assets requested.

The use case that brings this issue about is that I want consuming "Host" applications to draw layout items (nav, top-bar, footer, etc.) which will require loading styles/javascript. The Engine renders into whatever space the Host gives it.

So, the need is to select _which_ Webpacker instance we want to use given the context. 

Something like this:

```
# app/helpers/my_engine/application_helper.rb
# ....
def current_webpacker_instance
      return MyEngine.webpacker if virtual_path.include?(MyEngine.name.underscore)

      ::Webpacker.instance
end
# ....
```

The `virtual_path` instance variable is given by ActionView when it is rendering a template. This is available in the `application_helper` since it is included into the Controller during the request. 

**Why this works**
`virtual_path` gives the relative path (from the base `views` directory) of the current template being rendered, which is extremely useful for Webpacker. Why? Given that we are in an Engine context, all of our Views are namespaced i.e. the `virtual_path` will contain the underscored/lowercased module name. This allows us to say "Are we rendering a view that I care about and have assets for?" and defer to `::Webpacker.instance` (the Host Webpacker) if we are not.

**Comment by justin808** [comment]
Closing because stale.
