### ISSUE TITLE
Problems with Yarn symlinks (bin-links) under Windows host with Vagrant Linux guest

### ISSUE THREAD

**Issue by Rynaro** [rails/webpacker#229]
I think it's Yarn problem, but if we consider all ways to work with Rails, we need to consider a Windows running a Vagrant instance as a development environment. (Is one of my available environments to work. And with this environment, fortunately I get the problem)

Vagrant uses the host filesystem to hold the guest filesystem. And when we call a npm, or yarn action to install or configure, we will get a problem to create _symlinks_ like `.bin` folders. And this behaviour avoids the _webpacker:install_ to create some environment files like `manifest.json`. After some warnings, and link errors, the installations return a success for **webpacker** installation.

I see both Yarn and NPM has the `--no-bin-links`, I think it's a great idea to include a argument on install to create this behavior. Or add other ways to configure the webpacker on Vagrant on Windows.

_Note: In Linux with a Linux Vagrant the **webpacker** works well. I only found this "problem" in Windows with Linux Vagrant._

**Comment by andreas-sotnik** [comment]
I have same issues using **Docker Toolbox** with **Windows 10** on the host machine.

**Comment by gauravtiwari** [comment]
@Rynaro Could you pull in latest master `bundle update webpacker` and verify if this problem still exist?

**Comment by Rynaro** [comment]
@gauravtiwari . Sure, I will setup the same configuration Windows system with Vagrant (+ Ubuntu) workspace that gives to me this issue behavior.
I'll update you soon as possible.

**Comment by gauravtiwari** [comment]
This is fixed now on latest master. Please update webpacker, re-run installer to replace binstubs and try again 👍

**Comment by Rynaro** [comment]
@gauravtiwari I've checked here. And is really fixed on code based in master release!

**Comment by gauravtiwari** [comment]
Awesome 👍

**Comment by estvmachine** [comment]
@Rynaro  Hi, you can share your vagrant file, package.json. I cant made works with vagrant?. 
Thanks in advance

**Comment by gauravtiwari** [comment]
@estvmachine Are you getting any errors? Please could you share the problem.

**Comment by estvmachine** [comment]
@gauravtiwari  I did a ticket in #562 but basically is the same problem exposed here,  from windows i use a vagrant ubuntu machine that always give me the error with symlink associated to '../acorn/bin/accorn' and symlink associated to '../../../multicast-dns/cli.js'

![image](https://user-images.githubusercontent.com/2062668/28243006-69080df4-698a-11e7-855f-f105e59f89b1.png)

**Comment by gauravtiwari** [comment]
@estvmachine Ohh, sorry I missed that one but from the logs this seems to be related to yarn. Can you try reinstalling dev server using npm instead - `npm install --save-dev webpack-dev-server` and see what happens? 

May be you should file the same issue to yarn repo :)

**Comment by stvmachine** [comment]
hi try to do that but works :(.  Is a problem with vagrant, but others people can solved for their problems, but i dont know what to do for webpacker: https://github.com/mitchellh/vagrant/issues/6188

**Comment by wcalvert88** [comment]
I'm not sure if this issue is a problem for anyone else but I was able to work around it by stopping vagrant and just running yarn install in the synced folder and then vagrant up and everything worked fine.  One thing to note though since I did this outside of the vm when I do vagrant up it says cannot find base.  To fix that find your box id and do `vagrant up idHere`  I hope it helps
