### ISSUE TITLE
How to add short_name to the manifest

### ISSUE THREAD

**Issue by jfqd** [rails/webpacker#2291]
I am searching for a way to add `short_name`, `background_color`, `display`, etc. to the manifest, but cannot find anything in the docs about it. Is this possible? And when how?

**Comment by jakeNiemiec** [comment]
The generated asset manifest (https://github.com/danethurber/webpack-manifest-plugin) is different from a Web App Manifest (https://developer.mozilla.org/en-US/docs/Web/Manifest).
