### ISSUE TITLE
Broken Component ReactJS

### ISSUE THREAD

**Issue by Bdoom** [rails/webpacker#2294]
For some reason, webpacker isn't compiling all of my components. It compiles all but this one:

`[101] ./app/javascript/components/Conversation.js + 1 modules 8.17 KiB {0} {1} [optional] [built]
`

For some reason, my other components work just fine.

**Comment by jakeNiemiec** [comment]
Where is `app/javascript/components/Conversation.js` imported?

**Comment by guillaumebriday** [comment]
I think you have a problem inside this component
