### ISSUE TITLE
Troubleshooting webpacker

### ISSUE THREAD

**Issue by jamesla** [rails/webpacker#2296]
I have a rails 6 app that works fine in dev but in prod the styles are not working. This is very difficult to troubleshoot since webpackers verbose option only appears to be related to compilation errors which I am not getting any of.

It's also very difficult to troubleshoot since the files are all minimised so not easy to read.

I have read through the docs but I am unable to find some simple webpacker debugging instructions for the instance that an app works in dev but not in production and no error is thrown. 

I am not getting a browser console error, a webpacker compilation error or any rails log errors however it works fine in dev. Where can I find additional information on how to troubleshoot webpacker?

**Comment by jamesla** [comment]
Ok I solved my own problem, for some reason I neeeded

```
<%= stylesheet_pack_tag 'application' %>
```

in prod even though you don't need it in dev.

**Comment by renchap** [comment]
In development mode, the styles are loaded using Javascript (so hot reloading works).
In production, styles are compiled to a `.css` file, so it needs to be loaded by your page.
