### ISSUE TITLE
gem rails 6.0.0.rc2 and yarn upgrade issue

### ISSUE THREAD

**Issue by aliraxa-max** [rails/webpacker#2300]

**Comment by aliraxa-max** [comment]
=> Booting Puma
=> Rails 6.0.0.rc2 application starting in development 
=> Run `rails server --help` for more startup options
error Couldn't find an integrity file                                                                                                                
error Found 1 errors.                                                                                                                                


========================================
  Your Yarn packages are out of date!
  Please run `yarn install --check-files` to update.
========================================


To disable this check, please change `check_yarn_integrity`
to `false` in your webpacker config file (config/webpacker.yml).


yarn check v1.17.3
info Visit https://yarnpkg.com/en/docs/cli/check for documentation about this command.


Exiting

**Comment by jakeNiemiec** [comment]
Wheres the problem? Did you try following the instructions from the error message?
