### ISSUE TITLE
How to use webpacker with loadable-components?

### ISSUE THREAD

**Issue by zverexe** [rails/webpacker#2302]
Hello, I want to use https://github.com/smooth-code/loadable-components for better components lazy loading(splitting components)? I cannot find an appropriate way to add proper configs to webpacker config, especially for ssr. I saw this issue https://github.com/rails/webpacker/issues/1403 that was resolved and the example provided, can somebody do something similar?

**Comment by jakeNiemiec** [comment]
SSR is far outside the scope of webpacker. (SSR like https://www.smooth-code.com/open-source/loadable-components/docs/server-side-rendering/#collecting-chunks)

I hear [React on Rails](https://github.com/shakacode/react_on_rails) has a good SSR flow.

**Comment by justin808** [comment]
Hi @zverexe, we've got [loadable-components.com](https://loadable-components.com/)  working great with React on Rails. At the present time, this requires a Node renderer and thus [React on Rails Pro](https://www.shakacode.com/react-on-rails-pro/).

You can see an example using this here: https://www.cafemonarch.com/

![image](https://user-images.githubusercontent.com/1118459/78464926-26b2b880-768b-11ea-8719-32001758b6df.png)
