### ISSUE TITLE
Invocation of optimize-css-assets-webpack-plugin is incorrect

### ISSUE THREAD

**Issue by jamesarosen** [rails/webpacker#2304]
`production.js` [adds](https://github.com/rails/webpacker/blob/2cef2fd6c20876704062c40dd612c219166deed7/package/environments/production.js#L33-L42) an instance of `optimize-css-assets-webpack-plugin`:
```js
this.plugins.append(
  'OptimizeCSSAssets',
  new OptimizeCSSAssetsPlugin({
    parser: safePostCssParser,
    map: {
      inline: false,
      annotation: true
    }
  })
)
```

But that's not the API for [that plugin](https://github.com/NMFR/optimize-css-assets-webpack-plugin/blob/v5.0.3/src/index.js). There is no mention of `parser` in that file. The way to pass `map` options is through `cssProcessorOptions`:
```js
this.plugins.append(
  'OptimizeCSSAssets',
  new OptimizeCSSAssetsPlugin({
    cssProcessorOptions: {
      map: {
        annotation: true,
        inline: false,
      },
    },
  })
)
```

**Comment by aried3r** [comment]
Hmm, is this `parser` option really for the plugin? I am not a 100% sure, but I believe `cssProcessorOptions` is passed to postcss itself. WDYT, @jamesarosen? 

It gets [set here](https://github.com/NMFR/optimize-css-assets-webpack-plugin/blob/0a410a9bf28c7b0e81a3470a13748e68ca2f50aa/src/index.js#L25-L27) Then [used here](https://github.com/NMFR/optimize-css-assets-webpack-plugin/blob/0a410a9bf28c7b0e81a3470a13748e68ca2f50aa/src/index.js#L45-L48) and this is finally [used here](https://github.com/NMFR/optimize-css-assets-webpack-plugin/blob/0a410a9bf28c7b0e81a3470a13748e68ca2f50aa/src/index.js#L73).

`parser` option: https://github.com/postcss/postcss#options

**Comment by jamesarosen** [comment]
I find the [PostCSS "Options" section](https://github.com/postcss/postcss#options) that you linked to revealing:

> Options
> Most PostCSS runners accept two parameters:
>  * An array of plugins.
>  * An object of options.
>
> Common options:
>  * syntax: an object providing a syntax parser and a stringifier.
>  * parser: a special syntax parser (for example, SCSS).
>  * stringifier: a special syntax output generator (for example, Midas).
>  * map: source map options.
>  * from: the input file name (most runners set it automatically).
>  * to: the output file name (most runners set it automatically).

It seems like @rails/webpacker is _assuming_ that OptimizeCSSAssetsPlugin obeys that standard but it does not.

The [postcss-loader](https://github.com/postcss/postcss-loader) for Webpack has cssnano support built-in now. We may be able to replace the OptimizeCSSAssetsPlugin with that altogether. From their docs:

```js
// webpack.config.js
{
  loader: 'postcss-loader',
  options: {
    ident: 'postcss',
    plugins: (loader) => [
      require('postcss-import')({ root: loader.resourcePath }),
      require('postcss-preset-env')(),
      require('cssnano')()
    ]
  }
}
```

**Comment by aried3r** [comment]
> It seems like @rails/webpacker is _assuming_ that OptimizeCSSAssetsPlugin obeys that standard but it does not.

Does it not? From the source that I posted I assumed it gets passed correctly to the postcss processor.

Anyway, if you believe that we can do without this plugin altogether, would you be up for putting together a PR? :)

**Comment by jamesarosen** [comment]
> It gets [set here](https://github.com/NMFR/optimize-css-assets-webpack-plugin/blob/0a410a9bf28c7b0e81a3470a13748e68ca2f50aa/src/index.js#L25-L27)

The plugin expects to be called as
```js
new OptimizeCssAssetsWebpackPlugin({ cssProcessorOptions })
```
but this project calls it as
```js
new OptimizeCssAssetsWebpackPlugin({ parser, map })
```
