### ISSUE TITLE
Cannot find module 'core-js/stable' on new install

### ISSUE THREAD

**Issue by soundasleep** [rails/webpacker#2305]
A brand new install on Rails 5.2.3, following the instructions on the README.md. I've added the gem to the `Gemfile`, ran `bundle exec rails webpacker:install` and `bundle exec rails webpacker:install:react`. Everything seems fine so far.

If I put this into the top of my `/app/javascripts/packs/application.js`:

```js
import "core-js/stable";
```

Then I get a missing module error:

```
Uncaught Error: Cannot find module 'core-js/stable'
    at webpackMissingModule (application.js:1)
```

I'm not sure what module this is or where it should be coming from. Is it necessary? Is the README up to date?

**Comment by jakeNiemiec** [comment]
If you were following the [Babel Guide](https://github.com/rails/webpacker/blob/d393cc4f4c2e547fbfe0c131be74f562a3da4c49/docs/es6.md#babel), try running `yarn add regenerator-runtime core-js`

**Comment by pedro21** [comment]
Hi, did you get to solve the problem? I am currently experiencing the same problem.
Thanks in advance

**Comment by guillaumebriday** [comment]
Can this issue be closed ?

**Comment by rbgada-hayfin** [comment]
Same issue
