### ISSUE TITLE
Problem with svelte/store import

### ISSUE THREAD

**Issue by cgimenez** [rails/webpacker#2307]
I've got pretty good results with WebPacker svelte integration, until I tried to use stores. 

**store.js**
```
import { writable } from 'svelte/store';
export const count = writable(0);
```

**myComponent.svelte**
```
<script>
import { count } from './store.js';
</script>
```

the webpacker-dev process produces an error

`
ERROR in ./app/javascript/svelte/store.js 2:19-27
"export 'writable' was not found in 'svelte/store'
`

webpacker.yml is quite a stock version excepted for dev_server host, port and public settings

WebPacker version is from master branch

**package.json**

```
{
  "name": "svelte_app",
  "private": true,
  "dependencies": {
    "@rails/actioncable": "^6.0.0-alpha",
    "@rails/activestorage": "^6.0.0-alpha",
    "@rails/ujs": "^6.0.0-alpha",
    "@rails/webpacker": "^4.0.7",
    "core-js": "^3.2.1",
    "rails-erb-loader": "^5.5.2",
    "regenerator-runtime": "^0.13.3",
    "svelte": "^3.12.1",
    "svelte-loader": "^2.13.6",
    "turbolinks": "^5.2.0"
  },
  "version": "0.1.0",
  "devDependencies": {
    "webpack-dev-server": "^3.8.1"
  }
}
```

**Comment by cgimenez** [comment]
I recreated an empty rails 6 + WebPacker from master + svelte and erb loaders

Everything is working as expected. So it's not an issue with WebPacker, it's a config problem in my working app. Sorry for the inconvenience !

**Comment by davidwparker** [comment]
> I recreated an empty rails 6 + WebPacker from master + svelte and erb loaders
> 
> Everything is working as expected. So it's not an issue with WebPacker, it's a config problem in my working app. Sorry for the inconvenience !

Care to share what you ended up doing/ how you ended up implementing this?
I'm having similar issues now.

Though I can clearly see in /node_modules that svelte/store is all there and I'm able to import other things okay.
