### ISSUE TITLE
How to use webpacker with jQuery and RJS?

### ISSUE THREAD

**Issue by sr3d** [rails/webpacker#2308]
I'd like to be able to use RJS to do some minor updates on the screen, before in the RJS response I could do something like  `$("#target").html("<%= j some_html %>")` but since moving to Rails 6.1 and webpacker, I keep getting an error for $ is null.

Apparently the RJS is appended to the page as a script tag and it is then evaluated, but the context is different and $ (or jquery, or window.jquery) isn't available anymore.

In the environment.js file I have already included jQuery:
```javascript
const { environment } = require('@rails/webpacker')

const webpack = require('webpack');
environment.plugins.append('Provide', new webpack.ProvidePlugin({
  $: 'jquery',
  jQuery: 'jquery',
  jquery: 'jquery',
  'window.jQuery': 'jquery',
  "window.$": "jquery",
  "Pusher": 'Pusher',

  Rails: ['@rails/ujs'],

}));
module.exports = environment
```

Any help would be appreciated!

**Comment by rossta** [comment]
The `ProvidePlugin` as you've configured it, will import jquery to modules **within** your Webpack build. A rails JS template as you've described, does not have access to JS within your Webpack modules unless you **expose** those vars to the global scope. There are a number of ways you could accomplish this, each with pros and cons. Here's one SO post that shows how you'd use the `expose-loader`. https://stackoverflow.com/questions/29080148/expose-jquery-to-real-window-object-with-webpack

**Comment by guillaumebriday** [comment]
Can this issue be closed ?
