### ISSUE TITLE
Webpacker config files in coffeescript?

### ISSUE THREAD

**Issue by joker-777** [rails/webpacker#2309]
Hi,

Is there a way to write the webpacker config files in CoffeeScript? It looks like that it only accepts javascript files.

Thanks!

**Comment by gingerlime** [comment]
Does [this](https://github.com/rails/webpacker/issues/993) help?

**Comment by guillaumebriday** [comment]
Can this issue be closed ?

**Comment by joker-777** [comment]
From our side yes. We eventually switched to plain Javascript.

**Comment by guillaumebriday** [comment]
Feel free to close it then 👍
