### ISSUE TITLE
How to minify files on development env? 

### ISSUE THREAD

**Issue by masudhossain** [rails/webpacker#2313]
I wanna minify my JS files on development and not just production, so how can i do this? 

config/webpack/development.js 
`const environment = require('./environment')`
`module.exports = environment.toWebpackConfig()`

**Comment by jakeNiemiec** [comment]
What is the purpose of this?

**Comment by masudhossain** [comment]
@jakeNiemiec we're getting an error in production with minified js files and want to reproduce it in dev env.

**Comment by jakeNiemiec** [comment]
Option A: You should be able to use chrome browser to unminify the code using the sourcemaps (assuming you are using stock-webpacker).

Option B: You can try `NODE_ENV=production ./bin/webpack` or `NODE_ENV=production ./bin/webpack-dev-server`. 

Option C: You can also add the minifier directly into `environment` if you really need minified dev code.

I don't think what you have above would be valid, I think it needs to be `module.exports = environment` at the end of the file. 

Hope this helps.
