### ISSUE TITLE
Keep old assets for some period of time

### ISSUE THREAD

**Issue by irbis999** [rails/webpacker#2319]
Hello! I have a SPA (VueJS) that first in loaded as a standard page like this
```
html
  head
   = javascript_pack_tag 'app'
   = stylesheet_pack_tag 'app'
  body
    #app
```
And then VueJS controls routing via vue-router. 
During deploy i found a problem:
- user is online, doing something on a page
- at this time deploy finishes 
- user clicks on a router-link - wants to go to the next page
- browser asks server to load asset for this page (something like /packs/js/1-dfkdlfd.js)
- file was deleted during deploy, browser gets 404 error
- user can't navigate to the next page - he gets an error

I think that i need to keep webpacker assets for some period of time instead of completely deleting old assets during deploy. How can i do this?
And maybe there is some other solution for this problem.

**Comment by guillaumebriday** [comment]
Webpacker does not delete old assets automatically.

You need to run the `webpacker:clean`.

Maybe you should check in your deploy script if you don't run this command by yourself?
