### ISSUE TITLE
 Webpacker::Manifest::MissingEntryError exception message is not actionable

### ISSUE THREAD

**Issue by p-mongo** [rails/webpacker#2321]
I used `rails g` to create a new application, and running the server produced the webpacker exception. The message of the exception is not actionable in that it does not say how to address the problems it is mentioning.

The exception is as follows:

<pre>

Webpacker::Manifest::MissingEntryError in Posts#index

Showing /home/sandbox/1/blog/app/views/layouts/application.html.erb where line #9 raised:

Webpacker can't find application in /home/sandbox/1/blog/public/packs/manifest.json. Possible causes:
1. You want to set webpacker.yml value of compile to true for your environment
   unless you are using the `webpack -w` or the webpack-dev-server.
2. webpack has not yet re-run to reflect updates.
3. You have misconfigured Webpacker's config/webpacker.yml file.
4. Your webpack configuration is not creating a manifest.
Your manifest contains:
{
}
</pre>

Looking at these one by one:

1. My webpacker.yml already contains compile:true in all environments (as per generated default, apparently). Webpacker should only mention this as a possible cause if compile is not already set to true.
2. How do I make webpack rerun to detect updates?
3. How would I have misconfigured webpacker? What is the misconfiguration? What is the next step I need to take to troubleshoot?
4. How do I get webpack configuration to create the manifest?

This error is particularly perplexing because I haven't done anything with rails or webpacker or webpack yet (literally I ran `rails g` followed by `rails g scaffold`)>

**Comment by rossta** [comment]
@p-mongo Did `bundle exec rails webpacker:install` succeed? Anything in `app/javascript/packs`? Does `rails webpacker:compile` succeed?

**Comment by p-mongo** [comment]
I deleted the entire application and recreated it, hence I am not able to answer these questions.

The point of the issue is not any specific problem with the particular application but lack of actionable guidance to the user receiving the stated exception as to how to proceed with fixing it.

**Comment by jakeNiemiec** [comment]
I just tried this locally. Everything seems to work as intended. Even if I delete `manifest.json`, it is automatically regenerated without error.

> I am not able to answer these questions.

Without repro, we cannot confirm the specifics of how you got to that invalid state. If you would like to purpose a change to the content of that error message, feel free to open a PR.
