### ISSUE TITLE
Webpacker::Compiler.watched_paths doesn't take a directory

### ISSUE THREAD

**Issue by zarqman** [rails/webpacker#2328]
Hi. It appears that `Webpacker::Compiler.watched_paths` automatically silently filters out directories, only keeping files or globs. Filtering out directories (at compiler.rb:54) makes sense, but the code & readme examples are `Webpacker::Compiler.watched_paths << 'bower_components'` which I believe to be a directory.

It seems that perhaps the examples should be changed to demonstrate both a file and a glob. Before submitting a PR, I wanted to check if this is correct? Another alternative I considered is perhaps turning any directories into globs automatically, but I don't know if that's too reaching of a change. What would you like the behavior/docs to be?

Gem: Webpacker 4.0.7

**Comment by guillaumebriday** [comment]
Webpacker::Compiler.watched_paths has been deprecated. Please see https://github.com/rails/webpacker#additional-paths
