### ISSUE TITLE
Can I structure my files in the following way?

### ISSUE THREAD

**Issue by ankitrg** [rails/webpacker#233]
I very much like the Rails structure of having a folder with the controller name and then the views based on the action names.

I want to rename the `packs` to `views` which I can do, but I am not sure if this will be possible:

```
packs/posts/new.js
packs/posts/index.js
packs/blog/new.js
```

is doing something like this possible? Do you suggest some convention?

----
Edit

I think we can achieve this if this if the pack files generated are placed under their respective folders. Then we could do somthing like
```<%= javascript_pack_tag 'posts/new' %>```

**Comment by ytbryan** [comment]
> Can I structure my files in the following way?

Yes. This is possible after https://github.com/rails/webpacker/pull/201

**Comment by gauravtiwari** [comment]
@ankitrg Please close the issue, this feature is on master. You have to re-run `bundle exec rails webpacker:install` to replace to your current shared.js
