### ISSUE TITLE
WebPackerClean#clean does not remove files that are not in manifest

### ISSUE THREAD

**Issue by spaghetticode** [rails/webpacker#2338]
https://github.com/rails/webpacker/blob/23d5fdd66b0184ac08fb0fce855c813b4a3ee36d/lib/webpacker/commands.rb#L8

I think there's a minor issue with this method. 

The code tracks files that should be removed by using the assets manifest, and removes old versions of still-existing assets. But if a source file was removed and it is not referenced anymore in the assets manifest, its compiled files will be never deleted. Same goes for arbitrary files that may end up in the folder. 

Changing specularly the way that the code works, ie keep only files that are listed in the manifest and their more recent versions won't be optimal either,  as this would also remove compiled files whose sources have been recently removed and were supposed to be kept.

**Comment by spaghetticode** [comment]
@justin808 I've seen this is closed now, can you confirm this is not an issue anymore?

**Comment by justin808** [comment]
@spaghetticode Definitely, I have not confirmed. However, the code changed significantly since you last posted this issue.

Can you take a look and confirm?
