### ISSUE TITLE
confusion on how to handle webpack upgrade on CommonsChunkPlugin changes

### ISSUE THREAD

**Issue by kimyu92** [rails/webpacker#2344]
Based on reading https://github.com/rails/webpacker/blob/master/docs/webpack.md#add-common-chunks-deprecated-in-webpack-v4 and https://github.com/rails/webpacker/blob/master/docs/v4-upgrade.md#splitchunks-configuration, I would like to get some clarification on how to migrate to webpack 4:

1. How to handle conditional `javascript_packs_with_chunks_tag` in the template layout which is not recommended from the guide?
2. Does using `javascript_packs_with_chunks_tag` means it automatically bring in all vendors which is equivalent to previous behavior of having `CommonsChunkVendor`?
3. Do I still need to include manifest in `javascript_packs_with_chunks_tag`? Why is it needed previously or why is it not needed now?

`config/webpack/environment.js`
```js
// old
const webpack = require('webpack')

environment.plugins.append(
  'CommonsChunkVendor',
  new webpack.optimize.CommonsChunkPlugin({
    name: 'vendor',
    minChunks: (module) => {
      // this assumes your vendor imports exist in the node_modules directory
      return module.context && module.context.indexOf('node_modules') !== -1
    }
  })
)

environment.plugins.append(
  'CommonsChunkManifest',
  new webpack.optimize.CommonsChunkPlugin({
    name: 'manifest',
    minChunks: Infinity
  })
)

// new
const WebpackAssetsManifest = require('webpack-assets-manifest');

// Enable the default config
environment.splitChunks()

// or using custom config
environment.splitChunks((config) => Object.assign({}, config, { optimization: { splitChunks: false }}))
```

`layouts/application.html.erb`
```
// old
<%# Head %>

<%= javascript_pack_tag "manifest" %>
<%= javascript_pack_tag "vendor" %>

<%# If importing any styles from node_modules in your JS app %>

<%= stylesheet_pack_tag "vendor" %>

// new
<%# DO %>
<%= javascript_packs_with_chunks_tag 'calendar', 'map' %>

<%# DON'T %>
<%= javascript_packs_with_chunks_tag 'calendar' %>
<%= javascript_packs_with_chunks_tag 'map' %>
```

**Comment by rossta** [comment]
@kimyu92 Using `environment.splitChunks()` in your webpacker js config will get you something reasonable close to what you had before. Here's the bit that gets added to your final Webpack config:
https://github.com/rails/webpacker/blob/23d5fdd66b0184ac08fb0fce855c813b4a3ee36d/package/environments/base.js#L124-L134

It's a bit opaque, but what this basically says is, "extract the manifest into its own initial chunk" and "split out vendor and common modules into another initial chunk(s)".

The `javascript_packs_with_chunks_tag` allows you to not have to think about what manifest (be default now called the `runtime`), vendor,  and common chunks to explicitly reference in your view. 

So you can simply add `<%= javascript_packs_with_chunks_tag 'application' %>` to a simple app with one `application` pack and the `splitChunks` config and it will output all the required chunks, e.g.:

```html
<script src="/packs/js/runtime~application-2a426143d8d4ad5ac92e.js"></script> <!-- the manifest chunk -->
<script src="/packs/js/0-7655049a0ebf702f44f8.chunk.js"></script> <!-- the vendor/common chunk -->
<script src="/packs/js/application-02743b7c93e2cb7c7960.chunk.js"></script> <!-- your app code chunk -->
```
Hope that helps!

**Comment by kimyu92** [comment]
@rossta So based on what you said, there is no need to add `javascript_packs_with_chunks_tag "manifest"` and `javascript_packs_with_chunks_tag "vendors"`. How about multiple pack files scenario? Also, any insight on conditional pack file scenario below as well?

```erb
<% if [true, false].sample %>
  <%= javascript_packs_with_chunks_tag 'random' %>
<% end %>

<%= javascript_packs_with_chunks_tag 'app' %>
```

**Comment by rossta** [comment]
@kimyu92 

> there is no need to add javascript_packs_with_chunks_tag "manifest" and javascript_packs_with_chunks_tag "vendors"

Correct

> How about multiple pack files scenario?

There should only be one use of `javascript_packs_with_chunks_tag` during page render so pass both pack names in one call just like the example: `<%= javascript_packs_with_chunks_tag 'calendar', 'map' %>`.

> Also, any insight on conditional pack file scenario below as well?

Use a helper method: `<%= javascript_packs_with_chunks_tag *determine_what_packs_to_include %>

```ruby
def determine_what_packs_to_use
  packs = ['app']
  # additional logic to add to array
  packs
end
```

**Comment by kimyu92** [comment]
I have to tweak optimization config for `environment.splitChunks()` for my current environment setup, just want to leave it here in case it could be useful for someone who comes across issues in replacing existing `CommonsChunkVendor`

```js
  optimization: {
    runtimeChunk: {
      name: 'manifest',
    },
    splitChunks: {
      chunks: 'all',
      cacheGroups: {
        vendors: false,
      },
    },
  },
```

**Comment by rossta** [comment]
Great. Sounds like this issue can be closed then?

**Comment by kimyu92** [comment]
@rossta sounds good to me
