### ISSUE TITLE
WebPackerClean#clean does not remove `.gz` versions of stale manifest files

### ISSUE THREAD

**Issue by spaghetticode** [rails/webpacker#2347]
Currently the `webpacker:clean` task only remove uncompressed files. 

Given that Webpacker may generate also compressed `.gz` versions of these files (and this is actually the default for production env AFAIK) then also stale `.gz` files should be removed.

**Comment by justin808** [comment]
https://github.com/rails/webpacker/blob/master/lib/webpacker/commands.rb doesn't show this as an issue.

**Comment by benlangfeld** [comment]
Indeed 4.3.0 has the opposite problem, it deletes compressed versions of assets that are in the manifest and shouldn't be removed.

**Comment by benlangfeld** [comment]
The following in an initializer is tiding us over until we can come up with a long-term alternative:

```ruby
# frozen_string_literal: true

# Prevent webpacker from cleaning away compressed variants of current assets
class Webpacker::Commands
  private
    def current_version
      manifest.refresh.values.map do |value|
        next if value.is_a?(Hash)

        filename = File.join(config.root_path, "public", value)
        [filename, "#{filename}.gz", "#{filename}.br"]
      end.flatten.compact
    end
end
```
