### ISSUE TITLE
Stuck on "Compiling..." in produciton on Heroku

### ISSUE THREAD

**Issue by JWesorick** [rails/webpacker#2350]
I don't have a lot of info here but hope to get some visibility to the issue. We are attempting to upgrade to rails `5.2.3`. The only change is upgrading the rails version and adding the bootstap gem. We are on webpacker `4.0.7`.

![Screen Shot 2019-11-04 at 5 09 11 PM](https://user-images.githubusercontent.com/801062/68162380-e4434f00-ff25-11e9-9ed8-342575ad9eed.png)

Everything works fine locally. But when we push to heroku it times out on "Compiling...".

Locally `bundle exec rails webpacker:compile` works. And I can run `NODE_ENV=production bin/webpack` in a Heroku CI node without it hanging but on the same node `bundle exec rails webpacker:compile` gets hung up and never finishes.

**Comment by rossta** [comment]
Just to clarify, for local test, did you use `NODE_ENV=production bundle exec rails webpacker:compile`?

**Comment by cmitz** [comment]
I'm getting it locally too, since yesterday. I suspect a dependency not building correctly (private package that was updated), but Webpacker is not providing any logs or feedback.

**Comment by JWesorick** [comment]
@rossta The readme says that the rake tasks compile in production by default. 

Running it like you suggested seems to surface another issue where it says `Integrity check failed` for yarn packages despite `yarn install` saying everything is up to date. Setting `  check_yarn_integrity` to false in `webpacker.yml` also does not seem to remove the integrity check failure when running the rake task that way.

**Comment by JWesorick** [comment]
@cmitz I can run `NODE_ENV=production bin/webpack` both locally and on heroku just fine so I think your issue might be a different one.

**Comment by cmitz** [comment]
Okay. I made a new issue anyway (#2352) 😄

**Comment by JWesorick** [comment]
Ok fixed with `yarn upgrade webpack @rails/webpacker` which bumped webpacks version in `yarn.lock` from `4.35.0` to `4.41.2`.

**Comment by rossta** [comment]
@JWesorick 
> The readme says that the rake tasks compile in production by default.
Yes, thanks for the clarification, I see that was a recent change now.

Glad you were able to fix the issue.
