### ISSUE TITLE
Webpacker hangs without output when dependency fails to build

### ISSUE THREAD

**Issue by cmitz** [rails/webpacker#2352]
This is a hard issue to debug, but it comes down to this:

1) I have a private NPM package that fails to build - a faulty `url(...)` import in scss.
2) More importantly, I do `RAILS_ENV=production NODE_ENV=production ./bin/webpack`
3) An error occurs: `ModuleNotFoundError: Module not found: Error: Can't resolve './assets/Roboto-Medium.ttf'` (with stacktrace)
4) The process hangs indefinitely without output; a ctrl-c interrupt is required

However, the ModuleNotFoundError and stacktrace **do not** occur when invoking `RAILS_ENV=production rails assets:precompile` or `RAILS_ENV=production rails webpack:compile`.

The easy fix is repairing the npm package. However, it took a while before we figured out what was happening, since `Compiling...` always takes a minute anyway. Now it just takes forever. Some more information by webpacker would have helped.

It seems since the process doesn't succeed or fail, this line is never reached: https://github.com/rails/webpacker/blob/23d5fdd66b0184ac08fb0fce855c813b4a3ee36d/lib/webpacker/compiler.rb#L80

I'm not sure how to proceed though

**Comment by jakeNiemiec** [comment]
Might be related to: https://github.com/rails/webpacker/issues/2312

**Comment by rossta** [comment]
@cmitz Webpacker will not print to STDOUT by default during compilation as of https://github.com/rails/webpacker/pull/2224.

Would you like to revisit this issue with more info or could you otherwise close? Thank you!

**Comment by cmitz** [comment]
@rossta After some thought, let me boil it down to this:
- If `bin/webpack` hangs, all we'll see in `webpack:compile` is `Compiling...`

This is more of an area of improvement than a bug, although it's definitely time-consuming for everyone encountering this.
