### ISSUE TITLE
pack subdirectories ??

### ISSUE THREAD

**Issue by andyl** [rails/webpacker#236]
I'm using Rails 5.1RC1 and would like to organize my entry points into subdirectories under the pack directory, and call them like `<%= javascript_pack_tag 'subdir/entry' %>`.  

Have had no success working with pack subdirectories.  Get an error message saying "Can't find subdir/entry.js in manifest.json".  

Is there anything I can do to make this work??

**Comment by gauravtiwari** [comment]
@andyl Did you re-run `bundle exec rails webpacker:install`? Please ensure to sync your version of gem with master, this got merged yesterday.

**Comment by gauravtiwari** [comment]
Please close the issue if the above works for you 😄

**Comment by andyl** [comment]
Thanks so much for your fast reply!!  Installed the latest webpacker from github, then re-ran `webpacker:install` and got this message...

    > bundle exec rails webpacker:install
    Webpacker requires Node.js >= 6.4 and you are using v6.10.1
    Please upgrade Node.js https://nodejs.org/en/download/

Are we shaving yaks yet?  Let me know if you'd like me to file a separate bug, or if there is something else going on here...

**Comment by gauravtiwari** [comment]
@andyl No problem. As suggested in the comment, please upgrade your node version. Webpacker works with node.js > 6.4

**Comment by gauravtiwari** [comment]
It might work with 6.10, but that's default since 6.4 has 95% compatibility with es6 spec.

**Comment by andyl** [comment]
Oh!  Is 6.10.1 not >= 6.4??  Should I downgrade to 6.4??  (i'm running on Ubuntu 16.04 fyi...)

**Comment by aganov** [comment]
@andyl `v6.10.2` is the latest stable, there is a bug in `webpack:check_node` task which calculatuing 6.10.1 (calculated 6.1) < 6.4, this will be fixed after the merge of #232

**Comment by gauravtiwari** [comment]
Whoops! My bad, this is a bug, which will be fixed in https://github.com/rails/webpacker/pull/232

**Comment by gauravtiwari** [comment]
Just upgrade to 7.0 or something for now

**Comment by ytbryan** [comment]
Alternatively, @andyl use the fix now. 

`gem 'webpacker', github: "aganov/webpacker",  branch: "fix/webpacker-check-node"`

**Comment by andyl** [comment]
I installed the aganov version - it fixed the versioning issue, but I don't notice a fix for the subdirectory issue.

Unless I hear otherwise - I'll wait a few days for things to converge, then test again...

**Comment by aganov** [comment]
@andyl My PR was merged a few hours ago, so you can revert to `gem "webpacker", git: "rails/webpacker"`

**Comment by andyl** [comment]
Can confirm - the most recent `rails/webpacker` solves both the node-versioning issue and the subdirectory issue.

Many thanks.
