### ISSUE TITLE
Environment variables change do not trigger recompilation?

### ISSUE THREAD

**Issue by trafium** [rails/webpacker#2361]
I am providing custom env variable to compiler:
```js
environment.plugins.prepend('Environment', new webpack.EnvironmentPlugin([ 'MY_CUSTOM_VAR' ]));
```
And in my application code I use it:
```js
console.log( process.env.MY_CUSTOM_VAR );
```
Then I start rails server for the first time like this `MY_CUSTOM_VAR=foo rails s` and app correctly outputs `foo` in browser console. But if i restart server with different value for `MY_CUSTOM_VAR`, it does not detect any changes, saying `Everything's up-to-date. Nothing to do`, and still outputs `foo` in browser console. 

Is there any way to configure webpacker/webpack to watch code dependent on `process.env` variables?

**Comment by rossta** [comment]
The compiler is capable of watching files. You could try using a project like `dotenv` or `direnv` in development to read ENV vars from a file, e.g. like `.envrc` if using [direnv](https://direnv.net/), and add that file to `Webpacker::Compiler.watched_paths`.

https://github.com/rails/webpacker/tree/5da39a18e0bd1fa7041575aaba1d710f31ccfb17#watched

**Comment by trafium** [comment]
Sure, that would work, I just thought maybe webpacker/webpacker could automagically track dependent environment variables change, but seems like it does not.

Thanks!
