### ISSUE TITLE
Vue.js code not compiling in Capybara tests

### ISSUE THREAD

**Issue by DaniG2k** [rails/webpacker#2363]
I am trying to run some integration tests using RSpec & Capybara with Headless Chrome.

However, it seems the Vue.js code on the page doesn't get compiled, so the integration test fails to run properly.

I am using the following gems:

```
group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'pry'
  gem 'rspec-rails', '~> 3.8'
  gem 'factory_bot_rails'
  gem 'faker', git: 'https://github.com/stympy/faker.git', branch: 'master'
  gem 'database_cleaner'
  gem 'selenium-webdriver'
end

group :test do
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '>= 2.15'
  gem 'capybara-selenium'
  gem 'webdrivers'
end
```

My `rails_helper.rb` includes the lines:

```
require 'rspec/rails'
require 'capybara/rails'
require 'capybara/rspec'
require 'selenium/webdriver'

# ...

Capybara.register_driver :chrome do |app|
  Capybara::Selenium::Driver.new(app, browser: :chrome)
end

Capybara.register_driver :headless_chrome do |app|
  capabilities = Selenium::WebDriver::Remote::Capabilities.chrome(
    chromeOptions: { args: %w[headless disable-gpu] }
  )

  Capybara::Selenium::Driver.new app,
    browser: :chrome,
    desired_capabilities: capabilities
end

Capybara.default_driver = :chrome
Capybara.javascript_driver = :chrome
```

The output of webpacker info:

```
bundle exec rails webpacker:info                                  
Ruby: ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin19]
Rails: 6.0.1
Webpacker: 4.0.7
Node: v8.9.2
Yarn: 1.19.1

@rails/webpacker: 
myapp@ /Users/me/Documents/apps/myapp
└── @rails/webpacker@4.0.7 

Is bin/webpack present?: true
Is bin/webpack-dev-server present?: true
Is bin/yarn present?: true
```

But when I run the integration, instead of the Vue.js code executing as expected I am seeing it being output as text to the page, as such:

![tX8nC](https://user-images.githubusercontent.com/1641910/68656611-7228c680-0532-11ea-904f-966f1d579eb9.png)

I've also tried running

```
RAILS_ENV=test rails assets:precompile
```

before running the spec but that didn't seem to work either.

Any idea what I'm doing incorrectly? Thanks in advance

**Comment by connorshea** [comment]
Do you have a Content Security Policy set up? I had a similar problem at one point: https://github.com/rails/webpacker/issues/1900

**Comment by DaniG2k** [comment]
Thanks @connorshea , I just tried with the following config:

```ruby
Rails.application.config.content_security_policy do |policy|
  if Rails.env.development?
    policy.script_src :self, :https, :unsafe_eval
  else
    policy.script_src :self, :https, :unsafe_eval, :unsafe_inline
  end
end
```

But I am still not seeing the JS being evaluated properly.
Do you know if there's a way to check whether webpacker is compiling properly in test? I'd be curious to see if there are test compilation errors.

Thanks again

**Comment by connorshea** [comment]
The easiest way would be to use capybara’s save_and_open_page (the method is something like that) and see if vue has managed to inject anything into the page.

In my rails app I have this for printing JS errors to the terminal, it might be useful?: https://github.com/connorshea/VideoGameList/blob/56fd1749665cc6d90258bc804c7e27559faf60d7/spec/rails_helper.rb#L83

**Comment by DaniG2k** [comment]
I'm actually not running the tests with `:headless_chrome`, I'm running them with the `:chrome` driver. So I am already able to see the browser navigate to the page, and I see the form. The items that are being improperly rendered/populated are the ones that depend on Vue.js code.

For the record, the test is very simple. It looks like this:

```ruby
RSpec.feature 'Users can create invocies' do
  let(:user) { create(:user) }
  let(:address) { create(:address, user: user) }

  let(:client) { create(:client, user: user) }
  let!(:client_address) { create(:address, user: user, client: client) }

  before do
    login_as user
    visit new_invoice_path
  end

  context 'successfully' do
    it 'displays a success message on creation' do
      fill_in 'Invoice No.', with: rand(1..100)
      select address.full_address, from: 'invoice_personal_address'
      select client_address.full_address, from: 'invoice_client_address'

      fill_in 'Service name', with: 'Amazing web development'
      fill_in 'Service description', with: 'Web development for real pros.'

      fill_in 'Quantity', with: rand(1..10)
      fill_in 'Rate', with: rand(30.0..80.0)

      fill_in 'Date issued', with: Date.today
      fill_in 'Date due', with: 1.month.from_now

      click_button 'Create Invoice'

      expect(page).to have_content 'Invoice was successfully created.'
    end
  end
end
```

**Comment by justin808** [comment]
Vue is no longer supported within rails/webpacker.
