### ISSUE TITLE
Yarn install runs twice after upgrading to 4.2.0

### ISSUE THREAD

**Issue by b-nik** [rails/webpacker#2369]
Running  bundle exec rake assets:precompile now runs yarn install twice: (This didn't happen with 4.0.7)

```
yarn install v1.19.1
[1/4] Resolving packages...
success Already up-to-date.
Done in 1.66s.
yarn install v1.19.1
[1/4] Resolving packages...
success Already up-to-date.
Done in 2.00s.
Everything's up-to-date. Nothing to do
```

Also now when deploying (capistrano) yarn install always fetches packages (it never says "already up-to-date" anymore). This wasn't the case with 4.0.7 (node_modules and public/packs are in the linked_dirs option)

Rails 6.0.1 
Webpacker 4.2.0

**Comment by ytbryan** [comment]
yup it ran twice on my machine too

**Comment by mech** [comment]
There may also be file-loader issues where production deploy will failed to find file-loader.

**Comment by akaspick** [comment]
Rails 6 already enhances `assets:precompile` with `yarn:install`

https://github.com/rails/rails/blob/34d66ca6bab109540299a7b30980627bea37e323/railties/lib/rails/tasks/yarn.rake#L17

So webpacker should likely not be enhancing `assets:precompile` for Rails > 6

https://github.com/rails/webpacker/blob/417542c8ed7d344ecc24b3ae40e303d478ad50d0/lib/tasks/webpacker/compile.rake#L20

**Comment by alaarab** [comment]
Running twice in my app as well

**Comment by wilpar** [comment]
<aol>
me too
</aol>

**Comment by jasoares** [comment]
Yap, can confirm on webpacker 4.2.2. A fix for this would be nice

**Comment by VSPPedro** [comment]
Running twice in my app as well (2)

**Comment by kimyu92** [comment]
@gauravtiwari any idea?

**Comment by sinsoku** [comment]
This issue occurs with the following code:

https://github.com/rails/webpacker/blob/96af013eed295576ac246f46dee1d01d67888801/lib/tasks/webpacker/yarn_install.rake#L16-L21

This code is executed before defining the `yarn:install` in railties, and the condition always returns false.

If you want to fix the problem immediately, you can fix it by removing `webpacker:yarn_install` in the `Rakefile`.

```ruby
require_relative 'config/application'

Rails.application.load_tasks

# Remove `webpacker:yarn_install` task
#
# ref: https://github.com/rails/webpacker/issues/2369
Rake::Task['yarn:install'].tap do |t|
  raise 'Consider removing this patch' unless t.prerequisites.include?('webpacker:yarn_install')

  prerequisites = t.prerequisites - ['webpacker:yarn_install']
  t.clear_prerequisites
  t.enhance(prerequisites) unless prerequisites.empty?
end
```

**Comment by gauravtiwari** [comment]
This is now fixed 👍

**Comment by cooperka** [comment]
Thanks for the fix @gauravtiwari, look like the fix made it to master but there hasn't been a release in almost 2 months, do you know if this is likely to be available soon? Cheers!
