### ISSUE TITLE
same filename of stylesheet_pack_tag and javascript_pack_tag

### ISSUE THREAD

**Issue by AlexAslam** [rails/webpacker#2383]
I'm having an issue with these two tags javascript_pack_tag and stylesheet_pack_tag, when i try to add them both but only styles are working whether i have stylesheet_pack_tag or not, javascript_pack_tag works for stylesheet not for javascript its a weird issue.

**Comment by rossta** [comment]
Please be as specific as possible when describing your problem. 

What is in your `app/javascript/packs` directory? What's in your config/webpacker.yml? What version of the webpacker gem and the `@rails/webpacker` npm package are you using, What  html snippets you're using for the pack tags? etc.
