### ISSUE TITLE
I can't seem to use javascript_pack_tag without fingerprinting.

### ISSUE THREAD

**Issue by ytbryan** [rails/webpacker#24]
Please let me know if you are getting the same issue. Thank you. 

<%= javascript_pack_tag 'hello_vue-ceb9bfb89eb3dbc910d5' %> #works
<%= javascript_pack_tag 'hello_vue' %> #/packs/hello_vue.js not found

**Comment by guilleiguaran** [comment]
Do you have `config.x.webpacker[:digesting] = true` in your `production.rb`?

**Comment by ytbryan** [comment]
Yes. And I am using the rails 5.1.alpha from the master branch if this info helps.

**Comment by dhh** [comment]
Did you compile your production packs before booting the server? You can
compile using `rails webpacker:compile`. That'll generate both the
fingerprinted packs but also the /packs/digests.json file needed to
correctly lookup the file names. I just confirmed that this works using
rails/master and latest webpacker.
