### ISSUE TITLE
Webpacker @ 4.2.2 - CSS Modules empty object issue

### ISSUE THREAD

**Issue by jayjamero** [rails/webpacker#2404]
Hi,

Having some issues with importing `scss files` (css modules) into webpacker. I have a basic react component doing something like

```
import React from 'react';
import PropTypes from 'prop-types';
import styles from './styles.scss';

export default class HelloWorld extends React.Component {
  render() {
    console.log("styless ", styles);
    return <h1>Noish</h1>
  }
}
```

Looking at this bit of code results in 

```
const getStyleRule = (test, modules = false, preprocessors = []) => {
  const use = [
    {
      loader: 'css-loader',
      options: {
        sourceMap: true,
        importLoaders: 2,
        modules: modules ? {
          localIdentName: '[name]__[local]___[hash:base64:5]'
        } : false
      }
    },
```

an empty style object:
<img width="308" alt="Screen Shot 2019-12-19 at 7 58 27 am" src="https://user-images.githubusercontent.com/837252/71124247-8c904700-2238-11ea-9a7e-a553ddb426a2.png">

However changing it to 

```
const getStyleRule = (test, modules = false, preprocessors = []) => {
  const use = [
    {
      loader: 'css-loader',
      options: {
        sourceMap: true,
        importLoaders: 2,
        modules
      }
    },
```

Finally gives me the style object i want 

<img width="363" alt="Screen Shot 2019-12-19 at 12 18 24 am" src="https://user-images.githubusercontent.com/837252/71124295-a7fb5200-2238-11ea-802f-842c39272436.png">

I still need all that magic from `localIdentName`. So had a look at this issue before: https://github.com/rails/webpacker/issues/2197 so my first thing was to bump it to get the updated dependency version of css-loader.

Not sure whats going on here

**Comment by jayjamero** [comment]
Looking into this line as the culprit

```
        modules: modules ? {
          localIdentName: '[name]__[local]___[hash:base64:5]'
        } : false
```

changing it to 

```
        modules: {
          localIdentName: '[name]__[local]___[hash:base64:5]'
        }
```

Also fixes it but we lose the conditional `false` flag - which actually shouldn't matter as its false by default

**Comment by jayjamero** [comment]
Looking into this line as the culprit

```
        modules: modules ? {
          localIdentName: '[name]__[local]___[hash:base64:5]'
        } : false
```

changing it to 

```
        modules: {
          localIdentName: '[name]__[local]___[hash:base64:5]'
        }
```

Also fixes it but we lose the conditional `false` flag - which actually shouldn't matter as its false by default, working on this little refactor now

**Comment by jayjamero** [comment]
Scratching my head, this works, its almost as if problem is that there are two rules added for scss files, and the later is not taking precedence.

Would there be an issue enabling this for all?

```
   modules: { localIdentName: '[name]__[local]___[hash:base64:5]' }
```

**Comment by jayjamero** [comment]
Scratching my head, this works, its almost as if the problem is that there are two rules added for scss files, and the later is not taking precedence.

Would there be an issue enabling this for all?

```
   modules: { localIdentName: '[name]__[local]___[hash:base64:5]' }
```

**Comment by gauravtiwari** [comment]
To enable css modules, you need to name file as `style.module.scss`

**Comment by jayjamero** [comment]
Cheers that did it!
