### ISSUE TITLE
Webpack version

### ISSUE THREAD

**Issue by dijonkitchen** [rails/webpacker#241]
Does the webpacker gem use Webpack V1 or V2? I couldn't find any documentation here on which was used. 

I'd presume V2 would be favored; it seems V1 is deprecated and there's a migration strategy for V2.

References: 
https://medium.com/webpack/webpack-2-and-beyond-40520af9067f
https://webpack.js.org/guides/migrating/

**Comment by ytbryan** [comment]
2. https://github.com/rails/webpacker/search?q=webpack+2&type=Commits&utf8=✓

**Comment by dijonkitchen** [comment]
Agreed, and the links need to point to the newer V2 documentation.

**Comment by gauravtiwari** [comment]
Feel free to make a PR for this 😄
