### ISSUE TITLE
Test packs not recompiled in engine dummy app

### ISSUE THREAD

**Issue by tf** [rails/webpacker#2410]
I'm developing a Rails engine which relies on Webpacker being installed in the root application. For tests, I thus install Webpacker in the dummy application. This works fine.

When running tests from the root of the engine project, though, files are not recompiled when the packs in the dummy app change. [`Webpacker::Compiler` resolves its `watch_paths`](https://github.com/lsylvester/webpacker/blob/48946cc335a8a6eb1e1c3386a620e5355c44c278/lib/webpacker/compiler.rb#L47) relative to the present working directory. So it only watches `my_engine/app/javascript` not `my_engine/spec/dummy/app/javascript`. This might be what you want if you run Webpacker isolated inside the engine (as described in the [engine guide](https://github.com/rails/webpacker/blob/master/docs/engines.md)). I would have expected paths to be resolved relative to Webpacker's  `root_path`, though. 

PR #1667 already moved things in this direction, by using binstubs from the dummy app directory, but left watched paths unchanged.

In my case, the problem was easy to fix by manually adding absolute watch paths in a test helper:
```
# spec/support/webpacker.rb
Webpacker::Compiler.watched_paths << Rails.root.join('app/javascript/**/*.js')
```
It does feel a bit inconsequential, though. Maybe this can at least be documented somewhere? Or maybe it is and I didn't see it? The engine guide seems like the wrong place, though, since it only talks about the "Webpacker in an engine" case, while this is more about "engines for root applications that use Webpacker".

**Comment by justin808** [comment]
@tf can you please submit a doc PR if you feel this applies to v6.
