### ISSUE TITLE
How do you use webpacker without `webpack-dev-server`?

### ISSUE THREAD

**Issue by mikeyhew** [rails/webpacker#242]
The README seem to suggest that running `bin/webpack-dev-server` is optional. However, when I'm not running it, my script tags (created with `javascript_pack_tag`) still point to `localhost:8080`.

Is there a way to have rails serve the javascript files instead, and have the `javascript_pack_tag` point to the main rails server?

**Comment by gauravtiwari** [comment]
Hey @mikeyhew you can run `./bin/webpack-watcher` instead. Also, please turn off the dev server from `config/webpack/development.server.yml` (You will be getting a message when you run a watcher to disable dev server)

![screen shot 2017-04-07 at 07 27 13](https://cloud.githubusercontent.com/assets/771039/24788113/a7b1588c-1b63-11e7-9d0f-c0aae48d4339.png)

**Comment by mikeyhew** [comment]
@gauravtiwari thanks, I just needed to turn it off in the config file. The Readme should be more clear that you have to do that, because I didn't notice that warning in the terminal output when I ran `bin/webpack-watcher`.

**Comment by gauravtiwari** [comment]
@mikeyhew It's in the readme, just a little further down in advanced configuration section - https://github.com/rails/webpacker#advanced-configuration

**Comment by dhh** [comment]
I like the clarification @mikeyhew. Submit a PR?

**Comment by mikeyhew** [comment]
@dhh oops, I thought I submitted one already. I'll do that right now.

**Comment by mikeyhew** [comment]
PR: #252

**Comment by gauravtiwari** [comment]
Merged :)
