### ISSUE TITLE
error @rails/webpacker@4.2.2: The engine "node" is incompatible with this module. Expected version ">=8.16.0". Got "8.10.0"

### ISSUE THREAD

**Issue by mayordwells** [rails/webpacker#2424]
Why do we randomly get this during deployment?
Sometimes it appears, sometimes it doesn't.

And every time it appears, it breaks the deployment flow by returning a non zero error. How can we make this go away?

yarn install v1.21.1
[1/4] Resolving packages...
[2/4] Fetching packages...
warning sha.js@2.4.11: Invalid bin entry for "sha.js" (in "sha.js").
error @rails/webpacker@4.2.2: The engine "node" is incompatible with this module. Expected version ">=8.16.0". Got "8.10.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by rossta** [comment]
In `@rails/webpacker@4.2.2` the required minimum node version is specified in `package.json` as `">= 8.16.0"`: https://github.com/rails/webpacker/blob/c7292e9a1e158e5fc9ec3026256cf7a42d70f549/package.json#L11

I'm assuming from your error message that your deployment target environment loads node 8.10.0. This does not meet the constraint. Try installing 8.16.0 or higher. I'd actually recommend shooting for an active or current LTS version if possible: https://nodejs.org/en/about/releases/

**Comment by mayordwells** [comment]
Hi, @rossta thanks for your response. 
I use docker and my deployment target environment uses node 13.x.x -
`RUN curl -sL https://deb.nodesource.com/setup_13.x | bash`

That's why I'm confused by this error.

**Comment by rossta** [comment]
@mayordwells Try some debugging to challenge the assumption that your expected node version successfully installs and gets loaded in the shell. The behavior of your yarn install command suggests that it is not.

**Comment by mayordwells** [comment]
Okay, @rossta I'll dig deeper and update the issue if anything. 
I'll close the issue for now since it seems the issue is from my side. 
Thanks

**Comment by rossta** [comment]
@mayordwells Ok, great. Please share if you learn anything new.

**Comment by zakariaf** [comment]
@mayordwells I have exactly this problem, did you find anything?

**Comment by Meekohi** [comment]
Having the same issue, but I'm on node 10.16?
`Stderr: warning sha.js@2.4.11: Invalid bin entry for "sha.js" (in "sha.js").`

**Comment by mayordwells** [comment]
> @mayordwells I have exactly the same problem, did you find anything?

No, @zakariaf I was not able to fix it. Usually, I would reset our docker to factory settings and just rebuild the image, that has been the only possible fix for me. The error is quite random which makes it very hard to debug.

**Comment by mayordwells** [comment]
> Having the same issue, but I'm on node 10.16.0?
> `Stderr: warning sha.js@2.4.11: Invalid bin entry for "sha.js" (in "sha.js").`

@Meekohi I also run on the latest version of node - 13.x.x but I still get this error randomly. I believe this is a result of one of the dependencies of webpacker trying to override the node in our current environment.

**Comment by jakeNiemiec** [comment]
https://github.com/crypto-browserify/sha.js/pull/65

**Comment by development-amold** [comment]
Quick Fix:
Root Cause: As far as I understood, during the deployment process, it's looking the Node version in this directory `/bin/node` and it ignores the NVM node version from this directory `~/.nvm/` as well as engine version written in `package.json` file.

Solution: Need to upgrade version located in `bin` directory
`sudo npm cache clean -f`   // Clean cache
`sudo npm install -g n`    // install npm globally
`sudo n stable`   //install latest node stable version which should be >=8.16.0
