### ISSUE TITLE
Publicly accessible mainfest.json: information disclosure?

### ISSUE THREAD

**Issue by tagliala** [rails/webpacker#2430]
Hi,

I've noticed that webpacker produces publicly accessible non-fingerprinted `manifest.json` in the `/packs` folder. That is acceptable in a lot of circumstances, but when you do something like

```js
require.context('../images', true)
```

as [suggested here](https://github.com/rails/webpacker/blob/master/docs/assets.md#link-in-your-rails-views), it looks to me like allowing access to the index page of `/packs/media/images`.

What do you think about this?

**Comment by jakeNiemiec** [comment]
Yes, this is intended. As a rule, Webpacker should only handle public assets.
