### ISSUE TITLE
Turn on polling via environment variables

### ISSUE THREAD

**Issue by luisfelipemourapereira** [rails/webpacker#2435]
Environment variables such as WEBPACKER_DEV_SERVER_HOST i.e. WEBPACKER_DEV_SERVER_{OPTION} seems to work and be piped down to a .fetch() call.

```ENV["#{env_prefix}_#{key.upcase}"] || config.dev_server.fetch(key, defaults[key])```

However, I am attempting to turn on polling via environment variable which has extra scope on the hash.  it is watch_options => poll.  

I believe fetch here would not work for fetching something like watch_options => poll.  Since this code would only fetch the first level option on the hash. 

So my question is, what is the most advisable way to have an env var like ```WEBPACKER_DEV_SERVER_WATCH_OPTIONS_POLL=true``` respected as an override.

My suggestion is for multi-level hash getting we could use .dig().
https://tiagoamaro.com.br/2016/08/27/ruby-2-3-dig/
this would provide a way to break down the environment variable flattened key and then be able to enable a multi-level hash fetch.

Thoughts?

**Comment by justin808** [comment]
I don't understand what you are trying to accomplish, or maybe the why of what you're doing, that would suggest changing rails/webpacker.
