### ISSUE TITLE
Why isn't .yarn/ in .gitignore?

### ISSUE THREAD

**Issue by ratahtatah** [rails/webpacker#2446]
Why isn't the `.yarn/` folder in `.gitignore`? Am I missing something obvious?

Thanks!

**Comment by jakeNiemiec** [comment]
What version of yarn are you using? (`yarn --version`)

**Comment by ratahtatah** [comment]
Hello  @jakeNiemiec,
```
% yarn --version
2.0.0-rc.27
```

Here's the content of my `.yarn/` folder: https://gist.github.com/ratahtatah/984afa9857f40251f53821b3155b5d0c
And my `node_modules/` folder: https://gist.github.com/ratahtatah/7201c886173cf926a4bbe483942c9680

Shouldn't these be in the root of my homedir instead of in my app's folder?

**Comment by jakeNiemiec** [comment]
Yarn 2.0 will not work with webpacker yet, you will need yarn 1.x.

**Comment by ratahtatah** [comment]
@jakeNiemiec oh I see. Thanks for the info. Any idea when this support will be implemented?

**Comment by jakeNiemiec** [comment]
@ratahtatah thanks for getting back to us about it. This should produce a warning now.
