### ISSUE TITLE
Add post-install messages, redo README.md and move documentation to separate file

### ISSUE THREAD

**Issue by ghost** [rails/webpacker#2452]
All in all this experience has been terribly confusing, especially for me who is a beginner to Rails and thought everything would be ready to go after `rails new myapp`.

Instead it turned out I had to downgrade Yarn. I also struggled to install basic packages like jQuery and had to resort to outdated and flat out wrong 3rd party tutorials out there on the web.

Is there any way to make this experience easier for average users? Perhaps add post-install messages like most other Rails gems do?

Also could you guys simplify the README.md by turning it into a getting started guide for beginners, and then move the actual documentation into a separate file and link to it from the README? It's currently way too much info there adding more confusion than clarity.

Thanks for listening!

**Comment by justin808** [comment]
@jakeNiemiec, #2448 will help.

**Comment by arjundedha** [comment]
https://speciallyshoes.com/best-basketball-shoes-for-ankle-support/

**Comment by SWITCHAccess** [comment]
I wish I could tell you how much I understand but I'm very unsure murkmyself. Yes I absolutely agree that there has got to be an easier way. I completely agree. I wish I was not new and could offer my hand to help! 
Thanks for listening

**Comment by Bramdimalone226** [comment]
> All in all this experience has been terribly confusing, especially for me who is a beginner to Rails and thought everything would be ready to go after `rails new myapp`.
> 
> Instead it turned out I had to downgrade Yarn. I also struggled to install basic packages like jQuery and had to resort to outdated and flat out wrong 3rd party tutorials out there on the web.
> 
> Is there any way to make this experience easier for average users? Perhaps add post-install messages like most other Rails gems do?
> 
> Also could you guys simplify the README.md by turning it into a getting started guide for beginners, and then move the actual documentation into a separate file and link to it from the README? It's currently way too much info there adding more confusion than clarity.
> 
> Thanks for listening!
