### ISSUE TITLE
Add a toString on the webpack config object

### ISSUE THREAD

**Issue by justin808** [rails/webpacker#2460]
Here's a good example of what to do. @gauravtiwari @jakeNiemiec if you like this, I might throw together a PR.

* https://github.com/neutrinojs/webpack-chain/pull/53/files
* https://github.com/neutrinojs/neutrino/pull/928/files

While this sort of debug logging works, we can probably do better:

```javascript
const DashboardPlugin = require("webpack-dashboard/plugin");
const environment = require("./environment");

process.env.NODE_ENV = process.env.NODE_ENV || "development";

environment.plugins.prepend("DashboardPlugin", new DashboardPlugin());

const webpackConfig = environment.toWebpackConfig();

console.log(
  "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ"
);
console.log("webpack.config for development:");
console.log(JSON.stringify(webpackConfig, null, 2));
console.log(
  "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ"
);

module.exports = webpackConfig;
```

**Comment by justin808** [comment]
Then again, just running this works pretty well:

```
bin/webpack --debug
```

**Comment by justin808** [comment]
(ps, that was my PR 😆 )

**Comment by jakeNiemiec** [comment]
Would this just be for debugging? Are you testing this in a terminal or devtools?

**Comment by justin808** [comment]
Just a nice to have for debugging. I haven't tried it. The basic JSON.stringify is slightly misleading.

**Comment by jakeNiemiec** [comment]
`[object Object]` got you down? There are ways you can fix that in your environment.js:

```js
// environment.js
let webpackConfig = environment.toWebpackConfig();
// don't use an arrow function here because the lexical `this` will be different!
webpackConfig.prototype.toString = function() { 
  JSON.stringify(this, undefined, 2);
}
```
--OR if we wanted to modify webpacker:
```js
// webpacker/package/config_types/config_object.js:10
class ConfigObject extends Object {
  //...
  toString() {
    return JSON.stringify(this, undefined, 2)
  }
  //...
} 
```

> then it would be nice to have an awesome printout of a webpack config

There are also other modern ways to debug this stuff. I really like logpoints:

![image](https://umaar.com/assets/images/dev-tips/node-connection.gif)

![image](https://umaar.com/assets/images/dev-tips/ndb-node-debug.gif)

![image](https://umaar.com/assets/images/dev-tips/logpoint.gif)

[link ](https://umaar.com/dev-tips/149-node-connection/)[link ](https://umaar.com/dev-tips/177-ndb-node-debug/)[link](https://umaar.com/assets/images/dev-tips/logpoint.gif)

**Comment by justin808** [comment]
I think the debugger is a super simple and memorable way to get the printout.

@rossta anything to add here?
