### ISSUE TITLE
complete list of directories and files installed by webpacker

### ISSUE THREAD

**Issue by matthewgoodwin** [rails/webpacker#2461]
Hey Everyone, I want to do a fresh install of webpacker, so I want to gut my app of Webpacker. Im looking for a way to uninstall webpacker, and Im also looking for a complete list of directories and files installed by webpacker. Thanks in advance!

**Comment by justin808** [comment]
@matthewgoodwin The easiest thing to do is create a fresh Rails app without webpacker, git commit, run the webpacker install, git commit, and look at the changes from the second commit.

For the install, you might want the basic one or one like the React one.

Or just look at the files here: https://github.com/rails/webpacker/tree/master/lib/install

**Comment by matthewgoodwin** [comment]
Thanks, that was an excellent suggestion!
