### ISSUE TITLE
Produce CSS source-maps in production build

### ISSUE THREAD

**Issue by nliapis** [rails/webpacker#2466]
Is there any way to produce CSS source-maps for the production environment?

I have seen that source-maps are [enabled](https://github.com/rails/webpacker/blob/master/package/environments/production.js#L45) but it seems that [OptimizeCSSAssetsPlugin](https://github.com/rails/webpacker/blob/master/package/environments/production.js#L35) prevent this functionality. 

Tried to change OptimizeCSSAssetsPlugin [config](https://github.com/rails/webpacker/blob/master/package/environments/production.js#L38) to `inline: true` without positive results.

Finally, the only way to have CSS source-maps was to completely disable/remove OptimizeCSSAssetsPlugin, but is there any better approach?

**Comment by jakeNiemiec** [comment]
> Tried to change OptimizeCSSAssetsPlugin config to inline: true without positive results.

Make sure you also have the devtool set up: https://github.com/rails/webpacker/issues/2003#issuecomment-511474134

> Finally, the only way to have CSS source-maps was to completely disable/remove OptimizeCSSAssetsPlugin, but is there any better approach?

I'll have to do some testing to make sure OptimizeCSSAssetsPlugin is doing what it needs to do.

**Comment by nliapis** [comment]
Thank you @jakeNiemiec for your comment. 

> Make sure you also have the devtool set up: #2003 (comment)

I checked it and devtools are enabled.

The problem is that the production build doesn't include CSS source-maps.
Is this behavior what we want? 

For example, I see JS source-maps are produced and work as expected.

**Comment by jakeNiemiec** [comment]
> I checked it and devtools are enabled

Specifically, I meant `devtoolModuleFilenameTemplate`.

> The problem is that the production build doesn't include CSS source-maps.
Is this behavior what we want?

Can you post one of your css files? If you have `inline: true`, the sourcemap will be inside the file instead of a separate `file.map.css`.

**Comment by nliapis** [comment]
This is what I'm taking when running a production build, `RAILS_ENV=production NODE_ENV=production bin/webpack`


<img width="431" alt="Screenshot 2020-02-20 at 10 51 20 AM" src="https://user-images.githubusercontent.com/5075083/74917060-97e62700-53cf-11ea-94f9-0399f403b8f7.png">

> If you have inline: true, the sourcemap will be inside the file instead of a separate file.map.css.

There are no sourcemaps inside `CSS` file and there is no `sourceMappingURL` inside CSS file. 

If I run a build in development, `bin/webpack`, I see sourcemaps and I see also inside CSS file the `sourceMappingURL`.

<img width="442" alt="Screenshot 2020-02-20 at 10 59 17 AM" src="https://user-images.githubusercontent.com/5075083/74918023-2909cd80-53d1-11ea-8de5-fc72991c43f5.png">

`/*# sourceMappingURL=application-27c04aa1.css.map*/`

Am I missing something?

**Comment by jakeNiemiec** [comment]
Can you post your `environment.js` file(s)?

**Comment by nliapis** [comment]
Haven't changed anything neither in `environment.js` nor `production.js`, are the defaults one.

`environment.js`
```
const { environment } = require('@rails/webpacker')

module.exports = environment
```

`production.js`
```
process.env.NODE_ENV = process.env.NODE_ENV || 'production'

const environment = require('./environment')

module.exports = environment.toWebpackConfig()
```
Keep in mind that I tried also to install a new rails app and I had the same behavior, no CSS source-maps in the production build.

**Comment by jakeNiemiec** [comment]
> Tried to change OptimizeCSSAssetsPlugin config to `inline: true` without positive results.

If you set `inline: true`, you should see `sourceMappingURL` at the bottom of the css file, otherwise the maps are "optimized out".

**Comment by nliapis** [comment]
Could you please explain where I need to set `inline: true` configuration?

**Comment by jakeNiemiec** [comment]
> Could you please explain where I need to set inline: true configuration?

Something like this should work:
```js
// Remove the plugin
environment.plugins.delete('OptimizeCSSAssets')

// Add back with custom options
environment.plugins.plugins.append(
  'OptimizeCSSAssets',
  new OptimizeCSSAssetsPlugin({
    parser: safePostCssParser,
    map: {
      inline: true,
      annotation: true
    }
  })
)
```
You can see the full config api here:

https://github.com/rails/webpacker/blob/13756f1ea6b3393117878bb339b9dd507b801eb2/package/config_types/config_list.js#L5-L13

**Comment by jakeNiemiec** [comment]
TBH, you could just remove the OptimizeCSSAssets plugin.

**Comment by nliapis** [comment]
Thank you a lot @jakeNiemiec for your help, I have tried almost everything from your suggestions.

1. Remove the OptimizeCSSAssets plugin works but CSS file is not minified, you need to apply another minifier like `cssnano` into `postcss.config.js` file. This solution works but is this way the preferable?
2. Change the `OptimizeCSSAssetsPlugin` map config to `inline: true` didn't work. No CSS source maps.  Also I see in the [documentation](https://github.com/NMFR/optimize-css-assets-webpack-plugin#example) of `OptimizeCSSAssets` plugin that the configuration is different from what exists in  rails/webpacker environments directory.

**Comment by jakeNiemiec** [comment]
> works but CSS file is not minified

Are you running webpacker 4+?

**Comment by jakeNiemiec** [comment]
> you need to apply another minifier like cssnano into postcss.config.js file. This solution works but is this way the preferable?

😅 I guess I forgot about `cssnano`. My webpacker config is very unconventional, but this is how I personally minify & autoprefix:
```js
{
  loader: 'postcss-loader',
  options: {
    sourceMap: true,
    ident: 'postcss',
    plugins: [
      require('cssnano')({
        preset: ['advanced', { reduceIdents: false, autoprefixer: autoprefixerOpts }]
      })
    ]
  }
};
```

https://github.com/rails/webpacker/blob/13756f1ea6b3393117878bb339b9dd507b801eb2/package/utils/get_style_rule.js#L9-L43

I actually don't see a way to inject `cssnano` into the `postcss-loader`; `postcss.config.js` might be the only way, but I don't remember that working well. Hope this helps regardless.

**Comment by piotrb** [comment]
Based on a bunch of these options above I came up with a pretty clean way of swapping all the right bits in.

With the help of `css-minimizer-webpack-plugin` this can be done by just removing the builtin CSS Optimizer, and swapping in this plugin. This will use `cssnano` under the hood and make it all work nicely.

in `production.js`
```js
require("./production/css_optimization")(environment)
```
(somewhere above the module.exports line)

And `production/css_optimization.js` itself:
```js
const CssMinimizerPlugin = require("css-minimizer-webpack-plugin")

module.exports = function (environment) {
  // Remove the plugin
  environment.plugins.delete("OptimizeCSSAssets")

  // Add a different optimizer that actually preserves source maps
  environment.config.optimization.minimizer.push(new CssMinimizerPlugin())
}
```
