### ISSUE TITLE
file-loader using bad regexp

### ISSUE THREAD

**Issue by ngan** [rails/webpacker#2469]
I noticed the `file-loader` rule has the following:
```
{
  test: /(.jpg|.jpeg|.png|.gif|.tiff|.ico|.svg|.eot|.otf|.ttf|.woff|.woff2)$/i,
  use: { ... }
}
```

That regexp looks like it's not exactly right. Eg, it'd match a file named `ajpg` or `xpng` since the `.` isn't escaped and is acting as a wildcard.

If this is really a bug, I'd be happy to put up a fix. The fix would be to escape the string first. Let me know if you'd prefer a home-baked solution (eg `string.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');`) or using a package like https://www.npmjs.com/package/escape-string-regexp.

**Comment by jakeNiemiec** [comment]
How about this?:
```js
{
  test: /\.(jpe?g|png|gif|tiff|ico|svg|eot|otf|ttf|woff2?)$/i,
  use: { ... }
}
```

**Comment by ngan** [comment]
The regex is formed by the list of extensions defined in your `config/webpacker.yml`. So, I'm not sure if you want to get extra smart and do simplifications like `jpe?g`. Also, an extension can be `.foo.bar` so we can't safely assume that there's 1 dot in every extension to remove. I think the safest thing to do is to take the extensions as-is and escape them.

**Comment by guillaumebriday** [comment]
I think it's not relevant now: https://github.com/rails/webpacker/blob/5-x-stable/package/rules/file.js#L5

Could you close the issue if it's ok for you?
