### ISSUE TITLE
"Webpack not found" error if yarn install was run with --no-bin-links flag (Docker Toolbox on Windows)

### ISSUE THREAD

**Issue by carlaraya** [rails/webpacker#2472]
In docker toolbox on windows you cannot create symlinks as windows does not support them so you have to run yarn install with --no-bin-links flag. But if I run docker-compose up and access a website this error pops up in console:
![asdfasdfs](https://user-images.githubusercontent.com/13644295/75352288-7b248480-58e4-11ea-897b-ea87e6f90a39.png)

How to replicate: start up any rails app that utilizes webpack, but run yarn install with --no-bin-links flag. then run the server and access a webpage.

There is a ~~similar~~ near-identical issue https://github.com/rails/webpacker/issues/229 but their fix does not work.

**Comment by carlaraya** [comment]
Hello. I just tried  `yarn install --no-bin-links` with my Rails installation on Linux. It outputs the exact same error as in Docker Toolbox on Windows (command webpack not found). I do not think this is a problem with Docker, but with webpacker and/or yarn. Please see https://github.com/rails/webpacker/issues/229, they explain the issue better.

**Comment by guillaumebriday** [comment]
Is this still an issue? Feel free to reopen if needed
