### ISSUE TITLE
Engines using webpacker precompiling all individual packs even if no code change

### ISSUE THREAD

**Issue by cpetley** [rails/webpacker#2473]
Hello

I have followed this guide to the letter https://github.com/rails/webpacker/blob/master/docs/engines.md and now have engines successfully compiling individual packs in production. Thanks so much for adding this to webpacker!!

However, I now find that my app takes a very long time to deploy. When running `rake assets:precompile RAILS_ENV=production`, the individual compilation of each engine can take a VERY long time - like over 60 seconds per engine. And I have 30 engines...

Is there a way to ensure that webpacker only recompiles the packs that have changed code? In my lib/tasks/engine.rake files, there seems to be no check to see if recompilation is necessary. Am I missing something? 

Thanks

**Comment by jakeNiemiec** [comment]
I am afraid I don't have too much experience with the engine flow, but this may be helpful if you can manage a DIY solution: https://github.com/trivago/parallel-webpack

**Comment by tleish** [comment]
@cpetley - interesting, I have the opposite issue with engines... where once I compile the assets, they will not recompile when changes are made in the engine.  I have to remove the compiled packs first before precompiling.  I'm curious as to how our setups differ that cause yours to always recompile and mine to only recompile once

**Comment by tleish** [comment]
Take a look at my recent discovery in #2487.  It could be that the list of files being searched to calculate the digest is your entire project, not just the javascript files?

You might be able to figure this out by adding the following monkey patch.

```ruby
# engines/foo/config/initializers/webpacker.rb
module Webpacker
  module WatchedFilesDigestPatch
    private

    def watched_files_digest
      digest = super
      files = Dir[*default_watched_paths, *watched_paths].reject { |f| File.directory?(f) }
      puts '#' * 20
      puts digest
      puts files
      puts '#' * 20
      digest
    end
  end
end

Webpacker::Compiler.prepend Webpacker::WatchedFilesDigestPatch
```

The above debugging code would allow you to print all the digest and files that are being watched so you can determine if your configuration needs to be adjusted to narrow the list of watched files.

See also: #2487

**Comment by cpetley** [comment]
@tleish thanks very much for the above. 
My app is organised in fairly standard way, in that I have a central app that calls different engines. 
It has highlighted that if I change ANY file in the central app, all the engines will recompile, and if I don't, none of them will! Wonder if that might be linked to your issue of none of your engines recompiling?

**Comment by cpetley** [comment]
@tleish I've got it working by inserting the line 
`Dir.chdir(config.root_path.cleanpath)` before the files declaration in your method. Don't know if this will help you but thought I'd mention it
