### ISSUE TITLE
Where are the transpiled files?

### ISSUE THREAD

**Issue by benlieb** [rails/webpacker#2474]
I'm porting a react-based chrome extension that I made 3 years ago in reactapp to a rails and webpacker-backed extension. 

I want to use the packs build system to build my js. But the final step for making the extension involves making a build directory that will be uploaded as the extension. This will require that I copy some of the webpacker-built js files into another directory and rename the files without a hash at the end (the have to be named specifically for chrome extensions).

I've built the rails app, and the packs are compiling and loading into a standard web page, but I can't find the actual pack-build js files to copy into my build directory?

Where are these stored? Perhaps they're just in memory in the dev env? Do I need to manually run a compile task or something?

Help appreciated!

UPDATE:

It seems I can run `rake webpacker:compile` and this puts the files in public/packs/js.

Is this the best way to do what I'm trying to do? Is there a way to compile without the digest attached (in dev only, which is ignored in .gitignore)?

**Comment by jakeNiemiec** [comment]
> Is this the best way to do what I'm trying to do? Is there a way to compile without the digest attached (in dev only, which is ignored in .gitignore)?

The docs for doing this are located here: https://github.com/rails/webpacker/blob/master/docs/webpack.md#configuration

```js
// in your environment.js file
environment.config.set('output.filename', '[name].js') // the default is 'js/[name]-[contenthash].js',
```
It would look something like that. Hope this helps.

**Comment by benlieb** [comment]
@jakeNiemiec thanks for the info, but I already looked at that. If I'm not mistaken this setting will be global and effect all files. I don't want to change the way webpacker is working, but IN ADDITION to the normal `myfile-adf234qwer132352.js` file I need to copy this file to an outside directory and name i `myfile.js`. 

So far I've just written a simple script to do this, but it is a bit complicated by the fact that multiple calls to `rake webpacker:compile` will leave multiple copies of the file with hash laying around. Not obvious to tell which is the "most recent".

**Comment by jakeNiemiec** [comment]
> Not obvious to tell which is the "most recent".

Take a look at `manifest.json` in the same directory. It will list all of the "fresh" files by name and entrypoint.

**Comment by guillaumebriday** [comment]
Can this issue be closed ?
