### ISSUE TITLE
Datta-Able in vuejs

### ISSUE THREAD

**Issue by HaniGerges** [rails/webpacker#2477]
i have an issue with Datta able template...
when i split it in components .vue
its not working, like nav in page and header in page
if nav close header still in same place doesnt move
 but if all of them in single page everything work like (Menu got on and off and everything move with it)

**Comment by guillaumebriday** [comment]
I think this issue is out of the scope of Webpacker.

Here is the documentation about component splited in chunks: https://github.com/rails/webpacker/blob/master/docs/integrations.md#lazy-loading-integration

Hope this help, feel free to close the issue if it's ok for you
