### ISSUE TITLE
React and Vue simultaneously integration

### ISSUE THREAD

**Issue by wendellpbarreto** [rails/webpacker#2480]
Is it possible to have both React and Vue integration on a Rails project? Already tried a lot of things but without success.

**Comment by jakeNiemiec** [comment]
Yes: Docs for [React](https://github.com/rails/webpacker#react) & [Vue](https://github.com/rails/webpacker#vue). Feel free to detail any webpacker-specific problems that you ran into.

**Comment by wendellpbarreto** [comment]
Thanks, @jacksonrayhamilton! I'm closing this card and create a new one specifying the problem

**Comment by donni106** [comment]
@wendellpbarreto have you finished the integration of react + vue simultaneously in your react app? if yes, how was it going, if no, what were the problems?
