### ISSUE TITLE
"_typeof is not a function" bug on production env

### ISSUE THREAD

**Issue by wendellpbarreto** [rails/webpacker#2483]
When compiling in production, js dependencies that uses typeof expression will output "_typeof" instead and cause the error "_typeof is not a function"

I searched a lot and understand that @babel/preset-env is transforming "typeof" in "_typeof", but if we add "transform-typeof-symbol" to exclude rule, everything should work. But is not working with me.

The line of lib that uses typeof is this one: https://github.com/zenorocha/clipboard.js/blob/master/dist/clipboard.js#L516

The output code is:
![image](https://user-images.githubusercontent.com/2782873/76245700-1984e400-621b-11ea-95e6-add062a8a45e.png)
![image](https://user-images.githubusercontent.com/2782873/76245734-27d30000-621b-11ea-9733-add322d1f826.png)

And my babel.config.js generated by this gem:
![image](https://user-images.githubusercontent.com/2782873/76246154-ebec6a80-621b-11ea-9c07-978d55855691.png)

Someone knows what I'm doing wrong?

**Comment by jakeNiemiec** [comment]
> And my babel.config.js generated by this gem

`babel.config.js` should contain a lot more than just that.

> Someone knows what I'm doing wrong?

`environment.loaders.delete('nodeModules');` like in https://github.com/rails/webpacker/issues/2131#issuecomment-577337437 will most likely solve your problem. You can read my explanation there for further details 👍.

**Comment by wendellpbarreto** [comment]
Thanks, @jakeNiemiec! This just solve the problem.
