### ISSUE TITLE
Webpacker is compiling twice when using --config

### ISSUE THREAD

**Issue by joker-777** [rails/webpacker#2484]
Hi,

Webpacker is compiling twice when using the `--config` to specify a configuration file. We have the feeling it uses the specified configuration file as well as the configuration file in `config/webpack/<environment>.js`.

I hope you guys can help here. Thanks!

**Comment by kimyu92** [comment]
This is fixed in master from cb8c07999c39be48afa4ebeb73160c2b5a5ee192
This seems to be problematic for a lot of people including myself, can we have a patch release for webpacker? cc @jakeNiemiec @gauravtiwari
