### ISSUE TITLE
Webpacker not detecting up changes in engines

### ISSUE THREAD

**Issue by tleish** [rails/webpacker#2487]
I followed the instructions outlined in [webpacker/engines](https://github.com/rails/webpacker/blob/master/docs/engines.md).  rails asset precompile picks up and compiles files initially, but it does not detect and/or precompile changes unless I clobber the assets first and then precompile again. Webpacker is not detecting javascript changes in an engine.

Steps to reproduce:
1. run `bundle exec rake RAILS_ENV=production assets:precompile`
2. Make a change to a javascript file
3. run `bundle exec rake RAILS_ENV=production assets:precompile` 

After step 1, all javascript files are compiled
After step 3, nothing is compiled until after I clobber the assets.  It seems all files are cached.

Current workaround: clobber precompiled assets/packs and the recompile.

How can I configure webpacker on the engine to detect precompile changed files, while still caching the unchanged files.

**Comment by tleish** [comment]
Related to #2410

**Comment by tleish** [comment]
```ruby
class Webpacker::Compiler
  
  #...
   
  private
  
  def watched_files_digest
    files = Dir[*default_watched_paths, *watched_paths].reject { |f| File.directory?(f) }
    file_ids = files.sort.map { |f| "#{File.basename(f)}/#{Digest::SHA1.file(f).hexdigest}" }
    Digest::SHA1.hexdigest(file_ids.join("/"))
  end

  # ...
   
  def default_watched_paths
    [
    *config.resolved_paths_globbed,
    "#{config.source_path.relative_path_from(config.root_path)}/**/*",
    "yarn.lock", "package.json",
    "config/webpack/**/*"
    ].freeze
  end
end
```

The problem is that if `resolved_paths` is defined in `engine/foo/config/webpacker.yml`, the pathes need to be relative to the engine root, not the application root.  Otherwise it won't compile.

However, when the compiler builds the `watched_files_digest`, it does so from root app directory, not the engine directory.  So, the it can't find the relative file paths.  Some have found a workaround to explicately add the absolute paths to watched_paths.

```ruby
Webpacker::Compiler.watched_paths << '/absolute/path/to/app/javascript/**/*'
```

The following change resolves the issue in my project without forcing absolute paths:

```diff
def watched_files_digest
+ Dir.chdir config.root_path do
    files = Dir[*default_watched_paths, *watched_paths].reject { |f| File.directory?(f) }
    file_ids = files.sort.map { |f| "#{File.basename(f)}/#{Digest::SHA1.file(f).hexdigest}" }
    Digest::SHA1.hexdigest(file_ids.join("/"))
+ end
end
```

I've done this using the following monkeypatch:

```ruby
# engines/foo/config/initializers/webpacker.rb
module Webpacker
  module WatchedFilesDigestPatch
    private

    def watched_files_digest
      Dir.chdir config.root_path do
        super
      end
    end
  end
end

Webpacker::Compiler.prepend Webpacker::WatchedFilesDigestPatch
```

May want to consider this as a permanent fix.  It should work for both Rails apps and engines, assuming the engines are defined with the correct `root_path` based on the engines instructions.

**Comment by thomasbrus** [comment]
@tleish That monkey patch works great. 

Did you you ever manage to get this working with `bin/webpack-dev-server`? For me it only compiles assets in the host application. Can't run `bin/webpack-dev-serve`r in the engine at the same time obviously cause it runs on the same port.

**Comment by tleish** [comment]
@thomasbrus - To run multiple `bin/webpack-dev-server`:

1. Change the default dev_server port and env_prefix in the engines `webpacker.yml`
```yaml
# engines/abc-engine/config/webpacker.yml
development:
  #...
  dev_server:
    env_prefix: "ABC_ENGINE_WEBPACKER_DEV_SERVER"
    host: localhost
    port: 3037
    public: localhost:3037

# engines/xyz-engine/config/webpacker.yml
development:
  #...
  dev_server:
    env_prefix: "XYZ_ENGINE_WEBPACKER_DEV_SERVER"
    host: localhost
    port: 3038
    public: localhost:3038
```
2. Run the webpack dev server inside the engine:
```
ruby engines/abc/bin/webpack-dev-server
```

**Comment by thomasbrus** [comment]
@tleish Hey that works great, thanks man!

One more thing. In the host app the page doesn't reload when making changes in the engine (when running `bin/webpack-dev-server` in both host and engine). I see this error in the browser console:

> sockjs.js:1796 Refused to connect to 'http://localhost:3036/sockjs-node/info?t=1599815131383' because it violates the following Content Security Policy directive: "connect-src 'self' https: http://localhost:3035 ws://localhost:3035".

('l'll update here once fixed..)

**Comment by n-rodriguez** [comment]
This is not a good solution as it will break with Ruby 3 : https://github.com/rails/webpacker/issues/2801
