### ISSUE TITLE
Precompiled webpack assets for CI

### ISSUE THREAD

**Issue by ngan** [rails/webpacker#2488]
Hi, this is more seeking advice than anything. Apologizes if this is not the right forum, but maybe this will evolve into a PR enhancement.

We precompile Webpacker assets for CI, cache it, then make it available for our integration tests to be run in parallel on many machines. In `config/webpacker.yml`, we have our `compile` option set to `true`. This is the default and because we want lazy asset compilation for local testing. However, on CI, which runs as `RAILS_ENV=test`, I would like Webpack to *not* compile, and therefore *not* make the **expensive** check to watched folders to see if any js/css files changed.

I currently have a "hack" in my RSpec support file:
```
if ENV['CI']
  Webpacker.instance.config.__send__(:data)[:compile] = false
end
```

This seems dirty and was wondering if anyone else has a better solution or if we can engineer solution into Webpacker.

**Comment by tleish** [comment]
Just a guess, but if you change `compile: false` in your `config/webpacker.yml`, does that resolve the issue?

```yaml
test:
  <<: *default
  compile: false
```

**Comment by ngan** [comment]
It does, but that is not desired during local development since I want it to lazy-compile for test runs.

**Comment by davefp** [comment]
Webpacker supports custom Rails environments, perhaps a `ci` env would do the trick? https://github.com/rails/webpacker#custom-rails-environments

**Comment by harmdewit** [comment]
Got the same issue and I don't really like adding another environment. I would prefer reusing the test environment and override specific settings. Perhaps add a new environment variable here?
 
https://github.com/rails/webpacker/blob/da362b8c96a4be5a4af8f8ad886f5dd8451f457f/lib/webpacker/configuration.rb#L18-L20

```ruby
def compile? 
  ENV.fetch('WEBPACKER_COMPILE') { fetch(:compile) }
end 
```

**Comment by guillaumebriday** [comment]
Thanks @harmdewit

**Comment by syakovyn** [comment]
@guillaumebriday, could you explain why the issue was closed? I can't find the WEBPACKER_COMPILE usage in the webpacker gem codebase. 
From your comment I understood you are going to implement what @harmdewit suggested but it doesn't look like that.
