### ISSUE TITLE
how to use condition class in .erb from js function ?

### ISSUE THREAD

**Issue by ibantoo** [rails/webpacker#2491]
i have fucntions on `app/javascript/packs/is_mobile.js`
like this : 
```
function isMobile() {
    if(window.innerWidth >= 991) {
        return "d-flex flex-row justify-content-center"
    } else {
        return "d-flex flex-column justify-content-center"
    }
}
```

i put in .erb file like this 
```
  <%= javascript_pack_tag 'is_mobile' %>
 <div class="<% isMobile %"> </div>
```

nothing change or work 
and i do this also 
```
 <div onresize="isMobile()"> </div>
```

is there any way to work for that function in .erb ?

**Comment by guillaumebriday** [comment]
You can't write a JavaScript function and call it with Ruby. 

You should select your `div` in javascript and change its class dynamically.
