### ISSUE TITLE
more consistent/frequent release schedule

### ISSUE THREAD

**Issue by kimyu92** [rails/webpacker#2497]
Here are some of the releases:
```
on Dec 9, 2019 v4.2.2 
on Dec 9, 2019 v4.2.1
on Nov 12, 2019 v4.2.0
on Nov 12, 2019 v4.1.0
on Jun 3, 2019 v4.0.7
```

There are inconsistent and yet huge gaps between each release and it seems like webpacker gem can be benefit with more minor releases to catch up with front-end packages changes (which imo can be handled through dependabot) and it helps to mitigate security issues. Would like to have discussion here and keep the gem healthy ✌️

**Comment by guillaumebriday** [comment]
Webpacker is using https://semver.org. You can find the release notes in the https://github.com/rails/webpacker/blob/master/CHANGELOG.md
