### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by suneelvalipi** [rails/webpacker#2505]

**Comment by michelin22** [comment]
Hola... creo que voy a necesitar ayuda! 
Ya hace una semana y media  que vengo metida en mi teléfono.. son tantas cosas para saber y descargar, que aún no eh podido organizar mi pagina github! 
Necesito generar unas cuentas.. esa es mi meta... 
Con el nombre Damian Gerez/ número telefónico +5492355475240/ y el mail que puede ser también de utilidad, Damiangerez_36@hotmail.com..
Las cuentas son las básicas, Facebook, Instagram y whats App
