### ISSUE TITLE
Reduced Rails comfort when switching git branches

### ISSUE THREAD

**Issue by schmijos** [rails/webpacker#2506]
I switch my git branches like a brisk bird. I work on a feature, then check out a remote change and then switch back to the master.

Since we got _Webpacker_ in _Rails_, my life became less comfortable: while switching branches works well with _Ruby_ gems (because you can have multiple versions installed and dependency resolution is fast), it doesn't with _node_ packages. I encounter the following message way too often when running `rails s`:

```
========================================
  Your Yarn packages are out of date!
  Please run `yarn install --check-files` to update.
========================================
```

https://github.com/rails/webpacker/issues/1135 makes it even worse.

_Rails_ should not annoy me because of _Webpacker_. Can we do something about that?
A naive idea would be to make separate `node_modules` folders for each `yarn.lock`.

Are there any other (more feasible) ideas?

**Comment by michelin22** [comment]
Hola Schmijos!! Soy nueva en esta situación paginas! Me interesa, me parece muy fascinante... y quisiera aprender de a poco, ya que todo me parece raro aún... es hasta que empieza anda andarle las teclas... 
si no te molesta, me podrías ayudar?? 
Quizás, embleme demasiadas frecuencia, quizás no me explico bien.. como podría hacerlo mejor? 
Y por ejemplo, tú dices hacer node_modules y yarn.lock, y por separado... disculpa mi ignorancia, pero esto sería en la misma paginas de Github, en una página web como por ejemplo: Chrome, o en las direcciones de las redes sociales qué hay que completar para poder ingresar?

**Comment by michelin22** [comment]
Y otra cosa más! Creo que me falta no unos pasos para poder ofertar terminar de ordenar mi pa pagina github, no sé si es mi teléfono por su configuración y aplicaciones que están de gustos, que me vuelvo loca yendo de una pagina a la otra! No quiero saltearme nada y prestar atención a cada cosa (qué es un mar de palabras, proveedores, cookies, etc..) ya llevo 54 pestañas abiertas, (solo en Chrome) y llevo una semana y media metida en mi telefono.. 
son tantas cosas para poder empezar con todo y de una vez que ya me siento a algo mareada! 
Necesito ayuda

**Comment by SkipKayhil** [comment]
I think this is one of the places that Yarn 2 (specifically PnP #2112) would be very beneficial. It would remove the need for a `node_modules` folder and module resolution would happen on the fly so re-installs should not be necessary.

**Comment by jakeNiemiec** [comment]
> while switching branches **works well with Ruby gems** (because you can have multiple versions installed and dependency resolution is fast), **it doesn't with node packages**. 

Do you have your `yarn.lock` file under version control?

**Comment by rossta** [comment]
I don’t think this is a problem Webpacker should solve. This is an issue for any yarn- or npm-managed project: you have to run `yarn install` each time you switch branches. This can be handled with a git hook https://andy-carter.com/blog/automating-npm-and-composer-with-git-hooks

**Comment by guillaumebriday** [comment]
I think this has been removed in https://github.com/rails/webpacker/commit/09caeed2edd8372238ea82e577452443aa2775cf

thanks @rossta
