### ISSUE TITLE
After upgrade, webpacker breaks deployment over environment.js configuration

### ISSUE THREAD

**Issue by RailsCod3rFuture** [rails/webpacker#2510]
I recently updated the webpacker gem in my project to webpacker 4.2.2. Now I'm unable to deploy without receiving **configuration has unknown property 'resolvedModules'. These properties are valid**.

my environment.js is below

```
const {environment} = require('@rails/webpacker');
const webpack = require('webpack');

environment.plugins.prepend('Provide',
   new webpack.ProvidePlugin({
      $: 'jquery',
       jQuery: 'jquery',
      moment: 'moment'
  }));

environment.config.merge({
   resolve: {
    alias: {
    jquery: 'jquery/src/jquery',
    }
  }
});
module.exports = environment;
```

Has anyone experienced this problem, recently?

**Comment by rossta** [comment]
What is in your `production.js` file?

**Comment by RailsCod3rFuture** [comment]
I fixed it. by using environment.toWebpackConfig(); Also, there were some dependencies inside of my pack file that were not initialized in the application.js file.
