### ISSUE TITLE
Is core-js really needed in package.json dependencies?

### ISSUE THREAD

**Issue by Borzik** [rails/webpacker#2514]
`core-js` is mentioned in only 7 files:

- angular install script (where it actually does `yarn add core-js`) and angular example
- docs: es6, changelog, readme
- package.json
- node_modules' rules

So is it really needed there? I don't really need to support angular example in my own project. And since it's [not used by default and needs to be enabled manually](https://github.com/rails/webpacker#usage), do we really need it to be included in package.json and have in installed in every webpacker project? If someone needs polyfills, they can easily install `core-js` (it's a matter of running `yarn add core-js`) or whatever other polyfilling lib they might need.

**Comment by SkipKayhil** [comment]
In addition, I don't think it should be recommended in the README to add `core-js` and `regenerator-runtime` imports to `packs/application.js`. These libraries are used by Babel to polyfill functions if they are needed, so they don't need to be manually imported.

**Comment by jakeNiemiec** [comment]
> These libraries are used by Babel to polyfill functions if they are needed

Yeah, but you don't know which polyfill you will need until runtime. You could remove it, but things may break for you or your users. More info: [core-js](url), [browser compatibility](url).

**Comment by SkipKayhil** [comment]
> 
> 
> > These libraries are used by Babel to polyfill functions if they are needed
> 
> Yeah, but you don't know which polyfill you will need until runtime. You could remove it, but things may break for you or your users. More info: [core-js](url), [browser compatibility](url).

I thought that was the purpose of `useBuiltIns: usage`, so babel knows exactly what to polyfill based on which functions you call. [Relevant docs](https://babeljs.io/docs/en/babel-preset-env#usebuiltins-usage).

Actually it looks like the current recommended babel config in webpacker uses `useBuiltIns: 'entry'` so you are probably correct. However, I think looking into using the `usage` option and removing the direct dependencies may be a better solution

**Comment by jakeNiemiec** [comment]
`usage` will just inject the `core-js` polyfills inline, you would still need it.

> so babel knows exactly what to polyfill based on which functions you call

You may be thinking of `browserslist`, this is what tells babel which polyfills to worry about. https://babeljs.io/docs/en/babel-preset-env#browserslist-integration

**Comment by justin808** [comment]
If you really want simple, then Rails 7 has non-webpack support for JS.
