### ISSUE TITLE
Assets load in Rails views and JS files but not SCSS

### ISSUE THREAD

**Issue by nickmjones** [rails/webpacker#2516]
With the following as my `application.js' in `app/javascript/'...

```
require.context('../images', true)
require("@rails/ujs").start()
require("turbolinks").start()
require("@rails/activestorage").start()
require("channels")
import "./styles/application.scss";
import "@fortawesome/fontawesome-free/js/all";

// Uncomment to copy all static images under ../images to the output folder and reference
// them with the image_pack_tag helper in views (e.g <%= image_pack_tag 'rails.png' %>)
// or the `imagePath` JavaScript helper below.
//
const images = require.context('../images', true)
const imagePath = (name) => images(name, true)
// Support component names relative to this directory:
var componentRequireContext = require.context("components", true);
var ReactRailsUJS = require("react_ujs");
ReactRailsUJS.useContext(componentRequireContext);
```

I'm able to add images to Rails views like so:

```
<img src="<%= asset_pack_path 'media/images/checked.png' %>" />
```

However, I can't include images in CSS like this:

```
.bar > input:checked + div {
  background: rgba(255, 255, 255, 0.1) url('media/images/checked.png') center center no-repeat;
}
```

Any help appreciated.

**Comment by rossta** [comment]
Try using a relative path in your CSS, e.g. `url('../images/checked.png')`.

**Comment by AndrewVos** [comment]
I am having this issue too. Did you resolve it @nickmjones ? I have the corrent path in my manifest, but it's just not working in scss.

**Comment by nickmjones** [comment]
I never got to any resolution. I was early in a project so I could choose a new framework, so I did. Working in Rails is becoming a chore.

**Comment by nickmjones** [comment]
> I am having this issue too. Did you resolve it @nickmjones ? I have the correct path in my manifest, but it's just not working in scss.

I never got to any resolution. I was early in a project so I could choose a new framework, so I did. Working in Rails is becoming a chore.
