### ISSUE TITLE
How to enable gzip woff woff2 fonts files?

### ISSUE THREAD

**Issue by nPaul** [rails/webpacker#2523]
How to enable gzip woff woff2 fonts files?

**Comment by guillaumebriday** [comment]
I think we need to add those extensions here https://github.com/rails/webpacker/blob/master/package/environments/production.js#L16

Feel free to open a PR, I'll try to do it today

**Comment by guillaumebriday** [comment]
Hope this help, please consider to close this issue 👍

**Comment by nPaul** [comment]
yes is true
woff woff2 not need to compress

**Comment by guillaumebriday** [comment]
Feel free to close your issue then 👍
