### ISSUE TITLE
confusing docs re: environment variables and dotenv

### ISSUE THREAD

**Issue by jhackett1** [rails/webpacker#2531]
hello!

i've just tried to follow the instructions [here](https://github.com/rails/webpacker/blob/master/docs/env.md_) to get some basic dotenv support up and running and i found it pretty tough.

the big code snippet for my `environment.js` file in the middle of the instructions doesn't actually seem necessary to get dotenv working - in fact it broke it for me.

should these be updated or re-worded to be more beginner-friendly?

**Comment by rossta** [comment]
These docs are removed in Webpacker 6. I added some info in another thread which I hope you'll find helpful https://github.com/rails/webpacker/issues/2846#issuecomment-752782823
