### ISSUE TITLE
Same js pack loaded multiple times

### ISSUE THREAD

**Issue by woniesong92** [rails/webpacker#2533]
I noticed from the console that the same JavaScript pack was loaded multiple times. It looks like the source file is different though: one from the actual source file and the other from the webpack bundle. This is causing an unexpected behavior when I try to render a react component in a loaded DOM.

![loaded_multiple_times](https://user-images.githubusercontent.com/2935309/79171276-75a4d000-7da6-11ea-9cbb-33caec45bfc1.png)

Can anyone explain why this is happening and what I can do to fix it?

Repro:

```
// edit.html.erb
<%= javascript_pack_tag 'SomeEdit', 'data-turbolinks-track': 'reload' %>

// SomeEdit.js
console.log("I'm loaded!")
console.log(true)
```

**Comment by jakeNiemiec** [comment]
What happens when you follow this link?
![image](https://user-images.githubusercontent.com/16782063/80777840-2263a900-8b2c-11ea-98f6-0d1242677206.png)


Try `console.warn("I'm loaded!")`, it will provide you with a stack trace. It's most likely related to WDS injected code or hot reloading.

**Comment by guillaumebriday** [comment]
Your `javascript_pack_tag` should be in your `head`.

It's loaded on your first load and reloaded when turbolinks parse the body I think.

**Comment by martinbarilik** [comment]
@woniesong92 how did you manage to solve this, i am encountering the same behaviour with javascript_pack_tag being in my show template

**Comment by matheusbsilva** [comment]
I'm facing the same issue, any update on this?
