### ISSUE TITLE
image_pack_tag with srcset does not compute relative path correctly

### ISSUE THREAD

**Issue by deepj** [rails/webpacker#2539]
Example:

```ruby
image_pack_tag('mypicture.png', srcset: { 'mypicture-2x.png' => '2x' })
```

Actual:

```html
<img src="/media/images/mypicture-7cca48e6cae66ec07b8ee0db62bbef6.png" srcset= "/images/mypicture-2x.png 2x">
```

Expected:

```html
<img src="/media/images/mypicture-7cca48e6cae66ec07b8ee0db62bbef6.png" srcset= "/media/images/mypicture-2x-9bcc3bef4c080665d829f495fabc8647.png 2x">
```

**Comment by gauravtiwari** [comment]
Ahh that doesn't look right. Could you please make a PR?

**Comment by deepj** [comment]
@gauravtiwari I looked it before posting the issue here. I'm just afraid this cannot be changed easily. Correct me if I'm wrong.

When I look at https://github.com/rails/rails/blob/e09df779283bd2ba4d887559983cecaf3fd452b1/actionview/lib/action_view/helpers/asset_tag_helper.rb#L347-L352

I guess Webpacker doesn't bypass `path_to_image`, right? To fix this would be needed to change it in Rails as well. But personally I don't have an insight into assets internals.
