### ISSUE TITLE
webpack not installed

### ISSUE THREAD

**Issue by keyboard-clacker** [rails/webpacker#2545]
Hey there! I just upgraded from webpacker 4.2.2 to 5.0.1 and when running `bundle exec rake webpacker:compile` I now get the error `webpack not installed`. I'm not sure what's changed, but I was hoping by using webpacker I did not need to install my own version of webpack, as it is declared as a production dependency of webpacker. Is there any solution to this when using yarn besides additionally adding webpack as a dependency of my application? This seems brittle, as they could easily get out of date with webpacker's internal version of webpack (even though it seems to not be getting installed).

**Comment by moubry** [comment]
I had this same issue using the Heroku buildpack for Ruby. Webpacker would work locally, but not with the buildpack. I tried adding `webpack` to my `package.json`, and that didn’t fix things.

The solution: adding the `binstub` for `bin/yarn` fixed the issue for me. It was missing from my project — and apparently the upgrade from Webpacker 4 → 5 required it to be there.

**Comment by michaelkoper** [comment]
@moubry that fixed it for me, thanks!

In case somebody needs to add this as well. This is the standard bin/yarn from rails new:

```ruby
#!/usr/bin/env ruby
APP_ROOT = File.expand_path('..', __dir__)
Dir.chdir(APP_ROOT) do
  begin
    exec "yarnpkg", *ARGV
  rescue Errno::ENOENT
    $stderr.puts "Yarn executable was not detected in the system."
    $stderr.puts "Download Yarn at https://yarnpkg.com/en/docs/install"
    exit 1
  end
end
```

**Comment by keyboard-clacker** [comment]
Oh yeah sorry I forgot to post my temporary fix! I somehow got this to work by declaring webpack as a dependency of my project, even though it was already in my node modules because of webpacker. Hopefully they don't get out of date 😂

**Comment by guillaumebriday** [comment]
Could this issue be closed?

**Comment by keyboard-clacker** [comment]
I'd put it out there that users of webpacker still should not be required to pin a webpack version in their package json, but I may be in the minority there haha

**Comment by keyboard-clacker** [comment]
There are other libraries that do this and every time I encounter an error because of this it's hours of development time lost trying to investigate 😢
