### ISSUE TITLE
webpacker generates unique hashes on ubuntu on every run.. but not on mac

### ISSUE THREAD

**Issue by 34code** [rails/webpacker#2557]
there is some inconsistency in how webpacker is generating hashes for files. 

**expected behavior**: hashes should be a function of the file content and should not change on every webpacker reload

**actual behavior**: hashes do change on every compilation without files changing on ubuntu.. not on mac (this is happening for bin/webpack and bin/webpack-dev-server)

**Comment by jakeNiemiec** [comment]
Closing in favor of related issues: https://github.com/rails/webpacker/issues/2471 https://github.com/rails/webpacker/issues/2003
