### ISSUE TITLE
5.1 introduces TypeScript property errors (too strict?)

### ISSUE THREAD

**Issue by noelrappin** [rails/webpacker#2558]
Updating a project from Webpacker 5.0.x to 5.1, and after going through all the upgrade documentation to change to babel-loader. Everything else is up to date...

I have a simple Stimulus controller, defined to start as follows:

```
import { Controller } from "stimulus"

export default class extends Controller {
  static classes = ["hidden"]
  static targets = ["filterInput", "concert"]

  hiddenClass: string
  concertTargets: HTMLElement[]
  filterInputTarget: HTMLInputElement

  // and so on
```

Works fine with Webpacker 5.0.1, in 5.1.1 now I am getting `TypeError: Cannot set property hiddenClass of #<extended> which has only a getter`

It seems as though the babel loader has put TypeScript into strict mode? Or am I missing something?

**Comment by gopeter** [comment]
Hmmm I don't think that this is more strict, since it reads the same `tsconfig.json` as `ts-loader` and does not bring it's own rules.

I found a few related issues [here](https://github.com/stimulusjs/stimulus/issues/121#issuecomment-455353044) and [here](https://github.com/stimulusjs/stimulus/issues/221).

**Comment by noelrappin** [comment]
Thanks for looking. 

Okay, it's not strict, but it is a behavior change, since the code runs fine in 5.0 and fails in 5.1.

**Comment by gopeter** [comment]
Thats true, but it's also the "right" way as you can see in the [TC39 proposal](https://tc39.es/proposal-class-fields/#sec-define-field) (got it from [this comment](https://github.com/babel/babel/issues/8280#issuecomment-403019035)). So `babel-loader` does the right thing actually.

For now, you can [fool TS](https://github.com/babel/babel/issues/8280#issuecomment-403019035).

I'm not sure if this is going to be resolved anytime soon. Here's a quote from the corresponding [babel issue](https://github.com/babel/babel/issues/7644):

> At any rate, this is a conflict between the current TC39 class properties proposal and TypeScript properties.
> 
> If you declare a property without initializing, you are still declaring the property, and so it must be initialized to undefined according to spec. The type annotation for the property is still being correctly stripped; but the property itself still exists.

**Comment by guillaumebriday** [comment]
Is this still an issue?

Feel free to reopen if needed
