### ISSUE TITLE
Correct preload of fonts/styles

### ISSUE THREAD

**Issue by zverexe** [rails/webpacker#2559]
I have such imports in my /packs/client.js
```
import (/* webpackPreload: true */ 'bootstrap/dist/css/bootstrap.css');
import (/* webpackPreload: true */ '@fortawesome/fontawesome-pro/css/all.css');
```

I added  `webpackPreload: true` as was advised here https://github.com/rails/webpacker/issues/1874#issuecomment-500936752 but it doesn't add any preload attribute and I still see warnings from Lighthouse

**Comment by jakeNiemiec** [comment]
> it doesn't add any preload attribute and I still see warnings from Lighthouse

What kind of warnings?

**Comment by guillaumebriday** [comment]
@zverexe Could you please provide your Lighthouse report please?

Do you see the preload tag in your `<head>`?
