### ISSUE TITLE
rails webpacker:compile very slow compared to bin/webpack

### ISSUE THREAD

**Issue by scottrobertson** [rails/webpacker#2564]
We have been having an issue for a while now with our production builds taking 4+ minutes, compared to ~30s locally.

I assumed until now that this was an issue with CI resources, however, I have since found that running `bin/webpack` is a huge amount faster. See below:

`bundle exec rails webpacker:compile `

```
Hash: fae915c931e9f41b0499
Version: webpack 4.42.1
Time: 211332ms
Built at: 29/04/2020 13:14:22
```

`bin/webpack`

```
Hash: 7ab04632a7b9a483ef83
Version: webpack 4.42.1
Time: 58670ms
Built at: 29/04/2020 13:16:03
```

I am clearing `tmp/cache` and `public/packs` between builds.

Any suggestions on how to debug this?

I can replicate this consistently locally, and on CI.

**Comment by scottrobertson** [comment]
Looks like no css is extracted when running bin/webpack, so that probably explains why it's slower.

Will debug some more.

**Comment by scottrobertson** [comment]
```
Hash: 0e4cfc914194c2c6e9e7
Version: webpack 4.42.1
Time: 225482ms
Built at: 04/29/2020 12:44:54 PM
```

with `extract_css` set to false, so it's not that.

**Comment by scottrobertson** [comment]
```
bin/webpack --config config/webpack/production.js
```

Is just as slow as `bundle exec rails webpacker:compile`, so it's something in our configs by the looks of it.

**Comment by dkniffin** [comment]
@scottrobertson I'm seeing this behavior on my app now. Did you track down what was causing this? Is it safe to just run `bin/webpack` instead of `bin/rails webpacker:compile`? I wonder if it's simply because it has to load up the whole Rails environment again?

**Comment by scottrobertson** [comment]
The main issue for us was we were building within a docker environment on CircleCI. Switching that to a machine instead resolved most speed issues.

**Comment by trackedsupport** [comment]
Same thing is happening for me all of a sudden, not sure what I've changed. 

But its 10 seconds vs 68 seconds.
