### ISSUE TITLE
rails assets:precompile fails silently when Node is not available

### ISSUE THREAD

**Issue by dmolesUC** [rails/webpacker#2570]
## Steps to reproduce

- Create a git repository for a Rails 6 app using Webpacker 
- On a system without Node installed, clone the repository
- Run `bundle install`
- Run `rails assets:precompile`

## Expected

- `rails assets:precompile` fails, with information that allows me to figure out that the problem is that Node/NPM is not available

## Actual

- `rails assets:precompile` does nothing, but appears to succeed
- `rails webpacker:compile` fails with 

   ```sh
   sh: node: command not found
   sh: nodejs: command not found
   Node.js not installed. Please download and install Node.js 
   https://nodejs.org/en/download/
   ```
- installing Node (e.g. with NVM: `source /usr/local/opt/nvm/nvm.sh && nvm use stable`)
  allows `rails assets:precompile` to proceed normally with `yarn install…` etc.

**Comment by jakeNiemiec** [comment]
NVM stands for "**n**ode **v**ersion **m**anager", this installs node (which happens to come with npm).

Webpacker will not work without Node >=10, this is why it said `nodejs: command not found Node.js not installed`. Hope that helps.

**Comment by dmolesUC** [comment]
@jakeNiemiec Yes, I totally get that. What I'm complaining about is that `assets:precompile` hides the error.

**Comment by kolesa** [comment]
@dmolesUC Is your idea to add a message something like 'npm is not installed' when a user is trying to execute `rails assets:precompile` without installed npm?

**Comment by dmolesUC** [comment]
@kolesa I haven't looked at the code, but my assumption is that `assets:precompile` is calling `webpacker:compile`, `webpacker:compile` is failing, but the failure message is being suppressed. I don't think any new failure message needs to be added — I would expect to see the same failure I get when I call `webpacker:compile` directly.

**Comment by jakeNiemiec** [comment]
Webpacker does not check to see if npm is available, [but it _will_ check for yarn & node](https://github.com/rails/webpacker/blob/3eecc5c0596a276eb36cc84bb30829a584b6b1c0/lib/tasks/webpacker/verify_install.rake#L5). Just make sure to follow [the installation section of the readme](https://github.com/rails/webpacker#installation).

**Comment by dmolesUC** [comment]
@jakeNiemiec I've updated the ticket to say "Node" instead of "NPM", if that helps. Again, if `webpacker:compile` is supposed to be called as a side effect of `assets:precompile`, I don't think its error messages should be suppressed.

**Comment by jakeNiemiec** [comment]
When you ran `bundle install`, did you also remember to run `bundle exec rake webpacker:install`?

**Comment by dmolesUC** [comment]
It's run by default as part of generating a new Rails 6 app. I just reproduced the problem with a new app from scratch:

## steps to reproduce

1. ensure `node` and `yarn` are not available
2. run:

   ```sh
   rails new --no-skip-javascript --no-skip-webpack-install --no-rc myapp
   ```

3. note `webpacker:install` is run as part of the setup process
4. cd to `myapp`
5. disable `check_yarn_integrity` in `config/webpacker.yml`
6. ensure `node` and `yarn` are not available
7. run `rails assets:precompile`

## expected

- error message

## actual

- no error message

---

Obviously installing / uninstalling node and yarn is not a realistic scenario, but it is realistic to generate an app on a machine that has node and yarn, commit it to version control, and later clone it on a machine that doesn't.

**Comment by jakeNiemiec** [comment]
> webpacker:install is run as part of the setup process

This is where the error message should be displayed, can you confirm that it is missing (or provide the output)?

**Comment by dmolesUC** [comment]
@jakeNiemiec Sorry, there was a typo in my reproduction instructions -- fixed now. Step 1 should have said "ensure `node` and `yarn` **are** available" -- in which case there is no error message. 

Again, a more realistic scenario than doing this on the same machine is creating an app on a machine that does have yarn installed, then cloning the repo on one that doesn't. Sample repo here: https://github.com/dmolesUC/webpacker-2570

**Comment by justin808** [comment]
@dmolesUC please submit a PR if you want to improve the error messages.
