### ISSUE TITLE
Using React.Lazy to code split components

### ISSUE THREAD

**Issue by obedparla** [rails/webpacker#2579]
Hi 👋. 

I'm struggling to be able to lazy load components in my app. I'm running `@rails/webpacker: 4.0.7`. 

I pretty much have the default config that comes with Webpacker, plus I added `splitChunks` to `environment.js` for webpack:

```
const { environment } = require('@rails/webpacker');
const webpack = require('webpack');
environment.splitChunks();
module.exports = environment;
```

And I'm trying to get lazy load of a component like this (simplified code, using React Router v6):

```
const Vouchers = React.lazy(() =>
  import('./vouchers'),
);

const App => () => {
return (
       <Suspense fallback={<Spinner />}>
          <Routes>
            <Route path='vouchers/*' element={<Vouchers />} />
          </Routes>
        </Suspense>
)}
```

Whenever I load the `App` component I can see Suspense's spinner and then the component shows up, but there's no new bundle/chunk in the network tab. 

Checking my chunks, I can find the `vouchers` component code being part of one of the chunks, which shouldn't be the case since it should be an async chunk.

Any clue as to how to get `React.lazy` to work? I'm happy to try stuff around.

Update: I checked the documentation for [es6](https://github.com/rails/webpacker/blob/master/docs/es6.md) and it includes an example for Vue but not for React. I'm assuming Webpack supports lazy loading and It's an issue with my setup? 🤔

**Comment by rossta** [comment]
What version of React are you on? What’s in your ‘./vouchers’ file?

**Comment by obedparla** [comment]
Thank you for answering @rossta 🙏 . 

`vouchers` is a React component with a default export like you'd expect to do it for `React.lazy`. 

I tried to do this as well without using the Router, instead rendering it based on state, something like (I just wrote this, please ignore any syntax errors or such)

```javascript
const Vouchers = React.lazy(() =>
  import('./vouchers'),
);

const Component = () => {
 const [state, setState] = useState(false)

 return (
   <button onClick={() => setState(true)}>Click me</button>
  <React.Suspense fallback={<div>Loading ... </div>}
      {state && <Vouchers />}
  </React.Suspense>
 )
}
```

The above should load the Vouchers component on button click, but instead, it shows right away. I checked the network tab and confirmed I got nothing new being loaded. I tried multiple times, disabling cache, and disabled the network altogether. The component still showed up right away, which means it's loaded in the bundle rather than asked on-request.

I also disabled `splitChunks` to discard if it was connected to it.

Do you have any idea what I could try out?

**Comment by rossta** [comment]
I think you want `{state && ... }` to surround the `React.Suspense` component instead.

**Comment by obedparla** [comment]
Hey, sorry for the super late reply.

I checked this and that's not the case. Even if `Voucher` was rendered right away, `React.lazy` would still need to load it and Suspense would show the `loading`. 

Do you have any example anywhere where you know React lazy is loading? I'm not sure if it's my config (nearly the default one that comes with Webpacker) or a bug in Webpacker itself.

**Comment by obedparla** [comment]
Further digging into this, I discovered that I can create `chunks` for `node modules` but not for components. 

This works:
```
  React.useEffect(() => {
    // node module
    import('leaflet').then(({ default: def }) => leafletSet(def));
  }, []);
```

While this doesn't:
```
  React.useEffect(() => {
   // React component. I also tried `Vouchers.jsx` and other variations
    import('./vouchers/Vouchers').then(
      ({ default: def }) => (Vouchers = def),
    );
  }, []);
```

I was thinking It may be related to how Webpacker tests Webpack to include the javascript files in the `javascript` folder?

**Comment by rossta** [comment]
I'm not entirely sure what you're observing or not observing that leads you to your conclusions. It may help to know what's exported in Vouchers and whether it's also imported elsewhere.

> Do you have any example anywhere where you know React lazy is loading?

I'm not entirely sure what you mean by this. It may help to name the import chunk so it's easier to observe in the DevTools console. To do this use the magic comment "webpackChunkName", i.e., `import(/* wepackChunkName: vouchers */ './vouchers/Vouchers')`

> I discovered that I can create chunks for node modules but not for components.

I'd be surprised if this were the case. I don't know of any configuration that would explicitly disable dynamic imports for node_modules vs components. There may be some behavior specific to the vouchers module, but again, I'm not entirely sure what you're observing.

**Comment by guillaumebriday** [comment]
Is this issue still relevant?

Feel free to close if not 👍

**Comment by obedparla** [comment]
Closing it now. I never fully figured it out but I no longer work with Webpacker. Thank you for your help 🙏

**Comment by eni9889** [comment]
@obedparla @guillaumebriday I have the same issue. No chunks get generated when using React.lazy

**Comment by obedparla** [comment]
> Closing it now. I never fully figured it out but I no longer work with Webpacker. Thank you for your help 🙏

Never figured it out 🤷‍♂️. I no longer work with Rails.
