### ISSUE TITLE
How do you include polyfills in each entry point?

### ISSUE THREAD

**Issue by poloka** [rails/webpacker#258]
My original webpack code I was able to include es6-shim and array-includes polyfills and my Promise code worked.  After converting to utilize webpacker, I'm getting errors around 
```
TypeError: this.JSONRPC.request(...).then is not a function
```
The library that I'm utilizing is [jsonrpc-dispatch](https://github.com/cerner/jsonrpc-dispatch).  

Was reviewing the config and the entry is dictated I tried adding my polyfills to my app/javascript/packs/application.js
```
require('es6-shim');
require('array-includes');
require('application');
```
But that didn't seem to work either.  Wondering if I'm mistaking how to include polyfills into my packed code?

**Comment by poloka** [comment]
Issue was caused by my own conflicting modules overwriting each other because I had a dependency for 1.0 and 2.0 in the same project.  corrected that collision and issue was resolved.  The inclusion of the polyfills was correct in adding it to the /packs/application.js.

**Comment by gauravtiwari** [comment]
@poloka create a pollyfills.js file outside packs and then import it into particular pack where you need it inside packs/* directory. For ex - if you need packs/application.js to have this pollyfil then - 

```js
import '../polyfills.js'
```

and your polyfills.js can have all the relevant pollyfills - 

```js
import('es6-shim');
import('array-includes');
```

Also, I guess the error you are getting is related to JSONRPC. Have you included that inside your pack?

```js
import JSONRPC from 'jsonrpc-dispatch'
```

Also you may wanna add this too inside polyfills.js

```
yarn add promise
```

```
if (typeof Promise === 'undefined') {
  require('promise/lib/rejection-tracking').enable()
  window.Promise = require('promise/lib/es6-extensions.js')
}
```

**Comment by gauravtiwari** [comment]
Or just use this service that adds all required polyfills for you - [https://polyfill.io/v2/docs/](https://polyfill.io/v2/docs/)
