### ISSUE TITLE
Multi-file entry point

### ISSUE THREAD

**Issue by radar** [rails/webpacker#2584]
The changelog here: https://github.com/rails/webpacker/blob/master/CHANGELOG.md#500---2020-03-22 Mentions that you can do multi-file entrypoints but doesn’t specify where that code goes.

Is there some documentation that I can read that shows me where that code should go?

**Comment by rossta** [comment]
I opened a PR to address this issue with regards to the most common use case (I think): bundling a JS and CSS pack as part of the same entry point. https://github.com/rails/webpacker/pull/2597/files#diff-01d310e8cacb961dc603124012408be2R21-R30

The default Webpacker config does not support arbitrary lists of files to be grouped as a multi-file entry point (as in a raw webpack config), but will bundle "packs" of the same canonical name and different file extensions as a single entry point.
