### ISSUE TITLE
Force SockJS client to perform a Turbolinks page reload

### ISSUE THREAD

**Issue by michaelbaudino** [rails/webpacker#2586]
Hi there,

On a fresh Rails 6 install, we are using the following snippet in `config/webpack/development.js` to ask the browser to reload the page when we modify a Rails view (adapted from [this comment from a Webpack dev](https://github.com/webpack/webpack-dev-server/issues/1271#issuecomment-359817498)):

```javascript
const chokidar = require('chokidar')
environment.config.devServer.before = (_app, server) => {
  chokidar.watch([
    'config/locales/*.yml',
    'app/views/**/*.erb',
    'app/views/**/*.haml',
    'app/views/**/*.slim'
  ]).on('change', () => server.sockWrite(server.sockets, 'content-changed'))
}
```

Does anyone know how we could ask the browser to perform this page reload using Turbolinks, rather than this full page reload? Is there a way to add a handle for a custom event (other than `content-changed`) to SockJS client in our Webpacker configuration?

Thanks a lot in advance.

**Comment by guillaumebriday** [comment]
Thanks for the example @michaelbaudino! 🙏 

I'm not sure that's possible for Turbolinks though :/

I'm closing because it's not directly related to Webpacker.
