### ISSUE TITLE
Switching between using webpack-dev-server and only rails server for development?

### ISSUE THREAD

**Issue by kochalex** [rails/webpacker#2588]
I am running into a minor local development issue where switching to using  just `bundle exec rails server` (with a default webpacker configuration) after having used `webpack-dev-server` doesn't work seamlessly - assets are not compiled in this scenario without taking extra actions.  It fixable by running `bundle exec rails webpacker:clobber` (or similar to force a recompilation)

If `webpacker-dev-server` and `rails server` have been run and closed, ensuring a `manifest.json` & the compilation_digest file exists, and no other files have changed, webpacker does not recompile when switching to just using `rails server`.  The `stale?` check in the compiler that shows no files have changed [1] so it thinks nothing needs to be compiled.  However, the asset files do not exist in `public/packs` at this point and 404.

[1] https://github.com/rails/webpacker/blob/1b2ba329e429131e2dc960aefcce1a2d343f0115/lib/webpacker/compiler.rb#L22

Again, it's not a huge deal, but feels like a minor bug.

**Comment by justin808** [comment]
We have some more descriptive issues around what you're seeing.
