### ISSUE TITLE
Compilation Failed with warnings

### ISSUE THREAD

**Issue by PathaShiva** [rails/webpacker#2590]
**Please help me find what is the issue**

Compilation failed:
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`

Hash: 5fc8346583041c60c71f
Version: webpack 4.41.2
Time: 63373ms
Built at: 05/15/2020 4:44:37 AM
                                                   Asset       Size  Chunks                                Chunk Names
                        css/platform-bundle-a1af2e96.css    702 KiB       1  [emitted] [immutable]  [big]  platform-bundle
                     css/platform-bundle-a1af2e96.css.gz     99 KiB          [emitted]
                  css/standard-external-app-b87b5baf.css    641 KiB       2  [emitted] [immutable]  [big]  standard-external-app
               css/standard-external-app-b87b5baf.css.gz   85.7 KiB          [emitted]
                 js/external-app-0a075c7b433854d2f513.js    599 KiB       0  [emitted] [immutable]  [big]  external-app
         js/external-app-0a075c7b433854d2f513.js.LICENSE   1.08 KiB          [emitted]
              js/external-app-0a075c7b433854d2f513.js.gz    152 KiB          [emitted]
             js/external-app-0a075c7b433854d2f513.js.map   1.58 MiB       0  [emitted] [dev]               external-app
          js/external-app-0a075c7b433854d2f513.js.map.gz    383 KiB          [emitted]              [big]
              js/platform-bundle-e35e05fd7bbaf44e7bef.js    4.5 MiB       1  [emitted] [immutable]  [big]  platform-bundle
      js/platform-bundle-e35e05fd7bbaf44e7bef.js.LICENSE   4.82 KiB          [emitted]
           js/platform-bundle-e35e05fd7bbaf44e7bef.js.gz   1.12 MiB          [emitted]              [big]
          js/platform-bundle-e35e05fd7bbaf44e7bef.js.map   17.2 MiB       1  [emitted] [dev]               platform-bundle
       js/platform-bundle-e35e05fd7bbaf44e7bef.js.map.gz   3.95 MiB          [emitted]              [big]
        js/standard-external-app-89fc76595b9ba63ffed7.js   2.51 MiB       2  [emitted] [immutable]  [big]  standard-external-app
js/standard-external-app-89fc76595b9ba63ffed7.js.LICENSE   3.29 KiB          [emitted]
     js/standard-external-app-89fc76595b9ba63ffed7.js.gz    667 KiB          [emitted]              [big]
    js/standard-external-app-89fc76595b9ba63ffed7.js.map   9.14 MiB       2  [emitted] [dev]               standard-external-app
 js/standard-external-app-89fc76595b9ba63ffed7.js.map.gz    2.2 MiB          [emitted]              [big]
                                           manifest.json   1.78 KiB          [emitted]
                                        manifest.json.gz  402 bytes          [emitted]
                      media/icons/dxicons-1286a19f.woff2   11.6 KiB          [emitted]
                        media/icons/dxicons-147eb6fe.ttf   27.7 KiB          [emitted]
                     media/icons/dxicons-147eb6fe.ttf.gz   14.5 KiB          [emitted]
                       media/icons/dxicons-2b145cef.woff   14.6 KiB          [emitted]
                      media/images/logo-old-6a69cce6.png   7.61 KiB          [emitted]
                    media/images/logo-small-53649cdc.png   2.75 KiB          [emitted]
Entrypoint external-app [big] = js/external-app-0a075c7b433854d2f513.js js/external-app-0a075c7b433854d2f513.js.map
Entrypoint platform-bundle [big] = css/platform-bundle-a1af2e96.css js/platform-bundle-e35e05fd7bbaf44e7bef.js js/platform-bundle-e35e05fd7bbaf44e7bef.js.map
Entrypoint standard-external-app [big] = css/standard-external-app-b87b5baf.css js/standard-external-app-89fc76595b9ba63ffed7.js js/standard-external-app-89fc76595b9ba63ffed7.js.map
  [13] ./app/javascript/constants/PramataTrackerInfo.js 2.73 KiB {0} {1} {2} [built]
  [45] ./app/javascript/constants/PramataAppConstants.js 907 bytes {1} {2} [built]
 [501] ./app/javascript/bundles/Platform/components/Root/App/SideBar.jsx + 3 modules 25 KiB {1} [built]
       |    4 modules
 [718] ./app/javascript/bundles/Platform/components/Root/App/SolutionForm.jsx + 198 modules 1.47 MiB {1} [built]
       | ./app/javascript/lib/ResizeSensor.js 4.82 KiB [built]
       |     + 198 hidden modules
 [719] ./app/javascript/bundles/Platform/components/Root/App.jsx + 2 modules 20.7 KiB {1} [built]
       | ./app/javascript/react-utils/UserOnboardingGuide.jsx 7.41 KiB [built]
       | ./app/javascript/bundles/Platform/contexts/UserFeatureTourContext.jsx 5.73 KiB [built]
       |     + 1 hidden module
 [815] ./app/javascript/bundles/Platform/components/Root/App/UsersContainer/UserFormContainer.jsx + 13 modules 39.3 KiB {1} [built]
       |    14 modules
 [816] ./app/javascript/bundles/Platform/components/Root/App/UsersContainer.jsx + 12 modules 44.9 KiB {1} [built]
       |    13 modules
 [817] ./app/javascript/bundles/Platform/components/Root/App/SearchResultsContainer.jsx + 6 modules 30.7 KiB {1} [built]
       |    7 modules
 [818] ./app/javascript/bundles/Platform/components/Root/App/SearchResultsContainer/CommercialTermsResults.jsx + 1 modules 8.49 KiB {1} [built]
       | ./app/javascript/react-utils/ContractLink.jsx 2.73 KiB [built]
       |     + 1 hidden module
[1348] ./app/javascript/packs/external-app.js 704 bytes {0} [built]
[1358] ./app/javascript/bundles/ExternalApp/components sync ^\.\/.*$ 210 bytes {0} [built]
[1359] ./app/javascript/packs/platform-bundle.js 701 bytes {1} [built]
[1360] ./app/javascript/bundles/Platform/components sync ^\.\/.*$ 2.52 KiB {1} [built]
[1590] ./app/javascript/packs/standard-external-app.js 712 bytes {2} [built]
[1591] ./app/javascript/bundles/StandardExternalApp/components sync ^\.\/.*$ 406 bytes {2} [built]
    + 1807 hidden modules

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets:
  js/external-app-0a075c7b433854d2f513.js (599 KiB)
  css/platform-bundle-a1af2e96.css (702 KiB)
  js/platform-bundle-e35e05fd7bbaf44e7bef.js (4.5 MiB)
  css/standard-external-app-b87b5baf.css (641 KiB)
  js/standard-external-app-89fc76595b9ba63ffed7.js (2.51 MiB)
  js/external-app-0a075c7b433854d2f513.js.map.gz (383 KiB)
  js/standard-external-app-89fc76595b9ba63ffed7.js.gz (667 KiB)
  js/platform-bundle-e35e05fd7bbaf44e7bef.js.gz (1.12 MiB)
  js/standard-external-app-89fc76595b9ba63ffed7.js.map.gz (2.2 MiB)
  js/platform-bundle-e35e05fd7bbaf44e7bef.js.map.gz (3.95 MiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  external-app (599 KiB)
      js/external-app-0a075c7b433854d2f513.js
  platform-bundle (5.19 MiB)
      css/platform-bundle-a1af2e96.css
      js/platform-bundle-e35e05fd7bbaf44e7bef.js
  standard-external-app (3.13 MiB)
      css/standard-external-app-b87b5baf.css
      js/standard-external-app-89fc76595b9ba63ffed7.js

WARNING in webpack performance recommendations:
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--6-1!node_modules/postcss-loader/src/index.js??ref--6-2!app/javascript/bundles/Platform/components/Root/App.css:
    Entrypoint mini-css-extract-plugin = *
       2 modules
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--6-1!node_modules/postcss-loader/src/index.js??ref--6-2!app/javascript/bundles/Platform/components/Root/App/AppHeader.css:
    Entrypoint mini-css-extract-plugin = *
       2 modules
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--6-1!node_modules/postcss-loader/src/index.js??ref--6-2!app/javascript/bundles/Platform/components/Root/App/AppHeader/SearchSugesstion.css:
    Entrypoint mini-css-extract-plugin = *
       2 modules
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--6-1!node_modules/postcss-loader/src/index.js??ref--6-2!app/javascript/bundles/Platform/components/Root/App/SearchResultsContainer/SearchResultsSection.css:
    Entrypoint mini-css-extract-plugin = *
       2 modules
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--6-1!node_modules/postcss-loader/src/index.js??ref--6-2!app/javascript/bundles/Platform/components/Root/App/SideBar.css:
    Entrypoint mini-css-extract-plugin = *
       2 modules
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--6-1!node_modules/postcss-loader/src/index.js??ref--6-2!app/javascript/bundles/Platform/components/Root/App/SolutionContainer.css:
    Entrypoint mini-css-extract-plugin = *
       2 modules
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--6-1!node_modules/postcss-loader/src/index.js??ref--6-2!app/javascript/bundles/Platform/components/Root/App/SolutionContainer/Affliations.css:
    Entrypoint mini-css-extract-plugin = *
       2 modules
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--6-1!node_modules/postcss-loader/src/index.js??ref--6-2!app/javascript/bundles/Platform/components/Root/App/SolutionForm.css:
    Entrypoint mini-css-extract-plugin = *
       2 modules
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--6-1!node_modules/postcss-loader/src/index.js??ref--6-2!app/javascript/bundles/Platform/components/Root/App/UserManagement.css:
    Entrypoint mini-css-extract-plugin = *
       2 modules
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--6-1!node_modules/postcss-loader/src/index.js??ref--6-2!app/javascript/bundles/StandardExternalApp/components/StdExternalApp.css:
    Entrypoint mini-css-extract-plugin = *
       2 modules
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--6-1!node_modules/postcss-loader/src/index.js??ref--6-2!app/javascript/react-utils/DashBoard.css:
    Entrypoint mini-css-extract-plugin = *
    [0] ./node_modules/css-loader/dist/cjs.js??ref--6-1!./node_modules/postcss-loader/src??ref--6-2!./app/javascript/react-utils/DashBoard.css 766 bytes {0} [built]
        + 1 hidden module
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--6-1!node_modules/postcss-loader/src/index.js??ref--6-2!app/javascript/react-utils/Documents/DocumentFamily/DocumentFamily.css:
    Entrypoint mini-css-extract-plugin = *
    [0] ./node_modules/css-loader/dist/cjs.js??ref--6-1!./node_modules/postcss-loader/src??ref--6-2!./app/javascript/react-utils/Documents/DocumentFamily/DocumentFamily.css 20.3 KiB {0} [built]
        + 1 hidden module
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--6-1!node_modules/postcss-loader/src/index.js??ref--6-2!app/javascript/react-utils/DownloadProgress.css:
    Entrypoint mini-css-extract-plugin = *
    [0] ./node_modules/css-loader/dist/cjs.js??ref--6-1!./node_modules/postcss-loader/src??ref--6-2!./app/javascript/react-utils/DownloadProgress.css 1.7 KiB {0} [built]
        + 1 hidden module
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--6-1!node_modules/postcss-loader/src/index.js??ref--6-2!app/javascript/react-utils/Pdf.css:
    Entrypoint mini-css-extract-plugin = *
    [0] ./node_modules/css-loader/dist/cjs.js??ref--6-1!./node_modules/postcss-loader/src??ref--6-2!./app/javascript/react-utils/Pdf.css 522 bytes {0} [built]
        + 1 hidden module
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--6-1!node_modules/postcss-loader/src/index.js??ref--6-2!app/javascript/react-utils/PramataModal.css:
    Entrypoint mini-css-extract-plugin = *
    [0] ./node_modules/css-loader/dist/cjs.js??ref--6-1!./node_modules/postcss-loader/src??ref--6-2!./app/javascript/react-utils/PramataModal.css 498 bytes {0} [built]
        + 1 hidden module
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--6-1!node_modules/postcss-loader/src/index.js??ref--6-2!app/javascript/react-utils/TermDataElement/TermDataElement.css:
    Entrypoint mini-css-extract-plugin = *
    [0] ./node_modules/css-loader/dist/cjs.js??ref--6-1!./node_modules/postcss-loader/src??ref--6-2!./app/javascript/react-utils/TermDataElement/TermDataElement.css 1.59 KiB {0} [built]
        + 1 hidden module
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--6-1!node_modules/postcss-loader/src/index.js??ref--6-2!app/javascript/react-utils/Title.css:
    Entrypoint mini-css-extract-plugin = *
    [0] ./node_modules/css-loader/dist/cjs.js??ref--6-1!./node_modules/postcss-loader/src??ref--6-2!./app/javascript/react-utils/Title.css 771 bytes {0} [built]

        + 1 hidden module
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--6-1!node_modules/postcss-loader/src/index.js??ref--6-2!app/javascript/react-utils/UserOnboardingGuide.css:
    Entrypoint mini-css-extract-plugin = *
    [0] ./node_modules/css-loader/dist/cjs.js??ref--6-1!./node_modules/postcss-loader/src??ref--6-2!./app/javascript/react-utils/UserOnboardingGuide.css 5.14 KiB {0} [built]
        + 1 hidden module
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--6-1!node_modules/postcss-loader/src/index.js??ref--6-2!node_modules/devextreme/dist/css/dx.common.css:
    Entrypoint mini-css-extract-plugin = *
       2 modules
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--6-1!node_modules/postcss-loader/src/index.js??ref--6-2!node_modules/devextreme/dist/css/dx.light.css:
    Entrypoint mini-css-extract-plugin = *
       6 modules
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--6-1!node_modules/postcss-loader/src/index.js??ref--6-2!node_modules/handsontable/dist/handsontable.full.css:
    Entrypoint mini-css-extract-plugin = *
       2 modules
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--6-1!node_modules/postcss-loader/src/index.js??ref--6-2!node_modules/react-slidedown/lib/slidedown.css:
    Entrypoint mini-css-extract-plugin = *
       2 modules
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--6-1!node_modules/postcss-loader/src/index.js??ref--6-2!node_modules/react-splitter-layout/lib/index.css:
    Entrypoint mini-css-extract-plugin = *
       2 modules
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--6-1!node_modules/postcss-loader/src/index.js??ref--6-2!node_modules/react-table/react-table.css:
    Entrypoint mini-css-extract-plugin = *
       2 modules
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--6-1!node_modules/postcss-loader/src/index.js??ref--6-2!node_modules/react-tippy/dist/tippy.css:
    Entrypoint mini-css-extract-plugin = *
       2 modules

**Comment by cintrzyk** [comment]
@PathaShiva take a look at https://github.com/postcss/autoprefixer/issues/1184 might be helpful :)

**Comment by guillaumebriday** [comment]
it seems to be a warning not an error.

Consider using the `insert code` button next time 👍
