### ISSUE TITLE
How to use the picture element in webpacker

### ISSUE THREAD

**Issue by y-yudai** [rails/webpacker#2599]
### Question
How can I use the picture element with the webpacker?

### Context
I'm considering implementing this in the picture element to support responsive images, I need to enter the image path of image_pack_tag in srcset of source, is there a good way to do this?
Is there any other way to write this kind of code?

I looked at the documentation and couldn't find anything that outputs image_pack_path or a picture tag.

### Code
```Controller
def image_pack_path(path)
  view_context.asset_pack_path "media/images/#{path}"
end
```

```view
picture
  source srcset=image_pack_path('/xxx/xxx.png') media="(max-width:640px)"
  image_pack_tag('/xxx/xxx.png')
```

**Comment by guillaumebriday** [comment]
You can find the related documentation here: https://github.com/rails/webpacker/blob/5-x-stable/docs/assets.md#link-in-your-rails-views

You should be go to go with `image_pack_tag` and `image_pack_path`
