### ISSUE TITLE
Are you open to built-in support for Vue?

### ISSUE THREAD

**Issue by chrisvfritz** [rails/webpacker#26]
Just saw the [built-in React support](https://github.com/rails/webpacker/blob/master/lib/tasks/webpacker.rake#L25-L50). Would you be open to a PR adding similar support for Vue?

**Comment by Nitrino** [comment]
@chrisvfritz here is the answer to your question #20
Also already have PR #25

**Comment by chrisvfritz** [comment]
Ouch - sorry for missing that. I guess that's what happens when you open source passed 2am. 😬
