### ISSUE TITLE
Can't get sourcemaps in production?

### ISSUE THREAD

**Issue by rainyday** [rails/webpacker#260]
I've tried adding `devtool: 'sourcemap'` to the production.js file but I'm still not getting any sourcemaps outputted in the compiled javascript. Am I missing a step?

**Comment by p0wl** [comment]
You have to tell uglifyjs that you want sourcemaps: https://github.com/webpack/webpack/issues/2704#issuecomment-228860162

**Comment by gauravtiwari** [comment]
@rainyday As @p0wl suggested, this should fix the issue for you 👍 

```js
devtool: 'sourcemap',
new webpack.optimize.UglifyJsPlugin({
    sourceMap: true
 })
```

**Comment by rainyday** [comment]
Thanks, that worked!

**Comment by gauravtiwari** [comment]
Document this in README/guide - #372

**Comment by tavelli** [comment]
@gauravtiwari do you mean?
````javascript
devtool: 'source-map'
