### ISSUE TITLE
Update node-sass to 4.14.1 to fix NPM advisory 1500

### ISSUE THREAD

**Issue by jaredbeck** [rails/webpacker#2600]
- https://www.npmjs.com/advisories/1500
- https://github.com/sass/node-sass/issues/2912

If this is as simple as editing `package.json` and running `yarn`, I'm happy to make a PR.

It might also be a good time to discuss relaxing the version constraint, eg. `^4.14` instead of `^4.14.1`?

**Comment by SkipKayhil** [comment]
Fixed in #2609 ?
