### ISSUE TITLE
Question: Shouldn't the default value in test.js be test?

### ISSUE THREAD

**Issue by nickytonline** [rails/webpacker#2602]
Hi and thanks for the webpacker project. 👏 

Quick question. Shouldn't [line 1](https://github.com/rails/webpacker/blob/master/lib/install/config/webpack/test.js#L1) of test.js be `process.env.NODE_ENV = process.env.NODE_ENV || 'test'` ?

**Comment by guillaumebriday** [comment]
see https://github.com/rails/webpacker/pull/3059#issuecomment-863971069
