### ISSUE TITLE
require .js from another gem

### ISSUE THREAD

**Issue by thebravoman** [rails/webpacker#2603]
Our host app is requiring a few gems that have js in them. These are not js libraries that you could get from npm. These are gems internal to our organization that are rails engines and they have views, controller, models and much more. They also have js files. 

With sprockets they were all just in the assets.paths and sprockets was doing its magic with '//= require' But now with webpacker it is not clear for me how this js files should be included in the application.js. They are not located int he app/javascript/ folder of the host app. They are scattered in app/assets/javascript/ and vendor/assets/javascript/ folders of other gems.

I think it would be good to add such documentation to the README. Is this even possible or all the JS are expected to live in the host app in the app/javascript/packs folder?

**Comment by thebravoman** [comment]
Trying migrating application.js to application.js.erb and importing with 
```
import "<%= File.join(Gem.loaded_specs['my_gem'].full_gem_path, 'app', 'assets', 'javascript', 'fc', 'main', 'custom.js') %>";
```
Where custom.js is a js file coming from another gem and it says

```
ERROR in ./app/javascript/packs/application.js.erb
Module not found: Error: Can't resolve '/home/user/my_gem/app/assets/javascript/fc/main/custom.js' in '/home/user/host_app/app/javascript/packs'
 @ ./app/javascript/packs/application.js.erb 20:0-100

```

**Comment by guillaumebriday** [comment]
Hum if the code is not available as npm package, you should still use the Asset Pipeline.

Mixing Webpacker and Sprockets code should be avoided. But you can use Webpacker and the Asset Pipeline side by side
