### ISSUE TITLE
Is it possible to use Quasar framework in webpacker?

### ISSUE THREAD

**Issue by zac-chen** [rails/webpacker#2616]
I am currently working on a project in Ruby on Rails and I am using webpacker to integrate front end with Vue JS, however I want to use Quasar framework in my view and it seems there's no way to add this framework in webpacker which can support single file component. I want to know is it possible add Quasar framework in webpacker?

**Comment by guillaumebriday** [comment]
Quasar comes with its own internal CLI. I don't think you can install as it through Webpack (and by extension Webpacker)

**Comment by uifox** [comment]
@zac-chen Have you tried the ["CDN - UMD" install](https://quasar.dev/start/umd)? It may work with webpacker.
