### ISSUE TITLE
Small issue in documentation referencing how to lookup additional modules [documentation bug]

### ISSUE THREAD

**Issue by myyellowshoe** [rails/webpacker#2620]
Found a small issue in the docs. Looks like `additional_paths` was changed to `resolved_paths` but the documentation wasn't updated accordingly. When I used `resolved_paths` it worked great.

**In the main documentation it states:**
If you are adding Webpacker to an existing app that has most of the assets inside app/assets or inside an engine, and you want to share that with webpack modules, you can use the additional_paths option available in config/webpacker.yml. This lets you add additional paths that webpack should lookup when resolving modules:

```
additional_paths: ['app/assets']
```

**Its actually correct in the webpacker.yml, and mentions `resolved_paths`**
```
 # Additional paths webpack should lookup modules
 # ['app/assets', 'engine/foo/app/assets']
  resolved_paths: []
```

Happy to put a PR for this verbage update.

**Comment by guillaumebriday** [comment]
It has been fixed. Thanks for reporting
