### ISSUE TITLE
error al cargar en heroku, me ayudan porfa. 

### ISSUE THREAD

**Issue by emersonxinay** [rails/webpacker#2621]
MacBook-Air-de-Emerson:hazukionline2 emerson$ git push heroku master
Enumerating objects: 843, done.
Counting objects: 100% (843/843), done.
Delta compression using up to 4 threads
Compressing objects: 100% (385/385), done.
Writing objects: 100% (843/843), 4.91 MiB | 574.00 KiB/s, done.
Total 843 (delta 411), reused 817 (delta 397)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote:  !     Warning: Multiple default buildpacks reported the ability to handle this app. The first buildpack in the list below will be used.
remote: 			Detected buildpacks: Ruby,Node.js
remote: 			See https://devcenter.heroku.com/articles/buildpacks#buildpack-detect-order
remote: -----> Ruby app detected
remote: -----> Installing bundler 2.0.2
remote: -----> Removing BUNDLED WITH version in the Gemfile.lock
remote: -----> Compiling Ruby/Rails
remote: -----> Using Ruby version: ruby-2.6.3
remote: -----> Installing dependencies using bundler 2.0.2
remote:        Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
remote:        Your Gemfile lists the gem pg (>= 0.18, < 2.0) more than once.
remote:        You should probably keep only one of them.
remote:        Remove any duplicate entries and specify the gem only once (per group).
remote:        While it's not a problem now, it could cause errors if you change the version of one of them later.
remote:        The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
remote:        Fetching gem metadata from https://rubygems.org/............
remote:        Fetching rake 13.0.1
remote:        Installing rake 13.0.1
remote:        Fetching concurrent-ruby 1.1.6
remote:        Fetching minitest 5.14.0
remote:        Fetching thread_safe 0.3.6
remote:        Installing thread_safe 0.3.6
remote:        Installing minitest 5.14.0
remote:        Installing concurrent-ruby 1.1.6
remote:        Fetching builder 3.2.4
remote:        Installing builder 3.2.4
remote:        Fetching erubi 1.9.0
remote:        Installing erubi 1.9.0
remote:        Fetching mini_portile2 2.4.0
remote:        Fetching crass 1.0.6
remote:        Installing mini_portile2 2.4.0
remote:        Installing crass 1.0.6
remote:        Fetching rack 2.2.2
remote:        Fetching nio4r 2.5.2
remote:        Installing nio4r 2.5.2 with native extensions
remote:        Installing rack 2.2.2
remote:        Fetching websocket-extensions 0.1.4
remote:        Installing websocket-extensions 0.1.4
remote:        Fetching mini_mime 1.0.2
remote:        Installing mini_mime 1.0.2
remote:        Fetching method_source 1.0.0
remote:        Fetching formtastic_i18n 0.6.0
remote:        Installing method_source 1.0.0
remote:        Installing formtastic_i18n 0.6.0
remote:        Fetching thor 1.0.1
remote:        Fetching kaminari-core 1.2.0
remote:        Installing kaminari-core 1.2.0
remote:        Installing thor 1.0.1
remote:        Fetching arel 9.0.0
remote:        Fetching ffi 1.12.2
remote:        Installing arel 9.0.0
remote:        Installing ffi 1.12.2 with native extensions
remote:        Fetching tilt 2.0.10
remote:        Installing tilt 2.0.10
remote:        Fetching mimemagic 0.3.5
remote:        Installing mimemagic 0.3.5
remote:        Fetching public_suffix 4.0.5
remote:        Installing public_suffix 4.0.5
remote:        Fetching execjs 2.7.0
remote:        Installing execjs 2.7.0
remote:        Fetching bcrypt 3.1.13
remote:        Installing bcrypt 3.1.13 with native extensions
remote:        Fetching msgpack 1.3.3
remote:        Installing msgpack 1.3.3 with native extensions
remote:        Fetching popper_js 1.16.0
remote:        Installing popper_js 1.16.0
remote:        Using bundler 2.0.2
remote:        Fetching cancancan 3.1.0
remote:        Installing cancancan 3.1.0
remote:        Fetching mini_magick 4.10.1
remote:        Installing mini_magick 4.10.1
remote:        Fetching coffee-script-source 1.12.2
remote:        Installing coffee-script-source 1.12.2
remote:        Fetching orm_adapter 0.5.0
remote:        Installing orm_adapter 0.5.0
remote:        Fetching dotenv 2.7.5
remote:        Installing dotenv 2.7.5
remote:        Fetching multipart-post 2.1.1
remote:        Installing multipart-post 2.1.1
remote:        Fetching geocoder 1.6.3
remote:        Installing geocoder 1.6.3
remote:        Fetching hashie 4.1.0
remote:        Installing hashie 4.1.0
remote:        Fetching jwt 2.2.1
remote:        Installing jwt 2.2.1
remote:        Fetching multi_json 1.14.1
remote:        Installing multi_json 1.14.1
remote:        Fetching multi_xml 0.6.0
remote:        Installing multi_xml 0.6.0
remote:        Fetching xml-simple 1.1.5
remote:        Installing xml-simple 1.1.5
remote:        Fetching pg 1.2.3
remote:        Installing pg 1.2.3 with native extensions
remote:        Fetching puma 3.12.4
remote:        Installing puma 3.12.4 with native extensions
remote:        Fetching rb-fsevent 0.10.4
remote:        Installing rb-fsevent 0.10.4
remote:        Fetching turbolinks-source 5.2.0
remote:        Installing turbolinks-source 5.2.0
remote:        Fetching wkhtmltopdf-binary 0.12.5.4
remote:        Installing wkhtmltopdf-binary 0.12.5.4
remote:        Fetching tzinfo 1.2.7
remote:        Installing tzinfo 1.2.7
remote:        Fetching nokogiri 1.10.9
remote:        Installing nokogiri 1.10.9 with native extensions
remote:        Fetching i18n 1.8.2
remote:        Installing i18n 1.8.2
remote:        Fetching websocket-driver 0.7.1
remote:        Installing websocket-driver 0.7.1 with native extensions
remote:        Fetching mail 2.7.1
remote:        Installing mail 2.7.1
remote:        Fetching rack-test 1.1.0
remote:        Installing rack-test 1.1.0
remote:        Fetching sprockets 3.7.2
remote:        Installing sprockets 3.7.2
remote:        Fetching warden 1.2.8
remote:        Installing warden 1.2.8
remote:        Fetching marcel 0.3.3
remote:        Installing marcel 0.3.3
remote:        Fetching addressable 2.7.0
remote:        Installing addressable 2.7.0
remote:        Fetching autoprefixer-rails 9.7.6
remote:        Installing autoprefixer-rails 9.7.6
remote:        Fetching uglifier 4.2.0
remote:        Installing uglifier 4.2.0
remote:        Fetching coffee-script 2.4.1
remote:        Installing coffee-script 2.4.1
remote:        Fetching faraday 1.0.1
remote:        Installing faraday 1.0.1
remote:        Fetching omniauth 1.9.1
remote:        Installing omniauth 1.9.1
remote:        Fetching paypal-sdk-rest 1.7.4
remote:        Installing paypal-sdk-rest 1.7.4
remote:        Fetching sassc 2.3.0
remote:        Installing sassc 2.3.0 with native extensions
remote:        Fetching ruby-vips 2.0.17
remote:        Installing ruby-vips 2.0.17
remote:        Fetching rb-inotify 0.10.1
remote:        Installing rb-inotify 0.10.1
remote:        Fetching bootsnap 1.4.6
remote:        Installing bootsnap 1.4.6 with native extensions
remote:        Fetching turbolinks 5.2.1
remote:        Installing turbolinks 5.2.1
remote:        Fetching activesupport 5.2.4.2
remote:        Installing activesupport 5.2.4.2
remote:        Fetching oauth2 1.4.4
remote:        Installing oauth2 1.4.4
remote:        Fetching loofah 2.5.0
remote:        Installing loofah 2.5.0
remote:        Fetching image_processing 1.10.3
remote:        Installing image_processing 1.10.3
remote:        Fetching sass-listen 4.0.0
remote:        Installing sass-listen 4.0.0
remote:        Fetching rails-dom-testing 2.0.3
remote:        Installing rails-dom-testing 2.0.3
remote:        Fetching globalid 0.4.2
remote:        Installing globalid 0.4.2
remote:        Fetching arbre 1.2.1
remote:        Installing arbre 1.2.1
remote:        Fetching activemodel 5.2.4.2
remote:        Installing activemodel 5.2.4.2
remote:        Fetching jbuilder 2.10.0
remote:        Installing jbuilder 2.10.0
remote:        Fetching wicked_pdf 2.0.2
remote:        Installing wicked_pdf 2.0.2
remote:        Fetching omniauth-oauth2 1.6.0
remote:        Installing omniauth-oauth2 1.6.0
remote:        Fetching rails-html-sanitizer 1.3.0
remote:        Installing rails-html-sanitizer 1.3.0
remote:        Fetching sass 3.7.4
remote:        Installing sass 3.7.4
remote:        Fetching activejob 5.2.4.2
remote:        Installing activejob 5.2.4.2
remote:        Fetching activerecord 5.2.4.2
remote:        Installing activerecord 5.2.4.2
remote:        Fetching carrierwave 2.1.0
remote:        Installing carrierwave 2.1.0
remote:        Fetching omniauth-facebook 6.0.0
remote:        Installing omniauth-facebook 6.0.0
remote:        Fetching actionview 5.2.4.2
remote:        Installing actionview 5.2.4.2
remote:        Fetching kaminari-activerecord 1.2.0
remote:        Installing kaminari-activerecord 1.2.0
remote:        Fetching polyamorous 2.3.2
remote:        Installing polyamorous 2.3.2
remote:        Fetching actionpack 5.2.4.2
remote:        Installing actionpack 5.2.4.2
remote:        Fetching kaminari-actionview 1.2.0
remote:        Installing kaminari-actionview 1.2.0
remote:        Fetching ransack 2.3.2
remote:        Installing ransack 2.3.2
remote:        Fetching actioncable 5.2.4.2
remote:        Installing actioncable 5.2.4.2
remote:        Fetching actionmailer 5.2.4.2
remote:        Installing actionmailer 5.2.4.2
remote:        Fetching formtastic 3.1.5
remote:        Installing formtastic 3.1.5
remote:        Fetching has_scope 0.7.2
remote:        Installing has_scope 0.7.2
remote:        Fetching railties 5.2.4.2
remote:        Installing railties 5.2.4.2
remote:        Fetching sprockets-rails 3.2.1
remote:        Installing sprockets-rails 3.2.1
remote:        Fetching activestorage 5.2.4.2
remote:        Installing activestorage 5.2.4.2
remote:        Fetching kaminari 1.2.0
remote:        Installing kaminari 1.2.0
remote:        Fetching responders 3.0.0
remote:        Installing responders 3.0.0
remote:        Fetching jquery-rails 4.3.5
remote:        Installing jquery-rails 4.3.5
remote:        Fetching coffee-rails 4.2.2
remote:        Installing coffee-rails 4.2.2
remote:        Fetching dotenv-rails 2.7.5
remote:        Installing dotenv-rails 2.7.5
remote:        Fetching font-awesome-rails 4.7.0.5
remote:        Installing font-awesome-rails 4.7.0.5
remote:        Fetching rails-i18n 5.1.3
remote:        Installing rails-i18n 5.1.3
remote:        Fetching sass-rails 5.1.0
remote:        Installing sass-rails 5.1.0
remote:        Fetching rails 5.2.4.2
remote:        Installing rails 5.2.4.2
remote:        Fetching inherited_resources 1.11.0
remote:        Installing inherited_resources 1.11.0
remote:        Fetching devise 4.7.1
remote:        Installing devise 4.7.1
remote:        Fetching sassc-rails 2.1.2
remote:        Fetching font-awesome-sass 5.12.0
remote:        Installing sassc-rails 2.1.2
remote:        Installing font-awesome-sass 5.12.0
remote:        Fetching activeadmin 2.7.0
remote:        Installing activeadmin 2.7.0
remote:        Fetching bootstrap 4.4.1
remote:        Installing bootstrap 4.4.1
remote:        Bundle complete! 37 Gemfile dependencies, 110 gems now installed
remote:        Gems in the groups development and test were not installed.
remote:        Bundled gems are installed into `./vendor/bundle`
remote:        Post-install message from i18n:
remote:        
remote:        HEADS UP! i18n 1.1 changed fallbacks to exclude default locale.
remote:        But that may break your application.
remote:        
remote:        If you are upgrading your Rails application from an older version of Rails:
remote:        
remote:        Please check your Rails app for 'config.i18n.fallbacks = true'.
remote:        If you're using I18n (>= 1.1.0) and Rails (< 5.2.2), this should be
remote:        'config.i18n.fallbacks = [I18n.default_locale]'.
remote:        If not, fallbacks will be broken in your app by I18n 1.1.x.
remote:        
remote:        If you are starting a NEW Rails application, you can ignore this notice.
remote:        
remote:        For more info see:
remote:        https://github.com/svenfuchs/i18n/releases/tag/v1.1.0
remote:        
remote:        Post-install message from sass:
remote:        
remote:        Ruby Sass has reached end-of-life and should no longer be used.
remote:        
remote:        * If you use Sass as a command-line tool, we recommend using Dart Sass, the new
remote:          primary implementation: https://sass-lang.com/install
remote:        
remote:        * If you use Sass as a plug-in for a Ruby web framework, we recommend using the
remote:          sassc gem: https://github.com/sass/sassc-ruby#readme
remote:        
remote:        * For more details, please refer to the Sass blog:
remote:          https://sass-lang.com/blog/posts/7828841
remote:        
remote:        Bundle completed (213.60s)
remote:        Cleaning up the bundler cache.
remote: -----> Installing node-v10.15.3-linux-x64
remote: -----> Detecting rake tasks
remote: -----> Preparing app for Rails asset pipeline
remote:        Running: rake assets:precompile
remote:        rake aborted!
remote:        Psych::SyntaxError: (<unknown>): mapping values are not allowed in this context at line 27 column 21
remote:        /tmp/build_aeb14ca2116eee1183f4c8cb96012421/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.2/lib/rails/secrets.rb:29:in `block in parse'
remote:        /tmp/build_aeb14ca2116eee1183f4c8cb96012421/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.2/lib/rails/secrets.rb:26:in `each'
remote:        /tmp/build_aeb14ca2116eee1183f4c8cb96012421/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.2/lib/rails/secrets.rb:26:in `each_with_object'
remote:        /tmp/build_aeb14ca2116eee1183f4c8cb96012421/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.2/lib/rails/secrets.rb:26:in `parse'
remote:        /tmp/build_aeb14ca2116eee1183f4c8cb96012421/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.2/lib/rails/application.rb:399:in `secrets'
remote:        /tmp/build_aeb14ca2116eee1183f4c8cb96012421/vendor/bundle/ruby/2.6.0/gems/devise-4.7.1/lib/devise/secret_key_finder.rb:12:in `find'
remote:        /tmp/build_aeb14ca2116eee1183f4c8cb96012421/vendor/bundle/ruby/2.6.0/gems/devise-4.7.1/lib/devise/rails.rb:37:in `block in <class:Engine>'
remote:        /tmp/build_aeb14ca2116eee1183f4c8cb96012421/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:32:in `instance_exec'
remote:        /tmp/build_aeb14ca2116eee1183f4c8cb96012421/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:32:in `run'
remote:        /tmp/build_aeb14ca2116eee1183f4c8cb96012421/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:61:in `block in run_initializers'
remote:        /tmp/build_aeb14ca2116eee1183f4c8cb96012421/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:60:in `run_initializers'
remote:        /tmp/build_aeb14ca2116eee1183f4c8cb96012421/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.2/lib/rails/application.rb:361:in `initialize!'
remote:        /tmp/build_aeb14ca2116eee1183f4c8cb96012421/config/environment.rb:5:in `<main>'
remote:        /tmp/build_aeb14ca2116eee1183f4c8cb96012421/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
remote:        /tmp/build_aeb14ca2116eee1183f4c8cb96012421/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
remote:        /tmp/build_aeb14ca2116eee1183f4c8cb96012421/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
remote:        /tmp/build_aeb14ca2116eee1183f4c8cb96012421/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
remote:        /tmp/build_aeb14ca2116eee1183f4c8cb96012421/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
remote:        /tmp/build_aeb14ca2116eee1183f4c8cb96012421/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `block in require'
remote:        /tmp/build_aeb14ca2116eee1183f4c8cb96012421/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:257:in `load_dependency'
remote:        /tmp/build_aeb14ca2116eee1183f4c8cb96012421/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
remote:        /tmp/build_aeb14ca2116eee1183f4c8cb96012421/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.2/lib/rails/application.rb:337:in `require_environment!
remote:        /tmp/build_aeb14ca2116eee1183f4c8cb96012421/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.2/lib/rails/application.rb:520:in `block in run_tasks_blocks'
remote:        /tmp/build_aeb14ca2116eee1183f4c8cb96012421/vendor/bundle/ruby/2.6.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:62:in `block (2 levels) in define'
remote:        /tmp/build_aeb14ca2116eee1183f4c8cb96012421/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
remote:        Tasks: TOP => environment
remote:        (See full trace by running task with --trace)
remote:        W, [2020-06-05T06:49:47.762341 #1646]  WARN -- : DEBUG log level not allowed in sandbox mode for security of confidential information. Changing log level to INFO...
remote: 
remote:  !
remote:  !     Precompiling assets failed.
remote:  !
remote:  !     Push rejected, failed to compile Ruby app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !	Push rejected to floating-chamber-22953.
remote: 
To https://git.heroku.com/floating-chamber-22953.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/floating-chamber-22953.git'

**Comment by pedrofurtado** [comment]
Hey @emersonxinay ! 👋 

Could you explain what you were doing that generates the error? It will be awesome if you also provide the environment configuration (ruby version, rails version, webpacker version, and so on) 👍

**Comment by guillaumebriday** [comment]
Feel free to reopen if you still have the issue.
