### ISSUE TITLE
Containerized Rails 6 application yarn Integrity check: Flags don't match

### ISSUE THREAD

**Issue by dmlond** [rails/webpacker#2625]
I have a containerized rails 6 + webpacker + yarn application that I am deploying to kubernetes. My Dockerfile basically does something like:

```
COPY Gemfile* /app
RUN bundle install
COPY package.json /app
COPY yarn.lock /app
RUN yarn install --check-files
COPY . /app
RUN RAILS_ENV=production rake assets:precompile
```

I precompile assets as production in order to get scss to compile to css.

My CI system builds the image in one job/stage, then runs rspec in another job/stage. That fails when it runs rails db:create before running rspec to prep the ephemeral postgres db
```
$ rake db:create
warning Integrity check: Flags don't match
error Integrity check failed
error Found 1 errors.
========================================
 Your Yarn packages are out of date!
 Please run `yarn install --check-files` to update.
========================================
To disable this check, please change `check_yarn_integrity`
to `false` in your webpacker config file (config/webpacker.yml).
yarn check v1.22.4
info Visit https://yarnpkg.com/en/docs/cli/check for documentation about this command.
```

Now, if I change the order of the commands in the Dockerfile to
```
COPY Gemfile* /app
RUN bundle install
COPY . /app
RUN RAILS_ENV=production rake assets:precompile && yarn install --check-files
```

it works.  I would prefer to run yarn install --check-files before I add the rest of the code, so that container image build caching can speed up builds with commits containing standard code changes, e.g. app, spec, config.

A) where are these flags stored, and documentated?
B) what is the recommendation?

ruby -v
ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-linux]
node -v
v10.20.1
yarn -v
1.22.4
rails (6.0.3.1)

**Comment by wissem1210** [comment]
Add "config.webpacker.check_yarn_integrity = false" in "development.rb" will solve the problem

**Comment by guillaumebriday** [comment]
thanks @wissem1210
