### ISSUE TITLE
Turbolinks not working as expected

### ISSUE THREAD

**Issue by ibraheemdev** [rails/webpacker#2627]
I created my app using `rails new myapp --webpack=react`, so `turbolinks` is being required and run in my `application.js` pack like this: 

`require("turbolinks").start();`. 

And my js packs are being loaded like this:
When a form is submitted, it triggers a `redirect_to example_path` in my controller. `example_path` is a rails view, with a `<%= javascript_pack_tag 'example' %>`, and a `div tag` which is being used to mount a react component. The react component is being mounted like this:
```
  document.addEventListener("turbolinks:load", () => {
    const node = document.getElementById(nodeId);
    // ...
    ReactDOM.render(<Component {...props} />, node);
  });
```

However, after the form submission, I am being redirected to a blank page that requires a full page reload to mount my react component. I have tried `redirect_to example_path(turbolinks: false)` and `redirect_to example_path('data-turbolinks': false)` as Issue #161  suggested. How can I solve this issue?

**Comment by redline-gh** [comment]
I found out that disabling turbolinks worked when I wrote: 

`redirect_to example_path, data: { turbolinks: false }`

But what if I don't want to disable turbolinks on a redirect. Why isn't waiting for the `turbolinks:load` event causing my component to be mounted correctly? Or is it working as expected, and I am just not fully understanding the `turbolinks` event lifecycle?

**Comment by justin808** [comment]
I think interactions between React and Turbolinks are out of the scope of rails/webpacker.
