### ISSUE TITLE
extract_css: true results in a link tag with media="screen"

### ISSUE THREAD

**Issue by willlma** [rails/webpacker#2628]
As a result, when trying to print a page in production, no styles are applied. I would like to remove the media attribute.

Current output:
```
<link rel="stylesheet" media="screen" href="/packs/css/shared-d1c88a72.css">
```

Desired output:
```
<link rel="stylesheet" href="/packs/css/shared-d1c88a72.css">
```

The closest documentation I can find is webpack's style-loader [attribute docs](https://webpack.js.org/loaders/style-loader/#attributes) for _adding_ attributes to the link tag, but given that `extract_css: true` results in [mini-css-extract-plugin](https://github.com/webpack-contrib/mini-css-extract-plugin) in being used instead of style-loader, I'm not sure how to go about altering the link tag's attributes or how I would remove one.

**Comment by rossta** [comment]
The `stylesheet_pack_tag` helper delegates to `stylesheet_link_tag` provided by Rails: https://github.com/rails/webpacker/blob/6779013ee445d162f55f11bfa10ac104178c8f42/lib/webpacker/helper.rb#L162

What you're observing is the default behavior of `stylesheet_link_tag`: https://apidock.com/rails/ActionView/Helpers/AssetTagHelper/stylesheet_link_tag

No need to modify webpack config; to omit the `media` attribute, it looks like you would need to pass `media: nil` as an option to the helper:

```erb
<%= stylesheet_pack_tag 'application', media: nil %>
```
