### ISSUE TITLE
Slow build using webpack-dev-server causes read timeout with no override

### ISSUE THREAD

**Issue by wwahammy** [rails/webpacker#2632]
If you are using webpacker with webpack-dev-server, it is possible for your build to take longer than 60 seconds to complete once you've gone to a page. I noticed this using fork-ts-checker-webpack-plugin with Typescript files. If this happens, your main server process will close the connection to webpack-dev-server with an Net::ReadTimeout exception and then close its connection to the browser. This sort of defeats the purpose of using webpack-dev-server. :smile: 

The problem is that Webpacker::DevServerProxy as a child class of Rack::Proxy has a default read timeout of 60 seconds. While Webpacker::DevServerProxy does pass its options to Rack::Proxy, there's no mechanism via application configuration to set the options passed to  Webpacker::DevServerProxy.

Addressing this properly will require adding a mechanism to set options passed to Webpacker::DevServerProxy via configuration or simply setting a higher read_timeout in [lib/webpacker/dev_server_proxy.rb](https://github.com/rails/webpacker/blob/master/lib/webpacker/dev_server_proxy.rb) or [lib/webpacker/railtie.rb](https://github.com/rails/webpacker/blob/master/lib/webpacker/railtie.rb)

# Workaround
As a workaround, you can add create an initializer in your config/application.rb file. This places another instance of Webpacker::DevServerProxy with a longer read_timeout in your middleware:

```ruby
   initializer "webpacker.proxy" do |app|
      insert_middleware = Webpacker.config.dev_server.present? rescue nil
      if insert_middleware
        app.middleware.insert_before 0,
             Webpacker::DevServerProxy, ssl_verify_none: true, read_timeout: 500 # or your preferred timeout length
      end
    end
```

This has the unfortunate problem of adding two Webpacker::DevServerProxy instance to your middleware. I didn't see a good way of deleting the one added by Webpacker and then adding the new one. They don't seem to conflict though.

**Comment by justin808** [comment]
Can you just hit refresh?
