### ISSUE TITLE
webpack-dev-server stops compiling after one compilation error

### ISSUE THREAD

**Issue by alexandreruban** [rails/webpacker#2635]
Hello ! 👋 

I am not sure this is the right place to file this issue but I have a weird issue with webpack hot reloading in a new rails application. 

### Issue
I want all my assets to be compiled using webpack, so I create a file `app/javascript/stylesheets/application.scss` and then import it in `app/javascript/packs/application.js`. Everything works as expected but if I make a syntax error in `application.scss`, the compilation fails and hot reloading stops. If I correct this syntax error, webpack does not recompile, and I have to restart webpack-dev-server to make it work again.

### Expected behaviour
I should not have to restart webpack-dev-server in order for webpack to recompile assets when the syntax error is corrected.

### Steps to reproduce 
Ruby version : 2.6.5
Rails version : 6.0.3.2

```shell
rails new issue-app
cd issue-app
rails g controller pages home
mkdir app/javascript/stylesheets
touch app/javascript/stylesheets/application.scss
```

```scss
// app/javascript/stylesheets/application.scss

h1 { color: red; }
```

```js
// app/javascript/packs/application.js

import "stylesheets/application.scss"
```

```rb
# app/views/layouts/application.html.erb

stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
```

When I visit `http://localhost:3000/pages/home` the title is red as expected. If I change the color to blue, the color of the title changes without having to reload the page manually. If I make a syntax error, the compilation fails and I see the overlay with failed to compile. 
```scss
// app/javascript/stylesheets/application.scss

h1 { color: ; } // syntax error
```

If I correct this mistake, hot reloading does not work anymore. Even when I refresh the page nothing changes. When I look at the console running webpack-dev-server, nothing happens when I save the corrected scss file. I have to restart webpack-dev-server manually to restart hot reloading.

Do you have any idea why ? I could not find any answer on the internet and tired on two different computers. Thank you so much for your help 🙏 

*Edit :*
It works as expected if I change the file from application.scss => application.css, so this might be a sass loader issue ?
Also, there are breaking changes to the sass-loader v8 version, it might come from this ?

**Comment by justin808** [comment]
Please try again with the latest dependencies and reopen if you like.
