### ISSUE TITLE
Erb plugin for webpacker doesn't install webpacker

### ISSUE THREAD

**Issue by a-ta-ta** [rails/webpacker#2639]
Using: Rails 6.0.3.2, Ruby 2.7.0

Trying make a new app with:
`rails new erb1 --webpack=erb --database=postgresql`

Rails starts with default sreen, then I try 
`rails g controller Welcome index`
and change routes accordingly.
Reload localhost and:
```
internal/modules/cjs/loader.js:983
  throw err;
  ^

Error: Cannot find module 'webpack'
Require stack:
- /home/alex/prjcts/erb1/node_modules/webpack-dev-server/bin/webpack-dev-server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/alex/prjcts/erb1/node_modules/webpack-dev-server/bin/webpack-dev-server.js:12:17)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/alex/prjcts/erb1/node_modules/webpack-dev-server/bin/webpack-dev-server.js'
  ]
}

```

Auto-generated package.json looks like:

```
{
  "name": "erb1",
  "private": true,
  "dependencies": {
    "@rails/actioncable": "^6.0.0",
    "@rails/activestorage": "^6.0.0",
    "@rails/ujs": "^6.0.0",
    "rails-erb-loader": "^5.5.2",
    "turbolinks": "^5.2.0"
  },
  "version": "0.1.0",
  "devDependencies": {
    "webpack-dev-server": "^3.11.0"
  }
}
```

I doubt if it's right to add "`@rails/webpacker": "4.2.2"` manually. Moreover, if I add it - it complains about absence of packs folder with manifest in the public folder:
`Webpacker can't find application in /home/alex/prjcts/erb1/public/packs/manifest.json.`
Also tried reinstalling webpack and installing webpack-cli with no effect.

**Comment by guillaumebriday** [comment]
Is this still an issue for you?

Feel free to reopen if needed

**Comment by a-ta-ta** [comment]
Actually I switched to Vue quite long ago since erb wasnt maintained. I mean there's no information how to install and use erb, there's no even a tiny example app.

However, I dunno if it is a right thing for Rails team to back down. Vue, React and other frameworks arent perfect. They were done for nodejs and mostly hostile to Rails, breaking its basic principles and changing its clear logic into mess. Honestly saying, apps made with Vue and Rails look like two-headed cyclops. They have all the disadvantages of both frameworks and lost some Rails advantages (like clear ajax calls)

It is more than an issue for me in context of my personal vision, and not an issue anymore in aspect of my current work.

**Comment by guillaumebriday** [comment]
You must have encountered an error during the rails new process. Your `package.json` is missing most of required dependencies.

The second error is because webpack is not installed in your project. So yeah basically Webpacker cannot compile anything.

I don't know what was your error exactly but just tried and it works fine.

You can use Vue with ERB but it's not really recommended though.
