### ISSUE TITLE
DevServer disabled for RAILS_ENV=test, but manifest.json doesn't know about it

### ISSUE THREAD

**Issue by naps62** [rails/webpacker#265]
After setting up webpacker, I was having trouble figuring out why some of my tests would just hang or fail.

I was running `RAILS_ENV=test bin/webpack` before my tests, but the request to the pack file would still fail in test mode.

After some digging, I noticed that `manifest.json` was generating `http://localhost:8080/...` urls.

The problem seems to be here:

```js
// config/webpack/configuration.js

const publicPath = env.NODE_ENV !== 'production' && devServer.enabled ? 'http://${devServer.host}:${devServer.port}/` : `/${paths.entry}/'
```

since `devServer.enabled` is true (coming from the YAML file) regardless of which environment I'm using, this was ending up with the wrong urls.
I added `&& env.NODE_ENV !== 'test'` to the conditions to disable this for test as well.

Or was I suposed to run the dev server in test mode as well? If so, then something is missing in the generators, because that would not be intuitive either.

I'll gladly sumit a PR to fix this. I just didn't do so yet because I'm not sure what the proper solution for this is

**Comment by zhumo** [comment]
You should not have to use dev-server in test. Because dev server is not used in production, you should have your test env match that.

There should be a `manifest-test.json` generated by `bin/webpack` if env is test. Do you have that? Otherwise, please ensure your development.server.yml file has `test: enabled: false`.

**Comment by naps62** [comment]
@zhumo I believe you misunderstood the issue. I do have a manifest.json generated, but it comes with `http://localhost:8080/application.js`, when for test mode it should just be `/packs/application.js`

Here's a screenshot that shows the packs directory starting out empty, then building the assets in test mode, and the manifest coming out wrong after that:

![2017-04-17-224701_1653x344_scrot](https://cloud.githubusercontent.com/assets/283819/25106147/0d5da53c-23c0-11e7-8a98-29ecde62df2a.png)

The fix I made, for now, was to change the previously mentioned line:

```js
// config/webpack/configuration.js

// change this:
const publicPath = env.NODE_ENV !== 'production' && devServer.enabled ? 'http://${devServer.host}:${devServer.port}/` : `/${paths.entry}/'

// to this:
const publicPath = env.NODE_ENV !== 'production' && env.NODE_ENV !== 'test' && devServer.enabled ? 'http://${devServer.host}:${devServer.port}/` : `/${paths.entry}/'
```

**Comment by naps62** [comment]
@zhumo I believe you misunderstood the issue. I do have a manifest.json generated, but it comes with `http://localhost:8080/application.js`, when for test mode it should just be `/packs/application.js`

Here's a screenshot that shows the packs directory starting out empty, then building the assets in test mode, and the manifest coming out wrong after that:

![2017-04-17-224701_1653x344_scrot](https://cloud.githubusercontent.com/assets/283819/25106147/0d5da53c-23c0-11e7-8a98-29ecde62df2a.png)

The fix I made, for now, was to change the previously mentioned line:

```js
// config/webpack/configuration.js

// change this:
const publicPath = env.NODE_ENV !== 'production' && devServer.enabled ? 'http://${devServer.host}:${devServer.port}/` : `/${paths.entry}/'

// to this:
const publicPath = env.NODE_ENV !== 'production' && env.NODE_ENV !== 'test' && devServer.enabled ? 'http://${devServer.host}:${devServer.port}/` : `/${paths.entry}/'
```

**Comment by naps62** [comment]
Also, adding `test: enabled: false` to `development.server.yml` doesn't seem to change anything. That `test` key doesn't seem to be used anywhere in `configuration.js` either

**Comment by zhumo** [comment]
`manifest.json` or `manifest-test.json`? If you don't have a `manifest-test.json` file, maybe you are using an older version of webpacker? When I compile in test environment, it generates a separate `manifest-test.json` file as according to this PR https://github.com/rails/webpacker/issues/189. If it doesn't do that for you, then maybe you're using a version of webpacker that existed before this fixed was merged.

**Comment by naps62** [comment]
Hmm, maybe I was using an older commit, or maybe I didn't overwrite one of the files when I last regenerated everything.

Since yesterday I removed all webpack configs and ran the generators from scratch. It now seems to be working. I didn't notice you mentioned `manifest-test.json` at first, sorry about that
