### ISSUE TITLE
When node.js's version is <13.7 , we can't use webpacker.(we can't make public/packs in short)

### ISSUE THREAD

**Issue by kazuhitonakayama** [rails/webpacker#2651]
When node.js's version is <13.7 , we can't use webpacker.(we can't make public/packs in short).
But we upgrade node's version to >=13.7, we can use webpacker。

**Comment by gauravtiwari** [comment]
@kazuhitonakayama hey, is it possible you might have upgraded some internal dependencies or another one that requires nodejs > 13.7?

Webacker support nodejs: https://github.com/rails/webpacker/blob/master/package.json#L11

**Comment by kazuhitonakayama** [comment]
Thank you for your comment！
@gauravtiwari 
I only upgraded node's version from 13.5 to 13.8.0

**Comment by jakeNiemiec** [comment]
Odd-numbered releases are for library authors and are only "current" for less than 2 months. 

Webpacker only supports `Active/Maintenance LTS` releases of node.js. You can view these here: https://nodejs.org/en/about/releases/

**Comment by guillaumebriday** [comment]
I think it's not webpacker related. Some of your dependencies might need node >= 13.7 indeed.

**Comment by guillaumebriday** [comment]
Feel free to close the issue if it's good for you
