### ISSUE TITLE
Updating from 4.2.2 to 5.1.1: No longer finding element-icons used in Element UI

### ISSUE THREAD

**Issue by tbtalbottjr** [rails/webpacker#2658]
I have been trying to determine what has changed doing this update that would cause the icons to no longer render correctly.  I do not receive any errors browser, but I see that it is no longer trying to load the font file (previously was /packs/media/fonts/element-icons-xxx.woff)

The manifest.json contains an entry for the file:

    "media/fonts/element-icons.woff": "/packs/media/fonts/element-icons-313f7dac.woff",

I have compared the generated webpack.config.js and see very few changes:

- "output.pathinfo: true" has been removed
- ""cache": true," has been removed
- under ""loader": "sass-loader"" the following has been added under "options":
```
      "sassOptions": {
         "includePaths": []
       }
```
- under "plugins" a ""logger": {}," has been added above ""pathCache": {},"

The theme is currently being loaded via babel.config.js under plugins:

          [
            "component",
            {
              "libraryName": "element-ui",
              "styleLibraryName": "theme-chalk"
            }
         ]

But I have also tried importing it in the main entrypoint with:
`import 'element-ui/lib/theme-chalk/index.css';`
with the same result.

I have added in the 'resolve-url-loader' as recommended in some posts:
```
environment.loaders.get('sass').use.splice(-1, 0, {
  loader: 'resolve-url-loader'
});
```
Which places it right above the 'sass-loader':
```
  {
    "key": "sass",
    "value": {
      "test": {},
      "use": [
        "/Users/tom/LGL_DEV/lgl/node_modules/@rails/webpacker/node_modules/mini-css-extract-plugin/dist/loader.js",
        {
          "loader": "css-loader",
          "options": {
            "sourceMap": true,
            "importLoaders": 2,
            "modules": false
          }
        },
        {
          "loader": "postcss-loader",
          "options": {
            "config": {
              "path": "/Users/tom/LGL_DEV/lgl"
            },
            "sourceMap": true
          }
        },
        {
          "loader": "resolve-url-loader"
        },
        {
          "loader": "sass-loader",
          "options": {
            "sourceMap": true,
            "sassOptions": {
              "includePaths": []
            }
          }
        }
      ],
      "sideEffects": true,
      "exclude": {}
    }
  },
```

I'm going to need to fall back to 4.2.2 until this can be resolved.

**Comment by guillaumebriday** [comment]
Did you find a solution @tbtalbottjr?

**Comment by tbtalbottjr** [comment]
Sorry @guillaumebriday, we are currently stuck on Webpacker 4.3 and Webpack 4.41.5 until a workaround can be found. I've spent many hours trying to figure out what is going on, but have had no luck so far.

**Comment by justin808** [comment]
Let's reopen if needed for 6.0.
