### ISSUE TITLE
core-js/regenerator-runtime discrepancy between README and rails@6.0.3.2

### ISSUE THREAD

**Issue by josh-m-sharpe** [rails/webpacker#2660]
This repo has the following in the README:

```
In /packs/application.js, include this at the top of the file:

import 'core-js/stable'
import 'regenerator-runtime/runtime'
```

...but a freshly generated rails app using 6.0.3.2 does not add those import statements to packs/application.js

Which should it be?

**Comment by rossta** [comment]
@josh-m-sharpe My reading of it is the README is instructing developers to add this import themselves; the installer will not assume you want to add polyfills.

**Comment by josh-m-sharpe** [comment]
I suppose I would expect the rails installer to follow the recommended setup of the packages it is using.  Maybe that's an incorrect assumption.

**Comment by masterkain** [comment]
https://babeljs.io/docs/en/v7-migration#remove-proposal-polyfills-in-babelpolyfillhttpsgithubcombabelbabelissues8416
