### ISSUE TITLE
"error Command "webpack" not found." When building React/Ruby app.

### ISSUE THREAD

**Issue by JCGuest** [rails/webpacker#2664]
![heroku error](https://user-images.githubusercontent.com/52436800/87709077-559bf880-c769-11ea-8d34-e1ae99498166.png)

heroku buildpacks : 
1. heroku/nodejs
2. heroku/ruby

Trying to deploy a React/Rails app. Looks like I am missing a dependency but I'm not sure where to add it.

**Comment by jeffchuber** [comment]
@JCGuest did you resolve this? running into same thing

**Comment by jeffchuber** [comment]
@JCGuest did you figure out a solution to this?

**Comment by guillaumebriday** [comment]
@JCGuest What is your Rails / Webpack / Node version ? Did you run `bundle install` and `yarn install` ?

**Comment by otimong** [comment]
@JCGuest  did you find the solution to this?
