### ISSUE TITLE
Prevent browser caching of javascript packs, using a hash in the filename

### ISSUE THREAD

**Issue by mikeyhew** [rails/webpacker#267]
Chrome keeps running old versions of application.js, unless I disable the cache in developer tools. This doesn't happen with sprockets because it includes a hash of the file's contents in the filename, preventing chrome from loading the file from cache unless the hash is the same.

Can we add this feature to webpacker? How would you recommend it be implemented?

**Comment by ytbryan** [comment]
I guess you are referring to development mode. 

Because the hash is already available during production. So we can just switch it on for development? cc @gauravtiwari

**Comment by gauravtiwari** [comment]
@ytbryan Yeah, we can do that, although I never had this problem :) but makes sense to just follow what sprockets is doing so, it works for all cases 👍

**Comment by mikeyhew** [comment]
@ytbryan @gauravtiwari That sounds good. Where is the config for this?

**Comment by mikeyhew** [comment]
Never mind, I found it. See the above pull request. Are any tests needed?

**Comment by dhh** [comment]
Need to set the right cache-control headers like sprockets does.
