### ISSUE TITLE
Compression defaults

### ISSUE THREAD

**Issue by strobilomyces** [rails/webpacker#2671]
This may be more of a conceptual question, but I couldn't find it in the docs. I'm wondering what the default settings are for compression in webpacker, since there's nothing referencing this in webpacker.yml and nothing outputted during compilation that might indicate it other than the raw numbers.

Specifically, I'm wondering what the default compression level, threshold, and minRatio are for Brotli. The defaults seem inadequate, so I'm guessing that the compression level is rather low.

I tried adding [webpack-compression-plugin](https://webpack.js.org/plugins/compression-webpack-plugin/#using-brotli) to my config/webpack/production.js in order to fine-tune things (11 would have taken the rest of my natural life, 7 was beyond slow, and 5 was slightly slower than vanilla webpacker), but I feel like I'm dealing with a black box in terms of webpacker--how does what I'm generating compare with the defaults?

Any help would be appreciated. Thanks.

**Comment by rossta** [comment]
The Webpacker default production webpack config already uses compression-webpack-plugin and will produce [multiple compressed versions of assets](https://webpack.js.org/plugins/compression-webpack-plugin/#multiple-compressed-versions-of-assets-for-different-algorithm) when brotli is available in the current node version. 

Here is the default config in Webpacker:
https://github.com/rails/webpacker/blob/bf278f9787704ed0f78038ad7d36c008abc2edfd/package/environments/production.js#L11-L29

As you can see in the config, values for compression, threshold, and minRatio are not explicitly set, so would result in the plugin default values which are all documented at the link you provided.

To override, you could do something like:

```javascript
// config/webpack/environment.js

const BrotliCompressionPluginInstance = environment.plugins.get('Compression Brotli')
BrotliCompressionPluginInstance.minRatio = 0.75
// etc
```

**Comment by strobilomyces** [comment]
Thanks so much for the response, @rossta ; I figured I might have been reinventing the wheel. The override was just what I needed.
