### ISSUE TITLE
defer:true with stylesheet_packs_with_chunks_tag 

### ISSUE THREAD

**Issue by strobilomyces** [rails/webpacker#2672]
I'm using stylesheet_packs_with_chunks_tag to load both a stylesheet that's critical for my layout and another with animations that can be deferred. Given that the documentation says to use a single stylesheet_packs_with_chunks_tag declaration, how is it possible to defer the non-critical CSS? Thank you.

**Comment by rossta** [comment]
I've never tried this but my guess would be that this is not supported based on source code of the helper method:

https://github.com/rails/webpacker/blob/bf278f9787704ed0f78038ad7d36c008abc2edfd/lib/webpacker/helper.rb#L160-L164

The given options would be applied to all usages of the underlying `stylesheet_link_tag` so it doesn't appear possible to target selected chunks.

**Comment by strobilomyces** [comment]
Thanks for the response. I thought not, but I figured I'd ask.

In theory, would it be crazy for stylesheet_packs_with_chunks_tag (and by proxy javascript_packs_with_chunks_tag) to take a hash that allows for individual options, or would using plain old stylesheet_pack_tag make more sense?

**Comment by rossta** [comment]
You could always try a PR? 

For CSS, I haven't found chunking to be worth it—it's easy to make mistakes with the cascade, for example—so I typically combine all CSS into one file, e.g.:

```javascript
optimization: {
      splitChunks: {
        // ...
        cacheGroups: {
          styles: {
            name: 'styles',
            test: /\.(sass|scss|css)$/,
            chunks: 'all',
            enforce: true,
          },
      //...
```

Optionally, I'd recommend instead considering dynamic imports for non-critical JS especially instead of using multiple packs for "sprinkles". I think of additional packs for completely different sections of the site, e.g. "application" and "admin".

**Comment by strobilomyces** [comment]
I think I've definitely been going a little overboard lately with the "sprinkles" in trying to avoid large pack sizes. Thanks so much, again, for taking the time to answer my questions. I'll give it some thought before any misguided pull requests :)

**Comment by rossta** [comment]
Yeah, give dynamic imports a shot. It's not mutually exclusive to splitChunks, but if you're trying to solve for deferring non-critical JS, that's exactly what dynamic imports is for.

**Comment by guillaumebriday** [comment]
I'm not sure to understand exactly what you want to do, but as far as I know you cannot defer CSS like JS.

You can achieve the same behavior with this hack: https://web.dev/defer-non-critical-css/

Does this help ?

**Comment by strobilomyces** [comment]
Thanks for the reply, @guillaumebriday 

I was just trying to separate some heavy page-specific CSS, but thanks to the above, I realized it was the wrong approach. I really should have closed this issue a while ago, so my apologies for that. Thank you for the link, nonetheless.
