### ISSUE TITLE
Question: How can I render a webpack js file from my rails controller?

### ISSUE THREAD

**Issue by brmi** [rails/webpacker#2681]
My situation is similar to the one here: https://github.com/rails/webpacker/issues/334

I hand off a script to a client that points to my Rails Controller, which renders a `.js.erb` file. I would like to load a React application from this file, and attach it to a DOM element on my clients website. That seems to have been discussed briefly in the issue I posted above.

I'm thinking it would also work to just have my Rails Controller link to the `javascript/packs` file directly. Is there a way I can render a javascript file in the `javascript/packs` folder from my Rails Controller? Or is there a way I can render webpack output in a `.js.erb` file?

**Comment by andrewcmyk** [comment]
I'm using this approach now, but I came here to ask the same question. Would prefer a render of pack contents instead of redirect.
https://www.mikewilson.dev/posts/redirecting-to-static-webpacker-content-with-rails/
