### ISSUE TITLE
Allow setting --progress and --color separately

### ISSUE THREAD

**Issue by ksweetie** [rails/webpacker#2682]
The `pretty` flag toggles both `--progress` and `--color`:

https://github.com/rails/webpacker/blob/ce0133d1948d545058eb279191063c5699849f14/lib/webpacker/dev_server_runner.rb#L62

IMO, these should configurable separately. This is exacerbated, because webpacker doesn't allow users to pass arbitrary arguments to webpack-dev-server (related issue: https://github.com/rails/webpacker/issues/2000). As far as I can tell, there's no possible way for me to currently send `--colors` to wds, but not `--progress`.

My use case for wanting to do this: I'm using foreman, but colors aren't being set. If I flip on `pretty`, colors begin to work, but the `--progress` flag works horribly with foreman.

I'm willing to make a PR for this, but I'm not sure what the maintainers would prefer. Ideally, I would just get rid of `pretty` and separate these two arguments into two flags, however, that would be a breaking change. Should I add two new flags for `colors` and `progress`, in addition to the existing `pretty` (which we could then deprecate and await a major version to remove)?

**Comment by rossta** [comment]
Now that #2595 has been merged, I believe you'll be able to accomplish what you want in an upcoming Webpacker release. Try using Webpacker from master to verify if you're able.

**Comment by ksweetie** [comment]
Hey @rossta, that's even better, and I can confirm that it works perfectly for me. Thank you so much! Any chance we can cut a new release? I don't think that went out with 5.2.1.

**Comment by rossta** [comment]
@ksweetie 

> Any chance we can cut a new release? 

That's out of my hands :) 

I expect it will be in the v6.0 release though!
