### ISSUE TITLE
Using npm @rails/webpacker@4.0.7 with webpacker-3.5.5 gem

### ISSUE THREAD

**Issue by lawrenceelitzer** [rails/webpacker#2684]
Not sure if this is the place to ask, but I've recently become part of a project that seems to be using the webpacker 4 npm pkg with the 3.5.5 gem. Is this kosher? Surprisingly (to me at least) it's been running without issues. It seems like they should match up, correct? Thanks!

**Comment by guillaumebriday** [comment]
Gem and package are published with the same version number. For best compatibility you should use the same version for both yes.

**Comment by lawrenceelitzer** [comment]
Yeah right I get that. We've been happily running with out-of-sync versions between gem and package for quite some time and haven't noticed any issues. So I was wondering if there was any urgent need to get them in sync or things I should look out for to look for inconsistencies/issues? But that's probably too broad of a question. I would've assumed it wouldn't work if they are out of sync I guess. I was just surprised to find the node in that state.

**Comment by guillaumebriday** [comment]
I tried to be async and it works because most of changes are not breaking changes, they are minor updates.

But it cost nothing to be sync between package and gem 👍 

I think you can close because we can't do anything special.

**Comment by lawrenceelitzer** [comment]
Awesome thank you for the info, I will close.
