### ISSUE TITLE
Implement Rome (on a `next` or `edge` branch perhaps)

### ISSUE THREAD

**Issue by tsujp** [rails/webpacker#2691]
Website: https://romefrontend.dev/
GitHub: https://github.com/romefrontend/rome

Rome's just entered the ecosystem publicly and aims to converge a number of discrete tools into one monolithic architecture; knowing first hand the nuisance and pain of getting a working eslint, babel, webpack, and typescript config up and running for a new yet still unfamiliar stack this sounds like a dream come true. Further, the pedigree of being implemented by the developer of such tools of Yarn and Babel gives me confidence it can be done.

Currently it's only focus is linting, is it worth adding as an alternative linter on a next or edge branch of webpacker and tracking implementing as Rome solidifies it's footing?

**Comment by guillaumebriday** [comment]
Rome is in his early stage of development and he's still in beta. Webpack is mature and used by millions of people now.

I think we might reconsider this issue in few years.

**Comment by gauravtiwari** [comment]
thanks @guillaumebriday
