### ISSUE TITLE
ActionView::Template::Error (Webpacker can't find application in ...manifest.json

### ISSUE THREAD

**Issue by bjpcjp** [rails/webpacker#2698]
This is similar to [2674](https://github.com/rails/webpacker/issues/2674):

Rails 6.0.3.2, Ruby 2.7.1
webpacker 4.0
node v11.5.0

Newly created apps run correctly out of the box, but crash when the first controller is instantiated. Webpacker can't find application in /public/packs/manifest.json. (There's no packs folder.)

$rails webpacker:install has no effect.

Suggestions?

**Comment by Sakshi1305** [comment]
@bjpcjp : Is this error happening in your development mode? If so, then run this command that create packs folder :
 $ **rake webpacker:compile** and make sure in webpack.yml configuration compile is true i.e. compile: true

**Comment by bjpcjp** [comment]
It was indeed happening in devt mode. I can confirm that webpack.yml configuration compile: true was set as required; I believe (but can't confirm) that $rake webpacker:compile was executed.

I deleted the app in frustration, then created another using the same dependencies. This time the app launched without problem. The only known difference is in the quality of the package downloads (I am working from a mobile hotspot).

Given that I no longer have access to the log in question, replicating the problem isn't possible. So I'll close this issue and thank @Sakshi1305 for his/her response.
