### ISSUE TITLE
5.2.0 breaks some custom loggers

### ISSUE THREAD

**Issue by tragiclifestories** [rails/webpacker#2700]
We have our own internal logging library that enforces our company standards. It implements `#tagged` identically to ActiveSupport's TaggedLogging.

Before https://github.com/rails/webpacker/pull/1311, webpacker would happily use our custom logger. But that PR flips the if statement, and now Webpacker is messing with our logger, replacing our formatter with some random unwanted one which is incompatible with our gem (we only emit structured JSON logs and handle the lines internally as hashes, so we get `no implicit conversion` errors instead of log lines).

**Comment by gauravtiwari** [comment]
@tragiclifestories sorry about that - lets revert that change 👍

**Comment by tragiclifestories** [comment]
Cheers! I think there must be a way to fix the original reported problem without breaking us, but I can't see one just yet.

**Comment by gauravtiwari** [comment]
No worries, released 5.2.1

Yes, me neither. Makes sense to revert since it's possible a lot of people might be customising the logger.  

// @flippakitten

**Comment by gauravtiwari** [comment]
Feel free to close if all good

**Comment by tragiclifestories** [comment]
Looks good. Thanks for the quick fix!

**Comment by flippakitten** [comment]
Wow, this PR is a blast from the past. 

If my memory serves me correctly, the issue was around centralized logging and when you completely replace the rails logger so when Webpacker initializes it overwrites your logger with a new TaggedLogging instance. 

@tragiclifestories Sorry about introducing breaking changes.

@gauravtiwari what about a config option or revert to the current implementation?

```
  initializer "webpacker.logger" do
    config.after_initialize do
      if ::Rails.logger.respond_to?(:tagged) || use_default_rails_logger
        Webpacker.logger = ::Rails.logger
      else
        Webpacker.logger = ActiveSupport::TaggedLogging.new(::Rails.logger)
      end
    end
  end
```

**Comment by scottrobertson** [comment]
What changes happened in 5.2.0? No change log entries.

**Comment by gauravtiwari** [comment]
@flippakitten thank you for update. Is it not possible to override `Webpacker.logger` in the app itself?

@scottrobertson Mainly, dependencies update and some minor fixes: https://github.com/rails/webpacker/compare/v5.1.1...5-x-stable

**Comment by emilkarl** [comment]
Reverting this actually breaks it for us when using [lograge](https://github.com/roidrage/lograge). Changing it to the other way around works tho. Any idea why? 

Works
```ruby
initializer "webpacker.logger" do
  config.after_initialize do
    if ::Rails.logger.respond_to?(:tagged)
      Webpacker.logger = ActiveSupport::TaggedLogging.new(::Rails.logger)
    else
      Webpacker.logger = ::Rails.logger
    end
  end
end
```
