### ISSUE TITLE
 Your Yarn packages are out of date

### ISSUE THREAD

**Issue by scratchoo** [rails/webpacker#2703]
Whenever I precompile assets

`rails assets:precompile RAILS_ENV="production"`

Then I try 

`rails assets:clobber`

I get the message:

```
warning Integrity check: Flags don't match                                                                                                 
error Integrity check failed                                                                                                               
error Found 1 errors.                                                                                                                      


========================================
  Your Yarn packages are out of date!
  Please run `yarn install --check-files` to update.
========================================


To disable this check, please change `check_yarn_integrity`
to `false` in your webpacker config file (config/webpacker.yml).


yarn check v1.19.0
info Visit https://yarnpkg.com/en/docs/cli/check for documentation about this command.
```

To fix this I have to delete the node_modules every time (before I run assets:clobber) and install the packages using yarn install. Once done, the rails assets:clobber works, if I repeat again (1- precompile assets, then 2- try assets:clobber) the error shows up again.

my rails version:  Rails 6.0.3.2

**Comment by gauravtiwari** [comment]
@scratchoo It's mainly because `rails assets:precompile RAILS_ENV="production"` installs node modules in production mode and when you do `rails assets:clobber` it's run in development mode and integrity check fails due to env mismatch. 

BTW, this check is now removed from Webpacker 5.2.1/master
