### ISSUE TITLE
Deprecation warning for check_yarn_integrity seems not to happen?

### ISSUE THREAD

**Issue by jaredbeck** [rails/webpacker#2714]
@rossta Hi Ross 👋  In https://github.com/rails/webpacker/pull/2518, you added this deprecation warning:

```
# webpacker/configuration.rb
  def check_yarn_integrity=(value)
    warn "Webpacker::Configuration#check_yarn_integrity=(value) has been deprecated. The integrity check has been removed from Webpacker so changing this setting will have no effect."
  end
```

But I don't see it in my log.

```
bin/rails server
=> Booting Puma
...
Processing by MainController#index as HTML
...
[Webpacker] Everything's up-to-date. Nothing to do
```

My configuration:

```
# config/environments/development.rb
Rails.application.configure do
...
  config.webpacker.check_yarn_integrity = true
```

Maybe `config.webpacker.check_yarn_integrity` is an old API, so old that it wasn't working anyway? I'm trying to trace the call to `check_yarn_integrity=` using my debugger, but I'm unsure how the config gets from railties to webpacker.

Is this worth spending time on? I just want other people to see this warning.

**Comment by jaredbeck** [comment]
Additionally, the `warn` message says "has been deprecated" but I think "has been removed" would be more accurate.

**Comment by rossta** [comment]
Ah, this would have to be a call to the Webpacker logger instead of Kernel#warn.

**Comment by jaredbeck** [comment]
> Ah, this would have to be a call to the Webpacker logger instead of Kernel#warn.

Taking that approach, I started to write a test for this.

```
# test/configuration_test.rb
  def test_check_yarn_integrity_is_obsolete
    assert_output(nil, /is obsolete/) {
      @config.check_yarn_integrity = true
    }
  end
```

I expected it to fail, but it passed. So, `minitest` thinks we are writing to stderr ..

**Comment by justin808** [comment]
fixed by removing this https://github.com/rails/webpacker/blob/63f59de51f7f558fca0b69bbb3f7413ca552067c/lib/webpacker/configuration.rb#L58
