### ISSUE TITLE
application.css no longer generated after upgrade

### ISSUE THREAD

**Issue by gsouf** [rails/webpacker#2718]
Hi,

I just upgraded

- webpack: `3.5.5` to `4.44.1`
- @rails/webpacker: `3.2.1` to `5.2.1`
- webpacker-dev-server: `2.9.3` to `3.11.0`

as well as various webpack loaders.

I migrated various configs to get everything fixed, but now `application.css` is no longer generated. Error is:

```
Webpacker can't find application.css in .../public/packs/manifest.json
```

If I remove `<%= stylesheet_pack_tag 'application' %>` from the erb file then it works well, except that global styles are not loaded.

Any ideas what could get `application.css` to be skipped after upgrade?

Thanks

**Comment by rossta** [comment]
Have you set `extract_css: true` in your `config/webpacker.yml`? This is an option added since `3.5.5` (I think) and may be defaulting to false if not present in your config. https://github.com/rails/webpacker/blob/5780a0a9b969560596e3a0ace2398c7e291f9c0b/lib/install/config/webpacker.yml#L19

**Comment by guillaumebriday** [comment]
Upgrading from 3.x to 4.x is not trivial. Webpack changed a lot.

Did you follow the steps in https://github.com/rails/webpacker/blob/master/docs/v4-upgrade.md ?

**Comment by gsouf** [comment]
@rossta  @guillaumebriday  thanks for feedback. I havent tried to upgrade again since you answered. I'll try soon according to your info and let you know,

Thanks

**Comment by gsouf** [comment]
@guillaumebriday looking at the upgrade guide and migrate to 4.x then to 5.x helped. 

Thanks for your times
