### ISSUE TITLE
Using webpacker in production environment is not looking for compiled assets in manifest.

### ISSUE THREAD

**Issue by JDutil** [rails/webpacker#272]
I've recently migrated an application from using webpack-rails to webpacker, but I'm running into a manifest issue when trying to serve assets without the dev server running.  

Essentially I compile my assets for production, and things appear to compile correctly and be listed in the `manifest.json`.  However when running my app with `RAILS_ENV=production` I receive the error `Can't find admin.css in /Users/JDutil/Code/spreeworks/public/packs/manifest.json. Is webpack still compiling?`.  It's not finding site.css in the manifest because the manifest has the digest appended to it.  

I'm wondering why running my app in production environment wouldn't be looking for `site-[hash].css` as I'm expecting it to so that it can properly find the assets.  I'm sure this is probably some basic configuration option that I'm missing, but I can't seem to figure it out and haven't seen anything in the README or other issues here talking about this.

Let me know if there is any more information you'd like to troubleshoot this. Thanks.

**Comment by zhumo** [comment]
So you're doing `RAILS_ENV=production` in your local environment and then getting this error? Or are you doing this in some kind of production environment? Are you simply prepending the RAILS_ENV command to `bin/webpack` command or are you setting that in .env or something similar?

**Comment by JDutil** [comment]
I'm just doing `RAILS_ENV=production bin/webpack` and `RAILS_ENV=production rails s`, and experiencing it that way. Once I can get it working locally in production environment I'll deploy to staging for testing.

I'm also experiencing it using `yarn build`, which is configured like so:
```
  "scripts": {
    "start": "bundle exec rake js_routes:export && ./node_modules/.bin/webpack-dev-server --host 0.0.0.0 --config config/webpack/development.js --progress --colors --inline --hot",
    "build": "NODE_ENV=production ./node_modules/.bin/webpack --config ./config/webpack/production.js --bail"
  },
```

Using `yarn start` is working fine though as well.

**Comment by gauravtiwari** [comment]
@JDutil Hey, is webpacker pinned to master? Have you updated the gem - `bundle update webpacker`? If you have then - are all your webpack config up-to-date i.e. `bundle exec rails webpacker:install`?

**Comment by JDutil** [comment]
@gauravtiwari yes I had originally tried with v1.1, but later updated to master branch @ a06421ffe300e4f32af186f09ed5d1c64b311f5e and updated the config files.  

I just updated again to latest @ 740189b9f1f3a7ec35adb12df3361c28f52c4809 and updated config files again without any luck.

I'm thinking this issue is more related to ruby/rails than the webpack configuration, but then again I could be wrong as looking through the webpacker code seems it is pulling in configuration from the js files. It seems to me the issue is with `stylesheet_pack_tag` & `javascript_pack_tag` are not adding the hash as if `compute_asset_extname` method within them is not executing properly. I assume that's a rails method as I'm not seeing it defined within the webpacker code anywhere?

I do have `config.assets.digest = true` set in the `config/environments/production.rb` file so I'd expect it to work. Unless there is some other option I'm missing.

**Comment by JDutil** [comment]
Well actually found `compute_asset_extname` in Rails, but now realizing that's not what generates the digest: https://github.com/rails/rails/blob/5-0-stable/actionview/lib/action_view/helpers/asset_url_helper.rb#L180-L186

Looking through the webpacker code I'm really not sure what generates it at all.  It seems like it just uses whatever name is passed to the `stylesheet_pack_tag` & `javascript_pack_tag` methods... Is there something more than just calling `stylesheet_pack_tag 'site.css'` to get the digest appended? 

Or can someone point me to the code that should be converting `site.css` into `site-[hash].css`?

**Comment by gauravtiwari** [comment]
You got this repo somewhere I can look?

**Comment by JDutil** [comment]
@gauravtiwari unfortunately this is a private project for my company, but I'll try recreating the issue with our configuration in a new rails app I can make public.

**Comment by JDutil** [comment]
@gauravtiwari so I ended up running into a rails bug that prevented me from getting a new rails app working :(

However I believe I've found the culprit as I just got assets served to me in production environment 🎉 🍻 

It looks like the issue was my copying over a plugin from our previous configuration. Once I removed this plugin from our `shared.js` it seems to be working: 
```
    new StatsPlugin('manifest.json', {
      chunkModules: false,
      source: false,
      chunks: false,
      modules: false,
      assets: true
    })
```

Still need to determine whether we actually need that plugin anymore or not once I talk to the developer who added it, but I think this issue can be closed out. Thanks!

**Comment by JDutil** [comment]
Just to follow up apparently this `StatsPlugin` was what was used for webpack-rails to generate the manifest for rails to work with.  So since webpacker handles the manifest for us now after migrating removing that plugin should be fine for us.
