### ISSUE TITLE
Upgrading to v5.1+ breaks `Object.assign(this, ...)` in base class

### ISSUE THREAD

**Issue by vfonic** [rails/webpacker#2725]
I followed the instructions for upgrading to v5.1, to use @babel/preset-typescript:
https://github.com/rails/webpacker/blob/master/docs/typescript.md#upgrading-to-51

This broke my app in such a way that I don't know how to fix it easily. Maybe the way I'm doing this is wrong.

Here's what I had:

```ts

class BaseModel {
  public id: string;

  public constructor(doc) {
    Object.assign(this, { ...doc, id });
  }
}


class Event extends BaseModel {
  public constructor(doc) {
    super(doc);
  }

  public title?: string;
  public startAt?: Date;
  public endAt?: Date;
  // ...
}
```

This used to work with `ts-loader` (and before I introduced TypeScript to this project).
`BaseModel` assigns all properties to `this`. Doing this, it actually assigns it to `Event` model properties, so I can do:

```ts
event = new Event({ title: 'End of the world', id: 5 })
console.log(event.title); // 'End of the world'
```

However, after upgrading to webpacker 5.2 and @rails/webpacker 5.2 and following the upgrade instructions to switch from `ts-loader` to `@babel/preset-typescript` (and remove the changes in `environmnet.js`), this stopped working:

```ts
event = new Event({ title: 'End of the world', id: 5 })
console.log(event.title); // undefined
console.log(event); // { id: 5, title: undefined }
```

What am I doing wrong? Should I also report this to @babel/preset-typescript repo?

Thanks!

**Comment by guillaumebriday** [comment]
Did you find the solution @vfonic?

**Comment by vfonic** [comment]
No, I'm still using lower versions of webpacker.

**Comment by guillaumebriday** [comment]
I think it's related to your babel configuration and its plugins. 

I not sure it's an issue with Webpacker itself
