### ISSUE TITLE
Rename loaders to loaderRules

### ISSUE THREAD

**Issue by justin808** [rails/webpacker#2726]
Could “loaders” be renamed to “loaderRules” ? It’s very confusing when the rule is a combination of some matching criteria plus one or more webpack loaders to apply.

![image](https://user-images.githubusercontent.com/1118459/92796196-adf80c80-f34c-11ea-92a4-e95e77dad20b.png)

@gauravtiwari can you tell a bit more about your planned API changes?

**Comment by guillaumebriday** [comment]
That is no longer relevant with Webpacker 6.

Thanks for the suggestion
