### ISSUE TITLE
Babel.config.js cache issue

### ISSUE THREAD

**Issue by mazen506** [rails/webpacker#2728]
I am working on a "ruby on rails" project, using "rails-react" gem for react components. I have the following issue in Babel.config.js file. though I have changed the file contents but the old file contents are still showing in the error message. How can I clear the cache so that the new syntax gets compiled? Thanks.

Version:
Ruby 2.6.6
Rails 6.0.3

```
Uncaught Error: Module build failed (from ./node_modules/babel-loader/lib/index.js):
D:\dropshipping\development\apps\fruits-app\babel.config.js:29
     ],
       ^

SyntaxError: Unexpected token ','"

```

**Comment by guillaumebriday** [comment]
Could you give us the complete config file or a repo please ?

**Comment by mazen506** [comment]
Hi @guillaumebriday , below is the code. However, even if I edit it or even delete the whole file, the same error keeps showing, it's cached but I don't know how to clear the cached file.


module.exports = function(api) {
  var validEnv = ['development', 'test', 'production']
  var currentEnv = api.env()
  var isDevelopmentEnv = api.env('development')
  var isProductionEnv = api.env('production')
  var isTestEnv = api.env('test')

  if (!validEnv.includes(currentEnv)) {
    throw new Error(
      'Please specify a valid `NODE_ENV` or ' +
        '`BABEL_ENV` environment variables. Valid values are "development", ' +
        '"test", and "production". Instead, received: ' +
        JSON.stringify(currentEnv) +
        '.'
    )
  }
  api.cache(false);

  return {
    presets: [
      (isProductionEnv || isDevelopmentEnv) && [
        '@babel/preset-env',
        {
          forceAllTransforms: true,
          useBuiltIns: 'entry',
          corejs: 3,
          modules: false,
          exclude: ['transform-typeof-symbol']
        }
      ]
    ].filter(Boolean),
    plugins: [
      'babel-plugin-macros',
      '@babel/plugin-syntax-dynamic-import',
      isTestEnv && 'babel-plugin-dynamic-import-node',
      '@babel/plugin-transform-destructuring',
      [
        '@babel/plugin-proposal-class-properties',
        {
          loose: true
        }
      ],
      [
        '@babel/plugin-proposal-object-rest-spread',
        {
          useBuiltIns: true
        }
      ],
      [
        '@babel/plugin-transform-runtime',
        {
          helpers: false,
          regenerator: true,
          corejs: false
        }
      ],
      [
        '@babel/plugin-transform-regenerator',
        {
          async: false
        }
      ]
    ].filter(Boolean),
  }
  
}

**Comment by guillaumebriday** [comment]
Please use the `code` block to format the code

**Comment by mazen506** [comment]
Alright. Thanks for the prompt response.

`module.exports = function(api) {
var validEnv = ['development', 'test', 'production']
var currentEnv = api.env()
var isDevelopmentEnv = api.env('development')
var isProductionEnv = api.env('production')
var isTestEnv = api.env('test')

if (!validEnv.includes(currentEnv)) {
throw new Error(
'Please specify a valid NODE_ENV or ' +
'BABEL_ENV environment variables. Valid values are "development", ' +
'"test", and "production". Instead, received: ' +
JSON.stringify(currentEnv) +
'.'
)
}
api.cache(false);

return {
presets: [
(isProductionEnv || isDevelopmentEnv) && [
'@babel/preset-env',
{
forceAllTransforms: true,
useBuiltIns: 'entry',
corejs: 3,
modules: false,
exclude: ['transform-typeof-symbol']
}
]
].filter(Boolean),
plugins: [
'babel-plugin-macros',
'@babel/plugin-syntax-dynamic-import',
isTestEnv && 'babel-plugin-dynamic-import-node',
'@babel/plugin-transform-destructuring',
[
'@babel/plugin-proposal-class-properties',
{
loose: true
}
],
[
'@babel/plugin-proposal-object-rest-spread',
{
useBuiltIns: true
}
],
[
'@babel/plugin-transform-runtime',
{
helpers: false,
regenerator: true,
corejs: false
}
],
[
'@babel/plugin-transform-regenerator',
{
async: false
}
]
].filter(Boolean),
}

}`

**Comment by guillaumebriday** [comment]
It seems that you have a syntax error. Fix it in your editor

For reference, here's the original file: https://github.com/rails/webpacker/blob/5-x-stable/lib/install/config/babel.config.js

**Comment by asecondwill** [comment]
i have the same error.   When I delete the contents of babel.config.js or even delete the file and restart my rails server, the same error persists.  how do I let webpacker / babel no to look again at the babel.config.js file?
