### ISSUE TITLE
How to disable SSR?

### ISSUE THREAD

**Issue by hopewise** [rails/webpacker#2731]
I need to disable SSR as I precompile assets at deployment to keep CPU usage as low as possible at runtime.

How would SSR get disabled?

**Comment by SampsonCrowley** [comment]
@hopewise not a maintainer here, but:

1) how did you enable it? Nothing is automatically rendered server side without doing any config to add SSR

2) Everyone precompiles assets in production, that doesn't have anything to do with SSR

3) From my perspective it seems that you're confusing dynamic compilation with server-side rendering

SSR is a complex feature that is definitely not enabled by default in Webpacker. If you have it already setup and enabled, one I'm impressed, and two I'd recommend you leave it that way. it should only be happening on HTML (i.e. first) requests regardless. A few extra CPU cycles is worth the SEO and accessibility benefits

**Comment by justin808** [comment]
Hi @hopewise, are you using [React on Rails](https://github.com/shakacode/react_on_rails)?

By the way, you need to precompile with webpack even if SSR is off.

**Comment by hopewise** [comment]
I am using [React-Rails](https://github.com/reactjs/react-rails), @SampsonCrowley  I need to read more about SSR, thanks for your notes as I had some concepts confusing.

My issue was solved when I precompiled assets into the Dockerfile it self rather in the host and then copying precompiled within the app folder into the container..
