### ISSUE TITLE
bundle exec rake assets:precompile is compiling all assets (but only every time another OS is compiling them)

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [rails/webpacker#2736]
Our team has a big problem and we tried multiple countermeasures, but we couldn't find any solution.

Due to server and system constraints, we precompile our assets (sprockets + webpacker) before releasing new versions.

The normal rails script RAILS_ENV=production bundle exec rake assets:precompile  is working fine and compiles only the last changed files - except if someone of my team is compiling them also.

We are syncing all code changes before with git, we run yarn install --check-files before each compilation to ensure we have the same npm packages. But it still doesn't work as expected.

When I compile only on my machine, only new assets get compiled. When another teammate compiles them (with pulled changes, updated manifest files,...), all assets get precompiled. If they compile again only on their machine, only the latest changed files are precompiled again.

I'm on OSX, my mates are on Linux/Ubuntu.

Does anyone have a suggestion on how to fix this issue? Or do I miss something? My question is mostly about webpacker, sprockets looks fine.

Also it seems that only some small webpack internal numbers are incresed, see following screenshow:

![Bildschirmfoto 2020-09-22 um 17 23 00](https://user-images.githubusercontent.com/10075/93902944-6a13e880-fcf8-11ea-9547-3d7de4b2d178.png)
![Bildschirmfoto 2020-09-22 um 17 21 54](https://user-images.githubusercontent.com/10075/93902953-6b451580-fcf8-11ea-967e-98b8fdf62528.png)

Node: v.14.9.0
Yarn: 1.22.5

**Comment by Aeon** [comment]
@h0jeZvgoxFepBQ2C look into the files `tmp/cache/webpacker/last-compilation-digest-development`, `tmp/cache/webpacker/last-compilation-digest-production`, etc.

Implementation details in https://github.com/rails/webpacker/blob/master/lib/webpacker/compiler.rb - the `fresh?` check uses this file at each run to determine whether recompilation is needed

**Comment by justin808** [comment]
We've got some other issues that concern this.

> Due to server and system constraints, we precompile our assets (sprockets + webpacker) before releasing new versions.

that's normal.

Please reopen if you have more details.
