### ISSUE TITLE
Setting the javascript_pack_tag host globally

### ISSUE THREAD

**Issue by abdelbk** [rails/webpacker#2739]
I can't seem to find a way to set the host for the javascript_pack_tag globally.

Setting `config.asset_host` works but I don't want to do that because I still want to serve stylesheets via the asset pipeline.

The other route I found is to set the environment variable WEBPACKER_ASSET_HOST which doesn't affect javascript_pack_tag.

Setting the `:host` option in the javascript_pack_tag works too but I don't want to set it everytime.

Is there another way to configure webpacker's assets host ?

**Comment by juliantrueflynn** [comment]
`javascript_pack_tag` is just a thin wrapper of `javascript_include_tag` ([source](https://github.com/rails/webpacker/blob/395ecf7945f464cdaa291680617a5dece11b5d63/lib/webpacker/helper.rb#L96)). `WEBPACKER_ASSET_HOST` is just utilizing same host that would be used ([source](https://github.com/rails/webpacker/blob/1b2ba329e429131e2dc960aefcce1a2d343f0115/lib/webpacker/compiler.rb#L107)). Rails doesn't given a separate global host for javascript files, they just have one for assets in general, webpacker is the same way.

I would recommend just creating a helper, for example `javascript_pack_with_myhost_tag`, and setting `:host` option there.

**Comment by abdelbk** [comment]
Thank you for the response. I thought I was missing something. I'll go with the helper solution.
