### ISSUE TITLE
Packed assets not loading

### ISSUE THREAD

**Issue by caseyprovost** [rails/webpacker#274]
I get this error when starting a new rails app with webpacker and react...

```
http://localhost:8080/application.js 404 (Client error)
```

You can find the repo here: `https://github.com/caseyprovost/react-geocoder`

I have puma running with `bundle exec puma -C config/puma.rb` and the webpack dev server running with `bin/webpack-dev-server`.

I just followed the instructions to do the most basic setup, and cannot get the webpack JS to load. I get a 404 in the browser.

**Comment by gauravtiwari** [comment]
Are you sure both processes are running?

```ruby
# Procfile with foreman
web: bundle exec rails s
webpacker: ./bin/webpack-dev-server
```

**Comment by gauravtiwari** [comment]
Btw, you have PG gem, but no database.yml in the repo?

**Comment by caseyprovost** [comment]
@gauravtiwari yup I am sure :) And I never include that database.yml file, but here is a template...


```ruby
default: &default
  adapter: postgresql
  encoding: unicode
  username: YOUR_POSTGRES_USERNAME
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: geocoder_dev

test:
  <<: *default
  database: geocoder_test

production:
  url: <%= ENV['DATABASE_URL'] %>
```

**Comment by gauravtiwari** [comment]
Strange! Because I just cloned the repo and ran following commands and all works - 

```
bundle
yarn 
foreman start -f Procfile
```

**Comment by caseyprovost** [comment]
So you see a hello world message? If you do then lets compare some versions...

```
node v7.9.0
yarn 0.23.2
```

**Comment by gauravtiwari** [comment]
Yepp. I was using 7.8.0, but upgraded and tried with 7.9.0 too and still works :)

**Comment by caseyprovost** [comment]
hmm that is interesting. What other compatibility issues could be causing it. I am using `ruby 2.3.1p112`

**Comment by gauravtiwari** [comment]
Could you please paste your chrome network tab screenshot? Is it plain 404? Could you also try accessing the pack - http://localhost:8080/application.js ?

**Comment by caseyprovost** [comment]
OMG. I found the issue. Apparently VLC Remote spawns a process for VideoLAN on port 8080 and it was causing a conflict. Sorry for the ruckus that is embarrassing.

**Comment by gauravtiwari** [comment]
No worries. Cool 👍  🍰
