### ISSUE TITLE
Automatically run web-dev-server script after rails server boots in development?

### ISSUE THREAD

**Issue by RailsCod3rFuture** [rails/webpacker#2741]
I tried running it with 

```
config.after_initialize do
  system('./bin/webpack-dev-server')
end
```

But, it stops the rails server from serving assets.

Anyone have a way of pulling this off successfully?

**Comment by tlatsas** [comment]
You can easily achieve this using [foreman](https://rubygems.org/gems/foreman).

Install the foreman gem and create a file named `Procfile` in the root of your project directory. Then edit the file to add all the components you need to launch like this:

```
rails: bin/rails server -b 0.0.0.0 -p 3000
webpack: bin/webpack-dev-server
```

Finally, run `foreman start`

**Comment by RailsCod3rFuture** [comment]
Thanks

**Comment by guillaumebriday** [comment]
Could this PR be closed ?
