### ISSUE TITLE
rake webpacker:install fails on Windows 10 with "Malformed version number string" citing node version.

### ISSUE THREAD

**Issue by drmartell** [rails/webpacker#2742]
"$ rake webpacker:install --trace
** Invoke webpacker:install (first_time)
** Invoke webpacker:check_node (first_time)
** Execute webpacker:check_node
rake aborted!
ArgumentError: Malformed version number string Actie code page: 1252
12.18.4
E:/Ruby26-x64/lib/ruby/2.6.0/rubygems/version.rb:212:in `initialize'
E:/Ruby26-x64/lib/ruby/2.6.0/rubygems/version.rb:203:in `new'
E:/Ruby26-x64/lib/ruby/2.6.0/rubygems/version.rb:203:in `new'
E:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/webpacker-4.3.0/lib/tasks/webpacker/check_node.rake:12:in `block (2 levels) in <top (required)>'
E:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `block in execute'
E:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `each'
E:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `execute'
E:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
E:/Ruby26-x64/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
E:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
E:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:243:in `block in invoke_prerequisites'
E:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:241:in `each'
E:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:241:in `invoke_prerequisites'
E:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
E:/Ruby26-x64/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
E:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
E:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:188:in `invoke'
E:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:160:in `invoke_task'
E:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
E:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `each'
E:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `block in top_level'
E:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:125:in `run_with_threads'
E:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:110:in `top_level'
E:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:83:in `block in run'
E:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'
E:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:80:in `run'
E:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
E:/Ruby26-x64/bin/rake:23:in `load'
E:/Ruby26-x64/bin/rake:23:in `<main>'
Tasks: TOP => webpacker:install => webpacker:check_node"

ruby -v
ruby 2.6.6p146 (2020-03-31 revision 67876) [x64-mingw32]

rails -v
Rails 6.0.3.3

node -v
v12.18.4

In searching for solutions to this, I've seen recommendations to update node and yarn, both of which I've done.

**Comment by artfuldodger** [comment]
Is upgrading to webpacker 5+ an option? It looks like the way the node version is checked was changed with webpacker 5 to starting using the [semantic_range gem](https://github.com/librariesio/semantic_range) which might help.
