### ISSUE TITLE
Stylesheets in Webpacker

### ISSUE THREAD

**Issue by renatodex** [rails/webpacker#275]
I have this killing doubt:

Why Rails still use Sprockets?
I dont understand why i should leave half of my assets in Webpacker and the other half on Sprockets.
Seems very odd to me.

Can`t Webpacker do everything that Sprockets do?

**Comment by gauravtiwari** [comment]
@renatodex  Please checkout this section - https://github.com/rails/webpacker#linking-to-static-assets Webpacker can do almost anything sprockets does so, you can choose either one depending on your need. 

And, you can use `module-resolver` babel plugin to link assets from rails assets more cleanly - https://github.com/tleunen/babel-plugin-module-resolver

**Comment by renatodex** [comment]
Woah, its a nice start!
Thans @gauravtiwari !

**Comment by gauravtiwari** [comment]
Document this in README/guide - #372
