### ISSUE TITLE
Open for PR for having react_typescript as generator?

### ISSUE THREAD

**Issue by juliantrueflynn** [rails/webpacker#2750]
If I were to do a PR for adding `react_typescript` generator, to replace having to run `webpack:install:react` then `webpack:install:typescript` separately, would this be accepted? (Of course assuming code looks good.)

The current process has users doing the following:
- `bundle exec rails webpack:install:react`
- `bundle exec rails webpack:install:typescript`
- Rename `hello_react.jsx` to `hello_react.tsx`

With that, typescript users don't need `prop-types` and `babel-plugin-transform-react-remove-prop-types`, which are added from `webpack:install:react`.

I'm hoping to optimize the process to just having to run `bundle exec rails webpack:install:react_typescript`.

I wanted to ask before doing a PR to see if this is a road the project would be open going down.

**Comment by justin808** [comment]
No more generators for this sort of thing.
