### ISSUE TITLE
when i starting to launch my rail server  it shows Configuration:"no webpacker was found" .....then i gave install webpacker command it shows"install node" Please help me to setup my webpacker and to install and set node in it

### ISSUE THREAD

**Issue by santhiyas19** [rails/webpacker#2753]
C:\Users\ELCOT\Desktop\rubyBox\web>rails server
=> Booting Puma
=> Rails 6.0.3.3 application starting in development
=> Run `rails server --help` for more startup options
Exiting
Traceback (most recent call last):
        49: from bin/rails:4:in `<main>'
        48: from bin/rails:4:in `require'
        47: from C:/Ruby/lib/ruby/gems/2.6.0/gems/railties-6.0.3.3/lib/rails/commands.rb:18:in `<top (required)>'
        46: from C:/Ruby/lib/ruby/gems/2.6.0/gems/railties-6.0.3.3/lib/rails/command.rb:46:in `invoke'
        45: from C:/Ruby/lib/ruby/gems/2.6.0/gems/railties-6.0.3.3/lib/rails/command/base.rb:69:in `perform'
        44: from C:/Ruby/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
        43: from C:/Ruby/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        42: from C:/Ruby/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        41: from C:/Ruby/lib/ruby/gems/2.6.0/gems/railties-6.0.3.3/lib/rails/commands/server/server_command.rb:138:in `perform'
        40: from C:/Ruby/lib/ruby/gems/2.6.0/gems/railties-6.0.3.3/lib/rails/commands/server/server_command.rb:138:in `tap'
        39: from C:/Ruby/lib/ruby/gems/2.6.0/gems/railties-6.0.3.3/lib/rails/commands/server/server_command.rb:147:in `block in perform'
        38: from C:/Ruby/lib/ruby/gems/2.6.0/gems/railties-6.0.3.3/lib/rails/commands/server/server_command.rb:37:in `start'
        37: from C:/Ruby/lib/ruby/gems/2.6.0/gems/railties-6.0.3.3/lib/rails/commands/server/server_command.rb:77:in `log_to_stdout'
        36: from C:/Ruby/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/server.rb:422:in `wrapped_app'
        35: from C:/Ruby/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/server.rb:249:in `app'
        34: from C:/Ruby/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/server.rb:349:in `build_app_and_options_from_config'
        33: from C:/Ruby/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
        32: from C:/Ruby/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
        31: from C:/Ruby/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
        30: from C:/Ruby/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
        29: from config.ru:3:in `block in <main>'
        28: from config.ru:3:in `require_relative'
        27: from C:/Users/ELCOT/Desktop/rubyBox/web/config/environment.rb:5:in `<top (required)>'
        26: from C:/Ruby/lib/ruby/gems/2.6.0/gems/railties-6.0.3.3/lib/rails/application.rb:363:in `initialize!'
        25: from C:/Ruby/lib/ruby/gems/2.6.0/gems/railties-6.0.3.3/lib/rails/initializable.rb:60:in `run_initializers'
        24: from C:/Ruby/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
        23: from C:/Ruby/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
        22: from C:/Ruby/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
        21: from C:/Ruby/lib/ruby/2.6.0/tsort.rb:347:in `call'
        20: from C:/Ruby/lib/ruby/2.6.0/tsort.rb:347:in `each'
        19: from C:/Ruby/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
        18: from C:/Ruby/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
        17: from C:/Ruby/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        16: from C:/Ruby/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
        15: from C:/Ruby/lib/ruby/gems/2.6.0/gems/railties-6.0.3.3/lib/rails/initializable.rb:61:in `block in run_initializers'
        14: from C:/Ruby/lib/ruby/gems/2.6.0/gems/railties-6.0.3.3/lib/rails/initializable.rb:32:in `run'
        13: from C:/Ruby/lib/ruby/gems/2.6.0/gems/railties-6.0.3.3/lib/rails/initializable.rb:32:in `instance_exec'
        12: from C:/Ruby/lib/ruby/gems/2.6.0/gems/webpacker-4.3.0/lib/webpacker/railtie.rb:84:in `block in <class:Engine>'
        11: from C:/Ruby/lib/ruby/gems/2.6.0/gems/webpacker-4.3.0/lib/webpacker.rb:35:in `bootstrap'
        10: from C:/Ruby/lib/ruby/gems/2.6.0/gems/webpacker-4.3.0/lib/webpacker/commands.rb:25:in `bootstrap'
         9: from C:/Ruby/lib/ruby/gems/2.6.0/gems/webpacker-4.3.0/lib/webpacker/manifest.rb:18:in `refresh'
         8: from C:/Ruby/lib/ruby/gems/2.6.0/gems/webpacker-4.3.0/lib/webpacker/manifest.rb:83:in `load'
         7: from C:/Ruby/lib/ruby/gems/2.6.0/gems/webpacker-4.3.0/lib/webpacker/configuration.rb:51:in `public_manifest_path'
         6: from C:/Ruby/lib/ruby/gems/2.6.0/gems/webpacker-4.3.0/lib/webpacker/configuration.rb:47:in `public_output_path'
         5: from C:/Ruby/lib/ruby/gems/2.6.0/gems/webpacker-4.3.0/lib/webpacker/configuration.rb:43:in `public_path'
         4: from C:/Ruby/lib/ruby/gems/2.6.0/gems/webpacker-4.3.0/lib/webpacker/configuration.rb:84:in `fetch'
         3: from C:/Ruby/lib/ruby/gems/2.6.0/gems/webpacker-4.3.0/lib/webpacker/configuration.rb:88:in `data'
         2: from C:/Ruby/lib/ruby/gems/2.6.0/gems/webpacker-4.3.0/lib/webpacker/configuration.rb:92:in `load'
         1: from C:/Ruby/lib/ruby/gems/2.6.0/gems/webpacker-4.3.0/lib/webpacker/configuration.rb:92:in `read'
C:/Ruby/lib/ruby/gems/2.6.0/gems/webpacker-4.3.0/lib/webpacker/configuration.rb:92:in `read': No such file or directory @ rb_sysopen - C:/Users/ELCOT/Desktop/rubyBox/web/config/webpacker.yml (Errno::ENOENT)
        48: from bin/rails:4:in `<main>'
        47: from bin/rails:4:in `require'
        46: from C:/Ruby/lib/ruby/gems/2.6.0/gems/railties-6.0.3.3/lib/rails/commands.rb:18:in `<top (required)>'
        45: from C:/Ruby/lib/ruby/gems/2.6.0/gems/railties-6.0.3.3/lib/rails/command.rb:46:in `invoke'
        44: from C:/Ruby/lib/ruby/gems/2.6.0/gems/railties-6.0.3.3/lib/rails/command/base.rb:69:in `perform'
        43: from C:/Ruby/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
        42: from C:/Ruby/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        41: from C:/Ruby/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        40: from C:/Ruby/lib/ruby/gems/2.6.0/gems/railties-6.0.3.3/lib/rails/commands/server/server_command.rb:138:in `perform'
        39: from C:/Ruby/lib/ruby/gems/2.6.0/gems/railties-6.0.3.3/lib/rails/commands/server/server_command.rb:138:in `tap'
        38: from C:/Ruby/lib/ruby/gems/2.6.0/gems/railties-6.0.3.3/lib/rails/commands/server/server_command.rb:147:in `block in perform'
        37: from C:/Ruby/lib/ruby/gems/2.6.0/gems/railties-6.0.3.3/lib/rails/commands/server/server_command.rb:37:in `start'
        36: from C:/Ruby/lib/ruby/gems/2.6.0/gems/railties-6.0.3.3/lib/rails/commands/server/server_command.rb:77:in `log_to_stdout'
        35: from C:/Ruby/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/server.rb:422:in `wrapped_app'
        34: from C:/Ruby/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/server.rb:249:in `app'
        33: from C:/Ruby/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/server.rb:349:in `build_app_and_options_from_config'
        32: from C:/Ruby/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
        31: from C:/Ruby/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
        30: from C:/Ruby/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
        29: from C:/Ruby/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
        28: from config.ru:3:in `block in <main>'
        27: from config.ru:3:in `require_relative'
        26: from C:/Users/ELCOT/Desktop/rubyBox/web/config/environment.rb:5:in `<top (required)>'
        25: from C:/Ruby/lib/ruby/gems/2.6.0/gems/railties-6.0.3.3/lib/rails/application.rb:363:in `initialize!'
        24: from C:/Ruby/lib/ruby/gems/2.6.0/gems/railties-6.0.3.3/lib/rails/initializable.rb:60:in `run_initializers'
        23: from C:/Ruby/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
        22: from C:/Ruby/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
        21: from C:/Ruby/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
        20: from C:/Ruby/lib/ruby/2.6.0/tsort.rb:347:in `call'
        19: from C:/Ruby/lib/ruby/2.6.0/tsort.rb:347:in `each'
        18: from C:/Ruby/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
        17: from C:/Ruby/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
        16: from C:/Ruby/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        15: from C:/Ruby/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
        14: from C:/Ruby/lib/ruby/gems/2.6.0/gems/railties-6.0.3.3/lib/rails/initializable.rb:61:in `block in run_initializers'
        13: from C:/Ruby/lib/ruby/gems/2.6.0/gems/railties-6.0.3.3/lib/rails/initializable.rb:32:in `run'
        12: from C:/Ruby/lib/ruby/gems/2.6.0/gems/railties-6.0.3.3/lib/rails/initializable.rb:32:in `instance_exec'
        11: from C:/Ruby/lib/ruby/gems/2.6.0/gems/webpacker-4.3.0/lib/webpacker/railtie.rb:84:in `block in <class:Engine>'
        10: from C:/Ruby/lib/ruby/gems/2.6.0/gems/webpacker-4.3.0/lib/webpacker.rb:35:in `bootstrap'
         9: from C:/Ruby/lib/ruby/gems/2.6.0/gems/webpacker-4.3.0/lib/webpacker/commands.rb:25:in `bootstrap'
         8: from C:/Ruby/lib/ruby/gems/2.6.0/gems/webpacker-4.3.0/lib/webpacker/manifest.rb:18:in `refresh'
         7: from C:/Ruby/lib/ruby/gems/2.6.0/gems/webpacker-4.3.0/lib/webpacker/manifest.rb:83:in `load'
         6: from C:/Ruby/lib/ruby/gems/2.6.0/gems/webpacker-4.3.0/lib/webpacker/configuration.rb:51:in `public_manifest_path'
         5: from C:/Ruby/lib/ruby/gems/2.6.0/gems/webpacker-4.3.0/lib/webpacker/configuration.rb:47:in `public_output_path'
         4: from C:/Ruby/lib/ruby/gems/2.6.0/gems/webpacker-4.3.0/lib/webpacker/configuration.rb:43:in `public_path'
         3: from C:/Ruby/lib/ruby/gems/2.6.0/gems/webpacker-4.3.0/lib/webpacker/configuration.rb:84:in `fetch'
         2: from C:/Ruby/lib/ruby/gems/2.6.0/gems/webpacker-4.3.0/lib/webpacker/configuration.rb:88:in `data'
         1: from C:/Ruby/lib/ruby/gems/2.6.0/gems/webpacker-4.3.0/lib/webpacker/configuration.rb:91:in `load'
C:/Ruby/lib/ruby/gems/2.6.0/gems/webpacker-4.3.0/lib/webpacker/configuration.rb:95:in `rescue in load': Webpacker configuration file not found C:/Users/ELCOT/Desktop/rubyBox/web/config/webpacker.yml. Please run rails webpacker:install Error: No such file or directory @ rb_sysopen - C:/Users/ELCOT/Desktop/rubyBox/web/config/webpacker.yml (RuntimeError)

C:\Users\ELCOT\Desktop\rubyBox\web>rails webpacker:install

**Comment by guillaumebriday** [comment]
Could you please format the response with a code block please ?
