### ISSUE TITLE
Getting Error In asset precompile step : NoMethodError (undefined method `+' for nil:NilClass) on v5.2.1

### ISSUE THREAD

**Issue by Priyanka4328** [rails/webpacker#2758]
I was getting above error in asset precompile step during deployment.

I have also got know to the root cause of this error.

Can i can raise PR for the same.

**Comment by navidemad** [comment]
In your webpacker.yml, change the key
`resolved_paths:`
to
`additional_paths:`

**Comment by guillaumebriday** [comment]
I think this issue can be closed
