### ISSUE TITLE
How to customize babel config with new webpacker configuration?

### ISSUE THREAD

**Issue by pustovalov** [rails/webpacker#2775]
Hey,

injection of babel config recently was changed:

https://github.com/rails/webpacker/pull/2633/files#diff-5b9c334d542cd6b11f4035ee36a8630bc46c395443623be9cf4e7acc9b0751bcR45

>Running webpacker:install will now add browserslist and babel configuration into package.json instead of copying files.

How the user can now extend default babel configuration? For example to add `React Refresh Webpack Plugin
`
https://github.com/rails/webpacker/blob/master/docs/react.md#react-refresh-webpack-plugin

>Update babel.config.js adding
```
plugins: [
  process.env.WEBPACK_DEV_SERVER && 'react-refresh/babel',
  // other plugin
```

but new users will not have `babel.config.js`, `process.env` not available inside `package.json`

How the user can add some babel plugin for a specific environment?

after these changes default setup has been simplified, but it became more difficult to add something custom

**Comment by tomprats** [comment]
This was definitely easier than I thought. I was worried I'd have to copy and paste the default setup, but you can just do something like this in your babel.config.js:

```
module.exports = function config(api) {
  plugins: [
    api.env('development') && 'react-refresh/babel',
  ].filter(Boolean),
  presets: [
    "./node_modules/@rails/webpacker/package/babel/preset.js"
  ]
}
```

Or if you don't need the environment, you can just use an object with whatever plugins

```
module.exports = {
  plugins: [
    "@babel/plugin-proposal-export-default-from"
  ],
  presets: [
    "./node_modules/@rails/webpacker/package/babel/preset.js"
  ]
}
```

**Comment by justin808** [comment]
I think this is really a documentation issue.

I added a PR to address that: https://github.com/rails/webpacker/pull/3247.
