### ISSUE TITLE
Allow TypeScript webpack configuration files

### ISSUE THREAD

**Issue by bencallaway** [rails/webpacker#2787]
My Rails application shares some arbitrary data with my webpack configuration. The frontend is predominately written in TypeScript, and it would be desirable and simpler to close the loop and use TS as the language for these shared files. Webpack allows TypeScript as a [configuration language](https://v4.webpack.js.org/configuration/configuration-languages/), and I've been able to do so without too much fuss. I was able to keep webpacker running by just hacking the expected path of my webpack config [here](https://github.com/rails/webpacker/blob/31b7a6f31e38d0d45b0e2ab162f28db1afc5ffac/lib/webpacker/runner.rb#L14), which really only required me changing the file extension to `.ts`.

I am happy to work on a PR with a more thoughtful way of allowing different configuration paths, but I wanted to run the idea by you all first. Would this have any other implications beyond how the runners work?

It seems TS webpack config files can be allowed by just permitting a means of overriding the path to the webpack config for any/all environments. I can imagine this being an option in webpacker.yml and/or and ENV variable and/or a command line argument that would be used to override the default.

How does this sound?

**Comment by justin808** [comment]
I think TS is already supported.

**Comment by justin808** [comment]
Feel free to submit a PR so we can see what this would look like.

**Comment by justin808** [comment]
Feel free to reopen this issue here: 
https://github.com/shakacode/shakapacker/issues
