### ISSUE TITLE
Memory Leak issue with hash output file name

### ISSUE THREAD

**Issue by davidfabreguette** [rails/webpacker#2803]
Hi !
As I was struggling with a memory leak issue on webpack development environment on a slightly big project,
I found this issue on github : https://github.com/webpack/webpack-dev-server/issues/438

I inspected webpacker generated config, and found those "[hash]" in output files names.
So I decided to remove those just to check if it was causing those memory leaks and ... tada ! 

That seems to be the origin of my problem. Here's my webpack development config :

```javascript
const config = environment.toWebpackConfig();
config.devtool = 'inline-cheap-source-map';
config.output = {
    ...config.output,
    futureEmitAssets: true,
    filename: 'js/[name].js',
    chunkFilename: 'js/[name].chunk.js',
    hotUpdateChunkFilename: 'js/[id].hot-update.js'
}
module.exports = config;
```

Can someone explain to me :
- Why do we have [hash] in output file names ?
- Is it normal ? and ok to remove them ?

**Comment by davidfabreguette** [comment]
And this is my concern : https://github.com/webpack/webpack-dev-server/issues/438#issuecomment-236845226

**Comment by justin808** [comment]
Please reopen if still an issue with latest updates.
