### ISSUE TITLE
Unable to use scss in Vue single file components.

### ISSUE THREAD

**Issue by sgaxr** [rails/webpacker#2806]
I am unable to get Vue single file components to work with extract_css (`<style lang="scss">`). I'm not sure if this is an issue with my setup, or an issue with webpacker. Any help would be greatly appreciated.

Here are the exact steps I've followed to attempt to get this to work:

**1 - Create a new rails project.**

```bash
$ rails new example-app --webpack=vue
```

**2 - Add yarn dependencies.**

```bash
$ yarn add pug pug-plain-loader sass-loader
```

**3 - Setup loaders.**

config/webpack/loaders/sass.js
```js
module.exports = {
  test: /\.(sass|scss)(\.erb)?$/,
  use: ['vue-style-loader', 'css-loader', 'sass-loader']
}
```

config/webpack/loaders/pug.js
```js
module.exports = {
  test: /\.pug(\.erb)?$/,
  use: [{
    loader: 'pug-plain-loader'
  }]
}
```

config/webpack/loaders/vue.js
```js
module.exports = {
  test: /\.vue(\.erb)?$/,
  use: [{
    loader: 'vue-loader',
    options: { extract_css: true }
  }]
}
```

config/webpack/environment.js
```js
const { environment } = require('@rails/webpacker')
const { VueLoaderPlugin } = require('vue-loader')
const vue = require('./loaders/vue')
const sass = require('./loaders/sass')
const pug = require('./loaders/pug')

environment.plugins.prepend('VueLoaderPlugin', new VueLoaderPlugin())
environment.loaders.prepend('vue', vue)
environment.loaders.prepend('sass', sass)
environment.loaders.prepend('pug', pug)

module.exports = environment
```

**4 - Change webpacker config.**

config/webpacker.yml
```yaml
# change line 20
  extract_css: true
```

**5 - Home controller.**

```bash
$ rails g controller home index
```

config/routes.rb
```rb
  root to: 'home#index'
```

**6 - Add pack tags to app layout**

app/views/layouts/application.html.erb
```erb
<%= javascript_pack_tag 'hello_vue' %>
<%= stylesheet_pack_tag 'hello_vue' %>
```

**7 - Change template language to pug**

app/javascript/app.vue
```vue
<template lang="pug">
  #app
    p {{ message }}
</template>
```

At this point, everything is working exactly as expected.

**8 - Change style language to scss**

app/javascript/app.vue
```vue
<style scoped lang="scss">
p {
  color: red; /* added to verify change */
  font-size: 2em;
  text-align: center;
}
</style>
```

At this point, if you start the webpack dev server (or just compile with webpack), no css files are generated. Removing `lang="scss"` from the component results in css files being generated again.

**Comment by sgaxr** [comment]
Oh man, I was just googling around trying to solve this problem and I got so excited to see that someone else was having the exact same problem only to realize that this is a ticket I opened up a few months ago.

**Comment by sgaxr** [comment]
Gah, I got myself again! X{

**Comment by gregorvand** [comment]
I also have this issue @sgaxr - any luck?

**Comment by sgaxr** [comment]
@gregorvand No, no luck. I've only been able to get around this by not using scss.

**Comment by justin808** [comment]
Given that rails/webpacker will not be maintaining framework support, I'm closing this issue.

CC: @guillaumebriday
