### ISSUE TITLE
Update Docs for Rendering Partials in erb files

### ISSUE THREAD

**Issue by mvastola** [rails/webpacker#2808]
So I'd submit a PR for this but I'm not confident enough that this has no unintended consequences. (Happy to do so if requested, however.)

Basically, the docs have [example code](https://github.com/rails/webpacker/blob/master/docs/assets.md#import-from-sprockets-using-helpers)  for using helpers in `.js.erb` files (or, presumably, any `.*.erb` file):
> ## Import from Sprockets using helpers
> ```erb
> <%# app/javascript/my_pack/example.js.erb %>
>
> <% helpers = ActionController::Base.helpers %>
> const railsImagePath = "<%= helpers.image_path('rails.png') %>"
> ```

I just tried to use this idea to render a partial into a JS file, only to find it didn't work (apparently invoking it this way causes the view paths not to be populated.

I found instead, however, that replacing `ActionController::Base.helpers` with `ActionController::Base.new.helpers`, works correctly. 
I further realized that using `ApplicationController` in lieu of `ActionController::Base` seemed to also carry an added benefit in that app-specific helpers became available.

Is there some subtle drawback that makes using `ApplicationController.new.helpers` inadvisable? Or would it be okay to use this (ostensibly) superior invocation in the docs?

**Comment by justin808** [comment]
Please open a doc PR if you're confident.

**Comment by justin808** [comment]
Feel free to reopen this issue here: 
https://github.com/shakacode/shakapacker/issues
