### ISSUE TITLE
Freezes on **Execute Environment during deployment

### ISSUE THREAD

**Issue by von-christian** [rails/webpacker#2809]
I am currently having an issue with webpacker during deployment process. It freezes on the **Execute environment step
Rails 5.2 
mina 1.2.3
webpacker 3.6.0
node 10.23.0
yarn 1.22.5

` ** Invoke assets:precompile (first_time)`
` ** Invoke assets:environment (first_time)`
`** Execute assets:environment`
 `** Invoke environment (first_time)`
 `** Execute environment`

Thank you for the help in advance

**Comment by pedrofurtado** [comment]
Hey @von-christian ! 👋 

Unfortunately you are using a very old version of webpacker (v3.6.0)😢

Is it possible for you to upgrade the webpacker gem in your project?

In repo there are some upgrade guides for each major version until 5.x (latest stable major version):

https://github.com/rails/webpacker/tree/v4.0.0#upgrading
https://github.com/rails/webpacker/tree/v5.0.0#upgrading

Let us know some more details about this situation, or the result of your upgrade🤝
