### ISSUE TITLE
webpacker 5.2.1 still shows node-sass as dependency

### ISSUE THREAD

**Issue by SmartManoj** [rails/webpacker#2811]
[As it moved to sass](https://github.com/rails/webpacker/commit/950979a2ee7e1ebc819ce226184637c4cfc685bd#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519), how it still shows?
![image](https://user-images.githubusercontent.com/7231077/102485861-2f6ae380-408e-11eb-8508-8c84b3db1a59.png)

**Comment by JoshRobertson** [comment]
There hasn't been a new version published including that change, or any change in the master branch since 5.2.1 was published back in August.

**Comment by SmartManoj** [comment]
last release on Aug 17
committed on Aug 31
