### ISSUE TITLE
When using a custom node_modules directory, babel-loader writes its cache to the default node_modules directory

### ISSUE THREAD

**Issue by nickjj** [rails/webpacker#2812]
I'm using Rails 6.1.0, and my `package.json` looks like this:

```json
{
  "name": "myapp",
  "private": true,
  "dependencies": {
    "@rails/actioncable": "6.0.0",
    "@rails/activestorage": "6.0.0",
    "@rails/ujs": "6.0.0",
    "@rails/webpacker": "rails/webpacker#4210dd56",
    "turbolinks": "5.2.0"
  },
  "version": "0.1.0",
  "devDependencies": {
    "webpack-cli": "^4.0.0",
    "webpack-dev-server": "3.11.0"
  }
}
```

I start things up by running `"./bin/webpack --watch --progress --color"` and I haven't modified `./bin/webpack`.

I've added a `.yarnrc` to the root of my Rails project with `--modules-folder /node_modules`. My app is running in Docker and I wanted to write node_modules out to the root file system path to avoid volume mounting it back to the host.

Everything works except when I start the Rails application this directory gets immediately created in the root of my Rails project:

```
node_modules/
  .cache/
    babel-loader/
      abc123.json
      xyz456.json
```

I would have expected those files to be written to the custom `/node_modules/.cache` directory. I haven't looked into Webpacker's source code but do you have a relative `node_modules` path hard coded somewhere?

A temporary workaround is to add `node_modules/` to your `.dockerignore` but ideally it should use the configured `node_modules` directory or perhaps the `tmp/cache/webpacker` directory to store these files right?

**Comment by pedrofurtado** [comment]
Hey, @nickjj! 👋 

Using a symbolic link of default `node_modules` folder to another location in container, is a good solution for this scenario?

Let me know your results on this 🤝

**Comment by nickjj** [comment]
Hi,

A symlink would mean `node_modules/` would wind up being volume mounted back to the host, unless I misunderstood your suggestion? That wouldn't be ideal because now there's going to be a billion files on the host's file system.
