### ISSUE TITLE
Production fails to compile when testing-library is in devDependencies

### ISSUE THREAD

**Issue by crice88** [rails/webpacker#2813]
Running into an issue when trying to run my app in production. Webpack fails to find testing-library because it's not included in dependencies. In my tsconfig I have it excluding those files, yet they still continue to be compiled. Any thoughts?

```
{
  "compilerOptions": {
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es6", "dom"],
    "module": "es6",
    "moduleResolution": "node",
    "sourceMap": true,
    "target": "es5",
    "jsx": "react",
    "noEmit": true,
    "allowSyntheticDefaultImports": true
  },
  "exclude": [
    "**/*.spec.ts",
    "**/*.spec.tsx",
    "node_modules",
    "vendor",
    "public"
  ],
  "compileOnSave": false
}
```

My tests are located near their modules so, `app/javascript/packs/hello/__tests__/hello.spec.tsx`

All other is config is default besides my package.json which includes this Jest config...

```
"jest": {
    "collectCoverageFrom": [
      "app/javascript/**/*.{js,jsx,ts,tsx}",
      "!<rootDir>/node_modules/"
    ],
    "modulePathIgnorePatterns": [
      "config/webpack"
    ],
    "roots": [
      "app/javascript"
    ],
    "moduleDirectories": [
      "node_modules",
      "app/javascript"
    ],
    "moduleNameMapper": {
      "\\.(jpg|ico|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "<rootDir>/app/javascript/packs/__mocks__/fileMock.ts"
    },
    "coverageThreshold": {
      "global": {
        "branches": 70,
        "functions": 70,
        "lines": 70,
        "statements": 70
      }
    }
  }
```

**Comment by rossta** [comment]
Any file in the packs directory is treated as an entry point per Webpacker convention. You should probably start with just one file, like application.js, and move all your modules and tests to another directory under `app/javascript`, e.g., `app/javascript/src`. 

This [blog post](https://rossta.net/blog/overpacking-a-common-webpacker-mistake.html) explains the problem you have in more detail.

**Comment by crice88** [comment]
Boom that was it! Thanks so much. After moving the files out, had to do a bit of finagling with the assets, but worked like a charm!
