### ISSUE TITLE
Please update docs to reflect 6.x

### ISSUE THREAD

**Issue by tagliala** [rails/webpacker#2816]
Hi,

I was trying to migrate Webpacker from 5.x to 6.x, but I can see that the configuration changed

In example, I think that the following should be updated:
- https://github.com/rails/webpacker/blob/v5.2.0/docs/css.md#resolve-url-loader

I was also used to customize `environment.js` by prepending some plugins in the following way:

```js
// Webpacker 5
const { environment } = require('@rails/webpacker')

environment.plugins.prepend(
  // ...
```

But this does not work anymore.

Since I'm not a JavaScript developer, it is not straightforward for me understand what to change. A migration guide would be appreciated

Thanks for any help you can provide

**Comment by gauravtiwari** [comment]
Thanks @tagliala that's the plan to do next

**Comment by pustovalov** [comment]
I think it will also be useful to show an example of how you can add a custom webpack plugin

**Comment by gauravtiwari** [comment]
Please see Readme and lets fill in the gaps together 🙏

**Comment by tagliala** [comment]
Hi @gauravtiwari 

Thanks for the upgrading guide. It helps together with readme, but I have still questions that are probably caused by my poor understanding of the webpack pipeline

I think that for my use case I need:
- css
- postcss (autoprefixer and stylelint)
- sass

So I run the three relevant lines, but with

> `yarn add postcss-loader`

This complains about missing postcss:

```
warning " > postcss-loader@4.1.0" has unmet peer dependency "postcss@^7.0.0 || ^8.0.1".
```

Should it be: `yarn add postcss postcss-loader`? If yes, should happen the same with `sass-loader` and `sass`?

Then, in my use case I have the following custom configuration:

```js
// resolve-url-loader must be used before sass-loader
environment.loaders.get('sass').use.splice(-1, 0, {
  loader: 'resolve-url-loader'
});

environment.loaders.append('handlebars-loader', {
  test: /\.handlebars$/,
  use: 'handlebars-loader'
})
```

By reading both upgrading guide and readme, I cannot understand how to merge the previous custom config with base webpackConfig, because they are not hash objects

Ref to webpack 5 custom configuration:
- https://github.com/diowa/ruby2-rails6-bootstrap-heroku/blob/master/config/webpack/environment.js
- https://github.com/diowa/ruby2-rails6-bootstrap-heroku/blob/master/config/webpack/development.js

**Comment by gauravtiwari** [comment]
@tagliala I have just updated docs

regarding `resolve-url-loader`, you have to add it manually but perhaps we can support that out of the box and all you need to do is install the package.

**Comment by tagliala** [comment]
Hi @gauravtiwari 

Thanks again for the updates. I've submitted an opinionated PR at #2831 for a small change

>  you have to add it manually but perhaps we can support that out of the box and all you need to do is install the package.

That would be good if that loader it is still widely used by the webpacker community

As per my original request, it is not about `resolve-url-loader` specifically. I would like to improve the documentation in a way that it is clear to RoR developers how it is possible to customize webpacker configuration, because tomorrow I may need another loader (in a specific position, e.g., before `sass-loader`) and, if that is not supported out of the box, then I will be at the same point

I will give another read to the docs and try to understand how to manually add loaders and plugins

**Comment by OscarBarrett** [comment]
RE the `resolve-url-loader` configuration, `attempts` is no longer an option. So you can just add the following

```js
environment.loaders.get('sass').use.splice(-1, 0, {
  loader: 'resolve-url-loader'
});
```

**Comment by dkniffin** [comment]
Just to point it out for anyone else who stumbles upon this issue when looking for how to upgrade to 6.0, here's the upgrade guide doc: https://github.com/rails/webpacker/blob/master/6_0_upgrade.md

**Comment by dkniffin** [comment]
Should there be a step in that upgrade guide to review everything in here? https://webpack.js.org/migrate/5/
