### ISSUE TITLE
Webpacker Error: Cannot read property .toWebpackConfig of undefined

### ISSUE THREAD

**Issue by dashcraft** [rails/webpacker#2817]
I added a new dependency, pdf-lib, and now webpack/webpacker is blowing up.

ruby version 2.7.0
node version 14.15.3

dependencies:
"dependencies": {
    "@rails/actioncable": "^6.0.0",
    "@rails/actiontext": "^6.0.0",
    "@rails/activestorage": "^6.0.0",
    "@rails/ujs": "^6.0.0",
    "@rails/webpacker": "github:rails/webpacker",
    "@tailwindcss/aspect-ratio": "^0.2.0",
    "@tailwindcss/forms": "^0.2.1",
    "@tailwindcss/typography": "^0.3.1",
    "autoprefixer": "^10.0.2",
    "clipboard": "^2.0.4",
    "core-js": "3",
    "flatpickr": "^4.6.1",
    "js-cookie": "^2.2.0",
    "jstz": "^2.0.0",
    "local-time": "^2.1.0",
    "pdf-lib": "^1.12.0",
    "postcss": "^8.1.7",
    "slim-select": "^1.23.1",
    "sortablejs": "^1.12.0",
    "stimulus": "^2.0.0",
    "stimulus-flatpickr": "^1.2.4",
    "tailwindcss": "^2.0.1",
    "tailwindcss-stimulus-components": "^2.0.0",
    "tippy.js": "^6.0.0",
    "tributejs": "^5.0.0",
    "trix": "^1.2.0",
    "turbolinks": "^5.2.0",
    "webpack": "^5.11.0"
  },

error

TypeError: Cannot read property 'toWebpackConfig' of undefined
    at Object.<anonymous> (/config/webpack/development.js:5:30)
    
config/development

```
process.env.NODE_ENV = process.env.NODE_ENV || 'development'

const { environment } = require('@rails/webpacker')



module.exports = environment.toWebpackConfig()

```

/config/environment
```

const { environment } = require('@rails/webpacker')


module.exports = environment
```

**Comment by gauravtiwari** [comment]
Please upgrade to version 6.0 - see Readme

**Comment by rossta** [comment]
@dashcraft can this issue be closed?

**Comment by dashcraft** [comment]
Yes, sorry, it was a version issue. There are a handful of packages that point to the github head, vs a version which obviously broke during the major version release.
