### ISSUE TITLE
In webpacker 6.x, import content of json static files not work anymore

### ISSUE THREAD

**Issue by pedrofurtado** [rails/webpacker#2818]
@gauravtiwari hey! 🤝 

In webpacker 5.x, this line works:

```javascript
import myContent from './my-json-file.json'
console.log(myContent); // -> This returns the JSON itself, for: example: { a: 1, b: 2 }
```

But in webpacker 6.x, this same not works:

```javascript
import myContent from './my-json-file.json'
console.log(myContent); // -> This returns a Module Object, for example: Module {default: {…}, __esModule: true, Symbol(Symbol.toStringTag): "Module"}

console.log(myContent.default); // -> This returns the path of file, instead of content. example: "/packs/static/v0954jv844tgr.json"
```

**Comment by gauravtiwari** [comment]
Hi @pedrofurtado 

Looks like we need raw loader equivalent for JSON: https://webpack.js.org/guides/asset-modules/

**Comment by pedrofurtado** [comment]
This loader will be available inside webpacker gem? Ou will be needed that us do it in our application?

**Comment by pedrofurtado** [comment]
@gauravtiwari Doubt: This PR ( https://github.com/rails/webpacker/pull/2827 ) rollback the behavior of 5.x of gem in this scenario? 👍

**Comment by gauravtiwari** [comment]
<img width="456" alt="Screenshot 2020-12-23 at 17 33 57" src="https://user-images.githubusercontent.com/771039/103023028-0c847780-4545-11eb-8666-aaf9f2c5717b.png">

**Comment by pedrofurtado** [comment]
Good news! I will download the 6.0.0-beta1 here, to test 🤝

**Comment by pedrofurtado** [comment]
🎉 🎉 🎉 🎉 🎉  It worked! 🏆
