### ISSUE TITLE
Webpacker can't find application.js in D:/ROR/blog/public/packs/manifest.json in Ruby on Rails 6.1

### ISSUE THREAD

**Issue by youthtech-228** [rails/webpacker#2825]
I am new in Rails 6. I followed their document(https://guides.rubyonrails.org/getting_started.html) but I had some errors related to webpacker. 
I made a route on routes file(config/routes.rb)

`````````````````````````````
Rails.application.routes.draw do
  get "/articles", to: "articles#index"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
````````````````````````````````````

And I created ArticlesController and its index action
`bin/rails generate controller Articles index --skip-routes`

And I run the server

`bin/rails server`

when I visit http://localhost:3000/articles, this error happend.
`````````````````````````````````````````````
Webpacker::Manifest::MissingEntryError in Articles#index

Showing D:/ROR/blog/app/views/layouts/application.html.erb where line #10 raised:

Webpacker can't find application.js in D:/ROR/blog/public/packs/manifest.json. Possible causes:
1. You want to set webpacker.yml value of compile to true for your environment
   unless you are using the `webpack -w` or the webpack-dev-server.
2. webpack has not yet re-run to reflect updates.
3. You have misconfigured Webpacker's config/webpacker.yml file.
4. Your webpack configuration is not creating a manifest.
Your manifest contains:
{
}
``````````````````````````````````````````````````````````
![Screenshot 2020-12-23 180722](https://user-images.githubusercontent.com/68208337/102986266-80c21980-454b-11eb-999b-47bba4a8cdbe.png)

**Comment by Diogomartf** [comment]
what's your gemfile?

**Comment by youthtech-228** [comment]
`````````````````````````

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.2'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 6.1.0'
# Use sqlite3 as the database for Active Record
gem 'sqlite3', '~> 1.4'
# Use Puma as the app server
gem 'puma', '~> 5.0'
# Use SCSS for stylesheets
gem 'sass-rails', '>= 6'
# Transpile app-like JavaScript. Read more: https://github.com/rails/webpacker
gem 'webpacker', '~> 5.0'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.7'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Active Storage variant
# gem 'image_processing', '~> 1.2'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.4', require: false

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '>= 4.1.0'
  # Display performance information such as SQL time and flame graphs for each request in your browser.
  # Can be configured to work on production as well see: https://github.com/MiniProfiler/rack-mini-profiler/blob/master/README.md
  gem 'rack-mini-profiler', '~> 2.0'
end

group :test do
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '>= 3.26'
  gem 'selenium-webdriver'
  # Easy installation and use of web drivers to run system tests with browsers
  gem 'webdrivers'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

``````````````````````````````````````

**Comment by youthtech-228** [comment]
This is the Gemfile.

**Comment by Diogomartf** [comment]
I'm currently with same problem.

I think you can solve it by installing the gem from the master branch
`gem 'webpacker', git: 'https://github.com/rails/webpacker.git`
But I would like to avoid this route.

Does someone has an idea of why this is happening?

**Comment by pedrofurtado** [comment]
Hello @youthtech-228 ! 👋 

I don't have much details about your problem, but I guess (looking your printscreen) this error is occuring with you because you did not compile the assets yet. Or you dont have created the file `app/javascript/packs/application.js`.

Could you try execute `rails webpacker:compile` and refresh the page to check if the error persists? This error is commonly related to this.

If the error persist, please let me know, and then we can get some more informations to investigate the root cause 🔍

**Comment by Destinyspell189** [comment]
I have this exact same issue and I tried to run `rails webpacker:compile` but nothing happened. I even downgraded my rails version to 5.3.2.

**Comment by pedrofurtado** [comment]
@youthtech-228 @Destinyspell189 If is possible, could you provide to us a reproducible repo that occurs this error on it?

Sorry, I really didn't understand well the situation yet 🙈 But with the repo, it will be more easy to help you guys 🤝

**Comment by youthtech-228** [comment]
> Hello @youthtech-228 ! 👋
> 
> I don't have much details about your problem, but I guess (looking your printscreen) this error is occuring with you because you did not compile the assets yet. Or you dont have created the file `app/javascript/packs/application.js`.
> 
> Could you try execute `rails webpacker:compile` and refresh the page to check if the error persists? This error is commonly related to this.
> 
> If the error persist, please let me know, and then we can get some more informations to investigate the root cause 🔍
> 
> Thanks! 🤝

Thanks

**Comment by MattNemeth** [comment]
any luck getting this solved? I was able to get the tutorial working on an Ubuntu (20.04 LTS) virtualbox machine but when trying to get RoR working on a raspberry pi 4 (Ubuntu 20.10) it gives this error and I don't know how to solve it.

**Comment by kurt-mueller-osumc** [comment]
> Hello @youthtech-228 ! 👋
> 
> I don't have much details about your problem, but I guess (looking your printscreen) this error is occuring with you because you did not compile the assets yet. Or you dont have created the file `app/javascript/packs/application.js`.
> 
> Could you try execute `rails webpacker:compile` and refresh the page to check if the error persists? This error is commonly related to this.
> 
> If the error persist, please let me know, and then we can get some more informations to investigate the root cause 🔍
> 
> Thanks! 🤝

The readme says to place the files in `app/packs`, not `app/javascript/packs`.

**Comment by MattNemeth** [comment]
I ended up finding a fix for my issue through this link: https://discuss.rubyonrails.org/t/pretty-astonishing/76850

I don't know if you are running into the same issue but it is worth a shot and maybe anyone else who stumbles here might find it useful. It seems that upon using the default installation process for RoR, it grabs a beta version of webpacker and you hit all kinds of issues because of it. Ross Kaffenberger understood the issue better so check out the link to read more from him but here were the steps to fix the issue:

$ yarn remove @rails/webpacker
$ rm -rf ./node_modules # clean slate
$ yarn add @rails/webpacker@^5.2.1

Hopefully it works or helps anyone else who is struggling.

**Comment by CodingItWrong** [comment]
This error also occurred for me when I pulled down my app locally and ran `bundle install` but forgot to run `yarn install`. There were no `node_modules` installed, but that wasn't directly indicated; the error I saw was "Webpacker can't find application.js"

**Comment by anasaijaz** [comment]
`yarn remove @rails/webpacker `
returned cannot find webpacker
but then I ran `yarn add @rails/webpacker@5.2.1`
it exited with error error 

/home/fixed/Desktop/deep_rails/node_modules/node-sass: Command failed.

but surprising enough my website started working

**Comment by thiagonzalez** [comment]
> `yarn remove @rails/webpacker `
> returned cannot find webpacker
> but then I ran `yarn add @rails/webpacker@5.2.1`
> it exited with error error
> 
> /home/fixed/Desktop/deep_rails/node_modules/node-sass: Command failed.
> 
> but surprising enough my website started working

that worked for me! Thank you so much, @anasaijaz ! 💯

**Comment by Godstrump** [comment]
Solved this here 
https://stackoverflow.com/a/69511508/13486752

**Comment by a3626a** [comment]
If you are using node 17, try to downgrade to 16

**Comment by rilwansmith** [comment]
Downgrading my Nodejs 17.3.0 to Nodejs 16.13.1 LTS for my ruby on rails project worked for me.

**Comment by cimm** [comment]
I had the same `ERR_OSSL_EVP_UNSUPPORTED` error when running my RSpec tests on github CI. Adding `NODE_OPTIONS='--openssl-legacy-provider'` in my .github/workflows/ci.yml fixed the issue.

```
...
 steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Install packages
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Load schema
        run: bin/rails db:schema:load
      - name: Run specs
        run: NODE_OPTIONS='--openssl-legacy-provider' bundle exec rspec spec
...
```

**Comment by mhcrocky** [comment]
> rails webpacker:compile

it worked.
great help

**Comment by ninjadrupal** [comment]
babel.config.js change 

- '@babel/plugin-proposal-private-methods',
+ '@babel/plugin-transform-private-methods',

terminal : 
export NODE_OPTIONS=--openssl-legacy-provider

package.json change : 

  "devDependencies": {
    "@babel/plugin-proposal-private-property-in-object": "^7.21.11",
    "webpack-dev-server": "^3"
  } 

rm -rf node_modules
rails assets:clobber
yarn
rails assets:precompile

**Comment by MartGS** [comment]
> `yarn remove @rails/webpacker ` returned cannot find webpacker but then I ran `yarn add @rails/webpacker@5.2.1` it exited with error error
> 
> /home/fixed/Desktop/deep_rails/node_modules/node-sass: Command failed.
> 
> but surprising enough my website started working


@anasaijaz, Thank you! I faced the same problem. My ruby application '2.7.1', rails 6.1.7.6. Although I tried many other ways but to no avail.
And only your tutorial works for me! Thank you!

**Comment by sailor95** [comment]
> babel.config.js change
> 
> Replace this : '@babel/plugin-proposal-private-methods', with '@babel/plugin-transform-private-methods',
> 
> terminal : export NODE_OPTIONS=--openssl-legacy-provider
> 
> package.json change :
> 
> "devDependencies": { "@babel/plugin-proposal-private-property-in-object": "^7.21.11", "webpack-dev-server": "^3" }
> 
> rm -rf node_modules rails assets:clobber yarn rails assets:precompile

This worked for me on `ruby 3.3.6` + `rails 6.1.7.10`, much appreciate
