### ISSUE TITLE
Webpacker 6.x - Dev server not reloads automatically in browser (refreshing the webpage without press f5 key)

### ISSUE THREAD

**Issue by pedrofurtado** [rails/webpacker#2832]
Hey @gauravtiwari ! 🤝 

Once I updated to webpacker 6.x beta 2, the dev server not automatically reloads the browser. But if I revert to 5.x this works well. Any configuration about it was changed (new defaults, required external libs, and so on)?

**Comment by pedrofurtado** [comment]
@gauravtiwari  I think this bug can in `webpacker` be related with theses facts:

1 - The `webpack-dev-server` is compatible with `webpack-cli v4` only in your 4.x version (today, the last release of `webpack-dev-server` in NPM is 4.0.0-beta.0).
2 - This PR ( https://github.com/rails/webpacker/pull/2783 ) changes the default behavior of dev server in `webpacker`, to use the `@webpack-cli/serve` for it (that behaves like a proxy to `webpack-dev-server`).
3 - But the current codebase of `webpacker` gem is only compatible with `webpack-dev-server` 3.x. In order to be compatible with `webpack-dev-server` 4.x, there are some breaking changes in configuration options. That's why, I supposed, the webpacker 6.x not works the live reload on browser.

🔍

**Comment by pedrofurtado** [comment]
I am investigating what keys we will need to change here: https://github.com/rails/webpacker/blob/master/package/environments/development.js#L25-L52

But any help @gauravtiwari  will be awesome hehehe I am new in codebase of webpacker 🤝

**Comment by pedrofurtado** [comment]
@gauravtiwari  Well, researching here, we need make webpacker compatible with webpack-dev-server v4 (even in beta), because with the compatibility of gem with webpack v5, the old webpack-dev-server v3 not works anymore (because it is not compatible with webpack v5) 🙈 

Ps: Merry Christmas for all 🎄 🎅 ☃️

**Comment by apuntovanini** [comment]
Up, HMR seems broken with version 6

**Comment by pedrofurtado** [comment]
@gauravtiwari 🤝

**Comment by pedrofurtado** [comment]
@gauravtiwari 🤝

**Comment by gauravtiwari** [comment]
Seems to broken for me too 😄  will take a look at this. Thanks for reporting @pedrofurtado

**Comment by pedrofurtado** [comment]
@gauravtiwari 🤝 👍

**Comment by justin808** [comment]
@gauravtiwari any progress on this? Need any help?

**Comment by scottrobertson** [comment]
```
WEBPACK_DEV_SERVER=true bin/webpack-dev-server
```

Works as a tmp fix.

**Comment by crawler** [comment]
@gauravtiwari 

I submitted two pull requests that should solve this:
#2890 #2892 

For temporary fix use @scottrobertson comment + add following code to your development.js

```javascript
const webpackConfig = require('./base') // expeted
//... 
// Add this:
if (webpackConfig.devServer) {
  webpackConfig.devServer.injectClient = true
}
//...
module.exports = webpackConfig
```
