### ISSUE TITLE
Webpacker 6.0.0.beta.2 - vue-loader doesn't work

### ISSUE THREAD

**Issue by holidayworking** [rails/webpacker#2835]
I'm trying Webpacker 6.0.0.beta.2 and I'm getting the following error:

```bash
$ ./bin/webpack
warning package.json: No license field
[webpack-cli] Error: [VueLoaderPlugin Error] No matching use for vue-loader is found.
Make sure the rule matching .vue files include vue-loader in its use.
    at VueLoaderPlugin.apply (/Users/hidekazu/workspace/webpacker-6.0.0-vue-bug-report-app/node_modules/vue-loader/lib/plugin-webpack5.js:93:13)
    at createCompiler (/Users/hidekazu/workspace/webpacker-6.0.0-vue-bug-report-app/node_modules/webpack/lib/webpack.js:69:12)
    at create (/Users/hidekazu/workspace/webpacker-6.0.0-vue-bug-report-app/node_modules/webpack/lib/webpack.js:113:15)
    at webpack (/Users/hidekazu/workspace/webpacker-6.0.0-vue-bug-report-app/node_modules/webpack/lib/webpack.js:121:46)
    at f (/Users/hidekazu/workspace/webpacker-6.0.0-vue-bug-report-app/node_modules/webpack/lib/index.js:37:15)
    at WebpackCLI.createCompiler (/Users/hidekazu/workspace/webpacker-6.0.0-vue-bug-report-app/node_modules/webpack-cli/lib/webpack-cli.js:1093:24)
    at async WebpackCLI.bundleCommand (/Users/hidekazu/workspace/webpacker-6.0.0-vue-bug-report-app/node_modules/webpack-cli/lib/webpack-cli.js:1217:20)
    at async Command.<anonymous> (/Users/hidekazu/workspace/webpacker-6.0.0-vue-bug-report-app/node_modules/webpack-cli/lib/webpack-cli.js:271:21)
    at async Promise.all (index 1)
    at async Command.<anonymous> (/Users/hidekazu/workspace/webpacker-6.0.0-vue-bug-report-app/node_modules/webpack-cli/lib/webpack-cli.js:652:13)
```

I created a [sample app](https://github.com/holidayworking/webpacker-6.0.0-vue-bug-report-app) to report this issue.
The files related to webpacker are as follows.
- package.json
    ```javascript
    {
      "dependencies": {
        "@rails/webpacker": "^6.0.0-beta.2",
        "vue-loader": "^15.9.6",
        "vue-template-compiler": "^2.6.12",
        "webpack": "^5.11.0",
        "webpack-cli": "^4.2.0"
      },
      "devDependencies": {
        "@webpack-cli/serve": "^1.2.0",
        "webpack-dev-server": "^3.11.0"
      },
      "babel": {
        "presets": [
          "./node_modules/@rails/webpacker/package/babel/preset.js"
        ]
      },
      "browserslist": [
        "defaults"
      ]
    }
    ```
- config/webpack/base.js
    ```javascript
    const { webpackConfig, merge } = require('@rails/webpacker')
    const vueConfig = require('./rules/vue')

    module.exports = merge(webpackConfig, vueConfig)
    ```
- config/webpack/rules/vue.js 
    ```javascript
    const VueLoaderPlugin = require('vue-loader/lib/plugin')
    
    module.exports = {
      module: {
        rules: [
          {
            test: /\.vue$/,
            loader: 'vue-loader'
          }
        ]
      },
      plugins: [new VueLoaderPlugin()]
    }
    ```

I think it's the effect of https://github.com/rails/webpacker/blob/v6.0.0.beta.2/package/rules/raw.js.
The rules of webpack are as follows.

```javascript
> const webpackConfig = require('./config/webpack/development.js')
undefined
> webpackConfig.module.rules
[
  {
    test: [ /\.html$/ ],
    exclude: [ /\.(js|mjs|jsx|ts|tsx)$/ ],
    type: 'asset/source'
  },
  {
    test: [
      /\.bmp$/,   /\.gif$/,
      /\.jpe?g$/, /\.png$/,
      /\.tiff$/,  /\.ico$/,
      /\.avif$/,  /\.webp$/,
      /\.eot$/,   /\.otf$/,
      /\.ttf$/,   /\.woff$/,
      /\.woff2$/, /\.svg$/
    ],
    exclude: [ /\.(js|mjs|jsx|ts|tsx)$/ ],
    type: 'asset/resource',
    generator: { filename: 'media/images/[hash][ext][query]' }
  },
  {
    test: /\.(js|jsx|mjs|ts|tsx)?(\.erb)?$/,
    include: [
      '/Users/hidekazu/workspace/webpacker-6.0.0-vue-bug-report-app/app/javascript'
    ],
    exclude: /node_modules/,
    use: [ [Object] ]
  },
  { test: /\.vue$/, loader: 'vue-loader' }
]
```

And vue-loader selects https://github.com/rails/webpacker/blob/v6.0.0.beta.2/package/rules/raw.js, I think it will cause an error.
https://github.com/vuejs/vue-loader/blob/v15.9.6/lib/plugin-webpack5.js#L44-L97

I did the following and it was successful.

```bash
$ cp -a node_modules/@rails/webpacker/package/rules/raw.js{,.orig}
$ vi node_modules/@rails/webpacker/package/rules/raw.js
$ diff -u node_modules/@rails/webpacker/package/rules/raw.js{.orig,}
--- node_modules/@rails/webpacker/package/rules/raw.js.orig     2020-12-26 07:51:57.000000000 +0900
+++ node_modules/@rails/webpacker/package/rules/raw.js  2020-12-26 07:52:22.000000000 +0900
@@ -1,5 +1,5 @@
 module.exports = {
-  test: [/\.html$/],
+  test: [/(?<!vue)\.html$/],
   exclude: [/\.(js|mjs|jsx|ts|tsx)$/],
   type: 'asset/source'
 }
$ ./bin/webpack
warning package.json: No license field
asset js/runtime-4b8517b74fdceb3a9b80.js 5.37 KiB [emitted] [immutable] (name: runtime) 1 related asset
asset js/application-557a0d826fc1c514fa11.js 2 KiB [emitted] [immutable] (name: application) 1 related asset
asset manifest.json 542 bytes [emitted]
Entrypoint application 7.38 KiB (6.34 KiB) = js/runtime-4b8517b74fdceb3a9b80.js 5.37 KiB js/application-557a0d826fc1c514fa11.js 2 KiB 2 auxiliary assets
runtime modules 2.66 KiB 2 modules
cacheable modules 1.3 KiB
  ./app/javascript/packs/application.css 487 bytes [built] [code generated]
  ./app/javascript/packs/application.js 845 bytes [built] [code generated]
webpack 5.11.0 compiled successfully in 2476 ms
```

Is this the correct fix?

**Comment by karlwilbur** [comment]
I have the same issue.

```
[webpack-cli] Error: [VueLoaderPlugin Error] No matching use for vue-loader is found.
Make sure the rule matching .vue files include vue-loader in its use.
...
```

Our app is working with Webpacker `5.2.1` but encounters this error when upgraded to `6.0.0.pre.2` (along with the other associated config and package updates).

@holidayworking, Making your change to the local file in `node_modules` also gets our app working again:

```bash
sed -i 's@\\\.html@(?<!vue)\\.html@' node_modules/@rails/webpacker/package/rules/raw.js
```

Adding the negative look-behind assertion doesn't seem like the best solution. This feels like something that should have been resolved by earlier compilation steps before Webpacker gets to this point. However, it does get my app working locally for now.

Maybe it would be better to have the `vue` as an exclude. This also seems to work:
```javascript
  exclude: [/\.(js|mjs|jsx|ts|tsx|vue\.html)$/],
```

...but it also is not the best and looks uglier than the exclusion inside the `test` value.

**Comment by scottrobertson** [comment]
Also seeing this

**Comment by scottrobertson** [comment]
@holidayworking @karlwilbur did either of you have any luck with a more permanent solution for this?

**Comment by karlwilbur** [comment]
No. I'm still working on it. Will be putting in much more time this weekend.

--
Karl Wilbur
513-322-2481
karl@karlwilbur.net

**Comment by scottrobertson** [comment]
Awesome, thank you @karlwilbur. I would offer to help, but my webpack(er) knowledge is pretty limited!

**Comment by karlwilbur** [comment]
I made a simple workaround that doesn't require editing the source code for the `@rails/webpacker` package. I'm going to submit as a [PR to @holidayworking's example app](https://github.com/holidayworking/webpacker-6.0.0-vue-bug-report-app/pull/1)

**Comment by karlwilbur** [comment]
It would appear that the primary problem was a missing `use` here:

```javascript
const VueLoaderPlugin = require('vue-loader/lib/plugin')

module.exports = {
  module: {
    rules: [
      {
        test: /\.vue$/,
        loader: 'vue-loader'
      }
    ]
  },
  plugins: [new VueLoaderPlugin()]
}
```

which should look like:
```javascript
const VueLoaderPlugin = require('vue-loader/lib/plugin')

module.exports = {
  module: {
    rules: [
      {
        test: /\.vue$/,
        use: { loader: 'vue-loader' }
      }
    ]
  },
  plugins: [new VueLoaderPlugin()]
}
```

But that change was itself was not sufficient to get things running again. I still needed to stop that other rule (`@rails/webpacker/package/rules/raw.js`) from running, as well as disable Webpacker's `optimizations`.

**Comment by holidayworking** [comment]
@karlwilbur Thank you. I have confirmed that it works fine.

**Comment by scottrobertson** [comment]
@holidayworking please leave this open. It needs to be resolved properly.

**Comment by venables** [comment]
I was able to get the default example (from the Webpacker [README](https://github.com/rails/webpacker#other-frameworks)) working just fine by switching the order of the `merge` call, as `vue` files need to be read before other types:

```diff
// config/webpack/rules/vue.js
const VueLoaderPlugin = require('vue-loader/lib/plugin')

module.exports = {
  module: {
    rules: [
      {
        test: /\.vue$/,
        loader: 'vue-loader'
      }
    ]
  },
  plugins: [new VueLoaderPlugin()]
}

// config/webpack/base.js
const { webpackConfig, merge } = require('@rails/webpacker')
const vueConfig = require('./rules/vue')

-module.exports = merge(webpackConfig, vueConfig)
+module.exports = merge(vueConfig, webpackConfig)
```

**Comment by scottrobertson** [comment]
Just confirmed that worked for me too @venables

**Comment by rossta** [comment]
#2884 added all the [webpack-merge](https://github.com/survivejs/webpack-merge) [v5 functions](https://github.com/survivejs/webpack-merge/blob/28cfdbda7bfa54717c13d1f28d715d33fdc7b339/src/index.ts#L294-L304) to the `@rails/webpacker` module.exports. 

The webpack-merge provides a number of helpful utility functions for extending and customizing webpack config. 

The `mergeWithRules` function could be a useful for way to support Vue in Webpacker 6:

```javascript
const { webpackConfig, mergeWithRules } = require('@rails/webpacker')
const VueLoaderPlugin = require('vue-loader/lib/plugin')

// Add `vue-loader` to support "Single File Component"-style components
const vueConfig = {
  module: {
    rules: [
      {
        test: [/\.html$/],
        exclude: [/\.(js|mjs|jsx|ts|tsx|vue\.html)$/],
        type: 'asset/source',
      },
      {
        test: /\.vue$/,
        use: { loader: 'vue-loader' },
      },
    ],
  },
  plugins: [new VueLoaderPlugin()],
  resolve: {
    alias: {
      vue: 'vue/dist/vue.js',
    },
  },
}

const exportConfig = mergeWithRules({
  module: {
    rules: {
      test: 'match',
      exclude: 'replace',
      type: 'match',
    },
  },
})(webpackConfig, vueConfig)
```
The `mergeWithRules` logic above replaces the `exclude` option in module rules that match the default asset/source rule for html files while also performing the traditional merge of the VueLoaderPlugin and resolve options.

**Comment by keymastervn** [comment]
> #2884 added all the [webpack-merge](https://github.com/survivejs/webpack-merge) [v5 functions](https://github.com/survivejs/webpack-merge/blob/28cfdbda7bfa54717c13d1f28d715d33fdc7b339/src/index.ts#L294-L304) to the `@rails/webpacker` module.exports.
> 
> The webpack-merge provides a number of helpful utility functions for extending and customizing webpack config.
> 
> The `mergeWithRules` function could be a useful for way to support Vue in Webpacker 6:
> 
> ```js
> const { webpackConfig, mergeWithRules } = require('@rails/webpacker')
> const VueLoaderPlugin = require('vue-loader/lib/plugin')
> 
> // Add `vue-loader` to support "Single File Component"-style components
> const vueConfig = {
>   module: {
>     rules: [
>       {
>         test: [/\.html$/],
>         exclude: [/\.(js|mjs|jsx|ts|tsx|vue\.html)$/],
>         type: 'asset/source',
>       },
>       {
>         test: /\.vue$/,
>         use: { loader: 'vue-loader' },
>       },
>     ],
>   },
>   plugins: [new VueLoaderPlugin()],
>   resolve: {
>     alias: {
>       vue: 'vue/dist/vue.js',
>     },
>   },
> }
> 
> const exportConfig = mergeWithRules({
>   module: {
>     rules: {
>       test: 'match',
>       exclude: 'replace',
>       type: 'match',
>     },
>   },
> })(webpackConfig, vueConfig)
> ```
> 
> The `mergeWithRules` logic above replaces the `exclude` option in module rules that match the default asset/source rule for html files while also performing the traditional merge of the VueLoaderPlugin and resolve options.

With yours I can make it works too, but all the extensions is invalid forcing me to import the vue files with full naming manually.
Without the config below, the `vue-loader` still raises errors...
```js
      {
        test: [/\.html$/],
        exclude: [/\.(js|mjs|jsx|ts|tsx|vue\.html)$/],
        type: 'asset/source',
      },
```

**Comment by DNA** [comment]
Although it still need a definitive fix, the solution suggested by @rossta worked very well! 
Made just a few adjustments to keep `base.js` clean and it worked nicely :)

on `rules/vue.js`:
```js
const { mergeWithRules } = require('@rails/webpacker');
const { VueLoaderPlugin } = require('vue-loader')

// see https://github.com/rails/webpacker/issues/2835
const configFix = {
  module: {
    rules: [{
      test: /\.html$/,
      exclude: [/\.vue\.html$/]
    }]
  }
}

const vueConfig = {
  module: {
    rules: [{
      test: /\.vue$/,
      use: {
        loader: 'vue-loader'
      },
    }]
  },
  plugins: [new VueLoaderPlugin()]
}

const vueMerger = mergeWithRules({
  module: {
    rules: {
      test: "match",
      exclude: "append"
    },
  },
});

module.exports = (config) => vueMerger(config, configFix, vueConfig)
```

On `base.js`:
```js
const { webpackConfig } = require('@rails/webpacker')
const applyVueConfig = require('./integrations/vue')

module.exports = applyVueConfig(webpackConfig)
```

**Comment by tabishiqbal** [comment]
Does this way allow you to create single file components and also mix vue components in erb files?

**Comment by justin808** [comment]
Please reopen if relevant with the latest updates. Consider submitting a doc PR.
