### ISSUE TITLE
Webpacker v6 -- Blocker to GA -- extract_css removal

### ISSUE THREAD

**Issue by justin808** [rails/webpacker#2838]
Per my review of https://github.com/rails/webpacker/pull/2802#pullrequestreview-558901234

We need to do something about the removal of `extract_css` from `config/webpacker.yml`

AFAIK, if one wants to use HMR with CSS, with the `webpack-dev-server`, in development mode, then we want CSS to come from the regular JS Bundle, so:

1. We don't use the view helper for the CSS, since
2. We must not use the `mini-css-extract-plugin`

CC: @gauravtiwari

**Comment by justin808** [comment]
@gauravtiwari this may have changed in Webpack v5.

https://webpack.js.org/plugins/mini-css-extract-plugin/#hot-module-reloading-hmr

I'm investigating.

Did you test the React HMR with CSS changes?

**Comment by pedrofurtado** [comment]
@justin808 Maybe this issue can be related? -> https://github.com/rails/webpacker/issues/2832

**Comment by justin808** [comment]
Because css modules is probably the main way that hot loading of CSS works...

Per https://github.com/webpack-contrib/mini-css-extract-plugin/issues/519#issuecomment-719823040, we need to use the style-loader for HMR.

**Comment by justin808** [comment]
See fix in #3031.
