### ISSUE TITLE
Webpacker 6 and resolve-url-loader

### ISSUE THREAD

**Issue by n-rodriguez** [rails/webpacker#2844]
I use [`resolve-url-loader`](https://github.com/bholloway/resolve-url-loader/blob/master/packages/resolve-url-loader/README.md#configure-webpack) in my project and the doc says :

> The typical use case is resolve-url-loader between sass-loader and css-loader.

https://github.com/bholloway/resolve-url-loader/blob/master/packages/resolve-url-loader/README.md#configure-webpack

With Webpacker 5.x the config was :

```js
environment.loaders.get('sass').use.splice(-1, 0, {
  loader: 'resolve-url-loader'
})
```

How can I achieve the same with Webpacker 6?

Thank you!

**Comment by n-rodriguez** [comment]
@gauravtiwari any hint?

**Comment by gencer** [comment]
@n-rodriguez What about:

```javascript
webpackConfig.module.rules.map(module => { // lets iterate Rules...
  if (module.test && module.test.toString().includes('scss')) {
	// We need SCSS Rule. Now splice it with `resolve-url-loader`
    module.use.splice(-1, 0, {
	  loader: require.resolve('resolve-url-loader')
	})
  }
  return module
})
```

`map` is mutating so you don't need to assign this variable again.

**Comment by n-rodriguez** [comment]
@gencer thanks for your help :) it seems to work. I say it seems because now I'm blocked by https://github.com/rails/webpacker/issues/2845 :/

**Comment by gencer** [comment]
99.999% it will work. Let me know if it's not. I added some code on your blocked issue.
