### ISSUE TITLE
How to setup Webpacker 6 and environment variables

### ISSUE THREAD

**Issue by Diogomartf** [rails/webpacker#2846]
I can't make my .env variables accessible like I had with webpacker 5.

If someone could update this docs It would be great!

https://github.com/rails/webpacker/blob/a84a4bb6b385ae17dd775a6034a0b159b88c6ea9/docs/env.md#environment-variables

My setup was something like this:

```javascript
const { environment } = require('@rails/webpacker')
const webpack = require('webpack')
const dotenv = require('dotenv')

const dotenvFiles = [
  `.env.${process.env.NODE_ENV}.local`,
  '.env.local',
  `.env.${process.env.NODE_ENV}`,
  '.env'
]
dotenvFiles.forEach((dotenvFile) => {
  dotenv.config({ path: dotenvFile, silent: true })
})

environment.plugins.prepend('Environment', new webpack.EnvironmentPlugin(JSON.parse(JSON.stringify(process.env))))

module.exports = environment
```

But now we do not have access to `environment`,  how can we setup environment variables with webpacker?

**Comment by rossta** [comment]
Here's one way to modify your config for Webpacker 6:

```js
const { webpackConfig, merge } = require('@rails/webpacker')

const webpack = require('webpack')
const dotenv = require('dotenv')

const dotenvFiles = [
  `.env.${process.env.NODE_ENV}.local`,
  '.env.local',
  `.env.${process.env.NODE_ENV}`,
  '.env'
]
dotenvFiles.forEach((dotenvFile) => {
  dotenv.config({ path: dotenvFile, silent: true })
})

module.exports = merge(webpackConfig, {
  plugins: [new webpack.EnvironmentPlugin(JSON.parse(JSON.stringify(process.env)))],
})
```

Alternatively, since [@rails/webpacker is already providing environment variables to webpack](https://github.com/rails/webpacker/blob/461a61f2038b58bef99eaec64846e564e712dc9e/package/environments/base.js#L55), you can use the dotenv ruby CLI to call webpack commands to ensure your dotenv files are loaded:

```sh
$ dotenv -f ".env.development.local,.env.development,.env" bin/webpack-dev-server"
```

**Comment by Diogomartf** [comment]
Worked great. Thanks Ross!

**Comment by Diogomartf** [comment]
Worked great. Thanks Ross!

**Comment by earnold** [comment]
@rossta Thanks for providing this! 

One follow-up question: where would you place that code? And when/where is the appropriate time for it to be invoked?

I'm still trying to wrap my head around the correct use of Webpacker, so my apologies if this is super obvious.
