### ISSUE TITLE
Webpacker fails to load config/webpack/development.js

### ISSUE THREAD

**Issue by fyshhh** [rails/webpacker#2858]
I'm very new to Rails so please bear with me here. I tried generating a new controller with `rails generate controller Welcome index`; however, when I opened `localhost:3000/welcome/index`, I'm met with the following error:

Webpacker can't find application in /Users/illio/Documents/projects/cvwo_assignment/public/packs/manifest.json. Possible causes:
1. You want to set webpacker.yml value of compile to true for your environment
   unless you are using the `webpack -w` or the webpack-dev-server.
2. webpack has not yet re-run to reflect updates.
3. You have misconfigured Webpacker's config/webpacker.yml file.
4. Your webpack configuration is not creating a manifest.
Your manifest contains:
{
}

I went to the `public` directory and saw that no `manifest.json` file was being created. I then went to check the logs, and I see the following:

[Webpacker] Compiling...
[Webpacker] Compilation failed:
[webpack-cli] Failed to load '/Users/illio/Documents/projects/cvwo_assignment/config/webpack/development.js'
[webpack-cli] TypeError: Cannot read property 'toWebpackConfig' of undefined
    at Object.<anonymous> (/Users/illio/Documents/projects/cvwo_assignment/config/webpack/development.js:5:30)
    at Module._compile (/Users/illio/Documents/projects/cvwo_assignment/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (/Users/illio/Documents/projects/cvwo_assignment/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at loadConfig (/Users/illio/Documents/projects/cvwo_assignment/node_modules/webpack-cli/lib/webpack-cli.js:753:31)
    at /Users/illio/Documents/projects/cvwo_assignment/node_modules/webpack-cli/lib/webpack-cli.js:823:48
    at Array.map (<anonymous>)

This perplexes me, as the `development.js` file exists. This is what's contained in it:

```
process.env.NODE_ENV = process.env.NODE_ENV || 'development'

const environment = require('./environment')

module.exports = environment.toWebpackConfig()
```

I've tried to look around online for solutions, but I haven't been able to find anyone encountering a similar issue. Any help would be much appreciated. A copy of the repository can be found [here](https://github.com/fyshhh/cvwo_assignment).

**Comment by rossta** [comment]
Are you using Webpacker 6? It's still in beta so the documentation doesn't reflect the current usage.

Since you're just getting started, I'd recommend downgrading to Webpacker 5 for now, which includes the gem and the NPM package:

```ruby
gem 'webpacker', '~> 5.2.0'
```
```json
"@rails/webpacker": "^5.2.0"
```

Your current webpack config should work with those versions.

**Comment by fyshhh** [comment]
I'm actually using Webpacker 4.3.0. I followed [this](https://gorails.com/setup/osx/10.15-catalina) installation guide. I'll try upgrading to Webpacker 5 and see if it fixes it.

**Comment by fyshhh** [comment]
I ran `bundle exec rails webpacker:install` again and somehow it fixed itself.
