### ISSUE TITLE
Webpacker 6.0.0.beta.2 - images are emitted at root and folders are ignored

### ISSUE THREAD

**Issue by Intrepidd** [rails/webpacker#2859]
```javascript
// packs/application.js
require.context('../images', true)
```

I have a file under `app/javascript/images/favicons/apple-touch-icon.png`

With webpacker5, here's what I get in my manifest.json : 

```json
"media/images/favicons/apple-touch-icon.png": "/packs/media/images/favicons/apple-touch-icon-db2fed16c3be93f9d55f4fc441885704.png",
```

Now with webpacker6 here's what I have :

```json
"media/images/apple-touch-icon.png": "/packs/media/images/db2fed16c3be93f9d55f.png",
```

Is it on purpose ? Not being able to scope images by folder can be very annoying, let alone dangerous because of possible conflicts, etc

**Comment by gencer** [comment]
@Intrepidd Yes, this has changed with 6.x.

You can use something like this one I believe:


```javascript
const { webpackConfig } = require('@rails/webpacker')

webpackConfig.module.rules.map(module => {
  if (module.type === 'asset/resource') {
    module.generator = {
      filename: 'media/[folder]/[contenthash:16].[ext][query]' // insert [folder]
    }
  }

  return module
})

module.exports = webpackConfig
```

Didn't tested properly but it will probably work.

**Comment by Intrepidd** [comment]
Thanks! It's great to have a workaround! 

That said the current behavior doesn't seem like a sensible default to me. Rails is all about convention before configuration and I believe this change goes on the wrong way.

I'd love to understand why this was done

**Comment by n-rodriguez** [comment]
https://github.com/rails/webpacker/commit/938f060a5c80281d5c02dadff0c7850966b7ec7c#diff-716197750a05276089fff034fe03597e5d569526a8ea683fb0022cf69456cbc4

**Comment by n-rodriguez** [comment]
To restore the old behavior :

```js
const { join } = require('path')
const { webpackConfig, config } = require('@rails/webpacker')

webpackConfig.module.rules.map(module => {
  if (module.type === 'asset/resource') {
    delete module.type
    delete module.generator
    module.use = [
      {
        loader: 'file-loader',
        options: {
          name(file) {
            if (file.includes(config.source_path)) {
              return 'media/[path][name]-[hash].[ext]'
            }
            return 'media/[folder]/[name]-[hash:8].[ext]'
          },
          context: join(config.source_path)
        }
      }
    ]
  }
  return module
})
```

**Comment by venables** [comment]
I was able to get the default example (from the Webpacker [README](https://github.com/rails/webpacker#other-frameworks)) working just fine by switching the order of the `merge` call, as `vue` files need to be read before other types:

```diff
// config/webpack/rules/vue.js
const VueLoaderPlugin = require('vue-loader/lib/plugin')

module.exports = {
  module: {
    rules: [
      {
        test: /\.vue$/,
        loader: 'vue-loader'
      }
    ]
  },
  plugins: [new VueLoaderPlugin()]
}

// config/webpack/base.js
const { webpackConfig, merge } = require('@rails/webpacker')
const vueConfig = require('./rules/vue')

-module.exports = merge(webpackConfig, vueConfig)
+module.exports = merge(vueConfig, webpackConfig)
```

**Comment by patch0** [comment]
Just been through this myself, and the `[folder]` placeholder [suggested above](https://github.com/rails/webpacker/issues/2859#issuecomment-754120130) isn't in the list of tokens [in the docs](https://webpack.js.org/configuration/output/#template-strings), and I couldn't make it work.

However I did come up with something similar:

```js
const { join, dirname } = require('path')
const { webpackConfig, config } = require('@rails/webpacker')

webpackConfig.module.rules.map(module => {
  if (module.type === 'asset/resource') {
    module.generator = {
      filename: (pathData) => {
        if (pathData.filename.startsWith(config.source_path)) {
          // Strip the source path from the filename, and use it in place of the folder.
          let folder = dirname(pathData.filename.slice(config.source_path.length))
          return join('media', folder, '[name]-[hash:8].[ext]')
        }
        // Normal behaviour for webpacker.
        return 'media/images/[hash].[ext]'
      }
    }
  }

  return module
})
```

**Comment by Intrepidd** [comment]
Here is another way compatible with `css-loader` `6.0.0`, that doesn't use file-loader which seems to be deprecated : 

```js
webpackConfig.module.rules.map(module => {
  if (module.type === 'asset/resource') {
    module.generator = {
      filename: (pathData) => {
        const name = pathData.filename.replace('app/packs', 'media')
        return `${name}-[hash][ext]`
      }
    }
  }
  return module
})
```

I still don't believe the current defaults is sane though

**Comment by michaelbaudino** [comment]
I went with mostly the same workaround as @Intrepidd's, but with:
* a slightly shorter syntax :golf: :golfing: 
* dynamic `source_path` (it requires to import `config` from `@rails/webpacker`, though, but is probably less error-prone)
* `'static'` as output prefix, rather than `'media'` (to keep subdirectories structure but still comply with new naming convention)

Here it is:

```js
// config/webpack/base.js

const { webpackConfig, config: webpackerConfig } = require('@rails/webpacker')

webpackConfig.module.rules.find(module => module.type === 'asset/resource').generator = {
  filename: pathData => `${pathData.filename.replace(webpackerConfig.source_path, 'static')}-[hash][ext]`
}
```

**Comment by michaelbaudino** [comment]
Maintainers: any plan to change those defaults before v6 release?

Or do we want to keep flattening the `app/packs/images/` file hierarchy on purpose?

Does the current behaviour (flattening) provide any advantage?
