### ISSUE TITLE
Pass ARGV in webpack-dev-server?

### ISSUE THREAD

**Issue by lucaspiller** [rails/webpacker#286]
Is there any reason why ARGV isn't passed to the command run in `./bin/webpack-dev-server`, like the other two webpack binstubs?

In development, I often run the application on a separate machine, so need to pass the `--host` option. I can't set it in `config/webpack/development.server.yml` as that'll break things for my colleagues.

**Comment by gauravtiwari** [comment]
@lucaspiller Feel free to make a PR please 👍

**Comment by gauravtiwari** [comment]
Fixed by #295

**Comment by lucaspiller** [comment]
Thanks, however in regards to my actual issue (not having the server running on localhost), this didn't work as Rails was still rendering the URL as `localhost:8000`. In the end I changed `config/webpack/development.server.yml` and told Git to ignore the changes with:

```
git update-index --assume-unchanged config/webpack/development.server.yml
```

**Comment by timkrins** [comment]
It seems this issue was purposefully unfixed by https://github.com/rails/webpacker/pull/843

Now there is no ARGV support for webpack-dev-server, and we need to use ENV.
