### ISSUE TITLE
Race condition with parallel tests

### ISSUE THREAD

**Issue by Ecco** [rails/webpacker#2860]
This is a follow-up to #2324 which has not been fixed.

There is a race condition in Webpacker when you configure rails to use workers for parallelized tests:
```ruby
class ActiveSupport::TestCase
  parallelize(workers: :number_of_processors)
end
```

In that scenario, if you start a test run (`rails test`) with no pre-built packs (e.g. with `public/packs-test` empty), then you're very likely to have errors like this one:
```
Error:
ActionView::Template::Error: 767: unexpected token at ''
```

The error arises because one worker is creating the json manifest while the other one is trying to read. So one worker thinks the JSON file is ready to be read, and tries to read it, but then gets corrupt JSON data.

A simple fix would be to force compiling the pack *before* running the test suite. I don't know how to make this happen in Webpacker, but in the meantime here's a way to achieve this in your own app:

```ruby
Webpacker.manifest.lookup("missing.js") # Just used to force pack compilation before forking
# Indeed, "compile" is a private method, but a lookup will trigger compilation if needed
class ActiveSupport::TestCase
  parallelize(workers: :number_of_processors)
end
```

**Comment by euxx** [comment]
Hi, you could compile assets by `$ bundle exec rake assets:precompile RAILS_ENV=test`

**Comment by Ecco** [comment]
@euxx I'm not sure I follow. Of course if we pre-build the webpack, then the race condition disappears. But that's quite not the point, `rails test` should work no matter what is the previous webpack state.

Also, I'm not sure the command you gave works with webpacker at all. I think it's a sprockets command, but I might be wrong.

**Comment by euxx** [comment]
> But that's quite not the point, rails test should work no matter what is the previous webpack state.

I see, that indeed could be improved.

And `assets:precompile` works, I just checked it contains `webpacker:compile` task  from [README](https://github.com/rails/webpacker#deployment).

**Comment by Ecco** [comment]
> And assets:precompile works, I just checked it contains webpacker:compile task from README.

Oh, indeed. Good to know 😄

**Comment by earnold** [comment]
I see this ticket is about six months old. Are there any better work arounds for this issue? I just got bit by it myself.

**Comment by mscoutermarsh** [comment]
Ran into this too. The fix posted by @Ecco fixed it for us as well! Thank you.

**Comment by Ecco** [comment]
Glad I could help 😄
