### ISSUE TITLE
Supported / Maintained Versions

### ISSUE THREAD

**Issue by davidbarratt** [rails/webpacker#2867]
Could you tell me what versions are currently supported/maintained? v4? v3?
I didn't see this in the main README, but perhaps I missed it. :)

**Comment by rossta** [comment]
Don't take this as official, but my observation has been that the current version is actively maintained while the prior version gets critical bug fixes and occasional dependency updates. 

Now that the upcoming v6 release on the main branch is being actively developed, I would expect the version 5 to receive critical bug fixes if any and v4 to no longer be supported.

You can find stable release branches for some prior versions if needed:

* https://github.com/rails/webpacker/tree/3-x-stable
* https://github.com/rails/webpacker/tree/4 -x-stable
* https://github.com/rails/webpacker/tree/5-x-stable

Hope that's helpful.

**Comment by gmcgibbon** [comment]
Please see [the maintenance policy](https://guides.rubyonrails.org/maintenance_policy.html). This policy is for Rails, but it applies to all projects under the `rails/*`. New features go on master, bug fixes go on `5.2.x` (`5-x-stable`), and security patches on `5.2.x`, `5.0.x`, and `4.3.x` (`5-x-stable`, `4-x-stable`).
