### ISSUE TITLE
I install node.js and it says I need windows 8.1 or higher. I have windows 10, and have went through all the updates.

### ISSUE THREAD

**Issue by sarik20** [rails/webpacker#2871]
I install node.js and it says I need windows 8.1 or higher. I have windows 10, and have went through all the updates. 
I did get an older version of node to install through a command prompt, but I can't find a text editor to actually install npm packages.

PLEASE HELP!!

* **Node.js Version**:
* **OS**:
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

- [ ] __Originally posted by @ryansaginaw in https://github.com/nodejs/help/issues/3169__

**Comment by guillaumebriday** [comment]
It's not related to Webpacker directly.

Please take a look at https://nodejs.org/en/download/ or the issue you opened on the `nodejs/help` repo
