### ISSUE TITLE
Disable compression-webpack-plugin

### ISSUE THREAD

**Issue by scottrobertson** [rails/webpacker#2872]
Hey

Been looking for a while, but I cannot find anywhere how to do this.

How can i disable compression. I can only see how to do this on dev-server, but i want to disable it on compile too. The reason is that it's massively increasing my build times, and I am trying to debug why a pretty basic Vue app is taking over 2 minutes to compile.

<img width="436" alt="Screenshot 2021-01-10 at 12 23 36@2x" src="https://user-images.githubusercontent.com/68361/104122723-ae2a0800-533e-11eb-8134-cfb62bacb58d.png">

**Comment by rossta** [comment]
Here's how you could do it:

For Webpacker v4 or v5:

```js
environment.plugins.delete('Compression')
environment.plugins.delete('Compression Brotli')
```

For Webpacker 6

```js
const CompressionPlugin = require('compression-webpack-plugin')

webpackConfig.plugins = webpackConfig.plugins.filter((p) => !(p instanceof CompressionPlugin))
```

**Comment by scottrobertson** [comment]
Thanks @rossta. I ended up with the first one and forgot to close this!
