### ISSUE TITLE
Webpacker 5.2.1 compilation issues with Node 15?

### ISSUE THREAD

**Issue by sedubois** [rails/webpacker#2874]
This follows up on https://github.com/rails/rails/issues/41060.

On a macbook with Node 15.5.1 and Rails 6.1.0 `rails new` will create an app that fails to start.

According to the Prerequisites in Webpacker's README, supported Node versions are `Node.js 10.22.1+ || 12+ || 14+`. Does this include or exclude Node 15?

If Node 15 is supported, it should be added to the CI?

If Node 15 is not supported, webpacker should raise an error upon startup saying it's not compatible with Node 15?

**Comment by guillaumebriday** [comment]
What's your errors?

**Comment by sedubois** [comment]
For the errors I can only refer to the [Rails forum discussion](https://discuss.rubyonrails.org/t/pretty-astonishing/76850/31) linked from the Github discussion. I don't know which part is accurate however as I haven't tried to reproduce them on my machine so far. I'm just the messenger 🙂 That's why it would be great to add it to CI. But let me know if you first need help in reproducing it on my machine.

NB: In [my own test](https://discuss.rubyonrails.org/t/pretty-astonishing/76850/23?u=sdubois), running `rails new` on my macbook leads to the installation of node-sass 4.14.1, which to my understanding is [not compatible](https://www.npmjs.com/package/node-sass#node-version-support-policy) with Node 15.
