### ISSUE TITLE
React files not being resolved without extensions

### ISSUE THREAD

**Issue by noelrappin** [rails/webpacker#2882]
I'm not sure if this is a bug, but seems like a change in behavior from 5 to 6

In 5.x, using React, I could resolve a `.tsx` or `.jsx` file with:

`import Foo from "components/foo"`

In 6.0, with the default configuration and `preset-react`, I can't do that, I have to do the import as 

`import Foo from "components/foo.tsx"`

Can't tell if this is my error, or a deliberate change of some kind.

Thanks.

**Comment by gencer** [comment]
Have you tried

```javascript
// development.js OR base.js
// ...
webpackConfig.resolve.extensions.push('.tsx')
// ...
```

**Comment by rossta** [comment]
@noelrappin Could you try from master? This PR was recently merged and should address your issue https://github.com/rails/webpacker/pull/2862
