### ISSUE TITLE
media argument to stylesheet_pack_tag not working as expected

### ISSUE THREAD

**Issue by robskrob** [rails/webpacker#2885]
I have print styles that I need the browser to process. When I alter `stylesheet_pack_tag` to accept print styles using, `= stylesheet_pack_tag 'application', media: 'all'`, I still get `media: "screen"`:

```
<link rel="stylesheet" media="screen" href="/packs/css/application-7b3f3758.css">
```

How can I invoke, `stylesheet_pack_tag`, such that I get `media="all"` as the result instead?

```
<link rel="stylesheet" media="all" href="/packs/css/application-7b3f3758.css">
```
I've searched for documentation to help me, but couldn't find anything.

I'm currently using webpacker `4.0` and rails `6.0.1`.

**Comment by guillaumebriday** [comment]
This is the way to do it! 

I just tried with 4.0 and rails 6 and it works fine, do you have a reproduction repo?

**Comment by robskrob** [comment]
@guillaumebriday thank you for your reply! I think my environment was not using the right webpack configuration. I'm going to close this issue for now, and will report back with more information to clear everything up if necessary.
