### ISSUE TITLE
import layui.css with some mistake in webpacker 5.0

### ISSUE THREAD

**Issue by Spdwal** [rails/webpacker#2904]
ruby version: 3.0.0
rails version: 6.1.1
webpacker version: 5.0
OS: Mac OS X 10.15.7 19H15
layui.css path: node_modules/layui-src/src/css/layui.css
font path: node_modules/layui-src/src/font/

when I import layui.css in app/javascript/stylesheets/applicaiont.scss
I have 5 mistakes like this:
`
ERROR in ./app/javascript/packs/stylesheets/application.scss (./node_modules/css-loader/dist/cjs.js??ref--3-1!./node_modules/postcss-loader/src??ref--3-2!./node_modules/sass-loader/dist/cjs.js??ref--3-3!./app/javascript/packs/stylesheets/application.scss)
Module not found: Error: Can't resolve '../font/iconfont.woff?v=256' in '/Users/ayakawashinji/Documents/webpackerapp/app/javascript/packs/stylesheets'
 @ ./app/javascript/packs/stylesheets/application.scss (./node_modules/css-loader/dist/cjs.js??ref--3-1!./node_modules/postcss-loader/src??ref--3-2!./node_modules/sass-loader/dist/cjs.js??ref--3-3!./app/javascript/packs/stylesheets/application.scss) 6:36-74
 @ ./app/javascript/packs/stylesheets/application.scss
 `
The code in layui.css is 
`
@font-face {
  font-family: 'layui-icon';
  src: url('../font/iconfont.eot?v=256');
  src: url('../font/iconfont.eot?v=256#iefix') format('embedded-opentype'),
       url('../font/iconfont.woff2?v=256') format('woff2'),
       url('../font/iconfont.woff?v=256') format('woff'),
       url('../font/iconfont.ttf?v=256') format('truetype'),
       url('../font/iconfont.svg?v=256#layui-icon') format('svg');
}
`
I think the mistake is the loader try to find the font file in app/javascript/packs/font/ , but the file is in node_modules/layui-src/src/font/ .

**Comment by pedrofurtado** [comment]
Hey, @Spdwal ! 👋 

Maybe this error is ocurring because webpack is trying to resolve the relative path of fonts according to `app/packs/` instead of `node_modules/path/to/lib`. To confirm this supposition, please can you execute these steps below?

1. Upgrade webpacker gem and webpacker JS package to latest stable version (at this moment is v5.2.1)
2. Follow the instructions existing in https://github.com/rails/webpacker/blob/5-x-stable/docs/css.md#resolve-url-loader, to install resolve-url-loader, that fix this kind of error

Let me know your results on it 🤝

**Comment by Spdwal** [comment]
Thanks for answer, Sir.
I've update the webpacker to v5.2.1 and add resovle-url-loader as you said.
This is my environment.js
```
const { environment } = require('@rails/webpacker')
const { VueLoaderPlugin } = require('vue-loader')
const vue = require('./loaders/vue')

environment.plugins.prepend('VueLoaderPlugin', new VueLoaderPlugin())
environment.loaders.prepend('vue', vue)

const webpack = require('webpack')

environment.loaders.get('sass').use.splice(-1, 0, {
  loader: 'resolve-url-loader'
});

environment.plugins.prepend('Provide',
                            new webpack.ProvidePlugin({
                              $: 'jquery/src/jquery',
                              jQuery: 'jquery/src/jquery'
                            })
                           )
                     

module.exports = environment
```
But the error still exists:
```
ERROR in ./app/javascript/packs/stylesheets/lay.scss (./node_modules/css-loader/dist/cjs.js??ref--3-1!./node_modules/postcss-loader/src??ref--3-2!./node_modules/resolve-url-loader!./node_modules/sass-loader/dist/cjs.js??ref--3-4!./app/javascript/packs/stylesheets/lay.scss)
Module not found: Error: Can't resolve '../font/iconfont.eot?v=256' in '/Users/ayakawashinji/Documents/webpackerapp/app/javascript/packs/stylesheets'
 @ ./app/javascript/packs/stylesheets/lay.scss (./node_modules/css-loader/dist/cjs.js??ref--3-1!./node_modules/postcss-loader/src??ref--3-2!./node_modules/resolve-url-loader!./node_modules/sass-loader/dist/cjs.js??ref--3-4!./app/javascript/packs/stylesheets/lay.scss) 4:36-73
 @ ./app/javascript/packs/stylesheets/lay.scss

ERROR in ./app/javascript/packs/stylesheets/lay.scss (./node_modules/css-loader/dist/cjs.js??ref--3-1!./node_modules/postcss-loader/src??ref--3-2!./node_modules/resolve-url-loader!./node_modules/sass-loader/dist/cjs.js??ref--3-4!./app/javascript/packs/stylesheets/lay.scss)
Module not found: Error: Can't resolve '../font/iconfont.svg?v=256' in '/Users/ayakawashinji/Documents/webpackerapp/app/javascript/packs/stylesheets'
 @ ./app/javascript/packs/stylesheets/lay.scss (./node_modules/css-loader/dist/cjs.js??ref--3-1!./node_modules/postcss-loader/src??ref--3-2!./node_modules/resolve-url-loader!./node_modules/sass-loader/dist/cjs.js??ref--3-4!./app/javascript/packs/stylesheets/lay.scss) 8:36-73
 @ ./app/javascript/packs/stylesheets/lay.scss

ERROR in ./app/javascript/packs/stylesheets/lay.scss (./node_modules/css-loader/dist/cjs.js??ref--3-1!./node_modules/postcss-loader/src??ref--3-2!./node_modules/resolve-url-loader!./node_modules/sass-loader/dist/cjs.js??ref--3-4!./app/javascript/packs/stylesheets/lay.scss)
Module not found: Error: Can't resolve '../font/iconfont.ttf?v=256' in '/Users/ayakawashinji/Documents/webpackerapp/app/javascript/packs/stylesheets'
 @ ./app/javascript/packs/stylesheets/lay.scss (./node_modules/css-loader/dist/cjs.js??ref--3-1!./node_modules/postcss-loader/src??ref--3-2!./node_modules/resolve-url-loader!./node_modules/sass-loader/dist/cjs.js??ref--3-4!./app/javascript/packs/stylesheets/lay.scss) 7:36-73
 @ ./app/javascript/packs/stylesheets/lay.scss

ERROR in ./app/javascript/packs/stylesheets/lay.scss (./node_modules/css-loader/dist/cjs.js??ref--3-1!./node_modules/postcss-loader/src??ref--3-2!./node_modules/resolve-url-loader!./node_modules/sass-loader/dist/cjs.js??ref--3-4!./app/javascript/packs/stylesheets/lay.scss)
Module not found: Error: Can't resolve '../font/iconfont.woff2?v=256' in '/Users/ayakawashinji/Documents/webpackerapp/app/javascript/packs/stylesheets'
 @ ./app/javascript/packs/stylesheets/lay.scss (./node_modules/css-loader/dist/cjs.js??ref--3-1!./node_modules/postcss-loader/src??ref--3-2!./node_modules/resolve-url-loader!./node_modules/sass-loader/dist/cjs.js??ref--3-4!./app/javascript/packs/stylesheets/lay.scss) 5:36-75
 @ ./app/javascript/packs/stylesheets/lay.scss

ERROR in ./app/javascript/packs/stylesheets/lay.scss (./node_modules/css-loader/dist/cjs.js??ref--3-1!./node_modules/postcss-loader/src??ref--3-2!./node_modules/resolve-url-loader!./node_modules/sass-loader/dist/cjs.js??ref--3-4!./app/javascript/packs/stylesheets/lay.scss)
Module not found: Error: Can't resolve '../font/iconfont.woff?v=256' in '/Users/ayakawashinji/Documents/webpackerapp/app/javascript/packs/stylesheets'
 @ ./app/javascript/packs/stylesheets/lay.scss (./node_modules/css-loader/dist/cjs.js??ref--3-1!./node_modules/postcss-loader/src??ref--3-2!./node_modules/resolve-url-loader!./node_modules/sass-loader/dist/cjs.js??ref--3-4!./app/javascript/packs/stylesheets/lay.scss) 6:36-74
 @ ./app/javascript/packs/stylesheets/lay.scss
```

**Comment by pedrofurtado** [comment]
Inside your `app/javascript/packs/lay.scss`, maybe you can change the path for search to something like that:

`... src: url('../../../node_modules/your-module/font/iconfont.eot?v=256'); ...`
or
`... src: url('your-module-name-from-node-module/font/iconfont.eot?v=256'); ...`

Setting the path like the options above, suggests webpack to get content from node_modules 👍

**Comment by Spdwal** [comment]
Thanks, there is no error while compiling the code.
But the css is still not works。。。。
I think there is some other mistake in the module.
