### ISSUE TITLE
Error: Cannot find module 'webpack-cli/bin/config-yargs'

### ISSUE THREAD

**Issue by Dujota** [rails/webpacker#2905]
Rails 5.2
Ruby 2.7.2

Upgraded from webpacker 4 -> 5

steps taken:
1 - update gem file to webpacker 5
2 - bundle
3 - rails webpacker:install

all is well, but when i run `./bin/webpack-dev-server` i get the error mentioned above. 

```
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'webpack-cli/bin/config-yargs'
Require stack:
- /Users/denisdujota/Desktop/internationalsafety/node_modules/webpack-dev-server/bin/webpack-dev-server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/denisdujota/Desktop/internationalsafety/node_modules/webpack-dev-server/bin/webpack-dev-server.js:65:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/denisdujota/Desktop/internationalsafety/node_modules/webpack-dev-server/bin/webpack-dev-server.js'
  ]
}
```

**Comment by nicbet** [comment]
For what it's worth, I had the same issue happening to me on a Rails 6.1.0 project yesterday after following the same steps. In my case I discovered that I had explicitly added `webpack` as a `devDependency` to `package.json` a while ago in an attempt to silence the `web pack-dev-server has unmet dependency on webpack 4.0.0 || webpack 5.0.0` warnings. After removing the dependency the above error went away.

**Comment by waterquarks** [comment]
Try running `yarn install webpack-cli@3.3.12`.

ref: https://github.com/rails/tailwindcss-rails/issues/18#issuecomment-764686530

**Comment by hangtwenty** [comment]
@waterquarks thank you! this helped me.

note that [for recent versions of yarn] the command is `add` rather than `install`: `yarn add webpack-cli@3.3.12`

**Comment by hangtwenty** [comment]
What worked for me: from issue **https://github.com/rails/webpacker/issues/2875** — `rails webpacker:install` — and make sure to `git diff` and revert or merge `postcss.config.js` etc, as needed.

**Comment by memsenpai** [comment]
> yarn install webpack-cli@3.3.12
you save my day

**Comment by 9mm** [comment]
how does rails not work out of the box anymore, this is just absurd. for a simple 1 off project lets install 9000000 node_modules where rails no longer "Just works"

**Comment by dorianmariefr** [comment]
here is how I did fix it:

```
gem "webpacker", github: "rails/webpacker" # in Gemfile
yarn add https://github.com/rails/webpacker.git
rails webpacker:install # yes to everything
rm .browserslistrc # it's in package.json now

mv app/javascript/ app/packs
mv app/packs/javascript/ app/
mv app/javascript/* app/packs/
mv app/packs/packs/* app/packs/entrypoints/
rm -r app/packs/packs/ app/javascript/
```

I also remove the css managed by webpack to only use sprockets for css so you may have additional steps for the css

**Comment by dhh** [comment]
Please add any notes relevant to the v6 upgrade doc as a PR 👍
