### ISSUE TITLE
Method to selectively run dev-server on just one pack and serve the others from cache?

### ISSUE THREAD

**Issue by njradford** [rails/webpacker#2906]
I have seven packs in my current Rails app. Is a there a configuration option to effectively say "run webpack dev-server just for x pack, and use a cached, pre-compiled development version of any other pack that's requested?". 

I've hacked something together using ENV flags to manipulate the webpack entrypoints at runtime, however this has the consequence of rails not being able to find a pack in the manifest other than the one being actively developed with the dev server.

**Comment by juliusdelta** [comment]
Unfortunately I don't think targeting a specific entry point for compilation is possible. The `manifest.json` is written on each compilation, which is why when you use ENV flags to specify an entry point, other views that require other bundles break.

**Comment by njradford** [comment]
I think that makes sense and is certainly consistent. Thank you for your reply.
