### ISSUE TITLE
Get the fingerprint-including path of an asset from a pack

### ISSUE THREAD

**Issue by yoones** [rails/webpacker#2908]
Some libraries require during initialization that you provide a path to a file/folder that's in the npm package.

Example:

```
ZoomMtg.setZoomJSLib('https://source.zoom.us/1.8.6/lib', '/av');
AVFiles = {
    audioWorkerPath: `${zoomJSLib}${zoomJSAVLib}/${jsmediaVersion}_js_audio_process.min.js`,
    audioWorkletPath: `${zoomJSLib}${zoomJSAVLib}/${jsmediaVersion}_js_audio_worklet.min.js`,
    videoWorkerPath: `${zoomJSLib}${zoomJSAVLib}/${jsmediaVersion}_video_s.min.js`,
    videoMtWorkerPath: `${zoomJSLib}${zoomJSAVLib}/${jsmediaVersion}_video_m.min.js`,
    sharingWorkerPath: `${zoomJSLib}${zoomJSAVLib}/${jsmediaVersion}_sharing_s.min.js`,
    sharingMtWorkerPath: `${zoomJSLib}${zoomJSAVLib}/${jsmediaVersion}_sharing_m.min.js`,
    videoSIMDWorkerPath: `${zoomJSLib}${zoomJSAVLib}/${jsmediaVersion}_video_simd.min.js`,
    sharingSIMDWorkerPath: `${zoomJSLib}${zoomJSAVLib}/${jsmediaVersion}_sharing_simd.min.js`,
};

WasmFiles = {
 encode: `${zoomJSLib}${zoomJSAVLib}/audio.encode.wasm`,
 decode: `${zoomJSLib}${zoomJSAVLib}/video.decode.wasm`,
 decodeMt: `${zoomJSLib}${zoomJSAVLib}/video.mt.wasm`,
 decodeSimd: `${zoomJSLib}${zoomJSAVLib}/video.simd.wasm`,
};
```

I know there are some _not-so-pretty_ workarounds to make it work (such as copying files into the public folder). Is there a clean solution to this issue that's provided by webpacker? I'm thinking maybe there are helpers to get the url of an asset with their fingerprint like sprocket does?

**Comment by pedrofurtado** [comment]
Hey, @yoones ! 👋 

I did not understand the whole scenario. Your goal is copying files from `node_modules` to some folder path defined by application (to allow manipulation on them after)? If so, we can suggest copy-webpack-plugin ( https://github.com/webpack-contrib/copy-webpack-plugin ). We can help you with the initial setup to make it work with webpacker.

Let me know if I understand correctly your situation 🤝
