### ISSUE TITLE
Webpacker is loading files it should not rely on during webpacker:compile

### ISSUE THREAD

**Issue by nhh** [rails/webpacker#2909]
We have several points in our rails app where we fetch env variables and let the server gracefully die if this variable is not set. This works on all platforms where the belonging env variables are set. For example

There is a base url fetching needed for active storage url generation like this:

```ruby

Rails.application.routes.draw do
  default_url_options :host => ENV.fetch("BASE_URL")

  #...
end

```

When I am running the asset precompile/generation command I get this error.

```
RAILS_ENV=production bundle exec rails webpacker:compile
rails aborted!
KeyError: key not found: "BASE_URL"
...../Development/Ruby/my-app-backend/config/routes.rb:2:in `fetch'
```

This can be somewhat bypassed by using "NODE_ENV=production bin/webpack" but that leaves the manifest untouched resulting in a 500 thrown by the backend, after deployment.

`ActionView::Template::Error (Webpacker can't find application.css in`

Webpacker is very tightly coupled to the rails server process which makes it hard to "just" generate assets. It may be a simple bug that the env integration `gem 'dotenv-rails'` is not loaded or in a incorrect order idk.

gist: Why does webpacker rely on the whole rails app when its a "webpack wrapper"?

**Comment by pedrofurtado** [comment]
Hey, @nhh ! 👋 

Thanks for report!

Can you please test for us if this command works well?

```bash
BASE_URL=the-desired-value RAILS_ENV=production bundle exec rails webpacker:compile
```

let me know your result 🤝

**Comment by nhh** [comment]
Hi, @pedrofurtado ✋ 

Thank you for your answer. Manually sourcing the env variables is a workaround.

Is this the expected behavior? If so, this is unfortunate.

Let me know what you think 😀

**Comment by pedrofurtado** [comment]
@nhh , thanks for feedback! 

This kind of load, related to env variables from a `.env` file, cannot be made by webpacker itself. The best actor for this purpose is library `dotenv`.

You can make a simple integration between `dotenv` and `webpacker` using the binary files inside your application. Try to make this:

- Edit your `bin/webpack` and `bin/webpack-dev-server` files, to include (at the top of the file) something like this below:
```ruby
# Code snippet copied from: https://github.com/bkeepers/dotenv/#sinatra-or-plain-ol-ruby

require 'dotenv/load'
# or
require 'dotenv'
Dotenv.load
```

Then, try to execute `rails webpacker:compile`, for example, to verify if env variables are loaded correctly 🤝
