### ISSUE TITLE
assets:clean deletes lazy-loaded chunks

### ISSUE THREAD

**Issue by dkniffin** [rails/webpacker#2913]
We recently did a bunch of work around making a lot of our assets dynamic/lazy-loaded. Ultimately, it boiled down to swapping a lot of `import 'foo'` statements for `import('foo')` statements (though I also added a couple layers of abstraction around that in the process, but I don't believe that's relevant to this discussion). All of that works as expected. During compilation, new chunk files are created for each `import()` call, then when the `import()` call is made in the browser, the assets are loaded via a separate request. It has drastically reduced the size of our initial bundle, improving page size and SEO. Lazy-loading FTW! 

However, we've started seeing issues in our error tracker about `ChunkLoadError` because the assets are missing from the server. After some investigation, we believe what's going on is during deployment, `assets:clean` is incorrectly deleting the chunk files for some of the lazy-loaded assets. 

At first, we thought #2734 was the issue, but after digging some more, it looks like that won't solve our problem. The real culprit seems to be [`Webpacker::Commands#current_version`](https://github.com/rails/webpacker/blob/1aca8aaebd21a075d42e718d2b60dfba8e8d1b70/lib/webpacker/commands.rb#L65):

```rb
    def current_version
      packs = manifest.refresh.values.map do |value|
        value = value["src"] if value.is_a?(Hash)
        next unless value.is_a?(String)

        File.join(config.root_path, "public", "#{value}*")
      end.compact

      Dir.glob(packs).uniq
    end
```

This method reads in the `manifest.json` file, maps over the assets and adds them to the list of current asset files. However, this makes an assumption that all the current assets are listed in the `manifest.json` file (either as string values or nested under a `src` key in a hash value). From what I've gathered from digging this morning, lazy-loaded chunks are not included in that file at all. I'm not sure if that's by-design or an oversight, but it seems to be true, at least on our app. 

Side-note: With [`splitChunks()` enabled](https://github.com/rails/webpacker/blob/5-x-stable/docs/webpack.md#add-splitchunks-webpack-v4), another type of chunk file gets created inside the `entrypoints` key, and I believe those are also being missed. That's not the issue we're running into, but is also something that should likely be resolved. This should be as easy as drilling down into `entrypoints` and getting all the file names from in there. However, be aware that the structure of that `entrypoints` hash [seems to have changed in v4 of WebpackAssetsManifest](https://github.com/webdeveric/webpack-assets-manifest#new-in-version-4).

For the lazy-loaded chunks issue, I can think of a two possible solutions to this issue:
1. Webpack / [WebpackAssetsManifest](https://github.com/webdeveric/webpack-assets-manifest) (the plugin that writes the manifest.json file) could be updated to include the lazy-loaded chunks. This seems like the best solution if manifest.json is actually supposed to include all assets. I'm not sure if that's true or not though.
2. If manifest.json is not intended to include lazy-loaded assets, then those will need to be obtained in another way. One way might be to use [ChunkManifestWebpackPlugin](https://github.com/soundcloud/chunk-manifest-webpack-plugin) to make a `chunks-manifest.json` file or similar, then read that in and include that in the list of current files.

I hope that all makes sense. We've run into this issue on our production environment and as a result we've had to revert all of our lazy-loaded assets until we find a solution. I am willing to create a PR for either of the options above, but I need some direction first from someone with more knowledge on the Webpack manifest file as to which option makes more sense (or if there's something completely different that should be done instead).

**Comment by connorshea** [comment]
Oh my god is that why I've had that error in Sentry for the last year? Lmao

**Comment by dkniffin** [comment]
@gauravtiwari would you mind taking a look at this? I'm picking you to `@` because you're the one that merged #2734. I'm not sure if there's someone more relevant.

I'd really like to get this feedback so I can make the change and get it merged. This is a pretty important fix for us, because it's preventing us from lazy-importing our JS code, which impacts SEO and UX.

**Comment by rossta** [comment]
@dkniffin Thanks for this report. I agree this isn't desired behavior. 

Which version of Webpacker are you using? I believe I can replicate with v5.2.1 but haven't tried a v6 beta release yet.

By any chance are your dynamic chunks "un-named", e.g. `js/0-74574d082f00cc0d0f94.chunk.js`? Until it's addressed in the configuration, a workaround for you _might_ be to use the `webpackChunkName` magic comment. This will give the chunk a name and therefore a reference in the manifest (so chunks are properly handled in the clean task):

Examples:

```js
 import(/* webpackChunkName: "editor" */ "editor")
```

```js
import(/* webpackChunkName: "[request]" */ `../pages/${page}`)  // [request] generates name based on import
```

**Comment by dkniffin** [comment]
@rossta webpacker version 5.2.1

And no, we were not using named imports. I had recently tested adding this, but I didn't realize it would make a difference in the manifest.json. That's great! We were planning on adding them anyways, so this works out perfectly!

I'll leave this issue open because it still affects anyone who doesn't have named imports, but I think this resolves the issue for us.

Thank you so much! 🎉

**Comment by rogercampos** [comment]
For anyone else facing this issue, here's a monkeypatch until a proper solution is released:

```ruby
require 'webpacker/version'

if Webpacker::VERSION != "5.1.1"
  raise "Review this patch."
end

# https://github.com/rails/webpacker/issues/2913
#
# The assets:clean task is removing unnamed chunks because they're referenced in the manifest
# under a deeply nested hash named "entrypoints", and the `current_version` method here only
# checks for first level entries.
#
class Webpacker::Commands
  def deep_values(hash)
    hash.values.map {|x| x.is_a?(Hash) ? deep_values(x) : x }.flatten
  end

  def current_version
    packs = manifest.refresh.values.map do |value|
      next if value.is_a?(Hash)

      File.join(config.root_path, "public", "#{value}*")
    end.compact

    packs += deep_values(manifest.refresh["entrypoints"]).map {|value|
      File.join(config.root_path, "public", "#{value}*")
    }

    Dir.glob(packs).uniq
  end
end
```

**Comment by tsrivishnu** [comment]
Facing this issue as well. Tracked down that this is the issue for missing chunks on production and staging envs. `assets:clean` was deleting unnamed chunks. 

Will be using the monkey patch for now.

**Comment by dkniffin** [comment]
@rogercampos @tsrivishnu (and anyone else who comes in later) Just to point it out: the solution that actually solved this issue for us (we're running it on production now, and I'm 99.9% this issue is gone) was to add the `/* webpackChunkName: "[request]" */` magic comment. That names the chunks, which makes them appear in `manifest.json`, which prevents them from being deleted.

**Comment by tsrivishnu** [comment]
@dkniffin Thanks for the update. I did try that option initially and it seemed very promising. However, my experience with front-end technologies is not enough for me to identify all the cases that lead to un-named chunks. I was only able to identify the simple cases. Until my front-end team resolves them, my only alternative for a quick fix is to use the monkey-patch. 

I will also post an update when we manage to resolve those un-named chunks.

**Comment by jamesarosen** [comment]
The monkeypatch doesn't work for us because the missing assets are unnamed ones like `16-e7f6f2726128249b1600.chunk.js`. Those don't show up _anywhere_ in the `manifest.json`.

And using `import(webpackChunkName: "[request]" 'some/path')` just resulted in `public/assets/js/[request]-ed4f692f3e0a1df907e0.chunk.js`.

Lastly, I don't see a way to add Webpack comments for importing CSS from JS
```js
import { Foo } from '@example/foo'
import '@example/foo.scss' // This results in public/assets/css/45-83eb2e1984f0038f71ad.css
```

**Comment by jamesarosen** [comment]
I ended up fixing this by combining `webpack-manifest-plugin` with a patch for `Webpacker::Commands` based on @rogercampos's work above:

```js
// config/webpack/environment.js:

const { WebpackManifestPlugin } = require('webpack-manifest-plugin')

plugins: [
  new WebpackManifestPlugin({ fileName: 'chunk-manifest.json  }),
]
```

```rb
# config/initializers/webpack.rb:

# frozen_string_literal: true

require 'webpacker/version'

if Webpacker::VERSION != "5.2.1"
  raise "Review this patch, then update this version constraint"
end

# https://github.com/rails/webpacker/issues/2913
#
# The assets:clean task is removing unnamed chunks (e.g. `js/45-bf451ca90c.js`)
# because they're not in `public/assets/manifest.json`. We added a separate
# `WebpackManifestPlugin` that outputs a full manifest to `chunk-manifest.json`.
# This patch combines the two so we get a full list of currently-used assets
# and don't inadvertently delete needed assets.
class Webpacker::Commands
  alias clean_without_chunks clean
  alias current_version_without_chunks current_version

  def clean(*args)
    return unless File.exist?(webpack_manifest_path)
    clean_without_chunks(*args)
  end

  def current_version
    webpack_assets = JSON.parse(File.read(webpack_manifest_path)).values.map do |path|
      File.join(config.root_path, 'public', path)
    end

    (current_version_without_chunks + webpack_assets + [webpack_manifest_path]).uniq
  end

  private

  # See config/webpack/environment.js
  def webpack_manifest_path
    File.join(config.root_path, 'public', 'assets', 'chunk-manifest.json')
  end
end

```

**Comment by justin808** [comment]
The clean code was updated 4 months ago https://github.com/rails/webpacker/pull/2863.

@jamesarosen @dkniffin @tsrivishnu Can you check if there is still an issue, and if so, please open a PR.

**Comment by jamesarosen** [comment]
#2863 seems to only be available on the 6.0 RCs. 

Testing:

1. Upgrade to `webpacker@6.0.0.rc.6`
1. Run `rake assets:precompile`. This generates files like `public/assets/js/50-d41979c3aacbb678aa8d.chunk.js`. Those numbered files still don't appear in `public/assets/manifest.json`.
2. Run `rake assets:clean`. This does nothing because `count=2, age=3600` and the files are only a few seconds old.
3. Run `rake assets:clean[1, 10]`. Because of the way `assets:clean` depends on `webpacker:clean`, `args=[nil, nil, "1", "10"]`, so `count` and `age` become their defaults. This is a bug for another day.
4. Run `rake webpacker:clean[1,10]`. This deletes the numbered `.js` files, but not the `.js.map` files. So now we're going to build up `.js.map` files over time until we run out of disk space.

**Comment by justin808** [comment]
@jamesarosen Thank you so much for your thorough test!

> 2. Run rake assets:precompile. This generates files like public/assets/js/50-d41979c3aacbb678aa8d.chunk.js. Those numbered files still don't appear in public/assets/manifest.json.

Is your conclusion that there is still is the bug?

I'm personally **not interested** in working on this code since my deploys are all on Heroku, where the slug (a compressed file system for a deployment) is built from scratch each time. 

In fact, I'd love to see an ENV variable to opt-out of the clean rather than having to modify the rake tasks.

```ruby
Rake::Task['webpacker:compile'].clear
```

@guillaumebriday thoughts on this one?

@jamesarosen could you consider making a PR to improve this?
I think you've got the code above: https://github.com/rails/webpacker/issues/2913#issuecomment-956774220

Good unit tests that demonstrate the bugs and how they are fixed would be very much appreciated!

**Comment by justin808** [comment]
@dhh @guillaumebriday While this is a bug, I don't think it's worth holding up the v6 release for this.

**Comment by jamesarosen** [comment]
> Is your conclusion that there is still is the bug?

I think so, yes.

> I'm personally not interested in working on this code since my deploys are all on Heroku

Interestingly, ours are also on Heroku. We use [this addon](https://elements.heroku.com/buildpacks/epihubinc/heroku-buildpack-cachesave) to cache compiled assets, so we're not starting from a truly blank slate for each deploy.  Before we implemented a workaround (posted above), our slug would grow without bound until the build failed, at which point we would clean up old assets and start fresh.

**Comment by justin808** [comment]
@jamesarosen I'd rather use S3 for caching between builds. Caching bundles is something that [React on Rails Pro](https://www.shakacode.com/react-on-rails-pro/) does. Yes, I wrote much of that.

**Comment by jerw-git** [comment]
@dhh it appears this was closed as completed but above the people said it was still a bug. I am working on upgrading all the way to Shackapacker for webpacker v6 but need to know when to remove the monkey patch.

**Comment by justin808** [comment]
@jerw-git Can you please reopen this on [Shakapacker](https://github.com/shakacode/shakapacker/issues)? We'll try to get this resolved ASAP.
