### ISSUE TITLE
webpacker:check_yarn doesn't support versioning of yarn nightly builds

### ISSUE THREAD

**Issue by pustomytnyk** [rails/webpacker#2926]
The script relies on `SemanticRange.satisfies?` which doesn't seem to support versions like `1.23.0-20210103.1434` (current yarn Classic Nightly version). That leads to `Webpacker requires Yarn ">=1 <3" and you are using 1.23.0-20210103.1434` error.

**Comment by pedrofurtado** [comment]
Hey, @pustomytnyk ! 👋 

Thanks for report. 

After read your description, maybe this can related to `semantic_range` gem, that is a webpacker dependency. I suggest open a issue directly in semantic_range repository 🤝

**Comment by pustomytnyk** [comment]
I see, `satisfies?` in node semver has optional `includePrerelease` flag. I'll try to add it to SemanticRange.

**Comment by pedrofurtado** [comment]
@pustomytnyk Good news!

Please, could you link the issues/PRs that you opened in semantic_range repo, to be visible in this issue?

After the merge and release, we can update the version of semantic_range used in webpacker, to provide this new feature 🚀

Let us know the progress of this 🤝

**Comment by pedrofurtado** [comment]
@pustomytnyk Let us know when you have any progress with this change in semantic_range gem 🤝 🍻  Then, we will be able to include this in webpacker 👍

**Comment by pustomytnyk** [comment]
(librariesio/semantic_range#74 prepares SemanticRange for the new option, then we'll add `include_prerelease` option in another PR, and then we'll finally be able to properly fix `check_yarn.rake`)

**Comment by jdelStrother** [comment]
FWIW, Yarn's latest installation instructions suggest `yarn set version 3.x`, which results in `Webpacker requires Yarn ">=1 <4" and you are using 3.1.0-rc.5`

For now I've stubbed out webpacker's version checks by adding the following to my rakefile:

```ruby
Rake::Task["webpacker:check_yarn"].clear_actions
```
