### ISSUE TITLE
Running Rails tests no longer compiles test assets unless NODE_ENV is set to "test"

### ISSUE THREAD

**Issue by lserman** [rails/webpacker#2927]
On an older app I use the code mentioned here: https://github.com/rails/webpacker/pull/360 to precompile my test assets (`Webpacker.compile`)

Starting a new app today off 6.0.0.beta.2 and the same no longer works. I think it is because this line: https://github.com/rails/webpacker/blob/master/lib/tasks/webpacker/compile.rake#L23 uses the production environment if `NODE_ENV` is unset, while in older versions it uses `Webpacker.env` (which is based on `RAILS_ENV` instead, and is correctly set to "test" in my case).

I'm not sure which environment we should trust, so maybe relying on `NODE_ENV` is fine. Just took me by surprise today and I had to dig around in source code to figure it out. Setting `NODE_ENV=test` fixed the problem.

**Comment by rossta** [comment]
@lserman Could you explain in more detail how to reproduce the issue? I don't understand from your description.

**Comment by rossta** [comment]
For more info, I've created a branch in a demo app on Webpacker 6 that runs Rails system tests without any Webpacker-specific configuration. Webpacker precompiles as expected when I run system tests. I don't have enough info from your description to understand how to reproduce the issue you're have.

https://github.com/rossta/webpacker-6.0.0.beta-pdfjs-demo/compare/chore/rspec
