### ISSUE TITLE
Question: Why does CSS only have contentHash in production mode? (webpacker 6)

### ISSUE THREAD

**Issue by t27duck** [rails/webpacker#2928]
Sorry if this has been answered before. (Context: webpacker 6 beta 5)

Looking at the impllmentation of the MiniCssExtractPlugin...

https://github.com/rails/webpacker/blob/master/package/environments/base.js#L66

```js
  if (moduleExists('css-loader') && moduleExists('mini-css-extract-plugin')) {
    const MiniCssExtractPlugin = require('mini-css-extract-plugin')
    plugins.push(
      new MiniCssExtractPlugin({
        filename: isDevelopment
          ? 'css/[name].css'
          : 'css/[name]-[contenthash:8].css',
        chunkFilename: isDevelopment
          ? 'css/[id].css'
          : 'css/[id]-[contenthash:8].css'
      })
    )
  }
```

Why is it that the files development mode do not include `contentHash`? If I make a change to a CSS file, the view will get the same filename as before and will get a cached copy of the old styles. This is the opposite of the JS files that, on change, gives me a new file based on the hash.

I'm able to work around it be removing the existing plugin and merging in my own instance where the contentHash is always part of the file...

```js
// base.js

const { webpackConfig, merge } = require('@rails/webpacker')
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
webpackConfig.plugins = webpackConfig.plugins.filter(p => p.constructor.name != 'MiniCssExtractPlugin')

const customConfig = {
  plugins: [
    new MiniCssExtractPlugin({
      filename: 'css/[name]-[contenthash:8].css',
      chunkFilename: 'css/[id]-[contenthash:8].css'
    })
  ],
  resolve: {
    extensions: ['.css']
  }
}

module.exports = merge(webpackConfig, customConfig)
```

I'm more curious as to why it's like this?

**Comment by mikker** [comment]
Can confirm. Seeing the same in my Safari with current `master` (beta 6). @t27duck's hack fixes it.

**Comment by swanson** [comment]
Looks like this change happened during the Webpack 5 changes https://github.com/rails/webpacker/pull/2802
