### ISSUE TITLE
6.0.0-beta.5 - Loaded dynamic imports does not use rails relative url root

### ISSUE THREAD

**Issue by frullah** [rails/webpacker#2930]
i am using map path with value from RAILS_RELATIVE_URL_ROOT env in `config.ru`

```ruby
...
map ENV["RAILS_RELATIVE_URL_ROOT"] || "/" do
  run Rails.application
end
```

i also set relative_url_root in production environment configuration (`config/environments/production.rb`)

```ruby
...
config.relative_url_root = ENV["RAILS_RELATIVE_URL_ROOT"]
...
```

when i use dynamic import in some JS code like this

```javascript
...
await import('datatables.net').then(m => m.default())
...
```

the loaded dynamic import access path does not prefixed with relative url root,
which is __/packs/js/...__ instead of __\<relative url root\>/packs/js/...__

**Comment by justin808** [comment]
@frullah Any progress toward solving this issue?

**Comment by frullah** [comment]
@justin808 i solved it by removing all related `relative_url_root` config, and changing a little bit web server configuration for Rails app.


Here are the full steps
1. adding a new IP address to the server
2. creating a new server block in NGINX web server that listening on the new IP address
3. moving all web server configuration for Rails app into the new server block (previously it was combined with other app config in one NGINX server block)
4. removing all `relative_url_root` related config in Rails app. i.e `config.relative_url_root` and `config.action_cable.url`.


It also simplified the configuration on the web server, so I don't need to worry about this problem in the future.
