### ISSUE TITLE
Webpacker 6: webpack dev server output not colored

### ISSUE THREAD

**Issue by tagliala** [rails/webpacker#2936]
Hi,

I don't know if this change is intended. I've tried the search functionality but I wasn't able to find a duplicate or a commit documenting the change

### How to replicate

```
$ rails new test-webpacker6-webpack-dev-server --skip-active-record --skip-javascript
$ cd test-webpacker6-webpack-dev-server/
$ echo "gem 'webpacker', git: 'https://github.com/rails/webpacker.git'" >> Gemfile
$ bundle
$ rails webpacker:install
$ bin/webpack-dev-server
```

### Actual Result

![image](https://user-images.githubusercontent.com/556268/109046420-02156400-76d5-11eb-9be0-675e0dc7fa0b.png)

### Expected Result

![image](https://user-images.githubusercontent.com/556268/109047110-c75ffb80-76d5-11eb-80a3-d1f89ec2de65.png)

**Comment by rossta** [comment]
I believe the default option for `devServer.stats.colors` changed from `true` to `false` within the `webpack-dev-server` package: https://github.com/webpack/webpack-dev-server/pull/2660/files#r447299960

To re-enable for Webpacker 6:
```js
// config/webpack/development.js
process.env.NODE_ENV = process.env.NODE_ENV || 'development';

const { merge } = require('@rails/webpacker');

const webpackConfig = require('./base');

module.exports = merge(webpackConfig, {
  devServer: {
    stats: {
      colors: true,
    },
  },
});
```

**Comment by tagliala** [comment]
Thanks, it works!

I was surprised because I'm using the same `webpack-dev-server` version (3.11.2) in both webpacker v5 and v6 (so `colors: false` in both).

I've identified the root of the issue, it is just because webpacker 5 runs `webpack-dev-server`, which sets some defaults while webpacker uses `webpack serve`, and it doesn't go through `webpack-dev-server/lib/utils/createConfig.js`

Refs:
https://github.com/rails/webpacker/blob/b7069f4618de51415a4449908346a3c0853880dc/lib/webpacker/dev_server_runner.rb#L69-L73

https://github.com/rails/webpacker/blob/9ec5daabc5daea1c96f538d7af1f807ae9b077ec/lib/webpacker/dev_server_runner.rb#L50-L54
