### ISSUE TITLE
Webpacker 6: missing overlay errors (solved in webpack-dev-server 4)

### ISSUE THREAD

**Issue by tagliala** [rails/webpacker#2938]
### edit2: I can confirm that with the main branch of `webpack-dev-server` and some edits to `development.js`, overlay errors are back

---

Hi,

I don't know if this is an issue with webpacker itself. With webpacker 5, I was able to see lint errors on the front-end, now I just get "failed to compile" error

### How to replicate

1. Create application
```sh
$ rails _6.1.3_ new test-webpacker6-webpack-dev-server --skip-active-record --skip-javascript
$ cd test-webpacker6-webpack-dev-server
$ echo "gem 'webpacker', git: 'https://github.com/rails/webpacker.git'" >> Gemfile
$ bundle
$ rails webpacker:install
$ sed -i '3i\ \ root "pages#home"' config/routes.rb
$ sed -i '10i\ \ \ \ <%= javascript_pack_tag "application" %>' app/views/layouts/application.html.erb
$ rails g controller Pages home
```
2. Launch `bin/webpack-dev-server`
3. Launch the server `rails s` and navigate to `http://localhost:3000/`
4. Save `application.js` to check that hot reload works ("Hello World from Webpacker" appears in the console)
5. Make a syntax error in `application.js`
6. Save `application.js`

### Before (Webpacker 5)

![image](https://user-images.githubusercontent.com/556268/109172659-4eb77880-7783-11eb-9979-dfeeebd95052.png)

### After (Webpacker 6)

![image](https://user-images.githubusercontent.com/556268/109173001-a655e400-7783-11eb-8b8b-5b1056afc61d.png)

I can still see errors in `webpack-dev-server` console

![image](https://user-images.githubusercontent.com/556268/109173194-def5bd80-7783-11eb-93b1-40583e3b486b.png)

Ref: #2994

**Comment by tagliala** [comment]
Since webpack-dev-server 4 is now in RC, I wonder why if it is possible for Webpacker 6 to migrate to the new version

**Comment by dhh** [comment]
Upgraded to webpack-dev-server 4.
