### ISSUE TITLE
The latest Yarn Classic version (1.23.0-20210103.1434) is not being recognized as valid

### ISSUE THREAD

**Issue by dgacek** [rails/webpacker#2941]
When I run `rails new` I get this message at the end
`Webpacker requires Yarn ">=1 <2" and you are using 1.23.0-20210103.1434
Please upgrade Yarn https://yarnpkg.com/lang/en/docs/install/
Exiting!`

**Comment by pedrofurtado** [comment]
Related: https://github.com/rails/webpacker/issues/2926
