### ISSUE TITLE
Can't find executable for yarn on Capistrano deploy to server; server has yarn installed

### ISSUE THREAD

**Issue by walt93** [rails/webpacker#2945]
I am running $bundle exec rails webpacker:install in Rails v6.0.3.4 and am getting the following error:

/home/deploy/.rbenv/versions/2.6.6/lib/ruby/2.6.0/bundler/rubygems_integration.rb:462:in `block in replace_bin_path'
can't find executable yarn for gem yarn. yarn is not currently included in the bundle, perhaps you meant to add it to your Gemfile?

Deploy is working on another server (which should be nearly identical in configuration) and also working on local/dev.

Has anybody seen this?

**Comment by frullah** [comment]
are you using node version manager like fnm or nvm ?
if so, try to add node bin path into environment variable PATH by calling `set :default_env, { path: "<node bin>" }`

**Comment by mcmire** [comment]
Is there a backtrace that you could post? For some reason it thinks that Yarn is a Ruby gem, but that's all that is visible from your error. 

Also, you say that the other server is _nearly_ identical in configuration. What are the differences?

**Comment by walt93** [comment]
Both were installed clean from Ubuntu 18.04. One was a dedicated server, the other a VPS. When queried the hosting provider claimed no differences and were clearly misinformed. I gave up on the project and moved it to Heroku.
