### ISSUE TITLE
Create folder structure by default and folder naming suggestions?

### ISSUE THREAD

**Issue by MtnBiker** [rails/webpacker#2951]
Following https://github.com/rails/webpacker#upgrading create the empty folders (entrypoint, source, images) and add application.css by default with notes on how to use. I just created a new app and application.js was created which is a good start. 

I realize that this is a moving target. Was glad to see the new packs folder. 

Also why can't the application.* files be at the top level of the packs folder if there are only going to be two of them. Two advantages: 1) one less folder (entrypoint), 2) "logical" to have these files at higher level since they can reference the other folders and are accessed first. 

But would also make some sense (to me anyway) to have packs named webpack(er) and src be named javascript. But I'm not very knowledgeable about Rails, but have been dealing with some of this lately.

Thank you to all working to improve webpacker.

**Comment by anitagraham** [comment]
There might not be only two of them - you can have multiple entrypoints.

Why, I would ask, are there two of them.  That `application.css` gives me the shivers. 
 But yes - they were OK at the top of the tree.

Naming is always a problem, but calling them anything like 'webpack' presupposes that 'webpack' is going to the be processer foreverafter. 'Packs' as a top level name doesn't fully explain what lives underneath, either. 

I liked `javascripts`, with `packs` and `source` below, and I suppose there is nothing to stop me continuing to use that.

Where are these things discussed before they are pushed into the public domain?

**Comment by justin808** [comment]
Please check the latest docs and reopen if you think this issue is still relevant.
