### ISSUE TITLE
Webpacker 6 Buffer is not defined

### ISSUE THREAD

**Issue by gsouf** [rails/webpacker#2953]
Hi,

I just upgraded to version 6 of webpacker and I have a small issue that I didn't have with webpacker 5.
One of the vendor in my app uses the class "Buffer".

I suspect it has something to do with some polyfill not being applied anymore.

My first impression is that it could come from the fact that webpacker 6 ignores the file `.babelrc` in which I defined a target for preset-env. ie:

```
"presets": [
    [
      "@babel/preset-env",
      {
        "targets": {
          "browsers": [
            "Edge >= 44",
            "last 5 versions"
          ]
        }
      }
    ],
    "@babel/preset-react"
  ],
```

What do you think?

-------

Note that just adding anywhere in my js works:

```
window.Buffer = class Buffer {};
```

As I don't really need the Buffer class it works but I'm not happy with this solution as the initial error itself might indicate that something else is not configured properly

**Comment by gsouf** [comment]
It seems that is has something to do with the fact that webpack 5 has removed automatic nodejs polyfill.

https://webpack.js.org/blog/2020-10-10-webpack-5-release/#automatic-nodejs-polyfills-removed

Maybe something that should be specified in the upgrade notes?

**Comment by dhh** [comment]
Do open a PR with a note in the v6 upgrade instructions.
