### ISSUE TITLE
5.x Release

### ISSUE THREAD

**Issue by Pezmc** [rails/webpacker#2959]
While the final 6.x release is edging closer, there are a number of 5.x backport PR's that are sitting [waiting to be released](https://github.com/rails/webpacker/pulls?q=is%3Apr+is%3Aopen+base%3A5-x-stable), some since late January.

https://github.com/rails/webpacker/pull/2900
https://github.com/rails/webpacker/pull/2903
https://github.com/rails/webpacker/pull/2912
https://github.com/rails/webpacker/pull/2914

What's the process for getting a release cut? How can I help here?

CC: @gauravtiwari, @pedrofurtado, @simonoff, @guillaumebriday

**Comment by sam0x17** [comment]
We have a very strong need for the dart sass / `sass` stuff to get merged so happy to help however we can. Any idea when this will get released?

**Comment by damienh** [comment]
I have a question about future 5.x releases. Iv noticed two recent security alerts tied to dependencies in version 5 of webpacker Regular Expression Denial of Service (ReDoS) ssri (npm)
 https://github.com/advisories/GHSA-vx3p-948g-6vhq and Regular Expression Denial of Service (ReDoS) is-svg (npm) https://github.com/advisories/GHSA-7r28-3m3f-r2pr. 
 
I know this doesn't relate to version 6, but given that's still in beta, we wondered if a patch for version 5 will be released address these advisory notices.

**Comment by gauravtiwari** [comment]
Released in 34c02ffb411fe307f15a644362e5fda36f868388

Thank you :)
