### ISSUE TITLE
css assets not fingerprinted in development

### ISSUE THREAD

**Issue by fredplante** [rails/webpacker#2963]
Hi,

I was playing with a Rails 6.1 & tailwindcss. I updated to latest webpacker beta, then added postcss and other needed packages.

I have it working but I was surprised the stylesheet was not fingerprinted. I had to dig in sources to understand why:

https://github.com/rails/webpacker/blob/master/package/environments/base.js#L69-L76

What's the reason of this and why treating css files differently than js file in this regard?

Thanks

**Comment by fredplante** [comment]
Because of this the browser is always caching the stylesheet

**Comment by rossta** [comment]
This is a duplicate of #2928 and will be fixed by #2954

**Comment by fredplante** [comment]
Thanks @rossta, sorry for the noise
