### ISSUE TITLE
missing Runtime after upgrade to version 6

### ISSUE THREAD

**Issue by dvictory** [rails/webpacker#2966]
I am trying to upgrade to 6.0.0.pre.2.  I am running the default config, and have ripped out as much as I can to get the bare minimum install.  I noticed that the webpack output is now in two files  application-xx.js and runtime-xxx.js.  It was only 1 file in version 5.  That's fine, but when I add the files via 
```
javascript_pack_tag 'application'
```

it only adds the script tag for application.  I saw another issue where too many were getting added when you had multiple javascript_pack_tag tags.  I have the opposite issue, where I get none.  I can fix it by adjusting the optimization config to have runtimeChunk: false, which moves all back to 1 file.  But I wanted to see what the issue might be with the default install.  Am I missing a step in the upgrade?  Do I need to explicitly add a javascript_pack_tag for runtime.

Thanks

**Comment by bpo** [comment]
@dvictory I think you want to try `6.0.0.beta.6` (the latest 6.0 pre-release) rather than `6.0.0.pre.2` which is outdated. See related: #2940

**Comment by dvictory** [comment]
Thanks @bpo that did it!  Need to update, https://github.com/rails/webpacker/blob/master/6_0_upgrade.md.
