### ISSUE TITLE
Passing configuration to `mini-css-extract-plugin` in Webpacker setup

### ISSUE THREAD

**Issue by hamza** [rails/webpacker#2967]
Hello,

Forgive me if this question has been documented/answered elsewhere. I did do a search and could not find anything.

I'm in process of updating our Rails app to use Webpacker 6. We are using Webpacker to process our stylesheets.

I have a very simple need to pass configuration options to the `mini-css-extract-plugin`, in particular the [`ignoreOrder` option](https://www.npmjs.com/package/mini-css-extract-plugin#ignoreOrder).

When I attempt to merge a custom configuration for the plugin in to Webpacker, I get the error `Error: Didn't get a result from child compiler`, which according to Google happens when multiple loaders are configured to process the same file type.

That would seem to make sense since I assume Webpacker is setting up its own instance of the plugin behind the scenes, as I can see [here](https://github.com/rails/webpacker/blob/45cc2a2690964a916a4a64ddf626b70525c91e6f/package/environments/base.js#L66-L78).

Are there any recommendations for how I could address this?

**Comment by OscarBarrett** [comment]
You should be able to modify it in place like so:

```js
const { webpackConfig } = require('@rails/webpacker');

const cssPlugin = webpackConfig.plugins.find(p => p.constructor.name === 'MiniCssExtractPlugin');
cssPlugin.options.ignoreOrder = true;

module.exports = webpackConfig; // or merge(webpackConfig, customConfig);
```

**Comment by hamza** [comment]
Thank you @OscarBarrett, that helped

**Comment by choznerol** [comment]
Thanks @OscarBarrett for the snippet. However, in my case (webpacker 5.2.1) all the `p.constructor.name` were `"Object"` so I have to match with the `"key"` property:
```diff
const { webpackConfig } = require('@rails/webpacker');

- const cssPlugin = webpackConfig.plugins.find(p => p.constructor.name === 'MiniCssExtractPlugin');
+ const cssPlugin = webpackConfig.plugins.find(p => p.key === 'MiniCssExtract');
cssPlugin.options.ignoreOrder = true;

module.exports = webpackConfig; // or merge(webpackConfig, customConfig);
```
P.s. `"MiniCssExtract"` can be found [here](https://github.com/rails/webpacker/blob/5-x-stable/package/environments/base.js#L37) from the `5-x-stable` branch
