### ISSUE TITLE
JS won't work on a freshly generated Rails 6.1.3.1 app with Webpacker 6.0.0.beta.6

### ISSUE THREAD

**Issue by cloud69420** [rails/webpacker#2972]
Hello!

Can anyone tell why my freshly generated app won't output "Hello World from Webpacker" in the browser console?

```
/* eslint no-console:0 */
// This file is automatically compiled by Webpack, along with any other files
// present in this directory. You're encouraged to place your actual application logic in
// a relevant structure within app/javascript and only use these pack files to reference
// that code so it'll be compiled.
//
// To reference this file, add <%= javascript_pack_tag 'application' %> to the appropriate
// layout file, like app/views/layouts/application.html.erb


// Uncomment to copy all static images under ../images to the output folder and reference
// them with the image_pack_tag helper in views (e.g <%= image_pack_tag 'rails.png' %>)
// or the `imagePath` JavaScript helper below.
//
// const images = require.context('../images', true)
// const imagePath = (name) => images(name, true)

console.log('Hello World from Webpacker')
```
Here's the compiled version in the public folder:
```
(self.webpackChunkwebpacker6=self.webpackChunkwebpacker6||[]).push([[34],{669:function(){},494:function(){console.log("Hello World from Webpacker")}},function(e){"use strict";var n=function(n){return e(e.s=n)};n(669),n(494)}]);
//# sourceMappingURL=application-2e022aa529c569f5dcfa.js.map%
```

Git log: https://dpaste.org/kwxx

**Comment by kramerdog** [comment]
Doesnt work for me either with Rails 6.1.2 app with Webpacker 6.0.0.beta.6.

But in my case this could be linked to not being able to get jQuery to load and getting this error:

```
Uncaught ReferenceError: $ is not defined
```

I have all of this in application.js

```
import $ from 'jquery';
window.jQuery = $;
window.$ = $;
```

and this in custom.js

```
module.exports = {
    resolve: {
        alias: {
            $: 'jquery/src/jquery',
            jQuery: 'jquery/src/jquery',
            jquery: 'jquery'
        }
    }
}
```

**Comment by kramerdog** [comment]
Update:

Adding this at the start of my Coffescript file (copied from application.js) works

```
import $ from "jquery"
window.jQuery = $;
window.$ = $;
```

but why isnt this picked up from application.js?

**Comment by mcmire** [comment]
@cloud69420 Any way you can share your repo? Unless this is a known issue I think that would probably make it easier for all of us to figure out what's going on.

**Comment by cloud69420** [comment]
@mcmire yep, sure thing: https://github.com/cloud69420/webpacker6

**Comment by mcmire** [comment]
@cloud69420 Gotcha. Yeah, I can definitely reproduce it. `application.js` is being loaded, I can see it, but no matter what you put in that file nothing happens. Very strange.

**Comment by juliusdelta** [comment]
I checkout the test repo from [this comment](https://github.com/rails/webpacker/issues/2972#issuecomment-813128659) and confirmed this same issue with at least back to the v 6.0.0-beta-3 tag. Couldn't go back further cause I ran out of time. 

I began to wonder if it was an implementation problem, but wasn't 100% sure as I didn't have time to test further. If I get some time later today I'll continue some investigation to get more details.

**Comment by mcmire** [comment]
Is this a duplicate of #2955?

**Comment by mcmire** [comment]
@cloud69420 I think you might have the wrong version of Webpacker installed. You need to be explicit about which version is being installed in the Gemfile instead of using the twiddle-wakka, otherwise one of the `pre` versions will get installed. Might also be good to remove the '^' from the same dependency in your `package.json`. Then you should be good. See here: https://github.com/rails/webpacker/issues/2955#issuecomment-803527956

**Comment by cloud69420** [comment]
@mcmire apologies for the late reply! Being explicit did indeed solve my problem - thank you so much!
