### ISSUE TITLE
Error on production.js with css-minimizer-webpack-plugin

### ISSUE THREAD

**Issue by beqdot** [rails/webpacker#2982]
I use standard config and got this error when trying to precomplie production or using ./bin/webpack in a production mode.
Just add css-minimizer-webpack-plugin as it's advised in the readme

```
Invalid options object. Css Minimizer Plugin has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'sourceMap'. These properties are valid:
   object { test?, include?, exclude?, minimizerOptions?, parallel?, warningsFilter?, minify? }
```
Webpacker 6.0.0-beta.6

**Comment by stevestmartin** [comment]
Looks like css-minimizer-webpack-plugin just went 2.0 yesterday and they removed this option, I was able resolve by downgrading css-minimizer-webpack-plugin to 1.3.0

**Comment by mcmire** [comment]
Looks like we have two options to fix this in Webpacker:

* ask people to install css-minimizer-webpack-plugin@^1.0.0 (with a disclaimer that 2.x is not supported)
* ask people to install css-minimizer-webpack-plugin as is (no exact version; latest version assumed) and remove `sourceMap: true` from the set of options passed to the plugin

Does that seem correct? If so, I'm inclined to submit a PR for the second option.
