### ISSUE TITLE
Webpacker 6 beta not compatible css-minimizer-webpack-plugin  2.0 in production mode

### ISSUE THREAD

**Issue by t27duck** [rails/webpacker#2986]
Version 2.0 of `css-minimizer-webpack-plugin` dropped about a week ago. One of the breaking changes is the removal of the `sourceMap` option which the current beta uses in production mode. See here: https://github.com/rails/webpacker/blob/f1b06c7fd5bc4b7fc7128742d1078466b94af71f/package/environments/production.js#L40

Pinning `css-minimizer-webpack-plugin` keeps things working for now.

Plugin change log: https://github.com/webpack-contrib/css-minimizer-webpack-plugin/blob/master/CHANGELOG.md

**Comment by n-rodriguez** [comment]
https://github.com/webpack-contrib/css-minimizer-webpack-plugin/commit/8e5db6048f8f6fd9e853a03954e4625b1eb90f58#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R68

**Comment by n-rodriguez** [comment]
Duplicate https://github.com/rails/webpacker/issues/2982

**Comment by guillaumebriday** [comment]
thanks @n-rodriguez
