### ISSUE TITLE
version 5.3.0 is not in changelog

### ISSUE THREAD

**Issue by runephilosof-abtion** [rails/webpacker#2998]
Version 5.3.0 was recently released.
But not mention of it in the master branch's changelog.
The 5-x-stable branch's changelog mentions version 5.3.0, but not as released.

When I noticed, I was worried, for a minute, that a hacker had managed to slip in a release containing a backdoor.

Could something be setup to avoid this kind of mistake in releasing?
Please update the master branch's changelog.
Also, the 5-x-stable changelog seems a bit wrong, the yarn 2 support was in 5.2.2.
5.3.0 only adds the backup item.

**Comment by severin** [comment]
5.2.2 is also not in the CHANGELOG

**Comment by dhh** [comment]
Feel free to add a PR with the backfill.

**Comment by severin** [comment]
Seems like this happened in https://github.com/rails/webpacker/commit/c4c7fa772197a2f83c9e1e5025910e874e5fa7bf
