### ISSUE TITLE
How stable is v6.0.0.beta.7?

### ISSUE THREAD

**Issue by joker-777** [rails/webpacker#2999]
Hi, I saw that you've been working on webpacker 6 since December last year. How stable is the current beta version? Are you planning to add bigger changes? When are you going to release it officially?

Thanks for your great work!

**Comment by mcmire** [comment]
I too would like to know what remaining work is being targeted for v6. There are fair amount of issues that have been filed for the rcs and betas, and while I can identify some of them that _I_ would like to see addressed, it is difficult to know how far away from the finish line the current beta release is and what the maintainers feel is critical for a proper v6 release. Is it possible to create a meta-issue with a checklist of links to issues/PRs?

**Comment by t27duck** [comment]
Using 6 beta7 in 2-3 apps right now without issue... once I got through the upgrade guide and understood what it is webpacker 6 is and isn't now (read: more of a light wrapper around webpack with some defaults for plugins).

**Comment by johnpash** [comment]
Sorry to hi-jack this thread, but I just have a quick (related?) question. When I run `yarn outdated` it's telling me that pre.2 is newer than beta.7. Is this just because the word "pre" is alphabetically after the word "beta"? Or is pre.2 actually the latest?

```
Package          Current      Wanted      Latest Package Type URL                                    
@rails/webpacker 6.0.0-beta.7 6.0.0-pre.2 5.3.0  dependencies https://github.com/rails/webpacker  
```

**Comment by joker-777** [comment]
@johnpash I'm not sure why it shows you first the `pre` versions but you can checkout the latest versions [here](https://www.npmjs.com/package/@rails/webpacker)

**Comment by texpert** [comment]
> Sorry to hi-jack this thread, but I just have a quick (related?) question. When I run `yarn outdated` it's telling me that pre.2 is newer than beta.7. Is this just because the word "pre" is alphabetically after the word "beta"? Or is pre.2 actually the latest?

Yes, the issue is in the alphabetical order. You can make beta-7 a hard requirement in package.json: `"@rails/webpacker": "6.0.0-beta.7"`

**Comment by justin808** [comment]
See #3031. I just fixed CSS Modules with HMR. 

This definitely should go into a 6.0.0 final release.

**Comment by dhh** [comment]
6.0.0.rc.1 has been released.
