### ISSUE TITLE
Custom source path is not being set early enough in the Rails initialization process

### ISSUE THREAD

**Issue by agrobbin** [rails/webpacker#3001]
This is a new issue related to https://github.com/rails/webpacker/pull/2231#issuecomment-564049553, which unfortunately hasn't gotten the visibility I hoped it would!

When we set a custom `source_path` in `config/webpacker.yml` (in our case, `app/frontend`), the [`javascript_path` Rails config assignment](https://github.com/rails/webpacker/blob/532eb2fa92ea3af21554d603e5b628809b4059cc/lib/webpacker/railtie.rb#L50-L54) is not occurring early enough in the app initialization process to be properly ignored by [`Rails::Engine::Configuration#paths`](https://github.com/rails/rails/blob/a6a9fed1719a3cfe47eb1566ae4d6034374fd809/railties/lib/rails/engine/configuration.rb#L38-L73).

Based on what I can see, `Rails::Engine::Configuration#paths` is invoked before `javascript_path` has been set, which causes it to use the default of `"javascript"`, and eventually causes the [`eager_load!`](https://github.com/rails/rails/blob/v6.0.1/railties/lib/rails/application/finisher.rb#L116-L125) initializer block to fail due to Zeitwerk errors.

If someone can look into this, and maybe point me in the right direction for how best to fix this, that'd be awesome, thanks!

**Comment by jaredbeck** [comment]
To work around the zeitwerk error, you might try adding

```
# bottom of config/application.rb
Rails.autoloaders.main.ignore(
  Rails.root.join('app/packs') # or app/frontend, or whatever
)
```

**Comment by dhh** [comment]
cc @fxn Any good ideas on how to improve the ergonomics here?

**Comment by fxn** [comment]
Hey, I am focused on the removal of `classic`, but I'll think about it as soon as I can.

What's wrong here is the configuration used to setup the autoloader. In my view, the workaround is to fix the configuration:

```ruby
# In some initializer (untested).
ActiveSupport::Dependencies.autoload_paths.delete("#{Rails.root}/app/packs")
```

Better than configuring Zeitwerk with a root directory that is not a root directory.

But, in any case, that's just a workaround so that people facing this are not blocked. I'll follow up.

**Comment by agrobbin** [comment]
@fxn just checking in here, wondering if this is something you've been able to think about in the last couple of months!

**Comment by fxn** [comment]
@agrobbin oh! Does https://github.com/rails/webpacker/commit/77231548ee9981568ffbcadd7256a3ededcee834 fix this?

**Comment by justin808** [comment]
@agrobbin any info?
