### ISSUE TITLE
additional_paths

### ISSUE THREAD

**Issue by mices** [rails/webpacker#3006]
What should I put in additional_paths setting Should I put the path to my images and fonts here Do I need to use require.context in application.js in combination

**Comment by mcmire** [comment]
By default `app/javascript` is set up as the "default path" for Webpack. This means that if you want to import a module in your JavaScript, and you are not using a relative path, Webpack will look in `app/javascript` first to resolve that module. For instance if you have a file `app/javascript/foo.js`, and you have another file `app/javascript/bar.js`, you can require `foo.js` in `bar.js` by saying (note: here we assume that `foo.js` has a default export of `foo`):

``` javascript
import foo from "foo";
```

and Webpack will see `app/javascript/foo.js`.

The same mechanism is used when Webpacker resolves images and fonts. If you want to be able to use an image or font, make sure it is anywhere in `app/javascript`, and make sure to pre-`import` it (either in `application.js` or in any JavaScript file that `application.js` is importing). For instance, if you have a file `app/javascript/foo.png`, you should be able to display it by doing this:

``` javascript
// == app/javascript/packs/application.js ==
import 'foo.png';
```

``` erb 
<%# == some view == %>
<%= image_pack_tag 'foo.png' %>
```

So, you should not need to update `additional_paths` if you stick to these rules. The only time in which you would need to update this option is if you want to place your images/fonts/whatever in a different directory. For instance, if you wanted to put your fonts in `app/fonts` and images in `app/images`, you could update `additional_paths` like so:

``` yaml
additional_paths: ['app/fonts', 'app/images']
```

Now you can have a file `app/images/foo.png` and be able to use it the same way as above.

Hope that helps!
