### ISSUE TITLE
Few confusions

### ISSUE THREAD

**Issue by rctneil** [rails/webpacker#3007]
In the upgrade docs it states to change `app/javascript` to 'app/packs' and `packs` to `entrypoints`.  This makes sense to me, but when you perform webpacker:install, those paths are not set in the webpacker.yml file?

Also, what is the point of the application.css file in the entrypoints folder?    If I use this and import my .scss files into here, do I need to import my .scss files into application.js too?

Also, if using .scss, does the application.css file need to be renamed to .scss?   I'm just a bit confused as to what the purpose of the application.css file is and then how to use that with .scss?

**Comment by mcmire** [comment]
Make sure you're using the correct version of Webpacker. I've noticed the upgrade guide still mentions 6.0.0.pre.2. In your Gemfile you want to use:

``` ruby
gem 'webpacker', '~> 6.0.0.beta.7'
```

It's also best to be exact with the NPM package as well instead of using `next`:

```
yarn add @rails/webpacker@6.0.0-beta.7
```

As far as `application.css` goes, you don't need that in `app/packs/entrypoints`. If anything, you should place your Sass files in `app/packs` or in some other directory in `app/packs`. You can name this file anything, but yes, ultimately you will need to `import` your stylesheet in `application.js` so that Webpack will see it and compile it.

**Comment by rctneil** [comment]
@mcmire Thanks for the answers,

Just a couple of follow-up questions:

- If I import my stylesheets into my JS file, is it possible to only include the stylesheets into my views or would the JS have to come along as the styles are imported into that?

- I did try yesterday by moving my main `application.scss` file into `/entrypoints` and it did end up compiling and working.  I then tried both `stylesheet_pack_tag` and `javascript_pack_tag` both individually and together and got css and js separately and then together as expected.

Just wondering what the expected solution here is?

**Comment by mcmire** [comment]
Hi @rctneil,

Using JS files as entrypoints and importing CSS into JS is the more "traditional" way to use Webpack, which is what Webpacker is based on, so you will find more references to that if you choose to learn more about Webpack. That said, [Webpacker seems to configure Webpack in such a way]((https://github.com/rails/webpacker/blob/8c0e69ce65f4a35a52de2feba5dec2ec86b272aa/package/environments/base.js#L24-L25)) that CSS files can also be entrypoints. That means whether you want to place CSS files inside or outside of `entrypoints`, both seem to be valid ways of using Webpacker and both would produce the same result, as you've seen.

I realize I didn't answer your question about CSS vs. SCSS. You are free to use SCSS over CSS if you want, but you would need to rename the file `.scss`. In general Webpacker configures Webpack to use different strategies based on file extension. If you use `.css`, then the file will not get run through Sass; if you use `.scss` then it will.
