### ISSUE TITLE
Though the "loose" option was set to "false" in your @babel/preset-env config, it will not be used for @babel/plugin-proposal-private-methods since the "loose" mode option was set to "true" for @babel/plugin-proposal-class-properties

### ISSUE THREAD

**Issue by niedfelj** [rails/webpacker#3008]
I'm getting this warning over and over:

Though the "loose" option was set to "false" in your @babel/preset-env config, it will not be used for @babel/plugin-proposal-private-methods since the "loose" mode option was set to "true" for @babel/plugin-proposal-class-properties. The "loose" option must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object (when they are enabled): you can silence this warning by explicitly adding ["@babel/plugin-proposal-private-methods", { "loose": true }] to the "plugins" section of your Babel config.

**Comment by mcmire** [comment]
What version of Webpacker are you using (both Ruby gem and JavaScript package), and what is the content of your `babel.config.js`?

**Comment by dennyf** [comment]
Same issue here - just updated Webpacker to version 5.3.0 (from 5.2.1) and I'm getting this warning. Here is my `babel.config.js`:

```js
module.exports = function(api) {
  var validEnv = ['development', 'test', 'production']
  var currentEnv = api.env()
  var isDevelopmentEnv = api.env('development')
  var isProductionEnv = api.env('production')
  var isTestEnv = api.env('test')

  if (!validEnv.includes(currentEnv)) {
    throw new Error(
      'Please specify a valid `NODE_ENV` or ' +
        '`BABEL_ENV` environment variables. Valid values are "development", ' +
        '"test", and "production". Instead, received: ' +
        JSON.stringify(currentEnv) +
        '.'
    )
  }

  return {
    presets: [
      isTestEnv && [
        '@babel/preset-env',
        {
          targets: {
            node: 'current'
          }
        }
      ],
      (isProductionEnv || isDevelopmentEnv) && [
        '@babel/preset-env',
        {
          forceAllTransforms: true,
          useBuiltIns: 'entry',
          corejs: 3,
          modules: false,
          exclude: ['transform-typeof-symbol']
        }
      ]
    ].filter(Boolean),
    plugins: [
      'babel-plugin-macros',
      '@babel/plugin-syntax-dynamic-import',
      isTestEnv && 'babel-plugin-dynamic-import-node',
      '@babel/plugin-transform-destructuring',
      [
        '@babel/plugin-proposal-class-properties',
        {
          loose: true
        }
      ],
      [
        '@babel/plugin-proposal-object-rest-spread',
        {
          useBuiltIns: true
        }
      ],
      [
        '@babel/plugin-transform-runtime',
        {
          helpers: false,
          regenerator: true,
          corejs: false
        }
      ],
      [
        '@babel/plugin-transform-regenerator',
        {
          async: false
        }
      ]
    ].filter(Boolean)
  }
}
```

**Comment by Chwistophe** [comment]
Running webpacker 6.0.0-beta7 using webpack 5.36.2, this did the trick for me:

- `yarn add "@babel/plugin-proposal-private-methods"` 
- declare it in the babel plugins section in `package.json`: 

```javascript
"babel": {
    "presets": [
      "./node_modules/@rails/webpacker/package/babel/preset.js"
    ],
    "plugins": [
      "@babel/plugin-proposal-class-properties",
      "@babel/plugin-proposal-private-methods"
    ]
 }
```

You can then set the `loose` option on both directives keeping in mind they have to be the same.

**Comment by tagliala** [comment]
Hi,

I think I've found a way to replicate with a new webpacker installation

```sh
$ rails _6.1.3.2_ new test-babel-warning --skip-active-record --skip-javascript
$ cd test-babel-warning
$ echo "{ \"private\": true }" > package.json
$ echo "gem 'webpacker', '5.3.0'" >> Gemfile
$ echo "class Counter extends HTMLElement { #xValue = 0; }" >> app/javascript/packs/application.js
$ bin/webpack
```

Output:
```
Though the "loose" option was set to "false" in your @babel/preset-env config, it will not be used for @babel/plugin-proposal-private-methods since the "loose" mode option was set to "true" for @babel/plugin-proposal-class-properties.
The "loose" option must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object (when they are enabled): you can silence this warning by explicitly adding
	["@babel/plugin-proposal-private-methods", { "loose": true }]
to the "plugins" section of your Babel config.
Hash: 4e9d86a4e26c8c2229d9
Version: webpack 4.46.0
Time: 655ms
Built at: 05/10/2021 3:40:05 PM
                                     Asset       Size       Chunks                         Chunk Names
    js/application-fcea5ed095afa961aad5.js   8.71 KiB  application  [emitted] [immutable]  application
js/application-fcea5ed095afa961aad5.js.map   4.62 KiB  application  [emitted] [dev]        application
                             manifest.json  364 bytes               [emitted]              
Entrypoint application = js/application-fcea5ed095afa961aad5.js js/application-fcea5ed095afa961aad5.js.map
[./app/javascript/packs/application.js] 4.81 KiB {application} [built]
```

*NOTE* the warning will disappear after the second run of `bin/webpack` if the file does not change

Fix:
```diff
diff --git a/babel.config.js b/babel.config.js
index 4df1949..2fdd7d3 100644
--- a/babel.config.js
+++ b/babel.config.js
@@ -53,6 +53,12 @@ module.exports = function(api) {
           useBuiltIns: true
         }
       ],
+      [
+        '@babel/plugin-proposal-private-methods',
+        {
+          loose: true
+        }
+      ],
       [
         '@babel/plugin-transform-runtime',
         {
```

**Comment by pustovalov** [comment]
You can try this way:
`config/webpack/environment.js`

```
const { environment, config } = require('@rails/webpacker')
environment.loaders.delete('nodeModules')
```

Webpacker 6 doesn't have this issue because it no longer uses this loader
https://github.com/rails/webpacker/commit/24fe1aad6c803025db6e8ca4d92eba9edb5a580d

**Comment by dorianmariefr** [comment]
I just did `yarn add "@babel/plugin-proposal-private-methods"` and the warnings disappeared

**Comment by tagliala** [comment]
Hi @dorianmariefr , I cannot confirm that adding that package makes the warning disappear.

I've tried with the reduced test case at #3016, by running `yarn add "@babel/plugin-proposal-private-methods"` before the last step:

```
$ yarn add "@babel/plugin-proposal-private-methods"
yarn add v1.22.10
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "@babel/plugin-proposal-private-methods > @babel/helper-create-class-features-plugin@7.14.3" has unmet peer dependency "@babel/core@^7.0.0".
warning " > @babel/plugin-proposal-private-methods@7.13.0" has unmet peer dependency "@babel/core@^7.0.0-0".
[4/4] 🔨  Building fresh packages...
success Saved 1 new dependency.
info Direct dependencies
└─ @babel/plugin-proposal-private-methods@7.13.0
info All dependencies
└─ @babel/plugin-proposal-private-methods@7.13.0
✨  Done in 2.53s.
someone at somewhere in ~/test-babel-warning on master [?]
$ bin/webpack
Though the "loose" option was set to "false" in your @babel/preset-env config, it will not be used for @babel/plugin-proposal-private-methods since the "loose" mode option was set to "true" for @babel/plugin-proposal-class-properties.
The "loose" option must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object (when they are enabled): you can silence this warning by explicitly adding
	["@babel/plugin-proposal-private-methods", { "loose": true }]
to the "plugins" section of your Babel config.
```

This warning is not always displayed, I think it is only displayed the first time a class with a private variable is going to be compiled. You can just try to run `bin/webpack` twice and the second time it disappears

**Comment by LucasNeevs** [comment]
I did it to solve this error:

1º - My babelrc:
```
"plugins": [
    "babel-plugin-styled-components",
    ["@babel/plugin-proposal-private-methods", { "loose": true }]
]
```
  
2º - I've installed this: npm install --save-dev @babel/plugin-proposal-private-methodsl-private-methods.

My scenario: "webpack": "^4.46.0", "react": "^16.14.0", "@storybook/react": "^6.2.9".

**Comment by devzom** [comment]
If You're looking how to fix is easly in Nuxt.js, check this > [issue fix](https://stackoverflow.com/questions/67350359/nuxt-js-fresh-install-of-nuxt-2-14-6-contains-babel-loose-option-warnings?noredirect=1&lq=1)

**Comment by HtetAung7** [comment]
Try add these in nuxt.config.js:

build: {
  babel:{
    plugins: [
      ["@babel/plugin-proposal-class-properties", { "loose": true }],
      ["@babel/plugin-proposal-private-methods", { "loose": true }],
      ["@babel/plugin-proposal-private-property-in-object", { "loose": true }]
    ]
  }  
},

**Comment by ajaykaju** [comment]
Adding  **['@babel/plugin-proposal-private-property-in-object', { loose: true }]**  in build of nuxt.config.js solved my issue for   **Nuxt @ v2.15.7**      
```
build: {
  babel: {
    plugins: [
      ['@babel/plugin-proposal-private-property-in-object', { loose: true }]
    ],
  },
}
```

**Comment by AlecRust** [comment]
What about for Webpacker 5.x? Will there be no release which fixes this?

**Comment by adamransom** [comment]
I fixed this in Webpacker 5.4 by using adding the following `assumptions` ([mentioned in the Babel docs](https://babeljs.io/docs/en/babel-plugin-proposal-private-methods#loose)) to my `babel.config.js` and removing the individual `loose: true` statements we had:

```js
    assumptions: {
      privateFieldsAsProperties: true,
    },
```

**Comment by dhh** [comment]
Fixed in 5.4.2 for new installations.

**Comment by tomprats** [comment]
I was still running into this on webpacker 6.0.0-rc.5 with a babel.config.js file with an additional plugin, but adding the fix someone mentioned above and installing them as dependencies seems to have fixed the issue.

Before

```
module.exports = {
  plugins: [
    "@babel/plugin-proposal-export-default-from"
  ],
  presets: [
    "./node_modules/@rails/webpacker/package/babel/preset.js"
  ]
}
```

After

```
module.exports = {
  plugins: [
    "@babel/plugin-proposal-export-default-from",
    // Fixes for loose issue from https://github.com/rails/webpacker/issues/3008
    ["@babel/plugin-proposal-class-properties", {loose: true}],
    ["@babel/plugin-proposal-private-methods", {loose: true}],
    ["@babel/plugin-proposal-private-property-in-object", {loose: true}]
  ],
  presets: [
    "./node_modules/@rails/webpacker/package/babel/preset.js"
  ]
}
```

Plus

`yarn add ...`

**Comment by Diboby** [comment]
Hello !

Add `loose: true` here 👇 in my **babel.config.js** resolves that problem for me 😀

<img width="745" alt="Capture d’écran, le 2022-03-06 à 02 31 26" src="https://user-images.githubusercontent.com/57820648/156913759-0c42ae3a-4525-4e60-a85f-84ec3932bb45.png">

**Comment by sivaraj-v** [comment]
```
["@babel/plugin-proposal-class-properties", {loose: true}],
["@babel/plugin-proposal-private-methods", {loose: true}],
["@babel/plugin-proposal-private-property-in-object", {loose: true}]
```

Fixed @tomprats

**Comment by syedalimohsin** [comment]
@sivaraj-v thanks it is working for me. 
Can you tell me what should I provide here in the host? Actually, I want to deploy Mozilla hub on Virtual Machine.
![image](https://user-images.githubusercontent.com/57060853/166078593-6eb8e23e-7144-4e36-beb7-74d6dfa02c9a.png)
