### ISSUE TITLE
CSS / Images don't get transpiled unless some javascript was changed on production

### ISSUE THREAD

**Issue by joker-777** [rails/webpacker#3009]
Hi, we've been seeing this issue for quite some time now, in webpacker 5 but also 6. No matter if I run `bin/webpack` or `rake webpacker:compile`. It doesn't update/transpile css changes or changed images unless I also changed some javascript. This only happens in production mode though.
I will try to create a small example app but maybe it is a known behavior or maybe there is a known solution for it.

**Comment by justin808** [comment]
I"m very surprised. Can you try with the latest RC?

**Comment by joker-777** [comment]
Sorry, I forgot completely that I created this ticket. We found the reason for this problem. We forgot to add `- .scss` to the extensions configuration of `webpacker.yml`.
