### ISSUE TITLE
postcss 7.x (stable branch dependency) is unsupported and has an active security advisory

### ISSUE THREAD

**Issue by jthornhill** [rails/webpacker#3017]
A yarn audit this morning brought this one to light. There's currently a [moderate security advisory](https://www.npmjs.com/advisories/1693) in postcss.

Unfortunately, the postcss maintainer has indicated that [no fix will be provided for the 7.x branch](https://github.com/postcss/postcss/issues/1574), and advises the solution is to switch to 8.x

**Comment by athix** [comment]
Found this elsewhere, but you can add the following to your package.json to help resolve this dependency:

```json
"resolutions": {
  "postcss": ">= 8.2.10"
}
```

**Comment by jaredbeck** [comment]
Does the major breaking change in postcss 8 make it difficult to upgrade webpacker 5 to postcss 8?

> We now serve ES6+ sources in the npm package without Babel compilation.
> https://github.com/postcss/postcss/releases/tag/8.0.0

Or, is it only an issue for people who use postcss in the browser, eg. via [sanitize-html][1]?

PS: If you do use postcss 8, _in the browser_, in webpacker 5, you will want to be aware of this [solution](https://github.com/apostrophecms/sanitize-html/issues/420#issuecomment-824483498).

PPS: Webpacker 6 drops its ["nodeModules" loader][2] which should make it easier to use postcss 8 in the browser.

[1]: https://github.com/apostrophecms/sanitize-html
[2]: https://github.com/rails/webpacker/blob/5-x-stable/package/rules/node_modules.js

**Comment by athix** [comment]
If your use-case does not care about a regex denial of service, you can switch from `yarn audit` to `audit-ci` to allow ignoring this CVE until webpacker fixes their dependency.

1. Add `audit-ci` to your devDependencies:
```json
"devDependencies": {
  "audit-ci": "4.x"
}
```

2. Run `yarn install`

3. Update `yarn audit` to one of the following options:
* `npx audit-ci` (functionally equivalent to `npx audit-ci --high`)
* `npx audit-ci --low --allowlist 1693` (functionally equivalent to `yarn audit` while ignoring this particular CVE)

**Comment by Eusebius1920** [comment]
You can also use https://github.com/djfdyuruiry/improved-yarn-audit which works as a thin wrapper around `yarn audit` but filters out specified CVEs (via .iyarc file in the repository or via command-line flag)

Nonetheless the root issue should be fixed.

**Comment by guemidiborhane** [comment]
+1

**Comment by davidpocina** [comment]
It looks like webpacker 6 still uses `postcss-preset-env`, so this won't be solved until that project updates to postcss 8 too

csstools/postcss-preset-env#191

**Comment by afdev82** [comment]
The fix has been backported to v7: https://github.com/postcss/postcss/issues/1574#issuecomment-859226586

**Comment by dhh** [comment]
6.0 will not have a hard dependency on postcss any more. If someone wants to do the work to validate that it's safe to bump the dependency for 5-stable, please do so 🙏

**Comment by Eusebius1920** [comment]
The postcss maintainer already stepped in and released a backport to postcss 7.x that can be used with webpacker v5. So this issue can be closed.
