### ISSUE TITLE
has an unknown property 'watch_options'

### ISSUE THREAD

**Issue by anke1460** [rails/webpacker#3028]
When i run` ./bin/webpack-dev-server` will raise this errors:
`configuration.static has an unknown property 'watch_options'. These properties are valid:`

My webpacker version is `@rails/webpacker": "^6.0.0-beta.7`
I saw the document of  webpack 5 that  devServer  options includes watch_options property. 
And If i changed ` watchOptions: devServer.watch_options` in development.js to 
 `
static: {
        watch_options: devServer.watch_options
      }
` 
it works

**Comment by justin808** [comment]
@anke1460 Seems that your watch options is global, not for the dev-server.

https://webpack.js.org/configuration/watch/

**Comment by mejl** [comment]
I'm getting 

> options has an unknown property 'watchOptions'.
