### ISSUE TITLE
ERROR in Conflict: Multiple assets emit different content to the same filename js/.br

### ISSUE THREAD

**Issue by dorianmariefr** [rails/webpacker#3029]
I get this error when using latest release webpacker (6.0.0.beta.7)

was not happening before

Before: revision: 8c0e69ce65f4a35a52de2feba5dec2ec86b272aa
  
After: revision: ad8010fbeb20a767fb1a0dc2a0dea5890f41e4a7

**Comment by dorianmariefr** [comment]
A `rails webpacker:install fixed it`

**Comment by dorianmariefr** [comment]
Bumping @rails/webpacker from 6.0.0-beta.7 to 6.0.0-pre.2 while using the latest master breaks `rails assets:precompile` with the error mentioned

```
ERROR in Conflict: Multiple assets emit different content to the same filename js/.br #3029
```

**Comment by arschrier** [comment]
Encountered the same issue.

Yarn "upgraded" @rails/webpacker from 6.0.0-beta.7 to 6.0.0-pre.2. This was not actually an upgrade: 6.0.0-pre.2 is older than 6.0.0-beta.7.

Adding @rails/webpacker with `--exact` solved my issue.

**Comment by dorianmariefr** [comment]
thanks @arschrier, so it's `yarn add @rails/webpacker@6.0.0-beta.7 --exact`

```diff
-    "@rails/webpacker": "^6.0.0-beta.7",
+    "@rails/webpacker": "6.0.0-beta.7",
```

**Comment by arschrier** [comment]
Yep! That should do it.
