### ISSUE TITLE
javascript_pack_tag never works

### ISSUE THREAD

**Issue by goldenking0412** [rails/webpacker#3032]
I have application.js in app/javascript/packs

My rails version is 6.

In gemfile
```
gem 'webpacker', '~> 6.0.0.pre.1'
```

In package.json

```
{
  "name": "Testapp",
  "private": true,
  "dependencies": {
    "@rails/actioncable": "^6.0.0",
    "@rails/activestorage": "^6.0.0",
    "@rails/ujs": "^6.0.0",
    "@rails/webpacker": "^6.0.0-beta.7",
    "node-forge": "0.10.0",
    "turbolinks": "^5.2.0",
    "webpack": "^5.11.0",
    "webpack-cli": "^4.2.0"
  },
  "version": "0.1.0",
  "devDependencies": {
    "@webpack-cli/serve": "^1.4.0",
    "webpack-dev-server": "^3.11.2"
  },
  "babel": {
    "presets": [
      "./node_modules/@rails/webpacker/package/babel/preset.js"
    ]
  },
  "browserslist": [
    "defaults"
  ],
  "babel": {
    "presets": ["./node_modules/@rails/webpacker/package/babel/preset.js"]
  },
  "browserslist": [
    "defaults"
  ]
}

```

I have
```
console.log("Hello");
```
in 1st line of application.js

But never output hello

Any idea about that?

**Comment by volkert** [comment]
There is a bug with `pre.1` try:
`gem 'webpacker', '6.0.0.beta.7'`

**Comment by goldenking0412** [comment]
Still not working

I updated gemfile.
Did ``bundle install``

then ``rails webpacker:install``

Still not putting hello

**Comment by goldenking0412** [comment]
I replaced ``javascript_pack_tag`` with ``javascript_packs_with_chunks_tag`` and it fixed.

Thanks

**Comment by goldenking0412** [comment]
But I am still getting error ``Uncaught ReferenceError: $ is not defined``

I've followed this solution
https://stackoverflow.com/questions/55895494/is-not-defined-when-installing-jquery-in-rails-via-webpack

Is there anything wrong?

**Comment by mcmire** [comment]
If you can post a repo, that would be most helpful, so we can see what you're doing in its entirety.

**Comment by goldenking0412** [comment]
Unfortunately, I can not post repo as it's private and not hosted on mine.

What do you need? I will give you details

**Comment by goldenking0412** [comment]
Closing this issue as it's not related to webpacker
