### ISSUE TITLE
loading an svg as a react component fails

### ISSUE THREAD

**Issue by thushw** [rails/webpacker#3037]
Does anyone else get this error : 

ERROR in ./app/javascript/components/Header.js 342:76-87
Can't import the named export 'ReactComponent' (imported as 'ProfileIcon') from default-exporting module (only default export is available)

webpacker version:

` "@rails/webpacker": "^6.0.0-beta.7",`

my webpack config:

```
const { webpackConfig, merge } = require('@rails/webpacker')

// define additional loader rules
const loaders = [
  {
    test: /\.svg$/,
    use: ['@svgr/webpack', 'url-loader'],
  },
  // ... more loader rules
]

// merge with default webpack config 
// and export result
module.exports = merge(
  webpackConfig, 
  {
    module: {
      rules: loaders
    },
  }
)
```

the code that fails:

```
import { ReactComponent as ProfileIcon } from '../svg/Profile.svg';
```

**Comment by eeshaan** [comment]
Was able to resolve this using @zedtux's [solution](https://github.com/rails/webpacker/issues/918#issuecomment-706981769) in #918.   

In my case, I also had to remove `exclude: /node_modules/,` from the loader configuration because the SVG icons I'm using are from the [`@zendeskgarden/svg-icons`](https://github.com/zendeskgarden/svg-icons) package and add `packs/media` to `additional_paths` in `webpacker.yml`. In your case, it would be the path where `'../svg/Profile.svg'` is located.

  
`config/webpacker/environment.js`:
```js
const { environment } = require('@rails/webpacker')
const fileLoader = environment.loaders.get('file')

// exclude 'svg' from file loader for @zendeskgarden/svg-icons
// see https://github.com/rails/webpacker/issues/918#issuecomment-706981769
fileLoader.test = /\.(jpg|jpeg|png|gif|eot|otf|ttf|woff|woff2)$/i;
environment.loaders.prepend('svg', {
  test: /\.svg$/,
  loader: 'svg-react-loader'
})

module.exports = environment
```
  
`config/webpacker.yml`:
```yml
  additional_paths: ['packs/media'] # location of @zendeskgarden/svg-icons
```

**Comment by eeshaan** [comment]
> ``` import { ReactComponent as ProfileIcon } from '../svg/Profile.svg';```

Additionally, you might also want to try not importing with `ReactComponent`. Instead:

```js
import ProfileIcon from '../svg/Profile.svg';
```

**Comment by dhh** [comment]
Do add a PR with instructions on how to make this work.

**Comment by nvhungkt** [comment]
> Was able to resolve this using @zedtux's [solution](https://github.com/rails/webpacker/issues/918#issuecomment-706981769) in #918.
> 
> In my case, I also had to remove `exclude: /node_modules/,` from the loader configuration because the SVG icons I'm using are from the [`@zendeskgarden/svg-icons`](https://github.com/zendeskgarden/svg-icons) package and add `packs/media` to `additional_paths` in `webpacker.yml`. In your case, it would be the path where `'../svg/Profile.svg'` is located.
> 
> `config/webpacker/environment.js`:
> 
> ```js
> const { environment } = require('@rails/webpacker')
> const fileLoader = environment.loaders.get('file')
> 
> // exclude 'svg' from file loader for @zendeskgarden/svg-icons
> // see https://github.com/rails/webpacker/issues/918#issuecomment-706981769
> fileLoader.test = /\.(jpg|jpeg|png|gif|eot|otf|ttf|woff|woff2)$/i;
> environment.loaders.prepend('svg', {
>   test: /\.svg$/,
>   loader: 'svg-react-loader'
> })
> 
> module.exports = environment
> ```
> 
> `config/webpacker.yml`:
> 
> ```yaml
>   additional_paths: ['packs/media'] # location of @zendeskgarden/svg-icons
> ```

This is for older version of webpacker, not v6
