### ISSUE TITLE
Vulnerable sub-dependency: normalize-url

### ISSUE THREAD

**Issue by Eusebius1920** [rails/webpacker#3040]
### normalize-url

- **Advisory:** https://www.npmjs.com/advisories/1755
- **Patched versions:** `>=4.5.1 <5.0.0 || >=5.3.1 <6.0.0 || >=6.0.1`

In `@rails/webpacker^5.4.0` with dependency paths:

- `@rails/webpacker > mini-css-extract-plugin > normalize-url`: Can be solved by upgrading to mini-css-extract-plugin
  resolves to `normalize-url` to `1.9.1`
  **Resolution:**
  upgrading to any `mini-css-extract-plugin version` `>= 1.1.0` which removes normalize-url as dependency
  [changelog](https://github.com/webpack-contrib/mini-css-extract-plugin/blob/master/CHANGELOG.md#100-2020-10-09) indicates some breaking changes in v1.0.0 - are there any major problems? (nodejs-version should still match). Also be aware of the breaking changes in v1.3.0.
  
- `@rails/webpacker > optimize-css-assets-webpack-plugin > cssnano > cssnano-preset-default > postcss-normalize-url > normalize-url`
  resolves `normalize-url` to `3.3.0`
  **Resolution:**
  upgrade optimize-css-assets-webpack-plugin to `v6.0.0`. The "only" change of this version is the introduction to cssnano `v5` instead of `v4` (v5 is still `nodejs^10`) and the introduction to postcss `v8` which might be problematic?
  
- _Furthermore_: i guess the semver specification for ~~normalize-url~~ mini-css-extract-plugin `^0.9.0` in this package is wrong and should be `0.x` instead? In this constellation `^0.9.0` is equivalent to exact `0.9.0` which excludes for example `0.12.0`

* **edit**: I meant `^0.9.0` for `mini-css-extract-plugin` **not** `normalize-url`

**Comment by jaredbeck** [comment]
Neither dependency path exists in `master`. Both direct dependencies (`mini-css-extract-plugin` and `optimize-css-assets-webpack-plugin`) were removed in 6ba995aed2b609a27e4e35ec28b2a7f688cce0cf, released in `6.0.0.pre.1`.

So, IIUC, this advisory just increases the urgency of a v6 final release?

Corollary: to address this advisory today, our only option is to use a beta release of webpacker. Currently, the latest is `6.0.0.beta.7`.

Question for @gauravtiwari - Users of v6 will have the ability to choose a secure version of these dependencies, or choose not to use them at all, correct?

**Comment by Eusebius1920** [comment]
@jaredbeck yes, this vulnerability is only present in v5 (i.e. the latest stable release)

v6 is not affected (as the users can choose their own versions of the dependencies), but still not released yet either.

**Comment by OlivierJM** [comment]
any ideas when we can expect final stable release of v6 ? 
cc: @jaredbeck @gauravtiwari

**Comment by jaredbeck** [comment]
> Neither dependency path exists in master.

Because this is fixed in `master`, I'd suggest that this issue can be closed, and the conversation can move to e.g. https://github.com/rails/webpacker/issues/3055, which asks "what's blocking Webpacker 6?".

Oddly, [advisory 1755](https://www.npmjs.com/advisories/1755) no longer appears for when I run `yarn audit`. This is odd because I'm still using the same versions of `normalize-url` as [20 days ago](https://github.com/rails/webpacker/issues/3040#issuecomment-857898173), i.e. `1.9.1` and `3.3.0`. The only hypothesis I can suggest is that the advisory has been updated such that it no longer considers these versions to be affected.

**Comment by Eusebius1920** [comment]
You are right, 1755 is suddenly missing.

And I support your suggestion to push for webpacker v6 and closing this issue (just like #3042)

**Comment by Eusebius1920** [comment]
Apparently it is like you said, they updated the CVE:

https://www.npmjs.com/advisories/1755/versions

Here you can see that 1.9.1 and 3.3.0 are listed as "not affected". So one more reason to close this!
