### ISSUE TITLE
Vulnerable sub-dependency: css-what (Latest stable release ^5.0)

### ISSUE THREAD

**Issue by dmorton2297** [rails/webpacker#3042]
**css-what**
**Advisory:** https://www.npmjs.com/advisories/1754
**Patched versions:** >=5.0.1  
In @rails/webpacker^5.4.0 with dependency paths:

@rails/webpacker > @rails/webpacker > optimize-css-assets-webpack-plugin >   
cssnano > cssnano-preset-default > postcss-svgo > svgo > 
css-select > css-what      

**Resolution:** Update optimize-css-assets-webpack-plugin to version 6.0.0

**Context:** Using beta version (6.0) of webpacker is not feasible for my team until it is released

**Comment by Eusebius1920** [comment]
I don't think that this vulnerability is solvable at the moment. There is **no** svgo-version that does not introduce this vulnerability. And the latest optimize-css-assets-webpack-plugin keeps the whole path still intact (i.e. does not remove svgo and successors from the path)


See: https://github.com/svg/svgo/issues/1488

**Comment by dmorton2297** [comment]
Closing this as a wont-fix - resolving in 6.0 version of package

**Comment by jaredbeck** [comment]
> Closing this as a wont-fix - resolving in 6.0 version of package

Re: 6.0 release, see also https://github.com/rails/webpacker/issues/3055
