### ISSUE TITLE
V6 Beta Incompatible with Pysch 4

### ISSUE THREAD

**Issue by ryanquanz** [rails/webpacker#3046]
https://github.com/rails/webpacker/pull/3024 added Psych 4 support to Webpacker and was released in [`5.4.0`](https://github.com/rails/webpacker/releases/tag/v5.4.0), but hasn't been included in a V6 beta release yet.

I'm getting a `Psych::BadAlias: Unknown alias: default` error when trying to load `config/webpacker.yml` while upgrading.

I can downgrade the Psych version, but would appreciate this getting a release ❤️

**Comment by marcelolx** [comment]
@ryanquanz While there's no release you can use the master branch of webpacker which includes the support.

**Comment by dgolant** [comment]
Had this same problem after I updated Psych trying to resolve the mimemagic problem from a few months back (stagnant project). Commenting to bump :)

**Comment by dhh** [comment]
This has been fixed in rc1.
