### ISSUE TITLE
yarn issue 

### ISSUE THREAD

**Issue by AustinRhoads** [rails/webpacker#3047]
when I run `rails new app-name --webpack=react -T` I get the following error..
`` `block in replace_bin_path': can't find executable yarn for gem yarn. yarn is not currently included in the bundle, perhaps you meant to add it to your Gemfile? (Gem::Exception)
Yarn not installed. Please download and install Yarn from https://yarnpkg.com/lang/en/docs/install/
Exiting!`` 
I have yarn installed.

**Comment by guillaumebriday** [comment]
What happened when you run `yarn -v`?

Are you on windows?

**Comment by AustinRhoads** [comment]
I got the yarn gem version 0.1.1 apparently there are two different yarns and rails was confused.
