### ISSUE TITLE
NoMethodError: undefined method `assets' for #<Rails::Application::Configuration

### ISSUE THREAD

**Issue by dave105010** [rails/webpacker#3048]
Are we supposed to remove the following entries from "config/environments/*.yml" after migrating from sprockets to webpacker?
```
 config.assets.debug = true
  config.assets.compress = false
  config.assets.quiet = true
  config.assets.raise_runtime_errors = true
```

I'm getting "NoMethodError: undefined method `assets' for #<Rails::Application::Configuration" error.

**Comment by mcmire** [comment]
`config.assets` comes from Sprockets (specifically sprockets-rails), so if you removed it entirely you don't need those configuration options. That said, you don't have to remove Sprockets to use Webpacker.

**Comment by guillaumebriday** [comment]
Thanks @mcmire 

@dave105010 if you removed the sprockets gem, you need to remove these lines.
