### ISSUE TITLE
in `exec': Invalid argument - NODE_PATH=C:

### ISSUE THREAD

**Issue by p-adams** [rails/webpacker#305]
I am attempting to use webpacker with Windows 10 and I get this error when running `ruby bin\webpack-dev-server`:

`bin/webpack-dev-server:31:in `exec': Invalid argument - NODE_PATH=C:/Users/paadams/myapp/node_modules C:/Users/paadams/myapp/node_modules/.bin/webpack-dev-server --progress --color --config C:/Users/paadams/myapp/config/webpack/development.server.js  (Errno::EINVAL)
        from bin/webpack-dev-server:31:in `block in <main>'
        from bin/webpack-dev-server:30:in `chdir'
        from bin/webpack-dev-server:30:in `<main>'`

**Comment by gauravtiwari** [comment]
This seems to be related with #245 We probably need to fix these binstubs too for windows :)

**Comment by fsateler** [comment]
Hi, please check pr #355

**Comment by gauravtiwari** [comment]
Thanks @fsateler Merged 🎉
