### ISSUE TITLE
Webpacker 6: Don't know how to build task 'webpacker:install:stimulus'

### ISSUE THREAD

**Issue by anon987654321** [rails/webpacker#3052]
With Webpacker 6 installed:
```
% rails webpacker:install:stimulus
rails aborted!
Don't know how to build task 'webpacker:install:stimulus' (See the list of available tasks with `rails --tasks`)
Did you mean?  webpacker:install

(See full trace by running task with --trace)
```
I'm trying to set up StimulusReflex according to https://docs.stimulusreflex.com/hello-world/setup by running `rails stimulus_reflex:install`, unfortunately it errors out after trying `rails webpacker:install:stimulus`. This despite Stimulus actually being installed through `yarn add stimulus`.

@cc stimulus/issues

**Comment by sergiopantoja** [comment]
Webpacker 6 doesn't support custom installers anymore. It was removed with this PR here: https://github.com/rails/webpacker/pull/2802/files#diff-8efe491b392a5a50e31b54660bbc0e7258e544e36d4e0b8a65e4cca93d39d18c

I believe you should open an issue with Stimulus Reflex team so they can update their documentation.

**Comment by anon987654321** [comment]
Thanks for the info! Also, it seems the recommended way acording to the StimulusReflex guys on Discord is https://github.com/hotwired/stimulus-rails. Putting this matter to rest, thanks again 👍
