### ISSUE TITLE
How do I make Jquery external?

### ISSUE THREAD

**Issue by suni-masuno** [rails/webpacker#3053]
So I've picked up an old(ish) project that's rolled through a few teams and I'd like (like a lot of people) to run some jquery from the console. 

But to do that I "just" need to [make it external](https://github.com/webpack/webpack/issues/4258#issuecomment-279125730) in webpack, which seems no prob. 

But to do that I "just" need to [do it in webpacker](https://www.dwightwatson.com/posts/configuring-webpack-externals-with-webpacker). 

That's where I'm failing. I've tried a few wild approaches (including some of what I've found [here](https://github.com/rails/webpacker#webpack-configuration)) but I can't seem to get jquery to show up in the dev tools in chrome.

Am I missing some basic understanding/idea here? I wanna `$(".stuff").show()` and the like from the dev tools. Is there a simple option I just don't know how to set? A tutorial I should be reading?

**Comment by davidpocina** [comment]
You can try something like this in your main pack

```
import jQuery from 'jquery';

global.jQuery = jQuery;
global.$ = jQuery;
```

That will expose jQuery in the global object (window in the browser)

**Comment by guillaumebriday** [comment]
Take a look at the ProvidePlugin: https://webpack.js.org/plugins/provide-plugin/#usage-jquery

For instance:
In your `config/webpack/environment.js`:

```js
const webpack = require('webpack')

// ...

environment.plugins.append('Provide', new webpack.ProvidePlugin({
  $: 'jquery',
  jQuery: 'jquery',
  jquery: 'jquery',
  'window.jQuery': 'jquery',
  Popper: ['popper.js', 'default']
}))
```

**Comment by jaredbeck** [comment]
As with Guillaume, I also use `ProvidePlugin` for this, but I don't configure `window`, and `$` still works for me in the browser console.

```
environment.plugins.prepend(
  'Provide',
  new webpack.ProvidePlugin({
    $: 'jquery',
    jQuery: 'jquery'
  })
);
```

So, I'd say there's like a 50% chance that you don't need that `window` line, and a 50% chance that I don't know what I'm talking about 😆

**Comment by guillaumebriday** [comment]
ProvidePlugin does exactly that 👍 

Feel free to repoen if needed @suni-masuno

**Comment by guillaumebriday** [comment]
Just opened a PR about that: https://github.com/rails/webpacker/pull/3058 👍
