### ISSUE TITLE
Need to replace check for WEBPACK_DEV_SERVER to WEBPACK_DEV_SERVE when going to webpack-dev-server v4

### ISSUE THREAD

**Issue by justin808** [rails/webpacker#3057]
# Reminder for a future upgrade of the webpack-dev-server

`process.env.WEBPACK_DEV_SERVER` renamed to `process.env.WEBPACK_DEV_SERVE` in [PR 3000](https://github.com/webpack/webpack-dev-server/pull/3000) for v4 off [webpack-dev-server](https://github.com/webpack/webpack-dev-server).

# Details

## Older code:
https://github.com/webpack/webpack-dev-server/blob/7ee869e17fc3c0db56c8ff44dc1c6b6f03c85c1a/lib/Server.js#L65-L68

Originally added: https://github.com/webpack/webpack-dev-server/pull/1929

## Newer, on master:

https://github.com/webpack/webpack-dev-server/blob/master/lib/Server.js#L19-L21

**Comment by nertzy** [comment]
To help with future searches, it's actually `process.env.WEBPACK_SERVE` (no `_DEV_`)

**Comment by dhh** [comment]
This has been fixed in 6.0.0.rc.4.
