### ISSUE TITLE
Question about multiple source_entry_path s

### ISSUE THREAD

**Issue by pgruener** [rails/webpacker#3064]
Hi,

I have the following situation with a "modular monolith":
```
app/javascript/packs/pack1.js
app/javascript/packs/pack2.js
engines/frontend_engine/javascript/packs/slim_pack.js
engines/backend_engine/javascript/packs/full.js
```

So what I would like most, is to have the engines' packs just be compiled within the host applications webpack processor.

What I can do is to create a host application pack, which just loads the engine's pack

e.g. add file and load it, like:

_app/javascript/packs/frontend_engine_slim_pack.js_
```
const engineContext = require.context('frontend_engine/app/javascript/host_entrypoints', true, /^.*\.js$/)
engineContext.keys().forEach(engineContext)
```
(That's working because I've set additional_paths)

But I don't really like this approach, as I need to create such a file in the host application for each engine pack, I want to publish. This is like a dependency to a pluggable engine, where I cannot easy plug the engine or remove it, without changing the host application.

So, what I am looking for, is to declare different pack/entrypoint source paths, which can resolve (globbed) to my engines.

For example in _webpacker.yml_
```
default: &default
  source_path: app/javascript
  source_entry_path:
  - packs
  - ../../engines/*/app/javascript/host_entrypoints
```

And each pack in *host_entrypoints* should be used compiled by the host applications webpack processor.

As I noticed, it would need a simple change in environment/base.js, to use an array instead of the single path.

But I am also wondering, why I didn't find any other people, looking for sth like that.

Is there another handy option to solve my scenario?

Do other people think, this will be useful?

Or is there a way, how I could monkey patch the JS, which I didn't recognize yet?

Thanks for your opinions

Best

**Comment by brendon** [comment]
@pgruener, did you ever find a solution for this? My app is split into many engines and I'd like one of these to export an entrypoint. Right now it seems that this has to be placed in the main app's javascript/packs folder.

**Comment by pgruener** [comment]
@brendon I created a task for my scenario, which is discovering the engines' entry_point directories and generates corresponding files in the host_application's javascript/packs folder. It also may remove those, which are not necessary anymore. So for CI/CD purposes, when isolated engines are tested or deployed (thats both needed in our scenario), those entry_points can automatically be in sync with the present ones, without having "dead references".

If some parts of that might be helpful for you, you can have a look at https://gist.github.com/pgruener/4f3e383599a68386fb03dd730a2d1a3a

But that's of course still a workaround for the main topic...

**Comment by brendon** [comment]
Thanks @pgruener, I guess I kind of worked around it in the same way by adding a new file in the main application's `packs` directory that then imports the file at `engine/javascript/packs/engine_namespace`. I guess given the turn away from Webpack with Rails this one will probably never be properly solved :)

**Comment by pgruener** [comment]
lets keep hoping ;-)
