### ISSUE TITLE
Why webpacker-dev-server cannot auto-start when Rails booted up?

### ISSUE THREAD

**Issue by dave105010** [rails/webpacker#3065]
Hi,

Why `webpacker-dev-server` cannot auto-start when Rails booted up for development only?
It's adding an extra step to development every morning of the day to manually manage this.

Considering we never had to do this with sprockets, can something like below added in Rails? 

We could maybe turn this on or off in "webpacker.yml"?
```yml
# Example
development:
  <<: *default
  webpack_dev_server_autostart: true
```

It would save so much time if we automated this and we wouldn't have to deal with it every day while developing on Rails 6.

I'm currently using this code below in "config.ru" and it works very well but I'd rather not have a custom code for something very fundamental. 

The code below stops all the "webpack-dev-server" processes and starts a new instance of it whenever the web app is restarted and booted up through `config.ru` file. It redirects webpack-dev-server process stdout and stderr to default log/development.log. So, it's easy to manage it.

```ruby
...
...
run Rails.application
Rails.application.load_server

# Default Rails stuff above...
# Proposed starting webpack_dev_server automatically when the web app boots up.

if ENV["RAILS_ENV"] == "development"
  existing_webpack_dev_server_process = `pgrep -a -f node.*webpack-dev-server`
  puts "Checking if there is an existing webpack-dev-server: #{existing_webpack_dev_server_process}"

  kill_result = `pkill -f node.*webpack-dev-server`
  puts "webpack-dev-server killed: #{kill_result}"

  puts "Starting a new instance of webpack-dev-server"
  pid = Process.spawn("WEBPACKER_DEV_SERVER_PUBLIC=#{Rails.application.default_url_options[:host]} ./bin/webpack-dev-server",
                      [:out, :err]=>["log/development.log", "w"])
  Process.detach(pid)

  puts "active webpack-dev-server PID: #{pid}"
end
```

**Comment by mcmire** [comment]
I'm wondering if it might be better for Webpacker to include support for existing tools rather than bake a custom solution in. I've used both `heroku local` (from the Heroku toolbelt) and Overmind to run `bin/rails server` and `bin/webpack-dev-server` concurrently. Both key off of a Procfile that you can commit to the repo so other people can run the full application the same way.

**Comment by dave105010** [comment]
> I'm wondering if it might be better for Webpacker to include support for existing tools rather than bake a custom solution in. I've used both `heroku local` (from the Heroku toolbelt) and Overmind to run `bin/rails server` and `bin/webpack-dev-server` concurrently. Both key off of a Procfile that you can commit to the repo so other people can run the full application the same way.

Unfortunately we are not using Heroku, so keeping webpack-dev-server separate from Rails.application will cause so many problems for people using tons of different environments. 

It would be straightforward to bundle it with existing Rails. So, nothing else would need to be re-configured. If an additional config needs to be added, it's just going to create more extra configuration overhead to think about. There are already 120+ js libraries in node_modules that can break anytime. I would at least expect Rails to run without too many headaches so I won't also have to deal with webpack-dev-server or potential webpack changes in the future when a new webpack version is released etc.

**Comment by jcoyne** [comment]
Another problem is that Rails is a Ruby process and webpack-dev-server is a node process. So this would involve some sort of process orchestration, which would have to make assumptions about the environment you are running it in.  This wouldn't be too hard assuming Linux, but gets harder when you want to also support Windows and MacOS.

**Comment by dave105010** [comment]
> Another problem is that Rails is a Ruby process and webpack-dev-server is a node process. So this would involve some sort of process orchestration, which would have to make assumptions about the environment you are running it in. This wouldn't be too hard assuming Linux, but gets harder when you want to also support Windows and MacOS, not to mention alternative rubies like JRuby.

Maybe, what I did in my first post can be a gem and initialized when Rails booted up. The gem can be updated to add additional support OS support over time with node version checks and more options. When it's developed enough, it could be merged to Rails? This requires future planning though. So, probably Rails devs could step in to provide which direction Rails is heading regarding webpacker? I don't know.

**Comment by guillaumebriday** [comment]
As @mcmire mentions it, maybe you should try to use Procfile if you want to spawn multiple things at the the time.

And most people will use Webpacker without dev-server. 

Let's keep it simple for now. 👍

**Comment by dave105010** [comment]
@guillaumebriday It's extremely slow without the webpack-dev-server. Every page reload after a change takes at least 20 seconds because Rails doesn't hot-reload webpacks without webpack-dev-server process running.
