### ISSUE TITLE
Need to have webpacker better support the situation of calling javascript_pack_tag multiple times during rendering

### ISSUE THREAD

**Issue by justin808** [rails/webpacker#3068]
It's too difficult to depend on library users to know that they are calling `javascript_pack_tag` and `stylesheet_pack_tag` only once during the rendering cycle.

This is extremely deadly when using React as you get error like:

```
Original message: Hooks can only be called inside the body of a function component. (https://fb.me/react-invalid-hook-call)
```

Or other vague errors with React indicating that maybe multiple copies of react are included.

We have 2 ways to fix this:

1. Throw an error if this is detected during view rendering. While this seems unfriendly, it's WAY better than obscure errors. `Logger.warn` could also be done.
2.  Allow calling the view helper multiple times, so that "it just works."

# Current docs --> too hard

**Important:** Pass all your pack names as multiple arguments, not multiple calls, when using **`javascript_pack_tag`** and the **`stylesheet_pack_tag`**. Otherwise, you will
get duplicated chunks on the page. Be especially careful if you might be calling these view helpers from your view, partials, and the layout for a page. You will need some logic to ensure you call the helpers only once with multiple arguments.

```erb
<%# DO %>
<%= javascript_pack_tag 'calendar', 'map' %>
<%= stylesheet_pack_tag 'calendar', 'map' %>

<%# DON'T %>
<%= javascript_pack_tag 'calendar' %>
<%= javascript_pack_tag 'map' %>
<%= stylesheet_pack_tag 'calendar' %>
<%= stylesheet_pack_tag 'map' %>

**Comment by rossta** [comment]
Thanks for opening this issue, @justin808. This is a problem we should fix, also called out in #2932. I wanted to jot some thoughts down here while I had some time.

I would love Webpacker to provide "just works" version even if it means changing the helper API (again) but I'm not sure what would be most intuitive. Here are few general directions I've imagined:

* Keep track of which packs have been rendered during a single request and ensure duplicates aren't rendered. Considerations include how to ensure the "runtime" is rendered in a consistent/preferred place within the document.
* Use an alternative API that allows developers to register included packs from partials and render all registered packs in single call, e.g. `<% include_javascript_pack 'calendar' %>` then `<%= javascript_pack_tags %>`. Might have to think through how this would work with Turbolinks.
* Some combination of the two

**Comment by justin808** [comment]
@rossta I plan to post a PR for this. However, I'm currently traveling, so it will be a few weeks. In the meantime, any reason that we can't post a beta.8 release?

**Comment by dhh** [comment]
Now raising on double calls.

**Comment by justin808** [comment]
See https://github.com/rails/webpacker/issues/3265.
