### ISSUE TITLE
using defer with multiple packs?

### ISSUE THREAD

**Issue by Dujota** [rails/webpacker#3074]
I am trying to combine all the packs in one call as per the documentation

I need the navbar pack to be loaded after the dom loads since it relies on some elements in the application.html.erb to be rendered. 

Naturally i could put it at the bottom of the page or call defer on it, combining the two crashes with a syntax error. 

so i have this at the moment but I was wondering if anyone had any tip onhow to combine the two in order to avoid duplicate chunks on render?  

```
<%= javascript_packs_with_chunks_tag 'logrocket', "application", 'data-turbolinks-track': "reload"  %>

 <%= javascript_packs_with_chunks_tag 'navbar/mobile_nav', defer: true%>
```

I was contemplating doing a DOMContentLoaded Event listener wrapping the code for mobile_nav, thoughts?

**Comment by justin808** [comment]
@Dujota this is all changed for v6. Can you try master?

**Comment by Dujota** [comment]
@justin808 thanks for the heads up 👍 

Would you be able to give me some indication in which way it has changed?

**Comment by dhh** [comment]
Defer is the default now with 6.0.0.rc1.
