### ISSUE TITLE
Separate output path for fonts in webpacker v6

### ISSUE THREAD

**Issue by sled** [rails/webpacker#3080]
In v6.0.0-beta.7 the images and fonts are outputted in the same images/ folder, i.e I get this in my `manifest.json`:

```
"/packs/media/images/24e1f7f06b6876bf398d.eot",
"/packs/media/images/6cf5f320e27be83645d8.woff",
"/packs/media/images/e8e73160b2e1347f5f75.woff2"
```

In my opinion it would make sense to change this to:

```
"/packs/media/fonts/24e1f7f06b6876bf398d.eot",
"/packs/media/fonts/6cf5f320e27be83645d8.woff",
"/packs/media/fonts/e8e73160b2e1347f5f75.woff2"
```

All that needs to be done is to split the file rules [here](https://github.com/rails/webpacker/blob/v6.0.0.beta.7/package/rules/file.js) and add a separate rule for fonts like this:

```js
// rules/images.js
module.exports = {
  test: [
    /\.bmp$/,
    /\.gif$/,
    /\.jpe?g$/,
    /\.png$/,
    /\.tiff$/,
    /\.ico$/,
    /\.avif$/,
    /\.webp$/,
    /\.svg$/
  ],
  exclude: [/\.(js|mjs|jsx|ts|tsx)$/],
  type: 'asset/resource',
  generator: {
    filename: 'media/images/[hash][ext][query]'
  }
}
```

```js
// rules/fonts.js
module.exports = {
  test: [
    /\.eot$/,
    /\.otf$/,
    /\.ttf$/,
    /\.woff$/,
    /\.woff2$/
  ],
  exclude: [/\.(js|mjs|jsx|ts|tsx)$/],
  type: 'asset/resource',
  generator: {
    filename: 'media/fonts/[hash][ext][query]'
  }
}
```

What do you think?

**Comment by guillaumebriday** [comment]
I opened this PR before seeing this issue: https://github.com/rails/webpacker/pull/3082

But what do you think to put everything in the `static` folder?

I see no need to split images and fonts even for caching 🤔 do I miss something?

**Comment by JoeWoodward** [comment]
Also experiencing this

**Comment by JoeWoodward** [comment]
This is also removing the nesting. In my app I'm grouping fonts in a folder. e.g.

```
app/packs/fonts/sans-serif/
- black.woff
- black.woff2
- normal.woff
- normal.woff2
etc
```
but now the manifest shows
```
  "media/images/black.woff": "/packs/media/images/6929db676d3eeed59dc1.woff",
```
instead it should be (ignoring the "images" naming issue)
```
  "media/images/sans-serif/black.woff": "/packs/media/images/6929db676d3eeed59dc1.woff",
```

**Comment by sled** [comment]
> I opened this PR before seeing this issue: #3082
> 
> But what do you think to put everything in the `static` folder?
> 
> I see no need to split images and fonts even for caching 🤔 do I miss something?

No need to have explicit paths, it’s a purely cosmetic issue. Putting all assets in the `static` would be a good solution to keep things consistent.

**Comment by guillaumebriday** [comment]
Ok fine, I close the issue then 👌 

Thanks!
