### ISSUE TITLE
Static assets do not preserve path structure

### ISSUE THREAD

**Issue by JoeWoodward** [rails/webpacker#3087]
Somewhat related to #3080 

Previously static assets preserved their path structure. e.g. `app/packs/fonts/sans-serif/black.woff` would previously have a manifest entry `media/fonts/sans-serif/black.woff` but now it removes `sans-serif` and is just `media/images/black.woff`

Looks like it was introduced when upgrading to webpack 5 here https://github.com/rails/webpacker/commit/6ba995aed2b609a27e4e35ec28b2a7f688cce0cf#diff-716197750a05276089fff034fe03597e5d569526a8ea683fb0022cf69456cbc4 

In the old version the folder name was inserted but now only the hash is used https://github.com/rails/webpacker/blob/v6.0.0.beta.7/package/rules/file.js

**Comment by sled** [comment]
I think this is discussed in issue #2956 looks like this is an issue in the config for webpack-assets-manifest, see my comment here: https://github.com/rails/webpacker/issues/2956#issuecomment-874164220

**Comment by JoeWoodward** [comment]
Thanks @sled that fixed it! Closing in favor of #2956
