### ISSUE TITLE
5-x-stable: image_pack_tag fails with Webpacker::Manifest::MissingEntryError

### ISSUE THREAD

**Issue by dmolesUC** [rails/webpacker#3101]
Trying to follow the 5.x-stable [installation docs](https://github.com/rails/webpacker/tree/5-x-stable#installation), I've created a Rails 6.1 app with Webpacker 5.4.0 and Webpack 4.46.0 (and _without_ Sprockets). However, when I try to load a page, my application layout fails on the following code:

```erb
<%= image_pack_tag('UCBerkeley_Library_wordmark_black.svg') %>
```

with the error message:

```none
Webpacker can't find UCBerkeley_Library_wordmark_black.svg in /Users/david/Work/ucbears/public/packs/manifest.json
```

It's not lying; there's nothing in the manifest but the compiled `application.js`, and the compiled `application.js` doesn't appear to have anything in it but `webpackBootstrap` code and `@rails/ujs`.

Per the additional info in the error message, I've checked that `webpacker.yml` has `compile: true` for the development environment (I haven't touched `webpacker.yml` since I generated the app).

Am I missing something? I'm guessing there's something I need to put in `app/javascript/packs/application.js` in order for it to pick up the images under `app/javascript/packs/images`, but I don't see anything about that in the README.

### `manifest.json`

```json
{
  "application.js": "/packs/js/application-01a9c683f9016be4a754.js",
  "application.js.map": "/packs/js/application-01a9c683f9016be4a754.js.map",
  "entrypoints": {
    "application": {
      "js": [
        "/packs/js/application-01a9c683f9016be4a754.js"
      ],
      "js.map": [
        "/packs/js/application-01a9c683f9016be4a754.js.map"
      ]
    }
  }
}
```

I note that there's no CSS here, either. I assume I need to add `app/javascript/packs/application.[s]css` and do something to get it to pick up and compile `app/javascript/stylesheets/application.scss`? 

### `application.js`

```js
import Rails from "@rails/ujs"

Rails.start()
```

### `app/javascript` directory

```none
app/javascript
├── images
│   ├── UCBerkeley_Library_wordmark_black.svg
│   ├── UCBerkeley_wordmark_white.svg
│   ├── icons
│   │   ├── exclamation-triangle.svg
│   │   ├── facebook-square.svg
│   │   ├── instagram.svg
│   │   ├── twitter-square.svg
│   │   └── youtube-square.svg
│   └── nav-menu.svg
├── packs
│   ├── application.css
│   └── application.js
└── stylesheets
    ├── application.scss
    └── includes
        ├── body.scss
        ├── colors.scss
        ├── fonts.scss
        ├── footer.scss
        ├── globals.scss
        ├── header.scss
        ├── main.scss
        ├── reset.scss
        └── shared.scss
```

### `public/packs` directory

```none
public/packs
├── js
│   ├── application-01a9c683f9016be4a754.js
│   └── application-01a9c683f9016be4a754.js.map
└── manifest.json
```

### `package.json`

```json
{
  "name": "ucbears",
  "private": true,
  "dependencies": {
    "@rails/ujs": "^6.0.0",
    "@rails/webpacker": "5.4.0",
    "mirador": "^3.2.0",
    "sass": "^1.36.0",
    "sass-loader": "^12.1.0",
    "webpack": "^4.46.0",
    "webpack-cli": "^3.3.12"
  },
  "version": "0.1.0",
  "devDependencies": {
    "webpack-dev-server": "^3.11.2"
  }
}
```

**Comment by dmolesUC** [comment]
OK, I found `require.context('../images, true)` in the [assets documentation](https://github.com/rails/webpacker/blob/5-x-stable/docs/assets.md) and that fixed the image problem, if not the CSS. Could that be added to the README?

**Comment by dmolesUC** [comment]
For anyone coming across this later: to get stylesheets working, I had to downgrade `sass-loader` to  10.x (12.x only works with Webpack 5; 11.x might have worked, but 10.x seems to be what Webpacker 4 is tested with) and add `import '../stylesheets/application.scss'` to my `application.js`.

**Comment by olleolleolle** [comment]
@dmolesUC The README has a single link to the Assets file. Would the word "images" help you find things relating to images quicker, if the README had that? 

Or, would you want to find a new section in https://github.com/rails/webpacker/blob/master/docs/troubleshooting.md ?
