### ISSUE TITLE
babel 7 not handling typescript constructor call in Angular - Uncaught Error: Can't resolve all parameters for AppComponent: (?).

### ISSUE THREAD

**Issue by Cardyard** [rails/webpacker#3102]
Loving the new webpacker. Great job team! We're just upgrading AngularJS to Angular 2+, and Webpacker appeared to have all the answers, but then we couldn't inject classes using `constructor`. The following will fail in a newly created rails project with `rake webpacker:install:angular`

File: `app/javascript/hello_angular/app/app.component.ts`
Code...
```
import { Component, ElementRef} from '@angular/core'
@Component({
  selector: 'hello-angular',
  template: '<h1>Hello {{name}}</h1>'
})
export class AppComponent {
  name = 'Angular!';
  constructor(private elementRef: ElementRef){}
}
```

I found the following similar issue on the babel site:-> [https://github.com/babel/babel/issues/8752]()
and I saw the wonderful [Honeybadger](https://www.honeybadger.io/blog/angular-rails-5/) had success with an [older version of Webpacker](https://github.com/rails/webpacker/compare/v5.0.1...v5.1.0) that used [ts-Loader](https://yarnpkg.com/package/ts-loader) rather than babel-loader

So we have reverted to ts-loader whilst remaining on the latest release of webpacker and it seems to be working fine. We reverted to ts-loader by implementing the following in `config/webpack/environment.js`

```
// Create environment from definition installed by webpacker
const { environment } = require('@rails/webpacker')

// Get ts-loader
const typescript = require('./loaders/typescript')

// Modify scope of webpacker babel loader and remove ts|tsx
const babelIndex = environment.loaders.findIndex(element => element.key==='babel')
if(babelIndex !== -1){
  environment.loaders[babelIndex].value.test = /\.(js|jsx|mjs)?(\.erb)?$/
  // Apply new loader
  environment.loaders.prepend('typescript', typescript)
}

module.exports = environment

```
The babel issue is resolved, but we couldn't get it to work. We'll keep an eye on new releases, but we are working fine.

Thanks for a great product!
Mike

**Comment by justin808** [comment]
Thanks for the feedback. Please try out the new release.
