### ISSUE TITLE
Upgrading to 6.0.0-rc.1 doesn't allow to expose jquery with expose-loader

### ISSUE THREAD

**Issue by vtamara** [rails/webpacker#3116]
I'm testing in the branch `webpacker600rc1` of this application https://github.com/pasosdeJesus/heb412/tree/webpacker600rc1.  

After upgrading and launching the development application, the browser console presents:

```
motor.source.js.coffee.erb:1036 Uncaught ReferenceError: $ is not defined
    at motor.source.js.coffee.erb:1036
    at motor.source.js.coffee.erb:21
```

And it is unable to use jquery.

**Comment by vtamara** [comment]
One workaround is to stay in version 6.0.0.beta.7.

In `Gemfile`:
 ```
gem 'webpacker', '6.0.0.beta.7'
```

In `package.json`:
```
  "@rails/webpacker": "6.0.0-beta.7",  
```

**Comment by vtamara** [comment]
| Gemfile | package.json | Result |
|---|---|---|
| 6.0.0.beta.7 | 6.0.0-beta.7 | Ok |
| 6.0.0.beta.7 | 6.0.0-rc.1 | Ok |
| 6.0.0.rc.1 | 6.0.0-rc.1 | Fail |

**Comment by vtamara** [comment]
The problem is the change in the line 99 of  lib/webpacker/helper.rb
from
```
  javascript_include_tag(*sources_from_manifest_entrypoints(names, type: :javascript), **options)
```
to
```
  javascript_include_tag(*sources_from_manifest_entrypoints(names, type: :javascript), defer: true, **options)
```

**Comment by vtamara** [comment]
Removing the option `defer: true` solves the problem with jquery.
However since it is desired that by default it uses `defer: true` it could be better to use that unless options includes `defer: false`

**Comment by mattiagiuffrida-st** [comment]
@vtamara I had a similar issue and reached your same conclusion, you just need to pass `defer: false` to your call to `javascript_pack_tag` (NOTE: you mentioned `javascript_include_tag` in your last comment, but under webpacker you wouldn't call that method).

I understand the current syntax is a bit unorthodox, but it works as expected, so it's up to @dhh if he wants to change it with something clearer but also more verbose.

My 2 cents, if you're going to open a PR anyway, it would be much more useful to update the README to explain the new default value for `defer`. The example that shows the generated code from `javascript_pack_tag` is outdated and for this reason people might be caught by surprise. A quick note on how to set `defer` differently would also help 🙏
