### ISSUE TITLE
controlling location of asset paths

### ISSUE THREAD

**Issue by scottschafer** [rails/webpacker#3124]
I know something about webpack, and next to nothing about ruby on rails or webpacker. However, I've been asked to upgrade webpacker from 3 to 5 on an existing RoR project and so have landed here.

It seems like in the existing v3 project, images are emitted to` _/assets/etc`. After my upgrade, they are emitted to `media/etc`. This is reflected in the manifest.json.

I'd prefer to keep the existing location so as not to have to modify a lot of Ruby code, but I don't see how. Is there a way to do this?

**Comment by guillaumebriday** [comment]
That would be great to control the path directly in the config for sure. I'll check that and open a PR

**Comment by guillaumebriday** [comment]
I think you can change it like that in Webpacker 5

`environment.loaders.get('file').use.find(item => item.loader === 'file-loader').options.name = 'your-path-here/[folder]/[name]-[hash:8].[ext]'`

Is it what you're looking for?

**Comment by scottschafer** [comment]
Thanks - I ended up using the following code to revert to the old behavior as suggested in the change log: [https://github.com/rails/webpacker/blob/master/CHANGELOG.md](url)
```
const fileLoader = environment.loaders.get('file')
fileLoader.use[0].options.name = '[path][name]-[hash].[ext]'
fileLoader.use[0].options.context = join(config.source_path)
```
