### ISSUE TITLE
Running webpacker:install adds webpack-dev-server ^4.0.0 and the configuration has changed.

### ISSUE THREAD

**Issue by coder2000** [rails/webpacker#3125]
When running webpacker:install as described in the upgrade steps it replaces webpack-dev-server 3.11.2 with 4.0.0, which is good, however it also causes issues as the configuration options have changed for dev-server.

https://github.com/webpack/webpack-dev-server/blob/master/migration-v4.md

**Comment by anark** [comment]
See https://github.com/rails/webpacker/pull/3122 and https://github.com/rails/webpacker/issues/2994
