### ISSUE TITLE
Fails to install Webpacker git repo for upgrade 6.x 

### ISSUE THREAD

**Issue by ndrean** [rails/webpacker#3127]
When running `yarn add https://github.com/rails/webpacker.git`, I get:

error An unexpected error occurred: "expected hoisted manifest for \"@rails/webpacker#webpack#terser-webpack-plugin#webpack\"".

**Comment by PikachuEXE** [comment]
I think you should try
`yarn add webpacker@https://github.com/rails/webpacker.git`

**Comment by ndrean** [comment]
Yes!
    Le lundi 23 août 2021, 10:16:08 UTC+2, PikachuEXE ***@***.***> a écrit :  
 
 


I think you should try
yarn add ***@***.***://github.com/rails/webpacker.git

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ndrean** [comment]
Yes, `yarn add webpacker@https://github.com/rails/webpacker.git` and `gem 'webpacker', '~> 6.0.0.rc.1'` works. Doc to be corrected.

**Comment by ndrean** [comment]
Doc to be updated.
