### ISSUE TITLE
Webpacker 6.0.0.rc.1 doesn't know `install:react`

### ISSUE THREAD

**Issue by ndrean** [rails/webpacker#3129]
The command `rails webpacker:install:react` doesn't exist for 6.0.0.rc1.

**Comment by ndrean** [comment]
yes, maybe closed, I will check, but the [doc](https://github.com/rails/webpacker#installation) is obsolete and incorrect (#3127).

**Comment by guillaumebriday** [comment]
Which section is obsolete?

**Comment by ndrean** [comment]
This one for example:
```sh
# Gemfile
gem 'webpacker', '~> 6.x'              <- fails

# OR if you prefer to use master
gem 'webpacker', git: 'https://github.com/rails/webpacker.git'
(-) yarn add https://github.com/rails/webpacker.git
(+) yarn add webpacker@https://github.com/rails/webpacker.git
```

I do all this to try and get HMR working in a standalone container since this fails now with Rails 6.1.4 and Webpacker 5.4

**Comment by ndrean** [comment]
and (most importantly?) this one is obsolete [guides](https://edgeguides.rubyonrails.org/webpacker.html)

[2.1](https://edgeguides.rubyonrails.org/webpacker.html#integrating-frameworks-with-webpacker)

React | bin/rails webpacker:install:react | Sets up ReactJS

[3.1](https://edgeguides.rubyonrails.org/webpacker.html#using-webpacker-for-javascript)
=> not entrypoint in the file system presented.

**Comment by guillaumebriday** [comment]
I opened a PR to change the `gem` statement here https://github.com/rails/webpacker/pull/3133/

For me `yarn add https://github.com/rails/webpacker.git` is working just fine. What version of yarn are you using?

**Comment by guillaumebriday** [comment]
And yes, the guide need a complete rewrite.

**Comment by ndrean** [comment]
`webpack-cli info` gives me:
```sh
System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 187.48 MB / 16.00 GB
  Binaries:
    Node: 14.15.1 - /usr/local/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 7.20.3 - /usr/local/bin/npm
  Packages:
    webpack: ^4.46.0 => 4.46.0
    webpack-cli: ^4.8.0 => 4.8.0
    webpack-dev-server: ^4.0.0 => 4.0.0
```
I will try again
