### ISSUE TITLE
Add Elm support

### ISSUE THREAD

**Issue by bkuhlmann** [rails/webpacker#313]
I'd like to add support for Elm out-of-the box so that this option is available to those that want to run [Elm](http://elm-lang.org) on top of Rails: `webpacker:install:elm`.

I don't mind doing the work to make this happen if there are no objections? If so, are there any guidelines I need to be aware of before creating a PR (I imagine it'll be several commits consisting of documentation, examples, implementation + specs, generators, etc.)?

**Comment by dhh** [comment]
Go ahead, Brooke. You can follow the patterns from angular/react/vue.
There's not that much to it. Once you have a PR that includes everything,
someone will help review it. Thanks for helping out!

**Comment by bkuhlmann** [comment]
Awesome, will do. I'll work to have a PR ready soon. Thanks!

**Comment by bkuhlmann** [comment]
Support is on `master`, closing this issue. Thanks @gauravtiwari and @guilleiguaran for the support.
