### ISSUE TITLE
Webpacker 6: How to modify default rules (missing doc)

### ISSUE THREAD

**Issue by PikachuEXE** [rails/webpacker#3131]
E.g. I want to update the options for [default rule with `babel loader`](https://github.com/rails/webpacker/blob/v6.0.0.rc.1/package/rules/babel.js#L23-L27)

In webpacker 5 I simply recreate webpack config from part of "environment" exported from webpacker
Not sure what's best for webpacker 6

Edit: I have found a commit about [how to config babel in webpacker 6](https://discuss.rubyonrails.org/t/current-state-of-webpacker/78685/20?u=pikachuexe)

**Comment by guillaumebriday** [comment]
I added a section in this PR https://github.com/rails/webpacker/pull/3133

**Comment by PikachuEXE** [comment]
I will wait for #3133 to be merged then
