### ISSUE TITLE
javascript_pack_tag referencing localhost in production

### ISSUE THREAD

**Issue by gogo52cn** [rails/webpacker#314]
I recently updated webpacker.

Previously everything worked like a charm, javascript_pack_tag is referencing localhost in production.

I use puma as application server and NginX as reverse proxy.

What could be wrong?

**Comment by p0wl** [comment]
seems like somehow rails thinks that the webpack-dev-server is enabled (https://github.com/rails/webpacker/blob/master/lib/install/config/webpack/development.server.yml#L4). Are you using the `assets:precompile` hook or do you manually precompile the assets?

**Comment by gogo52cn** [comment]
Thanks for your comment.
I am using Capistrano. 

# Capfile:
`require 'capistrano/rails'`

# deploy.rb:
```
task :webpack_compile do
  on roles(:web), in: :groups, limit: 3, wait: 10 do
     within release_path do 
       execute :rails, 'webpacker:compile'
     end
  end
end
```

**Comment by gogo52cn** [comment]
The problem is solved.

Cause:

I upgraded from an earlier version of webpacker. I used the old "webpacker:compile" task.

With the new webpacker,  this is not needed. 

Removing this task in the deployment script solves the problem. 

As p0wl mentioned, this makes rails thinks that the development server is running.

**Comment by pierre-pretorius** [comment]
If you bin/rake assets:precompile without RAILS_ENV="production" it also keeps referencing localhost:8080 in the javascript tag even though rails is running in production mode.

**Comment by gauravtiwari** [comment]
@pierre-pretorius That's correct because it uses the local Rails environment so, if you just run that without RAILS_ENV or NODE_ENV being set to production it will compile whatever the current RAILS_ENV is on (or NODE_ENV if set)
