### ISSUE TITLE
Change the default output

### ISSUE THREAD

**Issue by guillaumebriday** [rails/webpacker#3143]
I'm currently looking to change the default Webpack output because it's bit hard to read.

For instance, Laravel-mix use [a custom output](https://github.com/JeffreyWay/laravel-mix/blob/master/src/webpackPlugins/BuildOutputPlugin.js) that we could get inspired of.

Default output:

<img width="1278" alt="Screen Shot 2021-08-28 at 13 14 25" src="https://user-images.githubusercontent.com/8252238/131216183-8033cc32-2f9d-4f6c-b8f1-28046cda97de.png">

Custom output by Laravel-mix:

<img width="1280" alt="Screen Shot 2021-08-28 at 13 14 20" src="https://user-images.githubusercontent.com/8252238/131216189-338655df-8745-422f-a4c6-b24e8357bb3e.png">

**Comment by guillaumebriday** [comment]
Maybe we should wait the answer for this issue: https://github.com/JeffreyWay/laravel-mix/issues/3078

**Comment by mcmire** [comment]
This would be a huge help, I think, for people who know little about Webpack. Based on my experiences with such devs, I seriously doubt that the output produced now is even looked at. So I think this is a great idea.

**Comment by justin808** [comment]
I'd lean toward using a well-supported dependency. There's already enough to support here.

In other words, when we upgrade webpack, who will upgrade the output? Should the output stop a webpack update?

**Comment by guillaumebriday** [comment]
@justin808 This is a concern but in the worst scenario we could just remove the custom output I guess.

Laravel-mix is shipped by default in Laravel and won't die anytime soon. Their community is huge.

We could also help them to maintain their output so it could become the reference for Webpack 5+.

Check out that: https://github.com/laravel-mix/laravel-mix/issues/3078#issuecomment-910724817
