### ISSUE TITLE
Upgrade guide from 4.x.x to 5.x.x

### ISSUE THREAD

**Issue by pawlarius** [rails/webpacker#3148]
Hi, is there any upgrade/migration guide from Webpacker v4.x.x to v5.x.x?

I tried to follow steps defined by the [official docs here](https://github.com/rails/webpacker/tree/5-x-stable#upgrading) but upon upgrading I encountered many different issues.

I'm trying to use upgrade webpacker from v4.3.0 to v5.4.2.

At first I got issues when running ./bin/webpack-dev/server, which installed "@webpack-cli/serve" as devDependencies but it will return errors like this.

<img width="611" alt="Screen Shot 2021-08-31 at 00 39 28" src="https://user-images.githubusercontent.com/27823957/131381384-2bc9cad5-ad42-43d0-a470-272298c50d83.png">

Then I need to manually fix that by removing the devDependencies then adding "webpack-cli": "^4.3.0" as dependencies.

Then I got another chunkhash error, which I need to manually add webpack output config inside config/webpack/environment.js
```
...
output: {
  filename: isDevelopment ? 'js/[name]-[hash].js' : '[name].[chunkhash].js',
},
...
```

After that, running ./bin/webpack-dev-server works, but it seems the rails server are ignoring the webpack.

Whenever I tried to access a page, the rails server will keep compiling webpacker even though ./bin/webpack-dev-server is already running in other tab.

I've enabled hmr in my webpacker.yml and when there is any file changes, the ./bin/webpack-dev-server will show some new compiling logs but it does no changes/refresh at all in my web browser..

Can anyone here share how you upgrade & adjust your webpacker?

**Comment by Erowlin** [comment]
I'm having the exact same issue. On my hand, it appears that the webpack-dev-server is starting on a different port (8080). 
One guess is that the webpacker.yml file is ignored and the defaults are loaded, I'm not sure why yet.

```
❯ /Users/xx/work/xx/node_modules/.bin/webpack-dev-server --config /Users/xx/work/xx/config/webpack/development.js
<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:8080/
<i> [webpack-dev-server] On Your Network (IPv4): http://192.168.1.17:8080/
<i> [webpack-dev-server] On Your Network (IPv6): http://[fe80::1]:8080/
<i> [webpack-dev-server] Content not from webpack is served from '/Users/xx/work/xx/public' directory
```

**Comment by Erowlin** [comment]
Wepacker 5.x is not yet compatible with webpack-dev-server 4

https://github.com/rails/webpacker/pull/3122

**Comment by bjufre** [comment]
@Erowlin any news on this? After updating, we're still getting the `TypeError: Class constructor ServeCommand cannot be invoked without 'new'`

**Comment by Erowlin** [comment]
We postponed the upgrade for now

**Comment by shaneajeffery** [comment]
I'm on the same bandwagon as @bjufre.  We are needing to upgrade to the latest version of Webpacker because our current version still has a dependency on `node-sass`.  `node-sass` will not compile on the new M1 macs.

Anyways, if anyone has a solve for the `TypeError: Class constructor ServeCommand cannot be invoked without 'new'`, please let us know!

Please note that the above error happens after we follow the upgrade path that Webpacker has laid out and after `webpack-cli` prompts us to install the new `serve` command as a part of the upgrade to the latest webpack dev server.

**Comment by shaneajeffery** [comment]
> @Erowlin any news on this? After updating, we're still getting the `TypeError: Class constructor ServeCommand cannot be invoked without 'new'`

@Erowlin If you never figured it out, it turns out that when you prompted install `@webpack-cli/serve`, it doesn't install the parent dependency.  So you have to do `yarn add @webpack-cli` and that solves the issue.

**Comment by zedtux** [comment]
Actually it's `yarn add webpack-cli` and it solves the error.

**Comment by justin808** [comment]
I think the v6 release should address your issues.

**Comment by zedtux** [comment]
okay, but version 6 is in rc so right now there's no solution, right?

**Comment by justin808** [comment]
Very soon!

**Comment by jshah** [comment]
Any update on the v6 release?

@justin808

**Comment by dep** [comment]
Like soon as in ...?

**Comment by justin808** [comment]
In case anybody gets here, please see:

https://github.com/shakacode/shakapacker/blob/master/docs/v6_upgrade.md
