### ISSUE TITLE
Feature Request - Remove PreCSS - add cssnext

### ISSUE THREAD

**Issue by djforth** [rails/webpacker#315]
PreCSS seems like it's not well maintained having not been touched in 2 years, when I tried to use in a project with just postcss is caused a lot of issues.  Also not sure what the benefit is of having scss-esque in css when scss is already included?

http://cssnext.io (postcss-cssnext) might be a better option to include? It well maintained and is pushing itself as a sort of babel for CSS, supporting upcoming features like the new  custom properties - http://cssnext.io/features/#custom-properties-var.  It also has autoprefixer included with it.

**Comment by gauravtiwari** [comment]
@djforth Sounds good 👍  Wanna make a PR for this ? 😄

**Comment by djforth** [comment]
Will do :)
