### ISSUE TITLE
Cannot use Stimulus 3.0.0-beta.1 with Webpacker 6.0.0.rc.5

### ISSUE THREAD

**Issue by dwightwatson** [rails/webpacker#3153]
I've just tried upgrading my Rails app with Webpacker 6.0.0.rc.5 to use Stimulus 3.0.0-beta.1. However, I get an error that I cannot invoke the Controller constructor.

```
application.js:75 Uncaught (in promise) TypeError: Class constructor Controller cannot be invoked without 'new'
    at new _default (application.js:75)
    at new extended (vendors-node_modules_hotwired_stimulus_dist_stimulus_js.js:1327)
    at new Context (vendors-node_modules_hotwired_stimulus_dist_stimulus_js.js:1187)
    at Module.fetchContextForScope (vendors-node_modules_hotwired_stimulus_dist_stimulus_js.js:1389)
    at Module.connectContextForScope (vendors-node_modules_hotwired_stimulus_dist_stimulus_js.js:1375)
    at Router.scopeConnected (vendors-node_modules_hotwired_stimulus_dist_stimulus_js.js:1694)
    at ScopeObserver.elementMatchedValue (vendors-node_modules_hotwired_stimulus_dist_stimulus_js.js:1612)
    at ValueListObserver.tokenMatched (vendors-node_modules_hotwired_stimulus_dist_stimulus_js.js:803)
    at TokenListObserver.tokenMatched (vendors-node_modules_hotwired_stimulus_dist_stimulus_js.js:736)
    at vendors-node_modules_hotwired_stimulus_dist_stimulus_js.js:730
```

It works fine with Stimulus 2. If I downgrade to Webpacker 5 with the Stimulus 3.x beta it also works fine. It is only broken with the Webpacker beta and Stimulus beta.

Here is the initial issue on the hotwired/stimulus#433 repo.

Here is a minimal reproduction with a fresh Rails/Webpacker beta/Stimulus beta setup: https://github.com/dwightwatson/stimulus-3-reproduction

**Comment by dhh** [comment]
I replicated this as well in my testing. Def need to sort it.

**Comment by dhh** [comment]
Choosing to pursue a path that's not contingent on Webpack API changes as explained in https://github.com/hotwired/stimulus/issues/433#issuecomment-917363278

**Comment by dhh** [comment]
I can't replicate this using webpack via jsbundling-rails. Maybe something else is wrongly setup in Webpacker. Anyway, reopening.

**Comment by adrienpoly** [comment]
This error is not limited to the stimulus/webpacker-helpers, more details [here](https://github.com/hotwired/stimulus/issues/433#issuecomment-926365479) 

After several testing and comparison with Webpacker 5 settings, I think I found the source. Removing `loose: true` in babel seems to solve the issue.

```diff
{
  useBuiltIns: 'entry',
  corejs: '3.8',
  modules: 'auto',
  bugfixes: true,
-  loose: true,
  exclude: ['transform-typeof-symbol']
}
```

@guillaumebriday any idea if there is something that should be changed in how Stimulus is bundled or if this setting should be removed from default Webpacker settings?

**Comment by mrhead** [comment]
We had the same issue with Webpacker 6 and Stimulus 3. Setting `loose: false` in `babel-preset.js` fixed the issue.

You can use the following commit (not mine) as reference: https://github.com/ubpb/catalog/commit/47bf8cc4c0def4a5f9a2d4c83e004b0baadd396e

**Comment by dwightwatson** [comment]
A comment from the original issue on Stimulus shows you can sidestep the issue by dropping IE 11 support: https://github.com/hotwired/stimulus/issues/433#issuecomment-956601114

Not ideal but a potential solution for those who don't need IE 11 support in the meantime.

**Comment by guillaumebriday** [comment]
It's definitively related to the `browserslist` configuration

**Comment by OuttaSpaceTime** [comment]
@guillaumebriday are you that this issue is closed? it does not seem like a real solution when the support of specific browser has to be dropped completely. 

Or is this dropping safe?

**Comment by t27duck** [comment]
It is also possible that the dropping of this line https://github.com/rails/webpacker/pull/3225/files#diff-b2ec4a738b0a348ca8f879ca88a9ae1e9d719564e7eb015b4ebaed1da127f6e6L45 makes Stimulus 3 magically work out of the box now.
