### ISSUE TITLE
Babel as opinionated dependency

### ISSUE THREAD

**Issue by vladimirtemnikov** [rails/webpacker#3155]
Greetings.

Just a quick question: is there any strong convention to specify babel, preset-env, etc as direct dependencies in Webpacker?

I mean, if the team prefers to skip the support of the older browsers for their project, is there any need to keep all of these packages (especially if using yarn v.2+ with zero-install feature) and processing js sources through babel (this can be disabled with monkey-patching Webpacker package's included rules but anyway)?

**Comment by justin808** [comment]
I think in the interests of sliming down rails/webpacker, removing the babel dependency is worthwhile as https://swc.rs/ seems to be gaining momentum.

**Comment by justin808** [comment]
@vladimirtemnikov you should be able to customize the packages and the webpack config, including the babel config. What's the issue?

> this can be disabled with monkey-patching Webpacker package's included rules but anyway

That's not really true. rails/webpacker provides a template webpack config object that you can modify with webpack-merge.

**Comment by alexvbush** [comment]
@justin808 so how would I remove babel from my project? related to https://github.com/rails/webpacker/issues/3255

**Comment by justin808** [comment]
@alexvbush you have 2 options for the webpack part:

1. Setup your own webpack configuration.
1. Provide a PR that makes babel an optional dependency

At the end of the day, you're having webpack run to produce a manifest and result files in the right spot, per webpacker.yml.

You can have webpack invoked either by:

1. replace the contents of bin/webpack with your own bash or ruby script
2. change the contents of the config/webpack/{test|development|production}.js files

I look forward to seeing what you come up with!
