### ISSUE TITLE
Using webpack=react and css

### ISSUE THREAD

**Issue by rafaelfranca** [rails/webpacker#317]
_From @MrSkinny on May 2, 2017 20:54_

The popular `create-react-app` uses a default config where you would create a complementary css file with every component, e.g.

```
// App.css

.App {
  /* stuff */
}
```

```
import './App.css';

const App = () => {
  return (
    <div className="App">App</div>
  );
};

export default App;
```

What is the best way to configure this in Rails 5.1 with `--webpack=react`?  It looks like `style-loader` and `css-loader` are bundled by default and I'm not getting an error when I `import './Whatever.css';` but it's not outputting the style tag to the DOM.

_Copied from original issue: rails/rails#28962_

**Comment by gauravtiwari** [comment]
@MrSkinny You would need to include `<%= stylesheet_pack_tag 'pack_name' %>` inside your views just like `javascript_pack_tag` helper. See the CSS section please - https://github.com/rails/webpacker#linking-to-static-assets

**Comment by MrSkinny** [comment]
Thanks for the fast help and pointers @rafaelfranca @gauravtiwari !

**Comment by gauravtiwari** [comment]
Great no problem Rich 👍 . Closing this now
