### ISSUE TITLE
Can't override loader options: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by boardfish** [rails/webpacker#3173]
Trying to follow [these steps](https://github.com/rails/webpacker/blob/5-x-stable/docs/webpack.md#overriding-loader-options-in-webpack-3-for-css-modules-etc) with Webpacker 6.0.0-rc.5, Webpack 5.53.0. The aim is to override `localIdentName` from the outside so that I can continue to use CSS modules with pseudo-encapsulation in Rails as I have before. I'd already achieved this in the previous version.

When I call `loaders` on `webpackConfig`, it returns `undefined`. `webpackConfig` itself returns the following:

```js
{
  mode: 'development',
  output: {
    filename: 'js/[name].js',
    chunkFilename: 'js/[name].chunk.js',
    hotUpdateChunkFilename: 'js/[id].[fullhash].hot-update.js',
    path: '/home/si/code/raisedev/public/packs',
    publicPath: '/packs/'
  },
  entry: {
    application: '/home/si/code/raisedev/app/packs/entrypoints/application.js'
  },
  resolve: {
    extensions: [ '.js', '.jsx', '.mjs', '.ts', '.tsx', '.coffee' ],
    modules: [
      '/home/si/code/raisedev/app/packs',
      '/home/si/code/raisedev/app/components',
      'node_modules'
    ],
    plugins: [ [Object] ]
  },
  plugins: [
    EnvironmentPlugin { keys: [Array], defaultValues: [Object] },
    WebpackAssetsManifest {
      hooks: [Object],
      options: [Object],
      assets: [Object: null prototype] {},
      assetNames: Map(0) {},
      currentAsset: null,
      compiler: null,
      [Symbol(isMerging)]: false
    },
    MiniCssExtractPlugin {
      _sortedModulesCache: [WeakMap],
      options: [Object],
      runtimeOptions: [Object]
    }
  ],
  resolveLoader: { modules: [ 'node_modules' ], plugins: [ [Object] ] },
  optimization: { splitChunks: { chunks: 'all' }, runtimeChunk: 'single' },
  module: {
    strictExportPresence: true,
    rules: [ [Object], [Object], [Object], [Object] ]
  },
  devtool: 'cheap-module-source-map'
}
```

**Comment by guillaumebriday** [comment]
`localIdentName` is specific to the `css-loader` so you should override this rule only

There is no key loaders on the config, there is `rules` with `loaders` inside as object

**Comment by boardfish** [comment]
I had a feeling that'd be the case. I just wasn't sure how to repeatably find the rule associated with `css-loader`, since the `loader` field points to a specific path under `node_modules` as opposed to a module name, so we can no longer `find(el => el.loader === 'css-loader')`.

I can raise a PR to update that documentation once we have the solution.

**Comment by boardfish** [comment]
It turned out I had to configure this inside `MiniCssExtractPlugin`, so I ended up doing the following:

```js
webpackConfig.module.rules.find(
  (rule) => rule.use && rule.use.includes(MiniCssExtractPlugin.loader)
).use = [
  MiniCssExtractPlugin.loader,
  {
    loader: "css-loader",
    options: {
      sourceMap: true,
      importLoaders: 2,
      modules: { auto: true, localIdentName: "[folder]_[name]__[local]" },
    },
  },
  {
    // PostCSS is configured at .postcssrc.yml.
    loader: "postcss-loader",
  },
]
```
