### ISSUE TITLE
Please help this newbie rails programmer

### ISSUE THREAD

**Issue by taesla14** [rails/webpacker#3175]
``I wanted to deploy my app to heroku.

But i got this error message and failed.

Is there anyone know how to solve it?
`remote:        Compiling…
remote:        Compilation failed:
remote:        error Command "webpack" not found.
remote:        
remote:        yarn run v1.22.4
remote:        info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
remote:        
remote: 
remote:  !
remote:  !     Precompiling assets failed.
remote:  !
remote:  !     Push rejected, failed to compile Ruby app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !       Push rejected to ancient-cove-39153.
remote: 
To https://git.heroku.com/ancient-cove-39153.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/ancient-cove-39153.git'`

**Comment by olleolleolle** [comment]
👋 @taesla14 Hello! This is a bug tracker, not a support forum. https://stackoverflow.com/questions/tagged/webpacker is a place on StackOverflow, which _is_ a community-driven support forum for all things. You may have more luck asking your question, there!

This repository has [a Troubleshooting document](https://github.com/rails/webpacker/blob/master/docs/troubleshooting.md), but I guess there's a Heroku connection to your issue, as well.

Best of luck!

**Comment by rlogwood** [comment]
This may help you:
```sh
% heroku apps:create --buildpack heroku/ruby my-app-name
# optionally set buildpack after heroku app creatikon
# % heroku buildpacks:set heroku/ruby
% heroku buildpacks:add --index 1 heroku/nodejs
% heroku buildpacks
% git checkout -b main
% git add .
% git commit -m "initial check-in"
% git push heroku main
```
