### ISSUE TITLE
Namespacing packs is broken

### ISSUE THREAD

**Issue by brandoncordell** [rails/webpacker#3179]
#3156 breaks namespaced packs.

We namespace our app heavily on the Rails side of things so we ended up following the same convention when we moved to webpacker. The above PR [removes the recursive glob from base.js](https://github.com/rails/webpacker/commit/5de0fbc1e16d3db0c93202fb39f5b4d80582c682#diff-7af8667a3e36201db57c02b68dd8651883d7bfc00dc9653661be11cd31feeccdR19).

**Comment by guillaumebriday** [comment]
Why did you close the issue @brandoncordell?

**Comment by brandoncordell** [comment]
@guillaumebriday I figured going by the original PR comments that this wasn't a change that would be reverted. If it's up for discussion, we can reopen it. 

If I have time later today I'll try and open a PR to make this work with the new folder structure.
