### ISSUE TITLE
[webpacker 6.0.0.rc.5] stylesheet_pack_tag doesn't work with HMR

### ISSUE THREAD

**Issue by pustovalov** [rails/webpacker#3183]
```
// webpacker.yml

hmr: false
```
![image](https://user-images.githubusercontent.com/1568885/135753441-0d2a38fb-5034-4d2f-a1f6-43008108d8fc.png)

```
// webpacker.yml

hmr: true
```

![image](https://user-images.githubusercontent.com/1568885/135753473-6154be93-65a9-44cd-8827-2a5e46ed12c7.png)

Demo repo:
https://github.com/pustovalov/webpacker-hmr-reproduce

**Comment by guillaumebriday** [comment]
Could you take a look @justin808 please?

**Comment by justin808** [comment]
Should we close this one? 

I don't see any documentation of the issue above.

**Comment by justin808** [comment]
Seems like a misunderstanding that HMR page should have the CSS  on the HTML. It just shouldn't.

**Comment by pustovalov** [comment]
>Should we close this one?

Need to describe it in the documentation at least. Webpacker v6 doesn't support HMR and CSS outside of JS together. Because this combination worked good in Webpacker v5.

**Comment by justin808** [comment]
@pustovalov I think this should be closed. We've got support for CSS with HMR.

For React, here's the configuration for HMR.

https://github.com/rails/webpacker/pull/3224

**Comment by pustovalov** [comment]
>We've got support for CSS with HMR.

@justin808 where was this support added? `stylesheet_pack_tag` still returns `nil`: https://github.com/rails/webpacker/blob/2f4df42c9a4b8d6f9838be0b60c599c8f1c5e363/lib/webpacker/helper.rb#L144

**Comment by justin808** [comment]
It's supposed to return blank if that value is true.

Just setup your webpscker config so that value is false.
