### ISSUE TITLE
javascript_pack_tag seems to add path twice with asset host

### ISSUE THREAD

**Issue by wjdhamilton** [rails/webpacker#320]
Since upgrading to 1.2 `javascript_pack_tag` no longer seems to render the correct url.

I am using an asset host, specified in `production.rb`. 

In previous versions, the`manifest.json` file copiled for production looked something like this:

```json
{
  "admin.js" : "/packs/admin-s089sdf098.js"
}
```

But now it explicitly includes the asset host path, rendering something like this:

```json
{
  "admin.js": "jiu8a9d8f9.cloudfront.net/packs/admin-s089sdf098.js"
}
```

The effect of this is that the `javascript_pack_tag` helper renders the path twice as follows:

`https://jiu8a9d8f9.cloudfront.net/javascripts/jiu8a9d8f9.cloudfront.net/packs/admin-s089sdf098.js`

Which doesn't work. 

Note that "javascripts" has made it into the link too, which I think is incorrect. 

I have run webpacker:install as part of the upgrade process, but perhaps I have missed something else.

Any ideas would be welcome!

**Comment by wjdhamilton** [comment]
I can confirm that moving back to webpacker 1.1 fixes the issue, so it looks like some kind of regression in 1.2.

Thanks very much for all you efforts in making this work btw!

**Comment by zinkkrysty** [comment]
It seems related to https://github.com/rails/webpacker/pull/224

**Comment by gauravtiwari** [comment]
Yes, this need fixing
