### ISSUE TITLE
Documentation for v6 upgrade is unclear

### ISSUE THREAD

**Issue by TruePath** [rails/webpacker#3202]
The documentation for v6 upgrade says: 

"Ensure that your layouts and views will only have at most one call to javascript_pack_tag or stylesheet_pack_tag."

This sentence is open to interpretation as saying that you can only call either javascript_pack_tag or stylesheet_pack_tag but not both (i.e. you can have at most one call to a helper in the set {javascript_pack_tag, stylesheet_pack_tag}). 

I suggest you reword it (assuming you mean this) as: 

"Ensure that your layouts and views will only have at most one call to javascript_pack_tag and at most one call to stylesheet_pack_tag."

I'd create a pull request but it would take more fuckery to actually generate the pull request and for you to review it than for you to just make the change if you agree.

(thanks for the great software BTW!!)

**Comment by guillaumebriday** [comment]
Could you open a PR with your suggestions please? Thanks 🙏
