### ISSUE TITLE
Future support and long term mantability, will this webpacker be deprecated? Asking for 100M user migration

### ISSUE THREAD

**Issue by gastonmorixe** [rails/webpacker#3204]
Hi community, 

A client of mine has a site with around 100M users which is considering moving to React and we need Webpack to integrate we Rails. It's a top website in the world and decisions must be taken carefully. 

We are using Rails 3 and plan to upgrade everything. We are considering all options to integrate JS with Rails and the easiest by far is using this gem. Sadly after a [few comments from @dhh here](https://world.hey.com/dhh/modern-web-apps-without-javascript-bundling-or-transpiling-a20f2755), which don't get me wrong I agree with most of them, my team is discouraged of using this gem and want to explore other options.

**My question is simply how do you see long term maintainability of this gem? specially after the drop of default in Rails 7.**

As of today webpacker ranks #517 with 39,439,103 downloads.

Thank you so much for your time

**Comment by dhh** [comment]
Webpacker v6 is a great option for those who want to continue on that track. But it will no longer be bundled with Rails 7. The path we're going with by default going forward is import maps (no Node required at all) and then jsbundling-rails as the step from there. But you don't need anyone's permission to continue to use Webpacker if you fancy. The gem will still be there, and v6 is a much slimmer fit than v5 was.

**Comment by gastonmorixe** [comment]
Thank you for your words @dhh

**Comment by justin808** [comment]
@gastonmorixe In case you didn't see, v6 got released as https://github.com/shakacode/shakapacker. 🚀
