### ISSUE TITLE
Rake tasks don't show log out put

### ISSUE THREAD

**Issue by joker-777** [rails/webpacker#3208]
This happens because you have to assign `Logger.new(STDOUT)` instead of `ActiveSupport::Logger.new(STDOUT)` to `Webpacker.logger`  [in this line](https://github.com/rails/webpacker/blob/master/lib/webpacker.rb#L27). This definitely happens on 5.4.3 but probably also in webpacker 6.

**Comment by joker-777** [comment]
We use [semantic logger for rails](https://github.com/reidmorrison/semantic_logger) which is probably the reason for this problem.

**Comment by justin808** [comment]
@guillaumebriday I took a look at the original change 

https://github.com/rails/webpacker/pull/2389/files#diff-7606e0573e7bae475cb0f71eff95e60a350c0df459bd9c992fd030de47c7c64cR27

If the intent of the code is to ALWAYS go to STDOUT, then the changes suggested look fine.
