### ISSUE TITLE
Webpacker doesn't support custom loaders

### ISSUE THREAD

**Issue by SamShekhovtsov** [rails/webpacker#3210]
### Custom loaders are causing webpacker to behave incorrectly, ignore some files from loading

if I add a custom loader, for example the haml loader:

```
// config/webpack/rules/haml.js
module.exports = {
    module: {
      rules: [
        {
          test: /\.haml$/,
          loader: 'haml-haml-loader'
        }
      ]
    },
    resolve: {
      extensions: ['.haml']
    }
  }
```

```
// config/webpack/base.js
const { webpackConfig, merge } = require('@rails/webpacker')
const hamlConfig = require('./rules/haml')

module.exports = merge(hamlConfig, webpackConfig)
```

some application files stop loading. For instance, I got Angular error because corresponding file wasn't loaded:

**TypeError: Cannot read properties of undefined**

just removing this custom loader makes everything work fine. When **ANY** custom loader is added the application files stop loading for some reason.

**Comment by SamShekhovtsov** [comment]
actually that only happens if I specify:

```
resolve: {
      extensions: ['.haml']
    }

```
if I remove that piece, **the custom loader works fine!**

**Comment by guillaumebriday** [comment]
Which version of Webpacker you're using?

**Comment by SamShekhovtsov** [comment]
the latest one: 6 release candidate (6.0.0-rc.5) . I think that this issue can be closed, because when I omit the **extensions: ['.haml']** part it works as desired.

**Comment by guillaumebriday** [comment]
Great!
