### ISSUE TITLE
Deployment instructions for Heroku apps potentially problematic

### ISSUE THREAD

**Issue by andreas-venturini** [rails/webpacker#3212]
In the [docs section about Heroku deployments](https://github.com/rails/webpacker/blob/master/docs/deployment.md#heroku) it's recommended to include the Heroku nodejs buildpack. 

However, this is potentially problematic as in Rails apps `yarn install` will again be [run as part of the asset precompilation step if the yarn binstub is present](https://github.com/rails/rails/blob/6-1-stable/railties/lib/rails/tasks/yarn.rake#L28) (which is probably the case for the majority of Rails apps)

This leads to yarn install being executed twice, as described [in this comment](https://github.com/heroku/heroku-buildpack-ruby/issues/654#issuecomment-377127345) .

In the same issue one suggested workaround is to [manually disable the yarn install rake task](https://github.com/heroku/heroku-buildpack-ruby/issues/654#issuecomment-387226196) - I think this should be added as a disclaimer to the deployment docs section.

If this is an agreeable change I can send a PR.

**Comment by dwightwatson** [comment]
The ruby buildpack should now include Node for Webpacker out of the box, so is this necessary at all? Could we just remove the node buildpack recommendation from the docs?

**Comment by andreas-venturini** [comment]
> The ruby buildpack should now include Node for Webpacker out of the box, so is this necessary at all

Technically it's not (at least not right now). However, I would advise against removing for two reasons:
1. with Yarn 2 the Ruby buildpack fails to [prune dev dependencies](https://devcenter.heroku.com/articles/migrating-to-yarn-2#pruning-devdependencies) which will increase the Heroku slug size. This is easy to miss as I imagine not everyone monitors their slug size.
2. the current Ruby buildpack seems deprecated and will be replaced w/ a [Cloud Native Buildpack](https://github.com/heroku/buildpacks-ruby) that explicitly requires node to be installed via the heroku/nodejs buildpack.

**Comment by justin808** [comment]
@guillaumebriday I made a small update here: https://github.com/rails/webpacker/pull/3231/files

@andreas-venturini Would be great if you can submit a PR with som add some additional details regarding the duplicate yarn install.

@dwightwatson I think having both the ruby and node buildpacks makes logical sense for Heroku applications using webpack.

**Comment by guillaumebriday** [comment]
Great! I'm pretty sure we can close this issue right?

**Comment by justin808** [comment]
@guillaumebriday, yes, I think so. In the future, somebody can open up a more specific issue with a problem and maybe a proposed solution.

While I think it's suboptimal for yarn to run twice with Heroku, it runs quite fast the second time, so it's not a huge issue.
