### ISSUE TITLE
ROR and Webapcker 6 is not compatible with Angular 13

### ISSUE THREAD

**Issue by SamShekhovtsov** [rails/webpacker#3215]
After creating a very simple application, it appears that the ROR with Webpacker 6 is not compatible with latest Angular.

When injecting a service as a constructor parameter using DI, following error is shown:

**Error: This constructor is not compatible with Angular Dependency Injection because its dependency at index 0 of the parameter list is invalid.**

it only happens when Angular is running with Ruby on Rails and Webpack. I've created a sample repository to easily reproduce this issue:

https://github.com/SamShekhovtsov/demo-webpa-k6-angular13

Any advice is much appreciated.

[ERROR screenshort](https://imgdb.net/storage/uploads/2e05720d73534e94ad04d9086ccf40fd032a9eefeb61a1e3b4b7eb0636f311c7.png)

**Comment by guillaumebriday** [comment]
After a quick Google search, your issue seems to be more related with your TS or babel config I guess right?

Or which version of Webpacker are you using exactly?

**Comment by guillaumebriday** [comment]
It does not seem related to Webpacker but to Angular 13 Babel and TS compatibility.

Could you try to tweak your configuration?

cf: https://github.com/rails/webpacker/issues/3219

Feel free to reopen if you're sure that is related to Webpacker in any way
