### ISSUE TITLE
Create git tag for v6.0.0.rc.6

### ISSUE THREAD

**Issue by n-rodriguez** [rails/webpacker#3216]
Hi there!

npm package has been released https://www.npmjs.com/package/@rails/webpacker/v/6.0.0-rc.6 but there is not git tag https://github.com/rails/webpacker/tags to keep the gem and the JS lib synced within an application.

ping @dhh 

Thank you!

**Comment by dhh** [comment]
Just pushed the tag 👍

**Comment by n-rodriguez** [comment]
Thank you!
