### ISSUE TITLE
Webpacker 6: Missing documentation on how to resolve images or fonts used in scss

### ISSUE THREAD

**Issue by kimyu92** [rails/webpacker#3222]
I believe it's quite common to use `resolver-url-loader` to ensure the relative path of image is working in scss.
However, it seems like I can't find any documentation in the upgrade guide that talks about this particular changes. 

### Error
Error 1: Failed to resolve image path used in scss (Resolved) 
```sh
Module not found: Error: Can't resolve '../assets/images/bar.png' in '/sample/app/javascript/packs'
resolve '../assets/images/bar.png' in '/sample/app/javascript/packs'
  using description file: /sample_app/package.json (relative path: ./app/javascript/packs)
    using description file: /sample_app/package.json (relative path: ./app/javascript/assets/images/bar.png)
```

Error 2: Similar to issues, https://github.com/rails/webpacker/issues/1267 & https://github.com/rails/webpacker/issues/1119, after upgrading to webpacker 6, it failed to resolve bootstrap glyhicons with previous workaround mentioned in https://github.com/rails/webpacker/issues/1119#issuecomment-352738508 
```sh
Module not found: Error: Can't resolve '../fonts/bootstrap/glyphicons-halflings-regular.svg' in '/sample/app/javascript/packs'
resolve '../fonts/bootstrap/glyphicons-halflings-regular.svg' in '/sample/app/javascript/packs'
  using description file: /sample_app/package.json (relative path: ./app/javascript/packs)
    using description file: /sample_app/package.json (relative path: ./app/javascript/assets/images/bar.png)
```

### Folder structure
```
app
  |___ javascript
  |   |
  |   |___ packs
  |      |
  |      |___ ApplicationPack.js
  |      |
  |___assets
  |   |  
  |   |___ stylesheets
  |   |  |   |
  |   |  |   |__ Application.scss
  |   |  |   |
  |   |___ images
  |   |  |   |
  |   |  |   |__ bar.png
```

```scss
# Application.scss
.foo {
  background-image: url('../assets/images/bar.png');
}
```

### Webpack config
```js
// config/webpack/base.js

const { webpackConfig, merge } = require('@rails/webpacker');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');

merge(webpackConfig, {
  module: {
    rules: [
      {
        test: /\.(sa|sc|c)ss$/i,
        use: [
          {
            loader: MiniCssExtractPlugin.loader,
          },
          'css-loader',
          'postcss-loader',
          'resolve-url-loader',
          {
            loader: 'sass-loader',
            options: {
              sourceMap: true,
              sourceMapContents: false,
            },
          },
        ],
      },
    ],
  },
});

module.exports = webpackConfig;
```

### System
- Webpacker 6.0.0-rc.6
- Webpack 5.62.x
- resolve-url-loader 4.0.0

### Update
To resolve relative image used in scss
- Follow https://github.com/rails/webpacker/issues/2956#issuecomment-878935678 to patch `/config/webpack/base.js`
```js
...

const customConfig = {
  context: path.resolve(__dirname, '../../app/javascript'), // Default webpacker setup, old setup was app/javascripts, this is the value from webpacker.yml "source_path"
  // ...rest of your customConfig goes here
}

// you may need to update relative path in scss as well, eg. update url('../assets/...') to url('../../assets/..')
```

Any guidance/insight regarding on how to resolve bootstrap glyphicons would be much appreciated 🙏 .

**Comment by justin808** [comment]
@guillaumebriday this seems to be a doc issue, as rails/webpacker code is just for the simple cases.

**Comment by kimyu92** [comment]
This seems to be related to `resolve-url-loader` instead of webpacker upgrade.

However, for those who encounter issue using resolve-url-loader >= 3 to import images in scss file, 

I ended up using [solution](https://github.com/bholloway/resolve-url-loader/issues/105#issuecomment-429322174) here where I create an alias for image directory in webpack `custom.js` and then instead of using relative path, I point it to `url('~images/x.png')`

```js
const path = require('path');
module.exports = {
  resolve: {
    alias: {
      images: path.resolve(__dirname, '../../app/assets/images'),
    },
  },
};
```

To resolve bootstrap-sass glyphicon issue, credit: https://github.com/maxmx/bootstrap-stylus/issues/129
```scss
$icon-font-path: '~bootstrap-sass/assets/fonts/bootstrap/';
@import '~bootstrap-sass/assets/stylesheets/bootstrap';
```

**Comment by justin808** [comment]
Thanks, @kimyu92! This is a useful tip!
