### ISSUE TITLE
Change name of bin/webpack to bin/webpacker (and bin/webpack-dev-server to bin/webpacker-dev-server)

### ISSUE THREAD

**Issue by justin808** [rails/webpacker#3237]
A source of confusion has always been using `bin/webpack` and `bin/webpack-dev-server` to call the respective node modules of `webpack` and `webpack-dev-server`. 

It's confusing to many to **override** those, *especially* to devs new to rails/webpacker. 

It would be much more clear to call these `bin/webpacker` and `bin/webpacker-dev-server`. (with the `webpacker` in the name).

The v6 release is the right time to do this.

**Comment by justin808** [comment]
@guillaumebriday do you like this idea?

**Comment by justin808** [comment]
@dhh any opinion on this one?

**Comment by guillaumebriday** [comment]
I like the idea! Because too much people are confused 👍

**Comment by apuntovanini** [comment]
Like the idea as well!

**Comment by guillaumebriday** [comment]
@justin808 Could you open a PR for that? With a note in the upgrade guide?

**Comment by justin808** [comment]
I'm on it! I didn't want to start until we had consensus.

**Comment by justin808** [comment]
@guillaumebriday Done! #3252
