### ISSUE TITLE
Ignore minifying one particular directory?

### ISSUE THREAD

**Issue by shaneajeffery** [rails/webpacker#3238]
We are using Webpacker v5 and are needing to exclude one directory from being minified during precompile of the assets.

How do you do this?  I know how you do this with Webpack on its own, but I'm not sure how to get to those options under Webpacker.

Thanks in advance for any guidance.

**Comment by justin808** [comment]
@shaneajeffery The easiest way is to use webpack-merge and merge in your changes. Or just modify the config object(s).

Check out my customizations in this directory: https://github.com/shakacode/react_on_rails_tutorial_with_ssr_and_hmr_fast_refresh/tree/master/config/webpack
