### ISSUE TITLE
Cache does not care about dependent environment variables

### ISSUE THREAD

**Issue by Tolsee** [rails/webpacker#3248]
## Problem statement
When we use environment variables like:
```js
function urlPath() {
  if (process.env.DEPLOYMENT_ENV === 'production') {
    return '/prod';
  }
  
  return '/staging';
}
```

Builds with these commands are actually different.
```sh
DEPLOYMENT_ENV=production bin/rails webpacker:compile 
```

```sh
DEPLOYMENT_ENV=development bin/rails webpacker:compile 
```

But, right now webpacker will say "Everything's up-to-date. Nothing to do"

## Possible solution
When calculating digest, add dependent environment variables as well.
https://github.com/rails/webpacker/blob/275fbb56e6b0c837ae4b214a276891558147d861/lib/webpacker/compiler.rb#L54-L61

**Comment by justin808** [comment]
Caching of the bundle creation (i.e., determining if we need to re-run bin/webpack) should really be moved outside of the main development flow, and there should be a way to add additional values to the cache key.

@Tolsee another option could be to have your deployment dirs based a different Rails ENV for production and production_staging, and then configure that in webpacker.yml.

**Comment by justin808** [comment]
Consider not having automatic compilation for production/staging. You should have a build script.
