### ISSUE TITLE
Webpacker 6 Disable Babel

### ISSUE THREAD

**Issue by alexvbush** [rails/webpacker#3255]
How can I disable babel transpiling? I have a typescript application where I'm targeting newer browsers and don't need all the legacy browsers support.

**Comment by justin808** [comment]
This should be configured with the babel.config.js.

Here's an example of how you can override the default setting. You can also create your own, fresh settings:

* https://github.com/shakacode/react_on_rails_tutorial_with_ssr_and_hmr_fast_refresh/blob/master/babel.config.js

Closing in favor of #3155
