### ISSUE TITLE
Webpacker router proxy

### ISSUE THREAD

**Issue by ZackMattor** [rails/webpacker#326]
Hey all! I have a question/suggestion.

I have a remote device that i point to my development server and it would be ideal if webpack dev urls went through the same endpoint as the webpage. This way all asset urls can be relative and we don't need to worry about setting up webpacker to use this new absolute endpoint for its asset urls.

Would it make sense to be able to proxy assets through the rails router? We could have it add this route in development and any requests to `[GET] /packs/:pack_name` would return the correct asset content. I haven't thought through how it could be done for the live reload server...

Just wondering if you folks have thought about this at all!

Best,
Zack

**Comment by ZackMattor** [comment]
Hmm.. just realized it compiles all the packs into the `public` folder so everything should be accessible via a relative path. Also just noticed that some of these variables are set in configuration.js... So i'll just play around with these for a bit and see if i can get what i need.

**Comment by gauravtiwari** [comment]
Sounds good @ZackMattor 👍

**Comment by ZackMattor** [comment]
Ooops! I lied... It only compiles them into `public/packs/pack_name.js` if you run it without the dev server (I had previously run this)! I forgot that the webpack-dev-server runs everything in memory.

**Comment by gauravtiwari** [comment]
@ZackMattor Yepp, that's right. I forgot too 😉 

May be you just want to use the `./bin/webpack --watch --progress` instead of `dev-server` that way you can use rails server url.
