### ISSUE TITLE
Pack missing from the asset pipeline error on Heroku

### ISSUE THREAD

**Issue by Fuffi** [rails/webpacker#327]
I have the latest version of Packer (Rails 5.1), after deploying to Heroku and trying to reach a page I am getting this error

```
ActionView::Template::Error (The asset "mycdn.com/packs/application-a62858b370302422758f.js" is not present in the asset pipeline.):
```

**Comment by gauravtiwari** [comment]
@Fuffi Could you please add CDN url like this for now - `//mycdn.com`.

**Comment by Fuffi** [comment]
@gauravtiwari what we're talking about here is, in production.rb have:

`config.action_controller.asset_host = '//mycdn.com'`

?

**Comment by gauravtiwari** [comment]
that's right 👍

**Comment by gauravtiwari** [comment]
Please try that out

**Comment by Fuffi** [comment]
@gauravtiwari it worked, thanks a lot! Hope it helps figuring out a bug!

**Comment by javan** [comment]
This was fixed in https://github.com/rails/webpacker/pull/397
