### ISSUE TITLE
Can't set a path in entry

### ISSUE THREAD

**Issue by Jakanapes** [rails/webpacker#328]
Trying to move the generated packs files under assets and having some issues.

First, I just changed the output key in paths.yml to public/assets.

This generated the packs directory in the correct location, but then javascript_pack_tag helper was pointing to the wrong directory.

So I reset the output key and set the entry key to assets/packs and am now getting this error

`Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.entry should be one of these:
   object { <key>: non-empty string | [non-empty string] } | non-empty string | [non-empty string] | function
   The entry point(s) of the compilation.
   Details:
    * configuration.entry should NOT have less than 1 properties ({
        "keyword": "minProperties",
        "dataPath": ".entry",
        "schemaPath": "#/oneOf/0/minProperties",
        "params": {
          "limit": 1
        },
        "message": "should NOT have less than 1 properties",
        "schema": 1,
        "parentSchema": {
          "minProperties": 1,
          "additionalProperties": {
            "oneOf": [
              {
                "description": "The string is resolved to a module which is loaded upon startup.",
                "minLength": 1,
                "type": "string"
              },
              {
                "description": "All modules are loaded upon startup. The last one is exported.",
                "$ref": "#/definitions/common.nonEmptyArrayOfUniqueStringValues"
              }
            ]
          },
          "description": "Multiple entry bundles are created. The key is the chunk name. The value can be a string or an array.",
          "type": "object"
        },
        "data": {}
      }).
      object { <key>: non-empty string | [non-empty string] }
      Multiple entry bundles are created. The key is the chunk name. The value can be a string or an array.
    * configuration.entry should be a string.
    * configuration.entry should be an array:
      [non-empty string]
    * configuration.entry should be an instance of function
      function returning an entry object or a promise..`

I could always just update configuration.js, but that's not the right solution.

What am I doing wrong?

**Comment by gauravtiwari** [comment]
@Jakanapes You would also need to move the packs i.e. js entry files to `assets/packs`

**Comment by gauravtiwari** [comment]
You can see an example here - https://github.com/gauravtiwari/webpacker-react-frontend

**Comment by Jakanapes** [comment]
OK, so if I'm understanding correctly, it should look something like this

config: config/webpack
entry: assets/packs
output: public
node_modules: node_modules
source: app
extensions:
  - .js
  - .vue
  - .sass
  - .scss
  - .css
  - .png
  - .svg
  - .gif
  - .jpeg


entry is appended to both source and output when those are used

**Comment by gauravtiwari** [comment]
Yes, that's correct 👍

**Comment by gauravtiwari** [comment]
@Jakanapes My bad, basically you always want to set the source directory to where the javascript app source lives so, in your case - `app/assets` and then within assets you will tell the config where the entries or packs are, which could be any directory where packs resides - `packs`

```yml
config: config/webpack
entry: packs
output: public
node_modules: node_modules
source: app/assets
# or
source: app/frontend
# or 
source: frontend
```
