### ISSUE TITLE
Security Vulnerability in minimist@0.0.8

### ISSUE THREAD

**Issue by nwarwick** [rails/webpacker#3287]
Dependabot notified me about a critical security warning (9.8/10 in terms of severity) in minimist@0.0.8 which is required through the transitive dependency on mkdirp@0.5.1.

<img width="1288" alt="Screen Shot 2022-06-24 at 9 38 07 AM" src="https://user-images.githubusercontent.com/7636254/175547462-4fbf6b27-25ad-42f9-afb3-7a3fd0bc1645.png">

**Comment by rafaelfranca** [comment]
Can't you upgrade in your app? None of the webpacker dependencies force you to use that version of minimist.

**Comment by rafaelfranca** [comment]
Yeah. You definitely can. Nothing in webpacker prevents you to upgrade.
