### ISSUE TITLE
Confusing gem description on RubyGems

### ISSUE THREAD

**Issue by justin808** [rails/webpacker#3307]
@dhh Could we update to mention that Webpacker is retired and the successor is either jsbundling-rails or shakapacker?

```
  s.summary  = "Use webpack to manage app-like JavaScript modules in Rails"
```

![image](https://user-images.githubusercontent.com/1118459/217690438-73f82210-b09f-49ff-bc80-2e0fa1f2f2a9.png)

**Comment by dhh** [comment]
Would require a new release. That doesn't make sense for this to me.
