### ISSUE TITLE
Prefer a Git rebase workflow

### ISSUE THREAD

**Issue by bkuhlmann** [rails/webpacker#331]
## Problem

It would be extremely beneficial to have the Git history preserved in this project by using a Git *rebase* workflow instead of the current *merge* workflow. With the current *merge* workflow the Git commit messages get separated from the files they reference leaving a single merge commit with all of the messages combined as one. This is problematic for several reasons:

0. The context of the Git commit message is lost and no longer related to the files it was intended to describe.
0. Makes it hard for new developers working on this project from being able to use Git to see the history of a single file; understand *why* it was added, updated, or removed; how the file evolved over time; etc.
0. Makes it hard to leverage `git biset` for debugging purposes because a single commit touches multiple files. In larger projects, `git bisect` is valuable in debugging projection issues quickly by narrowing down where the bug was first introduced.
0. A *rebase* workflow keeps the Git history linear and clean. Again, makes debugging with `git bisect` easier too. ...and avoids the dreaded [Guitar Hero](https://twitter.com/henryhoffman/status/694184106440200192?lang=en) of graphical Git log output.

## Solution

The fix for this is to update the project option settings as shown here:

![options](https://cloud.githubusercontent.com/assets/50245/25773558/780b84dc-323c-11e7-940d-c2516fe65bb7.png)

**Comment by matthewd** [comment]
You seem to mostly be complaining about squashes, not merges.

I see no need to disable merge types to force my fellow maintainers to use your preferred one. I personally prefer merge commits -- but I would've just asked you to manually squash the commits in #324 instead, so that wouldn't've gained much. ¯\\\_(ツ)\_/¯
