### ISSUE TITLE
How to render webpack output into erb.js view template?

### ISSUE THREAD

**Issue by christophermlne** [rails/webpacker#334]
My use case is I need to serve a React application to third-party sites.

I provide a script tag which my users can embed in their webpages, which then loads a script asynchronously which I provide through a js.erb view template. I would like to convert from my vanilla js app to something React based, but I haven't been able to figure out how to include the webpacker output in my js.erb template with the provided helper functions.

Any ideas on how I could do this?

I've tried `<%= render :partial => asset_pack_path('myscript.js')` %> but this doesn't work because the file is not a partial from ActionView's perspective.

I've also tried to reach the file content with `<%= IO.binread(asset_pack_path('myscript.js')) %>` but that fails because the file does not exist (I don't understand this, but for now I'm assuming this has to do with the order that things are rendered in the asset pipeline because i can visit the asset_pack_path url in my browser).

**Comment by christophermlne** [comment]
i'm wondering if i just need to move my vanilla js app code out of the view template and into the packs directory, and render the js directly from the controller?

**Comment by christophermlne** [comment]
closing as i now realize this gem won't work for what I'm trying to do

**Comment by ytbryan** [comment]
Maybe you would want to serve it through an iframe? Tho, you might need to check the browser compatibility and other issues with this approach.

**Comment by christophermlne** [comment]
thanks for the suggestion @ytbryan. an iframe is certainly one option. i'm trying to avoid it though.

i was in fact able to get this gem to work. i ended up using my view template to do some initialization work while fetching the compiled assets from the server. when the assets (ie the React app) are loaded i proceed with the rest of the 'boot'. i had to attach a class to the window object so that the app could be instantiated from the view template script.

so i'm incurring an extra trip to the server but that's a compromise i'm willing to make to finally have the power of web components ;-)

**Comment by brmi** [comment]
@christophermlne Do you mind sharing what you did to get the compiled assets from the server? I am in the same boat as you were in when you posted this question.
