### ISSUE TITLE
React + Turbolinks = Warning: unmountComponentAtNode()

### ISSUE THREAD

**Issue by iamraffe** [rails/webpacker#336]
Howdy!

I am getting this warning while using with React & Turbolinks:

> Warning: unmountComponentAtNode(): The node you're attempting to unmount was rendered by another copy of React.

I have checked all over ~~Google~~ the web and can't seem to make it work. The solution that seems to work for most people doesn't work for me:

```
function mountComponent(){
  ReactDOM.render(
    <Hello name="React" />,
    document.getElementById('app'),
  )
}

function unmountComponent(){
  ReactDOM.unmountComponentAtNode(document.getElementById('app'))
}

document.addEventListener('turbolinks:load', mountComponent, {once: true})
document.addEventListener('turbolinks:render', mountComponent)
document.addEventListener('turbolinks:before-render', unmountComponent)
```

I also tried this one:

```
document.addEventListener('turbolinks:load', mountComponent)
document.addEventListener('turbolinks:before-cache', unmountComponent)
```

No luck so far. Any suggestions?

**Comment by gauravtiwari** [comment]
@iamraffe Are you using multiple packs? Or a single pack for all components?

**Comment by iamraffe** [comment]
I am piggybacking on the hello_react.js stub that seems to be default when installing via command upon new project creation (`rails new app --webpack=react --force`)

Here's a link to my repo, in case you want to take a closer look  https://github.com/iamraffe/webpacker-example-app

**Comment by Mavvie** [comment]
Consider using [webpacker-react](https://github.com/renchap/webpacker-react) instead? 

I was able to fix this issue by adding the following listener:

```js
$(document).on('turbolinks:before-cache', () => WebpackerReact.unmountComponents())
```

**Comment by iamraffe** [comment]
@Mavvie thanks for offering your $0.02, I thought this was dead.

I think I would probably want to avoid using another gem _just to avoid_ getting this warning.

I think I would prefer to check out why that gem has solved it and try to solve it that way myself, or at least get an idea of how I would go about it.

Looking at the code, all that specific function does is the following:
```


  unmountComponents() {

    const mounted = document.querySelectorAll(`[${CLASS_ATTRIBUTE_NAME}]`)

    for (let i = 0; i < mounted.length; i += 1) {

      ReactDOM.unmountComponentAtNode(mounted[i])

    }

  }



```

So in theory it looks like it is doing the same thing?

**Comment by Mavvie** [comment]
Hmm, I agree that what you're doing looks equivalent. I'm not really an expert on Turbolinks or React, but maybe webpacker-react mounts the components in a different way? Or you could try storing the "original" React in a local, and use that original one in the unmount function.

**Comment by renchap** [comment]
You can have a look at the PR where @sevos implemented Turbolinks support in webpacker-react here: https://github.com/renchap/webpacker-react/pull/14

Specifically this comment: https://github.com/renchap/webpacker-react/pull/14#issuecomment-282500093

**Comment by kensupermen** [comment]
I have the same issue and when disable turbolinks everything ok.
Edit config turbolinks at `app/assets/javascripts/application.js` like this:
```javascript
//= xxxrequire turbolinks
```
