### ISSUE TITLE
extractCSS in vue-loader does not work for sass and scss styles

### ISSUE THREAD

**Issue by morr** [rails/webpacker#340]
Bug of #310 PR

Video http://take.ms/a7Pe2 (30sec)

This code generates css files
```html
<style scoped>
p {
  font-size: 2em;
  text-align: center;
  color: red;
}
</style>
```

This code does not generate css files
```html
<style scoped lang="scss">
p {
  font-size: 2em;
  text-align: center;
  color: red;
}
</style>
```
Example project (just generated new rails app and added webpacker to it) https://github.com/morr/rails-webpacker-vue-loader

**Comment by gauravtiwari** [comment]
@morr Want to make a PR for this? I think this needs adding explicit loaders per - https://github.com/vuejs/vue-loader/blob/master/docs/en/configurations/extract-css.md

**Comment by inopinatus** [comment]
Not sure this is fixed, or perhaps there is a regression? My test repo for SCSS at https://github.com/inopinatus/vue-scss-webpacker does not emit CSS files.

**Comment by inopinatus** [comment]
Update: thanks to Chris @ Gorails.com who diagnosed this for me.
This PR set `const extractStyles = false` in `loader/vue.js`, which breaks `stylesheet_pack_tag`.

**Comment by gauravtiwari** [comment]
@inopinatus Ahh yes, probably this option needs to be configurable based on env.

**Comment by sealocal** [comment]
If `extractStyles` is (or will be) configurable in `vue.js`, should it also be configurable in `react.js`?

**Comment by gauravtiwari** [comment]
@sealocal Yes that's the plan actually 😉

**Comment by inopinatus** [comment]
I am getting an intermittent "Uncaught TypeError: inherits is not a function" with subcomponents when `extractStyles = true`.

**Comment by gauravtiwari** [comment]
@inopinatus We will disable the `stylesheet_pack_tag` as well in development so it will return `nil`
