### ISSUE TITLE
`javascript_pack_tag` still refers to localhost with `rails assets:precompile`

### ISSUE THREAD

**Issue by yftang** [rails/webpacker#343]
I manually precompiled the assets by `rails assets:precompile`, after hitting `RAILS_ENV=production rails s`, puma server starts up
```
▶ RAILS_ENV=production rails s
=> Booting Puma
=> Rails 5.1.0 application starting in production on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.8.2 (ruby 2.4.1-p111), codename: Sassy Salamander

* Min threads: 5, max threads: 5
* Environment: production
* Listening on tcp://0.0.0.0:3000
Use Ctrl-C to stop
```
But `<%= javascript_pack_tag 'customers' %>` still refers to `<script src="http://localhost:8080/packs/customers.js"></script>` which cost errors.

**Comment by gauravtiwari** [comment]
Did you prepend RAILS_ENV with assets:precompile too? RAILS_ENV=production bundle exec rails assets:precompile

**Comment by yftang** [comment]
Oh, I forgot this. Silly question.
Thanks anyway and I'm closing this.

**Comment by javierojeda94** [comment]
Did add `RAILS_ENV=production` to the command solved the issue?

**Comment by gauravtiwari** [comment]
@javierojeda94 Yes, should solve the issue or `NODE_ENV=production bundle exec rails webpacker:compile`
