### ISSUE TITLE
Including template files with require

### ISSUE THREAD

**Issue by jlebrech** [rails/webpacker#345]
I'm moving a frontend written in AngularJS and i'm trying to use `ngtemplate-loader` but there are errors.

this is the configuration i've tried:

var path = require('path');

```
module.exports = {
    test: /\.html$/,
    loaders: [`ngtemplate?relativeTo=${path.join(__dirname, "/app")}`, "html"] //html?attrs[]=div:ng-include
}
```

But i'm getting this problem

```
Module not found: Error: Can't resolve 'html' in '/Users/joe/testrails5.1/app/javascript/app/scripts'
resolve 'html' in '/Users/joe/testrails5.1/app/javascript/app/scripts'
  Parsed request is a module
```

Could we have an example the uses `ngtemplate-loader` with appropriate config?

This can be for angular 2+ as it should try work for legacy angularjs.

My current working code uses "gulp-angular-templatecache" to do the same thing.

Should I move the view files into rails views (i see some advantages to this) or keep using `ngtemplate-loader` and keep the views in the javascripts folder?

**Comment by jlebrech** [comment]
I can now require html text from javascript with the following config:

var path = require('path');

```
module.exports = {
    test: /\.html$/,
    loader: "html-loader"
}
```

I'm still figuring out how to use webpack with ngtemplate-loader for ng-includes.

**Comment by gauravtiwari** [comment]
@jlebrech I think you are using wrong path - 

```
const { paths } = require('../configuration')

module.exports = {
    test: /\.html$/,
    loaders: [`ngtemplate?relativeTo=${path.resolve(paths.source, 'templates'}/!html`]
}
```

where templates live in for ex - `app/javascript/templates/*`

**Comment by jlebrech** [comment]
I've managed to import templates but as my code is in ES5 the code generated by webpack has dependency problems and the only thing I can see is to convert my code to ES6, unless there's a webpack module that's aware of this problem.

**Comment by gauravtiwari** [comment]
Great 👍  Didn't fully understand the second part. What issues are you facing when compiling your code?

**Comment by jlebrech** [comment]
Webpack cannot resolve dependencies, it needs a 1.5+ config for ngInject (i've tried many different loaders to no avail) or needs to be converted to ES6 for webpack to figure out dependencies

**Comment by gauravtiwari** [comment]
@jlebrech Ahh right. In that case, I think this isn't related to webpacker :) Not sure how else we can help here. Closing this one for now.
