### ISSUE TITLE
path to resource in node_modules folder

### ISSUE THREAD

**Issue by krazyjakee** [rails/webpacker#347]
How do I something like:
`asset_pack_path("bootstrap/dist/bootstrap.css")`

where the bootstrap folder is in the node_modules folder?

**Comment by gauravtiwari** [comment]
@krazyjakee You can't do that with Webpacker. One way is to link that file within the main pack bundle like so,

```js
// packs/application.js
import 'bootstrap/dist/bootstrap.css'
```

or you could do it with common chunk - https://webpack.js.org/plugins/commons-chunk-plugin/

**Comment by krazyjakee** [comment]
Using
```
import "react-rails-ujs/dist/react-rails-ujs.js"
```
I get
```
ERROR in ./~/react-rails-ujs/dist/react-rails-ujs.js
Module build failed: Error: Couldn't find preset "es2015" relative to directory "/Users/*/WebApp/node_modules/react-rails-ujs"
```

**Comment by gauravtiwari** [comment]
You would need to install es2015 preset `yarn add babel-preset-es2015`

**Comment by krazyjakee** [comment]
Thanks, that fixes the compilation issue but rails just gives me "Can't find react-rails-ujs/dist/react-rails-ujs.js".

**Comment by krazyjakee** [comment]
My mistake that was calling from elsewhere. Thanks!
