### ISSUE TITLE
Simple css import from node_modules

### ISSUE THREAD

**Issue by ulugbekov** [rails/webpacker#349]
First we add yarn add font-awesome
Then
In the app/javasctipts/packs/application.scss

@import "font-awesome";

Can not locate? Why?

Thanks

**Comment by gauravtiwari** [comment]
@ulugbekov For CSS you need to import exact file from `font-awesome` module 

```js
// Something like this, check node_modules/font-awesome folder
import 'font-awesome/css/font-awesome.css'
```

**Comment by krazyjakee** [comment]
I have the same issue with javascript. No matter where I put this exact import, it will not appear in my manifest.

**Comment by gauravtiwari** [comment]
Here you go, for example if you put the line in `hello_vue.js` pack you will get `hello_vue.css`

![screen shot 2017-05-09 at 14 00 27](https://cloud.githubusercontent.com/assets/771039/25852043/f5d0bb8c-34bf-11e7-8d8a-8c22a59a1639.png)
![screen shot 2017-05-09 at 14 00 39](https://cloud.githubusercontent.com/assets/771039/25852046/f7c958cc-34bf-11e7-8e90-b142e3c53075.png)
![screen shot 2017-05-09 at 14 00 19](https://cloud.githubusercontent.com/assets/771039/25852047/f996aaba-34bf-11e7-808f-5a416f83a599.png)

**Comment by wtfiwtz** [comment]
In `app/javascripts/packs/application.sass` I had to put a `~` in to pick up the file from `node_modules/`:

`@import '~font-awesome/css/font-awesome'`

**Comment by gauravtiwari** [comment]
@wtfiwtz Yes that's correct - so in JS file you don't need to put `~` but in sass or scss you have add a ~.

**Comment by fernandes** [comment]
@gauravtiwari just commenting to say thank you! your example helped me here!

**Comment by hundsim** [comment]
For anyone else coming here that need to import `normalize.css` in .scss-file, this is what worked for me:

`@import "~normalize.css";`

Note a couple of things:
1. The semi-colon
2. No pre-fixing of folder name

**Comment by ViggoV** [comment]
I've had no luck with any of these solutions. Locally it works with `@import 'codemirror/lib/codemirror.css'` but not with `~`.

After deployment, though, all css imported from node_modules subfolders is missing from the output folder.

**Comment by reichertm** [comment]
If you have upgraded your app from an earlier version of Rails make sure you add the following line: `Rails.application.config.assets.paths << Rails.root.join('node_modules')` in `config/initializers/assets.rb`. This is included by default in the newly generated apps.

Then in `app/javascripts/packs/application.sass` the following should do the job: 
`@import 'font-awesome/css/font-awesome';` (no `~` and no file extension)
