### ISSUE TITLE
Default to es2017

### ISSUE THREAD

**Issue by dhh** [rails/webpacker#35]
Let's give the people async/await by default (and the other es2017 goodies).

**Comment by guilleiguaran** [comment]
Done in af320768eb5dfe8

**Comment by abouthiroppy** [comment]
Cool 😄

**Comment by flybayer** [comment]
Async/await is not working for me in version 1.2 without installing and loading [babel-polyfill](https://babeljs.io/docs/usage/polyfill/)

Should I create a new issue or do you want to reopen this one?

**Comment by gauravtiwari** [comment]
@flybayer What version of node you got?

**Comment by flybayer** [comment]
Node 7.10.0

**Comment by gauravtiwari** [comment]
thanks, and you got .babelrc with `env` preset?

**Comment by flybayer** [comment]
I should have added the error I get in the Browser console without babel-polyfill:
```
Uncaught ReferenceError: regeneratorRuntime is not defined
```

My `.babelrc`:
```json
{
  "presets": [
    ["env", {"modules": false}]
  ],
  "plugins": [
    "transform-object-rest-spread",
  ],
}
```

**Comment by gauravtiwari** [comment]
Please would need to use this option - https://github.com/babel/babel-preset-env#usebuiltins-boolean and please checkout this issue - https://github.com/babel/babel-preset-env/issues/92

**Comment by gauravtiwari** [comment]
I guess something like this would work, please give it a go - 

```json
    "presets": [
      [
        "env",
        {
          "targets": {
            "node": "current"
          },
          "useBuiltIns": true
        }
      ]
    ]
```

**Comment by gauravtiwari** [comment]
We should probably update `.babelrc` 

```json
{
  "presets": [
    ["env", {
      "modules": false,
      "targets": {
        "node": "current"
      },
      "useBuiltIns": true
    }]
  ]
}
```

**Comment by flybayer** [comment]
This works perfect!! (without `babel-polyfill`). Thank you @gauravtiwari !!
```json
{
  "presets": [
    ["env", {
      "modules": false,
      "targets": {
        "node": "current"
      },
      "useBuiltIns": true
    }]
  ]
}
```

**Comment by flybayer** [comment]
So this changed worked fine until I tried to run in production mode which results in uglify failing because of ES6/7 syntax (see #306).

I'm now back to using `babel-polyfill` and:

```json
{
  "presets": [
    ["env", {
      "modules": false,
      "targets": {
        "node": "current",
        "uglify": true
      },
      "useBuiltIns": true
    }]
  ]
}
```

**Comment by gauravtiwari** [comment]
Lets document this in README @flybayer as this depends on the use case

**Comment by MiguelSavignano** [comment]
in webpacker (3.2.0)
Add the babel plugin transform-runtime

npm install babel-plugin-transform-runtime
```
{
  "presets": [
    [
      "env",
      {
        "modules": false,
        "targets": {
          "browsers": "> 1%",
          "uglify": true
        },
        "useBuiltIns": true
      }
    ]
  ],
  "plugins": [
    "syntax-dynamic-import",
    "transform-object-rest-spread",
    "transform-runtime",
    [
      "transform-class-properties",
      {
        "spec": true
      }
    ]
  ]
}
```

**Comment by nathanbirrell** [comment]
Thanks @MiguelSavignano. This solved the `Uncaught ReferenceError: regeneratorRuntime is not defined` issue for me too.
