### ISSUE TITLE
Elm doesn't work "out of the box"

### ISSUE THREAD

**Issue by joshuaclayton** [rails/webpacker#351]
Hi!

I recently tried out the new Elm support introduced by @bkuhlmann (thank you so much for this!) and found it didn't work directly out of the box. I created a [GitHub repo](https://github.com/joshuaclayton/rails_elm_webpacker_heroku_example_app) demonstrating the steps I had to take, but one of the more confusing ones was [adding the `.elm` extension to the JS import](https://github.com/joshuaclayton/rails_elm_webpacker_heroku_example_app/commit/a45ee7d6303655a064dd5c6f6162cc821b7aa6c7). Another alternative would be to [add `.elm` to the list of extensions supported by Webpack](https://github.com/joshuaclayton/rails_elm_webpacker_heroku_example_app/commit/cf20c6f301602e042be16caaa601f761bd80d231).

Is there a "right solution" in this case? I'm leaning towards the latter, but wanted to get some feedback.

In either case, does it make sense to adjust `hello_elm.js`, adding the extension, or update `elm.rb`'s generated output to remind developers to add the `.elm` extension to the list? I'm happy to help here!

**Comment by gauravtiwari** [comment]
@joshuaclayton Hey, I think .elm is already in the extensions list. Did you re-run `webpacker:install` to replace paths.yml?
 - https://github.com/rails/webpacker/blob/master/lib/install/config/webpack/paths.yml

**Comment by joshuaclayton** [comment]
@gauravtiwari aha, it is! Re-running it added it in correctly. Does it make sense to let users know to do that, or automate it somehow?

**Comment by bkuhlmann** [comment]
@joshuaclayton Thanks, glad you are making use of it. :)

@gauravtiwari is correct, the `.elm` extension is added to the `paths.yml` so you'll get that.

@joshuaclayton Thanks for putting together the demo repo. Your commit history was extremely valuable (especially the commit message bodies). The reason why you were not able to get the code you needed for a good first experience is between your [first](https://github.com/joshuaclayton/rails_elm_webpacker_heroku_example_app/commit/a67bd9926e6cc6cad085f5f792513891a3d85804) and [second](https://github.com/joshuaclayton/rails_elm_webpacker_heroku_example_app/commit/7baf14f8e78d0a50a553fd544934572f5508aadd) commit. In the first commit you were still using the old Webpacker gem (not Elm-enhanced). This is why you didn't get the updated `paths.yml`. By the time you got to the second commit, you had the latest version of the gem, but I'm afraid you only got the Elm specific bits but missed the common support in the base gem.

**Comment by joshuaclayton** [comment]
@bkuhlmann aha, that makes sense! Possible to have `webpack:install:X` each have a prerequisite of `webpack:install`, or maybe additional documentation around the few steps it takes to set things up?

**Comment by bkuhlmann** [comment]
@joshuaclayton Yeah, it would be possible to keep all of this contained within the Elm-specific support. I'll issue a fix for this because your use case proves that there is potential for someone to have a bad experience.

@gauravtiwari This might be something to double check with the React, Vue, Angular support as well. I think they suffer the same issue.

**Comment by joshuaclayton** [comment]
@bkuhlmann thank you! Happy to help where I can, too. It wasn't a *bad* experience, per se, just a bit confusing about where to look when things weren't working as expected. I was a bit giddy seeing Elm support added and couldn't contain myself 😄

**Comment by bkuhlmann** [comment]
@joshuaclayton Elm does have that effect. :)

**Comment by gauravtiwari** [comment]
@bkuhlmann Thanks for addressing this in #356

**Comment by aried3r** [comment]
> Did you re-run `webpacker:install` to replace paths.yml?

I know this is stated in the README as well as the CHANGELOG, but what do you think about a [post install message](http://brandonhilkert.com/blog/ruby-gem-post-install-message/)? webpacker is, after all, one of very few (in my case the only one) gems that require running a command after updating.

**Comment by dklima** [comment]
I keep getting:

```
$ rails webpacker:install:elm
rails aborted!
Don't know how to build task 'webpacker:install:elm' (see --tasks)
/usr/local/lib/ruby/gems/2.4.0/gems/railties-5.1.0/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'
/usr/local/lib/ruby/gems/2.4.0/gems/railties-5.1.0/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/usr/local/lib/ruby/gems/2.4.0/gems/railties-5.1.0/lib/rails/command.rb:46:in `invoke'
/usr/local/lib/ruby/gems/2.4.0/gems/railties-5.1.0/lib/rails/commands.rb:16:in `<top (required)>'
...
```

**Comment by dklima** [comment]
Solved by adding: 
`gem 'webpacker', git: 'https://github.com/rails/webpacker.git'` to `Gemfile`.

I think next gem version will solve this problem with webpacker 1.2.
