### ISSUE TITLE
Running tests doesn't set NODE_ENV=test

### ISSUE THREAD

**Issue by RobinClowers** [rails/webpacker#353]
When I run tests with `bin/rails test`, it fails unless I'm running the webpack dev server. Is this expected?

**Comment by gauravtiwari** [comment]
@RobinClowers You would need to compile packs before running tests - `NODE_ENV=test ./bin/webpack`. Are you getting `somefile` not found error when running tests?

**Comment by RobinClowers** [comment]
Yeah, that's exactly right, and `NODE_ENV=test ./bin/webpack` does sort it out. I feel like the readme could really use a section breaking down how the manifests are used and options for how to run tests locally vs CI.

**Comment by gauravtiwari** [comment]
@RobinClowers Yepp. There are two PR's pending to address some of these things - #341 and #292

**Comment by RobinClowers** [comment]
@gauravtiwari is there an easy way to use the dev server for tests locally, but use precompiled assets on CI?

**Comment by gauravtiwari** [comment]
@RobinClowers What issues are you facing? You can run dev server locally in a separate terminal and then run tests, which would work just fine as it will use dev server to serve assets. For CI, you can pre-compile `NODE_ENV=test ./bin/webpack` before running tests (much like assets:precompile).

**Comment by RobinClowers** [comment]
@gauravtiwari oh I see, for some reason I thought it would only use the test assets, that does indeed work. Thanks!
