### ISSUE TITLE
Can't install webpack in Travis CI

### ISSUE THREAD

**Issue by jlpereira** [rails/webpacker#357]
Hi

I'm trying to compile the assets to run the tests on Travis but when I try to do it I get this error.

> Compiling webpacker assets 🎉
sh: 1: ./bin/webpack: not found

The obvious reason probably is I should do rake webpacker:install
The problem with this is that I can not start this task because when it encounters conflict with the files it needs confirmation from the user to proceed, so Travis will be left waiting without doing anything.

Is there a way to install it in an unattended manner so that it does not replace any files? Or some way to install only the bin files

Btw, we're running Rails 4.2

Thanks!

**Comment by mfazekas** [comment]
./bin/webpack is something to be checked into your git repo. You don't want to run `webpacker:install` also make sure proper node, yarn is installed in your travis env.

**Comment by jlpereira** [comment]
@mfazekas thank you so much for your fast answer, and yes. That works. I removed the bin folder from gitignore to upload those and now is compiling... I think is okay this way

Thanks again!
