### ISSUE TITLE
Asset path not correct in production with asset_host

### ISSUE THREAD

**Issue by zinkkrysty** [rails/webpacker#358]
Instead of `https://assets.autouncle.com/packs/au_logo-ca819eb380d16ccacaa27b58bf6de9b3.png` the link becomes `https://packs/au_logo-ca819eb380d16ccacaa27b58bf6de9b3.png` in production.

I am referencing the asset from `.jsx`:
```js
import auLogo from './au_logo.png'
```

```jsx
<img
  className={styles.auLogo}
  src={auLogo}
  alt="React is alive!"
/>
```

CSS and JS assets work as they should though.

![image](https://cloud.githubusercontent.com/assets/570771/25895845/eb5bda66-3581-11e7-99aa-19528a5081db.png)

My manifest.json looks like this in production:
```json
{
  "application.js": "/packs/application-e59ce04015f5c4805038.js",
  "au_logo.png": "/packs/au_logo-ca819eb380d16ccacaa27b58bf6de9b3.png",
  "hello_react.css": "/packs/hello_react-e4f8b7143d6099d4ae0d.css",
  "hello_react.js": "/packs/hello_react-05621acfe18a877fb479.js",
  "react.svg": "/packs/react-4009eef3b3e291f296e71962c70895c5.svg"
}
```

I am using this assets.js webpack config:

```js
const Url = require('url-parse')
const { env, paths, publicPath } = require('../configuration.js')

// Make sure host has slashes
const ensureSlashes = ({ host, slashes }) => {
  if (slashes) { return `${host}/${paths.entry}/` }
  return `//${host}/${paths.entry}/`
}

// Compute path for internal pack assets if ASSET_HOST is supplied
const computeAssetPath = (host) => {
  if (!host) { return `/${paths.entry}/` }
  return ensureSlashes(new Url(host))
}

// Get asset options based on NODE_ENV
const assetOptions = (nodeENV) => {
  if (nodeENV === 'production') {
    return { publicPath: computeAssetPath(env.ASSET_HOST), name: '[name]-[hash].[ext]' }
  }
  return { publicPath, name: '[name].[ext]' }
}

module.exports = {
  test: /\.(jpg|jpeg|png|gif|svg|eot|ttf|woff|woff2)$/i,
  use: [{
    loader: 'file-loader',
    options: assetOptions(env.NODE_ENV)
  }]
}
```

**Comment by gauravtiwari** [comment]
@zinkkrysty One small change you have to fix - Please use the updated code - https://github.com/gauravtiwari/webpacker/blob/28279eab44be336469b4bef56023ee61233c9ddc/lib/install/config/loaders/core/assets.js

You are using host in the `ensureSlashes` method, change it to href please 👍

**Comment by zinkkrysty** [comment]
Oh I missed that @gauravtiwari , thanks! I am trying it out now :)

**Comment by gauravtiwari** [comment]
No worries, thanks. You would need to recompile the assets 😄  (unless on heroku)

**Comment by zinkkrysty** [comment]
Works! Thanks for help

**Comment by rezadhah** [comment]
so do we need to add this code from https://github.com/gauravtiwari/webpacker/blob/28279eab44be336469b4bef56023ee61233c9ddc/lib/install/config/loaders/core/assets.js to webpacker loader config?
