### ISSUE TITLE
Using Webpacker inside Docker container (Mac vs Windows)

### ISSUE THREAD

**Issue by johnbeynon** [rails/webpacker#359]
So I'd like to detail an issue I'm experiencing, I'm not sure where the problem lies but I want to share it with you in the hope that someone has an idea.

I run a rails Rails 5.1 inside a docker container, I've adjusted webpack-dev-server to run on 0.0.0.0 and I've exposed port 8080 to the host so that requests via the `javascript_pack_tag` are able to succeed. Looking at the source the pack URLs are http://0.0.0.0:8080/.... This works entirely as expected on OSX and the packs load.

The problem comes when using this container on a Windows host. The problem is that 0.0.0.0 isn't routable on Windows so the URLs for the pack are written as http://0.0.0.0:8080 but on Windows that won't load, if I manually change the URL to localhost then the packs load.

any ideas?

**Comment by gauravtiwari** [comment]
@johnbeynon You could set the host to localhost on windows machine or you need both setup working at the same time?  - there is development.server.yml

You can even pass inline args to dev-server binstub (--host localhost)

**Comment by johnbeynon** [comment]
I've tried playing with the configs. The webpack-dev-server needs to be running on 0.0.0.0 in the container so it's accessible from the host, but the paths that get written via the helper need to be configurable to localhost. Saying that, it seems like the helper just reads them from the manifest so the question becomes, How can I run the dev-server on 0.0.0.0 but have the paths written localhost.

Maybe?
.

**Comment by johnbeynon** [comment]
Figured out a possible workaround,

in the webpack\configuration.js, instead of 

`const devServerUrl = http://${devServer.host}:${devServer.port}/${paths.entry}/`

I've changed it to:

`const devServerUrl = http://localhost:${devServer.port}/${paths.entry}/`

that seems to work as it let's the server run on the devServer host specified value, 0.0.0.0 but the manifest gets written using localhost.

**Comment by gauravtiwari** [comment]
Ahh right. You could perhaps keep the config as is and reverse - development.server.yml to have host as localhost and then when running `webpack-dev-server` you can pass the `--host` argument inline which will override the config option. 

```
./bin/webpack-dev-server --host 0.0.0.0
```

![screen shot 2017-05-10 at 17 24 03](https://cloud.githubusercontent.com/assets/771039/25909565/7e7c7ddc-35a5-11e7-9c0e-07810d366741.png)
