### ISSUE TITLE
webpacker is installed... ./bin/webpack: not found

### ISSUE THREAD

**Issue by christophermlne** [rails/webpacker#379]
I'm not sure how to interpret this error that I get when trying to precompile assets on the server.
1) webpacker is installed
2) but webpack is not found
3) A JSON text must at least contain two octets! (thanks but which JSON file?)

```
app@vagrant:/var/www/app/application$ bundle exec rake assets:precompile
Webpacker is installed 🎉 🍰
Using /var/www/app/application/config/webpack/paths.yml file for setting up webpack paths
Compiling webpacker assets 🎉
sh: 1: ./bin/webpack: not found
rake aborted!
JSON::ParserError: A JSON text must at least contain two octets!
/home/app/.rbenv/versions/2.3.1/bin/bundle:23:in `load'
/home/app/.rbenv/versions/2.3.1/bin/bundle:23:in `<main>'
Tasks: TOP => webpacker:compile
(See full trace by running task with --trace)
```

**Comment by btc** [comment]
Perhaps you need `yarn global add webpack`

**Comment by christophermlne** [comment]
@btc i just tried your suggestion but unfortunately it didn't work. i get the same error.

this line https://github.com/rails/webpacker/blob/master/lib/tasks/webpacker/compile.rake#L11
is allowed to execute after `webpacker:verify_install` succeeds. i'm wondering if `webpacker:verify_install` ought to have failed here, since a working webpack installation doesn't seem to be present? (even though i can run 'webpack' in the terminal and it works)

**Comment by ytbryan** [comment]
Are you using rails 5? I think it's because you are lacking the binstub `webpack` in your bin folder.

**Comment by christophermlne** [comment]
@ytbryan you are right. i have a bin folder on my local machine but not on the remote server.

my webpacker version is 1.2

**Comment by christophermlne** [comment]
i ran `bundle exec bin/rails app:update:bin` and so now i have a bin folder.

i still get the same error though.

**Comment by christophermlne** [comment]
the issue was caused by the bin folder not being present, and updating the .gitignore file and redeploying fixed it.

**Comment by raldred** [comment]
What the solution for getting the webpack binstubs? in a rails 5.0.2 app? same as OP can't upgrade to 5.1 yet. 
no ./bin in gitignore 
`bundle exec bin/rails app:update:bin` runs no ./bin/webpack
`rails webpacker:install:react` errors `Webpack binstubs not found.`

**Comment by ytbryan** [comment]
@raldred Did you run `rails webpacker:install` ? Which version of webpacker are you using?

**Comment by raldred** [comment]
Doh. I guess I assumed `webpacker:install:react` would bootstrap it all. Sorry for wasting your time.

**Comment by TangMonk** [comment]
@raldred , same problem, I am assumed webpacker:install:react would auto generate all config files

**Comment by kevgathuku** [comment]
I also experienced this issue while trying to add webpacker to an existing rails app.
The solution I used was to runn the `webpacker:install`script first
Then after that was done, I ran `webpacker:install:react` which added the files I needed.

Trying to run `webpacker:install:react` first caused the error that brought me here in the first place 😄

**Comment by kwerle** [comment]
Running rails 4.2.  I also had to 
`rake webpacker:install`
before
`rake webpacker:install:vue`

**Comment by daryllxd** [comment]
I had this problem (`.bin/webpack not found`), but I think I had a different case. Turns out I wasn't `npm install`ing the webpack commands. I added `capistrano-npm` to my deploy process and it works. Might help someone

**Comment by Hazelwu2** [comment]
I also has the same problem, and I reinstall

>  rails webpacker:install 

many time >"<

**Comment by thanhtruong1216** [comment]
I also having the issues.

**Comment by AntonAL** [comment]
**Install webpack manually on your server:**

1. Add `webpack` to package.json – `yarn add webpack webpack-cli`;
2. In your server go to a folder of current release, that was failed and do `yarn`:
```sh
cd /var/www/your_project/releases/your_release_timestamp
yarn
```
3. Try to deploy – `bundle exec cap production deploy`
