### ISSUE TITLE
should rake task `webpacker:verify_install` fail if `./bin/webpack` is not present?

### ISSUE THREAD

**Issue by christophermlne** [rails/webpacker#380]
currently it does not.

discovered in https://github.com/rails/webpacker/issues/379

please feel free to close if this is the intended behaviour.

**Comment by ytbryan** [comment]
Thanks for filing this. How did you "install" your webpacker? Using `rails webpacker:install`? Or did you manually move those configuration files? 

Because I find it strange that the binstub `./bin/webpack` aren't installed in the first place. cc @gauravtiwari
