### ISSUE TITLE
Missing pathMake from elm-webpack-loader

### ISSUE THREAD

**Issue by gauravtiwari** [rails/webpacker#383]
@bkuhlmann Just tried elm support and it seems that loader can't access `elm-make` file when installed locally with `yarn`.

```
hvw00000gn/T/117413-10953-10rs2tp.wpu82xogvi.js
Could not find Elm compiler "elm-make". Is it installed?
```

After adding `pathMake` to loader config, it works. 

```js
const path = require('path')
const { env } = require('../configuration.js')

const elmSource = path.resolve(process.cwd())

const loaderOptions = () => {
  if (env.NODE_ENV === 'production') {
    return `elm-webpack-loader?cwd=${elmSource}&pathToMake=${elmSource}/node_modules/.bin/elm-make`
  }

  return `elm-hot-loader!elm-webpack-loader?cwd=${elmSource}&verbose=true&warn=true&debug=true&pathToMake=${elmSource}/node_modules/.bin/elm-make`
}

module.exports = {
  test: /\.elm$/,
  exclude: [/elm-stuff/, /node_modules/],
  loader: loaderOptions()
}

```

**Comment by bkuhlmann** [comment]
@gauravtiwari I'm not able to reproduce locally. Here are my steps:

```
brew uninstall elm # <-- I have to do this step first since I like to have Elm installed globally.
cd ~/scratch
git clone https://github.com/rails/webpacker.git
cd webpacker
bundle exec rake install
cd ~/scratch
rails new demo --webpack=elm
cd demo
rails s
bin/webpack-dev-server # <-- Run in a second terminal
```

Also, if I run the following within the `demo` app directory:

`yarn elm make`

I get the following output:

```
yarn elm-make v0.23.4
$ "~/scratch/demo/node_modules/.bin/elm-make"
Success! Compiled 0 modules.
✨  Done in 0.25s.
```

It is weird to see that only 0 modules are compiled, though.

**Comment by bkuhlmann** [comment]
Opps, forgot to add the source path when running `elm make`. Here is what you'd want to run:

`yarn elm make app/javascript/packs/**/*.elm`

...and now the resulting output looks better:

```
yarn elm v0.23.4
$ "~/scratch/demo/node_modules/.bin/elm" make app/javascript/packs/Main.elm
Success! Compiled 1 module.
Successfully generated index.html
✨  Done in 0.42s.
```

Now we see that one module id compiled (i.e. `Main.elm`).

**Comment by gauravtiwari** [comment]
Ahh I see. But does this work with `./bin/webpack`?

**Comment by bkuhlmann** [comment]
Thanks. Yes, I see the same error now. That's a bit a bummer but your solution above works. Should we add a new variable to make the solution a little easier to read? Example:

```
const elmMake = `${elmSource}/node_modules/.bin/elm-make`
```

**Comment by gauravtiwari** [comment]
@bkuhlmann Yepp, worked for me for the first time, but not sure what happened afterwards.There is a `node_modules` option in paths.yml which we can resolve to, but lets not use that. 

The above looks good 👍

**Comment by bkuhlmann** [comment]
ok, [PR](https://github.com/rails/webpacker/pull/393) is ready.
