### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by waleedarshad** [rails/webpacker#386]
These are my routes

When i use without index routes it work fine but when i use index routes routes i get error of maximum call stack. why?. i am asking here because of the issues referred to webpack configuration as compared to react-router

	<Router history={history}>
		<Route path="/" component={Home}>
			<IndexRedirect to="/" /> // Causing error

			<Route path="about" component={About} />
			<Route path="signup" component={SignUp} />
			<Route path="*" component={NotFound} />
		</Route>
		
	</Router>

        	<Router history={history}>
                             <Route path="/" component={Home}>
                                  <Route path="about" component={About} />
                                  <Route path="signup" component={SignUp}/>
                                   <Route path="*" component={NotFound} />
                             </Route>
                        </Router>

**Comment by gauravtiwari** [comment]
@waleedarshad Why are using `IndexRedirect`? Seems like multiple route matches causing router to go into infinite loop and ultimately exhausting the memory stack. May be you wanna checkout react router docs. 

Closing, unrelated to webpacker 👍

**Comment by waleedarshad** [comment]
Thanks
