### ISSUE TITLE
Missing SourceMaps for CSS in Development

### ISSUE THREAD

**Issue by dpuscher** [rails/webpacker#390]
I am using CSS modules in my react project which works quite well out of the box using webpacker. The only problem are the SourceMaps. In production everything is working well, but not so in development.

In production, webpack is generating `*.css`, `*.css.gz` and `*.css.map` when using
```
devtool: "source-map",
plugins: [
  new webpack.optimize.UglifyJsPlugin({
    sourceMap: true
  }),
  ...
```
in `config/webpack/production.js`.

In development I am using a different devtool setting, since "source-map" is too slow ([Documentation](https://webpack.js.org/configuration/devtool/))
```
devtool: "cheap-module-eval-source-map",
``` 
which works fine for JS-files (adding `sourceMappingURL=data:application/json;charset=utf-8;base64...` at the end of each module).
But it is sadly not working for my css/sass files...

Here my `sass` loader configuration:
```
const ExtractTextPlugin = require("extract-text-webpack-plugin");
const { dev } = require("../configuration.js");

module.exports = {
  test: /\.(scss|sass)$/i,
  use: ExtractTextPlugin.extract({
    fallback: "style-loader",
    use: [
      {
        loader: "css-loader",
        options: {
          modules: true,
          sourceMap: true,
          camelCase: "only",
          minimize: !dev && {
            autoprefixer: {
              browsers: ["> 1%", "last 2 versions", "IE > 9"],
              add: true
            }
          }
        }
      }, {
        loader: "sass-loader",
        options: {
          sourceMap: true,
          indentedSyntax: true
        }
      }
    ]
  })
};
```

**Comment by gauravtiwari** [comment]
@dpuscher Were you able to get this to work? Sorry for late response.

**Comment by dpuscher** [comment]
@gauravtiwari No, I couldn't get it to work... Do you have any idea?

**Comment by gauravtiwari** [comment]
@dpuscher Seems to be working for me with this setup - 

```js
// sass.js loader
const ExtractTextPlugin = require('extract-text-webpack-plugin')
const { env } = require('../configuration.js')

module.exports = {
  test: /\.(scss|sass|css)$/i,
  use: ExtractTextPlugin.extract({
    fallback: 'style-loader',
    use: [
      { loader: 'css-loader', options: { minimize: env.NODE_ENV === 'production', sourceMap: true } },
      { loader: 'postcss-loader', options: { sourceMap: true } },
      'resolve-url-loader',
      { loader: 'sass-loader', options: { sourceMap: true } }
    ]
  })
}
```
```js
// development.js
module.exports = merge(sharedConfig, {
  devtool: 'source-map',

```

![screen shot 2017-06-21 at 19 09 52](https://user-images.githubusercontent.com/771039/27399606-3e853f6c-56b5-11e7-9b3a-32bb2ab9acc8.png)

**Comment by dpuscher** [comment]
@gauravtiwari Thank you, the only problem was setting the devtool to `cheap-eval-source-map`. `source-map` and `cheap-source-map` work without a problem. 🙂
