### ISSUE TITLE
Assets are always served from localhost:8080

### ISSUE THREAD

**Issue by catskull** [rails/webpacker#396]
I have an app running in a staging/production environment, but it's trying to load assets from localhost:8080. How can I convince webpacker that I'm not in the dev environment?

**Comment by gauravtiwari** [comment]
Just set NODE_ENV to production 👍

**Comment by gauravtiwari** [comment]
or disable development server from `development.server.yml`

**Comment by catskull** [comment]
Thanks, I edited my .bash_profile to `export NODE_ENV=production` and in `development.server.yml` enabled is false for the production section, but still no luck.

**Comment by gauravtiwari** [comment]
You would need to define a staging environment in `development.server.yml`. Also, are you sure NODE_ENV is set to production on your staging environment?

**Comment by catskull** [comment]
Yeah, I fired up rails console on my staging server, and did `ENV["NODE_ENV"]` and it returned production.

UPDATE: Aghhhhh. Figured it out. We use capistrano for deploys. Someone recently added capistrano-faster-assets which doesn't run `assets:precompile` unless it thinks it needs to. I guess capistrano-faster-assets and webpacker don't play nicely.

**Comment by gauravtiwari** [comment]
Ahh, right. Great 👍 

No, don't think so it's made for sprockets I think.
