### ISSUE TITLE
Add and config test/test_helper.rb to the project

### ISSUE THREAD

**Issue by dayvsonlima** [rails/webpacker#4]

**Comment by dhh** [comment]
What test_helper.rb?

**Comment by dayvsonlima** [comment]
The intention is to allow the use of unit tests

**Comment by dhh** [comment]
Unit test of this plugin or of the JavaScript?

**Comment by dayvsonlima** [comment]
For this plugin

**Comment by matthewd** [comment]
A PR to add some tests would be welcome.. but we don't take feature requests as issues.
