### ISSUE TITLE
Angular CLI compatibility

### ISSUE THREAD

**Issue by berga** [rails/webpacker#400]
It would be great to use the CLI to generate angular components inside a rails app as happen with rails generators.

Since now I've been able to (starting from a fresh Rails 5.1.1 project):

- [X] integrate a generated cli project pointing src root to app/javascript[/packs] 
- [X] adjust the webpack config to use external html and css files generated from CLI
- [X] compile frontend in development
- [X] generate components using CLI 
- [ ] test production env
- [ ] add AOT to webpack
- [ ] wrap ng CLI to a rails generator (optional but cool) 

I'm wondering if it would be possible to enhance _webpacker:install_ 
to generate an Angular CLI compatible structure ready to work, 
an hello_word example a little bit more complex (with separated html and css) or take it out to a another gem, something like angular_rails_cli wrapping/using webpacker?

**Comment by gauravtiwari** [comment]
@berga Sounds like a good idea to start a companion webpacker gem with some installers - `webpacker-angular` that provided these advanced features plus automatic mounting using helpers - `<%= angular_component('Home') %>` inside views.

**Comment by returnlytom** [comment]
@berga Started implementing this on my own, then found your PR. Is there anything you would like help with?

**Comment by berga** [comment]
hi @returnlytom, I'me a bit late on it, I could push a bare gem structure, can you help me building it?

**Comment by returnlytom** [comment]
@berga Go ahead and push what you got, we can work on it collaboratively

**Comment by gauravtiwari** [comment]
Closing this - Feel free to make a PR for README once this is ready 👍

**Comment by jakehockey10** [comment]
Did this ever happen?

**Comment by TylerRick** [comment]
Has anyone added this feature yet?

**Comment by TylerRick** [comment]
To be able to use `ng generate` to generate new components, etc., and `ng test` to run tests for Angular components...

This would be huge for those using Angular.

**Comment by berga** [comment]
> @berga Go ahead and push what you got, we can work on it collaboratively

I'm sorry @returnlytom, I've abandoned too early the "monolytical" approach 
in favour of 2 levels separated app: rails api + angular front,
btw I could try to resume some dusty code
