### ISSUE TITLE
Extra node_modules directory was created during installation

### ISSUE THREAD

**Issue by effect305** [rails/webpacker#401]
I have a couple of directories in assets called `app`, like `project_name/app/assets/javascript/something/something/source/app`. And during `rails webpacker:install` there were created two `node_modules` directories, one in the `project_name/app` and in one of I mentioned above.

**Comment by ytbryan** [comment]
I'm not able to duplicate this error on rails `Rails 5.1.1`, webpacker master branch and macOS 10.12.4.

**Comment by effect305** [comment]
I've tried once again and could not replicate too. So it must be single fault.
