### ISSUE TITLE
Disable HMR in Dev? 

### ISSUE THREAD

**Issue by relativityboy** [rails/webpacker#404]
The app I'm writing really doesn't work well with HMR in develop. I need to disable it, but setting 

~~~javascript
{
   devServer: {
      hot:false
  }
}
~~~

In webpack/development.js or webpack/development.server.js has no effect. HMR is still running. There are no other instances of the word 'hot' in config/webpack ... what to do?

**Comment by gauravtiwari** [comment]
You mean live reloading on change? HMR isn't enabled by default.

**Comment by relativityboy** [comment]
Seems to be in the latest GEM. Anytime I mod a js file I get reloads on the client.

**Comment by gauravtiwari** [comment]
@relativityboy Yepp that's live reloading which is enabled by default in dev server.  Yes, you can always use just watcher in case you don't want dev server at all 👍

**Comment by gnapse** [comment]
How do you use `webpack --watch`. Running that command just like that does not work for me.

**Comment by gauravtiwari** [comment]
@gnapse `./bin/webpack --watch --progress --colors`

**Comment by relativityboy** [comment]
@gauravtiwari took a while to respond. For posterity:

I'd thought HMR & live reloading were essentially the same thing. I wanted both off. 

Looks like webpack 2 supports turning off live reload with " --no-inline" is that right? And, is it supported in 3?
