### ISSUE TITLE
Manchester Bombing 

### ISSUE THREAD

**Issue by ytbryan** [rails/webpacker#406]
Man, sending my regards to you, @gauravtiwari 

Saw your comment and knew you are safe. Webpacker can't do without you haha. Stay safe! 

Background: https://www.theguardian.com/uk-news/2017/may/22/manchester-arena-police-explosion-ariana-grande-concert-england

**Comment by gauravtiwari** [comment]
Bryan, thanks man ❤️  I am good 

Neither without you, thanks for helping out so far. You too  👍
