### ISSUE TITLE
Rails dependency

### ISSUE THREAD

**Issue by gckwan** [rails/webpacker#407]
The README claims support for Rails 4.2+, but it also says "It's designed to work with Rails 5.1+." I'm running 4.2.8, and when I try to run `rails webpacker:install`, I get `Error: Command 'webpacker:install' not recognized`. Is 4.2 no longer supported?

**Comment by gauravtiwari** [comment]
@gckwan You would need to use `bundle exec rake webpacker:install` instead. Let me know if that works

**Comment by gckwan** [comment]
That works, thanks!
