### ISSUE TITLE
How to use ejs?

### ISSUE THREAD

**Issue by airblade** [rails/webpacker#408]
Hello!

I am using webpacker without the asset pipeline on a new Rails 5.1.1 app.

I want to use [ejs](https://github.com/mde/ejs) for javascript templates but I cannot figure out how to get it to work.

This is what I tried:

- `$ yarn add ejs`
- `$ yarn add ejs-compiled-loader`
- In config/webpack/paths.yml I added `.ejs` to the list of `extensions`.
- In config/webpack/loaders/ I added a file `ejs.js`:

      module.exports = {
        test: /\.ejs$/,
        loader: 'ejs-compiled'
      }

- At the top of the javascript file where I want to render a template, I added `const ejs = require('ejs');`.

This gives the webpack error:

```
WARNING in ./~/ejs/lib/ejs.js
require.extensions is not supported by webpack. Use a loader instead.

WARNING in ./~/ejs/lib/ejs.js
374:11-18 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/ejs/lib/ejs.js
375:2-9 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

ERROR in ./~/ejs/lib/ejs.js
Module not found: Error: Can't resolve 'fs' in '/Users/andy/business/doubleagent/webapp/node_modules/ejs/lib'
 @ ./~/ejs/lib/ejs.js 16:9-22
```

Weirdly I now have a package.json and a yarn.lock file alongside my javascript files in  #app/javascript/application/`.

Please could somebody point me in the right direction?

Thanks!

**Comment by airblade** [comment]
I guess the problem is `fs` isn't available in a browser environment.

I know the asset pipeline has JST templating built in.  Is it possible to replicate that in webpacker?

**Comment by gauravtiwari** [comment]
Andy haven't used `ejs` with webpack before so don't know much. How is your app setup around `ejs`?

**Comment by p0wl** [comment]
I guess you don't need to require `ejs` itself, because the loader will handle the compiling of `.ejs` files automatically.

So when you want to render a template, just require the template and use it (see https://github.com/bazilio91/ejs-compiled-loader#usage).

Webpack will parse the template and transpile it using ejs during the build.

(I could be wrong, I have no experience with ejs, just read the docs of https://github.com/bazilio91/ejs-compiled-loader)

**Comment by airblade** [comment]
@p0wl Thanks to your comment I got it working like this:

- `yarn add ejs-compiled-loader`
- In config/webpack/paths.yml I added `.ejs` to the list of `extensions` (optional but allows me to omit the file extension when loading templates)
- In config/webpack/loaders/ I added a file `ejs.js`:

      module.exports = {
        test: /\.ejs$/,
        loader: 'ejs-compiled-loader'
      }

- When I want to use a template, say foo.ejs, I do this:

      const template = require('./foo');
      const output = template();

- That's it.

**Comment by StefH** [comment]
For my Vue.js project (https://github.com/StefH/Nethereum-CodeGenerator) I had to use `ejs-compiled-loader-webpack4`.
