### ISSUE TITLE
how about using uploaded manifest?

### ISSUE THREAD

**Issue by iguchi1124** [rails/webpacker#412]
I develop rails application with webpacker, and the application provides on AWS.

I want to use manifest.json which is in the asset host because I want to deploy `public/assets` and `public/packs` to AWS S3 by using ECS task.

But now, manifest.json loads only under local application directory, and asset paths decided at running asset precompe tasks. I think this behavior is different from default asset precompile / resolve asset paths flow.

So, I propose some solutions

1. fix to load from uploaded manifest if asset_host parameter was provided
1. fix manifest.json values not to include asset host, and javascript_pack_tag helper considers asset_host paramerters

What do you think? I'd like to send a patch if you like.

**Comment by gauravtiwari** [comment]
@iguchi1124 You mean you have local development URL's inside manifest.json? Could you post how is your current manifest.json and how you would like it to look please?

**Comment by iguchi1124** [comment]
@gauravtiwari 

My application running on docker image, and I want to use same image on staging and production environment.

e.g. 

### production environment
```console
$ ASSET_HOST=http://production.example.com rails assets:precompile
$ rails assets:deploy # deploy public/packs to s3 bucket
```

manifest.json at `http://production.example.com/packs/manifest.json`
```json
{
  "application.js": "http://production.example.com/packs/application.js"
}
```

### staging environment
```console
$ ASSET_HOST=http://staging.example.com rails assets:precompile
$ rails assets:deploy # deploy public/packs to s3 bucket
```

manifest.json at `http://staging.example.com/packs/manifest.json`
```json
{
  "application.js": "http://staging.example.com/packs/application.js"
}
```

So, I want to load uploaded manifest.json from application code.

**Comment by gauravtiwari** [comment]
@iguchi1124 Are you looking for this task?

`RAILS_ENV=production bundle exec rails webpacker:compile`
`RAILS_ENV=staging bundle exec rails webpacker:compile`
OR
`NODE_ENV=production bundle exec rails webpacker:compile`

This will include different asset host urls based on env config.

**Comment by gauravtiwari** [comment]
Sorry I haven't fully understood the problem :)

**Comment by iguchi1124** [comment]
I'm sorry for my bad explanation :bow:

I want to divide assets upload process and application deploy process for each environment.
And I don't want to use `Rails.application.root.join('public', 'packs', 'manifest.json')` on production and staging.

another example:
```console
$ RAILS_ENV=staging rails assets:precompile assets:deploy # assets deploy
$ RAILS_ENV=production rails assets:precompile assets:deploy

$ bundle exec cap staging deploy # don't  precompile and upload assets
$ bundle exec cap production deploy 
```

**Comment by iguchi1124** [comment]
I expected production server that does not have a public directory.

**Comment by Gargron** [comment]
I think I understand the described issue/use case.

For example, I run a cluster of 4 app servers. Only one of those lives on the same hardware as the load balancer, which would serve the static assets. Currently, I need to compile the assets on every app server separately (and hope to god that it's deterministic and the hashes are the same in each generated manifest, otherwise I need to sync the manifest file between all servers manually).

This could be avoided if each app server would use the one manifest.json served by the load balancer (ASSET_HOST) instead of looking into its own public/packs folder. Then I would only need to compile on that server.

**Comment by gauravtiwari** [comment]
Please see this comment as potential solution:  https://github.com/rails/webpacker/issues/618#issuecomment-322062852
