### ISSUE TITLE
Misc questions about config extension

### ISSUE THREAD

**Issue by chrisvfritz** [rails/webpacker#42]
I'm building in Vue support now and have run into a couple questions:

### 1. Supporting Vue's single-file components

Vue's [single-file components](https://vuejs.org/v2/guide/single-file-components.html) include a very useful feature to automatically scope CSS, but I saw that CSS and image support in webpacker has been intentionally left out for now. Does that mean you'd just like to keep it out of the _default_ config? In other words, would it still be a welcome addition in an installer? Without `css-loader` or `file-loader`, the basic functionality of `.vue` files will still work - they'd simply throw an error if a user tried to add a `<style>` tag or provide a relative link for an image in a `<template>`.

On a related note, would it be possible to share more of the reasoning behind leaving out CSS and image support? I see everything-is-a-module as Webpack's primary feature and it actually doesn't take very much for very basic CSS and image support ([for example](https://github.com/vuejs-templates/webpack-simple/blob/master/template/webpack.config.js)).

### 2. Out-of-the-box support for `.jsx` extensions

As I can't imagine a strategy for JSX support that wouldn't involve Babel, I was wondering if the `.jsx` extension should be matched (but not supported) out of the box. My thinking is it will save installers from having to patch that matcher, plus the resulting syntax error would point users closer to the actual problem than a module-not-found error. This is also the strategy preferred by some other libraries, [such as webpack-blocks](https://github.com/andywer/webpack-blocks/blob/b6c2145db05597f59b9691fed6a6afe3a7b48b59/packages/core/src/defaultFileTypes.js#L3). Thoughts?

### 3. Alternative strategies for patching the Webpack config

I'm a bit uncomfortable with the string replacement strategy currently used to extend the Webpack config. It seems like it would be quite brittle. Instead of using rake tasks to patch that file, what would you think about introducing a config file that the Webpack config could read to patch itself? It might look something like:

``` yml
babel:
  min_stage: 3

vue:
  jsx: true
  single_file_components: true
```

A rake task could still be used to generate an example (and perhaps also check to ensure that the features in the example are activated).

I'm not married to this specific strategy. Any other ideas to make config extension more sustainable are very welcome!

**Comment by chrisvfritz** [comment]
If @TheLarkInn has time, he probably has some better ideas regarding 3, perhaps having seen and aided with integrations in projects similar to Rails.

**Comment by TheLarkInn** [comment]
I'm a bit biased but I'd say expose the webpack compiler just as it's created or the options just before it's created. That way the options json/object could be modified and completely customizable.

**Comment by dhh** [comment]
Chris, I'd like to leave these installs for the bare minimum. They're a starting point, not an end point. So I'd rather we not get too sophisticated. It's fine to have additional plugins that provide that.

As far as babel goes, I'd like to be as progressive as we can. Let's bring the cutting edge to the floor. I've been enjoying class properties and decorators, for example.

With JSX, that would still need us to have all the React stuff available. So don't see the advantage of offering that without React as well? But maybe I'm misunderstanding.

**Comment by chrisvfritz** [comment]
@dhh Thanks for the clarification. It sounds like real Vue support (anything beyond the JSX) will probably not be possible with Webpacker then, as we really do need to be able to input and output more than just JS files. For others reading this, you can see [these Vue integrations](https://github.com/chrisvfritz/rails-javascript-integrations) for multiple working strategies for integrating Vue into Rails.

As for JSX, I was thinking we could support the extension out-of-the-box without supporting the syntax. Then integration for the various flavors of JSX would simpler to integrate and prior to handling the syntax, users would see better errors. It's not super important though.
