### ISSUE TITLE
Any alternatives for rails asset-data-url helper?

### ISSUE THREAD

**Issue by suhomozgy-andrey** [rails/webpacker#423]
I upload my images to app/javascript/packs/images and it's alright when I use asset_pack_path from views. But also I want to style elements from sass files like this: 

```
&::after
    ...
    background: url('nika_co.png')
    ...
```

Is anybody could help me? Do I need to write new loader or I can use some helpers like asset_pack_path. Is there any alternatives for rails asset-data-url helper?

**Comment by gauravtiwari** [comment]
@suhomozgy-andrey This should work out of the box if it's referenced correctly - https://github.com/gauravtiwari/webpacker-example-app/blob/master/app/assets/javascript/counter/styles/style.sass#L35

**Comment by gauravtiwari** [comment]
and the demo is here - https://webpacker-example-app.herokuapp.com/
