### ISSUE TITLE
.\bin\webpack-dev-server doesn't work on windows 10

### ISSUE THREAD

**Issue by krishnalr** [rails/webpacker#437]
After I created a project with "rails new myapp --webpack" command, then I tried to run ".\bin\webpack-dev-server". But, every time I get ERROR: '.' is not recognized as an internal or external command.

Then I tried with bin\webpacker-dev-server. But I got webpacker-dev-server is not recognized as internal or external command.

How to run webpacker within rails on windows 10 system?

**Comment by lucygliang** [comment]
Just went through the same thing. Run "ruby .\bin\webpack-dev-server"

You might have to also modify config\webpacker.yml and change "host: 0.0.0.0" to "host: 127.0.0.1"

**Comment by krishnalr** [comment]
It worked, thank you so much Lucy. Config files for webpack seems different for Windows and OS X, How do you manage them on git?

**Comment by ytbryan** [comment]
would you like to close this if it's non-issue? I think you can raise a separate issue if you have question or further problem.

**Comment by lucygliang** [comment]
Sorry @krishnalr I missed your reply. I haven't had much problems with them so far other than the one issue with the host addr.
