### ISSUE TITLE
Server side rendering (SSR) with Vue

### ISSUE THREAD

**Issue by kieraneglin** [rails/webpacker#438]
I'm using webpacker with Vue and I'm not using the Rails view layer and using vue-router instead.

The problem is that Google isn't crawling my page correctly.  I've found that the answer is SSR, but it doesn't look like there's webpacker support at this time.  

Is there a plan to include SSR support?  And until then, is there a recommended plan of attack to overcome this issue?

**Comment by renchap** [comment]
GogoleBot renders Javascript fine for at least a year. They use Chromium derivative to render webpages and it works fine (as long at it loads in < 4 seconds from what I remember).
Have you looked into Google Webmaster tools for errors? You can also check how GoogleBot sees your page.

Some research on the topic: http://searchengineland.com/tested-googlebot-crawls-javascript-heres-learned-220157

**Comment by kieraneglin** [comment]
I've checked my webmaster login and logs.  It looks like nginx is responding with a 499, but only when google crawls the site.  Looks like this is unrelated
