### ISSUE TITLE
Add option to skip overriding `assets:` tasks

### ISSUE THREAD

**Issue by mipearson** [rails/webpacker#440]
Hi,

I'm looking at moving our application off of my gem webpack-rails and on to webpacker and also writing a guide for others to do so, with the intention of sunsetting webpack-rails.

Our application builds the sprockets assets and webpack assets separately. By doing so, we can do some clever caching to avoid having to build our webpack assets (which takes ~40s in CI) on every CI build. I'd like to preserve this behaviour.

I'd like to submit a pull request to add an option to `config/webpacker.yml`  that disables the `Rake::Task[*].enhance` calls in webpacker.

Would this be acceptable?

**Comment by mipearson** [comment]
This would also offer a workaround for #405.

**Comment by mipearson** [comment]
Really janky, hopefully temporary workaround:

```ruby
%w{assets:clobber assets:precompile}.each do |task_name|
  Rake::Task[task_name].instance_eval do
    @actions.reject! { |action| action.source_location[0] =~ /webpacker/ }
  end
end
```

**Comment by ytbryan** [comment]
I think you should write that PR. Thanks for taking time to look at this.

**Comment by gauravtiwari** [comment]
@mipearson Feel free to make a PR when you get a chance and we can take look together 👍
