### ISSUE TITLE
Linking Styles not working for me.

### ISSUE THREAD

**Issue by vitalyliber** [rails/webpacker#446]
I used webpacker (1.2) with Rails 5.1 and tryed "linking styles" by instructions in the Readme, but I haven't success.

Styles haven't applyed for the React component.

Please, give any advise.

_app/javascript/main/pages/login_

```
import React, {Component} from 'react'
import '../styles/login.sass'

export default class Login extends Component {
  render(){
    return(
      <div className="account">
        <p>Hello</p>
      </div>
    )
  }
}
```
_app/javascript/main/styles/login.sass_

```
.account
  color: red
  padding: 20px
  font-size: 12px
  background-color: #1c2324
```

**Comment by gauravtiwari** [comment]
Could you please check your manifest.json and see what css files is being outputted? It's generally `[pack_name].css`

**Comment by vitalyliber** [comment]
@gauravtiwari I have this text in manifest.json
```
{
  "application.js": "http://0.0.0.0:8080/packs/application.js",
  "hello_react.js": "http://0.0.0.0:8080/packs/hello_react.js",
  "main.css": "http://0.0.0.0:8080/packs/main.css",
  "main.js": "http://0.0.0.0:8080/packs/main.js"
}
```
Also in 'view' I use only `= stylesheet_pack_tag 'main'`.

**Comment by gauravtiwari** [comment]
You would also need to add `<%= stylesheet_pack_tag 'main' %>`

**Comment by vitalyliber** [comment]
@gauravtiwari thanks. It is work.
But I used this part of readme. 

![screenshot from 2017-05-30 17-21-33](https://cloud.githubusercontent.com/assets/8033090/26580878/3e2eb424-4564-11e7-9be4-07062a6a164c.png)

Seems I don't should to use `<%= stylesheet_pack_tag 'main' %>`.

May be I'm wrong.

**Comment by gauravtiwari** [comment]
@vitalyliber It's documented just below that section - https://github.com/rails/webpacker#inside-views.

**Comment by xijo** [comment]
@gauravtiwari I just stumbled about the exact same issue, maybe we could emphasise this fact a bit in order to reduce future confusion?

**Comment by ajsharp** [comment]
@gauravtiwari This seems like a bug. I'm also following the exact instructions from "Within your JS app", including a sass stylesheet and an image. The image gets loaded fine and rendered correctly, the styles do not. If I print the styles to console, it returns an empty object.

It's also worth noting that inlining styles in this way can be very useful for hot reloading, which does not work for stylesheets linked from the pack stylesheet.

**Comment by ajsharp** [comment]
Upon further investigation, this appears to be an issue with the default webpacker sass configuration, which uses the `ExtractTextPlugin` in two places: [shared.js](https://github.com/rails/webpacker/blob/2b0972a0df158c1614c5c30e591c657813f1f904/lib/install/config/webpack/shared.js#L40) and [sass.js](https://github.com/rails/webpacker/blob/2b0972a0df158c1614c5c30e591c657813f1f904/lib/install/config/loaders/core/sass.js#L9).

If I comment out the plugin line in `shared.js` and change the configuration to this in `sass.js`, it works:

```js
module.exports = {
  test: /\.(scss|sass|css)$/i,
  use: [
    { loader: 'style-loader' },
    { loader: 'css-loader', options: { minimize: env.NODE_ENV === 'production' } },
    { loader: 'postcss-loader', options: { sourceMap: true } },
    'resolve-url-loader',
    { loader: 'sass-loader', options: { sourceMap: true } }
  ]
}
```

Obviously, this is not ideal for a production environment, but allows having css hot reloading in development.

**Comment by gauravtiwari** [comment]
Hey @ajsharp Yepp, waiting on a PR to me made for HMR which will restructure few of these bits - hopefully in next few days :)
