### ISSUE TITLE
How can I get image from the sass file in component?

### ISSUE THREAD

**Issue by vitalyliber** [rails/webpacker#447]
Hello!

I have a sass file in component folder `app/javascript/main/styles/login.sass`.

I want to add background image to body

```
body
  background-image: image_url('background.png')
```
But the link which I got with helper is broken: `image_url(../images/background.png);`

In manifest.json I see the different link: 
`"background.png": "http://0.0.0.0:8080/packs/background.png"`

Please, help me.

**Comment by guilleiguaran** [comment]
Try using `asset_pack_path('background.png')`

**Comment by vitalyliber** [comment]
@guilleiguaran Unfortunately the helper 'asset_pack_path' doesn't work.

```
body
  background-image: asset_pack_path('background.png')
```

![screenshot from 2017-05-31 11-27-56](https://cloud.githubusercontent.com/assets/8033090/26615880/866c404a-45f4-11e7-960f-0140125d537e.png)

**Comment by gauravtiwari** [comment]
Ohh that's a view helper - please just use normal sass code - url(). Just make sure relative path is correct and it should work.

**Comment by suhomozgy-andrey** [comment]
@vitalyliber I asked the same question here https://github.com/rails/webpacker/issues/423

**Comment by gauravtiwari** [comment]
Were you able to get it to work @suhomozgy-andrey ?

**Comment by gauravtiwari** [comment]
Looks like this isn't a problem anymore. Feel free to re-open 👍
