### ISSUE TITLE
Heroku crashes when trying to deploy with Webpacker 2.0

### ISSUE THREAD

**Issue by pbmarcano** [rails/webpacker#451]
Was just struggling for a second trying to deploy an updated version of my app with Webpacker 2.0.

Right when assets were precompiling and yarn was being installed, I got a time out.

This happened twice in a row with Webpacker 2.0, but it deployed flawlessly when I downgraded back to 1.2.

Is this a bizarre error or am I overlooking something?

``` 
...      
       Removing railties (5.1.0)
       Removing activerecord (5.1.0)
       Removing actionview (5.1.0)
       Removing devise (a62faa2c8258)
-----> Installing node-v6.10.0-linux-x64
-----> Installing yarn-0.22.0
 !
 !     Command: 'set -o pipefail; curl -L --fail --retry 5 --retry-delay 1 --connect-timeout 3 --max-time 30 https://yarnpkg.com/downloads/0.22.0/yarn-v0.22.0.tar.gz -s -o - | tar zxf - dist' failed unexpectedly:
 !     
 !     gzip: stdin: unexpected end of file
 !     tar: Child returned status 1
 !     tar: Error is not recoverable: exiting now
 !
/app/tmp/buildpacks/f6d48d8a14fccbb19c0c0402fca224929d18e9ee042b3e204bc5992612e990d3b3a0fb1f9627b1a3bae11e9fa20dffc96e136bd734a2f3cf92a0d05bedd42cfe/lib/language_pack/shell_helpers.rb:49:in `run!': Command: 'set -o pipefail; curl -L --fail --retry 5 --retry-delay 1 --connect-timeout 3 --max-time 30 https://yarnpkg.com/downloads/0.22.0/yarn-v0.22.0.tar.gz -s -o - | tar zxf - dist' failed unexpectedly: (LanguagePack::Fetcher::FetchError)
gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
...
```

**Comment by gauravtiwari** [comment]
@pbmarcano From logs it seems like heroku fails to install yarn (perhaps an intermittent network problem). Doesn't seem like it's related to webpacker though 👍

**Comment by pbmarcano** [comment]
All I know is that downgrading webpacker to 1.2 solved the issue - yarn installed fine. When I upgraded again to 2.0 it failed to install again...

Could just be heroku gremlins making me think it's related 🙄

**Comment by ytbryan** [comment]
@schneems  can we get a second opinion from you on this?

**Comment by raldred** [comment]
I wonder if it's an issue with the heroku region or particular instance your app is running on.
I have deployed a rails 5.0.2 app with webpacker today to a fresh EU heroku app, yarn installs without issue.

An obvious difference is Heroku installs yarn 0.24.5 for me.

```
-----> Installing binaries
       engines.node (package.json):  6.9.5
       engines.npm (package.json):   unspecified (use default)
       
       Downloading and installing node 6.9.5...
       Using default npm version: 3.10.10
       Resolving yarn version (latest) via semver.io...
       Downloading and installing yarn (0.24.5)...
       Installed yarn 0.24.5
```

**Comment by fabn** [comment]
Likely related to this https://status.heroku.com/incidents/1169

**Comment by gauravtiwari** [comment]
thanks @fabn 👍  Closing this since it's unrelated
