### ISSUE TITLE
Hard dependency on yarn.

### ISSUE THREAD

**Issue by gdborton** [rails/webpacker#452]
Our build machines are locked down pretty tightly and we aren't able to globally install packages. Would it be possible to use (or fallback to?) npm which is standard and ships w/ node.

If not, would you be open to expanding webpacker to enable usage of a locally installed copy of yarn? `./node_modules/.bin/yarn`

**Comment by ljharb** [comment]
It would be great if this was configurable; npm 5's release drastically alters the landscape for yarn, and it would be a mistake for rails to cement itself nonconfigurably onto a tool that may or may not be the best choice in years to come.

**Comment by gauravtiwari** [comment]
@gdborton Feel free to make a PR please 👍  May be @ljharb have some more ideas around how to make it configuration?

@ljharb Makes sense but I guess at this point we have pick one since both are very similar tools. It would be nice to move away though and leave this option to user 😄

**Comment by ljharb** [comment]
If you only have to pick one, pick the standard one that ships with node. That said, making it configurable with either default seems like the proper path :-)

**Comment by dhh** [comment]
Webpacker is going to follow what we're doing in Rails. If Rails moves to provide an alternative to Yarn, we'll piggyback off that. But we're not going to chart a separate path in Webpacker.
