### ISSUE TITLE
Cannot import modules with non-relative imports

### ISSUE THREAD

**Issue by zoras** [rails/webpacker#454]
I'm trying to use [Material Components Web (MDC-Web)](https://material.io/components/web/) but with no success.

The given example in [webpacker README](https://github.com/rails/webpacker#from-node-modules-folder) works for single file with non-relative imports within like:

`@import '~@material/animation/mdc-animation.scss' // works fine`

However it fails when I try to import whole MDC as suggested in https://yarnpkg.com/en/package/material-components-web

```(bash)
// app-styles.sass
@import "~material-components-web/material-components-web"

// console
Module build failed:
    @import "@material/animation/mdc-animation";
    ^
          File to import not found or unreadable: @material/animation/mdc-animation.
    Parent style sheet: /project_root/node_modules/material-components-web/material-components-web.scss
          in /project_root/node_modules/material-components-web/material-components-web.scss (line 17, column 1)
```

In /project_root/node_modules/material-components-web/material-components-web.scss (line 17, column 1)
`@import "@material/animation/mdc-animation";`

This doesn't seem to work whenever there is a non-relative import within the sass file being imported.

```[bash]
// app-styles.sass
@import "~@material/button/mdc-button"

// console
Module build failed:
    @import "@material/animation/variables";
    ^
          File to import not found or unreadable: @material/animation/variables.
    Parent style sheet: /project_root/node_modules/@material/button/mdc-button.scss
          in /project_root/node_modules/@material/button/mdc-button.scss (line 17, column 1)
```

In /project_root/node_modules/@material/button/mdc-button.scss (line 17, column 1)
`@import "@material/animation/variables";`

I tried tweaking things using below reources but couldn't figure it out.
https://webpack.js.org/configuration/resolve/
https://yarnpkg.com/en/package/module-alias

Related: https://stackoverflow.com/q/43187195

**Comment by gauravtiwari** [comment]
Please use dist - `@import "~material-components-web/dist/material-components-web"`

I think there is a bug with library, those files are not there:

![screen shot 2017-06-02 at 11 15 18](https://cloud.githubusercontent.com/assets/771039/26721830/5253bdf0-4785-11e7-8e24-6244bb950419.png)

**Comment by zoras** [comment]
@gauravtiwari Those files are there within `node_modules/@material` along with `node_modules/material-components-web` directory. 

```(bash)
❯ ls node_modules | grep material
@material
material-components-web
```

`material-components-web` creates a separate folder named `@material` and stores various components within it as subfolders.

<img width="1108" alt="screen shot 2017-06-02 at 4 53 29 pm" src="https://cloud.githubusercontent.com/assets/365783/26723459/599b4fcc-47b4-11e7-9ca7-3df335828d78.png">

**Comment by gauravtiwari** [comment]
@zoras Ahh that's why. You see, `sass-loader` needs a `~` in the beginning to understand that a particular file is using a node_modules import. Since `material-components-web` doesn't respect that unfortunately it's not possible - https://github.com/webpack-contrib/sass-loader#imports

The main file is referenced correctly but not the children modules. Another solution would be to import this inside `.js` file and see if that works?

`import 'material-components-web/material-components-web'`

**Comment by zoras** [comment]
@gauravtiwari nop, it didn't work and throws same error.

```(bash)
// in app/javascript/packs/application.js
import 'material-components-web/material-components-web'

// console
Module build failed:
@import "@material/animation/mdc-animation";
^
      File to import not found or unreadable: @material/animation/mdc-animation.
Parent style sheet: stdin
      in /project_root/node_modules/material-components-web/material-components-web.scss (line 17, column 1)
 @ ./~/material-components-web/material-components-web.scss 4:14-201
 @ ./app/javascript/packs/application.js

```

Is there any way to rewrite or tell `sass-loader` to check in `~` or `node_modules` directory by default?

**Comment by gauravtiwari** [comment]
@zoras Don't think that's easily possible. Have you figured it out yet? Perhaps you may want to open an issue on `material-components-web` repo.

**Comment by MidnightWonderer** [comment]
Spent some time debugging and figuring out what going on in the webpacker code.  
Here how I did it:  

* create a file as `config/webpack/loaders/sass.js` with content:
```javascript
const cssLoader = require('@rails/webpacker/package/rules/css')
const cloneDeep = require('lodash/fp/cloneDeep')
const deepMerge = require('@rails/webpacker/package/utils/deep_merge')

let sassLoader = cloneDeep(cssLoader)
module.exports = deepMerge(sassLoader, {
  test: /\.(scss|sass)$/i,
  use: [{
    loader: 'sass-loader',
    options: {
      includePaths: ['node_modules'],
      sourceMap: true,
    },
  }]
})
```
The content is mostly copied from `node_modules/@rails/webpacker/package/rules/sass.js`  
the important part is: `includePaths: ['node_modules'],`
* import the loader in this file `config/webpack/environment.js`  
This is mine (working on a typescript project)
```javascript
const { environment } = require('@rails/webpacker')
const typescript = require('./loaders/typescript')
const sass = require('./loaders/sass')

environment.loaders.append('typescript', typescript)
environment.loaders.append('sass', sass)

module.exports = environment
```
  
And it just works the had part was inspecting webpacker code and figuring out what to do.

**Comment by flippakitten** [comment]
If anyone else comes across this in future and the above didn't seem to work, you can also alias `@materilize`.  

`config/webpack/custom.js`
```
module.exports = {
  resolve: {
    alias: {
      '@material': 'node_modules/@material'
    }
  }
};
```
Then in application.scss (or where you need it)
`@import '@material/button/mdc-button';`

**Comment by flippakitten** [comment]
**Real Answer:** (ignore my above post)
Finally figured this out and it's actually pretty simple. You need to update the existing default `sass-loader`!
simply add the following in `config/webpack/enviroment.js` just before `module.exports`
```
environment.loaders.get('sass').use.find(item => item.loader === 'sass-loader').options.includePaths = ['node_modules']
```
Which is actually shown pretty well in [the documentation](https://github.com/rails/webpacker/blob/master/docs/webpack.md#loaders):

Probably a cleaner way to do it instead of chaining but it works.
