### ISSUE TITLE
Adjusting options for a given entry point

### ISSUE THREAD

**Issue by tristanoneil** [rails/webpacker#459]
I'm curious if it's possible to provide additional options for a given entry point. For instance one of my entry points works fine with the default configuration but one requires some additional configuration in `output`. Specifically I need to specify the following for one of my entry points.

```js
output: {
  libraryTarget: 'var'
}
```

From looking at `webpack/shared.js` there doesn't appear to be an officially supported paradigm to provide additional options on a per entry point basis but I figured I'd ask.

**Comment by gauravtiwari** [comment]
@tristanoneil No out-of-the-box webpacker doesn't support this but you can rewrite part of the config if needed - sounds bit tricky though . If however you have found a way to make this possible then feel free to make a PR please 👍
