### ISSUE TITLE
Reinstalling on 2.0 upgrade causes errors on all functional components

### ISSUE THREAD

**Issue by hundsim** [rails/webpacker#462]
I've upgraded Webpacker to 2.0 and my app worked without issues. But when I run the command `rails webpacker:install`, as instructed in the changelog, I'm getting errors referencing all my functional components.

The errors all point to the first character in my return statement. An example how the errors looks like:

	ERROR in ./app/javascript/packs/reusable-components/SingleInput.jsx
	Module build failed: SyntaxError: Unexpected token (6:1)

	  4 | 
	  5 | const SingleInput = (props) => (
	> 6 | 	<div className={styles.fieldWrap}>
	    | 	^
	  7 | 		<label className={styles.label}>
	  8 | 			{props.title}
	  9 | 			{props.children}

	 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 ./app/javascript/packs/reusable-components/SingleInput.jsx

Any idea what is happening here and how I can fix it?

**Comment by gauravtiwari** [comment]
Ahh I guess your `.baberc` is overwritten. You might wanna re-install react too - `bundle exec rails webpacker:install:react`

**Comment by hundsim** [comment]
That did it! Thank you **so much** for your incredible fast response 😮💛
