### ISSUE TITLE
typo: when run command `ralis webpacker`

### ISSUE THREAD

**Issue by TangMonk** [rails/webpacker#465]
![image](https://cloud.githubusercontent.com/assets/3498786/26750478/5f72d918-4856-11e7-9914-6f1dcba287ae.png)

did you notice this line:

```
webpacker:check_webpack_binstubsVerifies that bin/webpack & bin/webpack-dev-server are present
```

it should be 

```
webpacker:check_webpack_binstubs      <gap here>    Verifies that bin/webpack & bin/webpack-dev-server are present
```

**Comment by S-YOU** [comment]
It is not typo, but overflowing the column, IMO. I've sent a PR.
