### ISSUE TITLE
Error preventing deployment to Heroku: Module build failed: Error: ENOENT: no such file or directory, open '/tmp/build_008e928d...

### ISSUE THREAD

**Issue by hundsim** [rails/webpacker#467]
## My environment
Webpacker 2.0
Rails 5.1
Ruby 2.4.1
Node 8.0
Yarn 0.24.6

## Description
This is similar to issue #422, but as that one's closed and I'm still having issues despite following given recommendations over there and what is written under the [troubleshooting section](https://github.com/rails/webpacker#troubleshooting) - I thought I'd add my circumstances in case that brings some more light. 
- Everything works fine in my local setup.
- I have added these buildpacks on Heroku (in that order):
1. heroku/nodejs
2. heroku/ruby
- I have added this to `package.json`:  

	  "scripts": {
	    "postinstall": "npm rebuild node-sass"
	  },

## Log from Heroku deployment

	Counting objects: 19, done.
	Delta compression using up to 2 threads.
	Compressing objects: 100% (19/19), done.
	Writing objects: 100% (19/19), 1.73 KiB | 0 bytes/s, done.
	Total 19 (delta 16), reused 0 (delta 0)
	remote: Compressing source files... done.
	remote: Building source:
	remote: 
	remote: -----> Node.js app detected
	remote: 
	remote: -----> Creating runtime environment
	remote:        
	remote:        NPM_CONFIG_LOGLEVEL=error
	remote:        NPM_CONFIG_PRODUCTION=true
	remote:        NODE_VERBOSE=false
	remote:        NODE_ENV=production
	remote:        NODE_MODULES_CACHE=true
	remote: 
	remote: -----> Installing binaries
	remote:        engines.node (package.json):  unspecified
	remote:        engines.npm (package.json):   unspecified (use default)
	remote:        
	remote:        Resolving node version 6.x via semver.io...
	remote:        Downloading and installing node 6.10.3...
	remote:        Using default npm version: 3.10.10
	remote:        Resolving yarn version (latest) via semver.io...
	remote:        Downloading and installing yarn (0.24.5)...
	remote:        Installed yarn 0.24.5
	remote: 
	remote: -----> Restoring cache
	remote:        Loading 2 from cacheDirectories (default):
	remote:        - node_modules
	remote:        - bower_components (not cached - skipping)
	remote: 
	remote: -----> Building dependencies
	remote:        Installing node modules (yarn.lock)
	remote:        yarn install v0.24.5
	remote:        warning No license field
	remote:        [1/5] Resolving packages...
	remote:        [2/5] Fetching packages...
	remote:        warning fsevents@1.1.1: The platform "linux" is incompatible with this module.
	remote:        info "fsevents@1.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
	remote:        [3/5] Linking dependencies...
	remote:        [4/5] Building fresh packages...
	remote:        [5/5] Cleaning modules...
	remote:        $ npm rebuild node-sass
	remote:        
	remote:        > node-sass@4.5.3 install /tmp/build_87cc2a6479f1532a74d2d9ab8a5d3dd7/node_modules/node-sass
	remote:        > node scripts/install.js
	remote:        
	remote:        node-sass build Binary found at /tmp/build_87cc2a6479f1532a74d2d9ab8a5d3dd7/node_modules/node-sass/vendor/linux-x64-48/binding.node
	remote:        
	remote:        > node-sass@4.5.3 postinstall /tmp/build_87cc2a6479f1532a74d2d9ab8a5d3dd7/node_modules/node-sass
	remote:        > node scripts/build.js
	remote:        
	remote:        Binary found at /tmp/build_87cc2a6479f1532a74d2d9ab8a5d3dd7/node_modules/node-sass/vendor/linux-x64-48/binding.node
	remote:        Testing binary
	remote:        Binary is fine
	remote:        node-sass@4.5.3 /tmp/build_87cc2a6479f1532a74d2d9ab8a5d3dd7/node_modules/node-sass
	remote:        Done in 48.02s.
	remote: 
	remote: -----> Caching build
	remote:        Clearing previous node cache
	remote:        Saving 2 cacheDirectories (default):
	remote:        - node_modules
	remote:        - bower_components (nothing to cache)
	remote: 
	remote: -----> Build succeeded!
	remote: -----> Ruby app detected
	remote: -----> Compiling Ruby/Rails
	remote: -----> Using Ruby version: ruby-2.4.1
	remote: -----> Installing dependencies using bundler 1.13.7
	remote:        Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
	remote:        Warning: the running version of Bundler (1.13.7) is older than the version that created the lockfile (1.14.6). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
	remote:        Fetching gem metadata from https://rubygems.org/.......
	remote:        Fetching version metadata from https://rubygems.org/..
	remote:        Fetching dependency metadata from https://rubygems.org/.
	remote:        Using rake 12.0.0
	remote:        Using concurrent-ruby 1.0.5
	remote:        Using i18n 0.8.4
	remote:        Using minitest 5.10.2
	remote:        Using thread_safe 0.3.6
	remote:        Using builder 3.2.3
	remote:        Using erubi 1.6.0
	remote:        Using mini_portile2 2.1.0
	remote:        Using rack 2.0.3
	remote:        Using nio4r 2.1.0
	remote:        Using websocket-extensions 0.1.2
	remote:        Using mime-types-data 3.2016.0521
	remote:        Using arel 8.0.0
	remote:        Using public_suffix 2.0.5
	remote:        Using awesome_print 1.7.0
	remote:        Using aws_cf_signer 0.1.3
	remote:        Using babel-source 5.8.35
	remote:        Using execjs 2.7.0
	remote:        Using bcrypt 3.1.11
	remote:        Using browser 2.4.0
	remote:        Using unf_ext 0.0.7.4
	remote:        Using netrc 0.11.0
	remote:        Using coffee-script-source 1.12.2
	remote:        Using method_source 0.8.2
	remote:        Using thor 0.19.4
	remote:        Using connection_pool 2.2.1
	remote:        Using declarative 0.0.9
	remote:        Using declarative-option 0.1.0
	remote:        Using multipart-post 2.0.0
	remote:        Using sass 3.4.24
	remote:        Using jwt 1.5.6
	remote:        Using little-plugger 1.1.4
	remote:        Using multi_json 1.12.1
	remote:        Using memoist 0.15.0
	remote:        Using os 0.9.6
	remote:        Using httpclient 2.8.3
	remote:        Using uber 0.1.0
	remote:        Using retriable 3.0.2
	remote:        Using icalendar 2.4.1
	remote:        Using json 2.1.0
	remote:        Using pg 0.20.0
	remote:        Using newrelic_rpm 4.2.0.334
	remote:        Using puma 3.9.0
	remote:        Using bundler 1.13.7
	remote:        Using tilt 2.0.7
	remote:        Using redis 3.3.3
	remote:        Using timezone 1.2.7
	remote:        Using sucker_punch 2.0.2
	remote:        Using tzinfo 1.2.3
	remote:        Using nokogiri 1.7.2
	remote:        Using rack-test 0.6.3
	remote:        Using sprockets 3.7.1
	remote:        Using websocket-driver 0.6.5
	remote:        Using mime-types 3.1
	remote:        Using addressable 2.5.1
	remote:        Using babel-transpiler 0.7.0
	remote:        Using uglifier 3.2.0
	remote:        Using unf 0.1.4
	remote:        Using coffee-script 2.4.1
	remote:        Using faraday 0.12.1
	remote:        Using logging 2.2.2
	remote:        Using rollbar 2.14.1
	remote:        Using representable 3.0.4
	remote:        Using font-awesome-sass 4.7.0
	remote:        Using intercom 3.5.14
	remote:        Using activesupport 5.1.1
	remote:        Using loofah 2.0.3
	remote:        Using domain_name 0.5.20170404
	remote:        Using signet 0.7.3
	remote:        Using mail 2.6.5
	remote:        Using rails-dom-testing 2.0.3
	remote:        Using globalid 0.4.0
	remote:        Using activemodel 5.1.1
	remote:        Using intercom-rails 0.3.5
	remote:        Using jbuilder 2.6.4
	remote:        Using pundit 1.1.0
	remote:        Using rails-html-sanitizer 1.0.3
	remote:        Using googleauth 0.5.1
	remote:        Using http-cookie 1.0.3
	remote:        Using activejob 5.1.1
	remote:        Using actionview 5.1.1
	remote:        Using activerecord 5.1.1
	remote:        Using rest-client 2.0.2
	remote:        Using google-api-client 0.12.0
	remote:        Using actionpack 5.1.1
	remote:        Using jsonb_accessor 1.0.0.beta.6
	remote:        Using actioncable 5.1.1
	remote:        Using actionmailer 5.1.1
	remote:        Using railties 5.1.1
	remote:        Using sprockets-rails 3.2.0
	remote:        Using cloudinary 1.8.1
	remote:        Using mailgun-ruby 1.1.6
	remote:        Using coffee-rails 4.2.2
	remote:        Using jquery-rails 4.3.1
	remote:        Using lodash-rails 4.17.4
	remote:        Using react-rails 2.2.0
	remote:        Using webpacker 2.0
	remote:        Using rails 5.1.1
	remote:        Using sass-rails 5.0.6
	remote:        Bundle complete! 40 Gemfile dependencies, 99 gems now installed.
	remote:        Gems in the groups development and test were not installed.
	remote:        Bundled gems are installed into ./vendor/bundle.
	remote:        Bundle completed (2.88s)
	remote:        Cleaning up the bundler cache.
	remote:        Warning: the running version of Bundler (1.13.7) is older than the version that created the lockfile (1.14.6). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
	remote: -----> Detecting rake tasks
	remote: -----> Preparing app for Rails asset pipeline
	remote:        Running: rake assets:precompile
	remote:        yarn install v0.24.5
	remote:        warning No license field
	remote:        [1/5] Resolving packages...
	remote:        [2/5] Fetching packages...
	remote:        warning fsevents@1.1.1: The platform "linux" is incompatible with this module.
	remote:        info "fsevents@1.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
	remote:        [3/5] Linking dependencies...
	remote:        [4/5] Building fresh packages...
	remote:        [5/5] Cleaning modules...
	remote:        $ npm rebuild node-sass
	remote:        > node-sass@4.5.3 install /tmp/build_87cc2a6479f1532a74d2d9ab8a5d3dd7/node_modules/node-sass
	remote:        > node scripts/install.js
	remote:        node-sass build Binary found at /tmp/build_87cc2a6479f1532a74d2d9ab8a5d3dd7/node_modules/node-sass/vendor/linux-x64-48/binding.node
	remote:        > node-sass@4.5.3 postinstall /tmp/build_87cc2a6479f1532a74d2d9ab8a5d3dd7/node_modules/node-sass
	remote:        > node scripts/build.js
	remote:        Binary found at /tmp/build_87cc2a6479f1532a74d2d9ab8a5d3dd7/node_modules/node-sass/vendor/linux-x64-48/binding.node
	remote:        Testing binary
	remote:        Binary is fine
	remote:        node-sass@4.5.3 /tmp/build_87cc2a6479f1532a74d2d9ab8a5d3dd7/node_modules/node-sass
	remote:        Done in 33.47s.
	remote:        I, [2017-06-03T12:17:36.261971 #1241]  INFO -- : Writing /tmp/build_87cc2a6479f1532a74d2d9ab8a5d3dd7/public/assets/open-sans/OpenSans-Bold-5894a3649b213cf5b2d673b6e7a871815fd1d120fa68a463592f27db14eae323.ttf
	remote:        I, [2017-06-03T12:17:36.262861 #1241]  INFO -- : Writing /tmp/build_87cc2a6479f1532a74d2d9ab8a5d3dd7/public/assets/open-sans/OpenSans-Bold-5894a3649b213cf5b2d673b6e7a871815fd1d120fa68a463592f27db14eae323.ttf.gz
	remote:        I, [2017-06-03T12:17:36.266969 #1241]  INFO -- : Writing /tmp/build_87cc2a6479f1532a74d2d9ab8a5d3dd7/public/assets/open-sans/OpenSans-Regular-e64e508b2aa2880f907e470c4550980ec4c0694d103a43f36150ac3f93189bee.ttf
	remote:        I, [2017-06-03T12:17:36.267915 #1241]  INFO -- : Writing /tmp/build_87cc2a6479f1532a74d2d9ab8a5d3dd7/public/assets/open-sans/OpenSans-Regular-e64e508b2aa2880f907e470c4550980ec4c0694d103a43f36150ac3f93189bee.ttf.gz
	remote:        I, [2017-06-03T12:17:36.273573 #1241]  INFO -- : Writing /tmp/build_87cc2a6479f1532a74d2d9ab8a5d3dd7/public/assets/open-sans/OpenSans-Semibold-aa3b0ef53db12e3d45094030cac0e69d384e44cc5978643dd4390041cad546e2.ttf
	remote:        I, [2017-06-03T12:17:36.274793 #1241]  INFO -- : Writing /tmp/build_87cc2a6479f1532a74d2d9ab8a5d3dd7/public/assets/open-sans/OpenSans-Semibold-aa3b0ef53db12e3d45094030cac0e69d384e44cc5978643dd4390041cad546e2.ttf.gz
	remote:        I, [2017-06-03T12:18:33.320800 #1241]  INFO -- : Writing /tmp/build_87cc2a6479f1532a74d2d9ab8a5d3dd7/public/assets/application-14ff19e457ff749a4e406ab81b3db8a72a5ba2066e97c95146e8d87bfce448bc.js
	remote:        I, [2017-06-03T12:18:33.321026 #1241]  INFO -- : Writing /tmp/build_87cc2a6479f1532a74d2d9ab8a5d3dd7/public/assets/application-14ff19e457ff749a4e406ab81b3db8a72a5ba2066e97c95146e8d87bfce448bc.js.gz
	remote:        I, [2017-06-03T12:18:38.879154 #1241]  INFO -- : Writing /tmp/build_87cc2a6479f1532a74d2d9ab8a5d3dd7/public/assets/application-8475f5d70b51fb715296c802ec3b113a651a7c8a511d90fa8fdb36b9304ea191.css
	remote:        I, [2017-06-03T12:18:38.879725 #1241]  INFO -- : Writing /tmp/build_87cc2a6479f1532a74d2d9ab8a5d3dd7/public/assets/application-8475f5d70b51fb715296c802ec3b113a651a7c8a511d90fa8fdb36b9304ea191.css.gz
	remote:        I, [2017-06-03T12:18:39.568829 #1241]  INFO -- : Writing /tmp/build_87cc2a6479f1532a74d2d9ab8a5d3dd7/public/assets/express/lib/application-bcf7601db3a0edf987579a79c4b80e5a247dfbcad6d5c183f54cd05255b4ba5c.js
	remote:        I, [2017-06-03T12:18:39.568996 #1241]  INFO -- : Writing /tmp/build_87cc2a6479f1532a74d2d9ab8a5d3dd7/public/assets/express/lib/application-bcf7601db3a0edf987579a79c4b80e5a247dfbcad6d5c183f54cd05255b4ba5c.js.gz
	remote:        Webpacker is installed 🎉 🍰
	remote:        Using /tmp/build_87cc2a6479f1532a74d2d9ab8a5d3dd7/config/webpacker.yml file for setting up webpack paths
	remote:        [Webpacker] Compiling assets 🎉
	remote:        [Webpacker] Compilation Failed
	remote:        yarn run v0.24.5
	remote:        $ "/tmp/build_87cc2a6479f1532a74d2d9ab8a5d3dd7/node_modules/.bin/webpack" --config /tmp/build_87cc2a6479f1532a74d2d9ab8a5d3dd7/config/webpack/production.js
	remote:        Hash: 0f4a4bcf8af8497ead54
	remote:        Time: 45361ms
	remote:        [34] ./app/javascript/packs/reusable-components/FormFields.css 2.46 kB {0} {1} {2} {7} {8} {12} {16} {27} [built] [failed] [1 error]
	remote:        [51] ./app/javascript/packs/link-editor/CustomUrl.jsx 1.39 kB {0} {1} {2} {7} [built]
	remote:        [67] ./app/javascript/packs/link-editor/RadioButtonGroup.jsx 1.39 kB {0} {1} {21} [built]
	remote:        [73] ./app/javascript/packs/link-editor/reset.css 2.46 kB {0} {1} {28} [built] [failed] [1 error]
	remote:        [209] ./app/javascript/packs/dashboard-sections/EventsSection.jsx 5.45 kB {0} {4} [built]
	remote:        [210] ./app/javascript/packs/link-create-confirmation/ConfirmationPage.jsx 4.61 kB {0} {6} [built]
	remote:        [211] ./app/javascript/packs/link-editor/LinkCreator.jsx 6.42 kB {0} {1} [built]
	remote:        [212] ./app/javascript/packs/sidebar/CreateNewButton.jsx 345 bytes {0} {20} [built]
	remote:        [213] ./app/javascript/packs/sidebar/SidebarBox.jsx 1.42 kB {0} {19} [built]
	remote:        [231] ./app/javascript/packs/ListModule.jsx 2.38 kB {15} [built]
	remote:        [232] ./app/javascript/packs/dashboard/App.jsx 10.7 kB {0} [built]
	remote:        [233] ./app/javascript/packs/link-editor/react-available-times.jsx 248 bytes {31} [built]
	remote:        [234] ./app/javascript/packs/meeting_links/App.jsx 5.29 kB {3} [built]
	remote:        [235] ./app/javascript/packs/css/variables.css 2.46 kB {30} [built] [failed] [1 error]
	remote:        [236] ./app/javascript/packs/link-editor/Button.css 2.46 kB {29} [built] [failed] [1 error]
	remote:        + 245 hidden modules
	remote:        ERROR in ./~/css-loader?{"modules":true,"minimize":true,"localIdentName":"[name]__[local]--[hash:base64:5]"}!./~/postcss-loader/lib?{"sourceMap":true}!./~/resolve-url-loader!./~/sass-loader/lib/loader.js?{"sourceMap":true}!./app/javascript/packs/ListModule.css
	remote:        Module build failed: Error: ENOENT: no such file or directory, open '/tmp/build_87cc2a6479f1532a74d2d9ab8a5d3dd7/node_modules/svgo/lib/svgo/../../.svgo.yml'
	remote:        at Error (native)
	remote:        at Object.fs.openSync (fs.js:641:18)
	remote:        at Object.fs.readFileSync (fs.js:509:33)
	remote:        at module.exports (/tmp/build_87cc2a6479f1532a74d2d9ab8a5d3dd7/node_modules/svgo/lib/svgo/config.js:31:48)
	remote:        at new module.exports (/tmp/build_87cc2a6479f1532a74d2d9ab8a5d3dd7/node_modules/svgo/lib/svgo.js:21:19)
	remote:        at /tmp/build_87cc2a6479f1532a74d2d9ab8a5d3dd7/node_modules/postcss-svgo/dist/index.js:95:16
	remote:        at Object.creator [as postcssSvgo] (/tmp/build_87cc2a6479f1532a74d2d9ab8a5d3dd7/node_modules/postcss/lib/postcss.js:150:35)
	remote:        at /tmp/build_87cc2a6479f1532a74d2d9ab8a5d3dd7/node_modules/cssnano/dist/index.js:295:40
	remote:        at Array.forEach (native)
	remote:        at /tmp/build_87cc2a6479f1532a74d2d9ab8a5d3dd7/node_modules/cssnano/dist/index.js:282:29
	remote:        at creator (/tmp/build_87cc2a6479f1532a74d2d9ab8a5d3dd7/node_modules/postcss/lib/postcss.js:150:35)
	remote:        at processCss (/tmp/build_87cc2a6479f1532a74d2d9ab8a5d3dd7/node_modules/css-loader/lib/processCss.js:193:16)
	remote:        at Object.module.exports (/tmp/build_87cc2a6479f1532a74d2d9ab8a5d3dd7/node_modules/css-loader/lib/loader.js:40:2)
	remote:        @ ./app/javascript/packs/ListModule.css 4:14-263
	remote:        @ ./app/javascript/packs/ListModule.jsx
	remote:        ERROR in ./~/css-loader?{"modules":true,"minimize":true,"localIdentName":"[name]__[local]--[hash:base64:5]"}!./~/postcss-loader/lib?{"sourceMap":true}!./~/resolve-url-loader!./~/sass-loader/lib/loader.js?{"sourceMap":true}!./app/javascript/packs/link-editor/Button.css
	remote:        Module build failed: Error: ENOENT: no such file or directory, open '/tmp/build_87cc2a6479f1532a74d2d9ab8a5d3dd7/node_modules/svgo/lib/svgo/../../.svgo.yml'
	remote:        at Error (native)
	remote:        at Object.fs.openSync (fs.js:641:18)
	remote:        at Object.fs.readFileSync (fs.js:509:33)
	remote:        at module.exports (/tmp/build_87cc2a6479f1532a74d2d9ab8a5d3dd7/node_modules/svgo/lib/svgo/config.js:31:48)
	remote:        at new module.exports (/tmp/build_87cc2a6479f1532a74d2d9ab8a5d3dd7/node_modules/svgo/lib/svgo.js:21:19)
	remote:        at /tmp/build_87cc2a6479f1532a74d2d9ab8a5d3dd7/node_modules/postcss-svgo/dist/index.js:95:16
	remote:        at Object.creator [as postcssSvgo] (/tmp/build_87cc2a6479f1532a74d2d9ab8a5d3dd7/node_modules/postcss/lib/postcss.js:150:35)
	remote:        at /tmp/build_87cc2a6479f1532a74d2d9ab8a5d3dd7/node_modules/cssnano/dist/index.js:295:40
	remote:        at Array.forEach (native)
	remote:        at /tmp/build_87cc2a6479f1532a74d2d9ab8a5d3dd7/node_modules/cssnano/dist/index.js:282:29
	remote:        at creator (/tmp/build_87cc2a6479f1532a74d2d9ab8a5d3dd7/node_modules/postcss/lib/postcss.js:150:35)
	remote:        at processCss (/tmp/build_87cc2a6479f1532a74d2d9ab8a5d3dd7/node_modules/css-loader/lib/processCss.js:193:16)
	remote:        at Object.module.exports (/tmp/build_87cc2a6479f1532a74d2d9ab8a5d3dd7/node_modules/css-loader/lib/loader.js:40:2)
	remote:        @ ./app/javascript/packs/link-editor/Button.css 4:14-271
	remote:        ERROR in ./~/css-loader?{"modules":true,"minimize":true,"localIdentName":"[name]__[local]--[hash:base64:5]"}!./~/postcss-loader/lib?{"sourceMap":true}!./~/resolve-url-loader!./~/sass-loader/lib/loader.js?{"sourceMap":true}!./app/javascript/packs/link-editor/reset.css
	remote:        Module build failed: Error: ENOENT: no such file or directory, open '/tmp/build_87cc2a6479f1532a74d2d9ab8a5d3dd7/node_modules/svgo/lib/svgo/../../.svgo.yml'
    etc...

**Comment by gauravtiwari** [comment]
Do you have `.yarnclean` file in your root directory? Please remove and re-deploy again.

**Comment by hundsim** [comment]
This is probably 101 knowledge in the yarn/npm-world. Thank you sooo much for your (always) rapid and spot-on help. And your patience with a newbie who's dabbling his toes in this exciting js-water. I'm building an amazing app with already many, many happy users thanks to what webpacker has brought to Rails. Have the **best of weekends** 🙏
