### ISSUE TITLE
Test Packs are not recompiled when changed

### ISSUE THREAD

**Issue by richseviora** [rails/webpacker#468]
Opening issue for visibility.

As mentioned in the discussion in PR #360, test packs are not recompiled when changed. If the `packs-test` directory (or your default) already exists, subsequent changes to `app/javascript/pack` will not cause the `packs-test` directory to be regenerated.

`Webpacker::Manifest.lookup` checks to see if the file is found (`.find`) but there's no freshness check.

**Comment by gauravtiwari** [comment]
@richseviora Please see this comment - https://github.com/rails/webpacker/pull/360#issuecomment-306003866

**Comment by justin808** [comment]
@richseviora See #464. Also, I wrote the code for [React on Rails](https://github.com/shakacode/react_on_rails) that does this. We use the file mtimes.
