### ISSUE TITLE
move loaders and webpack plugins from "dependencies" to "devDependencies"

### ISSUE THREAD

**Issue by TangMonk** [rails/webpacker#469]
We can group  necessary  dependencies to vendor for [Code Splitting - Libraries
](https://webpack.js.org/guides/code-splitting-libraries/)
```
const pkg = require('./package.json')

  entry: {
    app: [`${PATHS.src}/index.js`],
    style: PATHS.style,
    vendor: Object.keys(pkg.dependencies))
  },
```

**Comment by gauravtiwari** [comment]
@TangMonk Please check these issues - https://github.com/rails/webpacker/issues/117 and https://github.com/rails/webpacker/issues/165 and https://github.com/rails/webpacker/issues/160
