### ISSUE TITLE
Windows 10 ./bin/webpack-dev-server command error

### ISSUE THREAD

**Issue by coding102** [rails/webpacker#470]
Running:  ruby 2.4.1
                rails 5.1.1
                windows 10 64 bit

Running this command on Bash on Ubuntu ****./bin/webpack-dev-server*** throws error.

Here is the error: 

$ "......................../node_modules/.bin/webpack-dev-server" --progress --color --config /mnt/c/Users/coding101/Desktop/test_webpacker/config/webpack/development.js
 10% building modules 2/2 modules 0 activeevents.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:8080
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at Server._listen2 (net.js:1258:14)
    at listen (net.js:1294:10)
    at net.js:1404:9
    at _combinedTickCallback (internal/process/next_tick.js:83:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by gauravtiwari** [comment]
@coding102 Do you have any process running on port 8080? Like nginx or something?

**Comment by coding102** [comment]
Rails = localhost:3000
pgAdmin4 = Port 5433

On powershell if typed  netstat -an and found this port listening

TCP    0.0.0.0:8080           0.0.0.0:0              LISTENING

I killed it and it's now compiling thanks

**Comment by EmmaAkin** [comment]
I am having similar problem. In my  case this is the error
yarn run v0.27.5
$ "~\investxd-frontEnd\node_modules\.bin\webpack-dev-server" "--progress" "--color" "--config" "C:/Users/emma/Documents/learningPython/investxd-frontEnd/config/webpack/development.js"
The filename, directory name, or volume label syntax is incorrect.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by Spazer9** [comment]
@EmmaAkin I'm having the exact same problem!! can't believe no one posted a fix so far.

Have you managed to solve it?

**Comment by EmmaAkin** [comment]
@Spazer9 did not fix it. I resolve not to go the rails/vuejs route rather I went with rails api and vuejs front end. Everything is fine, only that I have to write more ajax code to handle api calls.

**Comment by soundasleep** [comment]
@EmmaAkin @Spazer9 This might be a problem with yarn on Windows - one solution proposed is #584 which might be merged soon. Essentially webpack works if you bypass `yarn run webpack` and go straight to `node_modules/.bin/webpack`.
