### ISSUE TITLE
Adding styles and images to be processed results in generating a JS file

### ISSUE THREAD

**Issue by paulcsmith** [rails/webpacker#471]
According to https://github.com/rails/webpacker#inside-views it seems like I should be able to use web packer for CSS and images as well as JS assets. When I try to add images or CSS for webpack to process, it does appear to process them, but it treats them as JS. Here's the input and output (using a default web packer install).

-> packs: https://github.com/paulcsmith/webpacker-static/tree/master/app/javascript/packs
-> public output: https://github.com/paulcsmith/webpacker-static/tree/master/public/packs

It seems like using an object for the entry points causes the issue. If I create a webpack config and do something like this, it doesn't treat them as JS (but sadly it doesn't keep the folder structure)

```javascript
// for entry point
app: ['./app/javascript/packs/app.js', './app/javascript/packs/meme.jpg']
```

But doing this next style *does* cause images and css to be treated as JS, but *does* keep the correct folder structure. I believe this is the style webpacker is using.

```javascript
// for entry point
'./packs/meme.jpg': './app/javascript/packs/meme.jpg'
```

I see a couple things that could be the issue

1) I'm misunderstanding the README and using webpacker in an unsupported way. If that's the case, please LMK and I'll submit a PR for clarifying it so others don't get messed up the same way I am
2) This is supposed to be supported, but we need to change how the entries are generated so it works as expected (moving and fingerprinting the image, but not creating a JS file and minifying it in prod)

If you need any more info, LMK. Thanks for your hard work on this extremely helpful library!

**Comment by gauravtiwari** [comment]
@paulcsmith Hey, so by convention one should only put `.js` packs inside packs directory since they are treated in a special way by webpack. Other types of files like - styles, fonts and images should be placed outside of the packs directory and can be referenced from there. You can see a basic structure here - https://github.com/rails/webpacker#app-structure and https://github.com/rails/webpacker#within-your-js-app (notice where styles are placed)

If you think this isn't very clear, feel free to push a PR 👍

**Comment by paulcsmith** [comment]
@gauravtiwari I read that in the README, but I think I misunderstood. I'm guessing there is something missing from the docs to get from that file/dir structure to the expected output. I added a commit here: https://github.com/paulcsmith/webpacker-static/commit/3c6e98e34e01ee202ee32abb46bb4045e40e260a but the styles and images are not present in `/public` or in the manifest. **So I'm guessing something needs to go in `application.js` to load the css and image?** I think that's whats missing from the README. If you could give me a pointer on what's missing I would love to submit a PR so others can benefit as well.

Thanks for your patience. I find webpack to be a bit confusing so I can't figure out what I'm missing :S

**Comment by paulcsmith** [comment]
Never mind. I don't know how I missed it, but it's right here: https://github.com/rails/webpacker/blame/master/README.md#L421 Sorry about that. I think it's because I wasn't expecting to have to import non-JS code in a JS file.

Thanks!

**Comment by gauravtiwari** [comment]
@paulcsmith Great and no worries 👍  BTW you can also reference static assets inside stylesheets like you would do in either sass or vanilla css. For ex - https://github.com/gauravtiwari/webpacker-example-app/blob/master/app/assets/javascript/counter/styles/style.sass#L35

**Comment by paulcsmith** [comment]
Very cool! Strange that webpack doesn't keep the same folder structure when copying things over. Seems like assets could clash at some point, but this should do the trick for now. Thanks again!
