### ISSUE TITLE
i am new to angular and learning, i can't see where is @angular/router 

### ISSUE THREAD

**Issue by hashmee** [rails/webpacker#472]
I installed webpacker gem to make a single page application.
there is no router library in the angular repo of node_modules, any help would be very greatful

**Comment by gauravtiwari** [comment]
@hashmee Hey, we ship a minimal angular example without router. Please checkout this tutorial - https://angular.io/docs/ts/latest/guide/router.html

**Comment by hashmee** [comment]
Thank you @gauravtiwari **yarn** made my thing to install router and http in the node modules

**Comment by gauravtiwari** [comment]
@hashmee Awesome 👍  - if you just need to add a module use `yarn`
