### ISSUE TITLE
Loading vendor.scss breaks JS

### ISSUE THREAD

**Issue by rhymes** [rails/webpacker#485]
I'm trying to port a regular rails asset pipeline app to webpacker and I managed to have all the JS work, now I'm trying to "bring over" the CSS/SCSS and I started with creating a vendor.scss file in my packs folder, then referring it from application.html.erb as `<%= stylesheet_pack_tag 'vendor' %>` and webpack-dev-server picks it up correctly:

vendor.scss
```scss
@import '~bootstrap/dist/css/bootstrap'
```

manifest.json
```json
{
  "application.js": "http://0.0.0.0:8080/packs/application.js",
  "glyphicons-halflings-regular.eot": "http://0.0.0.0:8080/packs/glyphicons-halflings-regular.eot",
  "glyphicons-halflings-regular.svg": "http://0.0.0.0:8080/packs/glyphicons-halflings-regular.svg",
  "glyphicons-halflings-regular.ttf": "http://0.0.0.0:8080/packs/glyphicons-halflings-regular.ttf",
  "glyphicons-halflings-regular.woff": "http://0.0.0.0:8080/packs/glyphicons-halflings-regular.woff",
  "glyphicons-halflings-regular.woff2": "http://0.0.0.0:8080/packs/glyphicons-halflings-regular.woff2",
  "vendor.css": "http://0.0.0.0:8080/packs/vendor.css",
  "vendor.js": "http://0.0.0.0:8080/packs/vendor.js"
}
```

webpack-dev-server output
```
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 155 kB [entry] [rendered]
        [0] ./~/bootstrap/dist/fonts/glyphicons-halflings-regular.eot 78 bytes {0} [built]
        [1] ./~/css-loader/lib/css-base.js 2.26 kB {0} [built]
        [2] ./~/bootstrap/dist/fonts/glyphicons-halflings-regular.svg 78 bytes {0} [built]
        [3] ./~/bootstrap/dist/fonts/glyphicons-halflings-regular.ttf 78 bytes {0} [built]
        [4] ./~/bootstrap/dist/fonts/glyphicons-halflings-regular.woff 79 bytes {0} [built]
        [5] ./~/bootstrap/dist/fonts/glyphicons-halflings-regular.woff2 80 bytes {0} [built]
        [6] ./~/css-loader?{"minimize":false}!./~/postcss-loader/lib?{"sourceMap":true}!./~/resolve-url-loader!./~/sass-loader/lib/loader.js?{"sourceMap":true}!./frontend/packs/vendor.scss 152 kB {0} [built]
```

The issue, which is weird to me, is that when I start the Rails web server all the stuff referenced from the vendor.js (the JavaScript) stops working.

```
Uncaught ReferenceError: $ is not defined
    at eval (eval at module.exports (eval at <anonymous> (vendor.js:176)), <anonymous>:2:1)
    at eval (<anonymous>)
    at module.exports (eval at <anonymous> (vendor.js:176), <anonymous>:9:8)
    at eval (eval at <anonymous> (application.js:555), <anonymous>:1:62)
    at Object.<anonymous> (application.js:555)
    at __webpack_require__ (vendor.js:55)
    at eval (eval at <anonymous> (application.js:11), <anonymous>:34:90)
    at Object.<anonymous> (application.js:11)
    at __webpack_require__ (vendor.js:55)
    at Object.<anonymous> (application.js:660)
    at __webpack_require__ (vendor.js:55)
    at webpackJsonpCallback (vendor.js:26)
    at application.js:1
```

If I delete the vendor.scss file and the `<%= stylesheet_pack_tag 'vendor' %>` everything works (as before), so it seems I can't vendor in SCSS and JS at the same time?

This is part of my config/webpack/shared.js

```javascript
module.exports = {
  entry: packPaths.reduce(
    (map, entry) => {
      const localMap = map
      const namespace = relative(join(entryPath), dirname(entry))
      localMap[join(namespace, basename(entry, extname(entry)))] = resolve(entry)
      return localMap
    }, {}
  ),

  output: {
    filename: '[name].js',
    path: output.path,
    publicPath: output.publicPath
  },

  module: {
    rules: sync(join(loadersDir, '*.js')).map(loader => require(loader))
  },

  plugins: [
    new webpack.EnvironmentPlugin(JSON.parse(JSON.stringify(env))),
    new ExtractTextPlugin(env.NODE_ENV === 'production' ? '[name]-[hash].css' : '[name].css'),
    new webpack.optimize.CommonsChunkPlugin({
      name: 'vendor',
      minChunks: (module) => {
        // this assumes your vendor imports exist in the node_modules directory
        return module.context && module.context.indexOf('node_modules') !== -1;
      }
    }),
    new ManifestPlugin({
      publicPath: output.publicPath,
      writeToFileEmit: true
    }),
    new webpack.ProvidePlugin({
      $: 'jquery',
      jQuery: 'jquery'
    }),
  ],

  resolve: {
    extensions: settings.extensions,
    modules: [
      resolve(settings.source_path),
      'node_modules'
    ],
    alias: {
      jquery: 'jquery/src/jquery',
    }
  },

  resolveLoader: {
    modules: ['node_modules']
  }
}
```

and I haven't modified the config/webpack/loaders/sass.js file from when it was installed, so it's still like this:

```javascript
const ExtractTextPlugin = require('extract-text-webpack-plugin')
const { env } = require('../configuration.js')

module.exports = {
  test: /\.(scss|sass|css)$/i,
  use: ExtractTextPlugin.extract({
    fallback: 'style-loader',
    use: [
      { loader: 'css-loader', options: { minimize: env.NODE_ENV === 'production' } },
      { loader: 'postcss-loader', options: { sourceMap: true } },
      'resolve-url-loader',
      { loader: 'sass-loader', options: { sourceMap: true } }
    ]
  })
}
```

I have the following files in my "packs" folder:

```
frontend/packs
├── application.js
├── vendor.js
└── vendor.scss
```

vendor.js contains the imports of all the third party libraries, application.js my frontend code and i would like to do the same with the stylesheets.

Any ideas?

**Comment by rhymes** [comment]
It seems like it was a problem of naming.

I've renamed the file "thirdparty.scss", recompiled webpack, changed the statement to `<%= stylesheet_pack_tag 'thirdparty' %>` and magically now everything works

The resulting manifest is now:

```json
{
  "application.js": "http://0.0.0.0:8080/packs/application.js",
  "glyphicons-halflings-regular.eot": "http://0.0.0.0:8080/packs/glyphicons-halflings-regular.eot",
  "glyphicons-halflings-regular.svg": "http://0.0.0.0:8080/packs/glyphicons-halflings-regular.svg",
  "glyphicons-halflings-regular.ttf": "http://0.0.0.0:8080/packs/glyphicons-halflings-regular.ttf",
  "glyphicons-halflings-regular.woff": "http://0.0.0.0:8080/packs/glyphicons-halflings-regular.woff",
  "glyphicons-halflings-regular.woff2": "http://0.0.0.0:8080/packs/glyphicons-halflings-regular.woff2",
  "thirdparty.css": "http://0.0.0.0:8080/packs/thirdparty.css",
  "thirdparty.js": "http://0.0.0.0:8080/packs/thirdparty.js",
  "vendor.js": "http://0.0.0.0:8080/packs/vendor.js"
}
```

This makes me think that "vendor.js" and "vendor.scss" can't co-exist.

**Comment by gauravtiwari** [comment]
@rhymes Basically the earlier issue you had was a conflict between common chunk and your local packs. The packs directory is only for webpack entries - you shouldn't put `.scss` or any other type of file there - also they were using same name as plugin output filename. Please refer to this section - https://github.com/rails/webpacker#app-structure

To fix - move vendor.js and .scss outside of the packs directory and then reference the vendor.js into `application.js`. Also you have to either reference  - `vendor.scss` into `application.js` or `vendor.js` - whatever looks more elegant to you. I would suggest to not use vendor at all if you are using it for common chunk plugin - makes it confusing.

**Comment by rhymes** [comment]
@gauravtiwari thanks for the reply! 

I have this structure now and it works (it's not a component based app for now, it's just the porting of a jquery based traditional web app):

```
frontend/vendor.js
frontend/vendor.scss
frontend/packs/application.js
```

`application.js` contains `import '../vendor'`as the first line
`vendor.js` contains `import 'vendor.scss'` as the first line
`vendor.scss` is as before

The HTML/ERB file contains only `<%= stylesheet_pack_tag 'application' %>` in the `<head>` and `<%= javascript_pack_tag 'application' %>` at the end of the body.

Everything is working!

I am not sure I understand what you said here:

> I would suggest to not use vendor at all if you are using it for common chunk plugin - makes it confusing.

but I guess it is because I am totally new at webpack/webpacker and will have to learn more in the future :-)

**Comment by rhymes** [comment]
@gauravtiwari I was mistaken, the compilation step works but the app now throw this error:

```
application.js:1 Uncaught ReferenceError: webpackJsonp is not defined
```

**Comment by gauravtiwari** [comment]
@rhymes Oh you have to include `<%= javascript_pack_tag 'vendor'  %>` at the top - since that includes all vendor code (from common chunk plugin). 

If it's traditional app than I think you don't need this plugin - the plugin helps if you have a lot of entries/packs and each are using some common modules that you want to extract out to improve pack size so you can deliver smaller chunks using client side router.

If you consider to remove the plugin then no extra setup is required just reference the packs in your views as you are doing now 👍

**Comment by rhymes** [comment]
@gauravtiwari you've been most helpful. I think i'll keep the plugin in for now, because my objective is to slowly rewrite the app to take advantage of those advantages.

Thank you!

**Comment by gauravtiwari** [comment]
> I would suggest to not use vendor at all if you are using it for common chunk plugin - makes it confusing.

I meant to not use same name for the file (inside plugin and pack) - so it's more clear to you. 

Basically both will do same thing one is implicit by design and other is explicit - 

1. If you import vendor code in your js pack file(with common chunk)

```js
// packs/application.js
import 'bootstrap'
import 'dist/bootstrap.css'
// if any app styles
import '../styles/app.scss'
```
outputs => vendor.js and vendor.css and application.js for you to reference in your views. If you have any local app styles then it will also output application.css

2. If you import vendor code in your js pack file(without common chunk)

```js
// packs/application.js
import 'bootstrap'
import 'dist/bootstrap.css'
```

outputs => application.js and application.css for you to reference in your views
