### ISSUE TITLE
Importing styles from node_modules is showing no file or directory error

### ISSUE THREAD

**Issue by johnisaac** [rails/webpacker#489]
Hi, 

   I tried to follow the [instructions](https://github.com/rails/webpacker#from-node-modules-folder) from the wiki to import styles from node_modules. But I keep getting the following error message.

> Module build failed: Error: ENOENT: no such file or directory, open '/Users/johnisaac/code/webpacker_sample/app/javascript/styles/~boostrap/dist/bootstrap.css'

Above line is in a _hello_react.sass_ file with the following content
`@import '~boostrap/dist/bootstrap.css'`

_hello_react.sass_ file is imported in another hello_react.js file like
`import '../styles/hello_react'`

Any help is appreciated.

**Comment by gauravtiwari** [comment]
@johnisaac Please don't use extension it's already added in the extensions list. 

`@import '~boostrap/dist/bootstrap`

**Comment by johnisaac** [comment]
@gauravtiwari When I tried without the extension, it is showing a similar error

> File to import not found or unreadable: ~boostrap/dist/bootstrap.

**Comment by gauravtiwari** [comment]
There is a typo - `~bootstrap/dist/bootstrap`

**Comment by johnisaac** [comment]
I did not include `.` at the end in the source code but it is showing up in the log.

<img width="478" alt="screen shot 2017-06-09 at 7 49 07 am" src="https://user-images.githubusercontent.com/284118/26980864-3b4a2da2-4ce8-11e7-84a7-611c6efbd8d1.png">

<img width="547" alt="screen shot 2017-06-09 at 7 50 37 am" src="https://user-images.githubusercontent.com/284118/26980917-63f77714-4ce8-11e7-8844-f2abb1558cfb.png">

**Comment by johnisaac** [comment]
Ah, I see you what you mean. Thanks!
