### ISSUE TITLE
Insure yarn is installed before running the install template.

### ISSUE THREAD

**Issue by jcoyne** [rails/webpacker#49]
As a n00b, I installed the gem and ran `bin/rails webpacker:install`

Then I saw the generator leave this message:

```
...
         run  ./bin/yarn add --dev webpack@beta webpack-merge path-complete-extname babel-loader babel-core babel-preset-latest coffee-loader coffee-script rails-erb-loader from "."
Yarn executable was not detected in the system.
Download Yarn at https://yarnpkg.com/en/docs/install
``` 

This error message should tell me what to do after I download Yarn. 

Perhaps add a check for yarn prior to here: https://github.com/rails/webpacker/blob/af320768eb5dfe82952238468021aea308a048d8/lib/tasks/webpacker.rake#L20 ?

P.S. I was using rails 5.0.1, which does not have yarn installed by default.  After I ran `brew install yarn` and reran the generator all was well.

**Comment by nicolasblanco** [comment]
Hello, I don't understand the issue there :).

You did not have `yarn` installed and got a nice error message when the script tried to run it, 
what do you want to change exactly?

IMHO, It's not really the current philosophy to put a pile of tests trying to detect all possible missing file or command before actually running the script.
There would be thousands of possible failures for each command.

**Comment by jcoyne** [comment]
@nicolasblanco I'm positing that a good error message tells the user what they did wrong (done) and what they should do now (missing).  It should say "go install yarn **and then run bin/rails webpacker:install again**"

**Comment by dhh** [comment]
This gem isn't currently designed with much intent for 5.0.1. It's intended target is 5.1, where Yarn is available by default. But feel free to submit a PR with a proposal for a different error message.
