### ISSUE TITLE
Importing Sass file results in error

### ISSUE THREAD

**Issue by woniesong92** [rails/webpacker#491]
**Component**

```
import React, { Component } from 'react'
import PropTypes from 'prop-types'

// FIXME: for some reason importing a stylesheet doesn't work?
import './grid.sass'

class Grid extends Component {
  render() {
    return (
      <div className="grid">
        <h2>Grid</h2>
      </div>
    )
  }
}

export default Grid
```

**sass file**
```
.grid {
  color: #e9e9e9;
}
```

**error message**
![image](https://user-images.githubusercontent.com/2935309/27008709-b9c8c552-4e2e-11e7-9fce-f9b54761b2e4.png)

Might be related:
https://github.com/vuejs/vue-loader/issues/174
https://github.com/sass/sass/issues/450

**Comment by gauravtiwari** [comment]
Please rename to .scss file since you got curly's - .sass doesn't have curlys

**Comment by woniesong92** [comment]
@gauravtiwari thank you! The error is gone now, but it seems the style doesn't seem to be applied now.

![image](https://user-images.githubusercontent.com/2935309/27009299-42c31ab4-4e3f-11e7-9f75-56849e77ebc6.png)

```
#Grid/index.js
import React, { Component } from 'react'
import PropTypes from 'prop-types'

import './grid.scss'

class Grid extends Component {
  render() {
    return (
      <div className="grid">
        <h2>Grid</h2>
      </div>
    )
  }
}

export default Grid
```

```
#Grid/grid.scss
.grid {
  color: #e9e9e9;
  font-size: 100px;
}
```

**Comment by gauravtiwari** [comment]
Have you included your styles in the view using `stylesheet_pack_tag? https://github.com/rails/webpacker#inside-views

**Comment by woniesong92** [comment]
@gauravtiwari that was it! thank you :)

**Comment by sai-github** [comment]
adding `;` at the end of import solved my issue
