### ISSUE TITLE
CSS only loading from node_modules

### ISSUE THREAD

**Issue by taniadaniela** [rails/webpacker#496]
Hello there.. I'm having issues loading my css files.. 

 I'm using the config from the css modules section: 
```
const ExtractTextPlugin = require('extract-text-webpack-plugin')
const { env } = require('../configuration.js')

module.exports = {
  test: /\.(scss|sass|css)$/i,
  use: ExtractTextPlugin.extract({
    fallback: 'style-loader',
    use: [
      { loader: 'css-loader', options: {
    minimize: env.NODE_ENV === 'production',
    modules: true,
    localIdentName: '[path][name]__[local]--[hash:base64:5]'
  }},
      { loader: 'postcss-loader', options: { sourceMap: true } },
      'resolve-url-loader',
      { loader: 'sass-loader', options: { sourceMap: true } }
    ]
  })
}
```
and my app/javascript folder structure is the following:
- packs/applications.js
- styles/applications.scss
- styles/main.scss

in styles/applications.scss I import the content of bootstrap and main.scss
```
@import '~bootstrap-sass/assets/stylesheets/_bootstrap.scss';
@import "main.scss";
```
in packs/applications.js I use:
```
import '../styles/application'
```

in my application.html.erb I use the helpers:
``` 
<%= javascript_pack_tag 'application' %>
 <%= favicon_link_tag %>
 <%= stylesheet_pack_tag 'application' %>
```

With all this I see the bootstrap styles but not my styles defined in main.scss... any ideas?
I also tried import '../styles/application.scss'  instead of import '../styles/application' but my styles still not loaded.

I can see that the file http://0.0.0.0:8080/packs/application.css is generated and has all my styles in there but for some reason I'm not able to them in my app.

**Comment by gauravtiwari** [comment]
@taniadaniela The stylesheet file is loading in your browser right - just your `main.scss` styles isn't being applied? Perhaps there is some typo in css classname/ids?

**Comment by taniadaniela** [comment]
There weren't errors on css, the problem seems to be the css modules configuration on the sass loader:
``` 
modules: true,
 localIdentName: '[path][name]__[local]--[hash:base64:5]'
```
I removed those and is loading styles now.. except for the fonts.

**Comment by gauravtiwari** [comment]
@taniadaniela Oh I see - sorry missed the css modules bit. If you are using css modules you would need to manually assign classnames to html tags.

**Comment by gauravtiwari** [comment]
An example is here - https://github.com/rails/webpacker#css-modules. Are you getting any errors for fonts?

**Comment by taniadaniela** [comment]
yes well using modules wasn't working so now I have my styles loaded so I think I'll leave that in teh working way.. and for the fonts I don't get  any error..

I have the following structure in app/javascript/styles:
main.scss
application.scss
fonts/all my fonts files here
fonts.scss
and in this fonts.scss I call the fonts files:
```
@font-face {
    font-family: 'my_font';
    src: font-url('./fonts/myfont-regular-webfont.eot');
    src: font-url('./fonts/myfont-regular-webfont.eot?#iefix') format('embedded-opentype'),
         font-url('./fonts/myfont-regular-webfont.woff2') format('woff2'),
         font-url('./fonts/myfont-regular-webfont.woff') format('woff'),
         font-url('./fonts/myfont-regular-webfont.ttf') format('truetype'),
         font-url('./fonts/myfont-regular-webfont.svg#my_fontregular') format('svg');
    font-weight: normal;
    font-style: normal;
}
```

**Comment by gauravtiwari** [comment]
Its `url` instead of `font-url` - https://github.com/gauravtiwari/webpacker-example-app/blob/374a13cf1207e5fdf3a41960bea736c716100d99/app/assets/javascript/counter/styles/style.sass

**Comment by taniadaniela** [comment]
thanks a lot @gauravtiwari you save my day!
