### ISSUE TITLE
Webpacker with Angular 4 Problem - Uncaught Error: Zone already loaded.

### ISSUE THREAD

**Issue by ncnthuy** [rails/webpacker#497]
Hi,

Currently, I'm using webpacker with Rails to use AngularV4 in my website.
In the homepage, I include a pack: ``ng_toppage.js``.
My homepage URL is: /index, when it has /index/# and click on button back of browser, the error has appeared.
![image](https://user-images.githubusercontent.com/2102816/27065970-effc1ce8-502a-11e7-889e-b88b2c81213c.png)
Please help me!
Regards.

**Comment by gauravtiwari** [comment]
Are you loading zone.js twice? Probably related to this - https://github.com/angular/zone.js/issues/405

**Comment by ncnthuy** [comment]
@gauravtiwari Thanks for your help, I have used Common Chunks and fixed the problem!

**Comment by gauravtiwari** [comment]
@ncnthuy Yepp that's good way to solve vendor lib duplication 👍

**Comment by pankajhirway** [comment]
@ncnthuy Hi, Can you please help me out how you managed to fix your issue ?

**Comment by Rhonun** [comment]
@pankajhirway for me in my test.ts file I had set up I was doing `import 'zone.js/dist/zone'` and that was causing my error

**Comment by patelneel1994** [comment]
Removing that import helps.

**Comment by rahuljograna** [comment]
This is the problem of new firebase update, here is a solution for this error

** Step: 1** Install the lower version of firebase using this command

npm install angularfire2@5.0.0-rc.4

** Step: 2**

npm install

Try.

**Comment by kapilraghuwanshi** [comment]
Not working any solution provided. Please help someone.

**Comment by vedhaperi** [comment]
+1

**Comment by vedhaperi** [comment]
1. remove 'import 'zone.js/dist/zone' in your test.ts. If that does not solve the problem, try 2.
 
2. <script src="https://unpkg.com/zone.js@0.6.23?main=browser"></script>  //remove this or similar line from your index.html.

 In your case, you might have to look for 'ng_toppage' or the file indicated in the error (search in your index.html file) and remove the line.
