### ISSUE TITLE
Do we want an extensible plugins directory? 

### ISSUE THREAD

**Issue by ytbryan** [rails/webpacker#507]
Want to get some consensus before sending in a PR. 

The PR will have these: 
- [ ] Adding of  a `plugins` directory at `config/webpack/plugins` 
- [ ] Refactoring of shared.js to use this plugins directory
- [ ] Making it easier for `webpacker-x` gems developers to drop in webpack plugins

Note that `loaders` is already using a loader directory. Hence, plugins is simply following this pattern. 

At `config/webpack/plugins`

![screen shot 2017-06-16 at 1 07 45 pm](https://user-images.githubusercontent.com/323891/27212599-a3b2b3cc-5293-11e7-888c-4afcf2aeaf9b.png)

At `configuration.js`

```
...
const pluginsDir = join(__dirname, 'plugins')
...
module.exports = {
  settings,
  env,
  loadersDir,
  output,
  pluginsDir
}

```

At `shared.js`

```
....
const { env, settings, output, loadersDir, pluginsDir } = require('./configuration.js')
...
module.exports = {

  plugins: sync(join(pluginsDir, '*.js')).map(loader => require(loader)),

}
```

**Comment by gauravtiwari** [comment]
@ytbryan Yepp thoughts about this earlier but there one major problem with this setup - the ordering of plugins matters and if we are simply syncing them like `loaders` we will get random bugs. The other idea I had was to have a `plugins.js` file and then have plugins per environment: 

```js
module.exports = {
  production: {
    // ... production plugins....
  }

  development: {
    //... development
  }
}
```

But I am not sure how stable this would be (pretty sure stumbled upon something with this too)

**Comment by ytbryan** [comment]
@gauravtiwari  For the ordering, I thought we could use a list of plugins filename in a `plugins.yml` file. Assuming there is `environment.js`, `extract_text.js` & `manifest.js` 

```
order: 
- environment
- extract_text
- manifest
```
When the `plugins.yml` file is present, we will use the order given. The order will generate an array of path `['path_to/environment.js', 'path_to/extract_text.js', 'path_to/manifest.js']`  However, I am not 100% certain if this is worth the effort? What do you think? 

For production & development plugins, I was thinking of using the above technique to create a drop-in directory. ie `config/plugins/production `  & `config/plugins/development`

**Comment by gauravtiwari** [comment]
@ytbryan Yepp, we can do that but like you said probably not worth the effort. It will complicate the whole setup and I am not sure how many issues we might get around this. Perhaps revisit this later?

**Comment by ytbryan** [comment]
agree!

**Comment by ytbryan** [comment]
@gauravtiwari  are you able to point me to some examples of ` the ordering of plugins matters and if we are simply syncing them like loaders we will get random bugs. `
