### ISSUE TITLE
regexp modified by webpacker

### ISSUE THREAD

**Issue by dorkalev** [rails/webpacker#509]
emojiRegex from https://github.com/mathiasbynens/emoji-regex gets added a "?" as last character by webpacker

**Comment by gauravtiwari** [comment]
@dorkalev Don't think it's related to webpacker. Perhaps you have to setup a webpack loader for emojis?

**Comment by dorkalev** [comment]
@gauravtiwari The regexp was modified by webpacker, that's for sure.
