### ISSUE TITLE
304 Not Modified

### ISSUE THREAD

**Issue by Davidzhu001** [rails/webpacker#513]
![image](https://user-images.githubusercontent.com/9436230/27256514-ef294912-537c-11e7-8e8c-ec697837361e.png)

When i try to call json. sometime it returns 304 status to me.

And i have tried to use CORS and configured like this

`Rails.application.config.middleware.insert_before 0, Rack::Cors do
     allow do
       origins '*'
       resource '*', :headers => :any, :methods => [:get, :post, :options]
     end
end`

**Comment by gauravtiwari** [comment]
@Davidzhu001 Not sure if this is related to webpacker but anyway are you caching the response on the client?  - https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/304 

Don't think this is a CORS problem. I think you probably need to calculate and send  - date-modified or ETag header with each request so client expires the cache when it needs to.
