### ISSUE TITLE
Using https breaks Hot Reloading

### ISSUE THREAD

**Issue by woniesong92** [rails/webpacker#515]
If you set `https` to `true` here:

# config/webpacker.yml
development:
  dev_server:
    host: 0.0.0.0
    port: 8080
    https: true

You see `[WDS] Disconnected!` error and hot reloading doesn't work anymore.

**Comment by gauravtiwari** [comment]
@woniesong92 Do you get any errors in the browser? Are you using a https host for rails app too? Seems like WDS isn't connected at all so hot reloading won't work.

**Comment by gauravtiwari** [comment]
Closing, feel free to reopen if still a problem 👍

**Comment by dmc2015** [comment]
This is an issue for me.

This happened after I attempted to turn https on for webpacker.

The rails app and webpacker are both set to https.

I am no longer getting an https error but now I am getting a 


```
GET https://localhost:8080/sockjs-node/info?t=1500582485213 net::ERR_INSECURE_RESPONSE
AbstractXHRObject._start @ 22:132
(anonymous) @ 22:21
```

and

[```
WDS] Disconnected!
log @ 34:45
close @ 34:130
sock.onclose @ 43:15
EventTarget.dispatchEvent @ 20:51
(anonymous) @ 64:356

```

**Comment by yourivdlans** [comment]
I had the same issue but removing the `host` entry didn't work.

The documentation states if you get errors on the `https://localhost:3035/sockjs-node/info` urls. Visit that url and accept the certificate.

https://github.com/rails/webpacker/blob/master/docs/webpack-dev-server.md#https
