### ISSUE TITLE
Intentions regarding webpack-dev-server?

### ISSUE THREAD

**Issue by nathanstitt** [rails/webpacker#52]
Hello,

I've also been experimenting with Ruby / Webpack integration.  My focus has mainly been on getting the developer experience similar to the existing asset-pipeline, but with the assets served via webpack-dev-server, so that source maps work and to utilize hot-reloading.

To that end I've created a few small wrappers for [yarn](https://github.com/nathanstitt/knitter) and [webpack](https://github.com/nathanstitt/ruby_webpack).  Both are extremely embryonic at the moment, and I'm quite happy to abandon them in favor of other solution(s) that are perhaps more established.

Do you envision `webpacker` controlling webpack-dev-server in any way?  My intended solution is to start it in a background process and provide asset tag helpers that would point to the appropriate address/port and paths.   I'd also like the solution to be Rails agnostic so it would work stand-alone, much like Sprockets does, since I also do some work with Sinatra.   If you see those goals as compatible, I'd love to drop the work I've done and contribute to `webpacker`.

Thoughts?

**Comment by renchap** [comment]
I am also thinking about how to be able to use `webpack-dev-server` with Webpacker, specifically to enable hot releoading with my `webpacker-react` gem.
It would be great if we can use `webpack-dev-server` the same way `./bin/webpack-watcher` is currently used, and this would not need much : a config file and a change to `javascript_pack_tag` to load the assets from it.

I planned to do this from my gem, but it would be much better to have this support directly into Webpacker. If this is not desirable,  an alternate solution would be to have a `webpacker-dev-server` gem that would add this support and that you can depend on.

**Comment by dhh** [comment]
I'm open to exploring the use of the dev-server, but I'm not convinced it's worth the extra complexity out the box. I want to make sure that everything is working just as well and easy as with the simple watcher. I heard several stories about hot loading not working too well in all scenarios.

But feel free to propose a PR and let's look at it!

**Comment by renchap** [comment]
I agree this needs to be optional and only enabled if the user has a need for it (or if he uses a webpacker plugin that requires it).

I am thinking about a new `./bin/webpack-dev-server` stub as long as a config option for the user to put in `config/environments/development.rb` to set the dev server host / port (with a default). Probably worth displaying usage for this option when you launch the dev server through the stub if its not set (I dont know if there is a proper way for this?). This way it is all optional.

Would that be a good starting point for you?

**Comment by dhh** [comment]
Yeah, let's give it a try and see how it feels.

**Comment by renchap** [comment]
@nathanstitt webpack-dev-server support is now merged with #55 :)

**Comment by nathanstitt** [comment]
Awesome news @renchap  - going to play with this shortly.  

I'd say we can close this now.  Thanks to all for the replies
