### ISSUE TITLE
HMR is not working nested directory in packs

### ISSUE THREAD

**Issue by ChangJoo-Park** [rails/webpacker#526]
I use webpacker with vue.js
Webpacker is working well with in packs's root directory (hello_vue.js, application.js etc..)
but I add nested directory for namespace like `posts`  for `posts#index` path.

I found webpacker.yml and source_entry_path. Is **packs** mean `packs/**/*` or only `packs/*`?
If it means `packs/*`, How do I use `<%= javascript_pack_tag "posts/index" %>`? 
I created `posts_index.js` in `packs/posts_index.js`. It works well.

please check [this repo](https://github.com/ChangJoo-Park/webpacker-vue-testing-nested-directories) for using nested directory. see `views/posts/index.html.erb`

```
<%= content_tag :div,
  id: "hello-vue",
  data: {
    message: "Hello!",
    posts: @posts,
    name: "David"
  }.to_json do %>
<% end %>
<!--
Not Working
<%= javascript_pack_tag "posts/index" %>
-->
<%= javascript_pack_tag "posts_index" %>


<%= link_to 'New Post', new_post_path %>
```

below my `packs/posts/index.js` file (and packs/posts_index.js same without relative .vue file path)

```
import Vue from 'vue'
import App from './index.vue'

  document.addEventListener('turbolinks:load', () => {
    const node = document.getElementById('hello-vue')
    console.log('node : ', node)
    if (node === null) {
      return
    }
    const props = JSON.parse(node.getAttribute('data'))
    console.log('props from rails ', props)
    const app = new Vue({
      render: h => h(App, { props })
    }).$mount('#hello-vue')
  })
```

**Comment by gauravtiwari** [comment]
@ChangJoo-Park HMR isn't enabled in config. You mean live reloading isn't working?

**Comment by gauravtiwari** [comment]
@ChangJoo-Park I see you got two files with same name - index.vue and index.js which is basically going to compiled down to `.js` file therefore can't use same name.

![screen shot 2017-06-21 at 18 43 22](https://user-images.githubusercontent.com/771039/27398405-8c3db58a-56b1-11e7-9285-463f73966253.png)

![screen shot 2017-06-21 at 18 43 29](https://user-images.githubusercontent.com/771039/27398409-8ffd8d4e-56b1-11e7-8e34-a08ba4e98388.png)

**Comment by ChangJoo-Park** [comment]
Thank you @gauravtiwari It works well. 👍
