### ISSUE TITLE
Instead of just Main, all elm modules are compiled

### ISSUE THREAD

**Issue by Vortex** [rails/webpacker#529]
I am trying to integrate a small app with the latest Rails (5.1.1) and webpacker and I noticed that all elm files are compiled which is really slow. Is this a bug or there is a way to tell webpacker to use just Main module?

**Comment by gauravtiwari** [comment]
@Vortex All elm files? How have you structured your app? Could you share the the directory structure please?

**Comment by Vortex** [comment]
```
javascript/packs/
               application.js
               Main.elm
               View.elm
               Data/
                    Module.elm
```
So, the Main.elm is referenced in application.js and I expected that elm-make will be run only for the Main.elm, but instead there are multiple elm-make calls, for each elm file.

**Comment by gauravtiwari** [comment]
Please move out any elm file that's not main pack i.e. not a webpack entry file. So perhaps:

```yml
app/javascript: 
  - application.js
  - view.elm
 - # etc....
packs: 
  - main.elm
```

**Comment by gauravtiwari** [comment]
Updated the comment - so if application.js is where you are bootstrapping elm component then that needs to be inside packs, rest can be referenced from outside 👍

**Comment by Vortex** [comment]
Yes that's i! I completely ignored the fact that source_path and source_entry_path are different things. Thanks for the helpful response, it's blazingly fast now. :)
