### ISSUE TITLE
How to reference assets in scss with webpacker?

### ISSUE THREAD

**Issue by resting** [rails/webpacker#536]
So I'm using loading my `scss` files in `application.js`. (initialized app with `rails new myapp --webpack=react`).
These images are saved in `app/assets/images/`.
Am running `webpack-dev-server` for dev.

Using `background-image: url('hero1.jpg')` works in dev.
But should I be using `image-url('hero1.jpg')` instead for production since the images will be processed by sprockets?
Problem is using `image-url('hero1.jpg')` isn't parse by `sass-rails` resulting in invalid css rule.

Pretty new to Rails so I might not be doing this right.

**Comment by resting** [comment]
Well, I just tried killing off `webpack-dev-server`, did  `rails assets:precompile RAILS_ENV=production` and `rails s -e production`.

Set `config/environments/production.rb` with `config.public_file_server.enabled = true`.
It seems to serve the assets fine with just `url()`.

**Comment by gauravtiwari** [comment]
@resting Yes, that's supported out of the box unless `config.public_file_server.enabled = true` is disabled.

**Comment by gauravtiwari** [comment]
Okay to close this issue?

**Comment by resting** [comment]
@gauravtiwari Right. I see, cool. Thanks for confirming. Yep. It can be closed.
