### ISSUE TITLE
add option to YML config for "dev_mode"

### ISSUE THREAD

**Issue by justin808** [rails/webpacker#537]
How about an option for:

dev_mode: dev-server | static | DLL

**dev-server** uses the normal live reload and is the default, and does not require the manifest.
**static** uses the normal fingerprinted, manifested assets.
**DLL* uses the webpack DLL which does not fingerprint the assets and does not uses a manifest.

See https://github.com/shakacode/webpacker_lite/issues/20.

**Comment by gauravtiwari** [comment]
@justin808 How this would help?

To me, this will complicate things - three modes just for development environment?
With webpacker the first two modes are pretty trivial to use - just switch the binstubs however I see the DLL mode requires some setup and bit complicated to use. 

Probably leave this to project owners?

**Comment by justin808** [comment]
@gauravtiwari, It turns out that when using the DLL, some assets need to be hashed. So we can close this ticket.
