### ISSUE TITLE
Using Vue components in Rails views

### ISSUE THREAD

**Issue by domi91c** [rails/webpacker#540]
I'm trying to setup the [Buefy](https://buefy.github.io/#/) Vue library, and so far I have it working under app/javascripts, but I'd also like to use the components within my Rails views. I tried doing so, but the components don't appear on the page. I'm not sure what I'm missing, because if I make my own components I'm able to have them appear in my views.

Am I missing some more setup? I installed Buefy through npm and have the hello world for Vue setup.

**Comment by ytbryan** [comment]
any repo to share?

**Comment by domi91c** [comment]
Thanks for that example @ytbryan, but I do have Buefy working within Vue. My problem is that I want to be able to use the components out of the box within my Rails Vues. For example, I'd like to have a basic Bulma navbar, and place a Buefy dropdown within it. I've been able to get this working by creating a Vue app containing just a Buefy dropdown, but I was hoping that I'd be able to use the Buefy dropdown component itself.


Here's what I want to do:

pages/index.html.erb:
```

<%= javascript_pack_tag 'application' %>
<%= stylesheet_pack_tag 'application' %>


<b-dropdown>
  <button class="button" slot="trigger">
    <span>Dropdown</span>
    <b-icon icon="arrow_drop_down"></b-icon>
  </button>

  <b-dropdown-option>Action</b-dropdown-option>
  <b-dropdown-option>Another action</b-dropdown-option>
  <b-dropdown-option>Something else</b-dropdown-option>
</b-dropdown>

```

**Comment by domi91c** [comment]
If what I'm asking for isn't possible, is there some sort of alternative, or will I have to create an app under `app/javascript/` for each Buefy component?

**Comment by gauravtiwari** [comment]
@domi91c I don't know much but yes - if you have a JS component that support `<b-dropdown>` app it should work. You have to include the app to the page though

```erb
<%= javascript_pack_tag 'dropdown' %>
<%= stylesheet_pack_tag 'dropdown' %>
```

**Comment by gauravtiwari** [comment]
In regards to your other question - there is no out-of-the-box `erb` integration
