### ISSUE TITLE
[Question] Can import a file by referencing it relative to the source_path?

### ISSUE THREAD

**Issue by alebian** [rails/webpacker#543]
Hello!

I have a kind of newbie question. I wanted to know if there is a way to reference files in relative to the source_path.

I have the default config:

    # webpacker.yml
    default: &default
      source_path: app/javascript
      source_entry_path: packs
      public_output_path: packs

And in my jsx files I have things like:

    import Something from '../../services/something';

I would like to know if there is a way to configure the project so I can just do:

    import Something from 'services/something';

Thanks!

**Comment by gauravtiwari** [comment]
@alebian There you go - https://github.com/rails/webpacker#using-babel-module-resolver

**Comment by alebian** [comment]
Thanks @gauravtiwari !! Shame on me for not reading the whole README :see_no_evil:
