### ISSUE TITLE
Support for minifying / compressing webpacker:compile output

### ISSUE THREAD

**Issue by ajsharp** [rails/webpacker#544]
Currently the packs produced by `webpacker:compile` are unminified, uncompressed files. The normal asset pipeline files get minified and gzip'd. Are there plans to support this functionality for webpacker? Thanks.

**Comment by renchap** [comment]
They are minified and compressed when compiled in the production environment, unless you changed the default configuration: https://github.com/rails/webpacker/blob/master/lib/install/config/webpack/production.js

**Comment by gauravtiwari** [comment]
`NODE_ENV=production bundle exec rails/rake webpacker:compile` - that should compile production ready assets

**Comment by Hamada92** [comment]
when I try Chrome Audit tool, it says JS can use more minifying.

**Comment by Hamada92** [comment]
<img width="741" alt="screen shot 2018-08-20 at 2 46 41 pm" src="https://user-images.githubusercontent.com/20448796/44360134-eab3eb00-a487-11e8-9a8f-f546e4de5c24.png">

**Comment by renchap** [comment]
Can you provide the URL of a sample file? Did you build it with the production config?

**Comment by Hamada92** [comment]
https://www.coursemate.io/packs/application-d7b96eefba522259c780.js

Yes, NODE_ENV is set to production in my environment variables.

**Comment by Hamada92** [comment]
@renchap any luck?

**Comment by renchap** [comment]
The file looks minified. I am not sure how Lighthouse calculated the gains you can have. After running your file through uglify 2, I get a 9% reduction, but I guess this is because you are not using the latest Uglify version.
I really think this is a Lighthouse problem here.

**Comment by Hamada92** [comment]
On another application, I installed PageSpeed module, and lighthouse got happy and no complains. I will dig into this and report my findings later.
