### ISSUE TITLE
Expose Environment Variables in Webpack Config by Default

### ISSUE THREAD

**Issue by fny** [rails/webpacker#546]
It's fairly reasonable to expect for users to share environment variables between their client-side JavaScript and their Rails app, so why not bake in something like `new webpack.EnvironmentPlugin(Object.keys(process.env))` to the list of plugins by default?

**Comment by renchap** [comment]
This is already done by default: https://github.com/rails/webpacker/blob/master/lib/install/config/webpack/shared.js#L39

**Comment by bbugh** [comment]
This file no longer exists, and I am not able to access Rails environment variables (other than RAILS_ENV) via webpack compiling. Was this feature removed?

**Comment by bbugh** [comment]
Of course, it mysteriously started working immediately after posting, after messing with it for a while. I love/hate when that happens. Nevermind!
