### ISSUE TITLE
Mixed content https issue when running from Heroku

### ISSUE THREAD

**Issue by BobWalsh** [rails/webpacker#547]
rails 5.1.2, webpacker 2.0, and reviewed issues for anything remotely relevant.

In a working rails app on heroku being served as https, hello_react.js is blocked:
"Mixed Content: The page at 'https://example.com/checkin' was loaded over HTTPS, but requested an insecure script 'http://0.0.0.0:8080/packs/hello_react.js'. This request has been blocked; the content must be served over HTTPS."

I assumed that this was the flip side of setting webpacker.yml in dev to https: true. But after adding the following code webpacker.yml, I get the same insecure script message.

my webpacker.yml (note last 2 lines I added)

```
default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_output_path: packs

  extensions:
    - .coffee
    - .erb
    - .js
    - .jsx
    - .ts
    - .vue
    - .sass
    - .scss
    - .css
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg

development:
  <<: *default

  dev_server:
    host: 0.0.0.0
    port: 8080
    https: false

test:
  <<: *default

  public_output_path: packs-test

production:
  <<: *default
  dev_server:
    https: true


What am I doing wrong?

**Comment by gauravtiwari** [comment]
@BobWalsh Why it's using dev server on production? It should use the compiler build. Have you compiled the assets locally and then deployed to heroku?

**Comment by BobWalsh** [comment]
I added dev_server: - my bad. I did a rake assets:precompile; is there a different command for webpacker and react components?

**Comment by gauravtiwari** [comment]
@BobWalsh > I did a rake assets:precompile

You mean locally before deployment?

**Comment by BobWalsh** [comment]
yes.

**Comment by BobWalsh** [comment]
What should I look for to determine if hello_react.js compiled?

**Comment by gauravtiwari** [comment]
Please remove public/assets/* directory and then do heroku deploy - heroku will compile assets automatically for you 👍

**Comment by BobWalsh** [comment]
ok - will give it a try!

**Comment by BobWalsh** [comment]
That was it! Many Thanks @gauravtiwari ! One other small question since it does not seem to be affecting anything. During (dev or production) compilation, I'm seeing the following warnings. What are these about?
```
Building dependencies
remote:        Installing node modules (yarn.lock)
remote:        yarn install v0.27.5
remote:        warning package.json: No license field
remote:        warning No license field
remote:        [1/4] Resolving packages...
remote:        [2/4] Fetching packages...
remote:        warning fsevents@1.1.2: The platform "linux" is incompatible with this module.
remote:        info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
remote:        [3/4] Linking dependencies...
remote:        warning "extract-text-webpack-plugin@2.1.2" has incorrect peer dependency "webpack@^2.2.0".
remote:        warning "rails-erb-loader@5.0.2" has incorrect peer dependency "webpack@2".
remote:        warning "webpack-dev-server@2.5.0" has incorrect peer dependency "webpack@^2.2.0".
remote:        [4/4] Building fresh packages...
remote:        Done in 34.05s.
```

**Comment by gauravtiwari** [comment]
@BobWalsh Just some package version inconsistencies since Webpack 3.0 released recently, should go away soon. You might wanna do `yarn upgrade rails-erb-loader extract-text-webpack-plugin` etc..... in case a patch is released.

**Comment by BobWalsh** [comment]
Thanks for the info @gauravtiwari - looking forward to the upgrade documentation :)

**Comment by matisoffn** [comment]
@gauravtiwari I'm not doing `rake assets:precompile`. My Procfile (deploying to Heroku) looks like this:

```ruby
# Procfile
web: bin/rails server -p $PORT -b 0.0.0.0
webpacker: ./bin/webpack-dev-server
release: bundle exec rails webpacker:compile && rails db:migrate
```

My app was initially an API only version of Rails, but I added webpacker. Not sure if this is causing me trouble. In the build logs, it looks like it's building just fine:

```
remote:
remote: Webpacker is installed 🎉 🍰
remote: Using /app/config/webpacker.yml file for setting up webpack paths
remote: [Webpacker] Compiling assets 🎉
remote: [Webpacker] Compiled digests for all packs in /app/app/javascript/packs:
remote: {"app/App.js"=>"/packs/app/App-20f0ace0968f84ade4c6.js",
```

But when I go into `heroku run bash`, I'm not seeing anything but `robots.txt` in the `public` directory. Any ideas?
