### ISSUE TITLE
Development JS often cached

### ISSUE THREAD

**Issue by terracatta** [rails/webpacker#550]
Related to #267

I am using Webpacker 2.0 extensively in our Rails app with the default generated `development.js` config options.

Many times, my browser (Chrome 59 running on macOS) will cache the contents of the js files produced by webpacker in development (seems random, but I'm sure there are a reproducible set of steps where you could achieve the bad caching behavior).

Upon inspection I see the following webpacker behavior (which I will contrast to assets served by the Rails asset pipeline):

1. Webpacker compiled assets do not contain hashes in development (assets compiled by the asset pipeline contain a hash: `product.self-67a415712cf8c824bc5cf9518a7d2ca725ff07a88d9b7ae73b43c426275c5444.js?body=1`)

1. Webpacker assets are served by my webserver (Using vanillia Puma in dev) without _any_ cache control settings (assets compiled by the asset pipeline are served with `Cache-Control:public, max-age=31536000`)

Someone proposed adding hashes to the dev config in PR #271 but DHH closed it because he thought we should be using cache-control like the Rails asset-pipeline does. But upon actual inspection, it looks like Rails asset pipeline actually hashes the files and asks for them to be cached by the browser.

I think the current Rails Asset Pipeline hashing and caching strategy is sound, robust, and should be ported over to webpacker.

**Comment by gauravtiwari** [comment]
@terracatta Are you using `./bin/webpack-dev-server` binstub or `./bin/webpack`? Does the issue persist with both?

**Comment by terracatta** [comment]
> Are you using ./bin/webpack-dev-server binstub or ./bin/webpack? Does the issue persist with both?

I'm using `./bin/webpack` but we used to use the dev server and I believe the issue persisted there but I can't comment on the cache-control settings on the dev-server.

**Comment by richardvenneman** [comment]
The absence of the `Cache-Control` header actually has caused us some trouble in production as well as CloudFront seems to evict the javascript pack file prematurely (we [share a CDN between staging/production](https://devcenter.heroku.com/articles/please-do-not-use-asset-sync#pipelines)).

**Comment by gauravtiwari** [comment]
Fixed in #653

**Comment by richardvenneman** [comment]
@gauravtiwari while #653 fixes 1, the `Cache-Control` header is still absent (2)

**Comment by gauravtiwari** [comment]
@richardvenneman Right I missed (2). Make sense to add

**Comment by gauravtiwari** [comment]
See #666 for context
