### ISSUE TITLE
vue.erb context

### ISSUE THREAD

**Issue by mdesantis** [rails/webpacker#553]
Hello,

I would like to use some helpers and more extensively the view context inside an `app.vue.erb` template. I expect its context to be the view context, instead it seems to be a not specified context:

```
app.vue.erb
<%= inspect %>
# writes `main`
```

Is it expected? [In the readme](https://github.com/rails/webpacker#using-rails-helpers-in-vue-files) it's written that is possible to use even helpers

**Comment by gauravtiwari** [comment]
@mdesantis Hey, unfortunately not everything is available. Just the one documented here - https://github.com/rails/webpacker#using-helpers

**Comment by mdesantis** [comment]
Uh, ok, thank you, I didn't read that line

**Comment by mdesantis** [comment]
Cycles are not supported neither? I have trouble using `form_with`:

```
<% include ActionController::Base.helpers %>

<template>
  <%= form_with model: [:'admin_home', Cover.new], local: true, builder: BulmaFormBuilder, html: { autocomplete: 'off' } do |form| %>
    <div id="admin_cover_form">
      <p class="asd">{{ message }}</p>
    </div>
  <% end %>
</template>
```
