### ISSUE TITLE
Too much resolve.extensions causing slow build time

### ISSUE THREAD

**Issue by tai2** [rails/webpacker#555]
# Problem

webpacker generates a config file which includes 13 extensions in `resolve.extensions`.
This results in significant build time increase.

I wrote a simple example code. You can make sure this really happens.
https://github.com/tai2/webpack-build-time-increase-example

This probably is a problem of webpack's module resolving algorithm so I reported it in there repo.

[Large resolve.extensions make build process slower significantly #5205](https://github.com/webpack/webpack/issues/5205)

But I think this problem may not be resolved soon because:

* Such a large resolve.extensions is unusual.
* This problem is not an easy problem as long as I inspected. I struggled webpack's codebase to fix it and I gave it up.
* They have already full of issues.

# Suggestion

How about limiting `resolve.extensions` to fewer number?
For example:

```
extensions: ['', '.js', '.jsx', '.json']
```

This is a typical setting many projects uses.

Note that this doesn't mean you cannot import `.erb`, `.png`, etc.
This just means webpack doesn't look up `.erb` file when you omit the file extensions.
So you can still import `.erb` file by `import 'foo.js.erb;'`

Besides this, I think containing whole supported extensions in `resolve.extensions` makes code difficult to read. For instance, you omit the extensions such as:

```
import foo from './foo';
```

What kind of file is this? You cannot know until you really search for directories.
Omitting file extensions hiding a cue from your code especially when it includes many possible extensions.

And finally, you can provide superior experience to users by shorter build time.

# Reference

https://webpack.js.org/configuration/resolve/#resolve-extensions

**Comment by gauravtiwari** [comment]
@tai2 That's good point and I noticed that too - default extensions at the moment are way too much. Will push a PR to fix this 👍

**Comment by tai2** [comment]
Referred in the above webpack issue,  I found that this performance problem depends on my specific environment. Configuration change is less important than I thought it was.

**Comment by gauravtiwari** [comment]
@tai2 Right I see, generally the performance impact is about 1 - 1.5sec although I have benchmarked it properly.
