### ISSUE TITLE
Import styles from /app/assets/stylesheets

### ISSUE THREAD

**Issue by frazboyz** [rails/webpacker#556]
Is it possible to import styles from /app/assets/stylesheets into your pack files? for example, App.vue?

**Comment by renchap** [comment]
One way is to add `/app/assets` to your Webpack load path. In `config/webpack/shared.js, change:

```es6
  resolve: {
    modules: [
      resolve(settings.source_path),
      resolve('app/assets'), // add this line
      ...
    ]
  }
```

You can then require your stylesheets like this:

```es6
import style from 'stylesheets/file'
```

**Comment by gauravtiwari** [comment]
Or, use module resolver plugin - https://github.com/rails/webpacker#using-babel-module-resolver

I am in the process of getting a PR ready to allow the resolved paths to be configurable.

**Comment by frazboyz** [comment]
@renchap That seems to have worked but after I import the style, how do i use it in my scoped scss?

**Comment by renchap** [comment]
You can import it from your SCSS file directly:

```scss
@import '~stylesheets/file.scss';
```

If your question is about how to use the scoped SCSS file in your JS, please look at `style-loader` documentation: https://github.com/webpack-contrib/style-loader
