### ISSUE TITLE
Cannot import css and .erb from external templates with angular.

### ISSUE THREAD

**Issue by rabinpoudyal** [rails/webpacker#558]
I am using angular 4 for my project. I want to keep my html.erb and .css files separate from js files. I tried the following in my component.ts file. I did some configuration to load external html using the webpacker docs. But it is not letting me import .html.erb file. As well as the css file cannot be loaded. I also tried to load sass file but not working.

import templateString from './templatestring.html.erb';
import styles from './styles.css'

And in my component class

templateUrl: templateString
styleUrls: ['./style.css']

And this is giving error and not working. Please tell me how to fix this issue. I don't want to use inline template and stylesheet.

**Comment by gauravtiwari** [comment]
@rabinpoudyal What errors you getting? I am assuming it has to do with module definition for css and erb.

**Comment by rabinpoudyal** [comment]
My component is `import { Component } from '@angular/core';
import templateString from './template.html';
import styles from './styles.css'

@Component({
  selector: 'product-search',
  template: templateString,
  style: styles
})
export class ProductSearchComponent {
  name = 'Angularddd!';


}
`
My module is
`import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { ProductSearchComponent } from './app.component';


@NgModule({
  declarations: [
    ProductSearchComponent
  ],
  imports: [
    BrowserModule
  ],
  providers: [],
  bootstrap: [ProductSearchComponent]
})
export class ProductSearchModule { }
`

Server gives error cannot import css file and it need loader of particular type. I chaged the webpacker loader configurations as given by docs. But not working. I also have index.html.erb file so I want to convert it into angular template. I have <%= %> erb templating inside my views but importing .html neglects those erb expressions and I cannot import .html.erb too. Please tell me what is wrong?

**Comment by gauravtiwari** [comment]
@rabinpoudyal Alright I will take a look at this - seems like `ts-loader` also needs `erb-loader` to compile erb tags and same I guess for styles.

**Comment by gauravtiwari** [comment]
@rabinpoudyal Were you able to figure this out?

**Comment by gauravtiwari** [comment]
@rabinpoudyal Apologies for late reply. Can't you do Ajax post to server from your angular component instead of template?

**Comment by rabinpoudyal** [comment]
Thanks @gauravtiwari . You can close the issue.

**Comment by gspreer** [comment]
Yes, that was the solution I came up with as well. Thanks for the reply.
