### ISSUE TITLE
Support for code splitting?

### ISSUE THREAD

**Issue by rossta** [rails/webpacker#560]
I wanted to open the discussion as to whether the default Webpacker configuration should take a stance on code-splitting, which can yield better build times and improved caching. There appear to be a few popular approaches, including using the `CommonChunksPlugin` and the `DllPlugin`+`DllReferencePlugin`. The "Dll" approach appears to be more powerful but would impact the design of current Webpacker config more significantly.

Thoughts?

* https://webpack.js.org/plugins/commons-chunk-plugin/
* https://robertknight.github.io/posts/webpack-dll-plugins/

**Comment by gauravtiwari** [comment]
@rossta Hey, thanks for opening the discussion here. I have been thinking about chunking setup but didn't arrive to any final conclusion, mainly because of the varied use cases and probably this might make usage bit confusing i.e. adding an extra vendor file along with the pack file. At the moment common chunk setup lives in the Readme and there is no documentation on using DLL plugin. Perhaps we just document the usage? What do you think?

**Comment by rossta** [comment]
@javan Thanks for your thoughts. I can see your point about varied use cases and possible confusion. We're trying to evaluate how best to maintain our Webpack js config files as we add functionality and our config starts to diverge from the Webpacker generated config through gem version upgrades. For now, documentation and careful merges seem the simplest path forward. I'd be happy to submit README  documentation if we decide to go ahead with the DLL plugin to support code splitting in our app.

**Comment by lucaspiller** [comment]
I apologise for reviving a dead issue, but @rossta did you find any solutions that work well with Webpacker? Our application has grown, and it now takes around 90s for a complete rebuild, so we would like to split up the build process.

**Comment by rossta** [comment]
@lucaspiller We're using the `CommonsChunkPlugin` similar to what's [documented in Webpacker](https://github.com/rails/webpacker/blob/master/docs/webpack.md#add-common-chunks). We haven't yet investigated the DLL plugin, but there was some discussion in #702 that may be helpful. No experience yet either with any async or on demand loading.
