### ISSUE TITLE
Many links to README now broken

### ISSUE THREAD

**Issue by unikitty37** [rails/webpacker#561]
A number of issues have the following link in their answers: https://github.com/rails/webpacker#linking-to-static-assets. However, https://github.com/rails/webpacker/pull/372 removes the anchor used in these links.

Would it be possible to re-insert the anchor at an appropriate point, so that there aren't a bunch of non-functional links? Maybe as an empty anchor tag, if GitHub's Markdown lets you do that…

**Comment by ytbryan** [comment]
Thanks for pointing this out. 

Hopefully, anyone reading this will know that this is the correct link to the above broken link https://github.com/rails/webpacker#linking-styles-images-and-fonts
