### ISSUE TITLE
Problems with sysmlink in vagrant

### ISSUE THREAD

**Issue by stvmachine** [rails/webpacker#562]
I read in the issue #229, if i use the latest version of master branch of webpacker its gonna work in Vagrant with Ubuntu:

gem 'webpacker', github: 'rails/webpacker'

But i still get the problems with sysmlink, i dont know the installation is ok or not, because say have errors but say the webpacker was successfully installed. I know yarn and npm can use the flag '--no-bin-links' and with that in vagrant works ok, but i dont how to pass thats args to the yarn in webpacker.

![image](https://user-images.githubusercontent.com/27148250/28079340-f0ebdf82-6635-11e7-864e-a3a94386b7f9.png)

**Comment by eimhin** [comment]
This is also happening to me.

**Comment by gauravtiwari** [comment]
Is this still a problem? Don't think this is related to webpacker though.

**Comment by estvmachine** [comment]
Yes still don't have solution. I think its a direct problem with webpacker because offuscate the process of use yarn with Params like --symlink

**Comment by gauravtiwari** [comment]
@estvmachine Not sure I understood. What do you mean? Do you need to pass that argument to yarn?

**Comment by gauravtiwari** [comment]
Have you tried this comment? https://github.com/mitchellh/vagrant/issues/6188#issuecomment-171396607
