### ISSUE TITLE
Webpacker Generated Assets Have Wrong Digests

### ISSUE THREAD

**Issue by bryanleetc** [rails/webpacker#563]
Getting this issue on a Rails app deployed using AWS Opsworks.

Using `javascript_pack_tag 'home'`, the resulting file generated is `packs/home-3ee57b398448ab07fd94.js`, but my manifest.json is actually `packs/home-a7362a3b4cd8a54e420c.js`. As you can see, the digest fingerprint is different from the one in manifest.json.

However, this problem is not universal across all webpacker generated assets. Some assets actually reference the correct fingerprint. If I go into the console and do `Webpacker::Manifest.lookup`, the digest fingerprint is correct.

**Comment by gauravtiwari** [comment]
You mean the `home` asset has correct fingerprint if you do lookup from console i.e. `Webpacker::Manifest.lookup` but not in the browser?

**Comment by bryanleetc** [comment]
Sorry I didn't make it too clear ust now. Correct, the home asset has the correct fingerprint in console but not in the browser.

There are also some webpacker asset files that have the correct fingerprint in the browser though,

**Comment by gauravtiwari** [comment]
No worries. May be the old assets are still cached? Have you tried in incognito mode?

**Comment by bryanleetc** [comment]
Just tried, still the wrong fingerprint. I've tried using Webpacker::Manifest.lookup in the views but no success.

One thing I noted is that the asset with the correct fingerprint is called directly in `layouts/application.slim`. The other asset files with the wrong fingerprints are called under `content_for :javascript` and `yield :javascript`. I've not tested this out yet, but would this be an issue?

I have another app deployed with assets called the same way but no issue there.

**Comment by gauravtiwari** [comment]
Are you using Rails fragment caching?

**Comment by bryanleetc** [comment]
Nope, not at all!

**Comment by gauravtiwari** [comment]
hmm that's strange - can't think of anything else. Perhaps you may want to debug more and see where you get to 👍  `content_for :javascript` and `yield :javascript`

**Comment by bryanleetc** [comment]
I ended up creating a new app and copying everything over, not sure what's the actual cause but problem solved.
