### ISSUE TITLE
autoprefixer / postcss-cssnext don't appear to be prefixing

### ISSUE THREAD

**Issue by unikitty37** [rails/webpacker#567]
In one of my .scss files, there is a class with `flex: 1 0 0;` on it. When I inspect an element having that class in the browser, I don't see any prefixes applied.

I've tried switching to postcss-cssnext, as per #344, but that doesn't do anything either. I can see prefixes on the CSS assigned to other elements, but I suspect Bootstrap is inserting those itself.

My `config/webpack/loaders/sass.js` is default, as far as I can see:

```js
const ExtractTextPlugin = require('extract-text-webpack-plugin')
const { env } = require('../configuration.js')

module.exports = {
  test: /\.(scss|sass|css)$/i,
  use: ExtractTextPlugin.extract({
    fallback: 'style-loader',
    use: [
      { loader: 'css-loader', options: { minimize: env.NODE_ENV === 'production' } },
      { loader: 'postcss-loader', options: { sourceMap: true } },
      'resolve-url-loader',
      { loader: 'sass-loader', options: { sourceMap: true } }
    ]
  })
}
```

I'm not sure whether it's reading the browser list, which I have put in .postcssrc.yml:

```yml
plugins:
      postcss-smart-import: {}
      postcss-cssnext:
        browserslist:
          - last 2 versions
          - IE >= 9
          - iOS >= 9
          - > 1%
```

Is that even the right place to configure it? None of the examples and documentation I can find for PostCSS in the context of a Rails 5.1 application, so it's a bit difficult to work out where this should go…

**Comment by gauravtiwari** [comment]
Hey, thanks for filing this. Seems to work for me: 

![screen shot 2017-07-15 at 21 42 36](https://user-images.githubusercontent.com/771039/28242534-8e9e827a-69a6-11e7-865c-11e457b8f9b4.png)

```yml
plugins:
  postcss-smart-import: {}
  postcss-cssnext: {}
```

```js
const ExtractTextPlugin = require('extract-text-webpack-plugin')
const path = require('path')

const { env } = require('../configuration.js')
const postcssConfig = path.resolve(process.cwd(), '.postcssrc.yml')

module.exports = {
  test: /\.(scss|sass|css)$/i,
  use: ExtractTextPlugin.extract({
    fallback: 'style-loader',
    use: [
      { loader: 'css-loader', options: { minimize: env.NODE_ENV === 'production',  } },
      { loader: 'postcss-loader', options: { sourceMap: true, config: { path: postcssConfig } } },
      'resolve-url-loader',
      { loader: 'sass-loader', options: { sourceMap: true } }
    ]
  })
}
```

**Comment by unikitty37** [comment]
Thanks for posting your loader — I wasn't passing the config to postcss-loader.

However, it still is not prefixing stuff:

![screen shot 2017-07-16 at 09 58 56](https://user-images.githubusercontent.com/139183/28246262-ca462ad2-6a0d-11e7-98e4-1174a216813d.png)

I tried switching that statement to just be `flex: 1;` in case the three-parameter version can't be prefixed for some reason, but it didn't make any difference. Do you have any idea what could be causing this?

(Incidentally, is my syntax for specifying the browser list correct? It's a bit hard to find YAML-based examples, and the Rails guides don't seem to have been updated for Webpack integration yet…)

**Comment by gauravtiwari** [comment]
@unikitty37 Is that Rails application.js file you are inspecting? The file in the screenshot seems to be referring the source from `application.self.hash.css`. Could you please check the Webpacker compiled css file?

**Comment by unikitty37** [comment]
The definition is in a .scss file that's included from `app/assets/stylesheets/main/application.scss`, which in turn is referenced by `*= require_tree ./styles` in `app/assets/stylesheets/application.css`. 

Experimenting with `application.html.erb` shows that all the styles are still coming in from `<%= stylesheet_link_tag 'application' %>` and not `<%= stylesheet_pack_tag 'application' %>` — I can remove the latter with no effect on what's rendered — so it looks like Rails is not sending the stylesheets through Webpacker at all.

The Rails edge guides still don't seem to mention Webpacker apart from the 5.1 release notes, which don't tell you how to use it. Could you please tell me what I need to do to make the SCSS go through all the loaders specified in `webpack\loaders\sass.js` and get packed by Webpacker?

**Comment by gauravtiwari** [comment]
@unikitty37 Ahh I see, that's why. You would need to include your stylesheets to your pack whatever you consider is the main pack and then it will go through webpacker. 

```js
//packs/main.js
import '../../app/assets/stylesheets/application.css'
```
this will output a main.css file for you to include in your view using `stylesheet_pack_tag`. Makes sense? Asset pipeline and Webpacker are two different worlds :)

**Comment by gauravtiwari** [comment]
Please also checkout this section - https://github.com/rails/webpacker#using-babel-module-resolver

**Comment by unikitty37** [comment]
Thanks — it doesn't appear to be running the stuff through the asset pipeline before importing, though, as now stylesheet_pack_tag is just returning this, which is the unprocessed application.css:

```css
/*
 * This is a manifest file that'll be compiled into application.css, which will include all the files
 * listed below.
 *
 * Any CSS and SCSS file within this directory, lib/assets/stylesheets, or any plugin's
 * vendor/assets/stylesheets directory can be referenced here using a relative path.
 *
 * You're free to add application-wide styles to this file and they'll appear at the bottom of the
 * compiled file so the styles you add here take precedence over styles defined in any other CSS/SCSS
 * files in this directory. Styles in this file should be added after the last require_* statement.
 * It is generally better to create a new file per style scope.
 *
 *= require_self
 *= depends_on /initializers/variables.scss;
 *= require_tree ./styles
 */
```

I'm hoping I don't have to manually include everything in the 'styles' folder in order to use Webpacker…

**Comment by gauravtiwari** [comment]
@unikitty37 Yes, you would need to do that since webpacker can't read sprockets manifest.

**Comment by unikitty37** [comment]
Thanks — I've added the following lines to `packs/application.js`, but I still don't get any styles:

```js
import '../../assets/stylesheets/styles/application.scss';
import '../../assets/stylesheets/styles/home.scss';
```

I assume it's trying to import them as Javascript. 
Could you tell me where to manually include them, please? Is there a link to a sample app where everything's already set up correctly?

(Given Rails is supposed to be about convention over configuration, shouldn't there be a specified folder where we can drop SCSS files and have the loader automatically pass them through Webpacker, rather than having to write all this config? :)

PHP is really starting to look attractive once more…

**Comment by gauravtiwari** [comment]
Have you added `<%= stylesheet_pack_tag('application') %>` to the view?

**Comment by gauravtiwari** [comment]
@unikitty37 Sorry about the confusion. In nutshell, both sprockets and webpacker does same thing except Webpacker is built to allow bundling using Webpack, which offers more advanced javascript features through babel and npm modules (es6 syntax and watnot). 

I made an example app here, so feel free to check it out: 
https://github.com/gauravtiwari/webpacker-example-app/blob/master/app/assets/javascript/entries/hello_react.jsx#L9
https://github.com/gauravtiwari/webpacker-example-app/blob/master/app/views/pages/index.html.erb#L28

1. https://github.com/gauravtiwari/webpacker-example-app
2. https://github.com/gauravtiwari/webpacker-react-frontend
3. https://github.com/gauravtiwari/rails-webpacker

**Comment by unikitty37** [comment]
Thanks — I know about the stuff in the first para, but the code seems to have leapt on ahead of the documentation: searching for `site:edgeguides.rubyonrails.org webpacker` just produces the release notes and no actual guide!

I'm looking at the example apps, and it's still rather confusing: **stylesheets** are in app/assets/**javascript**/entries in webpacker-example-app, while the layout of webpacker-react-frontend seems to be completely different from a standard Rails app. There doesn't seem to be any reference to `stylesheet_pack_tag` in rails-webpacker, so I'm assuming it's not going to be helpful.

Is there no way to tell Webpacker "JavaScript files are in app/assets/javascript_webpacker, CSS files are in app/assets/stylesheets_webpacker. Go pack the JavaScript into application.js, and the CSS into application.css"? That's a sufficiently sensible layout that it should probably be the default, TBH — convention over configuration, and all that.

**Comment by gauravtiwari** [comment]
@unikitty37 Yes, webpacker docs are not available on guides yet.  

> Is there no way to tell Webpacker "JavaScript files are in app/assets/javascript_webpacker, CSS files are in app/assets/stylesheets_webpacker. 

Yes, it is. You can change paths from config/webpacker.yml. The idea was to keep the webpacker related files separate since people might use both in an application. 

Pushed another example for you here that uses `app/assets` paths: https://github.com/gauravtiwari/webpacker-sprockets

**Comment by gauravtiwari** [comment]
To run: 

```
bundle
yarn
foreman start -f Procfile.dev
```

**Comment by unikitty37** [comment]
That seems to have worked. I'm still not sure why it was refusing to load stylesheets from the other location, but they're in there now; I just needed to change the relative path of a background-image to get everything as it should be.

Thanks for all your help — hopefully all this will prove useful to somebody else who finds it, as well :)

**Comment by nicmosc** [comment]
Hi, I'm having the same issues but following what was written above does not help... still no autoprefixer.

These answers are around 1 year old so maybe with all the new package versions some things got lost. Here is what I'm currently using:
- Webpacker (gem) 3.5.5
- @rails/webpacker 3.5
- webpack-dev-server 2.11.2

I've tried all of the above plus javascript only options to load the autoprefixer plugin but nothing seems to work:
```
environment.loaders.append("less", {
  test: /\.less$/,
  use: ExtractTextPlugin.extract({
    fallback: "style-loader",
    use: [
      {
        loader: "css-loader",
        options: {
          sourceMap: true,
          localIdentName: "[name]__[local]--[hash:base64:5]",
          importLoaders: 1,
        },
      },
      {
        loader: "postcss-loader",
        options: {
          ident: "postcss",
          sourceMap: true,
          config: { path: postcssConfig },   // following the answer https://github.com/rails/webpacker/issues/567#issuecomment-315561363
          // plugins: () => [ autoprefixer ],
        },
      },
      {
        loader: "less-loader",
        options: {
          sourceMap: true,
          strictMath: true,
        },
      },
    ],
  }),
});
```

And the .postcssrc.yml
```
plugins:
  postcss-import: {}
  postcss-cssnext: {}
  postcss-smart-import: {}
```

Do you have any idea what could be wrong?
