### ISSUE TITLE
asset_pack_path fails with webpack-dev-server

### ISSUE THREAD

**Issue by cbothner** [rails/webpacker#568]
Using webpack-dev-server locally and trying to configure a preload link, `asset_pack_path` fails with 
```
ActionView::Template::Error (Can't find case in /vagrant/public/packs/manifest.json. Is webpack still compiling?)
```

`javascript_pack_tag` works just fine.

**Comment by gauravtiwari** [comment]
@cbothner You would need to add extension as well to the file, for ex: case.js

**Comment by cbothner** [comment]
This works. Thanks much.
