### ISSUE TITLE
this._ir.once is not a function

### ISSUE THREAD

**Issue by mbajur** [rails/webpacker#570]
Hello!

I just started to use webpacker for my new rails + vue based project and i need to admit i love it! Thanks for this amazing piece of software.

However, in 1 in ~10 file saves and rebuilts, it throws a bunch of errors in javascript console and sometimes rebuilding the bundle several times fixes it but most of the times - i need to restart the yarn process. That's pretty random thing. 

The error is (there are 3 of them):

```
Uncaught TypeError: this._ir.once is not a function
    at new SockJS (main.js?8e93:122)
    at socket (socket.js?e5d0:7)
    at Object.eval (client?8505:165)
    at eval (48:190)
    at Object.<anonymous> (hello_vue.js:640)
    at __webpack_require__ (hello_vue.js:20)
    at Object.<anonymous> (hello_vue.js:3134)
    at __webpack_require__ (hello_vue.js:20)
    at hello_vue.js:63
    at hello_vue.js:66
```

```
Uncaught TypeError: this.xo.once is not a function
    at new InfoAjax (info-ajax.js?7213:21)
    at Function.InfoReceiver._getReceiver (info-receiver.js?aa33:39)
    at InfoReceiver.doXhr (info-receiver.js?aa33:56)
    at eval (info-receiver.js?aa33:25)
```

```
abstract-xhr.js?c769:21 Uncaught TypeError: self._start is not a function
    at eval (abstract-xhr.js?c769:21)
```

It doesn't looks like an error on my side as i can randomly fix it with rebuilding. On the other hand, i'm not too experienced with webpack internals so i can't say anything more about it. 

Thanks!

**Comment by VitorLuizC** [comment]
The same is happening to me. But i'm not using webpacker, just webpack and some loaders and plugins to bundle a Vue project.

It started after update `extract-text-webpack-plugin` and `webpack`

**Comment by gauravtiwari** [comment]
@mbajur Hey, thanks for filling the issue. Seems like this is related to SockJS. Have you tried rebuilding using webpack binstub instead of dev-server?

```
./bin/webpack
```

 Perhaps try upgrading your dependencies - `yarn upgrade` or upgrade dev-server.

**Comment by mbajur** [comment]
Hey @gauravtiwari, sorry for a delay, i was not able to do a yarn upgrade (was a bit scared tbh) but i did today and it's still failing the same way.

About the binstubs rebuilding - can you elaborate on it a bit? I'm not sure how to use that tip.

PS. I have an impression it has something to do with css in `.vue` files as this problem happens mostly when i'm starting to edit the <style> block of my `.vue` files.

**Comment by gauravtiwari** [comment]
@mbajur Are you using webpacker from master or 2.0?

**Comment by mbajur** [comment]
I'm on 2.0

**Comment by gauravtiwari** [comment]
@mbajur Could you please clone this repo and see if you can reproduce it? https://github.com/gauravtiwari/testwebpacker

Feel free to make a PR if you think something is missing in this setup vs yours. 

## To run

```
bundle
yarn
gem install foreman
foreman start
```

**Comment by mbajur** [comment]
Ok @gauravtiwari - i've made a PR with a setup pretty much like my local one. It's here: https://github.com/gauravtiwari/testwebpacker/pull/1

The bad news is that i'm not able to reproduce the issue. In my real setup, literally each save of `app/components/Bookmarks.vue` ends up with the error described above while in this repo, it seems to be fine. Is that anyhow helpfull to you guys?

**Comment by mbajur** [comment]
The only thing that comes to my mind is to give access to my real-world repo to any webpacker contributor. If that's a good idea, just let me know :)

**Comment by ytbryan** [comment]
Public repo? Share it and I will try to figure out when i'm free

**Comment by mbajur** [comment]
No, unfortunately it's not public but i can manage to add someone trustworthy (webpacker contributor) to it if needed.

New observation: i just noticed that this thing happens when i'm adding a style block to my .vue file component. If i have a component without `<style>`, each build succeeds. After adding a style block - it starts to throw errors.

What's more - when my app is in an "exception state", i can excape from that state by resaving any other component which has no `<style>` block in it.

**Comment by gauravtiwari** [comment]
@mbajur thanks for making the PR. I will take a look - I am suspecting it's related to inlining styles within packs.

**Comment by willin** [comment]
meet same problem when using vue

**Comment by willin** [comment]
<img width="1054" alt="wx20170810-203546 2x" src="https://user-images.githubusercontent.com/1890238/29170520-96b4998e-7d9e-11e7-92a4-c761f1c63999.png">

**Comment by gauravtiwari** [comment]
@mbajur Could you please try latest master? You would need to reinstall webpacker and also vue (replace update old config)

**Comment by mbajur** [comment]
@gauravtiwari i've updated webpacker to master, runned `./bin/rails webpacker:install:vue` to replace old configs and restarted the server/webpacker-dev and it's still the same. Srtup crashes the same way for `.vue` files with styles applied.

**Comment by gauravtiwari** [comment]
and `./bin/rails webpacker:install` as well?

**Comment by mbajur** [comment]
Oh, right. I forgot about that but did it now and the error is still there.

**Comment by gauravtiwari** [comment]
@mbajur Right I see. Webpacker doesn't really control any JS side so it could be that `sass-loader` or `vue-loader` or it's family got updated at some point and broke something for you. 

BTW, I would need to look into the findings you posted earlier and see if I can get to something 👍

**Comment by gauravtiwari** [comment]
On another note, have you tried deleting `node_modules` and reinstalling again?

**Comment by mbajur** [comment]
Yeah, i removed node_modules and installed everything from scratch - the error is still there :(

**Comment by mbajur** [comment]
@gauravtiwari what's actually causing this error? Is it webpacker gem or rather one of the dependencies used for webpack setup?

I'm asking because this issue is closed but i'm still facing the bug + i would love to continue this thread here or in the broken dependency github page, in separate issue.
