### ISSUE TITLE
Bind address configuration confusion & best practices

### ISSUE THREAD

**Issue by inopinatus** [rails/webpacker#572]
I'm concerned about the way the bind address for the development server is configured.

Binding to 0.0.0.0 by default is unsafe, it puts anyone using shared/untrusted networks at risk.

Is there a good reason not to have behaviour congruent to Rack behaviour, which defaults to localhost in development unless otherwise configured? See https://github.com/rack/rack/commit/28b014484a8ac0bbb388e7eaeeef159598ec64fc and this was confirmed in Rails 4.2 release notes.

I also think 99% of people, on seeing a configuration option for "host" and "port" in a section named "something_server" will be astonished to learn that it does not configure the host, but does configure the port, for that server. Surely a mistake? There's basically no way to configure the host binding short of editing bin/webpack-dev-server.

I think webpacker should, as much as possible, follow the same defaults and conventions as rack & rails with the listeners and asset URLs, with optional config of either in webpacker.yml.

Happy to put together a PR expressing this opinion.

**Comment by dhh** [comment]
Happy to see an option for this to be configured 👍
