### ISSUE TITLE
Is there a way to pass datas from the view to the js?

### ISSUE THREAD

**Issue by Drillan767** [rails/webpacker#575]
I'd  want to create a condition where some links appear if the user is connected with devise.
With react-rails and some others, I could do `<%= react_component('Hello', user_signed_in: current_user) %>` from the view, and I could get an id, so I knew the user was authenticated.

But now, how can I do that? I'm not a huge fan of working with cookies and so on, because I'd like to let devise on its own without editing the "after login / after logout" procedure.

I also found [this solution](https://github.com/rails/webpacker/issues/163), but it doesn't help at all.

**Comment by gauravtiwari** [comment]
@Drillan767 Did you see this section in the docs? https://github.com/rails/webpacker#pass-data-from-view
