### ISSUE TITLE
Webpacker not importing

### ISSUE THREAD

**Issue by dmc2015** [rails/webpacker#579]
webpacker is not seeing my directory and is giving me 

```
ERROR in ./app/javascript/packs/application.js
Module not found: Error: Can't resolve 'gorails'
```

when I try to compile.

I recently turned https on, I am not getting any errors from my console for https and I have a console.log in 'app/javascript/packs/application.js' that loads works.

I am trying to import  
this 
'app/javascript/packs/gorails/index.js'
```
export default { gorails: true }
```

in to application.js
```
import GoRails from 'gorails'
console.log('Hello World')
```

and the importing is causing the error.

I have tried running 
```
bin/webpack-dev-server --d
```
but it doesn't seem to give any extra details to help me solve the issue.

**Comment by dmc2015** [comment]
Is there something else I can change to make sure it picks up everything in the packs folder or another command I can use to debug?

**Comment by dmc2015** [comment]
Also during my build it shows the file and the folder:

  Asset       Size  Chunks                    Chunk Names
gorails/index.js     868 kB       0  [emitted]  [big]  gorails/index
  application.js     870 kB       1  [emitted]  [big]  application
   manifest.json  136 bytes          [emitted]         




[85] multi (webpack)-dev-server/client?https://0.0.0.0:8080 ./app/javascript/packs/gorails/index.js 40 bytes {0} [built]
  [86] ./app/javascript/packs/gorails/index.js 33 bytes {0} [built]
    + 72 hidden modules


So I am not sure what is going on here.
Any help would be appreciated.

**Comment by gauravtiwari** [comment]
@dmc2015 Can you change the host in `webpacker.yml` please to `localhost`? There is a fix on the master but not yet released. 

What is the problem with referencing the components? Do they live in the same folder?

**Comment by dmc2015** [comment]
I changed it to localhost, didn't have any effect. Should it make a difference?

I am relatively new to webpack and es6, please excuse and correct my approach or verbiage.

This is the general configuration/pattern I am using:
app -- >
           javascript -- > 
                    packs -- > 
                           Module
                                  ----> utiltiy/submodule.js
                                  ----> other/submodule.js
                                  ----> main_module.js
                           Module2
                                  ----> utiltiy/submodule.js
                                  ----> other/submodule.js
                                  ----> main_module.js

In this example my main_module.js will import files in the submodule folders (utility/submodule.js, other/submodule.js)

#main_module.js
import UtilitySubmodule from './utility/submodule.js'
import OtherSubmodule from './other/submodule.js'

if (OtherSubmodule['searchText'] === true) {
 searchText();
}


#submodule.js
export default {
  searchText: true
}


After the release will I be able to import files like this?
I was able to get it to acknowledge and load the files but I have to use my system file path, not ideal.

Can I have access to the master version with this?
```
gem 'webpacker', github: 'rails/webpacker'
```

**Comment by gauravtiwari** [comment]
@dmc2015 Thanks for detailed explanation. The `packs` directory is made only for `main_modules` or `entries` so you should move out any sub-modules to `app/javascript` or where ever you want to keep your JS source (this can be changed from webpacker.yml)

```js
// packs/main_module.js
import Post from '../post/show'
// this lives under app/javascript or change it from webpacker.yml
import Comment from '../post/comment'

// .... use the imports here
```

> I was able to get it to acknowledge and load the files but I have to use my system file path, not ideal.

What do you mean by system file path?

Yes you can use master if you like 👍

**Comment by gauravtiwari** [comment]
Checkout this section please for more info on structuring  - https://github.com/rails/webpacker#app-structure

**Comment by dmc2015** [comment]
By system file path, I mean the path from root of the system (computer) to the file. 

As opposed to the path from the importing file to the exporting file or from the root of the project.

**Comment by dmc2015** [comment]
Thanks a bunch!
