### ISSUE TITLE
ExecJS support

### ISSUE THREAD

**Issue by brodock** [rails/webpacker#58]
Any chance we can get ExecJS support for running `webpack`?

**Comment by dhh** [comment]
No plans for that at the moment. But if you want to work on it, feel free to open a PR if you get something together!

**Comment by guilleiguaran** [comment]
Sorry but probably no, per the FAQ of ExecJS: https://github.com/sstephenson/execjs#faq

```
Why can't I use CommonJS require() inside ExecJS?

ExecJS provides a lowest common denominator interface to any JavaScript runtime. Use ExecJS when it doesn't matter which JavaScript interpreter your code runs in. If you want to access the Node API, you should check another library like commonjs.rb designed to provide a consistent interface.
```

We need a full Node environment to run Webpack and ExecJS can't provide that.

**Comment by brodock** [comment]
@guilleiguaran so could https://github.com/cowboyd/commonjs.rb theoretically provide the required support? I'm asking that because webpack's minimal node version is `0.5`, so I'm guessing libv8 could provide whatever API's they are using.

While most of the time we would use nodejs, having an embedded executor could help into more restricted environments like heroku, or to build smaller docker images.

**Comment by guilleiguaran** [comment]
@brodock Yes, I think should be possible to use commonjs.rb (if the version of v8 provided by therubyracer is good enough) to do it.

You can check https://github.com/cowboyd/less.rb that is based in commonjs.rb for reference.

**Comment by perezperret** [comment]
@brodock I've been lookig into this, I haven't been able to get this working, but I know webpack lets you expose libraries as globals, maybe these would work with ExecJS? I know `react-rails` takes advantage of global variables to do server-side rendering, and I have read of people getting it to work with `browserify` by exposing globals, so maybe you can create a pack that exposes some globals [like this](https://gist.github.com/dreyescat/c3fd66ea0f7e97ba5c21#file-webpack-config-js-L8) and load those into ExecJS? Please do let us know if you get this somewhere

**Comment by brodock** [comment]
I will share a few experiments I've made. Because I don't understand well how the dependency system in JS works or is supposed to work, I think I'm missing something important: 

https://gist.github.com/brodock/f8862a94e3494d2cc20689b4f8bd6dfa
