### ISSUE TITLE
__webpack_require__(...) is not a function

### ISSUE THREAD

**Issue by theredorm** [rails/webpacker#588]
Halo guyz, i has a problem.
my testapp: https://github.com/theredorm/testwebpacker;
My steps:
1)./bin/webpak-dev-server
2)start server 
3)go to browser
4)all is good
5)little bit change js file
6)go to browser
7)see this trace: 
webpack-internal:///0:1 Uncaught TypeError: __webpack_require__(...) is not a function
    at eval (webpack-internal:///0:1)
    at Object.<anonymous> (hello_vue.js:75)
    at __webpack_require__ (hello_vue.js:20)
    at eval (webpack-internal:///47:5)
    at Object.<anonymous> (hello_vue.js:628)
    at __webpack_require__ (hello_vue.js:20)
    at eval (webpack-internal:///46:5)
    at Object.<anonymous> (hello_vue.js:616)
    at __webpack_require__ (hello_vue.js:20)
    at Object.eval (webpack-internal:///45:3)
8)reopen terminal
9)./bin/webpak-dev-server
10)all is good with new changes
Help me guyz pls, idk what the bug is this.
yarn: 0.27.5
node: 8.1.3
npm 5.0.3

**Comment by theredorm** [comment]
How can i fix it now?

**Comment by gauravtiwari** [comment]
@theredorm Are you using latest master or 2.0 version?

**Comment by theredorm** [comment]
i'm using latest master
in my gemfile:
gem 'webpacker', git: 'https://github.com/rails/webpacker.git'

**Comment by gauravtiwari** [comment]
@theredorm Could you please set `extractStyles` to false in loaders/vue.js? Do you also have styles in your vue component?

**Comment by theredorm** [comment]
my loader looks like:
module.exports = {
  test: /.vue$/,
  loader: 'vue-loader',
	options: {
  	extractStyles: false,
    extractCSS: true,

    loaders: {
      js: 'babel-loader',
      file: 'file-loader',
      scss: 'vue-style-loader!css-loader!postcss-loader!sass-loader',
      sass: 'vue-style-loader!css-loader!postcss-loader!sass-loader?indentedSyntax'
    }
  }
}
and it not works(

**Comment by gauravtiwari** [comment]
Try this please: 

```js
const ExtractTextPlugin = require('extract-text-webpack-plugin')
const { env } = require('../configuration.js')

// Change it to false if you prefer Vue styles to be inlined by javascript in runtime
const extractStyles = true

const cssLoader = [
  { loader: 'css-loader', options: { minimize: env.NODE_ENV === 'production' } },
  { loader: 'postcss-loader', options: { sourceMap: true } },
  'resolve-url-loader'
]
const sassLoader = cssLoader.concat([
  { loader: 'sass-loader', options: { sourceMap: true, indentedSyntax: true } }
])
const scssLoader = cssLoader.concat([
  { loader: 'sass-loader', options: { sourceMap: true } }
])

function vueStyleLoader(loader) {
  if (extractStyles) {
    return ExtractTextPlugin.extract({
      fallback: 'vue-style-loader',
      use: loader
    })
  }
  return ['vue-style-loader'].concat(loader)
}

module.exports = {
  test: /\.vue$/,
  loader: 'vue-loader',
  options: {
    loaders: {
      js: 'babel-loader',
      file: 'file-loader',
      css: vueStyleLoader(cssLoader),
      scss: vueStyleLoader(scssLoader),
      sass: vueStyleLoader(sassLoader)
    }
  }
}
```

**Comment by theredorm** [comment]
not work, mb u can check my testproject? https://github.com/theredorm/testwebpacker

**Comment by theredorm** [comment]
i frogot to say, i use ubuntu 17.04

**Comment by gauravtiwari** [comment]
@theredorm Made a PR here - https://github.com/theredorm/testwebpacker/pull/1

**Comment by theredorm** [comment]
@gauravtiwari thanks, it's work, but i have 1 question, this is a gem bug, or it is my curved hands?

**Comment by gauravtiwari** [comment]
@theredorm No, don't think this is a bug inside Webpacker. Probably some package wasn't installed correctly earlier. Feel free to close if you are happy 👍

**Comment by gauravtiwari** [comment]
@theredorm It could also be related to `yarn clean` or `.yarnclean`, which may remove necessary dependencies.
