### ISSUE TITLE
rails 4.2 and webpacker

### ISSUE THREAD

**Issue by victorhazbun** [rails/webpacker#590]
I'm getting `the selector "hello-angular" did not match any element` in the chrome inspector.

NOTE: Rails version 4.2

My `application.html.erb`

```
#header

<%= javascript_pack_tag 'hello_angular' %>

#body

<%= content_tag :div,
  id: "hello-angular",
  data: {
    message: 'Hello!',
    name: 'David'
}.to_json do %>
```

**Comment by gauravtiwari** [comment]
@victorhazbun I think you need `<hello-angular>Loading...</hello-angular>` like this. The one you have there is still div with id `hello-angular`

```html
<hello-angular data="<%= { message: 'Hello!', name: 'David' }.to_json %>">Loading...</hello-angular>
```

**Comment by gauravtiwari** [comment]
Feel free to reopen if this is still an issue 👍

**Comment by laertispappas** [comment]
I am facing the same problem with a Rails 4.2.7.1 application. I am facing the same problem when creating a new app using Rails 5.1.3 with the following command: `rails new myapp --webpack=angular`.

It seems that angular is not configured correctly to load the example app.

**Comment by gauravtiwari** [comment]
@laertispappas Have you followed the comments on the example i.e. including the `hello-angular ` tag and `javascript_pack_tag`

**Comment by gauravtiwari** [comment]
```
<hello-angular>Loading...</hello-angular>
 <%= javascript_pack_tag 'hello_angular' %>
```

**Comment by laertispappas** [comment]
Le me check

**Comment by laertispappas** [comment]
@gauravtiwari  Many thanks. It needs both statements to work.....

```JS
<hello-angular>Loading...</hello-angular>
 <%= javascript_pack_tag 'hello_angular' %>
```

**Comment by gauravtiwari** [comment]
That's correct 👍
