### ISSUE TITLE
Question about submodule packs

### ISSUE THREAD

**Issue by dmke** [rails/webpacker#591]
Hi,

I have a question regarding Git submodules in `app/javascript/pack`: How do I instruct webpack to ignore some directories within that submodule? (and/or: What is the recommended way to depend on a *private* code base without Webpack going crazy?)

Say, I have this directory layout:

```
RAILS_ROOT/
+-- app/
    +-- javascript/packs/
        +-- MyComponent/            # git submodule add $remote app/javascript/packs/MyComponent
        |   +-- src/                # component implementation 
        |   |   +-- MyComponent.js  # `export default class MyComponent { ... }`
        |   +-- spec/               # component spec files
        |   +-- package.json        # devDependencies and run scripts for specs
        |   +-- README.md           # installation instructions
        +-- application.js          # `import MyComponent from "./MyComponent/src/MyComponent`
```

When running `bin/webpack-dev-server`, it tries to bundle the files in `app/javascript/packs/MyComponent/spec/` and fails, because it can't find the dependencies for my specs.

Worse, if I *develop* within the submodule and run `yarn` in `app/javascript/packs/MyComponent/` (which creates `app/javascript/packs/MyComponent/node_modules`), the Webpack dev server quite happily bundles 10k chunks because they are `*.js` files underneath `webpacker.yml`'s source entry path...

I tried to reorganize the directory layout to this:

```
RAILS_ROOT/
+-- app/
    +-- javascript/
        +-- MyComponent/            # git submodule add $remote app/javascript/MyComponent
        |   +-- src/                # component implementation 
        |   |   +-- MyComponent.js  # `export default class MyComponent { ... }`
        |   +-- spec/               # component spec
        |   +-- package.json        # devDependencies and run scripts for specs
        |   +-- README.md           # installation instructions
        +-- packs/
            +-- MyComponent → ../MyComponent/src/
            +-- application.js      # `import MyComponent from "./MyComponent/MyComponent`
```

i.e. adding the submodule a level higher and symlinking the component. But somehow this still causes Webpack to include the `spec/` directory.

My current workaround is to *not* use a submodule, and to *copy* the files in `src/` directly into `app/javascript/packs/MyComponent` (which of course has other problems, like synchronization the copied files and the sources in the origin repository becomes hell...)

Thanks for any advice,
Dominik

**Comment by gauravtiwari** [comment]
`packs` directory is only made for Webpack entries so, only files that are main modules should be added here, which you can later reference using `javascript_pack_tag` helper:

Should be like this: *(package.json content can go into root package.json file)`

```yml
RAILS_ROOT/
+-- app/
    +-- javascript/
        +-- MyComponent/            # git submodule add $remote app/javascript/MyComponent
        |   +-- src/                # component implementation 
        |   |   +-- MyComponent.js  # `export default class MyComponent { ... }`
        |   +-- spec/               # component spec
        |   +-- package.json        # => can go inside package.json that comes with webpacker
        |   +-- README.md           # installation instructions
        +-- packs/
            +-- application.js      # `import MyComponent from "../MyComponent/src/MyComponent`
```

**Comment by dmke** [comment]
Ah, of course... Thank you!
