### ISSUE TITLE
Invalid format: ./bin/webpack

### ISSUE THREAD

**Issue by Dragas** [rails/webpacker#596]
On windows machines, it's impossible to run `webpacker:compile` task because by default windows treats `./bin/webpack` as a file without associated interpreting program. A workaround for this is to add `rails` before `./bin/webpack` at line 15 on `webpacker/compile.rake` file resulting in `rails ./bin/webpack`

**Comment by ytbryan** [comment]
Do you want to send a PR? The trouble is I (and we) don't have window machine to test it.
