### ISSUE TITLE
Is there a recommended way to handle I18N with this setup?

### ISSUE THREAD

**Issue by ankitrg** [rails/webpacker#597]
I want to use Rails i18n in my React/Vue files. How can I do this? Does webpacker helps us in anyway?

**Comment by ytbryan** [comment]
Have you look at https://github.com/kazupon/vue-i18n

**Comment by richardvenneman** [comment]
I use Polyglot with our React components: https://github.com/airbnb/polyglot.js

**Comment by gauravtiwari** [comment]
@ankitrg No not out the box. Pretty sure there are many examples out there though - easiest is, you can pass them as props from Rails views to your component.

@ytbryan @richardvenneman 🍰  👍

**Comment by aphilippartd** [comment]
@gauravtiwari would there be any way to access the rails locales contained in `config/locales` and using them as objects with the vue-i18n modules? I have been trying to access those files but I did not manage to make it work... Thanks!!

**Comment by coisnepe** [comment]
@aphilippartd Depending on the number of translations you have to deal with, I guess one way to do it could be to store the translations you need in `window` then access it from Vue.

```ruby
# application_controller.rb
def window_translations
  @translations = I18n.t(".")
end
```

```html
# application.html.erb
<script type="text/javascript">
  window.I18n = <%= @translations.to_json.html_safe %>;
</script>
```

**Comment by bazzel** [comment]
I was able to use i18n-js with webpacker and wrote it down in a [gist](https://gist.github.com/bazzel/ecdff4718962e57c2d5569cf01d332fe).
