### ISSUE TITLE
rake webpacker:compile Errno:ENOEXEC

### ISSUE THREAD

**Issue by jHnrd** [rails/webpacker#600]
I've just installled webpacker. I would like compile my assests.
But when I lauch: <code>rake webpacker:compile --trace</code>
I use **ruby 2.2.6** and **rails 4.2.6** on windows 10.

I have this error:

> 
> ** Invoke webpacker:compile (first_time)
> ** Invoke webpacker:verify_install (first_time)
> ** Invoke webpacker:check_node (first_time)
> ** Execute webpacker:check_node
> ** Invoke webpacker:check_yarn (first_time)
> ** Execute webpacker:check_yarn
> ** Invoke webpacker:check_webpack_binstubs (first_time)
> ** Execute webpacker:check_webpack_binstubs
> ** Execute webpacker:verify_install
> Webpacker is installed 🎉 🍰
> Using C:/Users/jonathan.henrard/Projets/mailing_manager/config/webpacker.yml file for setting up webpack paths
> ** Invoke environment (first_time)
> ** Execute environment
> ** Execute webpacker:compile
> [Webpacker] Compiling assets 🎉
> rake aborted!
> Errno::ENOEXEC: Exec format error - ./bin/webpack
> C:/rubies/ruby-2.2.6@chassis/lib/ruby/2.2.0/open3.rb:193:in `spawn'
> C:/rubies/ruby-2.2.6@chassis/lib/ruby/2.2.0/open3.rb:193:in `popen_run'
> C:/rubies/ruby-2.2.6@chassis/lib/ruby/2.2.0/open3.rb:93:in `popen3'
> C:/rubies/ruby-2.2.6@chassis/lib/ruby/2.2.0/open3.rb:252:in `capture3'
> C:/rubies/ruby-2.2.6@chassis/lib/ruby/gems/2.2.0/gems/webpacker-2.0/lib/tasks/webpacker/compile.rake:13:in `block (2 levels) in <top (required)>'
> C:/rubies/ruby-2.2.6@chassis/lib/ruby/gems/2.2.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `call'
> C:/rubies/ruby-2.2.6@chassis/lib/ruby/gems/2.2.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
> C:/rubies/ruby-2.2.6@chassis/lib/ruby/gems/2.2.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
> C:/rubies/ruby-2.2.6@chassis/lib/ruby/gems/2.2.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
> C:/rubies/ruby-2.2.6@chassis/lib/ruby/gems/2.2.0/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
> C:/rubies/ruby-2.2.6@chassis/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
> C:/rubies/ruby-2.2.6@chassis/lib/ruby/gems/2.2.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
> C:/rubies/ruby-2.2.6@chassis/lib/ruby/gems/2.2.0/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
> C:/rubies/ruby-2.2.6@chassis/lib/ruby/gems/2.2.0/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
> C:/rubies/ruby-2.2.6@chassis/lib/ruby/gems/2.2.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
> C:/rubies/ruby-2.2.6@chassis/lib/ruby/gems/2.2.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
> C:/rubies/ruby-2.2.6@chassis/lib/ruby/gems/2.2.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
> C:/rubies/ruby-2.2.6@chassis/lib/ruby/gems/2.2.0/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
> C:/rubies/ruby-2.2.6@chassis/lib/ruby/gems/2.2.0/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
> C:/rubies/ruby-2.2.6@chassis/lib/ruby/gems/2.2.0/gems/rake-12.0.0/lib/rake/application.rb:80:in `block in run'
> C:/rubies/ruby-2.2.6@chassis/lib/ruby/gems/2.2.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
> C:/rubies/ruby-2.2.6@chassis/lib/ruby/gems/2.2.0/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
> C:/rubies/ruby-2.2.6@chassis/lib/ruby/gems/2.2.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
> C:/rubies/ruby-2.2.6@chassis2/bin/rake:23:in `load'
> C:/rubies/ruby-2.2.6@chassis2/bin/rake:23:in `<main>'
> Tasks: TOP => webpacker:compile

**Comment by ytbryan** [comment]
probably related https://github.com/rails/webpacker/issues/596

**Comment by jHnrd** [comment]
Yes, I encountered this issue yesterday. I didn't see the #596 Post at that time. 
Sorry for duplication.
