### ISSUE TITLE
Contributor Guidelines?

### ISSUE THREAD

**Issue by justin808** [rails/webpacker#603]
Is there any contributor information, like this [shakacode/react_on_rails CONTRIBUTING.md](https://github.com/shakacode/react_on_rails/blob/master/CONTRIBUTING.md)?

1. Besides running unit tests with `rake`, what else needs to be tested, manually, etc.?
2. Any other guidelines, like fill in CHANGELOG.md in the PR.

**Comment by dhh** [comment]
This is an official Rails project, so that CONTRIBUTING guide applies: https://github.com/rails/rails/blob/master/CONTRIBUTING.md

**Comment by justin808** [comment]
@gauravtiwari Maybe you can add a doc file of what you do for manual testing for the parts that are not covered by running `rake`?
