### ISSUE TITLE
webpacker:compile should set the cache compilation timestamp file

### ISSUE THREAD

**Issue by renchap** [rails/webpacker#604]
This would be useful for CI, where you want to compile the assets before running your tests, so it does not mess up test performance.
Currently the assets are compiled on the first test, even if `rails webpacker:compile` has been called beforehand.

**Comment by gauravtiwari** [comment]
@renchap Makes sense. May be an env variable to disable the behaviour?

**Comment by renchap** [comment]
Or have 2 Rake tasks, one for the current behaviour and one that adds the timestamp?
I do not have a preference here.

**Comment by gauravtiwari** [comment]
@renchap Think this is fixed on master. We do set a timestamp file inside tmp

**Comment by renchap** [comment]
Yes, it works fine and my timings for `rails test` are no longer impacted by Webpacker's compilation time.
I just updated my (non trivial) config to your latest master changes, it simplified a lot of things. Nice work! 👍
