### ISSUE TITLE
Ajax in Webpacker

### ISSUE THREAD

**Issue by dmc2015** [rails/webpacker#605]
Is there an approach to handling ajax with webpacker?

Say for example that I have an ajax in a webpacker module that gets called on a click event. After it hits the server it will go back to show.js.erb or some other js.erb depending on the situation. I would rather it go to a file that I specify in my packs folder. Is there currently an implementation to do this ?

**Comment by gauravtiwari** [comment]
@dmc2015 You can trigger a redirect after Ajax success in your JS module.
