### ISSUE TITLE
Disable Webpacker classes minification

### ISSUE THREAD

**Issue by nvma** [rails/webpacker#616]
I've searched through all of the Webpacker config files and couldn't find where exactly class names get transformed into "c1", "c2", "c3". The configuration of the application is default one for Rails 5.1+, i.e. `rails new myapp --webpack=react`.
There are quite a few `material-ui@next` components in this application and in development, while they retain their specific names, it works just fine but upon precompling in production all classes get mangled into a one letter\number and styling chaos ensues. It does seem like there are lot of collisions since there are cases like inputs having styles of notification popups and such.
I would greatly appreciate any pointers as to how I can resolve this problem. Thanks a lot!

**Comment by renchap** [comment]
This is caused by `babel-preset-env`'s `uglify` option: https://github.com/babel/babel-preset-env#options
It runs https://github.com/mishoo/UglifyJS2 on the code in the production build, resulting is a smaller (and faster) JS pack. It is not recommended to remove it in production. Instead, you can use the source maps (https://developers.google.com/web/tools/chrome-devtools/javascript/source-maps) that are generated to display the non-minified code in your inspector.

**Comment by nvma** [comment]
Apologies for the late response, @renchap. Could you please clarify where exactly in webpack config in a Rails project I can disable classes minification? It's really the only thing that breaks our deployment and I had to write a new config file to compile React assets into a single bundle which I then fed to the pipeline, bypassing webpacker completely. But that's kind of counterproductive, I think there is surely a possibility to disable this behavior in webpacker, I just can't find where.

**Comment by renchap** [comment]
In your `.babelrc`, set `uglify` to `false`

**Comment by nvma** [comment]
@renchap unfortunately it doesn't seem to help, here's our modified .babel.rc
```
{
  "presets": [
    [
      "env",
      {
        "modules": false,
        "targets": {
          "browsers": "> 1%",
          "uglify": false
        },
        "useBuiltIns": true
      }
    ],
    "react"
  ],
  "plugins": [
    "syntax-dynamic-import",
    [
      "transform-class-properties",
      {
        "spec": true
      }
    ]
  ]
}
```
but our classes still look like this after precompile in production  `<input type="text" class="ci cp" value="" id="search">`.

**Comment by renchap** [comment]
I do not really know where it comes from. By briefly looking at `material-ui`, it seems they are using pure JS styling (see https://github.com/callemall/material-ui/blob/master/src/Badge/Badge.js#L4), so class names are generated.
This is not related to Webpacker, and I am quite confident this is a normal behaviour, and the problems you have do not come from a minification / optimisation step.

**Comment by renchap** [comment]
I forgot about it, but the default config also uses Webpack's uglifier plugin in production. You can disable it in `config/webpack/production.js` and see if it changes something.
