### ISSUE TITLE
Only re-compile assets that have changed?

### ISSUE THREAD

**Issue by catskull** [rails/webpacker#618]
We're using webpacker in production. Every time we deploy our servers, assets:precompile runs on each server adding ~30s * the number of servers we have. As we continue to scale, deploys will keep growing. Additionally, assets:precompile eats up a lot of CPU so doing a production deploy mid-day nearly halts production.

Is there any good way to only re-compile assets that have changed? Or any other strategies for dealing with this issue? Ideally I'd like to run assets:precompile locally and just deploy that with the rest of the code, no idea if that's feasible.

Any input is appreciated!

**Comment by gauravtiwari** [comment]
@catskull This feature is only available in testing environment. Perhaps makes sense to add it to production as well. You compile locally and commit your assets to source control though.

**Comment by catskull** [comment]
@gauravtiwari thanks! We were using `capistrano-faster-assets` but it 100% doesn't work with webpacker. Currently looking into `capistrano-local-precompile` which may do just what we need! I'll report back with what we find as I assume others are/will run into this issue.

**Comment by javan** [comment]
I suggest running `assets:precompile` on a single server and then `rsync`'ing the compiled assets to the rest of your servers. That's what we do at Basecamp using a couple small Cap tasks.

**Comment by catskull** [comment]
@javan thanks for the tip! I spent about a solid day fighting `capistrano-local-precompile`, but ultimately gave up. Just couldn't get it to work right for webpack assets.

Any chance you might share your cap tasks? I'm by no means a devops guy.

**Comment by javan** [comment]
I'm not the author of these so they're presented without guarantee or support:
```ruby
after 'deploy:bundle', 'assets:symlink_cache'
after 'assets:symlink_cache', 'assets:precompile'
after 'assets:precompile', 'assets:sync'

namespace :assets do
  task :precompile, roles: :asset_precompiler, only: { primary: true } do
    run "mkdir -p #{shared_path}/assets && ln -nfs #{shared_path}/assets #{release_path}/public/assets"
    run "cd #{release_path} && #{elapsed} RAILS_ENV=#{rails_env} RAILS_GROUPS=assets #{rake} assets:precompile --trace"
  end

  task :sync, roles: :asset_users, on_no_matching_servers: :continue do
    run "mkdir -p #{shared_path}/assets && ln -nfs #{shared_path}/assets #{release_path}/public/assets"
    precompiler = roles[:asset_precompiler].detect { |server| server.options[:primary] }
    run "#{elapsed} rsync -a #{precompiler}:#{shared_path}/assets/ #{shared_path}/assets"
  end

  task :symlink_cache, :roles => :asset_precompiler do
    run "mkdir -p #{shared_path}/tmp/cache && ln -nfs #{shared_path}/tmp/cache #{release_path}/tmp/cache"
  end
end
```

We set `public_output_path: assets/packs` in `webpacker.yml` to make this work for both sprockets and webpacker compiled assets.
