### ISSUE TITLE
font-awesome help

### ISSUE THREAD

**Issue by theredorm** [rails/webpacker#619]
Halo guyz, need your help.
font-awesome cant' work,
my steps:
install FA via yarn 
import 'font-awesome/css/font-awesome.css';
can't work;
my assets loader:
```
const { env, output } = require('../configuration.js');

module.exports = {
  test: /\.(jpg|jpeg|png|gif|svg|eot|ttf|woff|woff2)$/i,
  use: [{
    loader: 'file-loader',
    options: {
      publicPath: output.publicPath,
      name: env.NODE_ENV === 'production' ? '[name]-[hash].[ext]' : '[name].[ext]'
    }
  }]
};
```
My package.json
```
{
  "name": "ander",
  "private": true,
  "dependencies": {
    "autoprefixer": "^7.1.2",
    "babel-core": "^6.25.0",
    "babel-loader": "7.x",
    "babel-plugin-syntax-dynamic-import": "^6.18.0",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-object-rest-spread": "^6.23.0",
    "babel-polyfill": "^6.23.0",
    "babel-preset-env": "^1.6.0",
    "coffee-loader": "^0.7.3",
    "coffee-script": "^1.12.7",
    "compression-webpack-plugin": "^1.0.0",
    "css-loader": "^0.28.4",
    "extract-text-webpack-plugin": "^3.0.0",
    "file-loader": "^0.11.2",
    "font-awesome": "^4.7.0",
    "glob": "^7.1.2",
    "i": "^0.3.5",
    "js-yaml": "^3.9.0",
    "node-sass": "^4.5.3",
    "npm": "^5.3.0",
    "path-complete-extname": "^0.1.0",
    "postcss-cssnext": "^3.0.2",
    "postcss-loader": "^2.0.6",
    "postcss-smart-import": "^0.7.5",
    "precss": "^2.0.0",
    "rails-erb-loader": "^5.0.2",
    "resolve-url-loader": "^2.1.0",
    "sass-loader": "^6.0.6",
    "style-loader": "^0.18.2",
    "stylus": "^0.54.5",
    "stylus-loader": "^3.0.1",
    "url-loader": "^0.5.9",
    "vue": "^2.4.2",
    "vue-loader": "^12.2.2",
    "vue-template-compiler": "^2.4.2",
    "vuetify": "^0.14.5",
    "vuex": "^2.3.1",
    "webpack": "^3.4.1",
    "webpack-manifest-plugin": "^1.2.1",
    "webpack-merge": "^4.1.0"
  },
  "devDependencies": {
    "webpack-dev-server": "^2.6.1"
  }
}
```

Thanks for the help

**Comment by renchap** [comment]
What is the error message you get?

For me it works using this in my `style.scss`

```scss
$fa-font-path: "~font-awesome/fonts";
@import '~font-awesome/scss/font-awesome';
```

**Comment by michalhorcic** [comment]
This helped me at least. Didn't work for me when adding to assets/application.css. But this way worked great even on production. Thanks a lot.

**Comment by ahbou** [comment]
PSA font-awesome 5 has been [renamed on 5.10](https://github.com/FortAwesome/Font-Awesome/blob/master/UPGRADING.md#renamed-packages)

```
yarn add @fortawesome/fontawesome-free    
yarn add @fortawesome/free-solid-svg-icons
```
Add on application.scss
```
$fa-font-path: '~@fortawesome/fontawesome-free/webfonts'; 
@import '~@fortawesome/fontawesome-free/scss/fontawesome';
@import '~@fortawesome/fontawesome-free/scss/solid';
```

**Comment by fgblomqvist** [comment]
Didn't have to add the solid svg icons to yarn, but I did have to import both the solid and the regular to be able to use all the "normal" icons:
```
@import '~@fortawesome/fontawesome-free/scss/fontawesome';
@import '~@fortawesome/fontawesome-free/scss/regular';
@import '~@fortawesome/fontawesome-free/scss/solid';
```

**Comment by h0jeZvgoxFepBQ2C** [comment]
This worked for me

```shell
yarn add --dev @fortawesome/fontawesome-free
```

```
# application.scss
$fa-font-path: '~@fortawesome/fontawesome-free/webfonts'; 
@import '~@fortawesome/fontawesome-free/scss/fontawesome';
@import '~@fortawesome/fontawesome-free/scss/regular';
@import '~@fortawesome/fontawesome-free/scss/solid';
```

**Comment by hectortllo** [comment]
> PSA font-awesome 5 has been [renamed on 5.10](https://github.com/FortAwesome/Font-Awesome/blob/master/UPGRADING.md#renamed-packages)
> 
> ```
> yarn add @fortawesome/fontawesome-free    
> yarn add @fortawesome/free-solid-svg-icons
> ```
> 
> Add on application.scss
> 
> ```
> $fa-font-path: '~@fortawesome/fontawesome-free/webfonts'; 
> @import '~@fortawesome/fontawesome-free/scss/fontawesome';
> @import '~@fortawesome/fontawesome-free/scss/solid';
> ```

I did exactly what you said and it worked for me! Thanks

**Comment by samiggapps** [comment]
As of November 2019 I have found this the easiest way to get it all working:

Install via Yarn:

`yarn add @fortawesome/fontawesome-free`

Import in your `application.js` file:

`import "@fortawesome/fontawesome-free/css/all.css";`

Pretty straightforward and worked for me!

**Comment by rgaufman** [comment]
@samiggapps this worked for browsers and on iOS in development, but after assets:precompile and deploy to production, I can see icons on browsers, but not on iOS, any ideas at all?

**Comment by samiggapps** [comment]
@rgaufman I haven't done iOS development  so I wouldn't know, hopefully someone else will and post it here. If you crack it, let me know, good luck 👍

**Comment by rgaufman** [comment]
Hi Sorry, not iOS specifically, just mobile safari.

**Comment by jakeNiemiec** [comment]
@rgaufman Can you make a new ticket with more details?

**Comment by spernica** [comment]
in your .js file
`
import "@fortawesome/fontawesome-free/js/all.js";
import "@fortawesome/fontawesome-free/css/all.css";
`

This helps in my case

**Comment by paulmwatson** [comment]
Thanks for all the pointers, for Rails 6 and font awesome free this works for me (no gem used);
application.scss
```scss
...
$fa-font-path: '@fortawesome/fontawesome-free/webfonts';
@import '@fortawesome/fontawesome-free/scss/fontawesome';
@import '@fortawesome/fontawesome-free/scss/solid';
...
```

manifest.js
```javascript
...
//= link_tree ../../../node_modules/@fortawesome/fontawesome-free/webfonts/
...
```

**Comment by la-ruby** [comment]
One of the most liked answers here (by samiggapps) gave me this warning on heroku:

```
remote:        WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
remote:        Entrypoints:
remote:          application (1.54 MiB)
remote:              css/application-eb386482.css
remote:              js/application-537dc6eda555131605e9.js
```

**Comment by paulmwatson** [comment]
@la-ruby it is big. Not a direct solution but there is a sub-setter if you want a custom font icon set;
https://blog.fontawesome.com/desktop-subsetter-beta/

**Comment by maxnovee** [comment]
@paulmwatson great catch, but this way it won't work in production. @font-faces are still using wrong paths and can't find a way to `assets/`. To fix that, you still have to override imported @font-faces to use font-url as sources
```
@font-face {
  font-family: 'Font Awesome 5 Brands';
  font-style: normal;
  font-weight: 400;
  font-display: $fa-font-display;
  src: font-url('#{$fa-font-path}/fa-brands-400.eot');
  src: font-url('#{$fa-font-path}/fa-brands-400.eot?#iefix') format('embedded-opentype'),
  font-url('#{$fa-font-path}/fa-brands-400.woff2') format('woff2'),
  font-url('#{$fa-font-path}/fa-brands-400.woff') format('woff'),
  font-url('#{$fa-font-path}/fa-brands-400.ttf') format('truetype'),
  font-url('#{$fa-font-path}/fa-brands-400.svg#fontawesome') format('svg');
}
```
Or you have a more elegant solution?

**Comment by snex** [comment]
I have tried everything in this thread and Fontawesome still refuses to work. I'm on Rails 6.1.1, webpacker 4.3.0.

It works fine in dev environment, but after compiling and loading production (the font files even compile into the proper folders), I still get 404 errors on the font files.

**Comment by RyanB1303** [comment]
> I have tried everything in this thread and Fontawesome still refuses to work. I'm on Rails 6.1.1, webpacker 4.3.0.
> 
> It works fine in dev environment, but after compiling and loading production (the font files even compile into the proper folders), I still get 404 errors on the font files.

try importing it in application.scss file
```
$fa-font-path: '~@fortawesome/fontawesome-free/webfonts';
@import "~@fortawesome/fontawesome-free/scss/fontawesome.scss";
@import "~@fortawesome/fontawesome-free/scss/solid.scss";
@import "~@fortawesome/fontawesome-free/scss/regular.scss";
@import "~@fortawesome/fontawesome-free/scss/brands.scss";
@import "~@fortawesome/fontawesome-free/scss/v4-shims.scss";

```
in my application it works, Rails 6.1, webpacker 5

**Comment by snex** [comment]
Hi @RyanB1303 thanks for the reply. I have since moved to Rails 7, however the same issue still plagues me. I tried making the changes you suggested and still have the same problem - in fact it now no longer works in the dev environment as well. The one bright side is that there are now some relevant errors in the logs that might help:

```
Started GET "/webfonts/fa-solid-900.ttf" for 127.0.0.1 at 2022-03-30 13:03:46 -0700
  
ActionController::RoutingError (No route matches [GET] "/webfonts/fa-solid-900.ttf"):
```

I am not sure why it is trying to read fonts from that particular directory...

**Comment by danmar-varela** [comment]
> Hi @RyanB1303 thanks for the reply. I have since moved to Rails 7, however the same issue still plagues me. I tried making the changes you suggested and still have the same problem - in fact it now no longer works in the dev environment as well. The one bright side is that there are now some relevant errors in the logs that might help:
> 
> ```
> Started GET "/webfonts/fa-solid-900.ttf" for 127.0.0.1 at 2022-03-30 13:03:46 -0700
>   
> ActionController::RoutingError (No route matches [GET] "/webfonts/fa-solid-900.ttf"):
> ```
> 
> I am not sure why it is trying to read fonts from that particular directory...

Had the same problem too. I just imported the css files that I need in application.scss:

```
@import '@fortawesome/fontawesome-free/scss/fontawesome';
@import '@fortawesome/fontawesome-free/scss/regular';
@import '@fortawesome/fontawesome-free/scss/solid';
```
and then the corresponding js files in application.js:

```
import "@fortawesome/fontawesome-free/js/fontawesome"
import "@fortawesome/fontawesome-free/js/regular"
import "@fortawesome/fontawesome-free/js/solid"
```

**Comment by snex** [comment]
Hi @danmar-varela thanks for the help. Unfortunately I tried that and still get the same results.

**Comment by bwarner** [comment]
in order to get this to work I have to:
- install fontawesome node module
- In a file called fontawesome-pro.scss
  - define $fa-font-path 
  - import the fontawesome scss files 
  - redefine the @font-face CSS rules
- required it from application.css

This because the FontAwesome files define the src as 'url('#{$fa-font-path}/fa-solid-900.eot');' for example, but should defined it as 'font-url('#{$fa-font-path}/fa-solid-900.eot');'

After doing all of this it still causes an issue in Safari, it appears that Safari tries to load the fonts as defined in the fontawesome.scss files, before loading them with the corrected paths.

You get a 404 for the bad path, then it loads the fonts with the correct path.
