### ISSUE TITLE
unable to images from asset pipeline in stylesheets section

### ISSUE THREAD

**Issue by alec-c4** [rails/webpacker#621]
hi
I'm trying to use web packer with vue.js and I have following situation. I have some images in /app/assets/images and trying to work with in from vue component with following:

```
<template>
    <div id="home">
        <div id="intro" style="background-image: url('assets/cover-image-medium.png'); background-repeat: no-repeat">
        </div>
    </div>
</template>

<script>
    export default {}
</script>

<style>
    #intro {
        height: 500px;
        background: url("assets/cover-image-medium.png");
        background-repeat: no-repeat;
    }
</style>
```

code in template section works fine - image is displayed as div background, but from style section - doesn't work :( Whats wrong?

**Comment by gauravtiwari** [comment]
@alec-c4 you would need to reference them correctly inside styles i.e. relative to the directory where it exists. The HTML works because I think it goes through asset pipeline. 

An example: 

```sass
background: url("../../assets/images/cover-image-medium.png")
```
