### ISSUE TITLE
webpacker is serving stale assets to subsequent runs of test suite

### ISSUE THREAD

**Issue by jonworek** [rails/webpacker#623]
I'm using cucumber paired with capybara for running tests against my Rails app.  I've noticed that webpacker is only compiling assets on the first run of the test suite, placing them in `public/packs-test`.

On subsequent runs of the test suite, when I change code, I would expect that the results of my tests would change in the event that I introduce some breaking change in my app code that should cause tests to fail.

I'm working around this by creating the following initializer code to wipe out the `public/packs-test` directory when the app loads:

```
require "fileutils"

if Rails.env.test?
  config = YAML.load_file(File.join(Rails.root, "config/webpacker.yml"))

  packs_path = config[Rails.env]['public_output_path']
  packs_dir = File.join(Rails.root, "public", packs_path)

  FileUtils.rm_rf(packs_dir)
end
```

Now, when the test suite runs, webpacker will recompile the assets and I get the results that I would expect from my test suite.

I think this is something that probably could/should be integrated into webpacker.  I haven't looked at *how* yet, but I can figure it out if this issue is accepted.

Thanks!

**Comment by gauravtiwari** [comment]
@jonworek The assets should be recompiled if files that are under tracked paths are changed. Are you using latest master?

**Comment by jonworek** [comment]
@gauravtiwari yes, I am using the latest master.

In `Rails.env == 'development'`, where I'm running the webpack dev server, assets do get recompiled after a change.  However, in test, where webpack dev server is not being used, it doesn't happen.

It seems that all that is being checked for is whether something exists in `public/packs-test`, and a check isn't being made to see whether recompilation is necessary.

**Comment by gauravtiwari** [comment]
@jonworek We do perform a check to see if an asset has changed and then perform recompilation - https://github.com/rails/webpacker/blob/master/lib/webpacker/compiler.rb#L14

**Comment by marekciupak** [comment]
I can confirm the problem occurs in the latest release:
https://rubygems.org/gems/webpacker/versions/2.0.

Using the latest master solved the problem in my case.

**Comment by jonworek** [comment]
Ah, wonderful.  @marekciupak thank you for confirming that.

I made the wrong assumption that the version on rubygems was on par with what's in master.  I'm consuming this library via the gem, so that would explain things.

Thanks for clarifying and taking a look.

**Comment by brandoncc** [comment]
I am experiencing this problem using the latest version of master. The only way I can get it to recompile `public/packs-test/application.js` is if I delete `tmp/.last-compilation-digest`. The files I am working with are located `app/javascript/.../...`. There must be something wrong in the config, but I can't figure out what it is.

**Comment by brandoncc** [comment]
By the way, I am using the `rails test:system` command.
