### ISSUE TITLE
The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'.

### ISSUE THREAD

**Issue by mayordwells** [rails/webpacker#624]
I have no idea where this error with CORS is coming from and I have no idea how to fix it. 
I created a new Rails app using the Angular webpacker handle. (Rails v5.1.3, Angular v4.3.3)
Everything works perfectly well expect that I'm getting this endless log of CORS error in my console. 
<img width="1092" alt="screen shot 2017-08-08 at 4 36 55 pm" src="https://user-images.githubusercontent.com/1370340/29074476-1d63e0c2-7c58-11e7-9c5c-40a0ffae5e39.png">

How can I make this error go away?

**Comment by renchap** [comment]
This is a bug in the last `webpack-dev-server` version, released today. It is caused by this PR: https://github.com/webpack/webpack-dev-server/pull/911

I am opening a bug for this, in the meantime you can stick the the previous version:
`yarn add webpack-dev-server@2.6.1`

**Comment by renchap** [comment]
https://github.com/webpack/webpack-dev-server/issues/1021

**Comment by shellscape** [comment]
I commented on the linked issue there, but if anyone here can provide a _small_ example app which reproduces this error, I'd be happy to take a look at it.

**Comment by renchap** [comment]
`webpack-dev-server` 2.7.1 has just been released and fixed this issue.

**Comment by nengine** [comment]
I am using webpack with Vue.js template inside Rails 5.1 app and calling publicClient.getProducts() methods works fine.  But, to stream the data, when I open websocket  connection I am getting:

"Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ws-feed.gdax.com/. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing)."

Is this something has to do with Rails or Vue.js?  Any help is greatly appreciated.


```js
<template>
  <div id="trades">
    <p>{{ message }}</p>
    <button @click='load'>Load data</button>    
  </div>
</template>

<script>
  const Gdax = require('gdax');
  const publicClient = new Gdax.PublicClient();
  const websocket = new Gdax.WebsocketClient(['LTC-USD']);

  export default {
    data: function() {
      return {
        message: 'Hello from trades Vue'
      }
    },
    methods: {
      mounted: function() {
        websocket.on('message', data => {
          console.log(data);
        });    
      },

      load: function() {     
        publicClient.getProducts((error, response, data) => {
          if (error) {
            // handle the error
          } else {
            console.log(JSON.stringify(data));
          }
        });
      }
    }
  }
</script>
```

**Comment by gauravtiwari** [comment]
@nengine Nope, seems like something related to `https://ws-feed.gdax.com/`.

**Comment by rajranjan672** [comment]
@renchap i am still not able to fix error after installing the,  webpack-dev-server 2.7.1 can someone help me in fixing the error?
