### ISSUE TITLE
Is the logic for `fresh?` the wrong way round?

### ISSUE THREAD

**Issue by wannabefro** [rails/webpacker#628]
In https://github.com/rails/webpacker/commit/1b9752ae3218888189aae07a261ced6ac9c4e73a `fresh?` was introduced to determine whether the compile_tasks should be invoked. 

Previously the logic for `compile?` which is now `fresh?` would return the result of `File.read(cached_timestamp_path) != current_source_timestamp` (assuming the necessary files existed).

With the logic for `fresh?`, if the `cached_timestamp` does not have the same value as the `current_source_timestamp` then `fresh?` returns true (I believe that this should return false).

Since the check for `compile` is now dependent on `!fresh?` being true this seems to imply that the `compile_task` will be invoked if the files have not been changed and not invoked if the files being watched have changed.

**Comment by gauravtiwari** [comment]
@wannabefro Think this is fixed in another PR. Do you wanna give it another go and report back please?

**Comment by gauravtiwari** [comment]
@wannabefro Just tested and the issue still exists - making a PR 👍

**Comment by wannabefro** [comment]
Thanks so much for taking care of this @gauravtiwari. It all looks great. Closing the issue
