### ISSUE TITLE
New files are picked up by watcher, but not added to manifest.json

### ISSUE THREAD

**Issue by twss** [rails/webpacker#630]
When a new file is added to the watched folder, it is seen and triggers a compile. However, the file isn't included in the `manifest.json`.

**Comment by gauravtiwari** [comment]
@twss Are you using latest master?

**Comment by justin808** [comment]
@gauravtiwari @dhh can we get a beta release soon? I'd like to have React on Rails v9.x depend on this.

**Comment by dhh** [comment]
I'd like to wrap up the npm extraction of the configuration that @javan is working on first. Then we can cut a 3.0 beta.
