### ISSUE TITLE
 Module build failed: Error: Couldn't find preset "env" relative to directory

### ISSUE THREAD

**Issue by cahyowhy** [rails/webpacker#634]
hi..
i just started new rails project with webpack react preset, but it seems some module are undefined then i tried to install some module but unfortunately my terminal raise an error

` Module build failed: Error: Couldn't find preset "env" relative to directory`

and this is my package.json from my project
```
{
  "name": "mencoba-webpacker",
  "private": true,
  "dependencies": {
    "babel-plugin-syntax-dynamic-import": "^6.18.0",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-object-rest-spread": "^6.23.0",
    "babel-preset-react": "^6.24.1",
    "prop-types": "^15.5.10",
    "react": "^15.6.1",
    "react-dom": "^15.6.1"
  },
  "devDependencies": {
    "babel-core": "^6.25.0",
    "babel-loader": "^7.1.1",
    "extract-text-webpack-plugin": "^3.0.0",
    "js-yaml": "^3.9.1",
    "path-complete-extname": "^0.1.0",
    "webpack": "^3.5.3",
    "webpack-dev-server": "^2.7.1",
    "webpack-manifest-plugin": "^1.3.0",
    "webpack-merge": "^4.1.0"
  }
}

```

thanks for your concern and sorry for my bad english...

**Comment by gauravtiwari** [comment]
@cahyowhy You would need to add `babel-preset-env` i.e. `yarn add babel-preset-env`

**Comment by gauravtiwari** [comment]
`bundle exec rails webpacker:install` should add all this automatically for you though.

**Comment by cahyowhy** [comment]
ok its worked thanks :) @gauravtiwari

**Comment by BaiJiafan** [comment]
npm i babel-preset-env
