### ISSUE TITLE
Including Rails configuration in Javascript?

### ISSUE THREAD

**Issue by malonehedges** [rails/webpacker#639]
I tried to see if there were any issues that answered this but didn't have any luck.

I'm trying to integrate ActionCable into my javascript and need to access `Rails.application.config.action_cable.url`. Is there any way to get this information into the packs?

**Comment by malonehedges** [comment]
Just as I posted this I found a workaround: passing `Rails.application.config.action_cable.url` from the rails view to my HTML. Still would be interested in if there is a better way to do this though.

**Comment by gauravtiwari** [comment]
@malonehedges That's what I was going to recommend as well - there is also a helper tag that renders action cable url as meta tag

```
<%= action_cable_meta_tag %>
```

and then I think you can use JS magic to fetch the url from this tag on mount.

**Comment by gauravtiwari** [comment]
The other way is you can set is as an environment variable and access using process.env

**Comment by malonehedges** [comment]
@gauravtiwari Awesome, thanks for the help. Ended up going with the meta tag version.
