### ISSUE TITLE
Dev server proxy bypassed by static asset servers

### ISSUE THREAD

**Issue by javan** [rails/webpacker#644]
When using a local app server like [puma-dev](https://github.com/puma/puma-dev) or [pow](https://github.com/basecamp/pow) that serves static assets, starting `bin/webpack-dev-server` will have no effect if a compiled .js file already exists. The preexisting files in `public/packs` will be served directly and the requests never hit Rails.

Steps to reproduce:
1. Load a page with webpacker's `compile: true` option enabled (the default)
2. Start `bin/webpack-dev-server`
3. Change your application's js in some way and reload the page

/cc @gauravtiwari @dhh

**Comment by javan** [comment]
One possible solution is to use hashed filenames in development:
```diff
--- a/lib/install/config/webpack/development.js
+++ b/lib/install/config/webpack/development.js
@@ -8,7 +8,8 @@ module.exports = merge(sharedConfig, {
   devtool: 'cheap-eval-source-map',
 
   output: {
-    pathinfo: true
+    filename: '[name]-[chunkhash].js',
+    pathinfo: true,
   },
```
As a bonus, this makes [Turbolinks: Reloading When Assets Change](https://github.com/turbolinks/turbolinks#reloading-when-assets-change) work out of the box.

**Comment by gauravtiwari** [comment]
@javan Yeah, that looks like the simplest solution and it will also solve the `cache` problem, where people are getting there packs cached in development, when using watcher or on-demand compiler that are being served by Rails server.

**Comment by gauravtiwari** [comment]
We can turn on the hash by default for all env in shared.js

**Comment by javan** [comment]
+1. The only downside is you accumulate files when using `compile: true`. They don't cause any issues other than taking up disk space though.
```sh
$ ls -l public/packs/
total 8552
-rw-r--r--  1 javan  staff  726792 Aug 13 09:34 application-36f6f28d8bb2d149ef05.js
-rw-r--r--  1 javan  staff  726656 Aug 13 09:25 application-80ad03e43e4985328a12.js
-rw-r--r--  1 javan  staff  726650 Aug 13 09:26 application-993dbe16ed29dc8140b3.js
-rw-r--r--  1 javan  staff  726583 Aug 13 12:04 application-af0bc9664b9ae1f2f16f.js
-rw-r--r--  1 javan  staff  726657 Aug 13 09:24 application-b7a493dff2893b275ecc.js
-rw-r--r--  1 javan  staff  726699 Aug 13 09:31 application-b80de4c6d16e778d6472.js
-rw-r--r--  1 javan  staff      68 Aug 13 12:04 manifest.json
```

**Comment by gauravtiwari** [comment]
@javan May be we do clobber before running compile again?

**Comment by javan** [comment]
Yeah, that's worth exploring
