### ISSUE TITLE
Slim down the README

### ISSUE THREAD

**Issue by javan** [rails/webpacker#645]
The README has accumulated a lot of baggage that document webpacker changes, gotchas, and workarounds. I propose we pare it down to the basics and move non-essential bits to the wiki.

**Comment by gauravtiwari** [comment]
👍  💯

**Comment by dhh** [comment]
👍👍

**Comment by justin808** [comment]
Rather than a wiki, consider having a `/docs`, like we've done for https://github.com/shakacode/react_on_rails/tree/master/docs

The problem with the wiki is that you cannot change the branch and get relevant docs. Plus, doc changes can go into PRs.

**Comment by gauravtiwari** [comment]
@dhh May be we can have a page like this: http://guides.rubyonrails.org/asset_pipeline.html for webpacker too 😄  😉

**Comment by jeromedalbert** [comment]
Looks like this issue can be closed
