### ISSUE TITLE
Errno::ENOENT: No such file or directory @ rb_sysopen config/webpacker.yml

### ISSUE THREAD

**Issue by ytbryan** [rails/webpacker#663]
The webpacker's master branch (rails v5.1.3, ruby 2.4) is giving this error when i run `rails webpacker:install` on an existing rails project. The immediate solution is to use `gem 'webpacker', '~> 2.0'` instead. 

> Errno::ENOENT: No such file or directory @ rb_sysopen - /Users/ytbryan/Desktop/X/vue-X/config/webpacker.yml
> /Users/ytbryan/Desktop/Doerlist/X/config/environment.rb:5:in `<top (required)>'
> /Users/ytbryan/Desktop/Doerlist/X/bin/rails:9:in `require'
> /Users/ytbryan/Desktop/Doerlist/X/bin/rails:9:in `<top (required)>'
> /Users/ytbryan/Desktop/Doerlist/X/bin/spring:14:in `require'
> /Users/ytbryan/Desktop/Doerlist/X/bin/spring:14:in `<top (required)>'
> ./bin/rails:3:in `load'
> ./bin/rails:3:in `<main>'
> Tasks: TOP => app:template => environment
> (See full trace by running task with --trace)
> 

I will look at this when I'm free. Feel free to report or PR if you find out what's wrong.

**Comment by gauravtiwari** [comment]
@ytbryan Is `config/webpacker.yml` present?

**Comment by ytbryan** [comment]
@gauravtiwari nope then again, `rails webpacker:install` is supposed to install that. 

I think it was introduced in #636 

Specifically, [Line 9 of configuration.rb](https://github.com/rails/webpacker/blob/bd99b3274817e9dde8e2a43b3baf13c4138a07b4/lib/webpacker/configuration.rb#L9),  expecting `config/webpacker.yml` to be present but it is not produced yet. See full trace

> > ~/D/app ❯❯❯ rails webpacker:install                                 ⏎
> rails aborted!
> Errno::ENOENT: No such file or directory @ rb_sysopen - > /Users/ytbryan/Desktop/webpacker/lib/webpacker/configuration.rb:59:in `read'
> /Users/ytbryan/Desktop/webpacker/lib/webpacker/configuration.rb:59:in `read'
> /Users/ytbryan/Desktop/webpacker/lib/webpacker/configuration.rb:59:in `load'
> /Users/ytbryan/Desktop/webpacker/lib/webpacker/configuration.rb:9:in `refresh'
> /Users/ytbryan/Desktop/webpacker/lib/webpacker/commands.rb:14:in `bootstrap'
> /Users/ytbryan/Desktop/webpacker/lib/webpacker.rb:18:in `bootstrap'
> /Users/ytbryan/Desktop/webpacker/lib/webpacker/railtie.rb:32:in `block in <class:Engine>'
> /Users/ytbryan/Desktop/app/config/environment.rb:5:in `<top (required)>'
> /Users/ytbryan/Desktop/app/bin/rails:9:in `require'
> /Users/ytbryan/Desktop/app/bin/rails:9:in `<top (required)>'
> /Users/ytbryan/Desktop/app/bin/spring:15:in `require'
> /Users/ytbryan/Desktop/app/bin/spring:15:in `<top (required)>'
> ./bin/rails:3:in `load'
> ./bin/rails:3:in `<main>'
> Tasks: TOP => app:template => environment
> (See full trace by running task with --trace)
> ~/D/app ❯❯❯                                                         ⏎
