### ISSUE TITLE
Packs not being compiled on-demand in development environment

### ISSUE THREAD

**Issue by speckins** [rails/webpacker#673]
According to the [README](https://github.com/rails/webpacker/blob/3bdcad7b50f5c04dbc8820e58aec95600ad25d2e/README.md#developing-with-webpacker), webpacker compiles on demand in the development environment:

> In development, Webpacker compiles on demand rather than upfront by default. This happens when you refer to any of the pack assets using the Webpacker helper methods. That means you don't have to run any separate process. Compilation errors are logged to the standard Rails log.

In a new Rails 5.1.3 application generated with --webpack and with the following modifications:

**app/views/layouts/application.html.erb**
`<%= javascript_pack_tag    'application' %>`

**config/routes.rb**
`root to: 'application#index'`

**app/views/application/index.html**
_Empty file_

...I get the following error:

> **Webpacker::FileLoader::NotFoundError in Application#index**
> _Can't find application.js in ~/rails513-webpack/public/packs/manifest.json. Is webpack still compiling?_

After a manual invocation of "bin/rake webpacker:compile", the application.js pack loads without error but fails to update on-demand when app/javascript/packs/application.js is modified, as the documentation above would indicate it should.

(Tested on rails master - 5.2.0.alpha just now; same behavior.  Also probably a duplicate of #671.)

**Comment by gauravtiwari** [comment]
It’s on latest master (unreleased) and you have to reinstall webpacker.

**Comment by speckins** [comment]
Ah, thanks @gauravtiwari 

Confirmed.  Adding the following to the Gemfile...

`gem 'webpacker', github: "rails/webpacker"`

...followed by `bundle install` and `bin/rake webpacker:install` and the packs are now being built on-demand.

**Comment by gauravtiwari** [comment]
Awesome 👍
