### ISSUE TITLE
"localhost:8080/packs/application.js net::ERR_CONNECTION_REFUSED" after compiling 

### ISSUE THREAD

**Issue by Drillan767** [rails/webpacker#682]
Hello,

This is the first time ever I put a Rails / Webpacker to production so I might have forgotten something.
So I finished my development, put it on my server, and started to put it to production. I bundle installed the gem in deployment mode ( `bundle install --without development test `), ran the db creation to production, solved a few rake secrets problem, then ran `rake assets:precompile`, since I use sprocket for a few things.

Everything went smoothly, but when I reloaded the page, I noticed that my React gem is telling me that React has been put to prod, however my login page (where I'm supposed to land on connection is white, the DOM is loaded , the compiled files too but I have the error:

```localhost:8080/packs/application.js net::ERR_CONNECTION_REFUSED```

i guess that it expects Webpacker to run as a server, but it shouldn't.

What am I missing?

Thank you in advance

**Comment by gauravtiwari** [comment]
@Drillan767 Are you using webpacker 2.0 or from github?

**Comment by Drillan767** [comment]
I'm using Webpacker, with Rails 5.1

**Comment by gauravtiwari** [comment]
Also when you ran `rake assets:precompile` have you set RAILS_ENV or NODE_ENV to production i.e. `NODE_ENV=production rake assets:precompile`

**Comment by gauravtiwari** [comment]
I understand, I meant version of Webpacker

**Comment by gauravtiwari** [comment]
Can you also `cat` the content of manifest.json from production server? Also by any change you have set `ASSET_HOST` env when deploying to production?

**Comment by Drillan767** [comment]
`cat public/packs/manifest.json` gives the following:

``` json
cat public/packs/manifest.json
{
  "application.js": "http://localhost:8080/packs/application.js",
  "application.js.map": "http://localhost:8080/packs/application.js.map",
  "logo.png": "http://localhost:8080/packs/logo.png"
}

```

And where can I find this `ASSET_HOST` ? I set `RailsEnv` to production (I'm using Passenger) but other than that, it doesn't ring any bell..

**Comment by gauravtiwari** [comment]
@Drillan767 Strange that you got `http://localhost:8080` inside manifest.json, it should be relative in production env. That's why I asked if you could check that env `ASSET_HOST` is being set (you can check this in rails console - `ENV['ASSET_HOST']`). Btw, did you run `assets:precompile` on remote server or locally? 

In 2.0 we were embedding host info inside manifest.json. 

Perhaps you could pin your gem to Github and run `bundle exec rails webpacker:install`. We fixed a lot of issues and 3.0 will be released soon but for now you have to use master branch.

**Comment by Drillan767** [comment]
II ran `assets:precompile` to a remote server where the website I'm working on is hosted, but I can't connect right now so I can't tell you what's up with `ASSSET_HOST` until this evening.

Plus, I did run webpacker:install at the beginning of the development, but never again. Should I do it one more time?

**Comment by gauravtiwari** [comment]
> Plus, I did run webpacker:install at the beginning of the development, but never again. Should I do it one more time?

Yes please, after updating the Gemfile

```rb
gem 'webpacker', github: 'rails/webpacker'
```

**Comment by Drillan767** [comment]
I updated the Gemfile, ran the command and Webpacker got updated to 2.7.1.
I tried to recompile everything again, but I have a weird syntax error that I can't hanfle from my cell phone, I will keep you in touch this evening!

**Comment by gauravtiwari** [comment]
Sure, after updating gemfile: 

```
bundle update webpacker
bundle exec rails webpacker:install
```

**Comment by Drillan767** [comment]
So I did all this (it was tricky but finally webpacker got updated).
I also realized that when I installed webpacker, React (that I used) wasn't installed according to the "unexpected tokens" I got while compiling.
So I installed webpack by doing `rake webpacker:install:react`, everything went smoothly, I recompiled after this, but nothing shows up, and, in my console. I now have the following error:

```Failed to load resource: net::ERR_CONNECTION_REFUSED```

**Comment by gauravtiwari** [comment]
@Drillan767 Are you getting that error on production?

**Comment by Drillan767** [comment]
Yes I am!

(BTW I wanted to say "I installed React at my last comment, but I guess you had it" )

**Comment by gauravtiwari** [comment]
Is it possible you can share the app please? Like on Github so I can see what's wrong. 

BTW, just deployed an example app to heroku - https://github.com/gauravtiwari/webpacker-example-app (https://webpacker-example-app.herokuapp.com/)

**Comment by Drillan767** [comment]
[https://github.com/Drillan767/saint_gufre](https://github.com/Drillan767/saint_gufre)

Here you go, hope you can find what I couldn't... 

Thank you for your time!

**Comment by gauravtiwari** [comment]
@Drillan767 Your app is using really old version of webpacker (1.2). Updated it to master and made a PR: https://github.com/Drillan767/saint_gufre/pull/1

**Comment by Drillan767** [comment]
Just letting a message here because even though I accepted your pull request, I just didn't have the time to thank you properly. I had waaaay too much work to do even though I kept an eye on what you did in your PR. After a bit of tweaks (just 2 gems missing, one misplaced) it worked like a goddamn charm. 

THANK. YOU. A LOT.

 And all hail the Ruby on Rails community !

**Comment by gauravtiwari** [comment]
@Drillan767 Awesome, glad it worked out 🎉  🍰

**Comment by Drillan767** [comment]
I just have one question, if one day (not planned yet) I want to edit some stuff, I have to recompile everything, right? 

(I'm asking this because I use the '/packs/application.js' and the React installation always corrupts what I write in it)
