### ISSUE TITLE
Assets referenced through webpack are not using the proxy

### ISSUE THREAD

**Issue by willcosgrove** [rails/webpacker#686]
I'm running Webpacker from master, and I've got some assets that I'm referencing from my JS files by way of the Babel Module Resolver plugin [(mentioned in the readme here)](https://github.com/rails/webpacker#using-babel-module-resolver).  The assets I'm importing are images, and I'm displaying them through a React app.  But the URL given to me when I import the files is not going through the webpack-dev-server proxy that Webpacker sets up.

I don't know if this is by design or not.  But my case for why it would be helpful if it did, goes like this:

We're trying to test out our web app on a mobile device.  So we use a proxying service called [ngrok](https://ngrok.com/) to make our local rails development server available publicly.

We were using Webpacker `~> 2.0` initially, but we were having to set up two tunnels to two separate hosts to connect to both the rails dev server and the webpack-dev-server.  I noticed, browsing through the Webpacker project, that a proxy had been added so we upgraded to pull Webpacker from master.  It worked great _except_ for the image assets we were pulling in.

```js
import MyImage from "assets/images/my_image.png"

console.log(MyImage) // "http://localhost:3035/packs/my_image.png"
```

The URLs given to us from the import include the asset host (localhost:3035), as webpack understands it to be, as opposed to proxying to the webpack-dev-server.  One way of resolving this, and what we're currently doing, is overriding the `ASSET_HOST` env variable provided to webpack-dev-server [(here)](https://github.com/rails/webpacker/blob/33a71339e2cb3efc131f88449261ca7e1d56ad5d/lib/install/bin/webpack-dev-server.tt#L57) to the same tunnel host as the Rails dev server.

```rb
env = {
  "NODE_PATH" => NODE_MODULES_PATH.shellescape,
  # "ASSET_HOST" => DEV_SERVER_ADDR.shellescape
  "ASSET_HOST" => "my-awesome-rails-app.ngrok.io"
}
```

But the ideal way to fix it would be to remove the host info from the URI entirely, so that the value given to me from importing was just `/packs/my-asset.png`.  That would allow the Webpacker proxy to handle it directly.

Let me know if this functions as intended, or if this is something that should be changed.  I'm game to help out in any way I can!

**Comment by gauravtiwari** [comment]
Pushed a fix on master 👍
