### ISSUE TITLE
Taking long time to compile

### ISSUE THREAD

**Issue by ulugbekov** [rails/webpacker#687]
One line of any js change is making webpack to compile all sass files.
Is there any flag to make it stop doing that.

Webpack version 2.

**Comment by gauravtiwari** [comment]
Are you using watcher or dev server? What version of webpacker is 2.0?

**Comment by ulugbekov** [comment]
Hi,
Yes webpack 2.
Using dev server.

**Comment by gauravtiwari** [comment]
@ulugbekov Probably related to how you have structured your app? Where are the sass files located? If inside `packs` directory consider them moving out the `source_path` i.e. `app/javascript`. More discussion here: https://github.com/rails/webpacker/issues/599
