### ISSUE TITLE
aliasing imported images

### ISSUE THREAD

**Issue by bk-brandung** [rails/webpacker#688]
I have the following `packs/application.js`:

```javascript
// ...
import 'images/logo/128.png';
import 'images/logo/256.png';
import 'images/logo/512.png';
import 'images/logo/1024.png';
// ...
```

In my Template I want to use one of the logos. I figured out that this just works like this: `asset_pack_path('512.png')`.

This is not optimal in my opinion, due to the fact that there may be other images named `512.png` and this would lead to naming collisions. Is there a way to alias the images?

I've tried that:

```javascript
import logo512 from 'images/logo/512.png';
```

and `asset_pack_path('logo512')`.

But that doesn't work.

Any idea?

**Comment by gauravtiwari** [comment]
@bk-brandung Perhaps you may wanna prefix images as `logo_512.png`, `logo_1024.png` etc?

**Comment by bk-brandung** [comment]
That's my workaround if there is no other solution :)

**Comment by gauravtiwari** [comment]
Made a PR - https://github.com/rails/webpacker/pull/695

**Comment by phortx** [comment]
Awesome! Thanks for the quick solution. Kudos 👍
