### ISSUE TITLE
Yarn dependency management. 

### ISSUE THREAD

**Issue by cgarvis** [rails/webpacker#69]
Thoughts on creating a babel preset or a npm package with all the dependencies this needs?

Seems easier than managing this line: https://github.com/babel/babel/tree/master/packages/babel-preset-latest

**Comment by merqlove** [comment]
I'm also had thoughts about splitting styles/js dep's in a single package.json, but currently yarn/npm does not support groups other than `optional`, `dev`. Optional works for me, but i hate this way.

**Comment by gauravtiwari** [comment]
#264 addresses this
