### ISSUE TITLE
Pass custom environment variables to the compiler

### ISSUE THREAD

**Issue by sjchmiela** [rails/webpacker#691]
Given deployment flow using Capistrano, one would like to pass custom environment variables, like current revision hash or some access tokens (to upload source map to Rollbar or API key for Google Maps) to Webpack, so it can compile them into generated code.

I suppose it could be done by extending [`webpack_env`](https://github.com/rails/webpacker/blame/master/lib/webpacker/compiler.rb#L71) method on `Webpacker::Compiler`?

**Comment by gauravtiwari** [comment]
@sjchmiela Good Point 👍  We probably wanna expose an `env` accessor like `watched_paths` to extend default env variables on compiler.

```rb
Webpacker::Compiler.env['FOO'] = 'bar'

=> Webpacker.compiler.env
=> { ASSET_HOST: 'x', FOO: 'bar', ....}
```

cc// @dhh

**Comment by dhh** [comment]
That sounds reasonable to me 👍

**Comment by sjchmiela** [comment]
Great! 👍 I'll submit a PR in a couple of hours. 

Dnia 24.08.2017 o godz. 16:32 David Heinemeier Hansson <notifications@github.com> napisał(a):

**Comment by TheRusskiy** [comment]
@sjchmiela if you don't mind me asking, how does one use this with capistrano? Specifically for setting `current_revision`.

**Comment by TheRusskiy** [comment]
I ended up doing
```
if File.exist?('REVISION')
  Webpacker::Compiler.env['CURRENT_REVISION'] = File.read('REVISION').strip
end
```
in my `application.rb`

**Comment by sjchmiela** [comment]
I've ended up using something similar:

```rb
# config/initializers/revision.rb
git_sha, = Open3.capture3('git rev-parse HEAD')
revision, _, revision_status = Open3.capture3('cat REVISION')

HealthNation::Application::REVISION =
  if revision_status.success?
    revision.chomp
  else
    git_sha.chomp
  end
```

and in `initializers/webpacker.rb`

```rb
Webpacker::Compiler.env['VERSION'] = HealthNation::Application::REVISION
```

**Comment by TheRusskiy** [comment]
@sjchmiela I see, thank you for responding!

**Comment by nozpheratu** [comment]
I noticed custom environments variables defined in this manner don't seem to be made available to Webpacker-compiled JavaScript via the `process.env` directive -- would I be wrong to assume that a file defined in `initializers/webpacker.rb` with the contents:

```ruby
Webpacker::Compiler.env['VERSION'] = '1.0'
```

should assign `process.env.VERSION` in JavaScript?

**Comment by bbugh** [comment]
I'm having the same issue as @nozpheratu  - setting variables with `Webpacker::Compiler.env` doesn't seem to make it into the actual javascript environment. Anyone have a suggestion? Did this break somewhere?

**Comment by gauravtiwari** [comment]
@bbugh Could you please file a separate issue for this one so we can test and push a fix?

**Comment by bbugh** [comment]
@gauravtiwari Whoops, sorry - I thought this one was still open. Too many related tabs. I will make another issue.
