### ISSUE TITLE
Need a Gem Version Released

### ISSUE THREAD

**Issue by justin808** [rails/webpacker#693]
I'd like to release [React on Rails](https://github.com/shakacode/react_on_rails) based on what is in master.

Can we cut a gem version? or at least a beta? or rc?

If not, is there a checklist of what needs to be done?

Thanks,

Justin

**Comment by dhh** [comment]
Things haven't changed much since we discussed this a few days ago 😄. We're looking at extracting a bunch of the generated JavaScript configuration into an NPM module, such that upgrading between versions will be smoother. @javan is looking at that.

I get that you're eager for a release, but I'd recommend just offering the github path for now. It doesn't make sense to release a 3.0 if we have another major change pending.

**Comment by justin808** [comment]
@dhh Any gut feel if there will be breaking changes in the config setup or ruby helpers?

Until release, any recommendations for React on Rails?

1. Depend on master branch from rails/webpacker and the Gemfile.lock and/or commit references to lock to an older version if needed.
2. Depend on branch from shakacode/webpacker, say `react-on-rails-9`
   * Tip of this branch works with react-on-rails
   * If any breakage occurs, then I'll create a tag, say `react-on-rails-9.0.0` and the next/current tip of React on Rails can point to the tip of the branch.

**Comment by dhh** [comment]
The JS config setup will definitely change, the whole point would be to slim that down dramatically. But I don't think we need to make any changes to config/webpacker.yml or the Ruby helpers.

I wouldn't make an official release of React on Rails that depends on this work until we're finished. But you can definitely encourage the adventurous to do the master tie. That's what we're doing in Basecamp 3, depending on master Webpacker.

**Comment by justin808** [comment]
@dhh I will look into having my generator for an example app to depend on the webpacker setup. My only issue with the current setup is that we need a different entry point for the server rendering bundle, so bundle content does not just vary by the env (test vs. production) but also in terms of client vs. server.
