### ISSUE TITLE
How do I put React in production mode?

### ISSUE THREAD

**Issue by Drillan767** [rails/webpacker#696]
I read the documentation quite a lot of time but i still can't figure this out, I finished building and compiling my application using Webpacker and React, but I just noticed that the React [extension](http://imgur.com/a/b3Uet) in my Chrome browser says that I'm using the development mode of React. How do I set it to production?

I read a lot of StackOverflow posts saying that you need to edit the package.json file and add some elements in it, but it always refer to a `webpack.config.js` , and i'm not really sure about where I cand find this file -- if it exists anywhere else than in `node_module`.

My most sincere apologies if this is an already asked question or if the answer is obvious, but I can't anything about this topic anywhere.

**Comment by gauravtiwari** [comment]
@Drillan767 You would need to set `NODE_ENV=production` or `RAILS_ENV=production`

```rb
NODE_ENV=production bundle exec rails assets:precompile
```

**Comment by Drillan767** [comment]
Thank you, it was way easier than I thought!

**Comment by mayordwells** [comment]
@gauravtiwari @Drillan767 if you are hosting on a platform like Heroku, where do you set 

`NODE_ENV=production` or `RAILS_ENV=production`

`NODE_ENV=production bundle exec rails assets:precompile`

??

**Comment by gauravtiwari** [comment]
You could set `NODE_ENV=production` in Heroku env variables: 

```bash
heroku config:set NODE_ENV=production
```

**Comment by Drillan767** [comment]
If it might help, I recently learned that running "rails webpacker:compile" without providing any environment will set the ENV to "production" by default (and do the work)
