### ISSUE TITLE
Vue.js + Jest

### ISSUE THREAD

**Issue by phortx** [rails/webpacker#698]
Has someone managed to get this combination running?

I've tried it and already solved some issues but currently im hanging on the fact that the vue files can't be compiled.

Im running jest via `NODE_ENV=test yarn run jest` and I get: `SyntaxError: Unexpected token <` when importing a vue component file.

Any idea?

**Comment by gauravtiwari** [comment]
@phortx You would need to configure Jest to load and process vue files. https://github.com/vire/jest-vue-preprocessor

**Comment by phortx** [comment]
It works! Awesome. You're my hero :)

**Comment by bbugh** [comment]
If anyone else ends up here from the first couple of search results, here's a good resource for how to set this up easily: https://wyeworks.com/blog/2018/1/16/Testing-Vuejs-in-Rails-with-Webpacker-and-Jest
