### ISSUE TITLE
Add config option to skip precompile enhancement

### ISSUE THREAD

**Issue by justin808** [rails/webpacker#707]
Pertaining to #440 from @mipearson...

@gauravtiwari, @dhh Could we add a configuration option to skip the running of the compile task?

I'm happy to submit a PR if you tell me what you want the config value to be.

This was suggested by @mipearson as a workaround:

```ruby
%w{assets:clobber assets:precompile}.each do |task_name|
  Rake::Task[task_name].instance_eval do
    @actions.reject! { |action| action.source_location[0] =~ /webpacker/ }
  end
end
```

However, this looks quite fragile.

React on Rails provides its own enhancement, and we don't want both to run:

https://github.com/shakacode/react_on_rails/blob/master/lib/tasks/assets.rake#L49

```ruby
namespace :react_on_rails do
  namespace :assets do
    desc <<-DESC.strip_heredoc
      Compile assets with webpack
      Uses command defined with ReactOnRails.configuration.npm_build_production_command
      sh "cd client && `ReactOnRails.configuration.npm_build_production_command`"
    DESC
    task webpack: :locale do
      if ReactOnRails.configuration.npm_build_production_command.present?
        sh "cd client && #{ReactOnRails.configuration.npm_build_production_command}"
      end
    end
  end
end
```

**Comment by gauravtiwari** [comment]
@justin808 You can clear the compile task, no?: 

```rb
if Rake::Task.task_defined?("webpacker:compile")
  Rake::Task["webpacker:compile"].clear
  #... anything else to clear
end
```

**Comment by dhh** [comment]
In the case of React on Rails, why even piggy back off the existing tasks? I thought you guys weren't using the asset pipeline as well?

**Comment by justin808** [comment]
@dhh If the bin stubs are not installed, then the precompile task fails. @gauravtiwari's solution solves this problem.
