### ISSUE TITLE
How do you upgrade from 2.x to 3.x?

### ISSUE THREAD

**Issue by timrogers** [rails/webpacker#721]
Are there any steps I'm expected to take to move from 2.x to 3.x? The CHANGELOG suggests there are breaking changes (although it has two "breaking changes" sections, which I'm a little confused by...) and alludes to re-running to install command. 

However, my application seems to continue to work as expected (i.e. as before) with no changes.

**Comment by gauravtiwari** [comment]
@timrogers The application should work as usual if there aren't many changes to webpack config. We mentioned `breaking changes` as-in you will have to cleanup certain old files as outlined here: https://github.com/rails/webpacker/blob/master/CHANGELOG.md#breaking-changes

These are the only files that needs to stay `config/webpack/{environment,development,test,production}.js` and rest can go away after running the installer.

**Comment by timrogers** [comment]
Okay - thanks!
