### ISSUE TITLE
undefined method `lookup' for Webpacker::Manifest:Class

### ISSUE THREAD

**Issue by beaver1992** [rails/webpacker#726]
After upgrading to Webpacker 3.0 get this error:
'undefined method `lookup' for Webpacker::Manifest:Class'

use with react-rails. Before update everything was good.

**Comment by gauravtiwari** [comment]
@beaver1992 We updated the manifest lookup API - please could you open this issue on `react-rails` repo for a fix.

**Comment by beaver1992** [comment]
ok, thank you
