### ISSUE TITLE
yarn 0.20.3 doesn't generate bin script for sub-dependencies in node_modules/.bin/

### ISSUE THREAD

**Issue by shaokun** [rails/webpacker#735]
When running with node 6.11.2 and yarn 0.20.3, after installing the webpacker, it doesn't generate bin script for sub-dependencies in node_modules/.bin/ so the bin/webpack script will be failed, since it's relied on node_modules/.bin/webpack.

After updated to 0.27.5, this issue is resolved.

The Prerequisites of webpacker is Yarn 0.20.1+. Probably need to update that information.

Might related to https://github.com/yarnpkg/yarn/issues/2874

**Comment by gauravtiwari** [comment]
We already pushed a fix here (https://github.com/rails/webpacker/commit/9e34e444a605538add73b49cf96aab2629c9d674) but forgot to update the README 

Done, thanks 👍  🍰
