### ISSUE TITLE
Heroku and webpacker v3.0.0

### ISSUE THREAD

**Issue by vavgustov** [rails/webpacker#739]
Heroku can't precompile assets with webpacker v3.0.0 but v.2.0.0 worked ok. It's because .bin/webpack doesn't exist:

```bash
➜  wb_test git:(master) heroku run rake assets:precompile
Running rake assets:precompile on ⬢ guarded-fortress-96119... up, run.9848 (Free)
yarn install v0.22.0
[1/4] Resolving packages...
success Already up-to-date.
Done in 1.81s.
Webpacker is installed 🎉 🍰
Using /app/config/webpacker.yml file for setting up webpack paths
Compiling…
Compilation failed:

./bin/webpack:26:in `exec': No such file or directory - /app/node_modules/.bin/webpack (Errno::ENOENT)
	from ./bin/webpack:26:in `block in <main>'
	from ./bin/webpack:25:in `chdir'
	from ./bin/webpack:25:in `<main>'
```
Content of `/app/node_modules/.bin/`:

```bash
~/node_modules/.bin $ ls
webpack-dev-server
```
Seems yarn v0.22.0 doesn't install bins for nested dependencies (in this case for `@rails/webpacker`). So if I add `webpack` as dependency then it works. It seems more like heroku/yarn issue but wanted to let you know.

**Comment by renchap** [comment]
See https://github.com/rails/webpacker/pull/727

Webpacker 3.0 requires Yarn >= 0.25.2

**Comment by vavgustov** [comment]
yes on my local machine with yarn v0.27.5 it works good. Seems heroku need some time to upgrade yarn version.

**Comment by renchap** [comment]
Looks like a PR is needed in the Ruby buildpack to change it: https://github.com/heroku/heroku-buildpack-ruby/blob/78eefa66b96fd04b4738ad8ed66d9bd038324064/lib/language_pack/helpers/nodebin.rb#L21

I suggest you open an issue on this repo, the maintainers are quite responsive.

**Comment by javan** [comment]
I just opened https://github.com/rails/webpacker/pull/740, which adds a yarn requirement to `package.json`'s "engines" section. Wonder if the buildpack could read / respect that somehow?

**Comment by gauravtiwari** [comment]
Yeah heroku respects the engines requirement - https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version, will take a look at the PR now and we can merge 👍

**Comment by javan** [comment]
I don't know if that'll work for an engines requirement from a dependency. Might only be for your app's package.json .

**Comment by gauravtiwari** [comment]
![screen shot 2017-09-01 at 15 35 04](https://user-images.githubusercontent.com/771039/29974542-2507e7a2-8f2b-11e7-8c3c-8d1fe9761407.png)

BTW just deployed an app to heroku and seems to pull in correct yarn version

**Comment by WoH** [comment]
@gauravtiwari It seems like you are using multiple (node + ruby) buildpacks.
People affected might be the ones only using the ruby buildpack.

**Comment by javan** [comment]
If you need a temporary workaround, you can update your app's `bin/webpack` to use `yarn run`:
```diff
--- a/bin/webpack
+++ b/bin/webpack
@@ -20,7 +20,7 @@ unless File.exist?(WEBPACK_CONFIG)
 end
 
 env = { "NODE_PATH" => NODE_MODULES_PATH.shellescape }
-cmd = [ "#{NODE_MODULES_PATH}/.bin/webpack", "--config", WEBPACK_CONFIG ] + ARGV
+cmd = [ "yarn", "run", "webpack", "--config", WEBPACK_CONFIG ] + ARGV
```

**Comment by gauravtiwari** [comment]
@WoH Oh yes, can confirm - since it's hardcoded. I guess the easiest fix would be to use both ruby and node js buildpack together and that way you don't need to modify anything for now 👍 

```bash
heroku buildpacks:set heroku/ruby
heroku buildpacks:set heroku/nodejs
```

**Comment by gauravtiwari** [comment]
//cc @schneems @hone

**Comment by johnrees** [comment]
@gauravtiwari `heroku buildpacks:set` will overwrite any previous buildpack(s) with the single buildpack you specify. I think the 'safe' way to run these commands would be -

`heroku buildpacks:add heroku/nodejs`
`heroku buildpacks:add heroku/ruby` (which you probably already have, so will return 'The buildpack heroku/ruby is already set on your app'.)

**Comment by caseyprovost** [comment]
@vavgustov I believe you should be all set here now. I am using webpacker 3 with vue 2 and rails 5.1 on Heroku just swimmingly :) Feel free to reach out if you are still having issues and maybe I can help you out.

**Comment by vavgustov** [comment]
@caseyprovost thanks, yes I also use solution with node buildpack and found it optimal while heroku works on ruby buildpack improvements. I guess they will add support for `engines` section for ruby buildpack or at least upgrade yarn.

From my side I would recommend these links for those who have troubles with node + ruby buildpacks:
- specify node/npm/yarn version: https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version. By the way webpacker already added yarn version in v3.0.1: https://github.com/rails/webpacker/blob/9d29ddd14c2cbe94f4aad154a92f4a2a40b498fd/package.json#L11
- how to add node buildpack and why order is important: https://devcenter.heroku.com/articles/using-multiple-buildpacks-for-an-app#adding-a-buildpack

**Comment by kylefox** [comment]
Just wanted to add that @johnrees's solution worked for me. I ran these commands and the next deploy worked 👍   

```
heroku buildpacks:clear
heroku buildpacks:set heroku/nodejs
heroku buildpacks:add heroku/ruby
```

**Comment by gauravtiwari** [comment]
@johnrees thanks 💯  👍

**Comment by schneems** [comment]
Sorry for the delay responding here. 

You can also do a `heroku buildpacks:add heroku/nodejs -i 0` to set nodejs first.

Upgrading the system version of Yarn to v1.0.2 would resolve the issue. Any problems doing that?

**Comment by gauravtiwari** [comment]
@schneems Thanks, that should work 👍  💯

**Comment by casiodk** [comment]
`heroku buildpacks:add heroku/nodejs -i 1` is the proper command

**Comment by antwonlee** [comment]
Thank you!  👍 💯

**Comment by kofronpi** [comment]
Is it mandatory to fiddle with the heroku buildpacks or is it a temporary fix ?

**Comment by gauravtiwari** [comment]
Until this PR is merged: https://github.com/heroku/heroku-buildpack-ruby/pull/620

**Comment by schneems** [comment]
I just merged in yarn 1.0.2 into the master branch of the buildpack. If there's no regressions or issues reported then i'll deploy it shortly. In the mean time use the `heroku/nodejs` buildpack.

**Comment by schneems** [comment]
To wrap things up, I deployed Yarn 1.0.2 today which should fix this up https://devcenter.heroku.com/changelog-items/1270.

**Comment by javan** [comment]
Thank you, @schneems!

**Comment by AdamT** [comment]
Pushing to Heroku I get the compilation failure in the output.
```
remote: -----> Installing node-v6.11.1-linux-x64
remote: -----> Installing yarn-v1.0.2
remote: -----> Detecting rake tasks
remote: -----> Preparing app for Rails asset pipeline
remote:        Running: rake assets:precompile
remote:        Webpacker is installed 🎉 🍰
remote:        Using /tmp/build_33ca1c3c1a48a7a9ec42a1429cb5fb45/config/webpacker.yml file for setting up webpack paths
remote:        Compiling…
remote:        Compilation failed:
remote:        ./bin/webpack:26:in `exec': No such file or directory - /tmp/build_33ca1c3c1a48a7a9ec42a1429cb5fb45/node_modules/.bin/webpack (Errno::ENOENT)
remote:        from ./bin/webpack:26:in `block in <main>'
remote:        from ./bin/webpack:25:in `chdir'
remote:        from ./bin/webpack:25:in `<main>'
remote:        Asset precompilation completed (2.88s)
remote:        Cleaning assets
remote:        Running: rake assets:clean
```

Rails 5.1.4
Webpacker 3.0.2

This seems like the same issue. 

When I add the nodejs buildpack via:
```
heroku buildpacks:add heroku/nodejs -i 1
```
then the compile works

**Comment by prrrnd** [comment]
Also getting the same compilation failure as @AdamT when removing the nodejs buildpack.

**Comment by gauravtiwari** [comment]
Could be related to yarn version being used with ruby buildpack? `Installing yarn-v1.0.2` What version of yarn it is using when you deploy with nodejs buildpack?

**Comment by prrrnd** [comment]
It seems to be related, yes. With the nodejs buildpack, yarn 1.3.2 gets installed vs. yarn 1.0.2 with the ruby buildpack.

**Comment by gauravtiwari** [comment]
Also, I see in the log it's not running `yarn install` after installing yarn so, that could be the problem too. Do you have a `webpack` and `yarn` binstub in your `./bin/*` directory?

**Comment by prrrnd** [comment]
Yes, I do have those binstubs. Anyway, it seems that going for the nodejs buildpack first is the solution as per [this comment](https://github.com/heroku/heroku-buildpack-ruby/pull/620#issuecomment-332302820).

**Comment by sambecker** [comment]
FWIW `heroku buildpacks:add heroku/nodejs -i 1` didn't properly reorder buildpacks for me.

I needed to manually reorder them from the Heroku dashboard in order for my deploy to work.
