### ISSUE TITLE
Getting Errno::ETIMEDOUT

### ISSUE THREAD

**Issue by mmaauu** [rails/webpacker#745]
Hi! I've added the webpacker gem, after bundle install with the gem, I run rails s and I'm getting this error, I can't figure out what's going on.
Thanks!

``
Puma caught this error: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. - user specified timeout (Errno::ETIMEDOUT)
c:/RailsInstaller/Ruby2.3.0/lib/ruby/2.3.0/socket.rb:61:in `connect_internal'
c:/RailsInstaller/Ruby2.3.0/lib/ruby/2.3.0/socket.rb:139:in `connect'
c:/RailsInstaller/Ruby2.3.0/lib/ruby/2.3.0/socket.rb:636:in `block in tcp'
c:/RailsInstaller/Ruby2.3.0/lib/ruby/2.3.0/socket.rb:231:in `each'
c:/RailsInstaller/Ruby2.3.0/lib/ruby/2.3.0/socket.rb:231:in `foreach'
c:/RailsInstaller/Ruby2.3.0/lib/ruby/2.3.0/socket.rb:626:in `tcp'
c:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/webpacker-3.0.0/lib/webpacker/dev_server.rb:9:in `running?'
c:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/webpacker-3.0.0/lib/webpacker/dev_server_proxy.rb:7:in `rewrite_response'
c:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/rack-proxy-0.6.2/lib/rack/proxy.rb:57:in `call'
c:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.1.3/lib/rails/engine.rb:522:in `call'
c:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/puma-3.10.0/lib/puma/configuration.rb:225:in `call'
c:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/puma-3.10.0/lib/puma/server.rb:605:in `handle_request'
c:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/puma-3.10.0/lib/puma/server.rb:437:in `process_client'
c:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/puma-3.10.0/lib/puma/server.rb:301:in `block in run'
c:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/puma-3.10.0/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
``

**Comment by gauravtiwari** [comment]
@mmaauu Are you using latest webpacker?

**Comment by gauravtiwari** [comment]
We just released 3.0.1, consider upgrading and see if it fixes the problem. You are not running webpack-dev-server though, right?

**Comment by mmaauu** [comment]
Thanks @gauravtiwari for your response, I've updated the gem ( $ bundle show webpacker
c:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/webpacker-3.0.1 ), but without luck, same error.

I'm just trying to install webpacker gem to start using it with react, I'm not using webpack-dev-server.

**Comment by gauravtiwari** [comment]
@mmaauu Thanks for confirming. Not sure why it's proxying to dev server then. Can you share your example on github please?

**Comment by javan** [comment]
Looks like we might need to rescue from `Errno::ETIMEDOUT` here too?
https://github.com/rails/webpacker/blob/fb8dd8c09ccc9d93ef3e084838e6e0f0683aaeb0/lib/webpacker/dev_server.rb#L8-L13

Side note: It's unfortunate if `dev_server.running?` is taking 1s just to determine that it's not running.

**Comment by mmaauu** [comment]
@javan I've made an example, same issue, please check this:
https://github.com/mmaauu/webpack-example

**Comment by swrobel** [comment]
Same issue here, had it on 3.0 and now 3.0.1 using default config. I was previously using a separate dev server process but was attempting to use the new 3.x functionality that doesn't require it. On the frontend, when I try to load `http://localhost:3000/packs/application-02bd72f5b4651ad6eea4.js` individually I get a 404 error

**Comment by gauravtiwari** [comment]
@mmaauu Just cloned your repo and everything seems to be running fine. @javan Yeah, make sense or we increase the timeout?

@swrobel Are you using windows? If you are not running dev server then the on-demand compiler should compile and rails server should serve assets for you. Just make sure your webpacker.yml has `compile: true` in development.

**Comment by swrobel** [comment]
I am on macOS and as I said I’m using the default config so yes it has compile true

**Comment by Bramjetten** [comment]
I'm experiencing the same thing on my iMac with the High Sierra beta. My Macbook with Sierra works fine.

**Comment by swrobel** [comment]
Completely forgot that I'm on High Sierra beta as well.

**Comment by javan** [comment]
Does is work when `bin/webpack-dev-server` is running? Also curious if using a newer ruby version helps.

**Comment by Bramjetten** [comment]
If `webpack-dev-server` is running it's fast. Using ruby 2.4.1. Is there a different way to determine if the dev server is running besides waiting for the connection to timeout?

**Comment by javan** [comment]
Not sure, but that would be ideal. Could look into writing a tmp file when `bin/webpack-dev-server` starts/stops.

**Comment by gauravtiwari** [comment]
I guess we just need to catch `Errno::ETIMEDOUT` and that should fix the timeout problem👍 

> JavaScript is compiled, but requests take a long time (3-5 secs).

@Bramjetten  What's the size of your project?

**Comment by gauravtiwari** [comment]
> JavaScript is compiled, but requests take a long time (3-5 secs).

This could also be related to: 

> This takes about 2 seconds to raise an error on High Sierra when the webpack dev server is off:
$ curl localhost:3035

i.e. `running?` is adding 2-3s overhead on each request hence taking long time.

**Comment by javan** [comment]
In addition to rescuing `Errno::ETIMEDOUT`, it looks like we can specify a lower `connect_timeout` option. Here's an example (with the dev server running):
```ruby
>> Socket.tcp('localhost', 3035, connect_timeout: 1).close
=> nil

>> Socket.tcp('localhost', 3035, connect_timeout: 0.1).close
=> nil

>> Socket.tcp('localhost', 3035, connect_timeout: 0.0001).close
=> nil

>> Socket.tcp('localhost', 3035, connect_timeout: 0.000001).close
Errno::ETIMEDOUT: Operation timed out - user specified timeout
```

I suggest changing it from `1` to `0.1` to start.

**Comment by Bramjetten** [comment]
That looks like the way to go. In my tests I saw that `running?` was called 3 times for a single request, that's why it took 3 extra seconds for each request. Changing it to 0.1 would mean an extra 300ms for each request which is a great improvement already. Ideally we'd call `running?` fewer times.

**Comment by mmaauu** [comment]
Hi @gauravtiwari! I can't find the issue to make it work, I'm running on windows 7, do you have any idea? Thanks!!

**Comment by javan** [comment]
Curious why High Sierra hits a timeout (`Errno::ETIMEDOUT`) vs. connection refused (`Errno::ECONNREFUSED`) on Sierra. Can you try higher port numbers (4XXX, 5XXX, etc) and see if that changes anything? Did you install Ruby after upgrading your OS or did it carry over from Sierra?

**Comment by Bramjetten** [comment]
Same for other port numbers. Same for everything I give curl actually. Ruby was carried over.

**Comment by javan** [comment]
Any change if you reinstall `curl` and/or Ruby? Wonder if it needs to be recompiled against updated system libs. Just shooting in the dark here. :)

**Comment by swrobel** [comment]
Tested on another Mac running Sierra (10.12.6) and I don't get this exception but I still get a 404 @ http://localhost:3000/packs/application-02bd72f5b4651ad6eea4.js so this magical proxying doesn't seem to be working any better.

**Comment by swrobel** [comment]
Tested on another Mac running Sierra (10.12.6) and it's working just fine so this definitely seems to be a High Sierra issue.

**Comment by BrianTatum** [comment]
@mmaauu Did you ever find a solution to this for Windows? I have the same problem on Windows 10.

**Comment by mmaauu** [comment]
@BrianTatum, I've cahged to the webpacker/lib/webpacker/dev_server.rb, I added this line, hope this helps.

```
def running?
    Socket.tcp(host, port, connect_timeout: 1).close
    true
   rescue Errno::ETIMEDOUT	# ADDED
    true
  rescue Errno::ECONNREFUSED, NoMethodError
    false	
end

```

**Comment by javan** [comment]
This was fixed in https://github.com/rails/webpacker/pull/753, but hasn't been released yet. You can use it now by pointing your Gemfile to `github: 'rails/webpacker'`.

**Comment by BrianTatum** [comment]
@javan Looks like that did fix it in it Windows 10. Thanks!! What is your schedule for releasing versions?

**Comment by davidteren** [comment]
Had the same issue on High Sierra and ` pointing my Gemfile to github: 'rails/webpacker' fixes it.

**Comment by fgermanojr** [comment]
I just upgraded to high sierra on mac. Stuff was running before. Now get the above mentioned error. 
What does "pointing my Gemfile to github: 'rails/webpacker'" exactly mean. Do I put this in some form on the gem 'webpacker' line. 

---
My Environment is a bit of a cludge. Currently running rails 5.1.3. react_on_rails 9 or 10, and ruby 2.4.2. I need to do a clean reconstruction to be sure of what I have. I worry about interaction between react_on_rails gem and the changing way rails is doing this. Aside from this problem version skew issues may remain. We need some clean set up docs for react_on_rails 9 vs 10.
In time I hope to help with this.

**Comment by gauravtiwari** [comment]
`bundle update webpacker` should fix it, since this got out in last release 3.0.2

**Comment by fgermanojr** [comment]
Thanks. I made a few changes in versions (react_on_rails to 9, ruby to 2.3.4) and it comes up.
gem list is showing webpacker 3.0.1 and 3.0.1. I will follow your suggesting and be sure to have webpacker at 3.0.2.

**Comment by gauravtiwari** [comment]
👍

**Comment by navjeetc** [comment]
I had the same issue in Windows (WSL-Ubuntu 16.04) and running `bundle update webpacker` fixed the issue
