### ISSUE TITLE
bin/webpack -p fails to process jest snapshot files

### ISSUE THREAD

**Issue by ktusznio** [rails/webpacker#746]
`bin/webpack` works fine, but `NODE_ENV=production RAILS_ENV=production bin/webpack -p` fails:

```
» RAILS_ENV=production NODE_ENV=production bin/webpack -p
Hash: 9b023edef321541c6d98
Version: webpack 3.5.5
...

ERROR in application-e06269f751f2d02e6bcf.js from UglifyJs
Unexpected character '`' [./app/javascript/apps/account/components/__snapshots__/AccountPage.test.js.snap:3,0][application-e06269f751f2d02e6bcf.js:1,279057
```

The offending file:

`./app/javascript/apps/account/components/__snapshots__/AccountPage.test.js.snap`:
```js
// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`AccountPage renders 1`] = `
<section
  className="AccountPage__Wrapper-orVeb jTAEQy"
>
</section>
`;
```

A few things are weird about this:

* webpack's `uglifyjs-webpack-plugin` uses "uglify-es" which should be able to process ES6 files.
* `uglifyjs-webpack-plugin@^0.4.6` tests against `/.js($|?)/i` files, which should not match `AccountPage.test.js.snap` -- why is UglifyJs processing this file?
* I'm using `ignore-loader` with the following config -- again, why is UglifyJs processing the snapshot file?

```js
module.exports = {
  test: /.test.js.snap$/,
  loader: 'ignore-loader'
}
```

**Comment by ktusznio** [comment]
Strangely, `RAILS_ENV=production NODE_ENV=production bundle exec rails webpacker:compile` does not throw an error:

```
Webpacker is installed 🎉 🍰
Using ./config/webpacker.yml file for setting up webpack paths
Compiling…
Compiled all packs in ./public/packs
```

**Comment by javan** [comment]
I'm not sure what's causing the error, but Webpacker already configures production builds so there's no need for the `-p` flag.
https://github.com/rails/webpacker/blob/fb8dd8c09ccc9d93ef3e084838e6e0f0683aaeb0/package/environments/production.js#L9-L25

**Comment by gauravtiwari** [comment]
Yep we do and hence the error - technically you are uglifying twice. 

For ignore loader, you can just setup with extension: 

```js
module.exports = {
  test: /\.snap$/,
  loader: 'ignore-loader'
}
```

**Comment by ktusznio** [comment]
Gotcha, thank you!
