### ISSUE TITLE
yarn upgrade : The engine "yarn" is incompatible with this module

### ISSUE THREAD

**Issue by kikan** [rails/webpacker#752]
In a brand new project, if I do
```shell
➜ yarn upgrade
```

I get an incompatibility error :

```shell
yarn upgrade v0.24.5
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error @rails/webpacker@3.0.1: The engine "yarn" is incompatible with this module. Expected version ">=0.25.2".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/upgrade for documentation about this command.
```

I tried to `bundle update` first, in case (and it updated webpacker to v.3.0.1), but it still fails.

**Comment by gauravtiwari** [comment]
@kikan You would need to bump up your yarn version so if installed with brew `brew upgrade yarn` or `curl -o- -L https://yarnpkg.com/install.sh | bash` - whatever works (https://yarnpkg.com/lang/en/docs/install/#mac-tab)

**Comment by kikan** [comment]
Ok, thanks 👍. I also managed to upgrade like this :
```shell
rm -rf node_modules
yarn
```

**Comment by PritamBhanji08** [comment]
I was also facing this issue. My package.json **engines** looks like this: 
"engines": {
    "node": "6.* || 8.* || >= 10.*"
  },

i just made 

"engines": {
    "node": ">= 8.*"
  },

And it worked.
