### ISSUE TITLE
Hardcoded rake path

### ISSUE THREAD

**Issue by roine** [rails/webpacker#757]
When I run `webpacker:install` it crashes with 
```
ruby: No such file or directory -- rake (LoadError)
```

I do not have rake installed in `/bin`, it's in `/usr/bin`. I'm on **CentOs**.

**Comment by ytbryan** [comment]
Why don't you have rake in `/bin`? Which version of rails are you using?

**Comment by roine** [comment]
I'm on a vagrant machine, using rails `4.2.7`

**Comment by gauravtiwari** [comment]
Please run this: `bundle install --binstubs` to generate binstubs

**Comment by roine** [comment]
Thank you @gauravtiwari, this helped!

```
bundle binstubs rake --path bin
bundle exec rake webpacker:install
```

Now works!

**Comment by gauravtiwari** [comment]
Great 👍

**Comment by roine** [comment]
I've got one last question, why are the bin not in `$root$/bin` rather than `$root$/lib/install/bin`?

Moving the bin to `$root$/bin` would allow me to do `bundle binstubs webpacker` and I could then avoid to generate all this files that I don't need.

**Comment by gauravtiwari** [comment]
@roine Because we add those binstubs through installer - `webpacker:install` and not `bundle binstubs`

**Comment by roine** [comment]
Couldn't `webpacker:install` access the `$root$/bin` directory instead.

I'm trying to set things up for a pre existing webpack with elm code base and having to install all this stuff isn't convenient for me.
