### ISSUE TITLE
Migrating webpack plugins from webpacker v2 to v3

### ISSUE THREAD

**Issue by DmytroStepaniuk** [rails/webpacker#759]
Hello everyone! 

Previously, i have used `shared.js` to additional plugins i want (using `ProvidePlugin`)

So, since webpacker v3 - there is no more `shared.js` stuff. 

And the question is - how and where should i describe `webpack.ProvidePlugin`? Thx!

**Comment by renchap** [comment]
https://github.com/rails/webpacker/blob/master/docs/webpack.md#plugins should show you the new way :)

**Comment by gauravtiwari** [comment]
Here: https://github.com/rails/webpacker/blob/master/docs/webpack.md#plugins 👍

**Comment by DmytroStepaniuk** [comment]
Thx a lot, guys! 👍 

_Now everything that was extracted into separate files are merged into `environment` (following that doc) and it make confused little bit._
