### ISSUE TITLE
Outdated Webpack Loader Pathing in `hello_vue` Example Entry Point?

### ISSUE THREAD

**Issue by aaronransley** [rails/webpacker#760]
Hi folks,

Looking at the example entry file created by the Vue install task at `app/javascript/packs/hello_vue.js`, I'm [seeing a reference](https://github.com/rails/webpacker/blob/50aaf772a50e589f7ddf4917a3dcd22e42ee3adc/lib/install/examples/vue/hello_vue.js#L4) to a `config/webpack/loaders` dir that doesn't exist. Searching the docs, I'm not seeing any supporting information about this dir, and am wondering if the comment in the example file is referring to a now-defunct config method?

AFAIK, the "right way" to configure loaders using webpacker is through the various environment files within `config/webpack` — am I mistaken?

Thank you all for the amazing work! Webpacker really helps bridge the gap between the Ruby & JS ecosystems 👍

**Comment by gauravtiwari** [comment]
Yepp, that's from 2.0 and this example needs to updated. All base config now lives under `@rails/webpacker` npm module.  Webpack related docs are here: https://github.com/rails/webpacker/blob/master/docs/webpack.md

Thank you and enjoy 👍
