### ISSUE TITLE
SCSS Compiling

### ISSUE THREAD

**Issue by caseyprovost** [rails/webpacker#761]
Not sure if this is the right place to post assumptions, but I will give it a whirl. If you include webpacker 3 with rails 5.1 and Vue.js2 you will find that CSS that you include via the "scoped" style tags in your vue components is missing. This is due to the fact that the configuration actually extracts them out into a file per component. 

I found this very interesting since webpacker 2 did not do this, and because it creates a weird interaction where you have to include a css file in your layout that never actually exists in your written code.

To be clear, lets say you have this file in your JS:

```javascript
//PersonCard.vue
<template>
<div class="col-4">
  <div class="card PersonCard" :data-id="person.id">
    <div class="card-body">
      <h4 class="card-title">
        <router-link :to="personLink()">
          {{ person.title }}
        </router-link>
      </h4>
      <span class="badge badge-info">
        Owner
      </span>
    </div>
  </div>
</div>
</template>

<script>
  export default {
    props: [
      'person',
      'currentUser'
    ],
    methods: {
      documentLink() {
        return '/projects/' + this.person.project_id + '/people/' + this.person.id
      }
    }
  }
</script>

<style lang="scss" scoped>
  .PersonCard {
    margin-bottom: 15px;
    border-top: 3px solid #42b983;

    .badge {
      vertical-align: top;
      margin-top: 5px;
    }

    .card-title {
      display: inline-block;
    }
  }
</style>
```

You will have to include the following file in your layout:

```erb
<%= stylesheet_pack_tag 'components/PersonCard.css' %>
```

Now this could totally be because of my naitivity around modern JS tooling and webpack itself, but it seems that this should just "work" without having to dive into webpack.

In the mean time, I created these helpers to get around the issue for myself.

```ruby
module ApplicationHelper
  def stylesheet_directory_pack_tag(directory_name)
    path = File.join(Rails.root, 'app', 'javascript', 'packs', directory_name)
    content = ""

    Dir.glob("#{path}/*").each do |file|
      filename = File.basename(file).gsub('.vue', '.css')
      next unless is_dynamic_css_file?(filename)
      content << stylesheet_pack_tag("#{directory_name}/#{filename}")
      content << "\n"
    end

    raw content
  end

  def is_dynamic_css_file?(filename)
    json = JSON.parse(
      File.read(File.join(Rails.root, 'public', 'packs', 'manifest.json'))
    )

    entry = json.detect{ |path, _| path.include?(filename) }
    entry.present?
  end
end
```

Then in your layout file:

```html
<%= stylesheet_directory_pack_tag 'components' %>
```

**Comment by gauravtiwari** [comment]
@caseyprovost Do you have HMR on in `config/webpacker.yml`? In webpacker 2 there was no HMR hence the default setup was to extract CSS files however in v3 we do support HMR and so if that option is turned on we will not extract but inline the styles in respective bundles. In production mode however each bundle will produce it's respective CSS (if available).

**Comment by caseyprovost** [comment]
@gauravtiwari I am using the dev server without HMR turned on. I am invoking the server like so: `webpack_dev_server: ./bin/webpack-dev-server` via a Procfile with Foreman. 

The real question I have is, in environments where CSS is extracted how does the developer which files need to be included via a stylesheet_pack_tag and what environments to include them in?

**Comment by gauravtiwari** [comment]
@caseyprovost - You can include this tag for the packs where you have included any styles within your component. In development, this tag will be simply ignored if using dev server with HMR, if not then this will be used to link the pack styles. Obviously, you will get 404 error if a pack does not have any styles and you have included the `stylesheet_pack_tag` anyway. Does this makes sense?

`stylesheet_pack_tag` behaves same in all environments except when running dev server with HMR turned on.

**Comment by caseyprovost** [comment]
@gauravtiwari I totally get it. My comment was more around the developer experience. I would expect to be able to put in some sort of tag that includes any extracted css like with `stylesheet_pack_tag 'compiled.css'`. 

The only way I found out this behavior was by watching my terminal as it compiled my JS and noticing all the CSS files it spit out. This also caused a surprise on Heroku where styles were missing because they were not being included properly.

My question is: does it make sense to instead extract to 1 file following the montra of "convention over configuration" and have developers always include that in their layout files? It would definitely make things more intuitive.

**Comment by gauravtiwari** [comment]
Ahh I see, sorry about that. This isn't available out of the box but you can use common chunk plugin to achieve same behaviour: 

```js
const webpack = require('webpack')
const { environment } = require('@rails/webpacker')

environment.plugins.set('CommonChunk',
  new webpack.optimize.CommonsChunkPlugin({
    name: 'vendor',
    filename: 'vendor.css',
    minChunks: (module) =>
      // combine all files matching the extension in a single vendor chunk 
      module.resource && (/\.(css|sass|scss)$/i).test(module.resource)
  })
)

const extractTextPlugin = environment.plugins.get('ExtractText')
extractTextPlugin.filename = 'vendor.css'

module.exports = environment
```

Output: 

```json
{
  "application.js": "/entries/application-2b6d662cc1b355728836.js",
  "hello_react.js": "/entries/hello_react-2b24cbccfe25b2a22291.js",
  "hello_react/react.png": "/entries/hello_react/react-a949710dd6374feac3b49e0b84b1a412.png",
  "hello_vue.js": "/entries/hello_vue-39dc2553f00701c6227a.js",
  "hello_vue/vue.png": "/entries/hello_vue/vue-3e4da6668d5c06a7d5a908be9ad024b8.png",
  "images/react.png": "/entries/images/react-a949710dd6374feac3b49e0b84b1a412.png",
  "images/vue.png": "/entries/images/vue-3e4da6668d5c06a7d5a908be9ad024b8.png",
  "vendor.css": "/entries/vendor.css"
}
```

The reason why this is not included out of the box is due to varied use cases and achieving any behaviour is trivial with plugins.  

Ref: https://webpack.js.org/plugins/commons-chunk-plugin/
