### ISSUE TITLE
Cannot load html templates in Angular

### ISSUE THREAD

**Issue by eamon-hguk** [rails/webpacker#764]
After upgrading to webpacker 3 my Angular html templates no longer load. I ran the installation again to update to the latest files.

This is the error I now get:

`Uncaught Error: Module parse failed: /Users/Me/Development/MyProject/app/javascript/bookings/sales.component.html Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| <div class="container" *ngIf="sales">`

I tried following the instructions in:
[https://github.com/rails/webpacker/blob/master/docs/typescript.md](https://github.com/rails/webpacker/blob/master/docs/typescript.md)

but I am not longer sure these are relevant, surely the html-loader for the html files should be in the loaders directory, though trying this does not work either.

It almost seems as if the loader is not loading itself.

**Comment by gauravtiwari** [comment]
@eamon-hguk You would need to add that loader in `config/webpack/environment.js`. Please follow this guide: https://github.com/rails/webpacker/blob/master/docs/typescript.md#html-templates-with-typescript-and-angular

**Comment by eamon-hguk** [comment]
@gauravtiwari Thanks for your reply.

If I add the loader into the environment.js file I get an  Unexpected value 'undefined' declared by the module 'AppModule', so it seems this means the module is not loading at all.
Why would the loader not be added into the loaders directory anyway?

**Comment by gauravtiwari** [comment]
@eamon-hguk Can you share your environment.js please?

**Comment by eamon-hguk** [comment]
@gauravtiwari 

This is it:

const { environment } = require('@rails/webpacker')
module.exports = environment

environment.loaders.set('html', {
  test: /\.html$/,
  use: [{
    loader: 'html-loader',
    options: {
      minimize: true,
      removeAttributeQuotes: false,
      caseSensitive: true,
      customAttrSurround: [ [/#/, /(?:)/], [/\*/, /(?:)/], [/\[?\(?/, /(?:)/] ],
      customAttrAssign: [ /\)?\]?=/ ]
    }
  }]
})

Thanks

**Comment by gauravtiwari** [comment]
@eamon-hguk Ahh, you have export after the loader is set: 

```js
const { environment } = require('@rails/webpacker')

environment.loaders.set('html', {
  test: /\.html$/,
  use: [{
    loader: 'html-loader',
    options: {
      minimize: true,
      removeAttributeQuotes: false,
      caseSensitive: true,
      customAttrSurround: [ [/#/, /(?:)/], [/\*/, /(?:)/], [/\[?\(?/, /(?:)/] ],
      customAttrAssign: [ /\)?\]?=/ ]
    }
  }]
})

module.exports = environment
```

**Comment by eamon-hguk** [comment]
@gauravtiwari

Sorry but changing it has the same result.

**Comment by eamon-hguk** [comment]
@gauravtiwari
The issue seems to be caused by another problem in the module due to something else in angular that has been upgraded, but doesn't seem to be caused by webpacker. Sorry for the bother and thank you for your help.

**Comment by DavidMMelin** [comment]
@eamon-hguk I'm currently getting the issue you described. With rails/webpacker/angular and using html templates.

What was causing your issue?
