### ISSUE TITLE
yarn run?

### ISSUE THREAD

**Issue by justin808** [rails/webpacker#765]
Why is the binstub referring to the exact path of the node_modules/.bin directory rather than calling `yarn run`?

https://yarnpkg.com/lang/en/docs/cli/run/

I bring this up, as I'm running into a situation where my CI is not finding the webpack exe that should be a dependency of @rails/webpacker.

**Comment by renchap** [comment]
Reasoning is here: https://github.com/rails/webpacker/pull/638
Your problem most probably comes from an outdated yarn version, see https://github.com/rails/webpacker/pull/727

**Comment by javan** [comment]
Thanks @renchap!
