### ISSUE TITLE
How can the default production environment be customized?

### ISSUE THREAD

**Issue by caselas** [rails/webpacker#771]
I apologize if this is documented somewhere, but I was unable to find it.

What is the correct approach to remove/replace, for example, the UglifyJs plugin in the webpack config for production? I would like to use `uglify-es` as a _replacement_ for `uglify-js`.

This was simple to do before 3.x due to the config existing within my application, but now that it's been abstracted into an internal default config, I'm not sure how to modify it.

Thanks!

**Comment by gauravtiwari** [comment]
You can delete the Uglify plugin from the plugins Map (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/delete) and add the one you need. Please see the documentation here on how to add a plugin. https://github.com/rails/webpacker/blob/master/docs/webpack.md

**Comment by caselas** [comment]
Thanks, I missed that somehow.

The solution is quite simple:

```javascript
// config/webpack/production.js
const UglifyJsPlugin = require('uglifyjs-webpack-plugin')
const environment = require('./environment')

environment.plugins.delete('UglifyJs')

environment.plugins.set(
  'UglifyJs',
  new UglifyJsPlugin({
    sourceMap: true
  })
)

module.exports = environment.toWebpackConfig()
```

**Comment by gauravtiwari** [comment]
Awesome, thanks for sharing 🍰  👍
