### ISSUE TITLE
disable HMR if using styles?

### ISSUE THREAD

**Issue by justin808** [rails/webpacker#781]
Is this instruction still needed in the https://github.com/rails/webpacker/blob/master/docs/webpack-dev-server.md#hot-module-replacement

```
Note: Don't forget to disable HMR if you are not running webpack-dev-server otherwise you will get not found error for stylesheets.
```

**Comment by gauravtiwari** [comment]
Yep, this needs to be removed 👍

**Comment by gauravtiwari** [comment]
Yes, this is still relevant if `stylesheet_pack_tag` is used in the view and HMR mode is on but the dev server is not running. The styles are extracted unless using dev server with HMR on.
