### ISSUE TITLE
customize sass-loader's `includePaths`

### ISSUE THREAD

**Issue by tonytonyjan** [rails/webpacker#782]
When it was v2, we can easily customize our loaders in `config/webpack/loaders` path. Now those files are all encapsulated inside a node package, I would like to know if there is a way to do this with v3.

**Comment by renchap** [comment]
This is documented here: https://github.com/rails/webpacker/blob/master/docs/webpack.md

**Comment by tonytonyjan** [comment]
@renchap Thank you! I finally end up with the following code:

```js
// config/webpack/environment.js
const { environment } = require("@rails/webpacker");
const { resolve } = require("path");

environment.loaders
  .get("style")
  .use.find(item => item.loader == "sass-loader").options.includePaths = [
  resolve("app", "javascript", "styles")
];

module.exports = environment;
```

**Comment by FrankFang** [comment]
@tonytonyjan  get('style') raises an error. Use this instead:
```
environment.loaders.get('sass')
  .use.find(item => item.loader === 'sass-loader').options.includePaths = [resolve("app", "javascript", "styles")]
```

**Comment by tonytonyjan** [comment]
@FrankFang my solution works before v3.1.0 (see CHANGELOG), and your solution works for versions >= 3.1.0.

Thanks for pointing out.
