### ISSUE TITLE
How do I turn off the elm debugger in staging and production?

### ISSUE THREAD

**Issue by mdxprograms** [rails/webpacker#786]
I couldn't find anywhere in the docs that explains how to disable the elm debugger in staging or production.

we are using `NODE_ENV=production bundle exec rails webpacker:compile` and the debugger is still showing after compiling :(

**Comment by mdxprograms** [comment]
for those wondering

1. add correct environment to `.env` ex: `NODE_ENV=production`
2. then add `module.exports = environment.toWebpackConfig({ debug: false });` to production.js in `config/webpack/`

**Comment by rusbal** [comment]
Very helpful, thank you!

**Comment by studiorubenz** [comment]
2023 update: only needed step 2, worked!
thanks!
