### ISSUE TITLE
when running webpack-dev-server, assets pipeline also run webpack build. building 2 times

### ISSUE THREAD

**Issue by pywebdesign** [rails/webpacker#789]
Hi,

Using a different process for running webpack like in webpacker version 2, I get a magnitude faster compilation.

After upgrading to webpacker3, and using the webpack-dev-server binstub, I run into a problem where on demand compilation is also run, resulting in 2 builds process on every request after a change.

I find it unclear how to disable compilation on demand in the docs. Does someone has any pointer on this?

**Comment by gauravtiwari** [comment]
@pywebdesign Set `compile: false` in webpacker.yml. If dev server is running it won't compile twice. I guess you are using watcher?

**Comment by pywebdesign** [comment]
Thank you @gauravtiwari, it does not seam to work for my setup, I am using 2 docker container, one running `./bin/webpack-dev-server` and the other `rails s -b 0.0.0.0`

Maybe this is not the way to go but the compiliation from ./bin/webpack-dev-server is 243 ms and the one from rails -s is around 3-4 seconds

**Comment by gauravtiwari** [comment]
@pywebdesign Is webpack dev server running and you can access the assets from the browser? Are you getting any errors? Did you switch off compile from webpacker.yml?

**Comment by pywebdesign** [comment]
Hi, @gauravtiwari 

Thank you very much! Everything works great and your solution did work quite well. I was blinded by another small mistake. I will be checking if this should be in the docs and propose something if so.
