### ISSUE TITLE
Add stylesheet_pack_tag method

### ISSUE THREAD

**Issue by kruczjak** [rails/webpacker#79]
Hi :)

I think it would be also nice to add possibility to require css that is built in webpack.
It can also have digest string in filename.

https://github.com/kruczjak/liveread/blob/master/app/views/layouts/application.html.erb#L7

**Comment by merqlove** [comment]
but you anyway have sprockets)

**Comment by kruczjak** [comment]
@merqlove Yes :), but with webpack, you can e.g. extract css that's  in `.js` or `.ts` sources to standalone `.css` file. (https://github.com/webpack-contrib/extract-text-webpack-plugin)

**Comment by merqlove** [comment]
i'm agree. here also can be anything not only stylesheet. resource_pack_tag :)

**Comment by dimroc** [comment]
It would be particularly useful when used alongside Vue single file components:
https://github.com/vuejs/vueify

**Comment by gauravtiwari** [comment]
@kruczjak We are tracking this issue here (#109) now, along with other assets. Please could you close this issue as it's duplicate.

**Comment by kruczjak** [comment]
Yes, of course :)
