### ISSUE TITLE
How do you know if tree-shaking is working?

### ISSUE THREAD

**Issue by cjstewart88** [rails/webpacker#790]
We have a large rails application with a ton of AngularJS code, we've decided to start down the Angular upgrade path using the webpacker gem. We're writing in TypeScript and so far we have about 4 components we've written and downgraded to work in our AngularJS application. When running `RAILS_ENV=production ./bin/webpack` we are getting the following packs:

```
     vendor-0aad2de6d45c76331680.js      841 kB        0  [emitted]  [big]  vendor
   app-139b45eda6b5952e6694.js           17.2 kB       1  [emitted]         app
    webpack-9532c79624d37cdfe46a.js      1.46 kB       2  [emitted]         webpack
 webpack-9532c79624d37cdfe46a.js.gz      819 bytes        [emitted]
app-139b45eda6b5952e6694.js.gz           3.86 kB          [emitted]
  vendor-0aad2de6d45c76331680.js.gz      212 kB           [emitted]
                      manifest.json      176 bytes        [emitted]
```

The vendor pack seems to be a little on the large side. Given how simple our first set of components are we're thinking tree-shaking should be eliminating much of Angular we're not using.

Is tree-shaking something that happens by default or is it something we need to configure?

We're brand new to the webpack game, so I'm not sure what all would be helpful... so here's a few config files that might get us started:

**config/webpack/environment.js:**
```
const webpack = require('webpack');
const { environment } = require('@rails/webpacker');
environment.loaders.set('html', require('./loaders/html.js'));
environment.loaders.set('angular', require('./loaders/angular.js'));

environment.plugins.set(
  'CommonsChunkVendor',
  new webpack.optimize.CommonsChunkPlugin({
    name: 'vendor',
    minChunks: (module) => { // eslint-disable-line arrow-body-style
      return module.context && module.context.indexOf('node_modules') !== -1;
    }
  })
);

environment.plugins.set(
  'CommonsChunkManifest',
  new webpack.optimize.CommonsChunkPlugin({
    name: 'webpack',
    minChunks: Infinity
  })
);

module.exports = environment;
```

**config/webpack/production.js**
```
const environment = require('./environment');

const uglify = environment.plugins.get('UglifyJs');
uglify.options.sourceMap = false;

module.exports = environment.toWebpackConfig();
```

**babel.rc**
```
{
  "presets": [
    ["env", {
      "modules": false,
      "targets": {
        "browsers": "> 1%",
        "uglify": true
      },
      "useBuiltIns": true
    }]
  ],

  "plugins": [
    "syntax-dynamic-import",
    "transform-object-rest-spread",
    ["transform-class-properties", { "spec": true }]
  ]
}
```

**tsconfig.json**
```
{
  "compilerOptions": {
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es6", "dom"],
    "module": "es6",
    "moduleResolution": "node",
    "sourceMap": true,
    "target": "es5"
  },
  "exclude": [
    "**/*.spec.ts",
    "node_modules",
    "vendor",
    "public"
  ],
  "compileOnSave": false
}
```

**Comment by gauravtiwari** [comment]
Yepp, it's there by default - more info here: https://webpack.js.org/guides/tree-shaking/

**Comment by gauravtiwari** [comment]
Probably, worth adding this plugin and investigating any expensive dependency: https://github.com/th0r/webpack-bundle-analyzer

**Comment by cjstewart88** [comment]
Thanks @guilleiguaran!

**Comment by codef0rmer** [comment]
@gauravtiwari if it is enabled by default, why am I seeing the unused imports in the build file? I do not even see this kind of comments `/* unused harmony export SomeMethod */` 🤔 

P.S. With standalone webpack, I could remove the unused imports using babili-webpack-plugin.

**Comment by vitalyliber** [comment]
@gauravtiwari Hi. Please, explain me how to add https://github.com/th0r/webpack-bundle-analyzer to Webpacker 3+

**Comment by gauravtiwari** [comment]
Like so @vitalyliber : 

```js
// environment.js
const { environment } = require('@rails/webpacker')
const BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin;

environment.plugins.append('BundleAnalyzer', new BundleAnalyzerPlugin())
module.exports = environment
```

**Comment by vitalyliber** [comment]
@gauravtiwari Thanks. It works!
