### ISSUE TITLE
Webpacker swallows puma/rails errors when starting under foreman

### ISSUE THREAD

**Issue by niedfelj** [rails/webpacker#799]
When we run foreman start -f Procfile.dev which looks like this

```
web: bundle exec puma -C puma_config.rb 2>&1
webpacker: ./bin/webpack-dev-server 2>&1
```

If there is an error loading/starting puma/rails, we don't see the error, it seems to just get swallowed and says exited with code 1.

I changed the yarn run command in bin/webpack-dev-server to --no-progress from the default of --progress and error messages appear correctly when puma/rails bails out.

There is also an issue in that webpacker/node continues to run, seems like the child processes are not under foreman control anymore when a boot error occurs?

**Comment by gauravtiwari** [comment]
Can't reproduce this with latest webpacker: 

```bash
web: bundle exec rails s
webpacker: bundle exec webpack-dev-server
```

Seems to display and exit when errors.
