### ISSUE TITLE
No documentation on how to work with/edit configuration

### ISSUE THREAD

**Issue by niedfelj** [rails/webpacker#802]
We use expose-loader and some resolve aliases, but the latest webpacker doesn't have any documentation on how to use these with environment.js to edit the environment before toWebpackConfig()...in fact, looking at the source code this doesn't seem possible, so maybe the call toWebpackConfig() should be in environment.js and not in each separate environment so we can make config changes in one spot for global items?

**Comment by rossta** [comment]
@niedfelj Do the docs at https://github.com/rails/webpacker/blob/master/docs/webpack.md#configuration help? Thoughts on what else this should cover?

**Comment by niedfelj** [comment]
@rossta Yes, this goes a long way to explaining the configuration. I think it should be included or linked from the main doc?

**Comment by rossta** [comment]
I can't speak for the maintainers to your question, but feel free to open a PR!

**Comment by colinrcummings** [comment]
Is there a better way to update entry points?

```
const environment = require('./environment');
const config = environment.toWebpackConfig();
const oldEntry = config.entry;
const newEntry = {};

for(const key of Object.keys(oldEntry)) {
    newEntry[key] = [
      'react-hot-loader/patch',
      oldEntry[key]
    ];
};

config.entry = newEntry;

module.exports = config;

```
