### ISSUE TITLE
Building in development then production causes development assets.

### ISSUE THREAD

**Issue by BookOfGreg** [rails/webpacker#806]
Because dev assets are revisioned now, when we do a production build it does a no-op and serves dev assets.

to replicate:
```
bin/webpack --progress --color
rails assets:precompile
```

And the files will not be production built!

On a side note, since the config was extracted into `@rails/webpacker`, it's become near impossible to configure it myself. I want to set `result.output.filename = assetHost.publicPathWithHost` but there is no way to require in asset_host.js

**Comment by BookOfGreg** [comment]
https://github.com/rails/webpacker/blob/v1.2.0/lib/webpacker/env.rb#L25

This line from Webpacker 2.0 used to guess `production` and cause a production webpack run, but now it follows the Rails default of precompiling in dev mode.

**Comment by gauravtiwari** [comment]
@BookOfGreg You would need to set `NODE_ENV=production ./bin/webpack` for building production asset.

**Comment by BookOfGreg** [comment]
If you build dev assets with this:
```
bin/webpack --progress --color
```
Followed by building production assets with this:
```
rails assets:precompile
```
Then nothing happens.

In webpacker 2, an assets:precompile would make production assets. No need to set environments anywhere.

I closed the PR because I realised its doing the right thing now but this is a change from previous versions of webpacker.
