### ISSUE TITLE
Filename digests in Webpacker 3.0

### ISSUE THREAD

**Issue by dnicolson** [rails/webpacker#807]
Is it intentional to add filename digests for all environments in Webpacker 3.0?

I have to overwrite the `output.filename` config value in `development` and `test` environments to achieve Webpacker 2.0 behaviour. I couldn't see anything in the CHANGELOG and it appears as though the `development` environment should not have digests:

https://github.com/rails/webpacker/blob/master/lib/webpacker/helper.rb#L8

**Comment by rossta** [comment]
@dnicolson For reference, this was a recent intentional change to address a few issues: https://github.com/rails/webpacker/pull/653
