### ISSUE TITLE
Check if pack exists without raise

### ISSUE THREAD

**Issue by exegete46** [rails/webpacker#808]
Sprockets supported finding if an asset exists, without raising an exception.  This was a bit hack-ish, requiring a train wreck: `Rails.application.assets.find_asset(name).present?`, but it was possible.  I used this to allow controller-specific Javascript / CSS to be included as-needed, rather than always being a part of the main application-level asset.

With Webpacker this feels even more hack-ish, using `Webpacker.manifest.refresh[name.to_s].present?`.  This feels like way too much knowledge about the inner workings of Manifest.

I'd like to add a method to check if the manifest includes an entry.  My first stab was to add a `#include?(name)` method to the public interface.  This change can be found [here](https://github.com/exegete46/webpacker/commit/d7216a42bb4768fb37468b63321d19d578e3aee2) on [my fork](https://github.com/exegete46/webpacker/tree/feature/manifest-include).

**Comment by rossta** [comment]
It may be easier to discuss your proposed change if you open a PR.

**Comment by exegete46** [comment]
Pull request created.  Sorry, not sure of the etiquette.

**Comment by gauravtiwari** [comment]
Fixed in #869
