### ISSUE TITLE
skip webpacker compile in certain environments?

### ISSUE THREAD

**Issue by mlennie** [rails/webpacker#811]
We host an app on two servers. One is our webapp and the other is a worker. Both use the same code. 

For the worker, we do not need to use webpacker and it even is currently interfering with deploying on our worker server. 

Is there a way to skip webpacker compiling? Such as through an environmental variable?

**Comment by ytbryan** [comment]
related? https://github.com/rails/webpacker/issues/905

**Comment by gauravtiwari** [comment]
Made a PR - #1023
