### ISSUE TITLE
Can't find executable yarn for yarn gem

### ISSUE THREAD

**Issue by pwenig** [rails/webpacker#818]
I am running $bundle exec rails webpacker:install in Rails v5.1 and am getting the following error:

/.rvm/gems/ruby-2.4.1/gems/bundler-1.16.0.pre.2/lib/bundler/rubygems_integration.rb:457:in `block in replace_bin_path': can't find executable yarn for gem yarn. yarn is not currently included in the bundle, perhaps you meant to add it to your Gemfile? (Gem::Exception)

I have Yarn v0.1.1 installed

Has anybody seen this?

**Comment by curvo** [comment]
Yarn has recently released v1 and we have dealt with issues around this for our team.  Most of us are on Macs so the commands we are using for our machines are:

## If you have npm... remove any npm global yarn installs first
`npm uninstall yarn -g`

## And then using homebrew install yarn
`brew update && brew install yarn`

## If yarn is already installed via homebrew
`brew update && brew upgrade yarn`

After that you should currently be up-to-date with yarn 1.0.2. 
Running `yarn --version` should confirm that.

**Comment by curvo** [comment]
I haven't run into that particular error but am hoping the above comment might help you?

**Comment by pwenig** [comment]
brew update && brew upgrade yarn returns:
Already up-to-date.
Error: yarn 1.0.2 already installed

 yarn --version returns: 
Yarn v0.1.1 2011 Jesper Kjeldgaard

**Comment by curvo** [comment]
I think v0.1.1 was installed via gem.  Try `gem uninstall yarn` and then follow the commands above maybe.  If that doesn't work... then what's the response from your system when you type `which yarn` ?

**Comment by pwenig** [comment]
I ran gem uninstall yarn and then followed the above again. 
$which yarn returns:
/.rvm/rubies/ruby-2.4.1/bin/yarn

**Comment by curvo** [comment]
@pwenig Sorry to leave you hanging here... both of my older kids had their first cross-country meet and I had to be there!

So, sounds like that didn't work.  

I have to admit, it's pretty hard to debug back and forth like this but I do have a few of ideas for you.  

## Idea 1:  Is this rails?  Try using bundler.
If this is a rails project using bundler and yarn is no longer in your Gemfile, try:

`bundle clean` 

Then type `which yarn` and if you get nothing... then follow the brew commands above.

## Idea 2: more comprehensive gem uninstall
If not, try using this expanded gem command:

`sudo gem uninstall -aIx yarn`

```
-a All versions
-I remove executables without confirmation
-x ignore dependencies
```

Then again, `which yarn` to see if you're ready to re-install via brew.

## Idea 3: shortcut... might work
Here's a thought for you... if you were to directly remove the yarn you get when you type `which yarn`,  you may then be able to follow the `brew` commands above to install yarn again.  

If you already have run `brew install yarn` you will be prompted to link it using `brew link yarn`.  That might be a short cut to avoid the most invasive idea below.

`rm /.rvm/rubies/ruby-2.4.1/bin/yarn` # you may need sudo here
`which yarn` # are you good?

## Idea 4: blow out your ruby and start over

I admit, this one is a bit tougher, but not un-doable.  I just did it locally to see how it might be.  It took me about 10 minutes to blow out my ruby, re-install it and use bundler to re-install my gems.
Bundling gems can sometimes be a pain, so please consider this one a **_use at your own risk_** bit of advice.

From within your rails project directory try this (_at your own risk_):

`sudo rvm uninstall ruby-2.4.1`
`rvm install ruby-2.4.1`
`sudo gem install rails`
`gem install bundler`
`bundle`
`which yarn` # If you're not good yet then I'm definitely gonna be scratching my head on this one!

Please let me know if any of that helps!

**Comment by curvo** [comment]
Wanted to note (for email threads of this) that I edited the last comment Idea 4 first command to now be:

`sudo rvm remove ruby-2.4.1` 

This is a more comprehensive removal of a ruby version and all related gems.  According to the [rvm docs](https://rvm.io/rubies/removing) it is also the preferred method for uninstalling ruby versions.

**Comment by pwenig** [comment]
@curvo Fixed! Idea #2 did the trick. I uninstalled and then reinstalled with brew and it works great. Thank you so much!! You responsiveness has been awesome!

**Comment by gauravtiwari** [comment]
Great thanks @curvo 💯

**Comment by curvo** [comment]
@pwenig @gauravtiwari Glad to help!

**Comment by jmoon90** [comment]
I ran into this with Yarn where `brew upgrade` or `gem uninstall` had no effect. The solution for me was to `brew reinstall yarn` and this updated to the latest version and I'm able to install
