### ISSUE TITLE
With dev server running keep getting NoMethodError: undefined method 'closed?' for nil:NilClass

### ISSUE THREAD

**Issue by getabetterpic** [rails/webpacker#822]
When running the webpack dev server I keep getting an `undefined method 'closed?'` error. Seems to be something going on with the proxy request? Been working on this all day and have had 0 luck. Any help would be greatly appreciated. Below is the stacktrace. I don't have this error when not running the dev server, my packs are served without an issue. It's just really slow and I really want to be able to use the dev server to take advantage of HMR and page auto-reload.

```
ERROR NoMethodError: undefined method `closed?' for nil:NilClass
Did you mean?  clone
        /Users/dan/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/net/http.rb:1475:in `begin_transport'
        /Users/dan/projects/rack-proxy/lib/net_http_hacked.rb:50:in `begin_request_hacked'
        /Users/dan/projects/rack-proxy/lib/rack/http_streaming_response.rb:62:in `response'
        /Users/dan/projects/rack-proxy/lib/rack/http_streaming_response.rb:29:in `headers'
        /Users/dan/projects/rack-proxy/lib/rack/proxy.rb:120:in `perform_request'
        /Users/dan/projects/webpacker/lib/webpacker/dev_server_proxy.rb:15:in `perform_request'
        /Users/dan/projects/rack-proxy/lib/rack/proxy.rb:57:in `call'
        /Users/dan/.rvm/gems/ruby-2.3.3@callrail/gems/railties-4.2.7.1/lib/rails/engine.rb:518:in `call'
        /Users/dan/.rvm/gems/ruby-2.3.3@callrail/gems/railties-4.2.7.1/lib/rails/application.rb:165:in `call'
        /Users/dan/.rvm/gems/ruby-2.3.3@callrail/gems/railties-4.2.7.1/lib/rails/railtie.rb:194:in `public_send'
        /Users/dan/.rvm/gems/ruby-2.3.3@callrail/gems/railties-4.2.7.1/lib/rails/railtie.rb:194:in `method_missing'
        /Users/dan/.rvm/gems/ruby-2.3.3@callrail/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
        /Users/dan/.rvm/gems/ruby-2.3.3@callrail/gems/rack-1.6.8/lib/rack/lock.rb:17:in `call'
        /Users/dan/.rvm/gems/ruby-2.3.3@callrail/gems/rack-1.6.8/lib/rack/content_length.rb:15:in `call'
        /Users/dan/.rvm/gems/ruby-2.3.3@callrail/gems/rack-1.6.8/lib/rack/handler/webrick.rb:88:in `service'
        /Users/dan/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
        /Users/dan/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
        /Users/dan/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
```

**Comment by curvo** [comment]
Seems like you are using local (possibly modified) versions of webpacker and of rack-project?  What happens if you load in the default gems for both of those?

**Comment by hstove** [comment]
I was having this issue too, where the default server would work fine, but using `bin/webpack-dev-server` would cause this exception. It also only started happening on a new project with webpacker 3, where it worked fine on 2.

After some Googling of the exception, I found [this discussion](https://github.com/bblimke/webmock/issues/374), and it turns out that **this error is due to loading `WebMock` in development environments**. 

For me, I only need WebMock in tests, so simply moving `gem 'webmock'` into a test-only group in my Gemfile fixed this issue completely.

**Comment by getabetterpic** [comment]
Oh, sorry about that. I'd been hacking a bit to see if I could find the source of the error. And I'm not using WebMock in development, so that doesn't seem to be the issue for me. Here's the stacktrace with the actual gems in use:

```
ERROR NoMethodError: undefined method `closed?' for nil:NilClass
Did you mean?  clone
        /Users/dan/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/net/http.rb:1475:in `begin_transport'
        /Users/dan/.rvm/gems/ruby-2.3.3@callrail/gems/rack-proxy-0.6.2/lib/net_http_hacked.rb:50:in `begin_request_hacked'
        /Users/dan/.rvm/gems/ruby-2.3.3@callrail/gems/rack-proxy-0.6.2/lib/rack/http_streaming_response.rb:60:in `response'
        /Users/dan/.rvm/gems/ruby-2.3.3@callrail/gems/rack-proxy-0.6.2/lib/rack/http_streaming_response.rb:29:in `headers'
        /Users/dan/.rvm/gems/ruby-2.3.3@callrail/gems/rack-proxy-0.6.2/lib/rack/proxy.rb:120:in `perform_request'
        /Users/dan/.rvm/gems/ruby-2.3.3@callrail/gems/webpacker-3.0.1/lib/webpacker/dev_server_proxy.rb:15:in `perform_request'
        /Users/dan/.rvm/gems/ruby-2.3.3@callrail/gems/rack-proxy-0.6.2/lib/rack/proxy.rb:57:in `call'
        /Users/dan/.rvm/gems/ruby-2.3.3@callrail/gems/railties-4.2.7.1/lib/rails/engine.rb:518:in `call'
        /Users/dan/.rvm/gems/ruby-2.3.3@callrail/gems/railties-4.2.7.1/lib/rails/application.rb:165:in `call'
        /Users/dan/.rvm/gems/ruby-2.3.3@callrail/gems/railties-4.2.7.1/lib/rails/railtie.rb:194:in `public_send'
        /Users/dan/.rvm/gems/ruby-2.3.3@callrail/gems/railties-4.2.7.1/lib/rails/railtie.rb:194:in `method_missing'
        /Users/dan/.rvm/gems/ruby-2.3.3@callrail/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
        /Users/dan/.rvm/gems/ruby-2.3.3@callrail/gems/rack-1.6.8/lib/rack/lock.rb:17:in `call'
        /Users/dan/.rvm/gems/ruby-2.3.3@callrail/gems/rack-1.6.8/lib/rack/content_length.rb:15:in `call'
        /Users/dan/.rvm/gems/ruby-2.3.3@callrail/gems/rack-1.6.8/lib/rack/handler/webrick.rb:88:in `service'
        /Users/dan/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
        /Users/dan/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
        /Users/dan/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
```

**Comment by getabetterpic** [comment]
I did track the error down to [this line](https://github.com/ruby/ruby/blob/v2_3_3/lib/net/http.rb#L1475) in the Net::HTTP library but can't figure out what is setting `@socket` to nil.

**Comment by curvo** [comment]
@getabetterpic - Is this a public project that I can download the run locally to see the error?  I'm running a rails project running rails 4.2.9 on ruby 2.3.4 and I haven't seen that issue.  I'm gonna try to reproduce it locally so maybe, even if your project is private, could you post your Gemfile so I can use that?  It might help me.

**Comment by gauravtiwari** [comment]
@javan Looks like it's same error you ran into the other day, right?

**Comment by getabetterpic** [comment]
Ok, so think I figured out what's going on finally. Even though WebMock was only in our `test` block in the Gemfile, some code in a `spec/support` file was getting executed that required it. This was then causing it to conflict with the `Rack::Proxy` gem thus throwing the error. I found this out by commenting the `gem 'webmock'` out of the Gemfile entirely which then caused `rails s` to throw the error pointing me in the right direction. Thanks for taking a look at this!

**Comment by javan** [comment]
Nice digging! If this is a webmock and/or rack-proxy issue then issues should be opened on the appropriate repos.

**Comment by sepehr500** [comment]
Anybody find a solution for this?

**Comment by hstove** [comment]
@sepehr500 seems like most of us narrowed it down to `WebMock` being loaded in some way in our development environments.

**Comment by sepehr500** [comment]
I am using WebMock and have the same issue. Is there any way around this problem? Maybe the ability to start `webpack-dev-server` without webpacker and manually proxy to the server?

**Comment by hstove** [comment]
Is there a reason you need WebMock is your development environment? It seems that in all of our cases, we had WebMock for our test environment, and for one reason or another it got loaded in development too. Typically, you don't want or need WebMock in your development environment.

If you absolutely must have WebMock required in development, then you'll probably have to dig deeper into some of the code mentioned above. Either way, as mentioned, this is **not a bug in webpacker**.

**Comment by sepehr500** [comment]
We use WebMock to mock web requests when doing local development. I know this is not a webpacker bug, I was just hoping there was some kind of workaround.

**Comment by yoonwaiyan** [comment]
I'm having this problem in my repo too. I'm not using webmock but I have this error as well. Checked out Gemfile.lock and saw `rack-proxy` is being used by webpacker and the installed version is 0.6.4. Any workaround?

**Comment by yukas** [comment]
For me moving the `fakeweb` gem from `:development, :test` group into the `:test` group solved the issue.
