### ISSUE TITLE
Capistrano deploy webpacker:install error - Webpack binstubs not found. Have you run rails webpacker:install ?

### ISSUE THREAD

**Issue by Austex** [rails/webpacker#823]
I'm trying to deploy my app to digital ocean using capistrano and I keep getting this error.

Webpack binstubs not found.
Have you run rails webpacker:install ?
Make sure the bin directory or binstubs are not included in .gitignore

I have tried all the following to get it resolved:
`rake assets:precompile`
`rails webpacker:install`
`rake assets:precompile RAILS_ENV=production`
`rails webpacker:compile`
`bundle config --delete bin`
`rails app:update:bin`
`bundle install --binstubs`

Here is my deploy.rb for adding node and yarn:

## Add node and yarn
set :nvm_type, :user # or :system, depends on your nvm setup
set :nvm_node, 'v8.5.0'
set :nvm_map_bins, %w{node npm yarn}
set :yarn_target_path, -> { release_path.join('client') } #
set :yarn_flags, '--production --silent --no-progress'    # default
set :yarn_roles, :all                                     # default
set :yarn_env_variables, {}

**Comment by curvo** [comment]
So you have run `rails webpacker:install` within your project and checked in the binstubs?

**Comment by Austex** [comment]
I've run that too, and the bin stub file is there.

**Comment by mattbrictson** [comment]
Is the binstub checked and pushed to origin? What does this show?

```
git show origin/master:bin/webpack
```

Also, is the binstub executable?

**Comment by gauravtiwari** [comment]
@Austex As @mattbrictson suggested you would need to check `./bin/webpack`binstub into your source control. Usually on Rails 4 this directory is ignored by default.

**Comment by Austex** [comment]
@mattbrictson here is the output:

#!/usr/bin/env ruby
$stdout.sync = true

require "shellwords"

ENV["RAILS_ENV"] ||= "development"
RAILS_ENV = ENV["RAILS_ENV"]

ENV["NODE_ENV"] ||= RAILS_ENV
NODE_ENV = ENV["NODE_ENV"]


APP_PATH          = File.expand_path("../", __dir__)
NODE_MODULES_PATH = File.join(APP_PATH, "node_modules")
WEBPACK_CONFIG    = File.join(APP_PATH, "config/webpack/#{NODE_ENV}.js")

unless File.exist?(WEBPACK_CONFIG)
  puts "Webpack configuration not found."
  puts "Please run bundle exec rails webpacker:install to install webpacker"
  exit!
end

env = { "NODE_PATH" => NODE_MODULES_PATH.shellescape }
cmd = [ "#{NODE_MODULES_PATH}/.bin/webpack", "--config", WEBPACK_CONFIG ] + ARGV

Dir.chdir(APP_PATH) do
  exec env, *cmd
end
