### ISSUE TITLE
Very slow webpacker compile

### ISSUE THREAD

**Issue by benrudolph** [rails/webpacker#824]
I've installed webpack on a new rails app using the `--webpack=react`. My application is a very basic rails app with a few additional libraries (redux and bootstrap). Right now it just loads a blank page with a header (https://github.com/benrudolph/lensradar).

I am using `./bin/webpack-dev-server --profile --color` to compile the javascript.

Each time I modify a javascript file, Rails takes around 6 seconds to render:
```
Processing by ApplicationController#index as HTML
  Rendering application/index.html.erb within layouts/application
  SQL (122.7ms)  SELECT ...
  Rendered application/index.html.erb within layouts/application (6830.0ms)
Completed 200 OK in 6847ms (Views: 6724.0ms | ActiveRecord: 122.7ms)
```

This only happens with the default webpacker settings that are used in this project. In other projects where I use webpack, this kind of compile slowness doesn't happen.

Curious if you've seen this before or have any clues on how to diagnose this. Apologies for the lack of detail, but I don't know of anything specific that could be causing this, it's almost a completely fresh rails project.

Thanks.

**Comment by gauravtiwari** [comment]
@benrudolph It seems because you are making a big query and rendering all `lenses` and `specs` in the view as json, this not related to webpacker. You can remove the `as_json` block from the view and notice the difference. Also, please don't use same name for two packs - there is `application.js` and `application.jsx`

```bash
| Started GET "/" for ::1 at 2017-09-18 09:10:53 +0100
09:11:03 web.1       | Processing by ApplicationController#index as HTML
09:11:03 web.1       |   Rendering application/index.html.erb within layouts/application
09:11:03 web.1       |   Lens Load (0.4ms)  SELECT  "lenses".* FROM "lenses" LIMIT ?  [["LIMIT", 10]]
09:11:03 web.1       |   Spec Load (0.4ms)  SELECT "specs".* FROM "specs" WHERE "specs"."lens_id" IN ('fujifilm_xf_80_2p8_r_lm_ois_wr_macro', 'fujifilm_gf_45_2p8_r_wr', 'canon_85mm_1p4_is_usm', 'canon_ts-e_50_2p8_macro', 'canon_ts-e_90_2p8_macro', 'canon_ts-e_135_4p0_macro', 'voigtlander_65_2_macro', 'nikon_af-p_70-300_4p5-5p6e_ed_vr', 'tamron_18-400_3p5-6p3_di_ii_vc_hld', 'zeiss_milvus_35_1p4')
09:11:03 web.1       |   Rendered application/index.html.erb within layouts/application (37.9ms)
09:11:03 web.1       | Completed 200 OK in 74ms (Views: 68.1ms | ActiveRecord: 3.3ms)
```

**Comment by benrudolph** [comment]
Thanks @gauravtiwari, should've realized that. Appreciate the help, makes sense.
