### ISSUE TITLE
http://localhost:3001/sockjs-node/info?t=1505753450537 404 (Not Found)

### ISSUE THREAD

**Issue by Jacky-Lei** [rails/webpacker#829]
Found the solution for this issue thru [https://github.com/glenjamin/webpack-hot-middleware/issues/170](url) but not sure how to apply it the configuration.js because the entry point is through packs and looking at `shared.js` seems like the `entry` value returns an object instead of an array 

![screen shot 2017-09-18 at 10 22 45 am](https://user-images.githubusercontent.com/12858707/30555082-56fecbee-9c5b-11e7-815a-dd62eed94a4b.png)

**Comment by rossta** [comment]
Link correction: https://github.com/glenjamin/webpack-hot-middleware/issues/70

**Comment by rossta** [comment]
@Jacky-Lei `webpack-hot-middleware` isn't currently a dependency of the project, so I'm not sure what you intend with the referenced fix.

Could you share more from your local webpack configuration; perhaps there's a simple change to make there instead?

If you are trying to use hot module replacement, there's more info on enabling Webpack's built-in support for hot module replacement via Webpacker here: https://github.com/rails/webpacker/blob/9bbc51f333137f51cdd676e2cf4abc3583fa5462/docs/webpack-dev-server.md#hot-module-replacement.

**Comment by gauravtiwari** [comment]
> looking at shared.js seems like the entry value returns an object instead of an array

No need, sounds like you are still using Webpacker 2.0. Please upgrade to 3.0.x and re-install webpacker config and binstubs. HMR is now supported out of the box 👍  all you have to do is enable it from `config/webpacker.yml` after upgrade.
