### ISSUE TITLE
webpack-dev-server 2.8 doesn't work with Safari on macOS/iOS

### ISSUE THREAD

**Issue by etherbob** [rails/webpacker#834]
https://github.com/webpack/webpack-dev-server/issues/1090

Was running into the problem referenced above with webpack-dev-server 2.8 and webpacker 3.0.1

Adding the following to a custom config and [merging it into the webpacker defaults](https://github.com/rails/webpacker/blob/master/docs/webpack.md#configuration) works around it for now. I'm not sure if this is something the webpacker team would want to handle in the defaults or mention in the readme to help the odd Safari user get this working again, but thought I'd share.

config/webpack/custom.js 
```
module: {
  rules: [
    {
      loader: 'babel-loader',
      include: [
        // webpack-dev-server#1090 for Safari
        /node_modules\/webpack-dev-server/
      ]
    }
  ]
}
```

config/webpack/development.js 
```
const merge = require('webpack-merge')
const environment = require('./environment')
const customConfig = require('./custom')

module.exports = merge(environment.toWebpackConfig(), customConfig)
```

.babelrc
```
{
  "presets": [
    ["env", {
      "modules": false,
      "targets": {
        "browsers": "> 1%",
        "uglify": true
      },
      "useBuiltIns": true
    }],
    "flow"
  ],

  "plugins": [
    "transform-react-jsx",
    "syntax-dynamic-import",
    "transform-object-rest-spread",
    "transform-es2015-block-scoped-functions",
    ["transform-class-properties", { "spec": true }]
  ]
}
```

**Comment by gauravtiwari** [comment]
Thanks for sharing, easiest workaround is use the latest `webpack-dev-server`
