### ISSUE TITLE
webpack-dev-server over SSL?

### ISSUE THREAD

**Issue by catskull** [rails/webpacker#835]
Since Chrome will start to force .dev domains to use HTTPS, I've proactively moved from pow to puma-dev since puma-dev gives me HTTPS locally. webpack-dev-server doesn't run using HTTPS, so Chrome blocks any webpack assets from loading. Is there any way to get webpack-dev-server to run locally over HTTPS?

Worth noting that this is not a big issue yet, I can simply load my local site using HTTP, but it could become a bigger issue soon.

**Comment by gauravtiwari** [comment]
@catskull What version of webpacker are you using? 3.0 has option for HTTPS which can be toggled from config/webpacker.yml

**Comment by gauravtiwari** [comment]
You can find latest doc here: https://github.com/rails/webpacker/blob/9bbc51f333137f51cdd676e2cf4abc3583fa5462/docs/webpack-dev-server.md#https

**Comment by catskull** [comment]
Ah, I missed that! Thanks!
