### ISSUE TITLE
Any documentation for testing .ts files using the current rails flow?

### ISSUE THREAD

**Issue by codef0rmer** [rails/webpacker#838]
I'm able to convert the `.ts` files to `.js` using `webpack-dev-server` with default configurations generated by webpacker. However, I've not found a way to unit test those `.ts` files.

Found `RAILS_ENV=test ./bin/rake webpacker:compile` command that generates packs-test but unable to use them since they are hashed. Anything am I missing?

**Comment by renchap** [comment]
What are you using for your JS testing?

**Comment by codef0rmer** [comment]
@renchap currently `rake jasmine:ci` but I am hoping to use karma webpack here since I've used it outside rails without any issue. But the generated webpack configurations and webpacker.yml are not useful much.

**Comment by renchap** [comment]
I am personally using Jest, but it is easier as it does not require Webpack and does the compilation itself. Have you looked at reading the manifest.json file and loading the JS packs using the hashed paths?

**Comment by gauravtiwari** [comment]
> I tried passing webpacker.yml in webpack --config webpacker.yml but it thrown some error related to the output path.

Guess that should be relevant webpack config file and not the yml file. 

`webpack --config config/webpack/development.js`

Also this issue might help in regards to Karma: https://github.com/rails/webpacker/issues/435

**Comment by codef0rmer** [comment]
I've managed to enable karma test runner. Do you guys want me to create a PR for this docs to help other lost souls? :)

**Comment by gauravtiwari** [comment]
Yes please 👍  🍰

**Comment by oanstein** [comment]
@codef0rmer maybe you can answer my question regarding karma and RoR: 
[[stackoverflow - bounty 50] Ruby on Rails 5.1 & Vue.js 2.4.x – Testing with Karma, Jasmine – How to install?](https://stackoverflow.com/questions/46194455/ruby-on-rails-5-1-vue-js-2-4-x-testing-with-karma-jasmine-how-to-install)
