### ISSUE TITLE
webpack-dev-server doesn't work with --inline --hot

### ISSUE THREAD

**Issue by iChip** [rails/webpacker#841]
e.g.

```sh
sh 'bin/webpack-dev-server --host my-server --hot --inline'

...

ERROR in chunk somepack [entry]
[name]-[chunkhash].js
Cannot use [chunkhash] for chunk in '[name]-[chunkhash].js' (use [hash] instead)
Error: Cannot use [chunkhash] for chunk in '[name]-[chunkhash].js' (use [hash] instead)
```

I found a related issue, apparently chunkhash isn't compatible with inline and hot options: https://github.com/webpack/webpack/issues/2393

Webpacker likely shouldn't be using [chunkhash] when these flags are used.

Another pertinent comment from that issue:

"Don’t use [chunkhash] in development since this will increase compilation time."

**Comment by iChip** [comment]
Going to close since I looked through the @rails/webpacker source and looks like this option is not supported.

**Comment by iChip** [comment]
Actually, it's in the doc...

**Comment by gauravtiwari** [comment]
@iChip Not sure I completely understand your issue. Are you getting any errors when running dev server? what version of webpacker are you using?

**Comment by gauravtiwari** [comment]
Ahh right I see - will update the docs (the cli args are going away). Basically if you need hot module replacing, just enable `hmr: true` in webpacker.yml

**Comment by gauravtiwari** [comment]
Fixed 👍
