### ISSUE TITLE
Rake assets:precompile broken with binstubs dependency (and Compiler class too)

### ISSUE THREAD

**Issue by curvo** [rails/webpacker#851]
On Friday my User Testing colleague, @aselder, discovered that a merge done a few weeks ago, #753, will be needed on once High Sierra is full out next week.  While supporting his build we discovered that our asset pipeline no longer compiled when we pointed to master instead of pulling the current 3.0.1 release.  

There are a couple of problems that I found currently in that branch.

1. The rake task, `check_binstubs`, shuts down `rake assets:precompile` right away once you remove the old binstubs from the project directory.  Since this should be the norm going forward, that check is no longer needed

2. The internals of the Webpacker::Compiler class currently attempt to execute the old `./bin/webpack` binstub and fail when it is removed.

I threw together a PR on friday (#849) and opened it over here, but it was too early as I continued to run into issues.  So I have closed that one and have a new branch passing tests and working with asset compilation opened on our fork: https://github.com/usertesting/webpacker/pull/2

Feel free to comment here on the problem and my approach.  I am getting some feedback from Andrew tomorrow hopefully and then will create a PR over here.    Thanks!

**Comment by curvo** [comment]
https://github.com/rails/webpacker/issues/848

**Comment by gauravtiwari** [comment]
@curvo 

> The rake task, check_binstubs, shuts down rake assets:precompile right away once you remove the old binstubs from the project directory. Since this should be the norm going forward, that check is no longer needed

Those binstubs needs to be there like `./bin/rails` binstub we use at many place. Obviously, if you install the gem globally (`gem install webpacker`) you will get `webpack-dev-server` and `webpack` executable like rails but that's not intended (since it may conflict with node exec).  You could run `bundle binstubs webpacker --force` to load the new binstubs. Please note the new ones are unlikely to go out of date so you are safe to check them into your source control like `rails`.  

We could also run it like so: 

```
bundle exec webpack-dev-server
bundle exec webpack
```

but again calling `./bin/webpack` is much simpler

**Comment by curvo** [comment]
@gauravtiwari Hmm, ok.  I didn't think we were still going to require that going forward but seems reasonable.  I'm trying that now and will report back.  Meanwhile, I still think it would be nice to consolidate some of the duplicate methods within the code eventually but perhaps little by little at the right moments.  

Thanks for responding!

**Comment by curvo** [comment]
@gauravtiwari Ok all good.  Wish I would have just done a cold-start test to better understand what would now be there by default.  Just tested rails 4 & 5 and a new install is all good... and creates and leaves the binstubs.  Thanks!
