### ISSUE TITLE
adding sourcemaps to css in case of HMR (in dev-mode)

### ISSUE THREAD

**Issue by 12finger** [rails/webpacker#856]
[webpacker v3]

This line seems *not* to do the trick:

https://github.com/rails/webpacker/blob/914a4ea64ea366eee81a612f4a1209ce1309a4d9/package/loaders/style.js#L28

So i patched it for dev-mode: `config/webpack/development.js`

```
// get sourcemaps combined with hot-reload
environment.loaders.get('style').use = [
    { loader: 'style-loader' },
    { loader: 'css-loader', options: { minimize: false, sourceMap: true, importLoaders: 1 } },
    { loader: 'postcss-loader', options: { sourceMap: true, config: { path: postcssConfigPath } } },
    { loader: 'resolve-url-loader' },
    { loader: 'sass-loader', options: { sourceMap: true } }
  ]
```

I think it is important to insert the style-loader not only nakedly as String, but via:
```
      {
          loader: 'style-loader'
      }
```
And then also add `sourceMap: true, importLoaders: 1` to the options of `css-loader`.

Can anybody with more/deeper understanding of webpack confirm this ? (and maybe also explain? ;)

*******
before: 
 no sourcemaps, inlined styles
![patient_checkout token ridfaqbe 2017-09-25 11-33-36](https://user-images.githubusercontent.com/1730022/30802025-7f31e4cc-a1e5-11e7-8e1e-8b0e2709fa05.png)

after:
![patient_checkout token ridfaqbe 2017-09-25 11-31-34](https://user-images.githubusercontent.com/1730022/30801940-41fe3c7c-a1e5-11e7-9ec1-146d4b387b7e.png)

**Comment by gauravtiwari** [comment]
You can enable sourcemaps like so: 

```js
const { environment } = require('@rails/webpacker')
const merge = require('webpack-merge')

const sourceMapOptions = {
  sourceMap: true,
  importLoaders: 1
}

const CSSLoader = environment.loaders.get('style').use.find(el => el.loader === 'css-loader')
CSSLoader.options = merge(CSSLoader.options, sourceMapOptions)

module.exports = environment
```

**Comment by 12finger** [comment]
thank you!
 this *is* doing the trick :)

.. and ohh, so simple. so there they go .. the many hours of figuring out how to achieve this.. ;) the webpack documentation on this is really scarce !

yours is definitely the cleaner and more desirable solution  ! 👍

**Comment by rdlu** [comment]
I did this, but I use scss files. As a result, everything is pointing to my _main.scss file, instead of inividual scss files.

Tried this:

    const sourceMapOptions = {
      sourceMap: true,
      importLoaders: 1
    }

    const CSSLoader = environment.loaders.get('style').use.find(el => el.loader === 'css-loader')
    CSSLoader.options = merge(CSSLoader.options, sourceMapOptions)

    const SassLoader = environment.loaders.get('style').use.find(el => el.loader === 'sass-loader')
    SassLoader.options = merge(SassLoader.options, { sourceMap: true })

Any tips? I'm myself a webpack newb.

**Comment by gauravtiwari** [comment]
Fixed in #884 - leaving it open until release. 

In HMR mode, everything is inlined though so no sourcemaps.

**Comment by ajsharp** [comment]
> In HMR mode, everything is inlined though so no sourcemaps.

@gauravtiwari Is this true for both JS and CSS? Without JS sourcemaps, in-browser debugging is impossible. Is there a way to enable this currently?

**Comment by gauravtiwari** [comment]
@ajsharp No, just css. JS sourcemaps will be there.
