### ISSUE TITLE
coffescript2

### ISSUE THREAD

**Issue by morr** [rails/webpacker#859]
Hi! Do you know that coffescript2 is released? http://coffeescript.org/announcing-coffeescript-2/
Its main feature is that coffee compiles now into es6 and it also supports some of es6 syntax (import, =>, async/await etc).
To make it work with webpack in my project I had to add `babel-loader` into `coffe-loader`

Here is the code
```js
// config/webpack/environment.js
babel = environment.loaders.get('babel')
coffee = environment.loaders.get('coffee')

coffee.use = [
  { loader: babel.loader, options: babel.options },
  coffee.loader
]
delete coffee.loader
```

Do you want me to make PR with such changes in webpacker?
```js
// config/webpack/environment.js
environment.supportCoffeescript2() // adds support for coffescript2

// webpacker/package/environment.js
module.exports = class Environment {
// ...
  supportCoffeescript2() {
    babel = this.loaders.get('babel')
    coffee = this.loaders.get('coffee')

    coffee.use = [
      { loader: babel.loader, options: babel.options },
      coffee.loader
    ]
    delete coffee.loader
  }
// ...
}
```

My first thought was to add coffescript version check into `webpacker/package/loaders/coffee.js` but it does not work because `yarn` takes coffee not from my project dependencies but from webpacker dependencies.
Webpacker depends on coffee1 and because coffee2 is not backwards compatible with coffee1 I can't just upgrade coffee version in webpacker `package.json`.

**Comment by renchap** [comment]
I am using Coffeescript 2 for some time, and I got it working simply by using this in `environment.js`:

```es6
const babelLoader = environment.loaders.get('babel')
babelLoader.test = /\.(coffee|js)(\.erb)?$/
```

It seems simpler, and should also work with CS 1 (albeit a bit slower because Babel will try to transpile non ES6 code, which is useless).

**Comment by morr** [comment]
@renchap, could you please elaborate how it works?
does webpack do
1) `coffee` -> `es6` via `coffee-loader`
2) `es6` -> `js` via `babel-loade`

or

1) `coffee` -> `coffee with js` via `babel-loader`
2) `coffee with js` -> `js` via `coffee-loader`

**Comment by renchap** [comment]
Loaders are applied in the reverse order they appear in Webpack config, and to files matching the `test` attribute.

So here, `file.coffee` will be processed by `coffee-loader` (outputing ES6), and then by `babel-loader` (taking the previous ES6 output), as it matches those 2 loader `test` attributes.

**Comment by morr** [comment]
@renchap, thank you. I will use your solution and close the issue then.

**Comment by renchap** [comment]
I think it might be a good idea to support CS2 out of the box, even if the workaround is not complex.

@gauravtiwari, any opinion?

**Comment by jurajmasar** [comment]
Here's a step by step solution if you came here from Google: https://github.com/rails/webpacker/issues/993

Thanks, everyone!
