### ISSUE TITLE
package dependency resolution fails to use package-lock.json

### ISSUE THREAD

**Issue by poloka** [rails/webpacker#865]
With the introduction of [npm-5.x](http://blog.npmjs.org/post/161081169345/v500), the lock file is automatically created.  The installation of modules invoked by webpacker utilizes yarn.  Need verification added to check if npm version >= 5.0 and perform `npm install` rather than `yarn install`.

**Comment by gauravtiwari** [comment]
Please see discussion here: https://github.com/rails/webpacker/pull/475 

For now, yarn is only supported option.
