### ISSUE TITLE
Importing a module in a .coffee.erb file from a vue file is not working without the .coffee extension

### ISSUE THREAD

**Issue by coffeebite** [rails/webpacker#866]
I have a module in a file, say, `amodule.coffee.erb`. 

When I try to import this module in a vue file as:

```javascript
import amodule from "amodule"
```
 it gives me the following error:

```
Module not found: Error: Can't resolve 'amodule`
```

But if I import it as:

```javascript
import amodule from "amodule.coffee"
```

it works.

Shouldn't the import work without the coffee extension?

**Comment by gauravtiwari** [comment]
@coffeebite Because the extension is `.coffee.erb`, if you see `config/webpacker.yml` only `.erb` or `.coffee` is automatically resolved
