### ISSUE TITLE
Vue.js:  CORS header ‘Access-Control-Allow-Origin’ missing for websocket connection

### ISSUE THREAD

**Issue by nengine** [rails/webpacker#871]
I have a Vue.js template inside Rails 5.1 app with latest webpack and calling REST API publicClient.getProducts() methods works fine. But opening a websocket connection is getting a problem as shown below.

"Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ws-feed.gdax.com/. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing)."

I also added Rack::Cors in application.rb but no changes.  Is there any way to set CORS for the Vue.js?

Any help is greatly appreciated.

```js
<template>
  <div id="trades">
    <p>{{ message }}</p>
    <button @click='load'>Load data</button>    
  </div>
</template>

<script>
  const Gdax = require('gdax');
  const publicClient = new Gdax.PublicClient();
  const websocket = new Gdax.WebsocketClient(['LTC-USD']);

  export default {
    data: function() {
      return {
        message: 'Hello from trades Vue'
      }
    },
    methods: {
      mounted: function() {
        websocket.on('message', data => {
          console.log(data);
        });    
      },

      load: function() {     
        publicClient.getProducts((error, response, data) => {
          if (error) {
            // handle the error
          } else {
            console.log(JSON.stringify(data));
          }
        });
      }
    }
  }
</script>
```

application.rb
```rb
    config.middleware.insert_before 0, Rack::Cors do
      allow do
        origins '*'
        resource '*', :headers => :any, :methods => [:get, :post, :options]
      end
    end
```

**Comment by renchap** [comment]
The CORS headers need to be set on the resource you are calling, here https://ws-feed.gdax.com/
See https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS

**Comment by nengine** [comment]
Hi Thanks, I have tested on pure express.js app with the similar script to access https://ws-feed.gdax.com/ and it is working fine without any problem as shown below. Since it is a same javascript, why it would work on express.js but not in Rails 5.1 webpack environment? Since I cannot ask the people developing the API to change on short notice, is there anyway I could do on client side of = webpack?

### example 1
```js
const Gdax = require('gdax');
const publicClient = new Gdax.PublicClient();
const websocket = new Gdax.WebsocketClient(['LTC-USD']);

websocket.on('message', data => {
  console.log(data);
});
```
### example 2
```js
const Gdax = require('gdax');
const publicClient = new Gdax.PublicClient();
const WebSocket = require('ws');

const ws = new WebSocket('wss://ws-feed.gdax.com');

ws.on('open', function open() {
  const subscribeMessage = {
      type: 'subscribe',
      product_ids: ['LTC-USD']
  };
  ws.send(JSON.stringify(subscribeMessage));

  var heartbeatMessage = {
    type: 'heartbeat',
    on: true,
  };
  ws.send(JSON.stringify(heartbeatMessage));
});

ws.on('message', function incoming(data) {
  console.log(data);
});
```

**Comment by gauravtiwari** [comment]
As pointed out earlier, this isn't related to Webpack since it just compiles and bundles your JS code. May be consider posting this on Stackoverflow and see if you get any response there. 

BTW, the examples you have posted above, one is using native Websockets where other is using some kinda of client: 

```js
const websocket = new Gdax.WebsocketClient(['LTC-USD']);
```

```js
const ws = new WebSocket('wss://ws-feed.gdax.com');
```

Both examples doesn't work with Rails and Webpacker?

**Comment by nengine** [comment]
Yes, both examples does not work inside Rails 5.1 webpack Vue.js 2 app.  But, it works inside express.js server app.  Thanks.
