### ISSUE TITLE
feature tests using rspec/poltergeist not working

### ISSUE THREAD

**Issue by compostbrain** [rails/webpacker#874]
I am testing an angular/webpacker/rails5.1.3 app and getting the following error running feature tests using rspec/poltergeist/phantomjs.  The only javascript on the page is the pack tag for the sample app so it should not throw an error...
`

  Failure/Error: visit new_tournament_path

     Capybara::Poltergeist::JavascriptError:
       One or more errors were raised in the Javascript code on the page. If you don't ca
re about these errors, you can ignore them by setting js_errors: false in your Poltergeis
t configuration (see documentation for details).

       TypeError: pre,template,textarea,script,style is not iterable!
       TypeError: pre,template,textarea,script,style is not iterable!
           at http://127.0.0.1:57503/packs-test/hello_angular-278f7997dcbecd5f596a.js:162
39 in exports
           at http://127.0.0.1:57503/packs-test/hello_angular-278f7997dcbecd5f596a.js:172
04
           at http://127.0.0.1:57503/packs-test/hello_angular-278f7997dcbecd5f596a.js:272
43 in Set
           at http://127.0.0.1:57503/packs-test/hello_angular-278f7997dcbecd5f596a.js:417
84
           at http://127.0.0.1:57503/packs-test/hello_angular-278f7997dcbecd5f596a.js:20
in __webpack_require__
           at http://127.0.0.1:57503/packs-test/hello_angular-278f7997dcbecd5f596a.js:302
03
           at http://127.0.0.1:57503/packs-test/hello_angular-278f7997dcbecd5f596a.js:20
in __webpack_require__
           at http://127.0.0.1:57503/packs-test/hello_angular-278f7997dcbecd5f596a.js:260
41
           at http://127.0.0.1:57503/packs-test/hello_angular-278f7997dcbecd5f596a.js:20
in __webpack_require__
           at http://127.0.0.1:57503/packs-test/hello_angular-278f7997dcbecd5f596a.js:260
32
           at http://127.0.0.1:57503/packs-test/hello_angular-278f7997dcbecd5f596a.js:20
in __webpack_require__
           at http://127.0.0.1:57503/packs-test/hello_angular-278f7997dcbecd5f596a.js:63
     # ./spec/features/tournament_spec.rb:21:in `block (3 levels) in <top (required)>'`

**Comment by ratneshraval** [comment]
I have similar setup and getting errors for Object.assign()
`undefined is not a constructor (evaluating 'object.assign`

Seems like I'm missing a polyfill in webpacker setup. Although my Karma tests are running fine when I added phantomJS polyfill

 ```
files: [
      './../node_modules/phantomjs-polyfill-object-assign/object-assign-polyfill.js',
      {pattern: './../test/javascript/tests.webpack.js', watched: true}
    ]
```

Is polyfill the issue? Then how do we add it to webpacker?

**Comment by rossta** [comment]
You could try `import 'babel-polyfill';` in your application pack.

**Comment by ratneshraval** [comment]
I was able to get it to work by modifying loader/babel.js and imported babel-polyfill which made the object.assign error go away but ran into more issues that I never run into when running with chrome instead of phantomjs/poltergeist. :(

Here is my updated file to get past object.assign error, if anyone is looking

```
module.exports = {
  test: /\.(js|jsx)(\.erb)?$/,
  exclude: /node_modules/,
  loader: 'babel-loader',
  query: {
    presets: [
      [ 'env', {
        'useBuiltIns': true
      }],
      'react'
    ],
    plugins: [
      'babel-plugin-syntax-dynamic-import',
      'babel-plugin-transform-class-properties',
      'babel-plugin-transform-runtime',
      'babel-plugin-transform-object-assign'
    ]
  }
}

```

**Comment by gauravtiwari** [comment]
There is a `.babelrc` file that ship with webpacker to add more plugins or presents so you don't need to directly update loader for that. Like @rossta pointed out, `babel-polyfill` can take care of this with `useBuiltIns` flags for `babel-preset-env` by automatically pulling in necessary polyfills.

Since this is not related to Webpacker, going to close 👍

**Comment by compostbrain** [comment]
Thanks for solving my issue!!
