### ISSUE TITLE
Errno::EBADF in `DevServer.running?

### ISSUE THREAD

**Issue by ketan** [rails/webpacker#876]
See similar issue https://github.com/rails/webpacker/issues/745.

I'm running on `jruby 9.1.13.0` and getting a `Errno::EBADF` when the webpack dev server is not running. Perhaps it's appropriate to catch all exceptions here and return a false? I can submit a PR if the solution is acceptable.

https://github.com/rails/webpacker/blob/a9a6a67fe34768ca7390eb93aa6a7574a746ce25/lib/webpacker/dev_server.rb#L12-L17

**Comment by gauravtiwari** [comment]
Yes, please feel free to submit a PR 👍
