### ISSUE TITLE
Is there a way to enable tree-shaking?

### ISSUE THREAD

**Issue by codef0rmer** [rails/webpacker#885]
As per this issue https://github.com/rails/webpacker/issues/790, it is enabled by default but I am not  seeing the unused imports comments i.e. `/* unused harmony export SomeMethod */` in the build file?

Although, the standalone Webpack setup seems to be working with just ts-loader. Am I missing something?

**Comment by gauravtiwari** [comment]
Depends on how you are importing within you code and if there is any dead code to eliminate in the first place. Usually, if you do named imports like here: https://webpack.js.org/guides/tree-shaking/#add-a-utility it should mark unused functions as `unused`.

**Comment by codef0rmer** [comment]
I tried that and everything else, but not able to figure it out with Webpacker. Any demo of tree shaking with Webpacker?

**Comment by gauravtiwari** [comment]
Just used the same example here: https://webpack.js.org/guides/tree-shaking/#add-a-utility

```js
// app/javascript/math.js
export function square(x) {
  return x * x;
}

export function cube(x) {
  return x * x * x;
}
```

```js
// app/javascript/packs/math.js
import { square } from '../math'

console.log(square(2))
```

![screen shot 2017-10-01 at 17 26 34](https://user-images.githubusercontent.com/771039/31056698-eb197f14-a6cd-11e7-83fd-add9982768ea.png)

**Comment by gauravtiwari** [comment]
In development we use `cheap-eval-source-map` for faster compilation that's why it's under `eval` vs a regular comment. Now with `sourcemap` turned on: 

```js
// config/webpack/development.js
const environment = require('./environment')

environment.config.devtool = 'sourcemap'
module.exports = environment.config

```
```js
"use strict";
/* harmony export (immutable) */ __webpack_exports__["a"] = square;
/* unused harmony export cube */
function square(x) {
  return x * x;
}

function cube(x) {
  return x * x * x;
}
```

**Comment by codef0rmer** [comment]
Thanks, @gauravtiwari. 

However, I'm still not seeing the `unused` comment.
```
/* harmony export (immutable) */ __webpack_exports__["square"] = square;
/* harmony export (immutable) */ __webpack_exports__["cube"] = cube;
/* harmony export (immutable) */ __webpack_exports__["generateGAPage"] = generateGAPage;
```

**Comment by gauravtiwari** [comment]
Strange! Are you using exact same example? Also, if you use both functions in your code then it's not `unused`: 

```js
// app/javascript/math.js
export function square(x) {
  return x * x;
}

export function cube(x) {
  return x * x * x;
}
```

```js
// app/javascript/packs/math.js
import { square } from '../math'

console.log(square(2))
```

**Comment by gauravtiwari** [comment]
Also, are you using same babel plugins as shipped by webpacker (in .babelrc)?

**Comment by codef0rmer** [comment]
No. I'm not importing all but cube.

This is my .babelrc file:
```
{
  "presets": [
    ["env", {
      "modules": false,
      "targets": {
        "browsers": "> 1%",
        "uglify": true
      },
      "useBuiltIns": true
    }]
  ],

  "plugins": [
    "syntax-dynamic-import",
    "transform-object-rest-spread",
    ["transform-class-properties", { "spec": true }]
  ]
}
```

**Comment by gauravtiwari** [comment]
That looks alright to me. It's hard to debug this way, can you push an example rails application with webpacker on github with this issue?

**Comment by codef0rmer** [comment]
@gauravtiwari I'm using `Rails 4.2.4` and `ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]`. Is that what causing the issue?

**Comment by codef0rmer** [comment]
@gauravtiwari Let me know if it works for you in the above repo. Also, curious to know which setup are you using wherein it worked last time?

**Comment by codef0rmer** [comment]
@gauravtiwari after few more googling, I came to know that it is using `babel-plugin-transform-es2015-modules-commonjs` plugin to transform es6 imports to commonjs which is what preventing the tree-shaking. Now Struggling to disable the same now 😭 

```
Object.defineProperty(__webpack_exports__, "__esModule", { value: true });
/* harmony export (immutable) */ __webpack_exports__["square"] = square;
/* harmony export (immutable) */ __webpack_exports__["cube"] = cube;
function square(x) {
    return x * x;
}
function cube(x) {
    return x * x * x;
}```

P.S. http://2ality.com/2015/12/webpack-tree-shaking.html

**Comment by codef0rmer** [comment]
@gauravtiwari I've even tried to add presets in the Webpack configurations but no luck 😞 

```
//config/webpack/development.js
const merge = require('webpack-merge')
const environment = require('./environment')
const webpackConfig = environment.toWebpackConfig()
webpackConfig.devtool = 'sourcemap'

const babelLoader = environment.loaders.get('babel')
babelLoader.options = merge(babelLoader.options, { 
  presets: [ 
    [ 'es2015', { modules: false } ] 
  ] 
})
module.exports = webpackConfig
```

**Comment by gauravtiwari** [comment]
@codef0rmer Apologies for late reply. Are you using `es2015` preset in .babelrc? With webpacker we don't ship es2015 but `babel-preset-env`

**Comment by gauravtiwari** [comment]
That's what I was trying to ask the other day, that if you are using anything else beyond what we ship with Webpacker: https://github.com/rails/webpacker/issues/885#issuecomment-333389488

**Comment by codef0rmer** [comment]
@gauravtiwari not sure what you mean? 

This is my .babelrc file created by Webpacker:
```
{
  "presets": [
    ["env", {
      "modules": false,
      "targets": {
        "browsers": "> 1%",
        "uglify": true
      },
      "useBuiltIns": true
    }]
  ],

  "plugins": [
    "syntax-dynamic-import",
    "transform-object-rest-spread",
    ["transform-class-properties", { "spec": true }]
  ]
}
```

**Comment by gauravtiwari** [comment]
Alright, taking a look at your example - hang on

**Comment by gauravtiwari** [comment]
Made a PR here: https://github.com/codef0rmer/rails-webpacker-treeshaking-example/pull/1, pretty simple fix. Please keep source files outside of `packs` since that's a special directory made only for webpack entry files: https://webpack.js.org/concepts/#entry

**Comment by codef0rmer** [comment]
@gauravtiwari Worked in the private project too. Awesome!
