### ISSUE TITLE
Is there any chance to add riotjs to integrations?

### ISSUE THREAD

**Issue by skatkov** [rails/webpacker#886]
There is this front-end framework called http://riotjs.com/ , would it be possible to add it to integrations in a similar fashion Vue/Reach is integrated?

**Comment by ytbryan** [comment]
Do you want to send a PR? And possibly maintain it?

**Comment by skatkov** [comment]
@ytbryan Thanks for indicating a possible interest in this.  I'm not affiliated with riotjs in anyway, I'll see what it will take to integrate riotjs into project i'm doing now.

I'm fairly new to webpack, my first attempt at this was a failure. I'll come back to you then I'll do a second one.

**Comment by ytbryan** [comment]
Just to clarify, i have no interest and also not using riotjs. 

I think supporting four (react, vue, angular and elm) is sufficient. In fact, four too many to support 😅

**Comment by gauravtiwari** [comment]
@skatkov thanks for this but we are not looking for more integrations. With loaders API, it's pretty trivial to add in new frameworks like riotjs (https://github.com/riot/tag-loader). 

Documentation: https://github.com/rails/webpacker/blob/master/docs/webpack.md
