### ISSUE TITLE
Bug with Safari Can't find variable: SockJS

### ISSUE THREAD

**Issue by savroff** [rails/webpacker#896]
From the box on `webpacker 3.0.1` for Vue.js setup get 
`Can't find variable: SockJS` error in Safari `Version 10.1.1 (12603.2.4)`

Issue showed here in Webpacker:
https://github.com/webpack/webpack-dev-server/issues/1090

As a solution we need to change in default config for `development.js:8`
`devtool: 'cheap-eval-source-map'` to  `'inline-source-map'`
We will lose in performance, but this is the best workaround at this moment.

**Comment by kozhin** [comment]
Do you use Docker? I had similar problem recently and we discussed it in the issue #762

**Comment by savroff** [comment]
@kozhin hi! 
Nope, just a plain setup on mac os.
I have no problem with prev version of webpacker. But thank you for reference to the issue, I will look at it.

**Comment by gauravtiwari** [comment]
@savroff Try upgrading `webpack-dev-server` to 2.9.x: `yarn upgrade webpack-dev-server --latest`

**Comment by gauravtiwari** [comment]
Closing since unrelated to Webpacker 👍
