### ISSUE TITLE
Can't install to existing Rails 4.2.3 app

### ISSUE THREAD

**Issue by crispwake** [rails/webpacker#898]
I'm trying to load Webpacker into an existing Rails 4.2.3 app, running Ruby 2.2.3.  I have done and run Webpacker successfully on a separate, new, test project using these versions.  When I try to do this in my existing project I get a `NameError: uninitialized constant Webpacker` error when running `bundle exec rake webpacker:install`.

```
Running via Spring preloader in process 78495
   identical  config/webpacker.yml
Copying webpack core config and loaders
       exist  config/webpack
   identical  config/webpack/development.js
   identical  config/webpack/environment.js
   identical  config/webpack/production.js
   identical  config/webpack/test.js
Copying .postcssrc.yml to app root directory
   identical  .postcssrc.yml
Copying .babelrc to app root directory
   identical  .babelrc
Creating javascript app source directory
rake aborted!
NameError: uninitialized constant Webpacker
/Users/ryan/.rvm/gems/ruby-2.2.3@cwa/gems/webpacker-3.0.2/lib/install/template.rb:14:in `apply'
/Users/ryan/.rvm/gems/ruby-2.2.3@cwa/gems/thor-0.20.0/lib/thor/actions.rb:225:in `instance_eval'
/Users/ryan/.rvm/gems/ruby-2.2.3@cwa/gems/thor-0.20.0/lib/thor/actions.rb:225:in `apply'
/Users/ryan/.rvm/gems/ruby-2.2.3@cwa/gems/railties-4.2.3/lib/rails/tasks/framework.rake:13:in `block (2 levels) in <top (required)>'
-e:1:in `<main>'
Tasks: TOP => rails:template
(See full trace by running task with --trace)

```

**Comment by curvo** [comment]
Hi @crispwake ... my guess is that you had your rails server running in another tab when you attempted to run that rake task?  If that were the case then Spring would cause your rake task to use the already loaded set of classes via the older process.  Make sure you do not have a console or server process running under spring and try it again.  It should work fine.

**Comment by gauravtiwari** [comment]
Probably, just kill spring and try again.

**Comment by crispwake** [comment]
I think you guys are correct (and geniuses) :)  I happened to try it again later and it did work, meant to close this out.  Thanks for your help.
