### ISSUE TITLE
Use of asset_pack_path seems very slow (in development)

### ISSUE THREAD

**Issue by tdegrunt** [rails/webpacker#899]
Somehow the use of asset_pack_path seems very slow. On my machine it takes 4 seconds to lookup 4 images, when running the webpack-dev-server it slightly improves to 3 seconds:
```
Rendered layouts/_language_switch.html.slim (4472.4ms)
```

I have folder structure as follows (app/webpacks is my source_path as configured in web packer.yml).
```
app/webpacks
  packs
    application.js
  images
    flags
      en.svg
```

Relevant code:
```ruby
= image_tag(asset_pack_path('images/flags/en.svg'), height: '16', width: '16')
```

I'm new to the webpack and web packer world, can someone please shed a light on this?

**Comment by gauravtiwari** [comment]
@tdegrunt Which  version of webpacker are you using?

**Comment by tdegrunt** [comment]
I'm using: 
    webpacker (3.0.1)

I just saw that 3.0.2 is out, I've tried that and now I'm no longer seeing the isuse
