### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by jensljungblad** [rails/webpacker#90]
Wondering how to deal with deployment to, say Heroku, or running tests on Travis.

I noticed this gem hooks into `assets:precompile` where it runs webpack. That seems to be a good solution since Heroku runs this when deploying. However, the yarn dependencies need to be installed somehow. 

Would it make sense to run `bin/yarn install` as part of this gem's `assets:precompile` hook? Or how would you install those dependencies on Heroku? Found this commit which said it would be handled in Rails 5.1, but didn't say how: https://github.com/rails/webpacker/commit/d2a6537e6ab0896a9bf14b6eddc5c0961db2c802

**Comment by jensljungblad** [comment]
Also wondering about this commit: https://github.com/rails/webpacker/commit/5afa88259c4fa7d3ed101ea354f769377a7c4688

If `webpack` etc are installed as dev dependencies, they won't be installed on, say Heroku. Does that mean you think assets should be built in a dev environment prior to deploying?

**Comment by joerodrig3** [comment]
- Creating a blank `yarn.lock` file in your root directory tricks Heroku into installing Yarn.

- For compiling your assets before deploying, you can create a rake task. Below is what I've been building off of:

```rake
# assets.rake
Rake::Task["assets:precompile"]
  .clear_prerequisites
  .enhance(["assets:compile_environment"])

namespace :assets do
  task compile_environment: [:yarn, :webpack] do
    Rake::Task["assets:environment"].invoke
  end

  desc "Install node deps via yarn"

  task :yarn do
    sh "bundle exec ./bin/yarn"
  end

  task :webpack do
    sh "bundle exec rails webpacker:compile"
  end
end
```

**Comment by jensljungblad** [comment]
@joerodrig3 Do you need the nodejs build pack on Heroku as well? I can't get it to work even with an empty `yarn.lock` file in the root directory.

**Comment by joerodrig3** [comment]
Yep, any app that uses node needs the nodejs buildpack on Heroku: `heroku/nodejs`

**Comment by jensljungblad** [comment]
Thanks, got it working with the node build pack. Wonder if it would make sense to add node and yarn to the Heroku ruby build pack? I guess a Rails 5.1 app won't function correctly without it?

I grabbed this from rails master which is similar to what you suggested: https://github.com/rails/rails/blob/f04a49b033e3da54a52f76289863ec87a3c30438/railties/lib/rails/tasks/yarn.rake

Reason dev dependencies get installed is that both rails and your rake task run yarn without the `--production` flag, which is the flag that skips dev dependencies. Not sure if that is intended or not?

**Comment by joerodrig3** [comment]
In https://github.com/rails/webpacker/issues/72 dhh stated:
> Heroku can update their Yarn detection in time.

So I am going to assume we'll have to wait and see what Heroku does :) Until then the Yarn hack seems like the only way to go. Custom buildpacks may help too. On a work project we did end up modifying one buildpack to fix a ruby version conflict we were having with Webpacker

**Comment by jensljungblad** [comment]
Sounds good!

**Comment by johnmaxwell** [comment]
> Reason dev dependencies get installed is that both rails and your rake task run yarn without the --production flag, which is the flag that skips dev dependencies. Not sure if that is intended or not?

I'm running into this right now. I'm using Vue, which uses the NODE_ENV environment var to determine if it should be run in production mode or not. (When I'm deploying, I want it in production mode.) When I set NODE_ENV to production on the production server and deploy, it will fail to to build the pack because webpack, et al are "devDependencies" and not "dependencies" in package.json 

What is the intended deployment strategy for webpacker? Based on the way webpacker compilation tagged onto the assets:precompile rake task, it seems like the idea is that we compile on the webpacker assets on deployment server during deployment -- like the assets pipeline assets. Is that correct?
