### ISSUE TITLE
Assets:precompile 

### ISSUE THREAD

**Issue by theredorm** [rails/webpacker#900]
Halo guyz i need help, if i try to use RAILS_ENV=production rake assets:precompile i get this errors:
`ERROR in ./node_modules/css-loader?minimize!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-9e58fde4","scoped":false,"hasInlineConfig":false}!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./app/javascript/components/product_cart.vue
Module build failed: Error: ENOENT: no such file or directory, open '/home/andrew/railsapp/ander/node_modules/svgo/lib/svgo/../../.svgo.yml'
    at Object.fs.openSync (fs.js:651:18)
    at Object.fs.readFileSync (fs.js:553:33)
    at module.exports (/home/andrew/railsapp/ander/node_modules/svgo/lib/svgo/config.js:31:48)
    at new module.exports (/home/andrew/railsapp/ander/node_modules/svgo/lib/svgo.js:21:19)
    at /home/andrew/railsapp/ander/node_modules/postcss-svgo/dist/index.js:95:16
    at Object.creator [as postcssSvgo] (/home/andrew/railsapp/ander/node_modules/postcss-svgo/node_modules/postcss/lib/postcss.js:150:35)
    at /home/andrew/railsapp/ander/node_modules/cssnano/dist/index.js:295:40
    at Array.forEach (native)
    at /home/andrew/railsapp/ander/node_modules/cssnano/dist/index.js:282:29
    at creator (/home/andrew/railsapp/ander/node_modules/cssnano/node_modules/postcss/lib/postcss.js:150:35)
    at processCss (/home/andrew/railsapp/ander/node_modules/css-loader/lib/processCss.js:199:16)
    at Object.module.exports (/home/andrew/railsapp/ander/node_modules/css-loader/lib/loader.js:40:2)
 @ ./node_modules/vue-style-loader!./node_modules/css-loader?minimize!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-9e58fde4","scoped":false,"hasInlineConfig":false}!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./app/javascript/components/product_cart.vue 4:14-311
 @ ./app/javascript/components/product_cart.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./app/javascript/components/products.vue
 @ ./app/javascript/components/products.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./app/javascript/components/products_page.vue
 @ ./app/javascript/components/products_page.vue
 @ ./app/javascript/packs/application.js
`
i use gem 'webpacker', '2.0' + vue, and in dev env all is good.

my .postcss.yml:
`plugins:
  postcss-smart-import: {}
  precss: {}
  autoprefixer: {}
`
my production,js:
`
/* eslint global-require: 0 */

const webpack = require('webpack')
const merge = require('webpack-merge')
const CompressionPlugin = require('compression-webpack-plugin')
const sharedConfig = require('./shared.js')

module.exports = merge(sharedConfig, {
  output: { filename: '[name]-[chunkhash].js' },
  devtool: 'source-map',
  stats: 'normal',

  plugins: [
    new webpack.optimize.UglifyJsPlugin({
      minimize: true,
      sourceMap: true,

      compress: {
        warnings: false
      },

      output: {
        comments: false
      }
    }),

    new CompressionPlugin({
      asset: '[path].gz[query]',
      algorithm: 'gzip',
      test: /\.(js|css|html|json|ico|svg|eot|otf|ttf)$/
    })
  ]
})
`
my style loader:
`
const ExtractTextPlugin = require('extract-text-webpack-plugin')
const path = require('path')

const postcssConfigPath = path.resolve(process.cwd(), '.postcssrc.yml')
const isProduction = process.env.NODE_ENV === 'production'

const extractOptions = {
	fallback: 'style-loader',
	use: [
		{ loader: 'css-loader', options: { minimize: isProduction } },
		{ loader: 'postcss-loader', options: { sourceMap: true, config: { path: postcssConfigPath } } },
		'resolve-url-loader',
		{ loader: 'sass-loader', options: { sourceMap: true } }
	]
}

// For production extract styles to a separate bundle
const extractCSSLoader = {
	test: /\.(scss|sass|css)$/i,
	use: ExtractTextPlugin.extract(extractOptions)
}

// For hot-reloading use regular loaders
const inlineCSSLoader = {
	test: /\.(scss|sass|css)$/i,
	use: ['style-loader'].concat(extractOptions.use)
}

module.exports = isProduction ? extractCSSLoader : inlineCSSLoader

`

my shared,js:
`
// Note: You must restart bin/webpack-dev-server for changes to take effect

/* eslint global-require: 0 */
/* eslint import/no-dynamic-require: 0 */

const webpack = require('webpack')
const { basename, dirname, join, relative, resolve } = require('path')
const { sync } = require('glob')
const ExtractTextPlugin = require('extract-text-webpack-plugin')
const ManifestPlugin = require('webpack-manifest-plugin')
const extname = require('path-complete-extname')
const { env, settings, output, loadersDir, resolvedModules } = require('./configuration.js')

const extensionGlob = `**/*{${settings.extensions.join(',')}}*`
const entryPath = join(settings.source_path, settings.source_entry_path)
const packPaths = sync(join(entryPath, extensionGlob))

module.exports = {
  entry: packPaths.reduce(
    (map, entry) => {
      const localMap = map
      const namespace = relative(join(entryPath), dirname(entry))
      localMap[join(namespace, basename(entry, extname(entry)))] = resolve(entry)
      return localMap
    }, {}
  ),

  output: {
    filename: '[name].js',
    path: output.path,
    publicPath: output.publicPath
  },

  module: {
    rules: sync(join(loadersDir, '*.js')).map(loader => require(loader))
  },

  plugins: [
    new webpack.EnvironmentPlugin(JSON.parse(JSON.stringify(env))),
    new ExtractTextPlugin(env.NODE_ENV === 'production' ? '[name]-[hash].css' : '[name].css'),
    new ManifestPlugin({
      publicPath: output.publicPath,
      writeToFileEmit: true
    })
  ],

  resolve: {
    extensions: settings.extensions,
    modules: resolvedModules
  },

  resolveLoader: {
    modules: ['node_modules']
  }
}

`

my webpack.yml:
`
# Note: You must restart bin/webpack-dev-server for changes to take effect

default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_output_path: packs

  compile: false

  # Additional paths webpack should lookup modules
  # ['app/assets', 'engine/foo/app/assets']
  resolved_paths: []

  extensions:
    - .coffee
    - .erb
    - .js
    - .jsx
    - .ts
    - .vue
    - .sass
    - .scss
    - .css
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg

development:
  <<: *default

  dev_server:
    host: localhost
    port: 8080
    https: false

test:
  <<: *default

  public_output_path: packs-test
  # Compile webpack assets during lookup when running tests
  compile: true

production:
  <<: *default

> 

`

Thanks for hepling.

**Comment by gauravtiwari** [comment]
Please remove `.yarnclean` from your root folder. Remove `node_modules` and reinstall again: `yarn install`
