### ISSUE TITLE
Installing from NPM

### ISSUE THREAD

**Issue by JarLowrey** [rails/webpacker#901]
If I attempt to install a node_module from NPM - e.g. `npm install --save styled-components` - instead of yarn I'll receive the following error when attempting to start the dev server:

```
$ ./bin/webpack-dev-server
./bin/webpack-dev-server:67:in `exec': No such file or directory - /home/james/Documents/comity.fit/node_modules/.bin/webpack-dev-server (Errno::ENOENT)
        from ./bin/webpack-dev-server:67:in `block in <main>'
        from ./bin/webpack-dev-server:66:in `chdir'
        from ./bin/webpack-dev-server:66:in `<main>'
```

How can we get this to work? Not all packages on NPM are on Yarn

**Comment by gauravtiwari** [comment]
@JarLowrey `yarn add  styled-components` doesn't work? If you use multiple bundlers, surely you will run into this kind of issues so, please use one.

**Comment by JarLowrey** [comment]
It does work, I was just trying to make an example. You cannot use both NPM and Yarn? From the Readme it appeared only Yarn was supported so I was curious if it was possible to use NPM, as it's not working for me.

**Comment by gauravtiwari** [comment]
@JarLowrey It is possible you can remove `yarn.lock`, remove `node_modules` and just use `npm` but don't use them together.

**Comment by shvetsovdm** [comment]
In order to replace Yarn with npm you can try [this solution](https://medium.com/@shvetsovdm/how-to-use-webpacker-with-npm-instead-of-yarn-a8a764e3a8ab)
