### ISSUE TITLE
Expose bundles to Sprockets

### ISSUE THREAD

**Issue by perezperret** [rails/webpacker#91]
I don't know the correct way to go about this, but I need to load a bundled file through `sprockets` for a `gem` to use it (`react-rails`). Basically, I expose a module globally in a `pack` (using `webpack`'s library output option) and I need to point `react-rails` to this bundle to pre-render some stuff with ExecJS, but `react-rails` loads `js` through sprockets, right now if I manually add the pack to the assets path in the assets initialisers, I can get the server-side renderer to load it through sprockets, but it doesn't detect changes to it, which causes the server rendered version to be out of sync with the client side version (which loads the bundle with the `javascript_pack` helper). I can only assume this is going to be an even bigger problem in production. What I guess I need is an interface for sprockets to load these bundles, does that make sense as part of this gem?

For reference, have a look at the [repo I'm working on](https://github.com/perezperret/react-rails-expenses#reactrailsexpenses), it is thoroughly explained in the README.

**Comment by gauravtiwari** [comment]
@perezperret You may want to use https://github.com/renchap/webpacker-react, drop-in replacement for react-rails and works with webpacker. 

Feel free to close this one if it's okay 👍

**Comment by justin808** [comment]
@perezperret We'll soon have Webpacker integration completed: https://github.com/shakacode/react_on_rails/pull/811

**Comment by gauravtiwari** [comment]
*Update:* Also `react-rails` now provides first-class support for Webpacker - https://github.com/reactjs/react-rails#use-with-webpacker
