### ISSUE TITLE
javascript_pack_tag not resolving correctly

### ISSUE THREAD

**Issue by hoodslide** [rails/webpacker#919]
`javascript_pack_tag` is resolving to `/pack/...`, rather than `http://localhost:3035/pack/...`.  Is there a config option I missed?

**Comment by gauravtiwari** [comment]
@hoodslide Post 3.0+ there is a proxy that maps all requests from `packs` to `dev server` if it's running so, path looks fine.

**Comment by gauravtiwari** [comment]
More info here: https://github.com/rails/webpacker#development

**Comment by hoodslide** [comment]
Thanks @gauravtiwari! webpack-dev-server is running, and generates a relative path sans the hostname and port. My manifest.json starts with:
```
{
  "application.js": "/packs/application-68743442517a29999ef7.js",
  "application.js.map": "/packs/application-68743442517a29999ef7.js.map",
 ....
}
```
If I update this manually to prepend `http://localhost:3035/`, the `javascript_pack_tag` functions as expected. I've tried altering the publicPath, but that seems to only affect the dest URL, not the manifest. Thoughts?

**Comment by gauravtiwari** [comment]
Yeah, that sounds alright to me. You don't need to prepend anything, it should just work. There is a Rake middleware the proxies webpacker asset requests to dev server if it's running. 

Are you having any issues?

**Comment by hoodslide** [comment]
Again, thanks for the quick response! My issue is that the script tag generated by `javascript_pack_tag` is:
```
<script src="/packs/application-68743442517a29999ef7.js"></script>
```
...which points to a relative `localhost:3000/packs/...`, my Rails server. The webpacker-dev-server is running on port 3035. So, the javascript is not found. Am I missing something simple in the configuration?

**Comment by gauravtiwari** [comment]
@hoodslide Sorry about the confusion, but that's expected behaviour. You see, the requests to rails server is proxies to webpack dev server internally, if it's running: https://github.com/rails/webpacker/blob/master/lib/webpacker/dev_server_proxy.rb 

> So, the javascript is not found

Are you getting 404 errors in console? Do you have dev server running?

**Comment by hoodslide** [comment]
webpack-dev-server is running (I can see the JS file via port 3035). When I navigate to the place javascript_pack_tag is pointing on port 3000, I get a Rails "Routing Error" page. Something I need to do in the Puma config perhaps? I would think URLs beginning with /pack/ should get proxied _before_ they get to Rails.

**Comment by gauravtiwari** [comment]
What version of webpacker are you on?

>  I would think URLs beginning with /pack/ should get proxied before they get to Rails.

Exactly what happens.

**Comment by gauravtiwari** [comment]
Could you open up rails console and see what this returns? `Webpacker.dev_server.running?`

**Comment by gauravtiwari** [comment]
Also, how does your `config/webpacker.yml` file looks?

**Comment by hoodslide** [comment]
Bloody hell. My package.json file showed Webpacker v3.0.1, but my Gemfile had 2.0. It's working fine now. Thanks so much for the help!

**Comment by gauravtiwari** [comment]
Yeah, that's what I suspected - usually happens when you have two packages to upgrade. No worries 👍  glad it's sorted.
