### ISSUE TITLE
Feature suggestion: add css-hot-loader

### ISSUE THREAD

**Issue by djforth** [rails/webpacker#924]
Just a thought, but rather than messing around inlining the CSS for HMR could we add https://github.com/shepherdwind/css-hot-loader to manage refreshing the CSS?

Happy to issue a pull request if it's considered a useful?

**Comment by gauravtiwari** [comment]
Thanks for this, have looked at it earlier but it seemed there are some gotchas involved: https://github.com/shepherdwind/css-hot-loader#attention

We want hashing to expire assets when they change. I see there are some problems solved with this loader but personally, haven't encountered them before.

**Comment by djforth** [comment]
Hi, sorry I had obviously missed that you had responded to this.

I have a quick question on this - I thought the hash is only really necessary when you deploy to the server and not really needed in development?  The css-loader takes care of this no problem in development (at least when I've used it).  Could we not check if your in development?  It seems an easier approach than having to write JS to inject the css into a style tag only in development in my opinion?

So my current set up like this (I use https://github.com/kentcdodds/webpack-config-utils to manage environments)

```
environment.plugins.set('ExtractText', new ExtractTextPlugin({
  filename: ifProduction('[name]-[hash].css', '[name].css'), allChunks: true
}));
```

Then in my loader:

```
if (ifDevelopment()){
    return {
      test: /\.(scss|sass|css)(\.erb)?$/i
      , use: ['css-hot-loader'].concat(ExtractTextPlugin.extract(extract))
    };
  }

  return {
    test: /\.(scss|sass|css)(\.erb)?$/i
    , use: ExtractTextPlugin.extract(extract)
  };
```

It certainly works well for me, although maybe I missing an advantage of using hashing in development?

**Comment by gauravtiwari** [comment]
> although maybe I missing an advantage of using hashing in development?

@djforth The idea behind hashing was to mimic sprockets behaviour and expire assets in development. Folks were complaining that their assets were cached in browser during development when not using hash.

**Comment by djforth** [comment]
@gauravtiwari  Ah I see, I always switch caching off when my dev tools are open, maybe that's why I'm not seeing the issue.  

I'll investigate when I have 5mins switching caching back on and see if causes an issue and report back.

**Comment by gauravtiwari** [comment]
Yeah, I do that but some folks stumbled upon this. Sure 👍
