### ISSUE TITLE
Making sass vars available for application sass files?

### ISSUE THREAD

**Issue by Drecula** [rails/webpacker#925]
Hi,

My Sass files should be aware of Sass Vars, as they are
imported before the file that uses them.

However, I get an 'undefined variable' error in my Sass file
when I reference the sassvar. All other styles work fine.

Is there a config I'm missing?

app/assets/stylesheets/application.scss             // 
`
@import 'MySassVars'; // has style $my-color: #BBB;
@import 'MySassFile'; // uses $my-color
`

**Comment by gauravtiwari** [comment]
Please double check the sassvar file in case something is undefined there or not referenced correctly. There is no extra config to enable, it should work out of the box.

**Comment by gauravtiwari** [comment]
If you could post bit more code then it would be helpful to figure out the problem, but again it's unrelated to Webpacker.
