### ISSUE TITLE
Removing cache from output filenames

### ISSUE THREAD

**Issue by eriknygren** [rails/webpacker#926]
Hi there,

I was trying to figure out how to remove the cache part of file outputs in the test environment, but I could not figure out how to change the `config.output.filename` property in `config/webpack/test.js`

Is it possible and could you give me a pointer how to achieve this please?

The reason I'm doing this is to load some webpack generated assets into an old teaspoon testing suite, as I'm trying to move over our asset compiling from sprockets to webpack. Hope that makes sense.

Thanks!

**Comment by gauravtiwari** [comment]
@eriknygren Yes, that's the correct way to do it in `test.js` file, `config.output.filename = '[name].js'`

```js
// config/webpack/test.js
const config = environment.toWebpackConfig()
config.output.filename = '[name].js'

module.exports = config
```

**Comment by eriknygren** [comment]
Aaah I just had it in the wrong order, didn't realise you had to call `.toWebpackConfig()` first before making any amends. Thanks a lot @gauravtiwari 🙏

**Comment by eriknygren** [comment]
@gauravtiwari how would I achieve this in newer versions of webpacker when `test.js` is not a thing anymore? the output filename doesn't seem to be configurable in the `webpacker.yml` file
