### ISSUE TITLE
Enabling HMR disables CSS extraction even when webpack-dev-server is not being used

### ISSUE THREAD

**Issue by bessey** [rails/webpacker#927]
Per discussion in #905. 

## Reproduction:
In webpack.yml set development to `compile: true` and dev_server to `hmr: true`

## Expected outcome:
When using `bin/webpack-dev-server`, pages load fine.

When  using `bin/rails s` without the dev server, pages still load fine, because `compile: true`

## Actual outcome:
✅  When using `bin/webpack-dev-server`, pages load fine.

🚫  When using `bin/rails s` without the dev server, CSS is not extracted, and Rails 500s complaining of missing CSS assets.

**Comment by gauravtiwari** [comment]
This is a simple fix - style loader needs to be aware of both options instead of just `hmr`. Feel free to make a PR to fix this 👍

**Comment by jacortinas** [comment]
@gauravtiwari I've been running into the same issue and trying to solve it, wouldn't it mean that the style loader needs to know if the dev server is running or not? I think it's the same config, with the only thing changing is whether the dev server is up or not.

**Comment by gauravtiwari** [comment]
@jacortinas Yep, almost identical to what ruby part does.
