### ISSUE TITLE
ERB transformer fails No such file error

### ISSUE THREAD

**Issue by raldred** [rails/webpacker#930]
I wanted to run one of my react components with the erb loader
But it fails to run:

```
ERROR in ./app/javascript/packs/components/offer_step_update.erb
Module build failed: Error: Command failed: bin/rails runner /Users/robaldred/Code/backstage/node_modules/rails-erb-loader/erb_transformer.rb __RAILS_ERB_LOADER_DELIMETER__ erb 0
env: ruby\r: No such file or directory
```

I've added the latest webpacker 3 with react support to a pretty basic Rails 5.0.1 app.

Ruby 2.4.0 is working fine and installed via RVM

`ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]`

**Comment by gauravtiwari** [comment]
@raldred Should be `./app/javascript/packs/components/offer_step_update.jsx.erb`

**Comment by gauravtiwari** [comment]
Probably, that's produces incorrect line ending and hence the error

**Comment by raldred** [comment]
same issue:
```
ERROR in ./app/javascript/packs/components/offer_step_update.jsx.erb
Module build failed: Error: Command failed: bin/rails runner /Users/robaldred/Code/backstage/node_modules/rails-erb-loader/erb_transformer.rb __RAILS_ERB_LOADER_DELIMETER__ erb 0
env: ruby\r: No such file or directory
```

**Comment by raldred** [comment]
Just to clarify, my component compiles and runs fine if I drop the erb from it.

**Comment by gauravtiwari** [comment]
These are only supported formats: https://github.com/rails/webpacker/blob/master/package/loaders/babel.js

```
.jsx.erb
.js.erb
```

Could you please check your file? Sounds like you're trying to run a script that has DOS/Windows line   endings (\r\n) on a machine that doesn't (linux/unix/mac os)?

Perhaps, create a new file and see if the error still persists.

**Comment by raldred** [comment]
Ha, wow, the bin/rails file (and all the others in the bin dir) had CRLF line endings. 
Not sure why that's happened.

Thanks @gauravtiwari
