### ISSUE TITLE
Webpacker gets stuck on assets:precompile with capistrano

### ISSUE THREAD

**Issue by kevinjcoleman** [rails/webpacker#934]
```
00:09 deploy:assets:precompile
      01 ~/.rvm/bin/rvm ruby-2.4.1 do bundle exec rake assets:precompile
      01 yarn install v0.27.5
      01 [1/4] Resolving packages...
      01 ⠂ webpack-dev-server@^2.7.1
      01 ⠄ yargs@^6.0.0
      01 ⡀ yargs-parser@^4.2.0
      01 ⢀ is-fullwidth-code-point@^1.0.0
      01 ⠠ number-is-nan@^1.0.0
      01 [2/4] Fetching packages...
      01 [3/4] Linking dependencies...
      01 [4/4] Building fresh packages...
      01 Done in 14.15s.
      01 Webpacker is installed 🎉 🍰
      01 Using /home/deploy/project_name/releases/20171012023010/config/webpacker.yml file for settin…
      01 [Webpacker] Compiling assets 🎉
```
It get's stuck here and the CPU on my instance shoots way up. It never actual fails, it just displays `Compiling assets 🎉` forever. It's very similar to this issue https://stackoverflow.com/questions/45555150/rails-5-1-capistrano-is-stuck-at-webpacker-compiling-assets.

**Comment by gauravtiwari** [comment]
@kevinjcoleman This is probably because the app may have many assets to compile and the instance memory is low than required (webpack usually eats up a lot of memory). Perhaps, you wanna compile them locally and then push it to the server or bump up the instance memory and see how it goes.

**Comment by kevinjcoleman** [comment]
@gauravtiwari 👍 yeah I switched to rsync-ing the assets, thanks!

**Comment by wokenqingtian** [comment]
I have fixed it through another way: add swap virtual memory to my Linux server.
