### ISSUE TITLE
 javascript_pack_tag causes error in production

### ISSUE THREAD

**Issue by heavenlypeach** [rails/webpacker#945]
When I run `rails s -e production` I get a 500 internal server error along with the following error caused by placing this code `<%= javascript_pack_tag 'hello-world-bundle' %>` in my head tag.

```
ActionView::Template::Error (Webpacker can't find hello-world-bundle.js in /Users/janedoe/Projects/Rails/myapp/public/packs/manifest.json. Possible causes:
1. You want to set webpacker.yml value of compile to true for your environment
   unless you are using the `webpack -w` or the webpack-dev-server.
2. Webpack has not yet re-run to reflect updates.
3. You have misconfigured Webpacker's config/webpacker.yml file.
4. Your Webpack configuration is not creating a manifest.
Your manifest contains:
{
}
):
```

**Comment by jacortinas** [comment]
@heavenlypeach in production the assets aren't generated when they are requested like dev and test, you have to use `rake assets:precompile`.

**Comment by heavenlypeach** [comment]
@jacortinas I ran `rake assets:precompile` and got the following error:

```
ActionController::RoutingError (No route matches [GET] "/packs/hello-world-bundle-8d452ed8d5646d08fbc8.js"):

ActionController::RoutingError (No route matches [GET] "/assets/application-ea8ca43729dabd837f81720aa2306d5344b0c1930e9d7f1677532fa5c24072bd.js"):

ActionController::RoutingError (No route matches [GET] "/assets/application-f0d704deea029cf000697e2c0181ec173a1b474645466ed843eb5ee7bb215794.css"):
```

**Comment by heavenlypeach** [comment]
Solved it. By default static assets in public are not loaded I just had to make sure that this line `config.public_file_server.enabled` is set to true.

**Comment by heavenlypeach** [comment]
Another issue I have found related to the `javascript_pack_tag` is that when running 'rspec in production mode' the following errors pop up on feature specs:

```
ActionView::Template::Error (Webpacker can't find hello-world-bundle.js in /Users/janedoe/Projects/Rails/version_17/myapp/public/packs/manifest.json. Possible causes:
1. You want to set webpacker.yml value of compile to true for your environment
   unless you are using the `webpack -w` or the webpack-dev-server.
2. Webpack has not yet re-run to reflect updates.
3. You have misconfigured Webpacker's config/webpacker.yml file.
4. Your Webpack configuration is not creating a manifest.
Your manifest contains:
{
}
):
```

**Comment by heavenlypeach** [comment]
About issue was a circleci config problem. circleci by default was using node 4.2.x and i needed to set node to version 6 or later. Once I set the node version in circle.yml file, my features tests on circleci passed.

```yaml
# circle.yml
machine:
  node:
    version: 8.5.0
```

**Comment by gauravtiwari** [comment]
@heavenlypeach Glad you figured it out yourself. Closing...

**Comment by EnziinSystem** [comment]
In "config/environments/production.rb":
`config.public_file_server.enabled = true`
And run:
`RAILS_ENV=production bundle exec rake assets:precompile`

**Comment by wonderer007** [comment]
@heavenlypeach Thanks!

**Comment by nezirz** [comment]
My fix was running this line inside mina deployed current dir 'RAILS_ENV=production bundle exec rake assets:precompile'

**Comment by hugoh59** [comment]
Did not fix it for me :/

**Comment by bhavik2936** [comment]
For me `RAILS_ENV=production bundle exec rake assets:precompile` does not work on heroku.

It gives me message
```
RAILS_ENV=production bundle exec rake assets:precompile environment is not defined in config/webpacker.yml, falling back to production environment
```
