### ISSUE TITLE
extractStyles in config/webpack/loaders/vue.js

### ISSUE THREAD

**Issue by ytbryan** [rails/webpacker#946]
Is these lines still relevant? 

found here: 

https://github.com/rails/webpacker/blob/3c8adb79201bf4928276936dcbb183c8c029e8f1/lib/install/examples/vue/hello_vue.js#L3-L4 cc @gauravtiwari

**Comment by gauravtiwari** [comment]
Oh no, not anymore. It's in the PR I am working on extending base config - but feel free to make one to remove this please 👍

**Comment by ytbryan** [comment]
ok, saw that commit at your PR 🙂
