### ISSUE TITLE
Semantic Versioning?

### ISSUE THREAD

**Issue by justin808** [rails/webpacker#959]
Going from 3.0.1 to 3.0.2 of webpacker seemed to break https://github.com/shakacode/react_on_rails/issues/956#issuecomment-336829731

Is this project following:

http://semver.org/

**Comment by guilleiguaran** [comment]
I had to say that the answer is "No": https://github.com/rails/webpacker/blob/master/CHANGELOG.md#removed

**Comment by javan** [comment]
It would be helpful you explained what broke and how you fixed it. That comment mentions something about foreman and Procfile, and there's no commit closing the issue.
