### ISSUE TITLE
Digests lookup fails due to invalid path construction

### ISSUE THREAD

**Issue by gauravtiwari** [rails/webpacker#96]
### Steps to reproduce

```bash
RAILS_ENV=production bundle exec rails assets:precompile
```

1. The digest lookup fails in production with following packs path,

```ruby
# current packs output config
# https://github.com/rails/webpacker/blob/master/lib/webpacker/railtie.rb#L12
config.x.webpacker[:packs_dist_path] = '/packs'
config.x.webpacker[:digests_path] = \
    Rails.root.join(
      'public',
      config.x.webpacker[:packs_dist_path],
      'digests.json'
    )

# produces this
# notice the path constructed isn't correct because we get '/packs', should be '/public/packs'
Rails.application.config.x.webpacker
=> {:packs_dist_path=>"/packs", :digesting=>true,  :digests_path=>#<Pathname:/packs/digests.json>}

# which causes the lookup to fail as it can't find the digests.json in /packs
Webpacker::Digests.lookup('home-react-component')
Webpacker::Digests::DigestError: Can\'t find home-react-component in #<Webpacker::Digests:0x007fe305dc7e28 @path=#<Pathname:/public/packs/digests.json>, @digests={}>
```

2. We get same problem here again during compilation (wrong path construction), https://github.com/rails/webpacker/blob/fd6a12d02227782dede22fa721b9b67efdc0d606/lib/tasks/webpacker.rake#L17
```
Error: EROFS: read-only file system, mkdir '/packs'
```

3. Simply changing `/packs` to `packs` introduces another problem,
```ruby
ActionView::Template::Error (The asset "packs/home-react-component-5939abb942a18ece63be.js" is not present in the asset pipeline.):
```

So, it seems we have to use another variable instead of `packs_dist_path` to fix this.

**Comment by serioushaircut** [comment]
Found the very same problem today. That's the way Rails.root.join works with an absolute path in the middle.  
```
irb(main):004:0> Rails.root.join('public', '/lib')
=> #<Pathname:/lib>
```
So the fallback in case no config available for these paths entails an absolute path '/packs' for digests_path which might break your setup depending on your permissions.

Simple workaround (not fix) is to configure packs_dist_path in your production/staging environment to be 'packs' instead of '/packs'. 

The  path assembly based on packs_path, digest_path, etc. can be found in at least two places:
lib/tasks/webpacker.rake
lib/webpacker/railtie.rb

**Comment by gauravtiwari** [comment]
@serioushaircut Hey, yes i tried that but it breaks the asset path because the same `packs_dist_path` is used for constructing asset path in the view. 

```ruby
ActionView::Template::Error (The asset "packs/home-react-component-5939abb942a18ece63be.js" is not present in the asset pipeline.):```

**Comment by serioushaircut** [comment]
@gauravtiwari mmh we could deploy without any errors after setting the relative packs path. I'm gonna check why is that.

**Comment by gauravtiwari** [comment]
@serioushaircut Yeah, the app deploys fine, but there is a runtime error.

**Comment by serioushaircut** [comment]
@gauravtiwari apparently, I did not read your issue carefully. You are right. We get a runtime error on the staging system, which I attributed to another failing part. Still digging what's going on during deployment on heroku.

**Comment by widescape** [comment]
I can confirm that https://github.com/rails/webpacker/pull/97 resolves the issue.

I'm in team with @serioushaircut and was seeing the same issue. @gauravtiwari

**Comment by gauravtiwari** [comment]
@serioushaircut Yeah, right did you take a look at this PR https://github.com/rails/webpacker/pull/97 ?

**Comment by gauravtiwari** [comment]
Cool @widescape 👍  Yeah, not sure if it's the best solution, but it fixes the issue.
