### ISSUE TITLE
Webpacker warnings when running tests

### ISSUE THREAD

**Issue by Jeremy-Walton** [rails/webpacker#960]
I am seeing some warnings from webpacker when running my tests. I see them in both rspec and spinach.

```
/Users/jeremywalton/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/webpacker-3.0.1/lib/tasks/installers.rake:1: warning: already initialized constant INSTALLERS
/Users/jeremywalton/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/webpacker-3.0.1/lib/tasks/installers.rake:1: warning: previous definition of INSTALLERS was here
/Users/jeremywalton/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/webpacker-3.0.1/lib/tasks/webpacker/install.rake:1: warning: already initialized constant WEBPACKER_APP_TEMPLATE_PATH
/Users/jeremywalton/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/webpacker-3.0.1/lib/tasks/webpacker/install.rake:1: warning: previous definition of WEBPACKER_APP_TEMPLATE_PATH was here
```
Ruby: 2.4.1
Rails: 5.1.4
Webpacker: 3.0.1

I would like to get rid of them so I have clean tests results. Any Idea what would cause them?

I see other people have them in their logs, but no issues have been raised about the warnings themselves.

https://github.com/rails/webpacker/issues/487
https://github.com/rails/webpacker/issues/476

**Comment by timirwin** [comment]
Any progress on this?

**Comment by emwalker** [comment]
An easy way to avoid these warnings would be to add a `defined?` check:
```
WEBPACKER_APP_TEMPLATE_PATH = '...' unless defined? WEBPACKER_APP_TEMPLATE_PATH
```
