### ISSUE TITLE
Import CSS Styles in Rails, Angular, Webpacker Project. 

### ISSUE THREAD

**Issue by mayordwells** [rails/webpacker#963]
I am trying to import Individual CSS modules into my component in Angular.
For example 
- component1.ts
- component1.css / component1.sass

- component2.ts
- component2.css / component2.sass

I have included this in the `html.d.ts` which allowed me to import html files as a string before, this also allowed me to import css file as a string, I'm not sure if this is needed.
```
declare module "*.css" {
  const content: string
  export default content
}
```

I added the css to the list of imports but angular did not allow me to use `homecss` as a variable in the component decorator. 
So used the style's url as is, however i am getting an error. 
I have installed css-loader. But I have no idea what other configuration i need to do to make this work. At least for the html part, it was clearly explained in the documentation here - [https://github.com/rails/webpacker/blob/master/docs/typescript.md](https://github.com/rails/webpacker/blob/master/docs/typescript.md)
So why is there no clear documentation on how to do the same thing with css? 
Here's my component file: 
```
import { Component } from '@angular/core';
import home from './home.html';
import homecss from './home.css';

@Component({
  selector: 'eg-home',
  template: home,
  styleUrls: ['./home.css']
})
export class HomeComponent { }
```
And here's what my error in the console looks like:
```
zone.js?6524:2933 GET http://localhost:5000/dashboard/home.css 404 (Not Found)
scheduleTask @ zone.js?6524:2933
ZoneDelegate.scheduleTask @ zone.js?6524:411
Zone.scheduleTask @ zone.js?6524:236
Zone.scheduleMacroTask @ zone.js?6524:259
(anonymous) @ zone.js?6524:2966
proto.(anonymous function) @ zone.js?6524:1366
ResourceLoaderImpl.get @ platform-browser-dynamic.es5.js?3bad:54
DirectiveNormalizer._fetch @ compiler.es5.js?524d:14079
(anonymous) @ compiler.es5.js?524d:14201
DirectiveNormalizer._loadMissingExternalStylesheets @ compiler.es5.js?524d:14201
DirectiveNormalizer.normalizeExternalStylesheets @ compiler.es5.js?524d:14178
(anonymous) @ compiler.es5.js?524d:14110
then @ compiler.es5.js?524d:1683
DirectiveNormalizer.normalizeTemplate @ compiler.es5.js?524d:14110
CompileMetadataResolver.loadDirectiveMetadata @ compiler.es5.js?524d:15139
(anonymous) @ compiler.es5.js?524d:26833
(anonymous) @ compiler.es5.js?524d:26832
JitCompiler._loadModules @ compiler.es5.js?524d:26829
JitCompiler._compileModuleAndComponents @ compiler.es5.js?524d:26799
JitCompiler.compileModuleAsync @ compiler.es5.js?524d:26728
PlatformRef_._bootstrapModuleWithZone @ core.es5.js?de3d:4536
PlatformRef_.bootstrapModule @ core.es5.js?de3d:4522
(anonymous) @ index.ts?c69e:5
ZoneDelegate.invokeTask @ zone.js?6524:425
Zone.runTask @ zone.js?6524:192
ZoneTask.invokeTask @ zone.js?6524:499
invokeTask @ zone.js?6524:1540
globalZoneAwareCallback @ zone.js?6524:1566
zone.js?6524:690 Unhandled Promise rejection: Failed to load home.css ; Zone: <root> ; Task: Promise.then ; Value: Failed to load home.css undefined
```

**Comment by giwa** [comment]
@gauravtiwari should the angular template be updated to include an example of using external files for templates and styles? I wouldn't mind putting together a PR for that.

**Comment by mayordwells** [comment]
Hi @giwa thanks for your response. Do we need to install any of these loaders, like css-loader, postcss-loader? 
Could you please share the link to the documentation once the PR is merged? 
Thank you.

**Comment by gauravtiwari** [comment]
Please feel free to add this to docs 👍

**Comment by audiodude** [comment]
Tried this with a fresh Rails app created with `--webpack=angular`. At first I got a bunch of errors that the various loaders weren't installed. I did `yarn add` for all of the missing ones, and now I get the following error:

```
    ERROR in ./node_modules/css-loader??ref--1-2!./node_modules/postcss-loader/lib??ref--1-3!./node_modules/to-string-loader/src/to-string.js!./node_modules/css-loader!./node_modules/postcss-loader/lib!./node_modules/resolve-url-loader!./node_modules/sass-loader/lib/loader.js!./app/javascript/hello_angular/app/app.component.css
    Module build failed: Syntax Error
 
    (2:9) Unknown word
 
      1 |
    > 2 |         var result = require("!!../../../../node_modules/css-loader/index.js!../../../../node_modules/postcss-loader/lib/index.js!../../../../node_modules/resolve-url-loader/index.js!../../../../node_modules/sass-loader/lib/loader.js!./app.component.css");
        |         ^
      3 |
      4 |         if (typeof result === "string") {
```

You can see my component here: https://github.com/audiodude/my-links/blob/6815d7223f5b9b94ff12b26280e6b0bec7c4b9e8/app/javascript/hello_angular/app/app.component.ts

I honestly have no idea what "Unknown word" means or how to debug this.

Thanks for any help.

**Comment by gauravtiwari** [comment]
@audiodude Ahh not sure what that error is but I just tried to reproduce your issue and couldn't. 

- created a rails webpacker app with angular - `rails new angular-app --webpack=angular`
- added a css module file and normal css - https://github.com/gauravtiwari/webpacker-angular-app/blob/master/app/javascript/hello_angular/app/app.component.ts#L2
- added node typing - https://github.com/gauravtiwari/webpacker-angular-app/blob/master/package.json#L11
- imported and required css module

Please see: https://github.com/gauravtiwari/webpacker-angular-app

**Comment by audiodude** [comment]
@gauravtiwari Thanks for the reply.

I removed all of the files that were added as part of the main solution on this bug, and attempted the "out of the box" solution you suggested. Although I can successfully `import './app.component.css';`  and `./app.component.sass`, neither seems to have any affect on my styles.

**Comment by audiodude** [comment]
@gauravtiwari Thanks, that fixes it! One thing though, this creates a "global" stylesheet, correct? That means I don't get to use so-called "component styles" (https://angular.io/guide/component-styles). It seems the solution by @giwa on this bug was trying to address the latter.

Thanks for your help though, I think I can get by with this approach for now.

**Comment by gauravtiwari** [comment]
Great 👍 

> One thing though, this creates a "global" stylesheet, correct? 

Nope it creates per component stylesheets so say if you create another module called 'page_2' and have another css file imported then you have to import styles in your view again with same pack name. 

Webpacker also supports css modules with following extension: module.css, module.scss or module.sass (which is scoped per component) - https://github.com/css-modules/css-modules

----
> https://angular.io/guide/component-styles#using-component-styles

Looks like this is CSS in JS approach so should work out the box. I haven't tried it though.

**Comment by aronbohl** [comment]
Are there any official docs for this yet? I wasn't able to find any and I'm still getting some really strange errors when trying to import any type of component styles. I tried a solution similar to what @giwa had posted with no luck.

**Comment by DenniJensen** [comment]
I have the same issue. I am not into webpacker this much to figure out where is issue is. Angular supports by default `templateUrl` and `styleUrls`. This is not the case with webpacker in rails.

**Comment by justin808** [comment]
Here's an example using Rails + React + Webpacker + react_on_rails: https://github.com/shakacode/react-webpack-rails-tutorial
