### ISSUE TITLE
Issues with static assets

### ISSUE THREAD

**Issue by hoodslide** [rails/webpacker#964]
Apologies if this is expected behavior (I'm new to webpack), but with the default webpacker config, running webpack against the following files:

app/javascript/packs/
├── application.js.ts
├── test-css.css
├── test-html.html
├── test-jpg.jpg
├── test-pug.pug
└── test-scss.scss

...I'm rewarded with:

public/packs/
├── application-76e95565ca7061123287.js
├── manifest.json
├── packs
│   └── test-jpg-053f2f3d50aa3043c2a2e8a0478939ea.jpg
├── test-css-76e95565ca7061123287.js
├── test-jpg-76e95565ca7061123287.js
└── test-scss-76e95565ca7061123287.js

Shouldn't the jpg be directly under public/packs? 
Are the css, jpg, and scss files in the TLD supposed to be wrapped in js? If so, how to access from a template?

Speaking of templates, should I use webpack-merge to add rules to my own environments/development.js in order to add support for pug? Or is there a better way? I haven't been able to find (working) examples of this anywhere.

Thank you!

**Comment by rossta** [comment]
If I'm reading your diagram correctly, it looks like you're placing your images and .html files inside `app/javascript/packs`. Webpacker treats this directory as the location for each of your entry points which will be converted into bundles. That means you'll want to put your img/css/static html elsewhere. See the [example directory layout in the README](https://github.com/rails/webpacker#usage) or you could put them in `app/assets` like traditional Sprockets apps and add let webpacker know where to look with [`resolved_paths`](https://github.com/rails/webpacker#resolved).
