### ISSUE TITLE
Vue component scope IDs inconsistent in production

### ISSUE THREAD

**Issue by inopinatus** [rails/webpacker#965]
Vue components compiled with webpacker in production have different module IDs between my servers.  As a result the .js and .css files generated have different fingerprints. 

This is playing merry hell with asset manifests, especially with a CDN.

It happens because capistrano folder naming includes deployment timestamp, which varies by a few seconds between hosts. The ugly surprise is vue-loader uses the *file path*, rather than *file contents*, to generated the moduleId. I don't know why they don't use a real fingerprint, but they don't.

Has anyone got a suggested fix. I'm out of ideas and about to fork vue-loader.

**Comment by ytbryan** [comment]
> between my servers.

Can you compile once and use the same one across the servers?

**Comment by inopinatus** [comment]
There are things I'll change my deployment sequences for, a small and poorly designed piece of Javascript is not one of them.

**Comment by inopinatus** [comment]
Closing this. It's not really a webpacker problem. I've submitted a PR for vue-loader, vue/vue-loader#1018.
