### ISSUE TITLE
Upgrading from 2.0.0 to 3.0.2 breaks configuration

### ISSUE THREAD

**Issue by kliph** [rails/webpacker#966]
It appears that #636 changed the API for accessing Webpacker's configuration.  

We previously found the source path via `Webpacker::Configuration.source`.
```ruby
> Webpacker::Configuration.source
=> "app/javascript"
```
After upgrading we get an error:
```ruby
> Webpacker::Configuration.source

NoMethodError:
  undefined method `source' for Webpacker::Configuration:Class
```

This change should be documented in the [upgrade guide](https://github.com/rails/webpacker#upgrading).

One solution to fix this problem is to use `Webpacker.config.source_path`, although note that now it returns a `Pathname` rather than a `String`.

**Comment by ytbryan** [comment]
> This change should be documented in the upgrade guide.

Yes, please send a PR. Appreciate the finding <3
