### ISSUE TITLE
Easy webpack-dev-server usage across different Rails envs 

### ISSUE THREAD

**Issue by huoxito** [rails/webpacker#971]
Hi all o/

I'm working on a project where webpack build times are not good (over 3min). We used to go with [webpack-rails](https://github.com/mipearson/webpack-rails) where dev-server was configured by a regular [rails config flag](https://github.com/mipearson/webpack-rails/blob/83a5d4c8af82e1f33116e3550d3bc3e8ecff977f/lib/webpack/railtie.rb#L37). On webpacker 3 though dev-server seems to get [pretty attached](https://github.com/rails/webpacker/blob/3b09f788ec7f55939b9b26d5feac870c2f18bf03/lib/webpacker/railtie.rb#L47-L51) to Rails development env and it can be painful to debug stuff in tests since recompiling outside webpack-dev-server can take a while. Previous webpack-rails approach looked more friendly since we could easily:

- Compile upfront in ci servers and production
- Use dev-server process for local development and even for local capybara whenever needed
- Not use dev-server process for local development when you're not working on client side related things (say by `PRECOMPILED=true bundle exec unicorn`) 

I've been trying to enable dev-server for rails test env but ended up hitting issues related to rack-proxy, sockets and webmock. I had to change test configs in webpacker.yml and added this to environments/test.rb:

```ruby
config.middleware.insert_before 0, Webpacker::DevServerProxy
```

Also had to set NODE_ENV=development while running tests, I guess so it would pick configs properly as well.

Do you see benefits on decoupling webpack and rails configs by env? Just trying to think of ways where one can easily switch among webpack configs independent of rails env. Skipping the [rack proxy approach](https://github.com/rails/webpacker/blob/3b09f788ec7f55939b9b26d5feac870c2f18bf03/lib/webpacker/helper.rb#L40-L49) by explicitly using `Webpacker.dev_server.host` and port sort of helps me with the webmock issue but that's still a lot to tweak.

hope I'm not missing something obvious here but let me know pls

cheers

**Comment by rossta** [comment]
It seems like there are multiple requests you're describing here so I don't follow the use case for separating Rails and Webpack environments. What exactly is the problem you're running into?

**Comment by sspread** [comment]
+1 I have a project with multiple environments that we use in "development". I'm unable use webpack-dev-server effectively with those custom environments.

**Comment by huoxito** [comment]
@rossta I'll try to get back to it and come up with a PR some time this week, maybe that's better for starting this conversation  (I was hoping the use cases on bullet list above would help).

I suspect the issue starts at using `Rails.env.development?`, instead of a regular rails app configuration option, for example to insert the assets proxy server.

And I understand if the team is not interested in isolating node envs from rails envs (stick with the convention approach). It's just that the current set up is painful for large apps compared to what we had with previous https://github.com/mipearson/webpack-rails gem.

**Comment by gauravtiwari** [comment]
Right, perhaps we configure when to use proxy using a config variable that can be overridden in various env files inside Rails.

```rb
# default
config.webpacker.dev_server_proxy = Rails.env.development?
# override in say production.rb
config.webpacker.dev_server_proxy = false
``` 

Would this work?

Or we can invert it i.e. run the proxy in all environment except production but I guess that's too implicit. 

What is the issue with webmock?

**Comment by huoxito** [comment]
hey @gauravtiwari thanks,  yes that would help a lot and the other thing is the `cache_manifest` option.

Do you think a `webpack.dev_server.enabled` flag alone could decide whether or not to cache the manifest file? Same flag could be used to prevent [messing with sockets](https://github.com/rails/webpacker/blob/ae8c948c2b68b7e916cccfff513508f4477810f7/lib/webpacker/dev_server.rb#L12) in production as well. I'm not sure I understand how the `cache_manifest` option is needed, looks like it could always infer based on the presence of webpack dev server.

@gauravtiwari the webmock issue is this one https://github.com/rails/webpacker/issues/822  or very similar. My guess is webmock is not compatible with rack-proxy but I couldn't isolate the issue to provide a solid example. For the main project I'm working on it doesn't make sense to compile assets on demand in tests, the first one would always timeout, so we also used webpack dev server when running capybara locally.

**Comment by huoxito** [comment]
ok so after reading latest code again, the following configuration should accomplish everything I mentioned on the issue description (much thanks to https://github.com/rails/webpacker/pull/957)

```yml
development:
  <<: *default
  compile: false
  dev_server:
    host: localhost
    port: 3035
    hmr: true
    https: false

test:
  <<: *default
  compile: false
  dev_server:
    host: localhost
    port: 3035
    hmr: true
    https: false

production:
  <<: *default
  compile: false
  cache_manifest: true
```

then add the middleware in _test.rb_ in case dev-server is needed for tests:

```ruby
config.middleware.insert_before 0, Webpacker::DevServerProxy
```

That means we can compile assets upfront and we don't have to run webpack-dev-server when we're not working on client side stuff. Plus we can use dev-server when tweaking capybara tests breaking due to client side updates.

thanks all! @gauravtiwari looking forward for the next release 🍻
