### ISSUE TITLE
Make webpack-dev-server can watch a different directory (e.g. views)

### ISSUE THREAD

**Issue by zw963** [rails/webpacker#973]
What I want is:

e.g. with semantic-ui, when i add a new class to view, can use HMR to hot loading page automatically.

I have no idea how to add 'app/views' directory into webpacker-dev-server watched list.

js version webpack-dev-server have a `--content-base` args, but, seem like webpacker's bind `bin/webpack-dev-server` even not support `--help`.

```sh
bin/webpack-dev-server --help
 10% building modules 1/1 modules 0 active                                         
Project is running at http://localhost:3035/
webpack output is served from /packs/

....
```

Thanks.

**Comment by zw963** [comment]
Rails 5.1.4, Webpack 3.8.1.

I have tried following command:

```sh
bin/webpack-dev-server --content-base app/assets/
```

When I change files in `app/assets`, no hotload is triggered.

**Comment by joerodrig** [comment]
Have you given the [resolved_paths](https://github.com/rails/webpacker/blob/8940b2cd8714f666cb4b2a14d5182daa976cfaa6/README.md#resolved) option a try?

**Comment by zw963** [comment]
@joerodrig , not work.

e.g.  i set like this: `resolved_paths: ['app/views/admin_panel/articles']`,
and in that folder, exist some `html.erb` files, when I change class name(with semantic-ui)
page is not autorefresh.

**Comment by rossta** [comment]
@zw963 I'm guessing that you're using a typical Rails application with Webpack. If that is correct, your Rails views are not compiled by Webpack; they are process by your Rails server. This explains why Webpack doesn't reload them when they've changed. 

What you can do is use a separate tool to watch and reload your Rails code when it changes. This project looks like exactly what you want: https://github.com/guard/guard-livereload

**Comment by zw963** [comment]
@rossta, Yes, I done this myself with my editor, when I edit some views file, I will add(or remove) my specify webpack js file with a comment line to archive this.

that work very well, thanks.
