### ISSUE TITLE
SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode. 

### ISSUE THREAD

**Issue by deesx** [rails/webpacker#974]
It only happen within safari. I might not be advanced enough to find the correct workaround to avoid this; I'm using the default webpacker install, webpack-dev-server is @2.9.3

**Comment by joerodrig** [comment]
Is this error appearing from code you wrote? Importing a 3rd party package? An example would help a bit.

**Comment by vitexikora** [comment]
Happens to me too, when I wanted to Local-test a React app in Safari, however the local testing fired even more problems. Currently it is in webpack code:
```js
eval("/* WEBPACK VAR INJECTION */(function(__resourceQuery) {\n\n/* global __resourceQuery WorkerGlobalScope self */\n/* eslint prefer-destructuring: off */\n\nconst url = __webpack_require__(\"./node_modules/url/url.js\"); .... ")
```

**Comment by p0wl** [comment]
Your babel configuration is probably wrong, so that it does not compile es6 to es5. Chrome is already supporting `const`, so it only breaks in safari.

can you show the content of your `.babelrc`?

**Comment by deesx** [comment]
It is actually the default one provided by webpacker:install :

```
{
  "presets": [
    [
      "env",
      {
        "modules": false,
        "targets": {
          "browsers": "> 1%",
          "uglify": true
        },
        "useBuiltIns": true
      }
    ],
    "react"
  ],
  "plugins": [
    "syntax-dynamic-import",
    "transform-object-rest-spread",
    [
      "transform-class-properties",
      {
        "spec": true
      }
    ]
  ]
}
```

I do use the following within nodejs apps, works well :

```
{
  "presets": [
    "es2015",
    "react",
    "stage-0"
  ],
  "plugins": ["transform-class-properties"]
}
```

Tried to add to the es2015 and stage-0 presets to the one within within rails (after adding the relevant packages), the error still persists. I clearly lack of understanding into this specific part; glad if it could be cleared

**Comment by joerodrig** [comment]
Babel has deprecated `babel-preset-es2015`, so you shouldn't need to use that anymore. [babel-preset-env](https://babeljs.io/docs/plugins/preset-env/), which is the default preset handles versioning, so you may have to adjust your `targets` line in your babelrc file.

Tried reproducing the error on Safari 11 from the code you submitted above and wasn't able to. The page appears to load fine. Here's the repo: https://github.com/joerodrig/safari-error. 

Is your version of safari less than 10? Versions 5.1 - 9.1 do not support using `const` in strict mode. Version 10 was the first to apparently have full support. See http://caniuse.com/#feat=const for reference

**Comment by deesx** [comment]
thx a lot for your insights. had not enough time to rebuild it all to reproduce; but i will double check. I'm 9.1, I guess that's the reason. thx alot

**Comment by dsacramone** [comment]
@joerodrig  So, I am using Safari 9.1 and getting the same answer. Other than "upgrading" Safari, is there a workaround?

**Comment by eirikb** [comment]
@dsacramone have you excluded _node_modules_?
Perhaps a dependency uses `const`, and so you can't exclude anything.
Just a thought .

**Comment by burrack** [comment]
@eirikb where he should exclude node_modules ?

Thanks

**Comment by eirikb** [comment]
@burrack _not_ exclude them. It's not uncommon to do something like this:
```JavaScript
     {
        test: /\.js$/,
        loader: 'babel-loader',
        exclude: /node_modules/
      }
```
, but instead I suggest 
```JavaScript
     {
        test: /\.js$/,
        loader: 'babel-loader'
      }
```
. Not sure how relevant that is though, just a thought, since some imported packages also needs to be transpiled.

**Comment by whusterj** [comment]
Someone pointed this out elsewhere, but if you are seeing this issue when using the webpack dev server, you'll need to downgrade:

https://github.com/webpack/webpack-dev-server#caveats - Version 2.8.0 introduced a change which included ES6 keywords const and let, to support older browsers, downgrade to version 2.7.1

**Comment by gauravtiwari** [comment]
thanks @whusterj 

Or upgrade to latest webpack-dev-server

**Comment by burrack** [comment]
I get this error on safari 9.
Maybe someone can help me ?

This is what i have:

**.babelrc**
```
{
  "presets" : [
    "es2015",
    "react",
    "stage-0"
  ],
  "plugins": [
    "syntax-dynamic-import"
  ]
}

```
webpack: 2.3.3

part of webpack config
```
 module: {
    rules: [
      {
        test: /\.js?/,
        include: [path.resolve(paths.client.appDir), path.resolve(paths.shared.dir)],
        use: {
          loader: 'babel-loader',
          options: {
            plugins: ['syntax-dynamic-import']
          }
        }
      },
```

**Comment by hiepnm** [comment]
I still get this error on iOS 9.3.5 and safari 9.0
"webpack-dev-server": "^3.1.2",

**Comment by francosalcedo** [comment]
Apparently there is no solution.
