### ISSUE TITLE
Webpack compiling all assets - 404 returned when loading them

### ISSUE THREAD

**Issue by ilrock** [rails/webpacker#977]
Hey there!

I'm deploying on Heroku a Rails 5 app using the webpack pipeline to load Vue.

When I deploy onto Heroku and the assets:precompile starts I see that webpack does precompile everything:

![image](https://user-images.githubusercontent.com/4171627/32086822-72d70600-ba9d-11e7-837e-552ebd16371d.png)

When the page tries to load it, however, I get a 404 error:

![image](https://user-images.githubusercontent.com/4171627/32086841-952c783e-ba9d-11e7-8509-3ab0ecb05aa0.png)

And in the Heroku logs I see this line:

`2017-10-19T10:04:51.947282+00:00 heroku[router]: at=info method=GET path="/packs/main-49ef6f7f11bf1482d113.js" host=lacerba-beta.herokuapp.com request_id=fce4e051-2880-4566-8e66-5cd3369a819f fwd="125.227.151.206" dyno=web.1 connect=0ms service=72ms status=404 bytes=1744 protocol=https
`

**Comment by rossta** [comment]
Do the digests in the browser match those found in `packs/manifest.json` and/or the ones found in `public/packs`?

**Comment by ilrock** [comment]
@rossta Thank you! Your hint got us to fix the issue! For some reason, public/packs was in the .gitignore and thus it was not getting pushed to Heroku!

**Comment by ivan-denysov** [comment]
This happened to me because I had `webpack dev server` running on a different project
