### ISSUE TITLE
Behavior in test is different from real situation(capybara)

### ISSUE THREAD

**Issue by stavskiys** [rails/webpacker#983]
Hello.
Capybara 2.14.1, rails 5.0.4, webpacker 1.1. I used headless_chrome for js tests. For debug I used chrome driver(not headless).

In my js code I used fbemitter. It is allow to notify any parts of js app about data changes and share the data. In real application it works ok. But in test I've got situation when received two different store. store - it is fbemitter instance.

Example:
```
//my_store.js
...
export default new MyStore

//react_component.js(one store here)
import store from 'stores/my_store'
...

//other_file.js(second store here)
import store from 'stores/my_store'
...
```
Do somebody have idea, whats wrong ?

**Comment by rossta** [comment]
I don't understand the issue you're trying to report. Could you clarify what you mean?

**Comment by gauravtiwari** [comment]
Closing, since this is unrelated to webpacker. Perhaps, consider opening an issue on `fbemitter` repo.
