### ISSUE TITLE
I can't get resolved_path to work in webpack.yml

### ISSUE THREAD

**Issue by ajnassar** [rails/webpacker#984]
Hello,

I was playing around with webpacker 3.0 and I want to test out adding webpacker to an existing rails app. This means I will have css in app/assets/stylesheets and I may have assets place elsewhere. 

So the solution for this should be to add resolve_paths: ['app/assets'] to the webpacker.yml file. But this doesn't really do anything for me. When I add a css file from app/assets/* it says that the module cannot be found. Can anyone please help me? The documentation makes it seem so easy, and it does seem easy but I can't seem to get it to work.

Also I have looked through a lot of the issues already mentioned under this github as well as videos, tutorials and blogs to try to solve the problem, but I haven't find a solution yet. 

Thanks for the help!

**Comment by ajnassar** [comment]
Following up on this issue. I think I figured out the problem. I was upgrading from webpacker 2.0 -> 3.0 and there was some residual configs from 2.0 -> 3.0. I needed to get rid of the configs that were conflicting.  This issue is now closed.

**Comment by iurevych** [comment]
For those who is still struggling:
1. Go into your webpack config (not `*.yml`, it should be a `*.js` config like `shared.js` by default)
2. Find `resolve` block in there (or create it if you don’t have it) – [screenshot](https://user-images.githubusercontent.com/325422/32579038-3247697c-c4e8-11e7-99db-c8d49f3c8a3d.png)

Here is my `resolve`:
```js
  resolve: {
    extensions: settings.extensions,
    modules: [
      resolve(settings.source_path),
      'node_modules',
      'app/javascript',
      'app/javascript/__tests__',
      'app/assets/images'
    ]
  },
```
3. Restart your Webpack dev server
4. Now you can `import` any assets from newly added directory inside your JS components like so (React example):
```jsx
import logo from 'application_v2/logo.png'
<img src={logo} />
```

Enjoy.

**Comment by gauravtiwari** [comment]
@iurevych The same can be done using `resolved_paths` option in config.yml(webpacker 3.0+): https://github.com/rails/webpacker/blob/master/lib/install/config/webpacker.yml#L11

**Comment by iurevych** [comment]
@gauravtiwari it did not help me unfortunately, probably because my `.js` config conflicted with the Yaml one.

**Comment by gauravtiwari** [comment]
Ahh okay, perhaps you may want to upgrade to latest webpacker config (more changes coming in #884) ;)
