### ISSUE TITLE
Resolve alias to source_path

### ISSUE THREAD

**Issue by nguyenj** [rails/webpacker#986]
I'm having a hard time finding a way to access the `source_path`. I'm able to find the public path just find with `asset_host`; but there doesn't seem to be a way to access the config values from webpacker.yml.

Here's what I'm trying to do:

```
// /app/javascripts/packs/main.js

import Signup from  '@components/signup.js'
```
I would like for webpack to resolve `@components` to `/apps/javascripts/components` (https://webpack.js.org/configuration/resolve/#resolve-alias).

I can hardcode the path via `path.resolve(__dirname, '..', 'app', 'javascripts')`; but I don't think that's an elegant path forward.

**Comment by gauravtiwari** [comment]
You can get `source_path` from config: 

```js
const config = require('@rails/webpacker/package/config')
```

**Comment by BoleLee** [comment]
I setted config according to the [docs:webpack](https://github.com/rails/webpacker/blob/master/docs/webpack.md):

```
module.exports = {
  resolve: {
    alias: {
      @: '/app/javascript/src',
      @views: '/app/javascript/src/views',
      @components: '/app/javascript/src/views/components'
    }
  }
}
```

however, when it compiles, it said cannot find the module.

**Comment by gauravtiwari** [comment]
@BoleLee What happens if you do this? 

```
module.exports = {
  resolve: {
    alias: {
      @: 'app/javascript/src',
      @views: 'app/javascript/src/views',
      @components: 'app/javascript/src/views/components'
    }
  }
```

**Comment by BoleLee** [comment]
```
# config/webpack/custom.js
const path = require('path')

module.exports = {
  resolve: {
    alias: {
      '@': path.resolve(__dirname, '..', '..', 'app/javascript/src'),
      '@views': path.resolve(__dirname, '..', '..', 'app/javascript/src/views'),
      '@components': path.resolve(__dirname, '..', '..', 'app/javascript/src/views/components')
    }
  }
}

# config/webpack/environment.js
const { environment } = require('@rails/webpacker')
const customConfig = require('./custom')

environment.config.merge(customConfig)
```

@gauravtiwari  I tried your solution in [#986](https://github.com/rails/webpacker/issues/1063#issuecomment-349374978), and it solve the problem.

**Comment by gauravtiwari** [comment]
Great 👍 - should be either complete absolute path (more robust) or relative path (from `node_modules` dir)

**Comment by stoplion** [comment]
What is the solution? You export a map of routes? And what does the file ` ./custom` suppose to contain?

**Comment by stoplion** [comment]
1. The fix is to export a map of routes? 
2. What file is this exported from
3. What is the require('./custom')?

**Comment by brunoporto** [comment]
Alternative `config/webpack/environment.js`

```javascript
const { environment } = require('@rails/webpacker')
const path = require('path')

environment.config.set('resolve.alias', {
    '@': path.resolve(__dirname, '..', '..', 'app/javascript'),
    '@controllers': path.resolve(__dirname, '..', '..', 'app/javascript/controllers')
});

module.exports = environment
``
