### ISSUE TITLE
Move location of .babelrc and package.json

### ISSUE THREAD

**Issue by tyleriguchi** [rails/webpacker#989]
Does webpacker support changing the location of the package.json and babelrc to a different directory?

**Comment by guilleiguaran** [comment]
We tried this in Rails/Webpacker (moving package.json to vendor folder) but it resulted in many problems because many Node tools/libs assume that the package.json is in the project root so we decided to just leave it in the root.

**Comment by tyleriguchi** [comment]
Haha gotcha, truthfully was hoping I could move the stuff around to fix an issue I'm having with .babelrc going to the parent directory to look for the configuration.
