### ISSUE TITLE
Webpacker.yml dev_server config doesn't apply

### ISSUE THREAD

**Issue by adam-h** [rails/webpacker#991]
The [default config](https://github.com/rails/webpacker/blob/05bf821ce983a2ad88fba0da476023e67f8efe43/lib/install/config/webpacker.yml#L36-L47) shows how to apply `dev_server` config from `webpacker.yml`.

This does not work and the comment at the top of the config links to webpack docs which say to define it in the webpack config - in this case [config/webpack/development.js](https://github.com/rails/webpacker/blob/05bf821ce983a2ad88fba0da476023e67f8efe43/lib/install/config/webpack/development.js).

It looks to me like the runner only takes the [host and port](https://github.com/rails/webpacker/blob/05bf821ce983a2ad88fba0da476023e67f8efe43/lib/webpacker/dev_server_runner.rb#L19-L20) out of this config then [doesn't actually pass](https://github.com/rails/webpacker/blob/05bf821ce983a2ad88fba0da476023e67f8efe43/lib/webpacker/dev_server_runner.rb#L43) any of it on to webpack-dev-server itself (instead just providing the JS /config/webpack/development.js file).

---

To workaround this locally I've defined the `dev_server` config in the JS webpack config (/config/webpack/development.js) with the options camelCased instead of snake_cased. This works, but contradicts the installed script here.

**Comment by gauravtiwari** [comment]
@adam-h That happens here: https://github.com/rails/webpacker/blob/master/package/environments/development.js#L3

Not sure I understand the issue? :)

**Comment by adam-h** [comment]
@gauravtiwari You're right! So sorry about that. Turns out in my `config/webpack/environment.js` I was importing `Environment` rather than `environment` (as I was extending the prototype), not realising that `Environment` doesn't have the same magic. Replaced it with:

```javascript
    const webpackper = require('@rails/webpacker')

    class PEEnvironment extends webpackper.environment.constructor {
        ...
    }
```

Which is working perfectly, with extendability and the magic environment dependant parent class.

**Comment by gauravtiwari** [comment]
Great 👍
