### ISSUE TITLE
Configure changes to all enviornments

### ISSUE THREAD

**Issue by nguyenj** [rails/webpacker#997]
Is there a way to set a configuration like the one in the example to all environments rather than having to copy-pasta the [merge tidbits](https://github.com/rails/webpacker/commit/3927eba603c8766786b55abc0c78664a45f06629#diff-8f1b860532856344d5023542844a1152R39) in all the environment files?

For example, take the example from the docs–how do you apply that `resolve` configuration to all environments in the `environments.js` file? If I had 4 environments, it's a little messy to require the same customConfig and merge in every environment file.

**Comment by gauravtiwari** [comment]
@nguyenj Yes, this will be fixed in #884

**Comment by nguyenj** [comment]
@gauravtiwari perfect, thank you. I'll close this out and follow that thread.
